name: Success Kid
source: http://knowyourmeme.com/memes/success-kid-i-hate-sandcastles
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- don't know a question on the test
- answer is in another question
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Success Kid, sometimes known as I Hate Sandcastles, is a reaction
  image of a baby at a beach with a smug facial expression. It has been used in image
  macros to designate either success or frustration. In early 2011, the original image
  was turned into an advice animal style image macro with captions describing a situation
  that goes better than expected. Origin The original image was taken by photographer
  Laney Griner of her then 11-month-old son Sammy on August 26th, 2007. She posted
  it to both her personal Flickr account[1] and put it up on Getty Images[6], which
  has since been removed. Spread As early as January 2008, users on social networking
  sites like MySpace[3] began incorporating the photo of Sammy into their profiles,
  either as their avatar or as part of the page''s layout. It was often paired with
  the phrases "Ima Fuck you up"[2] or "I Hate Sandcastles" In May 2008, the image
  was made freely available on image hosting site Pyzam.com[4] with a second child
  photoshopped in to the background. It was reposted on humor sites Damn Funny Pictures[8]
  and Daily Haha[9] the next month. This version was part of a photoshop thread on
  Russian-language social news site Yaplakal.com[5] on June 4th of that same year.
  Advice Animal One of the earliest Success Kid advice animal style image macros was
  uploaded to Reddit on January 28th, 2011.[10] As of February 2011, there are over
  66,000 instances of Success Kid on Quickmeme[11], nearly 300 on MemeGenerator[12],
  and over 3000 results on the Advice Animals subreddit.[13] In July 2011, the single
  topic blog on Tumblr called Fuck Yeah Success Kid[14] was started and collections
  of these images were posted to humor sites Pleated Jeans[15] in July 2011 and Uproxx[16]
  that November. There is also a category for Success Kid images on Ranker[17] and
  Memebase[18] and a Facebook[19] fan page with over 4000 likes. Kidney Transplant
  Crowdfunding Campaign On April 8th, 2015, Griner launched a crowdfunding page on
  GoFundMe[25] to raise money for her husband Justin''s kidney transplant (shown below).
  On April 13th, The Daily Dot[32] published an article about the crowdfunding effort,
  which included an email from Griner in which she revealed her husband "spends 12
  hours a week in a dialysis clinic." On April 15th, Redditor IrishProf[26] submitted
  an article about Griner''s campaign page to the /r/UpliftingNews[25] subreddit,
  where it gathered more than 3,900 votes (85% upvoted) in the the first 24 hours.
  In the coming days, many news sites published articles about the GoFundMe campaign,
  including Time,[27] E! Online,[28] Today,[29] IB Times[30] and Metro.[31] Within
  one week, the page reached over $88,000 of its $75,000 goal. BuzzFeed Interview
  On July 11th, 2020, Sam Griner appeared on the BuzzFeedVideos YouTube[34] channel
  to discuss his meme, garnering over 5.6 million views in two years (shown below).
  Copyright Lawsuit Against Former Rep. Steve King On January 23rd, 2020, Twitter[35]
  user @ehananoki shared a screenshot from former Republican Iowa Representative Steve
  King''s Facebook page that shows him using the Success Kid meme to fundraise. On
  that day, Success Kid''s mother retweeted[36] the post, writing, "Just so it’s clear
  – I have/would never give permission for use of my son’s photo to promote any agenda
  of this vile man or that disgusting party (shown below). On January 27th, the Hollywood
  Reporter[37] reported that Griner''s attorney sent a cease and desist letter to
  King over his use of the meme, posting the full contents of the letter to their
  article. King had until that Wednesday at 9:00 A.M to remove the post, which he
  did. In part, the letter reads: "You have a record of vitriolic criticism of individuals
  who belong to protected classes or disadvantaged groups, or who support legal rights
  that you condemn. The majority of U.S. consumers reject your political and other
  views, often vehemently, as they have a right to do. Those people may be repelled
  by any association with your politics and campaign and, therefore, unwilling to
  purchase products from legitimate licensees of the ''Success Kid'' meme, an association
  you have unilaterally and unlawfully imposed." On August 23rd, 2022, the Des Moines
  Register[38] reported that Griner filed a lawsuit against King in December 2020
  and it would be moving to a jury trial in November 2022. According to the article,
  King said of the lawsuit, ""It is a petty and politically motivated case of litigation
  persecution. I had no involvement or prior knowledge whatsoever and the plaintiff
  and her attorneys know that." Various Examples Success Kid in Advertising In February
  2012, British media company Virgin Media recently began running billboards featuring
  a mirrored version of Sammy''s photo. The advertising campaign was covered by New
  Rising Media[20] and the Daily What.[21] Griner later confirmed via Flickr that
  she did get paid for use of the photo and he would also be appearing in Vitamin
  Water commercials in the United States in 2012. White House Tweet On June 19, 2013,
  the @WhiteHouse[33] Twitter feed tweeted a Success Kid image with the caption "Pass
  Immigration Reform Save Taxpayers $897,000,000,000" (shown below). Other Pictures
  Laney Griner has continued to post photos of Sammy on her Flickr[7] through the
  years. Many have been shared on Reddit[22], Blame it on The Voices[23] and the Daily
  What.[24] Search Interest External References [1] Flickr – "Why I Oughta…" [2] Google
  – Image search results [3] All4MySpace (via Wayback Machine) – I Hate Sandcastles
  MySpace Layout [4] Pyzam (via Wayback Machine) – I Hate Sandcastles Graphic [5]
  Yaplakal – Fotozhaba: I''ll show you! [6] Getty Images – Little boy at the beach
  eating sand (page unavailable) [7] Flickr – Laney G''s Photostream [8] Damn Funny
  Pictures – I Hate Sand Castles [9] Daily Haha – I hate Sandcastles [10] Reddit –
  Success Kid Finds A Controller [11] Quickmeme – Success Kid [12] MemeGenerator –
  Success Kid [13] Reddit – Search results for "Success Kid" [14] Tumblr (via Wayback
  Machine) – Fuck Yeah Success Kid [15] Pleated Jeans – Best of The Success Kid Meme
  [16] Uproxx – Meme Watch: Success Kid Wins At Life, Excels In Cuteness [17] Ranker
  – The Very Best of the Success Kid Meme [18] Memebase – Success Kid Category [19]
  Facebook – Success Kid [20] New Rising Media – Virgin Media Using ''Success Kid''
  Meme For Marketing [21] The Daily What – The Interpipes are Leaking of the Day [22]
  Reddit – Do you recognize him? [23] Blame it on the Voices – Then and Now: Success
  Kid [24] The Daily What – Then And Now of the Day [25] GoFundMe – Justins Kidney
  Transplant [26] Reddit – Calling All Redditors [27] Time – Boy of Success Kid Meme
  Fundraises For Fathers Kidney Transplant [28] E! Online – Boy From Success Kid Meme
  is Now 8 [29] Today – Boy from Success Kid meme turns to Internet to help his dad
  find new kidney [30] IBI Times – Success Kid meme star Sammy Griner helps father
  in kidney transplant plea [31] Metro – The boy from the Success Kid meme [32] The
  Daily Dot – Success Kids dad needs your help getting a new kidney [33] Twitter –
  @ObamaWhiteHouse [34] YouTube – I Accidentally Became A Meme Success Kid [35] Twitter
  – ehananoki [36] Twitter – laneymg\ [37] Hollywood Reporter – Threatens to Sue Rep.
  Steve King for Using the Meme in Fundraising Effort [38] Des Moines Register – Meme
  baby lawsuit against former Rep. Steve King set for trial in November'
aside_content: MemeStatusConfirmedType:Image MacroYear2007OriginFlickrTagskids,exploitable,baby,success
  kid,success,advice animal,sandcastles,roflcon iii,victory baby,laney griner,irishprof,pleated
  jeans,vitamin water,@whitehouse,success kid memeAdditional ReferencesMeme GeneratorRedditWikipedia
added_at: '2009-08-24T22:47:07-04:00'
