name: Unpopular opinion puffin
source: http://knowyourmeme.com/memes/unpopular-opinion-puffin
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- I don't find Mitch Hedberg
- all the funny
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Unpopular Opinion Puffin is an advice animal image macro series
  featuring a photograph of a baby puffin[1] and various captions conveying opinions
  that are thought to be unpopular, in similar vein to other non-conformist advice
  animal characters like Confession Bear and Angry Walter. Origin According to an
  email sent to our site by the Imgur user Daemoos, the photographer of the original
  stock photo (shown below, left) is Andreas Mulder[16], a student in Netherlands.
  The image has been included in a photography book, early titled as "Silly Walk".
  The image appeared online as early as July 2010 on That Cute Site.[2] On July 24th,
  2013, it was used as an image macro for the first time in a submission to the /r/AdviceAnimals[3]
  subreddit. In the post, the OP suggested using it as an alternative to Confession
  Bear, which had been frequently used on the subreddit as a way to express an unpopular
  opinion disguised as a confession. Spread Before the image had become an image macro,
  the uncaptioned image was submitted to a number of subreddits in 2012 including
  /r/aww[4], /r/pics[5] and /r/PhotoshopBattles.[6] In February 2013, the photo was
  submitted to /r/aww[7] a second time. On August 23rd, an Unpopular Opinion Puffin
  supporting the announcement of Ben Affleck''s role in the latest Batman film[8]
  (shown below) hit the front page of Reddit, gaining more than 22,000 upvotes, 1,600
  points overall and 900 comments within two months. In late September 2013, the subreddit/r/UOPuffin[9]
  was created. Over the course of the following month, Unpopular Opinion Puffin instances
  appeared on 9gag[10], Meme Dad[11], Memebase[12] and FunnyJunk.[13] Notable Examples
  As of October 2013, there are more than 250 search results for "Unpopular Opinion
  Puffin" on Reddit.[14] Additionally, more than 450 instances have been submitted
  to MemeGen.[15] Search Interest [Not Currently Available] External References [1]
  Wikipedia – Puffin [2] That Cute Site – Puffin Skips To Its Lou [3] Reddit – /r/adviceanimals:
  With all the misuse of confession bear memes, I propose a new meme. Unpopular opinion
  puffin [4] Reddit – /r/aww: Puffin skip! [5] Reddit – /r/pics: Puffin'' along [6]
  Reddit – /r/photoshopbattles: Puffin Dancing (xpost /r/pics) [7] Reddit – /r/aww:
  Just found out that a baby puffin is called a "puffling" [8] Reddit – /r/adviceanimals:
  Unpopular Opinion Puffin [9] Reddit – /r/UOPuffin [10] 9gag – Unpopular Opinion
  Puffin [11] Meme Dad – Unpopular Opinion Puffin [12] Memebase – Unpopular Opinion
  Puffin [13] FunnyJunk – Unpopular Opinion Puffin [14] Reddit – Search Results for
  "unpopular opinion puffin [15] MemeGen – Unpopular Opinion Puffin [16] Imgur via
  Way Back Machine – Related Gallery'
aside_content: MemeStatusConfirmedType:Animal,Image MacroYear2013OriginRedditTagsadvice
  animal,unpopular opinion,puffin,stock photo,silly walk,imgru,reddit,funny,daemoos,andreas
  mulder,that cute siteAdditional ReferencesMeme GeneratorMemebaseReddit
added_at: '2013-10-21T14:00:24-04:00'
