example:
- I don't find Mitch Hedberg
- all the funny
keywords:
- null
name: Unpopular opinion puffin
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Unpopular Opinion Puffin | Know Your Meme Greetings! You must login\
  \ or signup first! Already a memeber? Login Now! Don't have an account? Sign up\
  \ Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos Submit\
  \ \u2192 Images Trending Most Commented Most Favorited High Score Low Score Most\
  \ Viewed All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Unpopular Opinion Puffin Added 11 years ago / Updated 10 days ago Confirmed\
  \ 396,121 Part of a series on Advice Animals. [View Related Entries] View All 143\
  \ Images Navigation About \u2022 Origin \u2022 Spread \u2022 Notable Examples \u2022\
  \ Search Interest \u2022 External References \u2022 Recent Images About Unpopular\
  \ Opinion Puffin is an advice animal image macro series featuring a photograph of\
  \ a baby puffin[1] and various captions conveying opinions that are thought to be\
  \ unpopular, in similar vein to other non-conformist advice animal characters like\
  \ Confession Bear and Angry Walter. Origin According to an email sent to our site\
  \ by the Imgur user Daemoos, the photographer of the original stock photo (shown\
  \ below, left) is Andreas Mulder[16], a student in Netherlands. The image has been\
  \ included in a photography book, early titled as \"Silly Walk\". The image appeared\
  \ online as early as July 2010 on That Cute Site.[2] On July 24th, 2013, it was\
  \ used as an image macro for the first time in a submission to the /r/AdviceAnimals[3]\
  \ subreddit. In the post, the OP suggested using it as an alternative to Confession\
  \ Bear, which had been frequently used on the subreddit as a way to express an unpopular\
  \ opinion disguised as a confession. Spread Before the image had become an image\
  \ macro, the uncaptioned image was submitted to a number of subreddits in 2012 including\
  \ /r/aww[4], /r/pics[5] and /r/PhotoshopBattles.[6] In February 2013, the photo\
  \ was submitted to /r/aww[7] a second time. On August 23rd, an Unpopular Opinion\
  \ Puffin supporting the announcement of Ben Affleck's role in the latest Batman\
  \ film[8] (shown below) hit the front page of Reddit, gaining more than 22,000 upvotes,\
  \ 1,600 points overall and 900 comments within two months. In late September 2013,\
  \ the subreddit/r/UOPuffin[9] was created. Over the course of the following month,\
  \ Unpopular Opinion Puffin instances appeared on 9gag[10], Meme Dad[11], Memebase[12]\
  \ and FunnyJunk.[13] Notable Examples As of October 2013, there are more than 250\
  \ search results for \"Unpopular Opinion Puffin\" on Reddit.[14] Additionally, more\
  \ than 450 instances have been submitted to MemeGen.[15] Search Interest [Not Currently\
  \ Available] External References [1] Wikipedia \u2013 Puffin [2] That Cute Site\
  \ \u2013 Puffin Skips To Its Lou [3] Reddit \u2013 /r/adviceanimals: With all the\
  \ misuse of confession bear memes, I propose a new meme. Unpopular opinion puffin\
  \ [4] Reddit \u2013 /r/aww: Puffin skip! [5] Reddit \u2013 /r/pics: Puffin' along\
  \ [6] Reddit \u2013 /r/photoshopbattles: Puffin Dancing (xpost /r/pics) [7] Reddit\
  \ \u2013 /r/aww: Just found out that a baby puffin is called a \"puffling\" [8]\
  \ Reddit \u2013 /r/adviceanimals: Unpopular Opinion Puffin [9] Reddit \u2013 /r/UOPuffin\
  \ [10] 9gag \u2013 Unpopular Opinion Puffin [11] Meme Dad \u2013 Unpopular Opinion\
  \ Puffin [12] Memebase \u2013 Unpopular Opinion Puffin [13] FunnyJunk \u2013 Unpopular\
  \ Opinion Puffin [14] Reddit \u2013 Search Results for \"unpopular opinion puffin\
  \ [15] MemeGen \u2013 Unpopular Opinion Puffin [16] Imgur via Way Back Machine \u2013\
  \ Related Gallery advice animal unpopular opinion puffin stock photo silly walk\
  \ imgru reddit funny daemoos andreas mulder that cute site Share Pin Related Entries\
  \ 115 total Ermahgerd Overly Attached Girlfriend Scumbag Steve Good Guy Greg View\
  \ All Related Entries Recent Images 143 total View All Images Recent Videos 0 total\
  \ There are no recent videos. Sign up for our Newsletter Load 77 Comments Comments\
  \ 77 total 24 Unpopular Opinion Puffin 396,121 0 143 77 Part of a series on Advice\
  \ Animals. [View Related Entries] Updated Dec 13, 2024 at 03:53PM EST by LiterallyAustin.\
  \ Added Oct 21, 2013 at 02:00PM EDT by amanda b.. Like us on Facebook! Like 1.8M\
  \ Share Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the\
  \ video gallery, or 'r' to view a random entry. Meme Status Confirmed Type: Animal,\
  \ Image Macro Year 2013 Origin Reddit Tags advice animal, unpopular opinion, puffin,\
  \ stock photo, silly walk, imgru, reddit, funny, daemoos, andreas mulder, that cute\
  \ site Additional References Meme Generator Memebase Reddit About Unpopular Opinion\
  \ Puffin is an advice animal image macro series featuring a photograph of a baby\
  \ puffin[1] and various captions conveying opinions that are thought to be unpopular,\
  \ in similar vein to other non-conformist advice animal characters like Confession\
  \ Bear and Angry Walter. Origin According to an email sent to our site by the Imgur\
  \ user Daemoos, the photographer of the original stock photo (shown below, left)\
  \ is Andreas Mulder[16], a student in Netherlands. The image has been included in\
  \ a photography book, early titled as \"Silly Walk\". The image appeared online\
  \ as early as July 2010 on That Cute Site.[2] On July 24th, 2013, it was used as\
  \ an image macro for the first time in a submission to the /r/AdviceAnimals[3] subreddit.\
  \ In the post, the OP suggested using it as an alternative to Confession Bear, which\
  \ had been frequently used on the subreddit as a way to express an unpopular opinion\
  \ disguised as a confession. Spread Before the image had become an image macro,\
  \ the uncaptioned image was submitted to a number of subreddits in 2012 including\
  \ /r/aww[4], /r/pics[5] and /r/PhotoshopBattles.[6] In February 2013, the photo\
  \ was submitted to /r/aww[7] a second time. On August 23rd, an Unpopular Opinion\
  \ Puffin supporting the announcement of Ben Affleck's role in the latest Batman\
  \ film[8] (shown below) hit the front page of Reddit, gaining more than 22,000 upvotes,\
  \ 1,600 points overall and 900 comments within two months. In late September 2013,\
  \ the subreddit/r/UOPuffin[9] was created. Over the course of the following month,\
  \ Unpopular Opinion Puffin instances appeared on 9gag[10], Meme Dad[11], Memebase[12]\
  \ and FunnyJunk.[13] Notable Examples As of October 2013, there are more than 250\
  \ search results for \"Unpopular Opinion Puffin\" on Reddit.[14] Additionally, more\
  \ than 450 instances have been submitted to MemeGen.[15] Search Interest [Not Currently\
  \ Available] External References [1] Wikipedia \u2013 Puffin [2] That Cute Site\
  \ \u2013 Puffin Skips To Its Lou [3] Reddit \u2013 /r/adviceanimals: With all the\
  \ misuse of confession bear memes, I propose a new meme. Unpopular opinion puffin\
  \ [4] Reddit \u2013 /r/aww: Puffin skip! [5] Reddit \u2013 /r/pics: Puffin' along\
  \ [6] Reddit \u2013 /r/photoshopbattles: Puffin Dancing (xpost /r/pics) [7] Reddit\
  \ \u2013 /r/aww: Just found out that a baby puffin is called a \"puffling\" [8]\
  \ Reddit \u2013 /r/adviceanimals: Unpopular Opinion Puffin [9] Reddit \u2013 /r/UOPuffin\
  \ [10] 9gag \u2013 Unpopular Opinion Puffin [11] Meme Dad \u2013 Unpopular Opinion\
  \ Puffin [12] Memebase \u2013 Unpopular Opinion Puffin [13] FunnyJunk \u2013 Unpopular\
  \ Opinion Puffin [14] Reddit \u2013 Search Results for \"unpopular opinion puffin\
  \ [15] MemeGen \u2013 Unpopular Opinion Puffin [16] Imgur via Way Back Machine \u2013\
  \ Related Gallery Related Entries 115 total Ermahgerd Overly Attached Girlfriend\
  \ Scumbag Steve Good Guy Greg Ridiculously Photogenic Guy Bad Luck Brian Philosoraptor\
  \ Annoying Facebook Girl The Most Interesting Man in the World Socially Awkward\
  \ Penguin Bear Grylls / Better Drink My Own Piss Successful Black Man View All Related\
  \ Entries Recent Videos There are no videos currently available. + Add a Video Recent\
  \ Images 143 total Unpopular Opinion Puffin Uploaded by Monkey-Thing Unpopular Opinion\
  \ Puffin Uploaded by Evilthing Unpopular Opinion Puffin Uploaded by Evilthing Unpopular\
  \ Opinion Puffin Uploaded by Vulture051 Unpopular Opinion Puffin Uploaded by Evilthing\
  \ Unpopular Opinion Puffin Uploaded by Evilthing Unpopular Opinion Puffin Uploaded\
  \ by Evilthing Unpopular Opinion Puffin Uploaded by Evilthing Unpopular Opinion\
  \ Puffin Uploaded by Evilthing Unpopular Opinion Puffin Uploaded by Evilthing Unpopular\
  \ Opinion Puffin Uploaded by Evilthing Unpopular Opinion Puffin Uploaded by Evilthing\
  \ + Add an Image View All Images Sign up for our Newsletter Top Comments Delete\
  \ Sensitive LNH Moderator Oct 21, 2013 at 03:28PM EDT these are quite unpopular\
  \ opinions. Related: +67 Reply Delete Sensitive Kung Fu Cthulhu Oct 21, 2013 at\
  \ 03:01PM EDT I think it's actually been months since a legitimate page on an Advice\
  \ Animal was made. I also think that this is basically a rehash of Confession Bear\
  \ (same song, different verse), but let's just see how it goes. +34 Reply + Add\
  \ a Comment Comments (77) Display Comments Add a Comment Top Entries This Month\
  \ Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare CEO Person\
  \ Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography Site\
  \ Whisper View More Suggest a Change Edit History Entry Editors (5) amanda b. Meme\
  \ Librarian Brad Digital Archaeologist & Treasurer & Pundit & Gallery Housekeeper\
  \ \xAD\xAD\xADAlex Mercer Entry Moderator & YouTube Scatologist LNH Deactivated\
  \ Y F Digital Archaeologist & Treasurer & Media Maid \u25BC + Request Editorship\
  \ View All Editors Today's Top Image Galleries Assassination of UnitedHealthcare\
  \ CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing Digital Circus About\
  \ Our Story Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes\
  \ News Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/unpopular-opinion-puffin
template_id: puffin
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
