name: Y'all Got Any More of Them
source: http://knowyourmeme.com/memes/yall-got-anymore-of
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- y'all got any more of them
- memes
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About "Y'all Got Anymore of…" is an expression typically used on
  discussion forums to request for additional information on a particular topic of
  interest, or more generally, to indicate one's intense craving for something. Originally
  quoted by the drug-fiending character Tyrone Biggums in Chappelle's Show, the phrase
  is often iterated as a reaction image or image macro format based on a still shot
  of Dave Chappelle's character and the phrasal template "Y'all any more of them /
  X?” Origin As early as June 2010,[5] image macros featuring the character Tyrone
  Biggums in front of a green and white color wheel background were submitted to Meme
  Generator[6] under the title "Crackhead." Spread The meme had its first break-out
  in December 2013, when Redditor abdullah10 submitted an image macro joking about
  asking for WiFi passwords to the /r/AdviceAnimals[1] subreddit, where it gained
  over 1,400 upvotes in three months (shown below, left). On January 4th, 2014, Redditor
  Baddabink posted a Tyrone Biggums image macro to /r/AdviceAnimals[7] mocking the
  practice of constantly refreshing Reddit while it is down (shown below, right).
  In two months, the post accumulated more than 13,000 upvotes and 90 comments. On
  February 28th, Redditor jlmawp submitted a Dave Chappelle Crackhead image macro
  complaining about cold weather in Chicago, Illinois to /r/AdviceAnimals[2] (shown
  below, left). On March 4th, Redditor mathemagician117 posted a low-resolution image
  macro with the caption "Y'all got any more of them / pixels" to /r/AdviceAnimals[4]
  (shown below, right). In the first month, the posts garnered upwards of 33,600 and
  11,900 upvotes, respectively. On March 7th, Redditor mathemagician117's image macro
  was reposted on 9gag.[11] On March 18th, Redditor Masshole224 submitted an image
  macro criticizing conspiracy theories regarding the missing Malaysian Airlines flight
  to /r/AdviceAnimals,[12] gathering over 11,200 upvotes and 190 comments in two weeks
  (shown below, left). On April 1st, Redditor aakme posted an image macro joking about
  asking his female roommates to set him up with their friends to /r/AdviceAnimals[13]
  (shown below, right). In less than 24 hours, the post accumulated upwards of 16,200
  upvotes and 400 comments. Various Examples As of April 2014, two additional pages
  have been created on Meme Generator[9][10] and a template titled "Dave Chappelle
  – Y'all Got Any More" was launched on the image-captioning site Livememe.[8] Search
  Interest External References [1] Reddit – Everytime I enter a place that has WiFi
  [2] Reddit – Chicago here. Its so cold [3] Reddit – After 11 Days of the news reporting
  on the same conspiracy theories [4] Reddit – Yall got any more of them [5] Wayback
  Machine – Chappelle crackhead [6] Meme Generator – Chappelle crackhead [7] Reddit
  – How I feel hitting the refresh button [8] Livememe – Livememe [9] Meme Generator
  – Chappelle crackhead [10] Meme Generator – Dave Chapelle crackhead [11] 9gag –
  Yall got any more of them [12] Reddit – After 11 days of the news reporting on the
  same conspiracy [13] Reddit – As a newly single guy with two female roommates
aside_content: MemeStatusConfirmedType:Exploitable,Image Macro,Pop Culture Reference,Reaction,SnowcloneYear2010OriginMeme
  GeneratorRegionUnited StatesTagsimage macro,crack,addiction,comedian,chappelle,crack
  head,request,dave chappelle crackhead memes,tyrone biggums,y'all got anymore of
  meme
added_at: '2014-04-02T12:48:13-04:00'
