example:
- y'all got any more of them
- memes
keywords:
- null
name: Y'all Got Any More of Them
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Y'all Got Anymore of... / Tyrone Biggums | Know Your Meme Hi! You\
  \ must login or signup first! Already a memeber? Login Now! Don't have an account?\
  \ Sign up Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos\
  \ Submit \u2192 Images Trending Most Commented Most Favorited High Score Low Score\
  \ Most Viewed All Templates Upload an Image Articles News Explainers Collections\
  \ Interviews Meme Insider Magazine More Discord Newsletter Episodes Forums Meme\
  \ Store Login Abstract user icon Memes Categories Trending News Images Trending\
  \ Images Videos Trending Videos Editorials Meme Insider Magazine Newsletter Policies\
  \ and Guidelines Meme Store Old site Login Know Your Meme is the property of Literally\
  \ Media \xA92024 Literally Media. All Rights Reserved. This image Of Woman Confidently\
  \ Strolling Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years\
  \ Ago, This Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The\
  \ Anarchy Chess Memes Turns Two Years Old Today Phrase 'The Fridge Protects The\
  \ Snacks' A Growing Favorite Among Pickup Artist Influencers Jamie G, The Bosh British\
  \ Charva, Has Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also\
  \ Trending: Honey Extension Influencer Scam Renegade Raider Copypasta Assassination\
  \ of UnitedHealthcare CEO Y'all Got Anymore of... / Tyrone Biggums Added 10 years\
  \ ago / Updated about 16 hours ago Confirmed 308,751 Part of a series on Chappelle's\
  \ Show. [View Related Entries] View All 27 Images Navigation About \u2022 Origin\
  \ \u2022 Spread \u2022 Various Examples \u2022 Search Interest \u2022 External References\
  \ \u2022 Recent Images About \"Y'all Got Anymore of\u2026\" is an expression typically\
  \ used on discussion forums to request for additional information on a particular\
  \ topic of interest, or more generally, to indicate one's intense craving for something.\
  \ Originally quoted by the drug-fiending character Tyrone Biggums in Chappelle's\
  \ Show, the phrase is often iterated as a reaction image or image macro format based\
  \ on a still shot of Dave Chappelle's character and the phrasal template \"Y'all\
  \ any more of them / X?\u201D Origin As early as June 2010,[5] image macros featuring\
  \ the character Tyrone Biggums in front of a green and white color wheel background\
  \ were submitted to Meme Generator[6] under the title \"Crackhead.\" Spread The\
  \ meme had its first break-out in December 2013, when Redditor abdullah10 submitted\
  \ an image macro joking about asking for WiFi passwords to the /r/AdviceAnimals[1]\
  \ subreddit, where it gained over 1,400 upvotes in three months (shown below, left).\
  \ On January 4th, 2014, Redditor Baddabink posted a Tyrone Biggums image macro to\
  \ /r/AdviceAnimals[7] mocking the practice of constantly refreshing Reddit while\
  \ it is down (shown below, right). In two months, the post accumulated more than\
  \ 13,000 upvotes and 90 comments. On February 28th, Redditor jlmawp submitted a\
  \ Dave Chappelle Crackhead image macro complaining about cold weather in Chicago,\
  \ Illinois to /r/AdviceAnimals[2] (shown below, left). On March 4th, Redditor mathemagician117\
  \ posted a low-resolution image macro with the caption \"Y'all got any more of them\
  \ / pixels\" to /r/AdviceAnimals[4] (shown below, right). In the first month, the\
  \ posts garnered upwards of 33,600 and 11,900 upvotes, respectively. On March 7th,\
  \ Redditor mathemagician117's image macro was reposted on 9gag.[11] On March 18th,\
  \ Redditor Masshole224 submitted an image macro criticizing conspiracy theories\
  \ regarding the missing Malaysian Airlines flight to /r/AdviceAnimals,[12] gathering\
  \ over 11,200 upvotes and 190 comments in two weeks (shown below, left). On April\
  \ 1st, Redditor aakme posted an image macro joking about asking his female roommates\
  \ to set him up with their friends to /r/AdviceAnimals[13] (shown below, right).\
  \ In less than 24 hours, the post accumulated upwards of 16,200 upvotes and 400\
  \ comments. Various Examples As of April 2014, two additional pages have been created\
  \ on Meme Generator[9][10] and a template titled \"Dave Chappelle \u2013 Y'all Got\
  \ Any More\" was launched on the image-captioning site Livememe.[8] Search Interest\
  \ External References [1] Reddit \u2013 Everytime I enter a place that has WiFi\
  \ [2] Reddit \u2013 Chicago here. Its so cold [3] Reddit \u2013 After 11 Days of\
  \ the news reporting on the same conspiracy theories [4] Reddit \u2013 Yall got\
  \ any more of them [5] Wayback Machine \u2013 Chappelle crackhead [6] Meme Generator\
  \ \u2013 Chappelle crackhead [7] Reddit \u2013 How I feel hitting the refresh button\
  \ [8] Livememe \u2013 Livememe [9] Meme Generator \u2013 Chappelle crackhead [10]\
  \ Meme Generator \u2013 Dave Chapelle crackhead [11] 9gag \u2013 Yall got any more\
  \ of them [12] Reddit \u2013 After 11 days of the news reporting on the same conspiracy\
  \ [13] Reddit \u2013 As a newly single guy with two female roommates image macro\
  \ crack addiction comedian chappelle crack head request dave chappelle crackhead\
  \ memes tyrone biggums y'all got anymore of meme Share Pin Related Entries 9 total\
  \ Fuck Yo Couch Modern Problems Require Moder... Cocaine Is A Hell Of A Drug I'm\
  \ Rick James, Bitch! View All Related Entries Recent Images 27 total View All Images\
  \ Recent Videos 0 total There are no recent videos. Sign up for our Newsletter Load\
  \ 17 Comments Comments 17 total 18 Y'all Got Anymore of... / Tyrone Biggums 308,751\
  \ 0 27 17 Part of a series on Chappelle's Show. [View Related Entries] Updated Dec\
  \ 23, 2024 at 04:23PM EST by LiterallyAustin. Added Apr 02, 2014 at 12:48PM EDT\
  \ by Don. Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i' to view\
  \ the image gallery, 'v' to view the video gallery, or 'r' to view a random entry.\
  \ Meme Status Confirmed Type: Exploitable, Image Macro, Pop Culture Reference, Reaction,\
  \ Snowclone Year 2010 Origin Meme Generator Region United States Tags image macro,\
  \ crack, addiction, comedian, chappelle, crack head, request, dave chappelle crackhead\
  \ memes, tyrone biggums, y'all got anymore of meme About \"Y'all Got Anymore of\u2026\
  \" is an expression typically used on discussion forums to request for additional\
  \ information on a particular topic of interest, or more generally, to indicate\
  \ one's intense craving for something. Originally quoted by the drug-fiending character\
  \ Tyrone Biggums in Chappelle's Show, the phrase is often iterated as a reaction\
  \ image or image macro format based on a still shot of Dave Chappelle's character\
  \ and the phrasal template \"Y'all any more of them / X?\u201D Origin As early as\
  \ June 2010,[5] image macros featuring the character Tyrone Biggums in front of\
  \ a green and white color wheel background were submitted to Meme Generator[6] under\
  \ the title \"Crackhead.\" Spread The meme had its first break-out in December 2013,\
  \ when Redditor abdullah10 submitted an image macro joking about asking for WiFi\
  \ passwords to the /r/AdviceAnimals[1] subreddit, where it gained over 1,400 upvotes\
  \ in three months (shown below, left). On January 4th, 2014, Redditor Baddabink\
  \ posted a Tyrone Biggums image macro to /r/AdviceAnimals[7] mocking the practice\
  \ of constantly refreshing Reddit while it is down (shown below, right). In two\
  \ months, the post accumulated more than 13,000 upvotes and 90 comments. On February\
  \ 28th, Redditor jlmawp submitted a Dave Chappelle Crackhead image macro complaining\
  \ about cold weather in Chicago, Illinois to /r/AdviceAnimals[2] (shown below, left).\
  \ On March 4th, Redditor mathemagician117 posted a low-resolution image macro with\
  \ the caption \"Y'all got any more of them / pixels\" to /r/AdviceAnimals[4] (shown\
  \ below, right). In the first month, the posts garnered upwards of 33,600 and 11,900\
  \ upvotes, respectively. On March 7th, Redditor mathemagician117's image macro was\
  \ reposted on 9gag.[11] On March 18th, Redditor Masshole224 submitted an image macro\
  \ criticizing conspiracy theories regarding the missing Malaysian Airlines flight\
  \ to /r/AdviceAnimals,[12] gathering over 11,200 upvotes and 190 comments in two\
  \ weeks (shown below, left). On April 1st, Redditor aakme posted an image macro\
  \ joking about asking his female roommates to set him up with their friends to /r/AdviceAnimals[13]\
  \ (shown below, right). In less than 24 hours, the post accumulated upwards of 16,200\
  \ upvotes and 400 comments. Various Examples As of April 2014, two additional pages\
  \ have been created on Meme Generator[9][10] and a template titled \"Dave Chappelle\
  \ \u2013 Y'all Got Any More\" was launched on the image-captioning site Livememe.[8]\
  \ Search Interest External References [1] Reddit \u2013 Everytime I enter a place\
  \ that has WiFi [2] Reddit \u2013 Chicago here. Its so cold [3] Reddit \u2013 After\
  \ 11 Days of the news reporting on the same conspiracy theories [4] Reddit \u2013\
  \ Yall got any more of them [5] Wayback Machine \u2013 Chappelle crackhead [6] Meme\
  \ Generator \u2013 Chappelle crackhead [7] Reddit \u2013 How I feel hitting the\
  \ refresh button [8] Livememe \u2013 Livememe [9] Meme Generator \u2013 Chappelle\
  \ crackhead [10] Meme Generator \u2013 Dave Chapelle crackhead [11] 9gag \u2013\
  \ Yall got any more of them [12] Reddit \u2013 After 11 days of the news reporting\
  \ on the same conspiracy [13] Reddit \u2013 As a newly single guy with two female\
  \ roommates Related Entries 9 total Fuck Yo Couch Modern Problems Require Modern\
  \ Solutions Cocaine Is A Hell Of A Drug I'm Rick James, Bitch! Is X Gonna Have to\
  \ Choke a Bitch? What did the 5 fingers say to the face? Dave Chappelle Reading\
  \ White People Magazine Charlie Murphy's True Hollywood Stories Kobe-ing Recent\
  \ Videos There are no videos currently available. + Add a Video Recent Images 27\
  \ total Y'all Got Anymore of... / Tyr... Uploaded by Rebecca Rhodes Y'all Got Anymore\
  \ of... / Tyr... Uploaded by Y F Y'all Got Anymore of... / Tyr... Uploaded by Atamagahen08\
  \ Y'all Got Anymore of... / Tyr... Uploaded by ceno666 Y'all Got Anymore of... /\
  \ Tyr... Uploaded by Kenetic Kups Y'all Got Anymore of... / Tyr... Uploaded by asdf122\
  \ 1 Y'all Got Anymore of... / Tyr... Uploaded by WalkerOfZion Y'all Got Anymore\
  \ of... / Tyr... Uploaded by Y F Y'all Got Anymore of... / Tyr... Uploaded by ballstothewall\
  \ Y'all Got Anymore of... / Tyr... Uploaded by satansyngel Y'all Got Anymore of...\
  \ / Tyr... Uploaded by Junpei Y'all Got Anymore of... / Tyr... Uploaded by Hastur\
  \ Xanthous king + Add an Image View All Images Sign up for our Newsletter Top Comments\
  \ Delete Sensitive WatchMaker Apr 02, 2014 at 09:34PM EDT +25 Reply Delete Sensitive\
  \ Sir Soundwave Moderator Apr 02, 2014 at 01:04PM EDT Y'all got any more of that\
  \ jaAm? +12 Reply + Add a Comment Comments (17) Display Comments Add a Comment Top\
  \ Entries This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (5) Don Administrator\
  \ & Meme Daddy LNH Deactivated Y F Digital Archaeologist & Treasurer & Media Maid\
  \ Matt Secretary of Memes Zach Memenator \u25BC + Request Editorship View All Editors\
  \ Today's Top Image Galleries Assassination of UnitedHealthcare CEO Squirrel Girl\
  \ (Doreen Green) Team Fortress 2 The Amazing Digital Circus About Our Story Site\
  \ Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes News Staff\
  \ Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/yall-got-anymore-of
template_id: yallgot
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
