example:
- It's OK to like trashy shows and movies
- If it makes you happy then it's not a waste of time
keywords:
- The Office
name: Jim Halpert Pointing to Whiteboard
overlay:
- angle: 0.0
  center_x: 0.77
  center_y: 0.13
  scale: 0.28
- angle: 0.0
  center_x: 0.74
  center_y: 0.67
  scale: 0.25
scraped_content: "Jim Halpert Pointing to Whiteboard | Know Your Meme Yo Yo! You must\
  \ login or signup first! Already a memeber? Login Now! Don't have an account? Sign\
  \ up Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos\
  \ Submit \u2192 Images Trending Most Commented Most Favorited High Score Low Score\
  \ Most Viewed All Templates Upload an Image Articles News Explainers Collections\
  \ Interviews Meme Insider Magazine More Discord Newsletter Episodes Forums Meme\
  \ Store Login Abstract user icon Memes Categories Trending News Images Trending\
  \ Images Videos Trending Videos Editorials Meme Insider Magazine Newsletter Policies\
  \ and Guidelines Meme Store Old site Login Know Your Meme is the property of Literally\
  \ Media \xA92024 Literally Media. All Rights Reserved. This image Of Woman Confidently\
  \ Strolling Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years\
  \ Ago, This Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The\
  \ Anarchy Chess Memes Turns Two Years Old Today Phrase 'The Fridge Protects The\
  \ Snacks' A Growing Favorite Among Pickup Artist Influencers Jamie G, The Bosh British\
  \ Charva, Has Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also\
  \ Trending: Honey Extension Influencer Scam Renegade Raider Copypasta Assassination\
  \ of UnitedHealthcare CEO Jim Halpert Pointing to Whiteboard Added 4 years ago /\
  \ Updated 3 years ago Submission 43,064 Part of a series on The Office. [View Related\
  \ Entries] View All 42 Images Navigation About \u2022 Origin \u2022 Spread \u2022\
  \ Various Examples \u2022 Template \u2022 Search Interest \u2022 External References\
  \ \u2022 Recent Images \u2022 Recent Videos About Jim Halpert Pointing to Whiteboard,\
  \ also known as Jim Halpert Explains, is a two-panel image edit series featuring\
  \ the character Jim Halpert from the American situational comedy The Office. Origin\
  \ On November 10th, 2008, the episode of The Office entitled \"Baby Shower\" aired\
  \ in the United States. In the episode, the character Jim charts how his boss Michael\
  \ (portrayed by John Krasinski and Steve Carrell, respectively) might be related\
  \ to another character's baby. He says, \"Jan is about to have a baby with a sperm\
  \ donor. And Michael is preparing for the birth of a watermelon with Dwight. Now,\
  \ this baby will be related to Michael through delusion.\"[1] On March 16th, 2016,\
  \ Tumblr [2] account the-office-daily posted a two-panel screenshot from the scene.\
  \ The post received more than 3,700 notes in less than four years (shown below).\
  \ Spread On April 17th, 2016, BuzzFeed [3] used an edited version of the image that\
  \ reads \"How compatible with Jim Halpert are you\" (shown below, left). Several\
  \ years later, on August 27th, 2019, Imgur [4] user fluffypancakes shared an edited\
  \ variation that rads \"Government is necessary because people left unchecked will\
  \ do evil. The government is composed of people left unchecked.\" The post received\
  \ more than 114,000 views and 4,400 points in less than one year (shown below, center).\
  \ That year, Redditor [5] weirdbokoblin posted a variation with the text \"In December\
  \ we should post our favorite memes from the 2010s in celebration of them. Please.\"\
  \ the post received more than 27,000 points (93% upvoted) and 200 comments in less\
  \ than six months (shown below, right). Various Examples Template Search Interest\
  \ Not available. External References [1] TV Fanatic \u2013 Jan is about to have\
  \ a baby with a sperm donor. And Michael is p\u2026 [2] Tumblr \u2013 the-office-daily's\
  \ Post [3] BuzzFeed \u2013 What Percent Compatible With Jim Halpert From \"The Office\"\
  \ Are You? [4] Imgur \u2013 Accurate [5] Reddit \u2013 /r/teenagers jim halpert\
  \ the office john krasinski television whiteboard comedy weirdbokoblin Share Pin\
  \ Related Entries 21 total They're The Same Picture Schrute Facts No God, Please\
  \ No! Young Michael Scott Shaking E... View All Related Entries Recent Images 42\
  \ total View All Images Recent Videos 1 total View All Videos Sign up for our Newsletter\
  \ Load 1 Comment Comments 1 total 5 Jim Halpert Pointing to Whiteboard 43,064 1\
  \ 42 1 Part of a series on The Office. [View Related Entries] Updated Apr 27, 2021\
  \ at 03:44AM EDT by shevyrolet. Added Mar 23, 2020 at 05:07PM EDT by Matt. Like\
  \ us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the image\
  \ gallery, 'v' to view the video gallery, or 'r' to view a random entry. This submission\
  \ is currently being researched & evaluated! You can help confirm this entry by\
  \ contributing facts, media, and other evidence of notability and mutation. Meme\
  \ Status Submission Type: Image Macro, Photoshop Year 2008 Origin The Office (TV\
  \ Series) Tags jim halpert, the office, john krasinski, television, whiteboard,\
  \ comedy, weirdbokoblin Additional References Meme Generator About Jim Halpert Pointing\
  \ to Whiteboard, also known as Jim Halpert Explains, is a two-panel image edit series\
  \ featuring the character Jim Halpert from the American situational comedy The Office.\
  \ Origin On November 10th, 2008, the episode of The Office entitled \"Baby Shower\"\
  \ aired in the United States. In the episode, the character Jim charts how his boss\
  \ Michael (portrayed by John Krasinski and Steve Carrell, respectively) might be\
  \ related to another character's baby. He says, \"Jan is about to have a baby with\
  \ a sperm donor. And Michael is preparing for the birth of a watermelon with Dwight.\
  \ Now, this baby will be related to Michael through delusion.\"[1] On March 16th,\
  \ 2016, Tumblr [2] account the-office-daily posted a two-panel screenshot from the\
  \ scene. The post received more than 3,700 notes in less than four years (shown\
  \ below). Spread On April 17th, 2016, BuzzFeed [3] used an edited version of the\
  \ image that reads \"How compatible with Jim Halpert are you\" (shown below, left).\
  \ Several years later, on August 27th, 2019, Imgur [4] user fluffypancakes shared\
  \ an edited variation that rads \"Government is necessary because people left unchecked\
  \ will do evil. The government is composed of people left unchecked.\" The post\
  \ received more than 114,000 views and 4,400 points in less than one year (shown\
  \ below, center). That year, Redditor [5] weirdbokoblin posted a variation with\
  \ the text \"In December we should post our favorite memes from the 2010s in celebration\
  \ of them. Please.\" the post received more than 27,000 points (93% upvoted) and\
  \ 200 comments in less than six months (shown below, right). Various Examples Template\
  \ Search Interest Not available. External References [1] TV Fanatic \u2013 Jan is\
  \ about to have a baby with a sperm donor. And Michael is p\u2026 [2] Tumblr \u2013\
  \ the-office-daily's Post [3] BuzzFeed \u2013 What Percent Compatible With Jim Halpert\
  \ From \"The Office\" Are You? [4] Imgur \u2013 Accurate [5] Reddit \u2013 /r/teenagers\
  \ Related Entries 21 total They're The Same Picture Schrute Facts No God, Please\
  \ No! Young Michael Scott Shaking Ed Truck's Hand Jim Halpert Smiling Through Blinds\
  \ Parkour! (The Office) Looks at the Camera Like I'm on The Office I Am Aware of\
  \ the Effect I Have on Women Did I Stutter (Stanley - The Office) Phyllis and Ryan\
  \ Office Christmas Party Photo Days Since Our Last Nonsense Racist Jim Halpert View\
  \ All Related Entries Recent Videos 1 total Jim Halpert Explains [MEME OR... Jim\
  \ Halpert Pointing to White... Uploaded by Team5PM + Add a Video Recent Images 42\
  \ total Jim Halpert Pointing to White... Uploaded by Jaimie Hamilton Jim Halpert\
  \ Pointing to White... Uploaded by Jaimie Hamilton Jim Halpert Pointing to White...\
  \ Uploaded by Jaimie Hamilton Jim Halpert Pointing to White... Uploaded by Jaimie\
  \ Hamilton Jim Halpert Pointing to White... Uploaded by Jaimie Hamilton Jim Halpert\
  \ Pointing to White... Uploaded by Jaimie Hamilton Jim Halpert Pointing to White...\
  \ Uploaded by Lugamo Jim Halpert Pointing to White... Uploaded by TheWolffromMars35\
  \ Jim Halpert Pointing to White... Uploaded by Arizona Kid Jim Halpert Pointing\
  \ to White... Uploaded by wimpykidfan37 Jim Halpert Pointing to White... Uploaded\
  \ by andcallmeshirley Jim Halpert Pointing to White... Uploaded by shevyrolet +\
  \ Add an Image View All Images Sign up for our Newsletter + Add a Comment Comments\
  \ (1) Display Comments Add a Comment Top Entries This Month Meme Saika Kawakita\
  \ Smile GIF Event Assassination of UnitedHealthcare CEO Person Luigi Mangione UHC\
  \ CEO Shooter Subculture The Ki Sisters Culture Pornography Site Whisper View More\
  \ Suggest a Change Edit History Entry Editors (3) Matt Secretary of Memes Y F Digital\
  \ Archaeologist & Treasurer & Media Maid shevyrolet Digital Archaeologist & Treasurer\
  \ & Media Bus Boy + Request Editorship View All Editors Today's Top Image Galleries\
  \ Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress\
  \ 2 The Amazing Digital Circus About Our Story Site Rules Policies and Guidelines\
  \ Credits Contact Meme DB Memes Episodes News Staff Contact Extras! Style Guide\
  \ RSS Feeds"
source: https://knowyourmeme.com/memes/jim-halpert-pointing-to-whiteboard
template_id: jim
text:
- align: center
  anchor_x: 0.025
  anchor_y: 0.045
  angle: 1.0
  color: black
  font: comic
  scale_x: 0.61
  scale_y: 0.22
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.02
  anchor_y: 0.56
  angle: 0.0
  color: black
  font: comic
  scale_x: 0.55
  scale_y: 0.35
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
