name: Jim Halpert Pointing to Whiteboard
source: https://knowyourmeme.com/memes/jim-halpert-pointing-to-whiteboard
keywords:
- The Office
text:
- style: upper
  color: black
  font: comic
  anchor_x: 0.025
  anchor_y: 0.045
  angle: 1.0
  scale_x: 0.61
  scale_y: 0.22
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: black
  font: comic
  anchor_x: 0.02
  anchor_y: 0.56
  angle: 0.0
  scale_x: 0.55
  scale_y: 0.35
  align: center
  start: 0.0
  stop: 1.0
example:
- It's OK to like trashy shows and movies
- If it makes you happy then it's not a waste of time
overlay:
- center_x: 0.77
  center_y: 0.13
  angle: 0.0
  scale: 0.28
- center_x: 0.74
  center_y: 0.67
  angle: 0.0
  scale: 0.25
scraped_content: About Jim Halpert Pointing to Whiteboard, also known as Jim Halpert
  Explains, is a two-panel image edit series featuring the character Jim Halpert from
  the American situational comedy The Office. Origin On November 10th, 2008, the episode
  of The Office entitled "Baby Shower" aired in the United States. In the episode,
  the character Jim charts how his boss Michael (portrayed by John Krasinski and Steve
  Carrell, respectively) might be related to another character's baby. He says, "Jan
  is about to have a baby with a sperm donor. And Michael is preparing for the birth
  of a watermelon with Dwight. Now, this baby will be related to Michael through delusion."[1]
  On March 16th, 2016, Tumblr [2] account the-office-daily posted a two-panel screenshot
  from the scene. The post received more than 3,700 notes in less than four years
  (shown below). Spread On April 17th, 2016, BuzzFeed [3] used an edited version of
  the image that reads "How compatible with Jim Halpert are you" (shown below, left).
  Several years later, on August 27th, 2019, Imgur [4] user fluffypancakes shared
  an edited variation that rads "Government is necessary because people left unchecked
  will do evil. The government is composed of people left unchecked." The post received
  more than 114,000 views and 4,400 points in less than one year (shown below, center).
  That year, Redditor [5] weirdbokoblin posted a variation with the text "In December
  we should post our favorite memes from the 2010s in celebration of them. Please."
  the post received more than 27,000 points (93% upvoted) and 200 comments in less
  than six months (shown below, right). Various Examples Template Search Interest
  Not available. External References [1] TV Fanatic – Jan is about to have a baby
  with a sperm donor. And Michael is p… [2] Tumblr – the-office-daily's Post [3] BuzzFeed
  – What Percent Compatible With Jim Halpert From "The Office" Are You? [4] Imgur
  – Accurate [5] Reddit – /r/teenagers
aside_content: MemeStatusSubmissionType:Image Macro,PhotoshopYear2008OriginThe Office
  (TV Series)Tagsjim halpert,the office,john krasinski,television,whiteboard,comedy,weirdbokoblinAdditional
  ReferencesMeme Generator
added_at: '2020-03-23T17:07:13-04:00'
