name: Sarcastic Bear
source: http://knowyourmeme.com/memes/sarcastic-bear
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- i'm so sorry
- i haven't memorized the internet
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About Sarcastic Bear is an advice animal image macro series featuring
  a photograph of a bear wearing what appears to be an irreverent and sardonic facial
  expression, captioned with sarcastic or derisive statements. The tone of the series
  bears similarities to Condescending Wonka image macros. Origin On May 28th, 2014,
  Redditor RuggedlyHandsome submitted a photograph of a brown bear with its mouth
  agape titled "bear looks sarcastic as fuck" to the /r/funny[4] subreddit, where
  it gained over 3,800 votes (94% upvoted) prior to being archived (shown below, left).
  The subreddit's commentators promptly predicted that the photo would spawn a new
  advice animal series, with the top-voted comment naming the meme "Sarcastic Bear".[4]
  Other commenters subsequently submitted captioned versions of the photo with sarcastic
  messages (shown below, right). Spread On June 5th, 2014, Redditor alazz posted a
  Sarcastic Bear image mocking those who use Scumbag Stacy memes to complain about
  women who sleep with their friends to /r/AdviceAnimals,[7] receiving more than 3,200
  votes (90% upvoted) before it was archived. On September 23rd, Imgur[2] user ShoopSythe
  submitted a Sarcastic Bear image macro titled "How people feel like when they repost,"
  featuring the caption "I'm so sorry / I haven't memorized the Internet" (shown below,
  right). In the next four months, the image garnered upwards of 7,300 points and
  200 comments. On January 31st, 2015, Imgur[6] user omgwhatamidoing submitted an
  image macro of Confession Bear directly above a Sarcastic Bear macro, which mocked
  the perceived similarities between the two advice animals (shown below). In 72 hours,
  the images gained over 6,600 points and 430 comments. Notable Examples Search Interest
  External References [1] Reddit – bear looks sarcastic as fuck [2] Imgur – How people
  feel like when they repost. [3] Imgur – Sarcastic Bear [4] Reddit – bear looks sarcastic
  as fuck – comments [5] Reddit – bear looks sarcastic as fuck – examples [6] Imgur
  – Life must be so hard [7] Reddit – Sarcastic Bear
aside_content: MemeStatusSubmissionBadges:ResearchingYear2014OriginRedditTagsimage
  macro,bear,sarcasm,advice animal,sarcastic,ruggedlyhandsome
added_at: '2015-01-31T06:52:42-05:00'
