example:
- i'm so sorry
- i haven't memorized the internet
keywords:
- null
name: Sarcastic Bear
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Sarcastic Bear | Know Your Meme Word Up! You must login or signup\
  \ first! Already a memeber? Login Now! Don't have an account? Sign up Now! Meme\
  \ Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Sarcastic Bear Added 9 years ago / Updated 5 years ago Submission 28,665 Part\
  \ of a series on Advice Animals. [View Related Entries] View All 20 Images Navigation\
  \ About \u2022 Origin \u2022 Spread \u2022 Notable Examples \u2022 Search Interest\
  \ \u2022 External References \u2022 Recent Images About Sarcastic Bear is an advice\
  \ animal image macro series featuring a photograph of a bear wearing what appears\
  \ to be an irreverent and sardonic facial expression, captioned with sarcastic or\
  \ derisive statements. The tone of the series bears similarities to Condescending\
  \ Wonka image macros. Origin On May 28th, 2014, Redditor RuggedlyHandsome submitted\
  \ a photograph of a brown bear with its mouth agape titled \"bear looks sarcastic\
  \ as fuck\" to the /r/funny[4] subreddit, where it gained over 3,800 votes (94%\
  \ upvoted) prior to being archived (shown below, left). The subreddit's commentators\
  \ promptly predicted that the photo would spawn a new advice animal series, with\
  \ the top-voted comment naming the meme \"Sarcastic Bear\".[4] Other commenters\
  \ subsequently submitted captioned versions of the photo with sarcastic messages\
  \ (shown below, right). Spread On June 5th, 2014, Redditor alazz posted a Sarcastic\
  \ Bear image mocking those who use Scumbag Stacy memes to complain about women who\
  \ sleep with their friends to /r/AdviceAnimals,[7] receiving more than 3,200 votes\
  \ (90% upvoted) before it was archived. On September 23rd, Imgur[2] user ShoopSythe\
  \ submitted a Sarcastic Bear image macro titled \"How people feel like when they\
  \ repost,\" featuring the caption \"I'm so sorry / I haven't memorized the Internet\"\
  \ (shown below, right). In the next four months, the image garnered upwards of 7,300\
  \ points and 200 comments. On January 31st, 2015, Imgur[6] user omgwhatamidoing\
  \ submitted an image macro of Confession Bear directly above a Sarcastic Bear macro,\
  \ which mocked the perceived similarities between the two advice animals (shown\
  \ below). In 72 hours, the images gained over 6,600 points and 430 comments. Notable\
  \ Examples Search Interest External References [1] Reddit \u2013 bear looks sarcastic\
  \ as fuck [2] Imgur \u2013 How people feel like when they repost. [3] Imgur \u2013\
  \ Sarcastic Bear [4] Reddit \u2013 bear looks sarcastic as fuck \u2013 comments\
  \ [5] Reddit \u2013 bear looks sarcastic as fuck \u2013 examples [6] Imgur \u2013\
  \ Life must be so hard [7] Reddit \u2013 Sarcastic Bear image macro bear sarcasm\
  \ advice animal sarcastic ruggedlyhandsome Share Pin Related Entries 115 total Ermahgerd\
  \ Overly Attached Girlfriend Scumbag Steve Good Guy Greg View All Related Entries\
  \ Recent Images 20 total View All Images Recent Videos 0 total There are no recent\
  \ videos. Sign up for our Newsletter Load 57 Comments Comments 57 total 10 Sarcastic\
  \ Bear 28,665 0 20 57 Part of a series on Advice Animals. [View Related Entries]\
  \ Updated Oct 31, 2019 at 04:11AM EDT by Y F. Added Jan 31, 2015 at 06:52AM EST\
  \ by Particle Mare. Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press\
  \ 'i' to view the image gallery, 'v' to view the video gallery, or 'r' to view a\
  \ random entry. This submission is currently being researched & evaluated! You can\
  \ help confirm this entry by contributing facts, media, and other evidence of notability\
  \ and mutation. Meme Status Submission Badges: Researching Year 2014 Origin Reddit\
  \ Tags image macro, bear, sarcasm, advice animal, sarcastic, ruggedlyhandsome About\
  \ Sarcastic Bear is an advice animal image macro series featuring a photograph of\
  \ a bear wearing what appears to be an irreverent and sardonic facial expression,\
  \ captioned with sarcastic or derisive statements. The tone of the series bears\
  \ similarities to Condescending Wonka image macros. Origin On May 28th, 2014, Redditor\
  \ RuggedlyHandsome submitted a photograph of a brown bear with its mouth agape titled\
  \ \"bear looks sarcastic as fuck\" to the /r/funny[4] subreddit, where it gained\
  \ over 3,800 votes (94% upvoted) prior to being archived (shown below, left). The\
  \ subreddit's commentators promptly predicted that the photo would spawn a new advice\
  \ animal series, with the top-voted comment naming the meme \"Sarcastic Bear\".[4]\
  \ Other commenters subsequently submitted captioned versions of the photo with sarcastic\
  \ messages (shown below, right). Spread On June 5th, 2014, Redditor alazz posted\
  \ a Sarcastic Bear image mocking those who use Scumbag Stacy memes to complain about\
  \ women who sleep with their friends to /r/AdviceAnimals,[7] receiving more than\
  \ 3,200 votes (90% upvoted) before it was archived. On September 23rd, Imgur[2]\
  \ user ShoopSythe submitted a Sarcastic Bear image macro titled \"How people feel\
  \ like when they repost,\" featuring the caption \"I'm so sorry / I haven't memorized\
  \ the Internet\" (shown below, right). In the next four months, the image garnered\
  \ upwards of 7,300 points and 200 comments. On January 31st, 2015, Imgur[6] user\
  \ omgwhatamidoing submitted an image macro of Confession Bear directly above a Sarcastic\
  \ Bear macro, which mocked the perceived similarities between the two advice animals\
  \ (shown below). In 72 hours, the images gained over 6,600 points and 430 comments.\
  \ Notable Examples Search Interest External References [1] Reddit \u2013 bear looks\
  \ sarcastic as fuck [2] Imgur \u2013 How people feel like when they repost. [3]\
  \ Imgur \u2013 Sarcastic Bear [4] Reddit \u2013 bear looks sarcastic as fuck \u2013\
  \ comments [5] Reddit \u2013 bear looks sarcastic as fuck \u2013 examples [6] Imgur\
  \ \u2013 Life must be so hard [7] Reddit \u2013 Sarcastic Bear Related Entries 115\
  \ total Ermahgerd Overly Attached Girlfriend Scumbag Steve Good Guy Greg Ridiculously\
  \ Photogenic Guy Bad Luck Brian Philosoraptor Annoying Facebook Girl The Most Interesting\
  \ Man in the World Socially Awkward Penguin Bear Grylls / Better Drink My Own Piss\
  \ Successful Black Man View All Related Entries Recent Videos There are no videos\
  \ currently available. + Add a Video Recent Images 20 total Sarcastic Bear Uploaded\
  \ by iBlewupthemoon Sarcastic Bear Uploaded by Don Sarcastic Bear Uploaded by Don\
  \ Sarcastic Bear Uploaded by Don Sarcastic Bear Uploaded by Don Sarcastic Bear Uploaded\
  \ by Don Sarcastic Bear Uploaded by Don Sarcastic Bear Uploaded by Don Sarcastic\
  \ Bear Uploaded by Particle Mare Sarcastic Bear Uploaded by Particle Mare Sarcastic\
  \ Bear Uploaded by Particle Mare Sarcastic Bear Uploaded by Particle Mare + Add\
  \ an Image View All Images Sign up for our Newsletter Top Comments Delete Sensitive\
  \ Dragon Lord Jan 31, 2015 at 07:16AM EST you may ask why but +84 Reply Delete Sensitive\
  \ Don Staff Feb 02, 2015 at 05:09PM EST I'm about to meme all over this entry. +62\
  \ Reply + Add a Comment Comments (57) Display Comments Add a Comment Top Entries\
  \ This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (3) Particle\
  \ Mare Wolf of Meme Street Don Administrator & Meme Daddy Y F Digital Archaeologist\
  \ & Treasurer & Media Maid + Request Editorship View All Editors Today's Top Image\
  \ Galleries Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team\
  \ Fortress 2 The Amazing Digital Circus About Our Story Site Rules Policies and\
  \ Guidelines Credits Contact Meme DB Memes Episodes News Staff Contact Extras! Style\
  \ Guide RSS Feeds"
source: http://knowyourmeme.com/memes/sarcastic-bear
template_id: sarcasticbear
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
