example:
- ''
- i feel like i'm taking crazy pills
keywords:
- null
name: I Feel Like I'm Taking Crazy Pills
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "I Feel Like I'm Taking Crazy Pills | Know Your Meme Greetings! You\
  \ must login or signup first! Already a memeber? Login Now! Don't have an account?\
  \ Sign up Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos\
  \ Submit \u2192 Images Trending Most Commented Most Favorited High Score Low Score\
  \ Most Viewed All Templates Upload an Image Articles News Explainers Collections\
  \ Interviews Meme Insider Magazine More Discord Newsletter Episodes Forums Meme\
  \ Store Login Abstract user icon Memes Categories Trending News Images Trending\
  \ Images Videos Trending Videos Editorials Meme Insider Magazine Newsletter Policies\
  \ and Guidelines Meme Store Old site Login Know Your Meme is the property of Literally\
  \ Media \xA92024 Literally Media. All Rights Reserved. This image Of Woman Confidently\
  \ Strolling Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years\
  \ Ago, This Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The\
  \ Anarchy Chess Memes Turns Two Years Old Today Phrase 'The Fridge Protects The\
  \ Snacks' A Growing Favorite Among Pickup Artist Influencers Jamie G, The Bosh British\
  \ Charva, Has Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also\
  \ Trending: Honey Extension Influencer Scam Renegade Raider Copypasta Assassination\
  \ of UnitedHealthcare CEO I Feel Like I'm Taking Crazy Pills Added 14 years ago\
  \ / Updated 9 years ago Submission 55,498 Part of a series on Zoolander. [View Related\
  \ Entries] View All 6 Images Navigation About \u2022 Origin \u2022 Spread \u2022\
  \ Recent Images About Origin Zoolander is a 2001 comedy film written, directed and\
  \ starring Ben Stiller. In it he plays Derek Zoolander, an American male model brainwashed\
  \ to kill the Prime Minister of Malaysia. The phrase \"I feel like I'm taking crazy\
  \ pills\" occurs when the fashion designer 'Jacobim Mugatu', played by Will Ferrell\
  \ finally expresses his frustration at the fact no one else in the fashion world\
  \ has noticed Derek Zoolander's supposedly career defining runway 'looks' are nothing\
  \ more than him pulling the same face over and over again. Spread Since the film's\
  \ release, the phrase has been used to describe vexation when the common consensus\
  \ appears to go against common sense or when an expected straight-forward situation\
  \ is greeted by a surprise outcome. On Facebook Am I Taking Crazy Pills or is Nicole\
  \ Kidman the Worst Actress in the World? On YTMND Crazydean.YTMND.com Crazypillzorz.YTMND.com\
  \ Willferrellmash.YTMND.com zoolander ben stiller will ferrell catchphrase Share\
  \ Pin Related Entries 6 total What is This? A Center for Ants? Zoolander Dance /\
  \ Jeep Party X Is So Hot Right Now Zoolander Stare / Zoolander S... View All Related\
  \ Entries Recent Images 6 total View All Images Recent Videos 0 total There are\
  \ no recent videos. Sign up for our Newsletter Load 7 Comments Comments 7 total\
  \ 6 I Feel Like I'm Taking Crazy Pills 55,498 0 6 7 Part of a series on Zoolander.\
  \ [View Related Entries] Updated Nov 21, 2015 at 02:31PM EST by Z.. Added Sep 07,\
  \ 2010 at 10:51PM EDT by Not_Penny's_Quote. Like us on Facebook! Like 1.8M Share\
  \ Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the video\
  \ gallery, or 'r' to view a random entry. This submission is currently being researched\
  \ & evaluated! You can help confirm this entry by contributing facts, media, and\
  \ other evidence of notability and mutation. Meme Status Submission Type: Year 2001\
  \ Origin Zoolander Tags zoolander, ben stiller, will ferrell, catchphrase About\
  \ Origin Zoolander is a 2001 comedy film written, directed and starring Ben Stiller.\
  \ In it he plays Derek Zoolander, an American male model brainwashed to kill the\
  \ Prime Minister of Malaysia. The phrase \"I feel like I'm taking crazy pills\"\
  \ occurs when the fashion designer 'Jacobim Mugatu', played by Will Ferrell finally\
  \ expresses his frustration at the fact no one else in the fashion world has noticed\
  \ Derek Zoolander's supposedly career defining runway 'looks' are nothing more than\
  \ him pulling the same face over and over again. Spread Since the film's release,\
  \ the phrase has been used to describe vexation when the common consensus appears\
  \ to go against common sense or when an expected straight-forward situation is greeted\
  \ by a surprise outcome. On Facebook Am I Taking Crazy Pills or is Nicole Kidman\
  \ the Worst Actress in the World? On YTMND Crazydean.YTMND.com Crazypillzorz.YTMND.com\
  \ Willferrellmash.YTMND.com Related Entries 6 total What is This? A Center for Ants?\
  \ Zoolander Dance / Jeep Party X Is So Hot Right Now Zoolander Stare / Zoolander\
  \ Sees Hansel On The Red Carpet Excuse Me Brah (Zoolander) Hansel Getting Photographed\
  \ / Riding Scooter (Zoolander) Recent Videos There are no videos currently available.\
  \ + Add a Video Recent Images 6 total I Feel Like I'm Taking Crazy ... Uploaded\
  \ by memetimeradiohour I Feel Like I'm Taking Crazy ... Uploaded by stormcrow704\
  \ I Feel Like I'm Taking Crazy ... Uploaded by Not_Penny's_Quote I Feel Like I'm\
  \ Taking Crazy ... Uploaded by Not_Penny's_Quote I Feel Like I'm Taking Crazy ...\
  \ Uploaded by Not_Penny's_Quote I Feel Like I'm Taking Crazy ... Uploaded by Not_Penny's_Quote\
  \ + Add an Image Sign up for our Newsletter + Add a Comment Comments (7) Display\
  \ Comments Add a Comment Top Entries This Month Meme Saika Kawakita Smile GIF Event\
  \ Assassination of UnitedHealthcare CEO Person Luigi Mangione UHC CEO Shooter Subculture\
  \ The Ki Sisters Culture Pornography Site Whisper View More Suggest a Change Edit\
  \ History Entry Editors (4) Not_Penny's_Quote Investigator & Scrapbooker Brad Digital\
  \ Archaeologist & Treasurer & Pundit & Gallery Housekeeper Molly Horan Tumblr Historian\
  \ Z. Database Moderator & Rage Comicologist + Request Editorship View All Editors\
  \ Today's Top Image Galleries Assassination of UnitedHealthcare CEO Squirrel Girl\
  \ (Doreen Green) Team Fortress 2 The Amazing Digital Circus About Our Story Site\
  \ Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes News Staff\
  \ Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/i-feel-like-im-taking-crazy-pills
template_id: crazypills
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
