name: I Feel Like I'm Taking Crazy Pills
source: http://knowyourmeme.com/memes/i-feel-like-im-taking-crazy-pills
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- ''
- i feel like i'm taking crazy pills
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About Origin Zoolander is a 2001 comedy film written, directed and
  starring Ben Stiller. In it he plays Derek Zoolander, an American male model brainwashed
  to kill the Prime Minister of Malaysia. The phrase "I feel like I'm taking crazy
  pills" occurs when the fashion designer 'Jacobim Mugatu', played by Will Ferrell
  finally expresses his frustration at the fact no one else in the fashion world has
  noticed Derek Zoolander's supposedly career defining runway 'looks' are nothing
  more than him pulling the same face over and over again. Spread Since the film's
  release, the phrase has been used to describe vexation when the common consensus
  appears to go against common sense or when an expected straight-forward situation
  is greeted by a surprise outcome. On Facebook Am I Taking Crazy Pills or is Nicole
  Kidman the Worst Actress in the World? On YTMND Crazydean.YTMND.com Crazypillzorz.YTMND.com
  Willferrellmash.YTMND.com
aside_content: MemeStatusSubmissionType:Year2001OriginZoolanderTagszoolander,ben stiller,will
  ferrell,catchphrase
added_at: '2010-09-07T22:51:55-04:00'
