name: First World Problems
source: http://knowyourmeme.com/memes/first-world-problems
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- someone on the internet
- disagrees with me
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About First World Problems, also known as "White Whine," are frustrations
  and complaints that are only experienced by privileged individuals in wealthy countries.
  It is typically used as a tongue-in-cheek comedic device to make light of trivial
  inconveniences. Origin The earliest known reference to "first world problems" can
  be found in the lyrics of Canadian alt rock band Matthew Good Band''s 1995 song
  titled "Omissions of the Omen," which was included as a bonus track on their full-length
  debut album Last of the Ghetto Astronauts: "And somewhere around the world / Someone
  would love to have my first world problems / Kill the moon and turn out the sun
  / Lock your door and load your gun / Free at last now the time has come to choose."
  The first Urban Dictionary[1] entry for the term was submitted on August 10th, 2005:
  First World Problems: Problems from living in a wealthy, industrialized nation that
  third worlders would probably roll their eyes at. Terminology The First World[26]
  is a term associated with already developed countries and their citizens. In contrast,
  the Third World[24] is a term coined in 1952 by French anthropologist Alfred Sauvy
  to define countries that did not take part in either capitalism (the First World)
  or communism (the Second World). Over the years, it gradually gained a negative
  connotation, being associated with poverty and a country being underdeveloped.[25]
  Spread On November 26th, 2008, a Tumblr[5] blog called "The Real First World Problems"
  was created. On June 9th, 2009, a Something Awful[2] Comedy Goldmine post titled
  "#firstworldproblems" complaining about Twitter received several pages worth of
  comments with various first world problems jokes followed by the hashtag. According
  to Trendistic[12], the hashtag #firstworldproblems saw its largest spike around
  noon (EST) on July 1st, 2011. On November 5th, 2010, This is Indexed blogger Jessica
  Hagy[13] posted an index card with a Venn diagram representation of "first world
  problems" and "real problems." In January 2011, American stand-up comic Louis C.K.
  released his third comedy album titled "Hilarious," which featured a skit about
  the extreme gap between the grievances of first world citizens living in over-developed
  societies--which he dubbed "white people problems," and the day-to-day struggles
  experienced by people living in countries that are considered to be of the Third
  World. The /r/firstworldproblems[4] subreddit was created on January 19th, 2011.
  Additional examples can be found under the "first world problems" tag on Tumblr.[10]
  Notable Examples Image Macros A collection of first world problems image macros
  were posted to the viral content site BuzzFeed[3] on March 23rd, 2011. A Meme Generator[6]
  page features a photo of a teenage boy slumped against a wall has 235 submissions
  and a Quickmeme[7] page using a stock photo of a crying woman with her hand against
  her face has 1435 submissions as of November 7th, 2011. Other image macro derivatives
  can be found on the meme builder site Troll.me[9], the image blog Don''t Cry "Emo"/memes/cultures/emo
  Kid[8] blog, and the advice animals subreddit.[11] Videos [This video has been removed]
  Derivatives Third World Success Third World Success features a photograph of a dancing
  tribal child with captions about overcoming hardships that are associated with life
  in underdeveloped countries. The series can be seen as a derivative of Success Kid
  and the anti-thesis of First World Problems. White Girl Problems "White Girl Problems"
  refer to the frustrations that are typically only experienced by privileged white
  adolescent females. Image macros typically feature captions superimposed over a
  picture of a young white girl crying. First World Problems Cat The First World Problems
  Cat series features a photo of a young kitten resting its head accompanied by various
  complaints experienced by house cats. Over-Educated Problems Over-Educated Problems
  features a photograph of a man glumly looking out a window on to a rainy street.
  The captions typically include frustrations associated with being "too well educated"
  compared to one''s peers. First World Metal Problems First World Metal Problems
  features a photograph of a man with a ponytail sitting on a bench wearing a black
  Stormtroopers of Death (S.O.D.) t-shirt and a solemn expression. The captions typically
  include trivial frustrations experienced by those who listen to the metal genre
  of rock music. 1990s First World Problems On July 4th, 2012, the Internet humor
  blog Pleated Jeans[14] published a post titled "Best of the 1990s Problems Meme",
  which featured a compilation of image macros using a screen capture of a crying
  Dawson Leary (played by James Van Der Beek) from the 1990s television series Dawson''s
  Creek. The captions included complaints about hardships associated with living in
  the United States during the 1990s, prior to the widespread use of broadband Internet,
  cell phones and DVD movies. On July 6th, the series was reblogged on the viral content
  site BuzzFeed[15] in a post titled "14 First World Problems From the 90s", which
  received over 6,000 Facebook shares within three days. On July 9th, The Huffington
  Post[16] published a slideshow of notable examples from the series, mentioning Van
  Der Beek''s animated GIF series "James Van Der Memes" produced for the Internet
  humor site Funny or Die. As of July 9th, 2012, the Quickmeme[17] page for "1990s
  Problems" has accumulated over 2,200 submissions. First World Stoner Problems First
  World Stoner Problems is a spin-off series featuring screen captures of the character
  Saul Silver (played by James Franco) from the 2008 comedy film Pineapple Express,
  crying while eating and paired with trivial complaints associated with those who
  consume the drug marijuana. As of March 2013, the "First World Stoner Problems"
  Quickmeme[25] page has received over 4,000 submissions. 1890s Problems 1890s Problems
  features a black-and-white photograph of a forlorn-looking woman accompanied by
  captions describing grievances related to living in the late 19th century. On July
  4th, 2012, Redditor QuelleDommage submitted an 1890s Problems image macro with the
  caption "Comes up with idea that can change modern science / is a woman" to the
  /r/AdviceAnimals[18] subreddit (shown below, left), which only received 16 up votes
  prior to being archived. On July 12th, Redditor Narcosist submitted an image macro
  with the caption "Telegraphed boyfriend / took him two weeks to reply" to the /r/AdviceAnimals[19]
  subreddit (shown below, right), receiving more than 5,100 up votes and 70 comments
  before it was archived. In the coming weeks, compilations of notable examples from
  the series were posted on various websites, including The Huffington Post,[20] BuzzFeed,[21]
  UpRoxx[22] and Neatorama.[23] As of March 2013, the "1890s Problems" Quickmeme[24]
  page has received over 450 submissions. Search Interest External References [1]
  Urban Dictionary – first world problems [2] Something Awful – #firstworldproblems
  [3] BuzzFeed – 15 Examples Of First World Problems [4] Reddit – /r/firstworldproblems
  [5] Tumblr – The Real First World Problems [6] Meme Generator – First World Problems
  [7] Quickmeme – First World Problems [8] Go Cry Emo Kid – You Can Always Use it
  Again in a Couple Months [9] Troll.me – first world problems [10] Tumblr – #first
  world problems [11] Reddit – first world problems [12] Trendistic – #firstworldproblems
  [13] This is Indexed – Poor things [14] Pleated Jeans – Best of the 1990s Problems
  Meme [15] BuzzFeed – 14 First World Problems From The 90s [16] The Huffington Post
  – 1990s Problems Meme [17] Quickmeme – 1990s Problems [18] Reddit – 1890s Problems
  [19] Reddit – 1890s Problems [20] The Huffington Post – 1890s Problems Meme Pictures
  [21] BuzzFeed – 1890s Problems Meme [22] UpRoxx – Meme Watch – 1890s Problems [23]
  Neatorama – 1890s Problems [24] Quickmeme – 1890s Problems [25] Quickmeme – First
  World Stoner Problems'
aside_content: MemeStatusConfirmedType:Catchphrase,Hashtag,Image MacroYear2011OriginUnknownTagsbest
  of 2011,notables of 2011,white people problems,1st world problem,problems that are
  not problems,louis ck,white whine,not really a problem,invented problems,white peopleAdditional
  ReferencesEncyclopedia DramaticaFacebookMeme GeneratorRedditTwitterUrban DictionaryWikipedia
added_at: '2011-06-30T17:44:11-04:00'
