name: It's Happening
source: http://knowyourmeme.com/memes/doom-paul-its-happening
keywords:
  -
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - ''
  - it's happening
overlay:
  - center_x: 0.425
    center_y: 0.3
    angle: 0.0
    scale: 0.45
