example:
- ''
- it's happening
keywords:
- null
name: It's Happening
overlay:
- angle: 0.0
  center_x: 0.425
  center_y: 0.3
  scale: 0.45
scraped_content: "Doom Paul / It's Happening | Know Your Meme Sup! You must login\
  \ or signup first! Already a memeber? Login Now! Don't have an account? Sign up\
  \ Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos Submit\
  \ \u2192 Images Trending Most Commented Most Favorited High Score Low Score Most\
  \ Viewed All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Doom Paul / It's Happening Added 12 years ago / Updated about 17 hours ago\
  \ Confirmed 648,653 Part of a series on Ron Paul. [View Related Entries] [View Related\
  \ Sub-entries] View All 357 Images Navigation About \u2022 Origin \u2022 Spread\
  \ \u2022 Various Examples \u2022 Search Interest \u2022 External References \u2022\
  \ Recent Images \u2022 Recent Videos About Doom Paul is an image macro and animated\
  \ GIF series featuring American physician Ron Paul. Originally used to jokingly\
  \ depict what could happen if Ron Paul was not elected for President during the\
  \ 2012 elections, the images eventually grew to be used alongside incoming events\
  \ to jokingly indicate that their arrival will have apocalyptic results. A common\
  \ catchphrase used in combination with Doom Paul image macros is \"It's Happening!\"\
  \ Origin In 2009, a user on 4chan's /new/ (news) board posted the first doom paul\
  \ image after he lost the 2008 republican nomination with the quote \"All is lost\"\
  \ and \"I told you so.\" The user said the Apocalypse was coming and that these\
  \ were the last days. 4chan soon removed the /new/ board after the founder, Moot,\
  \ got sick of the racism on the board. The meme vanished for awhile but was soon\
  \ mirrored on 4chon.net and it's backup /new/ board. Many of the images were created\
  \ there and remained. Until the founder, Moot, felt bad and recreated the /new/\
  \ board, this time dubbing it /pol/ (Politically incorrect). Soon the images were\
  \ posted again on the newly created /pol/. Spread Multiple Facebook pages were created[1][2]\
  \ to compile and share any images that other users created. The image was first\
  \ meant to be used for Trolling, but Doom Paul supporters quickly started using\
  \ and creating images for other purposes and to be used as a reply for incoming\
  \ events to jokingly indicate that their arrival will have apocalyptic results.\
  \ Doom Paul was also given its own header on Encyclopedia Dramatica's page for /pol/,[3]\
  \ which is also called Doom Paul in its URL. Doom Paul was also given a definition\
  \ on Urban Dictionary in February 2012.[4] Additional examples can also be found\
  \ on Tumblr under the \"Doom Paul\" tag,[5] and on the \"Paul Memes\" sub-Reddit.[6]\
  \ Various Examples Search Interest External References [1] Facebook \u2013 Doom\
  \ Paul [2] Facebook \u2013 DOOM PAUL [3] Encyclopedia Dramatica \u2013 Doom Paul\
  \ [4] Urban Dictionary \u2013 Doom Paul [5] Tumblr \u2013 Tagged: 'Doom-Paul' [6]\
  \ Reddit \u2013 r/Ronpaulmeme doom 4chan ron paul /new/ doom paul the end times\
  \ apaulcolypse /pol/ Share Pin Sub-entries 1 total Nothing Ever Happens Recent Images\
  \ 357 total View All Images Recent Videos 35 total View All Videos Sign up for our\
  \ Newsletter Load 110 Comments Comments 110 total 153 Doom Paul / It's Happening\
  \ 648,663 35 357 110 Part of a series on Ron Paul. [View Related Entries] [View\
  \ Related Sub-entries] Updated Dec 23, 2024 at 04:12PM EST by LiterallyAustin. Added\
  \ Jan 10, 2012 at 03:59AM EST by z0mbi3jesuz. Like us on Facebook! Like 1.8M Share\
  \ Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the video\
  \ gallery, or 'r' to view a random entry. Meme Status Confirmed Type: Image Macro,\
  \ Reaction Year 2009 Origin 4chan Tags doom, 4chan, ron paul, /new/, doom paul,\
  \ the end times, apaulcolypse, /pol/ Additional References Reddit Urban Dictionary\
  \ About Doom Paul is an image macro and animated GIF series featuring American physician\
  \ Ron Paul. Originally used to jokingly depict what could happen if Ron Paul was\
  \ not elected for President during the 2012 elections, the images eventually grew\
  \ to be used alongside incoming events to jokingly indicate that their arrival will\
  \ have apocalyptic results. A common catchphrase used in combination with Doom Paul\
  \ image macros is \"It's Happening!\" Origin In 2009, a user on 4chan's /new/ (news)\
  \ board posted the first doom paul image after he lost the 2008 republican nomination\
  \ with the quote \"All is lost\" and \"I told you so.\" The user said the Apocalypse\
  \ was coming and that these were the last days. 4chan soon removed the /new/ board\
  \ after the founder, Moot, got sick of the racism on the board. The meme vanished\
  \ for awhile but was soon mirrored on 4chon.net and it's backup /new/ board. Many\
  \ of the images were created there and remained. Until the founder, Moot, felt bad\
  \ and recreated the /new/ board, this time dubbing it /pol/ (Politically incorrect).\
  \ Soon the images were posted again on the newly created /pol/. Spread Multiple\
  \ Facebook pages were created[1][2] to compile and share any images that other users\
  \ created. The image was first meant to be used for Trolling, but Doom Paul supporters\
  \ quickly started using and creating images for other purposes and to be used as\
  \ a reply for incoming events to jokingly indicate that their arrival will have\
  \ apocalyptic results. Doom Paul was also given its own header on Encyclopedia Dramatica's\
  \ page for /pol/,[3] which is also called Doom Paul in its URL. Doom Paul was also\
  \ given a definition on Urban Dictionary in February 2012.[4] Additional examples\
  \ can also be found on Tumblr under the \"Doom Paul\" tag,[5] and on the \"Paul\
  \ Memes\" sub-Reddit.[6] Various Examples Search Interest External References [1]\
  \ Facebook \u2013 Doom Paul [2] Facebook \u2013 DOOM PAUL [3] Encyclopedia Dramatica\
  \ \u2013 Doom Paul [4] Urban Dictionary \u2013 Doom Paul [5] Tumblr \u2013 Tagged:\
  \ 'Doom-Paul' [6] Reddit \u2013 r/Ronpaulmeme Sub-entries 1 total Nothing Ever Happens\
  \ Recent Videos 35 total Happening time Doom Paul / It's Happening Uploaded by Fight\
  \ Milk22 Doom Paul - Its Happening Doom Paul / It's Happening Uploaded by Fight\
  \ Milk22 DOOM PAUL Doom Paul / It's Happening Uploaded by Fight Milk22 IT'S HAPPENING\
  \ Doom Paul / It's Happening Uploaded by Fight Milk22 RUSSIACON 1 Doom Paul / It's\
  \ Happening Uploaded by andcallmeshirley IT'S HAPPENING Doom Paul / It's Happening\
  \ Uploaded by andcallmeshirley WHAT'S HAPPENING? Doom Paul / It's Happening Uploaded\
  \ by Y F /pol/.mp4 Doom Paul / It's Happening Uploaded by Y F + Add a Video View\
  \ All Videos Recent Images 357 total Doom Paul / It's Happening Uploaded by IronXZ\
  \ Doom Paul / It's Happening Uploaded by IronXZ Doom Paul / It's Happening Uploaded\
  \ by The Anglo Doom Paul / It's Happening Uploaded by Internet Troll Doom Paul /\
  \ It's Happening Uploaded by Ryumaru Borike Doom Paul / It's Happening Uploaded\
  \ by OurDeerLeader Doom Paul / It's Happening Uploaded by $200 Doom Paul / It's\
  \ Happening Uploaded by Frozen99 Doom Paul / It's Happening Uploaded by Agent Doom\
  \ Paul / It's Happening Uploaded by Viuff, The Ancient Waifumancer Doom Paul / It's\
  \ Happening Uploaded by Vanillite Doom Paul / It's Happening Uploaded by coldacid\
  \ + Add an Image View All Images Sign up for our Newsletter Top Comments Delete\
  \ Sensitive FizzBuzz3000 Aug 23, 2014 at 01:49PM EDT It is done. +44 Reply Delete\
  \ Sensitive Jo\xE3o Pedro Brigatti Aug 23, 2014 at 09:12PM EDT >Confirmed +36 Reply\
  \ + Add a Comment Comments (110) Display Comments Add a Comment Top Entries This\
  \ Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare CEO\
  \ Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (12) z0mbi3jesuz\
  \ Dr.DoomPaul Brad Digital Archaeologist & Treasurer & Pundit & Gallery Housekeeper\
  \ Cyber6x Database Moderator & Midnight Channeler RandomMan Database Moderator &\
  \ God Tier Swag & Protip Advisor & Karma Tycoon & Meme Boi MScratch Database Moderator\
  \ & Historical Meme Historian & \u300CStand User\u300D Scorn Don Administrator &\
  \ Meme Daddy Twenty-One Anime Anthropologist & Protip Advisor & LGBT Community Expert\
  \ Y F Digital Archaeologist & Treasurer & Media Maid 3kole5 Sr. Entry Moderator\
  \ shevyrolet Digital Archaeologist & Treasurer & Media Bus Boy \u25BC + Request\
  \ Editorship View All Editors Today's Top Image Galleries Assassination of UnitedHealthcare\
  \ CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing Digital Circus About\
  \ Our Story Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes\
  \ News Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/doom-paul-its-happening
template_id: happening
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
