example:
- you keep using that word
- i do not think it means what you think it means
keywords:
- null
name: Inigo Montoya
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "You Keep Using That Word, I Do Not Think It Means What You Think\
  \ It Means | Know Your Meme 'lo! You must login or signup first! Already a memeber?\
  \ Login Now! Don't have an account? Sign up Now! Meme Encyclopedia All Cultures\
  \ Events People Sites Subcultures Videos Submit \u2192 Images Trending Most Commented\
  \ Most Favorited High Score Low Score Most Viewed All Templates Upload an Image\
  \ Articles News Explainers Collections Interviews Meme Insider Magazine More Discord\
  \ Newsletter Episodes Forums Meme Store Login Abstract user icon Memes Categories\
  \ Trending News Images Trending Images Videos Trending Videos Editorials Meme Insider\
  \ Magazine Newsletter Policies and Guidelines Meme Store Old site Login Know Your\
  \ Meme is the property of Literally Media \xA92024 Literally Media. All Rights Reserved.\
  \ This image Of Woman Confidently Strolling Through A Glass Panel Has Been A Redraw\
  \ Format Since 2021 Three Years Ago, This Boar's Head 'Exploded' Onto The Meme Scene\
  \ Remember Il Vaticano? The Anarchy Chess Memes Turns Two Years Old Today Phrase\
  \ 'The Fridge Protects The Snacks' A Growing Favorite Among Pickup Artist Influencers\
  \ Jamie G, The Bosh British Charva, Has Taken Over TikTok With His Signature 'Oh\
  \ Cherie Amour' Sound Also Trending: Honey Extension Influencer Scam Renegade Raider\
  \ Copypasta Assassination of UnitedHealthcare CEO You Keep Using That Word, I Do\
  \ Not Think It Means What You Think It Means Added 12 years ago / Updated 8 days\
  \ ago Confirmed 842,494 Part of a series on The Princess Bride. [View Related Entries]\
  \ View All 39 Images Navigation About \u2022 Origin \u2022 Spread \u2022 Various\
  \ Examples \u2022 Search Interest \u2022 External References \u2022 Recent Images\
  \ \u2022 Recent Videos About \"You Keep Using That Word, I Do Not Think It Means\
  \ What You Think It Means\" is a phrase used to call out someone else's incorrect\
  \ use of a word or phrase during online conversations. It is typically iterated\
  \ as an image macro series featuring the fictional character Inigo Montoya from\
  \ the 1987 romantic comedy film The Princess Bride. Origin The quote \u201CYou keep\
  \ using that word, I do not think it means what you think it means\u201D was said\
  \ by American actor Mandy Patinkin[2] who portrayed the swordsman Inigo Montoya[3]\
  \ in the 1987 romantic comedy The Princess Bride.[1] Throughout the movie, Sicilian\
  \ boss Vizzini (portrayed by Wallace Shawn[4]) repeatedly describes the unfolding\
  \ events as \u201Cinconceivable.\u201D After Vizzini attempts to cut a rope the\
  \ Dread Pirate Roberts is climbing up, he yells out that it was inconceivable that\
  \ the pirate did not fall. To this, Montoya replied with the quote: The clip of\
  \ the scene from Princess Bride was uploaded via YouTube channel Bagheadclips on\
  \ February 4th, 2007. Since its upload, the video has been used in the comments\
  \ of Reddit posts as early as since January 2008[20] and has gained more than 644,000\
  \ views as of July 2012. Spread Though the quote had been used to refute posters\
  \ on 4chan[17] as early as March 2010, the first advice animal style image macro\
  \ with the quote over a still photo of Mandy Patinkin as the character was shared\
  \ on the advice animals subreddit[8] on June 18th, 2011. The caption used the word\
  \ \u201Cdecimate\u201D as the example of what was being misused. While the word\
  \ is defined as \u201Cto kill, destroy, or remove a large percentage of\u201D[9],\
  \ it was originally used in the Roman era[10] to refer to a punishment in which\
  \ 1 in 10 men were killed. The misuse of the word to mean anything more than ten\
  \ percent has been blogged about on Listverse[11], personal blog World Wide Words[12]\
  \ and WikiHow.[13] More instances of the image macro have appeared on other subreddits\
  \ including /r/RonPaul[14] and /r/Anarcho_Capitalism.[15] As of July 2012, the Quickmeme[5]\
  \ page has 640 submissions and the Memegenerator[6]page has more than 1800 submissions.\
  \ Additional instances are posted on Memebase[18], Reddit[16] and Tumblr[7]with\
  \ the tag \u201CI do not think it means what you think it means.\u201D Various Examples\
  \ Search Interest External References [1] Wikipedia \u2013 The Princess Bride (film)\
  \ [2] Wikipedia \u2013 Mandy Patinkin [3] Wikipedia \u2013 Inigo Montoya [4] Wikipedia\
  \ \u2013 Wallace Shawn [5] Quickmeme \u2013 Inigo Montoya [6] Memegenerator \u2013\
  \ Inigo Montoya [7] Tumblr \u2013 Posts tagged \"i do not think it means what you\
  \ think it means\" [8] Reddit \u2013 Inigo Montoya says what many of us have been\
  \ thinking. [9] Google Dictionary \u2013 Decimate [10] Wikipedia \u2013 Decimation\
  \ (Roman Army) [11] Listverse \u2013 Top 10 Misused English Words [12] World Wide\
  \ Words \u2013 Decimate [13] WikiHow \u2013 How to Use Commonly Misused Words [14]\
  \ Reddit \u2013 Inigo Montoya schools the MSM [15] Reddit \u2013 Inigo Montoya on\
  \ statists' use of the word \"rights.\" [16] Reddit \u2013 Search results for \"\
  inigo montoya\" [17] chanarchive \u2013 Use of Inigo Montoya quote [18] Memebase\
  \ \u2013 Posts tagged \"Inigo Montoya\" [19] TV Tropes \u2013 You Keep Using That\
  \ Word [20] YouTube \u2013 You keep using that word. | Insights Graph image macro\
  \ movie quote inigo montoya princess bride you keep using that word meme i do not\
  \ think it means what you think it means catchphrases reaction images gif Share\
  \ Pin Related Entries 3 total You Killed My Father, Prepare... You Fell Victim to\
  \ One of the... Anybody Want a Peanut? Recent Images 39 total View All Images Recent\
  \ Videos 2 total View All Videos Sign up for our Newsletter Load 19 Comments Comments\
  \ 19 total 36 You Keep Using That Word, I Do Not Think It Means What You Think It\
  \ Means 842,494 2 39 19 Part of a series on The Princess Bride. [View Related Entries]\
  \ Updated Dec 15, 2024 at 06:54PM EST by LiterallyAustin. Added Jun 27, 2012 at\
  \ 04:36PM EDT by Nobody115. Like us on Facebook! Like 1.8M Share Save Tweet PROTIP:\
  \ Press 'i' to view the image gallery, 'v' to view the video gallery, or 'r' to\
  \ view a random entry. Meme Status Confirmed Type: Catchphrase, Image Macro, Pop\
  \ Culture Reference, Reaction Year 2011 Origin Reddit Tags image macro, movie quote,\
  \ inigo montoya, princess bride, you keep using that word meme, i do not think it\
  \ means what you think it means, catchphrases, reaction images, gif Additional References\
  \ Meme Generator Wikipedia About \"You Keep Using That Word, I Do Not Think It Means\
  \ What You Think It Means\" is a phrase used to call out someone else's incorrect\
  \ use of a word or phrase during online conversations. It is typically iterated\
  \ as an image macro series featuring the fictional character Inigo Montoya from\
  \ the 1987 romantic comedy film The Princess Bride. Origin The quote \u201CYou keep\
  \ using that word, I do not think it means what you think it means\u201D was said\
  \ by American actor Mandy Patinkin[2] who portrayed the swordsman Inigo Montoya[3]\
  \ in the 1987 romantic comedy The Princess Bride.[1] Throughout the movie, Sicilian\
  \ boss Vizzini (portrayed by Wallace Shawn[4]) repeatedly describes the unfolding\
  \ events as \u201Cinconceivable.\u201D After Vizzini attempts to cut a rope the\
  \ Dread Pirate Roberts is climbing up, he yells out that it was inconceivable that\
  \ the pirate did not fall. To this, Montoya replied with the quote: The clip of\
  \ the scene from Princess Bride was uploaded via YouTube channel Bagheadclips on\
  \ February 4th, 2007. Since its upload, the video has been used in the comments\
  \ of Reddit posts as early as since January 2008[20] and has gained more than 644,000\
  \ views as of July 2012. Spread Though the quote had been used to refute posters\
  \ on 4chan[17] as early as March 2010, the first advice animal style image macro\
  \ with the quote over a still photo of Mandy Patinkin as the character was shared\
  \ on the advice animals subreddit[8] on June 18th, 2011. The caption used the word\
  \ \u201Cdecimate\u201D as the example of what was being misused. While the word\
  \ is defined as \u201Cto kill, destroy, or remove a large percentage of\u201D[9],\
  \ it was originally used in the Roman era[10] to refer to a punishment in which\
  \ 1 in 10 men were killed. The misuse of the word to mean anything more than ten\
  \ percent has been blogged about on Listverse[11], personal blog World Wide Words[12]\
  \ and WikiHow.[13] More instances of the image macro have appeared on other subreddits\
  \ including /r/RonPaul[14] and /r/Anarcho_Capitalism.[15] As of July 2012, the Quickmeme[5]\
  \ page has 640 submissions and the Memegenerator[6]page has more than 1800 submissions.\
  \ Additional instances are posted on Memebase[18], Reddit[16] and Tumblr[7]with\
  \ the tag \u201CI do not think it means what you think it means.\u201D Various Examples\
  \ Search Interest External References [1] Wikipedia \u2013 The Princess Bride (film)\
  \ [2] Wikipedia \u2013 Mandy Patinkin [3] Wikipedia \u2013 Inigo Montoya [4] Wikipedia\
  \ \u2013 Wallace Shawn [5] Quickmeme \u2013 Inigo Montoya [6] Memegenerator \u2013\
  \ Inigo Montoya [7] Tumblr \u2013 Posts tagged \"i do not think it means what you\
  \ think it means\" [8] Reddit \u2013 Inigo Montoya says what many of us have been\
  \ thinking. [9] Google Dictionary \u2013 Decimate [10] Wikipedia \u2013 Decimation\
  \ (Roman Army) [11] Listverse \u2013 Top 10 Misused English Words [12] World Wide\
  \ Words \u2013 Decimate [13] WikiHow \u2013 How to Use Commonly Misused Words [14]\
  \ Reddit \u2013 Inigo Montoya schools the MSM [15] Reddit \u2013 Inigo Montoya on\
  \ statists' use of the word \"rights.\" [16] Reddit \u2013 Search results for \"\
  inigo montoya\" [17] chanarchive \u2013 Use of Inigo Montoya quote [18] Memebase\
  \ \u2013 Posts tagged \"Inigo Montoya\" [19] TV Tropes \u2013 You Keep Using That\
  \ Word [20] YouTube \u2013 You keep using that word. | Insights Graph Related Entries\
  \ 3 total You Killed My Father, Prepare to Die You Fell Victim to One of the Classic\
  \ Blunders Anybody Want a Peanut? Recent Videos 2 total You keep using that word.\
  \ I d... You Keep Using That Word, I D... Uploaded by Nobody115 You keep using that\
  \ word. You Keep Using That Word, I D... Uploaded by Nobody115 + Add a Video Recent\
  \ Images 39 total You Keep Using That Word, I D... Uploaded by Triplem You Keep\
  \ Using That Word, I D... Uploaded by bruhinb You Keep Using That Word, I D... Uploaded\
  \ by beyonder422 You Keep Using That Word, I D... Uploaded by Terry Jones You Keep\
  \ Using That Word, I D... Uploaded by Brad You Keep Using That Word, I D... Uploaded\
  \ by Alcom1 You Keep Using That Word, I D... Uploaded by nxrble You Keep Using That\
  \ Word, I D... Uploaded by Tripredacus You Keep Using That Word, I D... Uploaded\
  \ by CrystalDeth You Keep Using That Word, I D... Uploaded by Jill You Keep Using\
  \ That Word, I D... Uploaded by Emperor Palpitoad You Keep Using That Word, I D...\
  \ Uploaded by Emper0rH0rde + Add an Image View All Images Sign up for our Newsletter\
  \ Top Comments Delete Sensitive Necro910: That Krieger Dude Jun 28, 2012 at 03:04PM\
  \ EDT +1 confirm +1 work I've seen this for a while. I've also seen this page is\
  \ crap. +23 Reply Delete Sensitive Captain N the FlyingKickPunch Jul 04, 2012 at\
  \ 03:09PM EDT You keep using that word, and you killed my father, prepare to die?\
  \ +8 Reply + Add a Comment Comments (19) Display Comments Add a Comment Top Entries\
  \ This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (5) Nobody115\
  \ Investigator & Scrapbooker & Commentator amanda b. Meme Librarian Brad Digital\
  \ Archaeologist & Treasurer & Pundit & Gallery Housekeeper Molly Horan Tumblr Historian\
  \ Zach Memenator \u25BC + Request Editorship View All Editors Today's Top Image\
  \ Galleries Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team\
  \ Fortress 2 The Amazing Digital Circus About Our Story Site Rules Policies and\
  \ Guidelines Credits Contact Meme DB Memes Episodes News Staff Contact Extras! Style\
  \ Guide RSS Feeds"
source: http://knowyourmeme.com/memes/you-keep-using-that-word-i-do-not-think-it-means-what-you-think-it-means
template_id: inigo
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
