name: Inigo Montoya
source: http://knowyourmeme.com/memes/you-keep-using-that-word-i-do-not-think-it-means-what-you-think-it-means
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- you keep using that word
- i do not think it means what you think it means
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About "You Keep Using That Word, I Do Not Think It Means What You
  Think It Means" is a phrase used to call out someone else''s incorrect use of a
  word or phrase during online conversations. It is typically iterated as an image
  macro series featuring the fictional character Inigo Montoya from the 1987 romantic
  comedy film The Princess Bride. Origin The quote “You keep using that word, I do
  not think it means what you think it means” was said by American actor Mandy Patinkin[2]
  who portrayed the swordsman Inigo Montoya[3] in the 1987 romantic comedy The Princess
  Bride.[1] Throughout the movie, Sicilian boss Vizzini (portrayed by Wallace Shawn[4])
  repeatedly describes the unfolding events as “inconceivable.” After Vizzini attempts
  to cut a rope the Dread Pirate Roberts is climbing up, he yells out that it was
  inconceivable that the pirate did not fall. To this, Montoya replied with the quote:
  The clip of the scene from Princess Bride was uploaded via YouTube channel Bagheadclips
  on February 4th, 2007. Since its upload, the video has been used in the comments
  of Reddit posts as early as since January 2008[20] and has gained more than 644,000
  views as of July 2012. Spread Though the quote had been used to refute posters on
  4chan[17] as early as March 2010, the first advice animal style image macro with
  the quote over a still photo of Mandy Patinkin as the character was shared on the
  advice animals subreddit[8] on June 18th, 2011. The caption used the word “decimate”
  as the example of what was being misused. While the word is defined as “to kill,
  destroy, or remove a large percentage of”[9], it was originally used in the Roman
  era[10] to refer to a punishment in which 1 in 10 men were killed. The misuse of
  the word to mean anything more than ten percent has been blogged about on Listverse[11],
  personal blog World Wide Words[12] and WikiHow.[13] More instances of the image
  macro have appeared on other subreddits including /r/RonPaul[14] and /r/Anarcho_Capitalism.[15]
  As of July 2012, the Quickmeme[5] page has 640 submissions and the Memegenerator[6]page
  has more than 1800 submissions. Additional instances are posted on Memebase[18],
  Reddit[16] and Tumblr[7]with the tag “I do not think it means what you think it
  means.” Various Examples Search Interest External References [1] Wikipedia – The
  Princess Bride (film) [2] Wikipedia – Mandy Patinkin [3] Wikipedia – Inigo Montoya
  [4] Wikipedia – Wallace Shawn [5] Quickmeme – Inigo Montoya [6] Memegenerator –
  Inigo Montoya [7] Tumblr – Posts tagged "i do not think it means what you think
  it means" [8] Reddit – Inigo Montoya says what many of us have been thinking. [9]
  Google Dictionary – Decimate [10] Wikipedia – Decimation (Roman Army) [11] Listverse
  – Top 10 Misused English Words [12] World Wide Words – Decimate [13] WikiHow – How
  to Use Commonly Misused Words [14] Reddit – Inigo Montoya schools the MSM [15] Reddit
  – Inigo Montoya on statists'' use of the word "rights." [16] Reddit – Search results
  for "inigo montoya" [17] chanarchive – Use of Inigo Montoya quote [18] Memebase
  – Posts tagged "Inigo Montoya" [19] TV Tropes – You Keep Using That Word [20] YouTube
  – You keep using that word. | Insights Graph'
aside_content: MemeStatusConfirmedType:Catchphrase,Image Macro,Pop Culture Reference,ReactionYear2011OriginRedditTagsimage
  macro,movie quote,inigo montoya,princess bride,you keep using that word meme,i do
  not think it means what you think it means,catchphrases,reaction images,gifAdditional
  ReferencesMeme GeneratorWikipedia
added_at: '2012-06-27T16:36:13-04:00'
