example:
- remember this meme?
- pepperidge farm remembers
keywords:
- null
name: Pepperidge Farm Remembers
overlay:
- angle: 0.0
  center_x: 0.41
  center_y: 0.6
  scale: 0.25
scraped_content: "Pepperidge Farm Remembers | Know Your Meme O HAI! You must login\
  \ or signup first! Already a memeber? Login Now! Don't have an account? Sign up\
  \ Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos Submit\
  \ \u2192 Images Trending Most Commented Most Favorited High Score Low Score Most\
  \ Viewed All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Pepperidge Farm Remembers Added 12 years ago / Updated 3 years ago Confirmed\
  \ 697,391 Part of a series on Family Guy. [View Related Entries] View All 74 Images\
  \ Navigation About \u2022 Origin \u2022 Spread \u2022 Notable Examples \u2022 Search\
  \ Interest \u2022 External References \u2022 Recent Images \u2022 Recent Videos\
  \ About Pepperidge Farm Remembers is an image macro series based on a tagline used\
  \ in an advertisement for the commercial bakery Pepperidge Farm. The series features\
  \ a still-shot from a parody of the commercial as seen in the animated television\
  \ series Family Guy and captions reminiscing about outdated relics and practices\
  \ from the past decades. Origin In the early 1980s, Pepperidge Farm began airing\
  \ a commercial featuring an elderly man reminiscing about raisin bread that his\
  \ grandmother used to make with the tagline \u201CPepperidge Farm remembers\u201D\
  \ (shown below, left). Online interest in the commercial resurged more than a decade\
  \ later with a Family Guy parody in Season 5 Episode 3 \u201CHell Comes to Quahod,\u201D\
  \ in which an old man blackmails the audience into buying Milano cookies. The episode\
  \ was originally aired on September 24th, 2006. On June 4th, 2012, Redditor redherpbluederp\
  \ submitted a post to the /r/funny[6] subreddit titled \u201CGod dammit, YouTube\
  \ commentator!\u201D, which included a screenshot of a YouTube comment referencing\
  \ the Pepperidge Farm commercial (shown below). Within four months, the post received\
  \ over 12,725 up votes and 190 comments. Spread On June 6th, the Tumblr[2] blog\
  \ \u201CPepperidge Farm Remembers\u201D was launched with two image macros referencing\
  \ Ja Rule and MTV, though it has been most likely abandoned since. On June 27th,\
  \ 2012, Redditor holuh submitted a post titled \u201CPepperidge Farm,\u201D[7] featuring\
  \ an image macro using the company logo with the caption \u201CRemember a time when\
  \ Reddit had witty and original content / Pepperidge Farm remembers\u201D (shown\
  \ below). Within three months, the post received over 6,100 up votes and 145 comments.\
  \ On August 8th, Redditor cystalbyb submitted an image macro to the /r/memes[8]\
  \ subreddit featuring the caption \u201CRemember when Cartoon Netowork only played\
  \ cartoons? / Pepperidge Farm remembers\u201D (shown below, left). On October 1st,\
  \ Redditor Trollsamabinlolin submitted an image macro to the /r/AdviceAnimals[7]subreddit\
  \ with the caption \u201CRemember when being polite wasn\u2019t flirting? / Pepperidge\
  \ Farm remembers\u201D (shown below, right). With 24 hours, the post reached the\
  \ front page with over 7,400 up votes and 275 comments. As of October 2012, a Facebook[4]\
  \ page for \u201CPepperidge Farm Remembers\u201D has accrued 90 likes and the \u201C\
  Pepperidge Farm Remembers\u201D Quickmeme[1] page has accumulated 206 submissions.\
  \ The image macros have continued to spread on Tumblr[5] under the tag \u201C#pepperidge\
  \ farm remembers.\u201D Notable Examples Search Interest External References [1]\
  \ Quickmeme \u2013 Pepperidge Farm Remembers [2] Tumblr \u2013 Pepperidge Farm Remembers\
  \ via Archive.org [3] FunnyJunk \u2013 Pepperidge Farm Remembers [4] Facebook \u2013\
  \ Pepperidge Farms Remembers [5] Tumblr \u2013 #Pepperidge Farm Remembers [6] Reddit\
  \ \u2013 God dammit, YouTube Commentator! [7] Reddit \u2013 Pepperidge Farm [8]\
  \ Reddit \u2013 Pepperidge Farm Remembers image macro reddit family guy pepperidge\
  \ farms remembers redherpbluederp holuh trollsamabinlolin Share Pin Related Entries\
  \ 50 total Family Guy Effect Family Guy Death Pose / Peter... You Know What Really\
  \ Grinds M... Wacky Waving Inflatable Arm F... View All Related Entries Recent Images\
  \ 74 total View All Images Recent Videos 1 total View All Videos Sign up for our\
  \ Newsletter Load 54 Comments Comments 54 total 28 Pepperidge Farm Remembers 697,393\
  \ 1 74 54 Part of a series on Family Guy. [View Related Entries] Updated Apr 05,\
  \ 2021 at 12:44PM EDT by Matt. Added Oct 03, 2012 at 01:15PM EDT by Don. Like us\
  \ on Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the image gallery,\
  \ 'v' to view the video gallery, or 'r' to view a random entry. Meme Status Confirmed\
  \ Type: Catchphrase, Image Macro Year 2012 Origin Unknown Tags image macro, reddit,\
  \ family guy, pepperidge farms remembers, redherpbluederp, holuh, trollsamabinlolin\
  \ Additional References Reddit About Pepperidge Farm Remembers is an image macro\
  \ series based on a tagline used in an advertisement for the commercial bakery Pepperidge\
  \ Farm. The series features a still-shot from a parody of the commercial as seen\
  \ in the animated television series Family Guy and captions reminiscing about outdated\
  \ relics and practices from the past decades. Origin In the early 1980s, Pepperidge\
  \ Farm began airing a commercial featuring an elderly man reminiscing about raisin\
  \ bread that his grandmother used to make with the tagline \u201CPepperidge Farm\
  \ remembers\u201D (shown below, left). Online interest in the commercial resurged\
  \ more than a decade later with a Family Guy parody in Season 5 Episode 3 \u201C\
  Hell Comes to Quahod,\u201D in which an old man blackmails the audience into buying\
  \ Milano cookies. The episode was originally aired on September 24th, 2006. On June\
  \ 4th, 2012, Redditor redherpbluederp submitted a post to the /r/funny[6] subreddit\
  \ titled \u201CGod dammit, YouTube commentator!\u201D, which included a screenshot\
  \ of a YouTube comment referencing the Pepperidge Farm commercial (shown below).\
  \ Within four months, the post received over 12,725 up votes and 190 comments. Spread\
  \ On June 6th, the Tumblr[2] blog \u201CPepperidge Farm Remembers\u201D was launched\
  \ with two image macros referencing Ja Rule and MTV, though it has been most likely\
  \ abandoned since. On June 27th, 2012, Redditor holuh submitted a post titled \u201C\
  Pepperidge Farm,\u201D[7] featuring an image macro using the company logo with the\
  \ caption \u201CRemember a time when Reddit had witty and original content / Pepperidge\
  \ Farm remembers\u201D (shown below). Within three months, the post received over\
  \ 6,100 up votes and 145 comments. On August 8th, Redditor cystalbyb submitted an\
  \ image macro to the /r/memes[8] subreddit featuring the caption \u201CRemember\
  \ when Cartoon Netowork only played cartoons? / Pepperidge Farm remembers\u201D\
  \ (shown below, left). On October 1st, Redditor Trollsamabinlolin submitted an image\
  \ macro to the /r/AdviceAnimals[7]subreddit with the caption \u201CRemember when\
  \ being polite wasn\u2019t flirting? / Pepperidge Farm remembers\u201D (shown below,\
  \ right). With 24 hours, the post reached the front page with over 7,400 up votes\
  \ and 275 comments. As of October 2012, a Facebook[4] page for \u201CPepperidge\
  \ Farm Remembers\u201D has accrued 90 likes and the \u201CPepperidge Farm Remembers\u201D\
  \ Quickmeme[1] page has accumulated 206 submissions. The image macros have continued\
  \ to spread on Tumblr[5] under the tag \u201C#pepperidge farm remembers.\u201D Notable\
  \ Examples Search Interest External References [1] Quickmeme \u2013 Pepperidge Farm\
  \ Remembers [2] Tumblr \u2013 Pepperidge Farm Remembers via Archive.org [3] FunnyJunk\
  \ \u2013 Pepperidge Farm Remembers [4] Facebook \u2013 Pepperidge Farms Remembers\
  \ [5] Tumblr \u2013 #Pepperidge Farm Remembers [6] Reddit \u2013 God dammit, YouTube\
  \ Commentator! [7] Reddit \u2013 Pepperidge Farm [8] Reddit \u2013 Pepperidge Farm\
  \ Remembers Related Entries 50 total Family Guy Effect Family Guy Death Pose / Peter\
  \ Falls Down The Stairs You Know What Really Grinds My Gears Wacky Waving Inflatable\
  \ Arm Flailing Tube Man Death of Brian Griffin Quagmire Toilet You Guys Always Act\
  \ Like You're Better Than Me \"Who The Fuck Starts A Conversation Like That? I Just\
  \ Sat Down!\" Giggity Family Guy Funny Moments Peter Griffin At The Door / \"Holy\
  \ Crap Lois, It's X!\" Peter Is Going Insane Theory (Family Guy) View All Related\
  \ Entries Recent Videos 1 total Pepperidge Farm Commercial Pepperidge Farm Remembers\
  \ Uploaded by Dr. Cheetos + Add a Video Recent Images 74 total Pepperidge Farm Remembers\
  \ Uploaded by Reddit Moments Pepperidge Farm Remembers Uploaded by Edgar Weebling\
  \ Pepperidge Farm Remembers Uploaded by Edgar Weebling Pepperidge Farm Remembers\
  \ Uploaded by Reddit Moments Pepperidge Farm Remembers Uploaded by Rebecca Rhodes\
  \ Pepperidge Farm Remembers Uploaded by Rebecca Rhodes Pepperidge Farm Remembers\
  \ Uploaded by Rebecca Rhodes Pepperidge Farm Remembers Uploaded by Rebecca Rhodes\
  \ Pepperidge Farm Remembers Uploaded by Soup King Pepperidge Farm Remembers Uploaded\
  \ by YouMadeMe Pepperidge Farm Remembers Uploaded by Y F Pepperidge Farm Remembers\
  \ Uploaded by Aragamanagato + Add an Image View All Images Sign up for our Newsletter\
  \ Top Comments Delete Sensitive Zancrow Oct 03, 2012 at 05:47PM EDT Remember when\
  \ Family Guy was funny? Pepperidge Farm does not remember. +49 Reply Delete Sensitive\
  \ TehRussBus Oct 04, 2012 at 06:37PM EDT +25 Reply + Add a Comment Comments (54)\
  \ Display Comments Add a Comment Top Entries This Month Meme Saika Kawakita Smile\
  \ GIF Event Assassination of UnitedHealthcare CEO Person Luigi Mangione UHC CEO\
  \ Shooter Subculture The Ki Sisters Culture Pornography Site Whisper View More Suggest\
  \ a Change Edit History Entry Editors (6) Don Administrator & Meme Daddy Brad Digital\
  \ Archaeologist & Treasurer & Pundit & Gallery Housekeeper Z. Database Moderator\
  \ & Rage Comicologist Twenty-One Anime Anthropologist & Protip Advisor & LGBT Community\
  \ Expert Y F Digital Archaeologist & Treasurer & Media Maid Matt Secretary of Memes\
  \ \u25BC + Request Editorship View All Editors Today's Top Image Galleries Assassination\
  \ of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing\
  \ Digital Circus About Our Story Site Rules Policies and Guidelines Credits Contact\
  \ Meme DB Memes Episodes News Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/pepperidge-farm-remembers
template_id: remembers
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
