example:
- Kramer, what's going on in there?
- It's a Chicken Roaster sign, right across from my window.
keywords:
- null
name: Kramer, What's Going On In There?
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.505
  scale: 0.4
scraped_content: "Kramer, What's Going On In There? | Know Your Meme 'lo! You must\
  \ login or signup first! Already a memeber? Login Now! Don't have an account? Sign\
  \ up Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos\
  \ Submit \u2192 Images Trending Most Commented Most Favorited High Score Low Score\
  \ Most Viewed All Templates Upload an Image Articles News Explainers Collections\
  \ Interviews Meme Insider Magazine More Discord Newsletter Episodes Forums Meme\
  \ Store Login Abstract user icon Memes Categories Trending News Images Trending\
  \ Images Videos Trending Videos Editorials Meme Insider Magazine Newsletter Policies\
  \ and Guidelines Meme Store Old site Login Know Your Meme is the property of Literally\
  \ Media \xA92024 Literally Media. All Rights Reserved. This image Of Woman Confidently\
  \ Strolling Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years\
  \ Ago, This Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The\
  \ Anarchy Chess Memes Turns Two Years Old Today Phrase 'The Fridge Protects The\
  \ Snacks' A Growing Favorite Among Pickup Artist Influencers Jamie G, The Bosh British\
  \ Charva, Has Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also\
  \ Trending: Honey Extension Influencer Scam Renegade Raider Copypasta Assassination\
  \ of UnitedHealthcare CEO Kramer, What's Going On In There? Added 2 years ago /\
  \ Updated 12 days ago Confirmed 70,568 Part of a series on Seinfeld. [View Related\
  \ Entries] View All 129 Images Featured Episode Navigation About \u2022 Origin \u2022\
  \ Spread \u2022 Various Examples \u2022 Templates \u2022 Search Interest \u2022\
  \ External References \u2022 Recent Images \u2022 Recent Videos About Kramer, What's\
  \ Going On In There? refers to an exploitable image macro taken from a 1996 episode\
  \ of Seinfeld where Jerry Seinfeld asks Kramer (played by Michael Richards) what\
  \ is going on inside his apartment that is emitting a bright red light. The template\
  \ was first used on Facebook in late 2021 but picked up in abundance in early 2022,\
  \ where meme creators inserted their own subculture references and photoshopped\
  \ the original scene. Origin The template originates from episode eight of Seinfeld's\
  \ eighth season called, \"The Chicken Roaster.\"[1] In the episode, a chicken restaurant\
  \ with an unusually bright-red sign opens up across the street from Kramer's apartment.\
  \ The restaurant's sign is so bright that it drives Kramer crazy and Jerry and Kramer\
  \ end up switching apartments in the episode. When Jerry first notices the red light\
  \ in the episode, he asks Kramer, \"What's going on in there?\" The clip from the\
  \ episode was uploaded to YouTube [2] on August 23rd, 2009, by the channel SolidSnake986\
  \ (shown below). Over the course of 11 years, the video gained roughly 250,200 views\
  \ and 800 likes. The image macro template was first used on Facebook in September\
  \ 2021 in the Facebook[17] group Seinfeld SoupPosting. The earliest publicly available\
  \ meme based on the format, a crossover post between Facebook groups Seinfeld SoupPosting\
  \ and Halo Plasmaposting, was reposted to Twitter by the Twitter[18] page @Plasmaposting\
  \ on September 23rd, 2021. The meme (shown below) references the Halo video game\
  \ franchise. Over the course of three months, the tweet received over 280 likes.\
  \ Spread Starting in October 2021, the format achieved notable popularity in Seinfeld\
  \ SoupPosting Facebook group.[19][20] On October 24th, 2021, Twitter[3] user _QuietLeader_\
  \ reposted another version of the format (shown below), a meme referencing the Dune\
  \ universe. The meme was most likely inspired by the release of the Dune (2021)\
  \ movie around that time. The tweet received 178 likes over the course of two months.\
  \ On November 20th, 2021, Facebook[14] user Chris Scott posted a meme to the Star\
  \ Trek Shitposting Facebook group (shown below, left) that referenced \"The Rite\
  \ of Ascension\"[5] within the Klingon people of Star Trek. The post received roughly\
  \ 1,000 reactions over the course of a month and a half. Facebook[15] page Geek\
  \ Club posted a different version of Scott's meme the next day (shown below, right),\
  \ replacing the text with yellow, subtitle text. Their post received 276 reactions\
  \ in the same amount of time. The template circulated Facebook going into December\
  \ 2021. For instance, Facebook[16] user Erik Saucedo posted a version of the template\
  \ on December 19th to the Halo Plasmaposting Facebook group. The meme (shown below)\
  \ received 976 reactions over three weeks. In January 2022, the template was used\
  \ en masse on Twitter. On January 6th, 2022, Twitter[4] user derpman47 reposted\
  \ the Star Trek version of the meme. The tweet received roughly 20,300 likes over\
  \ the course of four days. It was also reposted to platforms like Tumblr [6] on\
  \ the same day, where it received roughly 9,200 notes over the same amount of time.\
  \ The first variant on Twitter was posted within the replies of the above Twitter\
  \ meme by Twitter[7] user owainjam on January 7th, 2022. The meme (shown below)\
  \ references Michael Richard's infamous \"N-word rant\"[8] at the L.A. Laugh Factory\
  \ in 2007 \u2014 a stand-up set that he was subsequently canceled for. The meme\
  \ received 47 likes in three days. More Twitter users exploited the template going\
  \ into the rest of January. For instance, Twitter[9] user buckadeath posted a version\
  \ on January 8th, 2022 (shown below, left), that referenced Balrogs from The Lord\
  \ of the Rings universe. The meme received roughly 48,500 likes in two days. Twitter[10]\
  \ user SilentDawnLB also posted a variant on January 8th (shown below, right) that\
  \ referenced the movie The Thing. Their meme gained roughly 17,900 likes in two\
  \ days. The trend spread to platforms like Instagram and Facebook on January 8th,\
  \ 2022, where Instagrammers like trashcanpaul[11] posted versions of the template.\
  \ Trashcanpaul, for instance, received roughly 62,700 likes over the course of two\
  \ days. Additionally, Facebook[12] page Classical Studies memes for Hellenistic\
  \ teens received roughly 3,300 reactions for its meme that used the template. Video\
  \ memes using the template appeared on Instagram as the format became more widespread.\
  \ For instance, Instagram[13] page fakejerryseinfeld posted a video on January 9th,\
  \ 2022, that referenced the movie Enter the Void (shown below). The post received\
  \ roughly 1,000 likes in less than 24 hours. As the template was exploited across\
  \ platforms, meme creators continued to change the color of the light's tint in\
  \ order to reference other movies and subcultures like The Matrix, Shrek and Uncut\
  \ Gems, among others. Additionally, multiple versions of the template were posted\
  \ in the Facebook[17] group Seinfeld SoupPosting going into January. Various Examples\
  \ Templates Search Interest External References [1] iMDb \u2013 The Chicken Roaster\
  \ [2] YouTube \u2013 Seinfeld: Jerry & Kramer \u2013 Chicken Roaster Sign [3] Twitter\
  \ \u2013 @_QuietLeader_ [4] Twitter \u2013 @derpman47 [5] Fandom \u2013 Rite of\
  \ Ascension [6] Tumblr \u2013 its-the-real-me [7] Twitter \u2013 @owainjam [8] Dailymotion\
  \ \u2013 N-word rant [9] Twitter \u2013 @buckadeath [10] Twitter \u2013 @SilentDawnLB\
  \ [11] Instagram \u2013 @trashcanpaul [12] Facebook \u2013 Classical Studies memes\
  \ for Hellenistic teens [13] Instagram \u2013 @fakejerryseinfeld [14] Facebook \u2013\
  \ Chris Scott [15] Facebook \u2013 Geek Club [16] Facebook \u2013 Erik Saucedo [17]\
  \ Facebook \u2013 Seinfeld SoupPosting [18] Twitter \u2013 @Plasmaposting [19] Facebook\
  \ \u2013 https://www.facebook.com/groups/soupposting/posts/309865390905299/ [20]\
  \ Facebook \u2013 Sven Bergeron kramer seinfeld meme memes michael richards exploitables\
  \ kramer red room meme red room image macros what's going on in there Share Pin\
  \ Related Entries 7 total Costanza.jpg / George Costanz... No Soup for You / Soup\
  \ Nazi I'm Shifting Into Soup Mode Seinfeld Theme Song Parodies View All Related\
  \ Entries Recent Images 129 total View All Images Recent Videos 5 total View All\
  \ Videos Sign up for our Newsletter Load 16 Comments Comments 16 total 13 Kramer,\
  \ What's Going On In There? 70,573 5 129 16 Part of a series on Seinfeld. [View\
  \ Related Entries] Updated Dec 11, 2024 at 04:29PM EST by LiterallyAustin. Added\
  \ Jan 10, 2022 at 08:55AM EST by Owen. Like us on Facebook! Like 1.8M Share Save\
  \ Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the video gallery,\
  \ or 'r' to view a random entry. Featured Episode Meme Status Confirmed Type: Exploitable,\
  \ Image Macro, Pop Culture Reference Year 1996 Origin Seinfeld Tags kramer, seinfeld,\
  \ meme, memes, michael richards, exploitables, kramer red room meme, red room, image\
  \ macros, what's going on in there About Kramer, What's Going On In There? refers\
  \ to an exploitable image macro taken from a 1996 episode of Seinfeld where Jerry\
  \ Seinfeld asks Kramer (played by Michael Richards) what is going on inside his\
  \ apartment that is emitting a bright red light. The template was first used on\
  \ Facebook in late 2021 but picked up in abundance in early 2022, where meme creators\
  \ inserted their own subculture references and photoshopped the original scene.\
  \ Origin The template originates from episode eight of Seinfeld's eighth season\
  \ called, \"The Chicken Roaster.\"[1] In the episode, a chicken restaurant with\
  \ an unusually bright-red sign opens up across the street from Kramer's apartment.\
  \ The restaurant's sign is so bright that it drives Kramer crazy and Jerry and Kramer\
  \ end up switching apartments in the episode. When Jerry first notices the red light\
  \ in the episode, he asks Kramer, \"What's going on in there?\" The clip from the\
  \ episode was uploaded to YouTube [2] on August 23rd, 2009, by the channel SolidSnake986\
  \ (shown below). Over the course of 11 years, the video gained roughly 250,200 views\
  \ and 800 likes. The image macro template was first used on Facebook in September\
  \ 2021 in the Facebook[17] group Seinfeld SoupPosting. The earliest publicly available\
  \ meme based on the format, a crossover post between Facebook groups Seinfeld SoupPosting\
  \ and Halo Plasmaposting, was reposted to Twitter by the Twitter[18] page @Plasmaposting\
  \ on September 23rd, 2021. The meme (shown below) references the Halo video game\
  \ franchise. Over the course of three months, the tweet received over 280 likes.\
  \ Spread Starting in October 2021, the format achieved notable popularity in Seinfeld\
  \ SoupPosting Facebook group.[19][20] On October 24th, 2021, Twitter[3] user _QuietLeader_\
  \ reposted another version of the format (shown below), a meme referencing the Dune\
  \ universe. The meme was most likely inspired by the release of the Dune (2021)\
  \ movie around that time. The tweet received 178 likes over the course of two months.\
  \ On November 20th, 2021, Facebook[14] user Chris Scott posted a meme to the Star\
  \ Trek Shitposting Facebook group (shown below, left) that referenced \"The Rite\
  \ of Ascension\"[5] within the Klingon people of Star Trek. The post received roughly\
  \ 1,000 reactions over the course of a month and a half. Facebook[15] page Geek\
  \ Club posted a different version of Scott's meme the next day (shown below, right),\
  \ replacing the text with yellow, subtitle text. Their post received 276 reactions\
  \ in the same amount of time. The template circulated Facebook going into December\
  \ 2021. For instance, Facebook[16] user Erik Saucedo posted a version of the template\
  \ on December 19th to the Halo Plasmaposting Facebook group. The meme (shown below)\
  \ received 976 reactions over three weeks. In January 2022, the template was used\
  \ en masse on Twitter. On January 6th, 2022, Twitter[4] user derpman47 reposted\
  \ the Star Trek version of the meme. The tweet received roughly 20,300 likes over\
  \ the course of four days. It was also reposted to platforms like Tumblr [6] on\
  \ the same day, where it received roughly 9,200 notes over the same amount of time.\
  \ The first variant on Twitter was posted within the replies of the above Twitter\
  \ meme by Twitter[7] user owainjam on January 7th, 2022. The meme (shown below)\
  \ references Michael Richard's infamous \"N-word rant\"[8] at the L.A. Laugh Factory\
  \ in 2007 \u2014 a stand-up set that he was subsequently canceled for. The meme\
  \ received 47 likes in three days. More Twitter users exploited the template going\
  \ into the rest of January. For instance, Twitter[9] user buckadeath posted a version\
  \ on January 8th, 2022 (shown below, left), that referenced Balrogs from The Lord\
  \ of the Rings universe. The meme received roughly 48,500 likes in two days. Twitter[10]\
  \ user SilentDawnLB also posted a variant on January 8th (shown below, right) that\
  \ referenced the movie The Thing. Their meme gained roughly 17,900 likes in two\
  \ days. The trend spread to platforms like Instagram and Facebook on January 8th,\
  \ 2022, where Instagrammers like trashcanpaul[11] posted versions of the template.\
  \ Trashcanpaul, for instance, received roughly 62,700 likes over the course of two\
  \ days. Additionally, Facebook[12] page Classical Studies memes for Hellenistic\
  \ teens received roughly 3,300 reactions for its meme that used the template. Video\
  \ memes using the template appeared on Instagram as the format became more widespread.\
  \ For instance, Instagram[13] page fakejerryseinfeld posted a video on January 9th,\
  \ 2022, that referenced the movie Enter the Void (shown below). The post received\
  \ roughly 1,000 likes in less than 24 hours. As the template was exploited across\
  \ platforms, meme creators continued to change the color of the light's tint in\
  \ order to reference other movies and subcultures like The Matrix, Shrek and Uncut\
  \ Gems, among others. Additionally, multiple versions of the template were posted\
  \ in the Facebook[17] group Seinfeld SoupPosting going into January. Various Examples\
  \ Templates Search Interest External References [1] iMDb \u2013 The Chicken Roaster\
  \ [2] YouTube \u2013 Seinfeld: Jerry & Kramer \u2013 Chicken Roaster Sign [3] Twitter\
  \ \u2013 @_QuietLeader_ [4] Twitter \u2013 @derpman47 [5] Fandom \u2013 Rite of\
  \ Ascension [6] Tumblr \u2013 its-the-real-me [7] Twitter \u2013 @owainjam [8] Dailymotion\
  \ \u2013 N-word rant [9] Twitter \u2013 @buckadeath [10] Twitter \u2013 @SilentDawnLB\
  \ [11] Instagram \u2013 @trashcanpaul [12] Facebook \u2013 Classical Studies memes\
  \ for Hellenistic teens [13] Instagram \u2013 @fakejerryseinfeld [14] Facebook \u2013\
  \ Chris Scott [15] Facebook \u2013 Geek Club [16] Facebook \u2013 Erik Saucedo [17]\
  \ Facebook \u2013 Seinfeld SoupPosting [18] Twitter \u2013 @Plasmaposting [19] Facebook\
  \ \u2013 https://www.facebook.com/groups/soupposting/posts/309865390905299/ [20]\
  \ Facebook \u2013 Sven Bergeron Related Entries 7 total Costanza.jpg / George Costanza\
  \ Reaction Face No Soup for You / Soup Nazi I'm Shifting Into Soup Mode Seinfeld\
  \ Theme Song Parodies You're Crying From X / George Costanza Crying Jerry Seinfeld\
  \ Kith Photoshoot I'm Not Ashamed of My Body / History Recent Videos 5 total Dagoth\
  \ Ur, What's going on in... Kramer, What's Going On In Th... Uploaded by Autumn\
  \ Able Kramereldansen Kramer, What's Going On In Th... Uploaded by 4chaniskill karamerdansen\
  \ Kramer, What's Going On In Th... Uploaded by Cyrannus95 What it feels like to\
  \ leave E... Kramer, What's Going On In Th... Uploaded by ed Kramer, What's Going\
  \ On In Th... Kramer, What's Going On In Th... Uploaded by Zach + Add a Video Recent\
  \ Images 129 total Kramer, What's Going On In Th... Uploaded by Triplem Kramer,\
  \ What's Going On In Th... Uploaded by Edgar Weebling Kramer, What's Going On In\
  \ Th... Uploaded by The Kreepy Krab Kramer, What's Going On In Th... Uploaded by\
  \ Autumn Able Kramer, What's Going On In Th... Uploaded by OrlandoLikeTheCity Kramer,\
  \ What's Going On In Th... Uploaded by Kotor Kramer, What's Going On In Th... Uploaded\
  \ by DaltonaCAN Kramer, What's Going On In Th... Uploaded by Philipp Kramer, What's\
  \ Going On In Th... Uploaded by Autumn Able Kramer, What's Going On In Th... Uploaded\
  \ by KZN02 Kramer, What's Going On In Th... Uploaded by KZN02 Kramer, What's Going\
  \ On In Th... Uploaded by AJ_Lethal + Add an Image View All Images Sign up for our\
  \ Newsletter Top Comments Delete Sensitive The Human Element Jan 10, 2022 at 02:18PM\
  \ EST Aurora Borealis. +40 Reply Delete Sensitive G\xF6rkt\xFCrks are furries Jan\
  \ 10, 2022 at 09:43AM EST i really like this one +15 Reply + Add a Comment Comments\
  \ (16) Display Comments Add a Comment Top Entries This Month Meme Saika Kawakita\
  \ Smile GIF Event Assassination of UnitedHealthcare CEO Person Luigi Mangione UHC\
  \ CEO Shooter Subculture The Ki Sisters Culture Pornography Site Whisper View More\
  \ Suggest a Change Edit History Entry Editors (3) Owen Federal Agent Zach Memenator\
  \ Philipp Memesplainer + Request Editorship View All Editors Today's Top Image Galleries\
  \ Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress\
  \ 2 The Amazing Digital Circus About Our Story Site Rules Policies and Guidelines\
  \ Credits Contact Meme DB Memes Episodes News Staff Contact Extras! Style Guide\
  \ RSS Feeds"
source: https://knowyourmeme.com/memes/kramer-whats-going-on-in-there
template_id: kramer
text:
- align: center
  anchor_x: 0.3
  anchor_y: 0.12
  angle: 0.0
  color: khaki
  font: thin
  scale_x: 0.7
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: khaki
  font: thin
  scale_x: 0.6
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: default
text_zones: 2
