example:
- i can has
- this meme?
keywords:
- null
name: I Can Has Cheezburger?
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Happy Cat | Know Your Meme Hi! You must login or signup first! Already\
  \ a memeber? Login Now! Don't have an account? Sign up Now! Meme Encyclopedia All\
  \ Cultures Events People Sites Subcultures Videos Submit \u2192 Images Trending\
  \ Most Commented Most Favorited High Score Low Score Most Viewed All Templates Upload\
  \ an Image Articles News Explainers Collections Interviews Meme Insider Magazine\
  \ More Discord Newsletter Episodes Forums Meme Store Login Abstract user icon Memes\
  \ Categories Trending News Images Trending Images Videos Trending Videos Editorials\
  \ Meme Insider Magazine Newsletter Policies and Guidelines Meme Store Old site Login\
  \ Know Your Meme is the property of Literally Media \xA92024 Literally Media. All\
  \ Rights Reserved. This image Of Woman Confidently Strolling Through A Glass Panel\
  \ Has Been A Redraw Format Since 2021 Three Years Ago, This Boar's Head 'Exploded'\
  \ Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess Memes Turns Two Years\
  \ Old Today Phrase 'The Fridge Protects The Snacks' A Growing Favorite Among Pickup\
  \ Artist Influencers Jamie G, The Bosh British Charva, Has Taken Over TikTok With\
  \ His Signature 'Oh Cherie Amour' Sound Also Trending: Honey Extension Influencer\
  \ Scam Renegade Raider Copypasta Assassination of UnitedHealthcare CEO Happy Cat\
  \ Added 15 years ago / Updated 13 days ago Confirmed 391,553 Part of a series on\
  \ Cats. [View Related Entries] [View Related Sub-entries] View All 53 Images Navigation\
  \ About \u2022 Origin \u2022 Spread \u2022 Various Examples \u2022 Search Interest\
  \ \u2022 External References \u2022 Recent Images \u2022 Recent Videos About Happy\
  \ Cat is the subject of a series of image macros and exploitable images, and among\
  \ the most well-known of LOLcats.. Happy Cat achieved fame via Something Awful in\
  \ 2003, when forum user FancyCat is speculated to have originally posted the image.\
  \ In 2007, a superimposed caption was placed on the image reading \"I Can Has Cheezburger?\"\
  \ This image spawned both the LOLcats meme and the website I Can Has Cheezburger,\
  \ as well as the NEDM meme. Happy Cat is of the British Shorthair breed. Origin\
  \ The earliest known appearance of Happy Cat on the web comes from a Russian cat\
  \ food company, also called Happy Cat. Although the cat was not the primary mascot\
  \ for the company, it did appear on the website as early as 2003, as evidenced in\
  \ an archived Happycat.ru thread.[1] There are conflicting reports on the identity\
  \ of the cat. Some believe Happy Cat is a British shorthair named Frank who was\
  \ born in 1994 and died in 2007. However, a blog post from corpuscola[7] says it\
  \ is named Misha and was born in 2003. According to Encyclopedia Dramatica[2] and\
  \ Oh Internet[3] articles, the Happy Cat meme began when the image was posted to\
  \ the Something Awful forums in 2003, by user FancyCat. The YTMND Wiki[4] page on\
  \ the subject also points to Something Awful as the birthplace of Happy Cat. While\
  \ there is no record of a user named FancyCat on SomethingAwful, there is a \"Fancy\
  \ Cat\"[5] (two words) who has been a registered user since 2002, but their post\
  \ history is incomplete. One of the earliest verifiable appearances of Happy Cat\
  \ on Something Awful occurred on May 12th, 2004 in an article entitled The Grocery\
  \ Gauntlet[6] written by Reid \"Frolixo\" Paskiewicz. Spread Happy Cat grew most\
  \ notable online through its popularity in various meme templates. LOLcats After\
  \ a caption reading \"I Can Has Cheezburger?\" was superimposed onto the Happy Cat\
  \ image, more images in similar fashion began appearing on the web, launching the\
  \ LOLcats meme and the popular I Can Has Cheezburger website. NEDM NEDM is an acronym\
  \ for \"Not Even Doom Music\", which is used as a catchphrase online. The face of\
  \ Happy Cat is now commonly associated with this phrase. Oh God How Did This Get\
  \ In Here I Am Not Good With Computer Oh God How Did This Get In Here I Am Not Good\
  \ With Computer is a catchphrase derived from an image featuring a poorly cropped\
  \ picture of Happy Cat. This catchphrase is often used as an ironic way of informing\
  \ a user that they are technologically inept. Various Examples Search Interest External\
  \ References [1] Happycat.ru \u2013 Original Thread [2] Encyclopedia Dramatica \u2013\
  \ Happy Cat [3] Oh Internet (via Wayback Machine) \u2013 Happy Cat [4] YTMND \u2013\
  \ Happy Cat [5] Something Awful \u2013 Fancy Cat [6] Something Awful \u2013 The\
  \ Grocery Gauntlet [7] Corpuscola Blogspot \u2013 Lurkmore on a note lolcat image\
  \ macro cheezburger funny something awful 4chan ytmnd mascot cat stare fancycat\
  \ i can has cheezburger british shorthair Share Pin Related Entries 211 total Grumpy\
  \ Cat Nyan Cat Business Cat Smudge the Cat View All Related Entries Sub-entries\
  \ 2 total NEDM Oh God How Did This Get Here ... Recent Images 53 total View All\
  \ Images Recent Videos 2 total View All Videos Sign up for our Newsletter Load 26\
  \ Comments Comments 26 total 34 Happy Cat 391,553 2 53 26 Part of a series on Cats.\
  \ [View Related Entries] [View Related Sub-entries] Updated Dec 10, 2024 at 03:57PM\
  \ EST by LiterallyAustin. Added Sep 09, 2009 at 03:36PM EDT by Chris Menning. Like\
  \ us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the image\
  \ gallery, 'v' to view the video gallery, or 'r' to view a random entry. Meme Status\
  \ Confirmed Type: Animal Year 2003 Origin Something Awful Tags lolcat, image macro,\
  \ cheezburger, funny, something awful, 4chan, ytmnd, mascot, cat, stare, fancycat,\
  \ i can has cheezburger, british shorthair Additional References Encyclopedia Dramatica\
  \ About Happy Cat is the subject of a series of image macros and exploitable images,\
  \ and among the most well-known of LOLcats.. Happy Cat achieved fame via Something\
  \ Awful in 2003, when forum user FancyCat is speculated to have originally posted\
  \ the image. In 2007, a superimposed caption was placed on the image reading \"\
  I Can Has Cheezburger?\" This image spawned both the LOLcats meme and the website\
  \ I Can Has Cheezburger, as well as the NEDM meme. Happy Cat is of the British Shorthair\
  \ breed. Origin The earliest known appearance of Happy Cat on the web comes from\
  \ a Russian cat food company, also called Happy Cat. Although the cat was not the\
  \ primary mascot for the company, it did appear on the website as early as 2003,\
  \ as evidenced in an archived Happycat.ru thread.[1] There are conflicting reports\
  \ on the identity of the cat. Some believe Happy Cat is a British shorthair named\
  \ Frank who was born in 1994 and died in 2007. However, a blog post from corpuscola[7]\
  \ says it is named Misha and was born in 2003. According to Encyclopedia Dramatica[2]\
  \ and Oh Internet[3] articles, the Happy Cat meme began when the image was posted\
  \ to the Something Awful forums in 2003, by user FancyCat. The YTMND Wiki[4] page\
  \ on the subject also points to Something Awful as the birthplace of Happy Cat.\
  \ While there is no record of a user named FancyCat on SomethingAwful, there is\
  \ a \"Fancy Cat\"[5] (two words) who has been a registered user since 2002, but\
  \ their post history is incomplete. One of the earliest verifiable appearances of\
  \ Happy Cat on Something Awful occurred on May 12th, 2004 in an article entitled\
  \ The Grocery Gauntlet[6] written by Reid \"Frolixo\" Paskiewicz. Spread Happy Cat\
  \ grew most notable online through its popularity in various meme templates. LOLcats\
  \ After a caption reading \"I Can Has Cheezburger?\" was superimposed onto the Happy\
  \ Cat image, more images in similar fashion began appearing on the web, launching\
  \ the LOLcats meme and the popular I Can Has Cheezburger website. NEDM NEDM is an\
  \ acronym for \"Not Even Doom Music\", which is used as a catchphrase online. The\
  \ face of Happy Cat is now commonly associated with this phrase. Oh God How Did\
  \ This Get In Here I Am Not Good With Computer Oh God How Did This Get In Here I\
  \ Am Not Good With Computer is a catchphrase derived from an image featuring a poorly\
  \ cropped picture of Happy Cat. This catchphrase is often used as an ironic way\
  \ of informing a user that they are technologically inept. Various Examples Search\
  \ Interest External References [1] Happycat.ru \u2013 Original Thread [2] Encyclopedia\
  \ Dramatica \u2013 Happy Cat [3] Oh Internet (via Wayback Machine) \u2013 Happy\
  \ Cat [4] YTMND \u2013 Happy Cat [5] Something Awful \u2013 Fancy Cat [6] Something\
  \ Awful \u2013 The Grocery Gauntlet [7] Corpuscola Blogspot \u2013 Lurkmore on a\
  \ note Related Entries 211 total Grumpy Cat Nyan Cat Business Cat Smudge the Cat\
  \ Longcat Chonk / Oh Lawd He Comin' Big Floppa Persian Cat Room Guardian Ceiling\
  \ Cat I Should Buy a Boat Cat Chemistry Cat Polite Cat View All Related Entries\
  \ Sub-entries 2 total NEDM Oh God How Did This Get Here I Am Not Good With Computer\
  \ Recent Videos 2 total TFP: Fowler Can Has Cheezburger Happy Cat Uploaded by ImTheGoddamnBatman\
  \ I PAINTED HAPPYCAT Happy Cat Uploaded by Don + Add a Video Recent Images 53 total\
  \ Happy Cat Uploaded by \U0001D4E2\U0001D58E\U0001D593\U0001D586\U0001D58A\U0001D591\
  \ \U0001D4F2\U0001D4FC \U0001D4FD\U0001D4F1\U0001D4EE \U0001D4D2\U0001D4D4\U0001D4DE\
  \ \U0001D4F8\U0001D4EF \U0001D4D7\U0001D4F8\U0001D4FB\U0001D4F7\U0001D502 Happy\
  \ Cat Uploaded by \U0001D4E2\U0001D58E\U0001D593\U0001D586\U0001D58A\U0001D591 \U0001D4F2\
  \U0001D4FC \U0001D4FD\U0001D4F1\U0001D4EE \U0001D4D2\U0001D4D4\U0001D4DE \U0001D4F8\
  \U0001D4EF \U0001D4D7\U0001D4F8\U0001D4FB\U0001D4F7\U0001D502 Happy Cat Uploaded\
  \ by \U0001D4E2\U0001D58E\U0001D593\U0001D586\U0001D58A\U0001D591 \U0001D4F2\U0001D4FC\
  \ \U0001D4FD\U0001D4F1\U0001D4EE \U0001D4D2\U0001D4D4\U0001D4DE \U0001D4F8\U0001D4EF\
  \ \U0001D4D7\U0001D4F8\U0001D4FB\U0001D4F7\U0001D502 Happy Cat Uploaded by \U0001D4E2\
  \U0001D58E\U0001D593\U0001D586\U0001D58A\U0001D591 \U0001D4F2\U0001D4FC \U0001D4FD\
  \U0001D4F1\U0001D4EE \U0001D4D2\U0001D4D4\U0001D4DE \U0001D4F8\U0001D4EF \U0001D4D7\
  \U0001D4F8\U0001D4FB\U0001D4F7\U0001D502 Happy Cat Uploaded by \U0001D4E2\U0001D58E\
  \U0001D593\U0001D586\U0001D58A\U0001D591 \U0001D4F2\U0001D4FC \U0001D4FD\U0001D4F1\
  \U0001D4EE \U0001D4D2\U0001D4D4\U0001D4DE \U0001D4F8\U0001D4EF \U0001D4D7\U0001D4F8\
  \U0001D4FB\U0001D4F7\U0001D502 Happy Cat Uploaded by \U0001D4E2\U0001D58E\U0001D593\
  \U0001D586\U0001D58A\U0001D591 \U0001D4F2\U0001D4FC \U0001D4FD\U0001D4F1\U0001D4EE\
  \ \U0001D4D2\U0001D4D4\U0001D4DE \U0001D4F8\U0001D4EF \U0001D4D7\U0001D4F8\U0001D4FB\
  \U0001D4F7\U0001D502 Happy Cat Uploaded by \U0001D4E2\U0001D58E\U0001D593\U0001D586\
  \U0001D58A\U0001D591 \U0001D4F2\U0001D4FC \U0001D4FD\U0001D4F1\U0001D4EE \U0001D4D2\
  \U0001D4D4\U0001D4DE \U0001D4F8\U0001D4EF \U0001D4D7\U0001D4F8\U0001D4FB\U0001D4F7\
  \U0001D502 Happy Cat Uploaded by \U0001D4E2\U0001D58E\U0001D593\U0001D586\U0001D58A\
  \U0001D591 \U0001D4F2\U0001D4FC \U0001D4FD\U0001D4F1\U0001D4EE \U0001D4D2\U0001D4D4\
  \U0001D4DE \U0001D4F8\U0001D4EF \U0001D4D7\U0001D4F8\U0001D4FB\U0001D4F7\U0001D502\
  \ Happy Cat Uploaded by Fun Police Happy Cat Uploaded by Fun Police Happy Cat Uploaded\
  \ by Fun Police Happy Cat Uploaded by Fun Police + Add an Image View All Images\
  \ Sign up for our Newsletter Top Comments Delete Sensitive \U0001D4E2\U0001D58E\U0001D593\
  \U0001D586\U0001D58A\U0001D591 \U0001D4F2\U0001D4FC \U0001D4FD\U0001D4F1\U0001D4EE\
  \ \U0001D4D2\U0001D4D4\U0001D4DE \U0001D4F8\U0001D4EF \U0001D4D7\U0001D4F8\U0001D4FB\
  \U0001D4F7\U0001D502 Oct 17, 2011 at 06:05PM EDT I will just put it here, in case\
  \ my suggestion for a change somehow wont be approved. The true origin of a Happy\
  \ Cat was revealed thanks to blogspot user Corpuscula (post \u2013 http://corpuscula.blogspot.com/2010/07/blog-post_9590.html)\
  \ and a person nicknamed Julia in that post. Original photo was taken for a year\
  \ 2002 calendar, and looked even funnier, thanks to a \u201Csad cat\u201D next to\
  \ \u201Chappy cat\u201D : (http://4.bp.blogspot.com/m0O2XlVi3Mc/TD8ZbaOdBiI/AAAAAAAACdo/l5D35tDd7L0/s1600/Solomatina11.jpg)\
  \ Happy Cat\u2019s actual name is Mishel. He was born in 15.07.2001 in Russian pet\
  \ center \u201C\u0422\u0443\u043C\u0430\u043D\u043D\u044B\u0439 \u0410\u043B\u044C\
  \u0431\u0438\u043E\u043D\u201D (\u201CFoggy Albion\u201D) in Moscow. (http://www.tumalbion.ru/details.php?aid=3)\
  \ His photos, including the one,used for \u201CCan i haz cheezburger\u201D picture,\
  \ can still be found in sites gallery : http://www.tumalbion.ru/boys/index2.htm.\
  \ There is one particular photo, that proves photos origin: http://www.tumalbion.ru/boys/slides/bigman9.htm\
  \ \u2013 on this picture Mishel is seen lying on the same couch, that is present\
  \ on canonical picture. Unofficial (web 1.0) site with lower quality photos of Mishel\
  \ and that \u201Csad cat\u201D can be found here : http://tumalbion.narod.ru/, along\
  \ with some other photos of cats on the same couch, including low quality group\
  \ photo of Mishel, \u201Csad cat\u201D and two younger kitten (http://tumalbion.narod.ru/solomatina_4.jpg).\
  \ He now lives happily with family that took him in somewhere in Moscow. +5 Reply\
  \ Delete Sensitive Keyboard Cat Jan 29, 2021 at 02:56AM EST Frank needs to make\
  \ a comeback +4 Reply + Add a Comment Comments (26) Display Comments Add a Comment\
  \ Top Entries This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (8) Chris Menning\
  \ Digital Archaeologist & Archivist & Pundit & Early Adopter (#8) Jamie Dubs Scientist\
  \ Emeritus Brad Digital Archaeologist & Treasurer & Pundit & Gallery Housekeeper\
  \ Fun Police Jr. Researcher & Commentator madcat Deactivated Y F Digital Archaeologist\
  \ & Treasurer & Media Maid Adam Know Your Meme Universal Champion andcallmeshirley\
  \ Digital Archaeologist & Treasurer & Collection Butler \u25BC + Request Editorship\
  \ View All Editors Today's Top Image Galleries Assassination of UnitedHealthcare\
  \ CEO Team Fortress 2 Squirrel Girl (Doreen Green) The Amazing Digital Circus About\
  \ Our Story Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes\
  \ News Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/happy-cat
template_id: icanhas
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
