name: I Can Has Cheezburger?
source: http://knowyourmeme.com/memes/happy-cat
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- i can has
- this meme?
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About Happy Cat is the subject of a series of image macros and exploitable
  images, and among the most well-known of LOLcats.. Happy Cat achieved fame via Something
  Awful in 2003, when forum user FancyCat is speculated to have originally posted
  the image. In 2007, a superimposed caption was placed on the image reading "I Can
  Has Cheezburger?" This image spawned both the LOLcats meme and the website I Can
  Has Cheezburger, as well as the NEDM meme. Happy Cat is of the British Shorthair
  breed. Origin The earliest known appearance of Happy Cat on the web comes from a
  Russian cat food company, also called Happy Cat. Although the cat was not the primary
  mascot for the company, it did appear on the website as early as 2003, as evidenced
  in an archived Happycat.ru thread.[1] There are conflicting reports on the identity
  of the cat. Some believe Happy Cat is a British shorthair named Frank who was born
  in 1994 and died in 2007. However, a blog post from corpuscola[7] says it is named
  Misha and was born in 2003. According to Encyclopedia Dramatica[2] and Oh Internet[3]
  articles, the Happy Cat meme began when the image was posted to the Something Awful
  forums in 2003, by user FancyCat. The YTMND Wiki[4] page on the subject also points
  to Something Awful as the birthplace of Happy Cat. While there is no record of a
  user named FancyCat on SomethingAwful, there is a "Fancy Cat"[5] (two words) who
  has been a registered user since 2002, but their post history is incomplete. One
  of the earliest verifiable appearances of Happy Cat on Something Awful occurred
  on May 12th, 2004 in an article entitled The Grocery Gauntlet[6] written by Reid
  "Frolixo" Paskiewicz. Spread Happy Cat grew most notable online through its popularity
  in various meme templates. LOLcats After a caption reading "I Can Has Cheezburger?"
  was superimposed onto the Happy Cat image, more images in similar fashion began
  appearing on the web, launching the LOLcats meme and the popular I Can Has Cheezburger
  website. NEDM NEDM is an acronym for "Not Even Doom Music", which is used as a catchphrase
  online. The face of Happy Cat is now commonly associated with this phrase. Oh God
  How Did This Get In Here I Am Not Good With Computer Oh God How Did This Get In
  Here I Am Not Good With Computer is a catchphrase derived from an image featuring
  a poorly cropped picture of Happy Cat. This catchphrase is often used as an ironic
  way of informing a user that they are technologically inept. Various Examples Search
  Interest External References [1] Happycat.ru – Original Thread [2] Encyclopedia
  Dramatica – Happy Cat [3] Oh Internet (via Wayback Machine) – Happy Cat [4] YTMND
  – Happy Cat [5] Something Awful – Fancy Cat [6] Something Awful – The Grocery Gauntlet
  [7] Corpuscola Blogspot – Lurkmore on a note
aside_content: MemeStatusConfirmedType:AnimalYear2003OriginSomething AwfulTagslolcat,image
  macro,cheezburger,funny,something awful,4chan,ytmnd,mascot,cat,stare,fancycat,i
  can has cheezburger,british shorthairAdditional ReferencesEncyclopedia Dramatica
added_at: '2009-09-09T15:36:41-04:00'
