name: Philosoraptor
source: http://knowyourmeme.com/memes/philosoraptor
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- if the earth is the third planet from the sun
- then isn't every country a third world country?
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Philosoraptor is an advice animal image macro series featuring
  an illustration of a Velociraptor paired with captions depicting the dinosaur as
  being deeply immersed in metaphysical inquiries or unraveling quirky paradoxes.
  Origin On October 8th, 2008, the original illustration of the Philosoraptor was
  released and copyrighted by creator Sam Smith as a T-shirt design for sale on the
  online retailer Lonely Dinosaur[1] (shown below). In an e-mail exchange with Know
  Your Meme, Smith revealed that the idea for "Philosoraptor" image was conceived
  sometime in the early of summer of 2008. The final image wasn''t created until late
  summer and the t-shirts went into production in August and September that year.
  The image itself was a mix of several images of velociraptors I got online, which
  I compressed to one-color images, then mixed together. I took the jaw off of one
  at the mouth, and cut it open to make the mouth look like it was hanging open. The
  claw was based off an image of an eagle talon that I flattened, drew in some bits,
  and moved and enlarged one of them to make the raptor-like claw. The last thing
  I did was nudge the eye slit over to the right like three times, and that pulled
  it all together- really gives him that far-away look. It was inspired by our friend
  Devin, who was a philosophy major and was always hunched over his desk thinking,
  so we called him the philosoraptor. We had never heard of it before at the time,
  but apparently the joke had been made previously on the interwebs. On 4chan On March
  30th, 2007,[3] the earliest known depiction of a Philosoraptor dinosaur was posted
  on YTMND page titled "New species of dinosaur discovered!", featuring a photoshopped
  image of a Velociraptor from the 1993 action film Jurassic Park holding a copy of
  Plato''s complete works (shown below, left). On February 18th, 2009, the earliest
  archived appearance of an image macro featuring the Lonely Dinosaur illustration
  was posted on 4chan /b/ board.[5] Etymology Although "Philosoraptor" (combination
  of Philosopher and velociraptor) appears on the original t-shirt design, the portmanteau
  word has been used elsewhere prior to the release of Lonely Dinosaur merchandises.
  Due to the similar sounds of the two words, it is quite likely that various people
  arrived at the concept of a Philosoraptor independent of one another. One of the
  earliest mentions of "philosoraptor" on the web can be found in a quote by a ten-year-old
  Hope from Kentucky, originally posted via children''s site EnchantedLearning[4]
  on December 28th, 1998: I like the philosoraptor because it spits an acidy type
  of substance in its victims eyes. I saw this dinosaur in the movie Jurassic Park
  and I did a report on it also. This dinosaur is da bomb. "Philosoraptor" has been
  also used as online identities on various occasions, most notably the politics-religion
  blog Philosoraptor,[8] which has been active since March 2003, and a notorious debater
  named "Philosoraptor" on Democratic Underground forums[7]. Spread In November 2009,
  Philosoraptor was added to the Advice Dog "variations" section on Encyclopedia Dramatica.[9]
  On November 26th, an entry for Philosoraptor was created on Urban Dictionary[2]
  (shown below). In December that year, Sam Smith sent an e-mail to inform the Lonely
  Dinosaur staff that was fine with the image being used as a meme: We''re not exactly
  sure who started putting text over it, and far be it from us to try and control
  a meme… We put a creative commons non-commercial license on it, so all your stuff
  is cool and we think what you''re doing is great, but now everyone thinks that the
  shirt we''re selling is just something we cut and pasted off the web, which kind
  of sucks for us. It''d be cool to see if we could put our side of the story out
  there and see if we can find the person who first put text over it, and have a complete
  history of origin of the meme. On October 25th, 2010, the Internet humor blog Smosh[10]
  published a listicle featuring 20 notable Philosoraptor examples. On November 23rd,
  the Internet news blog Mary Sue[11] posted an image gallery highlighting 50 Philosoraptor
  examples. By July 2011, Philosoraptor reached the "God Tier" on Memegenerator[6]
  with over 38,000 instances and 12 different templates. On December 29th, YouTuber
  Chris Schultz published an original pop song featuring lyrics inspired by Philosoraptor
  images (shown below, left). On August 28th, 2012, the animeme YouTube channel uploaded
  several animated versions of Philosoraptor image macros (shown below, right). In
  October 2013, a thread inviting users to post the best Philosoraptor jokes was submitted
  to the discussion site Quora.[12] On March 30th, 2016, the news site Observer[13]
  published an article describing the history of Philosoraptor and several other classic
  internet memes. Notable Examples Search Interest The largest peak in Philosoraptor
  queries began in December of 2008, two months following Smith''s copyright registration.
  External References [1] LonelyDinosaur (via Wayback Machine) – Philosoraptor Shirt
  [2] Urban Dictionary – Philosoraptor [3] YTMND – New species of dinosaur discovered!
  [4] EnchantedLearning – Dinosaur Favorites [5] chanarchive (via Wayback Machine)
  – Philosoraptor [6] MemeGenerator (via Wayback Machine) – Philosoraptor [7] Democratic
  Underground Forum – Search Results for Philosoraptor [8] Blogspot – Philosoraptor
  [9] Encyclopedia Dramatica – Philosoraptor (page unavailable) [10] Smosh (via Wayback
  Machine) – The 20 Wisest Philosoraptor Quotes [11] The Mary Sue – Philosoraptors
  50 Wisest Musings [12] Quora- What are the best philosoraptor jokes [13] Observer
  – The Origin Stories Behind 5 of the Internets Most Popular Memes'
aside_content: MemeStatusConfirmedType:Image MacroYear2008Origin4chanTagsphilosoraptor,raptor,philosophy,4chan,advice
  dog,sam smith,plato,this dinosaur is da bomb,single character image macro,lonely
  dinosaur,chris schultzAdditional ReferencesEncyclopedia DramaticaMeme GeneratorUrban
  Dictionary
added_at: '2009-03-21T02:45:19-04:00'
