example:
- Senior Developer
- Junior Developer
- Put it in the backlog.
- So we can fix it later, right?
- So we can fix it later, right?
keywords:
- null
name: Anakin and Padme Change the World For the Better
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Reddit - Dive into anything Skip to main content Open menu Open\
  \ navigation Go to Reddit Home r/MemeTemplatesOfficial A chip A close button Get\
  \ App Get the Reddit app Log In Log in to Reddit Expand user menu Open settings\
  \ menu Log In / Sign Up Advertise on Reddit Shop Collectible Avatars Go to MemeTemplatesOfficial\
  \ r/MemeTemplatesOfficial r/MemeTemplatesOfficial The biggest subreddit dedicated\
  \ to providing you with the meme templates you're looking for. Post your templates\
  \ or request one instead! Join us on Discord at https://discord.gg/TtR32WT. Members\
  \ Online \u2022 [deleted] ADMIN MOD I\u2019m going to change the world. For the\
  \ better right? Star Wars. Request Top 1% Rank by size Public Anyone can view, post,\
  \ and comment to this community Top Posts Reddit reReddit: Top posts of May 22,\
  \ 2021 Reddit reReddit: Top posts of May 2021 Reddit reReddit: Top posts of 2021\
  \ &nbsp; &nbsp; TOPICS Internet Culture (Viral) Amazing Animals & Pets Cringe &\
  \ Facepalm Funny Interesting Memes Oddly Satisfying Reddit Meta Wholesome & Heartwarming\
  \ Games Action Games Adventure Games Esports Gaming Consoles & Gear Gaming News\
  \ & Discussion Mobile Games Other Games Role-Playing Games Simulation Games Sports\
  \ & Racing Games Strategy Games Tabletop Games Q&As Q&As Stories & Confessions Technology\
  \ 3D Printing Artificial Intelligence & Machine Learning Computers & Hardware Consumer\
  \ Electronics DIY Electronics Programming Software & Apps Streaming Services Tech\
  \ News & Discussion Virtual & Augmented Reality Pop Culture Celebrities Creators\
  \ & Influencers Generations & Nostalgia Podcasts Streamers Tarot & Astrology Movies\
  \ & TV Action Movies & Series Animated Movies & Series Comedy Movies & Series Crime,\
  \ Mystery, & Thriller Movies & Series Documentary Movies & Series Drama Movies &\
  \ Series Fantasy Movies & Series Horror Movies & Series Movie News & Discussion\
  \ Reality TV Romance Movies & Series Sci-Fi Movies & Series Superhero Movies & Series\
  \ TV News & Discussion RESOURCES About Reddit Advertise Help Blog Careers Press\
  \ Communities Best of Reddit Topics Content Policy Privacy Policy User Agreement\
  \ Reddit, Inc. \xA9 2024. All rights reserved."
source: https://www.reddit.com/r/MemeTemplatesOfficial/comments/nia6wu/im_going_to_change_the_world_for_the_better_right/
template_id: right
text:
- align: center
  anchor_x: 0.09
  anchor_y: 0.01
  angle: 0.0
  color: white
  font: thick
  scale_x: 0.25
  scale_y: 0.1
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.65
  anchor_y: 0.01
  angle: 0.0
  color: white
  font: thick
  scale_x: 0.25
  scale_y: 0.1
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.399
  angle: 0.0
  color: white
  font: thin
  scale_x: 0.499
  scale_y: 0.1
  start: 0.2
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.502
  anchor_y: 0.399
  angle: 0.0
  color: khaki
  font: thin
  scale_x: 0.499
  scale_y: 0.1
  start: 0.4
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.502
  anchor_y: 0.9
  angle: 0.0
  color: khaki
  font: thin
  scale_x: 0.499
  scale_y: 0.1
  start: 0.7
  stop: 1.0
  style: default
text_zones: 5
