example:
- After all... why not?
- Why shouldn't I keep it?
keywords:
- Lord of the Rings
- Bilbo Baggins
name: Why Shouldn't I Keep It
overlay:
- angle: 0.0
  center_x: 0.8
  center_y: 0.88
  scale: 0.1
scraped_content: "After All, Why Not? Why Shouldn't I Keep It? | Know Your Meme Hi!\
  \ You must login or signup first! Already a memeber? Login Now! Don't have an account?\
  \ Sign up Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos\
  \ Submit \u2192 Images Trending Most Commented Most Favorited High Score Low Score\
  \ Most Viewed All Templates Upload an Image Articles News Explainers Collections\
  \ Interviews Meme Insider Magazine More Discord Newsletter Episodes Forums Meme\
  \ Store Login Abstract user icon Memes Categories Trending News Images Trending\
  \ Images Videos Trending Videos Editorials Meme Insider Magazine Newsletter Policies\
  \ and Guidelines Meme Store Old site Login Know Your Meme is the property of Literally\
  \ Media \xA92024 Literally Media. All Rights Reserved. This image Of Woman Confidently\
  \ Strolling Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years\
  \ Ago, This Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The\
  \ Anarchy Chess Memes Turns Two Years Old Today Phrase 'The Fridge Protects The\
  \ Snacks' A Growing Favorite Among Pickup Artist Influencers Jamie G, The Bosh British\
  \ Charva, Has Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also\
  \ Trending: Honey Extension Influencer Scam Renegade Raider Copypasta Assassination\
  \ of UnitedHealthcare CEO After All, Why Not? Why Shouldn't I Keep It? Added 3 years\
  \ ago / Updated 3 years ago Confirmed 81,099 Part of a series on Lord Of The Rings.\
  \ [View Related Entries] View All 42 Images Navigation About \u2022 Origin \u2022\
  \ Spread \u2022 Various Examples \u2022 Template \u2022 Search Interest \u2022 External\
  \ References \u2022 Recent Images \u2022 Recent Videos About \"After All, Why Not?\
  \ Why Shouldn't I Keep It?\" is a memorable quote uttered by the character Bilbo\
  \ Baggins in the 2001 fantasy film The Lord of the Rings: The Fellowship of the\
  \ Ring. Online, many use shots from the film of Bilbo saying the line in an image\
  \ macro scene about everyday objects that people borrow but rarely return. Origin\
  \ On December 19th, 2001, New Line Cinema released the film The Lord of the Rings:\
  \ The Fellowship of the Ring.[1] In the film, Bilbo Baggins (portrayed by Ian Holm)\
  \ must relinquish ownership of a dangerous and all-powerful magic ring to his nephew\
  \ Frodo (portrayed by Elijah Woods). Before handing it over to the intermediary,\
  \ the wizard Gandalf the Grey (portrayed by Sir Ian McKellen), he says to the ring,\
  \ \"After all, why not? Why shouldn't I keep it?\" On December 16th, 2013, YouTuber\
  \ Brian Herman shared a clip of the scene. The post received more than 14,000 views\
  \ in less than eight years (shown below). Spread Using the scene as a two-panel\
  \ image macro meme began during the mid-2010s. In these memes, people will either\
  \ add another panel that features a different object for Bilbo to keep or they replace\
  \ the ring with an image of a different object. For example, on May 15th, 2014,\
  \ Imgur [2] user David43 posted a three-panel image that includes a picture of a\
  \ pen and the caption, \"This is how I feel at the end of a day on which I used\
  \ a borrowed pen.\" The post received more than 6,700 views and 5,000 upvotes in\
  \ less than seven years (shown below, left). The next decade saw continued usage\
  \ of the format, including several examples that were shared by thousands of people.\
  \ On April 24th, 2018, Redditor Teegi shared a version about upvotes on Reddit in\
  \ the /r/lotrmemes[3] subreddit. The post received more than 12,000 points (94%\
  \ upvoted) in less than three years (shown below, center). Others used the image\
  \ a reaction image. The following year, on May 5th, 2019, Twitter [4] user @isawken\
  \ posted the image with the caption, \"6 year old me after finding a cool rock on\
  \ the ground.\" The tweet received more than 13,000 likes and 3,000 retweets in\
  \ less than two years (shown below, center). Various Examples Template Search Interest\
  \ External References [1] IMDB \u2013 The Lord of the Rings: The Fellowship of the\
  \ Ring [2] Imgur \u2013 It's a good pen why not [3] Reddit \u2013 /r/lotrmemes [4]\
  \ Twitter \u2013 @isawken bilbo ian holm lord of the rings fellowship of the ring\
  \ lighters Share Pin Related Entries 41 total One Does Not Simply Walk Into... Pondering\
  \ My Orb You Have My Sword, and My Bow... They're Taking the Hobbits to... View\
  \ All Related Entries Recent Images 42 total View All Images Recent Videos 5 total\
  \ View All Videos Sign up for our Newsletter Load 4 Comments Comments 4 total 10\
  \ After All, Why Not? Why Shouldn't I Keep It? 81,100 5 42 4 Part of a series on\
  \ Lord Of The Rings. [View Related Entries] Updated May 18, 2021 at 06:15AM EDT\
  \ by shevyrolet. Added Jan 13, 2021 at 03:40PM EST by Matt. Like us on Facebook!\
  \ Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to\
  \ view the video gallery, or 'r' to view a random entry. Meme Status Confirmed Type:\
  \ Image Macro Year 2013 Origin The Lord of the Rings: The Fellowship of the Ring\
  \ (Film) Tags bilbo, ian holm, lord of the rings, fellowship of the ring, lighters\
  \ Additional References Meme Generator About \"After All, Why Not? Why Shouldn't\
  \ I Keep It?\" is a memorable quote uttered by the character Bilbo Baggins in the\
  \ 2001 fantasy film The Lord of the Rings: The Fellowship of the Ring. Online, many\
  \ use shots from the film of Bilbo saying the line in an image macro scene about\
  \ everyday objects that people borrow but rarely return. Origin On December 19th,\
  \ 2001, New Line Cinema released the film The Lord of the Rings: The Fellowship\
  \ of the Ring.[1] In the film, Bilbo Baggins (portrayed by Ian Holm) must relinquish\
  \ ownership of a dangerous and all-powerful magic ring to his nephew Frodo (portrayed\
  \ by Elijah Woods). Before handing it over to the intermediary, the wizard Gandalf\
  \ the Grey (portrayed by Sir Ian McKellen), he says to the ring, \"After all, why\
  \ not? Why shouldn't I keep it?\" On December 16th, 2013, YouTuber Brian Herman\
  \ shared a clip of the scene. The post received more than 14,000 views in less than\
  \ eight years (shown below). Spread Using the scene as a two-panel image macro meme\
  \ began during the mid-2010s. In these memes, people will either add another panel\
  \ that features a different object for Bilbo to keep or they replace the ring with\
  \ an image of a different object. For example, on May 15th, 2014, Imgur [2] user\
  \ David43 posted a three-panel image that includes a picture of a pen and the caption,\
  \ \"This is how I feel at the end of a day on which I used a borrowed pen.\" The\
  \ post received more than 6,700 views and 5,000 upvotes in less than seven years\
  \ (shown below, left). The next decade saw continued usage of the format, including\
  \ several examples that were shared by thousands of people. On April 24th, 2018,\
  \ Redditor Teegi shared a version about upvotes on Reddit in the /r/lotrmemes[3]\
  \ subreddit. The post received more than 12,000 points (94% upvoted) in less than\
  \ three years (shown below, center). Others used the image a reaction image. The\
  \ following year, on May 5th, 2019, Twitter [4] user @isawken posted the image with\
  \ the caption, \"6 year old me after finding a cool rock on the ground.\" The tweet\
  \ received more than 13,000 likes and 3,000 retweets in less than two years (shown\
  \ below, center). Various Examples Template Search Interest External References\
  \ [1] IMDB \u2013 The Lord of the Rings: The Fellowship of the Ring [2] Imgur \u2013\
  \ It's a good pen why not [3] Reddit \u2013 /r/lotrmemes [4] Twitter \u2013 @isawken\
  \ Related Entries 41 total One Does Not Simply Walk Into Mordor Pondering My Orb\
  \ You Have My Sword, and My Bow, and My Axe They're Taking the Hobbits to Isengard\
  \ You Shall Not Pass!!! All Right Then, Keep Your Secrets Figwit You Have No Power\
  \ Here! What Do Your Elf Eyes See? Gandalf's \"So It Begins\" Viggo Mortensen Broke\
  \ His Toe In 'The Two Towers' #Orcposting View All Related Entries Recent Videos\
  \ 5 total After all, why not? Why shoul... After All, Why Not? Why Shoul... Uploaded\
  \ by shevyrolet Why shouldn't I keep it? After All, Why Not? Why Shoul... Uploaded\
  \ by shevyrolet LOTR The Fellowship of the Ri... After All, Why Not? Why Shoul...\
  \ Uploaded by shevyrolet + Add a Video Recent Images 42 total After All, Why Not?\
  \ Why Shoul... Uploaded by Jaimie Hamilton After All, Why Not? Why Shoul... Uploaded\
  \ by Aidan Walker After All, Why Not? Why Shoul... Uploaded by Reddit Moments After\
  \ All, Why Not? Why Shoul... Uploaded by Reddit Moments After All, Why Not? Why\
  \ Shoul... Uploaded by Reddit Moments After All, Why Not? Why Shoul... Uploaded\
  \ by silenzedFF After All, Why Not? Why Shoul... Uploaded by Trixie Jensen After\
  \ All, Why Not? Why Shoul... Uploaded by Philipp After All, Why Not? Why Shoul...\
  \ Uploaded by shevyrolet After All, Why Not? Why Shoul... Uploaded by Y F After\
  \ All, Why Not? Why Shoul... Uploaded by Y F After All, Why Not? Why Shoul... Uploaded\
  \ by Rebecca Rhodes + Add an Image View All Images Sign up for our Newsletter +\
  \ Add a Comment Comments (4) Display Comments Add a Comment Top Entries This Month\
  \ Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare CEO Person\
  \ Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography Site\
  \ Whisper View More Suggest a Change Edit History Entry Editors (4) Matt Secretary\
  \ of Memes andcallmeshirley Digital Archaeologist & Treasurer & Collection Butler\
  \ Y F Digital Archaeologist & Treasurer & Media Maid shevyrolet Digital Archaeologist\
  \ & Treasurer & Media Bus Boy + Request Editorship View All Editors Today's Top\
  \ Image Galleries Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen Green)\
  \ Team Fortress 2 The Amazing Digital Circus About Our Story Site Rules Policies\
  \ and Guidelines Credits Contact Meme DB Memes Episodes News Staff Contact Extras!\
  \ Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/after-all-why-not-why-shouldnt-i-keep-it
template_id: bilbo
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.4
  angle: 0.0
  color: white
  font: thin
  scale_x: 1.0
  scale_y: 0.1
  start: 0.0
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.0
  anchor_y: 0.9
  angle: 0.0
  color: white
  font: thin
  scale_x: 1.0
  scale_y: 0.1
  start: 0.0
  stop: 1.0
  style: default
text_zones: 2
