name: Why Shouldn't I Keep It
source: https://knowyourmeme.com/memes/after-all-why-not-why-shouldnt-i-keep-it
keywords:
- Lord of the Rings
- Bilbo Baggins
text:
- style: default
  color: white
  font: thin
  anchor_x: 0.0
  anchor_y: 0.4
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.1
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: white
  font: thin
  anchor_x: 0.0
  anchor_y: 0.9
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.1
  align: center
  start: 0.0
  stop: 1.0
example:
- After all... why not?
- Why shouldn't I keep it?
overlay:
- center_x: 0.8
  center_y: 0.88
  angle: 0.0
  scale: 0.1
scraped_content: 'About "After All, Why Not? Why Shouldn''t I Keep It?" is a memorable
  quote uttered by the character Bilbo Baggins in the 2001 fantasy film The Lord of
  the Rings: The Fellowship of the Ring. Online, many use shots from the film of Bilbo
  saying the line in an image macro scene about everyday objects that people borrow
  but rarely return. Origin On December 19th, 2001, New Line Cinema released the film
  The Lord of the Rings: The Fellowship of the Ring.[1] In the film, Bilbo Baggins
  (portrayed by Ian Holm) must relinquish ownership of a dangerous and all-powerful
  magic ring to his nephew Frodo (portrayed by Elijah Woods). Before handing it over
  to the intermediary, the wizard Gandalf the Grey (portrayed by Sir Ian McKellen),
  he says to the ring, "After all, why not? Why shouldn''t I keep it?" On December
  16th, 2013, YouTuber Brian Herman shared a clip of the scene. The post received
  more than 14,000 views in less than eight years (shown below). Spread Using the
  scene as a two-panel image macro meme began during the mid-2010s. In these memes,
  people will either add another panel that features a different object for Bilbo
  to keep or they replace the ring with an image of a different object. For example,
  on May 15th, 2014, Imgur [2] user David43 posted a three-panel image that includes
  a picture of a pen and the caption, "This is how I feel at the end of a day on which
  I used a borrowed pen." The post received more than 6,700 views and 5,000 upvotes
  in less than seven years (shown below, left). The next decade saw continued usage
  of the format, including several examples that were shared by thousands of people.
  On April 24th, 2018, Redditor Teegi shared a version about upvotes on Reddit in
  the /r/lotrmemes[3] subreddit. The post received more than 12,000 points (94% upvoted)
  in less than three years (shown below, center). Others used the image a reaction
  image. The following year, on May 5th, 2019, Twitter [4] user @isawken posted the
  image with the caption, "6 year old me after finding a cool rock on the ground."
  The tweet received more than 13,000 likes and 3,000 retweets in less than two years
  (shown below, center). Various Examples Template Search Interest External References
  [1] IMDB – The Lord of the Rings: The Fellowship of the Ring [2] Imgur – It''s a
  good pen why not [3] Reddit – /r/lotrmemes [4] Twitter – @isawken'
aside_content: 'MemeStatusConfirmedType:Image MacroYear2013OriginThe Lord of the Rings:
  The Fellowship of the Ring (Film)Tagsbilbo,ian holm,lord of the rings,fellowship
  of the ring,lightersAdditional ReferencesMeme Generator'
added_at: '2021-01-13T15:40:33-05:00'
