example:
- memes?
- ain't nobody got time fo' that
keywords:
- Ain't Nobody Got Time For That
name: Sweet Brown
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Sweet Brown / Ain't Nobody Got Time for That | Know Your Meme Word\
  \ Up! You must login or signup first! Already a memeber? Login Now! Don't have an\
  \ account? Sign up Now! Meme Encyclopedia All Cultures Events People Sites Subcultures\
  \ Videos Submit \u2192 Images Trending Most Commented Most Favorited High Score\
  \ Low Score Most Viewed All Templates Upload an Image Articles News Explainers Collections\
  \ Interviews Meme Insider Magazine More Discord Newsletter Episodes Forums Meme\
  \ Store Login Abstract user icon Memes Categories Trending News Images Trending\
  \ Images Videos Trending Videos Editorials Meme Insider Magazine Newsletter Policies\
  \ and Guidelines Meme Store Old site Login Know Your Meme is the property of Literally\
  \ Media \xA92024 Literally Media. All Rights Reserved. This image Of Woman Confidently\
  \ Strolling Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years\
  \ Ago, This Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The\
  \ Anarchy Chess Memes Turns Two Years Old Today Phrase 'The Fridge Protects The\
  \ Snacks' A Growing Favorite Among Pickup Artist Influencers Jamie G, The Bosh British\
  \ Charva, Has Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also\
  \ Trending: Honey Extension Influencer Scam Renegade Raider Copypasta Assassination\
  \ of UnitedHealthcare CEO Sweet Brown / Ain't Nobody Got Time for That Added 12\
  \ years ago / Updated about 16 hours ago Confirmed 2,044,284 Part of a series on\
  \ Viral Videos. [View Related Entries] View All 58 Images Navigation About \u2022\
  \ Origin \u2022 Spread \u2022 External References \u2022 Recent Images \u2022 Recent\
  \ Videos About Sweet Brown is a pseudonym used by Kimberly Wilkins, an Oklahoma\
  \ City resident who was interviewed by local news station KFOR News Channel 4 after\
  \ evacuating from her apartment building that was set on fire. Her emphatic testimony\
  \ of the chaotic scene quickly led to massive exposure on YouTube, similar to those\
  \ of Antoine Dodson and Eccentric Witness Lady. Origin On the morning of April 7th,\
  \ 2012, a three-alarm fire broke out at an Oklahoma City apartment complex in Oklahoma,\
  \ leaving one person hospitalized for smoke inhalation and five units damaged.[2]\
  \ The local station KFOR News Channel 4[1] was among the first to arrive on the\
  \ scene and interview one of the displaced residents Sweet Brown. During the interview,\
  \ she stated that she had woken up to get a \u201Ccold pop\u201D when she thought\
  \ someone was grilling before she realized there was a fire. Brown then proceeded\
  \ to run out of the apartment without shoes. In describing the heavy presence of\
  \ smoke from the fire, she uttered \u201Cain\u2019t nobody got time for that!\u201D\
  \ which became one of the more memorable lines. [This video has been removed] The\
  \ clip was first uploaded to YouTube[4] by KFOR employee Ted Malave on the same\
  \ day, however, another version uploaded by YouTuber lucasmarr[5] on April 9th became\
  \ the most shared version to date, gaining over 1 million views and over 109,000\
  \ Facebook shares[6] within 48 hours. Spread The video was reposted on Tosh.0[8]\
  \ on April 10th and eBaum's World[7] the following day. News sites including Hypervocal[9],\
  \ Long Island Press[10], and WCSH Portland[11], as well as culture sites Hip Hop\
  \ Wired[13], Gawker[14] and Buzzfeed[15] reported on the video between April 10th\
  \ and 11th. On August 23rd, Boston radio station WAAF released a ringtone featuring\
  \ the catchphrase from the interview. Follow-up Interview On April 12th, NBC conducted\
  \ a follow-up interview[3] with both Sweet Brown and her son, who were apparently\
  \ shocked by the amount of YouTube views her original news report had received.\
  \ This interview appeared on MSNBC[12] the same day. On April 13th, lucusmarr, who\
  \ uploaded the original new clip 4 days prior, found Sweet Brown via her son. He\
  \ brought her 4 cases Royal Crown Cola, which Sweet Brown responded \"I really got\
  \ time for this!\" [This video has been removed] Copyright Lawsuit On March 9th,\
  \ 2013, Oklahoman daily newspaper NewsOK reported that Kimberly Wilkins has filed\
  \ a federal copyright infringement lawsuit and a compensation of $15 million against\
  \ Apple Inc., Seattle-based radio program The Bob Rivers Show and a number of other\
  \ parties for unauthorized use of her likeness for commercial purposes. According\
  \ to the article, Wilkins filed her first complaint against \"I Got Bronchitis,\"\
  \ a remix based on audio samples from her KFOR news interview clip (shown below),\
  \ which became available for purchase via Apple's iTunes store in April 2012. While\
  \ the song has been since taken down from iTunes, the suit has since moved to the\
  \ United States District Court for the Western District of Oklahoma and remains\
  \ pending. Notable Remixes External References [1] NewsOK.com \u2013 Three-alarm\
  \ blaze Saturday in Oklahoma City sends apartment resident to hospital [2] KFOR\
  \ News Channel 4 website \u2013 Oklahoma City Apartment Complex Catches Fire [3]\
  \ KJRH news website \u2013 Oklahoma City Woman Sweet Brown Interview Goes Viral\
  \ [4] YouTube \u2013 Sound Bite of the Century \u2013 No time for Bronchitis [5]\
  \ YouTube \u2013 lucasmarr's channel [6] Viral Video Chart \u2013 Sweet Brown: No\
  \ time for bronchitis. [7] eBaum's World \u2013 Woman Interviewed About a Fire [8]\
  \ Tosh.0 \u2013 Sweet Brown's Cold Pop [9] Hypervocal \u2013 Sweet Brown, The Next\
  \ Great Local News Star, Ain\u2019t Got Time for Bronchitis [10] Long Island Press\
  \ \u2013 'Sweet Brown: No Time For Bronchitis\u2019 Video Goes Viral [11] WCSH Portland\
  \ \u2013 Sweet Brown's story of surviving an apartment fire goes viral [12] MSNBC\
  \ \u2013 Sweet Brown: Is she the new Antoine Dodson? (VIDEO) [13] Hip Hop Wired\
  \ \u2013 Oklahoma's Sweet Brown Coming For Antoine Dodson's Internet Crown [VIDEO]\
  \ [14] Gawker \u2013 Three-Alarm Fire Smokes Out Sweet Brown, the Latest Viral Video\
  \ Star [15] Buzzfeed \u2013 Sweet Brown Doesn't Have Time For Bronchitis [16] WAAF\
  \ \u2013 Ringtone: Ain't Nobody Got Time for That [17] Memegenerator \u2013 Ain't\
  \ Nobody Got Time for That newscast apartment fire oklahoma city sweet brown cold\
  \ pop lord jesus it's a fire barbequein bronchitis ain't nobody got time for that\
  \ aint nobody got time for that notables of 2012 people of 2012 mother's day Share\
  \ Pin Related Entries 430 total Honey Badger Hawk Tuah Girl Technoviking Lexi Bonner\
  \ Fighting Kid Footage View All Related Entries Recent Images 58 total View All\
  \ Images Recent Videos 13 total View All Videos Sign up for our Newsletter Load\
  \ 41 Comments Comments 41 total 65 Sweet Brown / Ain't Nobody Got Time for That\
  \ 2,044,284 13 58 41 Part of a series on Viral Videos. [View Related Entries] Updated\
  \ Dec 23, 2024 at 04:14PM EST by LiterallyAustin. Added Apr 09, 2012 at 10:04AM\
  \ EDT by ColtenW. Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press\
  \ 'i' to view the image gallery, 'v' to view the video gallery, or 'r' to view a\
  \ random entry. Meme Status Confirmed Type: Viral Video Year 2012 Origin KFOR News\
  \ Channel 4 (Oklahoma City) Tags newscast, apartment fire, oklahoma city, sweet\
  \ brown, cold pop, lord jesus it's a fire, barbequein, bronchitis, ain't nobody\
  \ got time for that, aint nobody got time for that, notables of 2012, people of\
  \ 2012, mother's day About Sweet Brown is a pseudonym used by Kimberly Wilkins,\
  \ an Oklahoma City resident who was interviewed by local news station KFOR News\
  \ Channel 4 after evacuating from her apartment building that was set on fire. Her\
  \ emphatic testimony of the chaotic scene quickly led to massive exposure on YouTube,\
  \ similar to those of Antoine Dodson and Eccentric Witness Lady. Origin On the morning\
  \ of April 7th, 2012, a three-alarm fire broke out at an Oklahoma City apartment\
  \ complex in Oklahoma, leaving one person hospitalized for smoke inhalation and\
  \ five units damaged.[2] The local station KFOR News Channel 4[1] was among the\
  \ first to arrive on the scene and interview one of the displaced residents Sweet\
  \ Brown. During the interview, she stated that she had woken up to get a \u201C\
  cold pop\u201D when she thought someone was grilling before she realized there was\
  \ a fire. Brown then proceeded to run out of the apartment without shoes. In describing\
  \ the heavy presence of smoke from the fire, she uttered \u201Cain\u2019t nobody\
  \ got time for that!\u201D which became one of the more memorable lines. [This video\
  \ has been removed] The clip was first uploaded to YouTube[4] by KFOR employee Ted\
  \ Malave on the same day, however, another version uploaded by YouTuber lucasmarr[5]\
  \ on April 9th became the most shared version to date, gaining over 1 million views\
  \ and over 109,000 Facebook shares[6] within 48 hours. Spread The video was reposted\
  \ on Tosh.0[8] on April 10th and eBaum's World[7] the following day. News sites\
  \ including Hypervocal[9], Long Island Press[10], and WCSH Portland[11], as well\
  \ as culture sites Hip Hop Wired[13], Gawker[14] and Buzzfeed[15] reported on the\
  \ video between April 10th and 11th. On August 23rd, Boston radio station WAAF released\
  \ a ringtone featuring the catchphrase from the interview. Follow-up Interview On\
  \ April 12th, NBC conducted a follow-up interview[3] with both Sweet Brown and her\
  \ son, who were apparently shocked by the amount of YouTube views her original news\
  \ report had received. This interview appeared on MSNBC[12] the same day. On April\
  \ 13th, lucusmarr, who uploaded the original new clip 4 days prior, found Sweet\
  \ Brown via her son. He brought her 4 cases Royal Crown Cola, which Sweet Brown\
  \ responded \"I really got time for this!\" [This video has been removed] Copyright\
  \ Lawsuit On March 9th, 2013, Oklahoman daily newspaper NewsOK reported that Kimberly\
  \ Wilkins has filed a federal copyright infringement lawsuit and a compensation\
  \ of $15 million against Apple Inc., Seattle-based radio program The Bob Rivers\
  \ Show and a number of other parties for unauthorized use of her likeness for commercial\
  \ purposes. According to the article, Wilkins filed her first complaint against\
  \ \"I Got Bronchitis,\" a remix based on audio samples from her KFOR news interview\
  \ clip (shown below), which became available for purchase via Apple's iTunes store\
  \ in April 2012. While the song has been since taken down from iTunes, the suit\
  \ has since moved to the United States District Court for the Western District of\
  \ Oklahoma and remains pending. Notable Remixes External References [1] NewsOK.com\
  \ \u2013 Three-alarm blaze Saturday in Oklahoma City sends apartment resident to\
  \ hospital [2] KFOR News Channel 4 website \u2013 Oklahoma City Apartment Complex\
  \ Catches Fire [3] KJRH news website \u2013 Oklahoma City Woman Sweet Brown Interview\
  \ Goes Viral [4] YouTube \u2013 Sound Bite of the Century \u2013 No time for Bronchitis\
  \ [5] YouTube \u2013 lucasmarr's channel [6] Viral Video Chart \u2013 Sweet Brown:\
  \ No time for bronchitis. [7] eBaum's World \u2013 Woman Interviewed About a Fire\
  \ [8] Tosh.0 \u2013 Sweet Brown's Cold Pop [9] Hypervocal \u2013 Sweet Brown, The\
  \ Next Great Local News Star, Ain\u2019t Got Time for Bronchitis [10] Long Island\
  \ Press \u2013 'Sweet Brown: No Time For Bronchitis\u2019 Video Goes Viral [11]\
  \ WCSH Portland \u2013 Sweet Brown's story of surviving an apartment fire goes viral\
  \ [12] MSNBC \u2013 Sweet Brown: Is she the new Antoine Dodson? (VIDEO) [13] Hip\
  \ Hop Wired \u2013 Oklahoma's Sweet Brown Coming For Antoine Dodson's Internet Crown\
  \ [VIDEO] [14] Gawker \u2013 Three-Alarm Fire Smokes Out Sweet Brown, the Latest\
  \ Viral Video Star [15] Buzzfeed \u2013 Sweet Brown Doesn't Have Time For Bronchitis\
  \ [16] WAAF \u2013 Ringtone: Ain't Nobody Got Time for That [17] Memegenerator \u2013\
  \ Ain't Nobody Got Time for That Related Entries 430 total Honey Badger Hawk Tuah\
  \ Girl Technoviking Lexi Bonner Fighting Kid Footage Dimitri Finds Out I Like Turtles\
  \ Zangief Kid Double Rainbow Asians in the Library Damn Daniel \"Tunak Tunak Tun\"\
  \ Dance Crazy Frog Brothers View All Related Entries Recent Videos 13 total Posh\
  \ Brown Sweet Brown / Ain't Nobody Go... Uploaded by Baron Hawk Skai Jackson as\
  \ Sweet Brown Sweet Brown / Ain't Nobody Go... Uploaded by Emper0rH0rde Sweet Brown\
  \ Has Time Brian Lo... Sweet Brown / Ain't Nobody Go... Uploaded by amanda b. Sweet\
  \ Brown: Toothache? Ain't... Sweet Brown / Ain't Nobody Go... Uploaded by Brad Sweet\
  \ Brown: Toothache? Ain't... Sweet Brown / Ain't Nobody Go... Uploaded by Don Sweet\
  \ Brown - Original Report... Sweet Brown / Ain't Nobody Go... Uploaded by Brad Sweet\
  \ Brown - Ain't Nobody Go... Sweet Brown / Ain't Nobody Go... Uploaded by Don Sweet\
  \ Brown - DETROIT REMIX [... Sweet Brown / Ain't Nobody Go... Uploaded by WTFBrahh\
  \ + Add a Video View All Videos Recent Images 58 total Sweet Brown / Ain't Nobody\
  \ Go... Uploaded by Jaimie Hamilton Sweet Brown / Ain't Nobody Go... Uploaded by\
  \ Reddit Moments Sweet Brown / Ain't Nobody Go... Uploaded by Serialkillerwhale\
  \ Sweet Brown / Ain't Nobody Go... Uploaded by Tysonist Sweet Brown / Ain't Nobody\
  \ Go... Uploaded by a n g e r e y Sweet Brown / Ain't Nobody Go... Uploaded by giogiosbizarre\
  \ Sweet Brown / Ain't Nobody Go... Uploaded by Victor George Sweet Brown / Ain't\
  \ Nobody Go... Uploaded by Chickadee-dee Sweet Brown / Ain't Nobody Go... Uploaded\
  \ by anthropocene man Sweet Brown / Ain't Nobody Go... Uploaded by Daniel Schutzsmith\
  \ Sweet Brown / Ain't Nobody Go... Uploaded by Edward Elric Sweet Brown / Ain't\
  \ Nobody Go... Uploaded by Dell Conagher + Add an Image View All Images Sign up\
  \ for our Newsletter Top Comments Delete Sensitive gridbug Apr 13, 2012 at 01:44AM\
  \ EDT +1 because I laughed my ass off. Godspeed! +16 Reply Delete Sensitive Lexicanium\
  \ Coeus Mar 31, 2017 at 12:46PM EDT Can someone check if this is legitimate? +7\
  \ Reply + Add a Comment Comments (41) Display Comments Add a Comment Top Entries\
  \ This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (8) ColtenW\
  \ Teh Brawler Webcomicologist & Twitterologist Don Administrator & Meme Daddy amanda\
  \ b. Meme Librarian Brad Digital Archaeologist & Treasurer & Pundit & Gallery Housekeeper\
  \ pug on toast Deactivated Twenty-One Anime Anthropologist & Protip Advisor & LGBT\
  \ Community Expert SabrinaTibbetts Memepuff \u25BC + Request Editorship View All\
  \ Editors Today's Top Image Galleries Assassination of UnitedHealthcare CEO Team\
  \ Fortress 2 Squirrel Girl (Doreen Green) The Amazing Digital Circus About Our Story\
  \ Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes News\
  \ Staff Contact Extras! Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/sweet-brown-aint-nobody-got-time-for-that
template_id: aint-got-time
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
