name: Sweet Brown
source: https://knowyourmeme.com/memes/sweet-brown-aint-nobody-got-time-for-that
keywords:
- Ain't Nobody Got Time For That
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- memes?
- ain't nobody got time fo' that
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Sweet Brown is a pseudonym used by Kimberly Wilkins, an Oklahoma
  City resident who was interviewed by local news station KFOR News Channel 4 after
  evacuating from her apartment building that was set on fire. Her emphatic testimony
  of the chaotic scene quickly led to massive exposure on YouTube, similar to those
  of Antoine Dodson and Eccentric Witness Lady. Origin On the morning of April 7th,
  2012, a three-alarm fire broke out at an Oklahoma City apartment complex in Oklahoma,
  leaving one person hospitalized for smoke inhalation and five units damaged.[2]
  The local station KFOR News Channel 4[1] was among the first to arrive on the scene
  and interview one of the displaced residents Sweet Brown. During the interview,
  she stated that she had woken up to get a “cold pop” when she thought someone was
  grilling before she realized there was a fire. Brown then proceeded to run out of
  the apartment without shoes. In describing the heavy presence of smoke from the
  fire, she uttered “ain’t nobody got time for that!” which became one of the more
  memorable lines. [This video has been removed] The clip was first uploaded to YouTube[4]
  by KFOR employee Ted Malave on the same day, however, another version uploaded by
  YouTuber lucasmarr[5] on April 9th became the most shared version to date, gaining
  over 1 million views and over 109,000 Facebook shares[6] within 48 hours. Spread
  The video was reposted on Tosh.0[8] on April 10th and eBaum''s World[7] the following
  day. News sites including Hypervocal[9], Long Island Press[10], and WCSH Portland[11],
  as well as culture sites Hip Hop Wired[13], Gawker[14] and Buzzfeed[15] reported
  on the video between April 10th and 11th. On August 23rd, Boston radio station WAAF
  released a ringtone featuring the catchphrase from the interview. Follow-up Interview
  On April 12th, NBC conducted a follow-up interview[3] with both Sweet Brown and
  her son, who were apparently shocked by the amount of YouTube views her original
  news report had received. This interview appeared on MSNBC[12] the same day. On
  April 13th, lucusmarr, who uploaded the original new clip 4 days prior, found Sweet
  Brown via her son. He brought her 4 cases Royal Crown Cola, which Sweet Brown responded
  "I really got time for this!" [This video has been removed] Copyright Lawsuit On
  March 9th, 2013, Oklahoman daily newspaper NewsOK reported that Kimberly Wilkins
  has filed a federal copyright infringement lawsuit and a compensation of $15 million
  against Apple Inc., Seattle-based radio program The Bob Rivers Show and a number
  of other parties for unauthorized use of her likeness for commercial purposes. According
  to the article, Wilkins filed her first complaint against "I Got Bronchitis," a
  remix based on audio samples from her KFOR news interview clip (shown below), which
  became available for purchase via Apple''s iTunes store in April 2012. While the
  song has been since taken down from iTunes, the suit has since moved to the United
  States District Court for the Western District of Oklahoma and remains pending.
  Notable Remixes External References [1] NewsOK.com – Three-alarm blaze Saturday
  in Oklahoma City sends apartment resident to hospital [2] KFOR News Channel 4 website
  – Oklahoma City Apartment Complex Catches Fire [3] KJRH news website – Oklahoma
  City Woman Sweet Brown Interview Goes Viral [4] YouTube – Sound Bite of the Century
  – No time for Bronchitis [5] YouTube – lucasmarr''s channel [6] Viral Video Chart
  – Sweet Brown: No time for bronchitis. [7] eBaum''s World – Woman Interviewed About
  a Fire [8] Tosh.0 – Sweet Brown''s Cold Pop [9] Hypervocal – Sweet Brown, The Next
  Great Local News Star, Ain’t Got Time for Bronchitis [10] Long Island Press – ''Sweet
  Brown: No Time For Bronchitis’ Video Goes Viral [11] WCSH Portland – Sweet Brown''s
  story of surviving an apartment fire goes viral [12] MSNBC – Sweet Brown: Is she
  the new Antoine Dodson? (VIDEO) [13] Hip Hop Wired – Oklahoma''s Sweet Brown Coming
  For Antoine Dodson''s Internet Crown [VIDEO] [14] Gawker – Three-Alarm Fire Smokes
  Out Sweet Brown, the Latest Viral Video Star [15] Buzzfeed – Sweet Brown Doesn''t
  Have Time For Bronchitis [16] WAAF – Ringtone: Ain''t Nobody Got Time for That [17]
  Memegenerator – Ain''t Nobody Got Time for That'
aside_content: MemeStatusConfirmedType:Viral VideoYear2012OriginKFOR News Channel
  4 (Oklahoma City)Tagsnewscast,apartment fire,oklahoma city,sweet brown,cold pop,lord
  jesus it's a fire,barbequein,bronchitis,ain't nobody got time for that,aint nobody
  got time for that,notables of 2012,people of 2012,mother's day
added_at: '2012-04-09T10:04:14-04:00'
