name: Member Berries
source: http://knowyourmeme.com/memes/member-berries
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- '''member'
- star wars?
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About Member Berries are a fictional superfruit that utter nostalgic,
  homophobic and racist phrases to people while they are being eaten in Season 20
  Episode 1 of the animated television series South Park. Origin On September 14th,
  2016, Comedy Central aired the South Park episode titled "Member Berries," in which
  the character Randy Marsh is shown eating talking purple berries mention various
  nostalgic pop culture icons, before asking if he could remember times when there
  were fewer Mexicans around, gay marriage was illegal and Ronald Reagan's presidency
  (shown below). Spread That day, the @MemberBerries[3] Twitter feed was launched,
  featuring tweets written from the perspective of the fictional purple berries. Also
  on September 14th, a Facebook[4] page titled "Member Berries" was launched, garnering
  upwards of 2,700 likes over the next two months. The following day, a page titled
  "Member Berries" was created on the South Park Wiki.[10] On September 16th, Urban
  Dictionary[2] user isblueacolor submitted an entry for "member berries," defining
  them as "tasty morsels of organic nostalgia." That day, a GIF of the South Park
  scene was uploaded to 9GAG[1] (shown below). Also on September 16th, Tumblr user
  TheMeghaMind posted a photograph of an Old Orchard for Kids grape juice bottle with
  smiling purple grapes with the caption "Member berries IRL" (shown below, left).
  On September 17th, the Memesallovertheplace Tumblr[6] feed posted a screen capture
  of the berries with the caption "'Member / Harambe" (shown below). On September
  26th, Redditor joegofett posted a member berries image macro with the caption "member
  when / Southparkstudios had all the episodes for free" to /r/southpark,[9] where
  it gathered more than 8,500 votes (87% upvoted) and 890 comments within one month
  (shown below, left). On October 1st, a "Member Berries" message board was created
  on GameFAQs.[5] On October 8th, Tumblr[8] user dirty-south-park-confessions posted
  a photoshopped screen capture from the 1994 animated film The Lion King while a
  member berry superimposed over the lion Mufasa and the caption "Member who you are,
  Simba" (shown below, right). Search Interest External References [1] 9gag – Could
  memberberries be a new meme? [2] Urban Dictionary – member berries [3] Twitter –
  @MemberBerries [4] Facebook – Member Berries [5] GameFAQs – Member Berries [6] Tumblr
  – memesallovertheplace [7] Tumblr – meghamind [8] Tumblr – dirty-south-park-confessions
  [9] Reddit – member berries [10] South Park Wiki – Member Berries
aside_content: MemeStatusConfirmedType:CharacterYear2016OriginSouth ParkTagssouth
  park,nostalgia,politics,ronald reagan,member berries meme
added_at: '2016-10-24T15:55:47-04:00'
