example:
- '''member'
- star wars?
keywords:
- null
name: Member Berries
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Member Berries | Know Your Meme Hey! You must login or signup first!\
  \ Already a memeber? Login Now! Don't have an account? Sign up Now! Meme Encyclopedia\
  \ All Cultures Events People Sites Subcultures Videos Submit \u2192 Images Trending\
  \ Most Commented Most Favorited High Score Low Score Most Viewed All Templates Upload\
  \ an Image Articles News Explainers Collections Interviews Meme Insider Magazine\
  \ More Discord Newsletter Episodes Forums Meme Store Login Abstract user icon Memes\
  \ Categories Trending News Images Trending Images Videos Trending Videos Editorials\
  \ Meme Insider Magazine Newsletter Policies and Guidelines Meme Store Old site Login\
  \ Know Your Meme is the property of Literally Media \xA92024 Literally Media. All\
  \ Rights Reserved. This image Of Woman Confidently Strolling Through A Glass Panel\
  \ Has Been A Redraw Format Since 2021 Three Years Ago, This Boar's Head 'Exploded'\
  \ Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess Memes Turns Two Years\
  \ Old Today Phrase 'The Fridge Protects The Snacks' A Growing Favorite Among Pickup\
  \ Artist Influencers Jamie G, The Bosh British Charva, Has Taken Over TikTok With\
  \ His Signature 'Oh Cherie Amour' Sound Also Trending: Honey Extension Influencer\
  \ Scam Renegade Raider Copypasta Assassination of UnitedHealthcare CEO Member Berries\
  \ Added 8 years ago / Updated 8 days ago Confirmed 136,698 Part of a series on South\
  \ Park. [View Related Entries] View All 10 Images Navigation About \u2022 Origin\
  \ \u2022 Spread \u2022 Search Interest \u2022 External References \u2022 Recent\
  \ Images \u2022 Recent Videos About Member Berries are a fictional superfruit that\
  \ utter nostalgic, homophobic and racist phrases to people while they are being\
  \ eaten in Season 20 Episode 1 of the animated television series South Park. Origin\
  \ On September 14th, 2016, Comedy Central aired the South Park episode titled \"\
  Member Berries,\" in which the character Randy Marsh is shown eating talking purple\
  \ berries mention various nostalgic pop culture icons, before asking if he could\
  \ remember times when there were fewer Mexicans around, gay marriage was illegal\
  \ and Ronald Reagan's presidency (shown below). Spread That day, the @MemberBerries[3]\
  \ Twitter feed was launched, featuring tweets written from the perspective of the\
  \ fictional purple berries. Also on September 14th, a Facebook[4] page titled \"\
  Member Berries\" was launched, garnering upwards of 2,700 likes over the next two\
  \ months. The following day, a page titled \"Member Berries\" was created on the\
  \ South Park Wiki.[10] On September 16th, Urban Dictionary[2] user isblueacolor\
  \ submitted an entry for \"member berries,\" defining them as \"tasty morsels of\
  \ organic nostalgia.\" That day, a GIF of the South Park scene was uploaded to 9GAG[1]\
  \ (shown below). Also on September 16th, Tumblr user TheMeghaMind posted a photograph\
  \ of an Old Orchard for Kids grape juice bottle with smiling purple grapes with\
  \ the caption \"Member berries IRL\" (shown below, left). On September 17th, the\
  \ Memesallovertheplace Tumblr[6] feed posted a screen capture of the berries with\
  \ the caption \"'Member / Harambe\" (shown below). On September 26th, Redditor joegofett\
  \ posted a member berries image macro with the caption \"member when / Southparkstudios\
  \ had all the episodes for free\" to /r/southpark,[9] where it gathered more than\
  \ 8,500 votes (87% upvoted) and 890 comments within one month (shown below, left).\
  \ On October 1st, a \"Member Berries\" message board was created on GameFAQs.[5]\
  \ On October 8th, Tumblr[8] user dirty-south-park-confessions posted a photoshopped\
  \ screen capture from the 1994 animated film The Lion King while a member berry\
  \ superimposed over the lion Mufasa and the caption \"Member who you are, Simba\"\
  \ (shown below, right). Search Interest External References [1] 9gag \u2013 Could\
  \ memberberries be a new meme? [2] Urban Dictionary \u2013 member berries [3] Twitter\
  \ \u2013 @MemberBerries [4] Facebook \u2013 Member Berries [5] GameFAQs \u2013 Member\
  \ Berries [6] Tumblr \u2013 memesallovertheplace [7] Tumblr \u2013 meghamind [8]\
  \ Tumblr \u2013 dirty-south-park-confessions [9] Reddit \u2013 member berries [10]\
  \ South Park Wiki \u2013 Member Berries south park nostalgia politics ronald reagan\
  \ member berries meme Share Pin Related Entries 22 total Tree Fiddy ???? PROFIT!!!!\
  \ Super Cool Ski Instructor And It's Gone View All Related Entries Recent Images\
  \ 10 total View All Images Recent Videos 2 total View All Videos Sign up for our\
  \ Newsletter Load 81 Comments Comments 81 total 15 Member Berries 136,698 2 10 81\
  \ Part of a series on South Park. [View Related Entries] Updated Dec 15, 2024 at\
  \ 07:21PM EST by LiterallyAustin. Added Oct 24, 2016 at 03:55PM EDT by Don. Like\
  \ us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the image\
  \ gallery, 'v' to view the video gallery, or 'r' to view a random entry. Meme Status\
  \ Confirmed Type: Character Year 2016 Origin South Park Tags south park, nostalgia,\
  \ politics, ronald reagan, member berries meme About Member Berries are a fictional\
  \ superfruit that utter nostalgic, homophobic and racist phrases to people while\
  \ they are being eaten in Season 20 Episode 1 of the animated television series\
  \ South Park. Origin On September 14th, 2016, Comedy Central aired the South Park\
  \ episode titled \"Member Berries,\" in which the character Randy Marsh is shown\
  \ eating talking purple berries mention various nostalgic pop culture icons, before\
  \ asking if he could remember times when there were fewer Mexicans around, gay marriage\
  \ was illegal and Ronald Reagan's presidency (shown below). Spread That day, the\
  \ @MemberBerries[3] Twitter feed was launched, featuring tweets written from the\
  \ perspective of the fictional purple berries. Also on September 14th, a Facebook[4]\
  \ page titled \"Member Berries\" was launched, garnering upwards of 2,700 likes\
  \ over the next two months. The following day, a page titled \"Member Berries\"\
  \ was created on the South Park Wiki.[10] On September 16th, Urban Dictionary[2]\
  \ user isblueacolor submitted an entry for \"member berries,\" defining them as\
  \ \"tasty morsels of organic nostalgia.\" That day, a GIF of the South Park scene\
  \ was uploaded to 9GAG[1] (shown below). Also on September 16th, Tumblr user TheMeghaMind\
  \ posted a photograph of an Old Orchard for Kids grape juice bottle with smiling\
  \ purple grapes with the caption \"Member berries IRL\" (shown below, left). On\
  \ September 17th, the Memesallovertheplace Tumblr[6] feed posted a screen capture\
  \ of the berries with the caption \"'Member / Harambe\" (shown below). On September\
  \ 26th, Redditor joegofett posted a member berries image macro with the caption\
  \ \"member when / Southparkstudios had all the episodes for free\" to /r/southpark,[9]\
  \ where it gathered more than 8,500 votes (87% upvoted) and 890 comments within\
  \ one month (shown below, left). On October 1st, a \"Member Berries\" message board\
  \ was created on GameFAQs.[5] On October 8th, Tumblr[8] user dirty-south-park-confessions\
  \ posted a photoshopped screen capture from the 1994 animated film The Lion King\
  \ while a member berry superimposed over the lion Mufasa and the caption \"Member\
  \ who you are, Simba\" (shown below, right). Search Interest External References\
  \ [1] 9gag \u2013 Could memberberries be a new meme? [2] Urban Dictionary \u2013\
  \ member berries [3] Twitter \u2013 @MemberBerries [4] Facebook \u2013 Member Berries\
  \ [5] GameFAQs \u2013 Member Berries [6] Tumblr \u2013 memesallovertheplace [7]\
  \ Tumblr \u2013 meghamind [8] Tumblr \u2013 dirty-south-park-confessions [9] Reddit\
  \ \u2013 member berries [10] South Park Wiki \u2013 Member Berries Related Entries\
  \ 22 total Tree Fiddy ???? PROFIT!!!! Super Cool Ski Instructor And It's Gone They\
  \ Took Our Jobs! Captain Hindsight Oh, I'm Sorry, I Thought This Was America Everybody\
  \ Draw Mohammed Day PC Bro I Didn't Hear No Bell South Park Transgender Athletes\
  \ Episode Controversy My Name Is Craig Tucker Copypasta View All Related Entries\
  \ Recent Videos 2 total Morpheus The Member Berry Member Berries Uploaded by Christian\
  \ Frates + Add a Video Recent Images 10 total Member Berries Uploaded by Dankasaurus\
  \ Rekt Member Berries Uploaded by The Doctor of Wumbology Member Berries Uploaded\
  \ by Gabenus Trollucus Member Berries Uploaded by cgoodness13 Member Berries Uploaded\
  \ by Paper Jam Dipper Member Berries Uploaded by CuvisTheConqueror Member Berries\
  \ Uploaded by Don Member Berries Uploaded by Don Member Berries Uploaded by Don\
  \ Member Berries Uploaded by Don + Add an Image Sign up for our Newsletter Top Comments\
  \ Delete Sensitive Nightfury Treann Oct 24, 2016 at 05:32PM EDT Member the Knowyourmeme\
  \ episodes?! +104 Reply Delete Sensitive pinkiespy - goat spy Oct 24, 2016 at 04:22PM\
  \ EDT Member Cringeworthy? +53 Reply + Add a Comment Comments (81) Display Comments\
  \ Add a Comment Top Entries This Month Meme Saika Kawakita Smile GIF Event Assassination\
  \ of UnitedHealthcare CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki\
  \ Sisters Culture Pornography Site Whisper View More Suggest a Change Edit History\
  \ Entry Editors (5) Don Administrator & Meme Daddy Y F Digital Archaeologist & Treasurer\
  \ & Media Maid Sophie Digital Archaeologist & Treasurer & Media Bus Boy 3kole5 Sr.\
  \ Entry Moderator Zach Memenator \u25BC + Request Editorship View All Editors Today's\
  \ Top Image Galleries Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen\
  \ Green) Team Fortress 2 The Amazing Digital Circus About Our Story Site Rules Policies\
  \ and Guidelines Credits Contact Meme DB Memes Episodes News Staff Contact Extras!\
  \ Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/member-berries
template_id: mb
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
