name: Scumbag Steve
source: http://knowyourmeme.com/memes/scumbag-steve
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- needs a place to crash
- never leaves
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Scumbag Steve Scumbag Steve is an advice animal character
  based on a photograph of a youth dressed in baggy clothes with a sideways fitted
  cap and standing in a hallway. As the name suggests, the image macros portray the
  character as an opportunistic and freeloading juvenile who wreak havoc in various
  social situations. Origin The original image came from the cover of the album "Ma
  Gangsta"[1] by the rap group Beantown Mafia.[2] The first known image macros were
  posted in a compilation to Reddit[3] in a thread that reached the front page on
  January 21st, 2011 and received 8,607 up votes prior to being archived. A commenter
  in the Reddit thread identified the young man in the photo as Blake Boston, also
  known as "Weezy B." In an interview with Know Your Meme, Blake revealed that the
  picture was originally taken by his mother. Spread The scumbagsteve.com[13] domain
  was registered on January 27th, 2011. A compilation of Scumbag Steve images were
  posted to BuzzFeed[14] on February 2nd, 2011. The Daily Mail[15] posted an article
  about Blake Boston''s reaction to becoming Internet famous on February 11th. A Facebook[16]
  fan page has 13,953 likes, a Quickmeme[20] page has 73,815 submissions and a Meme
  Generator[21] page has 153,149 submissions as of April 6th, 2012. Other derivatives
  can be found on Tumblr[17], Memebase[18] and Funny Junk.[19] Notable Examples The
  meme was particularly well received by Reddit''s /r/trees subreddit, leading to
  creation of many image macros with references to smoking etiquettes and commonly
  shared experiences under the influence of cannabis. Blake later confirmed his appreciation
  of the marijuana enthusiast subreddit, /trees. Derivatives A number of notable spin-off
  instances surfaced on Reddit, many of them influenced by the Dogfort saga as well
  as current news, such as the oh-so-funny "Mubarak Steve" satirizing the Egyptian
  president''s ill-advised decision to shut off the nation''s internet access for
  days in late January 2011. Scumbag Hat Hundreds of image macros have since emerged
  featuring Scumbag Steve''s trademark hat photoshopped onto other people and objects
  accompanied by Scumbag Steve style captions. The hat is a New Era Red Sox ''A-TOOTH''
  brown fitted hat. A similar style with slightly different colors can be found at
  the Hatland website.[6] Scumbag Brain The first Scumbag Brain derivative was posted
  to Reddit on March 24th, 2011. It featured an image of a human brain with text describing
  frustrating lapses in judgement or memory. On July 17th, 2011, a Quickmeme[7] page
  was created for "Scumbag Brain". There are currently over 400 submissions to the
  Quickmeme page as of August 11th, 2011. Identity & Presence Blake created the Twitter
  account @blakeboston617[4] on Jan 31st, 2011 and created the Tumblr "The Real Scumbag
  Steve" on February 7th, 2011. On March 6th, 2011, Blake Boston appeared in a video
  interview with Boston-based indie comedy improv company RoughDraft.TV[5], sharing
  his thoughts on the character of Scumbag Steve, how his MySpace picture from High
  School made its way to memedom as well as his first impression of Reddit and other
  online hubsites. "I have no regrets in my life …no matter what I do. I can completely
  fuck up on something and I still don''t regret it. Because at the end of the day,
  that makes me who I am, so I wouldn''t go back and erase anything, if I were to
  go back in time." Photos of Blake in real life posing with various fans have appeared
  on both Reddit[9][10] and FunnyJunk.[8][10] Open Letter On December 21st, 2011,
  Slacktory[22] editor Nick Douglas published an open letter from Blake Boston to
  the Annoying Facebook Girl in which he gives advice about how to deal with unintended
  Internet fame. Dear Annoying Facebook Girl, it’s me Blake. You may know me as Scumbag
  Steve. Or not, if you’re not on the internet much. I heard you just found out that
  your pics been all over the internet. Shocking huh? Google yourself, but have a
  friend with you for support. Feeling violated? Don’t. You see, like me, your picture
  was used as a meme. What the fuck, you may ask, is a meme? Well basically it’s you
  and others in image macro form, that represent a thought, behavior, style or idea
  that spreads from person to person within a culture. Waaah? Let me say it again.
  It’s one random picture, with various sayings on it, that tells a whole story, in
  really short form, for the world to see, it gets put on the internet and it spreads.
  Goes viral, like the worst case of herpes known to man. But before you feel like
  you’re going to jump, you need to know that it’s going to be OK. Now don’t have
  your folks look for a meme support group for you, cuz there isn’t one. We’re out
  here by ourselves. You may feel hurt and embarrassed that somehow one of your friends
  or foes took that godawful picture of you (we know you really don’t look like that
  all the time, right?) and put it where the internet meme makers dwell. 4chan. Don’t
  go there, especially if your parents are looking. You see, that pic resonated with
  people. It spoke of a crazy excited girl telling Facebook friends inane shit. It
  could have been any girl, there’s a million pics just like yours on Facebook. But
  it happened to be yours. Now, if you do see a pic of me, try not to go all wifey
  on me but (scumbag joke, these memes can get inside your head) that too was a pic
  of me a little younger, looking like a scumbag. Let’s face it. The pics look pretty
  true to form. But here’s what I need you to know. When you go off to college, and
  you’re walking down the hall and a group of kids see you and scream, “Oh my god
  it’s Annoying Facebook Girl,” don’t cry. You see. Some people can’t distinguish
  the internet from real life. There are people who refuse to believe my name isn’t
  Steve and that I am not really the scumbag (well not all the time, that is). Just
  remember who you are. And that you know you’re a decent kid. You’re going to be
  in shock for a while, when you see what people have written. But the most important
  and self-preserving thing you can do is know that it’s not you. You can’t take this
  personally. I’ll say that again, you can’t take this personally. Hell if I did…
  well let’s not go there. The part that will suck though is that there will always
  be those people that somehow think YOU did this, that you made the meme, and that
  you could stop it if you wanted to. That you have some control over it. You don’t.
  The internet birthed you and they’ll decide when you (the meme) will die. There
  will also be those people who assuage their guilt by telling you how great it is,
  how lucky you are to be a meme. Just smile. What they are really saying is, thank
  god it wasn’t me. So search Annoying Facebook Girl on Google images, pull up a chair
  with a group of your friends and laugh your fucking ass off. Cuz you know who you
  are and how strong you are and that, that picture has nothing to do with what makes
  you, you… Hopefully you’ll get to where I am, feeling like some memes are hysterical.
  But that takes time. I’m here if you need me. I’m sorry you’re hurting, -- Blake,
  a.k.a. Scumbag Steve Rap Career On January 20th, 2012, Blake was interviewed by
  the hip hop music blog Tech N9ne[23] and revealed that while he still wants to make
  music, he was placing his rap career on hold due to "personal issues." However,
  on May 3rd, 2012, Boston released his first video "Scumbag Steve Overture" via YouTube.
  He also announced a series called Scumbag Thursdays[24], releasing a song and video
  weekly. In the first day, the video garnered more than 1.2 million views and 20,000
  likes. The video was immediately shared on Reddit[25], where it received 41,765
  up votes and 2250 points overall. The video was also featured on Mashable[27], Slate[28]
  and Geekosystem.[29] The next day, Boston did a video interview with the Daily Dot[26]
  about his rap persona and the future of his videos. [This video has been removed]
  Search Interest External References [1] Myspace – Ma Gangsta [2] Myspace – Beantown
  Mafia [3] Reddit – I hated this dude 1/20/2011 [4] Twitter – @blakeboston617 [5]
  RoughtDraft TV [6] Hatland – Red Sox A-TOOTH Brown-Wheat Fitted Hats by New Era
  [7] Quickmeme – Scumbag Brain [8] FunnyJunk – I saw scumbag steve IRL [9] Reddit
  – I finally met him in person tonight at the HallowMEME party in NYC…folks, the
  real Scumbag Steve! [10] Reddit – Look Who I ran into at the bar [11] Tumblr via
  Wayback Machine – Blake Boston aka Scumbag Steve [12] Urlesque (via Wayback Machine)
  – Scumbag Steve Told Me to F*** Off – Rapper Blake Boston Hates and Loves and Hates
  Becoming a Meme [13] BuzzFeed – The Best of Scumbag Steve [14] ScumbagSteve.com
  – Scumbag Steve Meme Generator [15] The Daily Mail – Who is Scumbag Steve? Internet
  teenage hate figure reveals infamous picture was taken by his mother [16] Facebook
  – Scumbag Steve [17] Tumblr – #scumbag steve [18] Memebase – Scumbag Steve [19]
  Funny Junk – scumbag steve (login needed) [20] Quickmeme – Scumbag Steve [21] Meme
  Generator – Scumbag Steve [22] Slacktory via Wayback Machine – Scumbag Steve’s Advice
  for Annoying Facebook Girl [23] Tech N9ne – From Scumbag To Superstar – Scumbag
  Steve Talks Tech N9ne, Hip Hop, And More [24] Scumbag Thursdays [25] Reddit – Scumbag
  Steve himself just posted this song and holy shit [26] the Daily Dot – Scumbag Steve
  Speaks: "Everybody does pull scumbag moves" [27] Mashable – Scumbag Steve: How the
  Internet Meme Became a Rapper [28] Slate – The Story of Scumbag Steve, or What Happens
  to Memes When They Become Self Aware? [29] The Mary Sue (formerly geekosystem) –
  Scumbag Steve Puts Out A Rap Ode To Himself [Video]'
aside_content: MemeStatusConfirmedType:Character,Image MacroYear2011OriginRedditTags4chan
  image macro,best of 2011,roflcon iii,scumbag,advice animal,social stereotype,blake
  boston,scumbag hat,weezy b.Additional ReferencesEncyclopedia DramaticaFacebookMeme
  GeneratorRedditTwitterUrban DictionaryWikipedia
added_at: '2011-01-18T17:00:09-05:00'
