example:
- do the laundry they said
- it will be fun they said
keywords:
- null
name: Laundry Room Viking
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Laundry Room Viking | Know Your Meme O HAI! You must login or signup\
  \ first! Already a memeber? Login Now! Don't have an account? Sign up Now! Meme\
  \ Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Laundry Room Viking Added 12 years ago / Updated 8 days ago Confirmed 298,526\
  \ Part of a series on 2011 Hurricane Irene. [View Related Entries] View All 77 Images\
  \ Navigation About \u2022 Origin \u2022 Spread \u2022 Notable Examples \u2022 Search\
  \ Interest \u2022 External References \u2022 Recent Images About Laundry Room Viking\
  \ is an advice animal image macro series based on a Facebook photo of a guy treading\
  \ his way through a flooded laundry room after Hurricane Irene in August 2011. Echoing\
  \ the original caption \"do the laundry they said, it will be fun they said,\" the\
  \ series usually juxtaposes an overly optimistic statement quoted by someone else\
  \ against the undesirable conditions in reality. Origin The original photograph\
  \ was posted via Facebook as a profile picture on August 29th, 2011 and the first\
  \ captioned instance was posted sometime in September 2011, according to Redditor\
  \ ShivamJ[7], a close friend of the man depicted in the image. Catchphrase The phrase\
  \ \"X they said, it would be Y they said\" derives from the Franco-Belgian comic\
  \ series Asterix[12], in which the phrase \"join up they said, it's a man's life\
  \ they said\" (a very loose rendering of the French \"Engagez-vous, rengagez-vous,\
  \ qu'ils disaient,\" which more literally translates as \"enlist, re-enlist, they\
  \ told us\") is, in the English comics, a running gag \u2013 being frequently spoken\
  \ by disgruntled soldiers[13]. The vaguely Norse look of the man's helmet in the\
  \ picture, combined with his disgruntled expression and humorously uncomfortable\
  \ situation, likely evoked the Asterix reference. It is, however, currently unclear\
  \ as to where the connection was first made. That the catchphrase has been in use\
  \ outside of Asterix for some time[14] also muddles the origin. Spread The identity\
  \ of the man depicted in the image remains little known, except that his first name\
  \ is John. The image first came under spotlight on November 27th, 2011 after it\
  \ was posted on 4chan's /b/ (random) board. The same image was subsequently re-posted\
  \ on Reddit in a thread titled \"/b/ this morning,\"[1] receiving over 468,000 views\
  \ with a net score of 6,565 up votes and 5,481 down votes. In the following weeks\
  \ of November and December 2011, the image quickly made its way around other internet\
  \ humor sites including FunnyJunk[4], WeKnowMemes[2] and Daily Picks and Flicks.[6]\
  \ The interest in the image macro series resurged in January 30th, 2012, when Redditor\
  \ ShivamJ took Redditor Shaunre's request and posted the original photo which never\
  \ left facebook. ShivamJ also gave Shaunre a bonus picture of John saluting. Notable\
  \ Examples Following the Reddit thread in late Jaunary, a Quickmeme page[8] titled\
  \ \"Do the Laundry They Said\" was launched to accomodate the rising demand of more\
  \ image macros. Most variations of the image are cropped down in landscape dimension\
  \ and captioned with the phrasal template \"X, they said. Y, they said.\" Search\
  \ Interest External References [1] Reddit \u2013 /b/ this morning [2] WeKnowMemes\
  \ \u2013 Do the Laundry They Said [3] Imgur \u2013 /b/ this morning [4] FunnyJunk\
  \ \u2013 Do the Laundry They Said [5] 9GAG \u2013 They said [6] Daily PIcks and\
  \ Flicks \u2013 Do the Laundry They Said [7] Reddit \u2013 It's Easy They Said [8]\
  \ Quickmeme \u2013 Do The Laundry They Said [9] Reddit \u2013 And Now He's Famous\
  \ [10] Reddit \u2013 This Picture Never Fails to Laugh Me Out Loud [11] Imgur \u2013\
  \ MrFlopz on Imgur [12] Wikipedia \u2013 Asterix [13] Asterix \u2013 Running Gags\
  \ [14] TvTropes \u2013 Join the army, they said said the do room they laundry viking\
  \ Share Pin Related Entries 1 total Hurricane Shark Recent Images 77 total View\
  \ All Images Recent Videos 0 total There are no recent videos. Sign up for our Newsletter\
  \ Load 71 Comments Comments 71 total 79 Laundry Room Viking 298,526 0 77 71 Part\
  \ of a series on 2011 Hurricane Irene. [View Related Entries] Updated Dec 15, 2024\
  \ at 06:48PM EST by LiterallyAustin. Added Jan 30, 2012 at 08:09PM EST by shaunr.\
  \ Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the\
  \ image gallery, 'v' to view the video gallery, or 'r' to view a random entry. Meme\
  \ Status Confirmed Year 2011 Origin Reddit Tags said, the, do, room, they, laundry,\
  \ viking About Laundry Room Viking is an advice animal image macro series based\
  \ on a Facebook photo of a guy treading his way through a flooded laundry room after\
  \ Hurricane Irene in August 2011. Echoing the original caption \"do the laundry\
  \ they said, it will be fun they said,\" the series usually juxtaposes an overly\
  \ optimistic statement quoted by someone else against the undesirable conditions\
  \ in reality. Origin The original photograph was posted via Facebook as a profile\
  \ picture on August 29th, 2011 and the first captioned instance was posted sometime\
  \ in September 2011, according to Redditor ShivamJ[7], a close friend of the man\
  \ depicted in the image. Catchphrase The phrase \"X they said, it would be Y they\
  \ said\" derives from the Franco-Belgian comic series Asterix[12], in which the\
  \ phrase \"join up they said, it's a man's life they said\" (a very loose rendering\
  \ of the French \"Engagez-vous, rengagez-vous, qu'ils disaient,\" which more literally\
  \ translates as \"enlist, re-enlist, they told us\") is, in the English comics,\
  \ a running gag \u2013 being frequently spoken by disgruntled soldiers[13]. The\
  \ vaguely Norse look of the man's helmet in the picture, combined with his disgruntled\
  \ expression and humorously uncomfortable situation, likely evoked the Asterix reference.\
  \ It is, however, currently unclear as to where the connection was first made. That\
  \ the catchphrase has been in use outside of Asterix for some time[14] also muddles\
  \ the origin. Spread The identity of the man depicted in the image remains little\
  \ known, except that his first name is John. The image first came under spotlight\
  \ on November 27th, 2011 after it was posted on 4chan's /b/ (random) board. The\
  \ same image was subsequently re-posted on Reddit in a thread titled \"/b/ this\
  \ morning,\"[1] receiving over 468,000 views with a net score of 6,565 up votes\
  \ and 5,481 down votes. In the following weeks of November and December 2011, the\
  \ image quickly made its way around other internet humor sites including FunnyJunk[4],\
  \ WeKnowMemes[2] and Daily Picks and Flicks.[6] The interest in the image macro\
  \ series resurged in January 30th, 2012, when Redditor ShivamJ took Redditor Shaunre's\
  \ request and posted the original photo which never left facebook. ShivamJ also\
  \ gave Shaunre a bonus picture of John saluting. Notable Examples Following the\
  \ Reddit thread in late Jaunary, a Quickmeme page[8] titled \"Do the Laundry They\
  \ Said\" was launched to accomodate the rising demand of more image macros. Most\
  \ variations of the image are cropped down in landscape dimension and captioned\
  \ with the phrasal template \"X, they said. Y, they said.\" Search Interest External\
  \ References [1] Reddit \u2013 /b/ this morning [2] WeKnowMemes \u2013 Do the Laundry\
  \ They Said [3] Imgur \u2013 /b/ this morning [4] FunnyJunk \u2013 Do the Laundry\
  \ They Said [5] 9GAG \u2013 They said [6] Daily PIcks and Flicks \u2013 Do the Laundry\
  \ They Said [7] Reddit \u2013 It's Easy They Said [8] Quickmeme \u2013 Do The Laundry\
  \ They Said [9] Reddit \u2013 And Now He's Famous [10] Reddit \u2013 This Picture\
  \ Never Fails to Laugh Me Out Loud [11] Imgur \u2013 MrFlopz on Imgur [12] Wikipedia\
  \ \u2013 Asterix [13] Asterix \u2013 Running Gags [14] TvTropes \u2013 Join the\
  \ army, they said Related Entries 1 total Hurricane Shark Recent Videos There are\
  \ no videos currently available. + Add a Video Recent Images 77 total Laundry Room\
  \ Viking Uploaded by Excitebot theLEGO Laundry Room Viking Uploaded by Mongrel Laundry\
  \ Room Viking Uploaded by DrAngelMachine Laundry Room Viking Uploaded by PatGood\
  \ Laundry Room Viking Uploaded by Mulder444 Laundry Room Viking Uploaded by Don\
  \ Laundry Room Viking Uploaded by CommanderThunderush Laundry Room Viking Uploaded\
  \ by CP achtung Laundry Room Viking Uploaded by Veleth95 Laundry Room Viking Uploaded\
  \ by Craig Mammalton Laundry Room Viking Uploaded by Medicine Melancholy Laundry\
  \ Room Viking Uploaded by Sarkhan The Mad + Add an Image View All Images Sign up\
  \ for our Newsletter Top Comments Delete Sensitive Laundry Room Viking Oct 29, 2020\
  \ at 02:38AM EDT Aiight, in case there are two or three people in the world who\
  \ are still curious about my long dead meme, it all started when my basement flooded\
  \ from Hurricane Irene. I was using a large rubber box to shovel water into the\
  \ sink. It was taking forever, so I got bored and started rafting around in it.\
  \ Then my sister went to grab a fuzzy viking hat she had from some college event\
  \ and gave it to me for a photo. A friend of mine took the picture, and many others,\
  \ including my sister getting in her own rubber box with a sombrero and having a\
  \ swiffer mop duel with me. I never uploaded the photo anywhere except as my facebook\
  \ profile picture, but a friend I hadn't talked to in years made the meme out of\
  \ it and put it on reddit. I didn't even know what reddit was at the time but I\
  \ found out it was on the top page of it, which I learned was a big deal. Now the\
  \ guy who made the meme is my drummer and we have a mostly-just-improv band with\
  \ a fan base of -7 people called Government Issued Memories. +37 Reply Delete Sensitive\
  \ Bathezid Feb 01, 2012 at 03:56PM EST This is kinda funny to look at, but only\
  \ as the picture itself. Not the captions. When can we learn to stop with the advice\
  \ animals? +32 Reply + Add a Comment Comments (71) Display Comments Add a Comment\
  \ Top Entries This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (4) shaunr\
  \ Sleuth Brad Digital Archaeologist & Treasurer & Pundit & Gallery Housekeeper Platus\
  \ Database Moderator & Ponyologist opspe Historical Meme Historian + Request Editorship\
  \ View All Editors Today's Top Image Galleries Assassination of UnitedHealthcare\
  \ CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing Digital Circus About\
  \ Our Story Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes\
  \ News Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/laundry-room-viking
template_id: lrv
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
