example:
- your meme is bad
- and you should feel bad
keywords:
- Futurama
- Zoidberg
name: You Should Feel Bad
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Your Music's Bad and You Should Feel Bad | Know Your Meme Yo! You\
  \ must login or signup first! Already a memeber? Login Now! Don't have an account?\
  \ Sign up Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos\
  \ Submit \u2192 Images Trending Most Commented Most Favorited High Score Low Score\
  \ Most Viewed All Templates Upload an Image Articles News Explainers Collections\
  \ Interviews Meme Insider Magazine More Discord Newsletter Episodes Forums Meme\
  \ Store Login Abstract user icon Memes Categories Trending News Images Trending\
  \ Images Videos Trending Videos Editorials Meme Insider Magazine Newsletter Policies\
  \ and Guidelines Meme Store Old site Login Know Your Meme is the property of Literally\
  \ Media \xA92024 Literally Media. All Rights Reserved. This image Of Woman Confidently\
  \ Strolling Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years\
  \ Ago, This Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The\
  \ Anarchy Chess Memes Turns Two Years Old Today Phrase 'The Fridge Protects The\
  \ Snacks' A Growing Favorite Among Pickup Artist Influencers Jamie G, The Bosh British\
  \ Charva, Has Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also\
  \ Trending: Honey Extension Influencer Scam Renegade Raider Copypasta Assassination\
  \ of UnitedHealthcare CEO Your Music's Bad and You Should Feel Bad Added 14 years\
  \ ago / Updated 8 days ago Confirmed 307,849 Part of a series on Futurama. [View\
  \ Related Entries] View All 49 Images Navigation About \u2022 Origin \u2022 Spread\
  \ \u2022 Notable Examples \u2022 Search Interest \u2022 External References \u2022\
  \ Recent Images \u2022 Recent Videos About \"Your Music's Bad and You Should Feel\
  \ Bad\" is a memorable quote from a 2003 episode of Futurama. Online, it has become\
  \ a snowclone (\"Your X is Bad and You Should Feel Bad\"), most often used in an\
  \ image macro series featuring the character Zoidberg to shame others for actions\
  \ or opinions that someone perceives as negative. Origin The phrase \"Your Music's\
  \ Bad and You Should Feel Bad\" was first uttered in the Futurama episode titled\
  \ \"The Devil's Hands Are Idle Playthings,\"[5] which first aired on August 10th,\
  \ 2003. After Fry trades hands with the Robot Devil, he performs an opera in effort\
  \ to woo Leela. In the middle of the performance, the Robot Devil returns and demands\
  \ his hands back from Fry, or else the Devil would marry Leela himself. Fry agrees,\
  \ and continues the performance, who is now significantly less skilled at playing\
  \ the holophoner. As Fry is playing poorly, Zoidberg criticizes his music from the\
  \ crowd. Hedonism Bot: Less reality, more fantasy. Resume the opera. Fry: But I\
  \ can't play anymore! Dr. Zoidberg: Yes you can! The music was in your heart, not\
  \ your hands. [Fry plays off key, everyone boos.] Dr. Zoidberg: Your music's bad\
  \ and you should feel bad! Spread Snowclone derivatives of the phrase have been\
  \ used online since as early as February 2009. On February 5th, 2009, a user of\
  \ the MetaFilter MetaTalk[3] forums used \"Your tags are bad and you should feel\
  \ bad\" as the title of a post criticizing other users who do not properly tag their\
  \ submissions to MetaFilter. By July 2009, the snowclone phrase began to appear\
  \ with a still from the Futurama episode featuring Zoidberg wearing a tuxedo and\
  \ bow tie in a thread on the IGN forums.[1] In December 2009, \"Your Voting Is Bad\
  \ And You Should Feel Bad\" was used as the headline for a Deadspin[2] story on\
  \ voting for that year's All-Star basketball team. In 2010, two Facebook fan pages[4][6]\
  \ were created for the phrase, gaining less than 300 likes between them as of July\
  \ 2013. A third Facebook fan page[7] was created in October 2011, accruing 34 likes\
  \ as of July 2013. Two months later, in November, a thread titled \"Your English\
  \ is Bad and You Should Feel Bad\"[8] was created, mocking other posters who mixed\
  \ up the words \"your\" and \"you're.\" In March 2012, We Know Memes created an\
  \ image macro generator[9] using the Zoidberg still, which has since accrued 451\
  \ submissions. By July 2012, a Meme Generator[10] page was also created, accruing\
  \ nearly 600 submissions, as well as three separate Quickmeme generators[11][12][13]\
  \ which have more than 6,400 submissions among them. Notable Examples Search Interest\
  \ External References [1] IGN \u2013 This thread is bad and you should feel bad\
  \ | 06-22-2009 [2] Deadspin \u2013 Your Voting Is Bad And You Should Feel Bad [3]\
  \ MetaTalk \u2013 Your tags are ad and you should feel bad | 02-05-2009 [4] Facebook\
  \ \u2013 Your Music's Bad and You Should Feel Bad | 06-20-2010 [5] IMDb \u2013 The\
  \ Devil's Hands Are Idle Playthings: Quotes [6] Facebook \u2013 Your music's bad\
  \ and you should feel bad [7] Facebook \u2013 Your music's bad and you should feel\
  \ bad [8] Neoseeker \u2013 Your English is Bad and You Should Feel Bad! [9] We Know\
  \ Memes \u2013 You Should Feel Bad Zoidberg [10] Meme Generator \u2013 Your X is\
  \ bad and You should feel bad [11] Quickmeme \u2013 And you should feel bad [12]\
  \ Quickmeme \u2013 Your meme is bad and you should feel bad! [13] Quickmeme \u2013\
  \ Zoidberg you should feel bad zoidberg catchphrase futurama exploitable music Share\
  \ Pin Related Entries 16 total Futurama Fry / Not Sure If I Don't Want to Live on\
  \ This ... Shut Up And Take My Money! Futurama Zoidberg / Why Not Z... View All\
  \ Related Entries Recent Images 49 total View All Images Recent Videos 3 total View\
  \ All Videos Sign up for our Newsletter Load 54 Comments Comments 54 total 50 Your\
  \ Music's Bad and You Should Feel Bad 307,849 3 49 54 Part of a series on Futurama.\
  \ [View Related Entries] Updated Dec 15, 2024 at 06:35PM EST by LiterallyAustin.\
  \ Added Nov 22, 2010 at 11:18PM EST by Chris. Like us on Facebook! Like 1.8M Share\
  \ Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the video\
  \ gallery, or 'r' to view a random entry. Meme Status Confirmed Year 2003 Origin\
  \ Futurama Tags zoidberg, catchphrase, futurama, exploitable, music About \"Your\
  \ Music's Bad and You Should Feel Bad\" is a memorable quote from a 2003 episode\
  \ of Futurama. Online, it has become a snowclone (\"Your X is Bad and You Should\
  \ Feel Bad\"), most often used in an image macro series featuring the character\
  \ Zoidberg to shame others for actions or opinions that someone perceives as negative.\
  \ Origin The phrase \"Your Music's Bad and You Should Feel Bad\" was first uttered\
  \ in the Futurama episode titled \"The Devil's Hands Are Idle Playthings,\"[5] which\
  \ first aired on August 10th, 2003. After Fry trades hands with the Robot Devil,\
  \ he performs an opera in effort to woo Leela. In the middle of the performance,\
  \ the Robot Devil returns and demands his hands back from Fry, or else the Devil\
  \ would marry Leela himself. Fry agrees, and continues the performance, who is now\
  \ significantly less skilled at playing the holophoner. As Fry is playing poorly,\
  \ Zoidberg criticizes his music from the crowd. Hedonism Bot: Less reality, more\
  \ fantasy. Resume the opera. Fry: But I can't play anymore! Dr. Zoidberg: Yes you\
  \ can! The music was in your heart, not your hands. [Fry plays off key, everyone\
  \ boos.] Dr. Zoidberg: Your music's bad and you should feel bad! Spread Snowclone\
  \ derivatives of the phrase have been used online since as early as February 2009.\
  \ On February 5th, 2009, a user of the MetaFilter MetaTalk[3] forums used \"Your\
  \ tags are bad and you should feel bad\" as the title of a post criticizing other\
  \ users who do not properly tag their submissions to MetaFilter. By July 2009, the\
  \ snowclone phrase began to appear with a still from the Futurama episode featuring\
  \ Zoidberg wearing a tuxedo and bow tie in a thread on the IGN forums.[1] In December\
  \ 2009, \"Your Voting Is Bad And You Should Feel Bad\" was used as the headline\
  \ for a Deadspin[2] story on voting for that year's All-Star basketball team. In\
  \ 2010, two Facebook fan pages[4][6] were created for the phrase, gaining less than\
  \ 300 likes between them as of July 2013. A third Facebook fan page[7] was created\
  \ in October 2011, accruing 34 likes as of July 2013. Two months later, in November,\
  \ a thread titled \"Your English is Bad and You Should Feel Bad\"[8] was created,\
  \ mocking other posters who mixed up the words \"your\" and \"you're.\" In March\
  \ 2012, We Know Memes created an image macro generator[9] using the Zoidberg still,\
  \ which has since accrued 451 submissions. By July 2012, a Meme Generator[10] page\
  \ was also created, accruing nearly 600 submissions, as well as three separate Quickmeme\
  \ generators[11][12][13] which have more than 6,400 submissions among them. Notable\
  \ Examples Search Interest External References [1] IGN \u2013 This thread is bad\
  \ and you should feel bad | 06-22-2009 [2] Deadspin \u2013 Your Voting Is Bad And\
  \ You Should Feel Bad [3] MetaTalk \u2013 Your tags are ad and you should feel bad\
  \ | 02-05-2009 [4] Facebook \u2013 Your Music's Bad and You Should Feel Bad | 06-20-2010\
  \ [5] IMDb \u2013 The Devil's Hands Are Idle Playthings: Quotes [6] Facebook \u2013\
  \ Your music's bad and you should feel bad [7] Facebook \u2013 Your music's bad\
  \ and you should feel bad [8] Neoseeker \u2013 Your English is Bad and You Should\
  \ Feel Bad! [9] We Know Memes \u2013 You Should Feel Bad Zoidberg [10] Meme Generator\
  \ \u2013 Your X is bad and You should feel bad [11] Quickmeme \u2013 And you should\
  \ feel bad [12] Quickmeme \u2013 Your meme is bad and you should feel bad! [13]\
  \ Quickmeme \u2013 Zoidberg you should feel bad Related Entries 16 total Futurama\
  \ Fry / Not Sure If I Don't Want to Live on This Planet Anymore Shut Up And Take\
  \ My Money! Futurama Zoidberg / Why Not Zoidberg? Death By Snu Snu I'm Going To\
  \ Build My Own Theme Park With Blackjack and Hookers Windmills do not work that\
  \ way! Neutral Response Neat Oh Wait. You're Serious? Let Me Laugh Even Harder!\
  \ No Need to Thank Me Suicide Booth View All Related Entries Recent Videos 3 total\
  \ Your music's bad and you shou... Your Music's Bad and You Shou... Uploaded by\
  \ Nightmare_Flare Twilight Sparkle doesn't know... Your Music's Bad and You Shou...\
  \ Uploaded by Oclaf Your Music's Bad and You Shou... Your Music's Bad and You Shou...\
  \ Uploaded by Chris + Add a Video Recent Images 49 total Your Music's Bad and You\
  \ Shou... Uploaded by TOMNICE Your Music's Bad and You Shou... Uploaded by Rebecca\
  \ Rhodes Your Music's Bad and You Shou... Uploaded by babyhenchy1 Your Music's Bad\
  \ and You Shou... Uploaded by Hypercat-Z Your Music's Bad and You Shou... Uploaded\
  \ by neonix Your Music's Bad and You Shou... Uploaded by Slash Man Your Music's\
  \ Bad and You Shou... Uploaded by Official PSASD Your Music's Bad and You Shou...\
  \ Uploaded by yelling_into_the_void Your Music's Bad and You Shou... Uploaded by\
  \ Rarityo3o Your Music's Bad and You Shou... Uploaded by amanda b. Your Music's\
  \ Bad and You Shou... Uploaded by amanda b. Your Music's Bad and You Shou... Uploaded\
  \ by amanda b. + Add an Image View All Images Sign up for our Newsletter Top Comments\
  \ Delete Sensitive Carrie Enright Jul 07, 2013 at 06:30AM EDT +44 Reply Delete Sensitive\
  \ GHETT0SAUCE Jul 07, 2013 at 08:04AM EDT in reply to Carrie Enright You got me\
  \ +13 Reply + Add a Comment Comments (54) Display Comments Add a Comment Top Entries\
  \ This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (6) Chris Philip\
  \ J. Fry Pok\xE9mon Master Mr Bumhole #1 Fan Of Osaka Hamsteak #1 & Television Meme\
  \ Historian Brad Digital Archaeologist & Treasurer & Pundit & Gallery Housekeeper\
  \ amanda b. Meme Librarian Y F Digital Archaeologist & Treasurer & Media Maid \u25BC\
  \ + Request Editorship View All Editors Today's Top Image Galleries Assassination\
  \ of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing\
  \ Digital Circus About Our Story Site Rules Policies and Guidelines Credits Contact\
  \ Meme DB Memes Episodes News Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/your-musics-bad-and-you-should-feel-bad
template_id: bad
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
