name: You Should Feel Bad
source: http://knowyourmeme.com/memes/your-musics-bad-and-you-should-feel-bad
keywords:
- Futurama
- Zoidberg
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- your meme is bad
- and you should feel bad
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About "Your Music''s Bad and You Should Feel Bad" is a memorable
  quote from a 2003 episode of Futurama. Online, it has become a snowclone ("Your
  X is Bad and You Should Feel Bad"), most often used in an image macro series featuring
  the character Zoidberg to shame others for actions or opinions that someone perceives
  as negative. Origin The phrase "Your Music''s Bad and You Should Feel Bad" was first
  uttered in the Futurama episode titled "The Devil''s Hands Are Idle Playthings,"[5]
  which first aired on August 10th, 2003. After Fry trades hands with the Robot Devil,
  he performs an opera in effort to woo Leela. In the middle of the performance, the
  Robot Devil returns and demands his hands back from Fry, or else the Devil would
  marry Leela himself. Fry agrees, and continues the performance, who is now significantly
  less skilled at playing the holophoner. As Fry is playing poorly, Zoidberg criticizes
  his music from the crowd. Hedonism Bot: Less reality, more fantasy. Resume the opera.
  Fry: But I can''t play anymore! Dr. Zoidberg: Yes you can! The music was in your
  heart, not your hands. [Fry plays off key, everyone boos.] Dr. Zoidberg: Your music''s
  bad and you should feel bad! Spread Snowclone derivatives of the phrase have been
  used online since as early as February 2009. On February 5th, 2009, a user of the
  MetaFilter MetaTalk[3] forums used "Your tags are bad and you should feel bad" as
  the title of a post criticizing other users who do not properly tag their submissions
  to MetaFilter. By July 2009, the snowclone phrase began to appear with a still from
  the Futurama episode featuring Zoidberg wearing a tuxedo and bow tie in a thread
  on the IGN forums.[1] In December 2009, "Your Voting Is Bad And You Should Feel
  Bad" was used as the headline for a Deadspin[2] story on voting for that year''s
  All-Star basketball team. In 2010, two Facebook fan pages[4][6] were created for
  the phrase, gaining less than 300 likes between them as of July 2013. A third Facebook
  fan page[7] was created in October 2011, accruing 34 likes as of July 2013. Two
  months later, in November, a thread titled "Your English is Bad and You Should Feel
  Bad"[8] was created, mocking other posters who mixed up the words "your" and "you''re."
  In March 2012, We Know Memes created an image macro generator[9] using the Zoidberg
  still, which has since accrued 451 submissions. By July 2012, a Meme Generator[10]
  page was also created, accruing nearly 600 submissions, as well as three separate
  Quickmeme generators[11][12][13] which have more than 6,400 submissions among them.
  Notable Examples Search Interest External References [1] IGN – This thread is bad
  and you should feel bad | 06-22-2009 [2] Deadspin – Your Voting Is Bad And You Should
  Feel Bad [3] MetaTalk – Your tags are ad and you should feel bad | 02-05-2009 [4]
  Facebook – Your Music''s Bad and You Should Feel Bad | 06-20-2010 [5] IMDb – The
  Devil''s Hands Are Idle Playthings: Quotes [6] Facebook – Your music''s bad and
  you should feel bad [7] Facebook – Your music''s bad and you should feel bad [8]
  Neoseeker – Your English is Bad and You Should Feel Bad! [9] We Know Memes – You
  Should Feel Bad Zoidberg [10] Meme Generator – Your X is bad and You should feel
  bad [11] Quickmeme – And you should feel bad [12] Quickmeme – Your meme is bad and
  you should feel bad! [13] Quickmeme – Zoidberg you should feel bad'
aside_content: MemeStatusConfirmedYear2003OriginFuturamaTagszoidberg,catchphrase,futurama,exploitable,music
added_at: '2010-11-22T23:18:56-05:00'
