name: Mother Ignoring Kid Drowning In A Pool
source: https://knowyourmeme.com/memes/mother-ignoring-kid-drowning-in-a-pool
keywords:
- my cousins learning to swim
text:
- style: default
  color: white
  font: thick
  anchor_x: 0.33
  anchor_y: 0.4
  angle: 0.0
  scale_x: 0.4
  scale_y: 0.15
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: white
  font: thick
  anchor_x: 0.05
  anchor_y: 0.85
  angle: 0.0
  scale_x: 0.4
  scale_y: 0.15
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: white
  font: thick
  anchor_x: 0.6
  anchor_y: 0.65
  angle: 0.0
  scale_x: 0.4
  scale_y: 0.15
  align: center
  start: 0.0
  stop: 1.0
example:
- Posts in Hot
- Posts in New
- Redditors
overlay:
- center_x: 0.51
  center_y: 0.35
  angle: 0.0
  scale: 0.25
- center_x: 0.26
  center_y: 0.8
  angle: 0.0
  scale: 0.25
- center_x: 0.89
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About Mother Ignoring Kid Drowning In A Pool is an image macro of
  a woman lifting up one child in a pool while another child behind her is struggling
  to swim. The family photo was first posted to Reddit in 2018 and then circulated
  Reddit as an object-labeling meme. In 2020, the image acquired another panel that
  featured a skeleton sitting underwater below the original image. Origin On April
  11th, 2018, Redditor posted the image of a woman and two kids in a pool to r/pics[1]
  with the caption "My cousins learning to swim. circa 1980s" (shown below). The post
  gained over 90 points (86% upvoted) in two years. Spread On May 28th, 2018, Redditor
  matdonghia_ posted the image with the children labeled with different math equations
  to r/MemeEconomy[2] (shown below, left). The post garnered over 100 points (88%
  upvoted) in two years. On March 18th, 2019, Redditor 5683968 posted another object-labeled
  variation to r/funnyandsad[3] which acquired over 67,900 points (84% upvoted) in
  a year (shown below, right). In May 2020, Redditors began adding a second panel
  below the original image of a skeleton underwater. On May 26th, Redditor cheesytanker
  posted an example of the format labeled with Norse gods to r/dankmemes[4] (shown
  below). The post accumulated over 5,400 points (98% upvoted) in a day. StayHipp[5]
  published an article on these variations. Various Examples Templates Search Interest
  External References [1] Reddit – r/pics [2] Reddit – r/MemeEconomy [3] Reddit –
  r/FunnyandSad [4] Reddit – r/dankmemes [5] StayHipp – Kids and Mom In Swimming Pool
  Underwater Skeleton Memes
aside_content: MemeStatusConfirmedType:Image MacroYear2018OriginRedditTagsswimming,lifting,mom,kids,underwater,skeleton,matdonghia_,5683968,cheesytanker
added_at: '2020-06-26T15:55:25-04:00'
