example:
- Posts in Hot
- Posts in New
- Redditors
keywords:
- my cousins learning to swim
name: Mother Ignoring Kid Drowning In A Pool
overlay:
- angle: 0.0
  center_x: 0.51
  center_y: 0.35
  scale: 0.25
- angle: 0.0
  center_x: 0.26
  center_y: 0.8
  scale: 0.25
- angle: 0.0
  center_x: 0.89
  center_y: 0.5
  scale: 0.25
scraped_content: "Mother Ignoring Kid Drowning In A Pool | Know Your Meme Word Up!\
  \ You must login or signup first! Already a memeber? Login Now! Don't have an account?\
  \ Sign up Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos\
  \ Submit \u2192 Images Trending Most Commented Most Favorited High Score Low Score\
  \ Most Viewed All Templates Upload an Image Articles News Explainers Collections\
  \ Interviews Meme Insider Magazine More Discord Newsletter Episodes Forums Meme\
  \ Store Login Abstract user icon Memes Categories Trending News Images Trending\
  \ Images Videos Trending Videos Editorials Meme Insider Magazine Newsletter Policies\
  \ and Guidelines Meme Store Old site Login Know Your Meme is the property of Literally\
  \ Media \xA92024 Literally Media. All Rights Reserved. This image Of Woman Confidently\
  \ Strolling Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years\
  \ Ago, This Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The\
  \ Anarchy Chess Memes Turns Two Years Old Today Phrase 'The Fridge Protects The\
  \ Snacks' A Growing Favorite Among Pickup Artist Influencers Jamie G, The Bosh British\
  \ Charva, Has Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also\
  \ Trending: Honey Extension Influencer Scam Renegade Raider Copypasta Assassination\
  \ of UnitedHealthcare CEO Mother Ignoring Kid Drowning In A Pool Added 4 years ago\
  \ / Updated 4 years ago Confirmed 117,125 View All 44 Images Navigation About \u2022\
  \ Origin \u2022 Spread \u2022 Various Examples \u2022 Templates \u2022 Search Interest\
  \ \u2022 External References \u2022 Recent Images About Mother Ignoring Kid Drowning\
  \ In A Pool is an image macro of a woman lifting up one child in a pool while another\
  \ child behind her is struggling to swim. The family photo was first posted to Reddit\
  \ in 2018 and then circulated Reddit as an object-labeling meme. In 2020, the image\
  \ acquired another panel that featured a skeleton sitting underwater below the original\
  \ image. Origin On April 11th, 2018, Redditor posted the image of a woman and two\
  \ kids in a pool to r/pics[1] with the caption \"My cousins learning to swim. circa\
  \ 1980s\" (shown below). The post gained over 90 points (86% upvoted) in two years.\
  \ Spread On May 28th, 2018, Redditor matdonghia_ posted the image with the children\
  \ labeled with different math equations to r/MemeEconomy[2] (shown below, left).\
  \ The post garnered over 100 points (88% upvoted) in two years. On March 18th, 2019,\
  \ Redditor 5683968 posted another object-labeled variation to r/funnyandsad[3] which\
  \ acquired over 67,900 points (84% upvoted) in a year (shown below, right). In May\
  \ 2020, Redditors began adding a second panel below the original image of a skeleton\
  \ underwater. On May 26th, Redditor cheesytanker posted an example of the format\
  \ labeled with Norse gods to r/dankmemes[4] (shown below). The post accumulated\
  \ over 5,400 points (98% upvoted) in a day. StayHipp[5] published an article on\
  \ these variations. Various Examples Templates Search Interest External References\
  \ [1] Reddit \u2013 r/pics [2] Reddit \u2013 r/MemeEconomy [3] Reddit \u2013 r/FunnyandSad\
  \ [4] Reddit \u2013 r/dankmemes [5] StayHipp \u2013 Kids and Mom In Swimming Pool\
  \ Underwater Skeleton Memes swimming lifting mom kids underwater skeleton matdonghia_\
  \ 5683968 cheesytanker Share Pin Recent Images 44 total View All Images Recent Videos\
  \ 0 total There are no recent videos. Sign up for our Newsletter 8 Mother Ignoring\
  \ Kid Drowning In A Pool 117,125 0 44 0 Updated Jul 12, 2020 at 08:24AM EDT by Y\
  \ F. Added Jun 26, 2020 at 03:55PM EDT by Sophie. Like us on Facebook! Like 1.8M\
  \ Share Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the\
  \ video gallery, or 'r' to view a random entry. Meme Status Confirmed Type: Image\
  \ Macro Year 2018 Origin Reddit Tags swimming, lifting, mom, kids, underwater, skeleton,\
  \ matdonghia_, 5683968, cheesytanker About Mother Ignoring Kid Drowning In A Pool\
  \ is an image macro of a woman lifting up one child in a pool while another child\
  \ behind her is struggling to swim. The family photo was first posted to Reddit\
  \ in 2018 and then circulated Reddit as an object-labeling meme. In 2020, the image\
  \ acquired another panel that featured a skeleton sitting underwater below the original\
  \ image. Origin On April 11th, 2018, Redditor posted the image of a woman and two\
  \ kids in a pool to r/pics[1] with the caption \"My cousins learning to swim. circa\
  \ 1980s\" (shown below). The post gained over 90 points (86% upvoted) in two years.\
  \ Spread On May 28th, 2018, Redditor matdonghia_ posted the image with the children\
  \ labeled with different math equations to r/MemeEconomy[2] (shown below, left).\
  \ The post garnered over 100 points (88% upvoted) in two years. On March 18th, 2019,\
  \ Redditor 5683968 posted another object-labeled variation to r/funnyandsad[3] which\
  \ acquired over 67,900 points (84% upvoted) in a year (shown below, right). In May\
  \ 2020, Redditors began adding a second panel below the original image of a skeleton\
  \ underwater. On May 26th, Redditor cheesytanker posted an example of the format\
  \ labeled with Norse gods to r/dankmemes[4] (shown below). The post accumulated\
  \ over 5,400 points (98% upvoted) in a day. StayHipp[5] published an article on\
  \ these variations. Various Examples Templates Search Interest External References\
  \ [1] Reddit \u2013 r/pics [2] Reddit \u2013 r/MemeEconomy [3] Reddit \u2013 r/FunnyandSad\
  \ [4] Reddit \u2013 r/dankmemes [5] StayHipp \u2013 Kids and Mom In Swimming Pool\
  \ Underwater Skeleton Memes Recent Videos There are no videos currently available.\
  \ + Add a Video Recent Images 44 total Mother Ignoring Kid Drowning ... Uploaded\
  \ by Triplem Mother Ignoring Kid Drowning ... Uploaded by Jaimie Hamilton Mother\
  \ Ignoring Kid Drowning ... Uploaded by Jaimie Hamilton Mother Ignoring Kid Drowning\
  \ ... Uploaded by Jaimie Hamilton Mother Ignoring Kid Drowning ... Uploaded by Beetlebro\
  \ Mother Ignoring Kid Drowning ... Uploaded by Jaimie Hamilton Mother Ignoring Kid\
  \ Drowning ... Uploaded by Edgar Weebling Mother Ignoring Kid Drowning ... Uploaded\
  \ by Reddit Moments Mother Ignoring Kid Drowning ... Uploaded by Edgar Weebling\
  \ Mother Ignoring Kid Drowning ... Uploaded by Edgar Weebling Mother Ignoring Kid\
  \ Drowning ... Uploaded by Nyazilla Mother Ignoring Kid Drowning ... Uploaded by\
  \ man weed + Add an Image View All Images Sign up for our Newsletter + Add a Comment\
  \ Comments (0) There are no comments currently available. Display Comments Add a\
  \ Comment Top Entries This Month Meme Saika Kawakita Smile GIF Event Assassination\
  \ of UnitedHealthcare CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki\
  \ Sisters Culture Pornography Site Whisper View More Suggest a Change Edit History\
  \ Entry Editors (3) Sophie Digital Archaeologist & Treasurer & Media Bus Boy andcallmeshirley\
  \ Digital Archaeologist & Treasurer & Collection Butler Y F Digital Archaeologist\
  \ & Treasurer & Media Maid + Request Editorship View All Editors Today's Top Image\
  \ Galleries Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team\
  \ Fortress 2 The Amazing Digital Circus About Our Story Site Rules Policies and\
  \ Guidelines Credits Contact Meme DB Memes Episodes News Staff Contact Extras! Style\
  \ Guide RSS Feeds"
source: https://knowyourmeme.com/memes/mother-ignoring-kid-drowning-in-a-pool
template_id: pool
text:
- align: center
  anchor_x: 0.33
  anchor_y: 0.4
  angle: 0.0
  color: white
  font: thick
  scale_x: 0.4
  scale_y: 0.15
  start: 0.0
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.05
  anchor_y: 0.85
  angle: 0.0
  color: white
  font: thick
  scale_x: 0.4
  scale_y: 0.15
  start: 0.0
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.6
  anchor_y: 0.65
  angle: 0.0
  color: white
  font: thick
  scale_x: 0.4
  scale_y: 0.15
  start: 0.0
  stop: 1.0
  style: default
text_zones: 3
