name: Panik Kalm Panik
source: https://knowyourmeme.com/memes/panik-kalm
keywords:
- null
text:
- style: default
  color: black
  font: thin
  anchor_x: 0.01
  anchor_y: 0.01
  angle: 0.0
  scale_x: 0.45
  scale_y: 0.32
  align: center
  start: 0.1
  stop: 1.0
- style: default
  color: black
  font: thin
  anchor_x: 0.01
  anchor_y: 0.35
  angle: 0.0
  scale_x: 0.45
  scale_y: 0.32
  align: center
  start: 0.4
  stop: 1.0
- style: default
  color: black
  font: thin
  anchor_x: 0.01
  anchor_y: 0.69
  angle: 0.0
  scale_x: 0.45
  scale_y: 0.305
  align: center
  start: 0.7
  stop: 1.0
example:
- You hear a sound downstairs
- It's just a cat
- You don't have a cat
overlay:
- center_x: 0.75
  center_y: 0.8
  angle: 0.0
  scale: 0.25
scraped_content: About Panik Kalm, also known as Panic Calm, is a multi-panel exploitable
  featuring Meme Man in states of panic and calm. The meme takes on the format of
  the Galaxy Brain in which the left column of the meme indicates what Meme Man is
  responding to in the right column. Origin The earliest known usage of the meme was
  published on February 19th, 2020 by Redditor[3] svenskOST_. In the meme, Meme Man
  reacts to the phrases, "When the mother comes home and you haven't done dishes /
  You're a burglar / You're a burglar." The post received more than 11,000 points
  (94% upvoted) in less than five months (shown below). Spread On February 20th, 2020,
  by Redditor [1] xCrylol. In the meme, Meme Man reacts to the phrases "You need to
  pee / Finally you reach the bathroom / You're dreaming." The post received more
  than 24,000 points (95% upvoted) in less than two months (shown below). That day,
  Redditor[2] svenskOST_ shared a version about Adolf Hitler being rejected from art
  school. The post received more than 26,000 points (93% upvoted) in less than two
  months (shown below, left). Over the next month, the meme continued to grow in popularity
  on Reddit in both two- and three-panel variations (examples below). Various Examples
  Template Search Interest External References [1] Reddit – /r/dankmemes [2] Reddit
  – /r/dankmemes [3] Reddit – /r/dankmemes
aside_content: MemeStatusConfirmedType:Image MacroYear2020OriginRedditTagsmeme man,meme
  man wurds,stonks,expanding brain,galaxy brain,xcrylol,svenskost_,panic meme,panic
  calm meme,panik,kalmAdditional ReferencesMeme Generator
added_at: '2020-03-24T12:06:25-04:00'
