example:
- You hear a sound downstairs
- It's just a cat
- You don't have a cat
keywords:
- null
name: Panik Kalm Panik
overlay:
- angle: 0.0
  center_x: 0.75
  center_y: 0.8
  scale: 0.25
scraped_content: "Panik Kalm | Know Your Meme Howdy! You must login or signup first!\
  \ Already a memeber? Login Now! Don't have an account? Sign up Now! Meme Encyclopedia\
  \ All Cultures Events People Sites Subcultures Videos Submit \u2192 Images Trending\
  \ Most Commented Most Favorited High Score Low Score Most Viewed All Templates Upload\
  \ an Image Articles News Explainers Collections Interviews Meme Insider Magazine\
  \ More Discord Newsletter Episodes Forums Meme Store Login Abstract user icon Memes\
  \ Categories Trending News Images Trending Images Videos Trending Videos Editorials\
  \ Meme Insider Magazine Newsletter Policies and Guidelines Meme Store Old site Login\
  \ Know Your Meme is the property of Literally Media \xA92024 Literally Media. All\
  \ Rights Reserved. This image Of Woman Confidently Strolling Through A Glass Panel\
  \ Has Been A Redraw Format Since 2021 Three Years Ago, This Boar's Head 'Exploded'\
  \ Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess Memes Turns Two Years\
  \ Old Today Phrase 'The Fridge Protects The Snacks' A Growing Favorite Among Pickup\
  \ Artist Influencers Jamie G, The Bosh British Charva, Has Taken Over TikTok With\
  \ His Signature 'Oh Cherie Amour' Sound Also Trending: Honey Extension Influencer\
  \ Scam Renegade Raider Copypasta Assassination of UnitedHealthcare CEO Panik Kalm\
  \ Added 4 years ago / Updated about a year ago Confirmed 143,836 Part of a series\
  \ on Meme Man Wurds / Stonks Edits. [View Related Entries] Related Explainer: What's\
  \ The 'Panik Kalm' Meme? The Origin Of The 'Panic Calm' Exploitable Meme Explained\
  \ View All 34 Images Navigation About \u2022 Origin \u2022 Spread \u2022 Various\
  \ Examples \u2022 Template \u2022 Search Interest \u2022 External References \u2022\
  \ Recent Images \u2022 Recent Videos About Panik Kalm, also known as Panic Calm,\
  \ is a multi-panel exploitable featuring Meme Man in states of panic and calm. The\
  \ meme takes on the format of the Galaxy Brain in which the left column of the meme\
  \ indicates what Meme Man is responding to in the right column. Origin The earliest\
  \ known usage of the meme was published on February 19th, 2020 by Redditor[3] svenskOST_.\
  \ In the meme, Meme Man reacts to the phrases, \"When the mother comes home and\
  \ you haven't done dishes / You're a burglar / You're a burglar.\" The post received\
  \ more than 11,000 points (94% upvoted) in less than five months (shown below).\
  \ Spread On February 20th, 2020, by Redditor [1] xCrylol. In the meme, Meme Man\
  \ reacts to the phrases \"You need to pee / Finally you reach the bathroom / You're\
  \ dreaming.\" The post received more than 24,000 points (95% upvoted) in less than\
  \ two months (shown below). That day, Redditor[2] svenskOST_ shared a version about\
  \ Adolf Hitler being rejected from art school. The post received more than 26,000\
  \ points (93% upvoted) in less than two months (shown below, left). Over the next\
  \ month, the meme continued to grow in popularity on Reddit in both two- and three-panel\
  \ variations (examples below). Various Examples Template Search Interest External\
  \ References [1] Reddit \u2013 /r/dankmemes [2] Reddit \u2013 /r/dankmemes [3] Reddit\
  \ \u2013 /r/dankmemes meme man meme man wurds stonks expanding brain galaxy brain\
  \ xcrylol svenskost_ panic meme panic calm meme panik kalm Share Pin Related Entries\
  \ 7 total Stonks Helth Shef Tehc View All Related Entries Recent Images 34 total\
  \ View All Images Recent Videos 7 total View All Videos Sign up for our Newsletter\
  \ Load 8 Comments Comments 8 total 7 Panik Kalm 143,836 7 34 8 Part of a series\
  \ on Meme Man Wurds / Stonks Edits. [View Related Entries] Updated Jul 06, 2023\
  \ at 12:58PM EDT by Zach. Added Mar 24, 2020 at 12:06PM EDT by Matt. Like us on\
  \ Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the image gallery,\
  \ 'v' to view the video gallery, or 'r' to view a random entry. Related Explainer:\
  \ What's The 'Panik Kalm' Meme? The Origin Of The 'Panic Calm' Exploitable Meme\
  \ Explained Meme Status Confirmed Type: Image Macro Year 2020 Origin Reddit Tags\
  \ meme man, meme man wurds, stonks, expanding brain, galaxy brain, xcrylol, svenskost_,\
  \ panic meme, panic calm meme, panik, kalm Additional References Meme Generator\
  \ About Panik Kalm, also known as Panic Calm, is a multi-panel exploitable featuring\
  \ Meme Man in states of panic and calm. The meme takes on the format of the Galaxy\
  \ Brain in which the left column of the meme indicates what Meme Man is responding\
  \ to in the right column. Origin The earliest known usage of the meme was published\
  \ on February 19th, 2020 by Redditor[3] svenskOST_. In the meme, Meme Man reacts\
  \ to the phrases, \"When the mother comes home and you haven't done dishes / You're\
  \ a burglar / You're a burglar.\" The post received more than 11,000 points (94%\
  \ upvoted) in less than five months (shown below). Spread On February 20th, 2020,\
  \ by Redditor [1] xCrylol. In the meme, Meme Man reacts to the phrases \"You need\
  \ to pee / Finally you reach the bathroom / You're dreaming.\" The post received\
  \ more than 24,000 points (95% upvoted) in less than two months (shown below). That\
  \ day, Redditor[2] svenskOST_ shared a version about Adolf Hitler being rejected\
  \ from art school. The post received more than 26,000 points (93% upvoted) in less\
  \ than two months (shown below, left). Over the next month, the meme continued to\
  \ grow in popularity on Reddit in both two- and three-panel variations (examples\
  \ below). Various Examples Template Search Interest External References [1] Reddit\
  \ \u2013 /r/dankmemes [2] Reddit \u2013 /r/dankmemes [3] Reddit \u2013 /r/dankmemes\
  \ Related Entries 7 total Stonks Helth Shef Tehc Mekanik Kemist Acceleration Yes\
  \ Recent Videos 7 total PANIK - KALM - MORE PANIK - G... Panik Kalm Uploaded by\
  \ shevyrolet \U0001F4AFPanik Kalm Panik Memes (Ston... Panik Kalm Uploaded by shevyrolet\
  \ Panik, Kalm, Panik Meme Panik Kalm Uploaded by shevyrolet Panik\U0001F633 Kalm\U0001F60C\
  \ memes!!!\U0001F92F\U0001F976\U0001F60E\U0001F60E\U0001F60E Panik Kalm Uploaded\
  \ by shevyrolet Panik kalm meme compilation Panik Kalm Uploaded by shevyrolet panik\
  \ kalm meme Panik Kalm Uploaded by shevyrolet Panik Kalm Panik Memes (Stonk... Panik\
  \ Kalm Uploaded by shevyrolet + Add a Video Recent Images 34 total Panik Kalm Uploaded\
  \ by Mateus Panik Kalm Uploaded by Jaimie Hamilton Panik Kalm Uploaded by Jaimie\
  \ Hamilton Panik Kalm Uploaded by Reddit Moments Panik Kalm Uploaded by elchew Panik\
  \ Kalm Uploaded by Soup King Panik Kalm Uploaded by TheMemoryOfTrees Panik Kalm\
  \ Uploaded by shevyrolet Panik Kalm Uploaded by andcallmeshirley Panik Kalm Uploaded\
  \ by andcallmeshirley Panik Kalm Uploaded by shevyrolet Panik Kalm Uploaded by shevyrolet\
  \ + Add an Image View All Images Sign up for our Newsletter Top Comment Delete Sensitive\
  \ LinkR Mar 24, 2020 at 01:56PM EDT I used to ditch classes constantly in Community\
  \ College several years ago\u2026 To this day I'm still haunted by guilt dreams\
  \ where I'm completely unprepared for the final. Wasn't worth it. Hell, i passed\
  \ those classes and my conscience still won't let me move on. Some demons never\
  \ fuck off. +8 Reply + Add a Comment Comments (8) Display Comments Add a Comment\
  \ Top Entries This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (7) Matt Secretary\
  \ of Memes Y F Digital Archaeologist & Treasurer & Media Maid andcallmeshirley Digital\
  \ Archaeologist & Treasurer & Collection Butler nightqueen Archivist shevyrolet\
  \ Digital Archaeologist & Treasurer & Media Bus Boy Zach Memenator Mateus Staff\
  \ Member \u25BC + Request Editorship View All Editors Today's Top Image Galleries\
  \ Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress\
  \ 2 The Amazing Digital Circus About Our Story Site Rules Policies and Guidelines\
  \ Credits Contact Meme DB Memes Episodes News Staff Contact Extras! Style Guide\
  \ RSS Feeds"
source: https://knowyourmeme.com/memes/panik-kalm
template_id: panik-kalm-panik
text:
- align: center
  anchor_x: 0.01
  anchor_y: 0.01
  angle: 0.0
  color: black
  font: thin
  scale_x: 0.45
  scale_y: 0.32
  start: 0.1
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.01
  anchor_y: 0.35
  angle: 0.0
  color: black
  font: thin
  scale_x: 0.45
  scale_y: 0.32
  start: 0.4
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.01
  anchor_y: 0.69
  angle: 0.0
  color: black
  font: thin
  scale_x: 0.45
  scale_y: 0.305
  start: 0.7
  stop: 1.0
  style: default
text_zones: 3
