name: Communist Bugs Bunny
source: https://knowyourmeme.com/memes/communist-bugs-bunny
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- ''
- our memes!
overlay:
- center_x: 0.88
  center_y: 0.5
  angle: 0.0
  scale: 0.3
scraped_content: About Communist Bugs Bunny, sometimes known as We Have Bugs Bunny,
  is a reaction image featuring Loony Toons character Bugs Bunny with a red filter
  and the hammer and sickle from the Soviet Union flag. Typically, the image is used
  alongside a caption in which someone claims ownership of something that another
  subject (depicted as Bugs) claims as “ours.” The meme became popularized in June
  2020 across a variety of social media platforms. Origin The original clip that the
  meme is pulled from is seen during a Warner Bros. Merrie Melodies cartoon called
  “A Wild Hare,” released on July 27th, 1940, specifically the scene where Elmer Fudd
  is hunting Bugs Bunny in his rabbit hole. This cartoon is also considered Bugs’
  first official appearance. During this scene (seen below), Elmer Fudd approaches
  Bugs Bunny’s home and around the 57-second mark, he makes the pose used in the meme.
  Spread One of the earliest examples of the scene being used as a meme comes from
  June 8th, 2020, when Imgur[1] user WhatDoYouLookLike posted a version to the site
  under the title “Prove me wrong.” The meme (shown below) received over 144,000 views,
  2,700 points and 275 comments. On June 8th, 2020, YouTuber[2] SomethingDraw uploaded
  a video version of the meme under the title “Soviet Bugs Bunny” (shown below), receiving
  nearly 5,000 views, 157 likes and 50 comments. On Twitter,[3] Communist Bugs Bunny
  is also frequently used as a simple reaction in replies to various tweets. User
  dowvred can be seen tweeting one such example on June 13th, 2020, as a reply to
  an above caption, “my girl is so talented, biggest fan,” with “nossa girl” (or “our
  girl” in English). iFunny[4] user Slumpire uploaded another version on June 21st,
  2020 (seen below). Redditor[5] Jahanzaib69 posted a variant on June 23rd, 2020,
  to the r/dankmemes sub under the title “Comrade Homer.” The post (shown below) was
  upvoted over 35,200 times and commented on 108 times. On June 23rd, 2020, Redditor[6]
  AMIS7 posted a version referencing the U.S. to the r/dankmemes subreddit, receiving
  nearly 59,000 upvotes, 582 comments and three Reddit awards (seen below). Various
  Examples Template Search Interest External References [1] Imgur – Prove me wrong
  [2] YouTube – Soviet Bugs Bunny [3] Twitter – dowvred [4] iFunny – Bugs Bunny [5]
  Reddit – r/dankmemes [6] Reddit – r/dankmemes
aside_content: MemeStatusConfirmedType:Image Macro,ReactionYear1940OriginLooney ToonsTagsbugs
  bunny,soviet union,communist,communism,ussr,looney toons,cartoon,hammer and sickle,reaction,meme,jahanzaib69,amis7Additional
  ReferencesMeme Generator
added_at: '2020-06-26T15:15:09-04:00'
