name: Karate Kyle
source: https://knowyourmeme.com/memes/karate-kyle
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.15
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.85
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.15
  align: center
  start: 0.0
  stop: 1.0
example:
- they broke my pencils
- i broke their neck
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Karate Kyle is an advice animal image macro series similar
  to Vengeance Dad and PTSD Clarinet Boy where the original photo consists of a digital
  composite of the subject''s head enlarged around his entire body with the opacity
  decreased. The captions generally depict various violent acts Karate Kyle has performed
  in retaliation to being bullied. Origin On February 24th, 2011, the original Karate
  Kyle photo was uploaded to James Von Helton''s Facebook[1] page. While no archived
  threads exist, it is rumored to have spread to 4chan shortly afterward. The first
  Reddit[2] post including the Karate Kyle photo wth the caption "They broke my pencils
  / I broke their necks" was submitted on February 25th, 2011 but had no mention of
  the name "Karate Kyle". The second Reddit thread[3] titled "Introducing Karate Kyle"
  later that day with a round-up of Karate Kyle image macros. Spread The single topic
  blog for Karate Kyle on Tumblr[5] was created on May 17th, 2011. The first image
  macro published was captioned with "She deleted me from Facebook / I deleted her
  from life" and received over 500 notes within 9 months. Karate Kyle was #21 in BuzzFeed''s[10]
  "Top 40 Best Memes of 2011" post published on December 8th, 2011. Round-ups of derivatives
  has been posted to Smosh[8], Runt of the Web[7] and Funny or Die.[6] The Karate
  Kyle Quickmeme[4] page has 7,898 submissions and a Karate Kyle "public figure" Facebook[9]
  page has 798 likes as of February 20th, 2012. Notable Examples Template Search Interest
  Search query volume for "karate kyle" rose significantly in March of 2011, one month
  after it was originally posted on Facebook. External References [1] Facebook – Karate
  Kyle [2] Reddit – they broke my pencils [3] Reddit – Introducing Karate Kyle [4]
  Quickmeme – Karate Kyle [5] Tumblr – Karate Kyle [6] Funny Or Die – The 13 Funniest
  Examples of Karate Kyle [7] Runt of the Web – Introducing Your Worst Nightmare –
  Karate Kyle [8] Smosh – Best of Karate Kyle [9] Facebook – Karate Kyle [10] BuzzFeed
  – The 40 Best Memes of 2011'
aside_content: MemeStatusConfirmedYear2011Origin4chanTagskarate kyle,martial arts,advice
  animal,image overlayAdditional ReferencesMeme Generator
added_at: '2011-02-27T14:22:36-05:00'
