example:
- they broke my pencils
- i broke their neck
keywords:
- null
name: Karate Kyle
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Karate Kyle | Know Your Meme 'lo! You must login or signup first!\
  \ Already a memeber? Login Now! Don't have an account? Sign up Now! Meme Encyclopedia\
  \ All Cultures Events People Sites Subcultures Videos Submit \u2192 Images Trending\
  \ Most Commented Most Favorited High Score Low Score Most Viewed All Templates Upload\
  \ an Image Articles News Explainers Collections Interviews Meme Insider Magazine\
  \ More Discord Newsletter Episodes Forums Meme Store Login Abstract user icon Memes\
  \ Categories Trending News Images Trending Images Videos Trending Videos Editorials\
  \ Meme Insider Magazine Newsletter Policies and Guidelines Meme Store Old site Login\
  \ Know Your Meme is the property of Literally Media \xA92024 Literally Media. All\
  \ Rights Reserved. This image Of Woman Confidently Strolling Through A Glass Panel\
  \ Has Been A Redraw Format Since 2021 Three Years Ago, This Boar's Head 'Exploded'\
  \ Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess Memes Turns Two Years\
  \ Old Today Phrase 'The Fridge Protects The Snacks' A Growing Favorite Among Pickup\
  \ Artist Influencers Jamie G, The Bosh British Charva, Has Taken Over TikTok With\
  \ His Signature 'Oh Cherie Amour' Sound Also Trending: Honey Extension Influencer\
  \ Scam Renegade Raider Copypasta Assassination of UnitedHealthcare CEO Karate Kyle\
  \ Added 13 years ago / Updated 12 days ago Confirmed 746,590 Part of a series on\
  \ Advice Animals. [View Related Entries] View All 108 Images Navigation About \u2022\
  \ Origin \u2022 Spread \u2022 Template \u2022 Search Interest \u2022 External References\
  \ \u2022 Recent Images \u2022 Recent Videos About Karate Kyle is an advice animal\
  \ image macro series similar to Vengeance Dad and PTSD Clarinet Boy where the original\
  \ photo consists of a digital composite of the subject's head enlarged around his\
  \ entire body with the opacity decreased. The captions generally depict various\
  \ violent acts Karate Kyle has performed in retaliation to being bullied. Origin\
  \ On February 24th, 2011, the original Karate Kyle photo was uploaded to James Von\
  \ Helton's Facebook[1] page. While no archived threads exist, it is rumored to have\
  \ spread to 4chan shortly afterward. The first Reddit[2] post including the Karate\
  \ Kyle photo wth the caption \"They broke my pencils / I broke their necks\" was\
  \ submitted on February 25th, 2011 but had no mention of the name \"Karate Kyle\"\
  . The second Reddit thread[3] titled \"Introducing Karate Kyle\" later that day\
  \ with a round-up of Karate Kyle image macros. Spread The single topic blog for\
  \ Karate Kyle on Tumblr[5] was created on May 17th, 2011. The first image macro\
  \ published was captioned with \"She deleted me from Facebook / I deleted her from\
  \ life\" and received over 500 notes within 9 months. Karate Kyle was #21 in BuzzFeed's[10]\
  \ \"Top 40 Best Memes of 2011\" post published on December 8th, 2011. Round-ups\
  \ of derivatives has been posted to Smosh[8], Runt of the Web[7] and Funny or Die.[6]\
  \ The Karate Kyle Quickmeme[4] page has 7,898 submissions and a Karate Kyle \"public\
  \ figure\" Facebook[9] page has 798 likes as of February 20th, 2012. Notable Examples\
  \ Template Search Interest Search query volume for \"karate kyle\" rose significantly\
  \ in March of 2011, one month after it was originally posted on Facebook. External\
  \ References [1] Facebook \u2013 Karate Kyle [2] Reddit \u2013 they broke my pencils\
  \ [3] Reddit \u2013 Introducing Karate Kyle [4] Quickmeme \u2013 Karate Kyle [5]\
  \ Tumblr \u2013 Karate Kyle [6] Funny Or Die \u2013 The 13 Funniest Examples of\
  \ Karate Kyle [7] Runt of the Web \u2013 Introducing Your Worst Nightmare \u2013\
  \ Karate Kyle [8] Smosh \u2013 Best of Karate Kyle [9] Facebook \u2013 Karate Kyle\
  \ [10] BuzzFeed \u2013 The 40 Best Memes of 2011 karate kyle martial arts advice\
  \ animal image overlay Share Pin Related Entries 115 total Ermahgerd Overly Attached\
  \ Girlfriend Scumbag Steve Good Guy Greg View All Related Entries Recent Images\
  \ 108 total View All Images Recent Videos 1 total View All Videos Sign up for our\
  \ Newsletter Load 39 Comments Comments 39 total 76 Karate Kyle 746,590 1 108 39\
  \ Part of a series on Advice Animals. [View Related Entries] Updated Dec 11, 2024\
  \ at 12:28PM EST by LiterallyAustin. Added Feb 27, 2011 at 02:22PM EST by AK-. Like\
  \ us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the image\
  \ gallery, 'v' to view the video gallery, or 'r' to view a random entry. Meme Status\
  \ Confirmed Year 2011 Origin 4chan Tags karate kyle, martial arts, advice animal,\
  \ image overlay Additional References Meme Generator About Karate Kyle is an advice\
  \ animal image macro series similar to Vengeance Dad and PTSD Clarinet Boy where\
  \ the original photo consists of a digital composite of the subject's head enlarged\
  \ around his entire body with the opacity decreased. The captions generally depict\
  \ various violent acts Karate Kyle has performed in retaliation to being bullied.\
  \ Origin On February 24th, 2011, the original Karate Kyle photo was uploaded to\
  \ James Von Helton's Facebook[1] page. While no archived threads exist, it is rumored\
  \ to have spread to 4chan shortly afterward. The first Reddit[2] post including\
  \ the Karate Kyle photo wth the caption \"They broke my pencils / I broke their\
  \ necks\" was submitted on February 25th, 2011 but had no mention of the name \"\
  Karate Kyle\". The second Reddit thread[3] titled \"Introducing Karate Kyle\" later\
  \ that day with a round-up of Karate Kyle image macros. Spread The single topic\
  \ blog for Karate Kyle on Tumblr[5] was created on May 17th, 2011. The first image\
  \ macro published was captioned with \"She deleted me from Facebook / I deleted\
  \ her from life\" and received over 500 notes within 9 months. Karate Kyle was #21\
  \ in BuzzFeed's[10] \"Top 40 Best Memes of 2011\" post published on December 8th,\
  \ 2011. Round-ups of derivatives has been posted to Smosh[8], Runt of the Web[7]\
  \ and Funny or Die.[6] The Karate Kyle Quickmeme[4] page has 7,898 submissions and\
  \ a Karate Kyle \"public figure\" Facebook[9] page has 798 likes as of February\
  \ 20th, 2012. Notable Examples Template Search Interest Search query volume for\
  \ \"karate kyle\" rose significantly in March of 2011, one month after it was originally\
  \ posted on Facebook. External References [1] Facebook \u2013 Karate Kyle [2] Reddit\
  \ \u2013 they broke my pencils [3] Reddit \u2013 Introducing Karate Kyle [4] Quickmeme\
  \ \u2013 Karate Kyle [5] Tumblr \u2013 Karate Kyle [6] Funny Or Die \u2013 The 13\
  \ Funniest Examples of Karate Kyle [7] Runt of the Web \u2013 Introducing Your Worst\
  \ Nightmare \u2013 Karate Kyle [8] Smosh \u2013 Best of Karate Kyle [9] Facebook\
  \ \u2013 Karate Kyle [10] BuzzFeed \u2013 The 40 Best Memes of 2011 Related Entries\
  \ 115 total Ermahgerd Overly Attached Girlfriend Scumbag Steve Good Guy Greg Ridiculously\
  \ Photogenic Guy Bad Luck Brian Philosoraptor Annoying Facebook Girl The Most Interesting\
  \ Man in the World Socially Awkward Penguin Bear Grylls / Better Drink My Own Piss\
  \ Successful Black Man View All Related Entries Recent Videos 1 total Karate Kyle\
  \ Karate Kyle Uploaded by Abby of Many Fandoms + Add a Video Recent Images 108 total\
  \ Karate Kyle Uploaded by Weegee246 Karate Kyle Uploaded by Don Clawleone Karate\
  \ Kyle Uploaded by Don Clawleone Karate Kyle Uploaded by Don Clawleone Karate Kyle\
  \ Uploaded by Brad Karate Kyle Uploaded by \U0001F171en Shapiro Karate Kyle Uploaded\
  \ by Nighthawk87 Karate Kyle Uploaded by Nighthawk87 Karate Kyle Uploaded by Avon\
  \ Barksdale Karate Kyle Uploaded by Iroquois Pliskin Karate Kyle Uploaded by alexvw\
  \ Karate Kyle Uploaded by Wimbleflat + Add an Image View All Images Sign up for\
  \ our Newsletter Top Comments Delete Sensitive Chameleon Feb 21, 2012 at 06:43AM\
  \ EST Nobody like brutal guys who looks like nerd? + Confirm (Just kidding) +7 Reply\
  \ Delete Sensitive Skaw Aug 19, 2011 at 11:03PM EDT They told me I was just a submission\
  \ I submited them to their graves +1 Confirm +6 Reply + Add a Comment Comments (39)\
  \ Display Comments Add a Comment Top Entries This Month Meme Saika Kawakita Smile\
  \ GIF Event Assassination of UnitedHealthcare CEO Person Luigi Mangione UHC CEO\
  \ Shooter Subculture The Ki Sisters Culture Pornography Site Whisper View More Suggest\
  \ a Change Edit History Entry Editors (6) AK- Don Administrator & Meme Daddy Brad\
  \ Digital Archaeologist & Treasurer & Pundit & Gallery Housekeeper James Nic Cage\
  \ Fan SabrinaTibbetts Memepuff Y F Digital Archaeologist & Treasurer & Media Maid\
  \ \u25BC + Request Editorship View All Editors Today's Top Image Galleries Assassination\
  \ of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing\
  \ Digital Circus About Our Story Site Rules Policies and Guidelines Credits Contact\
  \ Meme DB Memes Episodes News Staff Contact Extras! Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/karate-kyle
template_id: kk
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.15
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.85
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.15
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
