example:
- Trying a thing.
- Trying a thing again.
keywords:
- null
name: Kombucha Girl
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "\u201CWoman Trying Kombucha\u201D TikTok Has Become A Huge MemeSkip\
  \ To ContentBuzzFeed HomepageSign InBuzzFeedGift GuidesQuizzesTV & MoviesCelebrityArcadeGift\
  \ GuidesQuizzesTrending Browse links Pop CultureTV & MoviesCelebrityBest of the\
  \ InternetAnimalsMusicRewindBooksLGBTQQuizzes & GamesArcadeNEW!LatestTrendingFoodLoveTriviaQuiz\
  \ PartyShowdownShoppingLatestHomeFashionTechBeauty & Personal CarePetsSports & FitnessBuzzFeed\
  \ MerchVideoLatestCocoa ButterMom In ProgressWorth ItUnsolvedMultiplayerPero LikeLifestyleStyleTravelGoodful:\
  \ WellnessNifty: DIYParentsFoodWeddingsSex And LoveTasty HomeCommunityMake a Quiz\
  \ or Post!Featured PostsLeaderboardFrom Our Partners2024 HighlightsBig League Gift\
  \ GuideMerry TechmasLet's Holiday ShopGet That BagAboutAbout UsAdvertiseInvestor\
  \ RelationsJobsNewslettersEditionUSUKAustraliaCanadaDeutschlandIndiaJapanLatamUS\
  \ residents can opt out of \"sales\" of personal data.Do Not Sell or Share My Personal\
  \ Information \xA9 2024 BuzzFeed, Inc PressRSSPrivacyConsent PreferencesUser TermsAccessibility\
  \ StatementAd ChoicesHelpContactSitemapBuzzFeed TastySearch, watch, and cook every\
  \ single Tasty recipe and video ever - all in one place!BuzzFeed GoodfulSelf care\
  \ and ideas to help you live a healthier, happier life.HuffPostNews, Politics, Culture,\
  \ Life, Entertainment, and more. Stories that matter to you.BuzzFeedGift GuidesQuizzesTV\
  \ & MoviesCelebrityArcadeGift GuidesQuizzesTrendingBuzz\xB7Posted on Aug 13, 2019Subscribe\
  \ to BuzzFeed Daily NewsletterCaret DownThe Viral \"Kombucha Girl\" Meme Is Super\
  \ Relatable And Here Are The Best JokesShe has the range.by Daniella EmanuelBuzzFeed\
  \ StaffLinkFacebookPinterestTwitterMail A TikTok of a woman trying kombucha for\
  \ the first time has been circulating the internet and it's providing me with A\
  \ LOT of joy. Let's break down this journey. We begin with the uncertainty of the\
  \ first sip. TikTok Then there's a pause for thought... TikTok Quickly followed\
  \ by disgust. TikTok BUT WAIT! There appears to be some self-doubt. TikTok Nah,\
  \ never mind she hates it. TikTok NOPE! She gets us AGAIN! Her last reaction seems\
  \ to be one of approval. TikTok Yes, you just witnessed a lifetime of emotion in\
  \ under 20 seconds. 22-year-old Brittany Tomlinson was inspired to try kombucha\
  \ after watching a YouTube video about the beverage. \"I watched Cody Ko's video\
  \ and thought 'what the actual fuck is this bacteria water,'\" she told BuzzFeed.\
  \ TikTok \"So I bought the cola flavor from Walmart because I'm poor. When I tasted\
  \ it, it literally tasted like expired coke,\" she said. Walmart The culprit. Her\
  \ final opinion? \"One thumb up, two thumbs down.\" TikTok / BuzzFeed Here are some\
  \ of the best tweets about how kombucha girl (AKA @brittanyt445) is all of us: 1.\
  \ lil adam @MaxxAtom Looking at myself naked in the mirror 09:21 PM - 11 Aug 2019\
  \ Reply Retweet Favorite 2. caitie delaney @caitiedelaney me trying to decide within\
  \ 30 seconds of meeting a man if we\u2019re going to get married 06:22 AM - 12 Aug\
  \ 2019 Reply Retweet Favorite 3. sarah fowerbaugh @sarfow11 me reading back my own\
  \ writing. 05:26 PM - 12 Aug 2019 Reply Retweet Favorite 4. Kara \U0001F5A4 @KaraKempp\
  \ \u201CLet\u2019s go out tonight\u201D Me: 02:59 PM - 12 Aug 2019 Reply Retweet\
  \ Favorite 5. Dave The IT \U0001F159 @PopstarDave When I tasted the cum for the\
  \ first time 05:31 AM - 09 Aug 2019 Reply Retweet Favorite 6. Harry Hill @veryharryhill\
  \ Me watching the manicurist paint my nails with some random Essie color that I\
  \ chose on a whim 07:21 PM - 12 Aug 2019 Reply Retweet Favorite 7. You Matter Hoodies\
  \ Return in September @DemetriusHarmon the first time i stole from self checkout\
  \ 04:54 PM - 11 Aug 2019 Reply Retweet Favorite 8. \U0001D565\U0001D552\U0001D566\
  \U0001D563\U0001D566\U0001D564 \U0001D55E\U0001D560\U0001D560\U0001D55F \U0001D55E\
  \U0001D560\U0001D55E \u2640 @astrolibran gemini, virgo, libra, scorpio, sagittarius,\
  \ aquarius, and pisces deciding wether or not they want to ghost someone 06:58 PM\
  \ - 11 Aug 2019 Reply Retweet Favorite 9. \U0001D565\U0001D552\U0001D566\U0001D563\
  \U0001D566\U0001D564 \U0001D55E\U0001D560\U0001D560\U0001D55F \U0001D55E\U0001D560\
  \U0001D55E \u2640 @astrolibran aries, cancer, leo, libra, and pisces deciding wether\
  \ or not they want to throw a tantrum over a minor inconvenience 05:46 PM - 12 Aug\
  \ 2019 Reply Retweet Favorite 10. Big Tucson Dad @BigTucsonDad Me acquiring the\
  \ taste for beer over the course of like 10 years 06:59 AM - 11 Aug 2019 Reply Retweet\
  \ Favorite 11. ya little sloot @momentssiIence me trying to decide if I find men\
  \ attractive or if it\u2019s just bc some of them have long hair 04:00 AM - 13 Aug\
  \ 2019 Reply Retweet Favorite 12. sock boy @cantreadorwrite when a grindr hookup\
  \ shows up and doesn\u2019t look like his pics but you still go through with it\
  \ 03:26 PM - 10 Aug 2019 Reply Retweet Favorite 13. Nico Correia @notn1co me typing\
  \ \u201Cgay\u201D into the search bar on p*rnhub in middle school 03:09 AM - 11\
  \ Aug 2019 Reply Retweet Favorite 14. troy @boy___troy big little lies season 2\
  \ 06:53 PM - 10 Aug 2019 Reply Retweet Favorite 15. \U0001D586\U0001D591\U0001D592\
  \U0001D594\U0001D593\U0001D589\U0001D592\U0001D58E\U0001D591\U0001D590\U0001D58D\
  \U0001D59A\U0001D593\U0001D593\U0001D58E @almondmilkhunni Me trying not to text\
  \ him 11:17 PM - 11 Aug 2019 Reply Retweet Favorite 16. Peter Marshall @PeterJMarshall\
  \ that first customer at the Pretty Patties stand 02:04 AM - 12 Aug 2019 Reply Retweet\
  \ Favorite 17. \U00013153 @saintsamiko @DemetriusHarmon 05:37 PM - 11 Aug 2019 Reply\
  \ Retweet Favorite BuzzFeed has reached out to Kombucha Girl\u2122 for comment and\
  \ will let you know her final opinions on the beverage as soon as we hear back."
source: https://www.buzzfeed.com/daniellaemanuel/woman-trying-kombucha-meme
template_id: kombucha
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: black
  font: thick
  scale_x: 0.5
  scale_y: 0.3
  start: 0.0
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.5125
  anchor_y: 0.0
  angle: 0.0
  color: black
  font: thick
  scale_x: 0.4875
  scale_y: 0.3
  start: 0.0
  stop: 1.0
  style: default
text_zones: 2
