name: We Have Food at Home
source: https://knowyourmeme.com/memes/we-have-food-at-home
keywords:
- null
text:
- style: default
  color: black
  font: thin
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.001
  scale_x: 1.0
  scale_y: 0.1
  align: left
  start: 0.0
  stop: 1.0
- style: default
  color: black
  font: thin
  anchor_x: 0.0
  anchor_y: 0.1
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.1
  align: left
  start: 0.0
  stop: 1.0
- style: default
  color: black
  font: thin
  anchor_x: 0.0
  anchor_y: 0.2
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.1
  align: left
  start: 0.0
  stop: 1.0
example:
- 'Me: Can we stop and get food?'
- 'Mom: We have food at home.'
- 'Food at home:'
overlay:
- center_x: 0.5
  center_y: 0.675
  angle: 0.0
  scale: 0.65
scraped_content: 'About We Have Food at Home is a series of jokes and mock conversations
  about the commonly shared experience of asking one''s parents for take out and being
  told "there''s food at home." In April 2019, humorous images highlighting low desirability
  of food at home gained popularity online, later expanding into a larger things I
  don''t like trope. In January 2020, comic version We Have Girlfriend at Home gained
  popularity. Origin While jokes involving this phrase have likely existed prior to
  their online appearance, the earliest available variation of the joke was posted
  on April 8th, 2009 by Twitter [1] @Guesswhocruz. They wrote, "back in the day flashback:
  saying i want Mcdonald''s and my mom use to say WE GOT FOOD AT HOME" (shown below).
  Spread Over the next decade, jokes involving the phrase grew in popularity on Twitter.
  For example, on February 3rd, 2012, Twitter[2] user @mariavargasxoxo tweeted, "Yeah
  mom there''s totally a lot of food at home" (shown below). On January 10th, 2014,
  Twitter[3] account @ghetttovine tweeted an image of Tyler, the Creator with the
  caption "When your Mom passes McDonalds and says ''There''s food at home.''" Within
  five years, the tweet received more than 1,000 retweets and 500 likes (shown below,
  center). Three years later, on February 6th, 2017, Instagram [4] user @rellstilldarealest
  posted a Gavin with the caption "When you want mcdonalds but ya mom says there''s
  food at home." The post received more than 1,000 likes in two years (shown below,
  right). On April 1st, 2019, Instagram[5] user @wilfordbrimly posted an image of
  a banana in a bowl of marinara sauce with the caption "Can we stop and get some
  food? Mom: we have food at home." The post received more than 3,200 likes in one
  week (shown below). On April 2nd, 2019, Redditor mnaimm posted a similarly captioned
  image created by an unknown author to /r/me_irl subreddit, where the post gained
  over 12,500 upvotes in two weeks.[6] In the following weeks, multiple posts following
  the trope were posted on Reddit, primarily in /r/dankmemes subreddit. Non-Food Versions
  On April 16th, 2019, Redditor Larssmaller posted the first known non-food version
  of the joke disparaging battle royale game Fortnite. [7] The post gained over 52,300
  upvotes in two days. In the following days, multiple notable posts carried out in
  a similar manner were posted online. For example, a post referencing the 2019 Notre
  Dame fire, posted by Redditor NexusVolt on the same day, gained over 7,100 upvotes
  in 24 hours.[8] We Have Girlfriend at Home On January 7th, 2020, Twitter[9] artist
  @PrincessHinghoi posted a comic in which a mother refuses to let her son to get
  a girlfriend, claiming that they "have one at home." In the second panel, it is
  revealed that by "girlfriend" the mother meant herself. The comic received over
  1,600 retweets and 9,400 likes in one week (shown below). On the same day, the image
  was posted to /r/AraAra[10] subreddit, where it received over 3,700 upvotes in one
  week. Reposts to /r/NoahGetTheBoat[11] and /r/ShotaCops[12] received over 5,100
  upvotes and 780 upvotes in the same period, while the same-day 9GAG[13] post received
  over 1,400 points. Edits On January 9th, 2020, Redditor Galaron_Shuri posted the
  earliest known edit of the comic referencing Milf Hunter Kakoyin meme (shown below,
  left). The post received over 4,600 upvotes in /r/ShitPostCrusaders in one week.
  Starting on January 9th, the comic gained moderate popularity in memes, with notable
  posts made by Redditors TryToEpic and MalcomLuvsPews (shown below, left and right).
  On January 15th, Redditor MalcomLuvsPewds posted a template for the format to /r/MemeTemplatesOfficial
  subreddit. Various Examples Template Search Interest External References [1] Twitter
  – @Guesswhocruz''s Tweet [2] Twitter – @mariavargasxoxo''s Tweet [3] Twitter – @ghetttovine''s
  Tweet [4] Instagram – @rellstilldarealest''s Post [5] Instagram – @wilfordbrimly''s
  Post [6] Reddit – me irl [7] Reddit – Worse than bad food! [8] Reddit – F in the
  chat for Notre Dame [9] Twitter – @PrincessHinghoi [10] Reddit – We have one at
  home [11] Reddit – We have a boat at home [12] Reddit – Mom no [13] 9GAG – Best
  day fOrEvEr'
aside_content: MemeStatusConfirmedType:ExploitableYear2012OriginTwitterTagstwitter,mom,food,food
  in the house,mcdonald's,conversations,parents,reaction images,games at home,there's
  food at home,we have food at home,fast food,x at home,mnaimm,larssmaller,nexusvolt,we
  have girlfriend at homeAdditional ReferencesMeme GeneratorMemebase
added_at: '2019-04-08T14:24:02-04:00'
