example:
- 'Me: Can we stop and get food?'
- 'Mom: We have food at home.'
- 'Food at home:'
keywords:
- null
name: We Have Food at Home
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.675
  scale: 0.65
scraped_content: "We Have Food at Home | Know Your Meme Yo! You must login or signup\
  \ first! Already a memeber? Login Now! Don't have an account? Sign up Now! Meme\
  \ Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO We Have Food at Home Added 5 years ago / Updated 3 years ago Confirmed 451,646\
  \ Part of a series on Snowclone. [View Related Entries] View All 121 Images Navigation\
  \ About \u2022 Origin \u2022 Spread \u2022 Various Examples \u2022 Template \u2022\
  \ Search Interest \u2022 External References \u2022 Recent Images \u2022 Recent\
  \ Videos About We Have Food at Home is a series of jokes and mock conversations\
  \ about the commonly shared experience of asking one's parents for take out and\
  \ being told \"there's food at home.\" In April 2019, humorous images highlighting\
  \ low desirability of food at home gained popularity online, later expanding into\
  \ a larger things I don't like trope. In January 2020, comic version We Have Girlfriend\
  \ at Home gained popularity. Origin While jokes involving this phrase have likely\
  \ existed prior to their online appearance, the earliest available variation of\
  \ the joke was posted on April 8th, 2009 by Twitter [1] @Guesswhocruz. They wrote,\
  \ \"back in the day flashback: saying i want Mcdonald's and my mom use to say WE\
  \ GOT FOOD AT HOME\" (shown below). Spread Over the next decade, jokes involving\
  \ the phrase grew in popularity on Twitter. For example, on February 3rd, 2012,\
  \ Twitter[2] user @mariavargasxoxo tweeted, \"Yeah mom there's totally a lot of\
  \ food at home\" (shown below). On January 10th, 2014, Twitter[3] account @ghetttovine\
  \ tweeted an image of Tyler, the Creator with the caption \"When your Mom passes\
  \ McDonalds and says 'There's food at home.'\" Within five years, the tweet received\
  \ more than 1,000 retweets and 500 likes (shown below, center). Three years later,\
  \ on February 6th, 2017, Instagram [4] user @rellstilldarealest posted a Gavin with\
  \ the caption \"When you want mcdonalds but ya mom says there's food at home.\"\
  \ The post received more than 1,000 likes in two years (shown below, right). On\
  \ April 1st, 2019, Instagram[5] user @wilfordbrimly posted an image of a banana\
  \ in a bowl of marinara sauce with the caption \"Can we stop and get some food?\
  \ Mom: we have food at home.\" The post received more than 3,200 likes in one week\
  \ (shown below). On April 2nd, 2019, Redditor mnaimm posted a similarly captioned\
  \ image created by an unknown author to /r/me_irl subreddit, where the post gained\
  \ over 12,500 upvotes in two weeks.[6] In the following weeks, multiple posts following\
  \ the trope were posted on Reddit, primarily in /r/dankmemes subreddit. Non-Food\
  \ Versions On April 16th, 2019, Redditor Larssmaller posted the first known non-food\
  \ version of the joke disparaging battle royale game Fortnite. [7] The post gained\
  \ over 52,300 upvotes in two days. In the following days, multiple notable posts\
  \ carried out in a similar manner were posted online. For example, a post referencing\
  \ the 2019 Notre Dame fire, posted by Redditor NexusVolt on the same day, gained\
  \ over 7,100 upvotes in 24 hours.[8] We Have Girlfriend at Home On January 7th,\
  \ 2020, Twitter[9] artist @PrincessHinghoi posted a comic in which a mother refuses\
  \ to let her son to get a girlfriend, claiming that they \"have one at home.\" In\
  \ the second panel, it is revealed that by \"girlfriend\" the mother meant herself.\
  \ The comic received over 1,600 retweets and 9,400 likes in one week (shown below).\
  \ On the same day, the image was posted to /r/AraAra[10] subreddit, where it received\
  \ over 3,700 upvotes in one week. Reposts to /r/NoahGetTheBoat[11] and /r/ShotaCops[12]\
  \ received over 5,100 upvotes and 780 upvotes in the same period, while the same-day\
  \ 9GAG[13] post received over 1,400 points. Edits On January 9th, 2020, Redditor\
  \ Galaron_Shuri posted the earliest known edit of the comic referencing Milf Hunter\
  \ Kakoyin meme (shown below, left). The post received over 4,600 upvotes in /r/ShitPostCrusaders\
  \ in one week. Starting on January 9th, the comic gained moderate popularity in\
  \ memes, with notable posts made by Redditors TryToEpic and MalcomLuvsPews (shown\
  \ below, left and right). On January 15th, Redditor MalcomLuvsPewds posted a template\
  \ for the format to /r/MemeTemplatesOfficial subreddit. Various Examples Template\
  \ Search Interest External References [1] Twitter \u2013 @Guesswhocruz's Tweet [2]\
  \ Twitter \u2013 @mariavargasxoxo's Tweet [3] Twitter \u2013 @ghetttovine's Tweet\
  \ [4] Instagram \u2013 @rellstilldarealest's Post [5] Instagram \u2013 @wilfordbrimly's\
  \ Post [6] Reddit \u2013 me irl [7] Reddit \u2013 Worse than bad food! [8] Reddit\
  \ \u2013 F in the chat for Notre Dame [9] Twitter \u2013 @PrincessHinghoi [10] Reddit\
  \ \u2013 We have one at home [11] Reddit \u2013 We have a boat at home [12] Reddit\
  \ \u2013 Mom no [13] 9GAG \u2013 Best day fOrEvEr twitter mom food food in the house\
  \ mcdonald's conversations parents reaction images games at home there's food at\
  \ home we have food at home fast food x at home mnaimm larssmaller nexusvolt we\
  \ have girlfriend at home Share Pin Related Entries 214 total He Protec but He Also\
  \ Attac Rain Drop Drop Top Slaps Roof of Car I Showed You My Dick Please R... View\
  \ All Related Entries Recent Images 121 total View All Images Recent Videos 5 total\
  \ View All Videos Sign up for our Newsletter Load 28 Comments Comments 28 total\
  \ 26 We Have Food at Home 451,659 5 121 28 Part of a series on Snowclone. [View\
  \ Related Entries] Updated Oct 15, 2021 at 12:24PM EDT by Philipp. Added Apr 08,\
  \ 2019 at 02:24PM EDT by Matt. Like us on Facebook! Like 1.8M Share Save Tweet PROTIP:\
  \ Press 'i' to view the image gallery, 'v' to view the video gallery, or 'r' to\
  \ view a random entry. Meme Status Confirmed Type: Exploitable Year 2012 Origin\
  \ Twitter Tags twitter, mom, food, food in the house, mcdonald's, conversations,\
  \ parents, reaction images, games at home, there's food at home, we have food at\
  \ home, fast food, x at home, mnaimm, larssmaller, nexusvolt, we have girlfriend\
  \ at home Additional References Meme Generator Memebase About We Have Food at Home\
  \ is a series of jokes and mock conversations about the commonly shared experience\
  \ of asking one's parents for take out and being told \"there's food at home.\"\
  \ In April 2019, humorous images highlighting low desirability of food at home gained\
  \ popularity online, later expanding into a larger things I don't like trope. In\
  \ January 2020, comic version We Have Girlfriend at Home gained popularity. Origin\
  \ While jokes involving this phrase have likely existed prior to their online appearance,\
  \ the earliest available variation of the joke was posted on April 8th, 2009 by\
  \ Twitter [1] @Guesswhocruz. They wrote, \"back in the day flashback: saying i want\
  \ Mcdonald's and my mom use to say WE GOT FOOD AT HOME\" (shown below). Spread Over\
  \ the next decade, jokes involving the phrase grew in popularity on Twitter. For\
  \ example, on February 3rd, 2012, Twitter[2] user @mariavargasxoxo tweeted, \"Yeah\
  \ mom there's totally a lot of food at home\" (shown below). On January 10th, 2014,\
  \ Twitter[3] account @ghetttovine tweeted an image of Tyler, the Creator with the\
  \ caption \"When your Mom passes McDonalds and says 'There's food at home.'\" Within\
  \ five years, the tweet received more than 1,000 retweets and 500 likes (shown below,\
  \ center). Three years later, on February 6th, 2017, Instagram [4] user @rellstilldarealest\
  \ posted a Gavin with the caption \"When you want mcdonalds but ya mom says there's\
  \ food at home.\" The post received more than 1,000 likes in two years (shown below,\
  \ right). On April 1st, 2019, Instagram[5] user @wilfordbrimly posted an image of\
  \ a banana in a bowl of marinara sauce with the caption \"Can we stop and get some\
  \ food? Mom: we have food at home.\" The post received more than 3,200 likes in\
  \ one week (shown below). On April 2nd, 2019, Redditor mnaimm posted a similarly\
  \ captioned image created by an unknown author to /r/me_irl subreddit, where the\
  \ post gained over 12,500 upvotes in two weeks.[6] In the following weeks, multiple\
  \ posts following the trope were posted on Reddit, primarily in /r/dankmemes subreddit.\
  \ Non-Food Versions On April 16th, 2019, Redditor Larssmaller posted the first known\
  \ non-food version of the joke disparaging battle royale game Fortnite. [7] The\
  \ post gained over 52,300 upvotes in two days. In the following days, multiple notable\
  \ posts carried out in a similar manner were posted online. For example, a post\
  \ referencing the 2019 Notre Dame fire, posted by Redditor NexusVolt on the same\
  \ day, gained over 7,100 upvotes in 24 hours.[8] We Have Girlfriend at Home On January\
  \ 7th, 2020, Twitter[9] artist @PrincessHinghoi posted a comic in which a mother\
  \ refuses to let her son to get a girlfriend, claiming that they \"have one at home.\"\
  \ In the second panel, it is revealed that by \"girlfriend\" the mother meant herself.\
  \ The comic received over 1,600 retweets and 9,400 likes in one week (shown below).\
  \ On the same day, the image was posted to /r/AraAra[10] subreddit, where it received\
  \ over 3,700 upvotes in one week. Reposts to /r/NoahGetTheBoat[11] and /r/ShotaCops[12]\
  \ received over 5,100 upvotes and 780 upvotes in the same period, while the same-day\
  \ 9GAG[13] post received over 1,400 points. Edits On January 9th, 2020, Redditor\
  \ Galaron_Shuri posted the earliest known edit of the comic referencing Milf Hunter\
  \ Kakoyin meme (shown below, left). The post received over 4,600 upvotes in /r/ShitPostCrusaders\
  \ in one week. Starting on January 9th, the comic gained moderate popularity in\
  \ memes, with notable posts made by Redditors TryToEpic and MalcomLuvsPews (shown\
  \ below, left and right). On January 15th, Redditor MalcomLuvsPewds posted a template\
  \ for the format to /r/MemeTemplatesOfficial subreddit. Various Examples Template\
  \ Search Interest External References [1] Twitter \u2013 @Guesswhocruz's Tweet [2]\
  \ Twitter \u2013 @mariavargasxoxo's Tweet [3] Twitter \u2013 @ghetttovine's Tweet\
  \ [4] Instagram \u2013 @rellstilldarealest's Post [5] Instagram \u2013 @wilfordbrimly's\
  \ Post [6] Reddit \u2013 me irl [7] Reddit \u2013 Worse than bad food! [8] Reddit\
  \ \u2013 F in the chat for Notre Dame [9] Twitter \u2013 @PrincessHinghoi [10] Reddit\
  \ \u2013 We have one at home [11] Reddit \u2013 We have a boat at home [12] Reddit\
  \ \u2013 Mom no [13] 9GAG \u2013 Best day fOrEvEr Related Entries 214 total He Protec\
  \ but He Also Attac Rain Drop Drop Top Slaps Roof of Car I Showed You My Dick Please\
  \ Respond Maybe The Real Treasure Was the Friends We Made Along the Way At First,\
  \ I Was Like, But Then, I Was Like Would You Still Love Me If I Was A Worm? Fuck\
  \ X, All My Homies Use Y If You Can't Handle Me at My Worst You Smoke Too Tough.\
  \ Your Swag Too Different. Your Bitch Is Too Bad. They\u2019ll Kill You I Am Forcibly\
  \ Removed From The Premises Born Too Late / Early / Just In Time To Explore X View\
  \ All Related Entries Recent Videos 5 total We have food at home Funny memes We\
  \ Have Food at Home Uploaded by Y F Eating Food At Home | Lessons... We Have Food\
  \ at Home Uploaded by Y F We've Got Food At Home - MEME... We Have Food at Home\
  \ Uploaded by Y F Memes I watch when mom says w... We Have Food at Home Uploaded\
  \ by Y F Memes I watch when mom says w... We Have Food at Home Uploaded by Y F +\
  \ Add a Video Recent Images 121 total We Have Food at Home Uploaded by Reddit Moments\
  \ We Have Food at Home Uploaded by Reddit Moments We Have Food at Home Uploaded\
  \ by Reddit Moments We Have Food at Home Uploaded by Squibblyskadew We Have Food\
  \ at Home Uploaded by Ashbie Moon We Have Food at Home Uploaded by Luc1337 We Have\
  \ Food at Home Uploaded by optimus primevil We Have Food at Home Uploaded by Reddit\
  \ Moments We Have Food at Home Uploaded by Triplem We Have Food at Home Uploaded\
  \ by Sum Lu Zer We Have Food at Home Uploaded by Cold Hard Crash We Have Food at\
  \ Home Uploaded by danthemanred + Add an Image View All Images Sign up for our Newsletter\
  \ Top Comments Delete Sensitive Jon the Wizard Apr 08, 2019 at 08:00PM EDT My version\
  \ went like this: Me: Can we get food? Mom: We can, but we won't. +36 Reply Delete\
  \ Sensitive Ten Shadows Jan 16, 2020 at 01:13PM EST >breathes new life into the\
  \ meme No, just punches the dead meme into the stomach so that it would cough out\
  \ its last dry raspy death croak. +33 Reply + Add a Comment Comments (28) Display\
  \ Comments Add a Comment Top Entries This Month Meme Saika Kawakita Smile GIF Event\
  \ Assassination of UnitedHealthcare CEO Person Luigi Mangione UHC CEO Shooter Subculture\
  \ The Ki Sisters Culture Pornography Site Whisper View More Suggest a Change Edit\
  \ History Entry Editors (6) Matt Secretary of Memes Philipp Memesplainer Y F Digital\
  \ Archaeologist & Treasurer & Media Maid shevyrolet Digital Archaeologist & Treasurer\
  \ & Media Bus Boy Rose Abrams Entry Moderator Autumn Able Sr. Entry Moderator \u25BC\
  \ + Request Editorship View All Editors Today's Top Image Galleries Assassination\
  \ of UnitedHealthcare CEO Team Fortress 2 Squirrel Girl (Doreen Green) The Amazing\
  \ Digital Circus About Our Story Site Rules Policies and Guidelines Credits Contact\
  \ Meme DB Memes Episodes News Staff Contact Extras! Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/we-have-food-at-home
template_id: home
text:
- align: left
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.001
  color: black
  font: thin
  scale_x: 1.0
  scale_y: 0.1
  start: 0.0
  stop: 1.0
  style: default
- align: left
  anchor_x: 0.0
  anchor_y: 0.1
  angle: 0.0
  color: black
  font: thin
  scale_x: 1.0
  scale_y: 0.1
  start: 0.0
  stop: 1.0
  style: default
- align: left
  anchor_x: 0.0
  anchor_y: 0.2
  angle: 0.0
  color: black
  font: thin
  scale_x: 1.0
  scale_y: 0.1
  start: 0.0
  stop: 1.0
  style: default
text_zones: 3
