name: Spider-Man Pointing at Spider-Man
source: https://knowyourmeme.com/memes/spider-man-pointing-at-spider-man
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.05
  anchor_y: 0.0
  angle: 0.0
  scale_x: 0.45
  scale_y: 0.15
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.5
  anchor_y: 0.85
  angle: 0.0
  scale_x: 0.45
  scale_y: 0.15
  align: center
  start: 0.0
  stop: 1.0
example:
- me pointing at you
- you pointing at me
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Spider-Man Pointing at Spider-Man refers to an image from
  the 60''s Spider-Man cartoon episode in which two people in Spider-Man costumes
  are pointing at each other. Origin The image comes from episode 19b of the 1967
  Spider-Man cartoon, "Double Identity."[1] In the episode, a villain attempts to
  impersonate the titular hero. The earliest known use of the two characters dressed
  as Spider-Man pointing at each other was an image macro posted February 5th, 2011
  on Sharenator[2] in a compilation of 60''s Spider-Man images (shown below). Spread
  In the coming years, the image would be used with various other texts on image macros.
  For example, on June 26, 2012, Funnyjunk[3] user generalshawn posted a version where
  the text read "SAMEFAG" in a thread (shown below, left). In early 2013, 9GAG user
  stormrdr[4] posted a version to the site where the text read "HA! Look at that asshole!"
  (shown below, right). The image wouldn''t begin seeing widespread popularity until
  the mid-2010s, when people would make jokes describing situations in which two people
  who are very similar meet. It started growing popular on Black Twitter, particularly
  related to hip-hop. On May 6th, 2016, Reddit user Dualestl[5] used the image to
  describe a meeting between similar-style rappers Future and Desiigner, gaining over
  1,300 points. The format began growing into a popular format on Twitter in early
  2017. On March 10th, @FreddyAmazin[6] published the photo with the caption "When
  your boo start talking like you," gaining over 3,400 retweets and 8,900 likes (shown
  below, left). On May 17th, a joke was uploaded to /r/funny,[7] where it gained over
  440 points (shown below, right). The post was also upped to /r/MemeEconomy[8] on
  July 9th, where it gained over 4,900 points. Spider-Man: No Way Home Cast Recreation
  On February 23rd, 2022, Tobey Maguire, Andrew Garfield, and Tom Holland, three actors
  who played Spider-Man in different runs of the film franchise and reunited in Spider-Man:
  No Way Home, recreated the meme. The post was shared by the film''s Twitter account
  (shown below), generating excited responses from film fans. of course, we got THE
  meme. #SpiderManNoWayHome swings home on Digital March 22 and on 4K UHD & Blu-ray
  on April 12! Pre-order now: https://t.co/Rythp0WfkU pic.twitter.com/pOmV6y3lJr—
  Spider-Man: No Way Home (@SpiderManMovie) February 23, 2022 Various Examples Search
  Interest Search Interest [1] Wikipedia – List of Spider-Man (1967 TV series) episodes
  [2] Sharenator – The Amazing Spiderman [3] Funnyjunk – Youtube comments [4] 9GAG
  – Spidey [5] Reddit – Future and Desiigner Will Both Be at Hot 97''s Summer Jam
  2016 [6] Twitter – @FreddyAmazin [7] Reddit – Tonight on date line… [8] Reddit –
  Spider-Man memes, Should I invest?'
aside_content: MemeStatusConfirmedType:Image Macro,ReactionYear2011OriginSharenatorRegionUnited
  StatesTagsspider-man,60s spider-man,image macro,reaction image,sharenator,generalshawn,stormrdr,freddyamazin,dualestlAdditional
  ReferencesGiphyMeme Generator
added_at: '2017-07-11T15:34:33-04:00'
