example:
- me pointing at you
- you pointing at me
keywords:
- null
name: Spider-Man Pointing at Spider-Man
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Spider-Man Pointing at Spider-Man | Know Your Meme Hello! You must\
  \ login or signup first! Already a memeber? Login Now! Don't have an account? Sign\
  \ up Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos\
  \ Submit \u2192 Images Trending Most Commented Most Favorited High Score Low Score\
  \ Most Viewed All Templates Upload an Image Articles News Explainers Collections\
  \ Interviews Meme Insider Magazine More Discord Newsletter Episodes Forums Meme\
  \ Store Login Abstract user icon Memes Categories Trending News Images Trending\
  \ Images Videos Trending Videos Editorials Meme Insider Magazine Newsletter Policies\
  \ and Guidelines Meme Store Old site Login Know Your Meme is the property of Literally\
  \ Media \xA92024 Literally Media. All Rights Reserved. This image Of Woman Confidently\
  \ Strolling Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years\
  \ Ago, This Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The\
  \ Anarchy Chess Memes Turns Two Years Old Today Phrase 'The Fridge Protects The\
  \ Snacks' A Growing Favorite Among Pickup Artist Influencers Jamie G, The Bosh British\
  \ Charva, Has Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also\
  \ Trending: Honey Extension Influencer Scam Renegade Raider Copypasta Spider-Man\
  \ Pointing at Spider-Man Added 7 years ago / Updated 5 months ago Confirmed 1,954,979\
  \ Part of a series on 60's Spider-Man. [View Related Entries] Related Explainer:\
  \ What Is The 'Spider-Man Pointing At Spider-Man' Meme? The Origins Of The Classic\
  \ Image Explained View All 110 Images Navigation About \u2022 Origin \u2022 Spread\
  \ \u2022 Various Examples \u2022 Search Interest \u2022 Search Interest \u2022 Recent\
  \ Images \u2022 Recent Videos About Spider-Man Pointing at Spider-Man refers to\
  \ an image from the 60's Spider-Man cartoon episode in which two people in Spider-Man\
  \ costumes are pointing at each other. Origin The image comes from episode 19b of\
  \ the 1967 Spider-Man cartoon, \"Double Identity.\"[1] In the episode, a villain\
  \ attempts to impersonate the titular hero. The earliest known use of the two characters\
  \ dressed as Spider-Man pointing at each other was an image macro posted February\
  \ 5th, 2011 on Sharenator[2] in a compilation of 60's Spider-Man images (shown below).\
  \ Spread In the coming years, the image would be used with various other texts on\
  \ image macros. For example, on June 26, 2012, Funnyjunk[3] user generalshawn posted\
  \ a version where the text read \"SAMEFAG\" in a thread (shown below, left). In\
  \ early 2013, 9GAG user stormrdr[4] posted a version to the site where the text\
  \ read \"HA! Look at that asshole!\" (shown below, right). The image wouldn't begin\
  \ seeing widespread popularity until the mid-2010s, when people would make jokes\
  \ describing situations in which two people who are very similar meet. It started\
  \ growing popular on Black Twitter, particularly related to hip-hop. On May 6th,\
  \ 2016, Reddit user Dualestl[5] used the image to describe a meeting between similar-style\
  \ rappers Future and Desiigner, gaining over 1,300 points. The format began growing\
  \ into a popular format on Twitter in early 2017. On March 10th, @FreddyAmazin[6]\
  \ published the photo with the caption \"When your boo start talking like you,\"\
  \ gaining over 3,400 retweets and 8,900 likes (shown below, left). On May 17th,\
  \ a joke was uploaded to /r/funny,[7] where it gained over 440 points (shown below,\
  \ right). The post was also upped to /r/MemeEconomy[8] on July 9th, where it gained\
  \ over 4,900 points. Spider-Man: No Way Home Cast Recreation On February 23rd, 2022,\
  \ Tobey Maguire, Andrew Garfield, and Tom Holland, three actors who played Spider-Man\
  \ in different runs of the film franchise and reunited in Spider-Man: No Way Home,\
  \ recreated the meme. The post was shared by the film's Twitter account (shown below),\
  \ generating excited responses from film fans. of course, we got THE meme. #SpiderManNoWayHome\
  \ swings home on Digital March 22 and on 4K UHD & Blu-ray on April 12! Pre-order\
  \ now: https://t.co/Rythp0WfkU pic.twitter.com/pOmV6y3lJr\u2014 Spider-Man: No Way\
  \ Home (@SpiderManMovie) February 23, 2022 Various Examples Search Interest Search\
  \ Interest [1] Wikipedia \u2013 List of Spider-Man (1967 TV series) episodes [2]\
  \ Sharenator \u2013 The Amazing Spiderman [3] Funnyjunk \u2013 Youtube comments\
  \ [4] 9GAG \u2013 Spidey [5] Reddit \u2013 Future and Desiigner Will Both Be at\
  \ Hot 97's Summer Jam 2016 [6] Twitter \u2013 @FreddyAmazin [7] Reddit \u2013 Tonight\
  \ on date line\u2026 [8] Reddit \u2013 Spider-Man memes, Should I invest? spider-man\
  \ 60s spider-man image macro reaction image sharenator generalshawn stormrdr freddyamazin\
  \ dualestl Share Pin Related Entries 6 total Masturbating Spider-Man 60's Spider-Man\
  \ Rhino Peter Parker Reading a Book This is Now A Spiderman Thread View All Related\
  \ Entries Recent Images 110 total View All Images Recent Videos 8 total View All\
  \ Videos Sign up for our Newsletter Load 31 Comments Comments 31 total 52 Spider-Man\
  \ Pointing at Spider-Man 1,954,980 8 110 31 Part of a series on 60's Spider-Man.\
  \ [View Related Entries] Updated Jul 09, 2024 at 11:00AM EDT by Zach. Added Jul\
  \ 11, 2017 at 03:34PM EDT by Adam. Like us on Facebook! Like 1.8M Share Save Tweet\
  \ PROTIP: Press 'i' to view the image gallery, 'v' to view the video gallery, or\
  \ 'r' to view a random entry. Related Explainer: What Is The 'Spider-Man Pointing\
  \ At Spider-Man' Meme? The Origins Of The Classic Image Explained Meme Status Confirmed\
  \ Type: Image Macro, Reaction Year 2011 Origin Sharenator Region United States Tags\
  \ spider-man, 60s spider-man, image macro, reaction image, sharenator, generalshawn,\
  \ stormrdr, freddyamazin, dualestl Additional References Giphy Meme Generator About\
  \ Spider-Man Pointing at Spider-Man refers to an image from the 60's Spider-Man\
  \ cartoon episode in which two people in Spider-Man costumes are pointing at each\
  \ other. Origin The image comes from episode 19b of the 1967 Spider-Man cartoon,\
  \ \"Double Identity.\"[1] In the episode, a villain attempts to impersonate the\
  \ titular hero. The earliest known use of the two characters dressed as Spider-Man\
  \ pointing at each other was an image macro posted February 5th, 2011 on Sharenator[2]\
  \ in a compilation of 60's Spider-Man images (shown below). Spread In the coming\
  \ years, the image would be used with various other texts on image macros. For example,\
  \ on June 26, 2012, Funnyjunk[3] user generalshawn posted a version where the text\
  \ read \"SAMEFAG\" in a thread (shown below, left). In early 2013, 9GAG user stormrdr[4]\
  \ posted a version to the site where the text read \"HA! Look at that asshole!\"\
  \ (shown below, right). The image wouldn't begin seeing widespread popularity until\
  \ the mid-2010s, when people would make jokes describing situations in which two\
  \ people who are very similar meet. It started growing popular on Black Twitter,\
  \ particularly related to hip-hop. On May 6th, 2016, Reddit user Dualestl[5] used\
  \ the image to describe a meeting between similar-style rappers Future and Desiigner,\
  \ gaining over 1,300 points. The format began growing into a popular format on Twitter\
  \ in early 2017. On March 10th, @FreddyAmazin[6] published the photo with the caption\
  \ \"When your boo start talking like you,\" gaining over 3,400 retweets and 8,900\
  \ likes (shown below, left). On May 17th, a joke was uploaded to /r/funny,[7] where\
  \ it gained over 440 points (shown below, right). The post was also upped to /r/MemeEconomy[8]\
  \ on July 9th, where it gained over 4,900 points. Spider-Man: No Way Home Cast Recreation\
  \ On February 23rd, 2022, Tobey Maguire, Andrew Garfield, and Tom Holland, three\
  \ actors who played Spider-Man in different runs of the film franchise and reunited\
  \ in Spider-Man: No Way Home, recreated the meme. The post was shared by the film's\
  \ Twitter account (shown below), generating excited responses from film fans. of\
  \ course, we got THE meme. #SpiderManNoWayHome swings home on Digital March 22 and\
  \ on 4K UHD & Blu-ray on April 12! Pre-order now: https://t.co/Rythp0WfkU pic.twitter.com/pOmV6y3lJr\u2014\
  \ Spider-Man: No Way Home (@SpiderManMovie) February 23, 2022 Various Examples Search\
  \ Interest Search Interest [1] Wikipedia \u2013 List of Spider-Man (1967 TV series)\
  \ episodes [2] Sharenator \u2013 The Amazing Spiderman [3] Funnyjunk \u2013 Youtube\
  \ comments [4] 9GAG \u2013 Spidey [5] Reddit \u2013 Future and Desiigner Will Both\
  \ Be at Hot 97's Summer Jam 2016 [6] Twitter \u2013 @FreddyAmazin [7] Reddit \u2013\
  \ Tonight on date line\u2026 [8] Reddit \u2013 Spider-Man memes, Should I invest?\
  \ Related Entries 6 total Masturbating Spider-Man 60's Spider-Man Rhino Peter Parker\
  \ Reading a Book This is Now A Spiderman Thread \"Do You See This Shit?\" I Don't\
  \ Need a Doctor, X Will Save Me Recent Videos 8 total Ghostfaces Spider-Man Pointing\
  \ at Spider... Uploaded by Autumn Able \u201CAll Stations, Stop Spider-Man\u201D\
  \ Spider-Man Pointing at Spider... Uploaded by Jazzyclown Bully Maguire lets Tom\
  \ Hollan... Spider-Man Pointing at Spider... Uploaded by Matterinov GET REAL (Spider-Man:\
  \ No Way ... Spider-Man Pointing at Spider... Uploaded by Matterinov Stop Pointing\
  \ At Me - Spider-... Spider-Man Pointing at Spider... Uploaded by shevyrolet Spider-Man\
  \ (PS4): Another Spi... Spider-Man Pointing at Spider... Uploaded by shevyrolet\
  \ Spider-Man Pointing at Spider... Spider-Man Pointing at Spider... Uploaded by\
  \ shevyrolet spider-man points at spider-m... Spider-Man Pointing at Spider... Uploaded\
  \ by shevyrolet + Add a Video Recent Images 110 total Spider-Man Pointing at Spider...\
  \ Uploaded by SoraUta Spider-Man Pointing at Spider... Uploaded by FatmanAss Spider-Man\
  \ Pointing at Spider... Uploaded by KZN02 Spider-Man Pointing at Spider... Uploaded\
  \ by Jaimie Hamilton Spider-Man Pointing at Spider... Uploaded by KZN02 Spider-Man\
  \ Pointing at Spider... Uploaded by Aidan Walker Spider-Man Pointing at Spider...\
  \ Uploaded by KZN02 Spider-Man Pointing at Spider... Uploaded by GeneHunt Spider-Man\
  \ Pointing at Spider... Uploaded by Evilthing Spider-Man Pointing at Spider... Uploaded\
  \ by Reddit Moments Spider-Man Pointing at Spider... Uploaded by mattwo Spider-Man\
  \ Pointing at Spider... Uploaded by Marwan Sallam + Add an Image View All Images\
  \ Sign up for our Newsletter Top Comments Delete Sensitive MahWaht Jul 11, 2017\
  \ at 08:15PM EDT What's this? A glorious 60's Spiderman meme is trending? +40 Reply\
  \ Delete Sensitive Seer Jul 11, 2017 at 07:29PM EDT Remember the time when 60 Spiderman\
  \ had to fight a losing battle against MLP for control of the Most View image gallery?\
  \ Remember when everytime it went away it came back out of nowhere? Remember when\
  \ Undertale replaced MLP and Spiderman never came back? I miss 2013 +34 Reply +\
  \ Add a Comment Comments (31) Display Comments Add a Comment Top Entries This Month\
  \ Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare CEO Person\
  \ Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography Site\
  \ Whisper View More Suggest a Change Edit History Entry Editors (7) Adam Know Your\
  \ Meme Universal Champion Y F Digital Archaeologist & Treasurer & Media Maid Don\
  \ Administrator & Meme Daddy Matt Secretary of Memes shevyrolet Digital Archaeologist\
  \ & Treasurer & Media Bus Boy sakshi Technosorcerer Zach Memenator \u25BC + Request\
  \ Editorship View All Editors Today's Top Image Galleries Assassination of UnitedHealthcare\
  \ CEO Team Fortress 2 Squirrel Girl (Doreen Green) The Amazing Digital Circus About\
  \ Our Story Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes\
  \ News Staff Contact Extras! Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/spider-man-pointing-at-spider-man
template_id: spiderman
text:
- align: center
  anchor_x: 0.05
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 0.45
  scale_y: 0.15
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.5
  anchor_y: 0.85
  angle: 0.0
  color: white
  font: thick
  scale_x: 0.45
  scale_y: 0.15
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
