name: Are You Two Friends?
source: https://knowyourmeme.com/memes/are-you-two-friends
keywords:
- Star Trek
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.25
  anchor_y: 0.2
  angle: -3.0
  scale_x: 0.6
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.05
  anchor_y: 0.65
  angle: 5.0
  scale_x: 0.4
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.46
  anchor_y: 0.69
  angle: 0.0
  scale_x: 0.45
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- Progressives
- Republicans
- Libertarians
overlay:
- center_x: 0.55
  center_y: 0.31
  angle: -3.0
  scale: 0.27
- center_x: 0.25
  center_y: 0.76
  angle: 5.0
  scale: 0.27
- center_x: 0.68
  center_y: 0.79
  angle: 0.0
  scale: 0.27
scraped_content: 'About Are You Two Friends? is a two-panel object-labeling meme format
  based on a scene from the Star Trek: Voyager TV series in which characters Ensign
  Kim and Tuvok provide opposite answers to the question whether they are friends.
  Gaining initial spread in July 2020, the format was popularized online in April
  2021. Origin On January 15th, 1997, episode 14 "Alter Ego" of season three of the
  science-fiction television series Star Trek: Voyager premiered.[1] In the episode,
  characters Ensign Kim and Tuvok become rivals in a love triangle with the character
  Marayana. In one scene of the episode, Marayana asks if Kim and Tuvok are friends,
  to which they provide simultaneous but opposite answers (scene shown below). - Are
  you two friends? - Yes. - No. On October 27th, 2016, Tumblr[2] user captainsblogsupplemental
  posted three images from the scene captioned with the dialogue (shown below). The
  post received over 7,600 likes and reblogs in five years. On July 12th, 2020, the
  Facebook[3] page United Federation Of Leftist Memes posted the earliest discovered
  meme based on the scene, with the post gaining over 1,600 reactions and 910 shares
  in one year (authorship unconfirmed, shown below). Spread In the following days,
  the meme received further spread online, including reposts by Facebook[4] page La
  Resistance and Instagram[5] account the.decadent.socialist. Following the spread
  of the post, in mid-July 2020, the format gained a limited presence online. On July
  13th, an unknown Redditor posted the first derivative meme based on the format,
  with the meme gaining over 4,400 upvotes in the /r/COMPLETEANARCHY[6] subreddit
  in six months (shown below, left). A July 14th post in the /r/YUROP[7] subreddit
  received over 860 upvotes (shown below, center). On October 19th, 2020, Facebook[8]
  page Classical Studies memes for Hellenistic teens posted a meme that received over
  3,400 reactions and 750 shares in six months (shown below, right). The format did
  not see active spread until April 10th, 2021, when Redditor duganaok posted a meme
  based on it, which received over 20,300 upvotes in /r/PoliticalCompassMemes[9] in
  18 days (shown below, left). In the following weeks, the format gained viral popularity
  online, primarily on Reddit and Facebook; for example, on April 18th, Redditor Stripe73
  posted a version that received over 32,700 upvotes in /r/PrequelMemes[10] in 10
  days (shown below, right). In addition to the standard version of the format, a
  version with both provided answers being "yes" also saw use. Various Examples Templates
  Search Interest External References [1] Wikipedia – Alter Ego [2] Tumblr – captainsblogsupplemental
  [3] Facebook – United Federation Of Leftist Memes [4] Facebook – La Risistance [5]
  Instagram – the.decadent.socialist [6] Reddit – Star Trek is Great [7] Reddit –
  Star Trek is Great [8] Facebook – Classical Studies memes for Hellenistic teens
  [9] Reddit – As shit posts go, it’s pretty accurate. [10] Reddit – We''ve got your
  back fellas.'
aside_content: 'MemeStatusSubmissionType:Exploitable,Image MacroYear2020OriginFacebookTagsstar
  trek: voyager,tuvok,harry kim,star trek,are you two friends,marayna,ensign kim,vulcan,object-labeling,image
  macro,exploitable'
added_at: '2021-04-28T10:38:02-04:00'
