example:
- it's a good time to sleep
- nothing will go wrong after this
keywords:
- null
name: Cheems
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Cheems | Know Your Meme Namaste! You must login or signup first!\
  \ Already a memeber? Login Now! Don't have an account? Sign up Now! Meme Encyclopedia\
  \ All Cultures Events People Sites Subcultures Videos Submit \u2192 Images Trending\
  \ Most Commented Most Favorited High Score Low Score Most Viewed All Templates Upload\
  \ an Image Articles News Explainers Collections Interviews Meme Insider Magazine\
  \ More Discord Newsletter Episodes Forums Meme Store Login Abstract user icon Memes\
  \ Categories Trending News Images Trending Images Videos Trending Videos Editorials\
  \ Meme Insider Magazine Newsletter Policies and Guidelines Meme Store Old site Login\
  \ Know Your Meme is the property of Literally Media \xA92024 Literally Media. All\
  \ Rights Reserved. This image Of Woman Confidently Strolling Through A Glass Panel\
  \ Has Been A Redraw Format Since 2021 Three Years Ago, This Boar's Head 'Exploded'\
  \ Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess Memes Turns Two Years\
  \ Old Today Phrase 'The Fridge Protects The Snacks' A Growing Favorite Among Pickup\
  \ Artist Influencers Jamie G, The Bosh British Charva, Has Taken Over TikTok With\
  \ His Signature 'Oh Cherie Amour' Sound Also Trending: Honey Extension Influencer\
  \ Scam Renegade Raider Copypasta Cheems Added 5 years ago / Updated 12 days ago\
  \ Confirmed 684,702 Part of a series on Dogelore. [View Related Entries] [View Related\
  \ Sub-entries] View All 123 Images Featured Episode Navigation About \u2022 Origin\
  \ \u2022 Spread \u2022 Related Memes \u2022 Various Examples \u2022 Template \u2022\
  \ Search Interest \u2022 External References \u2022 Recent Images \u2022 Recent\
  \ Videos About Cheems is an ironic Doge character popularized on /r/dogelore. The\
  \ dog's real name is Balltze, also nicknamed Ball Ball. In memes, he is known for\
  \ liking cheeseburgers, which the Shiba Inu pronounces, \"Cheemsburbger.\" Memes\
  \ featuring Cheems are usually based upon the character humorously misspelling various\
  \ words, particularly by including extra \"M\" letters and first appeared on /r/dogelore\
  \ in June 2019. In late August 2023, Balltze passed away due to complications from\
  \ thoracentesis surgery. Origin On September 4th, 2017, Instagram [3] user @balltze\
  \ posted an image of a Shiba Inu. The image of the dog's head was later used in\
  \ \"Cheems\" memes. Within three years, the post received more than 9,000 likes\
  \ (shown below). The earliest known usage of \"Cheemsburbger\" was published on\
  \ the /r/dogelore subreddit on June 8th, 2019 by Redditor [2] Spicy_Meme_Boi. The\
  \ four-panel meme, which features the smiling Doge with the caption \"Cheemsburbger,\"\
  \ received more than 1,600 points (99% upvoted) in less than one year (shown below).\
  \ Spread On August 8th, 2019, Redditor Octatracking posed an edited picture to /r/dogelore[1]\
  \ declaring \"A Cheems Is Born,\" imagining the creation of a doge that can only\
  \ say \"cheemsburbger.\" The post gained over 2,900 points (shown below). Over the\
  \ following months, the character and its lust for cheemsburbgers grew popular on\
  \ /r/dogelore, as users expanded upon the character to make it violently protective\
  \ of \"cheemsburbgers.\" For example, on August 21st, 2019, a deleted user posted\
  \ a threatening message about adding a loaf of Doge to its cheemsburbger recipe,\
  \ gaining over 7,400 points (shown below, left). User federic0_S_2 posted a similarly\
  \ violent image to /r/ImSorryKaren on October 30th, gaining over 270 points (shown\
  \ below, right). Other popular posts featuring Cheems include a post by nucleararmsdealer\
  \ that gained over 1,000 points in /r/dogelore (shown below, left) and a post by\
  \ KenNHK that gained over 1,800 points (shown below, right). Interview with Know\
  \ Your Meme On August 6th, 2020, KYM interviewed Balltze's owner, Kathy, as part\
  \ of their editorial series that follows up on people featured in prominent memes.\
  \ In the interview, Kathy shared the backstory of how Balltze came into her life\
  \ alongside detailed information of how the original photos of Balltze went on to\
  \ become Cheems. Cheems Pancreatitis On May 19th, 2022, Cheems' owner made a post\
  \ to Instagram[4] sharing several photos of Balltze at the vet. In the caption,\
  \ her owner shares that Balltze has been throwing up and having diarrhea and was\
  \ diagnosed with pancreatitis on May 10th. The photos were posted after a second\
  \ blood test, which showed test results better than the first. The post gained over\
  \ 48,000 likes in under 24 hours and many comments of support wishing Balltze a\
  \ quick recovery. On that day, a user of /r/dogelore[5] made a post sharing the\
  \ news, gaining over 2,700 upvotes in under a day and multiple well-wishing comments.\
  \ Death On August 19th, 2023, the @balltze[6] Instagram account published a post\
  \ that Balltze had passed away the previous day due to complications from a thoracentesis\
  \ surgery (shown below). Balltze's owners urged viewers to not \"be sad\" but to\
  \ \"remember the joy that Balltze brought to the world.\" As word of Balltze's death\
  \ spread online, numerous users across the internet posted memes and tributes to\
  \ commemorate Cheems. Related Memes Swole Doge vs. Cheems Swole Doge vs. Cheems\
  \ refers to a comparison format in which representatives of the same group from\
  \ two historical eras are presented as Swole Doge and Cheems and are compared to\
  \ each other. Originating from a viral Reddit meme, the format gained popularity\
  \ on Reddit and Facebook starting in mid-May 2020. Various Examples Template Search\
  \ Interest External References [1] Reddit \u2013 A Cheems Is Born [2] Reddit \u2013\
  \ /r/dogelore [3] Instagram \u2013 @balltze's Post [4] Instagram \u2013 balltze\
  \ [5] Reddit \u2013 dogelore [6] Instagram \u2013 @balltze ironic doge cheemsburger\
  \ octatracking federic0_s_2 nucleararmsdealer kennhk balltze cheemsburbger dog shiba\
  \ inu cheems meme memes animals Share Pin Related Entries 2 total Uncle Murphy Quoge\
  \ Sub-entries 4 total Bonk (Cheems) Slav Cat / Slav Cheebs Enfim, a Hipocrisia /\
  \ Hypocri... Nothing Wacky Going On Here Recent Images 123 total View All Images\
  \ Recent Videos 65 total View All Videos Sign up for our Newsletter Load 71 Comments\
  \ Comments 71 total 63 Cheems 684,702 65 123 71 Part of a series on Dogelore. [View\
  \ Related Entries] [View Related Sub-entries] Updated Dec 11, 2024 at 04:26PM EST\
  \ by LiterallyAustin. Added Dec 02, 2019 at 11:38AM EST by Adam. Like us on Facebook!\
  \ Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to\
  \ view the video gallery, or 'r' to view a random entry. Featured Episode Meme Status\
  \ Confirmed Type: Animal, Character Year 2019 Origin Instagram Region United States\
  \ Tags ironic, doge, cheemsburger, octatracking, federic0_s_2, nucleararmsdealer,\
  \ kennhk, balltze, cheemsburbger, dog, shiba inu, cheems meme, memes, animals Additional\
  \ References Fandom.com Reddit Twitter Urban Dictionary Wikipedia About Cheems is\
  \ an ironic Doge character popularized on /r/dogelore. The dog's real name is Balltze,\
  \ also nicknamed Ball Ball. In memes, he is known for liking cheeseburgers, which\
  \ the Shiba Inu pronounces, \"Cheemsburbger.\" Memes featuring Cheems are usually\
  \ based upon the character humorously misspelling various words, particularly by\
  \ including extra \"M\" letters and first appeared on /r/dogelore in June 2019.\
  \ In late August 2023, Balltze passed away due to complications from thoracentesis\
  \ surgery. Origin On September 4th, 2017, Instagram [3] user @balltze posted an\
  \ image of a Shiba Inu. The image of the dog's head was later used in \"Cheems\"\
  \ memes. Within three years, the post received more than 9,000 likes (shown below).\
  \ The earliest known usage of \"Cheemsburbger\" was published on the /r/dogelore\
  \ subreddit on June 8th, 2019 by Redditor [2] Spicy_Meme_Boi. The four-panel meme,\
  \ which features the smiling Doge with the caption \"Cheemsburbger,\" received more\
  \ than 1,600 points (99% upvoted) in less than one year (shown below). Spread On\
  \ August 8th, 2019, Redditor Octatracking posed an edited picture to /r/dogelore[1]\
  \ declaring \"A Cheems Is Born,\" imagining the creation of a doge that can only\
  \ say \"cheemsburbger.\" The post gained over 2,900 points (shown below). Over the\
  \ following months, the character and its lust for cheemsburbgers grew popular on\
  \ /r/dogelore, as users expanded upon the character to make it violently protective\
  \ of \"cheemsburbgers.\" For example, on August 21st, 2019, a deleted user posted\
  \ a threatening message about adding a loaf of Doge to its cheemsburbger recipe,\
  \ gaining over 7,400 points (shown below, left). User federic0_S_2 posted a similarly\
  \ violent image to /r/ImSorryKaren on October 30th, gaining over 270 points (shown\
  \ below, right). Other popular posts featuring Cheems include a post by nucleararmsdealer\
  \ that gained over 1,000 points in /r/dogelore (shown below, left) and a post by\
  \ KenNHK that gained over 1,800 points (shown below, right). Interview with Know\
  \ Your Meme On August 6th, 2020, KYM interviewed Balltze's owner, Kathy, as part\
  \ of their editorial series that follows up on people featured in prominent memes.\
  \ In the interview, Kathy shared the backstory of how Balltze came into her life\
  \ alongside detailed information of how the original photos of Balltze went on to\
  \ become Cheems. Cheems Pancreatitis On May 19th, 2022, Cheems' owner made a post\
  \ to Instagram[4] sharing several photos of Balltze at the vet. In the caption,\
  \ her owner shares that Balltze has been throwing up and having diarrhea and was\
  \ diagnosed with pancreatitis on May 10th. The photos were posted after a second\
  \ blood test, which showed test results better than the first. The post gained over\
  \ 48,000 likes in under 24 hours and many comments of support wishing Balltze a\
  \ quick recovery. On that day, a user of /r/dogelore[5] made a post sharing the\
  \ news, gaining over 2,700 upvotes in under a day and multiple well-wishing comments.\
  \ Death On August 19th, 2023, the @balltze[6] Instagram account published a post\
  \ that Balltze had passed away the previous day due to complications from a thoracentesis\
  \ surgery (shown below). Balltze's owners urged viewers to not \"be sad\" but to\
  \ \"remember the joy that Balltze brought to the world.\" As word of Balltze's death\
  \ spread online, numerous users across the internet posted memes and tributes to\
  \ commemorate Cheems. Related Memes Swole Doge vs. Cheems Swole Doge vs. Cheems\
  \ refers to a comparison format in which representatives of the same group from\
  \ two historical eras are presented as Swole Doge and Cheems and are compared to\
  \ each other. Originating from a viral Reddit meme, the format gained popularity\
  \ on Reddit and Facebook starting in mid-May 2020. Various Examples Template Search\
  \ Interest External References [1] Reddit \u2013 A Cheems Is Born [2] Reddit \u2013\
  \ /r/dogelore [3] Instagram \u2013 @balltze's Post [4] Instagram \u2013 balltze\
  \ [5] Reddit \u2013 dogelore [6] Instagram \u2013 @balltze Related Entries 2 total\
  \ Uncle Murphy Quoge Sub-entries 4 total Bonk (Cheems) Slav Cat / Slav Cheebs Enfim,\
  \ a Hipocrisia / Hypocrisy At Last Nothing Wacky Going On Here Recent Videos 65\
  \ total Goodbye Cheems Cheems Uploaded by Pikazilla Beloved Meme Dog, Cheems Cros...\
  \ Cheems Uploaded by Zach Cheemon Slayer Cheems Uploaded by tchitchouan Initial\
  \ Cheems eyecatchs (meme) Cheems Uploaded by Y F Poke cheems cap 1 Cheems Uploaded\
  \ by Y F Caso Cheems rado \U0001F605 Juicio a l... Cheems Uploaded by Y F Abro hilo\
  \ - Se burl\xF3 de m\xED y ... Cheems Uploaded by Y F Le Di Una Lecci\xF3n A Una\
  \ Novia... Cheems Uploaded by Y F + Add a Video View All Videos Recent Images 123\
  \ total Cheems Uploaded by DudeBroMan Cheems Uploaded by Reddit Moments Cheems Uploaded\
  \ by Reddit Moments Cheems Uploaded by Reddit Moments Cheems Uploaded by Reddit\
  \ Moments Cheems Uploaded by Reddit Moments Cheems Uploaded by Reddit Moments Cheems\
  \ Uploaded by Reddit Moments Cheems Uploaded by Reddit Moments Cheems Uploaded by\
  \ Reddit Moments Cheems Uploaded by Reddit Moments Cheems Uploaded by Reddit Moments\
  \ + Add an Image View All Images Sign up for our Newsletter Top Comments Delete\
  \ Sensitive nabusco Dec 02, 2019 at 06:07PM EST in reply to Roth \"Free will is\
  \ a myth. Religion is a joke. We are all pawns, controlled by something greater:\
  \ Memes. The DNA of the soul. They shape our will. They are the culture. They are\
  \ everything we pass on.\" +69 Reply Delete Sensitive Roth Dec 02, 2019 at 04:43PM\
  \ EST Can't believe we're bringing back I Can Has Cheezeburger after all these years.\
  \ +57 Reply + Add a Comment Comments (71) Display Comments Add a Comment Top Entries\
  \ This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (11) Adam Know\
  \ Your Meme Universal Champion andcallmeshirley Digital Archaeologist & Treasurer\
  \ & Collection Butler Y F Digital Archaeologist & Treasurer & Media Maid Philipp\
  \ Memesplainer Matt Secretary of Memes Iwazaru Sr. Entry Moderator & Constable Zach\
  \ Memenator shevyrolet Digital Archaeologist & Treasurer & Media Bus Boy Rose Abrams\
  \ Entry Moderator Phillip Hamilton Bonk Connoisseur Don Administrator & Meme Daddy\
  \ \u25BC + Request Editorship View All Editors Today's Top Image Galleries Assassination\
  \ of UnitedHealthcare CEO Team Fortress 2 Squirrel Girl (Doreen Green) The Amazing\
  \ Digital Circus About Our Story Site Rules Policies and Guidelines Credits Contact\
  \ Meme DB Memes Episodes News Staff Contact Extras! Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/cheems
template_id: cheems
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
