name: Cheems
source: https://knowyourmeme.com/memes/cheems
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- it's a good time to sleep
- nothing will go wrong after this
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About Cheems is an ironic Doge character popularized on /r/dogelore.
  The dog's real name is Balltze, also nicknamed Ball Ball. In memes, he is known
  for liking cheeseburgers, which the Shiba Inu pronounces, "Cheemsburbger." Memes
  featuring Cheems are usually based upon the character humorously misspelling various
  words, particularly by including extra "M" letters and first appeared on /r/dogelore
  in June 2019. In late August 2023, Balltze passed away due to complications from
  thoracentesis surgery. Origin On September 4th, 2017, Instagram [3] user @balltze
  posted an image of a Shiba Inu. The image of the dog's head was later used in "Cheems"
  memes. Within three years, the post received more than 9,000 likes (shown below).
  The earliest known usage of "Cheemsburbger" was published on the /r/dogelore subreddit
  on June 8th, 2019 by Redditor [2] Spicy_Meme_Boi. The four-panel meme, which features
  the smiling Doge with the caption "Cheemsburbger," received more than 1,600 points
  (99% upvoted) in less than one year (shown below). Spread On August 8th, 2019, Redditor
  Octatracking posed an edited picture to /r/dogelore[1] declaring "A Cheems Is Born,"
  imagining the creation of a doge that can only say "cheemsburbger." The post gained
  over 2,900 points (shown below). Over the following months, the character and its
  lust for cheemsburbgers grew popular on /r/dogelore, as users expanded upon the
  character to make it violently protective of "cheemsburbgers." For example, on August
  21st, 2019, a deleted user posted a threatening message about adding a loaf of Doge
  to its cheemsburbger recipe, gaining over 7,400 points (shown below, left). User
  federic0_S_2 posted a similarly violent image to /r/ImSorryKaren on October 30th,
  gaining over 270 points (shown below, right). Other popular posts featuring Cheems
  include a post by nucleararmsdealer that gained over 1,000 points in /r/dogelore
  (shown below, left) and a post by KenNHK that gained over 1,800 points (shown below,
  right). Interview with Know Your Meme On August 6th, 2020, KYM interviewed Balltze's
  owner, Kathy, as part of their editorial series that follows up on people featured
  in prominent memes. In the interview, Kathy shared the backstory of how Balltze
  came into her life alongside detailed information of how the original photos of
  Balltze went on to become Cheems. Cheems Pancreatitis On May 19th, 2022, Cheems'
  owner made a post to Instagram[4] sharing several photos of Balltze at the vet.
  In the caption, her owner shares that Balltze has been throwing up and having diarrhea
  and was diagnosed with pancreatitis on May 10th. The photos were posted after a
  second blood test, which showed test results better than the first. The post gained
  over 48,000 likes in under 24 hours and many comments of support wishing Balltze
  a quick recovery. On that day, a user of /r/dogelore[5] made a post sharing the
  news, gaining over 2,700 upvotes in under a day and multiple well-wishing comments.
  Death On August 19th, 2023, the @balltze[6] Instagram account published a post that
  Balltze had passed away the previous day due to complications from a thoracentesis
  surgery (shown below). Balltze's owners urged viewers to not "be sad" but to "remember
  the joy that Balltze brought to the world." As word of Balltze's death spread online,
  numerous users across the internet posted memes and tributes to commemorate Cheems.
  Related Memes Swole Doge vs. Cheems Swole Doge vs. Cheems refers to a comparison
  format in which representatives of the same group from two historical eras are presented
  as Swole Doge and Cheems and are compared to each other. Originating from a viral
  Reddit meme, the format gained popularity on Reddit and Facebook starting in mid-May
  2020. Various Examples Template Search Interest External References [1] Reddit –
  A Cheems Is Born [2] Reddit – /r/dogelore [3] Instagram – @balltze's Post [4] Instagram
  – balltze [5] Reddit – dogelore [6] Instagram – @balltze
aside_content: MemeStatusConfirmedType:Animal,CharacterYear2019OriginInstagramRegionUnited
  StatesTagsironic,doge,cheemsburger,octatracking,federic0_s_2,nucleararmsdealer,kennhk,balltze,cheemsburbger,dog,shiba
  inu,cheems meme,memes,animalsAdditional ReferencesFandom.comRedditTwitterUrban DictionaryWikipedia
added_at: '2019-12-02T11:38:39-05:00'
