name: Galaxy Brain
source: https://knowyourmeme.com/memes/galaxy-brain
keywords:
- null
text:
- style: none
  color: black
  font: thin
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 0.49
  scale_y: 0.245
  align: center
  start: 0.1
  stop: 1.0
- style: none
  color: black
  font: thin
  anchor_x: 0.0
  anchor_y: 0.255
  angle: 0.0
  scale_x: 0.49
  scale_y: 0.246
  align: center
  start: 0.3
  stop: 1.0
- style: none
  color: black
  font: thin
  anchor_x: 0.0
  anchor_y: 0.51
  angle: 0.0
  scale_x: 0.489
  scale_y: 0.224
  align: center
  start: 0.5
  stop: 1.0
- style: none
  color: black
  font: thin
  anchor_x: 0.0
  anchor_y: 0.746
  angle: 0.0
  scale_x: 0.49
  scale_y: 0.255
  align: center
  start: 0.7
  stop: 1.0
example:
- Who
- Whom
- Whom'st
- Whomst'd
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About Galaxy Brain, also known as Expanding Brain, is a multi-panel
  exploitable image series comparing the brain size of a person relative to other
  variables. Though the expanding brain is usually implied to showcase intellectual
  superiority over various objects, it is more often used in an ironic sense to imply
  the opposite, where objects of derision are implied to be of higher standard than
  objects that are usually highly regarded. For example, when used with Whomst, a
  person who uses "who" will be shown with the smallest brain, while a person who
  uses the most ridiculous variation, i.e. "whomst'd've", will be shown with the largest
  brain. Origin This meme originated as part of the "Whomst" meme where the left column
  was derivations of the word "Who" were paired with increasingly elaborate pictures
  of brains depending on how intense the "who" variation was. One of the most popular
  early examples was posted to /r/dankmemes on Reddit on January 31st, 2017 by janskishimanski[1]
  in a post that gained nearly 1,200 upvotes. Spread As "whomst" variations on the
  Expanding Brain template grew more elaborate, other subjects were applied to Expanding
  Brain, such as video games and politics. Expanding Brain variations continued appearing
  on /r/dankmemes and /r/MemeEconomy throughout the month of February. A video version
  of the meme posted by user BagelBoy in February 2017 gained over 2.1 million views
  (shown below). The meme was covered by media outlets including PopSugar,[3] New
  York Magazine,[4] Mic,[5] and others. Similar Memes The template of the Expanding
  Brain meme has been used with various other characters. Vince McMahon Reaction While
  the Vince McMahon Reaction existed as a video and GIF meme prior to its use as an
  Expanding Brain meme, the clips of McMahon were used in the Expanding Brain template
  after that meme got popular. Motion Blurred Astronaut Motion Blurred Astronaut refers
  to three images of an astronaut in a photography textbook taken to demonstrate the
  effect shutter speed can have on motion-blur. It began being used in memes in April
  2017 due to its aesthetic similarity to other popular memes of the time which use
  motion-blur and distortion effects. On April 2nd, 2017, Tumblr user the-captains-on-shore-leave
  uploaded a picture of a photography textbook demonstrating the effects shutter speed
  has on motion blur by showing three different pictures of an astronaut. They captioned
  the post, shown below, "i can’t stop laughing like i know it’s supposed to be educating
  me on shutter speed but it just looks like a fucking meme." The post has gained
  over 35,000 notes as of April 11th. Various Examples Drake Sprite Commercial Remix
  In 2010, Sprite released a commercial featuring rapper Drake, drinking a Sprite
  while recording and exploding (shown below). Eight years later, a series of Expanding
  Brain memes featuring three respective stages of Drake's explosion.[2] On June 23rd,
  2018, Instagram account @SonnySideUp[6] posted a Tanking the Bus Driver edition
  of the meme, garnering 43,600 likes within the first 90 days. Two days later, it
  was shared on Reddit. Shortly after, more users began using the format (examples
  below, center / right). Various Examples Search Interest External References [1]
  /r/dankmemes – whomst'd [2] Billboard – Drake Teams With Sprite for 'Spark' Campaign
  [3] Popsugar – The Internet Is Obsessed With This New Meme About How Smart People
  Are [4] Intelligencer (formerly Select All) – What Level of Brain-Meme Irony Are
  You On? [5] Mic – The expanding brain meme will take you to new frontiers of knowledge
  and understanding [6] Instagram – @SonnySideUp's Post
aside_content: MemeStatusConfirmedType:ExploitableYear2017OriginRedditTagsbrain,expanding,knowledge,whomst,intelligence,exploitable,image
  series,janskishimanski,bagelboy,galaxy brain,the-captains-on-shore-leave,sonnysideup,galaxybrain,galaxybrainfAdditional
  ReferencesFacebookMeme GeneratorReddit
added_at: '2017-02-17T18:58:52-05:00'
