name: Perfection
source: https://knowyourmeme.com/memes/perfection
keywords:
- I Prefer the Real Raven
text:
- style: upper
  color: black
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 0.5
  scale_y: 0.333
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: khaki
  font: thin
  anchor_x: 0.5
  anchor_y: 0.225
  angle: 0.0
  scale_x: 0.5
  scale_y: 0.1
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: black
  font: thick
  anchor_x: 0.0
  anchor_y: 0.333
  angle: 0.0
  scale_x: 0.5
  scale_y: 0.333
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: khaki
  font: thin
  anchor_x: 0.5
  anchor_y: 0.56
  angle: 0.0
  scale_x: 0.5
  scale_y: 0.1
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: black
  font: thick
  anchor_x: 0.0
  anchor_y: 0.666
  angle: 0.0
  scale_x: 0.5
  scale_y: 0.333
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: khaki
  font: thin
  anchor_x: 0.5
  anchor_y: 0.895
  angle: 0.0
  scale_x: 0.5
  scale_y: 0.1
  align: center
  start: 0.0
  stop: 1.0
example:
- Sebastian Shaw
- I prefer the real Darth Vader.
- Hayden Christensen
- I said, the real Darth Vader.
- Jake Lloyd
- Perfection.
overlay:
- center_x: 0.25
  center_y: 0.166
  angle: 0.0
  scale: 0.333
- center_x: 0.25
  center_y: 0.5
  angle: 0.0
  scale: 0.333
- center_x: 0.25
  center_y: 0.833
  angle: 0.0
  scale: 0.333
scraped_content: 'About Perfection refers to an exploitable image macro in which the
  character Erik Magnus Lehnsherr (Michael Fassbender), aka Magneto, in X-Men: First
  Class asks to be shown "the real X." He asks twice, and upon seeing what he is looking
  for, he says, "Perfection." What he is looking for is generally the punchline of
  the joke. Origin The scene comes from 2011''s X Men: First Class. Raven Darkhölme
  (Jennifer Lawrence), aka Mystique, a mutant with shapeshifting powers, attempts
  to seduce Erik by showing herself to him as a beautiful blonde woman (Rebecca Romijn).
  Erik responds by saying "I prefer the real Raven." Raven then shifts into the human
  form she usually presents to others. Erik presses, "I said the real Raven." Raven
  then turns into her natural blue form, to which Erik replies "Perfection." On October
  14th of that year, user jstupack uploaded the first variation of the exploitable
  to /r/funny.[1] In the post, Raven turns into actress Raven Symone before Erik says,
  "Perfection." The post gained 645 points (shown below). Spread In the following
  years, the format would prove a durable template for various jokes. After various
  plays on the word "Raven," the joke expanded to include various other "real" objects.
  For example, on May 13th, 2015, FunnyJunk user gwlk[2] uploaded a variation with
  Pepe the Frog that gained 1,111 points on the site (shown below). The format grew
  popular again in 2017 when it was adopted by the Star Wars fandom on Reddit as a
  means to compare various iterations of the franchise''s characters. On April 16th,
  user TehFlygon[3] posted a question to /r/OutOfTheLoop[3] asking about the origin
  of the template. Various Examples Search Interest External References [1] Reddit
  – /r/funny [2] FunnyJunk – The Rarest Pepe [3] Reddit – What is the "I prefer the
  real _____" meme from?'
aside_content: 'MemeStatusConfirmedType:Image Macro,Pop Culture ReferenceYear2011OriginX-Men:
  First ClassTagsxmen,magneto,exploitable,erik magnus lehnsherr,michael fassbender,raven
  darkhölme,mystique,rebecca romijn,jstupack,gwlk,tehflygon'
added_at: '2017-05-05T13:20:50-04:00'
