example:
- Clicking the 'X' on a mobile ad
- The 'X' is part of the ad
keywords:
- Disappointed Black Guy
name: Expectation vs. Reality
overlay:
- angle: 0.0
  center_x: 0.25
  center_y: 0.245
  scale: 0.492
- angle: 0.0
  center_x: 0.25
  center_y: 0.75
  scale: 0.5
scraped_content: "Disappointed Black Guy | Know Your Meme Howdy! You must login or\
  \ signup first! Already a memeber? Login Now! Don't have an account? Sign up Now!\
  \ Meme Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Disappointed Black Guy Added 11 years ago / Updated 2 years ago Confirmed\
  \ 243,192 Part of a series on Expectation vs. Reality. [View Related Entries] View\
  \ All 99 Images Featured Episode Navigation About \u2022 Origin \u2022 Spread \u2022\
  \ Various Examples \u2022 Templates \u2022 Search interest \u2022 External References\
  \ \u2022 Recent Images \u2022 Recent Videos About Disappointed Black Guy is a four-panel\
  \ reaction image macro that expresses the expectation-reality meme. The format follows\
  \ the following order: a picture of something the meme the author desires or anticipates\
  \ juxtaposes a photograph of a happy, excited man. The third panel usually reveals\
  \ the full picture of the first panel, which is different and unappealing, followed\
  \ by a picture of the same person, but now with an expression of disappointment\
  \ or shock. Origin On December 28th, 2011, Tumblr [1] user tediferous posted an\
  \ image of himself excitedly reading a new message and another picture of his disappointed\
  \ face when he sees the message features a racist slur. Within 10 years, the image\
  \ has received more than 120,000 notes (shown below). Spread On October 4th, 2012,\
  \ a Facebook fan page was created for the meme.[2] Currently, the page has over\
  \ 1,000 Likes. For example in 2015, MemeCenter [3] user yayayaya posted a variation\
  \ in which the man is disappointed to find out that he has been looking at the buttocks\
  \ of Sonic the Hedgehog. The post received more than 800 likes in four years (shown\
  \ below, left). On August 12th, 2018, Twitter[4] user @hexxem tweeted the image\
  \ with a joke about Dublin, Ireland. The post received more than 1,00 likes and\
  \ 200 retweets in one year (shown below, right). On August 15th, 2019, Redditor\
  \ [5] kayneshaw posted a variation in the /r/dankmemes subreddit. The post received\
  \ more than 51,000 points (97% upvoted) and 195 comments in 24 hours (shown below).\
  \ Various Examples Templates Search interest External References [1] Tumblr \u2013\
  \ tediferous [2] Facebook \u2013 Disappointed Black Guy [3] Memecenter \u2013 Disappointment\
  \ [4] Twitter \u2013 @hexxem's Tweet [5] Reddit \u2013 /r/dankmemes reality disappointed\
  \ expectation l\xE1zaro ramos hexxem kayneshaw we heart it siobhan yayayaya Share\
  \ Pin Related Entries 4 total What I Watched / What I Expec... Be Careful Who You\
  \ Call Ugly ... Name Brand vs. Great Value When I Take a Picture of My F... Recent\
  \ Images 99 total View All Images Recent Videos 1 total View All Videos Sign up\
  \ for our Newsletter Load 10 Comments Comments 10 total 34 Disappointed Black Guy\
  \ 243,192 1 99 10 Part of a series on Expectation vs. Reality. [View Related Entries]\
  \ Updated Mar 13, 2022 at 04:55AM EDT by Autumn Able. Added Jan 27, 2013 at 11:41PM\
  \ EST by HTK. Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i'\
  \ to view the image gallery, 'v' to view the video gallery, or 'r' to view a random\
  \ entry. Featured Episode Meme Status Confirmed Type: Exploitable Year 2011 Origin\
  \ Tumblr Tags reality, disappointed, expectation, l\xE1zaro ramos, hexxem, kayneshaw,\
  \ we heart it, siobhan, yayayaya Additional References Facebook Meme Generator Reddit\
  \ About Disappointed Black Guy is a four-panel reaction image macro that expresses\
  \ the expectation-reality meme. The format follows the following order: a picture\
  \ of something the meme the author desires or anticipates juxtaposes a photograph\
  \ of a happy, excited man. The third panel usually reveals the full picture of the\
  \ first panel, which is different and unappealing, followed by a picture of the\
  \ same person, but now with an expression of disappointment or shock. Origin On\
  \ December 28th, 2011, Tumblr [1] user tediferous posted an image of himself excitedly\
  \ reading a new message and another picture of his disappointed face when he sees\
  \ the message features a racist slur. Within 10 years, the image has received more\
  \ than 120,000 notes (shown below). Spread On October 4th, 2012, a Facebook fan\
  \ page was created for the meme.[2] Currently, the page has over 1,000 Likes. For\
  \ example in 2015, MemeCenter [3] user yayayaya posted a variation in which the\
  \ man is disappointed to find out that he has been looking at the buttocks of Sonic\
  \ the Hedgehog. The post received more than 800 likes in four years (shown below,\
  \ left). On August 12th, 2018, Twitter[4] user @hexxem tweeted the image with a\
  \ joke about Dublin, Ireland. The post received more than 1,00 likes and 200 retweets\
  \ in one year (shown below, right). On August 15th, 2019, Redditor [5] kayneshaw\
  \ posted a variation in the /r/dankmemes subreddit. The post received more than\
  \ 51,000 points (97% upvoted) and 195 comments in 24 hours (shown below). Various\
  \ Examples Templates Search interest External References [1] Tumblr \u2013 tediferous\
  \ [2] Facebook \u2013 Disappointed Black Guy [3] Memecenter \u2013 Disappointment\
  \ [4] Twitter \u2013 @hexxem's Tweet [5] Reddit \u2013 /r/dankmemes Related Entries\
  \ 4 total What I Watched / What I Expected / What I Got Be Careful Who You Call\
  \ Ugly in Middle School Name Brand vs. Great Value When I Take a Picture of My Friend\
  \ vs. When My Friend Takes a Picture of Me Recent Videos 1 total 'Disappointed Black\
  \ Guy' Meme... Disappointed Black Guy Uploaded by Zach + Add a Video Recent Images\
  \ 99 total Disappointed Black Guy Uploaded by Jaimie Hamilton Disappointed Black\
  \ Guy Uploaded by Minseung2003 Disappointed Black Guy Uploaded by Jaimie Hamilton\
  \ Disappointed Black Guy Uploaded by Jaimie Hamilton Disappointed Black Guy Uploaded\
  \ by Jaimie Hamilton Disappointed Black Guy Uploaded by Reddit Moments Disappointed\
  \ Black Guy Uploaded by Reddit Moments Disappointed Black Guy Uploaded by Reddit\
  \ Moments Disappointed Black Guy Uploaded by Marwan Sallam Disappointed Black Guy\
  \ Uploaded by Reddit Moments Disappointed Black Guy Uploaded by Reddit Moments Disappointed\
  \ Black Guy Uploaded by Reddit Moments + Add an Image View All Images Sign up for\
  \ our Newsletter Top Comment Delete Sensitive Jack Schadenfreude Jan 28, 2013 at\
  \ 01:10AM EST This definitely needs more research and work +9 Reply + Add a Comment\
  \ Comments (10) Display Comments Add a Comment Top Entries This Month Meme Saika\
  \ Kawakita Smile GIF Event Assassination of UnitedHealthcare CEO Person Luigi Mangione\
  \ UHC CEO Shooter Subculture The Ki Sisters Culture Pornography Site Whisper View\
  \ More Suggest a Change Edit History Entry Editors (13) HTK Sleuth Teh Brawler Webcomicologist\
  \ & Twitterologist Rukario Sleuth & Cataloger & Pundit Verbose Sr. Forum Moderator\
  \ & Pok\xE9mon Master Z. Database Moderator & Rage Comicologist Y F Digital Archaeologist\
  \ & Treasurer & Media Maid Matt Secretary of Memes andcallmeshirley Digital Archaeologist\
  \ & Treasurer & Collection Butler shevyrolet Digital Archaeologist & Treasurer &\
  \ Media Bus Boy Rose Abrams Entry Moderator Zach Memenator Adam Know Your Meme Universal\
  \ Champion Autumn Able Sr. Entry Moderator \u25BC + Request Editorship View All\
  \ Editors Today's Top Image Galleries Assassination of UnitedHealthcare CEO Squirrel\
  \ Girl (Doreen Green) Team Fortress 2 The Amazing Digital Circus About Our Story\
  \ Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes News\
  \ Staff Contact Extras! Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/disappointed-black-guy
template_id: dbg
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: black
  font: thin
  scale_x: 0.48
  scale_y: 0.5
  start: 0.0
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.0
  anchor_y: 0.5
  angle: 0.0
  color: black
  font: thin
  scale_x: 0.48
  scale_y: 0.5
  start: 0.0
  stop: 1.0
  style: default
text_zones: 2
