name: Expectation vs. Reality
source: https://knowyourmeme.com/memes/disappointed-black-guy
keywords:
- Disappointed Black Guy
text:
- style: default
  color: black
  font: thin
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 0.48
  scale_y: 0.5
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: black
  font: thin
  anchor_x: 0.0
  anchor_y: 0.5
  angle: 0.0
  scale_x: 0.48
  scale_y: 0.5
  align: center
  start: 0.0
  stop: 1.0
example:
- Clicking the 'X' on a mobile ad
- The 'X' is part of the ad
overlay:
- center_x: 0.25
  center_y: 0.245
  angle: 0.0
  scale: 0.492
- center_x: 0.25
  center_y: 0.75
  angle: 0.0
  scale: 0.5
scraped_content: 'About Disappointed Black Guy is a four-panel reaction image macro
  that expresses the expectation-reality meme. The format follows the following order:
  a picture of something the meme the author desires or anticipates juxtaposes a photograph
  of a happy, excited man. The third panel usually reveals the full picture of the
  first panel, which is different and unappealing, followed by a picture of the same
  person, but now with an expression of disappointment or shock. Origin On December
  28th, 2011, Tumblr [1] user tediferous posted an image of himself excitedly reading
  a new message and another picture of his disappointed face when he sees the message
  features a racist slur. Within 10 years, the image has received more than 120,000
  notes (shown below). Spread On October 4th, 2012, a Facebook fan page was created
  for the meme.[2] Currently, the page has over 1,000 Likes. For example in 2015,
  MemeCenter [3] user yayayaya posted a variation in which the man is disappointed
  to find out that he has been looking at the buttocks of Sonic the Hedgehog. The
  post received more than 800 likes in four years (shown below, left). On August 12th,
  2018, Twitter[4] user @hexxem tweeted the image with a joke about Dublin, Ireland.
  The post received more than 1,00 likes and 200 retweets in one year (shown below,
  right). On August 15th, 2019, Redditor [5] kayneshaw posted a variation in the /r/dankmemes
  subreddit. The post received more than 51,000 points (97% upvoted) and 195 comments
  in 24 hours (shown below). Various Examples Templates Search interest External References
  [1] Tumblr – tediferous [2] Facebook – Disappointed Black Guy [3] Memecenter – Disappointment
  [4] Twitter – @hexxem''s Tweet [5] Reddit – /r/dankmemes'
aside_content: MemeStatusConfirmedType:ExploitableYear2011OriginTumblrTagsreality,disappointed,expectation,lázaro
  ramos,hexxem,kayneshaw,we heart it,siobhan,yayayayaAdditional ReferencesFacebookMeme
  GeneratorReddit
added_at: '2013-01-27T23:41:10-05:00'
