example:
- Say the line, Senior Engineer!
- It depends.
keywords:
- The Simpsons
- Bart Simpson
name: Say the Line, Bart!
overlay:
- angle: 0.0
  center_x: 0.67
  center_y: 0.74
  scale: 0.23
scraped_content: "Say the Line, Bart! | Know Your Meme Namaste! You must login or\
  \ signup first! Already a memeber? Login Now! Don't have an account? Sign up Now!\
  \ Meme Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Say the Line, Bart! Added 6 years ago / Updated 10 days ago Confirmed 173,615\
  \ Part of a series on The Simpsons. [View Related Entries] View All 41 Images Navigation\
  \ About \u2022 Origin \u2022 Spread \u2022 Various Examples \u2022 Search Interest\
  \ \u2022 External References \u2022 Recent Images \u2022 Recent Videos About Say\
  \ the Line, Bart! refers to a three-panel series of exploitable stills from The\
  \ Simpsons in which the classmates of character Bart Simpson look at him expectedly,\
  \ asking him to say the catchphrase that made him famous in the episode. After he\
  \ says it dejectedly, the classmates celebrate. In the exploitables, the line Bart\
  \ says is changed. Origin The scene comes from The Simpsons episode \"Bart Gets\
  \ Famous,\" which first aired February 3rd, 1994.[1] In the scene, Milhouse asks\
  \ Bart to \"say the line,\" to which Bart dejectedly says, \"I didn't do it.\" His\
  \ classmates then erupt in applause. Spread Online, the scene is commonly parodied\
  \ by changing Bart's line of dialogue to a catchphrase from a particular subculture.\
  \ An early example posted to generator site memegen[2] shows Bart saying Fuck Her\
  \ Right In the Pussy (shown below). The February 2016 advent of Frinkiac helped\
  \ spread the meme, as more internet users had access to the screenshots and a generator\
  \ with which to make various different texts.[3] Some early examples include a post\
  \ where Bart is characterized as the Playstation (shown below, left) and a June\
  \ 29th, 2016 post to Simpsons Shitposting referencing Steamed Hams that gained over\
  \ 3,000 likes and reactions and was featured by Buzzfeed.[4] Other popular edits\
  \ include a February 5th, 2016 post to /r/pcmasterrace where the class says \"Say\
  \ the Line, Winrar\" gaining over 9,500 points (shown below, left). A May 10th,\
  \ 2018 post to /r/dankmemes about original content gained over 4,500 points (shown\
  \ below, right). Various Examples Search Interest External References [1] Wikipedia\
  \ \u2013 Bart Gets Famous [2] memegen \u2013 FHRITP [3] Frinkiac \u2013 I Didn't\
  \ Do It [4] Buzzfeed \u2013 Hundreds Of People Won't Stop Asking This Grocery Store\
  \ For Steamed Hams the simpsons bart gets famous bart snowclone image macro exploitable\
  \ Share Pin Related Entries 97 total Steamed Hams I, For One, Welcome Our New I...\
  \ Sneed's Feed and Seed Old Man Yells at Cloud View All Related Entries Recent Images\
  \ 41 total View All Images Recent Videos 4 total View All Videos Sign up for our\
  \ Newsletter Load 10 Comments Comments 10 total 20 Say the Line, Bart! 173,615 4\
  \ 41 10 Part of a series on The Simpsons. [View Related Entries] Updated Dec 13,\
  \ 2024 at 03:57PM EST by LiterallyAustin. Added May 11, 2018 at 11:51AM EDT by Adam.\
  \ Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the\
  \ image gallery, 'v' to view the video gallery, or 'r' to view a random entry. Meme\
  \ Status Confirmed Type: Exploitable, Image Macro Year 1994 Origin The Simpsons\
  \ Tags the simpsons, bart gets famous, bart, snowclone, image macro, exploitable\
  \ Additional References Meme Generator About Say the Line, Bart! refers to a three-panel\
  \ series of exploitable stills from The Simpsons in which the classmates of character\
  \ Bart Simpson look at him expectedly, asking him to say the catchphrase that made\
  \ him famous in the episode. After he says it dejectedly, the classmates celebrate.\
  \ In the exploitables, the line Bart says is changed. Origin The scene comes from\
  \ The Simpsons episode \"Bart Gets Famous,\" which first aired February 3rd, 1994.[1]\
  \ In the scene, Milhouse asks Bart to \"say the line,\" to which Bart dejectedly\
  \ says, \"I didn't do it.\" His classmates then erupt in applause. Spread Online,\
  \ the scene is commonly parodied by changing Bart's line of dialogue to a catchphrase\
  \ from a particular subculture. An early example posted to generator site memegen[2]\
  \ shows Bart saying Fuck Her Right In the Pussy (shown below). The February 2016\
  \ advent of Frinkiac helped spread the meme, as more internet users had access to\
  \ the screenshots and a generator with which to make various different texts.[3]\
  \ Some early examples include a post where Bart is characterized as the Playstation\
  \ (shown below, left) and a June 29th, 2016 post to Simpsons Shitposting referencing\
  \ Steamed Hams that gained over 3,000 likes and reactions and was featured by Buzzfeed.[4]\
  \ Other popular edits include a February 5th, 2016 post to /r/pcmasterrace where\
  \ the class says \"Say the Line, Winrar\" gaining over 9,500 points (shown below,\
  \ left). A May 10th, 2018 post to /r/dankmemes about original content gained over\
  \ 4,500 points (shown below, right). Various Examples Search Interest External References\
  \ [1] Wikipedia \u2013 Bart Gets Famous [2] memegen \u2013 FHRITP [3] Frinkiac \u2013\
  \ I Didn't Do It [4] Buzzfeed \u2013 Hundreds Of People Won't Stop Asking This Grocery\
  \ Store For Steamed Hams Related Entries 97 total Steamed Hams I, For One, Welcome\
  \ Our New Insect Overlords Sneed's Feed and Seed Old Man Yells at Cloud I Must Go\
  \ Do It For Her \"Milhouse Is Not A Meme\" Marge Krumping Principal Skinner's \"\
  Pathetic\" Homer Simpson Backs Into Bushes That's The Joke Bart, Get Out! I'm Piss!\
  \ View All Related Entries Recent Videos 4 total Say the Line, Ganon! Say the Line,\
  \ Bart! Uploaded by Sum Lu Zer SAY THE LINE, MARIO! Say the Line, Bart! Uploaded\
  \ by PWMW say the line, Bart Say the Line, Bart! Uploaded by Kalibur Kitty PSA:\
  \ Houston Say the Line, Bart! Uploaded by PYRO + Add a Video Recent Images 41 total\
  \ Say the Line, Bart! Uploaded by Reddit Moments Say the Line, Bart! Uploaded by\
  \ F1Krazy Say the Line, Bart! Uploaded by Triplem Say the Line, Bart! Uploaded by\
  \ Imabigfish Say the Line, Bart! Uploaded by Nyazilla Say the Line, Bart! Uploaded\
  \ by Reddit Moments Say the Line, Bart! Uploaded by fche Say the Line, Bart! Uploaded\
  \ by MegaDitto89 Say the Line, Bart! Uploaded by thatonebfdifan Say the Line, Bart!\
  \ Uploaded by Sum Lu Zer Say the Line, Bart! Uploaded by Lugamo Say the Line, Bart!\
  \ Uploaded by Y F + Add an Image View All Images Sign up for our Newsletter Top\
  \ Comment Delete Sensitive Nightfury Treann May 11, 2018 at 02:01PM EDT +61 Reply\
  \ + Add a Comment Comments (10) Display Comments Add a Comment Top Entries This\
  \ Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare CEO\
  \ Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (2) Adam Know\
  \ Your Meme Universal Champion andcallmeshirley Digital Archaeologist & Treasurer\
  \ & Collection Butler + Request Editorship View All Editors Today's Top Image Galleries\
  \ Assassination of UnitedHealthcare CEO Team Fortress 2 Squirrel Girl (Doreen Green)\
  \ The Amazing Digital Circus About Our Story Site Rules Policies and Guidelines\
  \ Credits Contact Meme DB Memes Episodes News Staff Contact Extras! Style Guide\
  \ RSS Feeds"
source: https://knowyourmeme.com/memes/say-the-line-bart
template_id: say
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.33
  angle: 0.0
  color: white
  font: comic
  scale_x: 1.0
  scale_y: 0.17
  start: 0.0
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.0
  anchor_y: 0.85
  angle: 0.0
  color: white
  font: comic
  scale_x: 1.0
  scale_y: 0.15
  start: 0.0
  stop: 1.0
  style: default
text_zones: 2
