name: Say the Line, Bart!
source: https://knowyourmeme.com/memes/say-the-line-bart
keywords:
- The Simpsons
- Bart Simpson
text:
- style: default
  color: white
  font: comic
  anchor_x: 0.0
  anchor_y: 0.33
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.17
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: white
  font: comic
  anchor_x: 0.0
  anchor_y: 0.85
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.15
  align: center
  start: 0.0
  stop: 1.0
example:
- Say the line, Senior Engineer!
- It depends.
overlay:
- center_x: 0.67
  center_y: 0.74
  angle: 0.0
  scale: 0.23
scraped_content: About Say the Line, Bart! refers to a three-panel series of exploitable
  stills from The Simpsons in which the classmates of character Bart Simpson look
  at him expectedly, asking him to say the catchphrase that made him famous in the
  episode. After he says it dejectedly, the classmates celebrate. In the exploitables,
  the line Bart says is changed. Origin The scene comes from The Simpsons episode
  "Bart Gets Famous," which first aired February 3rd, 1994.[1] In the scene, Milhouse
  asks Bart to "say the line," to which Bart dejectedly says, "I didn't do it." His
  classmates then erupt in applause. Spread Online, the scene is commonly parodied
  by changing Bart's line of dialogue to a catchphrase from a particular subculture.
  An early example posted to generator site memegen[2] shows Bart saying Fuck Her
  Right In the Pussy (shown below). The February 2016 advent of Frinkiac helped spread
  the meme, as more internet users had access to the screenshots and a generator with
  which to make various different texts.[3] Some early examples include a post where
  Bart is characterized as the Playstation (shown below, left) and a June 29th, 2016
  post to Simpsons Shitposting referencing Steamed Hams that gained over 3,000 likes
  and reactions and was featured by Buzzfeed.[4] Other popular edits include a February
  5th, 2016 post to /r/pcmasterrace where the class says "Say the Line, Winrar" gaining
  over 9,500 points (shown below, left). A May 10th, 2018 post to /r/dankmemes about
  original content gained over 4,500 points (shown below, right). Various Examples
  Search Interest External References [1] Wikipedia – Bart Gets Famous [2] memegen
  – FHRITP [3] Frinkiac – I Didn't Do It [4] Buzzfeed – Hundreds Of People Won't Stop
  Asking This Grocery Store For Steamed Hams
aside_content: MemeStatusConfirmedType:Exploitable,Image MacroYear1994OriginThe SimpsonsTagsthe
  simpsons,bart gets famous,bart,snowclone,image macro,exploitableAdditional ReferencesMeme
  Generator
added_at: '2018-05-11T11:51:06-04:00'
