name: Overly Attached Girlfriend
source: http://knowyourmeme.com/memes/overly-attached-girlfriend
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- i know you received my email
- because i checked your inbox
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Overly Attached Girlfriend is an advice animal image macro
  featuring webcam picture of vlogger Laina Morris and various captions portraying
  her in the stereotype of an overprotective and clingy girlfriend. Origin On June
  6th, 2012, YouTuber wzr0713 uploaded a webcam video titled "JB Fanvideo"[1] in which
  she performs a parody rendition of Justin Bieber''s latest single "Boyfriend" with
  personalized lyrics. According to Gawker''s article[2], the video was submitted
  in response to Bieber''s announcement of an online sing-off contest[3] in promoting
  his celebrity perfume "Girlfriend." If I was your girlfriend / I’d never let you
  leave / without a small recording device / taped under your sleeve I’ll always be
  checking up on you / Hey, boy, who you talking to? / Spend a day with your girl,
  I’ll be calling you my husband.” YouTuber wzr0713''s parody song, marked by its
  clingly, stalker-like lyrics, instantly drew attention from the viewers on YouTube
  and Reddit, many of whom wondered about the girl''s true intention behind making
  the video. In less than 48 hours of upload, the video received more than 1.35 million
  views. Spread On the following day of June 7th, Redditor yeahhtoast submitted a
  link to the YouTube video in a thread titled "Overly Attached Girlfriend,"[11] which
  generated more than 800 comments in the span of seven hours as well as a Quickmeme
  page[7] for an advice animal character bearing the same name. Meanwhile, many Redditors
  and YouTubers commented that the advice animal character of "Overly Attached Girlfriend"
  was nearly identical to an older image macro series known as Crazy Girlfriend Praying
  Mantis. Both the video and online reactions were subsequently picked up by numerous
  Internet culture blogs like The Daily What[13] Guyism[4], BuzzFeed[6], Jezebel[5]
  and The Daily Dot[12], not to mention its viral spread on Tumblr[13] and Facebook.
  Later that same day, a parody Twitter account[8] (@attachedGF) was launched to curate
  some of the notable captions from the series and a similar single topic Tumblr blog[9]
  was created on the following day. Identity On June 14th, 2012, Hockeys Future Forum[18]
  member Hoggy posted a link to the Facebook[19] profile (now disabled) of 20-year-old
  Laina Walker with the description "That crazy girl has a Facebook profile open now."
  On June 16th, the description for the "JB fan video" on YouTube was updated with
  links to her new Twitter[14] account and Facebook[15] page. The same day, Laina
  published her first tweet acknowledging the video''s success: I''m always amused
  by the @OvrlyAttachdGF tweets. Then I realize my face is associated with it and
  I''m slightly disturbed. Still awesome. — Laina (@laina622) June 16, 2012 On the
  Facebook page, Laina uploaded several photographs of herself (shown below) and urged
  fans to follow her on Twitter since she would be updating the Facebook page less
  frequently. Within three days, Walker accumulated over 7,800 new Twitter followers
  and 16,500 likes on Facebook. Laina has denied that Walker is her last name. On
  October 16th, The Daily Dot[41] identified OAG as Laina Morris, after she began
  creating videos to help charity organizations. Notable Examples Call Me Maybe Parody
  On June 18th, 2012, Walker uploaded a new video to her YouTube channel titled "CRJ
  Fanvideo", which featured a parody of Carly Rae Jepsen''s "Call Me Maybe" with clingy
  and overprotective lyrics similar to the original Justin Bieber video. The same
  day, Redditor StanFranXisco submitted the parody to the /r/videos subreddit in a
  post titled "Overly Attached Girlfriend''s Carly Rae Jepsen fan video." Within 24
  hours, the Reddit post accumulated over 20,300 up votes and the YouTube video accumulated
  over 1.8 million views. Overly Attached Boyfriend Spin-off attempts at creating
  a male counterpart character began on June 7th, the day after the upload of the
  "Girlfriend" fan video, with a Reddit post titled "Overly Attached Boyfriend" featuring
  a photo of a man staring creepily at the camera. Throughout the months of June and
  July, at least a dozen of user-submitted photos were used as base templates for
  advice animal-style image macros, though none of them took off until July 6th, 2012,
  when Redditor Phatrick129 submitted a picture of himself to the /r/pics subreddit
  with the title "Odd first post, but my friends keep reminding me I look like a certain
  someone."[21] The post was instantly met by a slew of comments pointing out his
  uncanny resemblance to Laina and soon reached the frontpage after receiving 26,222
  upvotes. One of the top voted comments was submitted by Redditor HertzaHaeon, which
  linked to a photoshopped "couple shot" image and an "obligatory" faceswap image
  featuring Laina and her male doppleganger. Later that same day, the Internet news
  site Daily Dot[20] posted an article titled "Meet the Overly Attached Boyfriend
  Meme," detailing the development of the meme in a chronological order. On July 7th,
  a single topic blog titled Overly Attached Boyfriend[25] was launched by Internet
  humor network Memesly and numerous image macros from the original Reddit thread
  were featured by BuzzFeed[23] and FunnyJunk.[24] On July 9th, Daily Dot posted a
  follow-up interview article[27] with Patrick Gill, the Redditor behind the newly
  dubbed Overly Attached Boyfriend. In the interview, the high school senior student
  from Arizona revealed that he decided to submit the post onto Reddit "after a little
  confidence boost from a friend." Misunderstood Girlfriend On September 3rd, 2012,
  Redditor Vinnyb90 submitted a post to the /r/AdviceAnimals[29] subreddit titled
  "Introducing, Misunderstood Girlfriend!", which included a photograph of Laina with
  the caption "Left 30 minute voicemail / butt dialed" (shown below). Within two days,
  the post received over 6,500 up votes and 280 comments. That day, 17 other "Misunderstood
  Girlfriend" image macros were submitted to the subreddit[28], four of which received
  enough up votes to reach the front page. On September 5th, the Tumblr[30] blog Pleated
  Jeans highlighted several notable examples in a post that received over 6,400 notes
  within 24 hours. The same day, additional compilations were reblogged on the Internet
  humor site Joes Daily[32] and the tech news blog Mashable.[31] As of September 6th,
  the "Misunderstood Girlfriend" Quickmeme[33] page has accumulated 75 submissions.
  The series bears many thematic similarities with the Good Girl Gina advice animal
  character, which features a stock photograph of a young brunette woman with captions
  depicting her as an altruistic mate. On September 5th, Redditor dgehen submitted
  a Good Girl Gina image macro with the caption "Replaced by Misunderstood Girlfriend
  / Doesn''t get jealous" (shown below). Within 24 hours, the post received over 5,000
  up votes. Breaking Up with Overly Attached Girlfriend On September 24th, YouTuber
  Jimmy Tatro uploaded a 3-minute skit titled "Breaking Up with Overly Attached Girlfriend"
  onto his channel LifeAccordingToJim, starring himself and Laina Walker as a couple
  going through an awkward break-up talk. On the following day, the video was submitted
  to the /r/videos subreddit, which subsequently reached the front page with more
  than 9,500 upvotes and 1240 comments. Within the first week of upload, the YouTube
  clip accumulated more than 6.3 million views. Underly Attached Girlfriend The antithetical
  character of Overly Attached Girlfriend has been brought up as early as July 4th,
  2012 with a Reddit post[35] renaming Scumbag Steve''s female counterpart Scumbag
  Stacy as the "Underly Attached Girlfriend." Submitted by Redditor prollyzooted[36],
  the post received more than 4,300 upvotes and 160 comments prior to being archived.
  However, the "Underly Attached Girlfriend" spin-off series didn''t take off until
  months later on September 29th, when Redditor anrennt98 submitted an image of American
  actress and Twilight cast member Kristen Stewart captioned with "You''re cheating?
  Cool, me too," a reference to the actress'' scandalous affair with American film
  director Rupert Sanders in July 2012. The post was well-received in the /r/adviceanimals
  subreddit[37] with 3,700 upvotes and a handful of follow-up image macro submissions.[38]
  Search Interest External References [1] YouTube – JB Fanvideo [2] Gawker – Help
  This Girl Win Justin Bieber’s ‘Girlfriend Sing-Off’ Contest or You’ll Be Sorry via
  Archive.org [3] Give Back Brands (via Wayback Machine) – Justin Bieber''s Girlfriend
  [4] BroBible (formerly Guyism) – GIRL’S JUSTIN BIEBER ‘GIRLFRIEND’ PARODY IS UNBEARABLY
  CREEPY [5] Jezebel – Meet ‘Overly Attached Girlfriend,’ Your Friday Meme [6] BuzzFeed
  – Overly Attached Girlfriend Is The Girlfriend Meme You''ve Been Waiting For [7]
  Quickmeme – Overly Attached Girlfriend [8] Twitter – Overly Attached GF [9] Tumblr
  – Overly Attached Girlfriend via Way back Machine [10] Reddit – Search Results for
  Overly Attached Girlfriend [11] Reddit – Overly Attached Girlfriend [12] Daily Dot
  – Bieber girlfriend contest spawns Overly Attached Girlfriend meme [13] The Daily
  What – Lights Out [14] Twitter – @laina622 [15] Facebook – Laina [16] Daily Mail
  – Meet Overly Attached Girlfriend! Hilarious Justin Bieber cover version spawns
  hundreds of internet memes [17] 9gag – Liana Walker aka Overly Attached Girlfriend
  [18] HF Boards – Hilarious Images Thread Part VIII [19] Facebook – lainawalker22
  [20] Daily Dot – Meet the Overly Attached Boyfriend [21] Reddit – Odd first post
  but, my friends keep reminding me I look like a certain someone… [22] Quickmeme
  – Overly Attached Boyfriend [23] BuzzFeed – Is This The Overly Attached Boyfriend?
  [24] FunnyJunk – Overly Attached Boyfriend [25] Memesly – Overly Attached Boyfriend
  [26] Huffington Post – Patrick Gill, ''Overly Attached Boyfriend,'' Looks Exactly
  Like ''Overly Attached Girlfriend'' [27] Daily Dot – Overly Attached Boyfriend Speaks
  [28] Reddit – misunderstood girlfriend [29] Reddit – Introducing Misunderstood Girlfriend
  [30] Tumblr – Pleated Jeans [31] Mashable – Overly Attached Girlfriend Evolves Into
  Misunderstood Girlfriend [32] Joes Daily – The Best of Misunderstood Girlfriend
  Memes [33] Quickmeme – Misunderstood Girlfriend [34] Reddit – Good Girl Gina on
  Misunderstood Girlfriend [35] Reddit – Scumbag Girl is Undelry Attached Girlfriend
  [36] Reddit – Underly Attached Girlfriend [37] Reddit – Search Results for Underly
  Attached Girlfriend [38] Quickmeme – Underly Attached Girlfriend Meme [39] YouTube
  – Breaking Up with Overly Attached Girlfriend [40] Reddit – Breaking Up with Overly
  Attached Girlfriend [41] The Daily Dot – Overly Attached Girlfriend uses her online
  fame for a good cause'
aside_content: MemeStatusConfirmedType:Image MacroYear2012OriginYouTubeTagsgirlfriend,overly
  attached girlfriend,attached,entry of june 2012,oag,notables of 2012,advice animals
  of 2012,advice animal,full circles of 2012,camgirl,stare,laina walker,laina morris,wzr0713,yeahhtoast,jimmy
  tatro,stanfranxisco,phatrick,crazy girlfriend memeAdditional ReferencesMeme GeneratorTwitterUrban
  DictionaryWikipediaYoutube Channel
added_at: '2012-06-07T15:56:32-04:00'
