example:
- Pls throw??
- NO TAKE!!
- ONLY THROW
keywords:
- null
name: No Take, Only Throw
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "No Take, Only Throw | Know Your Meme Yo Yo! You must login or signup\
  \ first! Already a memeber? Login Now! Don't have an account? Sign up Now! Meme\
  \ Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO No Take, Only Throw Added 6 years ago / Updated 5 years ago Confirmed 225,074\
  \ View All 34 Images Navigation About \u2022 Origin \u2022 Spread \u2022 Various\
  \ Examples \u2022 Search Interest \u2022 External References \u2022 Recent Images\
  \ About No Take, Only Throw refers to a webcomic strip in which a dog wants to play\
  \ fetch with its owner by asking \"please throw?\" in reference to the toy in its\
  \ mouth. However when the owner reaches for the toy, the dog says \"No take. Only\
  \ throw.\" The comic became an exploitable in which the dog is depicted as various\
  \ characters making contradictory demands. Origin The original comic was posted\
  \ July 18th, 2015 by Tumblr user cupcakelogic,[1] gaining over 293,000 notes (shown\
  \ below). Spread On November 15th, 2015, Imgur user PapaDap88 posted a real-life\
  \ recreation of the comic using their dog, gaining over 5,200 points on the site\
  \ (shown below, left). One of the earliest exploitable variations of the comic was\
  \ posted to Imgur on September 5th, 2015 (shown below, right). In the following\
  \ years, the comic would see many more exploitable variations in which the dog was\
  \ depicted as different characters making various unreasonable demands. One of the\
  \ more popular examples was posted by Twitter user @biggustiggus mocking Boomers\
  \ for demanding younger generations spend money without providing higher wages,\
  \ gaining over 14,000 retweets and 30,000 likes (shown below, left). On May 30th,\
  \ 2018, Tumblr user ink-quill-coffee posted a version mocking Todd Howard, gaining\
  \ over 800 notes (shown below, right). Various Examples Search Interest External\
  \ References [1] Tumblr \u2013 cupcakelogic comic dog tumblr Share Pin Recent Images\
  \ 34 total View All Images Recent Videos 0 total There are no recent videos. Sign\
  \ up for our Newsletter Load 13 Comments Comments 13 total 14 No Take, Only Throw\
  \ 225,081 0 34 13 Updated Feb 03, 2019 at 06:20AM EST by Y F. Added Nov 21, 2018\
  \ at 10:01AM EST by Adam. Like us on Facebook! Like 1.8M Share Save Tweet PROTIP:\
  \ Press 'i' to view the image gallery, 'v' to view the video gallery, or 'r' to\
  \ view a random entry. Meme Status Confirmed Type: Exploitable Year 2015 Origin\
  \ Tumblr Tags comic, dog, tumblr About No Take, Only Throw refers to a webcomic\
  \ strip in which a dog wants to play fetch with its owner by asking \"please throw?\"\
  \ in reference to the toy in its mouth. However when the owner reaches for the toy,\
  \ the dog says \"No take. Only throw.\" The comic became an exploitable in which\
  \ the dog is depicted as various characters making contradictory demands. Origin\
  \ The original comic was posted July 18th, 2015 by Tumblr user cupcakelogic,[1]\
  \ gaining over 293,000 notes (shown below). Spread On November 15th, 2015, Imgur\
  \ user PapaDap88 posted a real-life recreation of the comic using their dog, gaining\
  \ over 5,200 points on the site (shown below, left). One of the earliest exploitable\
  \ variations of the comic was posted to Imgur on September 5th, 2015 (shown below,\
  \ right). In the following years, the comic would see many more exploitable variations\
  \ in which the dog was depicted as different characters making various unreasonable\
  \ demands. One of the more popular examples was posted by Twitter user @biggustiggus\
  \ mocking Boomers for demanding younger generations spend money without providing\
  \ higher wages, gaining over 14,000 retweets and 30,000 likes (shown below, left).\
  \ On May 30th, 2018, Tumblr user ink-quill-coffee posted a version mocking Todd\
  \ Howard, gaining over 800 notes (shown below, right). Various Examples Search Interest\
  \ External References [1] Tumblr \u2013 cupcakelogic Recent Videos There are no\
  \ videos currently available. + Add a Video Recent Images 34 total No Take, Only\
  \ Throw Uploaded by BuccaneerMarx No Take, Only Throw Uploaded by KoimanZX No Take,\
  \ Only Throw Uploaded by JapanYoshiPlz No Take, Only Throw Uploaded by Vulture051\
  \ No Take, Only Throw Uploaded by Dym Sohin No Take, Only Throw Uploaded by Excitebot\
  \ theLEGO No Take, Only Throw Uploaded by Philipp No Take, Only Throw Uploaded by\
  \ Lugamo No Take, Only Throw Uploaded by Bilbo Swaggins No Take, Only Throw Uploaded\
  \ by hidralalo No Take, Only Throw Uploaded by hidralalo No Take, Only Throw Uploaded\
  \ by Twist + Add an Image View All Images Sign up for our Newsletter Top Comments\
  \ Delete Sensitive 12monkehs Nov 22, 2018 at 01:10PM EST +41 Reply Delete Sensitive\
  \ blanisquid Nov 21, 2018 at 01:31PM EST the original comic is so cute and true\
  \ to life that all of these memes just look terrible now +41 Reply + Add a Comment\
  \ Comments (13) Display Comments Add a Comment Top Entries This Month Meme Saika\
  \ Kawakita Smile GIF Event Assassination of UnitedHealthcare CEO Person Luigi Mangione\
  \ UHC CEO Shooter Subculture The Ki Sisters Culture Pornography Site Whisper View\
  \ More Suggest a Change Edit History Entry Editors (2) Adam Know Your Meme Universal\
  \ Champion Y F Digital Archaeologist & Treasurer & Media Maid + Request Editorship\
  \ View All Editors Today's Top Image Galleries Assassination of UnitedHealthcare\
  \ CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing Digital Circus About\
  \ Our Story Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes\
  \ News Staff Contact Extras! Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/no-take-only-throw
template_id: ntot
text:
- align: center
  anchor_x: 0.055
  anchor_y: 0.08
  angle: 12.0
  color: black
  font: thin
  scale_x: 0.21
  scale_y: 0.15
  start: 0.1
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.46
  anchor_y: 0.15
  angle: 0.0
  color: black
  font: thin
  scale_x: 0.18
  scale_y: 0.15
  start: 0.4
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.7
  anchor_y: 0.135
  angle: 0.0
  color: black
  font: thick
  scale_x: 0.25
  scale_y: 0.15
  start: 0.7
  stop: 1.0
  style: upper
text_zones: 3
