name: No Take, Only Throw
source: https://knowyourmeme.com/memes/no-take-only-throw
keywords:
- null
text:
- style: default
  color: black
  font: thin
  anchor_x: 0.055
  anchor_y: 0.08
  angle: 12.0
  scale_x: 0.21
  scale_y: 0.15
  align: center
  start: 0.1
  stop: 1.0
- style: default
  color: black
  font: thin
  anchor_x: 0.46
  anchor_y: 0.15
  angle: 0.0
  scale_x: 0.18
  scale_y: 0.15
  align: center
  start: 0.4
  stop: 1.0
- style: upper
  color: black
  font: thick
  anchor_x: 0.7
  anchor_y: 0.135
  angle: 0.0
  scale_x: 0.25
  scale_y: 0.15
  align: center
  start: 0.7
  stop: 1.0
example:
- Pls throw??
- NO TAKE!!
- ONLY THROW
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About No Take, Only Throw refers to a webcomic strip in which a dog
  wants to play fetch with its owner by asking "please throw?" in reference to the
  toy in its mouth. However when the owner reaches for the toy, the dog says "No take.
  Only throw." The comic became an exploitable in which the dog is depicted as various
  characters making contradictory demands. Origin The original comic was posted July
  18th, 2015 by Tumblr user cupcakelogic,[1] gaining over 293,000 notes (shown below).
  Spread On November 15th, 2015, Imgur user PapaDap88 posted a real-life recreation
  of the comic using their dog, gaining over 5,200 points on the site (shown below,
  left). One of the earliest exploitable variations of the comic was posted to Imgur
  on September 5th, 2015 (shown below, right). In the following years, the comic would
  see many more exploitable variations in which the dog was depicted as different
  characters making various unreasonable demands. One of the more popular examples
  was posted by Twitter user @biggustiggus mocking Boomers for demanding younger generations
  spend money without providing higher wages, gaining over 14,000 retweets and 30,000
  likes (shown below, left). On May 30th, 2018, Tumblr user ink-quill-coffee posted
  a version mocking Todd Howard, gaining over 800 notes (shown below, right). Various
  Examples Search Interest External References [1] Tumblr – cupcakelogic
aside_content: MemeStatusConfirmedType:ExploitableYear2015OriginTumblrTagscomic,dog,tumblr
added_at: '2018-11-21T10:01:01-05:00'
