name: Baby Insanity Wolf
source: http://knowyourmeme.com/memes/baby-insanity-wolf
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- gets iced coffee
- in the winter
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About Baby Insanity Wolf is an advice animal image macro series based
  on a photograph of a wolf cub howling and various captions describing small acts
  of defiance often perceptible only to the person carrying them out, in a similar
  vein to those highlighted in "Thug Life" remixes. Origin As the name suggests, the
  series can be seen as the diminutive cousin of Insanity Wolf. On June 20th, 2012,
  the baby wolf photo was posted to Baby Animal Zoo by a user named Zookeeper Joe[3].
  That same day, the photo was featured in a blog post titled "Awooo! You’ll Howl
  For These Wolf Pups" by Zookeeper Joe.[4] Previous to that, on June 20th, 2011,
  a cropped version of the same photograph was uploaded as part of a post titled "End
  Lethal Wolf Management" on the site BTC4Animals.com.[5] Spread The earliest iteration
  of the meme was posted to Reddit on December 8th, 2013 by /u/smith1225 in a post
  titled "How I feel about a lot of the new Insanity Wolf postings lately", poking
  fun at the perceived milquetoast nature of recent Insanity Wolf submissions (pictured
  below, left).[1] The post received 2,934 points (96% upvoted) and 512 comments before
  being archived. Another post on Reddit, made on December 9th, titled "Baby Insanity
  Wolf doesn't live by your rules", was submitted by /u/SpaceToeJam, and received
  2080 upvotes and 339 comments (pictured below, right)[2]. Various Examples Search
  Interest External References [1] Reddit – How I feel about a lot of the new Insanity
  Wolf postings lately. [2] Reddit – Baby Insanity Wolf doesn't live by your rules
  [3] Baby Animal Zoo – Gray Wolf Howl [4] Baby Animal Zoo – Awooo! You’ll Howl For
  These Wolf Pups. [5] BTC4Animals – End Lethal Wolf Management [6] Reddit – Search
  Results for 'Baby Insanity Wolf' [7] Reddit – Baby Insanity Wolf Doesn't Live By
  Your Rules [8] Reddit – /r/firstworldanarchists
aside_content: MemeStatusConfirmedType:Image MacroYear2013OriginRedditTagsimage macros,wolf,insanity
  wolf,advice animalsAdditional ReferencesMeme GeneratorReddit
added_at: '2015-02-19T20:42:53-05:00'
