name: Bongo Cat
source: https://knowyourmeme.com/memes/bongo-cat
keywords:
- null
text:
- style: default
  color: black
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 0.48
  scale_y: 0.5
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: black
  font: thick
  anchor_x: 0.0
  anchor_y: 0.5
  angle: 0.0
  scale_x: 0.48
  scale_y: 0.5
  align: center
  start: 0.0
  stop: 1.0
example:
- Any sound when you're trying to sleep
- Max volume alarm when you have to wake up
overlay:
- center_x: 0.25
  center_y: 0.25
  angle: 0.0
  scale: 0.5
- center_x: 0.25
  center_y: 0.75
  angle: 0.0
  scale: 0.5
scraped_content: About Bongo Cat refers to an animation of a cat appearing to play
  the bongos that has been used in various remix videos to make it appear as though
  the cat is playing along to different songs. After the original video grew popular,
  people made different versions of the video showing the cat playing other instruments
  or a variant of the cat with muscular arms banging on the table. Origin On May 7th,
  2018, Twitter user @DitzyFlama responded to Twitter user @StrayRogue's GIF of an
  animated cat slapping a table by posting a video in which he'd edited the GIF to
  include bongos and added the song "Athletic" from the Super Mario World soundtrack.
  The tweet gained over 3,800 retweets and 7,000 likes. pic.twitter.com/2LZlM2FYXm—
  DitzyFlama (@DitzyFlama) May 7, 2018 Spread On May 14th, the clip was posted to
  YouTube by user anon eats crayons (shown below, left). On May 20th, user GarinBadger
  uploaded a version of the video that played for the entire duration of "Athletic,"
  gaining over 61,000 views (shown below, right). In the following months, remixes
  began appearing on YouTube that featured the cat playing other instruments. On June
  7th, YouTube user Kirk Keely posted an edit in which the cat plays "Robot Rock"
  by Daft Punk on electric guitar (shown below, left). On September 8th, YouTuber
  BananaManPlays made a Running In the 90s parody of the animation, gaining over 41,000
  views (shown below, right). Around the same time, DitzyFlama began posting more
  versions of the meme, including a "Through the Fire and the Flames" edit (shown
  below, top) and a "Take On Me" edit (shown below, bottom). pic.twitter.com/mXhV3XKfN3—
  DitzyFlama (@DitzyFlama) September 9, 2018 pic.twitter.com/Rty3wUup0k— DitzyFlama
  (@DitzyFlama) September 9, 2018 Muscular Cat Variations In April of 2022, comparative
  Bongo Cat memes using a template that has a muscular Bongo Cat representing one
  concept and a weaker Bongo Cat representing a similar concept. One of the earliest
  examples was posted in /r/memes[1] by user ludicrosity548 on April 26th, 2022, gaining
  over 153,000 points in three days (shown below). The post was then crossposted to
  /r/MemeTemplatesOfficial[2] that day, gaining over 3,000 points.[2] Other popular
  examples on Reddit include an April 28th post by ludicrosity548 that gained over
  23,000 points in /r/memes[3] (shown below, left). The same day, user elwl8 posted
  an example that gained over 98,000 points in /r/memes[4] (shown below, right). Various
  Examples pic.twitter.com/ALLyGfZUkM— Ice Cream Sandwich (@ICSandwichGuy) September
  9, 2018 pic.twitter.com/SRVWRDqXpP— Fireburn (@fireburn02) September 9, 2018 pic.twitter.com/msKOf1L0s1—
  DitzyFlama (@DitzyFlama) September 10, 2018 Search Interest External References
  [1] Reddit – /r/memes [2] Reddit – /r/MemeTemplatesOfficial [3] Reddit – /r/memes
  [4] Reddit – /r/memes
aside_content: MemeStatusConfirmedType:Image Macro,Remix,Viral VideoYear2018OriginYouTubeTagscat,ditzyflama,remix,instruments,bongocat,anon
  eats crayons,garinbadger,kirk keely,bananamanplays,cat banging table,cat hitting
  table,muscular cat pounding on table,gif
added_at: '2018-09-10T11:16:21-04:00'
