name: Feels Good
source: https://knowyourmeme.com/memes/feels-good
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- ''
- feels good
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About Feels Good, not to be confused with Feels Good, Man, is an
  exploitable image of a man looking very satisfied while touching his face with both
  hands. On 4chan, the image is used to express satisfaction in response to another
  post. Origin The template image was created from a stock image of a man washing
  his face (shown below, left), which has often been used in skin care ads and blog
  posts.[6] The origin of the outline image (shown below, right) is unknown but is
  rumored to have been posted in the /b/ (random) board on 4chan sometime in 2011.
  Spread On August 28th, 2012, a thread was submitted to the /sp/ (sports) board on
  4chan,[1] which featured a version of the Feels Good template image with a superimposed
  That Feel face (shown below, left). On December 20th, 2012, NeoGAF[4] Forums member
  The Chris submitted a Tom Cruise adaptation of the original stock photo (shown below,
  right). On April 10th, 2013, Facepunch Forums[5] member whatthe posted the Feels
  Good exploitable to a thread of images edited to contain a continuous stream of
  running water (shown below, left). Immediately after, forum member <V()LT> replied
  by posting the Feels Good stock image to the same thread (shown below, right). On
  April 13th, NeoGAF Forums[6] member Atramental posted several examples in a "Pics
  that make you laugh" thread. On July 26th, a Legend of Zelda-themed Feels Good image
  was posted to a thread in the /vg/ (video games) board on 4chan[3] (shown below,
  left). On July 28th, an anonymous 4chan[2] user submitted an edited image made to
  look like a character from the online first-person shooter game Planetside 2 (shown
  below, right) to a thread on the /vg/ board. Notable Examples Search Interest External
  References [1] Foolz.us – /s/ Sports [2] Foolz.us – /vg/ [3] Foolz.us – /vg/ [4]
  NeoGAF – Pics that make you laugh [5] Facepunch via Wayback Machine – Continue the
  line [6] Google Image Search – men skin care [6] NeoGAF – pics that make you laugh
aside_content: MemeStatusConfirmedType:ExploitableYear2011Origin4chanTagsimage macro,karutchan,int,exploitable
added_at: '2011-06-13T15:03:04-04:00'
