example:
- ''
- feels good
keywords:
- null
name: Feels Good
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Feels Good | Know Your Meme Hauu! You must login or signup first!\
  \ Already a memeber? Login Now! Don't have an account? Sign up Now! Meme Encyclopedia\
  \ All Cultures Events People Sites Subcultures Videos Submit \u2192 Images Trending\
  \ Most Commented Most Favorited High Score Low Score Most Viewed All Templates Upload\
  \ an Image Articles News Explainers Collections Interviews Meme Insider Magazine\
  \ More Discord Newsletter Episodes Forums Meme Store Login Abstract user icon Memes\
  \ Categories Trending News Images Trending Images Videos Trending Videos Editorials\
  \ Meme Insider Magazine Newsletter Policies and Guidelines Meme Store Old site Login\
  \ Know Your Meme is the property of Literally Media \xA92024 Literally Media. All\
  \ Rights Reserved. This image Of Woman Confidently Strolling Through A Glass Panel\
  \ Has Been A Redraw Format Since 2021 Three Years Ago, This Boar's Head 'Exploded'\
  \ Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess Memes Turns Two Years\
  \ Old Today Phrase 'The Fridge Protects The Snacks' A Growing Favorite Among Pickup\
  \ Artist Influencers Jamie G, The Bosh British Charva, Has Taken Over TikTok With\
  \ His Signature 'Oh Cherie Amour' Sound Also Trending: Honey Extension Influencer\
  \ Scam Renegade Raider Copypasta Assassination of UnitedHealthcare CEO Feels Good\
  \ Added 13 years ago / Updated about 17 hours ago Confirmed 911,086 View All 302\
  \ Images Navigation About \u2022 Origin \u2022 Spread \u2022 Notable Examples \u2022\
  \ Search Interest \u2022 External References \u2022 Recent Images \u2022 Recent\
  \ Videos About Feels Good, not to be confused with Feels Good, Man, is an exploitable\
  \ image of a man looking very satisfied while touching his face with both hands.\
  \ On 4chan, the image is used to express satisfaction in response to another post.\
  \ Origin The template image was created from a stock image of a man washing his\
  \ face (shown below, left), which has often been used in skin care ads and blog\
  \ posts.[6] The origin of the outline image (shown below, right) is unknown but\
  \ is rumored to have been posted in the /b/ (random) board on 4chan sometime in\
  \ 2011. Spread On August 28th, 2012, a thread was submitted to the /sp/ (sports)\
  \ board on 4chan,[1] which featured a version of the Feels Good template image with\
  \ a superimposed That Feel face (shown below, left). On December 20th, 2012, NeoGAF[4]\
  \ Forums member The Chris submitted a Tom Cruise adaptation of the original stock\
  \ photo (shown below, right). On April 10th, 2013, Facepunch Forums[5] member whatthe\
  \ posted the Feels Good exploitable to a thread of images edited to contain a continuous\
  \ stream of running water (shown below, left). Immediately after, forum member <V()LT>\
  \ replied by posting the Feels Good stock image to the same thread (shown below,\
  \ right). On April 13th, NeoGAF Forums[6] member Atramental posted several examples\
  \ in a \"Pics that make you laugh\" thread. On July 26th, a Legend of Zelda-themed\
  \ Feels Good image was posted to a thread in the /vg/ (video games) board on 4chan[3]\
  \ (shown below, left). On July 28th, an anonymous 4chan[2] user submitted an edited\
  \ image made to look like a character from the online first-person shooter game\
  \ Planetside 2 (shown below, right) to a thread on the /vg/ board. Notable Examples\
  \ Search Interest External References [1] Foolz.us \u2013 /s/ Sports [2] Foolz.us\
  \ \u2013 /vg/ [3] Foolz.us \u2013 /vg/ [4] NeoGAF \u2013 Pics that make you laugh\
  \ [5] Facepunch via Wayback Machine \u2013 Continue the line [6] Google Image Search\
  \ \u2013 men skin care [6] NeoGAF \u2013 pics that make you laugh image macro karutchan\
  \ int exploitable Share Pin Recent Images 302 total View All Images Recent Videos\
  \ 2 total View All Videos Sign up for our Newsletter Load 23 Comments Comments 23\
  \ total 103 Feels Good 911,086 2 302 23 Updated Dec 23, 2024 at 04:09PM EST by LiterallyAustin.\
  \ Added Jun 13, 2011 at 03:03PM EDT by OCtaPuS. Like us on Facebook! Like 1.8M Share\
  \ Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the video\
  \ gallery, or 'r' to view a random entry. Meme Status Confirmed Type: Exploitable\
  \ Year 2011 Origin 4chan Tags image macro, karutchan, int, exploitable About Feels\
  \ Good, not to be confused with Feels Good, Man, is an exploitable image of a man\
  \ looking very satisfied while touching his face with both hands. On 4chan, the\
  \ image is used to express satisfaction in response to another post. Origin The\
  \ template image was created from a stock image of a man washing his face (shown\
  \ below, left), which has often been used in skin care ads and blog posts.[6] The\
  \ origin of the outline image (shown below, right) is unknown but is rumored to\
  \ have been posted in the /b/ (random) board on 4chan sometime in 2011. Spread On\
  \ August 28th, 2012, a thread was submitted to the /sp/ (sports) board on 4chan,[1]\
  \ which featured a version of the Feels Good template image with a superimposed\
  \ That Feel face (shown below, left). On December 20th, 2012, NeoGAF[4] Forums member\
  \ The Chris submitted a Tom Cruise adaptation of the original stock photo (shown\
  \ below, right). On April 10th, 2013, Facepunch Forums[5] member whatthe posted\
  \ the Feels Good exploitable to a thread of images edited to contain a continuous\
  \ stream of running water (shown below, left). Immediately after, forum member <V()LT>\
  \ replied by posting the Feels Good stock image to the same thread (shown below,\
  \ right). On April 13th, NeoGAF Forums[6] member Atramental posted several examples\
  \ in a \"Pics that make you laugh\" thread. On July 26th, a Legend of Zelda-themed\
  \ Feels Good image was posted to a thread in the /vg/ (video games) board on 4chan[3]\
  \ (shown below, left). On July 28th, an anonymous 4chan[2] user submitted an edited\
  \ image made to look like a character from the online first-person shooter game\
  \ Planetside 2 (shown below, right) to a thread on the /vg/ board. Notable Examples\
  \ Search Interest External References [1] Foolz.us \u2013 /s/ Sports [2] Foolz.us\
  \ \u2013 /vg/ [3] Foolz.us \u2013 /vg/ [4] NeoGAF \u2013 Pics that make you laugh\
  \ [5] Facepunch via Wayback Machine \u2013 Continue the line [6] Google Image Search\
  \ \u2013 men skin care [6] NeoGAF \u2013 pics that make you laugh Recent Videos\
  \ 2 total We Love Girls Feels Good Uploaded by LilousKindOfMovie Heavy Feel Guy\
  \ Feels Good Uploaded by crusty + Add a Video Recent Images 302 total Feels Good\
  \ Uploaded by Evilthing Feels Good Uploaded by Smuggest Frog Feels Good Uploaded\
  \ by Gnosys Feels Good Uploaded by DJ Some Idiot Feels Good Uploaded by The Anglo\
  \ Feels Good Uploaded by Mordheyn Feels Good Uploaded by The Greek Anon Feels Good\
  \ Uploaded by Hamkecc Feels Good Uploaded by Hamkecc Feels Good Uploaded by stinky2000\
  \ Feels Good Uploaded by Y F Feels Good Uploaded by Whitest Man in Argentina + Add\
  \ an Image View All Images Sign up for our Newsletter Top Comments Delete Sensitive\
  \ Rainbow Crash May 03, 2015 at 11:44AM EDT >widely used for years >in submission\
  \ for years +14 Reply Delete Sensitive Random Bot Sep 03, 2015 at 03:07AM EDT Yeah,\
  \ this happened recently and it seems a lot of people took it seriously. +8 Reply\
  \ + Add a Comment Comments (23) Display Comments Add a Comment Top Entries This\
  \ Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare CEO\
  \ Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (9) OCtaPuS\
  \ YouTube Scatologist amanda b. Meme Librarian Fun Police Jr. Researcher & Commentator\
  \ Don Administrator & Meme Daddy \xAD\xAD\xADAlex Mercer Entry Moderator & YouTube\
  \ Scatologist Z. Database Moderator & Rage Comicologist andcallmeshirley Digital\
  \ Archaeologist & Treasurer & Collection Butler Y F Digital Archaeologist & Treasurer\
  \ & Media Maid shevyrolet Digital Archaeologist & Treasurer & Media Bus Boy \u25BC\
  \ + Request Editorship View All Editors Today's Top Image Galleries Assassination\
  \ of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing\
  \ Digital Circus About Our Story Site Rules Policies and Guidelines Credits Contact\
  \ Meme DB Memes Episodes News Staff Contact Extras! Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/feels-good
template_id: feelsgood
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
