name: Hipster Barista
source: http://knowyourmeme.com/memes/hipster-barista
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- puts coffee deal on Groupon
- rolls eyes when you actually use it
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Hipster Barista is an image macro series featuring a tattoo
  covered man wearing a black v-neck t-shirt, glasses and scarf with a scowling expression.
  Influenced by the common "hipster" stereotypes of being judgmental yet hypocritical,
  Hipster Barista acknowledges the snobby side of American coffee culture. See also:
  Hipster Kitty and Hipster Ariel. Origin The first noted instance of Hipster Barista
  was uploaded on August 24, 2011 as a Quickmeme[2] submission with the caption “I
  got this tattoo for my love of coffee / I got this one because it’s ironic.” On
  August 25th, 2011, a link to another Quickmeme submission was posted in Reddit''s
  /r/AdviceAnimals[8] subreddit, which featured the caption "Che Guevara changed my
  life / Manager at Starbucks" and received 2,872 up votes (as of September 6th).
  Spread The restaurant & bar review blog Eater.com posted an article titled "The
  Hipster Barista Meme Is a Thing Now"[3] on August, 26, 2011. They identified the
  man in the original photograph as Dustin Mattson, a "coffee boss" at Octane Coffee
  in Atlanta, GA who placed 5th at the Southeast Regional Barista Competition 2010
  and 27th place at the US Barista Championship 2010. On August 26, 2011, Dustin tweeted
  about the notoriety stating "yeah it''s real representative of what I do to feed
  my family."[5] On August 29, 2011, Eater.com posted an interview with Dustin[4]
  in which he talks about how seriously he takes his job. "I do find it discouraging
  and disappointing that there was so much exposure brought to an attempt at making
  a joke of a culinary industry and the professional barista. To me, it''s very telling
  on how we laud farm-to-table food, craft beer, cocktail mixology, but it''s ok to
  have no respect for the specialty coffee world and the people who are committed
  to it." On August 30th, several instances of the image macro popped up on both the
  Sherdog Forums[6] and Bodybuilding.com Forums.[7] On September 4th, 2011, a Facebook
  fan page[10] was created that has 7 likes as of September 6th, 2011. Additional
  derivatives can be found on Tumblr[9], and the Advice Animals subreddit.[11] Notable
  Derivatives Template External References [1] Coffee Snobology – Coffee Snob Archetypes
  / 9-29-2010 [2] Quickmeme – Hipster Barista / 8-24-2011 [3] Eater.com – The Hipster
  Barista Meme Is a Thing Now / 8-26-2011 [4] Eater.com – Dustin Mattson, the ''Hipster
  Barista,'' Speaks / 8/29/2011 [5] Twitter.com/DustinColeMmm – yeah it''s real representative
  of what I do to feed my family. / 8/26/2011 [6] Sherdog Forums – Hipster Barista
  / 8/30/2011 [7] Bodybuilding.com Forums = Hipster Barista Meme / 8/30/2011 [8] Reddit
  – Hipster Barista [9] Tumblr – #hipster barista [10] Facebook – Hipster Barista
  [11] Reddit – hipster barista'
aside_content: MemeStatusConfirmedYear2011OriginUnknownTagsimage macro,hipster,hipster
  kitty,coffee,social stereotype,glasses
added_at: '2011-09-03T01:46:33-04:00'
