example:
- yo dawg
- i heard you like memes
keywords:
- null
name: Xzibit Yo Dawg
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Xzibit Yo Dawg | Know Your Meme 'lo! You must login or signup first!\
  \ Already a memeber? Login Now! Don't have an account? Sign up Now! Meme Encyclopedia\
  \ All Cultures Events People Sites Subcultures Videos Submit \u2192 Images Trending\
  \ Most Commented Most Favorited High Score Low Score Most Viewed All Templates Upload\
  \ an Image Articles News Explainers Collections Interviews Meme Insider Magazine\
  \ More Discord Newsletter Episodes Forums Meme Store Login Abstract user icon Memes\
  \ Categories Trending News Images Trending Images Videos Trending Videos Editorials\
  \ Meme Insider Magazine Newsletter Policies and Guidelines Meme Store Old site Login\
  \ Know Your Meme is the property of Literally Media \xA92024 Literally Media. All\
  \ Rights Reserved. This image Of Woman Confidently Strolling Through A Glass Panel\
  \ Has Been A Redraw Format Since 2021 Three Years Ago, This Boar's Head 'Exploded'\
  \ Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess Memes Turns Two Years\
  \ Old Today Phrase 'The Fridge Protects The Snacks' A Growing Favorite Among Pickup\
  \ Artist Influencers Jamie G, The Bosh British Charva, Has Taken Over TikTok With\
  \ His Signature 'Oh Cherie Amour' Sound Also Trending: Honey Extension Influencer\
  \ Scam Renegade Raider Copypasta Assassination of UnitedHealthcare CEO Xzibit Yo\
  \ Dawg Added 15 years ago / Updated about 16 hours ago Confirmed 2,822,317 View\
  \ All 730 Images Featured Episode Navigation About \u2022 Origin \u2022 Spread \u2022\
  \ Notable Examples \u2022 Search Interest \u2022 External References \u2022 Recent\
  \ Images \u2022 Recent Videos About Yo Dawg, or Sup Dawg, is an image macro series\
  \ based on portrait shots of American hip hop artist Alvin Nathaniel Joiner,[10]\
  \ better known by his stage name Xzibit, and humorous captions that are composed\
  \ around the recursive phrasal template \"Yo Dawg, I herd you like (noun X), so\
  \ I put an (noun X) in your (noun Y) so you can (verb Z) while you (verb Z).\" Since\
  \ rising to popularity in early 2007, the series has been considered one of the\
  \ most well-known and longest lasting examples of recursive humor on the Internet.\
  \ Origin The original image macro first appeared on 4chan in early 2007 and experienced\
  \ a resurgence in late 2008 on Reddit, Tumblr, and social networking sites. The\
  \ Yo Dawg series has a unique characteristic in being recursive. This multi-layered\
  \ structure in the Yo Dawg formula makes it reminiscent of the \"strange loops\"\
  \ described in Douglas Hofstadter's G\xF6del, Escher, Bach. The original photograph\
  \ of Xzibit comes from a set of studio portraits that were originally used to promote\
  \ the 2006 sports drama film Gridiron Gang, in which the rapper plays the role of\
  \ a minor character named Malcolm Moore. MTV Pimp My Ride While Xzibit initially\
  \ began his career in the entertainment industry as a rapper from Los Angeles, his\
  \ mainstream breakthrough came almost a decade later as the host of the MTV show\
  \ Pimp My Ride, which ran for six seasons from 2004 to 2007. In the show, Xzibit\
  \ gained a reputation for adding luxurious amenities and equipments like fish tanks,\
  \ clothes dryers and fireplaces into the participant's car, presumably without consent.\
  \ Spread Derivatives Standard: {yo,sup} dawg, I herd you like X, so I put an X in\
  \ your Y so you can VERB while you VERB Repetitive: {yo,sup} dawg, I herd you like\
  \ X, so I put an X in your X so you can X while you X Abstract: {yo,sup} dawg, I\
  \ herd you like X, so I put an Y in your Z so you can VERB while you VERB Xzibit's\
  \ Reaction The explosive popularity of microblogging service Twitter has reached\
  \ celebrities, Xzibit included. In one of his first tweets he decries his embodiment\
  \ as a meme ( View Tweet ), which led to the creation of this image macro: Several\
  \ days later, he rescinded his criticism, saying \"i'm not mad @ you\" (View Tweet).\
  \ In the final stage of celeb-o-meme -- \"acceptance\" -- Xzibit embraces the yo\
  \ dawg, attempting to his own: View Tweet Notable Examples Search Interest External\
  \ References [1] TV.com \u2013 MTV Pimp My Ride Episode 4 [2] TV.com \u2013 MTV\
  \ Pimp My Ride Episode 5 [3] TV.com \u2013 MTV Pimp My Ride Episode 6 [4] Superior\
  \ Pics \u2013 Gridiron Gang Film Promotion [5] Tumblr \u2013 Yo Dawg [6] Tumblr\
  \ \u2013 YoYoDawgDawg [7] Tumblr \u2013 Yo Dawg Pics [8] Urban Dictionary \u2013\
  \ Yo Dawg [9] Yo Dawg Yo \u2013 Yo Dawg / Sup Dawg [10] IMDB \u2013 Xzibit Biography\
  \ image macro rap mtv nested function celebrity catchphrase twitter recursion xzibit\
  \ pop culture hip hop photoshop meme reaction image strange loops pimp my ride mtv's\
  \ pimp my ride alvin nathaniel joiner douglas hofstadter malcolm moore Share Pin\
  \ Recent Images 730 total View All Images Recent Videos 11 total View All Videos\
  \ Sign up for our Newsletter Load 96 Comments Comments 96 total 258 Xzibit Yo Dawg\
  \ 2,822,317 11 730 96 Updated Dec 23, 2024 at 03:38PM EST by LiterallyAustin. Added\
  \ Jan 01, 2009 at 08:59PM EST by Jamie Dubs. Like us on Facebook! Like 1.8M Share\
  \ Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the video\
  \ gallery, or 'r' to view a random entry. Featured Episode Meme Status Confirmed\
  \ Type: Catchphrase, Image Macro Year 2007 Origin 4chan Tags image macro, rap, mtv,\
  \ nested function, celebrity, catchphrase, twitter, recursion, xzibit, pop culture,\
  \ hip hop, photoshop meme, reaction image, strange loops, pimp my ride, mtv's pimp\
  \ my ride, alvin nathaniel joiner, douglas hofstadter, malcolm moore Additional\
  \ References Encyclopedia Dramatica Meme Generator Reddit Twitter Urban Dictionary\
  \ Wikipedia About Yo Dawg, or Sup Dawg, is an image macro series based on portrait\
  \ shots of American hip hop artist Alvin Nathaniel Joiner,[10] better known by his\
  \ stage name Xzibit, and humorous captions that are composed around the recursive\
  \ phrasal template \"Yo Dawg, I herd you like (noun X), so I put an (noun X) in\
  \ your (noun Y) so you can (verb Z) while you (verb Z).\" Since rising to popularity\
  \ in early 2007, the series has been considered one of the most well-known and longest\
  \ lasting examples of recursive humor on the Internet. Origin The original image\
  \ macro first appeared on 4chan in early 2007 and experienced a resurgence in late\
  \ 2008 on Reddit, Tumblr, and social networking sites. The Yo Dawg series has a\
  \ unique characteristic in being recursive. This multi-layered structure in the\
  \ Yo Dawg formula makes it reminiscent of the \"strange loops\" described in Douglas\
  \ Hofstadter's G\xF6del, Escher, Bach. The original photograph of Xzibit comes from\
  \ a set of studio portraits that were originally used to promote the 2006 sports\
  \ drama film Gridiron Gang, in which the rapper plays the role of a minor character\
  \ named Malcolm Moore. MTV Pimp My Ride While Xzibit initially began his career\
  \ in the entertainment industry as a rapper from Los Angeles, his mainstream breakthrough\
  \ came almost a decade later as the host of the MTV show Pimp My Ride, which ran\
  \ for six seasons from 2004 to 2007. In the show, Xzibit gained a reputation for\
  \ adding luxurious amenities and equipments like fish tanks, clothes dryers and\
  \ fireplaces into the participant's car, presumably without consent. Spread Derivatives\
  \ Standard: {yo,sup} dawg, I herd you like X, so I put an X in your Y so you can\
  \ VERB while you VERB Repetitive: {yo,sup} dawg, I herd you like X, so I put an\
  \ X in your X so you can X while you X Abstract: {yo,sup} dawg, I herd you like\
  \ X, so I put an Y in your Z so you can VERB while you VERB Xzibit's Reaction The\
  \ explosive popularity of microblogging service Twitter has reached celebrities,\
  \ Xzibit included. In one of his first tweets he decries his embodiment as a meme\
  \ ( View Tweet ), which led to the creation of this image macro: Several days later,\
  \ he rescinded his criticism, saying \"i'm not mad @ you\" (View Tweet). In the\
  \ final stage of celeb-o-meme -- \"acceptance\" -- Xzibit embraces the yo dawg,\
  \ attempting to his own: View Tweet Notable Examples Search Interest External References\
  \ [1] TV.com \u2013 MTV Pimp My Ride Episode 4 [2] TV.com \u2013 MTV Pimp My Ride\
  \ Episode 5 [3] TV.com \u2013 MTV Pimp My Ride Episode 6 [4] Superior Pics \u2013\
  \ Gridiron Gang Film Promotion [5] Tumblr \u2013 Yo Dawg [6] Tumblr \u2013 YoYoDawgDawg\
  \ [7] Tumblr \u2013 Yo Dawg Pics [8] Urban Dictionary \u2013 Yo Dawg [9] Yo Dawg\
  \ Yo \u2013 Yo Dawg / Sup Dawg [10] IMDB \u2013 Xzibit Biography Recent Videos 11\
  \ total Reacts Xzibit Yo Dawg Uploaded by Sophie I BAKED YOU A PIE Xzibit Yo Dawg\
  \ Uploaded by Hypercat-Z Pimp My Ride - Xzibit Entranc... Xzibit Yo Dawg Uploaded\
  \ by Brad Doge Unboxing (such boxceptio... Xzibit Yo Dawg Uploaded by stockmann\
  \ Deadpool - Yo Dawg Xzibit Yo Dawg Uploaded by b2j135 Seven News' AAMI Park reporte...\
  \ Xzibit Yo Dawg Uploaded by Don Dan Rollman's post on Vine Xzibit Yo Dawg Uploaded\
  \ by Brad Know Your Meme: Yo Dawg Xzibit Yo Dawg Uploaded by James + Add a Video\
  \ View All Videos Recent Images 730 total Xzibit Yo Dawg Uploaded by Lugamo Xzibit\
  \ Yo Dawg Uploaded by bruhinb Xzibit Yo Dawg Uploaded by azren Xzibit Yo Dawg Uploaded\
  \ by Square Memester Xzibit Yo Dawg Uploaded by Y F Xzibit Yo Dawg Uploaded by DrossPedantic\
  \ Xzibit Yo Dawg Uploaded by Y F Xzibit Yo Dawg Uploaded by andcallmeshirley Xzibit\
  \ Yo Dawg Uploaded by Y F Xzibit Yo Dawg Uploaded by Y F Xzibit Yo Dawg Uploaded\
  \ by Y F Xzibit Yo Dawg Uploaded by Evilthing + Add an Image View All Images Sign\
  \ up for our Newsletter Top Comments Delete Sensitive Black Joseph Ducreux Jan 14,\
  \ 2011 at 08:40PM EST Yo dawg, I heard you're gay, so we put a cigarette, and a\
  \ dick in yo mouth so you can suck a fag while u suck a fag. +13 Reply Delete Sensitive\
  \ Black Joseph Ducreux Jan 14, 2011 at 08:03PM EST Sup dawg, I heard you like butterfly\
  \ doors, so we painted butterflies on your butterfly doors so you can look like\
  \ a faggot while you look like a douchebag. +11 Reply + Add a Comment Comments (96)\
  \ Display Comments Add a Comment Top Entries This Month Meme Saika Kawakita Smile\
  \ GIF Event Assassination of UnitedHealthcare CEO Person Luigi Mangione UHC CEO\
  \ Shooter Subculture The Ki Sisters Culture Pornography Site Whisper View More Suggest\
  \ a Change Edit History Entry Editors (10) Jamie Dubs Scientist Emeritus Chris Menning\
  \ Digital Archaeologist & Archivist & Pundit & Early Adopter (#8) yatta Internet\
  \ Scientist peeinears Don Administrator & Meme Daddy Brad Digital Archaeologist\
  \ & Treasurer & Pundit & Gallery Housekeeper Cyber6x Database Moderator & Midnight\
  \ Channeler Precious Roy Deactivated Y F Digital Archaeologist & Treasurer & Media\
  \ Maid Kevinvq2 Sr. Researcher & Scrapbooker & Media Chauffeur \u25BC + Request\
  \ Editorship View All Editors Today's Top Image Galleries Assassination of UnitedHealthcare\
  \ CEO Team Fortress 2 Squirrel Girl (Doreen Green) The Amazing Digital Circus About\
  \ Our Story Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes\
  \ News Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/xzibit-yo-dawg
template_id: yodawg
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
