example:
- Burger King
- The Monarch of Hamburg
keywords:
- null
name: Tuxedo Winnie the Pooh
overlay:
- angle: 0.0
  center_x: 0.75
  center_y: 0.25
  scale: 0.5
- angle: 0.0
  center_x: 0.75
  center_y: 0.75
  scale: 0.5
scraped_content: "Tuxedo Winnie the Pooh | Know Your Meme Hi! You must login or signup\
  \ first! Already a memeber? Login Now! Don't have an account? Sign up Now! Meme\
  \ Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Tuxedo Winnie the Pooh Added 5 years ago / Updated 17 days ago Confirmed 387,468\
  \ Part of a series on Winnie the Pooh. [View Related Entries] View All 214 Images\
  \ Navigation About \u2022 Origin \u2022 Spread \u2022 Various Examples \u2022 Templates\
  \ \u2022 Search Interest \u2022 External References \u2022 Recent Images \u2022\
  \ Recent Videos About Tuxedo Winnie the Pooh, also known as \"A Fellow Man of Culture\"\
  \ refers to a photoshopped image of character Winnie the Pooh sitting in an armchair.\
  \ Initially circulated as a reaction image on 4chan, in March 2019 the image gained\
  \ mainstream popularity on Reddit. Origin On December 20th, 1974, Disney animated\
  \ featurette Winnie the Pooh and Tigger Too was released.[1] In one scene of the\
  \ featurette, characters Winnie the Pooh and Piglet attend a meeting at Rabbit's\
  \ house, with Winnie constantly dozing off in a chair. In 1977, the featurette was\
  \ re-released as a part of The Many Adventures of Winnie the Pooh animated feature\
  \ film.[2] Spread Starting at least in 2013, a still of Winnie the Pooh sitting\
  \ in an armchair with an expression of apathy gained popularity as a reaction image\
  \ on 4chan. One of the most popular edits of the image, a Tuxedo Winnie the Pooh\
  \ was created by an anonymous 4chan user. On March 24th, 2019, Reddit[3] user avocadoMaster420\
  \ posted used \"a fellow man of culture\" macro in a post to /r/me_irl subreddit,[citation\
  \ needed] which gained over 14,900 upvotes in three days (shown below, left). On\
  \ March 25th, 2019, Redditor[4] NeonVanillaIcecream used a cropped version of the\
  \ macro for a post in /r/dankmemes subreddit,[citation needed] garnering over 58,300\
  \ upvotes in two days (shown below, right). In the following days, multiple notable\
  \ examples of the meme were posted to /r/dankmemes and other subreddits. Variations\
  \ On June 9th, 2019, an anonymous user on the 4chan[5] board /pol/ posted a variation\
  \ of the Winnie The Pooh image, replacing the illustration's eyes with the eyes\
  \ of the comic character Pepe the Frog (shown below). On October 22nd, Redditor[6]\
  \ nic-bit shared variation that features a DERP face onto Winnie the Pooh, indicating\
  \ that the meme's author finds the character to be mentally incompetent, next to\
  \ the text \"TikTok,\" comparing the social media app to other places to post memes.\
  \ The post received more than 35,000 points (86% upvoted) and 415 comments in three\
  \ days (shown below, left). This variant showcase a reversal of the typical progression,\
  \ in which each idea is more refined than the last. Here, the final level is the\
  \ worst option in the meme's author's opinion. The following day, Redditor[7] orqh\
  \ posted a variation of the tiered Winnie The Pooh list with a new layer that features\
  \ Winnie the Pooh wearing headphones next to the text that reads, \"Get the fuck\
  \ out of my room I'm playing Minecraft.\" The post received more than 56,000 points\
  \ (91% upvoted) and 130 comments (shown below, left). Various Examples Templates\
  \ Search Interest External References [1] Wikipedia \u2013 Winnie the Pooh and Tigger\
  \ Too [2] Wikipedia \u2013 The Many Adventures of Winnie the Pooh [3] Reddit \u2013\
  \ me\U0001F60Eirl [4] Reddit \u2013 Clap clap [5] 4chan \u2013 /pol/ [6] Reddit\
  \ \u2013 /r/memes [7] Reddit \u2013 /r/dankmemes smug suave gentleman tuxedo cool\
  \ winnie the pooh smoking jacket armchair refined avocadomaster420 winnie the pooh\
  \ and tigger too neonvanillaicecream fancy winnie the pooh fancy Share Pin Related\
  \ Entries 12 total Winnie The Pooh's Home Run Derby Sweet Jesus, Pooh! That's Not...\
  \ Me Showing My Mom a Funny Meme Winnie the Pooh Dancing Videos View All Related\
  \ Entries Recent Images 214 total View All Images Recent Videos 41 total View All\
  \ Videos Sign up for our Newsletter Load 21 Comments Comments 21 total 43 Tuxedo\
  \ Winnie the Pooh 387,468 41 214 21 Part of a series on Winnie the Pooh. [View Related\
  \ Entries] Updated Dec 06, 2024 at 04:00PM EST by LiterallyAustin. Added Mar 26,\
  \ 2019 at 02:07PM EDT by Philipp. Like us on Facebook! Like 1.8M Share Save Tweet\
  \ PROTIP: Press 'i' to view the image gallery, 'v' to view the video gallery, or\
  \ 'r' to view a random entry. Meme Status Confirmed Type: Character, Exploitable,\
  \ Reaction Year 2013 Origin 4chan Tags smug, suave, gentleman, tuxedo, cool, winnie\
  \ the pooh, smoking, jacket, armchair, refined, avocadomaster420, winnie the pooh\
  \ and tigger too, neonvanillaicecream, fancy winnie the pooh, fancy Additional References\
  \ Meme Generator Meming Wiki About Tuxedo Winnie the Pooh, also known as \"A Fellow\
  \ Man of Culture\" refers to a photoshopped image of character Winnie the Pooh sitting\
  \ in an armchair. Initially circulated as a reaction image on 4chan, in March 2019\
  \ the image gained mainstream popularity on Reddit. Origin On December 20th, 1974,\
  \ Disney animated featurette Winnie the Pooh and Tigger Too was released.[1] In\
  \ one scene of the featurette, characters Winnie the Pooh and Piglet attend a meeting\
  \ at Rabbit's house, with Winnie constantly dozing off in a chair. In 1977, the\
  \ featurette was re-released as a part of The Many Adventures of Winnie the Pooh\
  \ animated feature film.[2] Spread Starting at least in 2013, a still of Winnie\
  \ the Pooh sitting in an armchair with an expression of apathy gained popularity\
  \ as a reaction image on 4chan. One of the most popular edits of the image, a Tuxedo\
  \ Winnie the Pooh was created by an anonymous 4chan user. On March 24th, 2019, Reddit[3]\
  \ user avocadoMaster420 posted used \"a fellow man of culture\" macro in a post\
  \ to /r/me_irl subreddit,[citation needed] which gained over 14,900 upvotes in three\
  \ days (shown below, left). On March 25th, 2019, Redditor[4] NeonVanillaIcecream\
  \ used a cropped version of the macro for a post in /r/dankmemes subreddit,[citation\
  \ needed] garnering over 58,300 upvotes in two days (shown below, right). In the\
  \ following days, multiple notable examples of the meme were posted to /r/dankmemes\
  \ and other subreddits. Variations On June 9th, 2019, an anonymous user on the 4chan[5]\
  \ board /pol/ posted a variation of the Winnie The Pooh image, replacing the illustration's\
  \ eyes with the eyes of the comic character Pepe the Frog (shown below). On October\
  \ 22nd, Redditor[6] nic-bit shared variation that features a DERP face onto Winnie\
  \ the Pooh, indicating that the meme's author finds the character to be mentally\
  \ incompetent, next to the text \"TikTok,\" comparing the social media app to other\
  \ places to post memes. The post received more than 35,000 points (86% upvoted)\
  \ and 415 comments in three days (shown below, left). This variant showcase a reversal\
  \ of the typical progression, in which each idea is more refined than the last.\
  \ Here, the final level is the worst option in the meme's author's opinion. The\
  \ following day, Redditor[7] orqh posted a variation of the tiered Winnie The Pooh\
  \ list with a new layer that features Winnie the Pooh wearing headphones next to\
  \ the text that reads, \"Get the fuck out of my room I'm playing Minecraft.\" The\
  \ post received more than 56,000 points (91% upvoted) and 130 comments (shown below,\
  \ left). Various Examples Templates Search Interest External References [1] Wikipedia\
  \ \u2013 Winnie the Pooh and Tigger Too [2] Wikipedia \u2013 The Many Adventures\
  \ of Winnie the Pooh [3] Reddit \u2013 me\U0001F60Eirl [4] Reddit \u2013 Clap clap\
  \ [5] 4chan \u2013 /pol/ [6] Reddit \u2013 /r/memes [7] Reddit \u2013 /r/dankmemes\
  \ Related Entries 12 total Winnie The Pooh's Home Run Derby Sweet Jesus, Pooh! That's\
  \ Not Honey! Me Showing My Mom a Funny Meme Winnie the Pooh Dancing Videos Kanga\
  \ With Hair Winnie the Pooh Reading Goonbear I Love Honey, But You Know What I Don't\
  \ Love #PoohSays Winnie the Pooh: Blood and Honey Winnie The Poohing Winnie's Hole\
  \ Recent Videos 41 total Fancy winni the pooh memes! #... Tuxedo Winnie the Pooh\
  \ Uploaded by andcallmeshirley Memes De Winnie Pooh Elegante Tuxedo Winnie the Pooh\
  \ Uploaded by Y F Winnie The Pooh Memes Tuxedo Winnie the Pooh Uploaded by Y F REcopilacion\
  \ MEMES del Winnie... Tuxedo Winnie the Pooh Uploaded by Y F Best of Winnie the\
  \ Pooh 'Clas... Tuxedo Winnie the Pooh Uploaded by Y F Memes de Winnie Pooh Elegante\
  \ Tuxedo Winnie the Pooh Uploaded by Y F Why Is Pooh Bear So Fancy? | ... Tuxedo\
  \ Winnie the Pooh Uploaded by Y F Winnie The Pooh MEME COMPILAT... Tuxedo Winnie\
  \ the Pooh Uploaded by Y F + Add a Video View All Videos Recent Images 214 total\
  \ Tuxedo Winnie the Pooh Uploaded by Jaimie Hamilton Tuxedo Winnie the Pooh Uploaded\
  \ by Jaimie Hamilton Tuxedo Winnie the Pooh Uploaded by Jaimie Hamilton Tuxedo Winnie\
  \ the Pooh Uploaded by Marwan Sallam Tuxedo Winnie the Pooh Uploaded by Jaimie Hamilton\
  \ Tuxedo Winnie the Pooh Uploaded by Reddit Moments Tuxedo Winnie the Pooh Uploaded\
  \ by Reddit Moments Tuxedo Winnie the Pooh Uploaded by Reddit Moments Tuxedo Winnie\
  \ the Pooh Uploaded by Reddit Moments Tuxedo Winnie the Pooh Uploaded by Jaimie\
  \ Hamilton Tuxedo Winnie the Pooh Uploaded by Reddit Moments Tuxedo Winnie the Pooh\
  \ Uploaded by shadowviking + Add an Image View All Images Sign up for our Newsletter\
  \ Top Comments Delete Sensitive Jack the Dipper Mar 26, 2019 at 09:46PM EDT When\
  \ Reddit turns another old reaction image into an /r/dankmeme of the week. +36 Reply\
  \ Delete Sensitive ObadiahtheSlim Mar 27, 2019 at 02:19PM EDT +16 Reply + Add a\
  \ Comment Comments (21) Display Comments Add a Comment Top Entries This Month Meme\
  \ Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare CEO Person Luigi\
  \ Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography Site Whisper\
  \ View More Suggest a Change Edit History Entry Editors (6) Philipp Memesplainer\
  \ Y F Digital Archaeologist & Treasurer & Media Maid Matt Secretary of Memes andcallmeshirley\
  \ Digital Archaeologist & Treasurer & Collection Butler Adam Know Your Meme Universal\
  \ Champion shevyrolet Digital Archaeologist & Treasurer & Media Bus Boy \u25BC +\
  \ Request Editorship View All Editors Today's Top Image Galleries Assassination\
  \ of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing\
  \ Digital Circus About Our Story Site Rules Policies and Guidelines Credits Contact\
  \ Meme DB Memes Episodes News Staff Contact Extras! Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/tuxedo-winnie-the-pooh
template_id: pooh
text:
- align: center
  anchor_x: 0.5
  anchor_y: 0.0
  angle: 0.0
  color: black
  font: thick
  scale_x: 0.5
  scale_y: 0.5
  start: 0.0
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.5
  anchor_y: 0.5
  angle: 0.0
  color: black
  font: thick
  scale_x: 0.5
  scale_y: 0.5
  start: 0.0
  stop: 1.0
  style: default
text_zones: 2
