name: Tuxedo Winnie the Pooh
source: https://knowyourmeme.com/memes/tuxedo-winnie-the-pooh
keywords:
- null
text:
- style: default
  color: black
  font: thick
  anchor_x: 0.5
  anchor_y: 0.0
  angle: 0.0
  scale_x: 0.5
  scale_y: 0.5
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: black
  font: thick
  anchor_x: 0.5
  anchor_y: 0.5
  angle: 0.0
  scale_x: 0.5
  scale_y: 0.5
  align: center
  start: 0.0
  stop: 1.0
example:
- Burger King
- The Monarch of Hamburg
overlay:
- center_x: 0.75
  center_y: 0.25
  angle: 0.0
  scale: 0.5
- center_x: 0.75
  center_y: 0.75
  angle: 0.0
  scale: 0.5
scraped_content: About Tuxedo Winnie the Pooh, also known as "A Fellow Man of Culture"
  refers to a photoshopped image of character Winnie the Pooh sitting in an armchair.
  Initially circulated as a reaction image on 4chan, in March 2019 the image gained
  mainstream popularity on Reddit. Origin On December 20th, 1974, Disney animated
  featurette Winnie the Pooh and Tigger Too was released.[1] In one scene of the featurette,
  characters Winnie the Pooh and Piglet attend a meeting at Rabbit's house, with Winnie
  constantly dozing off in a chair. In 1977, the featurette was re-released as a part
  of The Many Adventures of Winnie the Pooh animated feature film.[2] Spread Starting
  at least in 2013, a still of Winnie the Pooh sitting in an armchair with an expression
  of apathy gained popularity as a reaction image on 4chan. One of the most popular
  edits of the image, a Tuxedo Winnie the Pooh was created by an anonymous 4chan user.
  On March 24th, 2019, Reddit[3] user avocadoMaster420 posted used "a fellow man of
  culture" macro in a post to /r/me_irl subreddit,[citation needed] which gained over
  14,900 upvotes in three days (shown below, left). On March 25th, 2019, Redditor[4]
  NeonVanillaIcecream used a cropped version of the macro for a post in /r/dankmemes
  subreddit,[citation needed] garnering over 58,300 upvotes in two days (shown below,
  right). In the following days, multiple notable examples of the meme were posted
  to /r/dankmemes and other subreddits. Variations On June 9th, 2019, an anonymous
  user on the 4chan[5] board /pol/ posted a variation of the Winnie The Pooh image,
  replacing the illustration's eyes with the eyes of the comic character Pepe the
  Frog (shown below). On October 22nd, Redditor[6] nic-bit shared variation that features
  a DERP face onto Winnie the Pooh, indicating that the meme's author finds the character
  to be mentally incompetent, next to the text "TikTok," comparing the social media
  app to other places to post memes. The post received more than 35,000 points (86%
  upvoted) and 415 comments in three days (shown below, left). This variant showcase
  a reversal of the typical progression, in which each idea is more refined than the
  last. Here, the final level is the worst option in the meme's author's opinion.
  The following day, Redditor[7] orqh posted a variation of the tiered Winnie The
  Pooh list with a new layer that features Winnie the Pooh wearing headphones next
  to the text that reads, "Get the fuck out of my room I'm playing Minecraft." The
  post received more than 56,000 points (91% upvoted) and 130 comments (shown below,
  left). Various Examples Templates Search Interest External References [1] Wikipedia
  – Winnie the Pooh and Tigger Too [2] Wikipedia – The Many Adventures of Winnie the
  Pooh [3] Reddit – me😎irl [4] Reddit – Clap clap [5] 4chan – /pol/ [6] Reddit – /r/memes
  [7] Reddit – /r/dankmemes
aside_content: MemeStatusConfirmedType:Character,Exploitable,ReactionYear2013Origin4chanTagssmug,suave,gentleman,tuxedo,cool,winnie
  the pooh,smoking,jacket,armchair,refined,avocadomaster420,winnie the pooh and tigger
  too,neonvanillaicecream,fancy winnie the pooh,fancyAdditional ReferencesMeme GeneratorMeming
  Wiki
added_at: '2019-03-26T14:07:12-04:00'
