example:
- stop it
- get some help
keywords:
- null
name: Stop It, Get Some Help
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Stop It, Get Some Help | Know Your Meme Yo! You must login or signup\
  \ first! Already a memeber? Login Now! Don't have an account? Sign up Now! Meme\
  \ Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Stop It, Get Some Help Added 8 years ago / Updated 7 months ago Confirmed\
  \ 191,130 Part of a series on Michael Jordan. [View Related Entries] Navigation\
  \ About \u2022 Origin \u2022 Spread \u2022 Search Interest \u2022 External References\
  \ \u2022 Recent Images \u2022 Recent Videos About \"Stop It, Get Some Help\" is\
  \ a quote said by former professional basketball player Michael Jordan in an anti-drug\
  \ public service announcement (PSA) that originally aired in May 1987. On Vine and\
  \ YouTube, Jordan's PSA has been widely used as a reaction video to poke fun at\
  \ cringeworthy media or express disapproval of behaviors and comments by others.\
  \ Origin Sponsored by McDonald's and starring Michael Jordan, the anti-drug public\
  \ service announcement premiered on ABC at the end of the network's anti-drug TV\
  \ special program Cracked Up that originally aired on May 26th, 1987. In the minute-long\
  \ video, Jordan urges teenagers to stay away from doing drugs, while pleading those\
  \ with substance abusing problems to \"stop it\" and \"get some help.\" The earliest\
  \ digital copy of the original video was uploaded by YouTuber EightiesTV on February\
  \ 4th, 2010. Jordan: Listen, you got at least three-fourths of your life to go.\
  \ That's three more lifetimes to you. So don't blow it. Don't do drugs. If you're\
  \ doing it, stop it. Get some help. Spread During the first half of the 2010s, several\
  \ duplicates of Michael Jordan's PSA video continued to surface on YouTube, and\
  \ later on, Vine; On January 2nd, 2014, Viner James King uploaded a video clip combining\
  \ an excerpt from Eminem's 2013 single \"Rap God\" and Michael Jordan's soundbite,\
  \ which remains the earliest known use of the PSA clip in a parody remix video to\
  \ date. On April 23rd, 2016, YouTuber Violet Dirge[1] uploaded an isolated video\
  \ clip of Jordan saying \"stop it, get some help,\" along with a short description\
  \ explaining its intended use as a forum weapon, garnering over 220,000 views in\
  \ just about four months. On May 31st, YouTuber XxWoLfxX115[2] uploaded a video\
  \ titled \"Furries need to stop and get some help,\" racking up over 50,000 views.\
  \ On June 7th, Viner Cringe Based uploaded a video clip of a man at a grocery talking\
  \ dirty to a box of Betty Crocker's \"super-moist\" cake, accompanied by Jordan's\
  \ \"stop it\" soundbite. In less than two months, the clip accumulated over 2.8\
  \ million views, 74,000 likes and 2,000 comments, serving as a major amplifier for\
  \ the #getsomehelp hashtag on Vine. Throughout June and August 2016, several dozens\
  \ of \"stop it, get some help\" remixes featuring cringeworthy videos popped up\
  \ on Vine, followed by compilations of notable remixes and parodies on YouTube.[3][4]\
  \ Search Interest External References [1] YouTube \u2013 Stop it. Get some help.\
  \ [2] YouTube \u2013 Furries need to stop and get some help [3] YouTube \u2013 Michael\
  \ Jordan \"Get Some Help\" Vine Compilation [4] YouTube \u2013 Michael Jordan \"\
  Get Some Help\" Vine Memes Compilation || 2016 [5] MemeOrigins \u2013 Get Some Help\
  \ michael jordan anti-drug psa Share Pin Related Entries 7 total Crying Michael\
  \ Jordan Fuck Them Kids Michael Jordan's \"And I Took ... Michael Jordan Jamming\
  \ Out View All Related Entries Recent Images 5 total View All Images Recent Videos\
  \ 5 total View All Videos Sign up for our Newsletter Load 13 Comments Comments 13\
  \ total 26 Stop It, Get Some Help 191,130 5 5 13 Part of a series on Michael Jordan.\
  \ [View Related Entries] Updated May 24, 2024 at 11:45AM EDT by sakshi. Added Aug\
  \ 21, 2016 at 05:53PM EDT by Your Waifu. Like us on Facebook! Like 1.8M Share Save\
  \ Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the video gallery,\
  \ or 'r' to view a random entry. Meme Status Confirmed Type: Reaction Year 1987\
  \ Origin Anti-Drug PSA Tags michael jordan, anti-drug, psa About \"Stop It, Get\
  \ Some Help\" is a quote said by former professional basketball player Michael Jordan\
  \ in an anti-drug public service announcement (PSA) that originally aired in May\
  \ 1987. On Vine and YouTube, Jordan's PSA has been widely used as a reaction video\
  \ to poke fun at cringeworthy media or express disapproval of behaviors and comments\
  \ by others. Origin Sponsored by McDonald's and starring Michael Jordan, the anti-drug\
  \ public service announcement premiered on ABC at the end of the network's anti-drug\
  \ TV special program Cracked Up that originally aired on May 26th, 1987. In the\
  \ minute-long video, Jordan urges teenagers to stay away from doing drugs, while\
  \ pleading those with substance abusing problems to \"stop it\" and \"get some help.\"\
  \ The earliest digital copy of the original video was uploaded by YouTuber EightiesTV\
  \ on February 4th, 2010. Jordan: Listen, you got at least three-fourths of your\
  \ life to go. That's three more lifetimes to you. So don't blow it. Don't do drugs.\
  \ If you're doing it, stop it. Get some help. Spread During the first half of the\
  \ 2010s, several duplicates of Michael Jordan's PSA video continued to surface on\
  \ YouTube, and later on, Vine; On January 2nd, 2014, Viner James King uploaded a\
  \ video clip combining an excerpt from Eminem's 2013 single \"Rap God\" and Michael\
  \ Jordan's soundbite, which remains the earliest known use of the PSA clip in a\
  \ parody remix video to date. On April 23rd, 2016, YouTuber Violet Dirge[1] uploaded\
  \ an isolated video clip of Jordan saying \"stop it, get some help,\" along with\
  \ a short description explaining its intended use as a forum weapon, garnering over\
  \ 220,000 views in just about four months. On May 31st, YouTuber XxWoLfxX115[2]\
  \ uploaded a video titled \"Furries need to stop and get some help,\" racking up\
  \ over 50,000 views. On June 7th, Viner Cringe Based uploaded a video clip of a\
  \ man at a grocery talking dirty to a box of Betty Crocker's \"super-moist\" cake,\
  \ accompanied by Jordan's \"stop it\" soundbite. In less than two months, the clip\
  \ accumulated over 2.8 million views, 74,000 likes and 2,000 comments, serving as\
  \ a major amplifier for the #getsomehelp hashtag on Vine. Throughout June and August\
  \ 2016, several dozens of \"stop it, get some help\" remixes featuring cringeworthy\
  \ videos popped up on Vine, followed by compilations of notable remixes and parodies\
  \ on YouTube.[3][4] Search Interest External References [1] YouTube \u2013 Stop\
  \ it. Get some help. [2] YouTube \u2013 Furries need to stop and get some help [3]\
  \ YouTube \u2013 Michael Jordan \"Get Some Help\" Vine Compilation [4] YouTube \u2013\
  \ Michael Jordan \"Get Some Help\" Vine Memes Compilation || 2016 [5] MemeOrigins\
  \ \u2013 Get Some Help Related Entries 7 total Crying Michael Jordan Fuck Them Kids\
  \ Michael Jordan's \"And I Took That Personally\" Michael Jordan Jamming Out Michael\
  \ Jordan Looking At iPad Michael Jordan Laughing Michael Jordan's Poisoned Pizza\
  \ Conspiracy Theory Recent Videos 5 total Stop it. Get some help. Stop It, Get Some\
  \ Help Uploaded by Brad Michael Jordan Anti-drug PSA ... Stop It, Get Some Help\
  \ Uploaded by Brad + Add a Video Recent Images 5 total Stop It, Get Some Help Uploaded\
  \ by Admiral Loadsamoney Stop It, Get Some Help Uploaded by WellHelloThere Stop\
  \ It, Get Some Help Uploaded by MisterZygarde64 Stop It, Get Some Help Uploaded\
  \ by Brad Stop It, Get Some Help Uploaded by Kirb Blanco + Add an Image Sign up\
  \ for our Newsletter Top Comments Delete Sensitive MaxInHell Aug 25, 2016 at 10:50PM\
  \ EDT +14 Reply Delete Sensitive Mameme Aug 22, 2016 at 11:38AM EDT This should\
  \ likely go into the section of Reaction Images or Michael Jordan for related entries.\
  \ +9 Reply + Add a Comment Comments (13) Display Comments Add a Comment Top Entries\
  \ This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (6) Your Waifu\
  \ Commentator Brad Digital Archaeologist & Treasurer & Pundit & Gallery Housekeeper\
  \ 3kole5 Sr. Entry Moderator Adam Know Your Meme Universal Champion Zach Memenator\
  \ sakshi Technosorcerer \u25BC + Request Editorship View All Editors Today's Top\
  \ Image Galleries Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen Green)\
  \ Team Fortress 2 The Amazing Digital Circus About Our Story Site Rules Policies\
  \ and Guidelines Credits Contact Meme DB Memes Episodes News Staff Contact Extras!\
  \ Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/stop-it-get-some-help
template_id: stop-it
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
