example:
- all the things!!!
keywords:
- null
name: X all the Y
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "All the Things | Know Your Meme Sup! You must login or signup first!\
  \ Already a memeber? Login Now! Don't have an account? Sign up Now! Meme Encyclopedia\
  \ All Cultures Events People Sites Subcultures Videos Submit \u2192 Images Trending\
  \ Most Commented Most Favorited High Score Low Score Most Viewed All Templates Upload\
  \ an Image Articles News Explainers Collections Interviews Meme Insider Magazine\
  \ More Discord Newsletter Episodes Forums Meme Store Login Abstract user icon Memes\
  \ Categories Trending News Images Trending Images Videos Trending Videos Editorials\
  \ Meme Insider Magazine Newsletter Policies and Guidelines Meme Store Old site Login\
  \ Know Your Meme is the property of Literally Media \xA92024 Literally Media. All\
  \ Rights Reserved. This image Of Woman Confidently Strolling Through A Glass Panel\
  \ Has Been A Redraw Format Since 2021 Three Years Ago, This Boar's Head 'Exploded'\
  \ Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess Memes Turns Two Years\
  \ Old Today Phrase 'The Fridge Protects The Snacks' A Growing Favorite Among Pickup\
  \ Artist Influencers Jamie G, The Bosh British Charva, Has Taken Over TikTok With\
  \ His Signature 'Oh Cherie Amour' Sound Also Trending: Honey Extension Influencer\
  \ Scam Renegade Raider Copypasta Assassination of UnitedHealthcare CEO All the Things\
  \ Added 13 years ago / Updated about 16 hours ago Confirmed 2,008,930 Part of a\
  \ series on Hyperbole and a Half. [View Related Entries] View All 700 Images Navigation\
  \ About \u2022 Origin \u2022 Spread \u2022 Notable Derivatives \u2022 Templates\
  \ \u2022 Search Interest \u2022 External References \u2022 Recent Images \u2022\
  \ Recent Videos About All the Things, sometimes known as X all the Y, is a snowclone\
  \ and exploitable cartoon used to make a hyperbolic statement about performing an\
  \ action. The person in the original comic panel is often manipulated to appear\
  \ as a different character. (See also: fsjal) Origin The blog Hyperbole and a Half[1]\
  \ published a comic titled \"This is Why I'll Never be an Adult\" by artist Allie\
  \ Brosh on June 17th, 2010. The comic describes the author's frustration with her\
  \ inability to maintain a consistent enthusiasm for her daily responsibilities.\
  \ The following two panels were part of the comic: Derivatives often use one of\
  \ these two images. Spread A Canvas[2] thread that featured remixed images \"clean\
  \ all the things?\" panel was created on April 28th, 2011. It was posted to the\
  \ Canvas blog[3] on May 2nd, 2011. A Reddit thread posted on June 23rd titled \"\
  Every afternoon on NPR\"[4] had a derivative that parodied the radio show \"All\
  \ Things Considered\", and reached the front page, receiving 6,299 upvotes. On June\
  \ 25th a derivative was posted titled \"How I feel whenever I play a Lego anything\
  \ videogame\"[5] to Reddit's rage comic f7u12 subreddit, and received 95 upvotes.\
  \ On June 27th, a derivative was posted titled \"Whenever I build a campfire\"[6]\
  \ that received 451 upvotes. The /r/allthethings[7] subreddit was created on July\
  \ 13th, 2011, and has 97 subscribers as of August 18th, 2011. Like most of the other\
  \ ragefaces, the \"CLEAN ALL THE THINGS!\" comic touches a direct nerve in me and\
  \ in many redditors. This community is devoted to memetic variations on that wonderful\
  \ image. Notable Derivatives Templates Search Interest Search queries for the original\
  \ phrase \"clean all the things\" picked up in June of 2010, and appear to be reaching\
  \ their highest peak yet in June of 2011. External References [1] Hyperbole and\
  \ a Half \u2013 Why I'll Never be an Adult / 6/16/2010 [2] Canvas \u2013 clean all\
  \ the things? / 4/28/2011 [3] Canvas \u2013 Things We Like: Hyperbole and a Half\
  \ / 5/2/2011 [4] Reddit \u2013 Every afternoon on NPR / 6/23/2011 [5] Reddit \u2013\
  \ How I feel whenever I play a Lego anything video game\u2026.. / 6/25/2011 [6]\
  \ Reddit \u2013 Whenever I build a campfire / 6/27/2011 [7] Reddit \u2013 all the\
  \ things!! comic best of 2011 exploitable f7u12 all the things meme clean all the\
  \ things hyperbole and a half webcomics Share Pin Related Entries 1 total The Alot\
  \ Recent Images 700 total View All Images Recent Videos 3 total View All Videos\
  \ Sign up for our Newsletter Load 99 Comments Comments 99 total 175 All the Things\
  \ 2,008,930 3 700 99 Part of a series on Hyperbole and a Half. [View Related Entries]\
  \ Updated Dec 23, 2024 at 04:09PM EST by LiterallyAustin. Added Jun 27, 2011 at\
  \ 04:51PM EDT by Don. Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press\
  \ 'i' to view the image gallery, 'v' to view the video gallery, or 'r' to view a\
  \ random entry. Meme Status Confirmed Type: Exploitable Year 2010 Origin Hyperbole\
  \ and a Half Tags comic, best of 2011, exploitable, f7u12, all the things meme,\
  \ clean all the things, hyperbole and a half, webcomics About All the Things, sometimes\
  \ known as X all the Y, is a snowclone and exploitable cartoon used to make a hyperbolic\
  \ statement about performing an action. The person in the original comic panel is\
  \ often manipulated to appear as a different character. (See also: fsjal) Origin\
  \ The blog Hyperbole and a Half[1] published a comic titled \"This is Why I'll Never\
  \ be an Adult\" by artist Allie Brosh on June 17th, 2010. The comic describes the\
  \ author's frustration with her inability to maintain a consistent enthusiasm for\
  \ her daily responsibilities. The following two panels were part of the comic: Derivatives\
  \ often use one of these two images. Spread A Canvas[2] thread that featured remixed\
  \ images \"clean all the things?\" panel was created on April 28th, 2011. It was\
  \ posted to the Canvas blog[3] on May 2nd, 2011. A Reddit thread posted on June\
  \ 23rd titled \"Every afternoon on NPR\"[4] had a derivative that parodied the radio\
  \ show \"All Things Considered\", and reached the front page, receiving 6,299 upvotes.\
  \ On June 25th a derivative was posted titled \"How I feel whenever I play a Lego\
  \ anything videogame\"[5] to Reddit's rage comic f7u12 subreddit, and received 95\
  \ upvotes. On June 27th, a derivative was posted titled \"Whenever I build a campfire\"\
  [6] that received 451 upvotes. The /r/allthethings[7] subreddit was created on July\
  \ 13th, 2011, and has 97 subscribers as of August 18th, 2011. Like most of the other\
  \ ragefaces, the \"CLEAN ALL THE THINGS!\" comic touches a direct nerve in me and\
  \ in many redditors. This community is devoted to memetic variations on that wonderful\
  \ image. Notable Derivatives Templates Search Interest Search queries for the original\
  \ phrase \"clean all the things\" picked up in June of 2010, and appear to be reaching\
  \ their highest peak yet in June of 2011. External References [1] Hyperbole and\
  \ a Half \u2013 Why I'll Never be an Adult / 6/16/2010 [2] Canvas \u2013 clean all\
  \ the things? / 4/28/2011 [3] Canvas \u2013 Things We Like: Hyperbole and a Half\
  \ / 5/2/2011 [4] Reddit \u2013 Every afternoon on NPR / 6/23/2011 [5] Reddit \u2013\
  \ How I feel whenever I play a Lego anything video game\u2026.. / 6/25/2011 [6]\
  \ Reddit \u2013 Whenever I build a campfire / 6/27/2011 [7] Reddit \u2013 all the\
  \ things!! Related Entries 1 total The Alot Recent Videos 3 total ANIMEME - X All\
  \ The Things All the Things Uploaded by Whales Are cool Gotta eat ALL the pigeons!\
  \ All the Things Uploaded by alonzorion Alex And Liam Do Walmart All the Things\
  \ Uploaded by GoodFella_Tudela + Add a Video Recent Images 700 total All the Things\
  \ Uploaded by Classic Rage Meme Rook 96 All the Things Uploaded by InterNevetsMemeBoy12\
  \ All the Things Uploaded by Classic Rage Meme Rook 96 All the Things Uploaded by\
  \ Triplem All the Things Uploaded by Classic Rage Meme Rook 96 All the Things Uploaded\
  \ by Classic Rage Meme Rook 96 All the Things Uploaded by Owen All the Things Uploaded\
  \ by 7 GRAND BOY All the Things Uploaded by DiamondRocks22 All the Things Uploaded\
  \ by izzmo All the Things Uploaded by \U0001D4E2\U0001D58E\U0001D593\U0001D586\U0001D58A\
  \U0001D591 \U0001D4F2\U0001D4FC \U0001D4FD\U0001D4F1\U0001D4EE \U0001D4D2\U0001D4D4\
  \U0001D4DE \U0001D4F8\U0001D4EF \U0001D4D7\U0001D4F8\U0001D4FB\U0001D4F7\U0001D502\
  \ All the Things Uploaded by Wesley + Add an Image View All Images Sign up for our\
  \ Newsletter Top Comments Delete Sensitive Interrobang Jul 15, 2011 at 06:31PM EDT\
  \ +1 CONFIRM ALL THE MEMES! +46 Reply Delete Sensitive Rainboom Guy Aug 04, 2011\
  \ at 09:31AM EDT +1 Convert All Teh Haters ! Yeah ! +20 Reply + Add a Comment Comments\
  \ (99) Display Comments Add a Comment Top Entries This Month Meme Saika Kawakita\
  \ Smile GIF Event Assassination of UnitedHealthcare CEO Person Luigi Mangione UHC\
  \ CEO Shooter Subculture The Ki Sisters Culture Pornography Site Whisper View More\
  \ Suggest a Change Edit History Entry Editors (10) Don Administrator & Meme Daddy\
  \ Brad Digital Archaeologist & Treasurer & Pundit & Gallery Housekeeper Mr Bumhole\
  \ #1 Fan Of Osaka Hamsteak #1 & Television Meme Historian Cyber6x Database Moderator\
  \ & Midnight Channeler amanda b. Meme Librarian \xAD\xAD\xADAlex Mercer Entry Moderator\
  \ & YouTube Scatologist SabrinaTibbetts Memepuff Y F Digital Archaeologist & Treasurer\
  \ & Media Maid Keira Jr. Researcher Zach Memenator \u25BC + Request Editorship View\
  \ All Editors Today's Top Image Galleries Assassination of UnitedHealthcare CEO\
  \ Team Fortress 2 Squirrel Girl (Doreen Green) The Amazing Digital Circus About\
  \ Our Story Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes\
  \ News Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/x-all-the-y
template_id: xy
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
