name: X all the Y
source: http://knowyourmeme.com/memes/x-all-the-y
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- all the things!!!
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About All the Things, sometimes known as X all the Y, is a snowclone
  and exploitable cartoon used to make a hyperbolic statement about performing an
  action. The person in the original comic panel is often manipulated to appear as
  a different character. (See also: fsjal) Origin The blog Hyperbole and a Half[1]
  published a comic titled "This is Why I''ll Never be an Adult" by artist Allie Brosh
  on June 17th, 2010. The comic describes the author''s frustration with her inability
  to maintain a consistent enthusiasm for her daily responsibilities. The following
  two panels were part of the comic: Derivatives often use one of these two images.
  Spread A Canvas[2] thread that featured remixed images "clean all the things?" panel
  was created on April 28th, 2011. It was posted to the Canvas blog[3] on May 2nd,
  2011. A Reddit thread posted on June 23rd titled "Every afternoon on NPR"[4] had
  a derivative that parodied the radio show "All Things Considered", and reached the
  front page, receiving 6,299 upvotes. On June 25th a derivative was posted titled
  "How I feel whenever I play a Lego anything videogame"[5] to Reddit''s rage comic
  f7u12 subreddit, and received 95 upvotes. On June 27th, a derivative was posted
  titled "Whenever I build a campfire"[6] that received 451 upvotes. The /r/allthethings[7]
  subreddit was created on July 13th, 2011, and has 97 subscribers as of August 18th,
  2011. Like most of the other ragefaces, the "CLEAN ALL THE THINGS!" comic touches
  a direct nerve in me and in many redditors. This community is devoted to memetic
  variations on that wonderful image. Notable Derivatives Templates Search Interest
  Search queries for the original phrase "clean all the things" picked up in June
  of 2010, and appear to be reaching their highest peak yet in June of 2011. External
  References [1] Hyperbole and a Half – Why I''ll Never be an Adult / 6/16/2010 [2]
  Canvas – clean all the things? / 4/28/2011 [3] Canvas – Things We Like: Hyperbole
  and a Half / 5/2/2011 [4] Reddit – Every afternoon on NPR / 6/23/2011 [5] Reddit
  – How I feel whenever I play a Lego anything video game….. / 6/25/2011 [6] Reddit
  – Whenever I build a campfire / 6/27/2011 [7] Reddit – all the things!!'
aside_content: MemeStatusConfirmedType:ExploitableYear2010OriginHyperbole and a HalfTagscomic,best
  of 2011,exploitable,f7u12,all the things meme,clean all the things,hyperbole and
  a half,webcomics
added_at: '2011-06-27T16:51:35-04:00'
