name: Scooby Doo Reveal
source: https://knowyourmeme.com/memes/lets-see-who-this-really-is
keywords:
- null
text:
- style: default
  color: white
  font: thick
  anchor_x: 0.04
  anchor_y: 0.26
  angle: 0.0
  scale_x: 0.3
  scale_y: 0.1
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: khaki
  font: thick
  anchor_x: 0.0
  anchor_y: 0.36
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.15
  align: center
  start: 0.2
  stop: 1.0
- style: default
  color: white
  font: thick
  anchor_x: 0.04
  anchor_y: 0.8
  angle: 0.0
  scale_x: 0.3
  scale_y: 0.1
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: khaki
  font: thick
  anchor_x: 0.0
  anchor_y: 0.9
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.1
  align: center
  start: 0.6
  stop: 1.0
example:
- Villain
- Let's see who you really are...
- Protagonist
- I knew it!
overlay:
- center_x: 0.21
  center_y: 0.215
  angle: 0.0
  scale: 0.27
- center_x: 0.23
  center_y: 0.69
  angle: 0.0
  scale: 0.27
scraped_content: About Let's See Who This Really Is, also known as Scooby Doo Reveal,
  is an exploitable image macro series featuring a scene from the Scooby Doo animated
  television series in which a man dressed as a ghost is unmasked. Online, photoshopped
  screenshots of the scene are often used in jokes mocking similarities between various
  characters and internet memes. Origin On September 27th, 1969, the Scooby-Doo, Where
  Are You! episode "Hassle in the Castle" was broadcast, in which the Mystery Inc.
  gang apprehends a man dressed as a ghost and takes off his mask, discovering that
  it is the ex-magician Bluestone the Great (shown below). [This video has been removed]
  Spread On July 16th 2017, Twitter user @SmashBros_Nin[1] tweeted a multi-panel image
  macro based on the scene featuring the character Crash Bandicoot unmasked to reveal
  a Dark Souls character, referencing the It's Just Like Dark Souls meme (shown below,
  left). On October 11th, Redditor alex2800 submitted a photoshop of the image featuring
  a Pingu Noot Noot that is revealed to be Skull Trumpet (shown below, right). Prior
  to being archived, the post gained over 4,300 points (98% upvoted) and 30 comments
  on /r/dankmemes.[2] On April 18th, 2018, Redditor Patterninterrupt submitted a variation
  of the image in which Who Killed Hannibal? is revealed to be Baton Roue in disguise
  (shown below). Within 24 hours, the post gained over 8,800 points (83% upvoted)
  and 100 comments on /r/MemeEconomy.[3] Various Examples Search Interest External
  References [1] Twitter – SmashBros_Nin [2] Reddit – /r/dankmemes [3] Reddit – /r/MemeEconomy
  [4] Reddit – /r/MGTOW
aside_content: MemeStatusConfirmedType:Exploitable,Image MacroYearUnknownOriginUnknownTagsscooby
  doo,mask,deception,photoshop,exploitable,patterninterruptAdditional ReferencesMeme
  Generator
added_at: '2018-04-19T12:12:22-04:00'
