example:
- Villain
- Let's see who you really are...
- Protagonist
- I knew it!
keywords:
- null
name: Scooby Doo Reveal
overlay:
- angle: 0.0
  center_x: 0.21
  center_y: 0.215
  scale: 0.27
- angle: 0.0
  center_x: 0.23
  center_y: 0.69
  scale: 0.27
scraped_content: "Let's See Who This Really Is | Know Your Meme Hi! You must login\
  \ or signup first! Already a memeber? Login Now! Don't have an account? Sign up\
  \ Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos Submit\
  \ \u2192 Images Trending Most Commented Most Favorited High Score Low Score Most\
  \ Viewed All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Let's See Who This Really Is Added 6 years ago / Updated about a month ago\
  \ Confirmed 64,096 Part of a series on Scooby-Doo. [View Related Entries] View All\
  \ 52 Images Navigation About \u2022 Origin \u2022 Spread \u2022 Various Examples\
  \ \u2022 Search Interest \u2022 External References \u2022 Recent Images \u2022\
  \ Recent Videos About Let's See Who This Really Is, also known as Scooby Doo Reveal,\
  \ is an exploitable image macro series featuring a scene from the Scooby Doo animated\
  \ television series in which a man dressed as a ghost is unmasked. Online, photoshopped\
  \ screenshots of the scene are often used in jokes mocking similarities between\
  \ various characters and internet memes. Origin On September 27th, 1969, the Scooby-Doo,\
  \ Where Are You! episode \"Hassle in the Castle\" was broadcast, in which the Mystery\
  \ Inc. gang apprehends a man dressed as a ghost and takes off his mask, discovering\
  \ that it is the ex-magician Bluestone the Great (shown below). [This video has\
  \ been removed] Spread On July 16th 2017, Twitter user @SmashBros_Nin[1] tweeted\
  \ a multi-panel image macro based on the scene featuring the character Crash Bandicoot\
  \ unmasked to reveal a Dark Souls character, referencing the It's Just Like Dark\
  \ Souls meme (shown below, left). On October 11th, Redditor alex2800 submitted a\
  \ photoshop of the image featuring a Pingu Noot Noot that is revealed to be Skull\
  \ Trumpet (shown below, right). Prior to being archived, the post gained over 4,300\
  \ points (98% upvoted) and 30 comments on /r/dankmemes.[2] On April 18th, 2018,\
  \ Redditor Patterninterrupt submitted a variation of the image in which Who Killed\
  \ Hannibal? is revealed to be Baton Roue in disguise (shown below). Within 24 hours,\
  \ the post gained over 8,800 points (83% upvoted) and 100 comments on /r/MemeEconomy.[3]\
  \ Various Examples Search Interest External References [1] Twitter \u2013 SmashBros_Nin\
  \ [2] Reddit \u2013 /r/dankmemes [3] Reddit \u2013 /r/MemeEconomy [4] Reddit \u2013\
  \ /r/MGTOW scooby doo mask deception photoshop exploitable patterninterrupt Share\
  \ Pin Related Entries 12 total The Misadventures of Skooks Shaggy Rogers Shaggy,\
  \ This Isn't Weed \"I Think Coolsville Sucks\" View All Related Entries Recent Images\
  \ 52 total View All Images Recent Videos 1 total View All Videos Sign up for our\
  \ Newsletter Load 10 Comments Comments 10 total 11 Let's See Who This Really Is\
  \ 64,096 1 52 10 Part of a series on Scooby-Doo. [View Related Entries] Updated\
  \ Nov 06, 2024 at 12:44PM EST by LiterallyAustin. Added Apr 19, 2018 at 12:12PM\
  \ EDT by Don. Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i'\
  \ to view the image gallery, 'v' to view the video gallery, or 'r' to view a random\
  \ entry. Meme Status Confirmed Type: Exploitable, Image Macro Year Unknown Origin\
  \ Unknown Tags scooby doo, mask, deception, photoshop, exploitable, patterninterrupt\
  \ Additional References Meme Generator About Let's See Who This Really Is, also\
  \ known as Scooby Doo Reveal, is an exploitable image macro series featuring a scene\
  \ from the Scooby Doo animated television series in which a man dressed as a ghost\
  \ is unmasked. Online, photoshopped screenshots of the scene are often used in jokes\
  \ mocking similarities between various characters and internet memes. Origin On\
  \ September 27th, 1969, the Scooby-Doo, Where Are You! episode \"Hassle in the Castle\"\
  \ was broadcast, in which the Mystery Inc. gang apprehends a man dressed as a ghost\
  \ and takes off his mask, discovering that it is the ex-magician Bluestone the Great\
  \ (shown below). [This video has been removed] Spread On July 16th 2017, Twitter\
  \ user @SmashBros_Nin[1] tweeted a multi-panel image macro based on the scene featuring\
  \ the character Crash Bandicoot unmasked to reveal a Dark Souls character, referencing\
  \ the It's Just Like Dark Souls meme (shown below, left). On October 11th, Redditor\
  \ alex2800 submitted a photoshop of the image featuring a Pingu Noot Noot that is\
  \ revealed to be Skull Trumpet (shown below, right). Prior to being archived, the\
  \ post gained over 4,300 points (98% upvoted) and 30 comments on /r/dankmemes.[2]\
  \ On April 18th, 2018, Redditor Patterninterrupt submitted a variation of the image\
  \ in which Who Killed Hannibal? is revealed to be Baton Roue in disguise (shown\
  \ below). Within 24 hours, the post gained over 8,800 points (83% upvoted) and 100\
  \ comments on /r/MemeEconomy.[3] Various Examples Search Interest External References\
  \ [1] Twitter \u2013 SmashBros_Nin [2] Reddit \u2013 /r/dankmemes [3] Reddit \u2013\
  \ /r/MemeEconomy [4] Reddit \u2013 /r/MGTOW Related Entries 12 total The Misadventures\
  \ of Skooks Shaggy Rogers Shaggy, This Isn't Weed \"I Think Coolsville Sucks\" Spooky\
  \ Skeleton Scoob! (2020) Velma (TV Series) Scooby-Doo Doors Rehehehe / Scooby-Doo\
  \ Laugh I Was Mostly Talking About Girls. Hot Missing Sixth Member of the Scooby-Doo\
  \ Gang Scooby-Doo Punches Fred GIF Recent Videos 1 total + Add a Video Recent Images\
  \ 52 total Let's See Who This Really Is Uploaded by Jaimie Hamilton Let's See Who\
  \ This Really Is Uploaded by Reddit Moments Let's See Who This Really Is Uploaded\
  \ by Mr. Nobody Returns Let's See Who This Really Is Uploaded by Reddit Moments\
  \ Let's See Who This Really Is Uploaded by Aidan Walker Let's See Who This Really\
  \ Is Uploaded by Calwings Let's See Who This Really Is Uploaded by Mr. Nobody Returns\
  \ Let's See Who This Really Is Uploaded by Mr. Nobody Returns Let's See Who This\
  \ Really Is Uploaded by Reddit Moments Let's See Who This Really Is Uploaded by\
  \ lardogbeck Let's See Who This Really Is Uploaded by andcallmeshirley Let's See\
  \ Who This Really Is Uploaded by Dormant Puffball + Add an Image View All Images\
  \ Sign up for our Newsletter Top Comments Delete Sensitive AliC202 Apr 19, 2018\
  \ at 08:56PM EDT Noone gonna mention how the original had Robbie Rotten with mustache?\
  \ +29 Reply Delete Sensitive Adam DeLand Apr 19, 2018 at 04:15PM EDT +11 Reply +\
  \ Add a Comment Comments (10) Display Comments Add a Comment Top Entries This Month\
  \ Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare CEO Person\
  \ Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography Site\
  \ Whisper View More Suggest a Change Edit History Entry Editors (3) Don Administrator\
  \ & Meme Daddy Jill Database Moderator & Karma Philanthropist & Meme Taxonomist\
  \ & Fleet Admiral & Amish Y F Digital Archaeologist & Treasurer & Media Maid + Request\
  \ Editorship View All Editors Today's Top Image Galleries Assassination of UnitedHealthcare\
  \ CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing Digital Circus About\
  \ Our Story Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes\
  \ News Staff Contact Extras! Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/lets-see-who-this-really-is
template_id: reveal
text:
- align: center
  anchor_x: 0.04
  anchor_y: 0.26
  angle: 0.0
  color: white
  font: thick
  scale_x: 0.3
  scale_y: 0.1
  start: 0.0
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.0
  anchor_y: 0.36
  angle: 0.0
  color: khaki
  font: thick
  scale_x: 1.0
  scale_y: 0.15
  start: 0.2
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.04
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 0.3
  scale_y: 0.1
  start: 0.0
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.0
  anchor_y: 0.9
  angle: 0.0
  color: khaki
  font: thick
  scale_x: 1.0
  scale_y: 0.1
  start: 0.6
  stop: 1.0
  style: upper
text_zones: 4
