example:
- what a surprise...
- you caught me again
keywords:
- null
name: This is Bull, Shark
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: Reddit - Dive into anything Skip to main content Open menu Open navigation
  Go to Reddit Home r/funny A chip A close button Get App Get the Reddit app Log In
  Log in to Reddit Expand user menu Open settings menu Log In / Sign Up Advertise
  on Reddit Shop Collectible Avatars
source: https://www.reddit.com/r/funny/comments/3grsfs
template_id: bs
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
