name: Super Cool Ski Instructor
source: http://knowyourmeme.com/memes/super-cool-ski-instructor
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- ''
- you're gonna have a bad time
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Super Cool Ski Instructor is an advice animal image macro
  series featuring a picture of the ski instructor Thumper from the animated sitcom
  South Park. The macros are accompanied by captions advising against risky or impetuous
  behaviors followed by the warning “you’re gonna have a bad time.” Origin The character
  first appeared in the South Park episode titled “Asspen”[1], which takes place at
  a ski resort in Aspen, Colorado. In the episode, Stan, Cartman, Kyle and Butters
  are given ski lessons by an instructor named Thumper who repeatedly warns about
  dangerous skiing practices saying “you’re gonna have a bad time.” The episode aired
  on March 20th, 2002. On February 14th, 2012, the first "Super Cool Ski Instructor"
  image macro was uploaded to Quickmeme[2] with the caption "If you''re trying to
  hit the front page without tits or a cat / you''re gonna have a bad time." The same
  day, it was posted to the /r/adviceanimals[4] subreddit accumulating over 3,700
  up votes within six weeks. Precursor: Captain Hindsight The character of "Super
  Cool Ski Instructor" can be largely seen as the foresighted counterpart of Captain
  Hindsight, yet another advice animal meme inspired by the eponymous character that
  appeared in an episode of South Park titled "Coon 2: Hindsight," which aired on
  October 27th, 2010. Both in the episode and the image macro series, Captain Hindsight
  is portrayed as an ill-timing preacher who lectures others on what could''ve been
  done differently to prevent a certain predicament or a negative situation that had
  already unfolded. Spread Few image macros were posted to Reddit for the rest of
  February, but the meme saw a resurgence on March 19th when over 40 submissions were
  posted in two days. On March 21st, 2012, Redditor lulzKat submitted an image macro
  to the /r/adviceanimals[6] subreddit featuring the South Park character Mr. Mackey
  with the caption "Beating the ski instructor meme into the ground is bad / M''Kay."
  The post received over 650 upvotes in less than a week. Later that day, a Bad Joke
  Eel Ski Instructor image macro reached the front page of Reddit[5] with the caption
  "If you break your watch / you''re gonna have a bad time", which received over 15,400
  up votes within a week. As of March 28th, 2012, the Quickmeme page accumulated over
  2,100 submissions and a Facebook[3] page for "Thumper the Super Cool Ski Instructor"
  received 50 likes. Notable Examples Template Search Interest External References
  [1] South Park Studios – Thumper, The Super-Cool Ski Instructor [2] Quickmeme –
  Super Cool Ski Instructor [3] Facebook – Thumper the Super Cool Ski Instructor [4]
  Reddit – Super Cool Ski Instructor [5] Reddit – Bad Joke Eel Ski Instructor [6]
  Reddit – Mr Mackets Views on Ski Instructor'
aside_content: MemeStatusConfirmedType:Character,Image MacroYear2012OriginRedditTagsimage
  macro,animation,south park,instruction,ski,snowclone,you're gonna have a bad time,sitcom,advice
  animals,advice animals of 2012,thumper,lulzkat
added_at: '2012-03-28T14:52:30-04:00'
