example:
- ''
- you're gonna have a bad time
keywords:
- null
name: Super Cool Ski Instructor
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Super Cool Ski Instructor | Know Your Meme 'lo! You must login or\
  \ signup first! Already a memeber? Login Now! Don't have an account? Sign up Now!\
  \ Meme Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Super Cool Ski Instructor Added 12 years ago / Updated 4 years ago Confirmed\
  \ 360,448 Part of a series on South Park. [View Related Entries] View All 111 Images\
  \ Navigation About \u2022 Origin \u2022 Spread \u2022 Search Interest \u2022 External\
  \ References \u2022 Recent Images \u2022 Recent Videos About Super Cool Ski Instructor\
  \ is an advice animal image macro series featuring a picture of the ski instructor\
  \ Thumper from the animated sitcom South Park. The macros are accompanied by captions\
  \ advising against risky or impetuous behaviors followed by the warning \u201Cyou\u2019\
  re gonna have a bad time.\u201D Origin The character first appeared in the South\
  \ Park episode titled \u201CAsspen\u201D[1], which takes place at a ski resort in\
  \ Aspen, Colorado. In the episode, Stan, Cartman, Kyle and Butters are given ski\
  \ lessons by an instructor named Thumper who repeatedly warns about dangerous skiing\
  \ practices saying \u201Cyou\u2019re gonna have a bad time.\u201D The episode aired\
  \ on March 20th, 2002. On February 14th, 2012, the first \"Super Cool Ski Instructor\"\
  \ image macro was uploaded to Quickmeme[2] with the caption \"If you're trying to\
  \ hit the front page without tits or a cat / you're gonna have a bad time.\" The\
  \ same day, it was posted to the /r/adviceanimals[4] subreddit accumulating over\
  \ 3,700 up votes within six weeks. Precursor: Captain Hindsight The character of\
  \ \"Super Cool Ski Instructor\" can be largely seen as the foresighted counterpart\
  \ of Captain Hindsight, yet another advice animal meme inspired by the eponymous\
  \ character that appeared in an episode of South Park titled \"Coon 2: Hindsight,\"\
  \ which aired on October 27th, 2010. Both in the episode and the image macro series,\
  \ Captain Hindsight is portrayed as an ill-timing preacher who lectures others on\
  \ what could've been done differently to prevent a certain predicament or a negative\
  \ situation that had already unfolded. Spread Few image macros were posted to Reddit\
  \ for the rest of February, but the meme saw a resurgence on March 19th when over\
  \ 40 submissions were posted in two days. On March 21st, 2012, Redditor lulzKat\
  \ submitted an image macro to the /r/adviceanimals[6] subreddit featuring the South\
  \ Park character Mr. Mackey with the caption \"Beating the ski instructor meme into\
  \ the ground is bad / M'Kay.\" The post received over 650 upvotes in less than a\
  \ week. Later that day, a Bad Joke Eel Ski Instructor image macro reached the front\
  \ page of Reddit[5] with the caption \"If you break your watch / you're gonna have\
  \ a bad time\", which received over 15,400 up votes within a week. As of March 28th,\
  \ 2012, the Quickmeme page accumulated over 2,100 submissions and a Facebook[3]\
  \ page for \"Thumper the Super Cool Ski Instructor\" received 50 likes. Notable\
  \ Examples Template Search Interest External References [1] South Park Studios \u2013\
  \ Thumper, The Super-Cool Ski Instructor [2] Quickmeme \u2013 Super Cool Ski Instructor\
  \ [3] Facebook \u2013 Thumper the Super Cool Ski Instructor [4] Reddit \u2013 Super\
  \ Cool Ski Instructor [5] Reddit \u2013 Bad Joke Eel Ski Instructor [6] Reddit \u2013\
  \ Mr Mackets Views on Ski Instructor image macro animation south park instruction\
  \ ski snowclone you're gonna have a bad time sitcom advice animals advice animals\
  \ of 2012 thumper lulzkat Share Pin Related Entries 22 total Tree Fiddy ???? PROFIT!!!!\
  \ And It's Gone They Took Our Jobs! View All Related Entries Recent Images 111 total\
  \ View All Images Recent Videos 2 total View All Videos Sign up for our Newsletter\
  \ Load 31 Comments Comments 31 total 43 Super Cool Ski Instructor 360,448 2 111\
  \ 31 Part of a series on South Park. [View Related Entries] Updated May 07, 2020\
  \ at 05:44PM EDT by 3kole5. Added Mar 28, 2012 at 02:52PM EDT by Don. Like us on\
  \ Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the image gallery,\
  \ 'v' to view the video gallery, or 'r' to view a random entry. Meme Status Confirmed\
  \ Type: Character, Image Macro Year 2012 Origin Reddit Tags image macro, animation,\
  \ south park, instruction, ski, snowclone, you're gonna have a bad time, sitcom,\
  \ advice animals, advice animals of 2012, thumper, lulzkat About Super Cool Ski\
  \ Instructor is an advice animal image macro series featuring a picture of the ski\
  \ instructor Thumper from the animated sitcom South Park. The macros are accompanied\
  \ by captions advising against risky or impetuous behaviors followed by the warning\
  \ \u201Cyou\u2019re gonna have a bad time.\u201D Origin The character first appeared\
  \ in the South Park episode titled \u201CAsspen\u201D[1], which takes place at a\
  \ ski resort in Aspen, Colorado. In the episode, Stan, Cartman, Kyle and Butters\
  \ are given ski lessons by an instructor named Thumper who repeatedly warns about\
  \ dangerous skiing practices saying \u201Cyou\u2019re gonna have a bad time.\u201D\
  \ The episode aired on March 20th, 2002. On February 14th, 2012, the first \"Super\
  \ Cool Ski Instructor\" image macro was uploaded to Quickmeme[2] with the caption\
  \ \"If you're trying to hit the front page without tits or a cat / you're gonna\
  \ have a bad time.\" The same day, it was posted to the /r/adviceanimals[4] subreddit\
  \ accumulating over 3,700 up votes within six weeks. Precursor: Captain Hindsight\
  \ The character of \"Super Cool Ski Instructor\" can be largely seen as the foresighted\
  \ counterpart of Captain Hindsight, yet another advice animal meme inspired by the\
  \ eponymous character that appeared in an episode of South Park titled \"Coon 2:\
  \ Hindsight,\" which aired on October 27th, 2010. Both in the episode and the image\
  \ macro series, Captain Hindsight is portrayed as an ill-timing preacher who lectures\
  \ others on what could've been done differently to prevent a certain predicament\
  \ or a negative situation that had already unfolded. Spread Few image macros were\
  \ posted to Reddit for the rest of February, but the meme saw a resurgence on March\
  \ 19th when over 40 submissions were posted in two days. On March 21st, 2012, Redditor\
  \ lulzKat submitted an image macro to the /r/adviceanimals[6] subreddit featuring\
  \ the South Park character Mr. Mackey with the caption \"Beating the ski instructor\
  \ meme into the ground is bad / M'Kay.\" The post received over 650 upvotes in less\
  \ than a week. Later that day, a Bad Joke Eel Ski Instructor image macro reached\
  \ the front page of Reddit[5] with the caption \"If you break your watch / you're\
  \ gonna have a bad time\", which received over 15,400 up votes within a week. As\
  \ of March 28th, 2012, the Quickmeme page accumulated over 2,100 submissions and\
  \ a Facebook[3] page for \"Thumper the Super Cool Ski Instructor\" received 50 likes.\
  \ Notable Examples Template Search Interest External References [1] South Park Studios\
  \ \u2013 Thumper, The Super-Cool Ski Instructor [2] Quickmeme \u2013 Super Cool\
  \ Ski Instructor [3] Facebook \u2013 Thumper the Super Cool Ski Instructor [4] Reddit\
  \ \u2013 Super Cool Ski Instructor [5] Reddit \u2013 Bad Joke Eel Ski Instructor\
  \ [6] Reddit \u2013 Mr Mackets Views on Ski Instructor Related Entries 22 total\
  \ Tree Fiddy ???? PROFIT!!!! And It's Gone They Took Our Jobs! Captain Hindsight\
  \ Member Berries Oh, I'm Sorry, I Thought This Was America Everybody Draw Mohammed\
  \ Day PC Bro I Didn't Hear No Bell South Park Transgender Athletes Episode Controversy\
  \ My Name Is Craig Tucker Copypasta View All Related Entries Recent Videos 2 total\
  \ YOU'RE GONNA HAVE A BAD TIME 2 Super Cool Ski Instructor Uploaded by Abby of Many\
  \ Fandoms You're Gonna Have a Bad Time Super Cool Ski Instructor Uploaded by Abby\
  \ of Many Fandoms + Add a Video Recent Images 111 total Super Cool Ski Instructor\
  \ Uploaded by Square Memester Super Cool Ski Instructor Uploaded by Fight Milk22\
  \ Super Cool Ski Instructor Uploaded by Y F Super Cool Ski Instructor Uploaded by\
  \ jalford Super Cool Ski Instructor Uploaded by GoldenCommentator Super Cool Ski\
  \ Instructor Uploaded by pissinyourmouth Super Cool Ski Instructor Uploaded by Freakenstein\
  \ Super Cool Ski Instructor Uploaded by SupernovA113 Super Cool Ski Instructor Uploaded\
  \ by Flynox Super Cool Ski Instructor Uploaded by giantsfn15 Super Cool Ski Instructor\
  \ Uploaded by Flynox Super Cool Ski Instructor Uploaded by Johnny Lee + Add an Image\
  \ View All Images Sign up for our Newsletter Top Comments Delete Sensitive Saporian\
  \ Mar 28, 2012 at 07:17PM EDT I'm distracted by the visitor chilling in the background.\
  \ +52 Reply Delete Sensitive Cian Mar 29, 2012 at 04:27AM EDT If you think complaining\
  \ about \"advice animal spinoffs\" is going to do anything at all, you're going\
  \ to have a bad time. +36 Reply + Add a Comment Comments (31) Display Comments Add\
  \ a Comment Top Entries This Month Meme Saika Kawakita Smile GIF Event Assassination\
  \ of UnitedHealthcare CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki\
  \ Sisters Culture Pornography Site Whisper View More Suggest a Change Edit History\
  \ Entry Editors (5) Don Administrator & Meme Daddy Brad Digital Archaeologist &\
  \ Treasurer & Pundit & Gallery Housekeeper Twenty-One Anime Anthropologist & Protip\
  \ Advisor & LGBT Community Expert Y F Digital Archaeologist & Treasurer & Media\
  \ Maid 3kole5 Sr. Entry Moderator \u25BC + Request Editorship View All Editors Today's\
  \ Top Image Galleries Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen\
  \ Green) Team Fortress 2 The Amazing Digital Circus About Our Story Site Rules Policies\
  \ and Guidelines Credits Contact Meme DB Memes Episodes News Staff Contact Extras!\
  \ Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/super-cool-ski-instructor
template_id: ski
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
