example:
- Here lies the last bit of human decency
- Society
- Social Media
keywords:
- null
name: Grant Gustin Next To Oliver Queen's Grave
overlay:
- angle: 4.0
  center_x: 0.245
  center_y: 0.35
  scale: 0.22
- angle: 5.0
  center_x: 0.29
  center_y: 0.85
  scale: 0.25
- angle: 30.0
  center_x: 0.56
  center_y: 0.45
  scale: 0.15
scraped_content: "Grant Gustin Next To Oliver Queen's Grave | Know Your Meme Yo Yo!\
  \ You must login or signup first! Already a memeber? Login Now! Don't have an account?\
  \ Sign up Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos\
  \ Submit \u2192 Images Trending Most Commented Most Favorited High Score Low Score\
  \ Most Viewed All Templates Upload an Image Articles News Explainers Collections\
  \ Interviews Meme Insider Magazine More Discord Newsletter Episodes Forums Meme\
  \ Store Login Abstract user icon Memes Categories Trending News Images Trending\
  \ Images Videos Trending Videos Editorials Meme Insider Magazine Newsletter Policies\
  \ and Guidelines Meme Store Old site Login Know Your Meme is the property of Literally\
  \ Media \xA92024 Literally Media. All Rights Reserved. This image Of Woman Confidently\
  \ Strolling Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years\
  \ Ago, This Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The\
  \ Anarchy Chess Memes Turns Two Years Old Today Phrase 'The Fridge Protects The\
  \ Snacks' A Growing Favorite Among Pickup Artist Influencers Jamie G, The Bosh British\
  \ Charva, Has Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also\
  \ Trending: Honey Extension Influencer Scam Renegade Raider Copypasta Assassination\
  \ of UnitedHealthcare CEO Grant Gustin Next To Oliver Queen's Grave Added 4 years\
  \ ago / Updated about a year ago Confirmed 478,222 Part of a series on DC Comics.\
  \ [View Related Entries] View All 45 Images Navigation About \u2022 Origin \u2022\
  \ Spread \u2022 Various Examples \u2022 Templates \u2022 Search Interest \u2022\
  \ External References \u2022 Recent Images \u2022 Recent Videos About Grant Gustin\
  \ Next to Oliver Queen's Grave is an image macro series based on a set photograph\
  \ of actor Grant Gustin, who plays the titular character on CW's The Flash, kneeling\
  \ and holding up peace sign next to the grave of Oliver Queen, also known as The\
  \ Green Arrow, the DC Comics superhero hero from the CW series Arrow. Origin On\
  \ January 28th, 2020, Arrow actor Echo Kells posted the image of Gustin next to\
  \ the grave on Instagram. [1] The post received more than 56,000 likes in less than\
  \ three weeks (shown below). Spread That day, Redditor [2] psp8199 shared the image\
  \ on the /r/FlashTV subreddit, where it received more than 2,100 points (98% upvoted)\
  \ in less than three days. Since this posting, the image went viral on Reddit. Later\
  \ that day, for example, Redditor[3] buff730 shared the image with the caption \"\
  When the guy who stole your girl dies\" on the /r/memes subreddit. The post received\
  \ more than 39,000 points (96% upvoted) and 360 comments in less than three days\
  \ (shown below, left). Over the next few days, the image continued to spread on\
  \ Reddit, inspiring image edit and object label variations. On January 29th, Redditor[4]\
  \ ItsP3anutButt3r shared a variation that shows the Google Chrome logo over Gustin's\
  \ face and the Internet Explorer logo on the grave. The post received more than\
  \ 29,000 points (98% upvoted) and 180 comments in less than three days (shown below,\
  \ center). Two days later, Facebook [5] user George Hampshire shared a variation\
  \ of the meme in the Marvel Shieldposting group. The post received more than 2,800\
  \ reactions in less than 24 hours (shown below, right). Various Examples Templates\
  \ Search Interest Unavailable. External References [1] Instagram \u2013 @echokells'\
  \ Post [2] Reddit \u2013 /r/TheFlashTV [3] Reddit \u2013 /r/memes [4] Reddit \u2013\
  \ /r/memes [5] Facebook \u2013 Marvel Shieldposting oliver queen the flash dc comics\
  \ grant gustin arrow peace sign superheroes awesomemergency psp8199 buff730 itsp3anutbutt3r\
  \ george hampshire stephen amell meme Share Pin Related Entries 26 total Batman\
  \ Batgirl Variant Cover Controv... My Goals Are Beyond Your Unde... It's Machine\
  \ Code View All Related Entries Recent Images 45 total View All Images Recent Videos\
  \ 2 total View All Videos Sign up for our Newsletter Load 8 Comments Comments 8\
  \ total 26 Grant Gustin Next To Oliver Queen's Grave 478,223 2 45 8 Part of a series\
  \ on DC Comics. [View Related Entries] Updated Aug 02, 2023 at 10:38AM EDT by Zach.\
  \ Added Jan 31, 2020 at 04:28PM EST by Matt. Like us on Facebook! Like 1.8M Share\
  \ Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the video\
  \ gallery, or 'r' to view a random entry. Meme Status Confirmed Type: Image Macro\
  \ Year 2020 Origin Instagram Tags oliver queen, the flash, dc comics, grant gustin,\
  \ arrow, peace sign, superheroes, awesomemergency, psp8199, buff730, itsp3anutbutt3r,\
  \ george hampshire, stephen amell meme About Grant Gustin Next to Oliver Queen's\
  \ Grave is an image macro series based on a set photograph of actor Grant Gustin,\
  \ who plays the titular character on CW's The Flash, kneeling and holding up peace\
  \ sign next to the grave of Oliver Queen, also known as The Green Arrow, the DC\
  \ Comics superhero hero from the CW series Arrow. Origin On January 28th, 2020,\
  \ Arrow actor Echo Kells posted the image of Gustin next to the grave on Instagram.\
  \ [1] The post received more than 56,000 likes in less than three weeks (shown below).\
  \ Spread That day, Redditor [2] psp8199 shared the image on the /r/FlashTV subreddit,\
  \ where it received more than 2,100 points (98% upvoted) in less than three days.\
  \ Since this posting, the image went viral on Reddit. Later that day, for example,\
  \ Redditor[3] buff730 shared the image with the caption \"When the guy who stole\
  \ your girl dies\" on the /r/memes subreddit. The post received more than 39,000\
  \ points (96% upvoted) and 360 comments in less than three days (shown below, left).\
  \ Over the next few days, the image continued to spread on Reddit, inspiring image\
  \ edit and object label variations. On January 29th, Redditor[4] ItsP3anutButt3r\
  \ shared a variation that shows the Google Chrome logo over Gustin's face and the\
  \ Internet Explorer logo on the grave. The post received more than 29,000 points\
  \ (98% upvoted) and 180 comments in less than three days (shown below, center).\
  \ Two days later, Facebook [5] user George Hampshire shared a variation of the meme\
  \ in the Marvel Shieldposting group. The post received more than 2,800 reactions\
  \ in less than 24 hours (shown below, right). Various Examples Templates Search\
  \ Interest Unavailable. External References [1] Instagram \u2013 @echokells' Post\
  \ [2] Reddit \u2013 /r/TheFlashTV [3] Reddit \u2013 /r/memes [4] Reddit \u2013 /r/memes\
  \ [5] Facebook \u2013 Marvel Shieldposting Related Entries 26 total Batman Batgirl\
  \ Variant Cover Controversy My Goals Are Beyond Your Understanding It's Machine\
  \ Code Justice League (2017 Film) Suicide Squad Teen Titans Batman v Superman: Dawn\
  \ of Justice Fridging Superman Aquaman Poster Edits Doctor Fate's Three Words View\
  \ All Related Entries Recent Videos 2 total Oliver Queen Funeral Eulogy |... Grant\
  \ Gustin Next To Oliver Q... Uploaded by nightqueen Grant Gustin Next To Oliver\
  \ Q... Grant Gustin Next To Oliver Q... Uploaded by nightqueen + Add a Video Recent\
  \ Images 45 total Grant Gustin Next To Oliver Q... Uploaded by Triplem Grant Gustin\
  \ Next To Oliver Q... Uploaded by Triplem Grant Gustin Next To Oliver Q... Uploaded\
  \ by Sum Lu Zer Grant Gustin Next To Oliver Q... Uploaded by BrentD15 Grant Gustin\
  \ Next To Oliver Q... Uploaded by Nyazilla Grant Gustin Next To Oliver Q... Uploaded\
  \ by DLD493v2 Grant Gustin Next To Oliver Q... Uploaded by SparkStar1991 Grant Gustin\
  \ Next To Oliver Q... Uploaded by GoingSolo44 Grant Gustin Next To Oliver Q... Uploaded\
  \ by Commander_pony Grant Gustin Next To Oliver Q... Uploaded by Cold Hard Crash\
  \ Grant Gustin Next To Oliver Q... Uploaded by Philipp Grant Gustin Next To Oliver\
  \ Q... Uploaded by andcallmeshirley + Add an Image View All Images Sign up for our\
  \ Newsletter Top Comments Delete Sensitive No!! Nov 01, 2021 at 10:34AM EDT Oh\u2026\
  \ I always thought this was Mat Pat from game theory posing on her real mother's\
  \ grave. This makes a lot more sense\u2026 +7 Reply Delete Sensitive Marshadow Jan\
  \ 31, 2020 at 05:28PM EST When we go from Arrowverse to Flashverse. +6 Reply + Add\
  \ a Comment Comments (8) Display Comments Add a Comment Top Entries This Month Meme\
  \ Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare CEO Person Luigi\
  \ Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography Site Whisper\
  \ View More Suggest a Change Edit History Entry Editors (4) Matt Secretary of Memes\
  \ Y F Digital Archaeologist & Treasurer & Media Maid Adam Know Your Meme Universal\
  \ Champion Zach Memenator + Request Editorship View All Editors Today's Top Image\
  \ Galleries Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team\
  \ Fortress 2 The Amazing Digital Circus About Our Story Site Rules Policies and\
  \ Guidelines Credits Contact Meme DB Memes Episodes News Staff Contact Extras! Style\
  \ Guide RSS Feeds"
source: https://knowyourmeme.com/memes/grant-gustin-next-to-oliver-queens-grave
template_id: grave
text:
- align: center
  anchor_x: 0.14
  anchor_y: 0.23
  angle: 4.0
  color: black
  font: thick
  scale_x: 0.2
  scale_y: 0.23
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.1
  anchor_y: 0.75
  angle: 5.0
  color: white
  font: thin
  scale_x: 0.4
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.5
  anchor_y: 0.48
  angle: 20.0
  color: white
  font: thin
  scale_x: 0.4
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: default
text_zones: 3
