name: Do You Want Ants?
source: http://knowyourmeme.com/memes/do-you-want-ants
keywords:
- Archer
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- do you want ants?
- because that's how you get ants
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About "Do you want ants? Because that''s how you get ants" is a
  memorable quote said by the character Malory Archer from the American animated TV
  series Archer while explaining the dangers of leaving sugary food products uncovered
  in an office. Online, the phrasal template “Do you want X? Because that’s how you
  get X" is typically used as a reaction image to warn against the potentially negative
  consequences of acting upon a decision. Origin In the closing scene of the pilot
  episode of the animated television series Archer, originally aired on September
  17th, 2009, Malory Archer, the mother and supervisor of the titular character Sterling,
  notices several donuts scattered across the floor and scolds her son, “Do you want
  ants? Because that’s how you get ants!” (shown below). On January 23rd, 2010, a
  Facebook[1] page titled “Do you want ants? Because that’s how you get ants!” was
  launched. [This video has been removed] Malory: …And why are there donuts everywhere?!
  Sterling: Lana did that. Lana: I -- Malory: Do you want ants?! Because that''s how
  you get ants! Spread On July 8th, 2013, Redditor SunnyDeligh submitted a two-panel
  image macro featuring a photograph of a love note written in candy pieces and a
  screenshot of Sterling Archer with the caption “This is how / we get ants” to the
  /r/funny[4] subreddit (shown below, left). Prior to being archived, the post gathered
  more than 21,200 up votes and 260 comments. On February 8th, 2014, Redditor existenjoy
  posted an Archer image macro poking fun at a woman’s online dating profile to /r/AdviceAnimals,[5]
  which accumulated upwards of 9,000 up votes and 150 comments within two months (shown
  below, right). On February 17th, Redditor myowngalactus submitted a two-panel image
  macro of Archer chastising Willy Wonka from the 1970 musical film Willy Wonka and
  the Chocolate Factory to /r/funny[3] (shown below, left). In the next month, the
  post gained over 6,800 up votes and 50 comments. On April 13th, Reddit LibonatiJT
  submitted an Archer image macro complaining about his mother ripping off his blanket
  in the morning to /r/AdviceAnimals[2] (shown below, right). In the first 24 hours,
  the post garnered upwards of 9,400 up votes and 400 comments. Notable Examples Search
  Interest External References [1] Facebook – Do you want ants? Because thats how
  you get ants [2] Reddit – When my mom comes in to wake me up by ripping off my blanket
  [3] Reddit – Do you want ants? [4] Reddit – The sweetest girl [5] Reddit – I saw
  a girls dating profile that listed s-- as something she cant live without'
aside_content: MemeStatusConfirmedYear2009OriginArcherTagsarcher,ants,reaction image,snowclone
added_at: '2014-04-13T09:32:40-04:00'
