name: That Would Be Great
source: http://knowyourmeme.com/memes/that-would-be-great
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- yeah...
- that'd be great
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About "That Would Be Great" is an image macro series featuring the
  character Bill Lumbergh from the 1999 comedy film Office Space. The captions typically
  mimic the character's non-confrontational speech with various requests ending with
  the expression "That'd be great." Origin The film Office Space was released on February
  19th, 1999, in which the protagonist Peter Gibbons (played by Ron Livingston) is
  repeatedly exploited by his boss Bill Lumbergh (played by Gary Cole), a stereotype
  of a corporate manager who focuses on pointless paperwork and asks employees to
  work over the weekend. On September 7th, 2011, Redditor Mekrob submitted a "read
  this in my voice" image macro to the /r/pics[1] subreddit, which featured a screen
  capture of Lumbergh with the caption "Yeeeaah, if you could just, go ahead and read
  this in my voice, that'd be great" (shown below). Prior to being archived, the post
  received over 480 up votes and 25 comments. Spread On October 10th, 2011, Redditor
  AnkenTEM submitted a post titled "That'd be great" to the /r/pics[6] subreddit,
  featuring a photograph of a hybrid cosplayer dressed as Lumbergh and Darth Vader
  from Star Wars with the caption "Yeah, if you could just, come to the dark side,
  that'd be great" (shown below, left). Prior to being archived, the post received
  over 3,400 upvotes and 40 comments. On May 13th, 2012, Redditor isntthatironic submitted
  a post titled "Lumbergh Cat" to the /r/AdviceAnimals[5] subreddit, featuring a photoshopped
  screen capture of Lumbergh with a superimposed cat's head and the caption "Yeeaaaaahhhhh
  / I'm gonna need you to let me out even though you just let me back in" (shown below,
  right). On December 24th, 2011 Redditor lifeisonebigjoe submitted a post titled
  "All I Want for Christmas" to the /r/AdviceAnimals[7] subreddit, which included
  a Bill Lumbergh image macro with the caption "Yeah, if we could all just stop shooting
  each other / That'd be great" (shown below). Within six hours, the post received
  over 17,000 up votes and 560 comments. As of December 24th, 2012, the Quickmeme
  page for "That Would Be Great"[2] has received more than 8,700 submissions, as well
  as two duplicate Quickmeme pages "Office Space Lumbergh"[3] and "Lumbergh"[4] with
  more than 880 submissions combined. Notable Examples Search Interest External References
  [1] Reddit – yeeaah if you could just read this [2] Quickmeme – That Would Be Great
  [3] Quickmeme – Office Space Lumbergh [4] Quickmeme – Bill Lumbergh [5] Reddit –
  Lumbergh Cat [6] Reddit – That'd Be Great [7] Reddit – All I Want for Christmas
aside_content: MemeStatusConfirmedType:Catchphrase,Image Macro,Pop Culture ReferenceYear2011OriginRedditTagsoffice
  space,that'd be great,that would be great,it would be great,movie character,office
  space meme,that would be great memeAdditional ReferencesMeme Generator
added_at: '2012-12-24T16:51:56-05:00'
