example:
- Twin Towers
- George Bush
- Why would Al-Qaeda do this?
keywords:
- null
name: Who Killed Hannibal?
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Who Killed Hannibal? | Know Your Meme Sup! You must login or signup\
  \ first! Already a memeber? Login Now! Don't have an account? Sign up Now! Meme\
  \ Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Who Killed Hannibal? Added 6 years ago / Updated 3 years ago Confirmed 342,354\
  \ Part of a series on The Eric Andre Show. [View Related Entries] View All 246 Images\
  \ Navigation About \u2022 Origin \u2022 Spread \u2022 Various Examples \u2022 Search\
  \ Interest \u2022 External References \u2022 Recent Images \u2022 Recent Videos\
  \ About Who Killed Hannibal?, also known as Eric Andre Shooting Hannibal Buress\
  \ and *Why Would X Do This?\", refers to a skit from The Eric Andre Show in which\
  \ we see Andre fire a gun multiple times as co-host Hannibal Buress, then turn to\
  \ the camera and ask \"Who killed Hannibal?\" The scene became an object labeling\
  \ exploitable image macro in 2018 in which the characters are labeled differently\
  \ and Andre's line of dialogue is substituted with variations of the phrasal template\
  \ \"Why would X do this?\" Origin The scene comes from Season 2, episode 6 of The\
  \ Eric Andre Show, which aired November 7th, 2013.[1] While making a joke about\
  \ climate change, Andre turns and shoots several bullets into Buress. He then reloads\
  \ the weapon, and fires several bullets at Buress again, then turns to the camera\
  \ and asks \"Who killed Hannibal?\" (shown below). Spread On October 16th, 2016,\
  \ Facebook meme page Holy shit dude is that a \u1D50\u1D49\u1D50\u1D49[2] uploaded\
  \ the clip, gaining over 16,000 likes and reactions. Screenshots of the scene began\
  \ becoming an exploitable object labeling meme in April of 2018. On April 16th,\
  \ 2018, /r/dankmemes[3] user lilbrubster posted a 9/11 joke, gaining over 18,000\
  \ points (shown below, left). Another popular post on the subreddit posted on the\
  \ 17th gained over 800 points (shown below, right). Following the image's spread\
  \ on /r/dankmemes, it was picked up in several posts on /r/MemeEconomy. The original\
  \ lilbruster post was reposted to /r/MemeEconomy and gained over 15,000 points.[4]\
  \ Another post referenced a nice guys edit posted to iFunny, gaining 180 points\
  \ (shown below, left). Another variation about Stalin and Soviet Russia gained 24\
  \ points in 8 hours (shown below, right). Various Examples Search Interest External\
  \ References [1] Wikipedia \u2013 List of Eric Andre Show Episodes [2] Facebook\
  \ \u2013 Holy shit dude is that a \u1D50\u1D49\u1D50\u1D49 [3] Reddit \u2013 /r/dankmemes\
  \ [4] /r/MemeEconomy \u2013 Any Possible Potential? object labeling eric andre show\
  \ hannibal burress lilbrubster Share Pin Related Entries 11 total Why Would You\
  \ Say Something S... Let Me In Why Are You Booing Me? I'm Right We'll Be Right Back\
  \ View All Related Entries Recent Images 246 total View All Images Recent Videos\
  \ 5 total View All Videos Sign up for our Newsletter Load 22 Comments Comments 22\
  \ total 54 Who Killed Hannibal? 342,354 5 246 22 Part of a series on The Eric Andre\
  \ Show. [View Related Entries] Updated Jun 07, 2021 at 02:24AM EDT by Autumn Able.\
  \ Added Apr 17, 2018 at 12:11PM EDT by Adam. Like us on Facebook! Like 1.8M Share\
  \ Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the video\
  \ gallery, or 'r' to view a random entry. Meme Status Confirmed Type: Exploitable\
  \ Year 2013 Origin The Eric Andre Show Tags object labeling, eric andre show, hannibal\
  \ burress, lilbrubster About Who Killed Hannibal?, also known as Eric Andre Shooting\
  \ Hannibal Buress and *Why Would X Do This?\", refers to a skit from The Eric Andre\
  \ Show in which we see Andre fire a gun multiple times as co-host Hannibal Buress,\
  \ then turn to the camera and ask \"Who killed Hannibal?\" The scene became an object\
  \ labeling exploitable image macro in 2018 in which the characters are labeled differently\
  \ and Andre's line of dialogue is substituted with variations of the phrasal template\
  \ \"Why would X do this?\" Origin The scene comes from Season 2, episode 6 of The\
  \ Eric Andre Show, which aired November 7th, 2013.[1] While making a joke about\
  \ climate change, Andre turns and shoots several bullets into Buress. He then reloads\
  \ the weapon, and fires several bullets at Buress again, then turns to the camera\
  \ and asks \"Who killed Hannibal?\" (shown below). Spread On October 16th, 2016,\
  \ Facebook meme page Holy shit dude is that a \u1D50\u1D49\u1D50\u1D49[2] uploaded\
  \ the clip, gaining over 16,000 likes and reactions. Screenshots of the scene began\
  \ becoming an exploitable object labeling meme in April of 2018. On April 16th,\
  \ 2018, /r/dankmemes[3] user lilbrubster posted a 9/11 joke, gaining over 18,000\
  \ points (shown below, left). Another popular post on the subreddit posted on the\
  \ 17th gained over 800 points (shown below, right). Following the image's spread\
  \ on /r/dankmemes, it was picked up in several posts on /r/MemeEconomy. The original\
  \ lilbruster post was reposted to /r/MemeEconomy and gained over 15,000 points.[4]\
  \ Another post referenced a nice guys edit posted to iFunny, gaining 180 points\
  \ (shown below, left). Another variation about Stalin and Soviet Russia gained 24\
  \ points in 8 hours (shown below, right). Various Examples Search Interest External\
  \ References [1] Wikipedia \u2013 List of Eric Andre Show Episodes [2] Facebook\
  \ \u2013 Holy shit dude is that a \u1D50\u1D49\u1D50\u1D49 [3] Reddit \u2013 /r/dankmemes\
  \ [4] /r/MemeEconomy \u2013 Any Possible Potential? Related Entries 11 total Why\
  \ Would You Say Something So Controversial Yet So Brave? Let Me In Why Are You Booing\
  \ Me? I'm Right We'll Be Right Back Wack Eric Andr\xE9 Cheers I'll Drink to That\
  \ Bro Pretzels Is the Same What If It Was Purple? Hannibal Buress Looking at His\
  \ Hands Google, Show Me This Guy's Balls Recent Videos 5 total [SFM] Who Killed\
  \ Hannibal Who Killed Hannibal? Uploaded by Krazy-Chibi IGotSilver on Twitter Who\
  \ Killed Hannibal? Uploaded by Sum Lu Zer [SFM Spyro] Who Killed Hannibal Who Killed\
  \ Hannibal? Uploaded by gnbman The Dio Brando Show | Who sho... Who Killed Hannibal?\
  \ Uploaded by iBlewupthemoon Who Killed Eric Andre? Who Killed Hannibal? Uploaded\
  \ by illuminachosTV + Add a Video Recent Images 246 total Who Killed Hannibal? Uploaded\
  \ by purple5628 Who Killed Hannibal? Uploaded by Triplem Who Killed Hannibal? Uploaded\
  \ by Reddit Moments Who Killed Hannibal? Uploaded by Usereus Who Killed Hannibal?\
  \ Uploaded by Aidan Walker Who Killed Hannibal? Uploaded by Evilthing Who Killed\
  \ Hannibal? Uploaded by ZackAkai Who Killed Hannibal? Uploaded by apersonontheinternet\
  \ Who Killed Hannibal? Uploaded by Chunmeista Who Killed Hannibal? Uploaded by Jokes\
  \ Joestar \U0001F44C\uA66E Who Killed Hannibal? Uploaded by BrentD15 Who Killed\
  \ Hannibal? Uploaded by Rebecca Rhodes + Add an Image View All Images Sign up for\
  \ our Newsletter Top Comments Delete Sensitive Knightshade Apr 17, 2018 at 02:13PM\
  \ EDT Object labeling AND blaming others for problems? +75 Reply Delete Sensitive\
  \ Winday, Furries Pirate Apr 17, 2018 at 08:22PM EDT in reply to 3kole5 *front paged\
  \ political news everyday \"NSFW is killing our meme.\" +63 Reply + Add a Comment\
  \ Comments (22) Display Comments Add a Comment Top Entries This Month Meme Saika\
  \ Kawakita Smile GIF Event Assassination of UnitedHealthcare CEO Person Luigi Mangione\
  \ UHC CEO Shooter Subculture The Ki Sisters Culture Pornography Site Whisper View\
  \ More Suggest a Change Edit History Entry Editors (6) Adam Know Your Meme Universal\
  \ Champion Don Administrator & Meme Daddy Y F Digital Archaeologist & Treasurer\
  \ & Media Maid 3kole5 Sr. Entry Moderator ohmyjosh Digital Archaeologist & Cataloger\
  \ Autumn Able Sr. Entry Moderator \u25BC + Request Editorship View All Editors Today's\
  \ Top Image Galleries Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen\
  \ Green) Team Fortress 2 The Amazing Digital Circus About Our Story Site Rules Policies\
  \ and Guidelines Credits Contact Meme DB Memes Episodes News Staff Contact Extras!\
  \ Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/who-killed-hannibal
template_id: wkh
text:
- align: center
  anchor_x: 0.1
  anchor_y: 0.3
  angle: 0.0
  color: white
  font: thick
  scale_x: 0.3
  scale_y: 0.1
  start: 0.0
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.53
  anchor_y: 0.35
  angle: 0.0
  color: white
  font: thick
  scale_x: 0.3
  scale_y: 0.1
  start: 0.0
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.0
  anchor_y: 0.875
  angle: 0.0
  color: khaki
  font: thick
  scale_x: 1.0
  scale_y: 0.125
  start: 0.2
  stop: 1.0
  style: default
text_zones: 3
