name: Who Killed Hannibal?
source: https://knowyourmeme.com/memes/who-killed-hannibal
keywords:
- null
text:
- style: default
  color: white
  font: thick
  anchor_x: 0.1
  anchor_y: 0.3
  angle: 0.0
  scale_x: 0.3
  scale_y: 0.1
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: white
  font: thick
  anchor_x: 0.53
  anchor_y: 0.35
  angle: 0.0
  scale_x: 0.3
  scale_y: 0.1
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: khaki
  font: thick
  anchor_x: 0.0
  anchor_y: 0.875
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.125
  align: center
  start: 0.2
  stop: 1.0
example:
- Twin Towers
- George Bush
- Why would Al-Qaeda do this?
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About Who Killed Hannibal?, also known as Eric Andre Shooting Hannibal
  Buress and *Why Would X Do This?", refers to a skit from The Eric Andre Show in
  which we see Andre fire a gun multiple times as co-host Hannibal Buress, then turn
  to the camera and ask "Who killed Hannibal?" The scene became an object labeling
  exploitable image macro in 2018 in which the characters are labeled differently
  and Andre's line of dialogue is substituted with variations of the phrasal template
  "Why would X do this?" Origin The scene comes from Season 2, episode 6 of The Eric
  Andre Show, which aired November 7th, 2013.[1] While making a joke about climate
  change, Andre turns and shoots several bullets into Buress. He then reloads the
  weapon, and fires several bullets at Buress again, then turns to the camera and
  asks "Who killed Hannibal?" (shown below). Spread On October 16th, 2016, Facebook
  meme page Holy shit dude is that a ᵐᵉᵐᵉ[2] uploaded the clip, gaining over 16,000
  likes and reactions. Screenshots of the scene began becoming an exploitable object
  labeling meme in April of 2018. On April 16th, 2018, /r/dankmemes[3] user lilbrubster
  posted a 9/11 joke, gaining over 18,000 points (shown below, left). Another popular
  post on the subreddit posted on the 17th gained over 800 points (shown below, right).
  Following the image's spread on /r/dankmemes, it was picked up in several posts
  on /r/MemeEconomy. The original lilbruster post was reposted to /r/MemeEconomy and
  gained over 15,000 points.[4] Another post referenced a nice guys edit posted to
  iFunny, gaining 180 points (shown below, left). Another variation about Stalin and
  Soviet Russia gained 24 points in 8 hours (shown below, right). Various Examples
  Search Interest External References [1] Wikipedia – List of Eric Andre Show Episodes
  [2] Facebook – Holy shit dude is that a ᵐᵉᵐᵉ [3] Reddit – /r/dankmemes [4] /r/MemeEconomy
  – Any Possible Potential?
aside_content: MemeStatusConfirmedType:ExploitableYear2013OriginThe Eric Andre ShowTagsobject
  labeling,eric andre show,hannibal burress,lilbrubster
added_at: '2018-04-17T12:11:49-04:00'
