name: Agnes Harkness Winking
source: https://knowyourmeme.com/memes/agnes-harkness-winking
keywords:
- WandaVision
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- ''
- i have read and agree to the terms and conditions
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'Editor''s Note: This entry contains spoilers for WandaVision; read
  at your own caution. About Agnes Harkness Winking, also known as Kathryn Hahn Winking,
  is a reaction image and video of the character Agnes, also known as Agatha Harkness,
  from the 2021 Marvel superhero comedy WandaVision. Online, use the moment to joke
  about a well-known open secret or an obvious lie. Origin On December 10th, 2020,
  the trailer for WandaVision debuted on YouTube. [1] Forty seconds into the video,
  the character Agnes (portrayed by Kathryn Hahn) winks in an exaggerated fashion.
  The post received more than 10 million views in less than six months (shown below).
  Roughly two months later, on January 22nd, 2021, the third episode of WandaVision,
  "Now in Color," aired on Disney+. The shot of Agnes winking comes from this episode
  (clip below, right). However, before the episode aired, people were already using
  the image in memes. On January 9th, 2021, USA Today reporter Alex Biese tweeted
  a GIF of the moment (shown below). The post received more than 950 likes and 40
  retweets in less than two months (shown below). It’s a wonderfully intimate return
  to the MCU, engaging with the TV medium with gusto and affection. Oh, and Kathryn
  Hahn is and always has been a treasure. pic.twitter.com/HBmGhk0YWS — Alex Biese
  (@ABieseAPP) January 9, 2021 Spread Memes and remixes of Agnes winking soon became
  a regular occurrence on the #AgnesTheNeighbor Twitter hashtag. On February 19th,
  2021, for example, Twitter[2] user @MoonLig40187480 tweeted a remix of the Grant
  Gustin Next To Oliver Queen''s Grave that featured the meme. The post received more
  than 5,200 likes and 900 retweets in less than two weeks (shown below, left). Soon
  the image came to have meaning outside the WandaVision fandom. On February 23rd,
  Twitter[3] user @acceptedrose tweeted the image in response to the reality television
  series The Bachelor. The tweet received more than 3,000 likes and 200 retweets in
  less than one week (shown below, center). Two days later, on February 25th, Twitter[4]
  user @ tweeted the image with a joke about the "Checkov''s Gun" narrative trope.
  They wrote, "Chekhov writing a gun into the first act of a play." The tweet received
  more than 75,000 likes and 8,200 retweets in less than three days (shown below,
  right). Various Examples Template Search Interest External References [1] IMDB –
  Now In Color [2] Twitter – @MoonLig40187480''s Tweet [3] Twitter – @acceptedrose''s
  Tweet [4] Twitter – @MatthewKBegbie'
aside_content: MemeStatusConfirmedType:Image MacroYear2020OriginWandaVision (Television)Tagswandavision,kathryn
  hahn,disney+,marvel,marvel cinematic universe,marvel memes,television,tv,agnes harknessAdditional
  ReferencesMeme Generator
added_at: '2021-02-26T13:55:23-05:00'
