example:
- ''
- i have read and agree to the terms and conditions
keywords:
- WandaVision
name: Agnes Harkness Winking
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Agnes Harkness Winking | Know Your Meme Hey! You must login or signup\
  \ first! Already a memeber? Login Now! Don't have an account? Sign up Now! Meme\
  \ Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Agnes Harkness Winking Added 3 years ago / Updated 3 years ago Confirmed 108,832\
  \ Part of a series on WandaVision. [View Related Entries] View All 36 Images Editor's\
  \ Note: This entry contains spoilers for WandaVision; read at your own caution.\
  \ Navigation About \u2022 Origin \u2022 Spread \u2022 Various Examples \u2022 Template\
  \ \u2022 Search Interest \u2022 External References \u2022 Recent Images \u2022\
  \ Recent Videos About Agnes Harkness Winking, also known as Kathryn Hahn Winking,\
  \ is a reaction image and video of the character Agnes, also known as Agatha Harkness,\
  \ from the 2021 Marvel superhero comedy WandaVision. Online, use the moment to joke\
  \ about a well-known open secret or an obvious lie. Origin On December 10th, 2020,\
  \ the trailer for WandaVision debuted on YouTube. [1] Forty seconds into the video,\
  \ the character Agnes (portrayed by Kathryn Hahn) winks in an exaggerated fashion.\
  \ The post received more than 10 million views in less than six months (shown below).\
  \ Roughly two months later, on January 22nd, 2021, the third episode of WandaVision,\
  \ \"Now in Color,\" aired on Disney+. The shot of Agnes winking comes from this\
  \ episode (clip below, right). However, before the episode aired, people were already\
  \ using the image in memes. On January 9th, 2021, USA Today reporter Alex Biese\
  \ tweeted a GIF of the moment (shown below). The post received more than 950 likes\
  \ and 40 retweets in less than two months (shown below). It\u2019s a wonderfully\
  \ intimate return to the MCU, engaging with the TV medium with gusto and affection.\
  \ Oh, and Kathryn Hahn is and always has been a treasure. pic.twitter.com/HBmGhk0YWS\
  \ \u2014 Alex Biese (@ABieseAPP) January 9, 2021 Spread Memes and remixes of Agnes\
  \ winking soon became a regular occurrence on the #AgnesTheNeighbor Twitter hashtag.\
  \ On February 19th, 2021, for example, Twitter[2] user @MoonLig40187480 tweeted\
  \ a remix of the Grant Gustin Next To Oliver Queen's Grave that featured the meme.\
  \ The post received more than 5,200 likes and 900 retweets in less than two weeks\
  \ (shown below, left). Soon the image came to have meaning outside the WandaVision\
  \ fandom. On February 23rd, Twitter[3] user @acceptedrose tweeted the image in response\
  \ to the reality television series The Bachelor. The tweet received more than 3,000\
  \ likes and 200 retweets in less than one week (shown below, center). Two days later,\
  \ on February 25th, Twitter[4] user @ tweeted the image with a joke about the \"\
  Checkov's Gun\" narrative trope. They wrote, \"Chekhov writing a gun into the first\
  \ act of a play.\" The tweet received more than 75,000 likes and 8,200 retweets\
  \ in less than three days (shown below, right). Various Examples Template Search\
  \ Interest External References [1] IMDB \u2013 Now In Color [2] Twitter \u2013 @MoonLig40187480's\
  \ Tweet [3] Twitter \u2013 @acceptedrose's Tweet [4] Twitter \u2013 @MatthewKBegbie\
  \ wandavision kathryn hahn disney+ marvel marvel cinematic universe marvel memes\
  \ television tv agnes harkness Share Pin Related Entries 6 total Vishawn What Is\
  \ Grief, If Not Love Pe... WandaVision \"Ship Of Theseus\"... Agatha All Along View\
  \ All Related Entries Recent Images 36 total View All Images Recent Videos 16 total\
  \ View All Videos Sign up for our Newsletter Load 3 Comments Comments 3 total 3\
  \ Agnes Harkness Winking 108,832 16 36 3 Part of a series on WandaVision. [View\
  \ Related Entries] Updated May 04, 2021 at 07:21AM EDT by shevyrolet. Added Feb\
  \ 26, 2021 at 01:55PM EST by Matt. Like us on Facebook! Like 1.8M Share Save Tweet\
  \ PROTIP: Press 'i' to view the image gallery, 'v' to view the video gallery, or\
  \ 'r' to view a random entry. Meme Status Confirmed Type: Image Macro Year 2020\
  \ Origin WandaVision (Television) Tags wandavision, kathryn hahn, disney+, marvel,\
  \ marvel cinematic universe, marvel memes, television, tv, agnes harkness Additional\
  \ References Meme Generator Editor's Note: This entry contains spoilers for WandaVision;\
  \ read at your own caution. About Agnes Harkness Winking, also known as Kathryn\
  \ Hahn Winking, is a reaction image and video of the character Agnes, also known\
  \ as Agatha Harkness, from the 2021 Marvel superhero comedy WandaVision. Online,\
  \ use the moment to joke about a well-known open secret or an obvious lie. Origin\
  \ On December 10th, 2020, the trailer for WandaVision debuted on YouTube. [1] Forty\
  \ seconds into the video, the character Agnes (portrayed by Kathryn Hahn) winks\
  \ in an exaggerated fashion. The post received more than 10 million views in less\
  \ than six months (shown below). Roughly two months later, on January 22nd, 2021,\
  \ the third episode of WandaVision, \"Now in Color,\" aired on Disney+. The shot\
  \ of Agnes winking comes from this episode (clip below, right). However, before\
  \ the episode aired, people were already using the image in memes. On January 9th,\
  \ 2021, USA Today reporter Alex Biese tweeted a GIF of the moment (shown below).\
  \ The post received more than 950 likes and 40 retweets in less than two months\
  \ (shown below). It\u2019s a wonderfully intimate return to the MCU, engaging with\
  \ the TV medium with gusto and affection. Oh, and Kathryn Hahn is and always has\
  \ been a treasure. pic.twitter.com/HBmGhk0YWS \u2014 Alex Biese (@ABieseAPP) January\
  \ 9, 2021 Spread Memes and remixes of Agnes winking soon became a regular occurrence\
  \ on the #AgnesTheNeighbor Twitter hashtag. On February 19th, 2021, for example,\
  \ Twitter[2] user @MoonLig40187480 tweeted a remix of the Grant Gustin Next To Oliver\
  \ Queen's Grave that featured the meme. The post received more than 5,200 likes\
  \ and 900 retweets in less than two weeks (shown below, left). Soon the image came\
  \ to have meaning outside the WandaVision fandom. On February 23rd, Twitter[3] user\
  \ @acceptedrose tweeted the image in response to the reality television series The\
  \ Bachelor. The tweet received more than 3,000 likes and 200 retweets in less than\
  \ one week (shown below, center). Two days later, on February 25th, Twitter[4] user\
  \ @ tweeted the image with a joke about the \"Checkov's Gun\" narrative trope. They\
  \ wrote, \"Chekhov writing a gun into the first act of a play.\" The tweet received\
  \ more than 75,000 likes and 8,200 retweets in less than three days (shown below,\
  \ right). Various Examples Template Search Interest External References [1] IMDB\
  \ \u2013 Now In Color [2] Twitter \u2013 @MoonLig40187480's Tweet [3] Twitter \u2013\
  \ @acceptedrose's Tweet [4] Twitter \u2013 @MatthewKBegbie Related Entries 6 total\
  \ Vishawn What Is Grief, If Not Love Persevering WandaVision \"Ship Of Theseus\"\
  \ Conversation Agatha All Along WandaVision Open Door Reveal Every Screenwriter\
  \ in the World Whispering Recent Videos 16 total Top 10 Best Kathryn Hahn Moments\
  \ Agnes Harkness Winking Uploaded by Y F Top 10 Agatha Harkness Facts ... Agnes\
  \ Harkness Winking Uploaded by Video Uploader bot Agatha Harkness in Different ...\
  \ Agnes Harkness Winking Uploaded by Video Uploader bot Why Is Agatha Harkness So\
  \ Pow... Agnes Harkness Winking Uploaded by Video Uploader bot AGATHA HARKNESS EDITS\
  \ 2 \U0001F52E Agnes Harkness Winking Uploaded by Video Uploader bot Agatha Harkness\
  \ scenes (X-Men... Agnes Harkness Winking Uploaded by Video Uploader bot WandaVision:\
  \ Agatha Harkness ... Agnes Harkness Winking Uploaded by Video Uploader bot WandaVision\
  \ S01xEp3 - Agnes a... Agnes Harkness Winking Uploaded by Video Uploader bot + Add\
  \ a Video View All Videos Recent Images 36 total Agnes Harkness Winking Uploaded\
  \ by NewJerseyGuy Agnes Harkness Winking Uploaded by Juan del Rancho Agnes Harkness\
  \ Winking Uploaded by andcallmeshirley Agnes Harkness Winking Uploaded by shevyrolet\
  \ Agnes Harkness Winking Uploaded by Rebecca Rhodes Agnes Harkness Winking Uploaded\
  \ by shevyrolet Agnes Harkness Winking Uploaded by shevyrolet Agnes Harkness Winking\
  \ Uploaded by andcallmeshirley Agnes Harkness Winking Uploaded by andcallmeshirley\
  \ Agnes Harkness Winking Uploaded by Y F Agnes Harkness Winking Uploaded by Y F\
  \ Agnes Harkness Winking Uploaded by Y F + Add an Image View All Images Sign up\
  \ for our Newsletter + Add a Comment Comments (3) Display Comments Add a Comment\
  \ Top Entries This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (3) Matt Secretary\
  \ of Memes andcallmeshirley Digital Archaeologist & Treasurer & Collection Butler\
  \ shevyrolet Digital Archaeologist & Treasurer & Media Bus Boy + Request Editorship\
  \ View All Editors Today's Top Image Galleries Assassination of UnitedHealthcare\
  \ CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing Digital Circus About\
  \ Our Story Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes\
  \ News Staff Contact Extras! Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/agnes-harkness-winking
template_id: agnes
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
