name: And Then I Said
source: https://knowyourmeme.com/memes/and-then-i-said
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- and then i said
- the exam will only contain what we've covered in lectures
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About "And Then I Said" is an image macro series featuring stock
  photographs of groups of people laughing and the caption “And then I said” or “And
  then we said” followed by an empty promise or implausible proposition. The format
  of the series bears many similarities with the "X They Said" image image macros
  in juxtaposing the contrast of what was promised and the actual outcome. Origin
  On July 25th, 2011, Redditor raks1991 submitted a post titled "We told them.." to
  the /r/pics[10] subreddit, featuring a photo of several politicians, including Ronald
  Reagan and George Bush Sr., and the caption "We told them wealth/ would ''trickle
  down''!" (shown below, left). Prior to being archived, the post received over 7,475
  up votes and 220 comments. The original photo was taken by Time[11] magazine photographer
  Diana Walker after Walter Cronkite interviewed President Ronald Reagan at the Oval
  Office on March 3rd, 1981 (shown below, right). "After Walter Cronkite''s last interview
  with the President as the anchor of the CBS Evening News, there was a little celebration
  in the room off the Oval Office," recounts photographer Diana Walker. "White House
  staffers, including Vice President Bush, enjoyed a good laugh over a joke that has
  never become public." In TV Shows The phrase “And then I said” has been also used
  as a framing device in TV shows in which characters recount an event or a story
  from the past in the succinct form of punchlines; a list of significant examples
  of this practice can be found on the TV Tropes page.[5] Spread On September 16th,
  2011, a stock photo from the Girls Laughing series accompanied by the caption “And
  then I told him… / Size doesn’t matter” (shown below, left) was submitted to the
  image macro website Meme Generator.[6] Months later in February 2012, an informal
  variation of the phrase "And I was like" was featured in the Story Time Jesus image
  macro series (shown below, right). On March 12th, 2012, Redditor trevs231 submitted
  a post titled “And then I said” to the /r/AdviceAnimals[2] subreddit, which included
  an image macro of laughing politicians and the caption "And then I said… / “The
  tests will look just like what we’ve covered in lecture!” (shown below, left). On
  the following day, Redditor TommyGetYourShineBox submitted an image macro to the
  /r/funny[3] subreddit of two white business men laughing with the caption "And then
  I said… / “Pay taxes? What am I… poor?” (shown below, middle). On July 3rd, Redditor
  GodlyGiBBson submitted an image macro to the /r/AdviceAnimals[1] subreddit featuring
  several hospital employees laughing with the caption “And then I said, / It’s perfectly
  normal to ejaculate during a prostate exam” (shown below, right). As of June 2013,
  several related Quickmeme[9] pages are available for the image macros, including
  the “And then they said”[7] page with over 3,100 submissions and “Rich Old Men”[8]
  with over 1,800 submissions. Additional examples can be found on the microblogging
  site Tumblr under the tag “#and then I said.”[12] Notable Examples Search Interest
  External References [1] Reddit – And then I said [2] Reddit – And then I said [3]
  Reddit – And then I said [4] Daily Dawdle – Hilarious – Best of And THen I Said
  Meme [5] TV Tropes – And Then I Said [6] Meme Generator – Laughing Girls [7] Quickmeme
  – And then I said [8] Quickmeme – Rich Old Men [9] Quickmeme – keyword – and then
  I said [10] Reddit – We told them [11] Time – Front-Row Seat at the Reagan White
  House [12] Tumblr – #and then i said'
aside_content: MemeStatusConfirmedYear2011OriginRedditTagspolitics,caption,laugh,laughter,taxes,saying,raks1991,ronald
  reagan,george bush sr,walter cronkite,diana walker,oval office,trevs231,tommygetyourshinebox,godlygibbsonAdditional
  ReferencesMeme Generator
added_at: '2012-10-04T08:27:20-04:00'
