example:
- and then i said
- the exam will only contain what we've covered in lectures
keywords:
- null
name: And Then I Said
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "And Then I Said | Know Your Meme Yo Yo! You must login or signup\
  \ first! Already a memeber? Login Now! Don't have an account? Sign up Now! Meme\
  \ Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO And Then I Said Added 12 years ago / Updated about 17 hours ago Confirmed\
  \ 305,420 View All 80 Images Navigation About \u2022 Origin \u2022 Spread \u2022\
  \ Notable Examples \u2022 Search Interest \u2022 External References \u2022 Recent\
  \ Images \u2022 Recent Videos About \"And Then I Said\" is an image macro series\
  \ featuring stock photographs of groups of people laughing and the caption \u201C\
  And then I said\u201D or \u201CAnd then we said\u201D followed by an empty promise\
  \ or implausible proposition. The format of the series bears many similarities with\
  \ the \"X They Said\" image image macros in juxtaposing the contrast of what was\
  \ promised and the actual outcome. Origin On July 25th, 2011, Redditor raks1991\
  \ submitted a post titled \"We told them..\" to the /r/pics[10] subreddit, featuring\
  \ a photo of several politicians, including Ronald Reagan and George Bush Sr., and\
  \ the caption \"We told them wealth/ would 'trickle down'!\" (shown below, left).\
  \ Prior to being archived, the post received over 7,475 up votes and 220 comments.\
  \ The original photo was taken by Time[11] magazine photographer Diana Walker after\
  \ Walter Cronkite interviewed President Ronald Reagan at the Oval Office on March\
  \ 3rd, 1981 (shown below, right). \"After Walter Cronkite's last interview with\
  \ the President as the anchor of the CBS Evening News, there was a little celebration\
  \ in the room off the Oval Office,\" recounts photographer Diana Walker. \"White\
  \ House staffers, including Vice President Bush, enjoyed a good laugh over a joke\
  \ that has never become public.\" In TV Shows The phrase \u201CAnd then I said\u201D\
  \ has been also used as a framing device in TV shows in which characters recount\
  \ an event or a story from the past in the succinct form of punchlines; a list of\
  \ significant examples of this practice can be found on the TV Tropes page.[5] Spread\
  \ On September 16th, 2011, a stock photo from the Girls Laughing series accompanied\
  \ by the caption \u201CAnd then I told him\u2026 / Size doesn\u2019t matter\u201D\
  \ (shown below, left) was submitted to the image macro website Meme Generator.[6]\
  \ Months later in February 2012, an informal variation of the phrase \"And I was\
  \ like\" was featured in the Story Time Jesus image macro series (shown below, right).\
  \ On March 12th, 2012, Redditor trevs231 submitted a post titled \u201CAnd then\
  \ I said\u201D to the /r/AdviceAnimals[2] subreddit, which included an image macro\
  \ of laughing politicians and the caption \"And then I said\u2026 / \u201CThe tests\
  \ will look just like what we\u2019ve covered in lecture!\u201D (shown below, left).\
  \ On the following day, Redditor TommyGetYourShineBox submitted an image macro to\
  \ the /r/funny[3] subreddit of two white business men laughing with the caption\
  \ \"And then I said\u2026 / \u201CPay taxes? What am I\u2026 poor?\u201D (shown\
  \ below, middle). On July 3rd, Redditor GodlyGiBBson submitted an image macro to\
  \ the /r/AdviceAnimals[1] subreddit featuring several hospital employees laughing\
  \ with the caption \u201CAnd then I said, / It\u2019s perfectly normal to ejaculate\
  \ during a prostate exam\u201D (shown below, right). As of June 2013, several related\
  \ Quickmeme[9] pages are available for the image macros, including the \u201CAnd\
  \ then they said\u201D[7] page with over 3,100 submissions and \u201CRich Old Men\u201D\
  [8] with over 1,800 submissions. Additional examples can be found on the microblogging\
  \ site Tumblr under the tag \u201C#and then I said.\u201D[12] Notable Examples Search\
  \ Interest External References [1] Reddit \u2013 And then I said [2] Reddit \u2013\
  \ And then I said [3] Reddit \u2013 And then I said [4] Daily Dawdle \u2013 Hilarious\
  \ \u2013 Best of And THen I Said Meme [5] TV Tropes \u2013 And Then I Said [6] Meme\
  \ Generator \u2013 Laughing Girls [7] Quickmeme \u2013 And then I said [8] Quickmeme\
  \ \u2013 Rich Old Men [9] Quickmeme \u2013 keyword \u2013 and then I said [10] Reddit\
  \ \u2013 We told them [11] Time \u2013 Front-Row Seat at the Reagan White House\
  \ [12] Tumblr \u2013 #and then i said politics caption laugh laughter taxes saying\
  \ raks1991 ronald reagan george bush sr walter cronkite diana walker oval office\
  \ trevs231 tommygetyourshinebox godlygibbson Share Pin Recent Images 80 total View\
  \ All Images Recent Videos 1 total View All Videos Sign up for our Newsletter Load\
  \ 19 Comments Comments 19 total 31 And Then I Said 305,420 1 80 19 Updated Dec 23,\
  \ 2024 at 04:17PM EST by LiterallyAustin. Added Oct 04, 2012 at 08:27AM EDT by T3XT.\
  \ Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the\
  \ image gallery, 'v' to view the video gallery, or 'r' to view a random entry. Meme\
  \ Status Confirmed Year 2011 Origin Reddit Tags politics, caption, laugh, laughter,\
  \ taxes, saying, raks1991, ronald reagan, george bush sr, walter cronkite, diana\
  \ walker, oval office, trevs231, tommygetyourshinebox, godlygibbson Additional References\
  \ Meme Generator About \"And Then I Said\" is an image macro series featuring stock\
  \ photographs of groups of people laughing and the caption \u201CAnd then I said\u201D\
  \ or \u201CAnd then we said\u201D followed by an empty promise or implausible proposition.\
  \ The format of the series bears many similarities with the \"X They Said\" image\
  \ image macros in juxtaposing the contrast of what was promised and the actual outcome.\
  \ Origin On July 25th, 2011, Redditor raks1991 submitted a post titled \"We told\
  \ them..\" to the /r/pics[10] subreddit, featuring a photo of several politicians,\
  \ including Ronald Reagan and George Bush Sr., and the caption \"We told them wealth/\
  \ would 'trickle down'!\" (shown below, left). Prior to being archived, the post\
  \ received over 7,475 up votes and 220 comments. The original photo was taken by\
  \ Time[11] magazine photographer Diana Walker after Walter Cronkite interviewed\
  \ President Ronald Reagan at the Oval Office on March 3rd, 1981 (shown below, right).\
  \ \"After Walter Cronkite's last interview with the President as the anchor of the\
  \ CBS Evening News, there was a little celebration in the room off the Oval Office,\"\
  \ recounts photographer Diana Walker. \"White House staffers, including Vice President\
  \ Bush, enjoyed a good laugh over a joke that has never become public.\" In TV Shows\
  \ The phrase \u201CAnd then I said\u201D has been also used as a framing device\
  \ in TV shows in which characters recount an event or a story from the past in the\
  \ succinct form of punchlines; a list of significant examples of this practice can\
  \ be found on the TV Tropes page.[5] Spread On September 16th, 2011, a stock photo\
  \ from the Girls Laughing series accompanied by the caption \u201CAnd then I told\
  \ him\u2026 / Size doesn\u2019t matter\u201D (shown below, left) was submitted to\
  \ the image macro website Meme Generator.[6] Months later in February 2012, an informal\
  \ variation of the phrase \"And I was like\" was featured in the Story Time Jesus\
  \ image macro series (shown below, right). On March 12th, 2012, Redditor trevs231\
  \ submitted a post titled \u201CAnd then I said\u201D to the /r/AdviceAnimals[2]\
  \ subreddit, which included an image macro of laughing politicians and the caption\
  \ \"And then I said\u2026 / \u201CThe tests will look just like what we\u2019ve\
  \ covered in lecture!\u201D (shown below, left). On the following day, Redditor\
  \ TommyGetYourShineBox submitted an image macro to the /r/funny[3] subreddit of\
  \ two white business men laughing with the caption \"And then I said\u2026 / \u201C\
  Pay taxes? What am I\u2026 poor?\u201D (shown below, middle). On July 3rd, Redditor\
  \ GodlyGiBBson submitted an image macro to the /r/AdviceAnimals[1] subreddit featuring\
  \ several hospital employees laughing with the caption \u201CAnd then I said, /\
  \ It\u2019s perfectly normal to ejaculate during a prostate exam\u201D (shown below,\
  \ right). As of June 2013, several related Quickmeme[9] pages are available for\
  \ the image macros, including the \u201CAnd then they said\u201D[7] page with over\
  \ 3,100 submissions and \u201CRich Old Men\u201D[8] with over 1,800 submissions.\
  \ Additional examples can be found on the microblogging site Tumblr under the tag\
  \ \u201C#and then I said.\u201D[12] Notable Examples Search Interest External References\
  \ [1] Reddit \u2013 And then I said [2] Reddit \u2013 And then I said [3] Reddit\
  \ \u2013 And then I said [4] Daily Dawdle \u2013 Hilarious \u2013 Best of And THen\
  \ I Said Meme [5] TV Tropes \u2013 And Then I Said [6] Meme Generator \u2013 Laughing\
  \ Girls [7] Quickmeme \u2013 And then I said [8] Quickmeme \u2013 Rich Old Men [9]\
  \ Quickmeme \u2013 keyword \u2013 and then I said [10] Reddit \u2013 We told them\
  \ [11] Time \u2013 Front-Row Seat at the Reagan White House [12] Tumblr \u2013 #and\
  \ then i said Recent Videos 1 total I'm gonna make it last... And Then I Said Uploaded\
  \ by Molly Horan + Add a Video Recent Images 80 total And Then I Said Uploaded by\
  \ Y F And Then I Said Uploaded by Bilbo Swaggins And Then I Said Uploaded by Lugamo\
  \ And Then I Said Uploaded by generalerror And Then I Said Uploaded by CuntLicker\
  \ And Then I Said Uploaded by CuntLicker And Then I Said Uploaded by DrAngelMachine\
  \ And Then I Said Uploaded by rsc92 And Then I Said Uploaded by rebelgamer And Then\
  \ I Said Uploaded by TheAnt And Then I Said Uploaded by babyhenchy1 And Then I Said\
  \ Uploaded by Brad + Add an Image View All Images Sign up for our Newsletter Top\
  \ Comments Delete Sensitive Emperor Palpitoad Oct 04, 2012 at 09:18PM EDT +46 Reply\
  \ Delete Sensitive Troublehalf: The Yuri Hunter Oct 06, 2012 at 10:58PM EDT Once\
  \ again I get down vote bombed when all I said was if something is spammed, it gets\
  \ added to KYM. I mean, some memes are added within hours of it being created. Memes\
  \ don't work the way they used to. They are very rarely organic now. If you can\
  \ get a picture and put text over it, it's a meme. But no, I get down voted for\
  \ saying that. +12 Reply + Add a Comment Comments (19) Display Comments Add a Comment\
  \ Top Entries This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (4) T3XT Don\
  \ Administrator & Meme Daddy Brad Digital Archaeologist & Treasurer & Pundit & Gallery\
  \ Housekeeper Y F Digital Archaeologist & Treasurer & Media Maid + Request Editorship\
  \ View All Editors Today's Top Image Galleries Assassination of UnitedHealthcare\
  \ CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing Digital Circus About\
  \ Our Story Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes\
  \ News Staff Contact Extras! Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/and-then-i-said
template_id: atis
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
