name: Mocking Spongebob
source: http://knowyourmeme.com/memes/mocking-spongebob
keywords:
- null
text:
- style: default
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: mock
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- 'BF: I don''t even know her like that'
- 'Me: i DoN''T eVeN KnOw HeR lIkE tHaT'
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Mocking SpongeBob, also known as Spongemock, refers to an
  image macro featuring cartoon character SpongeBob SquarePants in which people use
  a picture of SpongeBob to indicate a mocking tone towards an opinion or point of
  view. Origin The image of SpongeBob used for this series comes from the episode
  of the animated comedy series SpongeBob SquarePants called "Little Yellow Book,"
  which first aired on November 25th, 2012.[1] In the episode, Squidward reads SpongeBob''s
  diary, where he discovers that whenever SpongeBob sees plaid, he acts like a chicken.
  The earliest iteration of the scene being used as a meme occurred on May 4th, 2017.
  Twitter user @OGBEARD[2] posted a screenshot of the scene where SpongeBob acts like
  a chicken with the caption "How i stare back at little kids when they stare for
  too long." The tweet (shown below) has received more than 73,000 retweets and 147,300
  likes in five days. Spread On May 5th, Twitter user @lexysaeyang[4] posted the same
  screenshot (shown below), adding a call-and-response element to the meme, creating
  the effect that SpongeBob''s face and the alternation of uppercase and lowercase
  text represents a mocking tone. The tweet, which put the SpongeBob picture next
  to a picture of a bird with arms, received more than 37,100 retweets and 86,600
  likes. On May 6th, Twitter user @DaniLevyyy[3] posted a variation on the meme (shown
  below), which removed the second picture, and made a single image macro with the
  caption "Americans: I need healthcare because I have cancer and I''m dying. Republicans:
  I NeEd hEaLtHcArE bEcAuSe I hAvE caNcEr aNd iM dYinG." The tweet received more than
  86,900 retweets and 208,400 likes. In the coming days, Several news sites published
  pieces on the meme, including The Daily Dot,[5] Crave,[7] Teen Vogue[8] and Mashable.[6]
  Human Mocking SpongeBob Human Mocking SpongeBob refers to a real-life recreation
  of the Mocking SpongeBob meme by a man dressed in office attire. Originally posted
  by Facebook[9] page Corporate Bro in June 2017, the photograph received significant
  spread as a reaction after a meme based on it received viral spread in September
  2018. Nickelodeon All-Star Brawl Appearance On September 9th, 2021, the gameplay
  trailer for Nickelodeon All Star Brawl revealed that Mocking SpongeBob would be
  SpongeBob''s taunt animation. Various Examples Search Interest External References
  [1] IMDb – Little Yellow Book [2] Twitter via Wayback Machine – @OGBEARD''s Tweet
  [3] Twitter via Wayback Machine – @DaniLevyyy''s Tweet [4] Twitter – @lexysaeyang''s
  Tweet [5] The Daily Dot – ‘Mocking Spongebob’ is the most insulting meme of 2017
  [6] Mashable – Spongebob Squarepants will gladly mock you in the internet''s next,
  best meme [7] Crave (now Mandatory) – ‘Mocking SpongeBob’ Meme Is The Trendiest
  Way To Insult Someone [8] Teen Vogue – ''Mocking Spongebob'' Meme Takes Over Social
  Media [9] Facebook – Corporate Bro'
aside_content: MemeStatusConfirmedType:Image MacroYear2017OriginTwitterTagsspongebob,mocking,twitter,image
  macro,nicktoons,cartoons,spongebob squarepants,spongemock,@ogbeard,@lexysaeyang,@danilevyyy,chum
  bucket,savage patrick,patrick star,krusty krab,meme template,squidward meme,tired
  spongeobb,stephen hillenbu,spongebob mocking memeAdditional ReferencesFacebookMeme
  GeneratorRedditTwitterUrban DictionaryWikipedia
added_at: '2017-05-09T16:33:06-04:00'
