example:
- 'BF: I don''t even know her like that'
- 'Me: i DoN''T eVeN KnOw HeR lIkE tHaT'
keywords:
- null
name: Mocking Spongebob
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Mocking SpongeBob | Know Your Meme Namaste! You must login or signup\
  \ first! Already a memeber? Login Now! Don't have an account? Sign up Now! Meme\
  \ Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Mocking SpongeBob Added 7 years ago / Updated 12 days ago Confirmed 2,122,752\
  \ Part of a series on SpongeBob SquarePants. [View Related Entries] View All 84\
  \ Images Navigation About \u2022 Origin \u2022 Spread \u2022 Various Examples \u2022\
  \ Search Interest \u2022 External References \u2022 Recent Images \u2022 Recent\
  \ Videos About Mocking SpongeBob, also known as Spongemock, refers to an image macro\
  \ featuring cartoon character SpongeBob SquarePants in which people use a picture\
  \ of SpongeBob to indicate a mocking tone towards an opinion or point of view. Origin\
  \ The image of SpongeBob used for this series comes from the episode of the animated\
  \ comedy series SpongeBob SquarePants called \"Little Yellow Book,\" which first\
  \ aired on November 25th, 2012.[1] In the episode, Squidward reads SpongeBob's diary,\
  \ where he discovers that whenever SpongeBob sees plaid, he acts like a chicken.\
  \ The earliest iteration of the scene being used as a meme occurred on May 4th,\
  \ 2017. Twitter user @OGBEARD[2] posted a screenshot of the scene where SpongeBob\
  \ acts like a chicken with the caption \"How i stare back at little kids when they\
  \ stare for too long.\" The tweet (shown below) has received more than 73,000 retweets\
  \ and 147,300 likes in five days. Spread On May 5th, Twitter user @lexysaeyang[4]\
  \ posted the same screenshot (shown below), adding a call-and-response element to\
  \ the meme, creating the effect that SpongeBob's face and the alternation of uppercase\
  \ and lowercase text represents a mocking tone. The tweet, which put the SpongeBob\
  \ picture next to a picture of a bird with arms, received more than 37,100 retweets\
  \ and 86,600 likes. On May 6th, Twitter user @DaniLevyyy[3] posted a variation on\
  \ the meme (shown below), which removed the second picture, and made a single image\
  \ macro with the caption \"Americans: I need healthcare because I have cancer and\
  \ I'm dying. Republicans: I NeEd hEaLtHcArE bEcAuSe I hAvE caNcEr aNd iM dYinG.\"\
  \ The tweet received more than 86,900 retweets and 208,400 likes. In the coming\
  \ days, Several news sites published pieces on the meme, including The Daily Dot,[5]\
  \ Crave,[7] Teen Vogue[8] and Mashable.[6] Human Mocking SpongeBob Human Mocking\
  \ SpongeBob refers to a real-life recreation of the Mocking SpongeBob meme by a\
  \ man dressed in office attire. Originally posted by Facebook[9] page Corporate\
  \ Bro in June 2017, the photograph received significant spread as a reaction after\
  \ a meme based on it received viral spread in September 2018. Nickelodeon All-Star\
  \ Brawl Appearance On September 9th, 2021, the gameplay trailer for Nickelodeon\
  \ All Star Brawl revealed that Mocking SpongeBob would be SpongeBob's taunt animation.\
  \ Various Examples Search Interest External References [1] IMDb \u2013 Little Yellow\
  \ Book [2] Twitter via Wayback Machine \u2013 @OGBEARD's Tweet [3] Twitter via Wayback\
  \ Machine \u2013 @DaniLevyyy's Tweet [4] Twitter \u2013 @lexysaeyang's Tweet [5]\
  \ The Daily Dot \u2013 \u2018Mocking Spongebob\u2019 is the most insulting meme\
  \ of 2017 [6] Mashable \u2013 Spongebob Squarepants will gladly mock you in the\
  \ internet's next, best meme [7] Crave (now Mandatory) \u2013 \u2018Mocking SpongeBob\u2019\
  \ Meme Is The Trendiest Way To Insult Someone [8] Teen Vogue \u2013 'Mocking Spongebob'\
  \ Meme Takes Over Social Media [9] Facebook \u2013 Corporate Bro spongebob mocking\
  \ twitter image macro nicktoons cartoons spongebob squarepants spongemock @ogbeard\
  \ @lexysaeyang @danilevyyy chum bucket savage patrick patrick star krusty krab meme\
  \ template squidward meme tired spongeobb stephen hillenbu spongebob mocking meme\
  \ Share Pin Related Entries 218 total SpongeGar / Primitive Sponge ... Squidward's\
  \ Suicide Surprised Patrick *breath in* Boi View All Related Entries Recent Images\
  \ 84 total View All Images Recent Videos 10 total View All Videos Sign up for our\
  \ Newsletter Load 56 Comments Comments 56 total 52 Mocking SpongeBob 2,122,757 10\
  \ 84 56 Part of a series on SpongeBob SquarePants. [View Related Entries] Updated\
  \ Dec 11, 2024 at 04:23PM EST by LiterallyAustin. Added May 09, 2017 at 04:33PM\
  \ EDT by Matt. Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i'\
  \ to view the image gallery, 'v' to view the video gallery, or 'r' to view a random\
  \ entry. Meme Status Confirmed Type: Image Macro Year 2017 Origin Twitter Tags spongebob,\
  \ mocking, twitter, image macro, nicktoons, cartoons, spongebob squarepants, spongemock,\
  \ @ogbeard, @lexysaeyang, @danilevyyy, chum bucket, savage patrick, patrick star,\
  \ krusty krab, meme template, squidward meme, tired spongeobb, stephen hillenbu,\
  \ spongebob mocking meme Additional References Facebook Meme Generator Reddit Twitter\
  \ Urban Dictionary Wikipedia About Mocking SpongeBob, also known as Spongemock,\
  \ refers to an image macro featuring cartoon character SpongeBob SquarePants in\
  \ which people use a picture of SpongeBob to indicate a mocking tone towards an\
  \ opinion or point of view. Origin The image of SpongeBob used for this series comes\
  \ from the episode of the animated comedy series SpongeBob SquarePants called \"\
  Little Yellow Book,\" which first aired on November 25th, 2012.[1] In the episode,\
  \ Squidward reads SpongeBob's diary, where he discovers that whenever SpongeBob\
  \ sees plaid, he acts like a chicken. The earliest iteration of the scene being\
  \ used as a meme occurred on May 4th, 2017. Twitter user @OGBEARD[2] posted a screenshot\
  \ of the scene where SpongeBob acts like a chicken with the caption \"How i stare\
  \ back at little kids when they stare for too long.\" The tweet (shown below) has\
  \ received more than 73,000 retweets and 147,300 likes in five days. Spread On May\
  \ 5th, Twitter user @lexysaeyang[4] posted the same screenshot (shown below), adding\
  \ a call-and-response element to the meme, creating the effect that SpongeBob's\
  \ face and the alternation of uppercase and lowercase text represents a mocking\
  \ tone. The tweet, which put the SpongeBob picture next to a picture of a bird with\
  \ arms, received more than 37,100 retweets and 86,600 likes. On May 6th, Twitter\
  \ user @DaniLevyyy[3] posted a variation on the meme (shown below), which removed\
  \ the second picture, and made a single image macro with the caption \"Americans:\
  \ I need healthcare because I have cancer and I'm dying. Republicans: I NeEd hEaLtHcArE\
  \ bEcAuSe I hAvE caNcEr aNd iM dYinG.\" The tweet received more than 86,900 retweets\
  \ and 208,400 likes. In the coming days, Several news sites published pieces on\
  \ the meme, including The Daily Dot,[5] Crave,[7] Teen Vogue[8] and Mashable.[6]\
  \ Human Mocking SpongeBob Human Mocking SpongeBob refers to a real-life recreation\
  \ of the Mocking SpongeBob meme by a man dressed in office attire. Originally posted\
  \ by Facebook[9] page Corporate Bro in June 2017, the photograph received significant\
  \ spread as a reaction after a meme based on it received viral spread in September\
  \ 2018. Nickelodeon All-Star Brawl Appearance On September 9th, 2021, the gameplay\
  \ trailer for Nickelodeon All Star Brawl revealed that Mocking SpongeBob would be\
  \ SpongeBob's taunt animation. Various Examples Search Interest External References\
  \ [1] IMDb \u2013 Little Yellow Book [2] Twitter via Wayback Machine \u2013 @OGBEARD's\
  \ Tweet [3] Twitter via Wayback Machine \u2013 @DaniLevyyy's Tweet [4] Twitter \u2013\
  \ @lexysaeyang's Tweet [5] The Daily Dot \u2013 \u2018Mocking Spongebob\u2019 is\
  \ the most insulting meme of 2017 [6] Mashable \u2013 Spongebob Squarepants will\
  \ gladly mock you in the internet's next, best meme [7] Crave (now Mandatory) \u2013\
  \ \u2018Mocking SpongeBob\u2019 Meme Is The Trendiest Way To Insult Someone [8]\
  \ Teen Vogue \u2013 'Mocking Spongebob' Meme Takes Over Social Media [9] Facebook\
  \ \u2013 Corporate Bro Related Entries 218 total SpongeGar / Primitive Sponge /\
  \ Caveman Spongebob Squidward's Suicide Surprised Patrick *breath in* Boi Push It\
  \ Somewhere Else Patrick Inappropriate Timing Spongebob Banner \"Ocean Man\" by\
  \ Ween Welcome to the Salty Spitoon. How Tough Are Ya? Fake History No, This Is\
  \ Patrick Smitty Werbenjagermanjensen You Like Krabby Patties, Don\u2019t You Squidward?\
  \ View All Related Entries Recent Videos 10 total Mocking SpongeBob Uploaded by\
  \ shevyrolet Mocking SpongeBob Uploaded by shevyrolet THE MOCKING SPONGEBOB MEME\
  \ - ... Mocking SpongeBob Uploaded by shevyrolet Spongebob Memes from Spongebo...\
  \ Mocking SpongeBob Uploaded by shevyrolet How to Draw MOCKING SPONGEBOB... Mocking\
  \ SpongeBob Uploaded by shevyrolet Mocking SpongeBob Meme EXPLAI... Mocking SpongeBob\
  \ Uploaded by shevyrolet \"Spongebob Meme\" by Markiplier Mocking SpongeBob Uploaded\
  \ by Cyclone Shadow Spongemock - KILL YOUR MEME Mocking SpongeBob Uploaded by DamkNeme\
  \ + Add a Video View All Videos Recent Images 84 total Mocking SpongeBob Uploaded\
  \ by Marwan Sallam Mocking SpongeBob Uploaded by andcallmeshirley Mocking SpongeBob\
  \ Uploaded by Y F Mocking SpongeBob Uploaded by Y F Mocking SpongeBob Uploaded by\
  \ Y F Mocking SpongeBob Uploaded by Bridget Mocking SpongeBob Uploaded by Bridget\
  \ Mocking SpongeBob Uploaded by Channing Tater: The Potato... Mocking SpongeBob\
  \ Uploaded by Bridget Mocking SpongeBob Uploaded by xoxin Mocking SpongeBob Uploaded\
  \ by Bridget Mocking SpongeBob Uploaded by Bridget + Add an Image View All Images\
  \ Sign up for our Newsletter Top Comments Delete Sensitive Victor May 10, 2017 at\
  \ 10:07AM EDT Me: Don, not everything is a meme. Don: NoT eveRytHinG iS a MeMe +78\
  \ Reply Delete Sensitive le meme reference May 12, 2017 at 08:41AM EDT in reply\
  \ to Hwelse +34 Reply + Add a Comment Comments (56) Display Comments Add a Comment\
  \ Top Entries This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (10) Matt Secretary\
  \ of Memes Don Administrator & Meme Daddy Adam Know Your Meme Universal Champion\
  \ Y F Digital Archaeologist & Treasurer & Media Maid Brad Digital Archaeologist\
  \ & Treasurer & Pundit & Gallery Housekeeper andcallmeshirley Digital Archaeologist\
  \ & Treasurer & Collection Butler shevyrolet Digital Archaeologist & Treasurer &\
  \ Media Bus Boy Philipp Memesplainer Aidan Walker \"Discourse\" Analyst Zach Memenator\
  \ \u25BC + Request Editorship View All Editors Today's Top Image Galleries Assassination\
  \ of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing\
  \ Digital Circus About Our Story Site Rules Policies and Guidelines Credits Contact\
  \ Meme DB Memes Episodes News Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/mocking-spongebob
template_id: spongebob
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: mock
text_zones: 2
