example:
- Am I so out of touch?
- No, it's the children who are wrong.
keywords:
- Am I Out Of Touch?
- The Simpsons
name: Principal Skinner
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Am I So Out Of Touch? | Know Your Meme Greetings! You must login\
  \ or signup first! Already a memeber? Login Now! Don't have an account? Sign up\
  \ Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos Submit\
  \ \u2192 Images Trending Most Commented Most Favorited High Score Low Score Most\
  \ Viewed All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Am I So Out Of Touch? Added 8 years ago / Updated 2 years ago Confirmed 220,701\
  \ Part of a series on The Simpsons. [View Related Entries] View All 47 Images Navigation\
  \ About \u2022 Origin \u2022 Spread \u2022 Various Examples \u2022 Search Interest\
  \ \u2022 External References \u2022 Recent Images \u2022 Recent Videos About \"\
  Am I Out Of Touch\" is a two-panel image macro featuring the character Principal\
  \ Skinner from The Simpsons. along with the caption \"Am I out of touch? No, it's\
  \ the children who are wrong.\" The comic is typically used as a reaction image\
  \ on image boards and discussion forums to express a disconnect with contemporary\
  \ youth a culture. Origin The comic originates from a scene in Season 5 Episode\
  \ 20 of The Simpsons titled \"The Boy Who Knew Too Much,\" which first aired on\
  \ May 5th, 1994.[1] In the scene, Principal Skinner briefly questions if he is out\
  \ of touch before assuring himself that \"It's the children who are wrong\" (shown\
  \ below). On October 29th, 2013, Redditor GhostRidingtheWhip submitted a two-panel\
  \ comic of the scene in a post titled \"I'm starting to dislike all new hiphop and\
  \ pop music, this pretty much sums up my experience\" (shown below). Prior to being\
  \ archived, the post gained over 3,100 votes (95% upvoted) and 1,100 comments on\
  \ the /r/funny[4] subreddit. Spread On November 20th, 2013, Redditor NoahJAustin\
  \ submitted the reaction image in a post titled \"I work IT for a few schools. This.\
  \ Everyday\" on /r/funny.[5] On January 27th, 2014, Redditor Spider_Dude posted\
  \ the image macro to convey a feelings of being out of touch with contemporary pop\
  \ music. Prior to being archived, the post gathered more than 3,100 votes (91% upvoted)\
  \ on /r/funny.[6] On April 7th, 2014, the image was posted to the /r/TheSimpsons\
  \ subreddit[2] On January 6th, 2015, Tumblr user smitethepatriarchy[3] posted a\
  \ cropped version of the original image, gaining over 200,000 notes over the next\
  \ year. Various Examples Search Interest External References [1] Simpsons Wiki \u2013\
  \ The Boy Who Knew Too Much [2] Reddit \u2013 Am I so out of touch? [3] Tumblr \u2013\
  \ gets zero notes on a post [4] Reddit \u2013 Im starting to dislike all new hiphop\
  \ and pop music this pretty much sums up my experience [5] Reddit \u2013 I work\
  \ IT for a few schools [6] Reddit \u2013 Basically how i feel about the AMAs and\
  \ the Grammys since 2002. the simpsons principle skinner children spider_dude ghostridingthewhip\
  \ noahjaustin smitethepatriarchy Share Pin Related Entries 97 total Steamed Hams\
  \ I, For One, Welcome Our New I... Sneed's Feed and Seed Old Man Yells at Cloud\
  \ View All Related Entries Recent Images 47 total View All Images Recent Videos\
  \ 1 total View All Videos Sign up for our Newsletter Load 19 Comments Comments 19\
  \ total 32 Am I So Out Of Touch? 220,701 1 47 19 Part of a series on The Simpsons.\
  \ [View Related Entries] Updated Apr 04, 2022 at 05:20PM EDT by Rose Abrams. Added\
  \ Feb 27, 2016 at 02:29PM EST by Dreamworks. Like us on Facebook! Like 1.8M Share\
  \ Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the video\
  \ gallery, or 'r' to view a random entry. Meme Status Confirmed Year 1994 Origin\
  \ The Simpsons Tags the simpsons, principle skinner, children, spider_dude, ghostridingthewhip,\
  \ noahjaustin, smitethepatriarchy Additional References Meme Generator Tenor GIF\
  \ About \"Am I Out Of Touch\" is a two-panel image macro featuring the character\
  \ Principal Skinner from The Simpsons. along with the caption \"Am I out of touch?\
  \ No, it's the children who are wrong.\" The comic is typically used as a reaction\
  \ image on image boards and discussion forums to express a disconnect with contemporary\
  \ youth a culture. Origin The comic originates from a scene in Season 5 Episode\
  \ 20 of The Simpsons titled \"The Boy Who Knew Too Much,\" which first aired on\
  \ May 5th, 1994.[1] In the scene, Principal Skinner briefly questions if he is out\
  \ of touch before assuring himself that \"It's the children who are wrong\" (shown\
  \ below). On October 29th, 2013, Redditor GhostRidingtheWhip submitted a two-panel\
  \ comic of the scene in a post titled \"I'm starting to dislike all new hiphop and\
  \ pop music, this pretty much sums up my experience\" (shown below). Prior to being\
  \ archived, the post gained over 3,100 votes (95% upvoted) and 1,100 comments on\
  \ the /r/funny[4] subreddit. Spread On November 20th, 2013, Redditor NoahJAustin\
  \ submitted the reaction image in a post titled \"I work IT for a few schools. This.\
  \ Everyday\" on /r/funny.[5] On January 27th, 2014, Redditor Spider_Dude posted\
  \ the image macro to convey a feelings of being out of touch with contemporary pop\
  \ music. Prior to being archived, the post gathered more than 3,100 votes (91% upvoted)\
  \ on /r/funny.[6] On April 7th, 2014, the image was posted to the /r/TheSimpsons\
  \ subreddit[2] On January 6th, 2015, Tumblr user smitethepatriarchy[3] posted a\
  \ cropped version of the original image, gaining over 200,000 notes over the next\
  \ year. Various Examples Search Interest External References [1] Simpsons Wiki \u2013\
  \ The Boy Who Knew Too Much [2] Reddit \u2013 Am I so out of touch? [3] Tumblr \u2013\
  \ gets zero notes on a post [4] Reddit \u2013 Im starting to dislike all new hiphop\
  \ and pop music this pretty much sums up my experience [5] Reddit \u2013 I work\
  \ IT for a few schools [6] Reddit \u2013 Basically how i feel about the AMAs and\
  \ the Grammys since 2002. Related Entries 97 total Steamed Hams I, For One, Welcome\
  \ Our New Insect Overlords Sneed's Feed and Seed Old Man Yells at Cloud I Must Go\
  \ Do It For Her \"Milhouse Is Not A Meme\" Marge Krumping Principal Skinner's \"\
  Pathetic\" Homer Simpson Backs Into Bushes That's The Joke Bart, Get Out! I'm Piss!\
  \ View All Related Entries Recent Videos 1 total You're Out of Touch Am I So Out\
  \ Of Touch? Uploaded by thatguy1 + Add a Video Recent Images 47 total Am I So Out\
  \ Of Touch? Uploaded by Jaimie Hamilton Am I So Out Of Touch? Uploaded by NutTarZucchini\
  \ Am I So Out Of Touch? Uploaded by Triplem Am I So Out Of Touch? Uploaded by Reddit\
  \ Moments Am I So Out Of Touch? Uploaded by Reddit Moments Am I So Out Of Touch?\
  \ Uploaded by TheAnt Am I So Out Of Touch? Uploaded by Platus Am I So Out Of Touch?\
  \ Uploaded by Wrazid Am I So Out Of Touch? Uploaded by draeroz Am I So Out Of Touch?\
  \ Uploaded by mnemeros Am I So Out Of Touch? Uploaded by Kotor Am I So Out Of Touch?\
  \ Uploaded by Mr. Nobody Returns + Add an Image View All Images Sign up for our\
  \ Newsletter Top Comments Delete Sensitive H.UNgrammar Mar 01, 2016 at 03:12PM EST\
  \ Out of touch? Children who are the wrong? I know the guy who can help! +48 Reply\
  \ Delete Sensitive Adam DeLand Mar 01, 2016 at 04:00PM EST +18 Reply + Add a Comment\
  \ Comments (19) Display Comments Add a Comment Top Entries This Month Meme Saika\
  \ Kawakita Smile GIF Event Assassination of UnitedHealthcare CEO Person Luigi Mangione\
  \ UHC CEO Shooter Subculture The Ki Sisters Culture Pornography Site Whisper View\
  \ More Suggest a Change Edit History Entry Editors (9) Dreamworks Sr. Entry Moderator\
  \ & iFunnyologist & Turtle Emoji Z. Database Moderator & Rage Comicologist LNH Deactivated\
  \ Don Administrator & Meme Daddy Brad Digital Archaeologist & Treasurer & Pundit\
  \ & Gallery Housekeeper Y F Digital Archaeologist & Treasurer & Media Maid shevyrolet\
  \ Digital Archaeologist & Treasurer & Media Bus Boy Autumn Able Sr. Entry Moderator\
  \ Rose Abrams Entry Moderator \u25BC + Request Editorship View All Editors Today's\
  \ Top Image Galleries Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen\
  \ Green) Team Fortress 2 The Amazing Digital Circus About Our Story Site Rules Policies\
  \ and Guidelines Credits Contact Meme DB Memes Episodes News Staff Contact Extras!\
  \ Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/am-i-out-of-touch
template_id: touch
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.3
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: default
text_zones: 2
