name: Principal Skinner
source: https://knowyourmeme.com/memes/am-i-out-of-touch
keywords:
- Am I Out Of Touch?
- The Simpsons
text:
- style: default
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.3
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- Am I so out of touch?
- No, it's the children who are wrong.
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About "Am I Out Of Touch" is a two-panel image macro featuring the
  character Principal Skinner from The Simpsons. along with the caption "Am I out
  of touch? No, it's the children who are wrong." The comic is typically used as a
  reaction image on image boards and discussion forums to express a disconnect with
  contemporary youth a culture. Origin The comic originates from a scene in Season
  5 Episode 20 of The Simpsons titled "The Boy Who Knew Too Much," which first aired
  on May 5th, 1994.[1] In the scene, Principal Skinner briefly questions if he is
  out of touch before assuring himself that "It's the children who are wrong" (shown
  below). On October 29th, 2013, Redditor GhostRidingtheWhip submitted a two-panel
  comic of the scene in a post titled "I'm starting to dislike all new hiphop and
  pop music, this pretty much sums up my experience" (shown below). Prior to being
  archived, the post gained over 3,100 votes (95% upvoted) and 1,100 comments on the
  /r/funny[4] subreddit. Spread On November 20th, 2013, Redditor NoahJAustin submitted
  the reaction image in a post titled "I work IT for a few schools. This. Everyday"
  on /r/funny.[5] On January 27th, 2014, Redditor Spider_Dude posted the image macro
  to convey a feelings of being out of touch with contemporary pop music. Prior to
  being archived, the post gathered more than 3,100 votes (91% upvoted) on /r/funny.[6]
  On April 7th, 2014, the image was posted to the /r/TheSimpsons subreddit[2] On January
  6th, 2015, Tumblr user smitethepatriarchy[3] posted a cropped version of the original
  image, gaining over 200,000 notes over the next year. Various Examples Search Interest
  External References [1] Simpsons Wiki – The Boy Who Knew Too Much [2] Reddit – Am
  I so out of touch? [3] Tumblr – gets zero notes on a post [4] Reddit – Im starting
  to dislike all new hiphop and pop music this pretty much sums up my experience [5]
  Reddit – I work IT for a few schools [6] Reddit – Basically how i feel about the
  AMAs and the Grammys since 2002.
aside_content: MemeStatusConfirmedYear1994OriginThe SimpsonsTagsthe simpsons,principle
  skinner,children,spider_dude,ghostridingthewhip,noahjaustin,smitethepatriarchyAdditional
  ReferencesMeme GeneratorTenor GIF
added_at: '2016-02-27T14:29:56-05:00'
