example:
- oh, you just graduated?
- you must know everything
keywords:
- null
name: Condescending Wonka
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Condescending Wonka / Creepy Wonka | Know Your Meme O HAI! You must\
  \ login or signup first! Already a memeber? Login Now! Don't have an account? Sign\
  \ up Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos\
  \ Submit \u2192 Images Trending Most Commented Most Favorited High Score Low Score\
  \ Most Viewed All Templates Upload an Image Articles News Explainers Collections\
  \ Interviews Meme Insider Magazine More Discord Newsletter Episodes Forums Meme\
  \ Store Login Abstract user icon Memes Categories Trending News Images Trending\
  \ Images Videos Trending Videos Editorials Meme Insider Magazine Newsletter Policies\
  \ and Guidelines Meme Store Old site Login Know Your Meme is the property of Literally\
  \ Media \xA92024 Literally Media. All Rights Reserved. This image Of Woman Confidently\
  \ Strolling Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years\
  \ Ago, This Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The\
  \ Anarchy Chess Memes Turns Two Years Old Today Phrase 'The Fridge Protects The\
  \ Snacks' A Growing Favorite Among Pickup Artist Influencers Jamie G, The Bosh British\
  \ Charva, Has Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also\
  \ Trending: Honey Extension Influencer Scam Renegade Raider Copypasta Assassination\
  \ of UnitedHealthcare CEO Condescending Wonka / Creepy Wonka Added 12 years ago\
  \ / Updated about 16 hours ago Confirmed 1,059,332 Part of a series on Advice Animals.\
  \ [View Related Entries] View All 341 Images Navigation About \u2022 Origin \u2022\
  \ Spread \u2022 Notable Examples \u2022 Search Interest \u2022 External References\
  \ \u2022 Recent Images \u2022 Recent Videos About Condescending Wonka is an advice\
  \ animals image macro series featuring a screen capture of actor Gene Wilder in\
  \ the 1971 musical Willy Wonka and the Chocolate Factory. As its name suggests,\
  \ the captions can be characterized as patronizing and sarcastic. Origin The image\
  \ comes from a scene in the 1971 musical Willy Wonka & the Chocolate Factory in\
  \ which Willy Wonka, played by Gene Wilder, asks the children if they would like\
  \ to see a new candy he is working on called \"The Everlasting Gobstopper.\" On\
  \ the web, Wilder's picture from the film was introduced in January 2011 through\
  \ an instance of the \"You Must Be New Here\" reaction face. The image soon became\
  \ associated with other captions, from which emerged the advice animal series \"\
  Creepy Wonka\" featuring various double entendres with allusions to candies or confectioneries.\
  \ The earliest known image macro (shown below, left) was submitted to Quickmeme[3]\
  \ with the caption \"Close the door / I'll show my my fudge packing unit\" on March\
  \ 2nd, 2011. It was subsequently posted to the /r/pics subreddit[6] the same day,\
  \ where it was marked as spam for breaking the \"no comics/macros\" rule. The series\
  \ was renamed \"Condescending Wonka\" for the first time in October 2011 after it\
  \ was paired with the caption \"Oh, you just graduated? / you must know everything\"\
  \ in an instance submitted to Quickmeme.[7] The image was posted to Reddit[8] the\
  \ same day and reached the front page of the /r/pics subreddit prior to being marked\
  \ as spam for breaking the \"no comics/macros\" rule as well. Spread On October\
  \ 12th, 2011, the web culture blog The Bigster[9] posted a compilation of Creepy\
  \ Wonka derivatives. On November 27th, 2011, Redditor chicagowillbeours posted a\
  \ thread titled \"Let's all agree to change his name to 'Condescending Wonka'\"\
  \ that reached the front page of the Advice Animals subreddit. A Quickmeme[2] page\
  \ for \"Condescending Wonka\" was created on November 28th, 2011 and it has accumulated\
  \ more than 127,217 submissions as of June 2012. On January 8th, 2012, Redditor\
  \ hannibl posted a photo of a Weimaraner dog with the caption \"Oh, you run a chocolate\
  \ lab? / I am a chocolate lab.\" The thread reached the front page and accumulated\
  \ over 8,500 up votes within 5 days. Creepy Wonka macros have since spread to FunnyJunk[5]\
  \ and the Condescending Wonka macros can be found on Tumblr[4] under the \"#condescending\
  \ wonka\" tag. The original Creepy Wonka Quickmeme[1] page had accumulated over\
  \ 6,500 images in 9 months. Notable Examples Search Interest Search queries for\
  \ \"creepy wonka\" and \"condescending wonka\" picked up in October of 2011, the\
  \ same month the first Condescending Wonka macro was submitted to Quickmeme. External\
  \ References [1] Quickmeme \u2013 Creepy Wonka [2] Quickmeme \u2013 Condescending\
  \ Wonka [3] Quickmeme \u2013 Close the door [4] Tumblr \u2013 condescending wonka\
  \ [5] FunnyJunk \u2013 creepy wonka= [6] Reddit \u2013 Creepy Wonka [7] Quickmeme\
  \ \u2013 Oh, You Just Graduated? [8] Reddit \u2013 Every time I speak to a recent\
  \ grad\u2026 [9] The Bigster \u2013 The Best of Creepy Wonka [10] Reddit \u2013\
  \ Being condescending to Wonka [11] Reddit \u2013 Let's all agree to change his\
  \ name willy wonka unimpressed condescending how interesting esta muy interesante\
  \ interesante cuentame mas do tell more reaction image Share Pin Related Entries\
  \ 115 total Ermahgerd Overly Attached Girlfriend Scumbag Steve Good Guy Greg View\
  \ All Related Entries Recent Images 341 total View All Images Recent Videos 4 total\
  \ View All Videos Sign up for our Newsletter Load 107 Comments Comments 107 total\
  \ 133 Condescending Wonka / Creepy Wonka 1,059,332 4 341 107 Part of a series on\
  \ Advice Animals. [View Related Entries] Updated Dec 23, 2024 at 04:12PM EST by\
  \ LiterallyAustin. Added Jan 13, 2012 at 02:49PM EST by Don. Like us on Facebook!\
  \ Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to\
  \ view the video gallery, or 'r' to view a random entry. Meme Status Confirmed Year\
  \ 2010 Origin Quickmeme Tags willy wonka, unimpressed, condescending, how interesting,\
  \ esta muy interesante, interesante, cuentame mas, do tell more, reaction image\
  \ About Condescending Wonka is an advice animals image macro series featuring a\
  \ screen capture of actor Gene Wilder in the 1971 musical Willy Wonka and the Chocolate\
  \ Factory. As its name suggests, the captions can be characterized as patronizing\
  \ and sarcastic. Origin The image comes from a scene in the 1971 musical Willy Wonka\
  \ & the Chocolate Factory in which Willy Wonka, played by Gene Wilder, asks the\
  \ children if they would like to see a new candy he is working on called \"The Everlasting\
  \ Gobstopper.\" On the web, Wilder's picture from the film was introduced in January\
  \ 2011 through an instance of the \"You Must Be New Here\" reaction face. The image\
  \ soon became associated with other captions, from which emerged the advice animal\
  \ series \"Creepy Wonka\" featuring various double entendres with allusions to candies\
  \ or confectioneries. The earliest known image macro (shown below, left) was submitted\
  \ to Quickmeme[3] with the caption \"Close the door / I'll show my my fudge packing\
  \ unit\" on March 2nd, 2011. It was subsequently posted to the /r/pics subreddit[6]\
  \ the same day, where it was marked as spam for breaking the \"no comics/macros\"\
  \ rule. The series was renamed \"Condescending Wonka\" for the first time in October\
  \ 2011 after it was paired with the caption \"Oh, you just graduated? / you must\
  \ know everything\" in an instance submitted to Quickmeme.[7] The image was posted\
  \ to Reddit[8] the same day and reached the front page of the /r/pics subreddit\
  \ prior to being marked as spam for breaking the \"no comics/macros\" rule as well.\
  \ Spread On October 12th, 2011, the web culture blog The Bigster[9] posted a compilation\
  \ of Creepy Wonka derivatives. On November 27th, 2011, Redditor chicagowillbeours\
  \ posted a thread titled \"Let's all agree to change his name to 'Condescending\
  \ Wonka'\" that reached the front page of the Advice Animals subreddit. A Quickmeme[2]\
  \ page for \"Condescending Wonka\" was created on November 28th, 2011 and it has\
  \ accumulated more than 127,217 submissions as of June 2012. On January 8th, 2012,\
  \ Redditor hannibl posted a photo of a Weimaraner dog with the caption \"Oh, you\
  \ run a chocolate lab? / I am a chocolate lab.\" The thread reached the front page\
  \ and accumulated over 8,500 up votes within 5 days. Creepy Wonka macros have since\
  \ spread to FunnyJunk[5] and the Condescending Wonka macros can be found on Tumblr[4]\
  \ under the \"#condescending wonka\" tag. The original Creepy Wonka Quickmeme[1]\
  \ page had accumulated over 6,500 images in 9 months. Notable Examples Search Interest\
  \ Search queries for \"creepy wonka\" and \"condescending wonka\" picked up in October\
  \ of 2011, the same month the first Condescending Wonka macro was submitted to Quickmeme.\
  \ External References [1] Quickmeme \u2013 Creepy Wonka [2] Quickmeme \u2013 Condescending\
  \ Wonka [3] Quickmeme \u2013 Close the door [4] Tumblr \u2013 condescending wonka\
  \ [5] FunnyJunk \u2013 creepy wonka= [6] Reddit \u2013 Creepy Wonka [7] Quickmeme\
  \ \u2013 Oh, You Just Graduated? [8] Reddit \u2013 Every time I speak to a recent\
  \ grad\u2026 [9] The Bigster \u2013 The Best of Creepy Wonka [10] Reddit \u2013\
  \ Being condescending to Wonka [11] Reddit \u2013 Let's all agree to change his\
  \ name Related Entries 115 total Ermahgerd Overly Attached Girlfriend Scumbag Steve\
  \ Good Guy Greg Ridiculously Photogenic Guy Bad Luck Brian Philosoraptor Annoying\
  \ Facebook Girl The Most Interesting Man in the World Socially Awkward Penguin Bear\
  \ Grylls / Better Drink My Own Piss Successful Black Man View All Related Entries\
  \ Recent Videos 4 total Gene Wilder's greatest qualit... Condescending Wonka / Creepy\
  \ ... Uploaded by ThatOtherGuy80 RIP GENE WILDER (1933 - 2016)... Condescending\
  \ Wonka / Creepy ... Uploaded by ThatOtherGuy80 ANIMEME - Condescending Wonka Condescending\
  \ Wonka / Creepy ... Uploaded by Whales Are cool Scrumdiddlyumptious (Willy Wo...\
  \ Condescending Wonka / Creepy ... Uploaded by lifeiscrazy333888 + Add a Video Recent\
  \ Images 341 total Condescending Wonka / Creepy ... Uploaded by Jaimie Hamilton\
  \ Condescending Wonka / Creepy ... Uploaded by Rebecca Rhodes Condescending Wonka\
  \ / Creepy ... Uploaded by Adam B. Condescending Wonka / Creepy ... Uploaded by\
  \ VenHur Condescending Wonka / Creepy ... Uploaded by Tysonist Condescending Wonka\
  \ / Creepy ... Uploaded by SiRenfield Condescending Wonka / Creepy ... Uploaded\
  \ by luis009 Condescending Wonka / Creepy ... Uploaded by olicool10 Condescending\
  \ Wonka / Creepy ... Uploaded by m Condescending Wonka / Creepy ... Uploaded by\
  \ FigureGunplaFan Condescending Wonka / Creepy ... Uploaded by Danger Mountain Condescending\
  \ Wonka / Creepy ... Uploaded by joecool123 + Add an Image View All Images Sign\
  \ up for our Newsletter Top Comments Delete Sensitive Espurr Aug 29, 2016 at 04:04PM\
  \ EDT in reply to Espurr +60 Reply Delete Sensitive Thekidwiththehat Jan 13, 2012\
  \ at 07:47PM EST I believe this actually started on 4chan, in the form of \"You\
  \ must be new here\". +50 Reply + Add a Comment Comments (107) Display Comments\
  \ Add a Comment Top Entries This Month Meme Saika Kawakita Smile GIF Event Assassination\
  \ of UnitedHealthcare CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki\
  \ Sisters Culture Pornography Site Whisper View More Suggest a Change Edit History\
  \ Entry Editors (5) Don Administrator & Meme Daddy Tomberry Database Moderator &\
  \ French Specialist & Pony Hater Brad Digital Archaeologist & Treasurer & Pundit\
  \ & Gallery Housekeeper Particle Mare Wolf of Meme Street SabrinaTibbetts Memepuff\
  \ \u25BC + Request Editorship View All Editors Today's Top Image Galleries Assassination\
  \ of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing\
  \ Digital Circus About Our Story Site Rules Policies and Guidelines Credits Contact\
  \ Meme DB Memes Episodes News Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/condescending-wonka-creepy-wonka
template_id: wonka
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
