name: Condescending Wonka
source: http://knowyourmeme.com/memes/condescending-wonka-creepy-wonka
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- oh, you just graduated?
- you must know everything
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About Condescending Wonka is an advice animals image macro series
  featuring a screen capture of actor Gene Wilder in the 1971 musical Willy Wonka
  and the Chocolate Factory. As its name suggests, the captions can be characterized
  as patronizing and sarcastic. Origin The image comes from a scene in the 1971 musical
  Willy Wonka & the Chocolate Factory in which Willy Wonka, played by Gene Wilder,
  asks the children if they would like to see a new candy he is working on called
  "The Everlasting Gobstopper." On the web, Wilder's picture from the film was introduced
  in January 2011 through an instance of the "You Must Be New Here" reaction face.
  The image soon became associated with other captions, from which emerged the advice
  animal series "Creepy Wonka" featuring various double entendres with allusions to
  candies or confectioneries. The earliest known image macro (shown below, left) was
  submitted to Quickmeme[3] with the caption "Close the door / I'll show my my fudge
  packing unit" on March 2nd, 2011. It was subsequently posted to the /r/pics subreddit[6]
  the same day, where it was marked as spam for breaking the "no comics/macros" rule.
  The series was renamed "Condescending Wonka" for the first time in October 2011
  after it was paired with the caption "Oh, you just graduated? / you must know everything"
  in an instance submitted to Quickmeme.[7] The image was posted to Reddit[8] the
  same day and reached the front page of the /r/pics subreddit prior to being marked
  as spam for breaking the "no comics/macros" rule as well. Spread On October 12th,
  2011, the web culture blog The Bigster[9] posted a compilation of Creepy Wonka derivatives.
  On November 27th, 2011, Redditor chicagowillbeours posted a thread titled "Let's
  all agree to change his name to 'Condescending Wonka'" that reached the front page
  of the Advice Animals subreddit. A Quickmeme[2] page for "Condescending Wonka" was
  created on November 28th, 2011 and it has accumulated more than 127,217 submissions
  as of June 2012. On January 8th, 2012, Redditor hannibl posted a photo of a Weimaraner
  dog with the caption "Oh, you run a chocolate lab? / I am a chocolate lab." The
  thread reached the front page and accumulated over 8,500 up votes within 5 days.
  Creepy Wonka macros have since spread to FunnyJunk[5] and the Condescending Wonka
  macros can be found on Tumblr[4] under the "#condescending wonka" tag. The original
  Creepy Wonka Quickmeme[1] page had accumulated over 6,500 images in 9 months. Notable
  Examples Search Interest Search queries for "creepy wonka" and "condescending wonka"
  picked up in October of 2011, the same month the first Condescending Wonka macro
  was submitted to Quickmeme. External References [1] Quickmeme – Creepy Wonka [2]
  Quickmeme – Condescending Wonka [3] Quickmeme – Close the door [4] Tumblr – condescending
  wonka [5] FunnyJunk – creepy wonka= [6] Reddit – Creepy Wonka [7] Quickmeme – Oh,
  You Just Graduated? [8] Reddit – Every time I speak to a recent grad… [9] The Bigster
  – The Best of Creepy Wonka [10] Reddit – Being condescending to Wonka [11] Reddit
  – Let's all agree to change his name
aside_content: MemeStatusConfirmedYear2010OriginQuickmemeTagswilly wonka,unimpressed,condescending,how
  interesting,esta muy interesante,interesante,cuentame mas,do tell more,reaction
  image
added_at: '2012-01-13T14:49:59-05:00'
