name: Get Better Material
source: https://knowyourmeme.com/memes/get-better-material
keywords:
- null
text:
- style: upper
  color: black
  font: comic
  anchor_x: 0.325
  anchor_y: 0.02
  angle: 0.0
  scale_x: 0.15
  scale_y: 0.15
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: black
  font: comic
  anchor_x: 0.615
  anchor_y: 0.72
  angle: 12.0
  scale_x: 0.3
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- Caw Caw Caw
- Caw Caw Caw Caw Caw Caw
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About Get Better Material refers to a series of exploitable images
  based on a False Knees webcomic. In the meme, a bird is performing stand-up comedy.
  However, when a heckler boos the bird and says to "get better material," the bird
  looks at its notes only to realize that it does not have any other material. Origin
  On August 26th, 2016, Josh Barkman, the artist and writer of the webcomic False
  Knees, published the episode "Stand-up Cawmedian" on Tumblr [1] and his website.[2]
  In the issue, a crow performs stand-up comedy, saying "caw caw caw." A heckler in
  the audience then screams "Boo! Get better material!" Visibly nervous, the crow
  looks at its notes, which read "caw caw caw caw," indicating that that's all the
  bird has. The post (shown below) received more than 2,000 notes on Tumblr as of
  October 2017. Spread The following year, on September 26th, 2017, Twitter [4] user
  @pissed_eagel posted a four-panel version of the comic, receiving more than 8,000
  retweets and 20,000 likes in five days. Three days later, on September 29th, Redditor
  [3] jcdcwassup posted the comic in a four-panel, square format on the /r/me_irl
  subreddit. The post (shown below) received more than 30,000 points (91% upvoted)
  and 340 comments in three days. That day on the /r/NLSSCircleJerk subreddit, Redditor
  Wyattkins193 posted a variation in whcih the first two panels of the comic are photoshopped.
  In this variant, the crow says "60 years old should be euthanized and the heckler
  says "My dad just turned 60!" Within two days, the post received more than 780 points
  (96% upvoted). Various Examples Template External References [1] Tumblr – Falseknees'
  Post [2] False Knees – Stand-up Cawmedian [3] Reddit – me_irl [4] Twitter – @pissed_eagel's
  Post
aside_content: MemeStatusConfirmedType:ExploitableYear2017OriginFalse Knees WebcomicTagsfalse
  knees,birds,caw caw,stand-up cawmedian,josh barkman,web comics,stand-up comedy
added_at: '2017-10-02T10:48:41-04:00'
