example:
- Caw Caw Caw
- Caw Caw Caw Caw Caw Caw
keywords:
- null
name: Get Better Material
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Get Better Material | Know Your Meme Hi! You must login or signup\
  \ first! Already a memeber? Login Now! Don't have an account? Sign up Now! Meme\
  \ Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Get Better Material Added 7 years ago / Updated 8 days ago Confirmed 118,190\
  \ Part of a series on False Knees. [View Related Entries] View All 26 Images Navigation\
  \ About \u2022 Origin \u2022 Spread \u2022 Various Examples \u2022 External References\
  \ \u2022 Recent Images About Get Better Material refers to a series of exploitable\
  \ images based on a False Knees webcomic. In the meme, a bird is performing stand-up\
  \ comedy. However, when a heckler boos the bird and says to \"get better material,\"\
  \ the bird looks at its notes only to realize that it does not have any other material.\
  \ Origin On August 26th, 2016, Josh Barkman, the artist and writer of the webcomic\
  \ False Knees, published the episode \"Stand-up Cawmedian\" on Tumblr [1] and his\
  \ website.[2] In the issue, a crow performs stand-up comedy, saying \"caw caw caw.\"\
  \ A heckler in the audience then screams \"Boo! Get better material!\" Visibly nervous,\
  \ the crow looks at its notes, which read \"caw caw caw caw,\" indicating that that's\
  \ all the bird has. The post (shown below) received more than 2,000 notes on Tumblr\
  \ as of October 2017. Spread The following year, on September 26th, 2017, Twitter\
  \ [4] user @pissed_eagel posted a four-panel version of the comic, receiving more\
  \ than 8,000 retweets and 20,000 likes in five days. Three days later, on September\
  \ 29th, Redditor [3] jcdcwassup posted the comic in a four-panel, square format\
  \ on the /r/me_irl subreddit. The post (shown below) received more than 30,000 points\
  \ (91% upvoted) and 340 comments in three days. That day on the /r/NLSSCircleJerk\
  \ subreddit, Redditor Wyattkins193 posted a variation in whcih the first two panels\
  \ of the comic are photoshopped. In this variant, the crow says \"60 years old should\
  \ be euthanized and the heckler says \"My dad just turned 60!\" Within two days,\
  \ the post received more than 780 points (96% upvoted). Various Examples Template\
  \ External References [1] Tumblr \u2013 Falseknees' Post [2] False Knees \u2013\
  \ Stand-up Cawmedian [3] Reddit \u2013 me_irl [4] Twitter \u2013 @pissed_eagel's\
  \ Post false knees birds caw caw stand-up cawmedian josh barkman web comics stand-up\
  \ comedy Share Pin Related Entries 2 total Annoyed Bird Wasn't This Leaf Green Before?\
  \ Recent Images 26 total View All Images Recent Videos 0 total There are no recent\
  \ videos. Sign up for our Newsletter Load 19 Comments Comments 19 total 8 Get Better\
  \ Material 118,190 0 26 19 Part of a series on False Knees. [View Related Entries]\
  \ Updated Dec 15, 2024 at 04:34PM EST by LiterallyAustin. Added Oct 02, 2017 at\
  \ 10:48AM EDT by Matt. Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press\
  \ 'i' to view the image gallery, 'v' to view the video gallery, or 'r' to view a\
  \ random entry. Meme Status Confirmed Type: Exploitable Year 2017 Origin False Knees\
  \ Webcomic Tags false knees, birds, caw caw, stand-up cawmedian, josh barkman, web\
  \ comics, stand-up comedy About Get Better Material refers to a series of exploitable\
  \ images based on a False Knees webcomic. In the meme, a bird is performing stand-up\
  \ comedy. However, when a heckler boos the bird and says to \"get better material,\"\
  \ the bird looks at its notes only to realize that it does not have any other material.\
  \ Origin On August 26th, 2016, Josh Barkman, the artist and writer of the webcomic\
  \ False Knees, published the episode \"Stand-up Cawmedian\" on Tumblr [1] and his\
  \ website.[2] In the issue, a crow performs stand-up comedy, saying \"caw caw caw.\"\
  \ A heckler in the audience then screams \"Boo! Get better material!\" Visibly nervous,\
  \ the crow looks at its notes, which read \"caw caw caw caw,\" indicating that that's\
  \ all the bird has. The post (shown below) received more than 2,000 notes on Tumblr\
  \ as of October 2017. Spread The following year, on September 26th, 2017, Twitter\
  \ [4] user @pissed_eagel posted a four-panel version of the comic, receiving more\
  \ than 8,000 retweets and 20,000 likes in five days. Three days later, on September\
  \ 29th, Redditor [3] jcdcwassup posted the comic in a four-panel, square format\
  \ on the /r/me_irl subreddit. The post (shown below) received more than 30,000 points\
  \ (91% upvoted) and 340 comments in three days. That day on the /r/NLSSCircleJerk\
  \ subreddit, Redditor Wyattkins193 posted a variation in whcih the first two panels\
  \ of the comic are photoshopped. In this variant, the crow says \"60 years old should\
  \ be euthanized and the heckler says \"My dad just turned 60!\" Within two days,\
  \ the post received more than 780 points (96% upvoted). Various Examples Template\
  \ External References [1] Tumblr \u2013 Falseknees' Post [2] False Knees \u2013\
  \ Stand-up Cawmedian [3] Reddit \u2013 me_irl [4] Twitter \u2013 @pissed_eagel's\
  \ Post Related Entries 2 total Annoyed Bird Wasn't This Leaf Green Before? Recent\
  \ Videos There are no videos currently available. + Add a Video Recent Images 26\
  \ total Get Better Material Uploaded by Lugamo Get Better Material Uploaded by Lugamo\
  \ Get Better Material Uploaded by Lugamo Get Better Material Uploaded by Knightshade\
  \ Get Better Material Uploaded by Pepe 3 & Wojak Get Better Material Uploaded by\
  \ Mr. Nobody Returns Get Better Material Uploaded by Bilbo Swaggins Get Better Material\
  \ Uploaded by Philipp Get Better Material Uploaded by thesmashbro Get Better Material\
  \ Uploaded by Sum Lu Zer Get Better Material Uploaded by tygerbug Get Better Material\
  \ Uploaded by tygerbug + Add an Image View All Images Sign up for our Newsletter\
  \ Top Comments Delete Sensitive Elbough La Zoreille Oct 02, 2017 at 12:49PM EDT\
  \ \"An exploitable webcomic to make fn of unpopular opinions and everything OP doesn't\
  \ like\" \"Boo! Get better material!\" \"\u2026\" +56 Reply Delete Sensitive Nightfury\
  \ Treann Oct 02, 2017 at 01:13PM EDT +50 Reply + Add a Comment Comments (19) Display\
  \ Comments Add a Comment Top Entries This Month Meme Saika Kawakita Smile GIF Event\
  \ Assassination of UnitedHealthcare CEO Person Luigi Mangione UHC CEO Shooter Subculture\
  \ The Ki Sisters Culture Pornography Site Whisper View More Suggest a Change Edit\
  \ History Entry Editors (4) Matt Secretary of Memes Adam Know Your Meme Universal\
  \ Champion Y F Digital Archaeologist & Treasurer & Media Maid Philipp Memesplainer\
  \ + Request Editorship View All Editors Today's Top Image Galleries Assassination\
  \ of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing\
  \ Digital Circus About Our Story Site Rules Policies and Guidelines Credits Contact\
  \ Meme DB Memes Episodes News Staff Contact Extras! Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/get-better-material
template_id: crow
text:
- align: center
  anchor_x: 0.325
  anchor_y: 0.02
  angle: 0.0
  color: black
  font: comic
  scale_x: 0.15
  scale_y: 0.15
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.615
  anchor_y: 0.72
  angle: 12.0
  color: black
  font: comic
  scale_x: 0.3
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
