name: Error
source:
keywords:
  -
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.1
    anchor_y: 0.7
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - Top Line
  - Bottom Line
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
