name: It's A Trap!
source: http://knowyourmeme.com/memes/its-a-trap
keywords:
- Star Wards
- Admiral Ackbar
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- ''
- it's a trap!
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About It''s A Trap! is a catchphrase originating from the Star Wars
  character Admiral Ackbar, appearing in the 1983 film Episode VI: Return of the Jedi.
  The phrase and reaction image or GIF are used in a variety of ways online, sometimes
  in reactions to photos of transgender people (sometimes controversially referred
  to as "traps") or people who appear sexually ambiguous, as well as a warning of
  any potential danger more literally. In addition, the quote as it appears in the
  film has been widely regarded by the fans of Star Wars as one of the most famous
  and beloved lines from the original trilogy. Origin The phrase stems from a memorable
  quote said by Admiral Ackbar (voiced by Erik Bauersfeld),[14] the leader of Mon
  Calamari rebels, during the Battle of Endor in the 1983 Star Wars film Episode VI:
  Return of the Jedi.[9] In the movie, as the Alliance mobilize its forces in a concerted
  effort to destroy the Death Star, Admiral Ackbar encounters an unexpected ambush,
  which leads him to exclaim, "It''s a trap!"[1][10] Admiral Ackbar: "Take evasive
  action. Green Group, stay close to holding sector MD-7." Crewman: "Admiral, we have
  enemy ships in sector 47!" Admiral Ackbar: "It''s a trap!" Spread Sometime in the
  early 2000s, Something Awful administrator OMGWTFBBQ created and uploaded an image
  macro based on a screenshot of Admiral Ackbar from Return of the Jedi with the caption
  that reads "IT''S A TRAP." According to various accounts, the image macro soon became
  adopted as a popular reaction image used to warn others of a potential bait-and-switch
  prank ahead, and by mid-to-late 2002, the phrase had made its way to FARK and continued
  to gain traction as a running joke in Photoshop Phriday threads.[11] Beginning in
  2004, the joke spawned hundreds of parody sites featuring the soundbite of Admiral
  Ackbar''s quote on YTMND,[5] with the most notable instance uploaded by user MultiKoopa
  on June 2nd, 2005, which has garnered more than 313,000 views (as of April 2016).[6][7][8]
  Around the same time, shortly after the launch of the imageboard community 4chan,
  the phrase became closely associated with traps, a slang term for a photograph of
  a model or illustration of an anime character wherein the gender of the subject
  seems to be ambiguous or androgynous in appearance.[12] Following the launch of
  YouTube in 2005, more than a thousand fan-made videos that prominently feature or
  parody Admiral Ackbar''s line and the extended dialogue were uploaded to the video-sharing
  site.[15] On May 20th, 2009, an Urban Dictionary[2] entry was created for the phrase:
  A phrase based on a misspelling of "It''s a trap" a phrase and meme said by Ackbar
  in Star Wars Episode VI. It is popularly used sarcastically on message boards and
  chan sites. /b/tard #1: It''s a trap! /b/tard #2: No! It''s a tarp! Star Wars: The
  Force Unleashed In the Nintendo Wii version of LucasArts'' action-adventure video
  game Star Wars: The Force Unleashed, released on September 16th, 2008, Admiral Ackbar
  can be played as a hidden character if the player enters the cheat code "ITSATWAP."
  "It''s a TARP!" "It''s a Tarp!" is an intentional misspelling that spawned one of
  the more frequently posted derivatives. According to Google Trends, search queries
  for "it''s a tarp" picked up in April 2008. Several months later, the Obama administration''s
  introduction of the "Troubled Asset Relief Program," shortened as TARP, inspired
  a batch of additional derivatives.[3][4] On Comedy Central On February 11th, 2010,
  footage of Admiral Ackbar reciting the line was featured in two separate segments
  on Comedy Central''s The Daily Show and The Colbert Report, wherein the soundbite
  is intercut with news reel clips of Republican leaders describing an invitation
  to President Barack Obama''s health care summit as a "trap." On Family Guy On December
  21st, 2010, American animated TV series Family Guy released a direct-to-video special
  episode titled "It''s a Trap," which retells the story of Star Wars: Return of the
  Jedi, as the final chapter of the show''s Star Wars parody trilogy, with the other
  two being "Laugh It Up" and "Fuzzball." On May 22nd, 2011, Fox aired the hour-long
  special as the double-episode finale of Family Guy''s ninth season.[13] Search Interest
  External References [1] TVwiki – It''s a trap! [2] Urban Dictionary – It''s a tarp!
  / 5/20/2009 [3] LOLfed – It''s a TARP [4] Memebase – Admiral Ackbar [5] YTMND –
  Search Results for ''It''s a Trap'' [6] YTMND – It''s a trap [7] YTMND – It''s a
  trap it''s a trap it''s a trap it''s a trap it''s a trap it''s a trap [8] YTMND
  – It''s a trap rap [9] Wikipedia – "It''s a Trap!"! [10] Wikipedia – Admiral Ackbar
  [11] FARK – Photoshop Phriday: Goons show off their PS chops by making everything
  Batman themed [12] StraightDope Forum – ''It''s a Trap'' [13] Yahoo Movies – The
  Enduring Cult of Admiral Ackbar, ''Return of the Jedi''s'' Rebel Hero [14] Hollywood
  Reporter – Erik Bauersfeld, Admiral Ackbar Voice Actor in ''Star Wars'' Films, Dies
  at 93 [15] YouTube – Search Results for ''It''s a Trap'''
aside_content: MemeStatusConfirmedType:Catchphrase,Pop Culture Reference,ReactionYear2002OriginStar
  WarsRegionUnited StatesTagscatchphrase,star wars,film,fish,animals,sci-fi,image
  macro,ascii,movie,quote,pop culture,snowclone,comment,comments,movie quote,reaction
  image,admiral ackbar,multikoopaAdditional ReferencesEncyclopedia DramaticaWikipedia
added_at: '2009-04-16T22:21:01-04:00'
