example:
- ''
- it's a trap!
keywords:
- Star Wards
- Admiral Ackbar
name: It's A Trap!
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "It's A Trap! | Know Your Meme Howdy! You must login or signup first!\
  \ Already a memeber? Login Now! Don't have an account? Sign up Now! Meme Encyclopedia\
  \ All Cultures Events People Sites Subcultures Videos Submit \u2192 Images Trending\
  \ Most Commented Most Favorited High Score Low Score Most Viewed All Templates Upload\
  \ an Image Articles News Explainers Collections Interviews Meme Insider Magazine\
  \ More Discord Newsletter Episodes Forums Meme Store Login Abstract user icon Memes\
  \ Categories Trending News Images Trending Images Videos Trending Videos Editorials\
  \ Meme Insider Magazine Newsletter Policies and Guidelines Meme Store Old site Login\
  \ Know Your Meme is the property of Literally Media \xA92024 Literally Media. All\
  \ Rights Reserved. This image Of Woman Confidently Strolling Through A Glass Panel\
  \ Has Been A Redraw Format Since 2021 Three Years Ago, This Boar's Head 'Exploded'\
  \ Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess Memes Turns Two Years\
  \ Old Today Phrase 'The Fridge Protects The Snacks' A Growing Favorite Among Pickup\
  \ Artist Influencers Jamie G, The Bosh British Charva, Has Taken Over TikTok With\
  \ His Signature 'Oh Cherie Amour' Sound Also Trending: Honey Extension Influencer\
  \ Scam Renegade Raider Copypasta Assassination of UnitedHealthcare CEO It's A Trap!\
  \ Added 15 years ago / Updated 8 days ago Confirmed 1,387,307 Part of a series on\
  \ Star Wars. [View Related Entries] [View Related Sub-entries] View All 125 Images\
  \ Navigation About \u2022 Origin \u2022 Spread \u2022 Search Interest \u2022 External\
  \ References \u2022 Recent Images \u2022 Recent Videos About It's A Trap! is a catchphrase\
  \ originating from the Star Wars character Admiral Ackbar, appearing in the 1983\
  \ film Episode VI: Return of the Jedi. The phrase and reaction image or GIF are\
  \ used in a variety of ways online, sometimes in reactions to photos of transgender\
  \ people (sometimes controversially referred to as \"traps\") or people who appear\
  \ sexually ambiguous, as well as a warning of any potential danger more literally.\
  \ In addition, the quote as it appears in the film has been widely regarded by the\
  \ fans of Star Wars as one of the most famous and beloved lines from the original\
  \ trilogy. Origin The phrase stems from a memorable quote said by Admiral Ackbar\
  \ (voiced by Erik Bauersfeld),[14] the leader of Mon Calamari rebels, during the\
  \ Battle of Endor in the 1983 Star Wars film Episode VI: Return of the Jedi.[9]\
  \ In the movie, as the Alliance mobilize its forces in a concerted effort to destroy\
  \ the Death Star, Admiral Ackbar encounters an unexpected ambush, which leads him\
  \ to exclaim, \"It's a trap!\"[1][10] Admiral Ackbar: \"Take evasive action. Green\
  \ Group, stay close to holding sector MD-7.\" Crewman: \"Admiral, we have enemy\
  \ ships in sector 47!\" Admiral Ackbar: \"It's a trap!\" Spread Sometime in the\
  \ early 2000s, Something Awful administrator OMGWTFBBQ created and uploaded an image\
  \ macro based on a screenshot of Admiral Ackbar from Return of the Jedi with the\
  \ caption that reads \"IT'S A TRAP.\" According to various accounts, the image macro\
  \ soon became adopted as a popular reaction image used to warn others of a potential\
  \ bait-and-switch prank ahead, and by mid-to-late 2002, the phrase had made its\
  \ way to FARK and continued to gain traction as a running joke in Photoshop Phriday\
  \ threads.[11] Beginning in 2004, the joke spawned hundreds of parody sites featuring\
  \ the soundbite of Admiral Ackbar's quote on YTMND,[5] with the most notable instance\
  \ uploaded by user MultiKoopa on June 2nd, 2005, which has garnered more than 313,000\
  \ views (as of April 2016).[6][7][8] Around the same time, shortly after the launch\
  \ of the imageboard community 4chan, the phrase became closely associated with traps,\
  \ a slang term for a photograph of a model or illustration of an anime character\
  \ wherein the gender of the subject seems to be ambiguous or androgynous in appearance.[12]\
  \ Following the launch of YouTube in 2005, more than a thousand fan-made videos\
  \ that prominently feature or parody Admiral Ackbar's line and the extended dialogue\
  \ were uploaded to the video-sharing site.[15] On May 20th, 2009, an Urban Dictionary[2]\
  \ entry was created for the phrase: A phrase based on a misspelling of \"It's a\
  \ trap\" a phrase and meme said by Ackbar in Star Wars Episode VI. It is popularly\
  \ used sarcastically on message boards and chan sites. /b/tard #1: It's a trap!\
  \ /b/tard #2: No! It's a tarp! Star Wars: The Force Unleashed In the Nintendo Wii\
  \ version of LucasArts' action-adventure video game Star Wars: The Force Unleashed,\
  \ released on September 16th, 2008, Admiral Ackbar can be played as a hidden character\
  \ if the player enters the cheat code \"ITSATWAP.\" \"It's a TARP!\" \"It's a Tarp!\"\
  \ is an intentional misspelling that spawned one of the more frequently posted derivatives.\
  \ According to Google Trends, search queries for \"it's a tarp\" picked up in April\
  \ 2008. Several months later, the Obama administration's introduction of the \"\
  Troubled Asset Relief Program,\" shortened as TARP, inspired a batch of additional\
  \ derivatives.[3][4] On Comedy Central On February 11th, 2010, footage of Admiral\
  \ Ackbar reciting the line was featured in two separate segments on Comedy Central's\
  \ The Daily Show and The Colbert Report, wherein the soundbite is intercut with\
  \ news reel clips of Republican leaders describing an invitation to President Barack\
  \ Obama's health care summit as a \"trap.\" On Family Guy On December 21st, 2010,\
  \ American animated TV series Family Guy released a direct-to-video special episode\
  \ titled \"It's a Trap,\" which retells the story of Star Wars: Return of the Jedi,\
  \ as the final chapter of the show's Star Wars parody trilogy, with the other two\
  \ being \"Laugh It Up\" and \"Fuzzball.\" On May 22nd, 2011, Fox aired the hour-long\
  \ special as the double-episode finale of Family Guy's ninth season.[13] Search\
  \ Interest External References [1] TVwiki \u2013 It's a trap! [2] Urban Dictionary\
  \ \u2013 It's a tarp! / 5/20/2009 [3] LOLfed \u2013 It's a TARP [4] Memebase \u2013\
  \ Admiral Ackbar [5] YTMND \u2013 Search Results for 'It's a Trap' [6] YTMND \u2013\
  \ It's a trap [7] YTMND \u2013 It's a trap it's a trap it's a trap it's a trap it's\
  \ a trap it's a trap [8] YTMND \u2013 It's a trap rap [9] Wikipedia \u2013 \"It's\
  \ a Trap!\"! [10] Wikipedia \u2013 Admiral Ackbar [11] FARK \u2013 Photoshop Phriday:\
  \ Goons show off their PS chops by making everything Batman themed [12] StraightDope\
  \ Forum \u2013 'It's a Trap' [13] Yahoo Movies \u2013 The Enduring Cult of Admiral\
  \ Ackbar, 'Return of the Jedi's' Rebel Hero [14] Hollywood Reporter \u2013 Erik\
  \ Bauersfeld, Admiral Ackbar Voice Actor in 'Star Wars' Films, Dies at 93 [15] YouTube\
  \ \u2013 Search Results for 'It's a Trap' catchphrase star wars film fish animals\
  \ sci-fi image macro ascii movie quote pop culture snowclone comment comments movie\
  \ quote reaction image admiral ackbar multikoopa Share Pin Related Entries 64 total\
  \ Luke, I am Your Father Glup Shitto Red Leader Standing By Darth Vader's \"I Find\
  \ Your La... View All Related Entries Sub-entries 1 total Trap Recent Images 125\
  \ total View All Images Recent Videos 11 total View All Videos Sign up for our Newsletter\
  \ Load 64 Comments Comments 64 total 134 It's A Trap! 1,387,307 11 125 64 Part of\
  \ a series on Star Wars. [View Related Entries] [View Related Sub-entries] Updated\
  \ Dec 15, 2024 at 06:20PM EST by LiterallyAustin. Added Apr 16, 2009 at 10:21PM\
  \ EDT by Kenneth. Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press\
  \ 'i' to view the image gallery, 'v' to view the video gallery, or 'r' to view a\
  \ random entry. Meme Status Confirmed Type: Catchphrase, Pop Culture Reference,\
  \ Reaction Year 2002 Origin Star Wars Region United States Tags catchphrase, star\
  \ wars, film, fish, animals, sci-fi, image macro, ascii, movie, quote, pop culture,\
  \ snowclone, comment, comments, movie quote, reaction image, admiral ackbar, multikoopa\
  \ Additional References Encyclopedia Dramatica Wikipedia About It's A Trap! is a\
  \ catchphrase originating from the Star Wars character Admiral Ackbar, appearing\
  \ in the 1983 film Episode VI: Return of the Jedi. The phrase and reaction image\
  \ or GIF are used in a variety of ways online, sometimes in reactions to photos\
  \ of transgender people (sometimes controversially referred to as \"traps\") or\
  \ people who appear sexually ambiguous, as well as a warning of any potential danger\
  \ more literally. In addition, the quote as it appears in the film has been widely\
  \ regarded by the fans of Star Wars as one of the most famous and beloved lines\
  \ from the original trilogy. Origin The phrase stems from a memorable quote said\
  \ by Admiral Ackbar (voiced by Erik Bauersfeld),[14] the leader of Mon Calamari\
  \ rebels, during the Battle of Endor in the 1983 Star Wars film Episode VI: Return\
  \ of the Jedi.[9] In the movie, as the Alliance mobilize its forces in a concerted\
  \ effort to destroy the Death Star, Admiral Ackbar encounters an unexpected ambush,\
  \ which leads him to exclaim, \"It's a trap!\"[1][10] Admiral Ackbar: \"Take evasive\
  \ action. Green Group, stay close to holding sector MD-7.\" Crewman: \"Admiral,\
  \ we have enemy ships in sector 47!\" Admiral Ackbar: \"It's a trap!\" Spread Sometime\
  \ in the early 2000s, Something Awful administrator OMGWTFBBQ created and uploaded\
  \ an image macro based on a screenshot of Admiral Ackbar from Return of the Jedi\
  \ with the caption that reads \"IT'S A TRAP.\" According to various accounts, the\
  \ image macro soon became adopted as a popular reaction image used to warn others\
  \ of a potential bait-and-switch prank ahead, and by mid-to-late 2002, the phrase\
  \ had made its way to FARK and continued to gain traction as a running joke in Photoshop\
  \ Phriday threads.[11] Beginning in 2004, the joke spawned hundreds of parody sites\
  \ featuring the soundbite of Admiral Ackbar's quote on YTMND,[5] with the most notable\
  \ instance uploaded by user MultiKoopa on June 2nd, 2005, which has garnered more\
  \ than 313,000 views (as of April 2016).[6][7][8] Around the same time, shortly\
  \ after the launch of the imageboard community 4chan, the phrase became closely\
  \ associated with traps, a slang term for a photograph of a model or illustration\
  \ of an anime character wherein the gender of the subject seems to be ambiguous\
  \ or androgynous in appearance.[12] Following the launch of YouTube in 2005, more\
  \ than a thousand fan-made videos that prominently feature or parody Admiral Ackbar's\
  \ line and the extended dialogue were uploaded to the video-sharing site.[15] On\
  \ May 20th, 2009, an Urban Dictionary[2] entry was created for the phrase: A phrase\
  \ based on a misspelling of \"It's a trap\" a phrase and meme said by Ackbar in\
  \ Star Wars Episode VI. It is popularly used sarcastically on message boards and\
  \ chan sites. /b/tard #1: It's a trap! /b/tard #2: No! It's a tarp! Star Wars: The\
  \ Force Unleashed In the Nintendo Wii version of LucasArts' action-adventure video\
  \ game Star Wars: The Force Unleashed, released on September 16th, 2008, Admiral\
  \ Ackbar can be played as a hidden character if the player enters the cheat code\
  \ \"ITSATWAP.\" \"It's a TARP!\" \"It's a Tarp!\" is an intentional misspelling\
  \ that spawned one of the more frequently posted derivatives. According to Google\
  \ Trends, search queries for \"it's a tarp\" picked up in April 2008. Several months\
  \ later, the Obama administration's introduction of the \"Troubled Asset Relief\
  \ Program,\" shortened as TARP, inspired a batch of additional derivatives.[3][4]\
  \ On Comedy Central On February 11th, 2010, footage of Admiral Ackbar reciting the\
  \ line was featured in two separate segments on Comedy Central's The Daily Show\
  \ and The Colbert Report, wherein the soundbite is intercut with news reel clips\
  \ of Republican leaders describing an invitation to President Barack Obama's health\
  \ care summit as a \"trap.\" On Family Guy On December 21st, 2010, American animated\
  \ TV series Family Guy released a direct-to-video special episode titled \"It's\
  \ a Trap,\" which retells the story of Star Wars: Return of the Jedi, as the final\
  \ chapter of the show's Star Wars parody trilogy, with the other two being \"Laugh\
  \ It Up\" and \"Fuzzball.\" On May 22nd, 2011, Fox aired the hour-long special as\
  \ the double-episode finale of Family Guy's ninth season.[13] Search Interest External\
  \ References [1] TVwiki \u2013 It's a trap! [2] Urban Dictionary \u2013 It's a tarp!\
  \ / 5/20/2009 [3] LOLfed \u2013 It's a TARP [4] Memebase \u2013 Admiral Ackbar [5]\
  \ YTMND \u2013 Search Results for 'It's a Trap' [6] YTMND \u2013 It's a trap [7]\
  \ YTMND \u2013 It's a trap it's a trap it's a trap it's a trap it's a trap it's\
  \ a trap [8] YTMND \u2013 It's a trap rap [9] Wikipedia \u2013 \"It's a Trap!\"\
  ! [10] Wikipedia \u2013 Admiral Ackbar [11] FARK \u2013 Photoshop Phriday: Goons\
  \ show off their PS chops by making everything Batman themed [12] StraightDope Forum\
  \ \u2013 'It's a Trap' [13] Yahoo Movies \u2013 The Enduring Cult of Admiral Ackbar,\
  \ 'Return of the Jedi's' Rebel Hero [14] Hollywood Reporter \u2013 Erik Bauersfeld,\
  \ Admiral Ackbar Voice Actor in 'Star Wars' Films, Dies at 93 [15] YouTube \u2013\
  \ Search Results for 'It's a Trap' Related Entries 64 total Luke, I am Your Father\
  \ Glup Shitto Red Leader Standing By Darth Vader's \"I Find Your Lack of Faith Disturbing\"\
  \ Dancing Stormtrooper Prequel Memes It's an Older Meme, But It Checks Out Come\
  \ To The Dark Side These Are Not the Droids You Are Looking For I Am Altering The\
  \ Deal Star Wars: The Last Jedi May The Force Be With You / May the 4th Be With\
  \ You View All Related Entries Sub-entries 1 total Trap Recent Videos 11 total [18+]\
  \ \u0E23\u0E35\u0E27\u0E34\u0E27\u0E2D\u0E36\u0E4B\u0E21...\u0E14\u0E39\u0E08\u0E1A\
  \ 2 \u0E19\u0E32\u0E17\u0E35... It's A Trap! Uploaded by RChamy the Senator Admiral\
  \ Ackbar's Snackbar (Ac... It's A Trap! Uploaded by goldspectre It's A Trap Coffin\
  \ It's A Trap! Uploaded by BattlefieldJoe97 Robot Chicken: Admiral Ackbar... It's\
  \ A Trap! Uploaded by RandomMan Sheldon Cooper: It's a Trap It's A Trap! Uploaded\
  \ by User Name Star Wars Admiral Ackbar Sing... It's A Trap! Uploaded by ri Robot\
  \ Chicken: Ackbar on Pyramid It's A Trap! Uploaded by Brucker Rhian Touches Herself\
  \ HD It's A Trap! Uploaded by RubberMaddox + Add a Video View All Videos Recent\
  \ Images 125 total It's A Trap! Uploaded by Dry Ice It's A Trap! Uploaded by Twist\
  \ It's A Trap! Uploaded by Bridget It's A Trap! Uploaded by OurDeerLeader It's A\
  \ Trap! Uploaded by Cold Hard Crash It's A Trap! Uploaded by Zcure1 It's A Trap!\
  \ Uploaded by Platus It's A Trap! Uploaded by Hypercat-Z It's A Trap! Uploaded by\
  \ EventualZen It's A Trap! Uploaded by Particle Mare It's A Trap! Uploaded by Tomberry\
  \ It's A Trap! Uploaded by Sir Soundwave + Add an Image View All Images Sign up\
  \ for our Newsletter Top Comments Delete Sensitive TheKragen Apr 04, 2016 at 08:41PM\
  \ EDT Erik Bauersfeld, the original voice actor of Admiral Ackbar and Bib Fortuna\
  \ (and responsible for this meme) is dead :( (April 4, 2016) +37 Reply Delete Sensitive\
  \ Official PSASD Apr 05, 2016 at 04:08AM EDT Goodnight Sweet Prince :.( +20 Reply\
  \ + Add a Comment Comments (64) Display Comments Add a Comment Top Entries This\
  \ Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare CEO\
  \ Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (10) Kenneth\
  \ Chris Menning Digital Archaeologist & Archivist & Pundit & Early Adopter (#8)\
  \ Tomberry Database Moderator & French Specialist & Pony Hater Don Administrator\
  \ & Meme Daddy Brad Digital Archaeologist & Treasurer & Pundit & Gallery Housekeeper\
  \ Z. Database Moderator & Rage Comicologist SabrinaTibbetts Memepuff Kevinvq2 Sr.\
  \ Researcher & Scrapbooker & Media Chauffeur Y F Digital Archaeologist & Treasurer\
  \ & Media Maid Zach Memenator \u25BC + Request Editorship View All Editors Today's\
  \ Top Image Galleries Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen\
  \ Green) Team Fortress 2 The Amazing Digital Circus About Our Story Site Rules Policies\
  \ and Guidelines Credits Contact Meme DB Memes Episodes News Staff Contact Extras!\
  \ Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/its-a-trap
template_id: ackbar
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
