example:
- oh, i'm sorry
- i thought this was america
keywords:
- null
name: Oh, I'm Sorry, I Thought This Was America
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Oh, I'm Sorry, I Thought This Was America | Know Your Meme Hey!\
  \ You must login or signup first! Already a memeber? Login Now! Don't have an account?\
  \ Sign up Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos\
  \ Submit \u2192 Images Trending Most Commented Most Favorited High Score Low Score\
  \ Most Viewed All Templates Upload an Image Articles News Explainers Collections\
  \ Interviews Meme Insider Magazine More Discord Newsletter Episodes Forums Meme\
  \ Store Login Abstract user icon Memes Categories Trending News Images Trending\
  \ Images Videos Trending Videos Editorials Meme Insider Magazine Newsletter Policies\
  \ and Guidelines Meme Store Old site Login Know Your Meme is the property of Literally\
  \ Media \xA92024 Literally Media. All Rights Reserved. This image Of Woman Confidently\
  \ Strolling Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years\
  \ Ago, This Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The\
  \ Anarchy Chess Memes Turns Two Years Old Today Phrase 'The Fridge Protects The\
  \ Snacks' A Growing Favorite Among Pickup Artist Influencers Jamie G, The Bosh British\
  \ Charva, Has Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also\
  \ Trending: Honey Extension Influencer Scam Renegade Raider Copypasta Assassination\
  \ of UnitedHealthcare CEO Oh, I'm Sorry, I Thought This Was America Added 10 years\
  \ ago / Updated 4 years ago Confirmed 119,659 Part of a series on South Park. [View\
  \ Related Entries] View All 19 Images Navigation About \u2022 Origin \u2022 Spread\
  \ \u2022 Notable Examples \u2022 Search Interest \u2022 External References \u2022\
  \ Recent Images About \"Oh, I\u2019m Sorry, I Thought This Was America\" is a memorable\
  \ quote uttered by the character Randy Marsh from the animated television series\
  \ South Park. In the context of online discussions, the original quote and its snowclone\
  \ variations can be used as a blanket excuse for one's own action or statement in\
  \ response to a backlash or criticism. Origin On April 6th, 2005, an episode of\
  \ South Park titled \"The Losing Edge\" aired on Comedy Central. The episode features\
  \ the South Park kids at a baseball game. During the game, Randy Marsh, father of\
  \ Stan Marsh, is cheering for the team and trash talking the opposing team. After\
  \ another parent threatens to beat Randy up, Randy removes his shirt and a fight\
  \ begins. Every time the South Park team wins, Randy gets arrested by the cops and\
  \ complains, \"Oh, I thought this was America.\" Batdad: Now for the finishing move!\
  \ You're about to be \"Batdad-ed\"! Randy: Hey, Batdad, I didn't hear no bell. Batdad:\
  \ Batdad knows no fear! Batdad knows no pain! Randy: For what? Arresting me for\
  \ what? I'm not allowed to stand up for myself? I thought this was America! Huh?\
  \ Isn't this America? I'm sorry, I thought this was America. Randy: Denver sucks\
  \ ass. Spread On April 16th, 2005, a site titled \"Oh I'm Sorry I Thought This Was\
  \ America\" was created on YTMND, [2] featuring a tiled background image of Marsh\
  \ being arrested and a looped audio clip of him repeating the phrase. On March 17th,\
  \ 2007, user rawsonofchoice posed a question on on Yahoo Answers[3] about others'\
  \ favorite South Park episodes and titled the thread \"I'm sorry, i thought this\
  \ was america!!!?\" On September 17th, 2010, the Tumblr blog imsorryithoughtthiswasamerica[4]\
  \ was created. The satirical blog features posts that begin with the phrase and\
  \ go on to describe American \"outrages,\" such as every American not having an\
  \ iPhone and the price of luxury mattresses. On July 21st, 2011, an entry for \"\
  Oh Im Sorry I Thought This Was America\" was added to Urban Dictionary[1] by user\
  \ WavedBrute who defined the phrase as: \"Something yelled by white trash while\
  \ being arrested while wearing nothing but underpants.\" On October 19th, 2011,\
  \ Someecards[5] added a card that featured Thomas Jefferson appearing to address\
  \ a group of fellow founding fathers with the phrase \"Oh, I'm sorry. I thought\
  \ this was America. Notable Examples Search Interest External References [1] Urban\
  \ Dictionary \u2013 Oh I'm Sorry I Thought This Was America [2] YTMND \u2013 I Thought\
  \ This Was America [3] Yahoo Answers \u2013 I'm sorry, i thought this was america!!!?\
  \ [4] Tumblr \u2013 imsorryithoughtthiswasamerica [5] Some E-Cards -imsorryithoughtthiswasamerica\
  \ cartoon meme series quote phrase comedy south park show character episode comedy\
  \ central randy marsh oh i'm sorry i thought this was america best father randy\
  \ marsh arrested the losing edge Share Pin Related Entries 22 total Tree Fiddy ????\
  \ PROFIT!!!! Super Cool Ski Instructor And It's Gone View All Related Entries Recent\
  \ Images 19 total View All Images Recent Videos 0 total There are no recent videos.\
  \ Sign up for our Newsletter Load 35 Comments Comments 35 total 22 Oh, I'm Sorry,\
  \ I Thought This Was America 119,659 0 19 35 Part of a series on South Park. [View\
  \ Related Entries] Updated Aug 30, 2020 at 07:54AM EDT by shevyrolet. Added Mar\
  \ 13, 2014 at 10:07PM EDT by Gabenus Trollucus. Like us on Facebook! Like 1.8M Share\
  \ Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the video\
  \ gallery, or 'r' to view a random entry. Meme Status Confirmed Year 2005 Origin\
  \ South Park Tags cartoon, meme, series, quote, phrase, comedy, south park, show,\
  \ character, episode, comedy central, randy marsh, oh i'm sorry i thought this was\
  \ america, best father, randy marsh arrested, the losing edge Additional References\
  \ Meme Generator Urban Dictionary About \"Oh, I\u2019m Sorry, I Thought This Was\
  \ America\" is a memorable quote uttered by the character Randy Marsh from the animated\
  \ television series South Park. In the context of online discussions, the original\
  \ quote and its snowclone variations can be used as a blanket excuse for one's own\
  \ action or statement in response to a backlash or criticism. Origin On April 6th,\
  \ 2005, an episode of South Park titled \"The Losing Edge\" aired on Comedy Central.\
  \ The episode features the South Park kids at a baseball game. During the game,\
  \ Randy Marsh, father of Stan Marsh, is cheering for the team and trash talking\
  \ the opposing team. After another parent threatens to beat Randy up, Randy removes\
  \ his shirt and a fight begins. Every time the South Park team wins, Randy gets\
  \ arrested by the cops and complains, \"Oh, I thought this was America.\" Batdad:\
  \ Now for the finishing move! You're about to be \"Batdad-ed\"! Randy: Hey, Batdad,\
  \ I didn't hear no bell. Batdad: Batdad knows no fear! Batdad knows no pain! Randy:\
  \ For what? Arresting me for what? I'm not allowed to stand up for myself? I thought\
  \ this was America! Huh? Isn't this America? I'm sorry, I thought this was America.\
  \ Randy: Denver sucks ass. Spread On April 16th, 2005, a site titled \"Oh I'm Sorry\
  \ I Thought This Was America\" was created on YTMND, [2] featuring a tiled background\
  \ image of Marsh being arrested and a looped audio clip of him repeating the phrase.\
  \ On March 17th, 2007, user rawsonofchoice posed a question on on Yahoo Answers[3]\
  \ about others' favorite South Park episodes and titled the thread \"I'm sorry,\
  \ i thought this was america!!!?\" On September 17th, 2010, the Tumblr blog imsorryithoughtthiswasamerica[4]\
  \ was created. The satirical blog features posts that begin with the phrase and\
  \ go on to describe American \"outrages,\" such as every American not having an\
  \ iPhone and the price of luxury mattresses. On July 21st, 2011, an entry for \"\
  Oh Im Sorry I Thought This Was America\" was added to Urban Dictionary[1] by user\
  \ WavedBrute who defined the phrase as: \"Something yelled by white trash while\
  \ being arrested while wearing nothing but underpants.\" On October 19th, 2011,\
  \ Someecards[5] added a card that featured Thomas Jefferson appearing to address\
  \ a group of fellow founding fathers with the phrase \"Oh, I'm sorry. I thought\
  \ this was America. Notable Examples Search Interest External References [1] Urban\
  \ Dictionary \u2013 Oh I'm Sorry I Thought This Was America [2] YTMND \u2013 I Thought\
  \ This Was America [3] Yahoo Answers \u2013 I'm sorry, i thought this was america!!!?\
  \ [4] Tumblr \u2013 imsorryithoughtthiswasamerica [5] Some E-Cards -imsorryithoughtthiswasamerica\
  \ Related Entries 22 total Tree Fiddy ???? PROFIT!!!! Super Cool Ski Instructor\
  \ And It's Gone They Took Our Jobs! Captain Hindsight Member Berries Everybody Draw\
  \ Mohammed Day PC Bro I Didn't Hear No Bell South Park Transgender Athletes Episode\
  \ Controversy My Name Is Craig Tucker Copypasta View All Related Entries Recent\
  \ Videos There are no videos currently available. + Add a Video Recent Images 19\
  \ total Oh, I'm Sorry, I Thought This... Uploaded by Y F Oh, I'm Sorry, I Thought\
  \ This... Uploaded by Nedhitis Oh, I'm Sorry, I Thought This... Uploaded by Molly\
  \ Horan Oh, I'm Sorry, I Thought This... Uploaded by Molly Horan Oh, I'm Sorry,\
  \ I Thought This... Uploaded by Molly Horan Oh, I'm Sorry, I Thought This... Uploaded\
  \ by Molly Horan Oh, I'm Sorry, I Thought This... Uploaded by Molly Horan Oh, I'm\
  \ Sorry, I Thought This... Uploaded by Molly Horan Oh, I'm Sorry, I Thought This...\
  \ Uploaded by Gabenus Trollucus Oh, I'm Sorry, I Thought This... Uploaded by Gabenus\
  \ Trollucus Oh, I'm Sorry, I Thought This... Uploaded by Gabenus Trollucus Oh, I'm\
  \ Sorry, I Thought This... Uploaded by Gabenus Trollucus + Add an Image View All\
  \ Images Sign up for our Newsletter Top Comments Delete Sensitive SaturnSL1 Mar\
  \ 14, 2014 at 12:25AM EDT You thought this was X? +58 Reply Delete Sensitive WezliGiantsbane333\
  \ Mar 18, 2014 at 05:52PM EDT What, I can't worship Talos? Oh, I'm sorry, I thought\
  \ this was Skyrim. +32 Reply + Add a Comment Comments (35) Display Comments Add\
  \ a Comment Top Entries This Month Meme Saika Kawakita Smile GIF Event Assassination\
  \ of UnitedHealthcare CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki\
  \ Sisters Culture Pornography Site Whisper View More Suggest a Change Edit History\
  \ Entry Editors (5) Gabenus Trollucus Deactivated Molly Horan Tumblr Historian Brad\
  \ Digital Archaeologist & Treasurer & Pundit & Gallery Housekeeper Y F Digital Archaeologist\
  \ & Treasurer & Media Maid shevyrolet Digital Archaeologist & Treasurer & Media\
  \ Bus Boy \u25BC + Request Editorship View All Editors Today's Top Image Galleries\
  \ Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress\
  \ 2 The Amazing Digital Circus About Our Story Site Rules Policies and Guidelines\
  \ Credits Contact Meme DB Memes Episodes News Staff Contact Extras! Style Guide\
  \ RSS Feeds"
source: http://knowyourmeme.com/memes/oh-im-sorry-i-thought-this-was-america
template_id: imsorry
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
