name: Oh, I'm Sorry, I Thought This Was America
source: http://knowyourmeme.com/memes/oh-im-sorry-i-thought-this-was-america
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- oh, i'm sorry
- i thought this was america
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About "Oh, I’m Sorry, I Thought This Was America" is a memorable
  quote uttered by the character Randy Marsh from the animated television series South
  Park. In the context of online discussions, the original quote and its snowclone
  variations can be used as a blanket excuse for one''s own action or statement in
  response to a backlash or criticism. Origin On April 6th, 2005, an episode of South
  Park titled "The Losing Edge" aired on Comedy Central. The episode features the
  South Park kids at a baseball game. During the game, Randy Marsh, father of Stan
  Marsh, is cheering for the team and trash talking the opposing team. After another
  parent threatens to beat Randy up, Randy removes his shirt and a fight begins. Every
  time the South Park team wins, Randy gets arrested by the cops and complains, "Oh,
  I thought this was America." Batdad: Now for the finishing move! You''re about to
  be "Batdad-ed"! Randy: Hey, Batdad, I didn''t hear no bell. Batdad: Batdad knows
  no fear! Batdad knows no pain! Randy: For what? Arresting me for what? I''m not
  allowed to stand up for myself? I thought this was America! Huh? Isn''t this America?
  I''m sorry, I thought this was America. Randy: Denver sucks ass. Spread On April
  16th, 2005, a site titled "Oh I''m Sorry I Thought This Was America" was created
  on YTMND, [2] featuring a tiled background image of Marsh being arrested and a looped
  audio clip of him repeating the phrase. On March 17th, 2007, user rawsonofchoice
  posed a question on on Yahoo Answers[3] about others'' favorite South Park episodes
  and titled the thread "I''m sorry, i thought this was america!!!?" On September
  17th, 2010, the Tumblr blog imsorryithoughtthiswasamerica[4] was created. The satirical
  blog features posts that begin with the phrase and go on to describe American "outrages,"
  such as every American not having an iPhone and the price of luxury mattresses.
  On July 21st, 2011, an entry for "Oh Im Sorry I Thought This Was America" was added
  to Urban Dictionary[1] by user WavedBrute who defined the phrase as: "Something
  yelled by white trash while being arrested while wearing nothing but underpants."
  On October 19th, 2011, Someecards[5] added a card that featured Thomas Jefferson
  appearing to address a group of fellow founding fathers with the phrase "Oh, I''m
  sorry. I thought this was America. Notable Examples Search Interest External References
  [1] Urban Dictionary – Oh I''m Sorry I Thought This Was America [2] YTMND – I Thought
  This Was America [3] Yahoo Answers – I''m sorry, i thought this was america!!!?
  [4] Tumblr – imsorryithoughtthiswasamerica [5] Some E-Cards -imsorryithoughtthiswasamerica'
aside_content: MemeStatusConfirmedYear2005OriginSouth ParkTagscartoon,meme,series,quote,phrase,comedy,south
  park,show,character,episode,comedy central,randy marsh,oh i'm sorry i thought this
  was america,best father,randy marsh arrested,the losing edgeAdditional ReferencesMeme
  GeneratorUrban Dictionary
added_at: '2014-03-13T22:07:10-04:00'
