name: Schrute Facts
source: http://knowyourmeme.com/memes/schrute-facts
keywords:
- The Office
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- love is all you need?
- false. you need water and rations.
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Schrute Facts is an image macro series inspired by Dwight
  Schrute, a character from the American version of the TV sitcom The Office. The
  overlaid text typically begins with an idiom or common belief, followed by a refutation
  of the aforementioned idiom based on a rationalist interpretation similar to buzzkill
  humor. Origin Since the show''s U.S. debut in March 2005, Dwight Schrute[12] (played
  by actor Rainn Wilson[7]) has become a breakout character for being a know-it-all
  with poor social skills and a worldview that can be best characterized as realist
  and survivalist. In the episodes, Schrute often corrects others'' idiomatic statements
  by deeming them false and rebutting with real-life facts (shown below, left). Though
  he does not always say the word “false,” Schrute''s distinct interpretation of English
  colloquialisms has been noted since the pilot season[18] and parodied by character
  Jim Halpert in a cold open of an episode during the show’s third season (shown below,
  right). While image macros using Dwight Schrute''s likeness paired with actual quotes
  from the show appeared as early as February 2011 on FunnyJunk[5], the first image
  macro using the "Fact" format was created via Quickmeme[1] and uploaded to Reddit[2]
  on April 15th, 2011, where it received 1334 up votes. The caption featured Schrute''s
  rebuttal to the lyrics of The Beatles'' 1967 song “All You Need is Love” by asserting
  that a person only needs water and food to survive. Spread In the following days,
  several other instances of Schrute Facts appeared in the comments of the initial
  Reddit post. A single topic Tumblr[8] was created on April 19th, but has evolved
  into a personal blog as of September 2012. The blog Runt of the Web[4] posted a
  collection of the image macro series in a post titled “Dwight Schrute Knows Best”
  on July 19th. Over the next two months, additional images were shared on eBaum’s
  World[11], Uproxx[9], Buzzfeed.[14] In January 2012, a Facebook fan page[20] was
  started for Schrute Facts, but only gained 29 likes by September. Meanwhile, a Twitter
  feed[21] started in February has gained more than 8000 followers. As of February
  2012, there have been more than 300 Schrute Facts submitted to Reddit[19], more
  than 14,000 submissions to the the Quickmeme[3] page and approximately 280 submissions
  to the Memegenerator[10] page. There is also a Tumblr tag[13] for "Schrute Facts"
  under which several instances of the series can be found. Notable Examples Rainn
  Wilson''s Self-Tribute In September 2012, actor Rainn Wilson appeared in a video
  for Malarious[22], a series of comedic shorts created by College Humor to raise
  money for the charity Malaria No More.[23] In the video, Wilson read a selection
  of inspirational quotes aloud before discrediting them in the manner of the image
  macro series. The video was shared on a variety of celebrity gossip and tech blogs
  including Mashable[24], Laughing Squid[25], Yahoo! News[26], Entertainment Weekly
  PopWatch[27] and Entertainment on TODAY.[28] Search Interest Search queries for
  "schrute facts" began prior to the creation of the image macro series in February
  2010, which may have been sparked by a trivia game about Dwight Schrute on the website
  Sporcle.[6] Both "schrute facts" and "schrute meme" began rising in April 2011,
  the same month that the first image macro was published. External References [1]
  Quickmeme Via Way Back Machine- first Schrute macro [2] Reddit – Some Schrute Love
  [3] Quickmeme via Way Back Machine- Schrute [4] Runt of the Web – Dwight Schrute
  Knows Best [5] FunnyJunk – Dwight Schrute Meme [6] Sporcle – Can you name the facts
  about Dwight Schrute? [7] Wikipedia – Rainn Wilson [8] Tumblr – Schrute Facts [9]
  Uproxx – Meme Watch: Schrute Facts Debunk Pointless Expressions [10] Memegenerator
  – Dwight Schrute [11] eBaum''s World – The Dwight Schrute Meme Gallery [12] Wikipedia
  – Dwight Schrute [13] Tumblr – Posts tagged "Schrute Facts" [14] Buzzfeed – The
  Best Of The ‘Schrute Facts’ Meme [15] Paste – NBC Preps Dwight Schrute Spinoff [16]
  TVSomniac – The Office Spin Off: Rainn Wilson As Dwight Schrute Will Get His Very
  Own Show [17] MTV – Dwight Schrute Spin-Off From ''The Office'' In Works [18] TV
  Fanatic – Dwight Schrute Quotes [19] Reddit – Search results for "Schrute" in /r/AdviceAnimals
  [20] Facebook – Schrute Facts [21] Twitter – @SchruteFacts [22] College Humor via
  Wayback Machine – Malarious [23] Malaria No More – Home [24] Mashable – Rainn Wilson
  Proves Your Facebook Quotes Are False [VIDEO] [25] Laughing Squid – Your Facebook
  is False With The Office''s Rainn Wilson [26] Yahoo! News – Rainn Wilson Proves
  Your Facebook Quotes Are False [VIDEO] [27] EW PopWatch – ''False!'' Rainn Wilson
  explains why your inspirational quotes suck -- VIDEO [28] Entertainment on TODAY
  – Rainn Wilson deflates inspirational Facebook statuses in ''Malarious'' video'
aside_content: MemeStatusConfirmedYear2011OriginTumblrTagsschrute,tumblr,image macro,sitcom
added_at: '2011-07-27T17:08:08-04:00'
