example:
- love is all you need?
- false. you need water and rations.
keywords:
- The Office
name: Schrute Facts
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Schrute Facts | Know Your Meme Hauu! You must login or signup first!\
  \ Already a memeber? Login Now! Don't have an account? Sign up Now! Meme Encyclopedia\
  \ All Cultures Events People Sites Subcultures Videos Submit \u2192 Images Trending\
  \ Most Commented Most Favorited High Score Low Score Most Viewed All Templates Upload\
  \ an Image Articles News Explainers Collections Interviews Meme Insider Magazine\
  \ More Discord Newsletter Episodes Forums Meme Store Login Abstract user icon Memes\
  \ Categories Trending News Images Trending Images Videos Trending Videos Editorials\
  \ Meme Insider Magazine Newsletter Policies and Guidelines Meme Store Old site Login\
  \ Know Your Meme is the property of Literally Media \xA92024 Literally Media. All\
  \ Rights Reserved. This image Of Woman Confidently Strolling Through A Glass Panel\
  \ Has Been A Redraw Format Since 2021 Three Years Ago, This Boar's Head 'Exploded'\
  \ Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess Memes Turns Two Years\
  \ Old Today Phrase 'The Fridge Protects The Snacks' A Growing Favorite Among Pickup\
  \ Artist Influencers Jamie G, The Bosh British Charva, Has Taken Over TikTok With\
  \ His Signature 'Oh Cherie Amour' Sound Also Trending: Honey Extension Influencer\
  \ Scam Renegade Raider Copypasta Assassination of UnitedHealthcare CEO Schrute Facts\
  \ Added 13 years ago / Updated 8 days ago Confirmed 456,720 Part of a series on\
  \ The Office. [View Related Entries] View All 66 Images Navigation About \u2022\
  \ Origin \u2022 Spread \u2022 Notable Examples \u2022 External References \u2022\
  \ Recent Images \u2022 Recent Videos About Schrute Facts is an image macro series\
  \ inspired by Dwight Schrute, a character from the American version of the TV sitcom\
  \ The Office. The overlaid text typically begins with an idiom or common belief,\
  \ followed by a refutation of the aforementioned idiom based on a rationalist interpretation\
  \ similar to buzzkill humor. Origin Since the show's U.S. debut in March 2005, Dwight\
  \ Schrute[12] (played by actor Rainn Wilson[7]) has become a breakout character\
  \ for being a know-it-all with poor social skills and a worldview that can be best\
  \ characterized as realist and survivalist. In the episodes, Schrute often corrects\
  \ others' idiomatic statements by deeming them false and rebutting with real-life\
  \ facts (shown below, left). Though he does not always say the word \u201Cfalse,\u201D\
  \ Schrute's distinct interpretation of English colloquialisms has been noted since\
  \ the pilot season[18] and parodied by character Jim Halpert in a cold open of an\
  \ episode during the show\u2019s third season (shown below, right). While image\
  \ macros using Dwight Schrute's likeness paired with actual quotes from the show\
  \ appeared as early as February 2011 on FunnyJunk[5], the first image macro using\
  \ the \"Fact\" format was created via Quickmeme[1] and uploaded to Reddit[2] on\
  \ April 15th, 2011, where it received 1334 up votes. The caption featured Schrute's\
  \ rebuttal to the lyrics of The Beatles' 1967 song \u201CAll You Need is Love\u201D\
  \ by asserting that a person only needs water and food to survive. Spread In the\
  \ following days, several other instances of Schrute Facts appeared in the comments\
  \ of the initial Reddit post. A single topic Tumblr[8] was created on April 19th,\
  \ but has evolved into a personal blog as of September 2012. The blog Runt of the\
  \ Web[4] posted a collection of the image macro series in a post titled \u201CDwight\
  \ Schrute Knows Best\u201D on July 19th. Over the next two months, additional images\
  \ were shared on eBaum\u2019s World[11], Uproxx[9], Buzzfeed.[14] In January 2012,\
  \ a Facebook fan page[20] was started for Schrute Facts, but only gained 29 likes\
  \ by September. Meanwhile, a Twitter feed[21] started in February has gained more\
  \ than 8000 followers. As of February 2012, there have been more than 300 Schrute\
  \ Facts submitted to Reddit[19], more than 14,000 submissions to the the Quickmeme[3]\
  \ page and approximately 280 submissions to the Memegenerator[10] page. There is\
  \ also a Tumblr tag[13] for \"Schrute Facts\" under which several instances of the\
  \ series can be found. Notable Examples Rainn Wilson's Self-Tribute In September\
  \ 2012, actor Rainn Wilson appeared in a video for Malarious[22], a series of comedic\
  \ shorts created by College Humor to raise money for the charity Malaria No More.[23]\
  \ In the video, Wilson read a selection of inspirational quotes aloud before discrediting\
  \ them in the manner of the image macro series. The video was shared on a variety\
  \ of celebrity gossip and tech blogs including Mashable[24], Laughing Squid[25],\
  \ Yahoo! News[26], Entertainment Weekly PopWatch[27] and Entertainment on TODAY.[28]\
  \ Search Interest Search queries for \"schrute facts\" began prior to the creation\
  \ of the image macro series in February 2010, which may have been sparked by a trivia\
  \ game about Dwight Schrute on the website Sporcle.[6] Both \"schrute facts\" and\
  \ \"schrute meme\" began rising in April 2011, the same month that the first image\
  \ macro was published. External References [1] Quickmeme Via Way Back Machine- first\
  \ Schrute macro [2] Reddit \u2013 Some Schrute Love [3] Quickmeme via Way Back Machine-\
  \ Schrute [4] Runt of the Web \u2013 Dwight Schrute Knows Best [5] FunnyJunk \u2013\
  \ Dwight Schrute Meme [6] Sporcle \u2013 Can you name the facts about Dwight Schrute?\
  \ [7] Wikipedia \u2013 Rainn Wilson [8] Tumblr \u2013 Schrute Facts [9] Uproxx \u2013\
  \ Meme Watch: Schrute Facts Debunk Pointless Expressions [10] Memegenerator \u2013\
  \ Dwight Schrute [11] eBaum's World \u2013 The Dwight Schrute Meme Gallery [12]\
  \ Wikipedia \u2013 Dwight Schrute [13] Tumblr \u2013 Posts tagged \"Schrute Facts\"\
  \ [14] Buzzfeed \u2013 The Best Of The \u2018Schrute Facts\u2019 Meme [15] Paste\
  \ \u2013 NBC Preps Dwight Schrute Spinoff [16] TVSomniac \u2013 The Office Spin\
  \ Off: Rainn Wilson As Dwight Schrute Will Get His Very Own Show [17] MTV \u2013\
  \ Dwight Schrute Spin-Off From 'The Office' In Works [18] TV Fanatic \u2013 Dwight\
  \ Schrute Quotes [19] Reddit \u2013 Search results for \"Schrute\" in /r/AdviceAnimals\
  \ [20] Facebook \u2013 Schrute Facts [21] Twitter \u2013 @SchruteFacts [22] College\
  \ Humor via Wayback Machine \u2013 Malarious [23] Malaria No More \u2013 Home [24]\
  \ Mashable \u2013 Rainn Wilson Proves Your Facebook Quotes Are False [VIDEO] [25]\
  \ Laughing Squid \u2013 Your Facebook is False With The Office's Rainn Wilson [26]\
  \ Yahoo! News \u2013 Rainn Wilson Proves Your Facebook Quotes Are False [VIDEO]\
  \ [27] EW PopWatch \u2013 'False!' Rainn Wilson explains why your inspirational\
  \ quotes suck -- VIDEO [28] Entertainment on TODAY \u2013 Rainn Wilson deflates\
  \ inspirational Facebook statuses in 'Malarious' video schrute tumblr image macro\
  \ sitcom Share Pin Related Entries 21 total They're The Same Picture No God, Please\
  \ No! Young Michael Scott Shaking E... Jim Halpert Smiling Through B... View All\
  \ Related Entries Recent Images 66 total View All Images Recent Videos 2 total View\
  \ All Videos Sign up for our Newsletter Load 44 Comments Comments 44 total 89 Schrute\
  \ Facts 456,720 2 66 44 Part of a series on The Office. [View Related Entries] Updated\
  \ Dec 15, 2024 at 06:41PM EST by LiterallyAustin. Added Jul 27, 2011 at 05:08PM\
  \ EDT by snutch2thenutch. Like us on Facebook! Like 1.8M Share Save Tweet PROTIP:\
  \ Press 'i' to view the image gallery, 'v' to view the video gallery, or 'r' to\
  \ view a random entry. Meme Status Confirmed Year 2011 Origin Tumblr Tags schrute,\
  \ tumblr, image macro, sitcom About Schrute Facts is an image macro series inspired\
  \ by Dwight Schrute, a character from the American version of the TV sitcom The\
  \ Office. The overlaid text typically begins with an idiom or common belief, followed\
  \ by a refutation of the aforementioned idiom based on a rationalist interpretation\
  \ similar to buzzkill humor. Origin Since the show's U.S. debut in March 2005, Dwight\
  \ Schrute[12] (played by actor Rainn Wilson[7]) has become a breakout character\
  \ for being a know-it-all with poor social skills and a worldview that can be best\
  \ characterized as realist and survivalist. In the episodes, Schrute often corrects\
  \ others' idiomatic statements by deeming them false and rebutting with real-life\
  \ facts (shown below, left). Though he does not always say the word \u201Cfalse,\u201D\
  \ Schrute's distinct interpretation of English colloquialisms has been noted since\
  \ the pilot season[18] and parodied by character Jim Halpert in a cold open of an\
  \ episode during the show\u2019s third season (shown below, right). While image\
  \ macros using Dwight Schrute's likeness paired with actual quotes from the show\
  \ appeared as early as February 2011 on FunnyJunk[5], the first image macro using\
  \ the \"Fact\" format was created via Quickmeme[1] and uploaded to Reddit[2] on\
  \ April 15th, 2011, where it received 1334 up votes. The caption featured Schrute's\
  \ rebuttal to the lyrics of The Beatles' 1967 song \u201CAll You Need is Love\u201D\
  \ by asserting that a person only needs water and food to survive. Spread In the\
  \ following days, several other instances of Schrute Facts appeared in the comments\
  \ of the initial Reddit post. A single topic Tumblr[8] was created on April 19th,\
  \ but has evolved into a personal blog as of September 2012. The blog Runt of the\
  \ Web[4] posted a collection of the image macro series in a post titled \u201CDwight\
  \ Schrute Knows Best\u201D on July 19th. Over the next two months, additional images\
  \ were shared on eBaum\u2019s World[11], Uproxx[9], Buzzfeed.[14] In January 2012,\
  \ a Facebook fan page[20] was started for Schrute Facts, but only gained 29 likes\
  \ by September. Meanwhile, a Twitter feed[21] started in February has gained more\
  \ than 8000 followers. As of February 2012, there have been more than 300 Schrute\
  \ Facts submitted to Reddit[19], more than 14,000 submissions to the the Quickmeme[3]\
  \ page and approximately 280 submissions to the Memegenerator[10] page. There is\
  \ also a Tumblr tag[13] for \"Schrute Facts\" under which several instances of the\
  \ series can be found. Notable Examples Rainn Wilson's Self-Tribute In September\
  \ 2012, actor Rainn Wilson appeared in a video for Malarious[22], a series of comedic\
  \ shorts created by College Humor to raise money for the charity Malaria No More.[23]\
  \ In the video, Wilson read a selection of inspirational quotes aloud before discrediting\
  \ them in the manner of the image macro series. The video was shared on a variety\
  \ of celebrity gossip and tech blogs including Mashable[24], Laughing Squid[25],\
  \ Yahoo! News[26], Entertainment Weekly PopWatch[27] and Entertainment on TODAY.[28]\
  \ Search Interest Search queries for \"schrute facts\" began prior to the creation\
  \ of the image macro series in February 2010, which may have been sparked by a trivia\
  \ game about Dwight Schrute on the website Sporcle.[6] Both \"schrute facts\" and\
  \ \"schrute meme\" began rising in April 2011, the same month that the first image\
  \ macro was published. External References [1] Quickmeme Via Way Back Machine- first\
  \ Schrute macro [2] Reddit \u2013 Some Schrute Love [3] Quickmeme via Way Back Machine-\
  \ Schrute [4] Runt of the Web \u2013 Dwight Schrute Knows Best [5] FunnyJunk \u2013\
  \ Dwight Schrute Meme [6] Sporcle \u2013 Can you name the facts about Dwight Schrute?\
  \ [7] Wikipedia \u2013 Rainn Wilson [8] Tumblr \u2013 Schrute Facts [9] Uproxx \u2013\
  \ Meme Watch: Schrute Facts Debunk Pointless Expressions [10] Memegenerator \u2013\
  \ Dwight Schrute [11] eBaum's World \u2013 The Dwight Schrute Meme Gallery [12]\
  \ Wikipedia \u2013 Dwight Schrute [13] Tumblr \u2013 Posts tagged \"Schrute Facts\"\
  \ [14] Buzzfeed \u2013 The Best Of The \u2018Schrute Facts\u2019 Meme [15] Paste\
  \ \u2013 NBC Preps Dwight Schrute Spinoff [16] TVSomniac \u2013 The Office Spin\
  \ Off: Rainn Wilson As Dwight Schrute Will Get His Very Own Show [17] MTV \u2013\
  \ Dwight Schrute Spin-Off From 'The Office' In Works [18] TV Fanatic \u2013 Dwight\
  \ Schrute Quotes [19] Reddit \u2013 Search results for \"Schrute\" in /r/AdviceAnimals\
  \ [20] Facebook \u2013 Schrute Facts [21] Twitter \u2013 @SchruteFacts [22] College\
  \ Humor via Wayback Machine \u2013 Malarious [23] Malaria No More \u2013 Home [24]\
  \ Mashable \u2013 Rainn Wilson Proves Your Facebook Quotes Are False [VIDEO] [25]\
  \ Laughing Squid \u2013 Your Facebook is False With The Office's Rainn Wilson [26]\
  \ Yahoo! News \u2013 Rainn Wilson Proves Your Facebook Quotes Are False [VIDEO]\
  \ [27] EW PopWatch \u2013 'False!' Rainn Wilson explains why your inspirational\
  \ quotes suck -- VIDEO [28] Entertainment on TODAY \u2013 Rainn Wilson deflates\
  \ inspirational Facebook statuses in 'Malarious' video Related Entries 21 total\
  \ They're The Same Picture No God, Please No! Young Michael Scott Shaking Ed Truck's\
  \ Hand Jim Halpert Smiling Through Blinds Parkour! (The Office) Looks at the Camera\
  \ Like I'm on The Office I Am Aware of the Effect I Have on Women Jim Halpert Pointing\
  \ to Whiteboard Did I Stutter (Stanley - The Office) Phyllis and Ryan Office Christmas\
  \ Party Photo Days Since Our Last Nonsense Racist Jim Halpert View All Related Entries\
  \ Recent Videos 2 total Your Facebook is False (with ... Schrute Facts Uploaded\
  \ by yah Rule 17 according to Dwight S... Schrute Facts Uploaded by Sophie Lavender\
  \ + Add a Video Recent Images 66 total Schrute Facts Uploaded by probium Schrute\
  \ Facts Uploaded by Triplem Schrute Facts Uploaded by Fight Milk22 Schrute Facts\
  \ Uploaded by Y F Schrute Facts Uploaded by Z33k Zmorphod Schrute Facts Uploaded\
  \ by McGillis \"Makshima\" Fareed Schrute Facts Uploaded by Adam DeLand Schrute\
  \ Facts Uploaded by spongeboy1985 Schrute Facts Uploaded by redhawk23 Schrute Facts\
  \ Uploaded by Emperor Palpitoad Schrute Facts Uploaded by gaioaa Schrute Facts Uploaded\
  \ by Edward + Add an Image View All Images Sign up for our Newsletter Top Comments\
  \ Delete Sensitive Skaw Aug 03, 2011 at 04:20PM EDT +1 Deadpool False. This meme\
  \ deserves +1 Confirm, also a Pool of deads would be close due hazards +47 Reply\
  \ Delete Sensitive Machinates Silently Aug 03, 2011 at 05:22PM EDT > Ice cold water?\
  \ > False: if it was as cold as ice, it would be ice. False: water can exist as\
  \ either a solid or a liquid at its freezing point, dependent on its specfic latent\
  \ heat. +25 Reply + Add a Comment Comments (44) Display Comments Add a Comment Top\
  \ Entries This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (5) snutch2thenutch\
  \ Don Administrator & Meme Daddy amanda b. Meme Librarian Brad Digital Archaeologist\
  \ & Treasurer & Pundit & Gallery Housekeeper Y F Digital Archaeologist & Treasurer\
  \ & Media Maid \u25BC + Request Editorship View All Editors Today's Top Image Galleries\
  \ Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress\
  \ 2 The Amazing Digital Circus About Our Story Site Rules Policies and Guidelines\
  \ Credits Contact Meme DB Memes Episodes News Staff Contact Extras! Style Guide\
  \ RSS Feeds"
source: http://knowyourmeme.com/memes/schrute-facts
template_id: dwight
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
