name: An Older Code Sir, But It Checks Out
source: http://knowyourmeme.com/memes/its-an-older-meme-but-it-checks-out
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- it's an older meme sir
- but it checks out
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About "It''s an Older Meme, But it Checks Out" is an expression
  derived from a quote featured in the 1983 science fiction film Star Wars Episode
  VI: Return of the Jedi. In discussion threads and comments, the reaction image is
  typically used to validate the authenticity of an Internet meme reference that is
  outdated or culturally relevant. Origin On May 25th, 1983, the film Star Wars Episode
  VI: Return of the Jedi was released. in which a strike team led by the character
  Han Solo manages to sneak past Empire''s security under the guise of being an engineering
  crew. After Solo''s shuttle communicates with an Empire official, Admiral Piett,
  on the way to the planet Endor, the antagonist Darth Vader asks if they provided
  a "code clearance," to which Piett replies "it''s an older code, but it checks out"
  (shown below). On July 17th, 2012, Redditor iwan_w replied to a joke referencing
  the "I Herd U Like Mudkips" meme with the phrase "It''s an older meme, sir, but
  it checks out" (shown below).[1] Spread On July 28th, 2013, Imgur[2] user Valkor
  submitted a screen capture from the Star Wars scene with the caption "It''s an older
  meme, sir / but it checks out" (shown below). On June 26th, 2014, George Takei tweeted[4]
  a Star Trek-themed image macro with the description "It''s an older meme, but it
  checks out" (shown below). Within nine months, the tweet accumulated more than 1,300
  favorites and 760 retweets. On September 13th, Redditor pdmcmahon submitted an animated
  GIF of the Star Wars scene captioned with a parody dialogue between Vader and the
  Empire official to the /r/gifs[3] subreddit (shown below). Within five months, the
  post gathered upwards of 4,100 votes (94% upvoted) and 300 comments. Search Interest
  Not available. External References [1] Reddit – Perhaps he lieks mudkips [2] Imgur
  via Wayback Machine – Its an older meme sir but it checks out [3] Reddit – Now in
  gif form [4] Twitter – @GeorgeTakei'
aside_content: MemeStatusConfirmedYear2012OriginRedditTagsstar wars,image macro,reaction
  image,old meme,checks out
added_at: '2015-03-11T13:52:24-04:00'
