name: Foul Bachelor Frog
source: http://knowyourmeme.com/memes/foul-bachelor-frog
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- paper towel
- the plate that cleans up after itself
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About Foul Bachelor Frog is an advice animal image macro series featuring
  a frog's face in front of a color wheel background containing various shades of
  green. The images captions often depict lazy, disgusting and hedonistic behaviors
  associated with single men. Origin The original photo of the frog, filename frog-freckles-sore-throat-worst-home-remedies.jpg,
  first appeared in a post on the now defunct site remedicated.com titled "10 Bizarre
  and Ineffective Home Treatments" published sometime in June of 2008. Spread The
  image macro with the colour-wheel background, first began to surface in June 2009.
  The nature of the situations in which the Foul Bachelor Frog image macros describe,
  which most people can relate to, has made it one of the most generated Advice Animal
  image macros, and the second most copied advice animal on memegenerator.net[2].
  Other advice animal generator sites such as QuickMeme[3] and DIYLOL[4] contain generators
  for Foul Bachelor Frog. Foul Bachelor Frog gave inspiration for other related Advice
  Animal image macros such as Foul Bachelorette Frog Judging by search volume alone,
  Foul Bachelor Frog's popularity is comparable to that of some of the earliest advice
  animals. Part of this popularity is because it serves as a vehicle for sharing socially
  embarrassing behaviors that wouldn't be shared if it wasn't for anonymity. Many
  people may empathize with the behaviors finding it humorous that many others share
  the same experience. Notable Examples External References [1] Remedicated – 10 Bizarre
  and Ineffective Home Treatments (Web Archives) [2] Memegenerator.net – Foul Bachelor
  Frog [3] QuickMeme – Foul Bachelor Frog [4] DIYLOL – Foul Bachelor Frog [5] Urban
  Dictionary – It's funny because it's true [6] Chan4Chan – WAKE UP, MAKE PLANS FOR
  THE DAY – GRAB LAPTOP, STAY IN BED FOR 6 HOURS
aside_content: MemeStatusConfirmedBadges:SensitiveYear2009OriginMeme GeneratorTagsadvice
  dog,image macro,exploitable,frog,memegenerator,single character image macro,dating,relationship,boyfriend,singledom,social
  stereotypeAdditional ReferencesEncyclopedia Dramatica
added_at: '2009-11-06T16:24:15-05:00'
