name: Gru's Plan
source: https://knowyourmeme.com/memes/grus-plan
keywords:
- null
text:
- style: default
  color: black
  font: thin
  anchor_x: 0.275
  anchor_y: 0.2
  angle: 0.0
  scale_x: 0.2075
  scale_y: 0.2
  align: center
  start: 0.1
  stop: 1.0
- style: default
  color: black
  font: thin
  anchor_x: 0.78
  anchor_y: 0.2
  angle: 0.0
  scale_x: 0.205
  scale_y: 0.2
  align: center
  start: 0.3
  stop: 1.0
- style: default
  color: black
  font: thin
  anchor_x: 0.28
  anchor_y: 0.7
  angle: 0.0
  scale_x: 0.205
  scale_y: 0.2
  align: center
  start: 0.5
  stop: 1.0
- style: default
  color: black
  font: thin
  anchor_x: 0.78
  anchor_y: 0.7
  angle: 0.0
  scale_x: 0.205
  scale_y: 0.2
  align: center
  start: 0.7
  stop: 1.0
example:
- Learn how to make memes.
- Make a meme.
- No one likes it.
- No one likes it.
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About Gru's Plan is an exploitable four-panel comic series featuring
  the Despicable Me protagonist Gru using a presentation board. Edits of the comic
  typically feature an unexpected third presentation page, followed by a panel of
  Gru looking back at the board in confusion. Origin On July 9th, 2010 the film Despicable
  Me was released in theaters. In the film, the character Gru presents a plan to steal
  the moon in front of a man on a television screen and discovers a drawing of him
  sitting on the toilet hidden within his presentation pages. On March 9th, 2018,
  Redditor FieldMarshalSixDans submitted a four-panel version meme using screencaps
  from the scene in a post to r/deepfriedmemes. [1] The image was subsequently posted
  by /u/dankbob_memepants_ to r/memeeconomy that day, where it gathered over 18,000
  upvotes and 250 comments within 24 hours (shown below).[2] Spread On March 11th,
  2018 Reddit user very_niceu[3] uploaded a Nazi parody of the comic to /r/dankmemes,
  gathering upwards of 21,000 upvotes within 24 hours (shown below, left). Meanwhile,
  user charizard77[4] posted a edit about daylight savings time sleep schedules to
  /r/memes gathering more than 4,600 upvotes in the same timeframe (show below, center).
  Meanwhile, Reddit user 4k60fpsHDR[7] posted an edit about the education system to
  r/memes which gathered over 6,000 upvotes in under 24 hours. (Shown below, right)
  On March 12th, a Droste effect-themed version of the comic was submitted to /r/MemeEconomy[5]
  (shown below, left). That day, Redditor Pawaaar- posted a GIF version of the meme
  to /r/me_irl,[6] where it received upwards of 32,000 votes (89% upvoted) and 230
  comments within six hours (shown below, right). Later on March 14th, youtuber Pewdiepie
  made the 12th episode of his series entitled Meme Review. In this episode, Pewdiepie
  goes over memes such as "Peter Hurts His Knee", Inkling Girl's Eye, and Gru's Plan.
  This video went on to gain millions of views in it's first 24 hours alone. [This
  video has been removed] Various Examples Search Interest External References [1]
  /r/DeepFriedMemes – FieldMarshalSixDans [2] /r/MemeEconomy – dankbob_memepants_
  [3] /r/dankmemes/ – /u/very_niceu [4] /r/memes – /u/charizard77 [5] Reddit – /r/MemeEconomy
  [6] Reddit – me_irl [7] Reddit – u/4k60fpsHDR
aside_content: MemeStatusConfirmedType:Exploitable,PhotoshopYear2018OriginRedditTagsdespicable
  me,minions,2018,photoshop,reddit,grus plan,movies,fieldmarshalsixdans,very_niceu,charizard77,4k60fpshdr,presentation,pawaaar-,gru
  meme
added_at: '2018-03-11T10:15:15-04:00'
