example:
- Learn how to make memes.
- Make a meme.
- No one likes it.
- No one likes it.
keywords:
- null
name: Gru's Plan
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Gru's Plan | Know Your Meme Greetings! You must login or signup\
  \ first! Already a memeber? Login Now! Don't have an account? Sign up Now! Meme\
  \ Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Gru's Plan Added 6 years ago / Updated about a month ago Confirmed 317,866\
  \ Part of a series on Despicable Me. [View Related Entries] View All 485 Images\
  \ Navigation About \u2022 Origin \u2022 Spread \u2022 Various Examples \u2022 Search\
  \ Interest \u2022 External References \u2022 Recent Images \u2022 Recent Videos\
  \ About Gru's Plan is an exploitable four-panel comic series featuring the Despicable\
  \ Me protagonist Gru using a presentation board. Edits of the comic typically feature\
  \ an unexpected third presentation page, followed by a panel of Gru looking back\
  \ at the board in confusion. Origin On July 9th, 2010 the film Despicable Me was\
  \ released in theaters. In the film, the character Gru presents a plan to steal\
  \ the moon in front of a man on a television screen and discovers a drawing of him\
  \ sitting on the toilet hidden within his presentation pages. On March 9th, 2018,\
  \ Redditor FieldMarshalSixDans submitted a four-panel version meme using screencaps\
  \ from the scene in a post to r/deepfriedmemes. [1] The image was subsequently posted\
  \ by /u/dankbob_memepants_ to r/memeeconomy that day, where it gathered over 18,000\
  \ upvotes and 250 comments within 24 hours (shown below).[2] Spread On March 11th,\
  \ 2018 Reddit user very_niceu[3] uploaded a Nazi parody of the comic to /r/dankmemes,\
  \ gathering upwards of 21,000 upvotes within 24 hours (shown below, left). Meanwhile,\
  \ user charizard77[4] posted a edit about daylight savings time sleep schedules\
  \ to /r/memes gathering more than 4,600 upvotes in the same timeframe (show below,\
  \ center). Meanwhile, Reddit user 4k60fpsHDR[7] posted an edit about the education\
  \ system to r/memes which gathered over 6,000 upvotes in under 24 hours. (Shown\
  \ below, right) On March 12th, a Droste effect-themed version of the comic was submitted\
  \ to /r/MemeEconomy[5] (shown below, left). That day, Redditor Pawaaar- posted a\
  \ GIF version of the meme to /r/me_irl,[6] where it received upwards of 32,000 votes\
  \ (89% upvoted) and 230 comments within six hours (shown below, right). Later on\
  \ March 14th, youtuber Pewdiepie made the 12th episode of his series entitled Meme\
  \ Review. In this episode, Pewdiepie goes over memes such as \"Peter Hurts His Knee\"\
  , Inkling Girl's Eye, and Gru's Plan. This video went on to gain millions of views\
  \ in it's first 24 hours alone. [This video has been removed] Various Examples Search\
  \ Interest External References [1] /r/DeepFriedMemes \u2013 FieldMarshalSixDans\
  \ [2] /r/MemeEconomy \u2013 dankbob_memepants_ [3] /r/dankmemes/ \u2013 /u/very_niceu\
  \ [4] /r/memes \u2013 /u/charizard77 [5] Reddit \u2013 /r/MemeEconomy [6] Reddit\
  \ \u2013 me_irl [7] Reddit \u2013 u/4k60fpsHDR despicable me minions 2018 photoshop\
  \ reddit grus plan movies fieldmarshalsixdans very_niceu charizard77 4k60fpshdr\
  \ presentation pawaaar- gru meme Share Pin Related Entries 11 total Minions Vector\
  \ Gru Holding Gun / Things Are ... Gorl View All Related Entries Recent Images 485\
  \ total View All Images Recent Videos 6 total View All Videos Sign up for our Newsletter\
  \ Load 68 Comments Comments 68 total 92 Gru's Plan 317,866 6 485 68 Part of a series\
  \ on Despicable Me. [View Related Entries] Updated Nov 07, 2024 at 11:35AM EST by\
  \ LiterallyAustin. Added Mar 11, 2018 at 10:15AM EDT by 4k60fpsHDR. Like us on Facebook!\
  \ Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to\
  \ view the video gallery, or 'r' to view a random entry. Meme Status Confirmed Type:\
  \ Exploitable, Photoshop Year 2018 Origin Reddit Tags despicable me, minions, 2018,\
  \ photoshop, reddit, grus plan, movies, fieldmarshalsixdans, very_niceu, charizard77,\
  \ 4k60fpshdr, presentation, pawaaar-, gru meme About Gru's Plan is an exploitable\
  \ four-panel comic series featuring the Despicable Me protagonist Gru using a presentation\
  \ board. Edits of the comic typically feature an unexpected third presentation page,\
  \ followed by a panel of Gru looking back at the board in confusion. Origin On July\
  \ 9th, 2010 the film Despicable Me was released in theaters. In the film, the character\
  \ Gru presents a plan to steal the moon in front of a man on a television screen\
  \ and discovers a drawing of him sitting on the toilet hidden within his presentation\
  \ pages. On March 9th, 2018, Redditor FieldMarshalSixDans submitted a four-panel\
  \ version meme using screencaps from the scene in a post to r/deepfriedmemes. [1]\
  \ The image was subsequently posted by /u/dankbob_memepants_ to r/memeeconomy that\
  \ day, where it gathered over 18,000 upvotes and 250 comments within 24 hours (shown\
  \ below).[2] Spread On March 11th, 2018 Reddit user very_niceu[3] uploaded a Nazi\
  \ parody of the comic to /r/dankmemes, gathering upwards of 21,000 upvotes within\
  \ 24 hours (shown below, left). Meanwhile, user charizard77[4] posted a edit about\
  \ daylight savings time sleep schedules to /r/memes gathering more than 4,600 upvotes\
  \ in the same timeframe (show below, center). Meanwhile, Reddit user 4k60fpsHDR[7]\
  \ posted an edit about the education system to r/memes which gathered over 6,000\
  \ upvotes in under 24 hours. (Shown below, right) On March 12th, a Droste effect-themed\
  \ version of the comic was submitted to /r/MemeEconomy[5] (shown below, left). That\
  \ day, Redditor Pawaaar- posted a GIF version of the meme to /r/me_irl,[6] where\
  \ it received upwards of 32,000 votes (89% upvoted) and 230 comments within six\
  \ hours (shown below, right). Later on March 14th, youtuber Pewdiepie made the 12th\
  \ episode of his series entitled Meme Review. In this episode, Pewdiepie goes over\
  \ memes such as \"Peter Hurts His Knee\", Inkling Girl's Eye, and Gru's Plan. This\
  \ video went on to gain millions of views in it's first 24 hours alone. [This video\
  \ has been removed] Various Examples Search Interest External References [1] /r/DeepFriedMemes\
  \ \u2013 FieldMarshalSixDans [2] /r/MemeEconomy \u2013 dankbob_memepants_ [3] /r/dankmemes/\
  \ \u2013 /u/very_niceu [4] /r/memes \u2013 /u/charizard77 [5] Reddit \u2013 /r/MemeEconomy\
  \ [6] Reddit \u2013 me_irl [7] Reddit \u2013 u/4k60fpsHDR Related Entries 11 total\
  \ Minions Vector Gru Holding Gun / Things Are About to Get GRUesome Gorl IT'S SO\
  \ FLUFFY! Gru's Height Copypasta Gru Hella Gay Guys I Have Bad News Minions: The\
  \ Rise of Gru Gru Reading While Vector Explains Yes, I Am Pretty Despicable Recent\
  \ Videos 6 total Gru's Plan | Despicable Me 1 ... Gru's Plan Uploaded by Team5PM\
  \ Eu4 - Paradox's DLC Policy In... Gru's Plan Uploaded by Nigel the treasure hunter\
  \ What Super Smash Bros. Fans W... Gru's Plan Uploaded by Hypercat-Z Original scene\
  \ from which the... Gru's Plan Uploaded by Y F GRU'S PLAN MEME REVIEW Gru's Plan\
  \ Uploaded by hellyeahnick + Add a Video Recent Images 485 total Gru's Plan Uploaded\
  \ by Jaimie Hamilton Gru's Plan Uploaded by Reddit Moments Gru's Plan Uploaded by\
  \ arctic746 Gru's Plan Uploaded by Mr. Nobody Returns Gru's Plan Uploaded by Nyazilla\
  \ Gru's Plan Uploaded by Jaimie Hamilton Gru's Plan Uploaded by L Boy Gru's Plan\
  \ Uploaded by Reddit Moments Gru's Plan Uploaded by Yseult Gru's Plan Uploaded by\
  \ Reddit Moments Gru's Plan Uploaded by Reddit Moments Gru's Plan Uploaded by Triplem\
  \ + Add an Image View All Images Sign up for our Newsletter Top Comments Delete\
  \ Sensitive Nedhitis Mar 11, 2018 at 12:01PM EDT +118 Reply Delete Sensitive I keep\
  \ my ideals Mar 11, 2018 at 10:58AM EDT This is actually the only good Minions meme,\
  \ r/animemes are having a field day with this new exploitable. Especially good that\
  \ it's not a \"Things I don't like\" meme. +102 Reply + Add a Comment Comments (68)\
  \ Display Comments Add a Comment Top Entries This Month Meme Saika Kawakita Smile\
  \ GIF Event Assassination of UnitedHealthcare CEO Person Luigi Mangione UHC CEO\
  \ Shooter Subculture The Ki Sisters Culture Pornography Site Whisper View More Suggest\
  \ a Change Edit History Entry Editors (8) 4k60fpsHDR Deactivated Twist Database\
  \ Moderator & Ponyologist 3kole5 Sr. Entry Moderator Y F Digital Archaeologist &\
  \ Treasurer & Media Maid Don Administrator & Meme Daddy Z. Database Moderator &\
  \ Rage Comicologist Brad Digital Archaeologist & Treasurer & Pundit & Gallery Housekeeper\
  \ Zach Memenator \u25BC + Request Editorship View All Editors Today's Top Image\
  \ Galleries Assassination of UnitedHealthcare CEO Team Fortress 2 Squirrel Girl\
  \ (Doreen Green) The Amazing Digital Circus About Our Story Site Rules Policies\
  \ and Guidelines Credits Contact Meme DB Memes Episodes News Staff Contact Extras!\
  \ Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/grus-plan
template_id: gru
text:
- align: center
  anchor_x: 0.275
  anchor_y: 0.2
  angle: 0.0
  color: black
  font: thin
  scale_x: 0.2075
  scale_y: 0.2
  start: 0.1
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.78
  anchor_y: 0.2
  angle: 0.0
  color: black
  font: thin
  scale_x: 0.205
  scale_y: 0.2
  start: 0.3
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.28
  anchor_y: 0.7
  angle: 0.0
  color: black
  font: thin
  scale_x: 0.205
  scale_y: 0.2
  start: 0.5
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.78
  anchor_y: 0.7
  angle: 0.0
  color: black
  font: thin
  scale_x: 0.205
  scale_y: 0.2
  start: 0.7
  stop: 1.0
  style: default
text_zones: 4
