example:
- ''
- aliens
keywords:
- History Channel
name: Ancient Aliens Guy
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: 'Ancient Aliens | Know Your Meme Namaste! You must login or signup
  first! Already a memeber? Login Now! Don''t have an account? Sign up Now! Meme Encyclopedia
  All Cultures Events People Sites Subcultures Videos Submit → Images Trending Most
  Commented Most Favorited High Score Low Score Most Viewed All Templates Upload an
  Image Articles News Explainers Collections Interviews Meme Insider Magazine More
  Discord Newsletter Episodes Forums Meme Store Login Abstract user icon Memes Categories
  Trending News Images Trending Images Videos Trending Videos Editorials Meme Insider
  Magazine Newsletter Policies and Guidelines Meme Store Old site Login Know Your
  Meme is the property of Literally Media ©2024 Literally Media. All Rights Reserved.
  This image Of Woman Confidently Strolling Through A Glass Panel Has Been A Redraw
  Format Since 2021 Three Years Ago, This Boar''s Head ''Exploded'' Onto The Meme
  Scene Remember Il Vaticano? The Anarchy Chess Memes Turns Two Years Old Today Phrase
  ''The Fridge Protects The Snacks'' A Growing Favorite Among Pickup Artist Influencers
  Jamie G, The Bosh British Charva, Has Taken Over TikTok With His Signature ''Oh
  Cherie Amour'' Sound Also Trending: Honey Extension Influencer Scam Renegade Raider
  Copypasta Assassination of UnitedHealthcare CEO Ancient Aliens Added 13 years ago
  / Updated about 16 hours ago Confirmed 4,264,886 Part of a series on History Channel.
  [View Related Entries] View All 718 Images Featured Episode Navigation About • Origin
  • Spread • Templates • Search Interest • Recent Images • Recent Videos About Ancient
  Aliens is a series of image macros based on History Channel''s TV series with the
  same name starring alien expert Giorgio A. Tsoukalos, who often tends to explain
  inexplicable phenomena as the direct result of aliens or extraterrestrials being
  on Earth. In a somewhat similar fashion to Bill O''Reilly''s You Can''t Explain
  That series, the Ancient Aliens macros exaggerate Tsoukalos'' beliefs to such an
  extent that they become humourous. Origin The still shot of Giorgio A. Tsoukalos
  originated from the History Channel series Ancient Aliens[1], a documentary series
  that explores the possibility that aliens may have visited in the past. The program
  is directed and produced by Giorgio A. Tsoukalos and first aired on April 20th,
  2010. Ancient Astronaut Theory The documentary focuses on the "Ancient Astronaut
  Theory"[2] which states that extraterrestrial beings came to earth throughout the
  ancient times and helped shape history. For example, the Ancient Astronaut Theory
  insists that the pyramids were built by the help of alien technologies and that
  the great pyramids align with the constellation Orion; where some of the aliens
  may exist or came from. The show has come under some criticism for being "far fetched",
  "hugely speculative" and "expound[ing] wildly on theories suggesting that astronauts
  wandered the Earth freely in ancient time." Spread Giorgio A. Tsoukalos''s unworldly
  appearance and predictable resort to aliens in explaining various mysteries of human
  civilization caught many people''s attention in the audience. As early as in November
  2010, his "alien" repertoire became a popular subject of lulzy mockeries when it
  reached 4chan''s /b/ (random) board[3], spawning a steady stream of images centered
  around an exploitable screenshot of Giorgio A. Tsoukalos from the TV series. The
  image macros generally poke fun at Tsoukalos'' supposed obsession with "Ancient
  Astronaut Theory," featuring text that puts forth a question about a well-known
  mystery like the Egyptian pyramids, the answer to which is always aliens. The propagation
  of Ancient Aliens series was further aided by a number of image macro application
  sites including MemeGenerator[4], Quickmeme[5], DIYLOL[6] and Troll.me[7] among
  others. Beginning in mid-2011, the image macro series began to pick up momentum
  on several popular hubsites such as 4chan[8], Reddit[9], and Tumblr[10]. Since gaining
  a solid following on 4chan''s /b/, Ancient Alien image macros have also spread to
  related forums like /x/ (paranormal), /sci/[11] (science & math) and /tv/ (television)
  boards where they''re often used with intent to start a tireless debate or threadjack
  by bringing up the Ancient Astronaut Theory. Templates Notable Examples " Search
  Interest External References [1] Wikipedia – Ancient Aliens: Reception [2] Wikipedia
  – Ancient Astronaut Theory [3] 4chan – World War II: Star Wars Edition on /b/ (page
  unavailable) [4] MemeGenerator – Ancient Aliens [5] QuickMeme – Ancient Aliens [6]
  DIYLOL (via Wayback Machine) – Ancient Aliens [7] Troll.me (via Wayback Machine)
  – Ancient Aliens [8] 4chanarchive – UFO Stories on /x/ (page unavailable) [9] Reddit
  – Talking About Ancient Aliens [10] Tumblr – Tagged Results for Ancient Aliens [11]
  ArchivedMoe – Ancient Aliens on /sci/ [12] Sherdog Forum (via Wayback Machine) –
  Ancient aliens giorgio meme [13] BodyBuilding Forum – Anyone have the guy from Ancient
  Aliens meme pic? [14] FunnyJunk – Ancient Aliens Comp ancient aliens channel scifi
  parody image macro history notables of 2011 giorgio a. tsoukalos ancient astronaut
  theory ancient aliens meme ancient aliens memes Share Pin Related Entries 3 total
  Pawn Stars Duck Dynasty Controversy History Channel at Night Recent Images 718 total
  View All Images Recent Videos 25 total View All Videos Sign up for our Newsletter
  Load 111 Comments Comments 111 total 200 Ancient Aliens 4,264,888 25 718 111 Part
  of a series on History Channel. [View Related Entries] Updated Dec 23, 2024 at 04:08PM
  EST by LiterallyAustin. Added May 15, 2011 at 01:36AM EDT by JacobSk. Like us on
  Facebook! Like 1.8M Share Save Tweet PROTIP: Press ''i'' to view the image gallery,
  ''v'' to view the video gallery, or ''r'' to view a random entry. Featured Episode
  Meme Status Confirmed Type: Character, Conspiracy Theory, Image Macro, Parody, Pop
  Culture Reference Year 2010 Origin 4chan Tags ancient, aliens, channel, scifi, parody,
  image macro, history, notables of 2011, giorgio a. tsoukalos, ancient astronaut
  theory, ancient aliens meme, ancient aliens memes Additional References Meme Generator
  Wikipedia About Ancient Aliens is a series of image macros based on History Channel''s
  TV series with the same name starring alien expert Giorgio A. Tsoukalos, who often
  tends to explain inexplicable phenomena as the direct result of aliens or extraterrestrials
  being on Earth. In a somewhat similar fashion to Bill O''Reilly''s You Can''t Explain
  That series, the Ancient Aliens macros exaggerate Tsoukalos'' beliefs to such an
  extent that they become humourous. Origin The still shot of Giorgio A. Tsoukalos
  originated from the History Channel series Ancient Aliens[1], a documentary series
  that explores the possibility that aliens may have visited in the past. The program
  is directed and produced by Giorgio A. Tsoukalos and first aired on April 20th,
  2010. Ancient Astronaut Theory The documentary focuses on the "Ancient Astronaut
  Theory"[2] which states that extraterrestrial beings came to earth throughout the
  ancient times and helped shape history. For example, the Ancient Astronaut Theory
  insists that the pyramids were built by the help of alien technologies and that
  the great pyramids align with the constellation Orion; where some of the aliens
  may exist or came from. The show has come under some criticism for being "far fetched",
  "hugely speculative" and "expound[ing] wildly on theories suggesting that astronauts
  wandered the Earth freely in ancient time." Spread Giorgio A. Tsoukalos''s unworldly
  appearance and predictable resort to aliens in explaining various mysteries of human
  civilization caught many people''s attention in the audience. As early as in November
  2010, his "alien" repertoire became a popular subject of lulzy mockeries when it
  reached 4chan''s /b/ (random) board[3], spawning a steady stream of images centered
  around an exploitable screenshot of Giorgio A. Tsoukalos from the TV series. The
  image macros generally poke fun at Tsoukalos'' supposed obsession with "Ancient
  Astronaut Theory," featuring text that puts forth a question about a well-known
  mystery like the Egyptian pyramids, the answer to which is always aliens. The propagation
  of Ancient Aliens series was further aided by a number of image macro application
  sites including MemeGenerator[4], Quickmeme[5], DIYLOL[6] and Troll.me[7] among
  others. Beginning in mid-2011, the image macro series began to pick up momentum
  on several popular hubsites such as 4chan[8], Reddit[9], and Tumblr[10]. Since gaining
  a solid following on 4chan''s /b/, Ancient Alien image macros have also spread to
  related forums like /x/ (paranormal), /sci/[11] (science & math) and /tv/ (television)
  boards where they''re often used with intent to start a tireless debate or threadjack
  by bringing up the Ancient Astronaut Theory. Templates Notable Examples " Search
  Interest External References [1] Wikipedia – Ancient Aliens: Reception [2] Wikipedia
  – Ancient Astronaut Theory [3] 4chan – World War II: Star Wars Edition on /b/ (page
  unavailable) [4] MemeGenerator – Ancient Aliens [5] QuickMeme – Ancient Aliens [6]
  DIYLOL (via Wayback Machine) – Ancient Aliens [7] Troll.me (via Wayback Machine)
  – Ancient Aliens [8] 4chanarchive – UFO Stories on /x/ (page unavailable) [9] Reddit
  – Talking About Ancient Aliens [10] Tumblr – Tagged Results for Ancient Aliens [11]
  ArchivedMoe – Ancient Aliens on /sci/ [12] Sherdog Forum (via Wayback Machine) –
  Ancient aliens giorgio meme [13] BodyBuilding Forum – Anyone have the guy from Ancient
  Aliens meme pic? [14] FunnyJunk – Ancient Aliens Comp Related Entries 3 total Pawn
  Stars Duck Dynasty Controversy History Channel at Night Recent Videos 25 total Giorgio
  Tsoukalos Ancient Aliens Uploaded by shevyrolet aliens: meme Ancient Aliens Uploaded
  by shevyrolet Ancient Aliens: The Alien Det... Ancient Aliens Uploaded by shevyrolet
  Ancient Aliens: History Will ... Ancient Aliens Uploaded by shevyrolet Ancient Aliens:
  Robot Gods of... Ancient Aliens Uploaded by shevyrolet The Untold Truth Of Giorgio
  A... Ancient Aliens Uploaded by shevyrolet Ancient Aliens: Giorgio Expla... Ancient
  Aliens Uploaded by shevyrolet Alienation: Yes, It''s All Abo... Ancient Aliens Uploaded
  by shevyrolet + Add a Video View All Videos Recent Images 718 total Ancient Aliens
  Uploaded by Sum Lu Zer Ancient Aliens Uploaded by cfjulian Ancient Aliens Uploaded
  by cfjulian Ancient Aliens Uploaded by cfjulian Ancient Aliens Uploaded by Lorcan
  Wooster Ancient Aliens Uploaded by Renoc Ancient Aliens Uploaded by Y F Ancient
  Aliens Uploaded by Fight Milk22 Ancient Aliens Uploaded by the_transpirator Ancient
  Aliens Uploaded by andcallmeshirley Ancient Aliens Uploaded by Greenstreet Ancient
  Aliens Uploaded by Nyazilla + Add an Image View All Images Sign up for our Newsletter
  Top Comments Delete Sensitive Don Staff Aug 19, 2011 at 08:48PM EDT +46 Reply Delete
  Sensitive Jacob Hinds Jul 20, 2011 at 04:26AM EDT Ever noticed how the two editors
  of this article are called jacob? Aliens. +46 Reply + Add a Comment Comments (111)
  Display Comments Add a Comment Top Entries This Month Meme Saika Kawakita Smile
  GIF Event Assassination of UnitedHealthcare CEO Person Luigi Mangione UHC CEO Shooter
  Subculture The Ki Sisters Culture Pornography Site Whisper View More Suggest a Change
  Edit History Entry Editors (13) JacobSk Jacob Hinds Anako Sleuth & Scrapbooker &
  Conversationalist Ogreenworld Former Entry Moderator Mr Bumhole #1 Fan Of Osaka
  Hamsteak #1 & Television Meme Historian Brad Digital Archaeologist & Treasurer &
  Pundit & Gallery Housekeeper Don Administrator & Meme Daddy Synge Entry Moderator
  & Goat of the New World SabrinaTibbetts Memepuff Y F Digital Archaeologist & Treasurer
  & Media Maid andcallmeshirley Digital Archaeologist & Treasurer & Collection Butler
  shevyrolet Digital Archaeologist & Treasurer & Media Bus Boy Zach Memenator ▼ +
  Request Editorship View All Editors Today''s Top Image Galleries Assassination of
  UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing Digital
  Circus About Our Story Site Rules Policies and Guidelines Credits Contact Meme DB
  Memes Episodes News Staff Contact Extras! Style Guide RSS Feeds'
source: http://knowyourmeme.com/memes/ancient-aliens
template_id: aag
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
