name: Ancient Aliens Guy
source: http://knowyourmeme.com/memes/ancient-aliens
keywords:
- History Channel
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- ''
- aliens
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Ancient Aliens is a series of image macros based on History
  Channel''s TV series with the same name starring alien expert Giorgio A. Tsoukalos,
  who often tends to explain inexplicable phenomena as the direct result of aliens
  or extraterrestrials being on Earth. In a somewhat similar fashion to Bill O''Reilly''s
  You Can''t Explain That series, the Ancient Aliens macros exaggerate Tsoukalos''
  beliefs to such an extent that they become humourous. Origin The still shot of Giorgio
  A. Tsoukalos originated from the History Channel series Ancient Aliens[1], a documentary
  series that explores the possibility that aliens may have visited in the past. The
  program is directed and produced by Giorgio A. Tsoukalos and first aired on April
  20th, 2010. Ancient Astronaut Theory The documentary focuses on the "Ancient Astronaut
  Theory"[2] which states that extraterrestrial beings came to earth throughout the
  ancient times and helped shape history. For example, the Ancient Astronaut Theory
  insists that the pyramids were built by the help of alien technologies and that
  the great pyramids align with the constellation Orion; where some of the aliens
  may exist or came from. The show has come under some criticism for being "far fetched",
  "hugely speculative" and "expound[ing] wildly on theories suggesting that astronauts
  wandered the Earth freely in ancient time." Spread Giorgio A. Tsoukalos''s unworldly
  appearance and predictable resort to aliens in explaining various mysteries of human
  civilization caught many people''s attention in the audience. As early as in November
  2010, his "alien" repertoire became a popular subject of lulzy mockeries when it
  reached 4chan''s /b/ (random) board[3], spawning a steady stream of images centered
  around an exploitable screenshot of Giorgio A. Tsoukalos from the TV series. The
  image macros generally poke fun at Tsoukalos'' supposed obsession with "Ancient
  Astronaut Theory," featuring text that puts forth a question about a well-known
  mystery like the Egyptian pyramids, the answer to which is always aliens. The propagation
  of Ancient Aliens series was further aided by a number of image macro application
  sites including MemeGenerator[4], Quickmeme[5], DIYLOL[6] and Troll.me[7] among
  others. Beginning in mid-2011, the image macro series began to pick up momentum
  on several popular hubsites such as 4chan[8], Reddit[9], and Tumblr[10]. Since gaining
  a solid following on 4chan''s /b/, Ancient Alien image macros have also spread to
  related forums like /x/ (paranormal), /sci/[11] (science & math) and /tv/ (television)
  boards where they''re often used with intent to start a tireless debate or threadjack
  by bringing up the Ancient Astronaut Theory. Templates Notable Examples " Search
  Interest External References [1] Wikipedia – Ancient Aliens: Reception [2] Wikipedia
  – Ancient Astronaut Theory [3] 4chan – World War II: Star Wars Edition on /b/ (page
  unavailable) [4] MemeGenerator – Ancient Aliens [5] QuickMeme – Ancient Aliens [6]
  DIYLOL (via Wayback Machine) – Ancient Aliens [7] Troll.me (via Wayback Machine)
  – Ancient Aliens [8] 4chanarchive – UFO Stories on /x/ (page unavailable) [9] Reddit
  – Talking About Ancient Aliens [10] Tumblr – Tagged Results for Ancient Aliens [11]
  ArchivedMoe – Ancient Aliens on /sci/ [12] Sherdog Forum (via Wayback Machine) –
  Ancient aliens giorgio meme [13] BodyBuilding Forum – Anyone have the guy from Ancient
  Aliens meme pic? [14] FunnyJunk – Ancient Aliens Comp'
aside_content: MemeStatusConfirmedType:Character,Conspiracy Theory,Image Macro,Parody,Pop
  Culture ReferenceYear2010Origin4chanTagsancient,aliens,channel,scifi,parody,image
  macro,history,notables of 2011,giorgio a. tsoukalos,ancient astronaut theory,ancient
  aliens meme,ancient aliens memesAdditional ReferencesMeme GeneratorWikipedia
added_at: '2011-05-15T01:36:00-04:00'
