name: Afraid to Ask Andy
source: http://knowyourmeme.com/memes/afraid-to-ask-andy
keywords:
- Parks and Recreation
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- i don't know what this meme is for
- and at this point i'm too afraid to ask
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About "Afraid to Ask" Andy is an advice animal image macro series
  featuring a still image of Andy Dwyer (played by Chris Pratt), one of the main characters
  from the American TV sitcom Parks and Recreation, captioned with various confessions
  of one's ignorance in current events or common knowledge followed by the phrase
  "…and at this point I’m afraid to ask.” Origin The caption stems from a memorable
  quote uttered by Andy Dwyer, who is portrayed as an oblivious but lovable city worker
  in the fictional town of Pawnee, in Season 6 Episode 16 "A New Slogan"[5] originally
  aired on March 13th, 2014. On October 23rd, 2014, Redditor john_solo76 created a
  post titled “Afraid to Ask Andy – Reddit is hard to follow sometimes”, featuring
  a photo of Dwyer with the caption “I don’t know what GamerGate is / And at this
  point I’m too afraid to ask” (shown below). In the first 24 hours, the post gained
  over 3,800 upvotes and 2,000 comments on the /r/AdviceAnimals[2] subreddit. Spread
  On the same day, Redditor silkysmooth190 submitted an Afraid to Ask Andy image macro
  expressing ignorance about net neutrality to /r/AdviceAnimals[4] (shown below, left).
  On October 24th, 2014, Redditor I_Am_Batman_For_Real posted an Afraid to Ask Andy
  image macro joking about the online fandoms for actor Nicolas Cage to /r/AdviceAnimals.[3]
  In less than 24 hours, the posts received more than 3,300 votes (87% upvoted). The
  same day, the tech news blog Mashable[1] published an article highlighting several
  notable examples from the series. Notable Examples Search Interest Not available.
  External References [1] Mashable – Afraid to Ask Andy Meme Perfectly Captures Your
  Insecurities [2] Reddit – Afraid to Ask Andy [3] Reddit – Afraid to Ask Andy – Ive
  been on Reddit awhile and still I still dont know [4] Reddit – Afraid to ask Andy
  [5] SpringfieldSpringfield – Parks and Recreation Episode Scripts – New Slogan
aside_content: MemeStatusConfirmedType:Image MacroYear2014OriginRedditTagsimage macro,television,advice
  animal,john_solo76,silkysmooth190,i_am_batman_for_real
added_at: '2014-10-24T14:28:14-04:00'
