example:
- i don't know what this meme is for
- and at this point i'm too afraid to ask
keywords:
- Parks and Recreation
name: Afraid to Ask Andy
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "\"Afraid to Ask\" Andy | Know Your Meme Hello! You must login or\
  \ signup first! Already a memeber? Login Now! Don't have an account? Sign up Now!\
  \ Meme Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO \"Afraid to Ask\" Andy Added 10 years ago / Updated 5 years ago Confirmed\
  \ 246,823 Part of a series on Parks and Recreation. [View Related Entries] View\
  \ All 23 Images Navigation About \u2022 Origin \u2022 Spread \u2022 Notable Examples\
  \ \u2022 Search Interest \u2022 External References \u2022 Recent Images About \"\
  Afraid to Ask\" Andy is an advice animal image macro series featuring a still image\
  \ of Andy Dwyer (played by Chris Pratt), one of the main characters from the American\
  \ TV sitcom Parks and Recreation, captioned with various confessions of one's ignorance\
  \ in current events or common knowledge followed by the phrase \"\u2026and at this\
  \ point I\u2019m afraid to ask.\u201D Origin The caption stems from a memorable\
  \ quote uttered by Andy Dwyer, who is portrayed as an oblivious but lovable city\
  \ worker in the fictional town of Pawnee, in Season 6 Episode 16 \"A New Slogan\"\
  [5] originally aired on March 13th, 2014. On October 23rd, 2014, Redditor john_solo76\
  \ created a post titled \u201CAfraid to Ask Andy \u2013 Reddit is hard to follow\
  \ sometimes\u201D, featuring a photo of Dwyer with the caption \u201CI don\u2019\
  t know what GamerGate is / And at this point I\u2019m too afraid to ask\u201D (shown\
  \ below). In the first 24 hours, the post gained over 3,800 upvotes and 2,000 comments\
  \ on the /r/AdviceAnimals[2] subreddit. Spread On the same day, Redditor silkysmooth190\
  \ submitted an Afraid to Ask Andy image macro expressing ignorance about net neutrality\
  \ to /r/AdviceAnimals[4] (shown below, left). On October 24th, 2014, Redditor I_Am_Batman_For_Real\
  \ posted an Afraid to Ask Andy image macro joking about the online fandoms for actor\
  \ Nicolas Cage to /r/AdviceAnimals.[3] In less than 24 hours, the posts received\
  \ more than 3,300 votes (87% upvoted). The same day, the tech news blog Mashable[1]\
  \ published an article highlighting several notable examples from the series. Notable\
  \ Examples Search Interest Not available. External References [1] Mashable \u2013\
  \ Afraid to Ask Andy Meme Perfectly Captures Your Insecurities [2] Reddit \u2013\
  \ Afraid to Ask Andy [3] Reddit \u2013 Afraid to Ask Andy \u2013 Ive been on Reddit\
  \ awhile and still I still dont know [4] Reddit \u2013 Afraid to ask Andy [5] SpringfieldSpringfield\
  \ \u2013 Parks and Recreation Episode Scripts \u2013 New Slogan image macro television\
  \ advice animal john_solo76 silkysmooth190 i_am_batman_for_real Share Pin Related\
  \ Entries 11 total It's Beautiful I've Looked At... You Go To Jail \"I'm a Simple\
  \ Man\" Ron Swanson View All Related Entries Recent Images 23 total View All Images\
  \ Recent Videos 0 total There are no recent videos. Sign up for our Newsletter Load\
  \ 57 Comments Comments 57 total 12 \"Afraid to Ask\" Andy 246,823 0 23 57 Part of\
  \ a series on Parks and Recreation. [View Related Entries] Updated Sep 18, 2019\
  \ at 06:00AM EDT by Y F. Added Oct 24, 2014 at 02:28PM EDT by Don. Like us on Facebook!\
  \ Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to\
  \ view the video gallery, or 'r' to view a random entry. Meme Status Confirmed Type:\
  \ Image Macro Year 2014 Origin Reddit Tags image macro, television, advice animal,\
  \ john_solo76, silkysmooth190, i_am_batman_for_real About \"Afraid to Ask\" Andy\
  \ is an advice animal image macro series featuring a still image of Andy Dwyer (played\
  \ by Chris Pratt), one of the main characters from the American TV sitcom Parks\
  \ and Recreation, captioned with various confessions of one's ignorance in current\
  \ events or common knowledge followed by the phrase \"\u2026and at this point I\u2019\
  m afraid to ask.\u201D Origin The caption stems from a memorable quote uttered by\
  \ Andy Dwyer, who is portrayed as an oblivious but lovable city worker in the fictional\
  \ town of Pawnee, in Season 6 Episode 16 \"A New Slogan\"[5] originally aired on\
  \ March 13th, 2014. On October 23rd, 2014, Redditor john_solo76 created a post titled\
  \ \u201CAfraid to Ask Andy \u2013 Reddit is hard to follow sometimes\u201D, featuring\
  \ a photo of Dwyer with the caption \u201CI don\u2019t know what GamerGate is /\
  \ And at this point I\u2019m too afraid to ask\u201D (shown below). In the first\
  \ 24 hours, the post gained over 3,800 upvotes and 2,000 comments on the /r/AdviceAnimals[2]\
  \ subreddit. Spread On the same day, Redditor silkysmooth190 submitted an Afraid\
  \ to Ask Andy image macro expressing ignorance about net neutrality to /r/AdviceAnimals[4]\
  \ (shown below, left). On October 24th, 2014, Redditor I_Am_Batman_For_Real posted\
  \ an Afraid to Ask Andy image macro joking about the online fandoms for actor Nicolas\
  \ Cage to /r/AdviceAnimals.[3] In less than 24 hours, the posts received more than\
  \ 3,300 votes (87% upvoted). The same day, the tech news blog Mashable[1] published\
  \ an article highlighting several notable examples from the series. Notable Examples\
  \ Search Interest Not available. External References [1] Mashable \u2013 Afraid\
  \ to Ask Andy Meme Perfectly Captures Your Insecurities [2] Reddit \u2013 Afraid\
  \ to Ask Andy [3] Reddit \u2013 Afraid to Ask Andy \u2013 Ive been on Reddit awhile\
  \ and still I still dont know [4] Reddit \u2013 Afraid to ask Andy [5] SpringfieldSpringfield\
  \ \u2013 Parks and Recreation Episode Scripts \u2013 New Slogan Related Entries\
  \ 11 total It's Beautiful I've Looked At This For Five Hours Now You Go To Jail\
  \ \"I'm a Simple Man\" Ron Swanson Do You Have Any Mental Illness In Your Family\
  \ April, No! Someone Will Die. Of Fun. Okay, Well, That's Interesting. You Know\
  \ Why? Why? Because *Runs Away* No. We're Good, Thanks Galentine's Day Do You Think\
  \ a Depressed Person Could Make This? Recent Videos There are no videos currently\
  \ available. + Add a Video Recent Images 23 total \"Afraid to Ask\" Andy Uploaded\
  \ by Jill \"Afraid to Ask\" Andy Uploaded by Rebecca Rhodes \"Afraid to Ask\" Andy\
  \ Uploaded by Reddit Moments \"Afraid to Ask\" Andy Uploaded by Reddit Moments \"\
  Afraid to Ask\" Andy Uploaded by Reddit Moments \"Afraid to Ask\" Andy Uploaded\
  \ by Reddit Moments \"Afraid to Ask\" Andy Uploaded by Reddit Moments \"Afraid to\
  \ Ask\" Andy Uploaded by Rebecca Rhodes \"Afraid to Ask\" Andy Uploaded by Rebecca\
  \ Rhodes \"Afraid to Ask\" Andy Uploaded by Particle Mare \"Afraid to Ask\" Andy\
  \ Uploaded by murrayrelch \"Afraid to Ask\" Andy Uploaded by Particle Mare + Add\
  \ an Image View All Images Sign up for our Newsletter Top Comments Delete Sensitive\
  \ Crimeariver Oct 24, 2014 at 05:42PM EDT >New advice animal >Frontpage >Created\
  \ by Don +86 Reply Delete Sensitive Paulie DeMafia Mk2 Oct 24, 2014 at 02:54PM EDT\
  \ in reply to unosblade Don is the memegod of the internet. We are all part of his\
  \ grand design and that is to meme on everything that ever existed, currently exists\
  \ and shall exist in the future. Only then will the crucible collapse and his ascension\
  \ into godhood shall be complete! On his free time though, he is one of the admins\
  \ on KYM. He has documented many advice animals and some hashtags. People got angry\
  \ at him for doing that. I think that now complaining about \"Don making an Advice\
  \ Animal article\" has become more tongue in cheek. (I could be wrong though) +55\
  \ Reply + Add a Comment Comments (57) Display Comments Add a Comment Top Entries\
  \ This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (3) Don Administrator\
  \ & Meme Daddy andcallmeshirley Digital Archaeologist & Treasurer & Collection Butler\
  \ Y F Digital Archaeologist & Treasurer & Media Maid + Request Editorship View All\
  \ Editors Today's Top Image Galleries Assassination of UnitedHealthcare CEO Squirrel\
  \ Girl (Doreen Green) Team Fortress 2 The Amazing Digital Circus About Our Story\
  \ Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes News\
  \ Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/afraid-to-ask-andy
template_id: afraid
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
