name: Drowning High Five
source: https://knowyourmeme.com/memes/drowning-high-five
keywords:
- null
text:
- style: default
  color: white
  font: thick
  anchor_x: 0.03
  anchor_y: 0.33
  angle: 0.0
  scale_x: 0.46
  scale_y: 0.15
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: white
  font: thick
  anchor_x: 0.51
  anchor_y: 0.14
  angle: 0.0
  scale_x: 0.2
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: khaki
  font: thick
  anchor_x: 0.03
  anchor_y: 0.82
  angle: 0.0
  scale_x: 0.46
  scale_y: 0.15
  align: center
  start: 0.4
  stop: 1.0
example:
- Me Asking for Help
- Online Commenter
- I'm having that problem too.
overlay:
- center_x: 0.585
  center_y: 0.14
  angle: 0.0
  scale: 0.2
scraped_content: About Drowning High Five refers to a comic by Russian artist Gudim
  showing a hand reaching out of water, evidently belonging to a drowning person.
  Another hand comes in and gives the drowning hand a high five. The comic has been
  used as a reaction image and object labeling exploitable. Origin On June 19th, 2017,
  artist Gudim posted the drowning comic to their Instagram page,[1] where it gained
  over 43,000 likes (shown below). Spread The comic first began spreading as a reaction
  image, paired with captions where one celebrates the failure of others. For example,
  On February 26th, 2018, Facebook page Sarcasm Society[2] posted the image with the
  caption "When your ex drowning," gaining over 5,500 likes and reactions (shown below,
  left). A July 10th, 2017 post on /r/2meirl4meirl gained over 770 points (shown below,
  right). Later variations turned the image into an object labeling exploitable. For
  example, Redditor CorporalChipmunk posted an edit on January 9th, 2019 to /r/programmerhumor
  that gained over 34,000 points (shown below, left). A post by user OfficialHerst
  to /r/2meirl4meirl from December 26th, 2018 gained over 30,000 points (shown below,
  right). Various Examples Search Interest External References [1] Instagram – Gudim
  [2] Facebook – Sarcasm society
aside_content: MemeStatusConfirmedType:ExploitableYear2017OriginGudimTagscomic,drowning,object
  labeling,gudim,corporalchipmunk,officialherst
added_at: '2019-01-17T14:14:47-05:00'
