example:
- Me Asking for Help
- Online Commenter
- I'm having that problem too.
keywords:
- null
name: Drowning High Five
overlay:
- angle: 0.0
  center_x: 0.585
  center_y: 0.14
  scale: 0.2
scraped_content: "Drowning High Five | Know Your Meme Hey! You must login or signup\
  \ first! Already a memeber? Login Now! Don't have an account? Sign up Now! Meme\
  \ Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Drowning High Five Added 5 years ago / Updated 4 years ago Confirmed 74,301\
  \ Part of a series on Object Labeling. [View Related Entries] View All 15 Images\
  \ Navigation About \u2022 Origin \u2022 Spread \u2022 Various Examples \u2022 Search\
  \ Interest \u2022 External References \u2022 Recent Images About Drowning High Five\
  \ refers to a comic by Russian artist Gudim showing a hand reaching out of water,\
  \ evidently belonging to a drowning person. Another hand comes in and gives the\
  \ drowning hand a high five. The comic has been used as a reaction image and object\
  \ labeling exploitable. Origin On June 19th, 2017, artist Gudim posted the drowning\
  \ comic to their Instagram page,[1] where it gained over 43,000 likes (shown below).\
  \ Spread The comic first began spreading as a reaction image, paired with captions\
  \ where one celebrates the failure of others. For example, On February 26th, 2018,\
  \ Facebook page Sarcasm Society[2] posted the image with the caption \"When your\
  \ ex drowning,\" gaining over 5,500 likes and reactions (shown below, left). A July\
  \ 10th, 2017 post on /r/2meirl4meirl gained over 770 points (shown below, right).\
  \ Later variations turned the image into an object labeling exploitable. For example,\
  \ Redditor CorporalChipmunk posted an edit on January 9th, 2019 to /r/programmerhumor\
  \ that gained over 34,000 points (shown below, left). A post by user OfficialHerst\
  \ to /r/2meirl4meirl from December 26th, 2018 gained over 30,000 points (shown below,\
  \ right). Various Examples Search Interest External References [1] Instagram \u2013\
  \ Gudim [2] Facebook \u2013 Sarcasm society comic drowning object labeling gudim\
  \ corporalchipmunk officialherst Share Pin Related Entries 93 total Distracted Boyfriend\
  \ Forced to Drink Milk Epic Handshake Trumpet Boy View All Related Entries Recent\
  \ Images 15 total View All Images Recent Videos 0 total There are no recent videos.\
  \ Sign up for our Newsletter Load 5 Comments Comments 5 total 9 Drowning High Five\
  \ 74,301 0 15 5 Part of a series on Object Labeling. [View Related Entries] Updated\
  \ Sep 03, 2020 at 03:27AM EDT by ohmyjosh. Added Jan 17, 2019 at 02:14PM EST by\
  \ Adam. Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i' to view\
  \ the image gallery, 'v' to view the video gallery, or 'r' to view a random entry.\
  \ Meme Status Confirmed Type: Exploitable Year 2017 Origin Gudim Tags comic, drowning,\
  \ object labeling, gudim, corporalchipmunk, officialherst About Drowning High Five\
  \ refers to a comic by Russian artist Gudim showing a hand reaching out of water,\
  \ evidently belonging to a drowning person. Another hand comes in and gives the\
  \ drowning hand a high five. The comic has been used as a reaction image and object\
  \ labeling exploitable. Origin On June 19th, 2017, artist Gudim posted the drowning\
  \ comic to their Instagram page,[1] where it gained over 43,000 likes (shown below).\
  \ Spread The comic first began spreading as a reaction image, paired with captions\
  \ where one celebrates the failure of others. For example, On February 26th, 2018,\
  \ Facebook page Sarcasm Society[2] posted the image with the caption \"When your\
  \ ex drowning,\" gaining over 5,500 likes and reactions (shown below, left). A July\
  \ 10th, 2017 post on /r/2meirl4meirl gained over 770 points (shown below, right).\
  \ Later variations turned the image into an object labeling exploitable. For example,\
  \ Redditor CorporalChipmunk posted an edit on January 9th, 2019 to /r/programmerhumor\
  \ that gained over 34,000 points (shown below, left). A post by user OfficialHerst\
  \ to /r/2meirl4meirl from December 26th, 2018 gained over 30,000 points (shown below,\
  \ right). Various Examples Search Interest External References [1] Instagram \u2013\
  \ Gudim [2] Facebook \u2013 Sarcasm society Related Entries 93 total Distracted\
  \ Boyfriend Forced to Drink Milk Epic Handshake Trumpet Boy Respect Women Baton\
  \ Roue Bronze Medal Germany Oneesan / Anime Girl's Nazi Past The What / Rug Doctor\
  \ Woman Ad Left Exit 12 Off Ramp Fantasy Painting Object Labeling Assassination\
  \ Chain View All Related Entries Recent Videos There are no videos currently available.\
  \ + Add a Video Recent Images 15 total Drowning High Five Uploaded by Jaimie Hamilton\
  \ Drowning High Five Uploaded by OurDeerLeader Drowning High Five Uploaded by Mike\
  \ Drowning High Five Uploaded by D9fred95 Drowning High Five Uploaded by Adam Drowning\
  \ High Five Uploaded by Adam Drowning High Five Uploaded by Adam Drowning High Five\
  \ Uploaded by Adam Drowning High Five Uploaded by Adam Drowning High Five Uploaded\
  \ by Adam Drowning High Five Uploaded by Adam Drowning High Five Uploaded by Adam\
  \ + Add an Image View All Images Sign up for our Newsletter Top Comments Delete\
  \ Sensitive Adam DeLand Mar 13, 2019 at 10:46PM EDT Reminds me of this: +4 Reply\
  \ Delete Sensitive HelifIgno Jan 17, 2019 at 09:55PM EST I am disappointed that\
  \ the guy drowning did not thumbs up all Terminator style. +3 Reply + Add a Comment\
  \ Comments (5) Display Comments Add a Comment Top Entries This Month Meme Saika\
  \ Kawakita Smile GIF Event Assassination of UnitedHealthcare CEO Person Luigi Mangione\
  \ UHC CEO Shooter Subculture The Ki Sisters Culture Pornography Site Whisper View\
  \ More Suggest a Change Edit History Entry Editors (3) Adam Know Your Meme Universal\
  \ Champion Y F Digital Archaeologist & Treasurer & Media Maid ohmyjosh Digital Archaeologist\
  \ & Cataloger + Request Editorship View All Editors Today's Top Image Galleries\
  \ Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress\
  \ 2 The Amazing Digital Circus About Our Story Site Rules Policies and Guidelines\
  \ Credits Contact Meme DB Memes Episodes News Staff Contact Extras! Style Guide\
  \ RSS Feeds"
source: https://knowyourmeme.com/memes/drowning-high-five
template_id: drowning
text:
- align: center
  anchor_x: 0.03
  anchor_y: 0.33
  angle: 0.0
  color: white
  font: thick
  scale_x: 0.46
  scale_y: 0.15
  start: 0.0
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.51
  anchor_y: 0.14
  angle: 0.0
  color: white
  font: thick
  scale_x: 0.2
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.03
  anchor_y: 0.82
  angle: 0.0
  color: khaki
  font: thick
  scale_x: 0.46
  scale_y: 0.15
  start: 0.4
  stop: 1.0
  style: default
text_zones: 3
