example:
- Top Line
- Bottom Line
keywords:
- everybody gets
- you win
name: Oprah You Get a Car
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Oprah's \"You Get a Car\" | Know Your Meme Yo! You must login or\
  \ signup first! Already a memeber? Login Now! Don't have an account? Sign up Now!\
  \ Meme Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Oprah's \"You Get a Car\" Added 11 years ago / Updated about 17 hours ago\
  \ Confirmed 327,515 Part of a series on Oprah Winfrey. [View Related Entries] View\
  \ All 33 Images Navigation About \u2022 Origin \u2022 Spread \u2022 Notable Examples\
  \ \u2022 Search Interest \u2022 External References \u2022 Recent Images \u2022\
  \ Recent Videos About Oprah You Get a Car is a series of video remixes and advice\
  \ animal image macros parodying an episode of The Oprah Winfrey Show in which the\
  \ entire studio audience is given a free car. Many of the parodies mock the phrase\
  \ \"you get a car,\" which was repeated by the talk show host several times during\
  \ the episode. Origin On September 13th, 2004, Oprah gave away new Pontiac G6 cars\
  \ to the entire audience attending her show (shown below).[3] On May 15th, 2005,\
  \ the giveaway was parodied in Season 1 Episode 12 of the stop motion animated television\
  \ show Robot Chicken (shown below, left). On March 22nd, 2008, YouTuber merese uploaded\
  \ an animated parody of the car giveaway (shown below, right), gaining more than\
  \ 29,000 views and 90 comments in the next five years. [This video has been removed]\
  \ Spread On April 24th, 2008, YouTuber Ryazilian uploaded a music remix of the giveaway\
  \ footage (shown below, right), which received over 575,000 views and 900 comments\
  \ in the following five years. [This video has been removed] On December 25th, 2012,\
  \ Redditor Lite_It_Up submitted a post titled \"Merry Christmas everybody!\" to\
  \ the /r/AdviceAnimals[1] subreddit, featuring an image macro using a screen capture\
  \ of Oprah accompanied by the caption \"You get an upvote! / and you get an upvote!\
  \ / and you get an upvote! / Everybody gets an upvote!\" (shown below, left). Within\
  \ three months, the post gained upwards of 700 up votes and 10 comments. On January\
  \ 15th, 2013, Redditor BlankRuneWork submitted an image macro to the /r/AdviceAnimals[2]\
  \ subreddit, joking about each of his children getting the flu (shown below, right).\
  \ In the following two months, the post accumulated more than 8,500 up votes and\
  \ 270 comments. Notable Examples Advice Animal As of early April 2013, the \"Oprah\
  \ You Get a Car\" Quickmeme[4] page has received over 3,600 submissions. Related\
  \ Video: Oprah's Bee Giveaway On November 23rd, 2012, the late night talk show Conan\
  \ aired a parody of another Oprah giveaway, in which footage is edited to make it\
  \ appear as if the talk show host is setting a swarm of bees loose on her audience\
  \ (shown below). Search Interest External References [1] Reddit \u2013 Merry Christmas\
  \ Everybody [2] Reddit \u2013 As a father with four young children [3] Oprah \u2013\
  \ Moment #4 Oprah's Car Giveaway [4] Quickmeme \u2013 Oprah You Get a Car youtube\
  \ image macro remix advice animal Share Pin Related Entries 4 total I Love Bread\
  \ Dr. Phil Oprah 2020 Oprah Qanon Sex Trafficking C... Recent Images 33 total View\
  \ All Images Recent Videos 5 total View All Videos Sign up for our Newsletter Load\
  \ 17 Comments Comments 17 total 15 Oprah's \"You Get a Car\" 327,515 5 33 17 Part\
  \ of a series on Oprah Winfrey. [View Related Entries] Updated Dec 23, 2024 at 04:19PM\
  \ EST by LiterallyAustin. Added Apr 05, 2013 at 06:47PM EDT by Don. Like us on Facebook!\
  \ Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to\
  \ view the video gallery, or 'r' to view a random entry. Meme Status Confirmed Year\
  \ 2008 Origin YouTube Tags youtube, image macro, remix, advice animal About Oprah\
  \ You Get a Car is a series of video remixes and advice animal image macros parodying\
  \ an episode of The Oprah Winfrey Show in which the entire studio audience is given\
  \ a free car. Many of the parodies mock the phrase \"you get a car,\" which was\
  \ repeated by the talk show host several times during the episode. Origin On September\
  \ 13th, 2004, Oprah gave away new Pontiac G6 cars to the entire audience attending\
  \ her show (shown below).[3] On May 15th, 2005, the giveaway was parodied in Season\
  \ 1 Episode 12 of the stop motion animated television show Robot Chicken (shown\
  \ below, left). On March 22nd, 2008, YouTuber merese uploaded an animated parody\
  \ of the car giveaway (shown below, right), gaining more than 29,000 views and 90\
  \ comments in the next five years. [This video has been removed] Spread On April\
  \ 24th, 2008, YouTuber Ryazilian uploaded a music remix of the giveaway footage\
  \ (shown below, right), which received over 575,000 views and 900 comments in the\
  \ following five years. [This video has been removed] On December 25th, 2012, Redditor\
  \ Lite_It_Up submitted a post titled \"Merry Christmas everybody!\" to the /r/AdviceAnimals[1]\
  \ subreddit, featuring an image macro using a screen capture of Oprah accompanied\
  \ by the caption \"You get an upvote! / and you get an upvote! / and you get an\
  \ upvote! / Everybody gets an upvote!\" (shown below, left). Within three months,\
  \ the post gained upwards of 700 up votes and 10 comments. On January 15th, 2013,\
  \ Redditor BlankRuneWork submitted an image macro to the /r/AdviceAnimals[2] subreddit,\
  \ joking about each of his children getting the flu (shown below, right). In the\
  \ following two months, the post accumulated more than 8,500 up votes and 270 comments.\
  \ Notable Examples Advice Animal As of early April 2013, the \"Oprah You Get a Car\"\
  \ Quickmeme[4] page has received over 3,600 submissions. Related Video: Oprah's\
  \ Bee Giveaway On November 23rd, 2012, the late night talk show Conan aired a parody\
  \ of another Oprah giveaway, in which footage is edited to make it appear as if\
  \ the talk show host is setting a swarm of bees loose on her audience (shown below).\
  \ Search Interest External References [1] Reddit \u2013 Merry Christmas Everybody\
  \ [2] Reddit \u2013 As a father with four young children [3] Oprah \u2013 Moment\
  \ #4 Oprah's Car Giveaway [4] Quickmeme \u2013 Oprah You Get a Car Related Entries\
  \ 4 total I Love Bread Dr. Phil Oprah 2020 Oprah Qanon Sex Trafficking Conspiracy\
  \ Theory Recent Videos 5 total Tyra Banks - Vaseline Frenzy Oprah's \"You Get a\
  \ Car\" Uploaded by Samba \"Oprah, can I get a car?\" Oprah's \"You Get a Car\"\
  \ Uploaded by Don Wendy Ho - Oprah Winfrey - HO... Oprah's \"You Get a Car\" Uploaded\
  \ by Don BEES!!! Oprah's \"You Get a Car\" Uploaded by Daft Punkjet + Add a Video\
  \ Recent Images 33 total Oprah's \"You Get a Car\" Uploaded by Juan del Rancho Oprah's\
  \ \"You Get a Car\" Uploaded by Mexmaxx Oprah's \"You Get a Car\" Uploaded by elmashojaldra\
  \ Oprah's \"You Get a Car\" Uploaded by Ari Spool Oprah's \"You Get a Car\" Uploaded\
  \ by monkeysrool75 Oprah's \"You Get a Car\" Uploaded by Acconker Oprah's \"You\
  \ Get a Car\" Uploaded by RChamy the Senator Oprah's \"You Get a Car\" Uploaded\
  \ by Gabenus Trollucus Oprah's \"You Get a Car\" Uploaded by seki108 Oprah's \"\
  You Get a Car\" Uploaded by colin13194 Oprah's \"You Get a Car\" Uploaded by Gabenus\
  \ Trollucus Oprah's \"You Get a Car\" Uploaded by Unanimous Delivers + Add an Image\
  \ View All Images Sign up for our Newsletter Top Comments Delete Sensitive Kung\
  \ Fu Cthulhu Apr 05, 2013 at 06:51PM EDT PARTY HARD! PARTY HARD! PARTY HARD! PARTY\
  \ HARD! PARTY HARD! +25 Reply Delete Sensitive chowzburgerz Apr 05, 2013 at 07:57PM\
  \ EDT EVERYBODY GETS A CONFIRM!!!! +24 Reply + Add a Comment Comments (17) Display\
  \ Comments Add a Comment Top Entries This Month Meme Saika Kawakita Smile GIF Event\
  \ Assassination of UnitedHealthcare CEO Person Luigi Mangione UHC CEO Shooter Subculture\
  \ The Ki Sisters Culture Pornography Site Whisper View More Suggest a Change Edit\
  \ History Entry Editors (5) Don Administrator & Meme Daddy The Cute Master :3 Sr.\
  \ Entry Moderator Particle Mare Wolf of Meme Street Brad Digital Archaeologist &\
  \ Treasurer & Pundit & Gallery Housekeeper Y F Digital Archaeologist & Treasurer\
  \ & Media Maid \u25BC + Request Editorship View All Editors Today's Top Image Galleries\
  \ Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress\
  \ 2 The Amazing Digital Circus About Our Story Site Rules Policies and Guidelines\
  \ Credits Contact Meme DB Memes Episodes News Staff Contact Extras! Style Guide\
  \ RSS Feeds"
source: http://knowyourmeme.com/memes/oprah-you-get-a-car
template_id: oprah
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
