name: Oprah You Get a Car
source: http://knowyourmeme.com/memes/oprah-you-get-a-car
keywords:
- everybody gets
- you win
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- Top Line
- Bottom Line
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Oprah You Get a Car is a series of video remixes and advice
  animal image macros parodying an episode of The Oprah Winfrey Show in which the
  entire studio audience is given a free car. Many of the parodies mock the phrase
  "you get a car," which was repeated by the talk show host several times during the
  episode. Origin On September 13th, 2004, Oprah gave away new Pontiac G6 cars to
  the entire audience attending her show (shown below).[3] On May 15th, 2005, the
  giveaway was parodied in Season 1 Episode 12 of the stop motion animated television
  show Robot Chicken (shown below, left). On March 22nd, 2008, YouTuber merese uploaded
  an animated parody of the car giveaway (shown below, right), gaining more than 29,000
  views and 90 comments in the next five years. [This video has been removed] Spread
  On April 24th, 2008, YouTuber Ryazilian uploaded a music remix of the giveaway footage
  (shown below, right), which received over 575,000 views and 900 comments in the
  following five years. [This video has been removed] On December 25th, 2012, Redditor
  Lite_It_Up submitted a post titled "Merry Christmas everybody!" to the /r/AdviceAnimals[1]
  subreddit, featuring an image macro using a screen capture of Oprah accompanied
  by the caption "You get an upvote! / and you get an upvote! / and you get an upvote!
  / Everybody gets an upvote!" (shown below, left). Within three months, the post
  gained upwards of 700 up votes and 10 comments. On January 15th, 2013, Redditor
  BlankRuneWork submitted an image macro to the /r/AdviceAnimals[2] subreddit, joking
  about each of his children getting the flu (shown below, right). In the following
  two months, the post accumulated more than 8,500 up votes and 270 comments. Notable
  Examples Advice Animal As of early April 2013, the "Oprah You Get a Car" Quickmeme[4]
  page has received over 3,600 submissions. Related Video: Oprah''s Bee Giveaway On
  November 23rd, 2012, the late night talk show Conan aired a parody of another Oprah
  giveaway, in which footage is edited to make it appear as if the talk show host
  is setting a swarm of bees loose on her audience (shown below). Search Interest
  External References [1] Reddit – Merry Christmas Everybody [2] Reddit – As a father
  with four young children [3] Oprah – Moment #4 Oprah''s Car Giveaway [4] Quickmeme
  – Oprah You Get a Car'
aside_content: MemeStatusConfirmedYear2008OriginYouTubeTagsyoutube,image macro,remix,advice
  animal
added_at: '2013-04-05T18:47:51-04:00'
