name: One Does Not Simply Walk into Mordor
source: http://knowyourmeme.com/memes/one-does-not-simply-walk-into-mordor
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- one does not simply
- walk into mordor
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About "One Does Not Simply Walk Into Mordor" (snowclone: "One Does
  Not Simply X into Mordor") is a memorable quote from the 2001 fantasy epic film
  Lord of the Rings: The Fellowship of the Ring. Variants of the phrase are often
  used in image macros featuring Mordor, a fictional location from The Lord of the
  Rings franchise, or the character Boromir, who originally says the line in the film.
  Origin Lord of the Rings The phrase “One does not simply walk into Mordor” originates
  from a scene in Peter Jackson’s 2001 film adaption of J.R.R. Tolkien’s Lord of the
  Rings: The Fellowship of the Ring.[1] In the scene, the Council of Elrond reveals
  that an evil ring must be destroyed by being thrown into the fires of Mount Doom,
  a volcano deep in the territory of Mordor. Boromir promptly points out the difficultly
  of the task by saying, “One does not simply walk into Mordor." Elrond: The ring
  cannot be destroyed, Gimli, son of Gloin, by any craft that we here possess. The
  ring was made in the fires of Mount Doom. Only there can it be unmade. The ring
  must be taken deep into Mordor and cast back into the fiery chasm from whence it
  came. One of you must do this. Boromir: One does not simply walk into Mordor. Its
  black gates are guarded by more than just orcs. There is evil there that does not
  sleep. The great eye is ever watchful. It is a barren wasteland, riddled with fire,
  ash, and dust. The very air you breathe is a poisonous fume. Not with ten thousand
  men could you do this. It is folly. As a Snowclone In the "One does not simply X
  into Mordor" snowclone, the word “walk” is typically substituted with another verb
  which is often related to the subject of an image. The variation "One dos not simply
  walk into Y", swaps “Mordor” with another location that has relevance to the situation
  depicted in the image. One of the first instances of this usage in image macro form
  was posted in a Something Awful[2] thread with the caption "One does not simply
  / drive into Mordor" on January 16th, 2004. Spread On May 3rd, 2004, the Something
  Awful image macro was used in a YTMND page titled "Drive Into Mordor".[7] On September
  10th, 2005, a "more cowbell" mashup[8] YTMND was created titled "One does not simply
  cowbell into Mordor," which received over 21,000 views within seven years. On June
  21st, 2006, an image macro with the caption "One does not simply Telnet into Morder"
  (shown below, left) was posted on the Internet humor blog My[confined]Space.[9]
  On February 28th, 2007, an image of Boromir riding a cat with the caption "One does
  not simply / Tank Cat into Mordor" (shown below, right) was posted on the humor
  site I Can Has Cheezburger.[11] Google Maps[14] implemented a reminder that one
  cannot simply walk into Mordor on their walking directions from a Wisconson address
  masked as the Shire to an address masked as Mordor in Illinois.[14] The meme has
  continued to spread on Tumblr[3], Memebase[4], Reddit[5] and Facebook.[6] On August
  2015, the animated television show Gravity Falls referenced the meme in one of its
  episodes. Wherein after the mayoral candidate Stanford Pines answered poorly to
  interviews, he was met with mocked and negative approval. (Instance of the meme
  can be seen at the 0:50 mark.) Notable Examples Search Interest Search for the phrase
  started in December 2005, when a gif of the phrase was circulating the web[12],
  picked up again in October 2006, which may coincide with Rick Santorum explaining
  the Iraq war with a Mordor analogy.[13] External References [1] Something Awful
  – Thread [2] Wikipedia – The Lord of the Rings: The Fellowship of the Ring [3] -
  Tumblr – Tag – One does not simply into Mordor [4] Memebase – Tag – Mordor [5] Reddit
  – Tag – Mordor [6] Facebook via Wayback Machine – One does not simply walk into
  Mordor [7] YTMND – One Does Not Simply Drive Into Mordor… [8] YTMND – One does not
  simply cowbell into Mordor [9] My[confined]Space – One Does Not Simply Walk Into
  Mordor | June 21st, 2006 [10] My[confined]Space – One Does Not Simply Walk Into
  Mordor! | November 2nd, 2006 [11] I Can Has Cheezburger via Wayback Machine – one
  does not simply TANK CAT into Mordor [12] Digg via Wayback Machine – One does not
  simply walk into Mordor [13] Salon- Rick Santorum and the “Eye of Mordor” [14] Google
  Maps – Walking Directions from the Shire to Mordor'
aside_content: 'MemeStatusConfirmedType:Catchphrase,Pop Culture Reference,SnowcloneYear2001OriginLord
  of the Rings: The Fellowship of the RingTagscatchphrase,lotr,fantasy,pop-culture,movie
  quote,walks into mordor,blacklist,pop culture,snowclone,phrasal template,boromir,peter
  jackson,j.r.r. tolkien,stanford pinesAdditional ReferencesDictionary.comEncyclopedia
  DramaticaMeme GeneratorUrban Dictionary'
added_at: '2009-04-12T16:04:28-04:00'
