example:
- one does not simply
- walk into mordor
keywords:
- null
name: One Does Not Simply Walk into Mordor
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "One Does Not Simply Walk Into Mordor | Know Your Meme Sup! You must\
  \ login or signup first! Already a memeber? Login Now! Don't have an account? Sign\
  \ up Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos\
  \ Submit \u2192 Images Trending Most Commented Most Favorited High Score Low Score\
  \ Most Viewed All Templates Upload an Image Articles News Explainers Collections\
  \ Interviews Meme Insider Magazine More Discord Newsletter Episodes Forums Meme\
  \ Store Login Abstract user icon Memes Categories Trending News Images Trending\
  \ Images Videos Trending Videos Editorials Meme Insider Magazine Newsletter Policies\
  \ and Guidelines Meme Store Old site Login Know Your Meme is the property of Literally\
  \ Media \xA92024 Literally Media. All Rights Reserved. This image Of Woman Confidently\
  \ Strolling Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years\
  \ Ago, This Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The\
  \ Anarchy Chess Memes Turns Two Years Old Today Phrase 'The Fridge Protects The\
  \ Snacks' A Growing Favorite Among Pickup Artist Influencers Jamie G, The Bosh British\
  \ Charva, Has Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also\
  \ Trending: Honey Extension Influencer Scam Renegade Raider Copypasta Assassination\
  \ of UnitedHealthcare CEO One Does Not Simply Walk Into Mordor Added 15 years ago\
  \ / Updated about 17 hours ago Confirmed 2,225,733 Part of a series on Lord Of The\
  \ Rings. [View Related Entries] View All 482 Images Navigation About \u2022 Origin\
  \ \u2022 Spread \u2022 Search Interest \u2022 External References \u2022 Recent\
  \ Images \u2022 Recent Videos About \"One Does Not Simply Walk Into Mordor\" (snowclone:\
  \ \"One Does Not Simply X into Mordor\") is a memorable quote from the 2001 fantasy\
  \ epic film Lord of the Rings: The Fellowship of the Ring. Variants of the phrase\
  \ are often used in image macros featuring Mordor, a fictional location from The\
  \ Lord of the Rings franchise, or the character Boromir, who originally says the\
  \ line in the film. Origin Lord of the Rings The phrase \u201COne does not simply\
  \ walk into Mordor\u201D originates from a scene in Peter Jackson\u2019s 2001 film\
  \ adaption of J.R.R. Tolkien\u2019s Lord of the Rings: The Fellowship of the Ring.[1]\
  \ In the scene, the Council of Elrond reveals that an evil ring must be destroyed\
  \ by being thrown into the fires of Mount Doom, a volcano deep in the territory\
  \ of Mordor. Boromir promptly points out the difficultly of the task by saying,\
  \ \u201COne does not simply walk into Mordor.\" Elrond: The ring cannot be destroyed,\
  \ Gimli, son of Gloin, by any craft that we here possess. The ring was made in the\
  \ fires of Mount Doom. Only there can it be unmade. The ring must be taken deep\
  \ into Mordor and cast back into the fiery chasm from whence it came. One of you\
  \ must do this. Boromir: One does not simply walk into Mordor. Its black gates are\
  \ guarded by more than just orcs. There is evil there that does not sleep. The great\
  \ eye is ever watchful. It is a barren wasteland, riddled with fire, ash, and dust.\
  \ The very air you breathe is a poisonous fume. Not with ten thousand men could\
  \ you do this. It is folly. As a Snowclone In the \"One does not simply X into Mordor\"\
  \ snowclone, the word \u201Cwalk\u201D is typically substituted with another verb\
  \ which is often related to the subject of an image. The variation \"One dos not\
  \ simply walk into Y\", swaps \u201CMordor\u201D with another location that has\
  \ relevance to the situation depicted in the image. One of the first instances of\
  \ this usage in image macro form was posted in a Something Awful[2] thread with\
  \ the caption \"One does not simply / drive into Mordor\" on January 16th, 2004.\
  \ Spread On May 3rd, 2004, the Something Awful image macro was used in a YTMND page\
  \ titled \"Drive Into Mordor\".[7] On September 10th, 2005, a \"more cowbell\" mashup[8]\
  \ YTMND was created titled \"One does not simply cowbell into Mordor,\" which received\
  \ over 21,000 views within seven years. On June 21st, 2006, an image macro with\
  \ the caption \"One does not simply Telnet into Morder\" (shown below, left) was\
  \ posted on the Internet humor blog My[confined]Space.[9] On February 28th, 2007,\
  \ an image of Boromir riding a cat with the caption \"One does not simply / Tank\
  \ Cat into Mordor\" (shown below, right) was posted on the humor site I Can Has\
  \ Cheezburger.[11] Google Maps[14] implemented a reminder that one cannot simply\
  \ walk into Mordor on their walking directions from a Wisconson address masked as\
  \ the Shire to an address masked as Mordor in Illinois.[14] The meme has continued\
  \ to spread on Tumblr[3], Memebase[4], Reddit[5] and Facebook.[6] On August 2015,\
  \ the animated television show Gravity Falls referenced the meme in one of its episodes.\
  \ Wherein after the mayoral candidate Stanford Pines answered poorly to interviews,\
  \ he was met with mocked and negative approval. (Instance of the meme can be seen\
  \ at the 0:50 mark.) Notable Examples Search Interest Search for the phrase started\
  \ in December 2005, when a gif of the phrase was circulating the web[12], picked\
  \ up again in October 2006, which may coincide with Rick Santorum explaining the\
  \ Iraq war with a Mordor analogy.[13] External References [1] Something Awful \u2013\
  \ Thread [2] Wikipedia \u2013 The Lord of the Rings: The Fellowship of the Ring\
  \ [3] - Tumblr \u2013 Tag \u2013 One does not simply into Mordor [4] Memebase \u2013\
  \ Tag \u2013 Mordor [5] Reddit \u2013 Tag \u2013 Mordor [6] Facebook via Wayback\
  \ Machine \u2013 One does not simply walk into Mordor [7] YTMND \u2013 One Does\
  \ Not Simply Drive Into Mordor\u2026 [8] YTMND \u2013 One does not simply cowbell\
  \ into Mordor [9] My[confined]Space \u2013 One Does Not Simply Walk Into Mordor\
  \ | June 21st, 2006 [10] My[confined]Space \u2013 One Does Not Simply Walk Into\
  \ Mordor! | November 2nd, 2006 [11] I Can Has Cheezburger via Wayback Machine \u2013\
  \ one does not simply TANK CAT into Mordor [12] Digg via Wayback Machine \u2013\
  \ One does not simply walk into Mordor [13] Salon- Rick Santorum and the \u201C\
  Eye of Mordor\u201D [14] Google Maps \u2013 Walking Directions from the Shire to\
  \ Mordor catchphrase lotr fantasy pop-culture movie quote walks into mordor blacklist\
  \ pop culture snowclone phrasal template boromir peter jackson j.r.r. tolkien stanford\
  \ pines Share Pin Related Entries 41 total Pondering My Orb You Have My Sword, and\
  \ My Bow... They're Taking the Hobbits to... You Shall Not Pass!!! View All Related\
  \ Entries Recent Images 482 total View All Images Recent Videos 34 total View All\
  \ Videos Sign up for our Newsletter Load 53 Comments Comments 53 total 184 One Does\
  \ Not Simply Walk Into Mordor 2,225,735 34 482 53 Part of a series on Lord Of The\
  \ Rings. [View Related Entries] Updated Dec 23, 2024 at 04:00PM EST by LiterallyAustin.\
  \ Added Apr 12, 2009 at 04:04PM EDT by Captain Blubber. Like us on Facebook! Like\
  \ 1.8M Share Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view\
  \ the video gallery, or 'r' to view a random entry. Meme Status Confirmed Type:\
  \ Catchphrase, Pop Culture Reference, Snowclone Year 2001 Origin Lord of the Rings:\
  \ The Fellowship of the Ring Tags catchphrase, lotr, fantasy, pop-culture, movie\
  \ quote, walks into mordor, blacklist, pop culture, snowclone, phrasal template,\
  \ boromir, peter jackson, j.r.r. tolkien, stanford pines Additional References Dictionary.com\
  \ Encyclopedia Dramatica Meme Generator Urban Dictionary About \"One Does Not Simply\
  \ Walk Into Mordor\" (snowclone: \"One Does Not Simply X into Mordor\") is a memorable\
  \ quote from the 2001 fantasy epic film Lord of the Rings: The Fellowship of the\
  \ Ring. Variants of the phrase are often used in image macros featuring Mordor,\
  \ a fictional location from The Lord of the Rings franchise, or the character Boromir,\
  \ who originally says the line in the film. Origin Lord of the Rings The phrase\
  \ \u201COne does not simply walk into Mordor\u201D originates from a scene in Peter\
  \ Jackson\u2019s 2001 film adaption of J.R.R. Tolkien\u2019s Lord of the Rings:\
  \ The Fellowship of the Ring.[1] In the scene, the Council of Elrond reveals that\
  \ an evil ring must be destroyed by being thrown into the fires of Mount Doom, a\
  \ volcano deep in the territory of Mordor. Boromir promptly points out the difficultly\
  \ of the task by saying, \u201COne does not simply walk into Mordor.\" Elrond: The\
  \ ring cannot be destroyed, Gimli, son of Gloin, by any craft that we here possess.\
  \ The ring was made in the fires of Mount Doom. Only there can it be unmade. The\
  \ ring must be taken deep into Mordor and cast back into the fiery chasm from whence\
  \ it came. One of you must do this. Boromir: One does not simply walk into Mordor.\
  \ Its black gates are guarded by more than just orcs. There is evil there that does\
  \ not sleep. The great eye is ever watchful. It is a barren wasteland, riddled with\
  \ fire, ash, and dust. The very air you breathe is a poisonous fume. Not with ten\
  \ thousand men could you do this. It is folly. As a Snowclone In the \"One does\
  \ not simply X into Mordor\" snowclone, the word \u201Cwalk\u201D is typically substituted\
  \ with another verb which is often related to the subject of an image. The variation\
  \ \"One dos not simply walk into Y\", swaps \u201CMordor\u201D with another location\
  \ that has relevance to the situation depicted in the image. One of the first instances\
  \ of this usage in image macro form was posted in a Something Awful[2] thread with\
  \ the caption \"One does not simply / drive into Mordor\" on January 16th, 2004.\
  \ Spread On May 3rd, 2004, the Something Awful image macro was used in a YTMND page\
  \ titled \"Drive Into Mordor\".[7] On September 10th, 2005, a \"more cowbell\" mashup[8]\
  \ YTMND was created titled \"One does not simply cowbell into Mordor,\" which received\
  \ over 21,000 views within seven years. On June 21st, 2006, an image macro with\
  \ the caption \"One does not simply Telnet into Morder\" (shown below, left) was\
  \ posted on the Internet humor blog My[confined]Space.[9] On February 28th, 2007,\
  \ an image of Boromir riding a cat with the caption \"One does not simply / Tank\
  \ Cat into Mordor\" (shown below, right) was posted on the humor site I Can Has\
  \ Cheezburger.[11] Google Maps[14] implemented a reminder that one cannot simply\
  \ walk into Mordor on their walking directions from a Wisconson address masked as\
  \ the Shire to an address masked as Mordor in Illinois.[14] The meme has continued\
  \ to spread on Tumblr[3], Memebase[4], Reddit[5] and Facebook.[6] On August 2015,\
  \ the animated television show Gravity Falls referenced the meme in one of its episodes.\
  \ Wherein after the mayoral candidate Stanford Pines answered poorly to interviews,\
  \ he was met with mocked and negative approval. (Instance of the meme can be seen\
  \ at the 0:50 mark.) Notable Examples Search Interest Search for the phrase started\
  \ in December 2005, when a gif of the phrase was circulating the web[12], picked\
  \ up again in October 2006, which may coincide with Rick Santorum explaining the\
  \ Iraq war with a Mordor analogy.[13] External References [1] Something Awful \u2013\
  \ Thread [2] Wikipedia \u2013 The Lord of the Rings: The Fellowship of the Ring\
  \ [3] - Tumblr \u2013 Tag \u2013 One does not simply into Mordor [4] Memebase \u2013\
  \ Tag \u2013 Mordor [5] Reddit \u2013 Tag \u2013 Mordor [6] Facebook via Wayback\
  \ Machine \u2013 One does not simply walk into Mordor [7] YTMND \u2013 One Does\
  \ Not Simply Drive Into Mordor\u2026 [8] YTMND \u2013 One does not simply cowbell\
  \ into Mordor [9] My[confined]Space \u2013 One Does Not Simply Walk Into Mordor\
  \ | June 21st, 2006 [10] My[confined]Space \u2013 One Does Not Simply Walk Into\
  \ Mordor! | November 2nd, 2006 [11] I Can Has Cheezburger via Wayback Machine \u2013\
  \ one does not simply TANK CAT into Mordor [12] Digg via Wayback Machine \u2013\
  \ One does not simply walk into Mordor [13] Salon- Rick Santorum and the \u201C\
  Eye of Mordor\u201D [14] Google Maps \u2013 Walking Directions from the Shire to\
  \ Mordor Related Entries 41 total Pondering My Orb You Have My Sword, and My Bow,\
  \ and My Axe They're Taking the Hobbits to Isengard You Shall Not Pass!!! All Right\
  \ Then, Keep Your Secrets Figwit You Have No Power Here! What Do Your Elf Eyes See?\
  \ Gandalf's \"So It Begins\" Viggo Mortensen Broke His Toe In 'The Two Towers' #Orcposting\
  \ I'm Going On An Adventure! View All Related Entries Recent Videos 34 total One\
  \ does not simply gank Sona One Does Not Simply Walk Into... Uploaded by shevyrolet\
  \ Funny Memes| One Does Not Simply One Does Not Simply Walk Into... Uploaded by\
  \ shevyrolet How Will the Hyperloop Levitate? One Does Not Simply Walk Into... Uploaded\
  \ by shevyrolet One does not simply... One Does Not Simply Walk Into... Uploaded\
  \ by shevyrolet FRIENDZONE - One Does Not Simply One Does Not Simply Walk Into...\
  \ Uploaded by shevyrolet \"ONE DOES NOT SIMPLY WALK INT... One Does Not Simply Walk\
  \ Into... Uploaded by shevyrolet One does not simply walk into... One Does Not Simply\
  \ Walk Into... Uploaded by shevyrolet \"One does not simply walk int... One Does\
  \ Not Simply Walk Into... Uploaded by shevyrolet + Add a Video View All Videos Recent\
  \ Images 482 total One Does Not Simply Walk Into... Uploaded by greta.elisif One\
  \ Does Not Simply Walk Into... Uploaded by Dorian Mode One Does Not Simply Walk\
  \ Into... Uploaded by lil skooters fan One Does Not Simply Walk Into... Uploaded\
  \ by Zach One Does Not Simply Walk Into... Uploaded by Dry Ice One Does Not Simply\
  \ Walk Into... Uploaded by andcallmeshirley One Does Not Simply Walk Into... Uploaded\
  \ by funnyfaceking One Does Not Simply Walk Into... Uploaded by Mike One Does Not\
  \ Simply Walk Into... Uploaded by Mike One Does Not Simply Walk Into... Uploaded\
  \ by Mike One Does Not Simply Walk Into... Uploaded by Mike One Does Not Simply\
  \ Walk Into... Uploaded by OurDeerLeader + Add an Image View All Images Sign up\
  \ for our Newsletter Top Comments Delete Sensitive Realsorceror May 21, 2012 at\
  \ 11:12PM EDT It took this long to confirm? I guess\u2026.one does not simply confirm\
  \ this meme. +26 Reply Delete Sensitive Cyber6x Moderator Dec 10, 2011 at 08:41AM\
  \ EST Mfw I got this front-paged \u2013 +21 Reply + Add a Comment Comments (53)\
  \ Display Comments Add a Comment Top Entries This Month Meme Saika Kawakita Smile\
  \ GIF Event Assassination of UnitedHealthcare CEO Person Luigi Mangione UHC CEO\
  \ Shooter Subculture The Ki Sisters Culture Pornography Site Whisper View More Suggest\
  \ a Change Edit History Entry Editors (16) Captain Blubber Database Moderator &\
  \ Tikibar Management Chris Menning Digital Archaeologist & Archivist & Pundit &\
  \ Early Adopter (#8) Tomberry Database Moderator & French Specialist & Pony Hater\
  \ Don Administrator & Meme Daddy Brad Digital Archaeologist & Treasurer & Pundit\
  \ & Gallery Housekeeper RandomMan Database Moderator & God Tier Swag & Protip Advisor\
  \ & Karma Tycoon & Meme Boi Cyber6x Database Moderator & Midnight Channeler amanda\
  \ b. Meme Librarian Z. Database Moderator & Rage Comicologist Ricenburg Entry Moderator\
  \ & Tumblrologist SabrinaTibbetts Memepuff Y F Digital Archaeologist & Treasurer\
  \ & Media Maid andcallmeshirley Digital Archaeologist & Treasurer & Collection Butler\
  \ Kevinvq2 Sr. Researcher & Scrapbooker & Media Chauffeur shevyrolet Digital Archaeologist\
  \ & Treasurer & Media Bus Boy Philipp Memesplainer \u25BC + Request Editorship View\
  \ All Editors Today's Top Image Galleries Assassination of UnitedHealthcare CEO\
  \ Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing Digital Circus About\
  \ Our Story Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes\
  \ News Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/one-does-not-simply-walk-into-mordor
template_id: mordor
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
