name: See? Nobody Cares
source: http://knowyourmeme.com/memes/see-nobody-cares
keywords:
- Jurassic Park
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.2
  stop: 0.55
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.65
  stop: 1.0
example:
- we've got dodgson here!
- see? nobody cares
overlay:
- center_x: 0.25
  center_y: 0.2
  angle: 0.0
  scale: 0.2
scraped_content: 'About "See? Nobody Cares" is a catchphrase uttered by character
  Dennis Nedry in a dialogue scene from the 1993 science-fiction film Jurassic Park.
  On the Internet, the phrase has been frequently used as a reaction image to convey
  indifference or apathy towards someone soliciting unwarranted attention. Origin
  The memorable quote was originally featured in a dialogue segment from Jurassic
  Park wherein park employee and computer programmer Dennis Nedry (played by Wayne
  Knight) teases the head of research lab Lew Dodgson (played by Cameron Thor) for
  wearing a disguise while meeting at the terrace of a restaurant. A clip of the scene
  was uploaded to YouTube on July 11th, 2009 (shown below). Dennis Nedry: [waving]
  "Dodgson!" Lew Dodgson: [sitting down] "You shouldn''t use my name." Dennis Nedry:
  [loudly] "Dodgson, Dodgson, we''ve got Dodgson here! Nobody cares. Nice hat. What
  are you trying to look like, a secret agent?" On March 13th, 2007, the earliest
  known online parody of the scene was uploaded to YTMND user keatonkeaton999 in a
  page titled "Dodgson (fun times mix),"[7] which garnered nearly 180,000 views over
  the next seven years. Spread Between 2007 and 2009, more than a dozen additional
  YTMND pages[8] featuring Dennis Nedry''s quote were submitted to the site, though
  none of them were able to live up to the popularity of the original remix. Then
  on November 25th, 2012, a two-pane image macro template depicting the dialogue scene
  was submitted to Memegenerator[1], where it went on to spawn more than 50,000 variations,
  as of December 2014, during which the rhetorical question "See?" was added for additional
  emphasis. In 2013, the series continued to proliferate through a number of other
  image macro generator sites, including Quickmeme [2] and Imgflip[4], with several
  notable instances making appearances on WeKnowMeme[5], MemeCenter[6] and Car-memes.com.[3]
  Notable Examples Template Search Interest External References [1] Memegenerator
  – See? Nobody Cares [2] Quickmeme – See? Nobody Cares meme [3] Car-memes.com – Jurassic
  Park Nobody Cares Meme [4] Imgflip – See Nobody Cares [5] WeKnowMemes – See Nobody
  Cares [6] Memecenter – Nobody Cares [7] YTMND – Dodgson [8] YTMND – Search results
  for ''Dodgson'''
aside_content: MemeStatusConfirmedYear2012Originmemegenerator.netTagsimage macro,see,memegenerator,cares,nobody,advice
  animal,jurassic park,reaction image,lew dodgson,cameron thor,keatonkeaton999,wayne
  knightAdditional ReferencesMeme Generator
added_at: '2014-12-12T12:47:44-05:00'
