example:
- we've got dodgson here!
- see? nobody cares
keywords:
- Jurassic Park
name: See? Nobody Cares
overlay:
- angle: 0.0
  center_x: 0.25
  center_y: 0.2
  scale: 0.2
scraped_content: "See? Nobody Cares | Know Your Meme Hi! You must login or signup\
  \ first! Already a memeber? Login Now! Don't have an account? Sign up Now! Meme\
  \ Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO See? Nobody Cares Added 10 years ago / Updated 8 days ago Confirmed 159,540\
  \ Part of a series on Jurassic Park. [View Related Entries] View All 51 Images Navigation\
  \ About \u2022 Origin \u2022 Spread \u2022 Notable Examples \u2022 Template \u2022\
  \ Search Interest \u2022 External References \u2022 Recent Images About \"See? Nobody\
  \ Cares\" is a catchphrase uttered by character Dennis Nedry in a dialogue scene\
  \ from the 1993 science-fiction film Jurassic Park. On the Internet, the phrase\
  \ has been frequently used as a reaction image to convey indifference or apathy\
  \ towards someone soliciting unwarranted attention. Origin The memorable quote was\
  \ originally featured in a dialogue segment from Jurassic Park wherein park employee\
  \ and computer programmer Dennis Nedry (played by Wayne Knight) teases the head\
  \ of research lab Lew Dodgson (played by Cameron Thor) for wearing a disguise while\
  \ meeting at the terrace of a restaurant. A clip of the scene was uploaded to YouTube\
  \ on July 11th, 2009 (shown below). Dennis Nedry: [waving] \"Dodgson!\" Lew Dodgson:\
  \ [sitting down] \"You shouldn't use my name.\" Dennis Nedry: [loudly] \"Dodgson,\
  \ Dodgson, we've got Dodgson here! Nobody cares. Nice hat. What are you trying to\
  \ look like, a secret agent?\" On March 13th, 2007, the earliest known online parody\
  \ of the scene was uploaded to YTMND user keatonkeaton999 in a page titled \"Dodgson\
  \ (fun times mix),\"[7] which garnered nearly 180,000 views over the next seven\
  \ years. Spread Between 2007 and 2009, more than a dozen additional YTMND pages[8]\
  \ featuring Dennis Nedry's quote were submitted to the site, though none of them\
  \ were able to live up to the popularity of the original remix. Then on November\
  \ 25th, 2012, a two-pane image macro template depicting the dialogue scene was submitted\
  \ to Memegenerator[1], where it went on to spawn more than 50,000 variations, as\
  \ of December 2014, during which the rhetorical question \"See?\" was added for\
  \ additional emphasis. In 2013, the series continued to proliferate through a number\
  \ of other image macro generator sites, including Quickmeme [2] and Imgflip[4],\
  \ with several notable instances making appearances on WeKnowMeme[5], MemeCenter[6]\
  \ and Car-memes.com.[3] Notable Examples Template Search Interest External References\
  \ [1] Memegenerator \u2013 See? Nobody Cares [2] Quickmeme \u2013 See? Nobody Cares\
  \ meme [3] Car-memes.com \u2013 Jurassic Park Nobody Cares Meme [4] Imgflip \u2013\
  \ See Nobody Cares [5] WeKnowMemes \u2013 See Nobody Cares [6] Memecenter \u2013\
  \ Nobody Cares [7] YTMND \u2013 Dodgson [8] YTMND \u2013 Search results for 'Dodgson'\
  \ image macro see memegenerator cares nobody advice animal jurassic park reaction\
  \ image lew dodgson cameron thor keatonkeaton999 wayne knight Share Pin Related\
  \ Entries 11 total Clever Girl Holy Shit It's a Dinosaur! Life Finds a Way Your\
  \ Scientists Were So Preoc... View All Related Entries Recent Images 51 total View\
  \ All Images Recent Videos 0 total There are no recent videos. Sign up for our Newsletter\
  \ Load 27 Comments Comments 27 total 53 See? Nobody Cares 159,540 0 51 27 Part of\
  \ a series on Jurassic Park. [View Related Entries] Updated Dec 15, 2024 at 07:13PM\
  \ EST by LiterallyAustin. Added Dec 12, 2014 at 12:47PM EST by Tomberry. Like us\
  \ on Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the image gallery,\
  \ 'v' to view the video gallery, or 'r' to view a random entry. Meme Status Confirmed\
  \ Year 2012 Origin memegenerator.net Tags image macro, see, memegenerator, cares,\
  \ nobody, advice animal, jurassic park, reaction image, lew dodgson, cameron thor,\
  \ keatonkeaton999, wayne knight Additional References Meme Generator About \"See?\
  \ Nobody Cares\" is a catchphrase uttered by character Dennis Nedry in a dialogue\
  \ scene from the 1993 science-fiction film Jurassic Park. On the Internet, the phrase\
  \ has been frequently used as a reaction image to convey indifference or apathy\
  \ towards someone soliciting unwarranted attention. Origin The memorable quote was\
  \ originally featured in a dialogue segment from Jurassic Park wherein park employee\
  \ and computer programmer Dennis Nedry (played by Wayne Knight) teases the head\
  \ of research lab Lew Dodgson (played by Cameron Thor) for wearing a disguise while\
  \ meeting at the terrace of a restaurant. A clip of the scene was uploaded to YouTube\
  \ on July 11th, 2009 (shown below). Dennis Nedry: [waving] \"Dodgson!\" Lew Dodgson:\
  \ [sitting down] \"You shouldn't use my name.\" Dennis Nedry: [loudly] \"Dodgson,\
  \ Dodgson, we've got Dodgson here! Nobody cares. Nice hat. What are you trying to\
  \ look like, a secret agent?\" On March 13th, 2007, the earliest known online parody\
  \ of the scene was uploaded to YTMND user keatonkeaton999 in a page titled \"Dodgson\
  \ (fun times mix),\"[7] which garnered nearly 180,000 views over the next seven\
  \ years. Spread Between 2007 and 2009, more than a dozen additional YTMND pages[8]\
  \ featuring Dennis Nedry's quote were submitted to the site, though none of them\
  \ were able to live up to the popularity of the original remix. Then on November\
  \ 25th, 2012, a two-pane image macro template depicting the dialogue scene was submitted\
  \ to Memegenerator[1], where it went on to spawn more than 50,000 variations, as\
  \ of December 2014, during which the rhetorical question \"See?\" was added for\
  \ additional emphasis. In 2013, the series continued to proliferate through a number\
  \ of other image macro generator sites, including Quickmeme [2] and Imgflip[4],\
  \ with several notable instances making appearances on WeKnowMeme[5], MemeCenter[6]\
  \ and Car-memes.com.[3] Notable Examples Template Search Interest External References\
  \ [1] Memegenerator \u2013 See? Nobody Cares [2] Quickmeme \u2013 See? Nobody Cares\
  \ meme [3] Car-memes.com \u2013 Jurassic Park Nobody Cares Meme [4] Imgflip \u2013\
  \ See Nobody Cares [5] WeKnowMemes \u2013 See Nobody Cares [6] Memecenter \u2013\
  \ Nobody Cares [7] YTMND \u2013 Dodgson [8] YTMND \u2013 Search results for 'Dodgson'\
  \ Related Entries 11 total Clever Girl Holy Shit It's a Dinosaur! Life Finds a Way\
  \ Your Scientists Were So Preoccupied With Whether Or Not They Could, They Didn\u2019\
  t Stop To Think If They Should You Did It. The Crazy Son of a Bitch, You Did It\
  \ Callese Viejo Lesbiano Prattkeeping #BuildABetterFakeTheropod Steven Spielberg\
  \ Triceratops Photo Controversy / Triceratops Poacher Hoax Jurassic Park Logo Parodies\
  \ Jurassic World: Dominion Asks A Single Question Recent Videos There are no videos\
  \ currently available. + Add a Video Recent Images 51 total See? Nobody Cares Uploaded\
  \ by Nyazilla See? Nobody Cares Uploaded by Y F See? Nobody Cares Uploaded by Triumph101\
  \ See? Nobody Cares Uploaded by elmashojaldra See? Nobody Cares Uploaded by Y F\
  \ See? Nobody Cares Uploaded by Sachin X Deadpool See? Nobody Cares Uploaded by\
  \ Matt See? Nobody Cares Uploaded by Reddit Moments See? Nobody Cares Uploaded by\
  \ Private Mold See? Nobody Cares Uploaded by Emperor Palpitoad See? Nobody Cares\
  \ Uploaded by gaboman See? Nobody Cares Uploaded by Abodos + Add an Image View All\
  \ Images Sign up for our Newsletter Top Comments Delete Sensitive The that was easy\
  \ button Dec 12, 2014 at 01:27PM EST Hey everybody! We got a non Don meme over here!\
  \ Holy shit a lot of people care. +87 Reply Delete Sensitive Tomberry Moderator\
  \ Dec 12, 2014 at 12:49PM EST You expected Don to meme you on this time? Too bad,\
  \ it was me. +26 Reply + Add a Comment Comments (27) Display Comments Add a Comment\
  \ Top Entries This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (5) Tomberry\
  \ Database Moderator & French Specialist & Pony Hater Particle Mare Wolf of Meme\
  \ Street Brad Digital Archaeologist & Treasurer & Pundit & Gallery Housekeeper Z.\
  \ Database Moderator & Rage Comicologist Y F Digital Archaeologist & Treasurer &\
  \ Media Maid \u25BC + Request Editorship View All Editors Today's Top Image Galleries\
  \ Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress\
  \ 2 The Amazing Digital Circus About Our Story Site Rules Policies and Guidelines\
  \ Credits Contact Meme DB Memes Episodes News Staff Contact Extras! Style Guide\
  \ RSS Feeds"
source: http://knowyourmeme.com/memes/see-nobody-cares
template_id: dodgson
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.2
  stop: 0.55
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.65
  stop: 1.0
  style: upper
text_zones: 2
