example:
- y u no
- use this meme!?
keywords:
- null
name: Y U NO Guy
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "\"Y U NO\" Guy | Know Your Meme Greetings! You must login or signup\
  \ first! Already a memeber? Login Now! Don't have an account? Sign up Now! Meme\
  \ Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO \"Y U NO\" Guy Added 14 years ago / Updated about 16 hours ago Confirmed 5,056,096\
  \ Part of a series on Rage Comics. [View Related Entries] View All 924 Images Navigation\
  \ About \u2022 Origin \u2022 Spread & Popularity \u2022 External References \u2022\
  \ Recent Images \u2022 Recent Videos About \"Y U NO\" Guy (also known as \"Y U No\
  \ [X]?\") is an image macro series using SMS shorthands and carefree grammar as\
  \ a way to bring someone's attention on a particular subject or issue. The unique\
  \ facial expression worn by stick-figure character is believed to have been traced\
  \ from the Japanese sci-fi manga / anime series Gantz.[1] Origin The character's\
  \ facial expression, full of frustration and rage, can be found in Gantz' Chapter\
  \ 55: Naked King (\u88F8\u306E\u738B\u69D8), originally released in February 2002\
  \ and the English translation in June 2009. Click on the image for the full-sized\
  \ scan: Since the release of English translation, the Gantz image have been reportedly\
  \ traced by fans and circulating around 4chan imageboards prior to its adaptation\
  \ in the \"Y U NO\" series. Original Instance However, the original instance with\
  \ the \"Y U NO\" phrasal template was first posted via LOLTumblrWallpapers, which\
  \ gained over 10,000 reblogs & likes on Tumblr.[2] Set to a beige/light brownish\
  \ background with the Gantz character placed in center, the image macro read: \"\
  I TXT U, Y U NO TXT BAK!?\" During the process of its viral spread, an exploitable\
  \ version was uploaded onto MemeGenerator, spawning dozens of derivative images\
  \ based on the following formulaic sentence: \"(X, subject noun), <font color= cccccc\
  \ >[WH]Y <font color= cccccc >[YO]U NO (Y, verb)?\". Exploitable Spread & Popularity\
  \ In the span of few weeks, Tumblr and Meme Generator have gathered up a sizable\
  \ collection of the macro series: either as the image, or in text form without the\
  \ face. It has been also featured on FunnyJunk and other culture-related blogs.\
  \ The meme has been also referred to as \"TXT BAK\" or \"Y U NO?\" the internet.\
  \ It also has its own \"plz\" account at DeviantART [3] so that users can create\
  \ their own \"Y U NO TROLL\" in comments and journals without having to upload an\
  \ image macro each time. The phrase has been also used in YouTube comments and Omegle\
  \ chatrooms. Y U NO has also been recently put into advertisements on billboards\
  \ and magazines, such as a German print ad for the videogame Driver San Francisco[5]\
  \ and Hipchat. It has also been used on signs in Lybia and other places, asking\
  \ their government: Y U NO!?. External References [1] Wikipedia \u2013 Gantz [2]\
  \ Tumblr \u2013 \"LOLTumblrWallpapers\" (Deleted by Tumblr Staff 01/23/13 due to\
  \ the blog's owner being suspended without warning.) [3] Deviant Art \u2013 Y-U-NOplz\
  \ [4] Memebase \u2013 Y U No Guy [5] Zockwork Orange \u2013 Car Y U No Drive Fast\
  \ image macro catchphrase tumblr y u no txt bak rage guy Share Pin Related Entries\
  \ 49 total Forever Alone Me Gusta Yao Ming Face / Bitch Please NO. Rage Face View\
  \ All Related Entries Recent Images 924 total View All Images Recent Videos 10 total\
  \ View All Videos Sign up for our Newsletter Load 138 Comments Comments 138 total\
  \ 269 \"Y U NO\" Guy 5,056,107 10 924 138 Part of a series on Rage Comics. [View\
  \ Related Entries] Updated Dec 23, 2024 at 04:05PM EST by LiterallyAustin. Added\
  \ Oct 01, 2010 at 04:06AM EDT by Actual Agnes Oblige. Like us on Facebook! Like\
  \ 1.8M Share Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view\
  \ the video gallery, or 'r' to view a random entry. Meme Status Confirmed Type:\
  \ Character Year 2010 Origin Tumblr Tags image macro, catchphrase, tumblr, y u no,\
  \ txt bak, rage guy About \"Y U NO\" Guy (also known as \"Y U No [X]?\") is an image\
  \ macro series using SMS shorthands and carefree grammar as a way to bring someone's\
  \ attention on a particular subject or issue. The unique facial expression worn\
  \ by stick-figure character is believed to have been traced from the Japanese sci-fi\
  \ manga / anime series Gantz.[1] Origin The character's facial expression, full\
  \ of frustration and rage, can be found in Gantz' Chapter 55: Naked King (\u88F8\
  \u306E\u738B\u69D8), originally released in February 2002 and the English translation\
  \ in June 2009. Click on the image for the full-sized scan: Since the release of\
  \ English translation, the Gantz image have been reportedly traced by fans and circulating\
  \ around 4chan imageboards prior to its adaptation in the \"Y U NO\" series. Original\
  \ Instance However, the original instance with the \"Y U NO\" phrasal template was\
  \ first posted via LOLTumblrWallpapers, which gained over 10,000 reblogs & likes\
  \ on Tumblr.[2] Set to a beige/light brownish background with the Gantz character\
  \ placed in center, the image macro read: \"I TXT U, Y U NO TXT BAK!?\" During the\
  \ process of its viral spread, an exploitable version was uploaded onto MemeGenerator,\
  \ spawning dozens of derivative images based on the following formulaic sentence:\
  \ \"(X, subject noun), <font color= cccccc >[WH]Y <font color= cccccc >[YO]U NO\
  \ (Y, verb)?\". Exploitable Spread & Popularity In the span of few weeks, Tumblr\
  \ and Meme Generator have gathered up a sizable collection of the macro series:\
  \ either as the image, or in text form without the face. It has been also featured\
  \ on FunnyJunk and other culture-related blogs. The meme has been also referred\
  \ to as \"TXT BAK\" or \"Y U NO?\" the internet. It also has its own \"plz\" account\
  \ at DeviantART [3] so that users can create their own \"Y U NO TROLL\" in comments\
  \ and journals without having to upload an image macro each time. The phrase has\
  \ been also used in YouTube comments and Omegle chatrooms. Y U NO has also been\
  \ recently put into advertisements on billboards and magazines, such as a German\
  \ print ad for the videogame Driver San Francisco[5] and Hipchat. It has also been\
  \ used on signs in Lybia and other places, asking their government: Y U NO!?. External\
  \ References [1] Wikipedia \u2013 Gantz [2] Tumblr \u2013 \"LOLTumblrWallpapers\"\
  \ (Deleted by Tumblr Staff 01/23/13 due to the blog's owner being suspended without\
  \ warning.) [3] Deviant Art \u2013 Y-U-NOplz [4] Memebase \u2013 Y U No Guy [5]\
  \ Zockwork Orange \u2013 Car Y U No Drive Fast Related Entries 49 total Forever\
  \ Alone Me Gusta Yao Ming Face / Bitch Please NO. Rage Face Okay Guy Fuck Yea Rage\
  \ Guy (FFFFFUUUUUUUU-) Oh Crap / OMG Rage Face Are You Serious Face / Seriously?\
  \ Cereal Guy Are You Fucking Kidding Me? Sweet Jesus Face View All Related Entries\
  \ Recent Videos 10 total How To Jailbreak A iPhone 5 \"Y U NO\" Guy Uploaded by\
  \ cinematicfruits Y U NO \"Y U NO\" Guy Uploaded by Abby of Many Fandoms Game of\
  \ Trolls (Memes everywh... \"Y U NO\" Guy Uploaded by alandias2 Y U NO ?? \"Y U\
  \ NO\" Guy Uploaded by JamesCMarshall yuno \"Y U NO\" Guy Uploaded by gionetz What\
  \ a Medick... \"Y U NO\" Guy Uploaded by Oclaf The GAG Quartet - le Internet...\
  \ \"Y U NO\" Guy Uploaded by Actual Agnes Oblige Rage Quit - Mutant Storm: Rel...\
  \ \"Y U NO\" Guy Uploaded by GoodFella_Tudela + Add a Video View All Videos Recent\
  \ Images 924 total \"Y U NO\" Guy Uploaded by Classic Rage Meme Rook 96 \"Y U NO\"\
  \ Guy Uploaded by Classic Rage Meme Rook 96 \"Y U NO\" Guy Uploaded by Classic Rage\
  \ Meme Rook 96 \"Y U NO\" Guy Uploaded by Classic Rage Meme Rook 96 \"Y U NO\" Guy\
  \ Uploaded by Classic Rage Meme Rook 96 \"Y U NO\" Guy Uploaded by Rebecca Rhodes\
  \ \"Y U NO\" Guy Uploaded by MasterChi \"Y U NO\" Guy Uploaded by Jedolf Chrisler\
  \ \"Y U NO\" Guy Uploaded by Amongus \"Y U NO\" Guy Uploaded by #Star#Smile \"Y\
  \ U NO\" Guy Uploaded by TheMemoryOfTrees \"Y U NO\" Guy Uploaded by shadow_lepus\
  \ + Add an Image View All Images Sign up for our Newsletter Top Comments Delete\
  \ Sensitive JackJelloman Aug 09, 2011 at 04:22PM EDT MOAR PEOPLE NEED THIS------\u2192\
  \ \u10DA(\u0CA0\u76CA\u0CA0\u10DA +15 Reply Delete Sensitive Better_MixMaster Aug\
  \ 10, 2011 at 12:29AM EDT Its not cancer, house said so Y U NO LIKE PONIES +12 Reply\
  \ + Add a Comment Comments (138) Display Comments Add a Comment Top Entries This\
  \ Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare CEO\
  \ Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (7) Actual\
  \ Agnes Oblige Sleuth Tomberry Database Moderator & French Specialist & Pony Hater\
  \ stephenell69 Deactivated Brad Digital Archaeologist & Treasurer & Pundit & Gallery\
  \ Housekeeper Don Administrator & Meme Daddy amanda b. Meme Librarian SabrinaTibbetts\
  \ Memepuff \u25BC + Request Editorship View All Editors Today's Top Image Galleries\
  \ Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress\
  \ 2 The Amazing Digital Circus About Our Story Site Rules Policies and Guidelines\
  \ Credits Contact Meme DB Memes Episodes News Staff Contact Extras! Style Guide\
  \ RSS Feeds"
source: http://knowyourmeme.com/memes/y-u-no-guy
template_id: yuno
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
