name: Y U NO Guy
source: http://knowyourmeme.com/memes/y-u-no-guy
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- y u no
- use this meme!?
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About "Y U NO" Guy (also known as "Y U No [X]?") is an image macro
  series using SMS shorthands and carefree grammar as a way to bring someone''s attention
  on a particular subject or issue. The unique facial expression worn by stick-figure
  character is believed to have been traced from the Japanese sci-fi manga / anime
  series Gantz.[1] Origin The character''s facial expression, full of frustration
  and rage, can be found in Gantz'' Chapter 55: Naked King (裸の王様), originally released
  in February 2002 and the English translation in June 2009. Click on the image for
  the full-sized scan: Since the release of English translation, the Gantz image have
  been reportedly traced by fans and circulating around 4chan imageboards prior to
  its adaptation in the "Y U NO" series. Original Instance However, the original instance
  with the "Y U NO" phrasal template was first posted via LOLTumblrWallpapers, which
  gained over 10,000 reblogs & likes on Tumblr.[2] Set to a beige/light brownish background
  with the Gantz character placed in center, the image macro read: "I TXT U, Y U NO
  TXT BAK!?" During the process of its viral spread, an exploitable version was uploaded
  onto MemeGenerator, spawning dozens of derivative images based on the following
  formulaic sentence: "(X, subject noun), <font color= cccccc >[WH]Y <font color=
  cccccc >[YO]U NO (Y, verb)?". Exploitable Spread & Popularity In the span of few
  weeks, Tumblr and Meme Generator have gathered up a sizable collection of the macro
  series: either as the image, or in text form without the face. It has been also
  featured on FunnyJunk and other culture-related blogs. The meme has been also referred
  to as "TXT BAK" or "Y U NO?" the internet. It also has its own "plz" account at
  DeviantART [3] so that users can create their own "Y U NO TROLL" in comments and
  journals without having to upload an image macro each time. The phrase has been
  also used in YouTube comments and Omegle chatrooms. Y U NO has also been recently
  put into advertisements on billboards and magazines, such as a German print ad for
  the videogame Driver San Francisco[5] and Hipchat. It has also been used on signs
  in Lybia and other places, asking their government: Y U NO!?. External References
  [1] Wikipedia – Gantz [2] Tumblr – "LOLTumblrWallpapers" (Deleted by Tumblr Staff
  01/23/13 due to the blog''s owner being suspended without warning.) [3] Deviant
  Art – Y-U-NOplz [4] Memebase – Y U No Guy [5] Zockwork Orange – Car Y U No Drive
  Fast'
aside_content: MemeStatusConfirmedType:CharacterYear2010OriginTumblrTagsimage macro,catchphrase,tumblr,y
  u no,txt bak,rage guy
added_at: '2010-10-01T04:06:28-04:00'
