name: Hide the Pain Harold
source: https://knowyourmeme.com/memes/hide-the-pain-harold
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- when the boss sees
- your meme tab
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About Hide The Pain Harold, also simply referred to as "Harold" or
  "Maurice" is the nickname given to a senior stock photography model whose facial
  expression appears to indicate suppressed pain and/or discomfort. Origin The earliest
  known archived thread, where Harold first got attention, can be found on Facepunch,
  dating back to 2011. On September 13th, Facepunch forum user Greenen72, posted stock
  photos with the old man[1], originally from the site DreamsTime due to pictures
  having the site's watermark on them. Spread On October 23rd, 2011, a Facebook page
  for Hide the Pain Harold[3] was created. Another Facebook page was created on January
  1, 2014. This was titled "Maurice" (his alternate name) and has over 10k likes.[9]
  On May 5th, 2014, Harold's stock photos inspired a lengthy tribute thread on 4chan's
  /b/[7][4], crafting a fictional story about an unhappy old man working as a stock
  photography model. Then on September 7th, Imgur user someshitbag[2] compiled notable
  quotes from the 4chan thread into a gallery post titled "Hide-the-pain-harold,"[8]
  which garnered more than 880,000 views in just over three weeks. On September 10th,
  a Youtuber ChinnyxD uploaded the story, narrated through text-to-speech. On October
  31st, 2013, a subreddit community for stock images, including Harold, /r/youdontsurf[6],
  was created. On sites like MemeCenter[5], stock photos featuring Harold have been
  edited to image macros, mostly used for sex or similar kinds of jokes. Identity
  On March 3rd, Kőszeg, Hungary resident András Arató[10] identified himself as the
  man in the stock photo on the pain_harold[11] group on the Russian language social
  network VK (shown below). On March 5th, 2016, Redditor The_Shreckoning announced
  Arató's identity on the /r/youdontsurf[12] subrredit. The same day, YouTuber Gigatless
  uploaded footage of Arató appearing on a Hungarian television game show (shown below,
  left). On March 6th, the hidyourpain YouTube channel uploaded footage of Arató verifying
  his identity. Manchester Trip On March 23rd, 2018, Instagram user fuckitimarobot[13]
  posted a photograph of Arató posing with a fan at a bar with the caption "So my
  friend just met Harold tonight. Don't let your memes be dreams" (shown below). Within
  48 hours, the post gained over 16,100 likes. That day, YouTuber smillmf uploaded
  a mini documentary video of in which Arató visits Manchester, England to watch a
  football game (shown below). In the coming days, articles about the video were published
  by BoingBoing[14] and Manchester Evening News.[15] TedxTalk In September 2018, Arato
  hosted a Tedx Talk in Kyiv, Ukraine. In the talk, Arato discusses the story of his
  life as a "meme-hero," as well as his career as an electrical engineer in Ukraine.
  His story begins with a vacation in Turkey, where a photograph of him was taken.
  After uploading the photograph to Facebook, a professional photographer contacted
  Arato regarding modeling, inviting him to a trial shooting. Both were happy with
  the results and continue to work together, resulting in a "couple hundred" stock
  photographs. Several months later, Arato began finding the photographs used in a
  variety of other contexts, outside of the stock photographs he agreed to. While
  he considered taking action, he says, Arato decided there was not much he could
  do. There was "no solution--only a temporary solution." In the remainder of the
  speech, Arato discusses how he began to accept his meme celebrity and his embracing
  of the notoriety, establishing a homepage for the photographs. On June 25th, 2019,
  the presentation was uploaded to YouTube. The post received more than 580,000 views
  in three days (shown below). Interview with Know Your Meme On April 9th, 2020, KYM
  interviewed András Arató as part of their editorial series that follows up on people
  featured in prominent memes. In the interview, he shared his backstory alongside
  detailed information about how the stock photos became memes and how he ultimately
  learned to embrace the persona of "Hide the Pain Harold." Notable Examples Search
  Interest External References [1] Facepunch – original post [2] Imgur – Hide-the-pain-Harold
  [3] Facebook – Hide the Pain Harold [4] Reddit – Anon tells the story of Hide-the-Pain-Harold
  [5] MemeCenter – Hide the pain Harold search results [6] Reddit – /r/youdontsurf
  [7] Reddit – Anon tells the story of Hide-the-Pain-Harold [8] Reddit – Hide the
  Pain Harold [9] Facebook – Maurice [10] vk.com – András Arató's Profile [11] vk.com
  – pain_harold (Russian) [12] Reddit – We found him [13] Instagram – fuckitimarobot
  [14] BoingBoing – Meme Star Hide The Pain Harold [15] Manchester Evening News –
  Meme Star
aside_content: MemeStatusConfirmedType:Character,Image MacroYear2011OriginFacepunchTagsfacepunch,stock
  photos,harold,discomfort,stock photo,andrás arató,greenen72,someshitbag,chinnyxd,the_shreckoning,gigatless,fuckitimarobot,smillmf,dreamstime,maurice,meme
  haroldAdditional ReferencesDreamstimeFacebookMeme GeneratorRedditTwitterUrban DictionaryWikipedia
added_at: '2014-09-27T19:59:11-04:00'
