name: Ugandan Knuckles
source: http://knowyourmeme.com/memes/ugandan-knuckles
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- ''
- do u know de wey?
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Ugandan Knuckles is the nickname given to a depiction of the
  character Knuckles from the Sonic franchise created by YouTuber Gregzilla, which
  is often used as an avatar by players in the multiplayer game VRChat who repeat
  phrases like "do you know the way" and memes associated with the country Uganda,
  most notably the film Who Killed Captain Alex? and Zulul. The character is associated
  with the expression "do you know the way", which is typically spoken in a mock African
  accent and phonetically spelled as "do you know de wey." Along with the question
  in hand a VR user will start making "spitting" sounds, followed by a "mob like"
  mentality. Unsuspecting VRchat users fall victim to Ugandan Knuckles "promise" of
  showing "de wey". Only followed by a mass trolling. Origin On August 7th, 2016,
  YouTuber VirtuallyVain uploaded footage of himself roleplaying an African gangster
  in the game Call of Duty: Black Ops, saying lines like "Follow me, I know the way"
  (shown below). Within two years, the video accumulated 10.5 million views and 17,900
  comments. On February 20th, 2017, YouTuber Gregzilla uploaded a review of the 2013
  platformer game Sonic Lost World, which featured a parody animation of the character
  Knuckles (shown below, left). The video subsequently gave rise to the Knuckles Sings
  remix series. Fans of the Twitch streamer Forsen commonly reference various jokes
  related to Ugandan warriors while playing the game PlayerUnknown''s Battlegrounds.
  Additionally, viewers have been known to stream snipe his channel while yelling
  various Uganda-related memes. On September 15th, DeviantArtist[3] tidiestflyer released
  a 3D model based on Gregzilla''s Knuckles depiction (shown below). On December 22nd,
  YouTuber Stahlsby uploaded a video titled "You Do Not Know the Way," in which a
  swarm of VRChat players wearing Ugandan Knuckles avatars troll other players by
  making clicking noises and saying "You do not know the way" (shown below, right).
  [This video has been removed] [This video has been removed] The line "you do not
  know the way" is believed to be inspired by a line in Who Killed Captain Alex? in
  which a character says "He knows the way of using a gun" (shown below). Spread On
  December 23rd, 2017, YouTuber SoyerCake published another VRChat video of various
  players wearing Ugandan Knuckles avatars (shown below, left). On December 28th,
  2017, YouTuber TanksBlast uploaded a similar VRChat video titled "Ugandan Knuckles
  Tribe" (shown below, right). On January 1st, 2018, YouTuber Syrmor uploaded a VRChat
  video titled "Do You Know the Way" (shown below). Within 48 hours, the video gained
  over 199,000 views and 170 comments. On January 3rd, Redditor JebusMcAzn submitted
  TanksBlast''s "Ugandan Knuckles Tribe" video to /r/youtubehaiku,[1] where it received
  more than 400 points (93% upvoted) and 25 comments within 12 hours. On January 5th,
  Ebaumsworld[4] published an article about the meme titled "Ugandan Knuckles Is A
  Hilarious Meme That''s Taken Gaming By Storm." On January 7th, DeviantArtist tidiestflyer
  updated the 3D model page with a disclaimer urging viewers to "not use this to bug
  the users of VRChat." "Please do not use this to bug the users of Vrchat. Its community
  means a lot to me and it would hurt me to see the rights of other users taken away
  and possibly restricted because of how out of hand it can get. Showing off their
  creativity and what they are capable of. For me….. I''m in college and don''t have
  a lot of time to get on like I would like to anymore… I remember making this and
  thinking… Well it could be funny to show off to my friends and possibly mess with
  users. But I''ve learned what kind of things I''m really capable of making. Its
  always fun to be the one with models no one else has access to. Because I can make
  anything that I want to be. Its like….. Its like that special place for me. To get
  away from the real world and be someone I''m not….. But right now. Vrchat has become
  a meme ground and I feel I have helped to dig a grave for Vrchat. Soon enough people
  are gunna get tired of all the memes that now pollute the servers. And with 500
  people trying to just enjoy an event, they cant because there just isnt enough moderation
  to hold down the rampant amounts of memers. So please…. Think about the users that
  you''re playing with. Before they are all gone… Don''t let it be a second Second
  Life." The following day, Ebaumsworld[5] published an article title "Ugandan Knuckles
  Creator Says The Meme Has Gotten Out Of Hand." The tidiestflyer update was subsequently
  removed. Racism Accusations The Ugandan Knuckles character has been accused of promoting
  ethnic and racial stereotypes against Africans, though defenders of the meme have
  claimed the character is merely based on an appreciation for Who Killed Captain
  Alex? and Wakaliwood cinema. On January 20th, 2018, YouTuber Drift0r published a
  video titled "Is Ugandan Knuckles Racist?" (shown below). [This video has been removed]
  On January 24th, 2018, Kotaku[7] published an article titled "Racist Jokes Keep
  Showing Up In Overwatch League Broadcasts," which referred to Ugandan Knuckles as
  "a meme that became racist for reasons that are excruciating to explain." The following
  day, a similar article titled "Racist Ugandan Knuckles Meme Spreads to Overwatch,
  Esports" was published by The Daily Dot.[8] Razer Tweet On January 27th, 2018, the
  gaming company Razer tweeted a customer-created image featuring a swarm of Ugandan
  Knuckles characters accompanied by the caption "Razer is de wey" (shown below).
  In response, Twitter users began accusing the company of promoting racism by posting
  the Ugandan Knuckles meme (shown below). Meanwhile, the tech news site Gizmodo[6]
  published an article titled "Does Razer Know It Posted a Racist Meme?" That day,
  Razer tweeted that they had removed the post after discovering that "the meme may
  have negative undertones" (shown below). January 2019 Jokes In December of 2018,
  popular posts appeared on meme-based subreddits encouraging a revival of Ugandan
  Knuckles in January of 2019 in order to troll /r/funny. On December 16th, me_irl
  user marshmallowhonney posted a dam edit of Ugandan Knuckles preparing to flood
  the subreddit, gaining over 13,000 points (shown below, left). It was reposted to
  /r/MemeEconomy[9] later that day, gaining over 12,000 points. Jokes about the impending
  revival appeared on various subreddits over the following few days. For example,
  an Owl Turd Comix parody about the revival gained over 20,000 points on /r/PewDiePieSubmissions
  (shown below, right). The trend was inquired about on /r/OutOfTheLoop[10] on the
  18th. December 2021 Resurgence In late 2021, hype surrounding the release of Sonic
  the Hedgehog 2 inspired a resurgence in Ugandan Knuckles memes on Reddit, mainly
  because of the addition of Knuckles into the cinematic universe voiced by actor
  Idris Elba. When the movie''s first trailer was posted on social media to platforms
  like Twitter,[11] it received roughly 84,200 likes over six days. A meme format
  called Do I Look Like I Need Your Power? emerged from the trailer which used Knuckles''
  scene within the trailer as its reference. The first meme in December 2021 to reference
  Ugandan Knuckles in conjunction with the new Sonic movie was posted to Reddit by
  Redditor[17] MikeTony713 on December 12th. The meme (shown below) received 28 likes
  over three days'' time. Inspired by the "Do I Look Like I Need Your Power?" format,
  Redditor[12] ProAssassin666 was the first to remix Ugandan Knuckles into the new
  format. The meme (shown below) was posted on December 13th, 2021, and received roughly
  33,800 upvotes over two days. Inspired by the above meme, multiple Ugandan Knuckles
  memes started ironically re-emerging across Reddit. For instance, Redditor[13] mayonnaise219
  posted a meme on December 13th (shown below, left) depicting a grave digger digging
  up "Ugandan Knuckles" from the grave. The post amassed roughly 8,200 upvotes over
  two days. Redditor[14] TheRetroVideoGamer also posted a meme (shown below, right)
  that received roughly 6,300 likes over two days. It showed Ugandan Knuckles as the
  "720p" version of Sonic 2''s Knuckles. More and more Ugandan Knuckles memes flooded
  Reddit[15][16] going into December. Various Examples In the coming days, numerous
  image macros and photoshops referencing the Ugandan Knuckles character circulated
  within various meme-themed internet communities (shown below). Search Interest External
  References [1] Reddit – /r/youtubehaiku [2] Reddit – /r/livestreamfail [3] DeviantArt
  – 3D model [4] Ebaumsworld – Ugandan Knuckles Is A Hilarious Meme That''s Taken
  Gaming By Storm [5] Ebaumsworld – Ugandan Knuckles Creator Says The Meme Has Gotten
  Out Of Hand [6] Gizmodo – Does Razer Know It Posted a Racist Meme? [7] Kotaku –
  Racist Jokes Keep Showing Up In Overwatch League Broadcasts [8] The Daily Dot –
  Racist Ugandan Knuckles Meme Spreads to Overwatch Esports [9] Reddit – r/me_irl
  is planning to fire up r/funny with Uganda Knuckles on New Years. This one is coming
  back, buy now while it’s still cheap! [10] Reddit – /r/OutOfTheLoop [11] Twitter
  – @SonicMovie [12] Reddit – r/dankmemes [13] Reddit – r/memes [14] Reddit – r/memes
  [15] Reddit – r/dankmemes [16] Reddit – r/memes [17] Reddit – r/memes'
aside_content: MemeStatusConfirmedType:CharacterYear2017OriginGregzillaTagssonic sings,uganda
  knuckles,sonic the hedgehog,vrchat,avatar,de wey,da way,da wae,dey wey,know de wey,do
  you know,russian knuckles,ugandan knucles,dawae,gregzilla,do you know de wey,whey,da
  wea,knuckels,knukles,knackles,wei,dae waeAdditional ReferencesRedditTenor GIFsTwitterUrban
  DictionaryWikipedia
added_at: '2018-01-03T10:57:40-05:00'
