name: But It's Honest Work
source: https://knowyourmeme.com/memes/but-its-honest-work
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- it ain't much
- but it's honest work
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About But It''s Honest Work is a reaction image macro series featuring
  a photograph of a farmer named Dave Brandt saying "It ain''t much, but it''s honest
  work." After appearing in 2014, the meme format spread online, particularly on Reddit
  during the late 2010s. Origin On October 10th, 2014, the United States Department
  of Agriculture[1] posted an article entitled "Soil Health Campaign Turns Two: Seeks
  to Unlock Benefits on- and off-the-Farm." The article features a photograph of Ohio
  farmer and "soil health pioneer" David Brandt (shown below, left). Four years later,
  on December 15th, 2018, Redditor [2] pettergra posted the image in the /r/MemeEconomy
  subreddit, adding the text, "It ain''t much but it''s honest work." They captioned
  the image, "When you post OC and get 10 upvotes instead of reposting for thousands."
  The post received more than 18,000 points (85% upvoted) and 130 comments in three
  weeks (shown below, right). Spread On January 3rd, 2018, Redditor[3] yothisisyo
  posted a variation, which moved the text to the bottom of the image. They added
  the caption "When your teacher asks you why you have submitted only one paper of
  20 paper homework." The post received more than 11,000 points (97% upvoted) in 24
  hours (shown below). Death On May 21st, 2023, it was announced that Dave Brandt
  had died as a result of injuries received while working the field on May 20th. His
  death sent shockwaves through not one, but two communities, as he was even more
  influential and impactful in the world of no-till low impact agriculture than he
  was in memes. On May 22nd, 2023, the Redditor Stepbro_canhelp[4] uploaded a memorial
  post where various other memes welcomed him into heaven, earning over 44,000 likes
  in 12 hours (shown below). Various Examples Search Interest External References
  [1] USDA – Soil Health Campaign Turns Two: Seeks to Unlock Benefits on- and off-the-Farm
  [2] Reddit – Hot format! Invest?! [3] Reddit – /r/dankmemes [4] Reddit – stepbro_canhelp'
aside_content: MemeStatusConfirmedType:Image Macro,ReactionYear2018OriginRedditRegionUnited
  StatesTagsfarm,farmer,it ain't much,corn field,farming,dank memes,meme economy,pettergra,david
  brandt,yothisisyo,dave brandt,death,diedAdditional ReferencesMeme GeneratorTenor
added_at: '2019-01-03T12:43:18-05:00'
