example:
- it ain't much
- but it's honest work
keywords:
- null
name: But It's Honest Work
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "But It's Honest Work | Know Your Meme O HAI! You must login or signup\
  \ first! Already a memeber? Login Now! Don't have an account? Sign up Now! Meme\
  \ Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO But It's Honest Work Added 5 years ago / Updated about a year ago Confirmed\
  \ 651,658 Part of a series on Reaction Images. [View Related Entries] View All 81\
  \ Images Navigation About \u2022 Origin \u2022 Spread \u2022 Death \u2022 Various\
  \ Examples \u2022 Search Interest \u2022 External References \u2022 Recent Images\
  \ \u2022 Recent Videos About But It's Honest Work is a reaction image macro series\
  \ featuring a photograph of a farmer named Dave Brandt saying \"It ain't much, but\
  \ it's honest work.\" After appearing in 2014, the meme format spread online, particularly\
  \ on Reddit during the late 2010s. Origin On October 10th, 2014, the United States\
  \ Department of Agriculture[1] posted an article entitled \"Soil Health Campaign\
  \ Turns Two: Seeks to Unlock Benefits on- and off-the-Farm.\" The article features\
  \ a photograph of Ohio farmer and \"soil health pioneer\" David Brandt (shown below,\
  \ left). Four years later, on December 15th, 2018, Redditor [2] pettergra posted\
  \ the image in the /r/MemeEconomy subreddit, adding the text, \"It ain't much but\
  \ it's honest work.\" They captioned the image, \"When you post OC and get 10 upvotes\
  \ instead of reposting for thousands.\" The post received more than 18,000 points\
  \ (85% upvoted) and 130 comments in three weeks (shown below, right). Spread On\
  \ January 3rd, 2018, Redditor[3] yothisisyo posted a variation, which moved the\
  \ text to the bottom of the image. They added the caption \"When your teacher asks\
  \ you why you have submitted only one paper of 20 paper homework.\" The post received\
  \ more than 11,000 points (97% upvoted) in 24 hours (shown below). Death On May\
  \ 21st, 2023, it was announced that Dave Brandt had died as a result of injuries\
  \ received while working the field on May 20th. His death sent shockwaves through\
  \ not one, but two communities, as he was even more influential and impactful in\
  \ the world of no-till low impact agriculture than he was in memes. On May 22nd,\
  \ 2023, the Redditor Stepbro_canhelp[4] uploaded a memorial post where various other\
  \ memes welcomed him into heaven, earning over 44,000 likes in 12 hours (shown below).\
  \ Various Examples Search Interest External References [1] USDA \u2013 Soil Health\
  \ Campaign Turns Two: Seeks to Unlock Benefits on- and off-the-Farm [2] Reddit \u2013\
  \ Hot format! Invest?! [3] Reddit \u2013 /r/dankmemes [4] Reddit \u2013 stepbro_canhelp\
  \ farm farmer it ain't much corn field farming dank memes meme economy pettergra\
  \ david brandt yothisisyo dave brandt death died Share Pin Related Entries 190 total\
  \ Facepalm Deal With It Impossibru Math Lady / Confused Lady View All Related Entries\
  \ Recent Images 81 total View All Images Recent Videos 22 total View All Videos\
  \ Sign up for our Newsletter Load 4 Comments Comments 4 total 22 But It's Honest\
  \ Work 651,663 22 81 4 Part of a series on Reaction Images. [View Related Entries]\
  \ Updated May 22, 2023 at 05:55PM EDT by Brandon. Added Jan 03, 2019 at 12:43PM\
  \ EST by Matt. Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i'\
  \ to view the image gallery, 'v' to view the video gallery, or 'r' to view a random\
  \ entry. Meme Status Confirmed Type: Image Macro, Reaction Year 2018 Origin Reddit\
  \ Region United States Tags farm, farmer, it ain't much, corn field, farming, dank\
  \ memes, meme economy, pettergra, david brandt, yothisisyo, dave brandt, death,\
  \ died Additional References Meme Generator Tenor About But It's Honest Work is\
  \ a reaction image macro series featuring a photograph of a farmer named Dave Brandt\
  \ saying \"It ain't much, but it's honest work.\" After appearing in 2014, the meme\
  \ format spread online, particularly on Reddit during the late 2010s. Origin On\
  \ October 10th, 2014, the United States Department of Agriculture[1] posted an article\
  \ entitled \"Soil Health Campaign Turns Two: Seeks to Unlock Benefits on- and off-the-Farm.\"\
  \ The article features a photograph of Ohio farmer and \"soil health pioneer\" David\
  \ Brandt (shown below, left). Four years later, on December 15th, 2018, Redditor\
  \ [2] pettergra posted the image in the /r/MemeEconomy subreddit, adding the text,\
  \ \"It ain't much but it's honest work.\" They captioned the image, \"When you post\
  \ OC and get 10 upvotes instead of reposting for thousands.\" The post received\
  \ more than 18,000 points (85% upvoted) and 130 comments in three weeks (shown below,\
  \ right). Spread On January 3rd, 2018, Redditor[3] yothisisyo posted a variation,\
  \ which moved the text to the bottom of the image. They added the caption \"When\
  \ your teacher asks you why you have submitted only one paper of 20 paper homework.\"\
  \ The post received more than 11,000 points (97% upvoted) in 24 hours (shown below).\
  \ Death On May 21st, 2023, it was announced that Dave Brandt had died as a result\
  \ of injuries received while working the field on May 20th. His death sent shockwaves\
  \ through not one, but two communities, as he was even more influential and impactful\
  \ in the world of no-till low impact agriculture than he was in memes. On May 22nd,\
  \ 2023, the Redditor Stepbro_canhelp[4] uploaded a memorial post where various other\
  \ memes welcomed him into heaven, earning over 44,000 likes in 12 hours (shown below).\
  \ Various Examples Search Interest External References [1] USDA \u2013 Soil Health\
  \ Campaign Turns Two: Seeks to Unlock Benefits on- and off-the-Farm [2] Reddit \u2013\
  \ Hot format! Invest?! [3] Reddit \u2013 /r/dankmemes [4] Reddit \u2013 stepbro_canhelp\
  \ Related Entries 190 total Facepalm Deal With It Impossibru Math Lady / Confused\
  \ Lady Are You A Wizard Confused Black Girl Brent Rambo Ah, I See You're a Man of\
  \ Culture As Well Computer Reaction Faces Awesome Face / Epic Smiley Shocked Black\
  \ Guy L.A. Noire \"Doubt\" / Press X To Doubt View All Related Entries Recent Videos\
  \ 22 total IRL Dave did far more than wh... But It's Honest Work Uploaded by Rogue\
  \ Wisdom The real \"it ain't much, but ... But It's Honest Work Uploaded by Y F\
  \ It's honest work But It's Honest Work Uploaded by Y F Reverse order 66 (it ain't\
  \ mu... But It's Honest Work Uploaded by Y F It ain't much but it's honest... But\
  \ It's Honest Work Uploaded by Y F It ain't much, but it's hones... But It's Honest\
  \ Work Uploaded by Y F NON SAR\xC0 MOLTO MA \xC8 UN LAVORO... But It's Honest Work\
  \ Uploaded by Y F It Ain't Much, but It's Hones... But It's Honest Work Uploaded\
  \ by Y F + Add a Video View All Videos Recent Images 81 total But It's Honest Work\
  \ Uploaded by Marwan Sallam But It's Honest Work Uploaded by Aidan Walker But It's\
  \ Honest Work Uploaded by snoozelily But It's Honest Work Uploaded by Jaimie Hamilton\
  \ But It's Honest Work Uploaded by Reddit Moments But It's Honest Work Uploaded\
  \ by Sum Lu Zer But It's Honest Work Uploaded by Reddit Moments But It's Honest\
  \ Work Uploaded by Owen But It's Honest Work Uploaded by Brandon But It's Honest\
  \ Work Uploaded by Reddit Moments But It's Honest Work Uploaded by Reddit Moments\
  \ But It's Honest Work Uploaded by Reddit Moments + Add an Image View All Images\
  \ Sign up for our Newsletter + Add a Comment Comments (4) Display Comments Add a\
  \ Comment Top Entries This Month Meme Saika Kawakita Smile GIF Event Assassination\
  \ of UnitedHealthcare CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki\
  \ Sisters Culture Pornography Site Whisper View More Suggest a Change Edit History\
  \ Entry Editors (7) Matt Secretary of Memes Y F Digital Archaeologist & Treasurer\
  \ & Media Maid nightqueen Archivist shevyrolet Digital Archaeologist & Treasurer\
  \ & Media Bus Boy Autumn Able Sr. Entry Moderator Zach Memenator Brandon Brandy\
  \ From The Blockchain \u25BC + Request Editorship View All Editors Today's Top Image\
  \ Galleries Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team\
  \ Fortress 2 The Amazing Digital Circus About Our Story Site Rules Policies and\
  \ Guidelines Credits Contact Meme DB Memes Episodes News Staff Contact Extras! Style\
  \ Guide RSS Feeds"
source: https://knowyourmeme.com/memes/but-its-honest-work
template_id: bihw
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
