name: Sad Joe Biden
source: http://knowyourmeme.com/memes/sad-joe-biden
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- sad joe biden
- doesn't think you'll vote
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About Sad Joe Biden is a series of humorously captioned images based
  on a photograph of United States Vice President Joe Biden staring out a window during
  a summit between the U.S. president Barack Obama and Ukrainian President Petro Poroshenko
  at the White House in September 2014. Origin On September 18th, 2014, Getty Images
  photographer Oliver Douliery photographed Biden staring pensively out a window at
  the White House during a special summit with the Ukrainian president to address
  the escalating political tension between the East European nation and Russia. "US
  Vice-President Joe Biden looks on during a bilateral meeting between President Obama
  and President Petro Poroshenko of Ukraine in the Oval Office of the White House
  September 18, 2014 in Washington, DC. The two leaders held a bilateral meeting to
  discuss a strategic aid package for Ukraine for its battle with pro Russian separatists."
  On December 6th, 2014, Twitter user Michael Doran[2] tweeted the Getty Images photograph
  and invited his followers to come up with funny and fitting internal monologues
  for the image. Spread On December 6th, Twitter user @Popehat[7] tweeted the photo
  with a quote uttered by the character Tuco in the 1966 Spaghetti Western film The
  Good, the Bad and the Ugly (shown below, left). The following day, Twitter user
  Rachel Zarrell[8] posted the photo with the caption "but did adnan do it tho?" (shown
  below, right). . Several minutes later, the BuzzFeed Twitter[3] feed urged followers
  to caption the photo (shown below, left) On December 8th, Twitter user Vince Coglianese
  tweeted a photoshopped image of Biden looking at the window next to the character
  Clark Grisworld from the 1989 comedy film National Lampoon's Christmas Vacation
  (shown below, right). In the coming days, several news sites published articles
  about the Twitter captions, including The Daily Dot,[4] Today[5] and The Washington
  Post.[6] Notable Examples Search Interest Not available. External References [1]
  Getty Images – President Obama Meets With Ukraine's President Petro Poroshenko At
  The White House [2] Twitter – @Doranimated [3] Twitter – @BuzzFeed [4] The Daily
  Dot – Joe Biden looked out a window and instantly became a meme [5] Today – Photo
  of sad Joe Biden [6] Washington Post – This photo of Joe Biden staring out a window
  will haunt the Internet forever [7] Twitter – @PopeHat [8] Twitter – @rachelzarrell
aside_content: MemeStatusSubmissionYear2014OriginTwitterTagstwitter,caption,photograph,politician,photoshop,sad,celebrity,joe
  biden
added_at: '2014-12-08T17:53:35-05:00'
