example:
- sad joe biden
- doesn't think you'll vote
keywords:
- null
name: Sad Joe Biden
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Sad Joe Biden | Know Your Meme Hello! You must login or signup first!\
  \ Already a memeber? Login Now! Don't have an account? Sign up Now! Meme Encyclopedia\
  \ All Cultures Events People Sites Subcultures Videos Submit \u2192 Images Trending\
  \ Most Commented Most Favorited High Score Low Score Most Viewed All Templates Upload\
  \ an Image Articles News Explainers Collections Interviews Meme Insider Magazine\
  \ More Discord Newsletter Episodes Forums Meme Store Login Abstract user icon Memes\
  \ Categories Trending News Images Trending Images Videos Trending Videos Editorials\
  \ Meme Insider Magazine Newsletter Policies and Guidelines Meme Store Old site Login\
  \ Know Your Meme is the property of Literally Media \xA92024 Literally Media. All\
  \ Rights Reserved. This image Of Woman Confidently Strolling Through A Glass Panel\
  \ Has Been A Redraw Format Since 2021 Three Years Ago, This Boar's Head 'Exploded'\
  \ Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess Memes Turns Two Years\
  \ Old Today Phrase 'The Fridge Protects The Snacks' A Growing Favorite Among Pickup\
  \ Artist Influencers Jamie G, The Bosh British Charva, Has Taken Over TikTok With\
  \ His Signature 'Oh Cherie Amour' Sound Also Trending: Honey Extension Influencer\
  \ Scam Renegade Raider Copypasta Assassination of UnitedHealthcare CEO Sad Joe Biden\
  \ Added 10 years ago / Updated 9 years ago Submission 47,634 Part of a series on\
  \ Joe Biden. [View Related Entries] View All 24 Images Navigation About \u2022 Origin\
  \ \u2022 Spread \u2022 Notable Examples \u2022 Search Interest \u2022 External References\
  \ \u2022 Recent Images About Sad Joe Biden is a series of humorously captioned images\
  \ based on a photograph of United States Vice President Joe Biden staring out a\
  \ window during a summit between the U.S. president Barack Obama and Ukrainian President\
  \ Petro Poroshenko at the White House in September 2014. Origin On September 18th,\
  \ 2014, Getty Images photographer Oliver Douliery photographed Biden staring pensively\
  \ out a window at the White House during a special summit with the Ukrainian president\
  \ to address the escalating political tension between the East European nation and\
  \ Russia. \"US Vice-President Joe Biden looks on during a bilateral meeting between\
  \ President Obama and President Petro Poroshenko of Ukraine in the Oval Office of\
  \ the White House September 18, 2014 in Washington, DC. The two leaders held a bilateral\
  \ meeting to discuss a strategic aid package for Ukraine for its battle with pro\
  \ Russian separatists.\" On December 6th, 2014, Twitter user Michael Doran[2] tweeted\
  \ the Getty Images photograph and invited his followers to come up with funny and\
  \ fitting internal monologues for the image. Spread On December 6th, Twitter user\
  \ @Popehat[7] tweeted the photo with a quote uttered by the character Tuco in the\
  \ 1966 Spaghetti Western film The Good, the Bad and the Ugly (shown below, left).\
  \ The following day, Twitter user Rachel Zarrell[8] posted the photo with the caption\
  \ \"but did adnan do it tho?\" (shown below, right). . Several minutes later, the\
  \ BuzzFeed Twitter[3] feed urged followers to caption the photo (shown below, left)\
  \ On December 8th, Twitter user Vince Coglianese tweeted a photoshopped image of\
  \ Biden looking at the window next to the character Clark Grisworld from the 1989\
  \ comedy film National Lampoon's Christmas Vacation (shown below, right). In the\
  \ coming days, several news sites published articles about the Twitter captions,\
  \ including The Daily Dot,[4] Today[5] and The Washington Post.[6] Notable Examples\
  \ Search Interest Not available. External References [1] Getty Images \u2013 President\
  \ Obama Meets With Ukraine's President Petro Poroshenko At The White House [2] Twitter\
  \ \u2013 @Doranimated [3] Twitter \u2013 @BuzzFeed [4] The Daily Dot \u2013 Joe\
  \ Biden looked out a window and instantly became a meme [5] Today \u2013 Photo of\
  \ sad Joe Biden [6] Washington Post \u2013 This photo of Joe Biden staring out a\
  \ window will haunt the Internet forever [7] Twitter \u2013 @PopeHat [8] Twitter\
  \ \u2013 @rachelzarrell twitter caption photograph politician photoshop sad celebrity\
  \ joe biden Share Pin Related Entries 77 total Let's Go Brandon Dark Brandon Creepy\
  \ Joe Biden Prankster Joe Biden View All Related Entries Recent Images 24 total\
  \ View All Images Recent Videos 0 total There are no recent videos. Sign up for\
  \ our Newsletter Load 28 Comments Comments 28 total 14 Sad Joe Biden 47,634 0 24\
  \ 28 Part of a series on Joe Biden. [View Related Entries] Updated Oct 13, 2015\
  \ at 08:54PM EDT by Brad. Added Dec 08, 2014 at 05:53PM EST by Don. Like us on Facebook!\
  \ Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to\
  \ view the video gallery, or 'r' to view a random entry. This submission is currently\
  \ being researched & evaluated! You can help confirm this entry by contributing\
  \ facts, media, and other evidence of notability and mutation. Meme Status Submission\
  \ Year 2014 Origin Twitter Tags twitter, caption, photograph, politician, photoshop,\
  \ sad, celebrity, joe biden About Sad Joe Biden is a series of humorously captioned\
  \ images based on a photograph of United States Vice President Joe Biden staring\
  \ out a window during a summit between the U.S. president Barack Obama and Ukrainian\
  \ President Petro Poroshenko at the White House in September 2014. Origin On September\
  \ 18th, 2014, Getty Images photographer Oliver Douliery photographed Biden staring\
  \ pensively out a window at the White House during a special summit with the Ukrainian\
  \ president to address the escalating political tension between the East European\
  \ nation and Russia. \"US Vice-President Joe Biden looks on during a bilateral meeting\
  \ between President Obama and President Petro Poroshenko of Ukraine in the Oval\
  \ Office of the White House September 18, 2014 in Washington, DC. The two leaders\
  \ held a bilateral meeting to discuss a strategic aid package for Ukraine for its\
  \ battle with pro Russian separatists.\" On December 6th, 2014, Twitter user Michael\
  \ Doran[2] tweeted the Getty Images photograph and invited his followers to come\
  \ up with funny and fitting internal monologues for the image. Spread On December\
  \ 6th, Twitter user @Popehat[7] tweeted the photo with a quote uttered by the character\
  \ Tuco in the 1966 Spaghetti Western film The Good, the Bad and the Ugly (shown\
  \ below, left). The following day, Twitter user Rachel Zarrell[8] posted the photo\
  \ with the caption \"but did adnan do it tho?\" (shown below, right). . Several\
  \ minutes later, the BuzzFeed Twitter[3] feed urged followers to caption the photo\
  \ (shown below, left) On December 8th, Twitter user Vince Coglianese tweeted a photoshopped\
  \ image of Biden looking at the window next to the character Clark Grisworld from\
  \ the 1989 comedy film National Lampoon's Christmas Vacation (shown below, right).\
  \ In the coming days, several news sites published articles about the Twitter captions,\
  \ including The Daily Dot,[4] Today[5] and The Washington Post.[6] Notable Examples\
  \ Search Interest Not available. External References [1] Getty Images \u2013 President\
  \ Obama Meets With Ukraine's President Petro Poroshenko At The White House [2] Twitter\
  \ \u2013 @Doranimated [3] Twitter \u2013 @BuzzFeed [4] The Daily Dot \u2013 Joe\
  \ Biden looked out a window and instantly became a meme [5] Today \u2013 Photo of\
  \ sad Joe Biden [6] Washington Post \u2013 This photo of Joe Biden staring out a\
  \ window will haunt the Internet forever [7] Twitter \u2013 @PopeHat [8] Twitter\
  \ \u2013 @rachelzarrell Related Entries 77 total Let's Go Brandon Dark Brandon Creepy\
  \ Joe Biden Prankster Joe Biden Ok Smart Guy! Let's See YOU Take A Crack At It!\
  \ Joe Biden's Corn Pop Story Big Fucking Deal (Joe Biden) Laughing Joe Biden Poor\
  \ Boys Lady Gaga and Joe Biden Couple Picture Joe Biden Tripping on Boarding Stairs\
  \ Joe Biden's Bleeding Eye View All Related Entries Recent Videos There are no videos\
  \ currently available. + Add a Video Recent Images 24 total Sad Joe Biden Uploaded\
  \ by nightqueen Sad Joe Biden Uploaded by Zigil Sad Joe Biden Uploaded by SmellyPickle\
  \ Sad Joe Biden Uploaded by brucefiz Sad Joe Biden Uploaded by vtalucard Sad Joe\
  \ Biden Uploaded by Geekydestro Sad Joe Biden Uploaded by brucefiz Sad Joe Biden\
  \ Uploaded by NightmareNear Sad Joe Biden Uploaded by Bucky Sad Joe Biden Uploaded\
  \ by Don Sad Joe Biden Uploaded by Don Sad Joe Biden Uploaded by Don + Add an Image\
  \ View All Images Sign up for our Newsletter Top Comments Delete Sensitive Kakaraka\
  \ Dec 08, 2014 at 06:21PM EST Yet again +54 Reply Delete Sensitive NightmareNear\
  \ Dec 09, 2014 at 12:53AM EST +32 Reply + Add a Comment Comments (28) Display Comments\
  \ Add a Comment Top Entries This Month Meme Saika Kawakita Smile GIF Event Assassination\
  \ of UnitedHealthcare CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki\
  \ Sisters Culture Pornography Site Whisper View More Suggest a Change Edit History\
  \ Entry Editors (2) Don Administrator & Meme Daddy Brad Digital Archaeologist &\
  \ Treasurer & Pundit & Gallery Housekeeper + Request Editorship View All Editors\
  \ Today's Top Image Galleries Assassination of UnitedHealthcare CEO Squirrel Girl\
  \ (Doreen Green) Team Fortress 2 The Amazing Digital Circus About Our Story Site\
  \ Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes News Staff\
  \ Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/sad-joe-biden
template_id: sad-biden
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
