name: Stop It Patrick You're Scaring Him
source: https://knowyourmeme.com/memes/stop-it-patrick-youre-scaring-him
keywords:
- null
text:
- style: default
  color: '#b1e0d0'
  font: thin
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 0.5
  scale_y: 0.06
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: '#ffb6a6'
  font: thin
  anchor_x: 0.5
  anchor_y: 0.0
  angle: 0.0
  scale_x: 0.5
  scale_y: 0.075
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: '#fff05c'
  font: thin
  anchor_x: 0.18
  anchor_y: 0.335
  angle: 0.0
  scale_x: 0.32
  scale_y: 0.18
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: '#b1e0d0'
  font: thin
  anchor_x: 0.5
  anchor_y: 0.335
  angle: 0.0
  scale_x: 0.5
  scale_y: 0.07
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: '#ffb6a6'
  font: thin
  anchor_x: 0.0
  anchor_y: 0.67
  angle: 0.0
  scale_x: 0.5
  scale_y: 0.075
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: '#fff05c'
  font: thin
  anchor_x: 0.5
  anchor_y: 0.67
  angle: 0.0
  scale_x: 0.5
  scale_y: 0.075
  align: center
  start: 0.0
  stop: 1.0
example:
- I'm claustrophobic.
- What does "claustrophobic" mean?
- It means he's afraid of Santa Claus.
- No, it doesn't.
- HO-HO-HO
- Stop it, Patrick, you're scaring him!
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About Stop Patrick you're scaring him is an image exploitable from
  the television show Spongebob Squarepants. It is used to mock an individuals beliefs,
  organisation by by comparing what the individual says they believe versus how an
  outsider views them and their percieved actual extreme or ridiculous beliefs. Origin
  The meme format comes from the spongebob squarepants episode 72b 'wishing you well'
  from season 4 first shown on the 28th July 2006. in the original scene patrick and
  spongebob are confused by Squidward's claustrophbia thinking it means to be afraid
  of Santa Claus. Spread The first use of the template was uploaded by u/pleimer to
  r/masseffectmemes on the 13th of October 2018. From there it has been used to comment
  upon many beliefs and groups of people from anti-vaxxers to political centrists.
  Various Examples
aside_content: MemeStatusSubmissionType:ExploitableYear2018OriginSpongebob SquarepantsTagsspongebob
  squarepants,patrick,squidward,fear,phobiaAdditional ReferencesMeme GeneratorWikipedia
added_at: '2020-08-23T14:27:48-04:00'
