name: Always Has Been
source: https://knowyourmeme.com/memes/wait-its-all-ohio-always-has-been
keywords:
- null
text:
- style: default
  color: white
  font: thin
  anchor_x: 0.45
  anchor_y: 0.35
  angle: 0.0
  scale_x: 0.25
  scale_y: 0.1
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: white
  font: thin
  anchor_x: 0.75
  anchor_y: 0.0
  angle: 0.0
  scale_x: 0.25
  scale_y: 0.1
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: white
  font: thick
  anchor_x: 0.375
  anchor_y: 0.8
  angle: 0.0
  scale_x: 0.25
  scale_y: 0.1
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: white
  font: thick
  anchor_x: 0.75
  anchor_y: 0.7
  angle: 0.0
  scale_x: 0.25
  scale_y: 0.1
  align: center
  start: 0.0
  stop: 1.0
example:
- Wait, it's round?
- Always has been
- Flat Earther
- Science
overlay:
- center_x: 0.27
  center_y: 0.47
  angle: 0.0
  scale: 0.425
scraped_content: About Wait, It's All Ohio? Always Has Been refers to an exploitable
  template in which two astronauts are in space. One looks at Earth and realizes the
  entire Earth is made up of something other than what is expected, and asks "Wait,
  it's all X?" The other astronaut, preparing a gun, says "Always has been." Origin
  On December 11th, 2016, Redditor Wiegand6 posted in the /r/dankmemes[11] an MSPaint
  illustration of two astronauts looking at flat earth. One astronaut says, "wtf it's
  flat!!!" The other, pointing a gun at their fellow astronaut, says, "Sry fam." The
  post received more than 485 points (97% upvoted) in less than four years (shown
  below). On August 7th, 2018, an anonymous 4chan user posted the earliest known version
  of the template, using America as the surprise[1] (shown below). Spread The template
  did not begin seeing widespread use until over a year later in conjunction with
  the rise of Ohio vs. the World edits, when "Ohio" became a popular variation of
  the template's punchline. user iOhioian posted such an edit was posted to iFunny[2]
  on October 17th, 2019 (shown below, left). The post received more than 46,000 reactions
  and 1,700 comments in less than one year. This was reposted to Twitter,[3] Reddit,[4]
  Tumblr[5], and Instagram.[6] The image inspired further MS-Paint edits. For example,
  Facebook page Twingo Memes[7] posted an edit in which the punchline was France,
  gaining over 530 reactions (shown below, right). Edits would later come to use more
  realistic-looking versions of the astronauts. For example, on June 7th, 2020, Redditor
  nickslicktricks posted an example to /r/memes,[8] gaining over 33,000 points (shown
  below, left). On June 19th, 2020, Twitter user @Alexis_Grump[9] made an example
  using Bugsnax (shown below, right). On July 14th, Ebaumsworld[10] published a gallery
  featuring notable examples of the meme. Various Examples Template Search Interest
  External References [1] 4chan – pol [2] iFunny – iOhioan's Post [3] Twitter – @burgertownmw2
  [4] Reddit – IHateOhio [5] Tumblr – chemtraildude (unavailable) [6] Instagram –
  salad.snake (private account) [7] Facebook – Twingo Memes [8] Reddit – /r/memes
  [9] Twitter – Alexis_Grump [10] Ebaumsworld – Wait, It's All Ohio? Always Has Been
  Astronaut Memes That Are Out of This World [11] Reddit – /r/dankmemes
aside_content: MemeStatusConfirmedType:Catchphrase,ExploitableYear2018Origin4chanTagsastronauts,ohio
  vs. the world,gun,wait,its all?,always has been,nickslicktricks,@alexis_grump,always
  has been memeAdditional ReferencesMeme GeneratorMemebase
added_at: '2020-06-26T16:05:23-04:00'
