example:
- ''
- just as I planned...
keywords:
- null
name: Disaster Girl
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Disaster Girl | Know Your Meme Hey! You must login or signup first!\
  \ Already a memeber? Login Now! Don't have an account? Sign up Now! Meme Encyclopedia\
  \ All Cultures Events People Sites Subcultures Videos Submit \u2192 Images Trending\
  \ Most Commented Most Favorited High Score Low Score Most Viewed All Templates Upload\
  \ an Image Articles News Explainers Collections Interviews Meme Insider Magazine\
  \ More Discord Newsletter Episodes Forums Meme Store Login Abstract user icon Memes\
  \ Categories Trending News Images Trending Images Videos Trending Videos Editorials\
  \ Meme Insider Magazine Newsletter Policies and Guidelines Meme Store Old site Login\
  \ Know Your Meme is the property of Literally Media \xA92024 Literally Media. All\
  \ Rights Reserved. This image Of Woman Confidently Strolling Through A Glass Panel\
  \ Has Been A Redraw Format Since 2021 Three Years Ago, This Boar's Head 'Exploded'\
  \ Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess Memes Turns Two Years\
  \ Old Today Phrase 'The Fridge Protects The Snacks' A Growing Favorite Among Pickup\
  \ Artist Influencers Jamie G, The Bosh British Charva, Has Taken Over TikTok With\
  \ His Signature 'Oh Cherie Amour' Sound Also Trending: Honey Extension Influencer\
  \ Scam Renegade Raider Copypasta Assassination of UnitedHealthcare CEO Disaster\
  \ Girl Added 15 years ago / Updated 8 days ago Confirmed 2,026,011 View All 269\
  \ Images Featured Episode Navigation About \u2022 Origin \u2022 Spread \u2022 Notable\
  \ Examples \u2022 Search Interest \u2022 External References \u2022 Recent Images\
  \ \u2022 Recent Videos About Disaster Girl is a photoshop meme in which an exploitable\
  \ photo of a smiling girl is superimposed on to images of natural disasters and\
  \ accidents to imply that she has caused some type of calamity depicted in the background.\
  \ Origin The photograph of the girl and the burning house was taken by Dave Roth[1]\
  \ in January 2005[2] during the local fire department's live drill training two\
  \ blocks away from his home in Mebane, North Carolina. While observing the fire,\
  \ Dave caught his daughter, Zoe, smiling devilishly juxtaposed against the burning\
  \ house. Roth first uploaded the photo of his daughter, which he titled \"Firestarter,\"\
  \ to the image hosting service Zooomr[3] on January 2nd 2007. However, it did not\
  \ receive much attention until later that year on November 29th when Roth submitted\
  \ the same image to JPG Magazine[4] for an \"Emotion Capture\" competition. The\
  \ photo was selected for publication in the February / March 2008 print issue of\
  \ the magazine.[5] Spread In October 2008, JPG Magazine[6] spoke with Dave and Zoe,\
  \ who were both \"jazzed\" by the attention the photo had received. By November\
  \ 2008, the initial JPG Magazine post had gained over 95,000 views.[2] The original\
  \ photo was posted to Buzzfeed[7] on October 27th, 2008 with a followup[8] post\
  \ the next day highlighting the best derivatives, followed by similar posts on Digg[9],\
  \ TrendHunter[10], eBaum's World Forum[11] and Best Week Ever.[12] Over the years,\
  \ the photo and its derivatives have been mentioned on Neatorama[13], photo site\
  \ DamnCoolPictures[14], Cracked[15] and the Huffington Post.[16] Notable Examples\
  \ Disaster Girl Now Roth has continued to post photos of Zoe on his Flickr[17] account\
  \ over the years. Interview with Know Your Meme On December 18th, 2020, KYM interviewed\
  \ Zoe as part of their editorial series that follows up on people featured in prominent\
  \ memes. In the interview, we spoke with Roth to get a glimpse into what it was\
  \ like growing up with her image plastered all around the internet \u2014 even to\
  \ this day. Search Interest Search for Disaster Girl didn't begin until October\
  \ 2008, when the photos were posted to Buzzfeed. Search peaked in May 2011. External\
  \ References [1] The Traveling Roths \u2013 Home [2] The Traveling Roths \u2013\
  \ I Have A Meme: Disaster Girl [3] Zooomr (via Wayback Machine) \u2013 Firestarter\
  \ [4] JPG Magazine (via Wayback Machine) \u2013 Firestarter [5] JPG Magazine \u2013\
  \ Issue 14 [6] JPG Magazine (via Wayback Machine) \u2013 Disaster Girl is Coming\
  \ for You [7] Buzzfeed \u2013 Disaster Girl! [8] Buzzfeed \u2013 The Amazing True\
  \ Story of Disaster Girl [9] Digg \u2013 Make Your Own 'Disaster Girl' Background\
  \ [10] TrendHunter \u2013 Viral Compassion Through Photoshop [11] eBaum's World\
  \ Forum (via Wayback Machine) \u2013 Disaster Girl Strikes Again [12] Best Week\
  \ Ever (via Wayback Machine) \u2013 Disaster Girl: The New Fail [13] Neatorama \u2013\
  \ Disaster Girl [14] DamnCoolPictures \u2013 Disaster Girl Grown Up [15] Cracked\
  \ \u2013 6 Images of Kids Too Insane to Be Real (That Totally Are) [16] Huffington\
  \ Post \u2013 6 Amazing Kid Photos [17] Flickr \u2013 TravelingRoths [18] - Wikipedia\
  \ \u2013 A Girl Named Disaster [19] Macrochan (via Wayback Machine) \u2013 Disaster\
  \ Boy image macro photoshop mainstream buzzfeed exploitables dave roth neatorama\
  \ zooomr zoe roth firestarter Share Pin Recent Images 269 total View All Images\
  \ Recent Videos 47 total View All Videos Sign up for our Newsletter Load 52 Comments\
  \ Comments 52 total 138 Disaster Girl 2,026,011 47 269 52 Updated Dec 15, 2024 at\
  \ 06:20PM EST by LiterallyAustin. Added Dec 30, 2008 at 01:56PM EST by Jamie Dubs.\
  \ Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the\
  \ image gallery, 'v' to view the video gallery, or 'r' to view a random entry. Featured\
  \ Episode Meme Status Confirmed Type: Exploitable, Photoshop Year 2007 Origin Unknown\
  \ Tags image macro, photoshop, mainstream, buzzfeed, exploitables, dave roth, neatorama,\
  \ zooomr, zoe roth, firestarter Additional References Meme Generator About Disaster\
  \ Girl is a photoshop meme in which an exploitable photo of a smiling girl is superimposed\
  \ on to images of natural disasters and accidents to imply that she has caused some\
  \ type of calamity depicted in the background. Origin The photograph of the girl\
  \ and the burning house was taken by Dave Roth[1] in January 2005[2] during the\
  \ local fire department's live drill training two blocks away from his home in Mebane,\
  \ North Carolina. While observing the fire, Dave caught his daughter, Zoe, smiling\
  \ devilishly juxtaposed against the burning house. Roth first uploaded the photo\
  \ of his daughter, which he titled \"Firestarter,\" to the image hosting service\
  \ Zooomr[3] on January 2nd 2007. However, it did not receive much attention until\
  \ later that year on November 29th when Roth submitted the same image to JPG Magazine[4]\
  \ for an \"Emotion Capture\" competition. The photo was selected for publication\
  \ in the February / March 2008 print issue of the magazine.[5] Spread In October\
  \ 2008, JPG Magazine[6] spoke with Dave and Zoe, who were both \"jazzed\" by the\
  \ attention the photo had received. By November 2008, the initial JPG Magazine post\
  \ had gained over 95,000 views.[2] The original photo was posted to Buzzfeed[7]\
  \ on October 27th, 2008 with a followup[8] post the next day highlighting the best\
  \ derivatives, followed by similar posts on Digg[9], TrendHunter[10], eBaum's World\
  \ Forum[11] and Best Week Ever.[12] Over the years, the photo and its derivatives\
  \ have been mentioned on Neatorama[13], photo site DamnCoolPictures[14], Cracked[15]\
  \ and the Huffington Post.[16] Notable Examples Disaster Girl Now Roth has continued\
  \ to post photos of Zoe on his Flickr[17] account over the years. Interview with\
  \ Know Your Meme On December 18th, 2020, KYM interviewed Zoe as part of their editorial\
  \ series that follows up on people featured in prominent memes. In the interview,\
  \ we spoke with Roth to get a glimpse into what it was like growing up with her\
  \ image plastered all around the internet \u2014 even to this day. Search Interest\
  \ Search for Disaster Girl didn't begin until October 2008, when the photos were\
  \ posted to Buzzfeed. Search peaked in May 2011. External References [1] The Traveling\
  \ Roths \u2013 Home [2] The Traveling Roths \u2013 I Have A Meme: Disaster Girl\
  \ [3] Zooomr (via Wayback Machine) \u2013 Firestarter [4] JPG Magazine (via Wayback\
  \ Machine) \u2013 Firestarter [5] JPG Magazine \u2013 Issue 14 [6] JPG Magazine\
  \ (via Wayback Machine) \u2013 Disaster Girl is Coming for You [7] Buzzfeed \u2013\
  \ Disaster Girl! [8] Buzzfeed \u2013 The Amazing True Story of Disaster Girl [9]\
  \ Digg \u2013 Make Your Own 'Disaster Girl' Background [10] TrendHunter \u2013 Viral\
  \ Compassion Through Photoshop [11] eBaum's World Forum (via Wayback Machine) \u2013\
  \ Disaster Girl Strikes Again [12] Best Week Ever (via Wayback Machine) \u2013 Disaster\
  \ Girl: The New Fail [13] Neatorama \u2013 Disaster Girl [14] DamnCoolPictures \u2013\
  \ Disaster Girl Grown Up [15] Cracked \u2013 6 Images of Kids Too Insane to Be Real\
  \ (That Totally Are) [16] Huffington Post \u2013 6 Amazing Kid Photos [17] Flickr\
  \ \u2013 TravelingRoths [18] - Wikipedia \u2013 A Girl Named Disaster [19] Macrochan\
  \ (via Wayback Machine) \u2013 Disaster Boy Recent Videos 47 total \u0B8E\u0BA4\u0BB0\
  \u0BCD\u0B9A\u0BCD\u0B9A\u0BBF\u0BAF\u0BBE\u0B95 \u0B8E\u0B9F\u0BC1\u0BA4\u0BCD\u0BA4\
  \ \u0BAA\u0BC1\u0B95\u0BC8\u0BAA\u0BCD \u0BAA\u0B9F\u0BA4... Disaster Girl Uploaded\
  \ by shevyrolet POP CRYPTO WEEKLY: Opera + We... Disaster Girl Uploaded by shevyrolet\
  \ Disaster Girl Meme Gets Major... Disaster Girl Uploaded by andcallmeshirley Disaster\
  \ Girl Meme Sells for ... Disaster Girl Uploaded by andcallmeshirley Disaster Girl\
  \ Meme Sells for ... Disaster Girl Uploaded by Y F That Nerd Dad on Disaster Gir...\
  \ Disaster Girl Uploaded by Y F Photo: Woman From 'Disaster G... Disaster Girl Uploaded\
  \ by Y F Biden's Optical Illusion Phot... Disaster Girl Uploaded by andcallmeshirley\
  \ + Add a Video View All Videos Recent Images 269 total Disaster Girl Uploaded by\
  \ Triplem Disaster Girl Uploaded by Triplem Disaster Girl Uploaded by Reddit Moments\
  \ Disaster Girl Uploaded by KZN02 Disaster Girl Uploaded by Evilthing Disaster Girl\
  \ Uploaded by Triplem Disaster Girl Uploaded by KM/SU Disaster Girl Uploaded by\
  \ Doqqo Disaster Girl Uploaded by LouCypher Disaster Girl Uploaded by Tohsaka Kousaka-chan\
  \ Disaster Girl Uploaded by Bilbo Swaggins Disaster Girl Uploaded by Meemyoozr234\
  \ + Add an Image View All Images Sign up for our Newsletter Top Comments Delete\
  \ Sensitive alex1128 Nov 30, 2011 at 06:25PM EST +19 Reply Delete Sensitive shadowblade2584\
  \ Jul 23, 2011 at 02:06PM EDT Disaster Girl : That Bitch Crashes Know Your Meme.\
  \ +18 Reply + Add a Comment Comments (52) Display Comments Add a Comment Top Entries\
  \ This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (14) Jamie\
  \ Dubs Scientist Emeritus Chris Menning Digital Archaeologist & Archivist & Pundit\
  \ & Early Adopter (#8) peeinears Tomberry Database Moderator & French Specialist\
  \ & Pony Hater Andrew Deactivated Brad Digital Archaeologist & Treasurer & Pundit\
  \ & Gallery Housekeeper amanda b. Meme Librarian Y F Digital Archaeologist & Treasurer\
  \ & Media Maid Sophie Digital Archaeologist & Treasurer & Media Bus Boy Zach Memenator\
  \ andcallmeshirley Digital Archaeologist & Treasurer & Collection Butler Matt Secretary\
  \ of Memes shevyrolet Digital Archaeologist & Treasurer & Media Bus Boy Phillip\
  \ Hamilton Bonk Connoisseur \u25BC + Request Editorship View All Editors Today's\
  \ Top Image Galleries Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen\
  \ Green) Team Fortress 2 The Amazing Digital Circus About Our Story Site Rules Policies\
  \ and Guidelines Credits Contact Meme DB Memes Episodes News Staff Contact Extras!\
  \ Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/disaster-girl
template_id: disastergirl
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
