name: Disaster Girl
source: http://knowyourmeme.com/memes/disaster-girl
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- ''
- just as I planned...
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Disaster Girl is a photoshop meme in which an exploitable
  photo of a smiling girl is superimposed on to images of natural disasters and accidents
  to imply that she has caused some type of calamity depicted in the background. Origin
  The photograph of the girl and the burning house was taken by Dave Roth[1] in January
  2005[2] during the local fire department''s live drill training two blocks away
  from his home in Mebane, North Carolina. While observing the fire, Dave caught his
  daughter, Zoe, smiling devilishly juxtaposed against the burning house. Roth first
  uploaded the photo of his daughter, which he titled "Firestarter," to the image
  hosting service Zooomr[3] on January 2nd 2007. However, it did not receive much
  attention until later that year on November 29th when Roth submitted the same image
  to JPG Magazine[4] for an "Emotion Capture" competition. The photo was selected
  for publication in the February / March 2008 print issue of the magazine.[5] Spread
  In October 2008, JPG Magazine[6] spoke with Dave and Zoe, who were both "jazzed"
  by the attention the photo had received. By November 2008, the initial JPG Magazine
  post had gained over 95,000 views.[2] The original photo was posted to Buzzfeed[7]
  on October 27th, 2008 with a followup[8] post the next day highlighting the best
  derivatives, followed by similar posts on Digg[9], TrendHunter[10], eBaum''s World
  Forum[11] and Best Week Ever.[12] Over the years, the photo and its derivatives
  have been mentioned on Neatorama[13], photo site DamnCoolPictures[14], Cracked[15]
  and the Huffington Post.[16] Notable Examples Disaster Girl Now Roth has continued
  to post photos of Zoe on his Flickr[17] account over the years. Interview with Know
  Your Meme On December 18th, 2020, KYM interviewed Zoe as part of their editorial
  series that follows up on people featured in prominent memes. In the interview,
  we spoke with Roth to get a glimpse into what it was like growing up with her image
  plastered all around the internet — even to this day. Search Interest Search for
  Disaster Girl didn''t begin until October 2008, when the photos were posted to Buzzfeed.
  Search peaked in May 2011. External References [1] The Traveling Roths – Home [2]
  The Traveling Roths – I Have A Meme: Disaster Girl [3] Zooomr (via Wayback Machine)
  – Firestarter [4] JPG Magazine (via Wayback Machine) – Firestarter [5] JPG Magazine
  – Issue 14 [6] JPG Magazine (via Wayback Machine) – Disaster Girl is Coming for
  You [7] Buzzfeed – Disaster Girl! [8] Buzzfeed – The Amazing True Story of Disaster
  Girl [9] Digg – Make Your Own ''Disaster Girl'' Background [10] TrendHunter – Viral
  Compassion Through Photoshop [11] eBaum''s World Forum (via Wayback Machine) – Disaster
  Girl Strikes Again [12] Best Week Ever (via Wayback Machine) – Disaster Girl: The
  New Fail [13] Neatorama – Disaster Girl [14] DamnCoolPictures – Disaster Girl Grown
  Up [15] Cracked – 6 Images of Kids Too Insane to Be Real (That Totally Are) [16]
  Huffington Post – 6 Amazing Kid Photos [17] Flickr – TravelingRoths [18] - Wikipedia
  – A Girl Named Disaster [19] Macrochan (via Wayback Machine) – Disaster Boy'
aside_content: MemeStatusConfirmedType:Exploitable,PhotoshopYear2007OriginUnknownTagsimage
  macro,photoshop,mainstream,buzzfeed,exploitables,dave roth,neatorama,zooomr,zoe
  roth,firestarterAdditional ReferencesMeme Generator
added_at: '2008-12-30T13:56:56-05:00'
