name: Seal of Approval
source: http://knowyourmeme.com/memes/seal-of-approval
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- first wipe
- clean toiletpaper
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About Seal of Approval, also known as Satisfied Seal, is an advice
  animal image macro series featuring a close-up photograph of a seal with captions
  containing anecdotes about various gratifying experiences. Origin On August 18th,
  2007, Flickr[1] user Rick van Duivenboden uploaded a photograph of a Weddell seal
  at the Ecomare nature center on the island Texel in the Netherlands (shown below).
  On November 16th, 2014, Redditor Mictlantecuhtli submitted the photograph to /r/pics
  in a post titled "This is the most satisfied seal I've ever seen," to which the
  top voted comment replied "that is a seal of approval." Prior to being archived,
  the post gathered upwards of 4,600 votes (93% upvoted) and 240 comments. Spread
  The same day, Redditor boredengineer89 posted an image macro featuring the photograph
  with the caption "Standing naked over the bathroom vent / with the heat on" (shown
  below). Before the post was archived, it gained over 4,100 votes (95% upvoted) and
  240 comments on the /r/AdviceAnimals[3] subreddit. On December 11th, Redditor ButterflyPaun
  submitted a Seal of Approval image macro about a satisfying bowel movement to /r/AdviceAnimals,[4]
  garnering more than 3,700 votes (86% upvoted) and 430 comments before it was archived
  (shown below, right). On August 11th, 2015, Redditor JeffKnol posted an image macro
  expressing appreciation for a generous roommate to /r/AdviceAnimals,[5] receiving
  upwards of 7,700 votes (96% upvoted) and 640 comments in three months (shown below,
  left). On August 25th, Redditor BigTom1776 posted a Seal of Approval expressing
  satisfaction with arresting a man after a road rage incident (shown below, right).
  In two months, the post garnered over 7,800 votes (95% upvoted) and 1,600 comments
  on /r/AdviceAnimals.[6] Various Examples Search Interest External References [1]
  Flickr – Lets hug [2] Reddit – This is the most satisfied seal Ive ever seen [3]
  Reddit – Every morning this time of year [4] Reddit – This rarely happens but when
  it does [5] Reddit – My roommate is the best [6] Reddit – When taking my job as
  a Fire Marshal I never even considered this moment
aside_content: MemeStatusConfirmedYear2015OriginRedditTagsadvice animal,image macro,reddit,imgur,rick
  van duivenboden,mictlantecuhtli,ecomare nature center,netherlands,island texel,boredengineer89,butterflypaun
added_at: '2015-11-05T17:39:40-05:00'
