name: Ermahgerd
source: http://knowyourmeme.com/memes/ermahgerd
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- ermahgerd
- memes
overlay:
- center_x: 0.35
  center_y: 0.45
  angle: 0.0
  scale: 0.3
scraped_content: 'About Ermahgerd (also known as "Gersberms" and "Berks"), a rhotacized[26]
  pronunciation of "oh my god," is an image macro series featuring a photo of a young
  woman holding several books from the children’s horror fiction series Goosebumps.
  The phonetically written captions are meant to sound like a speech impediment caused
  by the use of an orthodontic retainer, often using the snowclone template "Ermahgerd
  X." Origin On March 14th, 2012, a post titled "Just a book owners smile…" was submitted
  to the /r/funny[9] subreddit with a photo of a young girl posing with three Goosebumps
  books and her mouth agape in excitement. A comment posted by Redditor plantlife[10]
  linked to a Quickmeme submission of the photo with the caption "Gersberms / Mah
  fravrit berks." The same day, the image macro was submitted in a post titled "BERKS!"[1]
  which reached the front page of Reddit accumulating over 17,000 up votes within
  two weeks. Precursors The humorous trope of "retainer lisp" has been portrayed through
  various characters in popular TV shows and films, such as Beth from the animated
  series Total Drama Island (shown left) and Stan’s sister Shelly from the animated
  television series South Park (shown right). Spread On March 15th, 2012, the image
  macro was submitted to Funnyjunk[2] by user michellemc, receiving over 18,000 views
  in less than two weeks. The same day, it was posted to the Memebase site Derp[8]
  with the title "Thurrrrr So Scurrrrry." On March 16th, YouTuber Berks Gerl uploaded
  a video titled "Mah Fravorit Berks!", which featured the original image macro accompanied
  by a voice-over narration of the caption. On March 19th, Body Building[7] forums
  member Wilsbrah posted a thread titled "Gersberms!" with the original macro embedded
  in the post. Other forum members responded to the thread using incorrect English
  mimicking the caption. On June 4th, Redditor TycoBrahe submitted a post titled "Ermahgerd!
  Cluhrnet!", which included an animated GIF of Malena Ernman performing a rendition
  of the orchestral interlude "Flight of the Bumblee." Within 16 days, the post received
  over 8,700 up votes and 270 comments. On June 16th, Graphic Design Forum[23] member
  KitchWitch submitted a thread titled "Ermahgerd", which included several notable
  image macros from the series. The meme has continued to spread on Memebase[17] and
  Tumblr[18] under the tag "#ermahgerd." As of June 20th, 2012, the “Berks” Quickmeme[3]
  page has received over 4,200 submissions, the “Ermahgerd” Meme Generator[20]page
  has received more than 1,000 items and a Facebook[21] page for “Ermahgerd, Berks”
  has accumulated over 990 likes. Various Examples Identity On March 28th, 2012, a
  post titled “BERKS Revealed” was submitted to the /r/adviceanimals[11] subreddit
  by user superdude4agze, which included a picture of a young woman with the caption
  “Ermahgerd / I’m hot” (shown left). The following day, a post comparing the facial
  features in the two photos (shown middle) reached the front page of Reddit[12],
  which sparked a lengthy discussion over the authenticity of Superdude5agze''s photo.
  On March 30th, Redditor ThazCrazy submitted a post to the /r/self[22] subreddit
  titled "Actual BERKS Girl", which included a photo of a woman named Maggie (shown
  right) whom ThazCrazy claimed was the real Berks woman. On October 15th, 2015, Vanity
  Fair published an extensive investigation into the meme, including an interview
  with Maggie Goldenberger, the woman originally pointed out by ThazCrazy. Goldberger
  spoke about how it felt to encounter herself online.[27] Maggie Goldenberger, in
  a picture from Vanity Fair Three years after first becoming an unwitting meme star,
  Goldenberger, who works as a nurse in Phoenix, still occasionally experiences the
  surreal, stupefying jolt of being ambushed by her own face online. “My eyes just
  get wide and I say, out loud, ‘This is so f--king weird.’ ” The magazine also identified
  the reddit user plantlife as the originator of the phrase "Gersberms / Mah fravrit
  berks." The article went on to tell the story of how Goldenberger and her friends
  took the original photograph. When Maggie Goldenberger was in fourth or fifth grade,
  she and her friends seriously got into playing dress-up. They would rummage through
  a dress-up box full of accessories owned by Goldenberger’s friend Kaelyn and devise
  outrageous outfits, inventing eccentric characters and snapping Polaroids of each
  other. . . “I remember having a lot of fun picking out the items,” she said, “and
  Kaelyn running downstairs to pick out books.” Kaelyn had suggested that Goldenberger
  should hold the American Girl doll tie-in books, with their saccharine pastel covers
  of smiling tween girls. Crucially, it was the Goosebumps books, with their instantly
  recognizable hyper-colored cover images by illustrator Tim Jacobus, that made the
  cut. Deciding against the coonskin cap, Goldenberger put on the vest, hoisted her
  hair up into intentionally dorky pigtails--she never wore them like that otherwise--brandished
  the chosen books, and pulled an intentionally hideous face for the camera. Normally,
  she hardly ever wore her retainer like she was supposed to, but it felt right for
  the character: she put it on for the shoot. According to the article, the embarrassing
  photo was then uploaded to Myspace and Facebook until it was discovered.[27] Animal
  Variations On June 8th, 2012, the website I Can Has Cheezburger[19] published a
  post titled "Animal Memes: Ermahgerd! Er''m a Perg!", which featured a photo of
  a pug staring at a box of Milk-Bone dog treats with the caption "Ermahgerd / merlkbehrns"
  (shown below, left). On June 16th, the pug image was submitted in a post titled
  “merlkbehrns” on the image remixing site Canvas[16], where it received several replies
  with other variations based on cute animal photos that were captioned with the snowclone
  template "Ermahgerd X" (shown below, middle, right). On June 18th, the Tumblr[15]
  blog Pleated Jeans published several images from the thread in a post which received
  over 67,300 notes within two days. The following day, the same images were published
  in a post titled "7 Super Excited ''Ermahgerd'' Animals" on the viral content site
  BuzzFeed.[14] Hurricane Irma On August 30th, 2017, Hurricane Irma developed off
  a tropical wave that moved off the west African coast, which rapidly intensified
  into a Category 3 hurricane. On September 5th, 2017, Irma was classified as a Category
  5 hurricane. On the morning of September 6th, it reached peak intensity, with winds
  up to 185 mph, tying it for the second most intense hurricanes in Atlantic history.
  On September 9th, Twitter user @ziyatong[28] tweeted a photograph of a boarded-up
  house with the words "Irma Gerd" spray-painted on the side (shown below). Within
  48 hours, the tweet gained over 22,000 likes and 64,000 retweets. Meanwhile, Twitter
  user AtterburyTCPalm posted a similar photograph of a boarded-up home decorated
  with the same graffiti (shown below, right). Meanwhile, several news sites published
  articles about the Ermahgerd-themed Hurricane Irma memes, including Miami New Times,[29]
  Heavy[30] and Newsweek.[31] Interview with Know Your Meme On January 8th, 2021,
  Know Your Meme interviewed Maggie Goldenburger about the origins of the original
  photo, history with the meme and more nine years after it spread online. Search
  Interest In its beginning, the meme was primarily referred to as "Berks" after the
  original instance of the series, but as it continued to spawn derivatives based
  on other images, the more generic term "Ermahgerd" surpassed the former in terms
  of search interest by May 2012. External References [1] Reddit – BERKS! [2] FunnyJunk
  – GERSBERMS [3] Quickmeme – BERKS [4] South Park Wiki – Shelly Marsh [5] Adventure
  Time Wiki – Lumpy Space Princess [6] Tumblr – berks [7] Body Building Forums – Gersberms!
  [8] Memebase Derp – Thurrrrr So Scurrrrry [9] Reddit – Just a book owners smile…
  [10] Reddit – plantlife [11] Reddit – BERKS Revealed [12] Reddit – BERKS ANALYSIS
  Not exactly an advice animal, but this is literally the only place to post this
  where people would care [13] Reddit – berks [14] BuzzFeed – 7 Super Excited Ermahgerd
  Animals [15] Tumblr – Pleated Jeans [16] Canvas – Posted in #funny merlkberns [17]
  Memebase – #ermahgerd [18] Tumblr – #ermahgerd [19] I Can Has Cheezburger – Animal
  Memes Ermahgerd Er''m a Perg! [20] Meme Generator – Ermahgerd [21] Facebook – Ermahgerd,
  Berks [22] Reddit – Actual BERKS Girl [23] Graphic Design Forum – Ermahgerd! [24]
  Tumblr – F--k Yeah Ermahgerd [25] Reddit – Ermahgerd! Cluhrnet! [26] Wikipedia –
  Rhotacism [27] Vanity Fair – Ermahgerddon: The Untold Story of the Ermahgerd Girl
  [28] Twitter – ziyatong [29] Miami New Times – Irmageddon 2017 [30] Heavy – Hurricane
  Irma [31] Newsweek – HURRICANE IRMA GERD HOW A 5-YEAR-OLD MEME PROMPTED A VERY 2017
  RESPONSE TO STORM IN FLORIDA'
aside_content: MemeStatusConfirmedType:Image Macro,SlangYear2012OriginRedditTagsfunnyjunk,gersberms,berks,goosebumps,berk,ermagerd,ermergerd,misspelled,err
  mah gerd,errmahgerd,ermagherd,er mah gerd,ehrmagherd,ehrmagerd,oh mer gherd,notables
  of 2012,memes of 2012,advice animals of 2012,mispronunciation,advice animalAdditional
  ReferencesUrban Dictionary
added_at: '2012-03-17T03:00:56-04:00'
