name: Left Exit 12 Off Ramp
source: https://knowyourmeme.com/memes/left-exit-12-off-ramp
keywords:
- null
text:
- style: default
  color: '#BBBBBB'
  font: thin
  anchor_x: 0.24
  anchor_y: 0.15
  angle: 0.0
  scale_x: 0.15
  scale_y: 0.22
  align: center
  start: 0.0
  stop: 1.0
- style: thin
  color: '#BBBBBB'
  font: thin
  anchor_x: 0.53
  anchor_y: 0.15
  angle: 0.0
  scale_x: 0.22
  scale_y: 0.22
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: white
  font: thin
  anchor_x: 0.46
  anchor_y: 0.85
  angle: 9.0
  scale_x: 0.32
  scale_y: 0.1
  align: center
  start: 0.0
  stop: 1.0
example:
- The Pins
- The Gutter
- Bowling Ball
overlay:
- center_x: 0.31
  center_y: 0.26
  angle: 0.0
  scale: 0.17
- center_x: 0.64
  center_y: 0.26
  angle: 0.0
  scale: 0.17
- center_x: 0.52
  center_y: 0.82
  angle: 8.0
  scale: 0.3
scraped_content: About Left Exit 12 Off Ramp is a series of exploitables in which
  a car swerving into an off ramp. On the highway sign, the meme's author photoshops
  something the author disapproves of and something they would prefer. The car swerves
  toward the preference. Origin The meme is a photoshop composite based on a YouTube
  video entitled "How to exit freeway like a boss." Uploaded on July 4th, 2013, the
  video by YouTuber[7] Fredrik Sørlie shows a car drifting into an off ramp; however,
  there are no highway signs at the off ramp. The video (shown below) received more
  than 97,000 views in four and a half years. Spread The earliest known use of the
  video as a meme was posted on December 29th, 2017 by HiddenLOL[6] user anon90. The
  post (shown below) entitled "made a template, don't know if it has potential, template
  in comments," shows car with the Swedish flag on it avoiding a photoshopped highway
  exit for "Continue being a stable first world country" and taking the exit for "Mass
  uncontrolled migration from third world nations." When shared by Redditor [3] Throwthowk,
  the post (shown below, left) received more than 275 points (94% upvoted) in less
  than one week. That day, HUGELOL[2] user dankhunt42 posted a version entitled "end
  it pls," which shows the car labeled me avoiding the exit for "A great life full
  of opportunities friends , girlfriends" for the exit "Fucking kill myself." The
  post (shown below, left) received more than 40 points in less than one week. The
  next day, on December 31st, Redditor[4] Laughing_Fish posted a variation on the
  /r/dankmemes subreddit. This version shows "A new year filled with new opportunities
  to better myself and make a difference" on the left. On the right, it reads, "Another
  year of shitposting memes on Reddit." The post (shown below, center) received more
  than 18,600 points (96% upvoted) and 120 comments in four days. On January 1st,
  2018, Imgur [5] user ArigatoKamisama posted another New Years version, featuring
  "New year new me" and "same shit different year." The post (shown below, right)
  received more than 2,100 views in three days. Various Examples External References
  [1] YouTube – cara exit highway yang betul [2] HUGELOL – end it pls [3] Reddit –
  Swedish Suicide Pill [4] Reddit – New year, new memes [5] Imgur – Back on my bullshit
  ¯\(ツ)/¯ [6] HiddenLOL – made a template, don't know if it has potential, template
  in comments [7] YouTube – How to exit freeway like a boss
aside_content: MemeStatusConfirmedType:ExploitableYear2017OriginYouTubeTagscar,off
  ramp,photoshop,wrong choice,fredrik sørlie,throwthowk,dankhunt42,arigatokamisama
added_at: '2018-01-04T15:38:12-05:00'
