name: Matrix Morpheus
source: http://knowyourmeme.com/memes/matrix-morpheus
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- what if I told you that
- reality was an illusion?
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About Matrix Morpheus is an advice animal image macro series featuring
  a screen capture of the fictional character Morpheus[1] (played by Lawrence Fishburne)
  from The Matrix franchise.[2] The captions typically follow a two line format with
  the first line reading "What if I Told You," followed by a revelation that often
  belittles futile or petty behavior, in a similar vein to the advice animal characters
  Conspiracy Keanu and Sudden Clarity Clarence. Origin While the line “What if I told
  you” was never heard in any of the Matrix films, it thought to be a paraphrased
  interpretation of a scene from The Matrix in which Morpheus informs the protagonist
  Neo (played by Keanu Reeves) that he lives in is a computer simulation (shown below,
  left). A different screen capture used in many of the image macros comes from a
  scene in which Morpheus warns Neo about the artificial intelligence programs known
  as "Agents" (shown below, right). On February 11th, 2012, Redditor haveacigaro submitted
  a post titled "Morpheus Uses a Mac" to the /r/AdviceAnimals[4] subreddit, which
  featured a screenshot of Morpheus sitting in a chair with a caption informing Macintosh
  computer users how to take a screenshot using a keyboard shortcut (shown below).
  Spread On March 27th, 2012, Redditor matthewkol186 submitted a Matrix Morpheus image
  macro with the caption "What if I told you / the side with the USB symbol will always
  be the top side" (shown below, left),[5] which received over 620 up votes and 35
  comments prior to being archived. On the following day, Redditor lindyhop411 submitted
  an image macro titled "Why I could never take Morpheus seriously" to the /r/AdviceAnimals[6]
  subreddit, which featured a screen capture of Lawrence Fishburn as the character
  Cowboy Curtis in the children's television show Pee Wee's Playhouse (shown below,
  right). Prior to being archived, the post received over 8,000 up votes and 200 comments.
  As of December 28th, 2012, the Quickmeme[3] page for "Matrix Morpheus" has received
  over 33,000 submissions. Malware On December 14th, 2018, the security news blog
  Trend Micro[9] published an article titled "Criminals Use Malicious Memes That Communicate
  With Malware," which reported that a type of remote access trojan (RAT) malware
  was using Matrix Morpheus memes posted to Twitter in order to hide "/print" commands
  (shown below). According to the malware analysis site Virus Total,[10] the malware
  began circulating in October 2018. On December 17th, a post about the discovery
  was submitted to /r/netsec.[11] Notable Examples Cat Morpheus On March 25th, 2012,
  Redditor ZeLittleMan submitted an image macro titled "Cat Morpheus" to the /r/AdviceAnimals[7]
  subreddit, which featured a black-and-white photograph of a cat wearing sunglasses
  with the caption "What if I told you / you can't catch the red dot" (shown below,
  left). Prior to being archived, the post received over 7,700 up votes and 70 comments.
  As of December 28th, 2012, the "Cat Morpheus" Quickmeme[8] page has received over
  100 submissions. Search Interest External References [1] Wikipedia – Morpheus [2]
  Wikipedia – The Matrix [3] Quickmeme – Matrix Morpheus [4] Reddit – Morpheus uses
  a Mac [5] Reddit – Matrix Morpheus [6] Reddit – Why I could never take Morpheus
  seriously [7] Reddit – Cat Morpheus [8] Quickmeme – Cat Morpheus [9] Trend Micro
  – Cybercriminals Use Malicious Memes that Communicate with Malware [10] VirusTotal
  – Application Framework [11] Reddit – /r/netsec
aside_content: MemeStatusConfirmedType:Image MacroYear2012OriginRedditTagsadvice animals,advice
  animals of 2012,advice animal,image macro,the matrix,what if i told you,haveacigaro,matthewkol186,lindyhop411,zelittleman
added_at: '2012-04-12T22:36:37-04:00'
