name: Running Away Balloon
source: https://knowyourmeme.com/memes/running-away-balloon
keywords:
- Superlmer
text:
- style: upper
  color: black
  font: comic
  anchor_x: 0.61
  anchor_y: 0.1
  angle: 0.0
  scale_x: 0.39
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: black
  font: comic
  anchor_x: 0.8
  anchor_y: 0.57
  angle: 0.0
  scale_x: 0.39
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: black
  font: comic
  anchor_x: 0.0
  anchor_y: 0.7
  angle: 0.0
  scale_x: 0.27
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- Opportunities
- Opportunities
- Shyness
overlay:
- center_x: 0.82
  center_y: 0.2
  angle: 0.0
  scale: 0.35
- center_x: 0.965
  center_y: 0.67
  angle: 0.0
  scale: 0.3
- center_x: 0.13
  center_y: 0.81
  angle: 0.0
  scale: 0.235
scraped_content: About Running Away Balloon is a two-panel exploitable webcomic featuring
  a grey character attempting to reach a yellow balloon but is being held back by
  a pink character. The meme has been used to express frustrations with the subject's
  limitations. Origin On April 21st, 2017, Facebook [1] user and webcomic artist Superlmer
  shared the original comic. In the original, the balloon is labeled "opportunities"
  and the pink character is label "shyness." The post received more than 158,000 shares,
  61,000 reactions and 7,300 comments (shown below). Roughly two weeks later, Twitter
  [2] user @drunktwi shared a Russian-language variation with the caption, "When I
  planned to go to bed early, that would be good to sleep." The tweet received more
  than 620 likes and 215 retweets in less than three years (shown below). Spread On
  December 8th, 2017, a variation was posted on 9GAG that labeled the yellow balloon
  "beautiful girls" and the pink character labeled "my face my luck my empty pockets."
  The post received more than 15,000 points and 475 comments in less than two years
  (shown below, left). The following year, on November 6th, 2018, Redditor U_ARE_BBQ
  shared a variation that received more than 900 points (98% upvoted) and 25 comments
  (shown below, center). Over the next year, others continued to share variations
  of the meme (example below, right). Various Examples Templates Search Interest Not
  available. External References [1] Facebook – Superelmer's Post [2] Twitter – @drunktwi's
  Tweet
aside_content: MemeStatusSubmissionType:ExploitableYear2017OriginFacebookTagssuperelmer,out
  of reach balloon,webcomics,running away,superlmer,drunktwi,u_are_bbq
added_at: '2019-10-25T15:06:26-04:00'
