name: Shut Up and Take My Money!
source: http://knowyourmeme.com/memes/shut-up-and-take-my-money
keywords:
- Futurama
- Philip J. Fry
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- shut up and
- take my money!
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About "Shut up And Take My Money!" is a catchphrase used to express
  enthusiastic approval toward a product or idea. It is often associated with an image
  macro featuring the character Fry from the animated television series Futurama.
  Origin On July 1st, 2010, the "Attack of the Killer App" episode aired during season
  six of the animated sitcom Futurama. In the episode, the company Mom Industries
  releases the eyePhone, a parody of the Apple iPhone. When the protagonist Fry attempts
  to purchase one at a store, he is warned by the cashier about reception and battery
  life issues to which he interrupts yelling "Shut up and take my money!" while waving
  several dollar bills (shown at the 26-second mark below). The following day, the
  German tech blog Crackajack[4] published a post about the episode and included an
  image macro of Fry with the caption "Shut up and take my money!" Spread The phrase
  is often used on web forums and image boards to express a desire to obtain a certain
  product or invention or to show approval for a proposed idea.[1] On Reddit, it is
  used as the title for posts with pictures and videos of new technology and gadgets.
  On March 7th, 2011, Redditor calivessel submitted a photo of a credit card with
  the Fry image printed on top to the /r/pics[10] subreddit. The post managed to reach
  the front page and accumulated over 4,000 upvotes prior to being archived. The /r/shutupandtakemymoney[2]
  subreddit was created for "the best, most creative, and classiest gadgets and nerdware
  on the interwebz" on April 26th, 2011. The domain for the gadget and novelty items
  retail website shutupandtakemymoney.com[6] was registered on May 3rd, 2011. The
  meme has since spread to sites like FunnyJunk[3][8], Tumblr[7] and deviantArt.[9]
  A Facebook[5] page for "Shut Up and Take My Money" has received 1,895 likes as of
  March, 7th, 2012. Exploitables The original Fry image has been used as a template
  for a number of exploitable derivatives, using the phrasal template "Shut up and
  take my (X)!" Templates Search Interest External References [1] Gametrailers.com
  – what makes you go shutup and take my money [2] Reddit – /r/shutupandtakemymoney
  [3] FunnyJunk – Shut up and take my money [4] Crackajack – Futuramas Eye Phone [5]
  Facebook – Shut Up and Taken My Money [6] shutupandtakemymoney.com – The Coolest
  Gadgets and Novelty Items on the Internet [7] Tumblr – #shut up and take my money
  [8] FunnyJunk – shut up and take my money [9] deviantArt – shut up and take my money
  [10] Reddit – Visa'
aside_content: MemeStatusConfirmedType:Catchphrase,Image Macro,Pop Culture Reference,ReactionYear2010OriginCrackajackTagsfuturama,fry,stfu,money,iphone,tv
  show quote,cash,comments,sitcom,crackajack,shut up and take my money meme,futurama
  memes
added_at: '2011-04-11T22:46:43-04:00'
