example:
- shut up and
- take my money!
keywords:
- Futurama
- Philip J. Fry
name: Shut Up and Take My Money!
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Shut Up And Take My Money! | Know Your Meme Hello! You must login\
  \ or signup first! Already a memeber? Login Now! Don't have an account? Sign up\
  \ Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos Submit\
  \ \u2192 Images Trending Most Commented Most Favorited High Score Low Score Most\
  \ Viewed All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Shut Up And Take My Money! Added 13 years ago / Updated 6 months ago Confirmed\
  \ 1,583,769 Part of a series on Futurama. [View Related Entries] Related Explainer:\
  \ What Is 'Shut Up And Take My Money' And Where Does The Quote Come From? The 'Futurama'\
  \ Buying Meme And Reaction Explained View All 281 Images Navigation About \u2022\
  \ Origin \u2022 Spread \u2022 Templates \u2022 Search Interest \u2022 External References\
  \ \u2022 Recent Images \u2022 Recent Videos About \"Shut up And Take My Money!\"\
  \ is a catchphrase used to express enthusiastic approval toward a product or idea.\
  \ It is often associated with an image macro featuring the character Fry from the\
  \ animated television series Futurama. Origin On July 1st, 2010, the \"Attack of\
  \ the Killer App\" episode aired during season six of the animated sitcom Futurama.\
  \ In the episode, the company Mom Industries releases the eyePhone, a parody of\
  \ the Apple iPhone. When the protagonist Fry attempts to purchase one at a store,\
  \ he is warned by the cashier about reception and battery life issues to which he\
  \ interrupts yelling \"Shut up and take my money!\" while waving several dollar\
  \ bills (shown at the 26-second mark below). The following day, the German tech\
  \ blog Crackajack[4] published a post about the episode and included an image macro\
  \ of Fry with the caption \"Shut up and take my money!\" Spread The phrase is often\
  \ used on web forums and image boards to express a desire to obtain a certain product\
  \ or invention or to show approval for a proposed idea.[1] On Reddit, it is used\
  \ as the title for posts with pictures and videos of new technology and gadgets.\
  \ On March 7th, 2011, Redditor calivessel submitted a photo of a credit card with\
  \ the Fry image printed on top to the /r/pics[10] subreddit. The post managed to\
  \ reach the front page and accumulated over 4,000 upvotes prior to being archived.\
  \ The /r/shutupandtakemymoney[2] subreddit was created for \"the best, most creative,\
  \ and classiest gadgets and nerdware on the interwebz\" on April 26th, 2011. The\
  \ domain for the gadget and novelty items retail website shutupandtakemymoney.com[6]\
  \ was registered on May 3rd, 2011. The meme has since spread to sites like FunnyJunk[3][8],\
  \ Tumblr[7] and deviantArt.[9] A Facebook[5] page for \"Shut Up and Take My Money\"\
  \ has received 1,895 likes as of March, 7th, 2012. Exploitables The original Fry\
  \ image has been used as a template for a number of exploitable derivatives, using\
  \ the phrasal template \"Shut up and take my (X)!\" Templates Search Interest External\
  \ References [1] Gametrailers.com \u2013 what makes you go shutup and take my money\
  \ [2] Reddit \u2013 /r/shutupandtakemymoney [3] FunnyJunk \u2013 Shut up and take\
  \ my money [4] Crackajack \u2013 Futuramas Eye Phone [5] Facebook \u2013 Shut Up\
  \ and Taken My Money [6] shutupandtakemymoney.com \u2013 The Coolest Gadgets and\
  \ Novelty Items on the Internet [7] Tumblr \u2013 #shut up and take my money [8]\
  \ FunnyJunk \u2013 shut up and take my money [9] deviantArt \u2013 shut up and take\
  \ my money [10] Reddit \u2013 Visa futurama fry stfu money iphone tv show quote\
  \ cash comments sitcom crackajack shut up and take my money meme futurama memes\
  \ Share Pin Related Entries 16 total Futurama Fry / Not Sure If I Don't Want to\
  \ Live on This ... Futurama Zoidberg / Why Not Z... Death By Snu Snu View All Related\
  \ Entries Recent Images 281 total View All Images Recent Videos 52 total View All\
  \ Videos Sign up for our Newsletter Load 61 Comments Comments 61 total 137 Shut\
  \ Up And Take My Money! 1,583,784 52 281 61 Part of a series on Futurama. [View\
  \ Related Entries] Updated Jun 14, 2024 at 06:00PM EDT by Zach. Added Apr 11, 2011\
  \ at 10:46PM EDT by Brownd. Like us on Facebook! Like 1.8M Share Save Tweet PROTIP:\
  \ Press 'i' to view the image gallery, 'v' to view the video gallery, or 'r' to\
  \ view a random entry. Related Explainer: What Is 'Shut Up And Take My Money' And\
  \ Where Does The Quote Come From? The 'Futurama' Buying Meme And Reaction Explained\
  \ Meme Status Confirmed Type: Catchphrase, Image Macro, Pop Culture Reference, Reaction\
  \ Year 2010 Origin Crackajack Tags futurama, fry, stfu, money, iphone, tv show quote,\
  \ cash, comments, sitcom, crackajack, shut up and take my money meme, futurama memes\
  \ About \"Shut up And Take My Money!\" is a catchphrase used to express enthusiastic\
  \ approval toward a product or idea. It is often associated with an image macro\
  \ featuring the character Fry from the animated television series Futurama. Origin\
  \ On July 1st, 2010, the \"Attack of the Killer App\" episode aired during season\
  \ six of the animated sitcom Futurama. In the episode, the company Mom Industries\
  \ releases the eyePhone, a parody of the Apple iPhone. When the protagonist Fry\
  \ attempts to purchase one at a store, he is warned by the cashier about reception\
  \ and battery life issues to which he interrupts yelling \"Shut up and take my money!\"\
  \ while waving several dollar bills (shown at the 26-second mark below). The following\
  \ day, the German tech blog Crackajack[4] published a post about the episode and\
  \ included an image macro of Fry with the caption \"Shut up and take my money!\"\
  \ Spread The phrase is often used on web forums and image boards to express a desire\
  \ to obtain a certain product or invention or to show approval for a proposed idea.[1]\
  \ On Reddit, it is used as the title for posts with pictures and videos of new technology\
  \ and gadgets. On March 7th, 2011, Redditor calivessel submitted a photo of a credit\
  \ card with the Fry image printed on top to the /r/pics[10] subreddit. The post\
  \ managed to reach the front page and accumulated over 4,000 upvotes prior to being\
  \ archived. The /r/shutupandtakemymoney[2] subreddit was created for \"the best,\
  \ most creative, and classiest gadgets and nerdware on the interwebz\" on April\
  \ 26th, 2011. The domain for the gadget and novelty items retail website shutupandtakemymoney.com[6]\
  \ was registered on May 3rd, 2011. The meme has since spread to sites like FunnyJunk[3][8],\
  \ Tumblr[7] and deviantArt.[9] A Facebook[5] page for \"Shut Up and Take My Money\"\
  \ has received 1,895 likes as of March, 7th, 2012. Exploitables The original Fry\
  \ image has been used as a template for a number of exploitable derivatives, using\
  \ the phrasal template \"Shut up and take my (X)!\" Templates Search Interest External\
  \ References [1] Gametrailers.com \u2013 what makes you go shutup and take my money\
  \ [2] Reddit \u2013 /r/shutupandtakemymoney [3] FunnyJunk \u2013 Shut up and take\
  \ my money [4] Crackajack \u2013 Futuramas Eye Phone [5] Facebook \u2013 Shut Up\
  \ and Taken My Money [6] shutupandtakemymoney.com \u2013 The Coolest Gadgets and\
  \ Novelty Items on the Internet [7] Tumblr \u2013 #shut up and take my money [8]\
  \ FunnyJunk \u2013 shut up and take my money [9] deviantArt \u2013 shut up and take\
  \ my money [10] Reddit \u2013 Visa Related Entries 16 total Futurama Fry / Not Sure\
  \ If I Don't Want to Live on This Planet Anymore Futurama Zoidberg / Why Not Zoidberg?\
  \ Death By Snu Snu I'm Going To Build My Own Theme Park With Blackjack and Hookers\
  \ Your Music's Bad and You Should Feel Bad Windmills do not work that way! Neutral\
  \ Response Neat Oh Wait. You're Serious? Let Me Laugh Even Harder! No Need to Thank\
  \ Me Suicide Booth View All Related Entries Recent Videos 52 total Streamable -\
  \ simple video sha... Shut Up And Take My Money! Uploaded by Don A working paper\
  \ organ made of... Shut Up And Take My Money! Uploaded by Brad Graduation Cap Demo\
  \ Shut Up And Take My Money! Uploaded by Brad Touchscreen Mirror Shut Up And Take\
  \ My Money! Uploaded by Brad It would be a good invention Shut Up And Take My Money!\
  \ Uploaded by Mart\xEDn Nicol\xE1s Ormaz\xE1bal Palma The Pontiac Stinger - The\
  \ Mos... Shut Up And Take My Money! Uploaded by Ari Spool Hexagon cake knife Shut\
  \ Up And Take My Money! Uploaded by Don Nerf US | Nerf Rival - Behind... Shut Up\
  \ And Take My Money! Uploaded by Don + Add a Video View All Videos Recent Images\
  \ 281 total Shut Up And Take My Money! Uploaded by Reddit Moments Shut Up And Take\
  \ My Money! Uploaded by Reddit Moments Shut Up And Take My Money! Uploaded by andcallmeshirley\
  \ Shut Up And Take My Money! Uploaded by Square Memester Shut Up And Take My Money!\
  \ Uploaded by Aragamanagato Shut Up And Take My Money! Uploaded by OurDeerLeader\
  \ Shut Up And Take My Money! Uploaded by Y F Shut Up And Take My Money! Uploaded\
  \ by Memister Shut Up And Take My Money! Uploaded by Bilbo Swaggins Shut Up And\
  \ Take My Money! Uploaded by mrdoctorderpy Shut Up And Take My Money! Uploaded by\
  \ malerfique Shut Up And Take My Money! Uploaded by Nedhitis + Add an Image View\
  \ All Images Sign up for our Newsletter Top Comments Delete Sensitive \xAD Jul 29,\
  \ 2011 at 08:05PM EDT SHUT UP AND TAKE MY +1CONFIRM +28 Reply Delete Sensitive Takashi.0\
  \ Jul 02, 2012 at 07:53PM EDT +6 Reply + Add a Comment Comments (61) Display Comments\
  \ Add a Comment Top Entries This Month Meme Saika Kawakita Smile GIF Event Assassination\
  \ of UnitedHealthcare CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki\
  \ Sisters Culture Pornography Site Whisper View More Suggest a Change Edit History\
  \ Entry Editors (8) Brownd Sleuth & Scrapbooker & Commentator SilverMonGoose Deactivated\
  \ Mr Bumhole #1 Fan Of Osaka Hamsteak #1 & Television Meme Historian Brad Digital\
  \ Archaeologist & Treasurer & Pundit & Gallery Housekeeper Don Administrator & Meme\
  \ Daddy SabrinaTibbetts Memepuff shevyrolet Digital Archaeologist & Treasurer &\
  \ Media Bus Boy Zach Memenator \u25BC + Request Editorship View All Editors Today's\
  \ Top Image Galleries Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen\
  \ Green) Team Fortress 2 The Amazing Digital Circus About Our Story Site Rules Policies\
  \ and Guidelines Credits Contact Meme DB Memes Episodes News Staff Contact Extras!\
  \ Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/shut-up-and-take-my-money
template_id: money
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
