name: All Your Base Are Belong to Us
source: https://knowyourmeme.com/memes/all-your-base-are-belong-to-us
keywords:
- null
text:
- style: upper
  color: palegoldenrod
  font: thick
  anchor_x: 0.025
  anchor_y: 0.7
  angle: 0.0
  scale_x: 0.95
  scale_y: 0.265
  align: center
  start: 0.0
  stop: 1.0
example:
- all your base are belong to us
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About "All Your Base Are Belong to Us" is a popular engrish catchphrase
  that grew popular across the internet as early as in 1998. An awkward translation
  of "all of your bases are now under our control", the quote originally appeared
  in the opening dialogue of Zero Wing, a 16-bit shoot''em up game released in 1989.
  Marked by poor grammar, the "All Your Base" phrase and the dialogue scene went viral
  on popular discussion forums in 2000, spawning thousands of image macros and flash
  animations featuring the slogan both on the web and in real life. Origin The phrase
  and game footage used in the meme come from the 1992 port of the 1989 side-scrolling
  arcade shooter Zero Wing,[8] released on the SEGA Mega Drive. The quote is from
  the introduction sequence of the game in which the main antagonist, the leader of
  CATS appears to announce "all your base are belong to us" during an exchange with
  the ship''s captain. The first GIF of the opening sequence is rumored to have originated
  on the Rage Games website in early 1998.[16] Additionally, the website Zany Video
  Game Quotes[11] has been credited with popularizing the GIF.[12][13] According to
  a timeline published on the site RetroGames.com,[15] the GIF was posted on the site
  Zany Video Game Quotes in "late 1998/early 1999." Captain: What happen ? Mechanic:
  Somebody set up us the bomb. Operator: We get signal. Captain: What ! Operator:
  Main screen turn on. Captain: It''s you !! CATS: How are you gentlemen !! CATS:
  All your base are belong to us. CATS: You are on the way to destruction. Captain:
  What you say !! CATS: You have no chance to survive make your time. CATS: Ha ha
  ha ha … Operator: Captain !! Captain: Take off every ''ZIG''!! Captain: You know
  what you doing. Captain: Move ''ZIG''. Captain: For great justice. Spread In June
  2000, Overclock.org posted their Zero Wing Dub Project, featuring a dubbed version
  of the introduction with Wayne Newton''s voice. The video is among the first response
  videos to the phrase. On December 16th, 2000, Tribal War Forums[14] member Bad_CRC
  submitted a thread titled "All your base are belong to us," featuring a quote from
  the opening sequence. In February 2001, Bad_CRC released a music video for a gabber
  remix of the song, which was also uploaded to Newgrounds[9] on February 16th, 2001
  (shown below). In late 2000, there was a large thread on the TribalWar forums. At
  this time, the trend also hit SomethingAwful. According to Frogstar.com, the first
  photoshop thread began in November 2000, obtaining over 2000 images. The thread
  has since been lost on account of hacking. This thread also led to the song Invasion
  of the Gabber Robots, by The Laziest Men On Mars. On February 23rd, 2001 Wired wrote
  an article on the phrase. That year, mention of "All Your Base" appeared on various
  news sites, such as the San Francisco Chronicle, The Guardian, and USA Today. In
  February 2004, North Carolina State University students hacked into the local news
  live broadcasting system that reports on weather-related closures and replaced it
  with the phrase "All your base are belong to us".[5] On June 1st, 2006, Engineers
  at YouTube replaced the site with a message reading "ALL YOUR VIDEO ARE BELONG TO
  US" as they prepared to roll out new site features.[6] "All Your Base" also appeared
  on a Chicago Fox news station, uploaded to YouTube in 2006, where Greg Lindsay from
  Inside.com compared repeating the phrase to people saying "WAZZZUP" in Budweiser
  commercials. On June 12, 2014, Elon Musk, CEO of Tesla Motors, released a blog posting
  stating that they "will not initiate patent lawsuits." The post was entitled: "All
  our Patent Are Belong to You".[7] In addition to the macros and videos, the meme
  also spawned a catchphrase of its own: For Great Justice. It is mainly used as a
  motto to encourage someone in carrying an action right to the end. Oh Internet describes
  it as: […]everyday tasks are made more humorous by adding the suffix "…for great
  justice" to a directive, invitation, or announcement. It is generally assumed that
  a person using this phrase (or any other meme) has nothing of real value to express.
  Several well-known video games such as World of Warcraft and Guild wars reference
  the line. The line also gained an article on the TV Tropes site. 2023 Zero Wing
  Rerelease On February 14th, 2023, Bitwave Games rereleased the classic Zero Wing
  on Steam[17] and other platforms, which initially drew criticism from some for not
  initially including the "All Your Base Are Belong To Us" scene. However, the Bitwave
  port was actually based on the 1989 arcade version of Zero Wing and not the Sega
  Genesis port, which included the humorous translation that spawned the meme.[18]
  However, on February 16th, following widespread coverage about the meme missing
  from the new remaster, Bitwave Games confirmed in a tweet on its official Twitter[18]
  account that the scene with CATs would be added in a patch soon, stating: Shmupers!
  CATs is coming to Zero Wing but hasn’t set us up the bomb yet. The iconic scene
  from Zero Wing, reimagined, will be included in a free patch coming soon. Thank
  you all for your patience! Then on March 2nd, 2023, Bitwave uploaded the reworked
  intro for Zero Wing that included the Sega Genesis version with the "All Your Base
  Are Belong To Us" scene to its YouTube channel, showing off a slightly redesigned
  CATs and the classic catchphrase. The video accumulated over 2,000 views in less
  than 24 hours, as well as receiving notable praise in the comments section (seen
  below). Various Examples Search Trends The rise of the All Your Base phenomenon
  also coincided with the advents in image-editing software like Photoshop, assisting
  in establishing Photoshopped images as a common medium for internet memes and mutations.
  Early derivatives took the form of image macros and Flash animations, and later
  the meme spread to YouTube videos as well. External References [1] Planet Tribes
  (via Wayback Machine) – All Your Base [2] All Your Base Are Belong To Us – All Your
  Base Are Belong To Us [3] Wikiquote – Zero Wing [4] Newgrounds – All Your Base [5]
  The Register -Wags Hijack TV [6] CNET – Youtube Prank [7] Tesla – All Our Patent
  Are Belong You [8] Wikipedia – Zero Wing [9] Newgrounds – all yor base r blong 2
  us [10] Classic Gaming – Classic Gaming [11] Wayback Machine – Zany Video Game Quotes
  [12] Wired – When Gamer Humor Attacks [13] AllYourBaseAreBelongToUs – AllYourBaseAreBelongToUs
  [14] Tribal War – All your base are belong to us [15] Web Archive – Retro Games
  [16] GameFAQs – Zero Wing [17] Steam – Zero Wing 2023 Rerelease [18] Kotaku – ‘All
  Your Base Are Belong To Us’ Game Out On Steam, But Without Famous Meme [19] Twitter
  – bitwavegames'
aside_content: MemeStatusConfirmedType:Pop Culture ReferenceYear1998OriginRage Games
  / Zany Video Game QuotesTagsengrish,videogames,somethingawful,catchphrase,classics,slogan,video
  game,video game quote,1990s,zero wing,zany video game quotes,all your base are belong
  to us meme,catsAdditional ReferencesEncyclopedia DramaticaUrban DictionaryWikipedia
added_at: '2008-12-12T15:10:09-05:00'
