example:
- nothing to do here
keywords:
- null
name: Nothing To Do Here
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Nothing To Do Here / Jet Pack Guy | Know Your Meme O HAI! You must\
  \ login or signup first! Already a memeber? Login Now! Don't have an account? Sign\
  \ up Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos\
  \ Submit \u2192 Images Trending Most Commented Most Favorited High Score Low Score\
  \ Most Viewed All Templates Upload an Image Articles News Explainers Collections\
  \ Interviews Meme Insider Magazine More Discord Newsletter Episodes Forums Meme\
  \ Store Login Abstract user icon Memes Categories Trending News Images Trending\
  \ Images Videos Trending Videos Editorials Meme Insider Magazine Newsletter Policies\
  \ and Guidelines Meme Store Old site Login Know Your Meme is the property of Literally\
  \ Media \xA92024 Literally Media. All Rights Reserved. This image Of Woman Confidently\
  \ Strolling Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years\
  \ Ago, This Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The\
  \ Anarchy Chess Memes Turns Two Years Old Today Phrase 'The Fridge Protects The\
  \ Snacks' A Growing Favorite Among Pickup Artist Influencers Jamie G, The Bosh British\
  \ Charva, Has Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also\
  \ Trending: Honey Extension Influencer Scam Renegade Raider Copypasta Assassination\
  \ of UnitedHealthcare CEO Nothing To Do Here / Jet Pack Guy Added 13 years ago /\
  \ Updated 8 days ago Confirmed 1,030,381 Part of a series on Rage Comics. [View\
  \ Related Entries] View All 198 Images Navigation About \u2022 Origin \u2022 Spread\
  \ \u2022 Various Examples \u2022 Search Interest \u2022 External References \u2022\
  \ Recent Images About \"Nothing To Do Here\" is a catchphrase associated with the\
  \ rage comic character Jet Pack Guy who escapes awkward or difficult situations\
  \ by flying away with his jet pack. It is used in a similar fashion to the jet pack\
  \ sprouting \"Spontaneous Snail\" featured in abandon thread images. Origin The\
  \ character was created on the Spanish rage comic site Cuanto Cabr\xF3n by user\
  \ premutos[1] on April 21st, 2011. The comic featured a man fleeing from a woman\
  \ with his jet pack after she informs him that she has a boyfriend. Spread An English\
  \ translated version of premutos' comic was posted to 9gag[3] in May of 2011. The\
  \ first known Jet Pack Guy comic on Reddit[4] was posted by user romanpppp on October\
  \ 1st, 2011. The thread managed to reach the front page of the f7u12 subreddit.\
  \ Since April 2011, Cuanto Cabron[10] has featured nearly 50 \u201Cnothing to do\
  \ here\u201D tagged comics and several pages of derivatives can be found on deviantArt[5],\
  \ 9gag[7], Tumblr[6][11] and FunnyJunk.[8] As of March 2012, a MemeGenerator[9]\
  \ page for Jet Pack Guy has over 250 submissions and a Facebook[2] fan page for\
  \ the character has over 120,000 likes. Various Examples Search Interest Search\
  \ queries for \"nothing to do here\" picked up in April of 2011, the same month\
  \ the first comic was posted to Cuanto Cabr\xF3n. Search hit an all time high in\
  \ February 2012. External References [1] Cuanto Cabron \u2013 Ligue fallido [2]\
  \ Facebook \u2013 Nothing To Do Here [3] 9gag \u2013 NOTHING TO DO HERE ._. [4]\
  \ Reddit \u2013 Why do they exist? [5] deviantArt \u2013 nothing to do here [6]\
  \ Tumblr \u2013 #nothing to do here [7] 9gag \u2013 nothing to do here [8] FunnyJunk\
  \ \u2013 nothing to do here [9] Meme Generator \u2013 Jet Pack Guy [10] Cuanto Cabron\
  \ \u2013 nothing to do here [11] Tumblr \u2013 Posts tagged \"Jet Pack Guy\" rage\
  \ face cuantocabron nothing to do here jet pack cuantocabr\xF3n comment comments\
  \ Share Pin Related Entries 49 total Forever Alone Me Gusta Yao Ming Face / Bitch\
  \ Please \"Y U NO\" Guy View All Related Entries Recent Images 198 total View All\
  \ Images Recent Videos 0 total There are no recent videos. Sign up for our Newsletter\
  \ Load 28 Comments Comments 28 total 68 Nothing To Do Here / Jet Pack Guy 1,030,381\
  \ 0 198 28 Part of a series on Rage Comics. [View Related Entries] Updated Dec 15,\
  \ 2024 at 03:32PM EST by LiterallyAustin. Added Aug 19, 2011 at 08:51AM EDT by Z..\
  \ Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the\
  \ image gallery, 'v' to view the video gallery, or 'r' to view a random entry. Meme\
  \ Status Confirmed Year 2011 Origin CuantoCabr\xF3n Tags rage face, cuantocabron,\
  \ nothing to do here, jet pack, cuantocabr\xF3n, comment, comments Additional References\
  \ Meme Generator About \"Nothing To Do Here\" is a catchphrase associated with the\
  \ rage comic character Jet Pack Guy who escapes awkward or difficult situations\
  \ by flying away with his jet pack. It is used in a similar fashion to the jet pack\
  \ sprouting \"Spontaneous Snail\" featured in abandon thread images. Origin The\
  \ character was created on the Spanish rage comic site Cuanto Cabr\xF3n by user\
  \ premutos[1] on April 21st, 2011. The comic featured a man fleeing from a woman\
  \ with his jet pack after she informs him that she has a boyfriend. Spread An English\
  \ translated version of premutos' comic was posted to 9gag[3] in May of 2011. The\
  \ first known Jet Pack Guy comic on Reddit[4] was posted by user romanpppp on October\
  \ 1st, 2011. The thread managed to reach the front page of the f7u12 subreddit.\
  \ Since April 2011, Cuanto Cabron[10] has featured nearly 50 \u201Cnothing to do\
  \ here\u201D tagged comics and several pages of derivatives can be found on deviantArt[5],\
  \ 9gag[7], Tumblr[6][11] and FunnyJunk.[8] As of March 2012, a MemeGenerator[9]\
  \ page for Jet Pack Guy has over 250 submissions and a Facebook[2] fan page for\
  \ the character has over 120,000 likes. Various Examples Search Interest Search\
  \ queries for \"nothing to do here\" picked up in April of 2011, the same month\
  \ the first comic was posted to Cuanto Cabr\xF3n. Search hit an all time high in\
  \ February 2012. External References [1] Cuanto Cabron \u2013 Ligue fallido [2]\
  \ Facebook \u2013 Nothing To Do Here [3] 9gag \u2013 NOTHING TO DO HERE ._. [4]\
  \ Reddit \u2013 Why do they exist? [5] deviantArt \u2013 nothing to do here [6]\
  \ Tumblr \u2013 #nothing to do here [7] 9gag \u2013 nothing to do here [8] FunnyJunk\
  \ \u2013 nothing to do here [9] Meme Generator \u2013 Jet Pack Guy [10] Cuanto Cabron\
  \ \u2013 nothing to do here [11] Tumblr \u2013 Posts tagged \"Jet Pack Guy\" Related\
  \ Entries 49 total Forever Alone Me Gusta Yao Ming Face / Bitch Please \"Y U NO\"\
  \ Guy NO. Rage Face Okay Guy Fuck Yea Rage Guy (FFFFFUUUUUUUU-) Oh Crap / OMG Rage\
  \ Face Are You Serious Face / Seriously? Cereal Guy Are You Fucking Kidding Me?\
  \ View All Related Entries Recent Videos There are no videos currently available.\
  \ + Add a Video Recent Images 198 total Nothing To Do Here / Jet Pack... Uploaded\
  \ by HyperMetalix Nothing To Do Here / Jet Pack... Uploaded by SOAD rapetime Nothing\
  \ To Do Here / Jet Pack... Uploaded by The Chairfondler Nothing To Do Here / Jet\
  \ Pack... Uploaded by Ivorykingchrono Nothing To Do Here / Jet Pack... Uploaded\
  \ by grcna Nothing To Do Here / Jet Pack... Uploaded by GigaMario5 Nothing To Do\
  \ Here / Jet Pack... Uploaded by James Nothing To Do Here / Jet Pack... Uploaded\
  \ by Z. Nothing To Do Here / Jet Pack... Uploaded by Slackin Walrus Nothing To Do\
  \ Here / Jet Pack... Uploaded by Z. Nothing To Do Here / Jet Pack... Uploaded by\
  \ Z. Nothing To Do Here / Jet Pack... Uploaded by Z. + Add an Image View All Images\
  \ Sign up for our Newsletter Top Comments Delete Sensitive Hybrid_Thing Sep 03,\
  \ 2011 at 06:37PM EDT Aw, I'd say +1 confirm since it's everywhere in the spanish\
  \ \"reddit\", aka CuantoCabr\xF3n. All reddit/4chan memes end up on CuantoCabr\xF3\
  n, but no CC memes end up in english speaking sites. +14 Reply Delete Sensitive\
  \ Dr. Give-a-crap Nov 03, 2011 at 10:57PM EDT Seen this a lot in reddit\u2026 Y\
  \ U NO CONFIRM?! +9 Reply + Add a Comment Comments (28) Display Comments Add a Comment\
  \ Top Entries This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (6) Z. Database\
  \ Moderator & Rage Comicologist Sav Rage Comicologist Hybrid_Thing Don Administrator\
  \ & Meme Daddy amanda b. Meme Librarian Brad Digital Archaeologist & Treasurer &\
  \ Pundit & Gallery Housekeeper \u25BC + Request Editorship View All Editors Today's\
  \ Top Image Galleries Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen\
  \ Green) Team Fortress 2 The Amazing Digital Circus About Our Story Site Rules Policies\
  \ and Guidelines Credits Contact Meme DB Memes Episodes News Staff Contact Extras!\
  \ Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/nothing-to-do-here-jet-pack-guy
template_id: jetpack
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
