name: Nothing To Do Here
source: http://knowyourmeme.com/memes/nothing-to-do-here-jet-pack-guy
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- nothing to do here
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About "Nothing To Do Here" is a catchphrase associated with the
  rage comic character Jet Pack Guy who escapes awkward or difficult situations by
  flying away with his jet pack. It is used in a similar fashion to the jet pack sprouting
  "Spontaneous Snail" featured in abandon thread images. Origin The character was
  created on the Spanish rage comic site Cuanto Cabrón by user premutos[1] on April
  21st, 2011. The comic featured a man fleeing from a woman with his jet pack after
  she informs him that she has a boyfriend. Spread An English translated version of
  premutos'' comic was posted to 9gag[3] in May of 2011. The first known Jet Pack
  Guy comic on Reddit[4] was posted by user romanpppp on October 1st, 2011. The thread
  managed to reach the front page of the f7u12 subreddit. Since April 2011, Cuanto
  Cabron[10] has featured nearly 50 “nothing to do here” tagged comics and several
  pages of derivatives can be found on deviantArt[5], 9gag[7], Tumblr[6][11] and FunnyJunk.[8]
  As of March 2012, a MemeGenerator[9] page for Jet Pack Guy has over 250 submissions
  and a Facebook[2] fan page for the character has over 120,000 likes. Various Examples
  Search Interest Search queries for "nothing to do here" picked up in April of 2011,
  the same month the first comic was posted to Cuanto Cabrón. Search hit an all time
  high in February 2012. External References [1] Cuanto Cabron – Ligue fallido [2]
  Facebook – Nothing To Do Here [3] 9gag – NOTHING TO DO HERE ._. [4] Reddit – Why
  do they exist? [5] deviantArt – nothing to do here [6] Tumblr – #nothing to do here
  [7] 9gag – nothing to do here [8] FunnyJunk – nothing to do here [9] Meme Generator
  – Jet Pack Guy [10] Cuanto Cabron – nothing to do here [11] Tumblr – Posts tagged
  "Jet Pack Guy"'
aside_content: MemeStatusConfirmedYear2011OriginCuantoCabrónTagsrage face,cuantocabron,nothing
  to do here,jet pack,cuantocabrón,comment,commentsAdditional ReferencesMeme Generator
added_at: '2011-08-19T08:51:43-04:00'
