name: Woman Holding Dog's Mouth
source: https://knowyourmeme.com/memes/women-holding-dogs-mouth
keywords:
- null
text:
- style: default
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.15
  angle: 0.0
  scale_x: 0.4
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: white
  font: thick
  anchor_x: 0.6
  anchor_y: 0.2
  angle: 0.0
  scale_x: 0.4
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: white
  font: thick
  anchor_x: 0.1
  anchor_y: 0.6
  angle: 0.0
  scale_x: 0.4
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- Sales Team presenting the solution in PowerPoint
- Excited Customer
- Engineering Team knowing the solution is not technically possible
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About Woman Holding Dog's Mouth is an object labeling template. It
  is used to show one person wants another to not say something unpopular, controversial
  or correct someone's wrong opinion around a group of people. The meme often has
  creator as dog persona and is used to share their unpopular humorous opinions. Origin
  The origin of the meme is unclear and the original of the image is unknown. the
  first recorded use of the meme was posted to r/suspiciouslyspecific by u/commieman420
  on the 25th of October 2019 where the image has gotten over 30,000 upvotes. Spread
  Although there was sporadic use of the meme it did not get real traction til November
  2020. The meme has been used to comment upon the Mandalorian, DC movies and religion
  & prayer. Template
aside_content: MemeStatusSubmissionType:ExploitableYear2019OriginRedditTagsdog,woman,dinner
  table,unpopular opinion,controversial opinionAdditional ReferencesMeme GeneratorReddit
added_at: '2020-11-21T14:07:15-05:00'
