name: Bad Luck Brian
source: http://knowyourmeme.com/memes/bad-luck-brian
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- falls asleep in class
- has a wet dream
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Bad Luck Brian is an advice animal-style image macro series
  featuring a photo of a blonde teenage boy wearing a plaid sweater vest and braces,
  accompanied by captions that describe a variety of embarrassing and tragic occurrences.
  Origin On January 23rd, 2012, the original instance of the meme was submitted to
  Reddit[5] by Ian Davies, a long-time friend of Kyle since elementary school, using
  a yearbook photograph of Kyle with the caption “Takes driving test . . . gets first
  DUI.” The original post received less than 5 up votes. Later that day, another macro
  was posted to Reddit[2] with the caption "Tries to stealthily fart in class / shits"
  (below right) which reached the front page of the /r/adviceanimals subreddit accumulating
  over 3,300 up votes in less than 2 months. Spread On January 29th, 2012, a collection
  of notable examples were posted on the digital marketing blog Twenty Something.[11]
  On March 12th, the series saw a resurgence in popularity when Redditor Very_Juicy
  submitted a macro to the /r/adviceanimals[3] subreddit with the caption "Falls asleep
  in class / wet dream." Within one week the post had received more than 2,900 up
  votes. On March 19th, this instance was reposted to humor site 9gag[8] where it
  received more than 48,000 likes within 24 hours. The same post was subsequently
  pinned on the social photo sharing website Pinterest[10] the same day. Later that
  month, additional collections were hosted on Buzzfeed[13] and Funny or Die.[14]
  The series has continued to spread on sites like FunnyJunk[7], Tumblr[7] and the
  /r/adviceanimals[12] subreddit. As of June 2012, the Quickmeme[1] page has received
  more than 104,047 submissions. Several Facebook pages have also been created for
  the character, with the largest[15] having more than 29,000 likes and the second[16]
  having more than 24,000. Identity Revealed On April 11th, 2012, a Redditor claiming
  to be Bad Luck Brian attempted to do an AMA thread in the Ask Me Anything subreddit,
  but the thread was removed. The moderator who removed the post left a lengthy comment[18]
  explaining why, which received more than 35,000 downvotes, making it one of the
  most downvoted comments on Reddit of all time. Redditor coyotecarl came back on
  May 8th with an AMA thread[17] on the Advice Animals subreddit. The post received
  24,722 upvotes and 2017 points overall. During the thread, he revealed his name
  is Kyle and the photo was taken as his seventh grade school photo, but the principal
  made him take it over again because he was under the impression Kyle was making
  the face on purpose. Over the course of the 3763 comments, Redditors quickly made
  Bad Luck Brian instances based on stories Kyle told. He also stated that he''s had
  relatively good luck in his life, once winning an XBox 360 and a PSP within two
  weeks (below left), he was recognized by actor Seth Rogen in public (below center)
  and played the hand chimes. (below right) Motif: Incontinence Like other advice
  animals Bear Grylls and College Freshman, a caption trend arose in which the text
  on the bottom remains consistent. After the "Tries to stealthily fart in class /
  shits" macro was submitted to Reddit, many other derivatives were produced with
  "shits" as the bottom caption. McDonald''s Advertisement On October 5th, 2018, McDonald''s
  released an advertisement featuring Kyle Craven. In the commercial, Craven discusses
  the meme and his connection to Bad Luck Brian in relation to a new contest at McDonald''s.
  Within four days, the video received more than 9,200 views (shown below, left).
  The following day, Redditor[20] Gl00by posted the image of a Reddit post sponsored
  by McDonald''s in the /r/CorporateFacepalm subreddit. The post features testimony
  from and an updated image macro featuring Craven. It reads, "I''m Bad Luck Brian:
  the internet''s unluckiest man. McDonald''s new Trick. Treat. Win! game has 1-in-4
  odds of winning great prizes instantly, and more ways to win on our App. With odds
  like that, not even Bad Luck Brian will need to win. But he might to claim his prize."
  The image macro reads, "Wins Free McFlurry Instantly / Instant Brain Freeze." The
  post received more than 1,100 points (95% upvoted) and 50 comments in two days (shown
  below, right). [This video has been removed] Related Memes Immediately Killed By
  Shadow People Immediately Killed By Shadow People refers to the bottom text of a
  Bad Luck Brian meme featuring top text reading "tries astral projection." The phrase
  became popular in ironic image macros and shitposts starting in 2019, with a cutout
  of the bottom text becoming an exploitable over the course of the next two years
  (examples shown below). Various Examples Template Search Interest Search query volume
  for "bad luck brian" picked up in January of 2012, the same month the first Quickmeme
  submissions were created. External References [1] Quickmeme – Bad Luck Brian [2]
  Reddit – Bad Luck Brian [3] Reddit – Bad Luck Brian [4] Quickmeme – Takes driving
  test gets first dui [5] Reddit – Bad Luck Brian [6] FunnyJunk – bad luck brian (login
  needed) [7] Tumblr – Bad Luck Brian [8] 9gag – Bad Luck Brian [9] Pinterest – bad
  luck brian [10] Pinterest – Fact [11] Twenty-Something – Meme dump bad luck brian
  [12] Reddit – bad luck brian [13] Buzzfeed – The Best Of The Bad Luck Brian Meme
  [14] Funny or Die via Wayback Machine- The Funniest Examples of The Bad Luck Brian
  Meme [15] Facebook – Bad Luck Brian 1 [16] Facebook – Bad Luck Brian 2 [17] Reddit
  – IAm Bad Luck Brian AMA [18] Reddit – Removal comment [19] Washington Post – Being
  Bad Luck Brian: When the meme that made you famous starts to fade away [20] Reddit
  – McDonalds trying to use memes'
aside_content: MemeStatusConfirmedType:Character,Image MacroYear2012OriginRedditRegionUnited
  StatesTagsadvice animal,unfortunate,incontinence,awkward,notables of 2012,advice,advice
  animals of 2012,full circles of 2012,yearbook,kyle craven,ian davies,very_juicy,bad
  luck brian memeAdditional ReferencesFacebookMeme GeneratorWikipedia
added_at: '2012-03-20T11:41:01-04:00'
