example:
- falls asleep in class
- has a wet dream
keywords:
- null
name: Bad Luck Brian
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Bad Luck Brian | Know Your Meme Hello! You must login or signup\
  \ first! Already a memeber? Login Now! Don't have an account? Sign up Now! Meme\
  \ Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Bad Luck Brian Added 12 years ago / Updated 8 days ago Confirmed 3,374,953\
  \ Part of a series on Advice Animals. [View Related Entries] [View Related Sub-entries]\
  \ Related Interview: Catching Up With Kyle Craven, The Face Of 'Bad Luck Brian'\
  \ View All 718 Images Featured Episode Navigation About \u2022 Origin \u2022 Spread\
  \ \u2022 Related Memes \u2022 Various Examples \u2022 Template \u2022 Search Interest\
  \ \u2022 External References \u2022 Recent Images \u2022 Recent Videos About Bad\
  \ Luck Brian is an advice animal-style image macro series featuring a photo of a\
  \ blonde teenage boy wearing a plaid sweater vest and braces, accompanied by captions\
  \ that describe a variety of embarrassing and tragic occurrences. Origin On January\
  \ 23rd, 2012, the original instance of the meme was submitted to Reddit[5] by Ian\
  \ Davies, a long-time friend of Kyle since elementary school, using a yearbook photograph\
  \ of Kyle with the caption \u201CTakes driving test .\u2009.\u2009. gets first DUI.\u201D\
  \ The original post received less than 5 up votes. Later that day, another macro\
  \ was posted to Reddit[2] with the caption \"Tries to stealthily fart in class /\
  \ shits\" (below right) which reached the front page of the /r/adviceanimals subreddit\
  \ accumulating over 3,300 up votes in less than 2 months. Spread On January 29th,\
  \ 2012, a collection of notable examples were posted on the digital marketing blog\
  \ Twenty Something.[11] On March 12th, the series saw a resurgence in popularity\
  \ when Redditor Very_Juicy submitted a macro to the /r/adviceanimals[3] subreddit\
  \ with the caption \"Falls asleep in class / wet dream.\" Within one week the post\
  \ had received more than 2,900 up votes. On March 19th, this instance was reposted\
  \ to humor site 9gag[8] where it received more than 48,000 likes within 24 hours.\
  \ The same post was subsequently pinned on the social photo sharing website Pinterest[10]\
  \ the same day. Later that month, additional collections were hosted on Buzzfeed[13]\
  \ and Funny or Die.[14] The series has continued to spread on sites like FunnyJunk[7],\
  \ Tumblr[7] and the /r/adviceanimals[12] subreddit. As of June 2012, the Quickmeme[1]\
  \ page has received more than 104,047 submissions. Several Facebook pages have also\
  \ been created for the character, with the largest[15] having more than 29,000 likes\
  \ and the second[16] having more than 24,000. Identity Revealed On April 11th, 2012,\
  \ a Redditor claiming to be Bad Luck Brian attempted to do an AMA thread in the\
  \ Ask Me Anything subreddit, but the thread was removed. The moderator who removed\
  \ the post left a lengthy comment[18] explaining why, which received more than 35,000\
  \ downvotes, making it one of the most downvoted comments on Reddit of all time.\
  \ Redditor coyotecarl came back on May 8th with an AMA thread[17] on the Advice\
  \ Animals subreddit. The post received 24,722 upvotes and 2017 points overall. During\
  \ the thread, he revealed his name is Kyle and the photo was taken as his seventh\
  \ grade school photo, but the principal made him take it over again because he was\
  \ under the impression Kyle was making the face on purpose. Over the course of the\
  \ 3763 comments, Redditors quickly made Bad Luck Brian instances based on stories\
  \ Kyle told. He also stated that he's had relatively good luck in his life, once\
  \ winning an XBox 360 and a PSP within two weeks (below left), he was recognized\
  \ by actor Seth Rogen in public (below center) and played the hand chimes. (below\
  \ right) Motif: Incontinence Like other advice animals Bear Grylls and College Freshman,\
  \ a caption trend arose in which the text on the bottom remains consistent. After\
  \ the \"Tries to stealthily fart in class / shits\" macro was submitted to Reddit,\
  \ many other derivatives were produced with \"shits\" as the bottom caption. McDonald's\
  \ Advertisement On October 5th, 2018, McDonald's released an advertisement featuring\
  \ Kyle Craven. In the commercial, Craven discusses the meme and his connection to\
  \ Bad Luck Brian in relation to a new contest at McDonald's. Within four days, the\
  \ video received more than 9,200 views (shown below, left). The following day, Redditor[20]\
  \ Gl00by posted the image of a Reddit post sponsored by McDonald's in the /r/CorporateFacepalm\
  \ subreddit. The post features testimony from and an updated image macro featuring\
  \ Craven. It reads, \"I'm Bad Luck Brian: the internet's unluckiest man. McDonald's\
  \ new Trick. Treat. Win! game has 1-in-4 odds of winning great prizes instantly,\
  \ and more ways to win on our App. With odds like that, not even Bad Luck Brian\
  \ will need to win. But he might to claim his prize.\" The image macro reads, \"\
  Wins Free McFlurry Instantly / Instant Brain Freeze.\" The post received more than\
  \ 1,100 points (95% upvoted) and 50 comments in two days (shown below, right). [This\
  \ video has been removed] Related Memes Immediately Killed By Shadow People Immediately\
  \ Killed By Shadow People refers to the bottom text of a Bad Luck Brian meme featuring\
  \ top text reading \"tries astral projection.\" The phrase became popular in ironic\
  \ image macros and shitposts starting in 2019, with a cutout of the bottom text\
  \ becoming an exploitable over the course of the next two years (examples shown\
  \ below). Various Examples Template Search Interest Search query volume for \"bad\
  \ luck brian\" picked up in January of 2012, the same month the first Quickmeme\
  \ submissions were created. External References [1] Quickmeme \u2013 Bad Luck Brian\
  \ [2] Reddit \u2013 Bad Luck Brian [3] Reddit \u2013 Bad Luck Brian [4] Quickmeme\
  \ \u2013 Takes driving test gets first dui [5] Reddit \u2013 Bad Luck Brian [6]\
  \ FunnyJunk \u2013 bad luck brian (login needed) [7] Tumblr \u2013 Bad Luck Brian\
  \ [8] 9gag \u2013 Bad Luck Brian [9] Pinterest \u2013 bad luck brian [10] Pinterest\
  \ \u2013 Fact [11] Twenty-Something \u2013 Meme dump bad luck brian [12] Reddit\
  \ \u2013 bad luck brian [13] Buzzfeed \u2013 The Best Of The Bad Luck Brian Meme\
  \ [14] Funny or Die via Wayback Machine- The Funniest Examples of The Bad Luck Brian\
  \ Meme [15] Facebook \u2013 Bad Luck Brian 1 [16] Facebook \u2013 Bad Luck Brian\
  \ 2 [17] Reddit \u2013 IAm Bad Luck Brian AMA [18] Reddit \u2013 Removal comment\
  \ [19] Washington Post \u2013 Being Bad Luck Brian: When the meme that made you\
  \ famous starts to fade away [20] Reddit \u2013 McDonalds trying to use memes advice\
  \ animal unfortunate incontinence awkward notables of 2012 advice advice animals\
  \ of 2012 full circles of 2012 yearbook kyle craven ian davies very_juicy bad luck\
  \ brian meme Share Pin Related Entries 115 total Ermahgerd Overly Attached Girlfriend\
  \ Scumbag Steve Good Guy Greg View All Related Entries Sub-entries 1 total Immediately\
  \ Killed By Shadow ... Recent Images 718 total View All Images Recent Videos 51\
  \ total View All Videos Sign up for our Newsletter Load 201 Comments Comments 201\
  \ total 156 Bad Luck Brian 3,374,953 51 718 201 Part of a series on Advice Animals.\
  \ [View Related Entries] [View Related Sub-entries] Updated Dec 15, 2024 at 03:42PM\
  \ EST by LiterallyAustin. Added Mar 20, 2012 at 11:41AM EDT by Don. Like us on Facebook!\
  \ Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to\
  \ view the video gallery, or 'r' to view a random entry. Related Interview: Catching\
  \ Up With Kyle Craven, The Face Of 'Bad Luck Brian' Featured Episode Meme Status\
  \ Confirmed Type: Character, Image Macro Year 2012 Origin Reddit Region United States\
  \ Tags advice animal, unfortunate, incontinence, awkward, notables of 2012, advice,\
  \ advice animals of 2012, full circles of 2012, yearbook, kyle craven, ian davies,\
  \ very_juicy, bad luck brian meme Additional References Facebook Meme Generator\
  \ Wikipedia About Bad Luck Brian is an advice animal-style image macro series featuring\
  \ a photo of a blonde teenage boy wearing a plaid sweater vest and braces, accompanied\
  \ by captions that describe a variety of embarrassing and tragic occurrences. Origin\
  \ On January 23rd, 2012, the original instance of the meme was submitted to Reddit[5]\
  \ by Ian Davies, a long-time friend of Kyle since elementary school, using a yearbook\
  \ photograph of Kyle with the caption \u201CTakes driving test .\u2009.\u2009. gets\
  \ first DUI.\u201D The original post received less than 5 up votes. Later that day,\
  \ another macro was posted to Reddit[2] with the caption \"Tries to stealthily fart\
  \ in class / shits\" (below right) which reached the front page of the /r/adviceanimals\
  \ subreddit accumulating over 3,300 up votes in less than 2 months. Spread On January\
  \ 29th, 2012, a collection of notable examples were posted on the digital marketing\
  \ blog Twenty Something.[11] On March 12th, the series saw a resurgence in popularity\
  \ when Redditor Very_Juicy submitted a macro to the /r/adviceanimals[3] subreddit\
  \ with the caption \"Falls asleep in class / wet dream.\" Within one week the post\
  \ had received more than 2,900 up votes. On March 19th, this instance was reposted\
  \ to humor site 9gag[8] where it received more than 48,000 likes within 24 hours.\
  \ The same post was subsequently pinned on the social photo sharing website Pinterest[10]\
  \ the same day. Later that month, additional collections were hosted on Buzzfeed[13]\
  \ and Funny or Die.[14] The series has continued to spread on sites like FunnyJunk[7],\
  \ Tumblr[7] and the /r/adviceanimals[12] subreddit. As of June 2012, the Quickmeme[1]\
  \ page has received more than 104,047 submissions. Several Facebook pages have also\
  \ been created for the character, with the largest[15] having more than 29,000 likes\
  \ and the second[16] having more than 24,000. Identity Revealed On April 11th, 2012,\
  \ a Redditor claiming to be Bad Luck Brian attempted to do an AMA thread in the\
  \ Ask Me Anything subreddit, but the thread was removed. The moderator who removed\
  \ the post left a lengthy comment[18] explaining why, which received more than 35,000\
  \ downvotes, making it one of the most downvoted comments on Reddit of all time.\
  \ Redditor coyotecarl came back on May 8th with an AMA thread[17] on the Advice\
  \ Animals subreddit. The post received 24,722 upvotes and 2017 points overall. During\
  \ the thread, he revealed his name is Kyle and the photo was taken as his seventh\
  \ grade school photo, but the principal made him take it over again because he was\
  \ under the impression Kyle was making the face on purpose. Over the course of the\
  \ 3763 comments, Redditors quickly made Bad Luck Brian instances based on stories\
  \ Kyle told. He also stated that he's had relatively good luck in his life, once\
  \ winning an XBox 360 and a PSP within two weeks (below left), he was recognized\
  \ by actor Seth Rogen in public (below center) and played the hand chimes. (below\
  \ right) Motif: Incontinence Like other advice animals Bear Grylls and College Freshman,\
  \ a caption trend arose in which the text on the bottom remains consistent. After\
  \ the \"Tries to stealthily fart in class / shits\" macro was submitted to Reddit,\
  \ many other derivatives were produced with \"shits\" as the bottom caption. McDonald's\
  \ Advertisement On October 5th, 2018, McDonald's released an advertisement featuring\
  \ Kyle Craven. In the commercial, Craven discusses the meme and his connection to\
  \ Bad Luck Brian in relation to a new contest at McDonald's. Within four days, the\
  \ video received more than 9,200 views (shown below, left). The following day, Redditor[20]\
  \ Gl00by posted the image of a Reddit post sponsored by McDonald's in the /r/CorporateFacepalm\
  \ subreddit. The post features testimony from and an updated image macro featuring\
  \ Craven. It reads, \"I'm Bad Luck Brian: the internet's unluckiest man. McDonald's\
  \ new Trick. Treat. Win! game has 1-in-4 odds of winning great prizes instantly,\
  \ and more ways to win on our App. With odds like that, not even Bad Luck Brian\
  \ will need to win. But he might to claim his prize.\" The image macro reads, \"\
  Wins Free McFlurry Instantly / Instant Brain Freeze.\" The post received more than\
  \ 1,100 points (95% upvoted) and 50 comments in two days (shown below, right). [This\
  \ video has been removed] Related Memes Immediately Killed By Shadow People Immediately\
  \ Killed By Shadow People refers to the bottom text of a Bad Luck Brian meme featuring\
  \ top text reading \"tries astral projection.\" The phrase became popular in ironic\
  \ image macros and shitposts starting in 2019, with a cutout of the bottom text\
  \ becoming an exploitable over the course of the next two years (examples shown\
  \ below). Various Examples Template Search Interest Search query volume for \"bad\
  \ luck brian\" picked up in January of 2012, the same month the first Quickmeme\
  \ submissions were created. External References [1] Quickmeme \u2013 Bad Luck Brian\
  \ [2] Reddit \u2013 Bad Luck Brian [3] Reddit \u2013 Bad Luck Brian [4] Quickmeme\
  \ \u2013 Takes driving test gets first dui [5] Reddit \u2013 Bad Luck Brian [6]\
  \ FunnyJunk \u2013 bad luck brian (login needed) [7] Tumblr \u2013 Bad Luck Brian\
  \ [8] 9gag \u2013 Bad Luck Brian [9] Pinterest \u2013 bad luck brian [10] Pinterest\
  \ \u2013 Fact [11] Twenty-Something \u2013 Meme dump bad luck brian [12] Reddit\
  \ \u2013 bad luck brian [13] Buzzfeed \u2013 The Best Of The Bad Luck Brian Meme\
  \ [14] Funny or Die via Wayback Machine- The Funniest Examples of The Bad Luck Brian\
  \ Meme [15] Facebook \u2013 Bad Luck Brian 1 [16] Facebook \u2013 Bad Luck Brian\
  \ 2 [17] Reddit \u2013 IAm Bad Luck Brian AMA [18] Reddit \u2013 Removal comment\
  \ [19] Washington Post \u2013 Being Bad Luck Brian: When the meme that made you\
  \ famous starts to fade away [20] Reddit \u2013 McDonalds trying to use memes Related\
  \ Entries 115 total Ermahgerd Overly Attached Girlfriend Scumbag Steve Good Guy\
  \ Greg Ridiculously Photogenic Guy Philosoraptor Annoying Facebook Girl The Most\
  \ Interesting Man in the World Socially Awkward Penguin Bear Grylls / Better Drink\
  \ My Own Piss Successful Black Man PTSD Clarinet Boy View All Related Entries Sub-entries\
  \ 1 total Immediately Killed By Shadow People Recent Videos 51 total What Happened\
  \ to Bad Luck Brian? Bad Luck Brian Uploaded by Zach Bad Luck Brian On What It's\
  \ L... Bad Luck Brian Uploaded by Zach Bad Luck Brian - Masterplan (... Bad Luck\
  \ Brian Uploaded by Y F Bad Luck Brian Bad Luck Brian Uploaded by Y F Best Of Bad\
  \ Luck Brian Montage Bad Luck Brian Uploaded by shevyrolet Bad Luck Brian Memes\
  \ #4 Bad Luck Brian Uploaded by shevyrolet 9GAG Q&A x Bad Luck Brian Bad Luck Brian\
  \ Uploaded by shevyrolet Vime - Bad Luck Brian Bad Luck Brian Uploaded by shevyrolet\
  \ + Add a Video View All Videos Recent Images 718 total Bad Luck Brian Uploaded\
  \ by Reddit Moments Bad Luck Brian Uploaded by Yngve64 Bad Luck Brian Uploaded by\
  \ Reddit Moments Bad Luck Brian Uploaded by Zach Bad Luck Brian Uploaded by Rebecca\
  \ Rhodes Bad Luck Brian Uploaded by Rebecca Rhodes Bad Luck Brian Uploaded by Rebecca\
  \ Rhodes Bad Luck Brian Uploaded by Rebecca Rhodes Bad Luck Brian Uploaded by Rebecca\
  \ Rhodes Bad Luck Brian Uploaded by Rebecca Rhodes Bad Luck Brian Uploaded by Shovelz\
  \ Bad Luck Brian Uploaded by Rebecca Rhodes + Add an Image View All Images Sign\
  \ up for our Newsletter Top Comments Delete Sensitive Tom Tom May 23, 2012 at 07:10PM\
  \ EDT Guys, Socially Awkward Penguin is about\u2026 well, socially awkward moments.\
  \ And this meme is about bad luck, there is a big difference. +70 Reply Delete Sensitive\
  \ InglipEfuner Mar 20, 2012 at 04:56PM EDT Socially Awkward penguin + Shit = Bad\
  \ Luck Brian +57 Reply + Add a Comment Comments (201) Display Comments Add a Comment\
  \ Top Entries This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (12) Don Administrator\
  \ & Meme Daddy amanda b. Meme Librarian Brad Digital Archaeologist & Treasurer &\
  \ Pundit & Gallery Housekeeper RandomMan Database Moderator & God Tier Swag & Protip\
  \ Advisor & Karma Tycoon & Meme Boi Jill Database Moderator & Karma Philanthropist\
  \ & Meme Taxonomist & Fleet Admiral & Amish Z. Database Moderator & Rage Comicologist\
  \ SabrinaTibbetts Memepuff Y F Digital Archaeologist & Treasurer & Media Maid Matt\
  \ Secretary of Memes shevyrolet Digital Archaeologist & Treasurer & Media Bus Boy\
  \ Phillip Hamilton Bonk Connoisseur Zach Memenator \u25BC + Request Editorship View\
  \ All Editors Today's Top Image Galleries Assassination of UnitedHealthcare CEO\
  \ Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing Digital Circus About\
  \ Our Story Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes\
  \ News Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/bad-luck-brian
template_id: blb
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
