name: Confession Bear
source: http://knowyourmeme.com/memes/confession-bear
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- i stole
- the pic-i-nic basket
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Confession Bear is an advice animal image macro series featuring
  a photo of a Malayan sun bear leaning against a log. The images are captioned with
  confessions about taboo behaviors and controversial opinions that are often kept
  secret for fear of being ostracized. Origin The original bear photo (shown below,
  left) was taken by photojournalist Clemens Bilan and was submitted to the stock
  photo website Getty Images[14] on April 12th, 2007. Several years later on June
  21st, 2012, Redditor F-18Bro submitted a post titled "I have a lot of weird stuff
  that I''d like to b able to confess to reddit so i can get it off my chest, so I
  made Confession Bear"[1], which included another image macro of the bear with the
  caption "I absolutely love / the smell of my own balls" (shown below, right). Within
  four days, the post received over 13,000 up votes and 1,100 comments. Spread On
  June 21st, 2012, several hours after F-18Bro''s Reddit post, a page for "Confession
  Bear" was created on the image macro website Quickmeme.[3] The same day, the single
  topic blog ConfessionBear.com[6] was launched and the @ConfessionBear_ Twitter[8]
  account was created. Also on June 21st, Redditor Zmo64 submitted a post titled "Confession
  Bear", featuring a Bear Grylls image macro with the caption "Sometimes / I drink
  my own piss" (shown below, left). Shortly after, Redditor PhtoJoe submitted a Futurama
  Fry example commenting on the captions used in the series (shown below, right).
  On June 23rd, the Internet humor site The FW[11] published a post titled "Funniest
  Memes of the Week", which featured Confession Bear as the staff favorite. The meme
  has continued to spread on the microblogging site Tumblr under the tag "#confession
  bear."[10] As of June 25th, 2012, the Quickmeme page has accumulated over 1,800
  submissions. Notable Examples Confession Tiger On August 6th, 2012, Redditor Zachcvh
  submitted an image macro of a bored-looking tiger paired with the caption "I ate
  that bear" in an /r/AdviceAnimals post titled "Confession Tiger."[31] In the following
  24 hours, a number of additional "Confession Tiger", also known as Terrible Tiger,
  image macros placing the tiger and the bear in a rivalry were submitted to the subreddit.
  Throughout 2012 and 2013, at least 80 image macro instances of the Confession Tiger
  were submitted to Reddit''s /r/AdviceAnimals[32], although many of them turned out
  to be reposts or variations on the existing theme of the tiger''s jealousy towards
  the bear. Confession Kid On April 27th, 2013, Redditor Notmiefault submitted an
  image macro titled "Confession Kid" to the /r/AdviceAnimals[2] subreddit, in which
  the OP recalled his naive belief as a child that automatic doors were controlled
  by an unseen operator using a surveillance camera (shown below, left). Throughout
  May, dozens of additional Confession Kid image macros looking back on embarrassing
  memories and tales from childhood continued to surface on Reddit''s /r/AdviceAnimals.
  Murder Confession Controversy On April 7th, 2013, Redditor Naratto submitted a Confession
  Bear image macro to the /r/AdviceAnimals[15] subreddit, which included a caption
  confessing to the murder of his sister''s meth-addicted boyfriend (shown below).
  Within 24 hours, the post received over 10,100 up votes and 3,100 comments. In the
  comments section of the post, Redditors began discussing the authenticity of the
  confession, with many noting its similarity to a scene in which the character Walt
  witnesses a heroin addict die in the television drama series Breaking Bad.[16] Other
  Redditors posted his name, Facebook page, employer and other personally identifiable
  information in the comments section, which were subsequently removed by moderators.
  Naratto responded by submitting a Super Cool Ski Instructor image macro in a new
  post on the /r/AdviceAnimals subreddit,[25] claiming that the confession was just
  a joke with "some truth behind it" (shown below) before deleting his entire account.
  The same day, Redditor Alcoholocaustic submitted a post to the /r/KarmaConspiracy[19]
  subreddit, which accused Naratto of posting the Confession Bear image macro to gain
  karma on the site. Within 24 hours, the post gained upwards of 2,000 up votes and
  120 comments. On April 8th, Redditor lemon_difficult submitted a Confession Bear
  image macro to the /r/circlejerk[20] subreddit, featuring a caption confessing to
  the murder of an Office Depot employee with his own stapler (shown below). In the
  following eight hours, the post accumulated more than 4,000 up votes and 130 comments.
  Also on April 8th, the Internet news blog The Daily Dot[17] published an article
  about the Reddit post, noting that a murder had been previously confessed on an
  Internet support group in 1998. Also on April 8th, the confession was reported on
  by several other news sites, including Gawker,[18] Examiner,[21] UpRoxx,[22] International
  Business Times[23] and MSN.[24] Several image macros referencing the confession
  were created shortly thereafter, featuring other advice animal characters like Internet
  Husband, Futurama Fry and Bad Luck Brian (shown below). Naratto''s Identity Upon
  discovering that Naratto did not use an ad hoc account (also known as a throwaway
  account) to post his Confession Bear image macro, Redditors began sifting through
  his post history to gather clues about his real identity, soon leading to the doxing
  of his age, birthdate, middle name, military record and work information. His handle
  Naratto was also traced to a long-forgotten Twitter account[26] that belongs to
  a San Diego resident named Colton R. Goodbrand. On April 10th, Gawker[27] published
  an article detailing Naratto''s online identity with numerous links to his social
  media profiles on Twitter, MySpace and LinkedIn, as well as a YouTube video starring
  Goodbrand. Three days later, a San Diego NBC news affiliate[30] reported that the
  local police had received a tip about the Gawker post and were launching an investigation
  with their cold case team. On April 16th, Gawker received an e-mail from Goodbrand
  confirming that he did make the Confession Bear post and threatening legal action
  if the site didn''t remove the article containing his personal information. As of
  April 17th, the post is still online, but a similar post on the Daily Mail[29] has
  been removed. Search Interest External References [1] Reddit – Original Post [2]
  Quick Meme – First QuickMeme Post [3] Quick Meme – Confession Bear [4] BuzzFeed
  – Sad Baby Animals [5] Kiss Funny – Empathy Bear [6] ConfessionBear.com (via Wayback
  Machine) – Confession Bear / snapshot October 17 2012 [7] Livejournal Best Photos
  of 2007 – the animals [8] Twitter – Confession Bear_ [9] Reddit – Confession Bear
  [10] Tumblr – posts tagged #confession bear [11] The FW – Funniest Memes of the
  Week [12] Reddit – Confusion about Confession Bear [13] Wildlife Direct – Fact file
  The dark side of the wildlife trade [14] Getty Images – Little Sun Bear [15] Reddit
  – Finally have the guts to say it [16] AMC – Breaking Bad Walts Indecision [17]
  The Daily Dot – Redditor uses popular meme to confess a murder [18] Gawker – Redditor
  confesses to murder with meme [19] Reddit – Guy murders someone and then makes a
  Confession Bear about it [20] Reddit – Finally had the guts to say it [21] Examiner
  (via Wayback Machine) – Reddit murder confession / snapshot April 13 2013 [22] UpRoxx
  – Did a murderer use confession bear [23] IBI Times – Reddit Murder Confession [24]
  MSN (via Wayback Machine) – Someone maybe confessed to a murder / snapshot April
  12 2013 [25] Reddit – In hindsight [26] Twitter – @Naratto [27] Gawker – Is This
  the Redditor Who Claimed to Have Murdered His Sister’s Abusive Ex? [28] Gawker –
  Redditor Who Claimed to Have Murdered His Sister’s Ex Admits He Claimed to Have
  Murdered His Sister’s Ex [29] The Daily Mail – Is this the 24-year-old Reddit user
  accused of using meme to confess murder? (Removed) [30] 7 San Diego – Police Investigate
  Alleged Online Murder Confession [31] Reddit – Confession Tiger [32] Reddit – Search
  Results for Confession Tiger'
aside_content: MemeStatusConfirmedType:AnimalYear2012OriginRedditTagsfunny,reddit,advice
  animal,advice animals of 2012,animals of 2012,confession,confession kid,confession
  tiger,image macro,clemens bilan,f-18bro,zmo64,phtojoe,zachcvh,notmiefault,naratto,alcoholocaustic,lemon_difficult
added_at: '2012-06-21T08:08:30-04:00'
