example:
- stop trying to make fetch happen
- it's not going to happen
keywords:
- null
name: Stop Trying to Make Fetch Happen
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Stop Trying to Make Fetch Happen | Know Your Meme Hello! You must\
  \ login or signup first! Already a memeber? Login Now! Don't have an account? Sign\
  \ up Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos\
  \ Submit \u2192 Images Trending Most Commented Most Favorited High Score Low Score\
  \ Most Viewed All Templates Upload an Image Articles News Explainers Collections\
  \ Interviews Meme Insider Magazine More Discord Newsletter Episodes Forums Meme\
  \ Store Login Abstract user icon Memes Categories Trending News Images Trending\
  \ Images Videos Trending Videos Editorials Meme Insider Magazine Newsletter Policies\
  \ and Guidelines Meme Store Old site Login Know Your Meme is the property of Literally\
  \ Media \xA92024 Literally Media. All Rights Reserved. This image Of Woman Confidently\
  \ Strolling Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years\
  \ Ago, This Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The\
  \ Anarchy Chess Memes Turns Two Years Old Today Phrase 'The Fridge Protects The\
  \ Snacks' A Growing Favorite Among Pickup Artist Influencers Jamie G, The Bosh British\
  \ Charva, Has Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also\
  \ Trending: Honey Extension Influencer Scam Renegade Raider Copypasta Assassination\
  \ of UnitedHealthcare CEO Stop Trying to Make Fetch Happen Added 10 years ago /\
  \ Updated about a year ago Confirmed 295,043 Part of a series on Mean Girls. [View\
  \ Related Entries] View All 34 Images Navigation About \u2022 Origin \u2022 Spread\
  \ \u2022 Notable Examples \u2022 Search Interest \u2022 External References \u2022\
  \ Recent Images \u2022 Recent Videos About \"Stop Trying to Make Fetch Happen\"\
  \ is a memorable quote uttered by the character Regina George in the 2004 teen comedy\
  \ film Mean Girls to discourage her friend Gretchen from using the slang term \"\
  fetch.\" The quote inspired the creation of an image macro series using the phrasal\
  \ template \"Stop trying to make X happen / It's not going to happen.\" Origin In\
  \ Mean Girls, released on April 30th, 2004, the character Regina George (played\
  \ by Rachel McAdams) scolds her friend Gretchen Wieners (played by Lacey Chabert)\
  \ for using the term \"fetch\" as a synonym for \"cool.\" Gretchen: \"That is so\
  \ fetch!\" Regina: \"Gretchen, stop trying to make fetch happen! It's not going\
  \ to happen!\" On March 1st, 2012, Redditor Keilantra submitted an image macro using\
  \ a screen capture of McAdams in Mean Girls with a caption urging Google to abandon\
  \ their efforts with the Google+ social networking service to /r/funny.[5] Prior\
  \ to being archived, the post gained over 1,000 upvotes and 60 comments. Spread\
  \ On September 25th, 2012, an image macro mocking Microsoft commercials promoting\
  \ their Internet Explorer web browser was posted to /r/AdviceAnimals[3] (shown below).\
  \ Before the post was archived, it accumulated more than 8,500 upvotes and 380 comments.\
  \ On January 27th, 2013, Redditor TrueWarrior submitted an image macro mocking Internet\
  \ Explorer's frequent attempts to make itself a default web browser to /r/AdviceAnimals[1]\
  \ (shown below, left). Prior to being archived, the post gained over 5,200 upvotes\
  \ and 65 comments. On March 17th, Redditor Drum Zildjian71 posted an image macro\
  \ criticizing Facebook's \"gift\" feature to /r/AdviceAnimals,[4] where it received\
  \ upwards of 12,300 upvotes and 150 comments before it was archived (shown below,\
  \ right). On January 21st, 2014, Redditor dubman42 posted an image macro mocking\
  \ the software company Adobe's promotion of the McAfee virus scanning program to\
  \ /r/AdviceAnimals (shown below, left). In the following four months, the post garnered\
  \ more than 11,000 upvotes and 210 comments. On June 4th, Redditor j2249 submitted\
  \ a Regina George image macro joking about iPhone keyboards mistakenly replacing\
  \ the word \"f--king\" with \"ducking\" to /r/AdviceAnimals,[2] gaining over 18,400\
  \ upvotes and 560 comments in the first 24 hours (shown below, right). Notable Examples\
  \ Search Interest External References [1] Reddit \u2013 Everytime I run Internet\
  \ Explorer by accident [2] Reddit \u2013 Dear Apple I would never use that word\
  \ in my life [3] Reddit \u2013 Every time I see the new Internet Explorer commercial\
  \ [4] Reddit \u2013 Facebook, we need to talk [5] Reddit \u2013 Google+ Share Pin\
  \ Related Entries 6 total Glen Coco Oh My God, Karen, You Can\u2019t J... Get In\
  \ Loser, We're Going Sho... So You Agree View All Related Entries Recent Images\
  \ 34 total View All Images Recent Videos 1 total View All Videos Sign up for our\
  \ Newsletter Load 37 Comments Comments 37 total 6 Stop Trying to Make Fetch Happen\
  \ 295,044 1 34 37 Part of a series on Mean Girls. [View Related Entries] Updated\
  \ Oct 04, 2023 at 12:06PM EDT by Don. Added Jun 04, 2014 at 04:04PM EDT by Don.\
  \ Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the\
  \ image gallery, 'v' to view the video gallery, or 'r' to view a random entry. Meme\
  \ Status Confirmed Year 2012 Origin Reddit Tags none... About \"Stop Trying to Make\
  \ Fetch Happen\" is a memorable quote uttered by the character Regina George in\
  \ the 2004 teen comedy film Mean Girls to discourage her friend Gretchen from using\
  \ the slang term \"fetch.\" The quote inspired the creation of an image macro series\
  \ using the phrasal template \"Stop trying to make X happen / It's not going to\
  \ happen.\" Origin In Mean Girls, released on April 30th, 2004, the character Regina\
  \ George (played by Rachel McAdams) scolds her friend Gretchen Wieners (played by\
  \ Lacey Chabert) for using the term \"fetch\" as a synonym for \"cool.\" Gretchen:\
  \ \"That is so fetch!\" Regina: \"Gretchen, stop trying to make fetch happen! It's\
  \ not going to happen!\" On March 1st, 2012, Redditor Keilantra submitted an image\
  \ macro using a screen capture of McAdams in Mean Girls with a caption urging Google\
  \ to abandon their efforts with the Google+ social networking service to /r/funny.[5]\
  \ Prior to being archived, the post gained over 1,000 upvotes and 60 comments. Spread\
  \ On September 25th, 2012, an image macro mocking Microsoft commercials promoting\
  \ their Internet Explorer web browser was posted to /r/AdviceAnimals[3] (shown below).\
  \ Before the post was archived, it accumulated more than 8,500 upvotes and 380 comments.\
  \ On January 27th, 2013, Redditor TrueWarrior submitted an image macro mocking Internet\
  \ Explorer's frequent attempts to make itself a default web browser to /r/AdviceAnimals[1]\
  \ (shown below, left). Prior to being archived, the post gained over 5,200 upvotes\
  \ and 65 comments. On March 17th, Redditor Drum Zildjian71 posted an image macro\
  \ criticizing Facebook's \"gift\" feature to /r/AdviceAnimals,[4] where it received\
  \ upwards of 12,300 upvotes and 150 comments before it was archived (shown below,\
  \ right). On January 21st, 2014, Redditor dubman42 posted an image macro mocking\
  \ the software company Adobe's promotion of the McAfee virus scanning program to\
  \ /r/AdviceAnimals (shown below, left). In the following four months, the post garnered\
  \ more than 11,000 upvotes and 210 comments. On June 4th, Redditor j2249 submitted\
  \ a Regina George image macro joking about iPhone keyboards mistakenly replacing\
  \ the word \"f--king\" with \"ducking\" to /r/AdviceAnimals,[2] gaining over 18,400\
  \ upvotes and 560 comments in the first 24 hours (shown below, right). Notable Examples\
  \ Search Interest External References [1] Reddit \u2013 Everytime I run Internet\
  \ Explorer by accident [2] Reddit \u2013 Dear Apple I would never use that word\
  \ in my life [3] Reddit \u2013 Every time I see the new Internet Explorer commercial\
  \ [4] Reddit \u2013 Facebook, we need to talk [5] Reddit \u2013 Google+ Related\
  \ Entries 6 total Glen Coco Oh My God, Karen, You Can\u2019t Just Ask Someone Why\
  \ They're White Get In Loser, We're Going Shopping So You Agree On Wednesdays We\
  \ Wear Pink Mean Girls' Day / It's October 3rd Recent Videos 1 total Mean Girls\
  \ - Stop Trying to M... Stop Trying to Make Fetch Happen Uploaded by Kung Fu Cthulhu\
  \ + Add a Video Recent Images 34 total Stop Trying to Make Fetch Happen Uploaded\
  \ by Rebecca Rhodes Stop Trying to Make Fetch Happen Uploaded by RedNine Stop Trying\
  \ to Make Fetch Happen Uploaded by oudaveguy98 Stop Trying to Make Fetch Happen\
  \ Uploaded by Syelle Stop Trying to Make Fetch Happen Uploaded by Eevee Enthusiast\
  \ Stop Trying to Make Fetch Happen Uploaded by Brad Stop Trying to Make Fetch Happen\
  \ Uploaded by Brad Stop Trying to Make Fetch Happen Uploaded by Brad Stop Trying\
  \ to Make Fetch Happen Uploaded by Brad Stop Trying to Make Fetch Happen Uploaded\
  \ by Brad Stop Trying to Make Fetch Happen Uploaded by Brad Stop Trying to Make\
  \ Fetch Happen Uploaded by Brad + Add an Image View All Images Sign up for our Newsletter\
  \ Top Comments Delete Sensitive DerpityKev69 Jun 04, 2014 at 10:01PM EDT +61 Reply\
  \ Delete Sensitive WhipperSnapper Jun 04, 2014 at 06:27PM EDT Stop trying to make\
  \ stop trying to make fetch happen happen. +31 Reply + Add a Comment Comments (37)\
  \ Display Comments Add a Comment Top Entries This Month Meme Saika Kawakita Smile\
  \ GIF Event Assassination of UnitedHealthcare CEO Person Luigi Mangione UHC CEO\
  \ Shooter Subculture The Ki Sisters Culture Pornography Site Whisper View More Suggest\
  \ a Change Edit History Entry Editor (1) Don Administrator & Meme Daddy + Request\
  \ Editorship View All Editors Today's Top Image Galleries Assassination of UnitedHealthcare\
  \ CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing Digital Circus About\
  \ Our Story Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes\
  \ News Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/stop-trying-to-make-fetch-happen
template_id: fetch
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
