name: Stop Trying to Make Fetch Happen
source: http://knowyourmeme.com/memes/stop-trying-to-make-fetch-happen
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- stop trying to make fetch happen
- it's not going to happen
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About "Stop Trying to Make Fetch Happen" is a memorable quote uttered
  by the character Regina George in the 2004 teen comedy film Mean Girls to discourage
  her friend Gretchen from using the slang term "fetch." The quote inspired the creation
  of an image macro series using the phrasal template "Stop trying to make X happen
  / It''s not going to happen." Origin In Mean Girls, released on April 30th, 2004,
  the character Regina George (played by Rachel McAdams) scolds her friend Gretchen
  Wieners (played by Lacey Chabert) for using the term "fetch" as a synonym for "cool."
  Gretchen: "That is so fetch!" Regina: "Gretchen, stop trying to make fetch happen!
  It''s not going to happen!" On March 1st, 2012, Redditor Keilantra submitted an
  image macro using a screen capture of McAdams in Mean Girls with a caption urging
  Google to abandon their efforts with the Google+ social networking service to /r/funny.[5]
  Prior to being archived, the post gained over 1,000 upvotes and 60 comments. Spread
  On September 25th, 2012, an image macro mocking Microsoft commercials promoting
  their Internet Explorer web browser was posted to /r/AdviceAnimals[3] (shown below).
  Before the post was archived, it accumulated more than 8,500 upvotes and 380 comments.
  On January 27th, 2013, Redditor TrueWarrior submitted an image macro mocking Internet
  Explorer''s frequent attempts to make itself a default web browser to /r/AdviceAnimals[1]
  (shown below, left). Prior to being archived, the post gained over 5,200 upvotes
  and 65 comments. On March 17th, Redditor Drum Zildjian71 posted an image macro criticizing
  Facebook''s "gift" feature to /r/AdviceAnimals,[4] where it received upwards of
  12,300 upvotes and 150 comments before it was archived (shown below, right). On
  January 21st, 2014, Redditor dubman42 posted an image macro mocking the software
  company Adobe''s promotion of the McAfee virus scanning program to /r/AdviceAnimals
  (shown below, left). In the following four months, the post garnered more than 11,000
  upvotes and 210 comments. On June 4th, Redditor j2249 submitted a Regina George
  image macro joking about iPhone keyboards mistakenly replacing the word "f--king"
  with "ducking" to /r/AdviceAnimals,[2] gaining over 18,400 upvotes and 560 comments
  in the first 24 hours (shown below, right). Notable Examples Search Interest External
  References [1] Reddit – Everytime I run Internet Explorer by accident [2] Reddit
  – Dear Apple I would never use that word in my life [3] Reddit – Every time I see
  the new Internet Explorer commercial [4] Reddit – Facebook, we need to talk [5]
  Reddit – Google+'
aside_content: MemeStatusConfirmedYear2012OriginRedditTagsnone...
added_at: '2014-06-04T16:04:15-04:00'
