example:
- 2-Day Delivery
- Overnight Shipping
- Shopping at the Store
keywords:
- null
name: Vince McMahon Reaction
overlay:
- angle: 0.0
  center_x: 0.25
  center_y: 0.155
  scale: 0.3
- angle: 0.0
  center_x: 0.25
  center_y: 0.5
  scale: 0.3
- angle: 0.0
  center_x: 0.25
  center_y: 0.84
  scale: 0.3
scraped_content: "Vince McMahon Reaction | Know Your Meme Howdy! You must login or\
  \ signup first! Already a memeber? Login Now! Don't have an account? Sign up Now!\
  \ Meme Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Vince McMahon Reaction Added 10 years ago / Updated 8 days ago Confirmed 479,989\
  \ Part of a series on Vince McMahon. [View Related Entries] View All 88 Images Navigation\
  \ About \u2022 Origin \u2022 Spread \u2022 Search Interest \u2022 External References\
  \ \u2022 Recent Images \u2022 Recent Videos About Vince McMahon Reaction is a series\
  \ of remix videos and animated GIFs that combine a variety of humorous video clips\
  \ and footage of the World Wrestling Entertainment (WWE) Chairman and CEO looking\
  \ utterly shocked in amazement. Origin During a 2002 episode of the WWE, professional\
  \ wrestler and model Stacy Keibler entered the ring and danced on the table in front\
  \ of McMahon while he watched in amazement during the performance (shown below).\
  \ Following the dance, McMahon hired Keibler as his personal assistant. On November\
  \ 1st, 2013, YouTuber wazeu2 uploaded a video titled \"Funny Vince McMahon looking\
  \ at a bodybuilder, which featured footage of bodybuilder Gary Strydom[5] flexing\
  \ during a World Bodybuilding Federation competition spliced between footage of\
  \ McMahon reacting to Keibler (mirror below). Spread That day, Imgur[3] user GodIsDeadLongLiveDog\
  \ uploaded an animated GIF of the video, receiving over 11,200 points and 320 comments\
  \ over the next year. On November 12th, 2014, the /r/VinceMcmahongifs[2] subreddit\
  \ was launched for animated GIFs featuring the WWE CEO. On March 8th, 2014, Something\
  \ Awful[1] Forums user Machai submitted a thread titled \"Vince McMahon.gif,\" which\
  \ highlighted several notable examples from the series. On October 28th, Redditor\
  \ TheDarkWayne posted a parody GIF featuring McMahon reacting to the announcements\
  \ of several Marvel comic book films to /r/gifs[6] (shown below). In the first month,\
  \ the post gained more than 4,200 votes (94% upvoted). On November 1st, the Strydom-McMahon\
  \ mashup GIF was featured during an episode of the comedy game show @Midnight (shown\
  \ below). Search Interest External References [1] Something Awful \u2013 Vine McMahon\
  \ [2] Reddit \u2013 VinceMcmahongifs [3] Imgur \u2013 This is my favourite GIF [4]\
  \ Reddit \u2013 That Vince McMahon reaction gif [5] YouTuber \u2013 Gary Strydom\
  \ WBF Posing [6] Reddit \u2013 Everyone ove rat /r/marvelstudios video gif parody\
  \ edit vince mcmahon reacts reaction image stacy keibler wazeu2 gary strydom thedarkwayne\
  \ Share Pin Related Entries 7 total It's Me, Austin! Vince McMahon Crying Vince\
  \ McMahon Smelling Money Vince McMahon Surprised / X W... View All Related Entries\
  \ Recent Images 88 total View All Images Recent Videos 5 total View All Videos Sign\
  \ up for our Newsletter Load 76 Comments Comments 76 total 118 Vince McMahon Reaction\
  \ 479,989 5 88 76 Part of a series on Vince McMahon. [View Related Entries] Updated\
  \ Dec 15, 2024 at 04:14PM EST by LiterallyAustin. Added Nov 25, 2014 at 03:12PM\
  \ EST by Don. Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i'\
  \ to view the image gallery, 'v' to view the video gallery, or 'r' to view a random\
  \ entry. Meme Status Confirmed Type: Reaction Year 2013 Origin YouTube Tags video,\
  \ gif, parody, edit, vince mcmahon reacts, reaction image, stacy keibler, wazeu2,\
  \ gary strydom, thedarkwayne About Vince McMahon Reaction is a series of remix videos\
  \ and animated GIFs that combine a variety of humorous video clips and footage of\
  \ the World Wrestling Entertainment (WWE) Chairman and CEO looking utterly shocked\
  \ in amazement. Origin During a 2002 episode of the WWE, professional wrestler and\
  \ model Stacy Keibler entered the ring and danced on the table in front of McMahon\
  \ while he watched in amazement during the performance (shown below). Following\
  \ the dance, McMahon hired Keibler as his personal assistant. On November 1st, 2013,\
  \ YouTuber wazeu2 uploaded a video titled \"Funny Vince McMahon looking at a bodybuilder,\
  \ which featured footage of bodybuilder Gary Strydom[5] flexing during a World Bodybuilding\
  \ Federation competition spliced between footage of McMahon reacting to Keibler\
  \ (mirror below). Spread That day, Imgur[3] user GodIsDeadLongLiveDog uploaded an\
  \ animated GIF of the video, receiving over 11,200 points and 320 comments over\
  \ the next year. On November 12th, 2014, the /r/VinceMcmahongifs[2] subreddit was\
  \ launched for animated GIFs featuring the WWE CEO. On March 8th, 2014, Something\
  \ Awful[1] Forums user Machai submitted a thread titled \"Vince McMahon.gif,\" which\
  \ highlighted several notable examples from the series. On October 28th, Redditor\
  \ TheDarkWayne posted a parody GIF featuring McMahon reacting to the announcements\
  \ of several Marvel comic book films to /r/gifs[6] (shown below). In the first month,\
  \ the post gained more than 4,200 votes (94% upvoted). On November 1st, the Strydom-McMahon\
  \ mashup GIF was featured during an episode of the comedy game show @Midnight (shown\
  \ below). Search Interest External References [1] Something Awful \u2013 Vine McMahon\
  \ [2] Reddit \u2013 VinceMcmahongifs [3] Imgur \u2013 This is my favourite GIF [4]\
  \ Reddit \u2013 That Vince McMahon reaction gif [5] YouTuber \u2013 Gary Strydom\
  \ WBF Posing [6] Reddit \u2013 Everyone ove rat /r/marvelstudios Related Entries\
  \ 7 total It's Me, Austin! Vince McMahon Crying Vince McMahon Smelling Money Vince\
  \ McMahon Surprised / X When Y Walks In Sir, We Found The Guy Who X / Take Me to\
  \ The Son of A Bitch Vince McMahon's Mustache Vince McMahon Sexual Misconduct Allegations\
  \ Recent Videos 5 total Vince reacts to Roman cocking... Vince McMahon Reaction\
  \ Uploaded by MScratch Bautista's Dick - Create, Dis... Vince McMahon Reaction Uploaded\
  \ by chowzburgerz #PC Master Race Vince McMahon Reaction Uploaded by xXMLG420 FaZe360noscopeXx\
  \ Vince McMahon Reaction to Lea... Vince McMahon Reaction Uploaded by Jack Black\
  \ + Add a Video Recent Images 88 total Vince McMahon Reaction Uploaded by ArcadeTwo\
  \ Vince McMahon Reaction Uploaded by nokia3310 Vince McMahon Reaction Uploaded by\
  \ Reddit Moments Vince McMahon Reaction Uploaded by Virgile Vince McMahon Reaction\
  \ Uploaded by Triplem Vince McMahon Reaction Uploaded by Virgile Vince McMahon Reaction\
  \ Uploaded by Mr.k2 Vince McMahon Reaction Uploaded by Nyazilla Vince McMahon Reaction\
  \ Uploaded by Adam Vince McMahon Reaction Uploaded by Mr.k2 Vince McMahon Reaction\
  \ Uploaded by Lugamo Vince McMahon Reaction Uploaded by OeperinoOomoro + Add an\
  \ Image View All Images Sign up for our Newsletter Top Comments Delete Sensitive\
  \ \"MYAAH Man\" Skely Savage Nov 25, 2014 at 09:20PM EST Oops, almost forgot one!\
  \ +61 Reply Delete Sensitive Jack Black Nov 25, 2014 at 04:30PM EST 1+best reaction\
  \ ever +53 Reply + Add a Comment Comments (76) Display Comments Add a Comment Top\
  \ Entries This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (6) Don Administrator\
  \ & Meme Daddy \xAD\xAD\xADAlex Mercer Entry Moderator & YouTube Scatologist Brad\
  \ Digital Archaeologist & Treasurer & Pundit & Gallery Housekeeper Particle Mare\
  \ Wolf of Meme Street Y F Digital Archaeologist & Treasurer & Media Maid Matt Secretary\
  \ of Memes \u25BC + Request Editorship View All Editors Today's Top Image Galleries\
  \ Assassination of UnitedHealthcare CEO Team Fortress 2 Squirrel Girl (Doreen Green)\
  \ The Amazing Digital Circus About Our Story Site Rules Policies and Guidelines\
  \ Credits Contact Meme DB Memes Episodes News Staff Contact Extras! Style Guide\
  \ RSS Feeds"
source: https://knowyourmeme.com/memes/vince-mcmahon-reaction
template_id: vince
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: black
  font: thin
  scale_x: 0.495
  scale_y: 0.315
  start: 0.1
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.0
  anchor_y: 0.32
  angle: 0.0
  color: black
  font: thin
  scale_x: 0.495
  scale_y: 0.357
  start: 0.4
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.0
  anchor_y: 0.68
  angle: 0.0
  color: black
  font: thin
  scale_x: 0.495
  scale_y: 0.32
  start: 0.7
  stop: 1.0
  style: default
text_zones: 3
