name: Vince McMahon Reaction
source: https://knowyourmeme.com/memes/vince-mcmahon-reaction
keywords:
- null
text:
- style: default
  color: black
  font: thin
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 0.495
  scale_y: 0.315
  align: center
  start: 0.1
  stop: 1.0
- style: default
  color: black
  font: thin
  anchor_x: 0.0
  anchor_y: 0.32
  angle: 0.0
  scale_x: 0.495
  scale_y: 0.357
  align: center
  start: 0.4
  stop: 1.0
- style: default
  color: black
  font: thin
  anchor_x: 0.0
  anchor_y: 0.68
  angle: 0.0
  scale_x: 0.495
  scale_y: 0.32
  align: center
  start: 0.7
  stop: 1.0
example:
- 2-Day Delivery
- Overnight Shipping
- Shopping at the Store
overlay:
- center_x: 0.25
  center_y: 0.155
  angle: 0.0
  scale: 0.3
- center_x: 0.25
  center_y: 0.5
  angle: 0.0
  scale: 0.3
- center_x: 0.25
  center_y: 0.84
  angle: 0.0
  scale: 0.3
scraped_content: About Vince McMahon Reaction is a series of remix videos and animated
  GIFs that combine a variety of humorous video clips and footage of the World Wrestling
  Entertainment (WWE) Chairman and CEO looking utterly shocked in amazement. Origin
  During a 2002 episode of the WWE, professional wrestler and model Stacy Keibler
  entered the ring and danced on the table in front of McMahon while he watched in
  amazement during the performance (shown below). Following the dance, McMahon hired
  Keibler as his personal assistant. On November 1st, 2013, YouTuber wazeu2 uploaded
  a video titled "Funny Vince McMahon looking at a bodybuilder, which featured footage
  of bodybuilder Gary Strydom[5] flexing during a World Bodybuilding Federation competition
  spliced between footage of McMahon reacting to Keibler (mirror below). Spread That
  day, Imgur[3] user GodIsDeadLongLiveDog uploaded an animated GIF of the video, receiving
  over 11,200 points and 320 comments over the next year. On November 12th, 2014,
  the /r/VinceMcmahongifs[2] subreddit was launched for animated GIFs featuring the
  WWE CEO. On March 8th, 2014, Something Awful[1] Forums user Machai submitted a thread
  titled "Vince McMahon.gif," which highlighted several notable examples from the
  series. On October 28th, Redditor TheDarkWayne posted a parody GIF featuring McMahon
  reacting to the announcements of several Marvel comic book films to /r/gifs[6] (shown
  below). In the first month, the post gained more than 4,200 votes (94% upvoted).
  On November 1st, the Strydom-McMahon mashup GIF was featured during an episode of
  the comedy game show @Midnight (shown below). Search Interest External References
  [1] Something Awful – Vine McMahon [2] Reddit – VinceMcmahongifs [3] Imgur – This
  is my favourite GIF [4] Reddit – That Vince McMahon reaction gif [5] YouTuber –
  Gary Strydom WBF Posing [6] Reddit – Everyone ove rat /r/marvelstudios
aside_content: MemeStatusConfirmedType:ReactionYear2013OriginYouTubeTagsvideo,gif,parody,edit,vince
  mcmahon reacts,reaction image,stacy keibler,wazeu2,gary strydom,thedarkwayne
added_at: '2014-11-25T15:12:02-05:00'
