name: 10 Guy
source: http://knowyourmeme.com/memes/10-guy
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- can't read the words on the menu
- turns down the radio
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About [10] Guy (also known as "Really High Guy" and "Stoner Stanley")
  is an advice animal image macro series featuring a photo of a young man who appears
  to be under the influence of marijuana. The captions typically portray stereotypical
  stoner behavior, similar to Stoner Dog, such as giving invalid answers to misunderstood
  questions and craving junk food. In April 2021, UK-based resident Connor Sinclair
  revealed himself to be the man depicted in 10 Guy after nearly a decade of anonymity.
  Origin On November 25th, 2011, Redditor randomdave posted a photo of a red-faced
  young man (below left) to the marijuana enthusiast r/trees subreddit titled "Being
  at a [10] is not always pretty."[10] The same day, the picture was submitted by
  redditor Ahahaha__10 with the caption "Texts the person next to them / 'I want hopsital'"
  (below right) in a post titled "The happened to a friend of mine on his first ever
  bong rip."[1] Etymology of [10] The name is derived from the scoring system used
  by members of the r/trees[16] subreddit, also known as “ents”, that indicates the
  relative level of intoxication with [1] being the lowest and [10] being the highest.
  Spread Shortly after Redditor Ahahaha__10 submitted the first image macro, Redditor
  vivalocaaa created a Quickmeme[3] page using the photo called "[10] Guy." On November
  30th, 2011, a post[5] titled "10 Guy ordering a cheeseburger" reached the front
  page of Reddit, accumulating over 3,000 up votes within 6 days. On December 2nd,
  compilations of "Really High Guy" examples were posted to the Body Building[6] forums
  and the Internet humor site BuzzFeed.[7] On December 5th, a slideshow of [10] Guy
  image macros was posted to the media hosting site Sharenator[8] titled "High High
  Schooler." On March 31st, 2012, additional photos of [10] Guy surfaced on the "Stoner
  Comics"[12] Tumblr blog. On April 6th, 2012, several examples were posted to the
  Internet humor site Ebaumsworld[11] by user yzman87. The meme continued to spread
  on sites like FunnyJunk[13], Memebase[15] and Tumblr under the tags "10 guy"[4]
  and "really high guy."[9] As of April 20th, 2012, the Quickmeme page has over 10,400
  submissions and a Facebook[14] page for "10 Guy" has 133 likes. Identity In early
  April 2021, UK-based resident Connor Sinclair revealed himself to be the man depicted
  in the 10 Guy meme after nearly a decade of remaining anonymous online when he created
  the Twitter account @10GuyOfficial. On April 11th, 2021, Sinclair then tweeted[23]
  an image of himself holding up the account name on a sheet of paper, confirming
  his identity (seen below). On May 6th, 2021, Sinclair uploaded a video to his YouTube[24]
  channel where he spoke about his role in the meme and revealed himself as the person
  depicted in 10 Guy (shown below). Notable Examples Derivatives [10] Keanu The face
  of [10] Guy has been photoshopped into the Conspiracy Keanu template. 10 Koala On
  April 29th, 2012, Redditor theofficialtevo submitted an image macro to the /r/trees[21]
  subreddit, which featured [10] Guy with the caption "Dude. You're a koala" followed
  by a photograph of a similar-looking koala with the caption "when?" (shown below,
  left). Prior to being archived, the post received over 1,900 upvotes and 70 comments.
  On May 9th, Redditor grantly0711 submitted an image macro using the same setup to
  the /r/AdviceAnimals[22] subreddit, which featured the caption "Dude. Eucalyptus.
  / I can lick what?" (shown below, right). The post accumulated 467 upvotes but only
  7 comments before it was archived. 10 Dog On February 1st, 2013, Redditor hairy_potter
  submitted an image post to the /r/funny[17] subreddit, featuring a photograph of
  his dog under the influence of anesthetic after a surgery (shown below, left). The
  post received over 47,900 upvotes and 830 comments prior to being archived, as well
  as several image macros portraying the dog as a stereotypical stoner (shown below,
  middle), similar to the character of Stoner Dog. The same day, Redditor Kuonji submitted
  a post titled “10 Dog at the park” to the /r/AdviceAnimals[18] subreddit, featuring
  an image macro of the dog photo with the caption “A squirrel is just / a tennis
  ball thrown by God” (shown below, right), which received more than 9,300 upvotes
  and 60 comments within the first week. In the following days, more than 150 instances
  of [10] Dog image macros were submitted to the /r/AdviceAnimals subreddit and at
  least 200 instances can be found on the Quickmeme[19] page for [10] Dog. On February
  5th, UpRoxx[20] published a slideshow post featuring notable examples from the series.
  Search Interest Search query volume for "10 guy" rose in November of 2011, the same
  month the images began circulating on Reddit. External References [1] Reddit – The
  happened to a friend of mine on his first ever bong rip [2] Reddit – 10 Guy returns,
  with food on his smoked out mind [3] Quickmeme – 10 Guy [4] Tumblr – posts tagged
  as 10 Guy [5] Reddit – 10 Guy ordering a cheeseburger [6] Body Building Forum –
  Really High Guy Meme [7] BuzzFeed (via Wayback Machine) – Best Of The Really High
  Guy Meme [8] Sharenator – High High Schooler [9] Tumblr – posts tagged as really
  high guy [10] Reddit – Being at a [10] is not always pretty [11] Ebaumsworld – 10
  Guy [12] Tumblr (via Wayback Machine) – 10 Guy [13] FunnyJunk – 10 guy= [14] Facebook
  – 10 guy [15] Memebase – tag for high [16] Reddit – /r/trees [17] Reddit – My dog
  just got out of surgery [18] Reddit – 10 Dog at the Park [19] Quickmeme – 10 Dog
  [20] UpRoxx – 10 Dog is the newest addtion to the stoner dog pantheon [21] Reddit
  – Dude, you're a koala [22] Reddit – 10 guy and his koala return [23] Twitter –
  10 Guy Reveal Tweet [24] YouTube – 10 Guy REVEALED
aside_content: MemeStatusConfirmedType:Image MacroYear2011OriginRedditTagsstoned,drugs,high,trees,weed,10,stoner,marijuana,[10],cannibus,stoner
  stanley,420,stoner humor,marilize legajuana,10 guy,10guy,advice animal,randomdave,ahahaha__10,vivalocaaa,sharenator,theofficialtevo,yzman87,koala,grantly0711,haAdditional
  ReferencesMeme Generator
added_at: '2011-12-03T23:37:50-05:00'
