name: Is This a Pigeon?
source: https://knowyourmeme.com/memes/is-this-a-pigeon
keywords:
- null
text:
- style: default
  color: white
  font: thick
  anchor_x: 0.15
  anchor_y: 0.0
  angle: 0.0
  scale_x: 0.35
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: white
  font: thick
  anchor_x: 0.71
  anchor_y: 0.3
  angle: 0.0
  scale_x: 0.175
  scale_y: 0.1
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: khaki
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.4
  stop: 1.0
example:
- Engineer
- PowerPoint
- Is this Photoshop?
overlay:
- center_x: 0.8
  center_y: 0.2
  angle: 0.0
  scale: 0.4
scraped_content: "About \"Is this a pigeon?\" is a memorable quote said by the protagonist\
  \ character from the 1990s Japanese anime TV series The Brave Fighter of Sun Fighbird\
  \ in a scene wherein the humanoid character erroneously identifies a butterfly as\
  \ a pigeon. On Tumblr, the quote, along with a reaction image of the scene featuring\
  \ the English-translated subtitle, is widely used to express utter confusion. Origin\
  \ The still shot originates from Season 1, Episode 3 of The Brave Fighter of Sun\
  \ Fighbird[1] (太陽の勇者ファイバード) (or simply Fighbird), which first premiered in Japan\
  \ in February 1991, in a scene where Yutaro Katori, a human android created by professor\
  \ Hiroshi Amano, misidentifies a butterfly as a pigeon while studying the earthly\
  \ nature. In addition to mistaking a pigeon for a butterfly, Katori also confuses\
  \ Rosaceae with Violaceae (shown below). On Tumblr, the quote has been occasionally\
  \ misinterpreted as an example of transcription FAIL, however, it is the direct\
  \ translation of the original line in verbatim: Spread On December 6th, 2011, the\
  \ image was uploaded for the first time by Tumblr user Indizi dell'avvenuta catastrofe,[2]\
  \ which managed to gain more than 111,000 notes over the next three years. On December\
  \ 11th, the picture was posted on AnimeUltima.tv website and Funny Pics.[6] On November\
  \ 23th, 2012, the picture was also included in Smosh's article titled \"22 Hysterical\
  \ Anime Screencaps,\" ranked in the second place.[8] On June 27th, 2013, Buzzfeed\
  \ highlighted the image in a compilation article titled \"27 Subtitles That Have\
  \ Gone Awesomely Wrong,\"[7] which misattributed Katori's quote as a fan-translation\
  \ FAIL. On TV Tropes, \"Is this a pigeon?\" is noted as a 'Photo reply to any picture\
  \ showing a butterfly' in Tumblr's Meme section.[9] Additional examples can also\
  \ be found on Tumblr through the #is-this-a-pigeon hashtag.[10] Various Examples\
  \ \uFEFF Don't Hug Me I'm Scared III The popular musical film series directed by\
  \ Becky Sloan & Joseph Pelling, Don't Hug Me I'm Scared, episode 3 referenced \"\
  Is this a pigeon?\" fad in form of The Yellow Guy mistaking a butterfly Shrignold\
  \ for 'A little baby pigeon'. It begun a new collection of editions and variations\
  \ on Tumblr.[11] 2018 Resurgence In late April and early May 2018, object-labeled\
  \ variations of the meme saw a significant resurgence on Twitter. On April 26th,\
  \ Twitter user romiosini tweeted a version labeling the butterfly as \"any makeup\
  \ look without red lipstick\" (shown below, left).[12] On May 3rd, Netflix tweeted\
  \ a variation joking about how 28-year-old actors are cast as teenagers in \"high\
  \ school TV dramas\" (shown below, right).[13] Within one week, the tweet gathered\
  \ upwards of 40,400 likes and 9,400 retweets. In the coming weeks, numerous other\
  \ object labeled examples were submitted to Twitter and Reddit (shown below). On\
  \ May 11th, 2018, Kara Dennison, one of the original fansubbers of the Fighbird\
  \ anime, made a Blogspot post about the backstory of the meme and the series which\
  \ it originated from. [14] Female Version On June 26th, 2018, Twitter user @ImFroppy[15]\
  \ tweeted a picture of a female character from the anime You're Under Arrest holding\
  \ pigeons with the fake caption \"Is this a butterfly?\" (shown below). Within 72\
  \ hours, the tweet gained over 77,300 likes and 35,800 retweets. The following day,\
  \ Twitter user @SeaShell_arts[16] tweeted a fan illustration of the two anime characters\
  \ (shown below, left). Meanwhile, others commented that the new female version was\
  \ still the original character, but had merely transitioned to the other gender\
  \ (shown below, right). Also on June 29th, The Daily Dot[17] published an article\
  \ about the new variation \"There’s a woman version of the butterfly meme--and the\
  \ internet loves it.\" Search Interest External References [1] Wikipedia – The Brave\
  \ Fighter of Sun Fighbird [2] Tumblr – Indizi dell'avvenuta catastrofe / Posted\
  \ on 12-6-2011 [3] Tumblr – Indizi dell'avvenuta catastrofe Archive [4] Know Your\
  \ Meme – LOLfansubs/Failsubs / Posted on 8-8-2010 [5] Know Your Meme – Image #213,616\
  \ / Posted on 12-6-2011 [6] animeultima.tv – Funny Pics / Posted on 12-11-2011 [7]\
  \ Buzzfeed – 27 Subtitles That Have Gone Awesomely Wrong / Posted on 6-27-2013 [8]\
  \ TV Tropes – Memes: Tumblr [9] Facebook – Smosh / Posted on 2-21-2014 [10] Tumblr\
  \ – #is this a pigeon [11] Tumblr – #dhmis [12] Twitter – romiosini [13] Twitter\
  \ – @netflix [14] The Dennison Collective, Blogspot – Hi, I'm Kara, and I inadvertently\
  \ helped make a meme. [15] Twitter – @ImFroppy [16] Twitter – @SeaShell_arts [17]\
  \ The Daily Dot – There’s a woman version of the butterfly meme--and the internet\
  \ loves it"
aside_content: MemeStatusConfirmedType:ExploitableYear1991OriginThe Brave Fighter
  of Sun Fighbird / 太陽の勇者ファイバードTagsanime,screenshot,response,tumblr,captioning,printscreen,reaction
  imagery,the brave fighter of sun fighbird,太陽の勇者ファイバード,hiroshi amano,indizi dell'avvenuta
  catastrofe,becky sloan,joseph pelling,romiosini,kara dennison,blogspotAdditional
  ReferencesMeme Generator
added_at: '2015-02-10T12:00:19-05:00'
