example:
- Engineer
- PowerPoint
- Is this Photoshop?
keywords:
- null
name: Is This a Pigeon?
overlay:
- angle: 0.0
  center_x: 0.8
  center_y: 0.2
  scale: 0.4
scraped_content: "Is This a Pigeon? | Know Your Meme O HAI! You must login or signup\
  \ first! Already a memeber? Login Now! Don't have an account? Sign up Now! Meme\
  \ Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Is This a Pigeon? Added 9 years ago / Updated 8 days ago Confirmed 1,242,119\
  \ Part of a series on Anime / Manga. [View Related Entries] View All 436 Images\
  \ Navigation About \u2022 Origin \u2022 Spread \u2022 Various Examples \u2022 Search\
  \ Interest \u2022 External References \u2022 Recent Images \u2022 Recent Videos\
  \ About \"Is this a pigeon?\" is a memorable quote said by the protagonist character\
  \ from the 1990s Japanese anime TV series The Brave Fighter of Sun Fighbird in a\
  \ scene wherein the humanoid character erroneously identifies a butterfly as a pigeon.\
  \ On Tumblr, the quote, along with a reaction image of the scene featuring the English-translated\
  \ subtitle, is widely used to express utter confusion. Origin The still shot originates\
  \ from Season 1, Episode 3 of The Brave Fighter of Sun Fighbird[1] (\u592A\u967D\
  \u306E\u52C7\u8005\u30D5\u30A1\u30A4\u30D0\u30FC\u30C9) (or simply Fighbird), which\
  \ first premiered in Japan in February 1991, in a scene where Yutaro Katori, a human\
  \ android created by professor Hiroshi Amano, misidentifies a butterfly as a pigeon\
  \ while studying the earthly nature. In addition to mistaking a pigeon for a butterfly,\
  \ Katori also confuses Rosaceae with Violaceae (shown below). On Tumblr, the quote\
  \ has been occasionally misinterpreted as an example of transcription FAIL, however,\
  \ it is the direct translation of the original line in verbatim: Spread On December\
  \ 6th, 2011, the image was uploaded for the first time by Tumblr user Indizi dell'avvenuta\
  \ catastrofe,[2] which managed to gain more than 111,000 notes over the next three\
  \ years. On December 11th, the picture was posted on AnimeUltima.tv website and\
  \ Funny Pics.[6] On November 23th, 2012, the picture was also included in Smosh's\
  \ article titled \"22 Hysterical Anime Screencaps,\" ranked in the second place.[8]\
  \ On June 27th, 2013, Buzzfeed highlighted the image in a compilation article titled\
  \ \"27 Subtitles That Have Gone Awesomely Wrong,\"[7] which misattributed Katori's\
  \ quote as a fan-translation FAIL. On TV Tropes, \"Is this a pigeon?\" is noted\
  \ as a 'Photo reply to any picture showing a butterfly' in Tumblr's Meme section.[9]\
  \ Additional examples can also be found on Tumblr through the #is-this-a-pigeon\
  \ hashtag.[10] Various Examples \uFEFF Don't Hug Me I'm Scared III The popular musical\
  \ film series directed by Becky Sloan & Joseph Pelling, Don't Hug Me I'm Scared,\
  \ episode 3 referenced \"Is this a pigeon?\" fad in form of The Yellow Guy mistaking\
  \ a butterfly Shrignold for 'A little baby pigeon'. It begun a new collection of\
  \ editions and variations on Tumblr.[11] 2018 Resurgence In late April and early\
  \ May 2018, object-labeled variations of the meme saw a significant resurgence on\
  \ Twitter. On April 26th, Twitter user romiosini tweeted a version labeling the\
  \ butterfly as \"any makeup look without red lipstick\" (shown below, left).[12]\
  \ On May 3rd, Netflix tweeted a variation joking about how 28-year-old actors are\
  \ cast as teenagers in \"high school TV dramas\" (shown below, right).[13] Within\
  \ one week, the tweet gathered upwards of 40,400 likes and 9,400 retweets. In the\
  \ coming weeks, numerous other object labeled examples were submitted to Twitter\
  \ and Reddit (shown below). On May 11th, 2018, Kara Dennison, one of the original\
  \ fansubbers of the Fighbird anime, made a Blogspot post about the backstory of\
  \ the meme and the series which it originated from. [14] Female Version On June\
  \ 26th, 2018, Twitter user @ImFroppy[15] tweeted a picture of a female character\
  \ from the anime You're Under Arrest holding pigeons with the fake caption \"Is\
  \ this a butterfly?\" (shown below). Within 72 hours, the tweet gained over 77,300\
  \ likes and 35,800 retweets. The following day, Twitter user @SeaShell_arts[16]\
  \ tweeted a fan illustration of the two anime characters (shown below, left). Meanwhile,\
  \ others commented that the new female version was still the original character,\
  \ but had merely transitioned to the other gender (shown below, right). Also on\
  \ June 29th, The Daily Dot[17] published an article about the new variation \"There\u2019\
  s a woman version of the butterfly meme--and the internet loves it.\" Search Interest\
  \ External References [1] Wikipedia \u2013 The Brave Fighter of Sun Fighbird [2]\
  \ Tumblr \u2013 Indizi dell'avvenuta catastrofe / Posted on 12-6-2011 [3] Tumblr\
  \ \u2013 Indizi dell'avvenuta catastrofe Archive [4] Know Your Meme \u2013 LOLfansubs/Failsubs\
  \ / Posted on 8-8-2010 [5] Know Your Meme \u2013 Image #213,616 / Posted on 12-6-2011\
  \ [6] animeultima.tv \u2013 Funny Pics / Posted on 12-11-2011 [7] Buzzfeed \u2013\
  \ 27 Subtitles That Have Gone Awesomely Wrong / Posted on 6-27-2013 [8] TV Tropes\
  \ \u2013 Memes: Tumblr [9] Facebook \u2013 Smosh / Posted on 2-21-2014 [10] Tumblr\
  \ \u2013 #is this a pigeon [11] Tumblr \u2013 #dhmis [12] Twitter \u2013 romiosini\
  \ [13] Twitter \u2013 @netflix [14] The Dennison Collective, Blogspot \u2013 Hi,\
  \ I'm Kara, and I inadvertently helped make a meme. [15] Twitter \u2013 @ImFroppy\
  \ [16] Twitter \u2013 @SeaShell_arts [17] The Daily Dot \u2013 There\u2019s a woman\
  \ version of the butterfly meme--and the internet loves it anime screenshot response\
  \ tumblr captioning printscreen reaction imagery the brave fighter of sun fighbird\
  \ \u592A\u967D\u306E\u52C7\u8005\u30D5\u30A1\u30A4\u30D0\u30FC\u30C9 hiroshi amano\
  \ indizi dell'avvenuta catastrofe becky sloan joseph pelling romiosini kara dennison\
  \ blogspot Share Pin Related Entries 119 total JoJo's Bizarre Adventure QUALITY\
  \ Hatsune Miku / Vocaloid Top 10 Anime List Parodies View All Related Entries Recent\
  \ Images 436 total View All Images Recent Videos 20 total View All Videos Sign up\
  \ for our Newsletter Load 52 Comments Comments 52 total 97 Is This a Pigeon? 1,242,119\
  \ 20 436 52 Part of a series on Anime / Manga. [View Related Entries] Updated Dec\
  \ 15, 2024 at 04:16PM EST by LiterallyAustin. Added Feb 10, 2015 at 12:00PM EST\
  \ by Miluk. Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i' to\
  \ view the image gallery, 'v' to view the video gallery, or 'r' to view a random\
  \ entry. Meme Status Confirmed Type: Exploitable Year 1991 Origin The Brave Fighter\
  \ of Sun Fighbird / \u592A\u967D\u306E\u52C7\u8005\u30D5\u30A1\u30A4\u30D0\u30FC\
  \u30C9 Tags anime, screenshot, response, tumblr, captioning, printscreen, reaction\
  \ imagery, the brave fighter of sun fighbird, \u592A\u967D\u306E\u52C7\u8005\u30D5\
  \u30A1\u30A4\u30D0\u30FC\u30C9, hiroshi amano, indizi dell'avvenuta catastrofe,\
  \ becky sloan, joseph pelling, romiosini, kara dennison, blogspot Additional References\
  \ Meme Generator About \"Is this a pigeon?\" is a memorable quote said by the protagonist\
  \ character from the 1990s Japanese anime TV series The Brave Fighter of Sun Fighbird\
  \ in a scene wherein the humanoid character erroneously identifies a butterfly as\
  \ a pigeon. On Tumblr, the quote, along with a reaction image of the scene featuring\
  \ the English-translated subtitle, is widely used to express utter confusion. Origin\
  \ The still shot originates from Season 1, Episode 3 of The Brave Fighter of Sun\
  \ Fighbird[1] (\u592A\u967D\u306E\u52C7\u8005\u30D5\u30A1\u30A4\u30D0\u30FC\u30C9\
  ) (or simply Fighbird), which first premiered in Japan in February 1991, in a scene\
  \ where Yutaro Katori, a human android created by professor Hiroshi Amano, misidentifies\
  \ a butterfly as a pigeon while studying the earthly nature. In addition to mistaking\
  \ a pigeon for a butterfly, Katori also confuses Rosaceae with Violaceae (shown\
  \ below). On Tumblr, the quote has been occasionally misinterpreted as an example\
  \ of transcription FAIL, however, it is the direct translation of the original line\
  \ in verbatim: Spread On December 6th, 2011, the image was uploaded for the first\
  \ time by Tumblr user Indizi dell'avvenuta catastrofe,[2] which managed to gain\
  \ more than 111,000 notes over the next three years. On December 11th, the picture\
  \ was posted on AnimeUltima.tv website and Funny Pics.[6] On November 23th, 2012,\
  \ the picture was also included in Smosh's article titled \"22 Hysterical Anime\
  \ Screencaps,\" ranked in the second place.[8] On June 27th, 2013, Buzzfeed highlighted\
  \ the image in a compilation article titled \"27 Subtitles That Have Gone Awesomely\
  \ Wrong,\"[7] which misattributed Katori's quote as a fan-translation FAIL. On TV\
  \ Tropes, \"Is this a pigeon?\" is noted as a 'Photo reply to any picture showing\
  \ a butterfly' in Tumblr's Meme section.[9] Additional examples can also be found\
  \ on Tumblr through the #is-this-a-pigeon hashtag.[10] Various Examples \uFEFF Don't\
  \ Hug Me I'm Scared III The popular musical film series directed by Becky Sloan\
  \ & Joseph Pelling, Don't Hug Me I'm Scared, episode 3 referenced \"Is this a pigeon?\"\
  \ fad in form of The Yellow Guy mistaking a butterfly Shrignold for 'A little baby\
  \ pigeon'. It begun a new collection of editions and variations on Tumblr.[11] 2018\
  \ Resurgence In late April and early May 2018, object-labeled variations of the\
  \ meme saw a significant resurgence on Twitter. On April 26th, Twitter user romiosini\
  \ tweeted a version labeling the butterfly as \"any makeup look without red lipstick\"\
  \ (shown below, left).[12] On May 3rd, Netflix tweeted a variation joking about\
  \ how 28-year-old actors are cast as teenagers in \"high school TV dramas\" (shown\
  \ below, right).[13] Within one week, the tweet gathered upwards of 40,400 likes\
  \ and 9,400 retweets. In the coming weeks, numerous other object labeled examples\
  \ were submitted to Twitter and Reddit (shown below). On May 11th, 2018, Kara Dennison,\
  \ one of the original fansubbers of the Fighbird anime, made a Blogspot post about\
  \ the backstory of the meme and the series which it originated from. [14] Female\
  \ Version On June 26th, 2018, Twitter user @ImFroppy[15] tweeted a picture of a\
  \ female character from the anime You're Under Arrest holding pigeons with the fake\
  \ caption \"Is this a butterfly?\" (shown below). Within 72 hours, the tweet gained\
  \ over 77,300 likes and 35,800 retweets. The following day, Twitter user @SeaShell_arts[16]\
  \ tweeted a fan illustration of the two anime characters (shown below, left). Meanwhile,\
  \ others commented that the new female version was still the original character,\
  \ but had merely transitioned to the other gender (shown below, right). Also on\
  \ June 29th, The Daily Dot[17] published an article about the new variation \"There\u2019\
  s a woman version of the butterfly meme--and the internet loves it.\" Search Interest\
  \ External References [1] Wikipedia \u2013 The Brave Fighter of Sun Fighbird [2]\
  \ Tumblr \u2013 Indizi dell'avvenuta catastrofe / Posted on 12-6-2011 [3] Tumblr\
  \ \u2013 Indizi dell'avvenuta catastrofe Archive [4] Know Your Meme \u2013 LOLfansubs/Failsubs\
  \ / Posted on 8-8-2010 [5] Know Your Meme \u2013 Image #213,616 / Posted on 12-6-2011\
  \ [6] animeultima.tv \u2013 Funny Pics / Posted on 12-11-2011 [7] Buzzfeed \u2013\
  \ 27 Subtitles That Have Gone Awesomely Wrong / Posted on 6-27-2013 [8] TV Tropes\
  \ \u2013 Memes: Tumblr [9] Facebook \u2013 Smosh / Posted on 2-21-2014 [10] Tumblr\
  \ \u2013 #is this a pigeon [11] Tumblr \u2013 #dhmis [12] Twitter \u2013 romiosini\
  \ [13] Twitter \u2013 @netflix [14] The Dennison Collective, Blogspot \u2013 Hi,\
  \ I'm Kara, and I inadvertently helped make a meme. [15] Twitter \u2013 @ImFroppy\
  \ [16] Twitter \u2013 @SeaShell_arts [17] The Daily Dot \u2013 There\u2019s a woman\
  \ version of the butterfly meme--and the internet loves it Related Entries 119 total\
  \ JoJo's Bizarre Adventure QUALITY Hatsune Miku / Vocaloid Top 10 Anime List Parodies\
  \ Attack on Titan / Shingeki No Kyojin \"S\" Stands For? / Smile Sweet Sister Sadistic\
  \ Suprise Service Flat Is Justice / Delicious Flat Chest New Anime Plot Anime Tiddies\
  \ Lolicon Dragon Ball Netflix Adaptation View All Related Entries Recent Videos\
  \ 20 total How to draw the \"Is this a pi... Is This a Pigeon? Uploaded by shevyrolet\
  \ Meme Graffiti and Origins - I... Is This a Pigeon? Uploaded by shevyrolet Is this\
  \ a pigeon? Is This a Pigeon? Uploaded by shevyrolet Is This A Pigeon? Meme Challa...\
  \ Is This a Pigeon? Uploaded by shevyrolet Is this a Pigeon ? - Minute M\xE8me Is\
  \ This a Pigeon? Uploaded by shevyrolet Origen del meme is this a pig... Is This\
  \ a Pigeon? Uploaded by shevyrolet || Is this a Pigeon? || Detro... Is This a Pigeon?\
  \ Uploaded by shevyrolet Is This a Pigeon?: The World'... Is This a Pigeon? Uploaded\
  \ by shevyrolet + Add a Video View All Videos Recent Images 436 total Is This a\
  \ Pigeon? Uploaded by Christian Frates Is This a Pigeon? Uploaded by metal poochyena\
  \ Is This a Pigeon? Uploaded by Triplem Is This a Pigeon? Uploaded by Jaimie Hamilton\
  \ Is This a Pigeon? Uploaded by PMRY Studio Is This a Pigeon? Uploaded by Edgar\
  \ Weebling Is This a Pigeon? Uploaded by Excitebot theLEGO Is This a Pigeon? Uploaded\
  \ by Excitebot theLEGO Is This a Pigeon? Uploaded by Edgar Weebling Is This a Pigeon?\
  \ Uploaded by Triplem Is This a Pigeon? Uploaded by Triplem Is This a Pigeon? Uploaded\
  \ by Jaimie Hamilton + Add an Image View All Images Sign up for our Newsletter Top\
  \ Comments Delete Sensitive CrashGordon94 Feb 10, 2015 at 01:19PM EST +120 Reply\
  \ Delete Sensitive dancing cactuar Feb 10, 2015 at 04:28PM EST No, this is Patrick!\
  \ +34 Reply + Add a Comment Comments (52) Display Comments Add a Comment Top Entries\
  \ This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (12) Miluk\
  \ Investigator & Cataloger & Commentator Z. Database Moderator & Rage Comicologist\
  \ MScratch Database Moderator & Historical Meme Historian & \u300CStand User\u300D\
  \ RandomMan Database Moderator & God Tier Swag & Protip Advisor & Karma Tycoon &\
  \ Meme Boi Brad Digital Archaeologist & Treasurer & Pundit & Gallery Housekeeper\
  \ Y F Digital Archaeologist & Treasurer & Media Maid Don Administrator & Meme Daddy\
  \ 3kole5 Sr. Entry Moderator Matt Secretary of Memes Juicydeath1025 Sr. Entry Moderator\
  \ andcallmeshirley Digital Archaeologist & Treasurer & Collection Butler shevyrolet\
  \ Digital Archaeologist & Treasurer & Media Bus Boy \u25BC + Request Editorship\
  \ View All Editors Today's Top Image Galleries Assassination of UnitedHealthcare\
  \ CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing Digital Circus About\
  \ Our Story Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes\
  \ News Staff Contact Extras! Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/is-this-a-pigeon
template_id: pigeon
text:
- align: center
  anchor_x: 0.15
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 0.35
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.71
  anchor_y: 0.3
  angle: 0.0
  color: white
  font: thick
  scale_x: 0.175
  scale_y: 0.1
  start: 0.0
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: khaki
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.4
  stop: 1.0
  style: default
text_zones: 3
