example:
- why don't we take all the memes
- and put them on memegen
keywords:
- null
name: Push it somewhere else Patrick
overlay:
- angle: 0.0
  center_x: 0.1
  center_y: 0.45
  scale: 0.2
- angle: 0.0
  center_x: 0.775
  center_y: 0.85
  scale: 0.25
scraped_content: "Push It Somewhere Else Patrick | Know Your Meme Yo! You must login\
  \ or signup first! Already a memeber? Login Now! Don't have an account? Sign up\
  \ Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos Submit\
  \ \u2192 Images Trending Most Commented Most Favorited High Score Low Score Most\
  \ Viewed All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Push It Somewhere Else Patrick Added 14 years ago / Updated 12 days ago Confirmed\
  \ 472,932 Part of a series on SpongeBob SquarePants. [View Related Entries] View\
  \ All 201 Images Navigation About \u2022 Origin \u2022 Spread \u2022 Various Examples\
  \ \u2022 Search Interest \u2022 External References \u2022 Recent Images About Push\
  \ It Somewhere Else Patrick (also known as \"Pushing Patrick\") is an image macro\
  \ series based on a scene from the animated television series SpongeBob SquarePants.\
  \ The captions typically use the snowclone template \u201CWe should take X and put\
  \ it Y\u201D or \u201CWe should X and Y\" to suggest an alternative solution to\
  \ a given problem. Origin The screen capture used in the image macro comes from\
  \ the Spongebob Squarepants episode \"Sandy, SpongeBob, and the Worm,\"[3] originally\
  \ aired on October 12th, 2001. In the episode, the character Patrick Star provides\
  \ a possible solution for dealing with the threat of an Alaskan Bull Worm, by suggesting\
  \ they relocate the entire town (shown below). \"We should take Bikini Bottom and\
  \ push it somewhere else.\" A Meme Generator[5] page for \u201CPush is Somewhere\
  \ Else Patrick\u201D was created at an unknown date in 2010, featuring two pane\
  \ image macros using screen captures from the Spongebob Squarepants scene. Google\
  \ Trends similarly suggests that the search interest in the phrase began to pick\
  \ up sometime in August 2010. Spread On July 29th, 2010, a single topic Tumblr[1]\
  \ blog titled \u201CFuck Yeah Push It Somewhere Else Patrick\u201D was created,\
  \ which featured image macros with the Meme Generator watermark. By August 5th,\
  \ \u201CPush it somewhere else Patrick\u201D had reached the tenth rank on Meme\
  \ Generator,[5] making it part of the \u201CDemigod Tier.\u201D On July 7th, 2011,\
  \ the Internet humor blog Smosh[6] published a post titled \"Best of the 'Push it\
  \ Somewhere Else Patrick' Meme,\" featuring a compilation of notable examples from\
  \ the series. Several Facebook[4] pages have been created referencing Patrick's\
  \ line in the Spongebob Squarepants scene. As of October 30th, 2012, a Quickmeme[2]\
  \ page has accumulated over 43,500 submissions and the Meme Generator[5] page has\
  \ received over 40,000 items. Various Examples Blank Template Search Interest External\
  \ References [1] Tumblr \u2013 Fuck Yeah Pushing PAtrick started on July 12, 2010.\
  \ [2] Quickmeme \u2013 Push It Somewhere Else Patrick [3] Spongebob Wiki \u2013\
  \ Sandy Spongebob and the Worm [4] Facebook \u2013 Push it somewhere else Patrick\
  \ [5] Meme Generator \u2013 Push it somewhere else Patrick [6] Smosh \u2013 Best\
  \ of Push it Somewhere Else PAtrick star 4chan push it somewhere else memegenerator\
  \ image macro patrick Share Pin Related Entries 218 total Mocking SpongeBob SpongeGar\
  \ / Primitive Sponge ... Squidward's Suicide Surprised Patrick View All Related\
  \ Entries Recent Images 201 total View All Images Recent Videos 0 total There are\
  \ no recent videos. Sign up for our Newsletter Load 122 Comments Comments 122 total\
  \ 161 Push It Somewhere Else Patrick 472,932 0 201 122 Part of a series on SpongeBob\
  \ SquarePants. [View Related Entries] Updated Dec 11, 2024 at 12:23PM EST by LiterallyAustin.\
  \ Added Jul 28, 2010 at 04:31AM EDT by TOAST7312. Like us on Facebook! Like 1.8M\
  \ Share Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the\
  \ video gallery, or 'r' to view a random entry. Meme Status Confirmed Year 2010\
  \ Origin 4chan Tags star, 4chan, push it somewhere else, memegenerator, image macro,\
  \ patrick About Push It Somewhere Else Patrick (also known as \"Pushing Patrick\"\
  ) is an image macro series based on a scene from the animated television series\
  \ SpongeBob SquarePants. The captions typically use the snowclone template \u201C\
  We should take X and put it Y\u201D or \u201CWe should X and Y\" to suggest an alternative\
  \ solution to a given problem. Origin The screen capture used in the image macro\
  \ comes from the Spongebob Squarepants episode \"Sandy, SpongeBob, and the Worm,\"\
  [3] originally aired on October 12th, 2001. In the episode, the character Patrick\
  \ Star provides a possible solution for dealing with the threat of an Alaskan Bull\
  \ Worm, by suggesting they relocate the entire town (shown below). \"We should take\
  \ Bikini Bottom and push it somewhere else.\" A Meme Generator[5] page for \u201C\
  Push is Somewhere Else Patrick\u201D was created at an unknown date in 2010, featuring\
  \ two pane image macros using screen captures from the Spongebob Squarepants scene.\
  \ Google Trends similarly suggests that the search interest in the phrase began\
  \ to pick up sometime in August 2010. Spread On July 29th, 2010, a single topic\
  \ Tumblr[1] blog titled \u201CFuck Yeah Push It Somewhere Else Patrick\u201D was\
  \ created, which featured image macros with the Meme Generator watermark. By August\
  \ 5th, \u201CPush it somewhere else Patrick\u201D had reached the tenth rank on\
  \ Meme Generator,[5] making it part of the \u201CDemigod Tier.\u201D On July 7th,\
  \ 2011, the Internet humor blog Smosh[6] published a post titled \"Best of the 'Push\
  \ it Somewhere Else Patrick' Meme,\" featuring a compilation of notable examples\
  \ from the series. Several Facebook[4] pages have been created referencing Patrick's\
  \ line in the Spongebob Squarepants scene. As of October 30th, 2012, a Quickmeme[2]\
  \ page has accumulated over 43,500 submissions and the Meme Generator[5] page has\
  \ received over 40,000 items. Various Examples Blank Template Search Interest External\
  \ References [1] Tumblr \u2013 Fuck Yeah Pushing PAtrick started on July 12, 2010.\
  \ [2] Quickmeme \u2013 Push It Somewhere Else Patrick [3] Spongebob Wiki \u2013\
  \ Sandy Spongebob and the Worm [4] Facebook \u2013 Push it somewhere else Patrick\
  \ [5] Meme Generator \u2013 Push it somewhere else Patrick [6] Smosh \u2013 Best\
  \ of Push it Somewhere Else PAtrick Related Entries 218 total Mocking SpongeBob\
  \ SpongeGar / Primitive Sponge / Caveman Spongebob Squidward's Suicide Surprised\
  \ Patrick *breath in* Boi Inappropriate Timing Spongebob Banner \"Ocean Man\" by\
  \ Ween Welcome to the Salty Spitoon. How Tough Are Ya? Fake History No, This Is\
  \ Patrick Smitty Werbenjagermanjensen You Like Krabby Patties, Don\u2019t You Squidward?\
  \ View All Related Entries Recent Videos There are no videos currently available.\
  \ + Add a Video Recent Images 201 total Push It Somewhere Else Patrick Uploaded\
  \ by Classic Rage Meme Rook 96 Push It Somewhere Else Patrick Uploaded by JapanYoshiPlz\
  \ Push It Somewhere Else Patrick Uploaded by MisterZygarde64 Push It Somewhere Else\
  \ Patrick Uploaded by MisterZygarde64 Push It Somewhere Else Patrick Uploaded by\
  \ Wesley Push It Somewhere Else Patrick Uploaded by SpongicX Push It Somewhere Else\
  \ Patrick Uploaded by Popcor11235 Push It Somewhere Else Patrick Uploaded by NoZaku\
  \ Push It Somewhere Else Patrick Uploaded by CartoonFreak666 Push It Somewhere Else\
  \ Patrick Uploaded by TwilighT Sparkller Push It Somewhere Else Patrick Uploaded\
  \ by Sir Soundwave Push It Somewhere Else Patrick Uploaded by Leafpodd + Add an\
  \ Image View All Images Sign up for our Newsletter Top Comments Delete Sensitive\
  \ Daft Punkjet Oct 19, 2012 at 09:42PM EDT Why isn't this confirmed yet? There's\
  \ another of these instances in the Binders Full of Women page\u2026it's proof that\
  \ the fad is still strong. +18 Reply Delete Sensitive pug on toast Jul 21, 2011\
  \ at 04:13PM EDT Definitely a meme, but a name too long. Change it to \"Pushing\
  \ Patrick\" maybe? +17 Reply + Add a Comment Comments (122) Display Comments Add\
  \ a Comment Top Entries This Month Meme Saika Kawakita Smile GIF Event Assassination\
  \ of UnitedHealthcare CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki\
  \ Sisters Culture Pornography Site Whisper View More Suggest a Change Edit History\
  \ Entry Editors (9) TOAST7312 Ogreenworld Former Entry Moderator DaDodacahedron\
  \ Conversationalist Olivia Gulin Original Gangster Don Administrator & Meme Daddy\
  \ Brad Digital Archaeologist & Treasurer & Pundit & Gallery Housekeeper RandomMan\
  \ Database Moderator & God Tier Swag & Protip Advisor & Karma Tycoon & Meme Boi\
  \ MScratch Database Moderator & Historical Meme Historian & \u300CStand User\u300D\
  \ Y F Digital Archaeologist & Treasurer & Media Maid \u25BC + Request Editorship\
  \ View All Editors Today's Top Image Galleries Assassination of UnitedHealthcare\
  \ CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing Digital Circus About\
  \ Our Story Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes\
  \ News Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/push-it-somewhere-else-patrick
template_id: patrick
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.15
  start: 0.15
  stop: 0.55
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.85
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.15
  start: 0.55
  stop: 1.0
  style: upper
text_zones: 2
