name: Push it somewhere else Patrick
source: http://knowyourmeme.com/memes/push-it-somewhere-else-patrick
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.15
  align: center
  start: 0.15
  stop: 0.55
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.85
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.15
  align: center
  start: 0.55
  stop: 1.0
example:
- why don't we take all the memes
- and put them on memegen
overlay:
- center_x: 0.1
  center_y: 0.45
  angle: 0.0
  scale: 0.2
- center_x: 0.775
  center_y: 0.85
  angle: 0.0
  scale: 0.25
scraped_content: About Push It Somewhere Else Patrick (also known as "Pushing Patrick")
  is an image macro series based on a scene from the animated television series SpongeBob
  SquarePants. The captions typically use the snowclone template “We should take X
  and put it Y” or “We should X and Y" to suggest an alternative solution to a given
  problem. Origin The screen capture used in the image macro comes from the Spongebob
  Squarepants episode "Sandy, SpongeBob, and the Worm,"[3] originally aired on October
  12th, 2001. In the episode, the character Patrick Star provides a possible solution
  for dealing with the threat of an Alaskan Bull Worm, by suggesting they relocate
  the entire town (shown below). "We should take Bikini Bottom and push it somewhere
  else." A Meme Generator[5] page for “Push is Somewhere Else Patrick” was created
  at an unknown date in 2010, featuring two pane image macros using screen captures
  from the Spongebob Squarepants scene. Google Trends similarly suggests that the
  search interest in the phrase began to pick up sometime in August 2010. Spread On
  July 29th, 2010, a single topic Tumblr[1] blog titled “Fuck Yeah Push It Somewhere
  Else Patrick” was created, which featured image macros with the Meme Generator watermark.
  By August 5th, “Push it somewhere else Patrick” had reached the tenth rank on Meme
  Generator,[5] making it part of the “Demigod Tier.” On July 7th, 2011, the Internet
  humor blog Smosh[6] published a post titled "Best of the 'Push it Somewhere Else
  Patrick' Meme," featuring a compilation of notable examples from the series. Several
  Facebook[4] pages have been created referencing Patrick's line in the Spongebob
  Squarepants scene. As of October 30th, 2012, a Quickmeme[2] page has accumulated
  over 43,500 submissions and the Meme Generator[5] page has received over 40,000
  items. Various Examples Blank Template Search Interest External References [1] Tumblr
  – Fuck Yeah Pushing PAtrick started on July 12, 2010. [2] Quickmeme – Push It Somewhere
  Else Patrick [3] Spongebob Wiki – Sandy Spongebob and the Worm [4] Facebook – Push
  it somewhere else Patrick [5] Meme Generator – Push it somewhere else Patrick [6]
  Smosh – Best of Push it Somewhere Else PAtrick
aside_content: MemeStatusConfirmedYear2010Origin4chanTagsstar,4chan,push it somewhere
  else,memegenerator,image macro,patrick
added_at: '2010-07-28T04:31:24-04:00'
