name: Push it somewhere else Patrick
source: http://knowyourmeme.com/memes/push-it-somewhere-else-patrick
keywords:
  -
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.15
    align: center
    start: 0.15
    stop: 0.55
  - style: upper
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.85
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.15
    align: center
    start: 0.55
    stop: 1.0
example:
  - why don't we take all the memes
  - and put them on memegen
overlay:
  - center_x: 0.1
    center_y: 0.45
    angle: 0.0
    scale: 0.2
  - center_x: 0.775
    center_y: 0.85
    angle: 0.0
    scale: 0.25
