name: I Guarantee It
source: http://knowyourmeme.com/memes/george-zimmer-i-guarantee-it
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- you're gonna like the way you look
- i guarantee it
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About George Zimmer Copypasta is a series of anecdotal stories that
  are narrated in the voice of the founder and CEO of the U.S. clothing retailer Men''s
  Wearhouse. Examples of the series detail Zimmer''s machismo and sexual escapades
  with colorful sexual metaphors. Similar to Billy Mays copypasta, each story typically
  begins with his TV commercial tagline "Hi, I''m George Zimmer, founder and CEO of
  the Men''s Wearhouse" and always ends with "I GUARANTEE IT." Origin The first known
  instance of the copypasta was posted via pop singer Ashlee Simpson''s official fan
  message board on October 23rd, 2004. Earlier that day, Simpson became involved in
  a scandal after she was seen lip-synching during her musical guest performance on
  Saturday Night Live, a late-night comedy program well-known for its traditionally
  live musical performances by famous singers and artists. In response to the mocking
  threads posted by Simpson''s detractors and anti-fans, the singer replied to the
  thread by saying people should just get over the mishap and move on. Shortly afterwards,
  a reader known as "George_Zimmer"[1] on the message board responded to Simpson''s
  post with the following message: HI… I''M GEORGE ZIMMER – FOUNDER AND CEO OF THE
  MEN''S WEARHOUSE. ASHLEE.. I WOULD LIKE TO FUCK YOU NICE AND DEEP IN THE SHOWER
  – YOUR FIST CLENCHING HALF OF MY COCK AT THE BASE WHILE THE OTHER HALF SLOWLY PENETRATES
  YOU. YOU WILL BE BLINDFOLDED WITH A HAIR FULL OF SHAMPOO WHILE RECITING THE LYRICS
  TO THE BEATLES'' ROCKY RACOON. WHEN YOU GET TO THE PART ABOUT GIDEON''S BIBLE, I
  WILL IGNITE MY COCK FUSE AND BLOW A LOAD SO HUGE YOU''LL GROW AN ADAM''S APPLE.
  I GUARANTEE IT. Although it remains little known whether the copypasta had existed
  prior to the post on Ashlee Simpson''s fan site, the unique style of anecdote became
  widespread through reposts on General Mayhem and 4chan amongst other places. George
  Zimmer George Zimmer was born in the state of New York in 1948. He joined his father
  in the men''s clothing business and became the founder and CEO of Men''s Wearhouse,
  a men''s clothing retailer chain. Zimmer has appeared in many of his company''s
  TV commercials in which he famously utters the company slogan: "You''re going to
  like the way you look. I guarantee it." Spread On that same day it was posted on
  Ashlee Simpson''s fan site, a similar version was posted on General Mayhem[2] forum
  in a thread about Ashlee Simpson''s Saturday Night Live performance. In May 2006,
  the copypasta phenomenon spread over to YTMND[3] with the creation of "I Guarantee
  It!" by one of the site moderators fyrestorm, who paired an obscene drawing of George
  Zimmer with "The Wings," the main theme of the 2005 romantic drama film Brokeback
  Mountain. In the following month, YTMND user boomaga followed up with another remix
  using both Zimmer''s quote as well as another obscene quote attributed to porn actor
  Peter North. George Zimmer copypasta has been also seen on Facebook[4], MySpace[5],
  Wikipedia[6] and Urban Dictionary.[7] Notable Examples 311 Edition I''M GEORGE ZIMMER,
  FOUNDER AND CEO OF THE MEN''S WEARHOUSE. MY SECRETARY, FOLLOWING A BARBARIC BEAVER
  BEATING THAT SLOUGHED OFF HER UTERINE LINING MORE EFFECTIVELY THAN HER OWN MENSTRUAL
  CYCLE, INFORMED ME THAT MY TWO LEAST FAVORITE ARTISTS, 311 AND SCOTT STAPP, WERE
  RECENTLY INVOLVED IN A SCUFFLE. HISTORICALLY A MEDIATOR, I FLEW IN MY LEARJET TO
  MEET THE TWO BANDS. THE TWO GROUPS WERE WHINING LIKE ANNA NICOLE SMITH AFTER INHERITANCE
  MONEY UNTIL I PREPPED THE MEMBERS OF 311 FOR THE IMPENDING IMPALEMENT WITH A COMPREHENSIVE
  COATING OF NUT NECTAR, GLUING THEM TO THE GROUND. AFTER SUSTAINING A BLUNT FORCE
  TRAUMA TO THE HEAD FROM MY CROTCH CRUSHING CONCUSSION CANE, STAPP WAS TAKEN ''HIGHER''
  THAN EVER BEFORE AS HE WAS BOUNCED LIKE A BABY UPON THE Z-MAN''S TWO-TON TROUSER-SCHNAUZER,
  WHILE THE 311 MEMBERS WERE HELD CAPTIVE BY THEIR OWN ASSHOLES LIKE BOWLING BALLS.
  THE FORCE FROM MY CULVERT-SIZED COCK SPLITTING STAPP APART WAS ENOUGH TO CAUSE HIM
  TO DEVELOP DUAL PERSONALITY DISORDER. AS STAPP PROCEEDED TO BLEED TO DEATH, MY STEADFAST
  SLUT-SPEARING SON-SIRING SKINFLUTE BURST THROUGH THE LEAD SINGER''S BVD''S, CAUSING
  HIM TO BREAK OUT INTO A RAPE-INSPIRED RENDITION OF ''COME ORIGINAL''. I COULD ONLY
  INTERPRET HIS SINGING TO INDICATE IT WAS TIME TO FINISH UP, SO I BURIED THE ALT-ROCK
  GREAT IN A GOOEY GRAVE OF GONAD GOULASH. MY GROIN YETI IS NOW THE SIXTH MEMBER OF
  311, I GUARANTEE IT. Chuck Norris Edition HI, I''M GEORGE ZIMMER, FOUNDER AND CEO
  OF THE MEN''S WEARHOUSE. I''D BEEN HEARING A LOT LATELY ABOUT THE MERITS OF THIS
  CHUCK NORRIS FELLOW, SO I THOUGHT I''D PAY HIM A VISIT- ZIMMER STYLE. AS I APPROACHED
  HIS HOUSE, I HEARD A TWIG SNAP BEHIND ME AND THEN OUT OF NOWHERE CAME THE LEG OF
  THE ONE AND ONLY CHUCK NORRIS. LUCKILY MY REFLEXES WERE TOO FAST FOR HIM. MY MASSIVE
  MASCULINE MEAT-PIPE BURST FORTH FROM MY FINELY-TAILORED TROUSERS, ENSNARING HIS
  LEG WITH THE POWER OF A THOUSAND ANACONDAS. HIS ONCE POWERFUL INSTRUMENT OF DEATH
  THUSLY DESTROYED, HE WAS COMPLETELY POWERLESS. I DECIDED THAT THAT UGLY MUG OF HIS
  WAS NOT UP TO ZIMMER STANDARDS, SO I DETERMINED TO DELIVER A MAKEOVER HE WOULDN''T
  SOON FORGET. HE BEGAN TO CRY LIKE A KITTEN UNDER A STEAMROLLER AS MY PULSATING PELVIC
  PILEDRIVER DELIVERED BLOW AFTER BLOW TO HIS EVER-SOFTENING SKULL. AS I FINISHED
  OFF MY FLESH-SCULPTURE, I REALIZED THAT I HAD FORMED HIS HEAD INTO THE SHAPE OF
  DEVIL''S TOWER. THE SHOCK CAUSED ME TO LET FORTH A FLOOD OF CAUSTIC COD CREME THAT
  BURNED OFF THAT RIDICULOUS STUBBLE HE CALLS A BEARD. HE''S UNCONCIOUS NOW, BUT HE''LL
  SOON WAKE UP. HE''S GONNA LIKE THE WAY HE LOOKS. I GUARANTEE IT. Size Comparison
  Edition HI, I''M GEORGE ZIMMER, FOUNDER AND CEO OF THE MENS WEARHOUSE. OBVIOUSLY,
  YOU PEOPLE CANNOT MATCH TO MY GREAT URETHA MOUTAIN TO YOUR PUNY FLESH WRINKLES SO
  YOU ALL DECIDE TO TRY AND 1-UP ME. I AM HERE TO TELL YOU THAT WILL BE POSSIBLE AS
  PLEASURING A GREAT HUMPBACK WHALE. GOOGLE_QUEEN, SINCE YOU''RE SO SMART AS YOU ELEQUENTLY
  SAY SO YOURSELF, YOU SHOULD KNOW THAT INDIVDIUALITY IS A MATTER OF BEING DIFFERENT.
  JUST BECAUSE I HAVE FUN DEFILING BEAUTIFUL YOUNG FEMALS AND CASUING HAVOC DOES NOT
  MAKE ME SICK AS IT IS ALL A MATTER OF OPINION. SAYING ''YOU NEED TO GET A LIFE''
  IS IMPLYING THAT YOU WANT ME TO LIVE A LIFE LIKE YOURS AS A LIFE, LIKE INDIVIDUALITY,
  WILL ALWAYS BE DIFFERENT. I GUARANTEE IT. Yellowstone Edition HI, I''M GEORGE ZIMMER,
  CEO AND FOUNDER OF THE MEN''S WEARHOUSE. ONE LATE EVENING, AS I WAS YODELING INTO
  THE CAVERNOUS COOCH OF MY COHABITATION PARTNER, I HAD A BRIGHT IDEA – TO STROKE
  MY MASSIVE MANLY MEATSICLE OVER THE BURNING FORESTS OF YELLOWSTONE. FIRE SUPPRESANT
  MAY NOT STOP THE RAGING FLAMES, BUT MY COLLOSAL COCK CONGLOMERATE WOULD. DOUSING
  THE FLAMES IN GEORGE''S JOCKSTRAP JUICE WOULD CAUSE THE FLAMES TO IMMEDIATELY EXTINGUISH,
  LEAVING NOTHING BUT TREES AND SLICK SACK SAUCE WITHIN THE PINES. WHILE WOODLAND
  ANIMALS WOULD NOT SURVIVE THE TORRENTIAL RAINS OF MY SUPER SPOOGE SYRUP, THE FOREST
  RANGERS, IF FEMALE, WOULD BE VERY APPRECIATIVE. I GUARANTEE IT. Search Interest
  External References [1] OkayPlayer – Ashlee Simpson''s message board = sheer hilarity
  [2] General Mayhem – lmao is ashlee simpson trying to be gwen stefani? [3] YTMND
  – George Zimmer [4] Facebook – George Zimmer [5] Myspace – Zimmerframe [6] Wikipedia
  – George Zimmer [7] Urban Dictionary – George Zimmer [8] Lurkmoar – George Zimmer
  [9] Tanasinn.info – George Zimmer [10] Chanarchive – Bill mays and friends'
aside_content: MemeStatusConfirmedYear2004OriginA post on a Ashlee Simpson message
  board(?)Tagscelebrity,trolling,men's wearhouse,commercial,copypasta,impersonation,tv,ashlee
  simpsonAdditional ReferencesEncyclopedia DramaticaWikipedia
added_at: '2009-06-08T15:52:57-04:00'
