example:
- "\u03C0"
- '3'
- The Bible
keywords:
- null
name: They're The Same Picture
overlay:
- angle: -12.0
  center_x: 0.275
  center_y: 0.19
  scale: 0.3
- angle: -12.0
  center_x: 0.8
  center_y: 0.25
  scale: 0.32
- angle: 0.0
  center_x: 0.665
  center_y: 0.65
  scale: 0.3
scraped_content: "They're The Same Picture | Know Your Meme Word Up! You must login\
  \ or signup first! Already a memeber? Login Now! Don't have an account? Sign up\
  \ Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos Submit\
  \ \u2192 Images Trending Most Commented Most Favorited High Score Low Score Most\
  \ Viewed All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO They're The Same Picture Added 6 years ago / Updated 3 years ago Confirmed\
  \ 607,000 Part of a series on The Office. [View Related Entries] View All 83 Images\
  \ Navigation About \u2022 Origin \u2022 Spread \u2022 Various Examples \u2022 Search\
  \ Interest \u2022 External References \u2022 Recent Images \u2022 Recent Videos\
  \ About They're The Same Picture is a two-panel exploitable meme based on a scene\
  \ from the television series The Office in which the character Pam presents two\
  \ pictures before Pam says they're the same picture in the second panel. Origin\
  \ On May 19th, 2011, the Office episode \"Search Committee\" premiered in the United\
  \ States. In the episode, Pam pranks acting manager Creed by asking him to spot\
  \ the differences between two pictures, clarifying off camera that they're actually\
  \ the same picture.[1] After seeing some use as a reaction image posted to make\
  \ the point that the user couldn't tell the difference between two things,[2] it\
  \ started seeing use as an exploitable beginning on June 22th, 2018, when an exploitable\
  \ comparing Fortnite to trash was posted to /r/MemeEconomy,[3] gaining over 26,000\
  \ points (shown below). Spread In the following months, the format was used to make\
  \ similar points about a number of subjects. For example, a post in /r/bojackhorseman\
  \ used the template to make a point about how the main character in Bojack Horseman\
  \ hates himself, gaining over 1,400 points (shown below, left). Another post referencing\
  \ Loss appeared in /r/MemeEconomy on June 23rd and gained over 95 points (shown\
  \ below, right). Other edits have used the format in a complimentary fashion. For\
  \ example, a post on /r/garlicbreadmemes comparing garlic bread to heaven gained\
  \ over 890 points after it was posted on June 23rd, 2018 (shown below, left). A\
  \ wholesome edit posted to /r/MemeEconomy on June 25th gained over 110 points (shown\
  \ below, right). Various Examples Search Interest External References [1] Reddit\
  \ \u2013 What episode has the \u2018corporate needs you to find the differences\
  \ between this picture and this picture? [2] Reddit \u2013 The Same Picture [3]\
  \ Reddit \u2013 Always buy Office memes. the office same picture they're the same\
  \ picture same picture reddit difference search committee Share Pin Related Entries\
  \ 21 total Schrute Facts No God, Please No! Young Michael Scott Shaking E... Jim\
  \ Halpert Smiling Through B... View All Related Entries Recent Images 83 total View\
  \ All Images Recent Videos 13 total View All Videos Sign up for our Newsletter Load\
  \ 4 Comments Comments 4 total 14 They're The Same Picture 607,018 13 83 4 Part of\
  \ a series on The Office. [View Related Entries] Updated May 09, 2021 at 01:00AM\
  \ EDT by Autumn Able. Added Nov 29, 2018 at 03:47PM EST by Darrel Gregory. Like\
  \ us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the image\
  \ gallery, 'v' to view the video gallery, or 'r' to view a random entry. Meme Status\
  \ Confirmed Type: Exploitable Year 2018 Origin The Office Tags the office, same,\
  \ picture, they're the same picture, same picture, reddit, difference, search committee\
  \ Additional References Meme Generator About They're The Same Picture is a two-panel\
  \ exploitable meme based on a scene from the television series The Office in which\
  \ the character Pam presents two pictures before Pam says they're the same picture\
  \ in the second panel. Origin On May 19th, 2011, the Office episode \"Search Committee\"\
  \ premiered in the United States. In the episode, Pam pranks acting manager Creed\
  \ by asking him to spot the differences between two pictures, clarifying off camera\
  \ that they're actually the same picture.[1] After seeing some use as a reaction\
  \ image posted to make the point that the user couldn't tell the difference between\
  \ two things,[2] it started seeing use as an exploitable beginning on June 22th,\
  \ 2018, when an exploitable comparing Fortnite to trash was posted to /r/MemeEconomy,[3]\
  \ gaining over 26,000 points (shown below). Spread In the following months, the\
  \ format was used to make similar points about a number of subjects. For example,\
  \ a post in /r/bojackhorseman used the template to make a point about how the main\
  \ character in Bojack Horseman hates himself, gaining over 1,400 points (shown below,\
  \ left). Another post referencing Loss appeared in /r/MemeEconomy on June 23rd and\
  \ gained over 95 points (shown below, right). Other edits have used the format in\
  \ a complimentary fashion. For example, a post on /r/garlicbreadmemes comparing\
  \ garlic bread to heaven gained over 890 points after it was posted on June 23rd,\
  \ 2018 (shown below, left). A wholesome edit posted to /r/MemeEconomy on June 25th\
  \ gained over 110 points (shown below, right). Various Examples Search Interest\
  \ External References [1] Reddit \u2013 What episode has the \u2018corporate needs\
  \ you to find the differences between this picture and this picture? [2] Reddit\
  \ \u2013 The Same Picture [3] Reddit \u2013 Always buy Office memes. Related Entries\
  \ 21 total Schrute Facts No God, Please No! Young Michael Scott Shaking Ed Truck's\
  \ Hand Jim Halpert Smiling Through Blinds Parkour! (The Office) Looks at the Camera\
  \ Like I'm on The Office I Am Aware of the Effect I Have on Women Jim Halpert Pointing\
  \ to Whiteboard Did I Stutter (Stanley - The Office) Phyllis and Ryan Office Christmas\
  \ Party Photo Days Since Our Last Nonsense Racist Jim Halpert View All Related Entries\
  \ Recent Videos 13 total They're The Same Scripture They're The Same Picture Uploaded\
  \ by Secrios Deathrend Karens be like (They're the s... They're The Same Picture\
  \ Uploaded by Y F THEY'RE THE SAME PICTURE They're The Same Picture Uploaded by\
  \ Y F They're the same picture but ... They're The Same Picture Uploaded by andcallmeshirley\
  \ They're the same picture They're The Same Picture Uploaded by andcallmeshirley\
  \ theyre the same picture They're The Same Picture Uploaded by andcallmeshirley\
  \ find the difference They're The Same Picture Uploaded by andcallmeshirley They're\
  \ the Same Picture - Un... They're The Same Picture Uploaded by andcallmeshirley\
  \ + Add a Video View All Videos Recent Images 83 total They're The Same Picture\
  \ Uploaded by Monkey-Thing They're The Same Picture Uploaded by Jaimie Hamilton\
  \ They're The Same Picture Uploaded by funnyfaceking They're The Same Picture Uploaded\
  \ by Nyazilla They're The Same Picture Uploaded by funnyfaceking They're The Same\
  \ Picture Uploaded by Evilthing They're The Same Picture Uploaded by CYSYS8993 They're\
  \ The Same Picture Uploaded by Excitebot theLEGO They're The Same Picture Uploaded\
  \ by MegaDitto89 They're The Same Picture Uploaded by Excitebot theLEGO They're\
  \ The Same Picture Uploaded by Doge Charger They're The Same Picture Uploaded by\
  \ Angel Chavez + Add an Image View All Images Sign up for our Newsletter + Add a\
  \ Comment Comments (4) Display Comments Add a Comment Top Entries This Month Meme\
  \ Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare CEO Person Luigi\
  \ Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography Site Whisper\
  \ View More Suggest a Change Edit History Entry Editors (7) Darrel Gregory Jr. Researcher\
  \ Adam Know Your Meme Universal Champion 3kole5 Sr. Entry Moderator Y F Digital\
  \ Archaeologist & Treasurer & Media Maid TjsWorld2011 Jr. Researcher andcallmeshirley\
  \ Digital Archaeologist & Treasurer & Collection Butler Autumn Able Sr. Entry Moderator\
  \ \u25BC + Request Editorship View All Editors Today's Top Image Galleries Assassination\
  \ of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing\
  \ Digital Circus About Our Story Site Rules Policies and Guidelines Credits Contact\
  \ Meme DB Memes Episodes News Staff Contact Extras! Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/theyre-the-same-picture
template_id: same
text:
- align: center
  anchor_x: 0.06
  anchor_y: 0.015
  angle: -12.0
  color: black
  font: thin
  scale_x: 0.35
  scale_y: 0.3
  start: 0.0
  stop: 1.0
  style: none
- align: center
  anchor_x: 0.525
  anchor_y: 0.06
  angle: -12.0
  color: black
  font: thin
  scale_x: 0.45
  scale_y: 0.3
  start: 0.0
  stop: 1.0
  style: none
- align: center
  anchor_x: 0.45
  anchor_y: 0.775
  angle: 0.0
  color: white
  font: thick
  scale_x: 0.4
  scale_y: 0.15
  start: 0.0
  stop: 1.0
  style: default
text_zones: 3
