name: They're The Same Picture
source: https://knowyourmeme.com/memes/theyre-the-same-picture
keywords:
- null
text:
- style: none
  color: black
  font: thin
  anchor_x: 0.06
  anchor_y: 0.015
  angle: -12.0
  scale_x: 0.35
  scale_y: 0.3
  align: center
  start: 0.0
  stop: 1.0
- style: none
  color: black
  font: thin
  anchor_x: 0.525
  anchor_y: 0.06
  angle: -12.0
  scale_x: 0.45
  scale_y: 0.3
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: white
  font: thick
  anchor_x: 0.45
  anchor_y: 0.775
  angle: 0.0
  scale_x: 0.4
  scale_y: 0.15
  align: center
  start: 0.0
  stop: 1.0
example:
- π
- '3'
- The Bible
overlay:
- center_x: 0.275
  center_y: 0.19
  angle: -12.0
  scale: 0.3
- center_x: 0.8
  center_y: 0.25
  angle: -12.0
  scale: 0.32
- center_x: 0.665
  center_y: 0.65
  angle: 0.0
  scale: 0.3
scraped_content: About They're The Same Picture is a two-panel exploitable meme based
  on a scene from the television series The Office in which the character Pam presents
  two pictures before Pam says they're the same picture in the second panel. Origin
  On May 19th, 2011, the Office episode "Search Committee" premiered in the United
  States. In the episode, Pam pranks acting manager Creed by asking him to spot the
  differences between two pictures, clarifying off camera that they're actually the
  same picture.[1] After seeing some use as a reaction image posted to make the point
  that the user couldn't tell the difference between two things,[2] it started seeing
  use as an exploitable beginning on June 22th, 2018, when an exploitable comparing
  Fortnite to trash was posted to /r/MemeEconomy,[3] gaining over 26,000 points (shown
  below). Spread In the following months, the format was used to make similar points
  about a number of subjects. For example, a post in /r/bojackhorseman used the template
  to make a point about how the main character in Bojack Horseman hates himself, gaining
  over 1,400 points (shown below, left). Another post referencing Loss appeared in
  /r/MemeEconomy on June 23rd and gained over 95 points (shown below, right). Other
  edits have used the format in a complimentary fashion. For example, a post on /r/garlicbreadmemes
  comparing garlic bread to heaven gained over 890 points after it was posted on June
  23rd, 2018 (shown below, left). A wholesome edit posted to /r/MemeEconomy on June
  25th gained over 110 points (shown below, right). Various Examples Search Interest
  External References [1] Reddit – What episode has the ‘corporate needs you to find
  the differences between this picture and this picture? [2] Reddit – The Same Picture
  [3] Reddit – Always buy Office memes.
aside_content: MemeStatusConfirmedType:ExploitableYear2018OriginThe OfficeTagsthe
  office,same,picture,they're the same picture,same picture,reddit,difference,search
  committeeAdditional ReferencesMeme Generator
added_at: '2018-11-29T15:47:06-05:00'
