example:
- ''
- so i got that goin' for me, which is nice
keywords:
- null
name: So I Got That Goin' For Me, Which is Nice
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "So I Got That Goin' For Me, Which is Nice | Know Your Meme Word\
  \ Up! You must login or signup first! Already a memeber? Login Now! Don't have an\
  \ account? Sign up Now! Meme Encyclopedia All Cultures Events People Sites Subcultures\
  \ Videos Submit \u2192 Images Trending Most Commented Most Favorited High Score\
  \ Low Score Most Viewed All Templates Upload an Image Articles News Explainers Collections\
  \ Interviews Meme Insider Magazine More Discord Newsletter Episodes Forums Meme\
  \ Store Login Abstract user icon Memes Categories Trending News Images Trending\
  \ Images Videos Trending Videos Editorials Meme Insider Magazine Newsletter Policies\
  \ and Guidelines Meme Store Old site Login Know Your Meme is the property of Literally\
  \ Media \xA92024 Literally Media. All Rights Reserved. This image Of Woman Confidently\
  \ Strolling Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years\
  \ Ago, This Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The\
  \ Anarchy Chess Memes Turns Two Years Old Today Phrase 'The Fridge Protects The\
  \ Snacks' A Growing Favorite Among Pickup Artist Influencers Jamie G, The Bosh British\
  \ Charva, Has Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also\
  \ Trending: Honey Extension Influencer Scam Renegade Raider Copypasta Assassination\
  \ of UnitedHealthcare CEO So I Got That Goin' For Me, Which is Nice Added 11 years\
  \ ago / Updated 8 years ago Confirmed 270,660 Part of a series on Bill Murray. [View\
  \ Related Entries] View All 26 Images Navigation About \u2022 Origin \u2022 Spread\
  \ \u2022 Notable Examples \u2022 Search Interest \u2022 External References \u2022\
  \ Recent Images About \"So I Got That Goin' For Me, Which is Nice\" is an advice\
  \ animal image macro series featuring a screen capture of the character Carl Spackler\
  \ (played by Bill Murray) from the 1980 comedy film Caddyshack. The captions usually\
  \ begin with a sentence revealing a personal problem or ordeal, followed by a notion\
  \ of a silver lining and the original quote from Caddyshack in verbatim. Origin\
  \ In the film Caddyshack, assistant greenskeeper Carl Spackler tells a story about\
  \ receiving a blessing in lieu of a tip while caddying for the Dalai Lama, ending\
  \ the anecdote with \"So I got that goin' for me, which is nice\" (shown below).\
  \ On June 23rd, 2013, Redditor Thereminz submitted an image macro of Carl Spackler\
  \ to the /r/AdviceAnimals[1] subreddit, which included a caption about losing his\
  \ job and having dental work done with the saving grace of receiving a gift of Reddit\
  \ gold (shown below). Within the first five months, the post gained over 7,300 up\
  \ votes and 75 comments. Spread On July 19th, 2013, Redditor yellow6r submitted\
  \ a Carl Spackler captioned image to /r/AdviceAnimals[2] celebrating the creation\
  \ of a moderately successful image macro (shown below, left), which received more\
  \ than 3,000 up votes and 30 comments in the next five months. On July 23rd, Redditor\
  \ Boozbooznbooz submitted a post to /r/AdviceAnimals[3] lamenting being stuck at\
  \ an office job all day, which including a Carl Spackler image macro celebrating\
  \ his Reddit profile anniversary (shown below, right). Within four months, the post\
  \ garnered upwards of 2,400 up votes and 15 comments. On November 27th, Redditor\
  \ indaochan posted an image macro to /r/AdviceAnimals[4] (shown below, left) mocking\
  \ Time Magazine's \"Person of the Year\" cover from 2006, which declared everyone\
  \ reading the magazine the year's winner. In the following three weeks, the post\
  \ gained over 18,000 up votes and 500 comments. On December 17th, Redditor acidulous\
  \ submitted a Carl Spackler image macro to /r/AdviceAnimals[5] about losing control\
  \ of several bodily functions (shown below, right), accumulating more than 12,200\
  \ up votes and 260 comments in the first 24 hours. Notable Examples Search Interest\
  \ External References [1] Reddit \u2013 trying to be positive over the past few\
  \ days [2] Reddit \u2013 This week is turning out pretty well [3] Reddit \u2013\
  \ I may be stuck at a desk staring at my computer for 12 hours today [4] Reddit\
  \ \u2013 It was an odd surprise that made me smile [5] Reddit \u2013 Serious it\
  \ felt like I was leaking out of almost every hole image macro celebrity film bill\
  \ murray screen capture caddyshack carl spackler Share Pin Related Entries 1 total\
  \ Sad Bill Murray Recent Images 26 total View All Images Recent Videos 0 total There\
  \ are no recent videos. Sign up for our Newsletter Load 61 Comments Comments 61\
  \ total 9 So I Got That Goin' For Me, Which is Nice 270,660 0 26 61 Part of a series\
  \ on Bill Murray. [View Related Entries] Updated Jun 11, 2016 at 04:20PM EDT by\
  \ Z.. Added Dec 18, 2013 at 05:45PM EST by Don. Like us on Facebook! Like 1.8M Share\
  \ Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the video\
  \ gallery, or 'r' to view a random entry. Meme Status Confirmed Type: Image Macro\
  \ Year 2013 Origin Reddit Tags image macro, celebrity, film, bill murray, screen\
  \ capture, caddyshack, carl spackler About \"So I Got That Goin' For Me, Which is\
  \ Nice\" is an advice animal image macro series featuring a screen capture of the\
  \ character Carl Spackler (played by Bill Murray) from the 1980 comedy film Caddyshack.\
  \ The captions usually begin with a sentence revealing a personal problem or ordeal,\
  \ followed by a notion of a silver lining and the original quote from Caddyshack\
  \ in verbatim. Origin In the film Caddyshack, assistant greenskeeper Carl Spackler\
  \ tells a story about receiving a blessing in lieu of a tip while caddying for the\
  \ Dalai Lama, ending the anecdote with \"So I got that goin' for me, which is nice\"\
  \ (shown below). On June 23rd, 2013, Redditor Thereminz submitted an image macro\
  \ of Carl Spackler to the /r/AdviceAnimals[1] subreddit, which included a caption\
  \ about losing his job and having dental work done with the saving grace of receiving\
  \ a gift of Reddit gold (shown below). Within the first five months, the post gained\
  \ over 7,300 up votes and 75 comments. Spread On July 19th, 2013, Redditor yellow6r\
  \ submitted a Carl Spackler captioned image to /r/AdviceAnimals[2] celebrating the\
  \ creation of a moderately successful image macro (shown below, left), which received\
  \ more than 3,000 up votes and 30 comments in the next five months. On July 23rd,\
  \ Redditor Boozbooznbooz submitted a post to /r/AdviceAnimals[3] lamenting being\
  \ stuck at an office job all day, which including a Carl Spackler image macro celebrating\
  \ his Reddit profile anniversary (shown below, right). Within four months, the post\
  \ garnered upwards of 2,400 up votes and 15 comments. On November 27th, Redditor\
  \ indaochan posted an image macro to /r/AdviceAnimals[4] (shown below, left) mocking\
  \ Time Magazine's \"Person of the Year\" cover from 2006, which declared everyone\
  \ reading the magazine the year's winner. In the following three weeks, the post\
  \ gained over 18,000 up votes and 500 comments. On December 17th, Redditor acidulous\
  \ submitted a Carl Spackler image macro to /r/AdviceAnimals[5] about losing control\
  \ of several bodily functions (shown below, right), accumulating more than 12,200\
  \ up votes and 260 comments in the first 24 hours. Notable Examples Search Interest\
  \ External References [1] Reddit \u2013 trying to be positive over the past few\
  \ days [2] Reddit \u2013 This week is turning out pretty well [3] Reddit \u2013\
  \ I may be stuck at a desk staring at my computer for 12 hours today [4] Reddit\
  \ \u2013 It was an odd surprise that made me smile [5] Reddit \u2013 Serious it\
  \ felt like I was leaking out of almost every hole Related Entries 1 total Sad Bill\
  \ Murray Recent Videos There are no videos currently available. + Add a Video Recent\
  \ Images 26 total So I Got That Goin' For Me, W... Uploaded by Particle Mare So\
  \ I Got That Goin' For Me, W... Uploaded by False_Skeptic So I Got That Goin' For\
  \ Me, W... Uploaded by \xAD\xAD\xAD\xAD\xAD\xAD\xAD\xAD\xAD\xAD So I Got That Goin'\
  \ For Me, W... Uploaded by Gabenus Trollucus So I Got That Goin' For Me, W... Uploaded\
  \ by 3went So I Got That Goin' For Me, W... Uploaded by syco87 So I Got That Goin'\
  \ For Me, W... Uploaded by Brad So I Got That Goin' For Me, W... Uploaded by Brad\
  \ So I Got That Goin' For Me, W... Uploaded by Brad So I Got That Goin' For Me,\
  \ W... Uploaded by Brad So I Got That Goin' For Me, W... Uploaded by Brad So I Got\
  \ That Goin' For Me, W... Uploaded by Brad + Add an Image View All Images Sign up\
  \ for our Newsletter Top Comments Delete Sensitive Weighted Companion Rectangle\
  \ Dec 18, 2013 at 07:20PM EST +48 Reply Delete Sensitive Homey Money Dec 18, 2013\
  \ at 07:49PM EST +35 Reply + Add a Comment Comments (61) Display Comments Add a\
  \ Comment Top Entries This Month Meme Saika Kawakita Smile GIF Event Assassination\
  \ of UnitedHealthcare CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki\
  \ Sisters Culture Pornography Site Whisper View More Suggest a Change Edit History\
  \ Entry Editors (3) Don Administrator & Meme Daddy Molly Horan Tumblr Historian\
  \ Z. Database Moderator & Rage Comicologist + Request Editorship View All Editors\
  \ Today's Top Image Galleries Assassination of UnitedHealthcare CEO Squirrel Girl\
  \ (Doreen Green) Team Fortress 2 The Amazing Digital Circus About Our Story Site\
  \ Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes News Staff\
  \ Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/so-i-got-that-goin-for-me-which-is-nice
template_id: nice
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
