name: So I Got That Goin' For Me, Which is Nice
source: http://knowyourmeme.com/memes/so-i-got-that-goin-for-me-which-is-nice
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- ''
- so i got that goin' for me, which is nice
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About "So I Got That Goin' For Me, Which is Nice" is an advice animal
  image macro series featuring a screen capture of the character Carl Spackler (played
  by Bill Murray) from the 1980 comedy film Caddyshack. The captions usually begin
  with a sentence revealing a personal problem or ordeal, followed by a notion of
  a silver lining and the original quote from Caddyshack in verbatim. Origin In the
  film Caddyshack, assistant greenskeeper Carl Spackler tells a story about receiving
  a blessing in lieu of a tip while caddying for the Dalai Lama, ending the anecdote
  with "So I got that goin' for me, which is nice" (shown below). On June 23rd, 2013,
  Redditor Thereminz submitted an image macro of Carl Spackler to the /r/AdviceAnimals[1]
  subreddit, which included a caption about losing his job and having dental work
  done with the saving grace of receiving a gift of Reddit gold (shown below). Within
  the first five months, the post gained over 7,300 up votes and 75 comments. Spread
  On July 19th, 2013, Redditor yellow6r submitted a Carl Spackler captioned image
  to /r/AdviceAnimals[2] celebrating the creation of a moderately successful image
  macro (shown below, left), which received more than 3,000 up votes and 30 comments
  in the next five months. On July 23rd, Redditor Boozbooznbooz submitted a post to
  /r/AdviceAnimals[3] lamenting being stuck at an office job all day, which including
  a Carl Spackler image macro celebrating his Reddit profile anniversary (shown below,
  right). Within four months, the post garnered upwards of 2,400 up votes and 15 comments.
  On November 27th, Redditor indaochan posted an image macro to /r/AdviceAnimals[4]
  (shown below, left) mocking Time Magazine's "Person of the Year" cover from 2006,
  which declared everyone reading the magazine the year's winner. In the following
  three weeks, the post gained over 18,000 up votes and 500 comments. On December
  17th, Redditor acidulous submitted a Carl Spackler image macro to /r/AdviceAnimals[5]
  about losing control of several bodily functions (shown below, right), accumulating
  more than 12,200 up votes and 260 comments in the first 24 hours. Notable Examples
  Search Interest External References [1] Reddit – trying to be positive over the
  past few days [2] Reddit – This week is turning out pretty well [3] Reddit – I may
  be stuck at a desk staring at my computer for 12 hours today [4] Reddit – It was
  an odd surprise that made me smile [5] Reddit – Serious it felt like I was leaking
  out of almost every hole
aside_content: MemeStatusConfirmedType:Image MacroYear2013OriginRedditTagsimage macro,celebrity,film,bill
  murray,screen capture,caddyshack,carl spackler
added_at: '2013-12-18T17:45:25-05:00'
