name: Doge
source: http://knowyourmeme.com/memes/doge
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- such meme
- very skill
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Doge (pronounced /ˈdoʊdʒ/ DOHJ) is a slang term for "dog"
  that is primarily associated with pictures of Shiba Inus (nicknamed "Shibe") and
  internal monologue captions on Tumblr. These photos may be photoshopped to change
  the dog''s face or captioned with interior monologues in Comic Sans font. The primary
  meme and iconography associated with Doge was the Shiba Inu named Kabosu, whose
  photos taken by her owner Atsuko Sato in early 2010 went viral across the internet,
  spawning numerous memes and larger trends in the following decades. Starting in
  2017, Ironic Doge formats gained prevalence over the original wholesome version
  as the memetic character continued to evolve. In 2024, president-elect Donald Trump
  announced plans to establish the Department of Government Efficiency (DOGE), named
  after the meme. Origin The use of the misspelled word "doge" to refer to a dog dates
  back to June 24th, 2005, when it was mentioned in an episode of Homestar Runner''s
  puppet show. In the episode titled "Biz Cas Fri 1"[2], Homestar calls Strong Bad
  his "d-o-g-e" while trying to distract him from his work. Identity On February 13th,
  2010, Japanese kindergarten teacher Atsuko Sato posted several photos of her rescue-adopted
  Shiba Inu dog Kabosu to her personal blog.[38] Among the photos included a peculiar
  shot of Kabosu sitting on a couch while glaring sideways at the camera with raised
  eyebrows (shown below, right). In December 2013, shortly after the breakout of "Doge,"
  the tech news site The Verge[39] published an article identifying Sato''s Kabosu
  as the original Shiba Inu depicted in the meme. In addition to Kabosu, The Verge
  also identified "Suki," a Shiba Inu who lives with San Francisco-based photographer
  Jonathan Fleming, as the scarfed dog portrayed in another popular instance of the
  meme. Spread On October 28th, 2010, a photo of Kabosu was submitted to the /r/Ads
  subreddit[3] with the title "LMBO LOOK @ THIS FUKKIN DOGE," where it received 266
  upvotes, 218 points overall and 48 comments prior to being archived. Sometime in
  April 2012, Tumblr user leonsumbitches[15] uploaded an audio file of a computer
  reading a passage written like the commands of a turn-based adventure game about
  encountering a "doge." The passage was paired with a photo of a woman patting a
  dog on the head[16] and has gained more than 33,000 notes as of July 2013. https://dailydoge.tumblr.com/post/21839788086/leonsumbitches-you-have-encountered-ａ-ｄｏｇｅ
  In response, the single-topic blog Your Daily Doge[17] was created but was quickly
  abandoned after reblogging leonsumbitches'' post several times. On May 7th, YouTuber
  KwandaoRen66 uploaded a video with a person reading the text over a fake Pokemon
  battle.[4] By June, doge threads in which numerous people shared photos of dogs
  in different outfits began appearing on 4chan boards, including /v/[11] (Video Games).
  The same month, a photoset of a dog with a cup and saucer balanced on his head went
  viral on Tumblr after airpi[14] referred to it as "Polite Doge." In August, the
  first doge single-topic blog, F--k Yeah Doge[13], launched on Tumblr. The growth
  in the summer of 2012 coincided with the popularity of the single topic Tumblr Shiba
  Confessions, as people began to refer to these dogs as "shibes."[18] In December
  2012, the term "doge" appeared on Reddit in a post submitted to /r/DogsIWannaHug.[6]
  The same month, an interior monologue captioned photo of a Schnauzer was submitted
  to Cheezburger[5] with the title "Schnauze." On January 8th, 2013, the subreddit
  /r/Doge[7] was created, sharing photos and videos of the captioned Shiba Inus.[8]
  In May, /r/dailydoge[9] was created to share one dog photo a day, captioned or not.
  Another single-topic blog, shibe-doge[12], launched in July 2013 dedicated to sharing
  Shiba Inu photos. On July 29th, 2013, a doge thread[19] was sticky-featured at the
  top of the 4chan board /s4s/ (Shit 4chan Says), garnering more than 600 replies.
  On November 20, 2013, YouTube implemented an Easter egg, that changes the text to
  be colored and in Comic Sans, much like the original internal-monologue style captions,
  when a user searches the phrase "doge meme".[22] On Tumblr, in addition to the captioned
  photos, the "doge" tag[10] often contains images of a Shiba Inu whose facial features
  have been manipulated, similar to Starecat. 4chan''s /r/Murica Raid On the evening
  of August 26th, 2013, a group of users on 4chan raided against Reddit''s tongue-in-cheek
  patriotic forum /r/Murica[20], flooding the subreddit''s frontpage with dozens of
  photoshopped images depicting the Doge character in All-American-themed settings
  (shown below). According to The Daily Dot''s report[21], the raid started late Sunday
  night and lasted until about 12:15 p.m. (ET) on August 27th, at which point /r/Murica''s
  moderators began removing Doge-related posts from the subreddit index. Unlike previous
  clashes between the users of 4chan and Reddit, the sudden influx of Doge images
  was reportedly met by little opposition from Reddit''s user base, reflecting the
  growing popularity of the character outside of Tumblr. Trademark Controversy On
  June 24th, 2014, the California-based gaming accessory company filed to trademark
  "Doge" with the United States patent office to sell card boxes and playing card
  covers with Kabosu''s likeness on the front. On June 23rd, The Daily Dot[41] published
  an article about the trademark filing, which included a statement from Ultra PRO
  General Manager Jay Kuo who claimed the trademark was filed to protect the company
  from being sued and that they would allow "royalty-free use for any vendor who wishes
  to use the mark." The article also contained a statement by the Intellectual Property
  Director at the Electronic Frontier Foundation Corynne McSherry, who noted that
  the filing is problematic because it attempts to trademark the entire word, not
  just a stylized version of it.[40] Death Hoax On March 31st, 2017, the Twitter account
  @CCTV reported that the Shiba Inu, Doge, had died at age 16.[42] The tweet received
  more than 8,400 retweets and 13,100 likes. However, the tweet was an April Fools''
  Day prank. According to Kabosu''s official Instagram account, @kabosumama, doge
  is alive and well. @Kabosumama posted a video of the dog (shown below), which received
  more than 4,600 likes and 22,600 views.[43] The post also contained the caption:
  "Kabosu is OK, she is alive! I don''t care that somebody told the lie that Kabosu
  is dead for April Fools'' Day, but one important thing for me is " Kabosu is a girl",
  she is a female dog." Dogecoin On December 6th, BitcoinTalk forum member Dogecoin
  introduced an alternative cryptocurrency based on the meme as a satire of the Bitcoin
  boom in a thread[23] titled "Dogecoin – very currency – many coin – wow – v1.1 Released."
  Similar to Bitcoin and its derivatives, Dogecoin can be mined and exchanged for
  goods and services among the participants, though it is programmed to level out
  at a higher threshold of up to 100 billion coins and prevent any use of special
  bitcoin-mining equipment like ASICs. In comparison, Bitcoin will cap out at 21 million
  coins and Litecoin will support up to 84 million coins in circulation. Following
  the launch of the official website,[24] a slew of social media channels and referential
  webpages soon emerged for Dogecoin, including a Twitter account[25] and a Facebook
  page,[26] racking up more than 1,000 followers and 1,800 likes within the first
  week, respectively. On December 8th, an entire subreddit community dedicated to
  the use of satirical cryptocurrency was launched at /r/dogecoin,[29] accruing more
  than 2,600 subscribers in just over a week. Throughout the first weekend of December,
  Dogecoin was highlighted by a number of tech news sites and blogs, providing a further
  boost to the value of the satirical currency.[35][36][37] By December 14th, an encyclopedic
  article[27] describing the concept of "Dogecoin" had been submitted by Wikipedia
  editor CitationNeeded. At its peak, the estimated value of DogeCoin skyrocketed
  to as high as $400.80 per coin (shown below).[28][31] As of December 15th, one Dogecoin
  (DOGE) is worth about $ 0.0002 USD, with a market capitalization of $1.45 million
  USD and 7.2% of the 100 billion total coins having been mined.[30][32][33][34] Political
  Examples Several Republican politicians have highlighted Doge-style image macros
  on their Twitter feeds. On December 23rd, 2013, Congressional Representatives Steve
  Stockman and Thomas Massie posted political Doge image macros (shown below). On
  June 9th, 2014, the official Republican National Committee Twitter feed posted a
  Doge image macro mocking Bill and Hillary Clinton. The same day, the official Democratic
  Party Twitter feed replied to the tweet mocking the use of Doge as being "as dated
  as your policies" (shown below). Ironic Doge Memes Ironic Doge Memes are memes that
  feature the Doge meme in strange or surreal circumstances. Many take the form of
  image macros and often feature edits to the Doge image for the purposes of dark
  or absurd humor. The format was popularized on deep iFunny and Facebook between
  2016 and 2017 and reached mainstream popularity in 2018, gaining prevalence over
  the original wholesome format. Atsuko Sato and Kabosu Interview On February 20th,
  2020, Japanese nursery teacher Atsuko Sato, the owner of Kabosu (Doge''s real name),
  conducted an interview with Know Your Meme to learn more about the origins of the
  meme and other details. Sato told KYM that Kabosu, 14 years old at the time, was
  a rescue dog when she adopted her from a kill shelter years before the meme. Kabosu''s
  breeder went out of business, and she was rescued by an animal welfare organization
  after being brought to an animal welfare center to be put down, along with 19 other
  Shiba Inu. Most of the Shiba Inu that were brought there with her were killed. Two
  years had passed since I lost my previous dog, and I wanted to live with a dog again.
  I looked at the information about the new arrivals that had just been advertised
  as looking for foster parents on the website and found out about Kabosu. Sixteen
  days after being brought to the animal welfare center, she became a member of my
  family. 2021 Doge NFT Auction In mid-June 2021, the photographs taken of Kabosu
  by Atsuko Sato that later became the Doge meme were auctioned off as a series of
  NFTs. On June 11th following the conclusion of the auction, the Doge NFT sold for
  roughly $4.06 million (1696.9 ETH), setting the record for the highest meme NFT
  auction ever. After the historic sale, Atsuko Sato donated a significant portion
  of the money to various charities, which included Plan International, Terra Renaissance,
  Florence, the Japanese Red Cross, World Food Program, Ashi Naga and Japan Heart.[44]
  As Kabosu became a meme people love so much, I came to believe that Kabosu was given
  a special mission by the universe. Through the launch of these NFTs, I''d like to
  help children in need all over the world. Kabosu and I would be very happy if we
  could help bring a smile to their face. Doge / Kabosu Cancer Diagnosis On December
  27th, 2022, Atsuko Sato announced on her Instagram[45] account @kabosumama that
  Kabosu (Doge) had been diagnosed with "acute cholangiohepatitis and chronic lymphoma
  leukemia," noting that she was in declining health but on medication to assist her
  recovery (seen below). The news of Kabosu''s cancer rapidly spread online shortly
  after, leading to an outpouring of support around the web. View this post on Instagram
  A post shared by かぼすママ (@kabosumama) In the following weeks and months, Sato continued
  sharing updates on Kabosu''s health as she slowly began to recover somewhat, according
  to her Instagram. For example, on February 9th, 2023, Sato said in an Instagram
  video that Kabosu was eating more food lately and doing therapy as part of her treatment,
  among other things (seen below). View this post on Instagram A post shared by かぼすママ
  (@kabosumama) On February 22nd, 2023, Atsuko Sato then posted another update on
  Kabosu''s status and shared images of her latest blood test results to her Instagram,[46]
  which noted that it was "an incredible recovery" as she thanked fans for their support.
  Doge / Kabosu''s Death On May 24th, 2024, Atsuko Sato announced on her Instagram[47]
  @kabosumama and blog[48] that Kabosu (Doge) died at the age of 18 after struggling
  with cancer. Sato wrote a message to Doge''s fans, saying, “To all of you who loved
  Kabosu, on the morning of the 24 May, Kabosu crossed the rainbow bridge. Thank you
  all so much for your support over the years.” The post (shown below) amassed more
  than 64,000 likes in a few hours. Doge''s death resulted in a massive outpouring
  of tributes, sentiments and memorials online, such as a post to the /r/Dogelore[49]
  subreddit on May 24th that received over 11,000 upvotes and 200 comments in 10 hours.
  Related Memes Wew Lad Wew Lad is an obfuscatory expression associated with circle
  jerking or shitposting, which is often accompanied by a poorly-drawn illustration
  of a man''s face known as the "Wrinkle Face" or a digitally altered picture of the
  Doge Shiba Inu. Cheems Cheems is an Ironic Doge character popular on /r/dogelore.
  His real name is Balltze, or Ball Ball. In memes, he is known for liking cheeseburgers,
  which he pronounces, "Cheemsburbger." Memes featuring Cheems are usually based upon
  the character humorously misspelling various words, particularly by including extra
  M letters and first appeared on /r/dogelore in June 2019. Swole Doge Swole Doge,
  also known as Chad Doge refers to a popular edit of Doge that imagines the character
  having an extremely muscular human body. The edit gained significant popularity
  in memes in major Doge meme pages on Facebook, Instagram and Reddit starting in
  July 2019. Swole Doge vs. Cheems Swole Doge vs. Cheems refers to a comparison format
  in which representatives of the same group from two historical eras are presented
  as Swole (Chad) Doge and Cheems and are compared to each other, similar to Virgin
  vs. Chad. Originating from a viral Facebook meme, the format gained popularity on
  Reddit and Facebook starting in mid-May 2020. Dogelore Dogelore is a subreddit dedicated
  exclusively to memes about Doge and related dog characters within the so-called
  "Doge lore" such as Walter, Perro, Cheems, Swole Doge and others. Created by /r/OKBR
  founder Kirbizia in 2018, the subreddit accumulated over 200,000 subscribers in
  two years and is one of the major hubs of Doge memes online. Department of Government
  Efficiency Department of Government Efficiency or DOGE refers to a planned state
  department in the United States whose establishment was announced by President-elect
  Donald Trump in November 2024. The planned department will be headed by American
  entrepreneurs Elon Musk and Vivek Ramaswamy. Following the announcement, the planned
  department, named after the Doge internet meme, became a subject of discussions
  and memes online. Various Examples Search Interest Editors Note: Search interest
  for the word "doge"[1] is partially inconsistent as it is also a Venetian term for
  "leader" used as a title in some Italian "crowned republics" including Genoa and
  Venice. Meme Trends External References [1] Wikipedia – Doge [2] Homestar Runner
  Wiki – Biz Caz Fri 1 [3] Reddit – /r/ads: LMBO LOOK @ THIS FUKKEN DOGE [4] YouTube
  – You have encountered A D O G E [5] Cheezburger – schnauze / 12/08/2012 [6] Reddit
  – /r/dogsiwannahug: Hugging precious doge / 12/24/2012 [7] Reddit – /r/doge / 01/08/2013
  [8] Reddit – /r/trees: Snope Doge / 01/17/2013 [9] Reddit – /r/dailydoge 05/16/2013
  [10] Tumblr – Posts tagged "doge" [11] Foolz Archive – Meet Doge / 06/16/2012 [12]
  Tumblr – shibe-doge web archive [13] Tumblr – f--kyeahdoge [14] Tumblr – airpi:
  A POLITE DOGE has approached you 06/24/2012 [15] Tumblr (via Wayback Machine) –
  leonsumbitches [16] Your Daily Doge – Reblog of leonsumbitches'' Post [17] Tumblr
  – Your Daily Doge [18] Tumblr – Posts Tagged "shibe" [19] 4chan – /s4s/: le sticky
  doge [20] Reddit – /r/Murica – Murica! F--k Yeah! [21] The Daily Dot – 4chan spammed
  Reddit with an army of Shiba Inus [22] Google Operating System – YouTube Easter
  Egg for Doge Meme [23] Bitcoin Talk Forum – [ANN][DOGE] Dogecoin – very currency
  – many coin – wow – v1.1 Released [24] Dogecoin.com – Dogecoin [25] Twitter – @Dogecoin''s
  Tweets [26] Facebook – Dogecoin [27] Wikipedia – Dogecoin [28] Doge Coin Official
  Forum – Topic: How many Dogecoins have you guys dug? [29] Reddit – /r/dogecoin [30]
  Coin Marketcap – DogeCoin 30-Day Market Cap Graph [31] Doge Coin Official Forum
  – [INFO] Current Average Value of DOGE [32] Slashgear – Dogecoin digital currency
  takes on Bitcoin with a bit of meme flair [33] Geek.com (via Wayback Machine) –
  Dogecoin: Not a viable alternative to Bitcoin, but possibly the best invention on
  the internet [34] Geekosystem (now The MarySue) – Dogecoin, A Cryptocurrency For
  Doges, Is Now A Thing [35] Dogecoin Forum (via Wayback Machine) – Dogewallet hacked!
  [36] The Verge – Millions of Dogecoin stolen in Christmas hack [37] Reddit – Dogewallet
  Explanation [38] Exblog – Kabosu112 [39] The Verge – Wow this Doge [40] United States
  Patent and Trademark Office – Doge [41] The Daily Dot – Doge Trademark Ultra PRO
  [42] Twitter – RIP, Doge! Shiba Inu who inspired popular Internet memes died in
  Japan aged 16 [43] Instagram – Kabosu is OK [44] Doge NFT Auction – Charities [45]
  Instagram – kabosumama [46] Instagram – kabosumama [47] Instagram – kabosumama [48]
  Kabochan Blog – May 24, 2024, Post [49] Reddit – r/dogelore'
aside_content: MemeStatusConfirmedType:Animal,Character,Exploitable,Image Macro,SlangYear2010OriginTumblrRegionJapanTagsanimal,dog,shiba
  inu,shibe,such doge,super shibe,japanese,tumblr,comic sans,photoshop meme,doges,dogges,reddit,bitcoin,dogecoin,canine,doge
  meme,atsuko sato,kabosu,doge memes,dogelore,kabosumamaAdditional ReferencesDictionary.comEncyclopedia
  DramaticaFacebookMeme GeneratorRedditTwitterUrban DictionaryWikipedia
added_at: '2013-07-24T16:29:55-04:00'
