name: Captain America Elevator Fight Dad Joke
source: https://knowyourmeme.com/memes/captain-america-elevator-fight-dad-joke
keywords:
- null
text:
- style: default
  color: khaki
  font: thick
  anchor_x: 0.0
  anchor_y: 0.23
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.1
  align: center
  start: 0.1
  stop: 1.0
- style: default
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.57
  angle: 0.0
  scale_x: 0.4
  scale_y: 0.08
  align: center
  start: 0.4
  stop: 1.0
- style: default
  color: khaki
  font: thick
  anchor_x: 0.5
  anchor_y: 0.56
  angle: 0.0
  scale_x: 0.5
  scale_y: 0.1
  align: center
  start: 0.7
  stop: 1.0
example:
- Have you ever eaten a clock?
- No, why?
- It's time consuming.
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Captain America Elevator Fight is an image macro series featuring
  screenshots from the films Captain America: The Winter Soldier and Avengers: Endgame
  in which Captain America fights a group of Hydra soldiers in an elevator. In February
  2020, a four-panel amalgamation of scenes from both films as a vehicle for various
  dad jokes went viral. Origin On April 4th, 2014, Marvel Studios released the film
  Captain America: The Winter Soldier.[1] In the film, Captain America (played by
  Chris Evans) fights a group of Hydra foot soldiers in an elevator (shown below,
  left). Roughly five years later, on April 26th, 2019, Marvel Studios released the
  film Avengers: Endgame, which features a recreation of the scene, in which Captain
  America whispers "Hail, Hydra" in the ear of Jasper Sitwell (Maximiliano Hernández)
  to avoid the fight (shown below, right).[2] [This video has been removed] The earliest
  available meme featuring a mashup of the two films together was published on June
  2nd, 2019. The meme features Captain America whispering to Sitwell, Sitwell responding
  with "Avengers Assemble" and, finally, a shot from Captain America: The Winter Soldier
  in which soldiers attack Captain America. The post, uploaded by Instagram [3] user
  @daily.dcmarvel.post, received more than 38,000 likes in less than one year (shown
  below). Spread The following year, on February 7th, 2020, Redditor[4] LazyMeercat
  shared a variation of the meme in which Captain America tells the dad joke "I saw
  my dog walk over sandpaper / he said rough rough." The post received more than 5,400
  points (98% upvoted) in less than three days (shown below, left). Over the next
  few days, others continued to share variations of the format. On February 8th, Instagram[5]
  user @trashcanpaul shared a variation with the joke "have you ever eaten a clock?
  / It''s time consuming." The post received more than 49,000 likes in less than two
  days (shown below, center). The following day, Redditor[6] ihazone shared a variation
  with the joke "Your flat earth movie was just nominated for an award / The Golden
  Globes." The post received more than 47,000 points (93% upvoted) and 100 comments
  in less than 24 hours (shown below, right). Various Examples Template Search Interest
  Not available. External References [1] Wikipedia – Captain America: The Winter Soldier
  [2] Wikipedia – Avengers: Endgame [3] Instagram – @daily.dcmarvel.post''s Post [4]
  Reddit – /r/memetemplatesofficial [5] Instagram – @trashcanpaul''s Post (page unavailable)
  [6] Reddit – /r/memes'
aside_content: 'MemeStatusConfirmedType:Image MacroYear2019OriginCaptain America:
  Winter Soldier and Avengers: Endgame (Films)Tagscaptain america,marvel,mcu,dad jokes,hydra,jasper
  sitwell,avengers assemble,daily.dcmarvel.post,lazymeercat,trashcanpaul,ihazone,maximiliano
  hernándezAdditional ReferencesMeme Generator'
added_at: '2020-02-08T19:21:31-05:00'
