name: Captain America Elevator Fight Dad Joke
source: https://knowyourmeme.com/memes/captain-america-elevator-fight-dad-joke
keywords:
  -
text:
  - style: default
    color: khaki
    font: thick
    anchor_x: 0.0
    anchor_y: 0.23
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.1
    align: center
    start: 0.1
    stop: 1.0
  - style: default
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.57
    angle: 0.0
    scale_x: 0.4
    scale_y: 0.08
    align: center
    start: 0.4
    stop: 1.0
  - style: default
    color: khaki
    font: thick
    anchor_x: 0.5
    anchor_y: 0.56
    angle: 0.0
    scale_x: 0.5
    scale_y: 0.1
    align: center
    start: 0.7
    stop: 1.0
example:
  - Have you ever eaten a clock?
  - No, why?
  - It's time consuming.
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
