example:
- Have you ever eaten a clock?
- No, why?
- It's time consuming.
keywords:
- null
name: Captain America Elevator Fight Dad Joke
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Captain America Elevator Fight | Know Your Meme Word Up! You must\
  \ login or signup first! Already a memeber? Login Now! Don't have an account? Sign\
  \ up Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos\
  \ Submit \u2192 Images Trending Most Commented Most Favorited High Score Low Score\
  \ Most Viewed All Templates Upload an Image Articles News Explainers Collections\
  \ Interviews Meme Insider Magazine More Discord Newsletter Episodes Forums Meme\
  \ Store Login Abstract user icon Memes Categories Trending News Images Trending\
  \ Images Videos Trending Videos Editorials Meme Insider Magazine Newsletter Policies\
  \ and Guidelines Meme Store Old site Login Know Your Meme is the property of Literally\
  \ Media \xA92024 Literally Media. All Rights Reserved. This image Of Woman Confidently\
  \ Strolling Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years\
  \ Ago, This Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The\
  \ Anarchy Chess Memes Turns Two Years Old Today Phrase 'The Fridge Protects The\
  \ Snacks' A Growing Favorite Among Pickup Artist Influencers Jamie G, The Bosh British\
  \ Charva, Has Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also\
  \ Trending: Honey Extension Influencer Scam Renegade Raider Copypasta Assassination\
  \ of UnitedHealthcare CEO Captain America Elevator Fight Added 4 years ago / Updated\
  \ about a month ago Confirmed 68,207 Part of a series on Captain America. [View\
  \ Related Entries] View All 36 Images Navigation About \u2022 Origin \u2022 Spread\
  \ \u2022 Various Examples \u2022 Template \u2022 Search Interest \u2022 External\
  \ References \u2022 Recent Images \u2022 Recent Videos About Captain America Elevator\
  \ Fight is an image macro series featuring screenshots from the films Captain America:\
  \ The Winter Soldier and Avengers: Endgame in which Captain America fights a group\
  \ of Hydra soldiers in an elevator. In February 2020, a four-panel amalgamation\
  \ of scenes from both films as a vehicle for various dad jokes went viral. Origin\
  \ On April 4th, 2014, Marvel Studios released the film Captain America: The Winter\
  \ Soldier.[1] In the film, Captain America (played by Chris Evans) fights a group\
  \ of Hydra foot soldiers in an elevator (shown below, left). Roughly five years\
  \ later, on April 26th, 2019, Marvel Studios released the film Avengers: Endgame,\
  \ which features a recreation of the scene, in which Captain America whispers \"\
  Hail, Hydra\" in the ear of Jasper Sitwell (Maximiliano Hern\xE1ndez) to avoid the\
  \ fight (shown below, right).[2] [This video has been removed] The earliest available\
  \ meme featuring a mashup of the two films together was published on June 2nd, 2019.\
  \ The meme features Captain America whispering to Sitwell, Sitwell responding with\
  \ \"Avengers Assemble\" and, finally, a shot from Captain America: The Winter Soldier\
  \ in which soldiers attack Captain America. The post, uploaded by Instagram [3]\
  \ user @daily.dcmarvel.post, received more than 38,000 likes in less than one year\
  \ (shown below). Spread The following year, on February 7th, 2020, Redditor[4] LazyMeercat\
  \ shared a variation of the meme in which Captain America tells the dad joke \"\
  I saw my dog walk over sandpaper / he said rough rough.\" The post received more\
  \ than 5,400 points (98% upvoted) in less than three days (shown below, left). Over\
  \ the next few days, others continued to share variations of the format. On February\
  \ 8th, Instagram[5] user @trashcanpaul shared a variation with the joke \"have you\
  \ ever eaten a clock? / It's time consuming.\" The post received more than 49,000\
  \ likes in less than two days (shown below, center). The following day, Redditor[6]\
  \ ihazone shared a variation with the joke \"Your flat earth movie was just nominated\
  \ for an award / The Golden Globes.\" The post received more than 47,000 points\
  \ (93% upvoted) and 100 comments in less than 24 hours (shown below, right). Various\
  \ Examples Template Search Interest Not available. External References [1] Wikipedia\
  \ \u2013 Captain America: The Winter Soldier [2] Wikipedia \u2013 Avengers: Endgame\
  \ [3] Instagram \u2013 @daily.dcmarvel.post's Post [4] Reddit \u2013 /r/memetemplatesofficial\
  \ [5] Instagram \u2013 @trashcanpaul's Post (page unavailable) [6] Reddit \u2013\
  \ /r/memes captain america marvel mcu dad jokes hydra jasper sitwell avengers assemble\
  \ daily.dcmarvel.post lazymeercat trashcanpaul ihazone maximiliano hern\xE1ndez\
  \ Share Pin Related Entries 7 total Hail Hydra Mission Report: December 16th...\
  \ Captain Hydra / Captain Ameri... Captain America: Civil War 4 ... View All Related\
  \ Entries Recent Images 36 total View All Images Recent Videos 41 total View All\
  \ Videos Sign up for our Newsletter Load 1 Comment Comments 1 total 9 Captain America\
  \ Elevator Fight 68,207 41 36 1 Part of a series on Captain America. [View Related\
  \ Entries] Updated Nov 06, 2024 at 11:52AM EST by LiterallyAustin. Added Feb 08,\
  \ 2020 at 07:21PM EST by Matt. Like us on Facebook! Like 1.8M Share Save Tweet PROTIP:\
  \ Press 'i' to view the image gallery, 'v' to view the video gallery, or 'r' to\
  \ view a random entry. Meme Status Confirmed Type: Image Macro Year 2019 Origin\
  \ Captain America: Winter Soldier and Avengers: Endgame (Films) Tags captain america,\
  \ marvel, mcu, dad jokes, hydra, jasper sitwell, avengers assemble, daily.dcmarvel.post,\
  \ lazymeercat, trashcanpaul, ihazone, maximiliano hern\xE1ndez Additional References\
  \ Meme Generator About Captain America Elevator Fight is an image macro series featuring\
  \ screenshots from the films Captain America: The Winter Soldier and Avengers: Endgame\
  \ in which Captain America fights a group of Hydra soldiers in an elevator. In February\
  \ 2020, a four-panel amalgamation of scenes from both films as a vehicle for various\
  \ dad jokes went viral. Origin On April 4th, 2014, Marvel Studios released the film\
  \ Captain America: The Winter Soldier.[1] In the film, Captain America (played by\
  \ Chris Evans) fights a group of Hydra foot soldiers in an elevator (shown below,\
  \ left). Roughly five years later, on April 26th, 2019, Marvel Studios released\
  \ the film Avengers: Endgame, which features a recreation of the scene, in which\
  \ Captain America whispers \"Hail, Hydra\" in the ear of Jasper Sitwell (Maximiliano\
  \ Hern\xE1ndez) to avoid the fight (shown below, right).[2] [This video has been\
  \ removed] The earliest available meme featuring a mashup of the two films together\
  \ was published on June 2nd, 2019. The meme features Captain America whispering\
  \ to Sitwell, Sitwell responding with \"Avengers Assemble\" and, finally, a shot\
  \ from Captain America: The Winter Soldier in which soldiers attack Captain America.\
  \ The post, uploaded by Instagram [3] user @daily.dcmarvel.post, received more than\
  \ 38,000 likes in less than one year (shown below). Spread The following year, on\
  \ February 7th, 2020, Redditor[4] LazyMeercat shared a variation of the meme in\
  \ which Captain America tells the dad joke \"I saw my dog walk over sandpaper /\
  \ he said rough rough.\" The post received more than 5,400 points (98% upvoted)\
  \ in less than three days (shown below, left). Over the next few days, others continued\
  \ to share variations of the format. On February 8th, Instagram[5] user @trashcanpaul\
  \ shared a variation with the joke \"have you ever eaten a clock? / It's time consuming.\"\
  \ The post received more than 49,000 likes in less than two days (shown below, center).\
  \ The following day, Redditor[6] ihazone shared a variation with the joke \"Your\
  \ flat earth movie was just nominated for an award / The Golden Globes.\" The post\
  \ received more than 47,000 points (93% upvoted) and 100 comments in less than 24\
  \ hours (shown below, right). Various Examples Template Search Interest Not available.\
  \ External References [1] Wikipedia \u2013 Captain America: The Winter Soldier [2]\
  \ Wikipedia \u2013 Avengers: Endgame [3] Instagram \u2013 @daily.dcmarvel.post's\
  \ Post [4] Reddit \u2013 /r/memetemplatesofficial [5] Instagram \u2013 @trashcanpaul's\
  \ Post (page unavailable) [6] Reddit \u2013 /r/memes Related Entries 7 total Hail\
  \ Hydra Mission Report: December 16th, 1991 Captain Hydra / Captain America \"Hail\
  \ Hydra\" Edits Captain America: Civil War 4 Pane / Captain America vs Iron Man\
  \ Captain America \"So, You Got Detention\" Captain America Lifting Mj\xF6lnir Sabra\
  \ (Israeli Marvel Superhero) Recent Videos 41 total Captain America meme/elevator\
  \ Captain America Elevator Fight Uploaded by shevyrolet \"Hail Hydra\" Elevator\
  \ Scene |... Captain America Elevator Fight Uploaded by andcallmeshirley captain\
  \ america elevator figh... Captain America Elevator Fight Uploaded by shevyrolet\
  \ Captain America Funny Elevato... Captain America Elevator Fight Uploaded by Fight\
  \ Milk22 Captain america ELEVATOR SCEN... Captain America Elevator Fight Uploaded\
  \ by andcallmeshirley Hail Hydra Scene With Elevato... Captain America Elevator\
  \ Fight Uploaded by andcallmeshirley captain america elevator - me... Captain America\
  \ Elevator Fight Uploaded by Y F Part 1 Captain America meme C... Captain America\
  \ Elevator Fight Uploaded by shevyrolet + Add a Video View All Videos Recent Images\
  \ 36 total Captain America Elevator Fight Uploaded by Lugamo Captain America Elevator\
  \ Fight Uploaded by Lugamo Captain America Elevator Fight Uploaded by shevyrolet\
  \ Captain America Elevator Fight Uploaded by nightqueen Captain America Elevator\
  \ Fight Uploaded by Y F Captain America Elevator Fight Uploaded by Lugamo Captain\
  \ America Elevator Fight Uploaded by asimthechemist Captain America Elevator Fight\
  \ Uploaded by shevyrolet Captain America Elevator Fight Uploaded by Cold Hard Crash\
  \ Captain America Elevator Fight Uploaded by Cold Hard Crash Captain America Elevator\
  \ Fight Uploaded by Breezem'0ut Captain America Elevator Fight Uploaded by Breezem'0ut\
  \ + Add an Image View All Images Sign up for our Newsletter + Add a Comment Comments\
  \ (1) Display Comments Add a Comment Top Entries This Month Meme Saika Kawakita\
  \ Smile GIF Event Assassination of UnitedHealthcare CEO Person Luigi Mangione UHC\
  \ CEO Shooter Subculture The Ki Sisters Culture Pornography Site Whisper View More\
  \ Suggest a Change Edit History Entry Editors (5) Matt Secretary of Memes andcallmeshirley\
  \ Digital Archaeologist & Treasurer & Collection Butler Y F Digital Archaeologist\
  \ & Treasurer & Media Maid shevyrolet Digital Archaeologist & Treasurer & Media\
  \ Bus Boy Philipp Memesplainer \u25BC + Request Editorship View All Editors Today's\
  \ Top Image Galleries Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen\
  \ Green) Team Fortress 2 The Amazing Digital Circus About Our Story Site Rules Policies\
  \ and Guidelines Credits Contact Meme DB Memes Episodes News Staff Contact Extras!\
  \ Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/captain-america-elevator-fight-dad-joke
template_id: captain-america
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.23
  angle: 0.0
  color: khaki
  font: thick
  scale_x: 1.0
  scale_y: 0.1
  start: 0.1
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.0
  anchor_y: 0.57
  angle: 0.0
  color: white
  font: thick
  scale_x: 0.4
  scale_y: 0.08
  start: 0.4
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.5
  anchor_y: 0.56
  angle: 0.0
  color: khaki
  font: thick
  scale_x: 0.5
  scale_y: 0.1
  start: 0.7
  stop: 1.0
  style: default
text_zones: 3
