name: Khaby Lame Shrug
source: https://knowyourmeme.com/photos/2132291-khaby-lame-shrug-its-that-simple
keywords:
  - It's That Sample
text:
  - style: default
    color: black
    font: thin
    anchor_x: 0.02
    anchor_y: 0.02
    angle: 0.0
    scale_x: 0.45
    scale_y: 0.47
    align: center
    start: 0.0
    stop: 1.0
  - style: default
    color: black
    font: thin
    anchor_x: 0.02
    anchor_y: 0.51
    angle: 0.0
    scale_x: 0.45
    scale_y: 0.47
    align: center
    start: 0.0
    stop: 1.0
example:
  - Bad mood?
  - Laugh at memes
overlay:
  - center_x: 0.25
    center_y: 0.255
    angle: 0.0
    scale: 0.48
  - center_x: 0.25
    center_y: 0.745
    angle: 0.0
    scale: 0.48
