name: Will Smith Slapping Chris Rock
source: https://knowyourmeme.com/memes/will-smith-slapping-chris-rock
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.18
  anchor_y: 0.13
  angle: 44.0
  scale_x: 0.35
  scale_y: 0.3
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.5
  anchor_y: 0.7
  angle: 0.0
  scale_x: 0.35
  scale_y: 0.3
  align: center
  start: 0.0
  stop: 1.0
example:
- Me Trying to Enjoy the Weekend
- Monday
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Will Smith Slapping Chris Rock refers to a moment from the
  2022 Oscars (held on March 27th) in which actor and musician Will Smith slapped
  comedian and actor Chris Rock over a joke he made about his wife Jada Pinkett Smith.
  The slap was televised and quickly became an object-labeling and an exploitable
  meme template. The still image of Smith hitting Rock in the face also became a source
  for redraws where the two were replaced with pop culture figures. Origin During
  the 94th Academy Awards ceremony on March 27th, 2022, comedian Chris Rock was presenting
  the award for best documentary feature, which eventually went to Summer of Soul.
  While on stage, Rock made a joke about Jada Pinkett Smith, Will Smith''s wife (also
  known from the Entanglement meme), and how because of her shaved haircut, she could
  have starred in G.I.Jane. This prompted a mixed reaction from the crowd with Will
  initially appearing to laugh but Jada visibly upset next to him (shown below). Moments
  later, Will stands and walks up the stage to Rock and slaps him across the head,
  which drew confusion from a crowd unsure if it was real or part of a bit. As Will
  went back to his seat, continuing to shout at Rock, he appears genuinely angry and
  yells, "Keep my wife''s name out your fucking mouth!" Though it was censored for
  the American telecast, an uncensored Japanese version was captured and tweeted out
  by Twitter user @bubbaprog[1] that night (shown below). The clip accumulated over
  38.5 million views, 126,500 retweets and 484,500 likes in eight hours. VIA JAPANESE
  TELEVISION: The uncensored exchange between Will Smith and Chris Rock pic.twitter.com/j0Z184ZyXa
  — Timothy Burke (@bubbaprog) March 28, 2022 - Jada, I love you. G.I. Jane 2, can''t
  wait to see it! Alright? That was a nice one. I''m out here… Uh-oh! [Will Smith
  comes on stage and slaps Chris Rock] – Oh wow! Wow! Will Smith just smacked the
  shit out of me! - Keep my wife''s name out your fucking mouth! - Wow, dude! It was
  a G.I. Jane joke! - Keep my wife''s name out your fucking mouth!! - I''m going to,
  okay? That was, uh, the greatest night in the history of television. Spread The
  image of the slap, which was captured from various angles as a highly televised
  event, quickly had an explosion in memes the night of the 2022 Oscars. For example,
  Twitter user evanssugarbaby[2] rapidly made and posted a meme on March 27th in which
  the logo of the Chris Rock-led TV show Everybody Hates Chris was superimposed on
  the image of him getting slapped (shown below, left). Reddit user Robecuba posted
  a meme[3] onto the /r/dankmemes subreddit showing Chris Rock with the Minecraft
  HUD overlaid and text showing him being in danger (shown below, right). Immediately
  following the event, an anonymous 4chan[4] user posted an exploitable template of
  Will Smith punching Chris Rock to the /tv/ board. In the following hours, the thread
  gained over 235 replies, with multiple users sharing memes and redraws based on
  the template (examples shown below). The exploitable is similar to the 2020 redraw
  trend Lev Punch Edits. Developments Chris Rock Does Not Press Charges With LAPD
  Although the slap was technically assault, Chris Rock did not press charges against
  Will Smith following the slap. CNN[5] received a statement from the Los Angeles
  Police Department following the Oscar''s where they stated, "LAPD investigative
  entities are aware of an incident between two individuals during the Academy Awards
  program. The incident involved one individual slapping another. The individual involved
  has declined to file a police report. If the involved party desires a police report
  at a later date, LAPD will be available to complete an investigative report." Memes
  and reactions ensued on Twitter amongst other platforms amid the development. Some
  online believed that Rock should press charges while others thought it was no big
  deal, outraged by the outrage levied against Smith. Will Smith''s Apology Letter
  On March 28th, Will Smith posted an apology letter to Facebook,[6] directed towards
  Chris Rock and his fellow Academy members. In less than 24 hours, the letter received
  roughly 1.9 million reactions (shown below). SlapChris.com On March 28th, the website
  https://www.slapchris.com/ became active, and featured an emoji palm that you can
  use your mouse to click and drag over to an animated face of Chris Rock. Depending
  on the speed that you do it, a measurement in KM/H or MPH will appear up top, with
  slaps over a certain velocity playing the instrumental hook to Gettin Jiggy With
  It by Will Smith. For April Fools Day 2022 the website changed it so you could slap
  Will Smith instead, causing many more to take notice of the site. Will Smith Apology
  On July 29th, 2022, Will Smith uploaded an apology / QnA video, four months after
  the fact, to his main YouTube channel[7], titling it ''It''s Been A Minute…'' which
  went on to receive over 3 million views in two days (shown below). As usual whenever
  there is some update to a situation like this, the YouTuber and Moist E-Sports creator
  Cr1tikal uploaded his own video about the matter, where he reacts to the apology
  and gives his unique brand of insight and weighs in. The Cr1tikal video[8] about
  Will Smith''s video, however, obtained over 3.5 million views, being a rare example
  of a YouTube Ratio (shown below). Related Memes Sad Will Smith / Entanglement Sad
  Will Smith / Entanglement is a reaction image macro series based on a screenshot
  of actor Will Smith during a discussion about his wife Jada Pinkett Smith''s relationship
  with singer August Alsina on her Facebook talk show "Red Table Talk". Pinkett Smith
  refers to her relationship with Alsina as her "entanglement," which became the subject
  of numerous jokes on social media. Various Examples Templates Search Interest External
  References [1] Twitter – @bubbaprog [2] Twitter – EvansSugarBaby [3] Reddit – dankmemes
  [4] 4Chan – /tv/ Thread #165698633 [5] CNN – Chris Rock LAPD [6] Facebook – Will
  Smith [7] YouTube – Will Smith Apology [8] YouTube – Cr1tikal'
aside_content: MemeStatusConfirmedType:Exploitable,Pop Culture Reference,Viral VideoYear2022OriginOscarsTagschris
  rock,will smith,oscars,jada pinkett smith,slapping,punching,exploitable,oscars 2022,will
  smith slapping chris rock memes,will smith slap,chris rock slap,will smith wife,redraws,exploitables,viral
  videos,oscars slap,academy awards sla
added_at: '2022-03-27T23:50:36-04:00'
