name: I Should Buy a Boat Cat
source: http://knowyourmeme.com/memes/i-should-buy-a-boat-cat
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- ''
- i should buy a boat
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About I Should Buy a Boat Cat, also known as "Sophisticated Cat"
  and "Fancy Cat," is an image macro series featuring a photograph of a cat wearing
  a suit while seated at a table reading a newspaper. The captions typically describe
  various epiphanies and desires, often using the snowclone template "I should buy
  a X." Origin The singer-songwriter Bjork released a music video directed by Spike
  Jonze for her song "Triumph of the Heart"[2] in January of 2005, in which she leaves
  her anthropomorphic cat husband for a night out in the city. In the video, the cat
  is is seen seated at a table drinking coffee and reading a newspaper while dressed
  in a blue shirt (shown at 3:56 below). On February 2nd, 2012, Redditor DrTango submitted
  a post titled “I’ll just leave this here" to the /r/funny[1] subreddit, featuring
  a screen capture of the cat with the caption “I should buy a boat” (shown below).
  Prior to being archived, the post received over 12,350 up votes and 165 comments.
  Spread On February 3rd, the Internet humor site 9gag[7] reposted the DrTango's image
  macro, receiving over 40,400 up votes and 4,200 Facebook shares within the next
  nine months. On February 9th, the image was reblogged on the Internet humor site
  College Humor.[3] On August 31st, the image was mentioned in an episode of the video
  game YouTube show Game Grumps. On September 10th, Redditor RoTTaax submitted a post
  titled "How I feel when I post a long comment that gets 3 upvotes" to the /r/AdviceAnimals[4]
  subreddit, featuring an image macro with the caption "I should write a book" (shown
  below). Within one month, the post received over 9,900 up votes and 45 comments.
  On November 6th, Redditor bathroomstalin submitted an image macro titled "We've
  all thought about it" to the /r/AdviceAnimals[5] subreddit, which featured the cat
  image with the caption "I should buy a "horse mask." The same day, Redditor TwoSwords
  submitted a post titled "Well, he went out and did it,"[6] which featured a photoshopped
  version of the image with a horse head mask superimposed over the cat's head (shown
  below). Within 24 hours, each post reached the front page receiving thousands of
  up votes. Notable Examples As of November 6th, 2012, a Quickmeme page for "Fancy
  Cat"[9] has received over 75 submissions and a page for "Sophisticated Cat"[10]
  as accumulated over 630 submissions. On Tumblr,[8] other photographs of inquisitive-looking
  subjects have been captioned with the phrase "I should buy a boat." Boat Advice
  On January 24th, 2013, Redditor al19 submitted a picture of a cat and a duck strolling
  alongside each other to the /r/aww subreddit.[11] While the image had been previously
  submitted many times since as early as in January 2012, Redditor al19's post was
  met by several references to Sophisticated Cat consulting Actual Advice Mallard
  for financial advices. That same day, Redditor ZeeHanzenShwanz submitted an image
  macro illustrating a dialogue between the cat and the duck about "catching the red
  dot" to the /r/AdviceAnimals subreddit (shown below, left).[12] As with other emerging
  advice animal series, a Quickmeme entry[13] for "Boat Advice" was launched shortly
  thereafter. Search Interest External References [1] Reddit – I'll just leave this
  here [2] Wikipedia – Triumph of the Heart [3] College Humor via Wayback Machine
  – Wealthy Cat Decides to Buy a Boat [4] Reddit – How I feel when I post a long comment
  that gets 3 upvotes [5] Reddit – We've all thought about it [6] Reddit – Well, he
  went out and did it [7] 9gag – I should buy a boat [8] Tumblr – I should buy a boat
  [9] Quickmeme – Fancy Cat [10] Quickmeme – Sophisticated Cat [11] Reddit – Just
  two friends out for a stroll [12] Reddit – Well someone had to break it to him eventually
  [13] Quickmeme (via Wayback Machine) – Boat Advice
aside_content: MemeStatusConfirmedYear2012OriginRedditTagsi should but a boat,animals
  of 2012,sea travel,zeehanzenshwanz,spike jonze,bjork,drtango,bathroomstalin,al19,sophisticated
  catAdditional ReferencesMeme Generator
added_at: '2012-11-06T19:12:00-05:00'
