name: Why Not Both?
source: http://knowyourmeme.com/memes/why-not-both-why-dont-we-have-both
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.2
  stop: 1.0
example:
- hard or soft tacos
- why not both?
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About "Why Don''t We Have Both?", also known as Why Not Both?, is
  a reaction image and catchphrase that is used in response to various problems that
  involve choosing between two options or solutions. Origin The expression "why don''t
  we have both?" was originally quoted by a child model in a TV commercial for the
  Old El Paso at-home taco kit that contains both hard-shell and soft tortillas. In
  the commercial, a group of Spanish speakers are seen arguing over the quality of
  hard and soft tacos, to which the girl proposes “Why not both?” with a shrug and
  puts an end to the debate. Though it is unclear when the commercial first aired,
  it was discussed online as early as September 2009.[1] Spread On June 23rd, 2010,
  a Facebook fan page[2] for the girl in the commercial was launched, though her off-screen
  identity remains unknown. On June 30th, 2011, one of the first image macros based
  on a still shot from the commercial was posted to FunnyJunk,[5] paired with a screen
  capture from an episode clip of Yo Gabba Gabba (shown below, left). On July 21st,
  a second image macro was shared on the Cheezburger site Comixed[3], attached to
  a question surveying the viewers if they would rather kill Justin Bieber or Rebecca
  Black (shown below, right). On the following day, the Black / Bieber comic was reposted
  to FunnyJunk.[4] On August 12th, 2011, the Yo Gabba Gabba multi-pane image was reposted
  to the /r/Drugs subreddit[6], where it gained 35 upvotes and 31 points overall.
  Sometime in October that year, "Why Not Both" reaction images were shared for the
  first time on Tumblr.[7] In January 2012, a "Why Not Both" Quickmeme[8] page was
  created, accumulating 3,300 submissions as of May 2013. Throughout that year, "Why
  Not Both" images were shared on numerous subreddits including /r/Trees[9] and /r/Funny[10],
  as well as several humor sites including The Meta Picture[11], Meme Center[12],
  and We Know Memes.[13] In December, a Meme Generator[14] page titled “Why Not Both
  Girl” was created, accruing more than 400 submissions as of May 2013. Various Examples
  Templates Search Interest External References [1] Commercials I Hate – Old El Paso
  [2] Facebook – The "Why not have both?" girl from Old El Paso Taco ads :) [3] Comixed
  – Compromise Actually Works [4] FunnyJunk – Why Cant We Have Both [5] FunnyJunk
  – Why Don''t We Have Both? [6] Reddit – /r/Drugs: Why Can''t We Have Both? [7] Tumblr
  – lethargiclogic: Why Not Both? [8] Quickmeme – Why not both [9] Reddit – /r/Trees:
  Tacos and Trees, why not both!? [10] Reddit – /r/Funny: why not both? [11] The Meta
  Picture – Why not both? [12] Meme Center – Why Not Both?? [13] We Know Memes (via
  Wayback Machine) – Why Not Both Einstein [14] Meme Generator – Why Not Both Girl'
aside_content: MemeStatusConfirmedType:Advertisement,Catchphrase,ReactionYear2011OriginOld
  El Paso commercialRegionUnited StatesTagswhy,tacos,both,snowclone,reaction image,why
  don't we have both meme,why not both meme,catchphrasesAdditional ReferencesMeme
  Generator
added_at: '2011-08-24T20:10:05-04:00'
