example:
- This is the worst day of my life.
- This is the worst day of your life so far.
keywords:
- null
name: The Worst Day Of Your Life So Far
overlay:
- angle: 0.0
  center_x: 0.485
  center_y: 0.1
  scale: 0.2
scraped_content: "The Worst Day Of Your Life So Far | Know Your Meme Hi! You must\
  \ login or signup first! Already a memeber? Login Now! Don't have an account? Sign\
  \ up Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos\
  \ Submit \u2192 Images Trending Most Commented Most Favorited High Score Low Score\
  \ Most Viewed All Templates Upload an Image Articles News Explainers Collections\
  \ Interviews Meme Insider Magazine More Discord Newsletter Episodes Forums Meme\
  \ Store Login Abstract user icon Memes Categories Trending News Images Trending\
  \ Images Videos Trending Videos Editorials Meme Insider Magazine Newsletter Policies\
  \ and Guidelines Meme Store Old site Login Know Your Meme is the property of Literally\
  \ Media \xA92024 Literally Media. All Rights Reserved. This image Of Woman Confidently\
  \ Strolling Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years\
  \ Ago, This Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The\
  \ Anarchy Chess Memes Turns Two Years Old Today Phrase 'The Fridge Protects The\
  \ Snacks' A Growing Favorite Among Pickup Artist Influencers Jamie G, The Bosh British\
  \ Charva, Has Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also\
  \ Trending: Honey Extension Influencer Scam Renegade Raider Copypasta Assassination\
  \ of UnitedHealthcare CEO The Worst Day Of Your Life So Far Added 3 years ago /\
  \ Updated 3 years ago Confirmed 52,646 Part of a series on The Simpsons. [View Related\
  \ Entries] View All 22 Images Navigation About \u2022 Origin \u2022 Spread \u2022\
  \ Various Examples \u2022 Template \u2022 Search Interest \u2022 External References\
  \ \u2022 Recent Images About The Worst Day Of Your Life So Far is an exploitable\
  \ 2-panel still from The Simpsons Movie. It is used to express in a humorous way\
  \ the pessimistic opinion that an already bad situation can, and likely will, get\
  \ worse. Origin The scene comes from The Simpsons Movie, released July 27th, 2007,[1]\
  \ where Bart Simpson ends up humiliated in public and Homer tries to console him\
  \ (shown below). The first known example of the scene getting posted as an image\
  \ macro appeared in a picture dump posted to Funcage[2] on January 14th, 2012 (shown\
  \ below). Spread On October 6th, 2017, Imgur[3] user Impeachhimalrdy posted one\
  \ of the earliest known parodies of the image, changing the text to be about mass\
  \ shootings. The post gained over 6,700 points (shown below, left). On June 14th,\
  \ 2018, Redditor memetimeradiohour posted an American war-themed parody to /r/Historymemes,[4]\
  \ gaining over 1,100 points (shown below, right). Over time, the template began\
  \ to see popular use on topics such as history, the Trump presidency, and the COVID-19\
  \ pandemic. The meme became increasingly popular in early 2021. One of the most\
  \ popular versions of the meme was posted by user keenfeed to /r/wallstreetbets[5]\
  \ regarding the Gamestop Short Squeeze, gaining over 185,000 points (shown below).\
  \ Various Examples Template Search Interest External References [1] IMDb \u2013\
  \ The Simpsons Movie [2] Funcage \u2013 Pic Dump [3] Imgur \u2013 Mass Shooting\
  \ [4] Reddit \u2013 /r/HistoryMemes [5] Reddit \u2013 /r/WallStreetBets the simpsons\
  \ the simpsons movie homer simpson bart simpson worst day of my life Share Pin Related\
  \ Entries 97 total Steamed Hams I, For One, Welcome Our New I... Sneed's Feed and\
  \ Seed Old Man Yells at Cloud View All Related Entries Recent Images 22 total View\
  \ All Images Recent Videos 0 total There are no recent videos. Sign up for our Newsletter\
  \ Load 3 Comments Comments 3 total 8 The Worst Day Of Your Life So Far 52,646 0\
  \ 22 3 Part of a series on The Simpsons. [View Related Entries] Updated Mar 04,\
  \ 2021 at 05:23AM EST by memetimeradiohour. Added Jan 31, 2021 at 11:47AM EST by\
  \ memetimeradiohour. Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press\
  \ 'i' to view the image gallery, 'v' to view the video gallery, or 'r' to view a\
  \ random entry. Meme Status Confirmed Type: Catchphrase, Exploitable Year 2018 Origin\
  \ The Simpsons Movie Tags the simpsons, the simpsons movie, homer simpson, bart\
  \ simpson, worst day of my life Additional References Meme Generator Reddit Wikipedia\
  \ About The Worst Day Of Your Life So Far is an exploitable 2-panel still from The\
  \ Simpsons Movie. It is used to express in a humorous way the pessimistic opinion\
  \ that an already bad situation can, and likely will, get worse. Origin The scene\
  \ comes from The Simpsons Movie, released July 27th, 2007,[1] where Bart Simpson\
  \ ends up humiliated in public and Homer tries to console him (shown below). The\
  \ first known example of the scene getting posted as an image macro appeared in\
  \ a picture dump posted to Funcage[2] on January 14th, 2012 (shown below). Spread\
  \ On October 6th, 2017, Imgur[3] user Impeachhimalrdy posted one of the earliest\
  \ known parodies of the image, changing the text to be about mass shootings. The\
  \ post gained over 6,700 points (shown below, left). On June 14th, 2018, Redditor\
  \ memetimeradiohour posted an American war-themed parody to /r/Historymemes,[4]\
  \ gaining over 1,100 points (shown below, right). Over time, the template began\
  \ to see popular use on topics such as history, the Trump presidency, and the COVID-19\
  \ pandemic. The meme became increasingly popular in early 2021. One of the most\
  \ popular versions of the meme was posted by user keenfeed to /r/wallstreetbets[5]\
  \ regarding the Gamestop Short Squeeze, gaining over 185,000 points (shown below).\
  \ Various Examples Template Search Interest External References [1] IMDb \u2013\
  \ The Simpsons Movie [2] Funcage \u2013 Pic Dump [3] Imgur \u2013 Mass Shooting\
  \ [4] Reddit \u2013 /r/HistoryMemes [5] Reddit \u2013 /r/WallStreetBets Related\
  \ Entries 97 total Steamed Hams I, For One, Welcome Our New Insect Overlords Sneed's\
  \ Feed and Seed Old Man Yells at Cloud I Must Go Do It For Her \"Milhouse Is Not\
  \ A Meme\" Marge Krumping Principal Skinner's \"Pathetic\" Homer Simpson Backs Into\
  \ Bushes That's The Joke Bart, Get Out! I'm Piss! View All Related Entries Recent\
  \ Videos There are no videos currently available. + Add a Video Recent Images 22\
  \ total The Worst Day Of Your Life So... Uploaded by Triplem The Worst Day Of Your\
  \ Life So... Uploaded by Bomber-Boi The Worst Day Of Your Life So... Uploaded by\
  \ liveangel The Worst Day Of Your Life So... Uploaded by Adam The Worst Day Of Your\
  \ Life So... Uploaded by Triplem The Worst Day Of Your Life So... Uploaded by Rebecca\
  \ Rhodes The Worst Day Of Your Life So... Uploaded by memetimeradiohour The Worst\
  \ Day Of Your Life So... Uploaded by memetimeradiohour The Worst Day Of Your Life\
  \ So... Uploaded by memetimeradiohour The Worst Day Of Your Life So... Uploaded\
  \ by memetimeradiohour The Worst Day Of Your Life So... Uploaded by memetimeradiohour\
  \ The Worst Day Of Your Life So... Uploaded by Adam + Add an Image View All Images\
  \ Sign up for our Newsletter + Add a Comment Comments (3) Display Comments Add a\
  \ Comment Top Entries This Month Meme Saika Kawakita Smile GIF Event Assassination\
  \ of UnitedHealthcare CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki\
  \ Sisters Culture Pornography Site Whisper View More Suggest a Change Edit History\
  \ Entry Editors (4) memetimeradiohour Investigator & Cataloger andcallmeshirley\
  \ Digital Archaeologist & Treasurer & Collection Butler Triplem Entry Moderator\
  \ Adam Know Your Meme Universal Champion + Request Editorship View All Editors Today's\
  \ Top Image Galleries Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen\
  \ Green) Team Fortress 2 The Amazing Digital Circus About Our Story Site Rules Policies\
  \ and Guidelines Credits Contact Meme DB Memes Episodes News Staff Contact Extras!\
  \ Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/the-worst-day-of-your-life-so-far
template_id: worst
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.4
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.1
  start: 0.0
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.0
  anchor_y: 0.9
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.1
  start: 0.0
  stop: 1.0
  style: default
text_zones: 2
