name: The Worst Day Of Your Life So Far
source: https://knowyourmeme.com/memes/the-worst-day-of-your-life-so-far
keywords:
- null
text:
- style: default
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.4
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.1
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.9
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.1
  align: center
  start: 0.0
  stop: 1.0
example:
- This is the worst day of my life.
- This is the worst day of your life so far.
overlay:
- center_x: 0.485
  center_y: 0.1
  angle: 0.0
  scale: 0.2
scraped_content: About The Worst Day Of Your Life So Far is an exploitable 2-panel
  still from The Simpsons Movie. It is used to express in a humorous way the pessimistic
  opinion that an already bad situation can, and likely will, get worse. Origin The
  scene comes from The Simpsons Movie, released July 27th, 2007,[1] where Bart Simpson
  ends up humiliated in public and Homer tries to console him (shown below). The first
  known example of the scene getting posted as an image macro appeared in a picture
  dump posted to Funcage[2] on January 14th, 2012 (shown below). Spread On October
  6th, 2017, Imgur[3] user Impeachhimalrdy posted one of the earliest known parodies
  of the image, changing the text to be about mass shootings. The post gained over
  6,700 points (shown below, left). On June 14th, 2018, Redditor memetimeradiohour
  posted an American war-themed parody to /r/Historymemes,[4] gaining over 1,100 points
  (shown below, right). Over time, the template began to see popular use on topics
  such as history, the Trump presidency, and the COVID-19 pandemic. The meme became
  increasingly popular in early 2021. One of the most popular versions of the meme
  was posted by user keenfeed to /r/wallstreetbets[5] regarding the Gamestop Short
  Squeeze, gaining over 185,000 points (shown below). Various Examples Template Search
  Interest External References [1] IMDb – The Simpsons Movie [2] Funcage – Pic Dump
  [3] Imgur – Mass Shooting [4] Reddit – /r/HistoryMemes [5] Reddit – /r/WallStreetBets
aside_content: MemeStatusConfirmedType:Catchphrase,ExploitableYear2018OriginThe Simpsons
  MovieTagsthe simpsons,the simpsons movie,homer simpson,bart simpson,worst day of
  my lifeAdditional ReferencesMeme GeneratorRedditWikipedia
added_at: '2021-01-31T11:47:31-05:00'
