example:
- we'll just invest that money
- '...aaaand it''s gone'
keywords:
- South Park
name: And It's Gone
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "And It's Gone | Know Your Meme Greetings! You must login or signup\
  \ first! Already a memeber? Login Now! Don't have an account? Sign up Now! Meme\
  \ Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO And It's Gone Added 12 years ago / Updated 8 days ago Confirmed 305,498 Part\
  \ of a series on South Park. [View Related Entries] View All 70 Images Navigation\
  \ About \u2022 Origin \u2022 Spread \u2022 Notable Examples \u2022 Search Interest\
  \ \u2022 External References \u2022 Recent Images About \"And It's Gone!\" (also\
  \ known as \"Aaaand It's Gone\") is an advice animal image macro series featuring\
  \ a picture of a bank teller from the animated television show South Park. The image\
  \ macros are often accompanied by captions describing lost opportunities or items,\
  \ ending in the titular phrase \"And it's gone\". Origin The original image is captured\
  \ from a scene in the South Park episode \"Margaritaville\"[1], which first aired\
  \ on March 25th, 2009. The phrase is used by a teller at South Park Bank Savings\
  \ and Loans while informing customers that their money has been lost. On April 22nd,\
  \ 2012, the first \"And it's gone!\" image macro was uploaded to Quickmeme[2] with\
  \ the caption \u201CYou post your new meme idea. You think it's going to do great\
  \ / Aaaand it's gone\" (shown below). Spread On May 14th, 2012, an image macro featuring\
  \ the caption \"So this one time, me and Jason\u2026 / Anddd it's gone\" (shown\
  \ below, left) was posted to the /r/trees[3] subreddit by user Taco4all, receiving\
  \ over 1,100 upvotes within two months. On May 25th, Redditor Dopecheez posted an\
  \ image macro with the caption \"I hope my post gets a lot of upvot- / Anddd it's\
  \ gone\" (shown below, right) to the /r/AdviceAnimals[4] subreddit, which received\
  \ over 1,000 up votes within one month. As of July 14th, 2012, the Quickmeme[2]\
  \ page for \"Aaaand It's Gone\" has accumulated over 2,500 submissions, the Quickmeme[6]\
  \ page for \"South Park Banker\" has accumulated 457 submissions, the Meme Generator[7]\
  \ page for \"Aand It's Gone\" the meme has received over 1000 items and a Facebook[8]\
  \ page titled \"Aaaand It's Gone\" has received over 990 likes. Notable Examples\
  \ Search Interest External References [1] South Park Wiki \u2013 Margaritaville\
  \ [2] Quickmeme \u2013 aaaand its gone [3] Reddit \u2013 Trying to tell a story\
  \ at 6 [4] Reddit \u2013 Every time I post something to r/new\u2026 [5] Quickmeme\
  \ \u2013 aaaand its gone [6] Quickmeme \u2013 South Park Banker [7] Meme Generator\
  \ \u2013 Aand Its Gone [8] Facebook \u2013 Aaaand It's Gone image macro animation\
  \ south park advice animals aaand its gone entry of july 2012 dopecheez Share Pin\
  \ Related Entries 22 total Tree Fiddy ???? PROFIT!!!! Super Cool Ski Instructor\
  \ They Took Our Jobs! View All Related Entries Recent Images 70 total View All Images\
  \ Recent Videos 0 total There are no recent videos. Sign up for our Newsletter Load\
  \ 23 Comments Comments 23 total 31 And It's Gone 305,498 0 70 23 Part of a series\
  \ on South Park. [View Related Entries] Updated Dec 15, 2024 at 03:47PM EST by LiterallyAustin.\
  \ Added Jul 14, 2012 at 10:15AM EDT by Blinkerbot. Like us on Facebook! Like 1.8M\
  \ Share Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the\
  \ video gallery, or 'r' to view a random entry. Meme Status Confirmed Year 2009\
  \ Origin South Park Tags image macro, animation, south park, advice animals, aaand\
  \ its gone, entry of july 2012, dopecheez Additional References Meme Generator About\
  \ \"And It's Gone!\" (also known as \"Aaaand It's Gone\") is an advice animal image\
  \ macro series featuring a picture of a bank teller from the animated television\
  \ show South Park. The image macros are often accompanied by captions describing\
  \ lost opportunities or items, ending in the titular phrase \"And it's gone\". Origin\
  \ The original image is captured from a scene in the South Park episode \"Margaritaville\"\
  [1], which first aired on March 25th, 2009. The phrase is used by a teller at South\
  \ Park Bank Savings and Loans while informing customers that their money has been\
  \ lost. On April 22nd, 2012, the first \"And it's gone!\" image macro was uploaded\
  \ to Quickmeme[2] with the caption \u201CYou post your new meme idea. You think\
  \ it's going to do great / Aaaand it's gone\" (shown below). Spread On May 14th,\
  \ 2012, an image macro featuring the caption \"So this one time, me and Jason\u2026\
  \ / Anddd it's gone\" (shown below, left) was posted to the /r/trees[3] subreddit\
  \ by user Taco4all, receiving over 1,100 upvotes within two months. On May 25th,\
  \ Redditor Dopecheez posted an image macro with the caption \"I hope my post gets\
  \ a lot of upvot- / Anddd it's gone\" (shown below, right) to the /r/AdviceAnimals[4]\
  \ subreddit, which received over 1,000 up votes within one month. As of July 14th,\
  \ 2012, the Quickmeme[2] page for \"Aaaand It's Gone\" has accumulated over 2,500\
  \ submissions, the Quickmeme[6] page for \"South Park Banker\" has accumulated 457\
  \ submissions, the Meme Generator[7] page for \"Aand It's Gone\" the meme has received\
  \ over 1000 items and a Facebook[8] page titled \"Aaaand It's Gone\" has received\
  \ over 990 likes. Notable Examples Search Interest External References [1] South\
  \ Park Wiki \u2013 Margaritaville [2] Quickmeme \u2013 aaaand its gone [3] Reddit\
  \ \u2013 Trying to tell a story at 6 [4] Reddit \u2013 Every time I post something\
  \ to r/new\u2026 [5] Quickmeme \u2013 aaaand its gone [6] Quickmeme \u2013 South\
  \ Park Banker [7] Meme Generator \u2013 Aand Its Gone [8] Facebook \u2013 Aaaand\
  \ It's Gone Related Entries 22 total Tree Fiddy ???? PROFIT!!!! Super Cool Ski Instructor\
  \ They Took Our Jobs! Captain Hindsight Member Berries Oh, I'm Sorry, I Thought\
  \ This Was America Everybody Draw Mohammed Day PC Bro I Didn't Hear No Bell South\
  \ Park Transgender Athletes Episode Controversy My Name Is Craig Tucker Copypasta\
  \ View All Related Entries Recent Videos There are no videos currently available.\
  \ + Add a Video Recent Images 70 total And It's Gone Uploaded by Rebecca Rhodes\
  \ And It's Gone Uploaded by Rebecca Rhodes And It's Gone Uploaded by Y F And It's\
  \ Gone Uploaded by vyhox And It's Gone Uploaded by Autumn Able And It's Gone Uploaded\
  \ by DuckDuckGoose And It's Gone Uploaded by Dr. Beetus And It's Gone Uploaded by\
  \ Boeing707 And It's Gone Uploaded by shortleif And It's Gone Uploaded by Crimeariver\
  \ And It's Gone Uploaded by Flynox And It's Gone Uploaded by Flynox + Add an Image\
  \ View All Images Sign up for our Newsletter Top Comments Delete Sensitive Pumpkinbot\
  \ Jul 16, 2012 at 09:19PM EDT This meme's getting used pretty often. Aaaaand it's\
  \ gone. +15 Reply Delete Sensitive Explosive Lasers AKA Solaire AKA Sexiest Jul\
  \ 14, 2012 at 01:12PM EDT Ironic that the first example of this advice animal started\
  \ as something that made fun of first examples of advice animals. Not sure if hax,\
  \ or good OP. Either way, I'll withhold my judgment on it until some time passes\
  \ and we see if it can take off, but the articles is pretty good, at least. +13\
  \ Reply + Add a Comment Comments (23) Display Comments Add a Comment Top Entries\
  \ This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (6) Blinkerbot\
  \ Jr. Researcher & Scrapbooker Don Administrator & Meme Daddy Brad Digital Archaeologist\
  \ & Treasurer & Pundit & Gallery Housekeeper Twenty-One Anime Anthropologist & Protip\
  \ Advisor & LGBT Community Expert Y F Digital Archaeologist & Treasurer & Media\
  \ Maid Zach Memenator \u25BC + Request Editorship View All Editors Today's Top Image\
  \ Galleries Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team\
  \ Fortress 2 The Amazing Digital Circus About Our Story Site Rules Policies and\
  \ Guidelines Credits Contact Meme DB Memes Episodes News Staff Contact Extras! Style\
  \ Guide RSS Feeds"
source: https://knowyourmeme.com/memes/and-its-gone
template_id: gone
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
