name: And It's Gone
source: https://knowyourmeme.com/memes/and-its-gone
keywords:
- South Park
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- we'll just invest that money
- '...aaaand it''s gone'
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About "And It's Gone!" (also known as "Aaaand It's Gone") is an advice
  animal image macro series featuring a picture of a bank teller from the animated
  television show South Park. The image macros are often accompanied by captions describing
  lost opportunities or items, ending in the titular phrase "And it's gone". Origin
  The original image is captured from a scene in the South Park episode "Margaritaville"[1],
  which first aired on March 25th, 2009. The phrase is used by a teller at South Park
  Bank Savings and Loans while informing customers that their money has been lost.
  On April 22nd, 2012, the first "And it's gone!" image macro was uploaded to Quickmeme[2]
  with the caption “You post your new meme idea. You think it's going to do great
  / Aaaand it's gone" (shown below). Spread On May 14th, 2012, an image macro featuring
  the caption "So this one time, me and Jason… / Anddd it's gone" (shown below, left)
  was posted to the /r/trees[3] subreddit by user Taco4all, receiving over 1,100 upvotes
  within two months. On May 25th, Redditor Dopecheez posted an image macro with the
  caption "I hope my post gets a lot of upvot- / Anddd it's gone" (shown below, right)
  to the /r/AdviceAnimals[4] subreddit, which received over 1,000 up votes within
  one month. As of July 14th, 2012, the Quickmeme[2] page for "Aaaand It's Gone" has
  accumulated over 2,500 submissions, the Quickmeme[6] page for "South Park Banker"
  has accumulated 457 submissions, the Meme Generator[7] page for "Aand It's Gone"
  the meme has received over 1000 items and a Facebook[8] page titled "Aaaand It's
  Gone" has received over 990 likes. Notable Examples Search Interest External References
  [1] South Park Wiki – Margaritaville [2] Quickmeme – aaaand its gone [3] Reddit
  – Trying to tell a story at 6 [4] Reddit – Every time I post something to r/new…
  [5] Quickmeme – aaaand its gone [6] Quickmeme – South Park Banker [7] Meme Generator
  – Aand Its Gone [8] Facebook – Aaaand It's Gone
aside_content: MemeStatusConfirmedYear2009OriginSouth ParkTagsimage macro,animation,south
  park,advice animals,aaand its gone,entry of july 2012,dopecheezAdditional ReferencesMeme
  Generator
added_at: '2012-07-14T10:15:21-04:00'
