name: I'm Going to Build My Own Theme Park
source: http://knowyourmeme.com/memes/im-going-to-build-my-own-theme-park-with-blackjack-and-hookers
keywords:
- Futurama
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- i'm going to build my own theme park
- with blackjack and hookers
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About "I''m Going To Build My Own Theme Park With Blackjack and
  Hookers" is a memorable quote said by Bender in a 1999 episode of the animated TV
  series Futurama. In image macros and comments, variations of the phrasal template
  “We’ll create our own (X) with blackjack and hookers” have been used to express
  dissatisfaction with the status quo, suggesting that the commenter could do it better.
  Origin The phrase was first uttered in the second episode of _Futurama_''s first
  season titled "The Series Has Landed"[1], which originally aired on April 4th, 1999.
  While on a trip to an amusement park on the moon, robotic anti-hero Bender is caught
  reaching through an arcade claw machine prize slot while trying to retrieve a set
  of lost keys and is ejected from the building. As he lands on the moon''s surface,
  he exclaims "I am going to build my own theme park with blackjack and hookers!"
  After walking back to the group''s spaceship, Bender sees the door close and thinks
  they are about to leave without him, causing him to utter the phrase again in reference
  to building his own lunar lander. [This video has been removed] Spread The quote
  was discussed online as early as April 2003, when a thread dedicated to it was created
  on the Prince.org forums.[2] That November, the phrase was added to Urban Dictionary[3],
  where it was described as a phrasal template used when someone gets kicked out of
  a physical place or group. In October 2007, it was used as the title of a personal
  blog post[5], describing how a graphic designer created a specific lighting shader
  program after someone deemed it impossible. In January 2008, the phrase was used
  on Reddit[6] for the first time by a Ron Paul opposer who was joking about creating
  a version of Reddit without any mentions of the politician. The post gained 5 upvotes
  but 0 points overall. On October 29th, 2009, a Facebook fan page titled "Blackjack
  and Hookers"[4] was created, accruing 413 likes as of September 2013. That year,
  the phrase "Blackjack and Hookers" was used as the title of an achievement in the
  Xbox game Kane and Lynch 2: Dog Days.[16] In January 2010, the subreddit /r/BlackjackAndHookers[7]
  launched, gaining nearly 400 subscribers as of September 2013. A second Facebook
  fan page[8] for the phrase was established on April 18th, 2010. Between 2010 and
  2011, the phrase was used to describe people wanting to create their own mobile
  operating systems[9], message board art threads[10] and Minecraft buildings from
  scratch.[11] By December 2011[13], the phrase had become associated with an image
  of Bender wearing a white fur coat and several gold rings taken from the February
  27th, 2000 episode "Raging Bender."[12] Notable Examples As of September 2013, there
  are two Meme Generator pages[14][15] utilizing the image of Bender in the fur coat
  with captions relating to blackjack and hookers, with more than 10,000 submissions
  combined. Search Interest External References [1] Wikipedia – The Series Has Landed
  [2] Prince.org – I''m gonna go build my own theme park with blackjack and hookers…
  In fact forget the park. [3] Urban Dictionary – Fine, I''m gonna make my own [something]!
  With blackjack…and hookers… In fact, forget the [something]. [4] Facebook – Blackjack
  and Hookers [5] What your mother never told you about graphics development: My own
  lighting shader with blackjack and hookers [6] Reddit – /r/reddit.com: I''m going
  to start my own Reddit (with blackjack and hookers) [7] Reddit – /r/BlackjackAndHookers
  [8] Facebook – Yeah, well… I''m gonna go build my own theme park, with blackjack
  and hookers. [9] Strongly Emergenct Blog – I''ll Build My Own Phone OS! With Blackjack!
  And Hookers! [10] Brontoforums – I''m Gonna'' Make My Own Art Thread; With Blackjack,
  And Hookers! [11] GameFAQs – so I made my own minecraft tavern/bar. with blackjack.
  and hookers. [12] Wikipedia – Raging Bender [13] WeKnowMemes (via Wayback Machine)
  – Well Start Our Own Internet With Blackjack And Hookers [14] Meme Generator – Bender
  Blackjack and Hookers [15] Meme Generator – Blackjack and Hookers Bender [16] Xbox
  360 Achievements – Kane & Lynch 2: Dog Days Achievements'
aside_content: MemeStatusConfirmedBadges:SensitiveYear1999OriginFuturamaTagsfuturama,bender,with
  blackjack and hookers!,snowclone,quoteAdditional ReferencesMeme GeneratorUrban Dictionary
added_at: '2012-07-12T07:32:59-04:00'
