example:
- i'm going to build my own theme park
- with blackjack and hookers
keywords:
- Futurama
name: I'm Going to Build My Own Theme Park
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "I'm Going To Build My Own Theme Park With Blackjack and Hookers\
  \ | Know Your Meme Yo Yo! You must login or signup first! Already a memeber? Login\
  \ Now! Don't have an account? Sign up Now! Meme Encyclopedia All Cultures Events\
  \ People Sites Subcultures Videos Submit \u2192 Images Trending Most Commented Most\
  \ Favorited High Score Low Score Most Viewed All Templates Upload an Image Articles\
  \ News Explainers Collections Interviews Meme Insider Magazine More Discord Newsletter\
  \ Episodes Forums Meme Store Login Abstract user icon Memes Categories Trending\
  \ News Images Trending Images Videos Trending Videos Editorials Meme Insider Magazine\
  \ Newsletter Policies and Guidelines Meme Store Old site Login Know Your Meme is\
  \ the property of Literally Media \xA92024 Literally Media. All Rights Reserved.\
  \ This image Of Woman Confidently Strolling Through A Glass Panel Has Been A Redraw\
  \ Format Since 2021 Three Years Ago, This Boar's Head 'Exploded' Onto The Meme Scene\
  \ Remember Il Vaticano? The Anarchy Chess Memes Turns Two Years Old Today Phrase\
  \ 'The Fridge Protects The Snacks' A Growing Favorite Among Pickup Artist Influencers\
  \ Jamie G, The Bosh British Charva, Has Taken Over TikTok With His Signature 'Oh\
  \ Cherie Amour' Sound Also Trending: Honey Extension Influencer Scam Renegade Raider\
  \ Copypasta Assassination of UnitedHealthcare CEO I'm Going To Build My Own Theme\
  \ Park With Blackjack and Hookers Added 12 years ago / Updated 8 days ago This entry\
  \ contains content that may be considered sensitive to some viewers. Confirmed 415,237\
  \ Part of a series on Futurama. [View Related Entries] Navigation About \u2022 Origin\
  \ \u2022 Spread \u2022 Notable Examples \u2022 Search Interest \u2022 External References\
  \ \u2022 Recent Images \u2022 Recent Videos About \"I'm Going To Build My Own Theme\
  \ Park With Blackjack and Hookers\" is a memorable quote said by Bender in a 1999\
  \ episode of the animated TV series Futurama. In image macros and comments, variations\
  \ of the phrasal template \u201CWe\u2019ll create our own (X) with blackjack and\
  \ hookers\u201D have been used to express dissatisfaction with the status quo, suggesting\
  \ that the commenter could do it better. Origin The phrase was first uttered in\
  \ the second episode of _Futurama_'s first season titled \"The Series Has Landed\"\
  [1], which originally aired on April 4th, 1999. While on a trip to an amusement\
  \ park on the moon, robotic anti-hero Bender is caught reaching through an arcade\
  \ claw machine prize slot while trying to retrieve a set of lost keys and is ejected\
  \ from the building. As he lands on the moon's surface, he exclaims \"I am going\
  \ to build my own theme park with blackjack and hookers!\" After walking back to\
  \ the group's spaceship, Bender sees the door close and thinks they are about to\
  \ leave without him, causing him to utter the phrase again in reference to building\
  \ his own lunar lander. [This video has been removed] Spread The quote was discussed\
  \ online as early as April 2003, when a thread dedicated to it was created on the\
  \ Prince.org forums.[2] That November, the phrase was added to Urban Dictionary[3],\
  \ where it was described as a phrasal template used when someone gets kicked out\
  \ of a physical place or group. In October 2007, it was used as the title of a personal\
  \ blog post[5], describing how a graphic designer created a specific lighting shader\
  \ program after someone deemed it impossible. In January 2008, the phrase was used\
  \ on Reddit[6] for the first time by a Ron Paul opposer who was joking about creating\
  \ a version of Reddit without any mentions of the politician. The post gained 5\
  \ upvotes but 0 points overall. On October 29th, 2009, a Facebook fan page titled\
  \ \"Blackjack and Hookers\"[4] was created, accruing 413 likes as of September 2013.\
  \ That year, the phrase \"Blackjack and Hookers\" was used as the title of an achievement\
  \ in the Xbox game Kane and Lynch 2: Dog Days.[16] In January 2010, the subreddit\
  \ /r/BlackjackAndHookers[7] launched, gaining nearly 400 subscribers as of September\
  \ 2013. A second Facebook fan page[8] for the phrase was established on April 18th,\
  \ 2010. Between 2010 and 2011, the phrase was used to describe people wanting to\
  \ create their own mobile operating systems[9], message board art threads[10] and\
  \ Minecraft buildings from scratch.[11] By December 2011[13], the phrase had become\
  \ associated with an image of Bender wearing a white fur coat and several gold rings\
  \ taken from the February 27th, 2000 episode \"Raging Bender.\"[12] Notable Examples\
  \ As of September 2013, there are two Meme Generator pages[14][15] utilizing the\
  \ image of Bender in the fur coat with captions relating to blackjack and hookers,\
  \ with more than 10,000 submissions combined. Search Interest External References\
  \ [1] Wikipedia \u2013 The Series Has Landed [2] Prince.org \u2013 I'm gonna go\
  \ build my own theme park with blackjack and hookers\u2026 In fact forget the park.\
  \ [3] Urban Dictionary \u2013 Fine, I'm gonna make my own [something]! With blackjack\u2026\
  and hookers\u2026 In fact, forget the [something]. [4] Facebook \u2013 Blackjack\
  \ and Hookers [5] What your mother never told you about graphics development: My\
  \ own lighting shader with blackjack and hookers [6] Reddit \u2013 /r/reddit.com:\
  \ I'm going to start my own Reddit (with blackjack and hookers) [7] Reddit \u2013\
  \ /r/BlackjackAndHookers [8] Facebook \u2013 Yeah, well\u2026 I'm gonna go build\
  \ my own theme park, with blackjack and hookers. [9] Strongly Emergenct Blog \u2013\
  \ I'll Build My Own Phone OS! With Blackjack! And Hookers! [10] Brontoforums \u2013\
  \ I'm Gonna' Make My Own Art Thread; With Blackjack, And Hookers! [11] GameFAQs\
  \ \u2013 so I made my own minecraft tavern/bar. with blackjack. and hookers. [12]\
  \ Wikipedia \u2013 Raging Bender [13] WeKnowMemes (via Wayback Machine) \u2013 Well\
  \ Start Our Own Internet With Blackjack And Hookers [14] Meme Generator \u2013 Bender\
  \ Blackjack and Hookers [15] Meme Generator \u2013 Blackjack and Hookers Bender\
  \ [16] Xbox 360 Achievements \u2013 Kane & Lynch 2: Dog Days Achievements futurama\
  \ bender with blackjack and hookers! snowclone quote Share Pin Related Entries 16\
  \ total Futurama Fry / Not Sure If I Don't Want to Live on This ... Shut Up And\
  \ Take My Money! Futurama Zoidberg / Why Not Z... View All Related Entries Recent\
  \ Images 42 total View All Images Recent Videos 10 total View All Videos Sign up\
  \ for our Newsletter Load 37 Comments Comments 37 total 48 I'm Going To Build My\
  \ Own Theme Park With Blackjack and Hookers 415,237 10 42 37 Part of a series on\
  \ Futurama. [View Related Entries] Updated Dec 15, 2024 at 03:47PM EST by LiterallyAustin.\
  \ Added Jul 12, 2012 at 07:32AM EDT by MediExcalibur2012 .. Like us on Facebook!\
  \ Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to\
  \ view the video gallery, or 'r' to view a random entry. This entry contains content\
  \ that may be considered sensitive to some viewers. Meme Status Confirmed Badges:\
  \ Sensitive Year 1999 Origin Futurama Tags futurama, bender, with blackjack and\
  \ hookers!, snowclone, quote Additional References Meme Generator Urban Dictionary\
  \ About \"I'm Going To Build My Own Theme Park With Blackjack and Hookers\" is a\
  \ memorable quote said by Bender in a 1999 episode of the animated TV series Futurama.\
  \ In image macros and comments, variations of the phrasal template \u201CWe\u2019\
  ll create our own (X) with blackjack and hookers\u201D have been used to express\
  \ dissatisfaction with the status quo, suggesting that the commenter could do it\
  \ better. Origin The phrase was first uttered in the second episode of _Futurama_'s\
  \ first season titled \"The Series Has Landed\"[1], which originally aired on April\
  \ 4th, 1999. While on a trip to an amusement park on the moon, robotic anti-hero\
  \ Bender is caught reaching through an arcade claw machine prize slot while trying\
  \ to retrieve a set of lost keys and is ejected from the building. As he lands on\
  \ the moon's surface, he exclaims \"I am going to build my own theme park with blackjack\
  \ and hookers!\" After walking back to the group's spaceship, Bender sees the door\
  \ close and thinks they are about to leave without him, causing him to utter the\
  \ phrase again in reference to building his own lunar lander. [This video has been\
  \ removed] Spread The quote was discussed online as early as April 2003, when a\
  \ thread dedicated to it was created on the Prince.org forums.[2] That November,\
  \ the phrase was added to Urban Dictionary[3], where it was described as a phrasal\
  \ template used when someone gets kicked out of a physical place or group. In October\
  \ 2007, it was used as the title of a personal blog post[5], describing how a graphic\
  \ designer created a specific lighting shader program after someone deemed it impossible.\
  \ In January 2008, the phrase was used on Reddit[6] for the first time by a Ron\
  \ Paul opposer who was joking about creating a version of Reddit without any mentions\
  \ of the politician. The post gained 5 upvotes but 0 points overall. On October\
  \ 29th, 2009, a Facebook fan page titled \"Blackjack and Hookers\"[4] was created,\
  \ accruing 413 likes as of September 2013. That year, the phrase \"Blackjack and\
  \ Hookers\" was used as the title of an achievement in the Xbox game Kane and Lynch\
  \ 2: Dog Days.[16] In January 2010, the subreddit /r/BlackjackAndHookers[7] launched,\
  \ gaining nearly 400 subscribers as of September 2013. A second Facebook fan page[8]\
  \ for the phrase was established on April 18th, 2010. Between 2010 and 2011, the\
  \ phrase was used to describe people wanting to create their own mobile operating\
  \ systems[9], message board art threads[10] and Minecraft buildings from scratch.[11]\
  \ By December 2011[13], the phrase had become associated with an image of Bender\
  \ wearing a white fur coat and several gold rings taken from the February 27th,\
  \ 2000 episode \"Raging Bender.\"[12] Notable Examples As of September 2013, there\
  \ are two Meme Generator pages[14][15] utilizing the image of Bender in the fur\
  \ coat with captions relating to blackjack and hookers, with more than 10,000 submissions\
  \ combined. Search Interest External References [1] Wikipedia \u2013 The Series\
  \ Has Landed [2] Prince.org \u2013 I'm gonna go build my own theme park with blackjack\
  \ and hookers\u2026 In fact forget the park. [3] Urban Dictionary \u2013 Fine, I'm\
  \ gonna make my own [something]! With blackjack\u2026and hookers\u2026 In fact,\
  \ forget the [something]. [4] Facebook \u2013 Blackjack and Hookers [5] What your\
  \ mother never told you about graphics development: My own lighting shader with\
  \ blackjack and hookers [6] Reddit \u2013 /r/reddit.com: I'm going to start my own\
  \ Reddit (with blackjack and hookers) [7] Reddit \u2013 /r/BlackjackAndHookers [8]\
  \ Facebook \u2013 Yeah, well\u2026 I'm gonna go build my own theme park, with blackjack\
  \ and hookers. [9] Strongly Emergenct Blog \u2013 I'll Build My Own Phone OS! With\
  \ Blackjack! And Hookers! [10] Brontoforums \u2013 I'm Gonna' Make My Own Art Thread;\
  \ With Blackjack, And Hookers! [11] GameFAQs \u2013 so I made my own minecraft tavern/bar.\
  \ with blackjack. and hookers. [12] Wikipedia \u2013 Raging Bender [13] WeKnowMemes\
  \ (via Wayback Machine) \u2013 Well Start Our Own Internet With Blackjack And Hookers\
  \ [14] Meme Generator \u2013 Bender Blackjack and Hookers [15] Meme Generator \u2013\
  \ Blackjack and Hookers Bender [16] Xbox 360 Achievements \u2013 Kane & Lynch 2:\
  \ Dog Days Achievements Related Entries 16 total Futurama Fry / Not Sure If I Don't\
  \ Want to Live on This Planet Anymore Shut Up And Take My Money! Futurama Zoidberg\
  \ / Why Not Zoidberg? Death By Snu Snu Your Music's Bad and You Should Feel Bad\
  \ Windmills do not work that way! Neutral Response Neat Oh Wait. You're Serious?\
  \ Let Me Laugh Even Harder! No Need to Thank Me Suicide Booth View All Related Entries\
  \ Recent Videos 10 total (HD) Bender: BlackJack und Nu... I'm Going To Build My\
  \ Own The... Uploaded by shevyrolet Bender - blackjack e squillo ... I'm Going To\
  \ Build My Own The... Uploaded by shevyrolet Futurama - Forget the lunar l... I'm\
  \ Going To Build My Own The... Uploaded by shevyrolet Dixie - Blackjack & Hookers\
  \ (... I'm Going To Build My Own The... Uploaded by shevyrolet Futurama - Build\
  \ my own theme... I'm Going To Build My Own The... Uploaded by shevyrolet Black\
  \ Jack and Hookers I'm Going To Build My Own The... Uploaded by shevyrolet Futurama:\
  \ Blackjack and hookers I'm Going To Build My Own The... Uploaded by shevyrolet\
  \ Blackjack and Hookers (BENDER!!) I'm Going To Build My Own The... Uploaded by\
  \ shevyrolet + Add a Video View All Videos Recent Images 42 total I'm Going To Build\
  \ My Own The... Uploaded by Jill I'm Going To Build My Own The... Uploaded by Rebecca\
  \ Rhodes I'm Going To Build My Own The... Uploaded by mnemeros I'm Going To Build\
  \ My Own The... Uploaded by Cold Hard Crash I'm Going To Build My Own The... Uploaded\
  \ by Reddit Moments I'm Going To Build My Own The... Uploaded by Jill I'm Going\
  \ To Build My Own The... Uploaded by yelling_into_the_void I'm Going To Build My\
  \ Own The... Uploaded by BigD1987 I'm Going To Build My Own The... Uploaded by HelixSquared\
  \ I'm Going To Build My Own The... Uploaded by Ox Doxon I'm Going To Build My Own\
  \ The... Uploaded by Prime2099 I'm Going To Build My Own The... Uploaded by Kenneth_W\
  \ + Add an Image View All Images Sign up for our Newsletter Top Comments Delete\
  \ Sensitive Jeff dumbham Sep 25, 2013 at 09:02PM EDT +1 blackjack and hooker +31\
  \ Reply Delete Sensitive MediExcalibur2012 . Jul 12, 2012 at 07:54AM EDT (JUST IN\
  \ CASE) DEADPOOLED?! FINE I\u2019LL GO MAKE MY OWN \u2018KNOW YOUR MEME\u2019 WEBSITE\
  \ WITH BLACKJACK AND HOOKERS. IN FACT, FORGET THE WEBSITE AND THE BLACKJACK! EH,\
  \ SCREW THE WHOLE THING! +26 Reply + Add a Comment Comments (37) Display Comments\
  \ Add a Comment Top Entries This Month Meme Saika Kawakita Smile GIF Event Assassination\
  \ of UnitedHealthcare CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki\
  \ Sisters Culture Pornography Site Whisper View More Suggest a Change Edit History\
  \ Entry Editors (5) MediExcalibur2012 . Deactivated Cronus Sleuth & Scrapbooker\
  \ & Pundit Trollkeeper Jr. Researcher & Cataloger & Pundit amanda b. Meme Librarian\
  \ shevyrolet Digital Archaeologist & Treasurer & Media Bus Boy \u25BC + Request\
  \ Editorship View All Editors Today's Top Image Galleries Assassination of UnitedHealthcare\
  \ CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing Digital Circus About\
  \ Our Story Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes\
  \ News Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/im-going-to-build-my-own-theme-park-with-blackjack-and-hookers
template_id: bender
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
