name: What Year Is It?
source: http://knowyourmeme.com/memes/what-year-is-it
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- ''
- what year is it?
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About "What Year Is It" is the caption of an image macro featuring
  a photo of Robin Williams'' disheveled-looking character from the 1995 film Jumanji.
  In rage comics, it is often used in similar fashion to the my face when reaction
  faces to convey the disoriented sense of time experienced when waking up. Origin
  Jumanji is a fantasy-comedy film released on December 15th, 1995, starring Robin
  Williams playing the role of Alan: a boy who is sucked into a board game only to
  emerge 26 years later. After being freed from the game, he asks the two children
  that have freed him "what year is it?"[1] and is shocked to discover how much time
  has past. The image used for the caption "What year is it?" was taken from the official
  Jumanji movie trailer and can be seen at 1:09 in the following video: The earliest
  known reaction image macro instance was posted to the r/pics subreddit in a thread
  titled "How I feel after an afternoon nap"[2] on September 7th, 2011 by Redditor
  topshelf89. The thread managed to reach the front page and has accumulated 16,886
  up votes as of November 30th, 2011. Spread The same reaction image reached the front
  page of the marijuana enthusiast r/trees subreddit in a thread titled "First words
  out of my mouth after waking up still a solid 6"[7] on October 13th, 2011. The first
  known rage comic using the captioned image titled "Every damn night"[5] was created
  by Redditor Arbypwnyou and reached the front page of the f7u12 rage comic subreddit
  on October 16th, 2011. On November 11th, 2011, a Skyrim rage comic[11] by Redditor
  JoshuaTheWarrior reached the front page of the r/gaming subreddit. Rage comics using
  the reaction image have since spread to FunnyJunk[4] and Tumblr.[3] Two Quickmeme[6][7]
  pages have been created featuring the image with a total of 32 submissions as of
  November 30th, 2011. Notable Examples External References [1] Movieclips – What
  Year is It? [2] Reddit – How I feel after an afternoon nap [3] Tumblr – posts tagged
  #what year is it [4] FunnyJunk – what year is it (login required) [5] Reddit – Every
  damn night [6] Quickmeme – Jumanji [7] Reddit – First words out of my mouth after
  waking up still stoned [8] Reddit – Shit, someone started another game of Jumanji
  [9] Reddit – I love those 2 mins feel like 50 hour naps [10] Reddit – What my life
  will be like after Skyrim [11] Reddit – Skyrim Sleep Rage'
aside_content: MemeStatusConfirmedYear2011OriginJumanjiTagsrage comics,jumanji,robin
  williams,reaction image,topshelf89,joshuathewarrior,arbypwnyouAdditional ReferencesMeme
  GeneratorTenor
added_at: '2011-11-30T11:35:40-05:00'
