example:
- ''
- what year is it?
keywords:
- null
name: What Year Is It?
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "What Year Is It? | Know Your Meme Yo! You must login or signup first!\
  \ Already a memeber? Login Now! Don't have an account? Sign up Now! Meme Encyclopedia\
  \ All Cultures Events People Sites Subcultures Videos Submit \u2192 Images Trending\
  \ Most Commented Most Favorited High Score Low Score Most Viewed All Templates Upload\
  \ an Image Articles News Explainers Collections Interviews Meme Insider Magazine\
  \ More Discord Newsletter Episodes Forums Meme Store Login Abstract user icon Memes\
  \ Categories Trending News Images Trending Images Videos Trending Videos Editorials\
  \ Meme Insider Magazine Newsletter Policies and Guidelines Meme Store Old site Login\
  \ Know Your Meme is the property of Literally Media \xA92024 Literally Media. All\
  \ Rights Reserved. This image Of Woman Confidently Strolling Through A Glass Panel\
  \ Has Been A Redraw Format Since 2021 Three Years Ago, This Boar's Head 'Exploded'\
  \ Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess Memes Turns Two Years\
  \ Old Today Phrase 'The Fridge Protects The Snacks' A Growing Favorite Among Pickup\
  \ Artist Influencers Jamie G, The Bosh British Charva, Has Taken Over TikTok With\
  \ His Signature 'Oh Cherie Amour' Sound Also Trending: Honey Extension Influencer\
  \ Scam Renegade Raider Copypasta Assassination of UnitedHealthcare CEO What Year\
  \ Is It? Added 13 years ago / Updated 3 years ago Confirmed 398,133 Part of a series\
  \ on Robin Williams. [View Related Entries] View All 30 Images Navigation About\
  \ \u2022 Origin \u2022 Spread \u2022 Notable Examples \u2022 External References\
  \ \u2022 Recent Images \u2022 Recent Videos About \"What Year Is It\" is the caption\
  \ of an image macro featuring a photo of Robin Williams' disheveled-looking character\
  \ from the 1995 film Jumanji. In rage comics, it is often used in similar fashion\
  \ to the my face when reaction faces to convey the disoriented sense of time experienced\
  \ when waking up. Origin Jumanji is a fantasy-comedy film released on December 15th,\
  \ 1995, starring Robin Williams playing the role of Alan: a boy who is sucked into\
  \ a board game only to emerge 26 years later. After being freed from the game, he\
  \ asks the two children that have freed him \"what year is it?\"[1] and is shocked\
  \ to discover how much time has past. The image used for the caption \"What year\
  \ is it?\" was taken from the official Jumanji movie trailer and can be seen at\
  \ 1:09 in the following video: The earliest known reaction image macro instance\
  \ was posted to the r/pics subreddit in a thread titled \"How I feel after an afternoon\
  \ nap\"[2] on September 7th, 2011 by Redditor topshelf89. The thread managed to\
  \ reach the front page and has accumulated 16,886 up votes as of November 30th,\
  \ 2011. Spread The same reaction image reached the front page of the marijuana enthusiast\
  \ r/trees subreddit in a thread titled \"First words out of my mouth after waking\
  \ up still a solid 6\"[7] on October 13th, 2011. The first known rage comic using\
  \ the captioned image titled \"Every damn night\"[5] was created by Redditor Arbypwnyou\
  \ and reached the front page of the f7u12 rage comic subreddit on October 16th,\
  \ 2011. On November 11th, 2011, a Skyrim rage comic[11] by Redditor JoshuaTheWarrior\
  \ reached the front page of the r/gaming subreddit. Rage comics using the reaction\
  \ image have since spread to FunnyJunk[4] and Tumblr.[3] Two Quickmeme[6][7] pages\
  \ have been created featuring the image with a total of 32 submissions as of November\
  \ 30th, 2011. Notable Examples External References [1] Movieclips \u2013 What Year\
  \ is It? [2] Reddit \u2013 How I feel after an afternoon nap [3] Tumblr \u2013 posts\
  \ tagged #what year is it [4] FunnyJunk \u2013 what year is it (login required)\
  \ [5] Reddit \u2013 Every damn night [6] Quickmeme \u2013 Jumanji [7] Reddit \u2013\
  \ First words out of my mouth after waking up still stoned [8] Reddit \u2013 Shit,\
  \ someone started another game of Jumanji [9] Reddit \u2013 I love those 2 mins\
  \ feel like 50 hour naps [10] Reddit \u2013 What my life will be like after Skyrim\
  \ [11] Reddit \u2013 Skyrim Sleep Rage rage comics jumanji robin williams reaction\
  \ image topshelf89 joshuathewarrior arbypwnyou Share Pin Recent Images 30 total\
  \ View All Images Recent Videos 5 total View All Videos Sign up for our Newsletter\
  \ Load 34 Comments Comments 34 total 39 What Year Is It? 398,133 5 30 34 Part of\
  \ a series on Robin Williams. [View Related Entries] Updated Jan 05, 2021 at 07:38AM\
  \ EST by andcallmeshirley. Added Nov 30, 2011 at 11:35AM EST by Don. Like us on\
  \ Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the image gallery,\
  \ 'v' to view the video gallery, or 'r' to view a random entry. Meme Status Confirmed\
  \ Year 2011 Origin Jumanji Tags rage comics, jumanji, robin williams, reaction image,\
  \ topshelf89, joshuathewarrior, arbypwnyou Additional References Meme Generator\
  \ Tenor About \"What Year Is It\" is the caption of an image macro featuring a photo\
  \ of Robin Williams' disheveled-looking character from the 1995 film Jumanji. In\
  \ rage comics, it is often used in similar fashion to the my face when reaction\
  \ faces to convey the disoriented sense of time experienced when waking up. Origin\
  \ Jumanji is a fantasy-comedy film released on December 15th, 1995, starring Robin\
  \ Williams playing the role of Alan: a boy who is sucked into a board game only\
  \ to emerge 26 years later. After being freed from the game, he asks the two children\
  \ that have freed him \"what year is it?\"[1] and is shocked to discover how much\
  \ time has past. The image used for the caption \"What year is it?\" was taken from\
  \ the official Jumanji movie trailer and can be seen at 1:09 in the following video:\
  \ The earliest known reaction image macro instance was posted to the r/pics subreddit\
  \ in a thread titled \"How I feel after an afternoon nap\"[2] on September 7th,\
  \ 2011 by Redditor topshelf89. The thread managed to reach the front page and has\
  \ accumulated 16,886 up votes as of November 30th, 2011. Spread The same reaction\
  \ image reached the front page of the marijuana enthusiast r/trees subreddit in\
  \ a thread titled \"First words out of my mouth after waking up still a solid 6\"\
  [7] on October 13th, 2011. The first known rage comic using the captioned image\
  \ titled \"Every damn night\"[5] was created by Redditor Arbypwnyou and reached\
  \ the front page of the f7u12 rage comic subreddit on October 16th, 2011. On November\
  \ 11th, 2011, a Skyrim rage comic[11] by Redditor JoshuaTheWarrior reached the front\
  \ page of the r/gaming subreddit. Rage comics using the reaction image have since\
  \ spread to FunnyJunk[4] and Tumblr.[3] Two Quickmeme[6][7] pages have been created\
  \ featuring the image with a total of 32 submissions as of November 30th, 2011.\
  \ Notable Examples External References [1] Movieclips \u2013 What Year is It? [2]\
  \ Reddit \u2013 How I feel after an afternoon nap [3] Tumblr \u2013 posts tagged\
  \ #what year is it [4] FunnyJunk \u2013 what year is it (login required) [5] Reddit\
  \ \u2013 Every damn night [6] Quickmeme \u2013 Jumanji [7] Reddit \u2013 First words\
  \ out of my mouth after waking up still stoned [8] Reddit \u2013 Shit, someone started\
  \ another game of Jumanji [9] Reddit \u2013 I love those 2 mins feel like 50 hour\
  \ naps [10] Reddit \u2013 What my life will be like after Skyrim [11] Reddit \u2013\
  \ Skyrim Sleep Rage Recent Videos 5 total What Year is It? Meme Jumanji What Year\
  \ Is It? Uploaded by andcallmeshirley Jumanji (2/8) Movie CLIP - Wh... What Year\
  \ Is It? Uploaded by andcallmeshirley Jumanji (1995) - Trailer What Year Is It?\
  \ Uploaded by andcallmeshirley 1964 Antique MODEM Live Demo What Year Is It? Uploaded\
  \ by Don + Add a Video Recent Images 30 total What Year Is It? Uploaded by gpaulh62\
  \ What Year Is It? Uploaded by justThisFool What Year Is It? Uploaded by m What\
  \ Year Is It? Uploaded by DeathbyExile What Year Is It? Uploaded by Jill What Year\
  \ Is It? Uploaded by ShiJo What Year Is It? Uploaded by Mister Musashi What Year\
  \ Is It? Uploaded by Mister Musashi What Year Is It? Uploaded by Fresh Prince of\
  \ Nohr What Year Is It? Uploaded by Brad What Year Is It? Uploaded by panda_chaos\
  \ What Year Is It? Uploaded by James + Add an Image View All Images Sign up for\
  \ our Newsletter Top Comments Delete Sensitive Cyber6x Moderator Dec 01, 2011 at\
  \ 05:51AM EST +32 Reply Delete Sensitive ConnerABacon Nov 30, 2011 at 06:29PM EST\
  \ ADVENTURE YEAR! +11 Reply + Add a Comment Comments (34) Display Comments Add a\
  \ Comment Top Entries This Month Meme Saika Kawakita Smile GIF Event Assassination\
  \ of UnitedHealthcare CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki\
  \ Sisters Culture Pornography Site Whisper View More Suggest a Change Edit History\
  \ Entry Editors (9) Don Administrator & Meme Daddy Cyber6x Database Moderator &\
  \ Midnight Channeler Teh Brawler Webcomicologist & Twitterologist Molly Horan Tumblr\
  \ Historian MScratch Database Moderator & Historical Meme Historian & \u300CStand\
  \ User\u300D Brad Digital Archaeologist & Treasurer & Pundit & Gallery Housekeeper\
  \ Z. Database Moderator & Rage Comicologist Y F Digital Archaeologist & Treasurer\
  \ & Media Maid andcallmeshirley Digital Archaeologist & Treasurer & Collection Butler\
  \ \u25BC + Request Editorship View All Editors Today's Top Image Galleries Assassination\
  \ of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing\
  \ Digital Circus About Our Story Site Rules Policies and Guidelines Credits Contact\
  \ Meme DB Memes Episodes News Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/what-year-is-it
template_id: whatyear
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
