name: I Have No Idea What I'm Doing
source: http://knowyourmeme.com/memes/i-have-no-idea-what-i-m-doing
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- i have no idea
- what i'm doing
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About "I Have No Idea What I''m Doing" is a catchphrase often used
  in image macro captions featuring photos of animals, typically canines, posed as
  if they are performing tasks associated with humans, in a similar vein to "Yes,
  This is Dog" and the Dog Fort comic series. Origin The earliest known appearance
  of the photo of a Golden Retriever posing with a camera appeared on the Hong Kong
  Wordpress site Photoblog[6] on November 20th, 2010. On February 27th, 2011, a photoshopped
  version was posted by Ben Grelle (a.k.a The Frogman) to his Tumblr[1] blog with
  the caption "I have no idea what I''m doing." The post received over 5,000 notes
  in less than a year. Spread On March 3rd, 2011, Frogman''s image was submitted to
  Reddit[2] and reached the front page accumulating 3,609 up votes prior to being
  archived. In the thread, Frogman responded with a complaint that his watermark had
  been cropped out of the image, and provided a link to his original post. The earliest
  known instance of the chemistry dog with the "I have no idea what I''m doing" caption
  was posted to the Lolabego Tumblr[4] on June 17th, 2011. Bailey the Golden Retriever
  On December 2th, 2011, an image of a dog sitting at a laptop accompanied by the
  catchphrase was submitted to the /r/funny[10] subreddit and reached the front page
  accumulating over 4,500 up votes within 6 weeks. On October 15th, 2014, Redditor
  Golden_Bailey submitted a photo gallery of the dog titled "Remember the ''I have
  no idea what I''m doing dog''? I am her owner and here is a small album of more(better)
  pictures of her" to /r/aww.[12] On January 8th, 2018, Redditor Golden_Bailey submitted
  another set of photographs identifying the dog as Bailey to /r/pics,[11] where the
  original desk picture was included (shown below). In the gallery, Bailey''s owner
  revealed she had died due to complications from bone cancer in early 2016. Within
  24 hours, the post garnered upwards of 124,000 points (88% upvoted) and 2,300 comments.
  Notable Examples Non-Canine Images Between 2012 and 2013, the phrase continued to
  grow in popularity as the scope of its usage began to expand beyond photographs
  of clueless-looking dogs. Search Interest Search queries for "have no idea what
  I''m doing" picked up in March of 2011, the same month the original Frogman instance
  was posted. External References [1] TheFrogman.me – The Frogman – Comedy, photoshop,
  kittens, & corgis [2] Reddit – I have no idea what I''m doing… [3] Reddit – thefrogman
  [4] Tumblr – Lolabego (unavailable) [5] Reddit – How I feel being told I''m an approved
  submitter [6] Photoblog – photoblog [7] Cheezburger – Tagged results for ''I Have
  No Idea What I''m Doing [8] Uproxx – Meme Watch: ‘I Have No Idea What I’m Doing’
  Sums Up The Internal Monologue Of Dogs [9] TVTropes – I Have No Idea What I''m Doing
  [10] Reddit – How I feel being told I''m an approved submitter [11] Reddit – Reddit
  you made our dog semi-famous years ago [12] Reddit – Remember the I have no idea
  what I''m doing dog? I am her owner and here is a small album of more(better) pictures
  of her'
aside_content: MemeStatusConfirmedYear2011OriginTumblrTagsi have no idea,no idea,no
  idea what im doing,dog,anthropomorphic dog,dog photoAdditional ReferencesMeme Generator
added_at: '2012-01-15T13:32:03-05:00'
