example:
- i have no idea
- what i'm doing
keywords:
- null
name: I Have No Idea What I'm Doing
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "I Have No Idea What I'm Doing | Know Your Meme Greetings! You must\
  \ login or signup first! Already a memeber? Login Now! Don't have an account? Sign\
  \ up Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos\
  \ Submit \u2192 Images Trending Most Commented Most Favorited High Score Low Score\
  \ Most Viewed All Templates Upload an Image Articles News Explainers Collections\
  \ Interviews Meme Insider Magazine More Discord Newsletter Episodes Forums Meme\
  \ Store Login Abstract user icon Memes Categories Trending News Images Trending\
  \ Images Videos Trending Videos Editorials Meme Insider Magazine Newsletter Policies\
  \ and Guidelines Meme Store Old site Login Know Your Meme is the property of Literally\
  \ Media \xA92024 Literally Media. All Rights Reserved. This image Of Woman Confidently\
  \ Strolling Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years\
  \ Ago, This Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The\
  \ Anarchy Chess Memes Turns Two Years Old Today Phrase 'The Fridge Protects The\
  \ Snacks' A Growing Favorite Among Pickup Artist Influencers Jamie G, The Bosh British\
  \ Charva, Has Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also\
  \ Trending: Honey Extension Influencer Scam Renegade Raider Copypasta Assassination\
  \ of UnitedHealthcare CEO I Have No Idea What I'm Doing Added 12 years ago / Updated\
  \ 8 days ago Confirmed 1,506,896 Part of a series on Dogs. [View Related Entries]\
  \ View All 128 Images Navigation About \u2022 Origin \u2022 Spread \u2022 Notable\
  \ Examples \u2022 Search Interest \u2022 External References \u2022 Recent Images\
  \ \u2022 Recent Videos About \"I Have No Idea What I'm Doing\" is a catchphrase\
  \ often used in image macro captions featuring photos of animals, typically canines,\
  \ posed as if they are performing tasks associated with humans, in a similar vein\
  \ to \"Yes, This is Dog\" and the Dog Fort comic series. Origin The earliest known\
  \ appearance of the photo of a Golden Retriever posing with a camera appeared on\
  \ the Hong Kong Wordpress site Photoblog[6] on November 20th, 2010. On February\
  \ 27th, 2011, a photoshopped version was posted by Ben Grelle (a.k.a The Frogman)\
  \ to his Tumblr[1] blog with the caption \"I have no idea what I'm doing.\" The\
  \ post received over 5,000 notes in less than a year. Spread On March 3rd, 2011,\
  \ Frogman's image was submitted to Reddit[2] and reached the front page accumulating\
  \ 3,609 up votes prior to being archived. In the thread, Frogman responded with\
  \ a complaint that his watermark had been cropped out of the image, and provided\
  \ a link to his original post. The earliest known instance of the chemistry dog\
  \ with the \"I have no idea what I'm doing\" caption was posted to the Lolabego\
  \ Tumblr[4] on June 17th, 2011. Bailey the Golden Retriever On December 2th, 2011,\
  \ an image of a dog sitting at a laptop accompanied by the catchphrase was submitted\
  \ to the /r/funny[10] subreddit and reached the front page accumulating over 4,500\
  \ up votes within 6 weeks. On October 15th, 2014, Redditor Golden_Bailey submitted\
  \ a photo gallery of the dog titled \"Remember the 'I have no idea what I'm doing\
  \ dog'? I am her owner and here is a small album of more(better) pictures of her\"\
  \ to /r/aww.[12] On January 8th, 2018, Redditor Golden_Bailey submitted another\
  \ set of photographs identifying the dog as Bailey to /r/pics,[11] where the original\
  \ desk picture was included (shown below). In the gallery, Bailey's owner revealed\
  \ she had died due to complications from bone cancer in early 2016. Within 24 hours,\
  \ the post garnered upwards of 124,000 points (88% upvoted) and 2,300 comments.\
  \ Notable Examples Non-Canine Images Between 2012 and 2013, the phrase continued\
  \ to grow in popularity as the scope of its usage began to expand beyond photographs\
  \ of clueless-looking dogs. Search Interest Search queries for \"have no idea what\
  \ I'm doing\" picked up in March of 2011, the same month the original Frogman instance\
  \ was posted. External References [1] TheFrogman.me \u2013 The Frogman \u2013 Comedy,\
  \ photoshop, kittens, & corgis [2] Reddit \u2013 I have no idea what I'm doing\u2026\
  \ [3] Reddit \u2013 thefrogman [4] Tumblr \u2013 Lolabego (unavailable) [5] Reddit\
  \ \u2013 How I feel being told I'm an approved submitter [6] Photoblog \u2013 photoblog\
  \ [7] Cheezburger \u2013 Tagged results for 'I Have No Idea What I'm Doing [8] Uproxx\
  \ \u2013 Meme Watch: \u2018I Have No Idea What I\u2019m Doing\u2019 Sums Up The\
  \ Internal Monologue Of Dogs [9] TVTropes \u2013 I Have No Idea What I'm Doing [10]\
  \ Reddit \u2013 How I feel being told I'm an approved submitter [11] Reddit \u2013\
  \ Reddit you made our dog semi-famous years ago [12] Reddit \u2013 Remember the\
  \ I have no idea what I'm doing dog? I am her owner and here is a small album of\
  \ more(better) pictures of her i have no idea no idea no idea what im doing dog\
  \ anthropomorphic dog dog photo Share Pin Related Entries 111 total Yes, This is\
  \ Dog Phteven / Tuna the Dog Gabe the Dog / Bork Remixes Pun Dog View All Related\
  \ Entries Recent Images 128 total View All Images Recent Videos 8 total View All\
  \ Videos Sign up for our Newsletter Load 32 Comments Comments 32 total 92 I Have\
  \ No Idea What I'm Doing 1,506,896 8 128 32 Part of a series on Dogs. [View Related\
  \ Entries] Updated Dec 15, 2024 at 03:38PM EST by LiterallyAustin. Added Jan 15,\
  \ 2012 at 01:32PM EST by chemchris. Like us on Facebook! Like 1.8M Share Save Tweet\
  \ PROTIP: Press 'i' to view the image gallery, 'v' to view the video gallery, or\
  \ 'r' to view a random entry. Meme Status Confirmed Year 2011 Origin Tumblr Tags\
  \ i have no idea, no idea, no idea what im doing, dog, anthropomorphic dog, dog\
  \ photo Additional References Meme Generator About \"I Have No Idea What I'm Doing\"\
  \ is a catchphrase often used in image macro captions featuring photos of animals,\
  \ typically canines, posed as if they are performing tasks associated with humans,\
  \ in a similar vein to \"Yes, This is Dog\" and the Dog Fort comic series. Origin\
  \ The earliest known appearance of the photo of a Golden Retriever posing with a\
  \ camera appeared on the Hong Kong Wordpress site Photoblog[6] on November 20th,\
  \ 2010. On February 27th, 2011, a photoshopped version was posted by Ben Grelle\
  \ (a.k.a The Frogman) to his Tumblr[1] blog with the caption \"I have no idea what\
  \ I'm doing.\" The post received over 5,000 notes in less than a year. Spread On\
  \ March 3rd, 2011, Frogman's image was submitted to Reddit[2] and reached the front\
  \ page accumulating 3,609 up votes prior to being archived. In the thread, Frogman\
  \ responded with a complaint that his watermark had been cropped out of the image,\
  \ and provided a link to his original post. The earliest known instance of the chemistry\
  \ dog with the \"I have no idea what I'm doing\" caption was posted to the Lolabego\
  \ Tumblr[4] on June 17th, 2011. Bailey the Golden Retriever On December 2th, 2011,\
  \ an image of a dog sitting at a laptop accompanied by the catchphrase was submitted\
  \ to the /r/funny[10] subreddit and reached the front page accumulating over 4,500\
  \ up votes within 6 weeks. On October 15th, 2014, Redditor Golden_Bailey submitted\
  \ a photo gallery of the dog titled \"Remember the 'I have no idea what I'm doing\
  \ dog'? I am her owner and here is a small album of more(better) pictures of her\"\
  \ to /r/aww.[12] On January 8th, 2018, Redditor Golden_Bailey submitted another\
  \ set of photographs identifying the dog as Bailey to /r/pics,[11] where the original\
  \ desk picture was included (shown below). In the gallery, Bailey's owner revealed\
  \ she had died due to complications from bone cancer in early 2016. Within 24 hours,\
  \ the post garnered upwards of 124,000 points (88% upvoted) and 2,300 comments.\
  \ Notable Examples Non-Canine Images Between 2012 and 2013, the phrase continued\
  \ to grow in popularity as the scope of its usage began to expand beyond photographs\
  \ of clueless-looking dogs. Search Interest Search queries for \"have no idea what\
  \ I'm doing\" picked up in March of 2011, the same month the original Frogman instance\
  \ was posted. External References [1] TheFrogman.me \u2013 The Frogman \u2013 Comedy,\
  \ photoshop, kittens, & corgis [2] Reddit \u2013 I have no idea what I'm doing\u2026\
  \ [3] Reddit \u2013 thefrogman [4] Tumblr \u2013 Lolabego (unavailable) [5] Reddit\
  \ \u2013 How I feel being told I'm an approved submitter [6] Photoblog \u2013 photoblog\
  \ [7] Cheezburger \u2013 Tagged results for 'I Have No Idea What I'm Doing [8] Uproxx\
  \ \u2013 Meme Watch: \u2018I Have No Idea What I\u2019m Doing\u2019 Sums Up The\
  \ Internal Monologue Of Dogs [9] TVTropes \u2013 I Have No Idea What I'm Doing [10]\
  \ Reddit \u2013 How I feel being told I'm an approved submitter [11] Reddit \u2013\
  \ Reddit you made our dog semi-famous years ago [12] Reddit \u2013 Remember the\
  \ I have no idea what I'm doing dog? I am her owner and here is a small album of\
  \ more(better) pictures of her Related Entries 111 total Yes, This is Dog Phteven\
  \ / Tuna the Dog Gabe the Dog / Bork Remixes Pun Dog Dog Fort My Faggot Dog Doggo\
  \ Homophobic Dog / Not Too Fond Of Gay People Birthday Dog Stoner Dog Cupcake Dog\
  \ Cool Dog View All Related Entries Recent Videos 8 total Future of self-driving\
  \ cars? I Have No Idea What I'm Doing Uploaded by Brad I Don't Know I Have No Idea\
  \ What I'm Doing Uploaded by Don LiveLeak.com - I have no idea I Have No Idea What\
  \ I'm Doing Uploaded by Don Hundefilmen I Have No Idea What I'm Doing Uploaded by\
  \ Avon Barksdale Meet Porter. The World's Firs... I Have No Idea What I'm Doing\
  \ Uploaded by BongDong DingDong NASL Season 4 - Chance the Ca... I Have No Idea\
  \ What I'm Doing Uploaded by Don [DONTSKIP.COM] Paris Hilton -... I Have No Idea\
  \ What I'm Doing Uploaded by Brad Heavy's magic trick I Have No Idea What I'm Doing\
  \ Uploaded by Jellote + Add a Video Recent Images 128 total I Have No Idea What\
  \ I'm Doing Uploaded by Bradley Q. I Have No Idea What I'm Doing Uploaded by pharmokan\
  \ I Have No Idea What I'm Doing Uploaded by Don I Have No Idea What I'm Doing Uploaded\
  \ by Don I Have No Idea What I'm Doing Uploaded by pleasedontmakemedothis I Have\
  \ No Idea What I'm Doing Uploaded by ballstothewall I Have No Idea What I'm Doing\
  \ Uploaded by TheAnt I Have No Idea What I'm Doing Uploaded by Mart\xEDn Nicol\xE1\
  s Ormaz\xE1bal Palma I Have No Idea What I'm Doing Uploaded by Samba I Have No Idea\
  \ What I'm Doing Uploaded by MagicaChocolate I Have No Idea What I'm Doing Uploaded\
  \ by LIMBERG92X I Have No Idea What I'm Doing Uploaded by EyexXx + Add an Image\
  \ View All Images Sign up for our Newsletter Top Comments Delete Sensitive Izzy\
  \ Jan 17, 2012 at 04:28PM EST Medic! What are you doing? +19 Reply Delete Sensitive\
  \ Iced Hot Chocolate Jan 15, 2012 at 03:25PM EST I actually have seen this around\u2026\
  so it isn't totally deadpoolable\u2026but it isn't really popular enough. +1 wait\
  \ +18 Reply + Add a Comment Comments (32) Display Comments Add a Comment Top Entries\
  \ This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (8) chemchris\
  \ Don Administrator & Meme Daddy Cyber6x Database Moderator & Midnight Channeler\
  \ Z. Database Moderator & Rage Comicologist amanda b. Meme Librarian Brad Digital\
  \ Archaeologist & Treasurer & Pundit & Gallery Housekeeper SabrinaTibbetts Memepuff\
  \ shevyrolet Digital Archaeologist & Treasurer & Media Bus Boy \u25BC + Request\
  \ Editorship View All Editors Today's Top Image Galleries Assassination of UnitedHealthcare\
  \ CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing Digital Circus About\
  \ Our Story Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes\
  \ News Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/i-have-no-idea-what-i-m-doing
template_id: noidea
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
