name: Woman Yelling at a Cat
source: https://knowyourmeme.com/memes/woman-yelling-at-a-cat
keywords:
- null
text:
- style: default
  color: black
  font: thin
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 0.5
  scale_y: 0.22
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: black
  font: thin
  anchor_x: 0.5
  anchor_y: 0.0
  angle: 0.0
  scale_x: 0.5
  scale_y: 0.22
  align: center
  start: 0.0
  stop: 1.0
example:
- Mom telling me how useless I am
- 12 year old me playing Minecraft
overlay:
- center_x: 0.25
  center_y: 0.61
  angle: 0.0
  scale: 0.78
- center_x: 0.75
  center_y: 0.61
  angle: 0.0
  scale: 0.78
scraped_content: 'About Woman Yelling at a Cat (not to be confused with Screaming
  Cat) refers to a meme format featuring a screen cap of The Real Housewives of Beverly
  Hills cast members Taylor Armstrong and Kyle Richards followed by a picture of a
  confused-looking cat sitting behind a dinner plate. The format gained significant
  popularity across the web in mid-June 2019 and the cat was later identified as Smudge
  the Cat. Origin Taylor Armstrong Crying and Pointing On December 5th, 2011, episode
  14 "Malibu Beach Party From Hell" of season two of The Real Housewives of Beverly
  Hills reality TV series premiered in the United States.[1] In the episode, cast
  member Taylor Armstrong cries during an argument, with cast member Kyle Richards
  attempting to calm her down. (shown below). On December 6th, Daily Mail published
  an article describing the events of the episode, posting a still of Armstrong pointing
  and crying and Richards hugging her (shown below).[2] Confused Cat at Dinner On
  June 19th, 2018, Tumblr user deadbefordeath posted a photograph of a white cat with
  a confused expression sitting in a chair in front of a plate with vegetables in
  it, titling the post "he no like vegetals." The post gained over 50,300 likes and
  reblogs in one year.[3] Following the popularity of the reaction image, on May 27th,
  2019, smudge_lord Instagram account was created for the cat,[13] with the cat''s
  name revealed to be Smudge. Woman Yelling at a Cat Until May 1st, 2019, both images
  saw moderate use as reactions on Twitter, 4chan and other websites.[4][5] On May
  1st, 2019, Twitter user @MISSINGEGIRL made a post containing both images, writing
  "These photos together is making me lose it."[6] The tweet gained over 78,900 retweets
  and 276,800 likes in two months (shown below). Spread On May 2nd, Twitter user @lc28__
  made the first known meme based on the format, gaining over 20 retweets and 180
  likes (shown below, left).[7] On June 2nd, 2019, Redditor PerpetualWinter made the
  first known object-labeling meme based on the format, gaining over 310 upvotes in
  one month (shown below, right).[8] On June 9th, Redditor 69- posted a template for
  the format to /r/memes subreddit.[9] On the same day, Redditor Apple-Trump posted
  a meme based on the format which gained over 38,600 upvotes in twelve days (shown
  below).[10] In the following days, the format gained significant spread on Reddit,
  with several highly-upvoted posts appearing in /r/dankmemes[11][12] and other subreddits.
  On November 4th, EbaumsWorld[14] published a collection of notable examples titled
  "49 Best ''Woman Yelling at a Cat'' Memes That Have Taken Over the Internet." Thurston
  Waffles Video On October 13th, 2019, Facebook user KucingMenangid posted a remix
  video of the Woman Yelling At Cat meme that places the cat Thurston Waffles in Smudge''s
  place. In a little over one week, the post received more than 727,000 views, 25,000
  shares, 12,000 reactions and 3,500 comments (shown below). Various Examples Templates
  Search Interest External References [1] Wikipedia – List of The Real Housewives
  of Beverly Hills episodes [2] Daily Mail – ''You, outside'': Taylor Armstrong has
  meltdown over husband Russell… as she lashes out at Housewives [3] Tumblr – deadbeforedeath''s
  Post [4] Twitter – YOU DO NOT MAKE KO CRY!!! [5] 4chan – /v/ Post #433704456 [6]
  Twitter – @missingegirl''s Tweet [7] Twitter – @lc28__ [8] Reddit – There’s a storm
  comin [9] Reddit – I’m giving out a free meme template [10] Reddit – Thanks for
  the free meme template u/-69-- [11] Reddit – Who tf is you [12] Reddit – Those bastards
  lied to me [13] Instagram – smudge_lord [14] EbaumsWorld – 49 best woman yelling
  at a cat memes'
aside_content: MemeStatusConfirmedType:ExploitableYear2019OriginTwitterTagscat,food,dinner,chair,the
  real housewives of beverly hills,taylor armstrong,kyle richards,malibu beach party
  from hell,salad cat,table cat,lady screaming at cat,smudge,taylor armstrong meme,cat
  meme,woman yelling at cat memeAdditional ReferencesEtsyMeme GeneratorRedditTwitterWikipedia
added_at: '2019-06-20T11:14:05-04:00'
