example:
- Mom telling me how useless I am
- 12 year old me playing Minecraft
keywords:
- null
name: Woman Yelling at a Cat
overlay:
- angle: 0.0
  center_x: 0.25
  center_y: 0.61
  scale: 0.78
- angle: 0.0
  center_x: 0.75
  center_y: 0.61
  scale: 0.78
scraped_content: "Woman Yelling at a Cat | Know Your Meme Yo Yo! You must login or\
  \ signup first! Already a memeber? Login Now! Don't have an account? Sign up Now!\
  \ Meme Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Woman Yelling at a Cat Added 5 years ago / Updated 8 days ago Confirmed 5,271,295\
  \ Part of a series on Smudge the Cat. [View Related Entries] View All 579 Images\
  \ Navigation About \u2022 Origin \u2022 Spread \u2022 Various Examples \u2022 Templates\
  \ \u2022 Search Interest \u2022 External References \u2022 Recent Images \u2022\
  \ Recent Videos About Woman Yelling at a Cat (not to be confused with Screaming\
  \ Cat) refers to a meme format featuring a screen cap of The Real Housewives of\
  \ Beverly Hills cast members Taylor Armstrong and Kyle Richards followed by a picture\
  \ of a confused-looking cat sitting behind a dinner plate. The format gained significant\
  \ popularity across the web in mid-June 2019 and the cat was later identified as\
  \ Smudge the Cat. Origin Taylor Armstrong Crying and Pointing On December 5th, 2011,\
  \ episode 14 \"Malibu Beach Party From Hell\" of season two of The Real Housewives\
  \ of Beverly Hills reality TV series premiered in the United States.[1] In the episode,\
  \ cast member Taylor Armstrong cries during an argument, with cast member Kyle Richards\
  \ attempting to calm her down. (shown below). On December 6th, Daily Mail published\
  \ an article describing the events of the episode, posting a still of Armstrong\
  \ pointing and crying and Richards hugging her (shown below).[2] Confused Cat at\
  \ Dinner On June 19th, 2018, Tumblr user deadbefordeath posted a photograph of a\
  \ white cat with a confused expression sitting in a chair in front of a plate with\
  \ vegetables in it, titling the post \"he no like vegetals.\" The post gained over\
  \ 50,300 likes and reblogs in one year.[3] Following the popularity of the reaction\
  \ image, on May 27th, 2019, smudge_lord Instagram account was created for the cat,[13]\
  \ with the cat's name revealed to be Smudge. Woman Yelling at a Cat Until May 1st,\
  \ 2019, both images saw moderate use as reactions on Twitter, 4chan and other websites.[4][5]\
  \ On May 1st, 2019, Twitter user @MISSINGEGIRL made a post containing both images,\
  \ writing \"These photos together is making me lose it.\"[6] The tweet gained over\
  \ 78,900 retweets and 276,800 likes in two months (shown below). Spread On May 2nd,\
  \ Twitter user @lc28__ made the first known meme based on the format, gaining over\
  \ 20 retweets and 180 likes (shown below, left).[7] On June 2nd, 2019, Redditor\
  \ PerpetualWinter made the first known object-labeling meme based on the format,\
  \ gaining over 310 upvotes in one month (shown below, right).[8] On June 9th, Redditor\
  \ 69- posted a template for the format to /r/memes subreddit.[9] On the same day,\
  \ Redditor Apple-Trump posted a meme based on the format which gained over 38,600\
  \ upvotes in twelve days (shown below).[10] In the following days, the format gained\
  \ significant spread on Reddit, with several highly-upvoted posts appearing in /r/dankmemes[11][12]\
  \ and other subreddits. On November 4th, EbaumsWorld[14] published a collection\
  \ of notable examples titled \"49 Best 'Woman Yelling at a Cat' Memes That Have\
  \ Taken Over the Internet.\" Thurston Waffles Video On October 13th, 2019, Facebook\
  \ user KucingMenangid posted a remix video of the Woman Yelling At Cat meme that\
  \ places the cat Thurston Waffles in Smudge's place. In a little over one week,\
  \ the post received more than 727,000 views, 25,000 shares, 12,000 reactions and\
  \ 3,500 comments (shown below). Various Examples Templates Search Interest External\
  \ References [1] Wikipedia \u2013 List of The Real Housewives of Beverly Hills episodes\
  \ [2] Daily Mail \u2013 'You, outside': Taylor Armstrong has meltdown over husband\
  \ Russell\u2026 as she lashes out at Housewives [3] Tumblr \u2013 deadbeforedeath's\
  \ Post [4] Twitter \u2013 YOU DO NOT MAKE KO CRY!!! [5] 4chan \u2013 /v/ Post #433704456\
  \ [6] Twitter \u2013 @missingegirl's Tweet [7] Twitter \u2013 @lc28__ [8] Reddit\
  \ \u2013 There\u2019s a storm comin [9] Reddit \u2013 I\u2019m giving out a free\
  \ meme template [10] Reddit \u2013 Thanks for the free meme template u/-69-- [11]\
  \ Reddit \u2013 Who tf is you [12] Reddit \u2013 Those bastards lied to me [13]\
  \ Instagram \u2013 smudge_lord [14] EbaumsWorld \u2013 49 best woman yelling at\
  \ a cat memes cat food dinner chair the real housewives of beverly hills taylor\
  \ armstrong kyle richards malibu beach party from hell salad cat table cat lady\
  \ screaming at cat smudge taylor armstrong meme cat meme woman yelling at cat meme\
  \ Share Pin Recent Images 579 total View All Images Recent Videos 48 total View\
  \ All Videos Sign up for our Newsletter Load 52 Comments Comments 52 total 155 Woman\
  \ Yelling at a Cat 5,271,306 48 579 52 Part of a series on Smudge the Cat. [View\
  \ Related Entries] Updated Dec 15, 2024 at 04:38PM EST by LiterallyAustin. Added\
  \ Jun 20, 2019 at 11:14AM EDT by Philipp. Like us on Facebook! Like 1.8M Share Save\
  \ Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the video gallery,\
  \ or 'r' to view a random entry. Meme Status Confirmed Type: Exploitable Year 2019\
  \ Origin Twitter Tags cat, food, dinner, chair, the real housewives of beverly hills,\
  \ taylor armstrong, kyle richards, malibu beach party from hell, salad cat, table\
  \ cat, lady screaming at cat, smudge, taylor armstrong meme, cat meme, woman yelling\
  \ at cat meme Additional References Etsy Meme Generator Reddit Twitter Wikipedia\
  \ About Woman Yelling at a Cat (not to be confused with Screaming Cat) refers to\
  \ a meme format featuring a screen cap of The Real Housewives of Beverly Hills cast\
  \ members Taylor Armstrong and Kyle Richards followed by a picture of a confused-looking\
  \ cat sitting behind a dinner plate. The format gained significant popularity across\
  \ the web in mid-June 2019 and the cat was later identified as Smudge the Cat. Origin\
  \ Taylor Armstrong Crying and Pointing On December 5th, 2011, episode 14 \"Malibu\
  \ Beach Party From Hell\" of season two of The Real Housewives of Beverly Hills\
  \ reality TV series premiered in the United States.[1] In the episode, cast member\
  \ Taylor Armstrong cries during an argument, with cast member Kyle Richards attempting\
  \ to calm her down. (shown below). On December 6th, Daily Mail published an article\
  \ describing the events of the episode, posting a still of Armstrong pointing and\
  \ crying and Richards hugging her (shown below).[2] Confused Cat at Dinner On June\
  \ 19th, 2018, Tumblr user deadbefordeath posted a photograph of a white cat with\
  \ a confused expression sitting in a chair in front of a plate with vegetables in\
  \ it, titling the post \"he no like vegetals.\" The post gained over 50,300 likes\
  \ and reblogs in one year.[3] Following the popularity of the reaction image, on\
  \ May 27th, 2019, smudge_lord Instagram account was created for the cat,[13] with\
  \ the cat's name revealed to be Smudge. Woman Yelling at a Cat Until May 1st, 2019,\
  \ both images saw moderate use as reactions on Twitter, 4chan and other websites.[4][5]\
  \ On May 1st, 2019, Twitter user @MISSINGEGIRL made a post containing both images,\
  \ writing \"These photos together is making me lose it.\"[6] The tweet gained over\
  \ 78,900 retweets and 276,800 likes in two months (shown below). Spread On May 2nd,\
  \ Twitter user @lc28__ made the first known meme based on the format, gaining over\
  \ 20 retweets and 180 likes (shown below, left).[7] On June 2nd, 2019, Redditor\
  \ PerpetualWinter made the first known object-labeling meme based on the format,\
  \ gaining over 310 upvotes in one month (shown below, right).[8] On June 9th, Redditor\
  \ 69- posted a template for the format to /r/memes subreddit.[9] On the same day,\
  \ Redditor Apple-Trump posted a meme based on the format which gained over 38,600\
  \ upvotes in twelve days (shown below).[10] In the following days, the format gained\
  \ significant spread on Reddit, with several highly-upvoted posts appearing in /r/dankmemes[11][12]\
  \ and other subreddits. On November 4th, EbaumsWorld[14] published a collection\
  \ of notable examples titled \"49 Best 'Woman Yelling at a Cat' Memes That Have\
  \ Taken Over the Internet.\" Thurston Waffles Video On October 13th, 2019, Facebook\
  \ user KucingMenangid posted a remix video of the Woman Yelling At Cat meme that\
  \ places the cat Thurston Waffles in Smudge's place. In a little over one week,\
  \ the post received more than 727,000 views, 25,000 shares, 12,000 reactions and\
  \ 3,500 comments (shown below). Various Examples Templates Search Interest External\
  \ References [1] Wikipedia \u2013 List of The Real Housewives of Beverly Hills episodes\
  \ [2] Daily Mail \u2013 'You, outside': Taylor Armstrong has meltdown over husband\
  \ Russell\u2026 as she lashes out at Housewives [3] Tumblr \u2013 deadbeforedeath's\
  \ Post [4] Twitter \u2013 YOU DO NOT MAKE KO CRY!!! [5] 4chan \u2013 /v/ Post #433704456\
  \ [6] Twitter \u2013 @missingegirl's Tweet [7] Twitter \u2013 @lc28__ [8] Reddit\
  \ \u2013 There\u2019s a storm comin [9] Reddit \u2013 I\u2019m giving out a free\
  \ meme template [10] Reddit \u2013 Thanks for the free meme template u/-69-- [11]\
  \ Reddit \u2013 Who tf is you [12] Reddit \u2013 Those bastards lied to me [13]\
  \ Instagram \u2013 smudge_lord [14] EbaumsWorld \u2013 49 best woman yelling at\
  \ a cat memes Recent Videos 48 total Two women yelling at a cat Woman Yelling at\
  \ a Cat Uploaded by shevyrolet Woman Yelling At Cat Meme || ... Woman Yelling at\
  \ a Cat Uploaded by shevyrolet How Did This Cat Became A The... Woman Yelling at\
  \ a Cat Uploaded by shevyrolet Woman Yelling at Cat Meme Woman Yelling at a Cat\
  \ Uploaded by shevyrolet Tuglife Woman yelling at a cat Woman Yelling at a Cat Uploaded\
  \ by shevyrolet Woman yelling at cat meme - Y... Woman Yelling at a Cat Uploaded\
  \ by shevyrolet Behind The Meme: Woman Yellin... Woman Yelling at a Cat Uploaded\
  \ by shevyrolet Angry woman yelling at confus... Woman Yelling at a Cat Uploaded\
  \ by shevyrolet + Add a Video View All Videos Recent Images 579 total Woman Yelling\
  \ at a Cat Uploaded by Unraveler Woman Yelling at a Cat Uploaded by LuisQuartz Woman\
  \ Yelling at a Cat Uploaded by Krazy-Chibi Woman Yelling at a Cat Uploaded by Triplem\
  \ Woman Yelling at a Cat Uploaded by PMRY Studio Woman Yelling at a Cat Uploaded\
  \ by Nyazilla Woman Yelling at a Cat Uploaded by Nyazilla Woman Yelling at a Cat\
  \ Uploaded by Memefart Woman Yelling at a Cat Uploaded by Jaimie Hamilton Woman\
  \ Yelling at a Cat Uploaded by Imabigfish Woman Yelling at a Cat Uploaded by Reddit\
  \ Moments Woman Yelling at a Cat Uploaded by CYSYS8993 + Add an Image View All Images\
  \ Sign up for our Newsletter Top Comments Delete Sensitive Smol boi Jun 20, 2019\
  \ at 07:52PM EDT KYM Members \"We want editable comments!\" KYM Staff/Mods: +122\
  \ Reply Delete Sensitive Goatllama Jun 26, 2019 at 06:10PM EDT in reply to TerribleTrike\
  \ +70 Reply + Add a Comment Comments (52) Display Comments Add a Comment Top Entries\
  \ This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (8) Philipp\
  \ Memesplainer Don Administrator & Meme Daddy Y F Digital Archaeologist & Treasurer\
  \ & Media Maid andcallmeshirley Digital Archaeologist & Treasurer & Collection Butler\
  \ Matt Secretary of Memes elenqy shevyrolet Digital Archaeologist & Treasurer &\
  \ Media Bus Boy Zach Memenator \u25BC + Request Editorship View All Editors Today's\
  \ Top Image Galleries Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen\
  \ Green) Team Fortress 2 The Amazing Digital Circus About Our Story Site Rules Policies\
  \ and Guidelines Credits Contact Meme DB Memes Episodes News Staff Contact Extras!\
  \ Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/woman-yelling-at-a-cat
template_id: woman-cat
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: black
  font: thin
  scale_x: 0.5
  scale_y: 0.22
  start: 0.0
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.5
  anchor_y: 0.0
  angle: 0.0
  color: black
  font: thin
  scale_x: 0.5
  scale_y: 0.22
  start: 0.0
  stop: 1.0
  style: default
text_zones: 2
