name: What's in the box!?
source: https://screenrant.com/hilarious-se7en-memes/
keywords:
  - Seven
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - ''
  - What's in the box!?
overlay:
  - center_x: 0.83
    center_y: 0.5
    angle: 0.0
    scale: 0.6
