name: Captain Hindsight
source: http://knowyourmeme.com/memes/captain-hindsight
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- if you wanted to avoid the friend zone
- you should have made your intentions known from the start
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Captain Hindsight is an image macro series based on the eponymous
  superhero character originally featured in an episode of the animated TV series
  South Park. Inspired by the character, image captions generally present various
  types of predicaments and then lecture on what could''ve been done differently to
  avoid the situation altogether (See Also: Captain Obvious). Origin Captain Hindsight
  first appeared in Season 14, Episode 11 of South Park titled "Coon 2: Hindsight"
  which aired on October 27th, 2010. In the episode, Captain Hindsight arrives at
  the scene of Deepwater Horizon oil spill, but instead of trying to resolve the crisis
  at hand, he explains to the crowd the precautions that should''ve been taken to
  prevent the disaster. Suddenly relieved, the crowd applaud as Captain Hindsight
  leaves behind the devastated beach: The show''s creators Matt Stone and Trey Parker
  later explained that character''s mock-superpower was inspired by the heavy hindsight
  bias in the news analysis following the outbreak of BP oil spill in the Gulf of
  Mexico in 2011. Urban Dictionary On the same night as its broadcast, Urban Dictionary
  definition of Captain Hindsight was submitted by user Xero_Manifesto: A stupid ass
  superhero from the South Park episode Coon 2: Hindsight. He flies around the world
  providing hindsight after every catastrophy that happens, but doesn''t actually
  do anything helpful. Spread On October 28th, Reddit user ironpirate83 posted a thread
  titled "BP knew well cement was ''unstable'' – Captain Hindsight," which linked
  to a MSNBC article indicating Haliburton may have been aware of the instability
  long prior to the accident. In early November, more tribute accounts and pages to
  Captain Hindsight began to emerge on various parts of the web, including the Twitter
  account @Capt_Hindsight, Facebook page for Captain Hindsight and Tumblr. The snowclone
  formula "If (x), you should''ve done (y)" emerged as early as on November 12th,
  2010 in a 4chan discussion thread about Minecraft: Captain Hindsight resurged on
  4chans'' /b/ board on March 13th, 2011, shortly after the Tohoku earthquake and
  tsunami across Japan. The date also coincides with upload date of the earliest image
  macro instance on Quickmeme: Notable Examples On Twitter Blank Template Search Interest
  External References [1] South Park Studios – God Bless You Captain Hindsight [2]
  Wikipedia – Coon 2: Hindsight [3] Wikipedia – Hindsight bias [4] Urban Dictionary
  – Captain Hindsight [5] Twitter – @Capt_Hindsight [6] Facebook – Captain Hindsight
  [7] Tumblr – Tagged Results for Captain Hindsight [8] 4chanarchive – Minecraft [9]
  4chanarchive – Japan Tsunami NSFW [10] Quickmeme – Captain Hindsight'
aside_content: MemeStatusConfirmedType:Character,Image MacroYear2010OriginSouth ParkTagsadvice
  animal,south park,superhero,snowclone,sitcom,regret,xero_manifesto,ironpirate83
added_at: '2011-09-01T12:36:19-04:00'
