example:
- if you wanted to avoid the friend zone
- you should have made your intentions known from the start
keywords:
- null
name: Captain Hindsight
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Captain Hindsight | Know Your Meme Hey! You must login or signup\
  \ first! Already a memeber? Login Now! Don't have an account? Sign up Now! Meme\
  \ Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Captain Hindsight Added 13 years ago / Updated 8 days ago Confirmed 202,589\
  \ Part of a series on South Park. [View Related Entries] View All 66 Images Navigation\
  \ About \u2022 Origin \u2022 Spread \u2022 Blank Template \u2022 Search Interest\
  \ \u2022 External References \u2022 Recent Images \u2022 Recent Videos About Captain\
  \ Hindsight is an image macro series based on the eponymous superhero character\
  \ originally featured in an episode of the animated TV series South Park. Inspired\
  \ by the character, image captions generally present various types of predicaments\
  \ and then lecture on what could've been done differently to avoid the situation\
  \ altogether (See Also: Captain Obvious). Origin Captain Hindsight first appeared\
  \ in Season 14, Episode 11 of South Park titled \"Coon 2: Hindsight\" which aired\
  \ on October 27th, 2010. In the episode, Captain Hindsight arrives at the scene\
  \ of Deepwater Horizon oil spill, but instead of trying to resolve the crisis at\
  \ hand, he explains to the crowd the precautions that should've been taken to prevent\
  \ the disaster. Suddenly relieved, the crowd applaud as Captain Hindsight leaves\
  \ behind the devastated beach: The show's creators Matt Stone and Trey Parker later\
  \ explained that character's mock-superpower was inspired by the heavy hindsight\
  \ bias in the news analysis following the outbreak of BP oil spill in the Gulf of\
  \ Mexico in 2011. Urban Dictionary On the same night as its broadcast, Urban Dictionary\
  \ definition of Captain Hindsight was submitted by user Xero_Manifesto: A stupid\
  \ ass superhero from the South Park episode Coon 2: Hindsight. He flies around the\
  \ world providing hindsight after every catastrophy that happens, but doesn't actually\
  \ do anything helpful. Spread On October 28th, Reddit user ironpirate83 posted a\
  \ thread titled \"BP knew well cement was 'unstable' \u2013 Captain Hindsight,\"\
  \ which linked to a MSNBC article indicating Haliburton may have been aware of the\
  \ instability long prior to the accident. In early November, more tribute accounts\
  \ and pages to Captain Hindsight began to emerge on various parts of the web, including\
  \ the Twitter account @Capt_Hindsight, Facebook page for Captain Hindsight and Tumblr.\
  \ The snowclone formula \"If (x), you should've done (y)\" emerged as early as on\
  \ November 12th, 2010 in a 4chan discussion thread about Minecraft: Captain Hindsight\
  \ resurged on 4chans' /b/ board on March 13th, 2011, shortly after the Tohoku earthquake\
  \ and tsunami across Japan. The date also coincides with upload date of the earliest\
  \ image macro instance on Quickmeme: Notable Examples On Twitter Blank Template\
  \ Search Interest External References [1] South Park Studios \u2013 God Bless You\
  \ Captain Hindsight [2] Wikipedia \u2013 Coon 2: Hindsight [3] Wikipedia \u2013\
  \ Hindsight bias [4] Urban Dictionary \u2013 Captain Hindsight [5] Twitter \u2013\
  \ @Capt_Hindsight [6] Facebook \u2013 Captain Hindsight [7] Tumblr \u2013 Tagged\
  \ Results for Captain Hindsight [8] 4chanarchive \u2013 Minecraft [9] 4chanarchive\
  \ \u2013 Japan Tsunami NSFW [10] Quickmeme \u2013 Captain Hindsight advice animal\
  \ south park superhero snowclone sitcom regret xero_manifesto ironpirate83 Share\
  \ Pin Related Entries 22 total Tree Fiddy ???? PROFIT!!!! Super Cool Ski Instructor\
  \ And It's Gone View All Related Entries Recent Images 66 total View All Images\
  \ Recent Videos 1 total View All Videos Sign up for our Newsletter Load 26 Comments\
  \ Comments 26 total 37 Captain Hindsight 202,589 1 66 26 Part of a series on South\
  \ Park. [View Related Entries] Updated Dec 15, 2024 at 06:43PM EST by LiterallyAustin.\
  \ Added Sep 01, 2011 at 12:36PM EDT by Brad. Like us on Facebook! Like 1.8M Share\
  \ Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the video\
  \ gallery, or 'r' to view a random entry. Meme Status Confirmed Type: Character,\
  \ Image Macro Year 2010 Origin South Park Tags advice animal, south park, superhero,\
  \ snowclone, sitcom, regret, xero_manifesto, ironpirate83 About Captain Hindsight\
  \ is an image macro series based on the eponymous superhero character originally\
  \ featured in an episode of the animated TV series South Park. Inspired by the character,\
  \ image captions generally present various types of predicaments and then lecture\
  \ on what could've been done differently to avoid the situation altogether (See\
  \ Also: Captain Obvious). Origin Captain Hindsight first appeared in Season 14,\
  \ Episode 11 of South Park titled \"Coon 2: Hindsight\" which aired on October 27th,\
  \ 2010. In the episode, Captain Hindsight arrives at the scene of Deepwater Horizon\
  \ oil spill, but instead of trying to resolve the crisis at hand, he explains to\
  \ the crowd the precautions that should've been taken to prevent the disaster. Suddenly\
  \ relieved, the crowd applaud as Captain Hindsight leaves behind the devastated\
  \ beach: The show's creators Matt Stone and Trey Parker later explained that character's\
  \ mock-superpower was inspired by the heavy hindsight bias in the news analysis\
  \ following the outbreak of BP oil spill in the Gulf of Mexico in 2011. Urban Dictionary\
  \ On the same night as its broadcast, Urban Dictionary definition of Captain Hindsight\
  \ was submitted by user Xero_Manifesto: A stupid ass superhero from the South Park\
  \ episode Coon 2: Hindsight. He flies around the world providing hindsight after\
  \ every catastrophy that happens, but doesn't actually do anything helpful. Spread\
  \ On October 28th, Reddit user ironpirate83 posted a thread titled \"BP knew well\
  \ cement was 'unstable' \u2013 Captain Hindsight,\" which linked to a MSNBC article\
  \ indicating Haliburton may have been aware of the instability long prior to the\
  \ accident. In early November, more tribute accounts and pages to Captain Hindsight\
  \ began to emerge on various parts of the web, including the Twitter account @Capt_Hindsight,\
  \ Facebook page for Captain Hindsight and Tumblr. The snowclone formula \"If (x),\
  \ you should've done (y)\" emerged as early as on November 12th, 2010 in a 4chan\
  \ discussion thread about Minecraft: Captain Hindsight resurged on 4chans' /b/ board\
  \ on March 13th, 2011, shortly after the Tohoku earthquake and tsunami across Japan.\
  \ The date also coincides with upload date of the earliest image macro instance\
  \ on Quickmeme: Notable Examples On Twitter Blank Template Search Interest External\
  \ References [1] South Park Studios \u2013 God Bless You Captain Hindsight [2] Wikipedia\
  \ \u2013 Coon 2: Hindsight [3] Wikipedia \u2013 Hindsight bias [4] Urban Dictionary\
  \ \u2013 Captain Hindsight [5] Twitter \u2013 @Capt_Hindsight [6] Facebook \u2013\
  \ Captain Hindsight [7] Tumblr \u2013 Tagged Results for Captain Hindsight [8] 4chanarchive\
  \ \u2013 Minecraft [9] 4chanarchive \u2013 Japan Tsunami NSFW [10] Quickmeme \u2013\
  \ Captain Hindsight Related Entries 22 total Tree Fiddy ???? PROFIT!!!! Super Cool\
  \ Ski Instructor And It's Gone They Took Our Jobs! Member Berries Oh, I'm Sorry,\
  \ I Thought This Was America Everybody Draw Mohammed Day PC Bro I Didn't Hear No\
  \ Bell South Park Transgender Athletes Episode Controversy My Name Is Craig Tucker\
  \ Copypasta View All Related Entries Recent Videos 1 total South Park Season 14\
  \ Coon 2: ... Captain Hindsight Uploaded by Brad + Add a Video Recent Images 66\
  \ total Captain Hindsight Uploaded by Reddit Moments Captain Hindsight Uploaded\
  \ by shadow_lepus Captain Hindsight Uploaded by Hypercat-Z Captain Hindsight Uploaded\
  \ by Emperor Palpitoad Captain Hindsight Uploaded by Keltapina Captain Hindsight\
  \ Uploaded by Calirolls Captain Hindsight Uploaded by klopek007 Captain Hindsight\
  \ Uploaded by klopek007 Captain Hindsight Uploaded by Brad Captain Hindsight Uploaded\
  \ by Brad Captain Hindsight Uploaded by Gabenus Trollucus Captain Hindsight Uploaded\
  \ by Brad + Add an Image View All Images Sign up for our Newsletter Top Comments\
  \ Delete Sensitive Magnan Sep 03, 2011 at 02:15PM EDT If I had thought of this first\
  \ then I'd be getting credit for this meme. +14 Reply Delete Sensitive Trollkeeper\
  \ Aug 12, 2012 at 10:20AM EDT +8 Reply + Add a Comment Comments (26) Display Comments\
  \ Add a Comment Top Entries This Month Meme Saika Kawakita Smile GIF Event Assassination\
  \ of UnitedHealthcare CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki\
  \ Sisters Culture Pornography Site Whisper View More Suggest a Change Edit History\
  \ Entry Editors (4) Brad Digital Archaeologist & Treasurer & Pundit & Gallery Housekeeper\
  \ Twenty-One Anime Anthropologist & Protip Advisor & LGBT Community Expert 3kole5\
  \ Sr. Entry Moderator Y F Digital Archaeologist & Treasurer & Media Maid + Request\
  \ Editorship View All Editors Today's Top Image Galleries Assassination of UnitedHealthcare\
  \ CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing Digital Circus About\
  \ Our Story Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes\
  \ News Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/captain-hindsight
template_id: ch
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
