example:
- ''
- you sit on a throne of lies
keywords:
- Elf
name: You Sit on a Throne of Lies
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "You Sit On A Throne Of Lies | Know Your Meme Howdy! You must login\
  \ or signup first! Already a memeber? Login Now! Don't have an account? Sign up\
  \ Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos Submit\
  \ \u2192 Images Trending Most Commented Most Favorited High Score Low Score Most\
  \ Viewed All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO You Sit On A Throne Of Lies Added 11 years ago / Updated 8 days ago Confirmed\
  \ 151,781 Part of a series on Reaction Images. [View Related Entries] View All 56\
  \ Images Navigation About \u2022 Origin \u2022 Spread \u2022 Notable Examples \u2022\
  \ Search Interest \u2022 External References \u2022 Recent Images \u2022 Recent\
  \ Videos About \"You Sit On A Throne Of Lies\" is a memorable quote uttered by Buddy\
  \ The Elf (played by Will Ferrell), the protagonist of the 2003 holiday family-comedy\
  \ film Elf. On the web, the phrase is typically used to expose a lie or otherwise\
  \ misleading statement told by someone else. Origin In the film, Buddy is disturbed\
  \ to discover that a mall Santa Claus is actually just a man dressed in a costume.\
  \ Believing that the man is trying to impersonate the Santa Claus he knows, Buddy\
  \ reacts with disgust, whispering to the man \"you sit on a throne of lies\" (shown\
  \ below). On June 1st, 2005, YTMND user Cryokenetic submitted a picture of Buddy\
  \ paired with audio of the \"You sit on a throne of lies\" clip.[1][2] Within the\
  \ next eight years, the page received over 220,000 views, 170 comments and the audio\
  \ clip was subsequently used on over 30 similar YTMNDs.[3][4] Spread The phrase\
  \ saw little activity on the web until June 11th, 2011, when it was added to the\
  \ \"That Liar Lies\" page on the trope database website TV Tropes.[8] On May 14th,\
  \ 2012, Redditor wordsandstuffs submitted a post titled \"You float on a throne\
  \ of lies\" to the /r/funny[10] subreddit, highlighting an animated GIF of a cat\
  \ destroying a floating cat balloon (shown below, left). Prior to being archived,\
  \ the post gathered more than 13,000 up votes and 240 comments. On May 5th, 2013,\
  \ Redditor likwitsnake submitted a post titled \"You sit on a throne of lies\" to\
  \ the /r/funny[9] subreddit, featuring a photograph of the nutritional information\
  \ on a bottle of \"+Calcium\" Hershey's chocolate syrup with 0% calcium (shown below,\
  \ right). In the first seven months, the post gained over 14,800 up votes and 340\
  \ comments. Notable Examples Image macros featuring Buddy accompanied by the quote\
  \ as a caption have been created on Meme Generator has created templates for Buddy\
  \ The Elf, featuring macros containing the quote in question and several others\
  \ related to the character.[5][6][7] Search Interest External References [1] YTMND\
  \ \u2013 You Sit on a Throne of Lies! [2] YTMND \u2013 Site Profile. [3] YTMND \u2013\
  \ Asset Information. [4] YTMND \u2013 'Throne Of Lies' Search. [5] Meme Generator\
  \ \u2013 Throne Of Lies Elf. [6] Meme Generator \u2013 Buddy The Elf. [7] Pinterest\
  \ \u2013 'You Sit On A Throne Of Lies' Search. [8] TV Tropes \u2013 That Liar Lies.\
  \ [9] Reddit \u2013 You Sit On A Throne Of Lies. [10] Reddit \u2013 You Float On\
  \ A Throne Of Lies. christmas lies will ferrell elf buddy the elf Share Pin Related\
  \ Entries 190 total Facepalm Deal With It Impossibru Math Lady / Confused Lady View\
  \ All Related Entries Recent Images 56 total View All Images Recent Videos 1 total\
  \ View All Videos Sign up for our Newsletter Load 37 Comments Comments 37 total\
  \ 47 You Sit On A Throne Of Lies 151,781 1 56 37 Part of a series on Reaction Images.\
  \ [View Related Entries] Updated Dec 15, 2024 at 07:07PM EST by LiterallyAustin.\
  \ Added Dec 14, 2013 at 09:04PM EST by Kung Fu Cthulhu. Like us on Facebook! Like\
  \ 1.8M Share Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view\
  \ the video gallery, or 'r' to view a random entry. Meme Status Confirmed Year 2005\
  \ Origin Elf (2003 Film) Tags christmas, lies, will ferrell, elf, buddy the elf\
  \ About \"You Sit On A Throne Of Lies\" is a memorable quote uttered by Buddy The\
  \ Elf (played by Will Ferrell), the protagonist of the 2003 holiday family-comedy\
  \ film Elf. On the web, the phrase is typically used to expose a lie or otherwise\
  \ misleading statement told by someone else. Origin In the film, Buddy is disturbed\
  \ to discover that a mall Santa Claus is actually just a man dressed in a costume.\
  \ Believing that the man is trying to impersonate the Santa Claus he knows, Buddy\
  \ reacts with disgust, whispering to the man \"you sit on a throne of lies\" (shown\
  \ below). On June 1st, 2005, YTMND user Cryokenetic submitted a picture of Buddy\
  \ paired with audio of the \"You sit on a throne of lies\" clip.[1][2] Within the\
  \ next eight years, the page received over 220,000 views, 170 comments and the audio\
  \ clip was subsequently used on over 30 similar YTMNDs.[3][4] Spread The phrase\
  \ saw little activity on the web until June 11th, 2011, when it was added to the\
  \ \"That Liar Lies\" page on the trope database website TV Tropes.[8] On May 14th,\
  \ 2012, Redditor wordsandstuffs submitted a post titled \"You float on a throne\
  \ of lies\" to the /r/funny[10] subreddit, highlighting an animated GIF of a cat\
  \ destroying a floating cat balloon (shown below, left). Prior to being archived,\
  \ the post gathered more than 13,000 up votes and 240 comments. On May 5th, 2013,\
  \ Redditor likwitsnake submitted a post titled \"You sit on a throne of lies\" to\
  \ the /r/funny[9] subreddit, featuring a photograph of the nutritional information\
  \ on a bottle of \"+Calcium\" Hershey's chocolate syrup with 0% calcium (shown below,\
  \ right). In the first seven months, the post gained over 14,800 up votes and 340\
  \ comments. Notable Examples Image macros featuring Buddy accompanied by the quote\
  \ as a caption have been created on Meme Generator has created templates for Buddy\
  \ The Elf, featuring macros containing the quote in question and several others\
  \ related to the character.[5][6][7] Search Interest External References [1] YTMND\
  \ \u2013 You Sit on a Throne of Lies! [2] YTMND \u2013 Site Profile. [3] YTMND \u2013\
  \ Asset Information. [4] YTMND \u2013 'Throne Of Lies' Search. [5] Meme Generator\
  \ \u2013 Throne Of Lies Elf. [6] Meme Generator \u2013 Buddy The Elf. [7] Pinterest\
  \ \u2013 'You Sit On A Throne Of Lies' Search. [8] TV Tropes \u2013 That Liar Lies.\
  \ [9] Reddit \u2013 You Sit On A Throne Of Lies. [10] Reddit \u2013 You Float On\
  \ A Throne Of Lies. Related Entries 190 total Facepalm Deal With It Impossibru Math\
  \ Lady / Confused Lady Are You A Wizard Confused Black Girl Brent Rambo Ah, I See\
  \ You're a Man of Culture As Well Computer Reaction Faces Awesome Face / Epic Smiley\
  \ Shocked Black Guy L.A. Noire \"Doubt\" / Press X To Doubt View All Related Entries\
  \ Recent Videos 1 total YouTube Poop: Aku sits on a t... You Sit On A Throne Of\
  \ Lies Uploaded by Christian Frates + Add a Video Recent Images 56 total You Sit\
  \ On A Throne Of Lies Uploaded by MageZ You Sit On A Throne Of Lies Uploaded by\
  \ FroJake You Sit On A Throne Of Lies Uploaded by Dormant Puffball You Sit On A\
  \ Throne Of Lies Uploaded by babyhenchy1 You Sit On A Throne Of Lies Uploaded by\
  \ Slapperfish You Sit On A Throne Of Lies Uploaded by Kung Fu Cthulhu You Sit On\
  \ A Throne Of Lies Uploaded by Don You Sit On A Throne Of Lies Uploaded by Don You\
  \ Sit On A Throne Of Lies Uploaded by Kung Fu Cthulhu You Sit On A Throne Of Lies\
  \ Uploaded by Kung Fu Cthulhu You Sit On A Throne Of Lies Uploaded by Kung Fu Cthulhu\
  \ You Sit On A Throne Of Lies Uploaded by Kung Fu Cthulhu + Add an Image View All\
  \ Images Sign up for our Newsletter Top Comments Delete Sensitive FluffBall Dec\
  \ 15, 2013 at 12:43AM EST +51 Reply Delete Sensitive Mr. Sparkle Dec 15, 2013 at\
  \ 12:19AM EST Wow, I forgot Elf came out 10 years ago\u2026 +27 Reply + Add a Comment\
  \ Comments (37) Display Comments Add a Comment Top Entries This Month Meme Saika\
  \ Kawakita Smile GIF Event Assassination of UnitedHealthcare CEO Person Luigi Mangione\
  \ UHC CEO Shooter Subculture The Ki Sisters Culture Pornography Site Whisper View\
  \ More Suggest a Change Edit History Entry Editors (7) Kung Fu Cthulhu Researcher\
  \ & Treasurer & Elocutionist & Media Bus Boy Don Administrator & Meme Daddy Molly\
  \ Horan Tumblr Historian Particle Mare Wolf of Meme Street Y F Digital Archaeologist\
  \ & Treasurer & Media Maid Rose Abrams Entry Moderator Brandon Brandy From The Blockchain\
  \ \u25BC + Request Editorship View All Editors Today's Top Image Galleries Assassination\
  \ of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing\
  \ Digital Circus About Our Story Site Rules Policies and Guidelines Credits Contact\
  \ Meme DB Memes Episodes News Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/you-sit-on-a-throne-of-lies
template_id: elf
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
