name: You Sit on a Throne of Lies
source: http://knowyourmeme.com/memes/you-sit-on-a-throne-of-lies
keywords:
- Elf
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- ''
- you sit on a throne of lies
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About "You Sit On A Throne Of Lies" is a memorable quote uttered
  by Buddy The Elf (played by Will Ferrell), the protagonist of the 2003 holiday family-comedy
  film Elf. On the web, the phrase is typically used to expose a lie or otherwise
  misleading statement told by someone else. Origin In the film, Buddy is disturbed
  to discover that a mall Santa Claus is actually just a man dressed in a costume.
  Believing that the man is trying to impersonate the Santa Claus he knows, Buddy
  reacts with disgust, whispering to the man "you sit on a throne of lies" (shown
  below). On June 1st, 2005, YTMND user Cryokenetic submitted a picture of Buddy paired
  with audio of the "You sit on a throne of lies" clip.[1][2] Within the next eight
  years, the page received over 220,000 views, 170 comments and the audio clip was
  subsequently used on over 30 similar YTMNDs.[3][4] Spread The phrase saw little
  activity on the web until June 11th, 2011, when it was added to the "That Liar Lies"
  page on the trope database website TV Tropes.[8] On May 14th, 2012, Redditor wordsandstuffs
  submitted a post titled "You float on a throne of lies" to the /r/funny[10] subreddit,
  highlighting an animated GIF of a cat destroying a floating cat balloon (shown below,
  left). Prior to being archived, the post gathered more than 13,000 up votes and
  240 comments. On May 5th, 2013, Redditor likwitsnake submitted a post titled "You
  sit on a throne of lies" to the /r/funny[9] subreddit, featuring a photograph of
  the nutritional information on a bottle of "+Calcium" Hershey's chocolate syrup
  with 0% calcium (shown below, right). In the first seven months, the post gained
  over 14,800 up votes and 340 comments. Notable Examples Image macros featuring Buddy
  accompanied by the quote as a caption have been created on Meme Generator has created
  templates for Buddy The Elf, featuring macros containing the quote in question and
  several others related to the character.[5][6][7] Search Interest External References
  [1] YTMND – You Sit on a Throne of Lies! [2] YTMND – Site Profile. [3] YTMND – Asset
  Information. [4] YTMND – 'Throne Of Lies' Search. [5] Meme Generator – Throne Of
  Lies Elf. [6] Meme Generator – Buddy The Elf. [7] Pinterest – 'You Sit On A Throne
  Of Lies' Search. [8] TV Tropes – That Liar Lies. [9] Reddit – You Sit On A Throne
  Of Lies. [10] Reddit – You Float On A Throne Of Lies.
aside_content: MemeStatusConfirmedYear2005OriginElf (2003 Film)Tagschristmas,lies,will
  ferrell,elf,buddy the elf
added_at: '2013-12-14T21:04:47-05:00'
