name: Leo Strutting
source: https://knowyourmeme.com/memes/strutting-leo
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- I have no idea
- what I am doing
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Strutting Leo is a photoshop meme featuring a photograph of
  the actor Leonardo DiCaprio walking merrily toward the camera while on the set of
  the 2010 science fiction film Inception. Examples of the meme typically superimpose
  DiCaprio''s cutout image into various humorous contexts, similar to the Disaster
  Girl and Prancing Cera exploitable series. Origin The original picture was taken
  on set during filming of the 2010 science fiction movie Inception. On August 19th,
  2009, the entertainment blog Celebrity-Gossip[14] published a post titled "Leonardo
  DiCaprio and Ellen Page: Filming in Paris", which featured the strutting image in
  an Inception photo gallery. Spread On August 28th, 2010, a forum thread titled "Photoshop
  Leonardo DiCaprio" was created on the flash animation website Newgrounds[13], which
  featured an exploitable template of the photo with a transparent background (shown
  below, left). On August 29th, Redditor WolfTweak submitted a post titled "Simple
  into Mordor" to the /r/pics[3] subreddit, highlighting a photoshopped image of DiCaprio
  strutting through scenes in the fantasy film series The Lord of the Rings (shown
  below, right). On August 31st, the "Fuck Yeah Strutting Leo" Tumblr[1] blog was
  launched. On the same day, the viral content site BuzzFeed[2] published a post titled
  "Strutting Leo", in which several users commented notable examples of the exploitable.
  On September 1st, the Internet humor site The Chive[6] published a compilation of
  notable examples from the series. On September 5th, Funny or Die[4] published a
  post titled "The 23 Funniest Strutting Pics", which received over 1.4 million views
  within two years. The same day, the single topic blog StruttingLeo.com[5] was launched.
  On September 7th, the Internet news site UpRoxx[9] published a post titled "Meme
  Watch: Strutting Leo", comparing the series to the Prancing Cera photoshop meme.
  On September 26th, YouTuber jkilaaa uploaded a music video titled "Jay Kila – Leo
  Strut (Official Video)", which featured animations of original DiCaprio photograph
  walking through various images accompanied by the rap song "Leo Strut." [This video
  has been removed] On October 4th, The Washington Post[15] published a blog post
  titled "Strutting Leo DiCaprio Meme Hits Warp Speed." The meme continued to spread
  on Memebase[16] and Tumblr[17] under the tag "#strutting leo." As of August 6th,
  2012, the "Strutting Leo" Facebook[7] page has accumulated over 9,200 likes. Various
  Examples Search Interest External References [1] Tumblr – Fuck yeah strutting Leo
  [2] BuzzFeed – Strutting Leo [3] Reddit – Simply strut into Mordor on [4] Funny
  or Die – The 23 Funniest Strutting Leo Pics [5] StruttingLeo.com – Strutting Leo
  [6] The Chive – Leo sutrtting gets the Photoshop treatment [7] Facebook – Strutting
  Leo [8] Washington Post – Strutting Leo DiCaprio meme hits warp speed [9] UpRoxx
  – Meme Watch – Strutting Leo [10] Funny or Die – The 23 Funniest Strutting Leo Pics
  [11] Tumblr – Strutting Leo [12] Memebase – #struttingleo [13] Newgrounds – Photoshop
  Leonardo DiCaprio [14] Celebrity-Gossip – Leonardo and Ellen Page – Filming in Paris
  [15] Washington Post – Strutting Leo DiCaprio meme hits warp speed [16] Memebase
  – #strutting leo [17] Tumblr – #strutting leo'
aside_content: MemeStatusConfirmedYear2010OriginNewgrounds.comTagsleonardo di caprio,strut,movie,napalm,3rd
  world country,nazis,incident,catastrophe,event,film,war,middle east,animals,actor,inception,happy,ìnception,photoshop
  meme,celebrity,exploitableAdditional ReferencesEncyclopedia Dramatica
added_at: '2010-08-28T17:33:34-04:00'
