example:
- can't get fired
- if you don't have a job
keywords:
- null
name: Roll Safe
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Roll Safe | Know Your Meme Yo Yo! You must login or signup first!\
  \ Already a memeber? Login Now! Don't have an account? Sign up Now! Meme Encyclopedia\
  \ All Cultures Events People Sites Subcultures Videos Submit \u2192 Images Trending\
  \ Most Commented Most Favorited High Score Low Score Most Viewed All Templates Upload\
  \ an Image Articles News Explainers Collections Interviews Meme Insider Magazine\
  \ More Discord Newsletter Episodes Forums Meme Store Login Abstract user icon Memes\
  \ Categories Trending News Images Trending Images Videos Trending Videos Editorials\
  \ Meme Insider Magazine Newsletter Policies and Guidelines Meme Store Old site Login\
  \ Know Your Meme is the property of Literally Media \xA92024 Literally Media. All\
  \ Rights Reserved. This image Of Woman Confidently Strolling Through A Glass Panel\
  \ Has Been A Redraw Format Since 2021 Three Years Ago, This Boar's Head 'Exploded'\
  \ Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess Memes Turns Two Years\
  \ Old Today Phrase 'The Fridge Protects The Snacks' A Growing Favorite Among Pickup\
  \ Artist Influencers Jamie G, The Bosh British Charva, Has Taken Over TikTok With\
  \ His Signature 'Oh Cherie Amour' Sound Also Trending: Honey Extension Influencer\
  \ Scam Renegade Raider Copypasta Assassination of UnitedHealthcare CEO Roll Safe\
  \ Added 7 years ago / Updated 12 days ago Confirmed 1,773,328 Part of a series on\
  \ Black Twitter. [View Related Entries] [View Related Sub-entries] View All 305\
  \ Images Navigation About \u2022 Origin \u2022 Spread \u2022 Various Examples \u2022\
  \ Search Interest \u2022 External References \u2022 Recent Images \u2022 Recent\
  \ Videos About Roll Safe is an image macro series featuring a screenshot of actor\
  \ Kayode Ewumi grinning and pointing to his temple while portraying the character\
  \ Reece Simpson (a.k.a. \"Roll Safe\") in the web series Hood Documentary. The images\
  \ are often captioned with various jokes mocking poor decision making and failures\
  \ in critical thinking. Origin On June 1st, 2016, the BBC Three YouTube channel\
  \ uploaded a mini-documentary on the Hood Documentary series, in which the Simpson\
  \ is shown pointing to his head and smiling after saying that he finds a woman \"\
  beautiful\" because \"she's got good brains,\" joking that she is skilled at performing\
  \ oral sex (shown below). Within eight months, the video gained over 1.04 million\
  \ views and 1,300 comments. Filmmaker: \"Oh, so you're attracted to intelligence,\
  \ RS?\" Reece Simpson: \"Yeah man, I think Rachel is beautiful because she's got\
  \ good brains.\" On November 15th, 2016, the @FootyHumor[1] Twitter feed posted\
  \ a screenshot of Ewumi pointing at his temple along with a joke about starting\
  \ a fight with a girlfriend in order to play video games (shown below). Spread On\
  \ January 22nd, 2017, Twitter user @trapafasa[2] posted the Roll Safe screenshot\
  \ along with a caption noting that \"'men are trash' tweets have gone down 70%\"\
  \ due to the approach of February (shown below, left). Within eight days, the tweet\
  \ gained over 18,000 retweets and 17,000 likes. The following day, Twitter user\
  \ @RyanWindoww[10] tweeted the image along with the message \"You can't be broke\
  \ if you don't check your bank account,\" receiving more than 74,000 likes and 47,000\
  \ retweets over the next week (shown below, right). The following day, Redditor\
  \ InformationSpork submitted a post asking about the meme to /r/OutOfTheLoop,[4]\
  \ where Redditor elfa82 cited the Hood Documentary series as the origin. On January\
  \ 28th, 2017, the @girlposts[5] Twitter feed posted the reaction image along with\
  \ the message \"you can't get cheated on if you don't get into a relationship,\"\
  \ gathering upwards of 14,000 likes and 3,700 retweets over the next four days (shown\
  \ below, left). On January 30th, Twitter user @Trillxdadian[6] submitted the Roll\
  \ Safe screenshot captioned with \"If you're already late.. take your time.. you\
  \ can't be late twice\" (shown below, right). Within 48 hours, the tweet garnered\
  \ more than 51,000 likes and 42,000 retweets. On February 1st, 2017, Redditor Dieselman25\
  \ submitted the screenshot of Ewumi in a post titled \"Roll Safe Memes on the Rise\
  \ Buy Immediately\" to /r/memeeconomy.[3] That day, Redditor SkipLoL submitted a\
  \ screenshot of @Trillxdadian's tweet to /r/BlackPeopleTwitter,[7] where it accumulated\
  \ over 7,700 points (96% upvoted) in less than 24 hours. Meanwhile, the news sites\
  \ HipHopWired[8] and Bossip[9] published articles about the image macro series.\
  \ Various Examples Search Interest External References [1] Twitter \u2013 @FootyHumor\
  \ [2] Twitter \u2013 @trapafasa [3] Reddit \u2013 Roll Safe Memes on the Rise Buy\
  \ Immediately [4] Reddit \u2013 New meme image going around [5] Twitter \u2013 @girlposts\
  \ [6] Twitter \u2013 @Trillxdadian [7] Reddit \u2013 hes not lying [8] HipHopWired\
  \ \u2013 Here Is The OG Video Behind Your Favorite Meme [9] Bossip \u2013 Meet The\
  \ New Hilariously Petty Meme Taking Over The Internet [10] Twitter \u2013 @RyanWindoww\
  \ image macro black twitter reaction thinking think smart be smart rollsafe it's\
  \ not if you logic public service announcement psa kayode ewumi reece simpson dieselman25\
  \ skiplol informationspork black guy thinking meme @trapafasa @footyhum Share Pin\
  \ Related Entries 44 total Conceited Reaction Black Guy on the Phone Daquan The\
  \ Barber View All Related Entries Sub-entries 1 total Back In The Day, Me And You\
  \ B... Recent Images 305 total View All Images Recent Videos 21 total View All Videos\
  \ Sign up for our Newsletter Load 31 Comments Comments 31 total 136 Roll Safe 1,773,332\
  \ 21 305 31 Part of a series on Black Twitter. [View Related Entries] [View Related\
  \ Sub-entries] Updated Dec 11, 2024 at 04:22PM EST by LiterallyAustin. Added Feb\
  \ 01, 2017 at 12:18PM EST by Don. Like us on Facebook! Like 1.8M Share Save Tweet\
  \ PROTIP: Press 'i' to view the image gallery, 'v' to view the video gallery, or\
  \ 'r' to view a random entry. Meme Status Confirmed Type: Reaction Year 2016 Origin\
  \ Twitter Tags image macro, black twitter, reaction, thinking, think smart, be smart,\
  \ rollsafe, it's not, if you, logic, public service announcement, psa, kayode ewumi,\
  \ reece simpson, dieselman25, skiplol, informationspork, black guy thinking meme,\
  \ @trapafasa, @footyhum Additional References Facebook IMDb Meme Generator Reddit\
  \ Twitter About Roll Safe is an image macro series featuring a screenshot of actor\
  \ Kayode Ewumi grinning and pointing to his temple while portraying the character\
  \ Reece Simpson (a.k.a. \"Roll Safe\") in the web series Hood Documentary. The images\
  \ are often captioned with various jokes mocking poor decision making and failures\
  \ in critical thinking. Origin On June 1st, 2016, the BBC Three YouTube channel\
  \ uploaded a mini-documentary on the Hood Documentary series, in which the Simpson\
  \ is shown pointing to his head and smiling after saying that he finds a woman \"\
  beautiful\" because \"she's got good brains,\" joking that she is skilled at performing\
  \ oral sex (shown below). Within eight months, the video gained over 1.04 million\
  \ views and 1,300 comments. Filmmaker: \"Oh, so you're attracted to intelligence,\
  \ RS?\" Reece Simpson: \"Yeah man, I think Rachel is beautiful because she's got\
  \ good brains.\" On November 15th, 2016, the @FootyHumor[1] Twitter feed posted\
  \ a screenshot of Ewumi pointing at his temple along with a joke about starting\
  \ a fight with a girlfriend in order to play video games (shown below). Spread On\
  \ January 22nd, 2017, Twitter user @trapafasa[2] posted the Roll Safe screenshot\
  \ along with a caption noting that \"'men are trash' tweets have gone down 70%\"\
  \ due to the approach of February (shown below, left). Within eight days, the tweet\
  \ gained over 18,000 retweets and 17,000 likes. The following day, Twitter user\
  \ @RyanWindoww[10] tweeted the image along with the message \"You can't be broke\
  \ if you don't check your bank account,\" receiving more than 74,000 likes and 47,000\
  \ retweets over the next week (shown below, right). The following day, Redditor\
  \ InformationSpork submitted a post asking about the meme to /r/OutOfTheLoop,[4]\
  \ where Redditor elfa82 cited the Hood Documentary series as the origin. On January\
  \ 28th, 2017, the @girlposts[5] Twitter feed posted the reaction image along with\
  \ the message \"you can't get cheated on if you don't get into a relationship,\"\
  \ gathering upwards of 14,000 likes and 3,700 retweets over the next four days (shown\
  \ below, left). On January 30th, Twitter user @Trillxdadian[6] submitted the Roll\
  \ Safe screenshot captioned with \"If you're already late.. take your time.. you\
  \ can't be late twice\" (shown below, right). Within 48 hours, the tweet garnered\
  \ more than 51,000 likes and 42,000 retweets. On February 1st, 2017, Redditor Dieselman25\
  \ submitted the screenshot of Ewumi in a post titled \"Roll Safe Memes on the Rise\
  \ Buy Immediately\" to /r/memeeconomy.[3] That day, Redditor SkipLoL submitted a\
  \ screenshot of @Trillxdadian's tweet to /r/BlackPeopleTwitter,[7] where it accumulated\
  \ over 7,700 points (96% upvoted) in less than 24 hours. Meanwhile, the news sites\
  \ HipHopWired[8] and Bossip[9] published articles about the image macro series.\
  \ Various Examples Search Interest External References [1] Twitter \u2013 @FootyHumor\
  \ [2] Twitter \u2013 @trapafasa [3] Reddit \u2013 Roll Safe Memes on the Rise Buy\
  \ Immediately [4] Reddit \u2013 New meme image going around [5] Twitter \u2013 @girlposts\
  \ [6] Twitter \u2013 @Trillxdadian [7] Reddit \u2013 hes not lying [8] HipHopWired\
  \ \u2013 Here Is The OG Video Behind Your Favorite Meme [9] Bossip \u2013 Meet The\
  \ New Hilariously Petty Meme Taking Over The Internet [10] Twitter \u2013 @RyanWindoww\
  \ Related Entries 44 total Conceited Reaction Black Guy on the Phone Daquan The\
  \ Barber Nutted But She Still Sucking Oh No Baby! What Is You Doin??? Nileseyy Niles\
  \ Disappears Delete This Nephew Turn Up the Volume Boo Boo the Fool Check Out My\
  \ Mixtape Deadass View All Related Entries Sub-entries 1 total Back In The Day,\
  \ Me And You Baby / That's Not My Son Recent Videos 21 total Roll Safe Dank Meme\
  \ Compilation Roll Safe Uploaded by andcallmeshirley Who is Roll Safe? The history...\
  \ Roll Safe Uploaded by andcallmeshirley #HoodDocumentary | Happy Belated Roll Safe\
  \ Uploaded by andcallmeshirley Roll Safe Thinking Meme ~ Bes... Roll Safe Uploaded\
  \ by Y F Roll Safe(Green Screen edit) Roll Safe Uploaded by Y F Roll Safe Memes!\
  \ Roll Safe Uploaded by Y F Roll Safe Meme Compilation 3 Roll Safe Uploaded by Y\
  \ F Roll Safe Meme Compilation 2 Roll Safe Uploaded by Y F + Add a Video View All\
  \ Videos Recent Images 305 total Roll Safe Uploaded by Reddit Moments Roll Safe\
  \ Uploaded by Fiftytwo144 Roll Safe Uploaded by Triplem Roll Safe Uploaded by Evilthing\
  \ Roll Safe Uploaded by Rebecca Rhodes Roll Safe Uploaded by nightqueen Roll Safe\
  \ Uploaded by Y F Roll Safe Uploaded by bastek66 Roll Safe Uploaded by Ally Dinning\
  \ Roll Safe Uploaded by Dry Ice Roll Safe Uploaded by B. M. S. Roll Safe Uploaded\
  \ by Bilbo Swaggins + Add an Image View All Images Sign up for our Newsletter Top\
  \ Comments Delete Sensitive Mr. Man Feb 01, 2017 at 04:46PM EST You cant shitpost\
  \ if you dont comment anything. +103 Reply Delete Sensitive Snickerway Feb 03, 2017\
  \ at 01:25PM EST Wright can't find contradictions in the testimony if I update the\
  \ autopsy report. +89 Reply + Add a Comment Comments (31) Display Comments Add a\
  \ Comment Top Entries This Month Meme Saika Kawakita Smile GIF Event Assassination\
  \ of UnitedHealthcare CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki\
  \ Sisters Culture Pornography Site Whisper View More Suggest a Change Edit History\
  \ Entry Editors (7) Don Administrator & Meme Daddy LNH Deactivated Brad Digital\
  \ Archaeologist & Treasurer & Pundit & Gallery Housekeeper Y F Digital Archaeologist\
  \ & Treasurer & Media Maid Sophie Digital Archaeologist & Treasurer & Media Bus\
  \ Boy Adam Know Your Meme Universal Champion andcallmeshirley Digital Archaeologist\
  \ & Treasurer & Collection Butler \u25BC + Request Editorship View All Editors Today's\
  \ Top Image Galleries Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen\
  \ Green) Team Fortress 2 The Amazing Digital Circus About Our Story Site Rules Policies\
  \ and Guidelines Credits Contact Meme DB Memes Episodes News Staff Contact Extras!\
  \ Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/roll-safe
template_id: rollsafe
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
