name: Roll Safe
source: http://knowyourmeme.com/memes/roll-safe
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- can't get fired
- if you don't have a job
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Roll Safe is an image macro series featuring a screenshot
  of actor Kayode Ewumi grinning and pointing to his temple while portraying the character
  Reece Simpson (a.k.a. "Roll Safe") in the web series Hood Documentary. The images
  are often captioned with various jokes mocking poor decision making and failures
  in critical thinking. Origin On June 1st, 2016, the BBC Three YouTube channel uploaded
  a mini-documentary on the Hood Documentary series, in which the Simpson is shown
  pointing to his head and smiling after saying that he finds a woman "beautiful"
  because "she''s got good brains," joking that she is skilled at performing oral
  sex (shown below). Within eight months, the video gained over 1.04 million views
  and 1,300 comments. Filmmaker: "Oh, so you''re attracted to intelligence, RS?" Reece
  Simpson: "Yeah man, I think Rachel is beautiful because she''s got good brains."
  On November 15th, 2016, the @FootyHumor[1] Twitter feed posted a screenshot of Ewumi
  pointing at his temple along with a joke about starting a fight with a girlfriend
  in order to play video games (shown below). Spread On January 22nd, 2017, Twitter
  user @trapafasa[2] posted the Roll Safe screenshot along with a caption noting that
  "''men are trash'' tweets have gone down 70%" due to the approach of February (shown
  below, left). Within eight days, the tweet gained over 18,000 retweets and 17,000
  likes. The following day, Twitter user @RyanWindoww[10] tweeted the image along
  with the message "You can''t be broke if you don''t check your bank account," receiving
  more than 74,000 likes and 47,000 retweets over the next week (shown below, right).
  The following day, Redditor InformationSpork submitted a post asking about the meme
  to /r/OutOfTheLoop,[4] where Redditor elfa82 cited the Hood Documentary series as
  the origin. On January 28th, 2017, the @girlposts[5] Twitter feed posted the reaction
  image along with the message "you can''t get cheated on if you don''t get into a
  relationship," gathering upwards of 14,000 likes and 3,700 retweets over the next
  four days (shown below, left). On January 30th, Twitter user @Trillxdadian[6] submitted
  the Roll Safe screenshot captioned with "If you''re already late.. take your time..
  you can''t be late twice" (shown below, right). Within 48 hours, the tweet garnered
  more than 51,000 likes and 42,000 retweets. On February 1st, 2017, Redditor Dieselman25
  submitted the screenshot of Ewumi in a post titled "Roll Safe Memes on the Rise
  Buy Immediately" to /r/memeeconomy.[3] That day, Redditor SkipLoL submitted a screenshot
  of @Trillxdadian''s tweet to /r/BlackPeopleTwitter,[7] where it accumulated over
  7,700 points (96% upvoted) in less than 24 hours. Meanwhile, the news sites HipHopWired[8]
  and Bossip[9] published articles about the image macro series. Various Examples
  Search Interest External References [1] Twitter – @FootyHumor [2] Twitter – @trapafasa
  [3] Reddit – Roll Safe Memes on the Rise Buy Immediately [4] Reddit – New meme image
  going around [5] Twitter – @girlposts [6] Twitter – @Trillxdadian [7] Reddit – hes
  not lying [8] HipHopWired – Here Is The OG Video Behind Your Favorite Meme [9] Bossip
  – Meet The New Hilariously Petty Meme Taking Over The Internet [10] Twitter – @RyanWindoww'
aside_content: MemeStatusConfirmedType:ReactionYear2016OriginTwitterTagsimage macro,black
  twitter,reaction,thinking,think smart,be smart,rollsafe,it's not,if you,logic,public
  service announcement,psa,kayode ewumi,reece simpson,dieselman25,skiplol,informationspork,black
  guy thinking meme,@trapafasa,@footyhumAdditional ReferencesFacebookIMDbMeme GeneratorRedditTwitter
added_at: '2017-02-01T12:18:47-05:00'
