name: Winter is coming
source: http://knowyourmeme.com/memes/imminent-ned-brace-yourselves-winter-is-coming
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- prepare yourself
- winter is coming
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Brace Yourselves, Winter is Coming, also known as Imminent
  Ned, is an image macro meme featuring the character Eddard "Ned" Stark (played by
  actor Sean Bean) from the HBO series Game of Thrones, a television adaption of George
  R. R. Martin''s epic fantasy novel series A Song of Ice and Fire. Its phrasal template
  "Brace Yourselves, X is Coming" can be versatilely used to forewarn or proclaim
  the impending arrival of a highly anticipated event, a product or an internet meme.
  Origin In George R. R. Martin''s A Song of Ice and Fire, the phrase "winter is coming"
  is prominently featured as the motto of House Stark of Winterfell, a noble clan
  renowned for its fortified ancient castle. It was also used in the HBO series Game
  of Thrones as the title of the pilot episode, which aired on April 17th, 2011, as
  well as for several promotional trailers and posters. An image macro featuring a
  photo of an owl and the phrase "winter is coming" (shown below, left) was submitted
  to Quickmeme[1] in July 2011, but the phrase didn''t take off until it was paired
  with an HBO promotional portrait of Ned Stark (played by Sean Bean) later in August
  that year. The earliest known instance using this image (shown below, right) surfaced
  shortly after the U.S. East Coast earthquake on August 23rd, 2011. Spread Throughout
  2011, Game of Thrones continued to climb in viewership and ratings and so did the
  prevalence of the image macro series on Reddit, where the subreddit[7] for the show
  had gained a large following of 20,128 subscribers by early October 2011. On Quickmeme,
  numerous entries dedicated to the series emerged in August 2011, most notably Imminent
  Ned[2], Winter is Coming and Ned Star Winter[3] is Coming. Outside of Reddit, there
  is a fan site for the TV series under the domain WinterIsComing.net and similar
  image macros can be found on Memebase[6] under the tag "Winter is Coming" and Tumblr[4]
  under the tag "Imminent Ned." Trump "Sanctions Are Coming" Tweet On November 2nd,
  2018, Donald Trump tweeted an image of himself with the words "Sanctions are coming"
  in the Game of Thrones logo superimposed over him (shown below). The "sanctions"
  in question are supposed to be against Iran, as the White House Twitter account
  qualified, "President @realDonaldTrump is reimposing all sanctions lifted under
  the unacceptable Iran deal. The U.S. is reimposing the toughest sanctions ever on
  Iran, targeting many of the corrupt regime’s critical sectors."[9] Reactions to
  the tweet ranged from confusion to mockery. Many who saw it were unaware of what
  Trump was referencing. User @swin24 tweeted "Against who/what?" (shown below, left).
  User @ditzkoff tweeted "I''m starting to question whether we are a grown-up, adult
  country," gaining over 190 retweets and 1,400 likes (shown below, right). Reactions
  to the tweet were covered by Daily Dot.[10] Various Examples As of June 2012, there
  are more than 1470 posts related to the phrase on Reddit[5], nearly 20,000 aggregated
  instances on Quickmeme and at least 1,330 likes on Facebook.[8] Templates Search
  Search queries for "winter is coming" saw a brief spike in April of 2011, coinciding
  with the premiere episode of HBO''s Game of Thrones. External Reference [1] Quickmeme
  – Winter is Coming [2] Quickmeme – Imminent Ned [3] Quickmeme – Ned Star Winter
  is coming [4] Tumblr – #imminent ned [5] Reddit – imminent ned [6] Memebase – winter
  is coming [7] Reddit – /r/gameofthrones [8] Facebook – Winter is Coming [9] Twitter
  – White House [10] Daily Dot – Trump ruins ‘Game of Thrones’ with meme threatening
  sanctions on Iran'
aside_content: MemeStatusConfirmedType:Image Macro,Pop Culture Reference,SnowcloneYear2011OriginRedditRegionUnited
  StatesTagsgame of thrones,ned stark,brace yourself,blacklist,snowclone,winter is
  coming meme,imminent ned meme,sean bean,got,image macros,phrasal templates
added_at: '2011-10-02T20:02:25-04:00'
