example:
- prepare yourself
- winter is coming
keywords:
- null
name: Winter is coming
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Brace Yourselves, Winter is Coming | Know Your Meme Hi! You must\
  \ login or signup first! Already a memeber? Login Now! Don't have an account? Sign\
  \ up Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos\
  \ Submit \u2192 Images Trending Most Commented Most Favorited High Score Low Score\
  \ Most Viewed All Templates Upload an Image Articles News Explainers Collections\
  \ Interviews Meme Insider Magazine More Discord Newsletter Episodes Forums Meme\
  \ Store Login Abstract user icon Memes Categories Trending News Images Trending\
  \ Images Videos Trending Videos Editorials Meme Insider Magazine Newsletter Policies\
  \ and Guidelines Meme Store Old site Login Know Your Meme is the property of Literally\
  \ Media \xA92024 Literally Media. All Rights Reserved. This image Of Woman Confidently\
  \ Strolling Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years\
  \ Ago, This Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The\
  \ Anarchy Chess Memes Turns Two Years Old Today Phrase 'The Fridge Protects The\
  \ Snacks' A Growing Favorite Among Pickup Artist Influencers Jamie G, The Bosh British\
  \ Charva, Has Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also\
  \ Trending: Honey Extension Influencer Scam Renegade Raider Copypasta Assassination\
  \ of UnitedHealthcare CEO Brace Yourselves, Winter is Coming Added 13 years ago\
  \ / Updated about 17 hours ago Confirmed 776,447 Part of a series on Game of Thrones.\
  \ [View Related Entries] Related Explainer: What Does 'Winter Is Coming' Mean? The\
  \ Viral 'Game Of Thrones' Meme From Ned Stark Explained View All 178 Images Navigation\
  \ About \u2022 Origin \u2022 Spread \u2022 Various Examples \u2022 Templates \u2022\
  \ Search \u2022 External Reference \u2022 Recent Images \u2022 Recent Videos About\
  \ Brace Yourselves, Winter is Coming, also known as Imminent Ned, is an image macro\
  \ meme featuring the character Eddard \"Ned\" Stark (played by actor Sean Bean)\
  \ from the HBO series Game of Thrones, a television adaption of George R. R. Martin's\
  \ epic fantasy novel series A Song of Ice and Fire. Its phrasal template \"Brace\
  \ Yourselves, X is Coming\" can be versatilely used to forewarn or proclaim the\
  \ impending arrival of a highly anticipated event, a product or an internet meme.\
  \ Origin In George R. R. Martin's A Song of Ice and Fire, the phrase \"winter is\
  \ coming\" is prominently featured as the motto of House Stark of Winterfell, a\
  \ noble clan renowned for its fortified ancient castle. It was also used in the\
  \ HBO series Game of Thrones as the title of the pilot episode, which aired on April\
  \ 17th, 2011, as well as for several promotional trailers and posters. An image\
  \ macro featuring a photo of an owl and the phrase \"winter is coming\" (shown below,\
  \ left) was submitted to Quickmeme[1] in July 2011, but the phrase didn't take off\
  \ until it was paired with an HBO promotional portrait of Ned Stark (played by Sean\
  \ Bean) later in August that year. The earliest known instance using this image\
  \ (shown below, right) surfaced shortly after the U.S. East Coast earthquake on\
  \ August 23rd, 2011. Spread Throughout 2011, Game of Thrones continued to climb\
  \ in viewership and ratings and so did the prevalence of the image macro series\
  \ on Reddit, where the subreddit[7] for the show had gained a large following of\
  \ 20,128 subscribers by early October 2011. On Quickmeme, numerous entries dedicated\
  \ to the series emerged in August 2011, most notably Imminent Ned[2], Winter is\
  \ Coming and Ned Star Winter[3] is Coming. Outside of Reddit, there is a fan site\
  \ for the TV series under the domain WinterIsComing.net and similar image macros\
  \ can be found on Memebase[6] under the tag \"Winter is Coming\" and Tumblr[4] under\
  \ the tag \"Imminent Ned.\" Trump \"Sanctions Are Coming\" Tweet On November 2nd,\
  \ 2018, Donald Trump tweeted an image of himself with the words \"Sanctions are\
  \ coming\" in the Game of Thrones logo superimposed over him (shown below). The\
  \ \"sanctions\" in question are supposed to be against Iran, as the White House\
  \ Twitter account qualified, \"President @realDonaldTrump is reimposing all sanctions\
  \ lifted under the unacceptable Iran deal. The U.S. is reimposing the toughest sanctions\
  \ ever on Iran, targeting many of the corrupt regime\u2019s critical sectors.\"\
  [9] Reactions to the tweet ranged from confusion to mockery. Many who saw it were\
  \ unaware of what Trump was referencing. User @swin24 tweeted \"Against who/what?\"\
  \ (shown below, left). User @ditzkoff tweeted \"I'm starting to question whether\
  \ we are a grown-up, adult country,\" gaining over 190 retweets and 1,400 likes\
  \ (shown below, right). Reactions to the tweet were covered by Daily Dot.[10] Various\
  \ Examples As of June 2012, there are more than 1470 posts related to the phrase\
  \ on Reddit[5], nearly 20,000 aggregated instances on Quickmeme and at least 1,330\
  \ likes on Facebook.[8] Templates Search Search queries for \"winter is coming\"\
  \ saw a brief spike in April of 2011, coinciding with the premiere episode of HBO's\
  \ Game of Thrones. External Reference [1] Quickmeme \u2013 Winter is Coming [2]\
  \ Quickmeme \u2013 Imminent Ned [3] Quickmeme \u2013 Ned Star Winter is coming [4]\
  \ Tumblr \u2013 #imminent ned [5] Reddit \u2013 imminent ned [6] Memebase \u2013\
  \ winter is coming [7] Reddit \u2013 /r/gameofthrones [8] Facebook \u2013 Winter\
  \ is Coming [9] Twitter \u2013 White House [10] Daily Dot \u2013 Trump ruins \u2018\
  Game of Thrones\u2019 with meme threatening sanctions on Iran game of thrones ned\
  \ stark brace yourself blacklist snowclone winter is coming meme imminent ned meme\
  \ sean bean got image macros phrasal templates Share Pin Related Entries 50 total\
  \ You Know Nothing, Jon Snow Cleganebowl R+L=J Stannis the Mannis View All Related\
  \ Entries Recent Images 178 total View All Images Recent Videos 3 total View All\
  \ Videos Sign up for our Newsletter Load 49 Comments Comments 49 total 61 Brace\
  \ Yourselves, Winter is Coming 776,447 3 178 49 Part of a series on Game of Thrones.\
  \ [View Related Entries] Updated Dec 23, 2024 at 04:11PM EST by LiterallyAustin.\
  \ Added Oct 02, 2011 at 08:02PM EDT by Zipodybop. Like us on Facebook! Like 1.8M\
  \ Share Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the\
  \ video gallery, or 'r' to view a random entry. Related Explainer: What Does 'Winter\
  \ Is Coming' Mean? The Viral 'Game Of Thrones' Meme From Ned Stark Explained Meme\
  \ Status Confirmed Type: Image Macro, Pop Culture Reference, Snowclone Year 2011\
  \ Origin Reddit Region United States Tags game of thrones, ned stark, brace yourself,\
  \ blacklist, snowclone, winter is coming meme, imminent ned meme, sean bean, got,\
  \ image macros, phrasal templates About Brace Yourselves, Winter is Coming, also\
  \ known as Imminent Ned, is an image macro meme featuring the character Eddard \"\
  Ned\" Stark (played by actor Sean Bean) from the HBO series Game of Thrones, a television\
  \ adaption of George R. R. Martin's epic fantasy novel series A Song of Ice and\
  \ Fire. Its phrasal template \"Brace Yourselves, X is Coming\" can be versatilely\
  \ used to forewarn or proclaim the impending arrival of a highly anticipated event,\
  \ a product or an internet meme. Origin In George R. R. Martin's A Song of Ice and\
  \ Fire, the phrase \"winter is coming\" is prominently featured as the motto of\
  \ House Stark of Winterfell, a noble clan renowned for its fortified ancient castle.\
  \ It was also used in the HBO series Game of Thrones as the title of the pilot episode,\
  \ which aired on April 17th, 2011, as well as for several promotional trailers and\
  \ posters. An image macro featuring a photo of an owl and the phrase \"winter is\
  \ coming\" (shown below, left) was submitted to Quickmeme[1] in July 2011, but the\
  \ phrase didn't take off until it was paired with an HBO promotional portrait of\
  \ Ned Stark (played by Sean Bean) later in August that year. The earliest known\
  \ instance using this image (shown below, right) surfaced shortly after the U.S.\
  \ East Coast earthquake on August 23rd, 2011. Spread Throughout 2011, Game of Thrones\
  \ continued to climb in viewership and ratings and so did the prevalence of the\
  \ image macro series on Reddit, where the subreddit[7] for the show had gained a\
  \ large following of 20,128 subscribers by early October 2011. On Quickmeme, numerous\
  \ entries dedicated to the series emerged in August 2011, most notably Imminent\
  \ Ned[2], Winter is Coming and Ned Star Winter[3] is Coming. Outside of Reddit,\
  \ there is a fan site for the TV series under the domain WinterIsComing.net and\
  \ similar image macros can be found on Memebase[6] under the tag \"Winter is Coming\"\
  \ and Tumblr[4] under the tag \"Imminent Ned.\" Trump \"Sanctions Are Coming\" Tweet\
  \ On November 2nd, 2018, Donald Trump tweeted an image of himself with the words\
  \ \"Sanctions are coming\" in the Game of Thrones logo superimposed over him (shown\
  \ below). The \"sanctions\" in question are supposed to be against Iran, as the\
  \ White House Twitter account qualified, \"President @realDonaldTrump is reimposing\
  \ all sanctions lifted under the unacceptable Iran deal. The U.S. is reimposing\
  \ the toughest sanctions ever on Iran, targeting many of the corrupt regime\u2019\
  s critical sectors.\"[9] Reactions to the tweet ranged from confusion to mockery.\
  \ Many who saw it were unaware of what Trump was referencing. User @swin24 tweeted\
  \ \"Against who/what?\" (shown below, left). User @ditzkoff tweeted \"I'm starting\
  \ to question whether we are a grown-up, adult country,\" gaining over 190 retweets\
  \ and 1,400 likes (shown below, right). Reactions to the tweet were covered by Daily\
  \ Dot.[10] Various Examples As of June 2012, there are more than 1470 posts related\
  \ to the phrase on Reddit[5], nearly 20,000 aggregated instances on Quickmeme and\
  \ at least 1,330 likes on Facebook.[8] Templates Search Search queries for \"winter\
  \ is coming\" saw a brief spike in April of 2011, coinciding with the premiere episode\
  \ of HBO's Game of Thrones. External Reference [1] Quickmeme \u2013 Winter is Coming\
  \ [2] Quickmeme \u2013 Imminent Ned [3] Quickmeme \u2013 Ned Star Winter is coming\
  \ [4] Tumblr \u2013 #imminent ned [5] Reddit \u2013 imminent ned [6] Memebase \u2013\
  \ winter is coming [7] Reddit \u2013 /r/gameofthrones [8] Facebook \u2013 Winter\
  \ is Coming [9] Twitter \u2013 White House [10] Daily Dot \u2013 Trump ruins \u2018\
  Game of Thrones\u2019 with meme threatening sanctions on Iran Related Entries 50\
  \ total You Know Nothing, Jon Snow Cleganebowl R+L=J Stannis the Mannis Hodor Hold\
  \ The Door Dany Kind of Forgot About the Iron Fleet Atheist Arya \"Tell Cersei.\
  \ I Want Her to Know It Was Me\" Boarposting / Bobbyposting My Name Is Reek Sandor\
  \ Clegane Loves Chicken View All Related Entries Recent Videos 3 total Winter is\
  \ Coming forecast Brace Yourselves, Winter is C... Uploaded by Roxsor Bread & Milk\
  \ Brace Yourselves, Winter is C... Uploaded by Brad Yogpod Animations - 15 - \"\
  Win... Brace Yourselves, Winter is C... Uploaded by Codeevee + Add a Video Recent\
  \ Images 178 total Brace Yourselves, Winter is C... Uploaded by andcallmeshirley\
  \ Brace Yourselves, Winter is C... Uploaded by Y F Brace Yourselves, Winter is C...\
  \ Uploaded by Y F Brace Yourselves, Winter is C... Uploaded by TalO Brace Yourselves,\
  \ Winter is C... Uploaded by Adam Brace Yourselves, Winter is C... Uploaded by Adam\
  \ Brace Yourselves, Winter is C... Uploaded by Adam Brace Yourselves, Winter is\
  \ C... Uploaded by Memister Brace Yourselves, Winter is C... Uploaded by Y F Brace\
  \ Yourselves, Winter is C... Uploaded by Political_LOL_center Brace Yourselves,\
  \ Winter is C... Uploaded by Rakashin Brace Yourselves, Winter is C... Uploaded\
  \ by Michael Moore + Add an Image View All Images Sign up for our Newsletter Top\
  \ Comments Delete Sensitive Natsuru Springfield Moderator Jun 05, 2012 at 05:55PM\
  \ EDT One does not simply brace themselves for Mordor. +35 Reply Delete Sensitive\
  \ Strid Nov 02, 2018 at 09:25PM EDT +30 Reply + Add a Comment Comments (49) Display\
  \ Comments Add a Comment Top Entries This Month Meme Saika Kawakita Smile GIF Event\
  \ Assassination of UnitedHealthcare CEO Person Luigi Mangione UHC CEO Shooter Subculture\
  \ The Ki Sisters Culture Pornography Site Whisper View More Suggest a Change Edit\
  \ History Entry Editors (10) Zipodybop Mr Bumhole #1 Fan Of Osaka Hamsteak #1 &\
  \ Television Meme Historian Laser Pacer Sleuth & Cataloger & Pundit Don Administrator\
  \ & Meme Daddy Brad Digital Archaeologist & Treasurer & Pundit & Gallery Housekeeper\
  \ MScratch Database Moderator & Historical Meme Historian & \u300CStand User\u300D\
  \ SabrinaTibbetts Memepuff Y F Digital Archaeologist & Treasurer & Media Maid Adam\
  \ Know Your Meme Universal Champion Zach Memenator \u25BC + Request Editorship View\
  \ All Editors Today's Top Image Galleries Assassination of UnitedHealthcare CEO\
  \ Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing Digital Circus About\
  \ Our Story Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes\
  \ News Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/imminent-ned-brace-yourselves-winter-is-coming
template_id: winter
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
