name: Change My Mind
source: https://knowyourmeme.com/memes/steven-crowders-change-my-mind-campus-sign
keywords:
- null
text:
- style: upper
  color: black
  font: thin
  anchor_x: 0.33
  anchor_y: 0.33
  angle: 23.0
  scale_x: 0.46
  scale_y: 0.25
  align: center
  start: 0.0
  stop: 1.0
example:
- pineapples don't belong on pizza
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Steven Crowder''s "Change My Mind" Campus Sign is a photograph
  of American-Canadian conservative podcaster Steven Crowder seated behind a sign
  that reads "Male Privilege is a myth / Change My Mind" outside of Texas Christian
  University. Since its upload via Crowder''s Twitter account in February 2018, the
  photograph has been turned into an exploitable template for online parodies. Origin
  On February 16th, 2018, comedian Steven Crowder tweeted[1] a picture of himself
  seated behind a sign that reads "Male privilege is a myth / Change my mind" and
  the caption, "Hello @TCU. Come one come all. #ChangeMyMind." The picture is part
  of Crowder''s podcast and YouTube in which he attempts to have people with opposing
  viewpoints convince him of various issues. The post (shown below) received more
  than 900 retweets and 6,400 likes in four days. Spread Shortly after Crowder posted
  the image, on February 18th, people began photoshopping different images on to the
  photograph. Twitter[2] user @Whatchamccaulit replaced Crowder''s head with Crying
  Michael Jordan (shown below, left). Twitter[3] user @IanWhetstone tweeted the image
  with the sign changed to read "The clitoris is a myth / Change my mind" (shown below,
  center). On February 19th, Twitter[4] user @RealishKyle tweeted the image with the
  sign photoshopped to read "Gonna drink this mug of Hot Piss / Change my mind." The
  post (shown below, right) received more than 200 retweets and 1,500 likes. That
  day, Redditors on the /r/dankmemes subreddit began posting photoshops of the image.
  Redditor[5] xereeto posted a version that reads "Traps are not gay / Change my mind."
  The post (shown below) received more than 5,000 points (98% upvoted) and 120 comments
  in 24 hours. Various Examples Search Interest Not Available. External References
  [1] Twitter – @scrowder''s Tweet [2] Twitter – @Whatchamccaulit''s Tweet [3] Twitter
  – @IanWhetstone''s Tweet [4] Twitter – @RealishKyle''s Tweet [5] Reddit – Traps
  are not gay'
aside_content: MemeStatusConfirmedType:ExploitableYear2018OriginTwitterRegionUnited
  StatesTagsmale privilege,myth,conservative,louder with crowder,steven crowder,whatchamccaulit,realishkyle,ianwhetstone,xereeto,change
  my mind memeAdditional ReferencesMeme GeneratorWikipedia
added_at: '2018-02-20T14:12:18-05:00'
