example:
- pineapples don't belong on pizza
keywords:
- null
name: Change My Mind
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Steven Crowder's \"Change My Mind\" Campus Sign | Know Your Meme\
  \ Sup! You must login or signup first! Already a memeber? Login Now! Don't have\
  \ an account? Sign up Now! Meme Encyclopedia All Cultures Events People Sites Subcultures\
  \ Videos Submit \u2192 Images Trending Most Commented Most Favorited High Score\
  \ Low Score Most Viewed All Templates Upload an Image Articles News Explainers Collections\
  \ Interviews Meme Insider Magazine More Discord Newsletter Episodes Forums Meme\
  \ Store Login Abstract user icon Memes Categories Trending News Images Trending\
  \ Images Videos Trending Videos Editorials Meme Insider Magazine Newsletter Policies\
  \ and Guidelines Meme Store Old site Login Know Your Meme is the property of Literally\
  \ Media \xA92024 Literally Media. All Rights Reserved. This image Of Woman Confidently\
  \ Strolling Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years\
  \ Ago, This Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The\
  \ Anarchy Chess Memes Turns Two Years Old Today Phrase 'The Fridge Protects The\
  \ Snacks' A Growing Favorite Among Pickup Artist Influencers Jamie G, The Bosh British\
  \ Charva, Has Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also\
  \ Trending: Honey Extension Influencer Scam Renegade Raider Copypasta Assassination\
  \ of UnitedHealthcare CEO Steven Crowder's \"Change My Mind\" Campus Sign Added\
  \ 6 years ago / Updated about a month ago Confirmed 1,346,916 Part of a series on\
  \ Steven Crowder. [View Related Entries] Related Explainer: What Is The 'Change\
  \ My Mind' Meme? Steven Crowder's Rise To Meme Fame And His Recent Divorce Controversies\
  \ Explained View All 361 Images Navigation About \u2022 Origin \u2022 Spread \u2022\
  \ Various Examples \u2022 Search Interest \u2022 External References \u2022 Recent\
  \ Images \u2022 Recent Videos About Steven Crowder's \"Change My Mind\" Campus Sign\
  \ is a photograph of American-Canadian conservative podcaster Steven Crowder seated\
  \ behind a sign that reads \"Male Privilege is a myth / Change My Mind\" outside\
  \ of Texas Christian University. Since its upload via Crowder's Twitter account\
  \ in February 2018, the photograph has been turned into an exploitable template\
  \ for online parodies. Origin On February 16th, 2018, comedian Steven Crowder tweeted[1]\
  \ a picture of himself seated behind a sign that reads \"Male privilege is a myth\
  \ / Change my mind\" and the caption, \"Hello @TCU. Come one come all. #ChangeMyMind.\"\
  \ The picture is part of Crowder's podcast and YouTube in which he attempts to have\
  \ people with opposing viewpoints convince him of various issues. The post (shown\
  \ below) received more than 900 retweets and 6,400 likes in four days. Spread Shortly\
  \ after Crowder posted the image, on February 18th, people began photoshopping different\
  \ images on to the photograph. Twitter[2] user @Whatchamccaulit replaced Crowder's\
  \ head with Crying Michael Jordan (shown below, left). Twitter[3] user @IanWhetstone\
  \ tweeted the image with the sign changed to read \"The clitoris is a myth / Change\
  \ my mind\" (shown below, center). On February 19th, Twitter[4] user @RealishKyle\
  \ tweeted the image with the sign photoshopped to read \"Gonna drink this mug of\
  \ Hot Piss / Change my mind.\" The post (shown below, right) received more than\
  \ 200 retweets and 1,500 likes. That day, Redditors on the /r/dankmemes subreddit\
  \ began posting photoshops of the image. Redditor[5] xereeto posted a version that\
  \ reads \"Traps are not gay / Change my mind.\" The post (shown below) received\
  \ more than 5,000 points (98% upvoted) and 120 comments in 24 hours. Various Examples\
  \ Search Interest Not Available. External References [1] Twitter \u2013 @scrowder's\
  \ Tweet [2] Twitter \u2013 @Whatchamccaulit's Tweet [3] Twitter \u2013 @IanWhetstone's\
  \ Tweet [4] Twitter \u2013 @RealishKyle's Tweet [5] Reddit \u2013 Traps are not\
  \ gay male privilege myth conservative louder with crowder steven crowder whatchamccaulit\
  \ realishkyle ianwhetstone xereeto change my mind meme Share Pin Related Entries\
  \ 1 total Steven Crowder's Divorce Recent Images 361 total View All Images Recent\
  \ Videos 21 total View All Videos Sign up for our Newsletter Load 92 Comments Comments\
  \ 92 total 56 Steven Crowder's \"Change My Mind\" Campus Sign 1,346,919 21 361 92\
  \ Part of a series on Steven Crowder. [View Related Entries] Updated Nov 13, 2024\
  \ at 10:24AM EST by Zach. Added Feb 20, 2018 at 02:12PM EST by Matt. Like us on\
  \ Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the image gallery,\
  \ 'v' to view the video gallery, or 'r' to view a random entry. Related Explainer:\
  \ What Is The 'Change My Mind' Meme? Steven Crowder's Rise To Meme Fame And His\
  \ Recent Divorce Controversies Explained Meme Status Confirmed Type: Exploitable\
  \ Year 2018 Origin Twitter Region United States Tags male privilege, myth, conservative,\
  \ louder with crowder, steven crowder, whatchamccaulit, realishkyle, ianwhetstone,\
  \ xereeto, change my mind meme Additional References Meme Generator Wikipedia About\
  \ Steven Crowder's \"Change My Mind\" Campus Sign is a photograph of American-Canadian\
  \ conservative podcaster Steven Crowder seated behind a sign that reads \"Male Privilege\
  \ is a myth / Change My Mind\" outside of Texas Christian University. Since its\
  \ upload via Crowder's Twitter account in February 2018, the photograph has been\
  \ turned into an exploitable template for online parodies. Origin On February 16th,\
  \ 2018, comedian Steven Crowder tweeted[1] a picture of himself seated behind a\
  \ sign that reads \"Male privilege is a myth / Change my mind\" and the caption,\
  \ \"Hello @TCU. Come one come all. #ChangeMyMind.\" The picture is part of Crowder's\
  \ podcast and YouTube in which he attempts to have people with opposing viewpoints\
  \ convince him of various issues. The post (shown below) received more than 900\
  \ retweets and 6,400 likes in four days. Spread Shortly after Crowder posted the\
  \ image, on February 18th, people began photoshopping different images on to the\
  \ photograph. Twitter[2] user @Whatchamccaulit replaced Crowder's head with Crying\
  \ Michael Jordan (shown below, left). Twitter[3] user @IanWhetstone tweeted the\
  \ image with the sign changed to read \"The clitoris is a myth / Change my mind\"\
  \ (shown below, center). On February 19th, Twitter[4] user @RealishKyle tweeted\
  \ the image with the sign photoshopped to read \"Gonna drink this mug of Hot Piss\
  \ / Change my mind.\" The post (shown below, right) received more than 200 retweets\
  \ and 1,500 likes. That day, Redditors on the /r/dankmemes subreddit began posting\
  \ photoshops of the image. Redditor[5] xereeto posted a version that reads \"Traps\
  \ are not gay / Change my mind.\" The post (shown below) received more than 5,000\
  \ points (98% upvoted) and 120 comments in 24 hours. Various Examples Search Interest\
  \ Not Available. External References [1] Twitter \u2013 @scrowder's Tweet [2] Twitter\
  \ \u2013 @Whatchamccaulit's Tweet [3] Twitter \u2013 @IanWhetstone's Tweet [4] Twitter\
  \ \u2013 @RealishKyle's Tweet [5] Reddit \u2013 Traps are not gay Related Entries\
  \ 1 total Steven Crowder's Divorce Recent Videos 21 total Change My Mind: origin/compil...\
  \ Steven Crowder's \"Change My M... Uploaded by shevyrolet Confirm Amy Coney Barrett\
  \ | C... Steven Crowder's \"Change My M... Uploaded by shevyrolet BONUS: America\
  \ Is Superior | ... Steven Crowder's \"Change My M... Uploaded by shevyrolet Build\
  \ The Wall | Change My Mind Steven Crowder's \"Change My M... Uploaded by shevyrolet\
  \ Hate Speech Isn't Real (Googl... Steven Crowder's \"Change My M... Uploaded by\
  \ shevyrolet Change my mind Meme Compilation Steven Crowder's \"Change My M... Uploaded\
  \ by shevyrolet Change my mind memes(Steven C... Steven Crowder's \"Change My M...\
  \ Uploaded by shevyrolet America Is Not Racist | Chang... Steven Crowder's \"Change\
  \ My M... Uploaded by shevyrolet + Add a Video View All Videos Recent Images 361\
  \ total Steven Crowder's \"Change My M... Uploaded by Ulysses Smith Steven Crowder's\
  \ \"Change My M... Uploaded by BrentD15 Steven Crowder's \"Change My M... Uploaded\
  \ by Jaimie Hamilton Steven Crowder's \"Change My M... Uploaded by Jaimie Hamilton\
  \ Steven Crowder's \"Change My M... Uploaded by KZN02 Steven Crowder's \"Change\
  \ My M... Uploaded by Triplem Steven Crowder's \"Change My M... Uploaded by GIR\
  \ Loves Waffles Steven Crowder's \"Change My M... Uploaded by Reddit Moments Steven\
  \ Crowder's \"Change My M... Uploaded by Jothulhu Steven Crowder's \"Change My M...\
  \ Uploaded by Jothulhu Steven Crowder's \"Change My M... Uploaded by BrentD15 Steven\
  \ Crowder's \"Change My M... Uploaded by KZN02 + Add an Image View All Images Sign\
  \ up for our Newsletter Top Comments Delete Sensitive Ryumaru Borike Feb 20, 2018\
  \ at 03:13PM EST This meme will be forgotten in a week ---------------------------------------------\
  \ Change my Mind. +121 Reply Delete Sensitive DirkDiggums Feb 21, 2018 at 09:35AM\
  \ EST Well at least he's trying to hear opposing viewpoints. +73 Reply + Add a Comment\
  \ Comments (92) Display Comments Add a Comment Top Entries This Month Meme Saika\
  \ Kawakita Smile GIF Event Assassination of UnitedHealthcare CEO Person Luigi Mangione\
  \ UHC CEO Shooter Subculture The Ki Sisters Culture Pornography Site Whisper View\
  \ More Suggest a Change Edit History Entry Editors (8) Matt Secretary of Memes Y\
  \ F Digital Archaeologist & Treasurer & Media Maid Don Administrator & Meme Daddy\
  \ Adam Know Your Meme Universal Champion Brad Digital Archaeologist & Treasurer\
  \ & Pundit & Gallery Housekeeper 3kole5 Sr. Entry Moderator shevyrolet Digital Archaeologist\
  \ & Treasurer & Media Bus Boy Zach Memenator \u25BC + Request Editorship View All\
  \ Editors Today's Top Image Galleries Assassination of UnitedHealthcare CEO Team\
  \ Fortress 2 Squirrel Girl (Doreen Green) The Amazing Digital Circus About Our Story\
  \ Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes News\
  \ Staff Contact Extras! Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/steven-crowders-change-my-mind-campus-sign
template_id: cmm
text:
- align: center
  anchor_x: 0.33
  anchor_y: 0.33
  angle: 23.0
  color: black
  font: thin
  scale_x: 0.46
  scale_y: 0.25
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 1
