name: Facepalm
source: http://knowyourmeme.com/memes/facepalm
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- ''
- I can't even
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Facepalm, also known as Facepalming, is a slang term that
  refers to the act of placing one''s face in one''s hand, a form of nonverbal-communication
  common among many cultures. The action conveys a message of dismay and is often
  a reaction toward someone''s momentary lapse of logic, judgment or memory. This
  reaction may be directed toward another person or be self-deprecating. Online, people
  post various reaction images, GIFs and videos of people performing the motion as
  memes to express embarrassment towards someone else''s actions. Origin The facepalm,
  as an expression, existed long before the internet in both human and non-human societies.
  For example, an 1896 statue entitled "Caïn" by Henri Vidal, which resides in Tuileries
  Garden, Paris, France, was unveiled in 1896 (shown below, left).[1] One of the most
  famous and widely used variations of the facepalm comes from an episode of Star
  Trek: The Next Generation, which first aired on February 5th, 1990. The clip shows
  the character Captain Jean-Luc Picard (played by Patrick Stewart) reacting to a
  stressful situation by placing his hand on his face (shown below, right). ![This
  video has been removed] The website Word Spy[2] cites a 2001 message board as the
  earliest usage of the expression. However, the actual post is no longer available.
  Therefore, the earliest available usage of the term online was posted on February
  10th, 2004, by Urban Dictionary [3] user Moondog. They defined the action as, "The
  act of dropping one''s face / forehead into one''s hand. Usually accompanied by
  a ''thunk'' or a cr a cry of ''D''oh!'' Usually written between asterisks in online
  conversation, to demonstrate an action." The post (shown below) received more than
  2,500 upvotes. Spread The following year, on September 5th, 2005, the action was
  defined on the website Wiktionary[4] as "To bring the palm(s) of one''s hand(s)
  to one''s face in mixed humor and disbelief (e.g.: when one is caught off-guard
  with a particularly bad pun)." On May 1st, 2007, the website "Facepalm.com" was
  registered.[5] Two years later, on August 28th, 2009, Redditor [9] namsilat launched
  the /r/facepalm subreddit. The message board, as described by the moderators, is
  designed to share content that "cause viewers to facepalm." In 2011, the Oxford
  English Dictionary[8] added the word and defined it as "A gesture in which the palm
  of one''s hand is brought to one''s face as an expression of dismay, exasperation,
  embarrassment, etc." In 2016, the "person facepalming" or "face palm emoji" was
  accepted by Unicode [6] as an emoji (shown below). Picard Facepalm One of the most
  popular facepalm images is one of Captain Jean-Luc Picard from Star Trek the Next
  Generation taken from the episode "Deja Q," which aired on February 5th, 1990. The
  earliest known reference to Picard''s action as a "facepalm" was uploaded to YouTube
  by YouTuber Johan Jacobsen on May 21st, 2007. The post (shown below, left) received
  more than 489,000 views. The following year, on January 14th, 2008, an article on
  Engagdet[7] used a screenshot from the scene as a reaction to the headline (shown
  below, right). They wrote, "Most bizarre thing you''ll read today: Mass Effect''s
  ''virtual orgasmic r--e.''" On January 29th, 2012, the image was uploaded to the
  website Meme Generator. [10] In about six-and-a-half years, the image has generated
  more than 23,000 memes. Collectible Bust In May 2019, the website ThinkGeek[11]
  began selling a bronze collectible bust of the infamous Star Trek facepalm (shown
  below). The bust weighs about one pound, is made of resin and retails for $69.99.
  In their description, ThinkGeek writes of the bust, "And since the dreaded Picard
  facepalm is such a big deal, we decided to “bronze it.” That way everyone can express
  their disappointment in us with bronzed Picards. Does it make the sting of embarrassment
  better or worse? We still don''t know." Various Examples Search Interest External
  References [1] Wikipedia – Facepalm [2] Word Spy – Facepalm [3] Urban Dictionary
  – Facepalm [4] Wiktionary – Facepalm [5] who.is – facepalm.com whois lookup – who.is
  [6] Emojipedia – face palm emoji [7] Endgadget – Most bizarre thing you''ll read
  today: Mass Effect''s ''virtual orgasmic r--e'' [8] Oxford English Dictionary –
  Facepalm [9] Reddit – A gallery of inexplicable stupidity [10] Meme Generator –
  PIcard Facepalm [11] ThinkGeek – Facepalm Bust'
aside_content: MemeStatusConfirmedType:Reaction,SlangYear2007OriginUrban DictionaryRegionUnited
  StatesTagsgesture,image macro,disapproval,comments,jean luc picard,reaction image,star
  trek,face palm,henri vidal,johan jacobsen,facepalm meme,internet slangAdditional
  ReferencesEncyclopedia DramaticaFacebookMeme GeneratorRedditTwitterUrban DictionaryWikipedia
added_at: '2009-07-27T13:11:58-04:00'
