example:
- ''
- I can't even
keywords:
- null
name: Facepalm
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Facepalm | Know Your Meme Sup! You must login or signup first! Already\
  \ a memeber? Login Now! Don't have an account? Sign up Now! Meme Encyclopedia All\
  \ Cultures Events People Sites Subcultures Videos Submit \u2192 Images Trending\
  \ Most Commented Most Favorited High Score Low Score Most Viewed All Templates Upload\
  \ an Image Articles News Explainers Collections Interviews Meme Insider Magazine\
  \ More Discord Newsletter Episodes Forums Meme Store Login Abstract user icon Memes\
  \ Categories Trending News Images Trending Images Videos Trending Videos Editorials\
  \ Meme Insider Magazine Newsletter Policies and Guidelines Meme Store Old site Login\
  \ Know Your Meme is the property of Literally Media \xA92024 Literally Media. All\
  \ Rights Reserved. This image Of Woman Confidently Strolling Through A Glass Panel\
  \ Has Been A Redraw Format Since 2021 Three Years Ago, This Boar's Head 'Exploded'\
  \ Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess Memes Turns Two Years\
  \ Old Today Phrase 'The Fridge Protects The Snacks' A Growing Favorite Among Pickup\
  \ Artist Influencers Jamie G, The Bosh British Charva, Has Taken Over TikTok With\
  \ His Signature 'Oh Cherie Amour' Sound Also Trending: Honey Extension Influencer\
  \ Scam Renegade Raider Copypasta Assassination of UnitedHealthcare CEO Facepalm\
  \ Added 15 years ago / Updated about a month ago Confirmed 2,371,351 Part of a series\
  \ on Reaction Images. [View Related Entries] [View Related Sub-entries] View All\
  \ 681 Images Navigation About \u2022 Origin \u2022 Spread \u2022 Various Examples\
  \ \u2022 Search Interest \u2022 External References \u2022 Recent Images \u2022\
  \ Recent Videos About Facepalm, also known as Facepalming, is a slang term that\
  \ refers to the act of placing one's face in one's hand, a form of nonverbal-communication\
  \ common among many cultures. The action conveys a message of dismay and is often\
  \ a reaction toward someone's momentary lapse of logic, judgment or memory. This\
  \ reaction may be directed toward another person or be self-deprecating. Online,\
  \ people post various reaction images, GIFs and videos of people performing the\
  \ motion as memes to express embarrassment towards someone else's actions. Origin\
  \ The facepalm, as an expression, existed long before the internet in both human\
  \ and non-human societies. For example, an 1896 statue entitled \"Ca\xEFn\" by Henri\
  \ Vidal, which resides in Tuileries Garden, Paris, France, was unveiled in 1896\
  \ (shown below, left).[1] One of the most famous and widely used variations of the\
  \ facepalm comes from an episode of Star Trek: The Next Generation, which first\
  \ aired on February 5th, 1990. The clip shows the character Captain Jean-Luc Picard\
  \ (played by Patrick Stewart) reacting to a stressful situation by placing his hand\
  \ on his face (shown below, right). ![This video has been removed] The website Word\
  \ Spy[2] cites a 2001 message board as the earliest usage of the expression. However,\
  \ the actual post is no longer available. Therefore, the earliest available usage\
  \ of the term online was posted on February 10th, 2004, by Urban Dictionary [3]\
  \ user Moondog. They defined the action as, \"The act of dropping one's face / forehead\
  \ into one's hand. Usually accompanied by a 'thunk' or a cr a cry of 'D'oh!' Usually\
  \ written between asterisks in online conversation, to demonstrate an action.\"\
  \ The post (shown below) received more than 2,500 upvotes. Spread The following\
  \ year, on September 5th, 2005, the action was defined on the website Wiktionary[4]\
  \ as \"To bring the palm(s) of one's hand(s) to one's face in mixed humor and disbelief\
  \ (e.g.: when one is caught off-guard with a particularly bad pun).\" On May 1st,\
  \ 2007, the website \"Facepalm.com\" was registered.[5] Two years later, on August\
  \ 28th, 2009, Redditor [9] namsilat launched the /r/facepalm subreddit. The message\
  \ board, as described by the moderators, is designed to share content that \"cause\
  \ viewers to facepalm.\" In 2011, the Oxford English Dictionary[8] added the word\
  \ and defined it as \"A gesture in which the palm of one's hand is brought to one's\
  \ face as an expression of dismay, exasperation, embarrassment, etc.\" In 2016,\
  \ the \"person facepalming\" or \"face palm emoji\" was accepted by Unicode [6]\
  \ as an emoji (shown below). Picard Facepalm One of the most popular facepalm images\
  \ is one of Captain Jean-Luc Picard from Star Trek the Next Generation taken from\
  \ the episode \"Deja Q,\" which aired on February 5th, 1990. The earliest known\
  \ reference to Picard's action as a \"facepalm\" was uploaded to YouTube by YouTuber\
  \ Johan Jacobsen on May 21st, 2007. The post (shown below, left) received more than\
  \ 489,000 views. The following year, on January 14th, 2008, an article on Engagdet[7]\
  \ used a screenshot from the scene as a reaction to the headline (shown below, right).\
  \ They wrote, \"Most bizarre thing you'll read today: Mass Effect's 'virtual orgasmic\
  \ r--e.'\" On January 29th, 2012, the image was uploaded to the website Meme Generator.\
  \ [10] In about six-and-a-half years, the image has generated more than 23,000 memes.\
  \ Collectible Bust In May 2019, the website ThinkGeek[11] began selling a bronze\
  \ collectible bust of the infamous Star Trek facepalm (shown below). The bust weighs\
  \ about one pound, is made of resin and retails for $69.99. In their description,\
  \ ThinkGeek writes of the bust, \"And since the dreaded Picard facepalm is such\
  \ a big deal, we decided to \u201Cbronze it.\u201D That way everyone can express\
  \ their disappointment in us with bronzed Picards. Does it make the sting of embarrassment\
  \ better or worse? We still don't know.\" Various Examples Search Interest External\
  \ References [1] Wikipedia \u2013 Facepalm [2] Word Spy \u2013 Facepalm [3] Urban\
  \ Dictionary \u2013 Facepalm [4] Wiktionary \u2013 Facepalm [5] who.is \u2013 facepalm.com\
  \ whois lookup \u2013 who.is [6] Emojipedia \u2013 face palm emoji [7] Endgadget\
  \ \u2013 Most bizarre thing you'll read today: Mass Effect's 'virtual orgasmic r--e'\
  \ [8] Oxford English Dictionary \u2013 Facepalm [9] Reddit \u2013 A gallery of inexplicable\
  \ stupidity [10] Meme Generator \u2013 PIcard Facepalm [11] ThinkGeek \u2013 Facepalm\
  \ Bust gesture image macro disapproval comments jean luc picard reaction image star\
  \ trek face palm henri vidal johan jacobsen facepalm meme internet slang Share Pin\
  \ Related Entries 190 total Deal With It Impossibru Math Lady / Confused Lady Are\
  \ You A Wizard View All Related Entries Sub-entries 2 total FaceFist Dr. Fauci's\
  \ Facepalm Recent Images 681 total View All Images Recent Videos 6 total View All\
  \ Videos Sign up for our Newsletter Load 40 Comments Comments 40 total 195 Facepalm\
  \ 2,371,351 6 681 40 Part of a series on Reaction Images. [View Related Entries]\
  \ [View Related Sub-entries] Updated Nov 05, 2024 at 05:21PM EST by LiterallyAustin.\
  \ Added Jul 27, 2009 at 01:11PM EDT by Chris Menning. Like us on Facebook! Like\
  \ 1.8M Share Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view\
  \ the video gallery, or 'r' to view a random entry. Meme Status Confirmed Type:\
  \ Reaction, Slang Year 2007 Origin Urban Dictionary Region United States Tags gesture,\
  \ image macro, disapproval, comments, jean luc picard, reaction image, star trek,\
  \ face palm, henri vidal, johan jacobsen, facepalm meme, internet slang Additional\
  \ References Encyclopedia Dramatica Facebook Meme Generator Reddit Twitter Urban\
  \ Dictionary Wikipedia About Facepalm, also known as Facepalming, is a slang term\
  \ that refers to the act of placing one's face in one's hand, a form of nonverbal-communication\
  \ common among many cultures. The action conveys a message of dismay and is often\
  \ a reaction toward someone's momentary lapse of logic, judgment or memory. This\
  \ reaction may be directed toward another person or be self-deprecating. Online,\
  \ people post various reaction images, GIFs and videos of people performing the\
  \ motion as memes to express embarrassment towards someone else's actions. Origin\
  \ The facepalm, as an expression, existed long before the internet in both human\
  \ and non-human societies. For example, an 1896 statue entitled \"Ca\xEFn\" by Henri\
  \ Vidal, which resides in Tuileries Garden, Paris, France, was unveiled in 1896\
  \ (shown below, left).[1] One of the most famous and widely used variations of the\
  \ facepalm comes from an episode of Star Trek: The Next Generation, which first\
  \ aired on February 5th, 1990. The clip shows the character Captain Jean-Luc Picard\
  \ (played by Patrick Stewart) reacting to a stressful situation by placing his hand\
  \ on his face (shown below, right). ![This video has been removed] The website Word\
  \ Spy[2] cites a 2001 message board as the earliest usage of the expression. However,\
  \ the actual post is no longer available. Therefore, the earliest available usage\
  \ of the term online was posted on February 10th, 2004, by Urban Dictionary [3]\
  \ user Moondog. They defined the action as, \"The act of dropping one's face / forehead\
  \ into one's hand. Usually accompanied by a 'thunk' or a cr a cry of 'D'oh!' Usually\
  \ written between asterisks in online conversation, to demonstrate an action.\"\
  \ The post (shown below) received more than 2,500 upvotes. Spread The following\
  \ year, on September 5th, 2005, the action was defined on the website Wiktionary[4]\
  \ as \"To bring the palm(s) of one's hand(s) to one's face in mixed humor and disbelief\
  \ (e.g.: when one is caught off-guard with a particularly bad pun).\" On May 1st,\
  \ 2007, the website \"Facepalm.com\" was registered.[5] Two years later, on August\
  \ 28th, 2009, Redditor [9] namsilat launched the /r/facepalm subreddit. The message\
  \ board, as described by the moderators, is designed to share content that \"cause\
  \ viewers to facepalm.\" In 2011, the Oxford English Dictionary[8] added the word\
  \ and defined it as \"A gesture in which the palm of one's hand is brought to one's\
  \ face as an expression of dismay, exasperation, embarrassment, etc.\" In 2016,\
  \ the \"person facepalming\" or \"face palm emoji\" was accepted by Unicode [6]\
  \ as an emoji (shown below). Picard Facepalm One of the most popular facepalm images\
  \ is one of Captain Jean-Luc Picard from Star Trek the Next Generation taken from\
  \ the episode \"Deja Q,\" which aired on February 5th, 1990. The earliest known\
  \ reference to Picard's action as a \"facepalm\" was uploaded to YouTube by YouTuber\
  \ Johan Jacobsen on May 21st, 2007. The post (shown below, left) received more than\
  \ 489,000 views. The following year, on January 14th, 2008, an article on Engagdet[7]\
  \ used a screenshot from the scene as a reaction to the headline (shown below, right).\
  \ They wrote, \"Most bizarre thing you'll read today: Mass Effect's 'virtual orgasmic\
  \ r--e.'\" On January 29th, 2012, the image was uploaded to the website Meme Generator.\
  \ [10] In about six-and-a-half years, the image has generated more than 23,000 memes.\
  \ Collectible Bust In May 2019, the website ThinkGeek[11] began selling a bronze\
  \ collectible bust of the infamous Star Trek facepalm (shown below). The bust weighs\
  \ about one pound, is made of resin and retails for $69.99. In their description,\
  \ ThinkGeek writes of the bust, \"And since the dreaded Picard facepalm is such\
  \ a big deal, we decided to \u201Cbronze it.\u201D That way everyone can express\
  \ their disappointment in us with bronzed Picards. Does it make the sting of embarrassment\
  \ better or worse? We still don't know.\" Various Examples Search Interest External\
  \ References [1] Wikipedia \u2013 Facepalm [2] Word Spy \u2013 Facepalm [3] Urban\
  \ Dictionary \u2013 Facepalm [4] Wiktionary \u2013 Facepalm [5] who.is \u2013 facepalm.com\
  \ whois lookup \u2013 who.is [6] Emojipedia \u2013 face palm emoji [7] Endgadget\
  \ \u2013 Most bizarre thing you'll read today: Mass Effect's 'virtual orgasmic r--e'\
  \ [8] Oxford English Dictionary \u2013 Facepalm [9] Reddit \u2013 A gallery of inexplicable\
  \ stupidity [10] Meme Generator \u2013 PIcard Facepalm [11] ThinkGeek \u2013 Facepalm\
  \ Bust Related Entries 190 total Deal With It Impossibru Math Lady / Confused Lady\
  \ Are You A Wizard Confused Black Girl Brent Rambo Ah, I See You're a Man of Culture\
  \ As Well Computer Reaction Faces Awesome Face / Epic Smiley Shocked Black Guy L.A.\
  \ Noire \"Doubt\" / Press X To Doubt But It's Honest Work View All Related Entries\
  \ Sub-entries 2 total FaceFist Dr. Fauci's Facepalm Recent Videos 6 total Two Decades\
  \ of Memes: Facepalm Facepalm Uploaded by Don When even god thinks you failed Facepalm\
  \ Uploaded by Darkraider Mortal Q (original facepalm) Facepalm Uploaded by Don atomic\
  \ facepalm Facepalm Uploaded by Sir Soundwave Ren goes mad Facepalm Uploaded by\
  \ venusaurmaster FACE PALM Facepalm Uploaded by Hypercat-Z + Add a Video Recent\
  \ Images 681 total Facepalm Uploaded by Jaimie Hamilton Facepalm Uploaded by Jaimie\
  \ Hamilton Facepalm Uploaded by Jaimie Hamilton Facepalm Uploaded by Jaimie Hamilton\
  \ Facepalm Uploaded by Jaimie Hamilton Facepalm Uploaded by Marwan Sallam Facepalm\
  \ Uploaded by Marwan Sallam Facepalm Uploaded by Marwan Sallam Facepalm Uploaded\
  \ by Marwan Sallam Facepalm Uploaded by Marwan Sallam Facepalm Uploaded by Marwan\
  \ Sallam Facepalm Uploaded by Marwan Sallam + Add an Image View All Images Sign\
  \ up for our Newsletter Top Comments Delete Sensitive Tiny_Robin Oct 07, 2011 at\
  \ 08:22PM EDT my favorite is triple facepalm +8 Reply Delete Sensitive Lord DIO\
  \ Feb 10, 2024 at 03:22PM EST A truly OG meme. +3 Reply + Add a Comment Comments\
  \ (40) Display Comments Add a Comment Top Entries This Month Meme Saika Kawakita\
  \ Smile GIF Event Assassination of UnitedHealthcare CEO Person Luigi Mangione UHC\
  \ CEO Shooter Subculture The Ki Sisters Culture Pornography Site Whisper View More\
  \ Suggest a Change Edit History Entry Editors (7) Chris Menning Digital Archaeologist\
  \ & Archivist & Pundit & Early Adopter (#8) Brad Digital Archaeologist & Treasurer\
  \ & Pundit & Gallery Housekeeper Don Administrator & Meme Daddy SabrinaTibbetts\
  \ Memepuff Y F Digital Archaeologist & Treasurer & Media Maid Matt Secretary of\
  \ Memes Zach Memenator \u25BC + Request Editorship View All Editors Today's Top\
  \ Image Galleries Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen Green)\
  \ Team Fortress 2 The Amazing Digital Circus About Our Story Site Rules Policies\
  \ and Guidelines Credits Contact Meme DB Memes Episodes News Staff Contact Extras!\
  \ Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/facepalm
template_id: facepalm
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
