example:
- ''
- stonks
keywords:
- null
name: Stonks
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Stonks | Know Your Meme Yo! You must login or signup first! Already\
  \ a memeber? Login Now! Don't have an account? Sign up Now! Meme Encyclopedia All\
  \ Cultures Events People Sites Subcultures Videos Submit \u2192 Images Trending\
  \ Most Commented Most Favorited High Score Low Score Most Viewed All Templates Upload\
  \ an Image Articles News Explainers Collections Interviews Meme Insider Magazine\
  \ More Discord Newsletter Episodes Forums Meme Store Login Abstract user icon Memes\
  \ Categories Trending News Images Trending Images Videos Trending Videos Editorials\
  \ Meme Insider Magazine Newsletter Policies and Guidelines Meme Store Old site Login\
  \ Know Your Meme is the property of Literally Media \xA92024 Literally Media. All\
  \ Rights Reserved. This image Of Woman Confidently Strolling Through A Glass Panel\
  \ Has Been A Redraw Format Since 2021 Three Years Ago, This Boar's Head 'Exploded'\
  \ Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess Memes Turns Two Years\
  \ Old Today Phrase 'The Fridge Protects The Snacks' A Growing Favorite Among Pickup\
  \ Artist Influencers Jamie G, The Bosh British Charva, Has Taken Over TikTok With\
  \ His Signature 'Oh Cherie Amour' Sound Also Trending: Honey Extension Influencer\
  \ Scam Renegade Raider Copypasta Stonks Added 5 years ago / Updated 6 months ago\
  \ Confirmed 2,334,065 Part of a series on Meme Man Wurds / Stonks Edits. [View Related\
  \ Entries] [View Related Sub-entries] View All 288 Images Navigation About \u2022\
  \ Origin \u2022 Spread \u2022 Various Examples \u2022 Template \u2022 Search Interest\
  \ \u2022 External References \u2022 Recent Images \u2022 Recent Videos About Stonks\
  \ is an intentional misspelling of the word \"stocks\" which is often associated\
  \ with a surreal meme featuring the character Meme Man standing in front of a picture\
  \ representing the stock market followed by the caption \"Stonks.\" The picture\
  \ began seeing use as a reaction image online in jokes about making poor financial\
  \ decisions. In the 2020s, the term \"stonks\" has come to be used within the Meme\
  \ Stocks community to describe humorous investing in various companies as a means\
  \ to manipulate the market. Origin On June 5th, 2017, Facebook page Special Meme\
  \ Fresh[1] posted the image of Meme Man in front of a stock photo representing the\
  \ stock market, captioned \"STONKS.\" The image gained over 3,600 likes and reactions\
  \ (shown below). Spread Over the following months, the image saw some spread in\
  \ jokes online. On July 3rd, 2017, the image was posted to /r/Ooer,[2] where it\
  \ gained over 400 points. On February 9th, 2018, YouTuber HallucinatoryMenu posted\
  \ a clip of the word being read with heavy reverb, gaining over 19,000 views (shown\
  \ below, left). On March 15th, an edit appeared in an Imgur photo dump posted by\
  \ 1860000000001[3] which gained over 131,000 views (shown below, right). On December\
  \ 5th, 2018, Redditor x37 posted an I'll Take Your Entire Stock meme to /r/memes\
  \ with the character[4] (shown below, left). On June 3rd, 2019, Redditor Renji posted\
  \ a fake text meme to /r/GoodFakeTexts,[5] gaining over 4,400 points (shown below,\
  \ right). The image also appeared in /r/me_irl[6] where it gained over 13,000 points.\
  \ The website eBaum's World published a list of 32 Weird Stonks Memes On The Rise.[7]\
  \ The popularity of \"Stonks\" went on to spawn multiple similar memes in 2019 featuring\
  \ Meme Man and focusing on other professions. Examples include Shef, Tehc and Helth.\
  \ I Didn't Mean To Send That I Didn't Mean To Send That is a phrase featured in\
  \ a series of viral videos depicting a string of texts sent from one person to their\
  \ significant other. The videos, shot from a first-person POV as if the viewer is\
  \ the one texting, feature a person sending a series of apology texts to their partner\
  \ before mistakenly sending an unrelated image, most often a Stonks meme. On June\
  \ 3rd, 2019, Redditor Renji posted a fake text meme on r/GoodFakeTexts, featuring\
  \ the text string as described in the About section of this page (shown below).\
  \ The \"accidentally sent\" image, in this case, is the Stonks meme. The post received\
  \ over 5,000 upvotes in 15 months. Use In Meme Stock Communities The term \"Stonks\"\
  \ is frequently used in Meme Stock communities such as /r/WallStreetBets, particularly\
  \ as users invest in seemingly dying stocks such as Gamestop in order to turn a\
  \ profit. Since the Gamestop Short Squeeze, similar Meme Stocks have been referred\
  \ to as \"Stonks.\" Various Examples Template Search Interest External References\
  \ [1] Facebook \u2013 Special Meme Fresh [2] Reddit \u2013 /r/Ooer [3] Imgur \u2013\
  \ Dump [4] Reddit \u2013 I'll Take Your Entire Stonk [5] Reddit \u2013 s t o n k\
  \ s [6] Reddit \u2013 me_irl [7] EbaumsWorld \u2013 32 Weird AF Stonks Memes stocks\
  \ meme man surreal memes special meme fresh hallucinatorymenu x37 renji stock market\
  \ stoinks 1860000000001 ooer r/ooer Share Pin Related Entries 7 total Helth Panik\
  \ Kalm Shef Tehc View All Related Entries Sub-entries 1 total I Didn't Mean To Send\
  \ That Recent Images 288 total View All Images Recent Videos 477 total View All\
  \ Videos Sign up for our Newsletter Load 15 Comments Comments 15 total 43 Stonks\
  \ 2,334,065 477 288 15 Part of a series on Meme Man Wurds / Stonks Edits. [View\
  \ Related Entries] [View Related Sub-entries] Updated Jun 04, 2024 at 04:30PM EDT\
  \ by Adam. Added Jun 05, 2019 at 01:33PM EDT by Adam. Like us on Facebook! Like\
  \ 1.8M Share Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view\
  \ the video gallery, or 'r' to view a random entry. Meme Status Confirmed Type:\
  \ Character, Slang Year 2017 Origin Facebook Tags stocks, meme man, surreal memes,\
  \ special meme fresh, hallucinatorymenu, x37, renji, stock market, stoinks, 1860000000001,\
  \ ooer, r/ooer Additional References Dictionary.com Meme Generator Reddit Twitter\
  \ Urban Dictionary About Stonks is an intentional misspelling of the word \"stocks\"\
  \ which is often associated with a surreal meme featuring the character Meme Man\
  \ standing in front of a picture representing the stock market followed by the caption\
  \ \"Stonks.\" The picture began seeing use as a reaction image online in jokes about\
  \ making poor financial decisions. In the 2020s, the term \"stonks\" has come to\
  \ be used within the Meme Stocks community to describe humorous investing in various\
  \ companies as a means to manipulate the market. Origin On June 5th, 2017, Facebook\
  \ page Special Meme Fresh[1] posted the image of Meme Man in front of a stock photo\
  \ representing the stock market, captioned \"STONKS.\" The image gained over 3,600\
  \ likes and reactions (shown below). Spread Over the following months, the image\
  \ saw some spread in jokes online. On July 3rd, 2017, the image was posted to /r/Ooer,[2]\
  \ where it gained over 400 points. On February 9th, 2018, YouTuber HallucinatoryMenu\
  \ posted a clip of the word being read with heavy reverb, gaining over 19,000 views\
  \ (shown below, left). On March 15th, an edit appeared in an Imgur photo dump posted\
  \ by 1860000000001[3] which gained over 131,000 views (shown below, right). On December\
  \ 5th, 2018, Redditor x37 posted an I'll Take Your Entire Stock meme to /r/memes\
  \ with the character[4] (shown below, left). On June 3rd, 2019, Redditor Renji posted\
  \ a fake text meme to /r/GoodFakeTexts,[5] gaining over 4,400 points (shown below,\
  \ right). The image also appeared in /r/me_irl[6] where it gained over 13,000 points.\
  \ The website eBaum's World published a list of 32 Weird Stonks Memes On The Rise.[7]\
  \ The popularity of \"Stonks\" went on to spawn multiple similar memes in 2019 featuring\
  \ Meme Man and focusing on other professions. Examples include Shef, Tehc and Helth.\
  \ I Didn't Mean To Send That I Didn't Mean To Send That is a phrase featured in\
  \ a series of viral videos depicting a string of texts sent from one person to their\
  \ significant other. The videos, shot from a first-person POV as if the viewer is\
  \ the one texting, feature a person sending a series of apology texts to their partner\
  \ before mistakenly sending an unrelated image, most often a Stonks meme. On June\
  \ 3rd, 2019, Redditor Renji posted a fake text meme on r/GoodFakeTexts, featuring\
  \ the text string as described in the About section of this page (shown below).\
  \ The \"accidentally sent\" image, in this case, is the Stonks meme. The post received\
  \ over 5,000 upvotes in 15 months. Use In Meme Stock Communities The term \"Stonks\"\
  \ is frequently used in Meme Stock communities such as /r/WallStreetBets, particularly\
  \ as users invest in seemingly dying stocks such as Gamestop in order to turn a\
  \ profit. Since the Gamestop Short Squeeze, similar Meme Stocks have been referred\
  \ to as \"Stonks.\" Various Examples Template Search Interest External References\
  \ [1] Facebook \u2013 Special Meme Fresh [2] Reddit \u2013 /r/Ooer [3] Imgur \u2013\
  \ Dump [4] Reddit \u2013 I'll Take Your Entire Stonk [5] Reddit \u2013 s t o n k\
  \ s [6] Reddit \u2013 me_irl [7] EbaumsWorld \u2013 32 Weird AF Stonks Memes Related\
  \ Entries 7 total Helth Panik Kalm Shef Tehc Mekanik Kemist Acceleration Yes Sub-entries\
  \ 1 total I Didn't Mean To Send That Recent Videos 477 total Stonks 10 abo-Special\
  \ 5/5 Stonks Uploaded by Y F shortest S T O N K S video on... Stonks Uploaded by\
  \ Y F stonks Stonks Uploaded by Y F STONKS *MEME SKIN* is BEST EV... Stonks Uploaded\
  \ by Y F STONKS !!! (uau stonks) Stonks Uploaded by Y F Fortnite Item Shop *NEW*\
  \ STON... Stonks Uploaded by Y F I Pretended To Be Boss STONKS... Stonks Uploaded\
  \ by Y F Fortnite STONKS \U0001F48E\U0001F64C Stonks Uploaded by Y F + Add a Video\
  \ View All Videos Recent Images 288 total Stonks Uploaded by deperpmemes Stonks\
  \ Uploaded by memeunk Stonks Uploaded by Evilthing Stonks Uploaded by Moldy Moldy\
  \ Stonks Uploaded by Raul Satisacro Stonks Uploaded by Cold Hard Crash Stonks Uploaded\
  \ by Sobsz Stonks Uploaded by wignut Stonks Uploaded by cfjulian Stonks Uploaded\
  \ by shevyrolet Stonks Uploaded by shevyrolet Stonks Uploaded by Y F + Add an Image\
  \ View All Images Sign up for our Newsletter Top Comments Delete Sensitive B2oo2\
  \ Jun 18, 2019 at 01:21PM EDT meme_economists.png +19 Reply Delete Sensitive Mace121\
  \ Jun 05, 2019 at 01:59PM EDT Kronk & Bonk's Stonks. +9 Reply + Add a Comment Comments\
  \ (15) Display Comments Add a Comment Top Entries This Month Meme Saika Kawakita\
  \ Smile GIF Event Assassination of UnitedHealthcare CEO Person Luigi Mangione UHC\
  \ CEO Shooter Subculture The Ki Sisters Culture Pornography Site Whisper View More\
  \ Suggest a Change Edit History Entry Editors (6) Adam Know Your Meme Universal\
  \ Champion 3kole5 Sr. Entry Moderator Philipp Memesplainer Y F Digital Archaeologist\
  \ & Treasurer & Media Maid Don Administrator & Meme Daddy Sophie Digital Archaeologist\
  \ & Treasurer & Media Bus Boy \u25BC + Request Editorship View All Editors Today's\
  \ Top Image Galleries Assassination of UnitedHealthcare CEO Team Fortress 2 Squirrel\
  \ Girl (Doreen Green) The Amazing Digital Circus About Our Story Site Rules Policies\
  \ and Guidelines Credits Contact Meme DB Memes Episodes News Staff Contact Extras!\
  \ Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/stonks
template_id: stonks
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
