name: Stonks
source: https://knowyourmeme.com/memes/stonks
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- ''
- stonks
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About Stonks is an intentional misspelling of the word "stocks" which
  is often associated with a surreal meme featuring the character Meme Man standing
  in front of a picture representing the stock market followed by the caption "Stonks."
  The picture began seeing use as a reaction image online in jokes about making poor
  financial decisions. In the 2020s, the term "stonks" has come to be used within
  the Meme Stocks community to describe humorous investing in various companies as
  a means to manipulate the market. Origin On June 5th, 2017, Facebook page Special
  Meme Fresh[1] posted the image of Meme Man in front of a stock photo representing
  the stock market, captioned "STONKS." The image gained over 3,600 likes and reactions
  (shown below). Spread Over the following months, the image saw some spread in jokes
  online. On July 3rd, 2017, the image was posted to /r/Ooer,[2] where it gained over
  400 points. On February 9th, 2018, YouTuber HallucinatoryMenu posted a clip of the
  word being read with heavy reverb, gaining over 19,000 views (shown below, left).
  On March 15th, an edit appeared in an Imgur photo dump posted by 1860000000001[3]
  which gained over 131,000 views (shown below, right). On December 5th, 2018, Redditor
  x37 posted an I'll Take Your Entire Stock meme to /r/memes with the character[4]
  (shown below, left). On June 3rd, 2019, Redditor Renji posted a fake text meme to
  /r/GoodFakeTexts,[5] gaining over 4,400 points (shown below, right). The image also
  appeared in /r/me_irl[6] where it gained over 13,000 points. The website eBaum's
  World published a list of 32 Weird Stonks Memes On The Rise.[7] The popularity of
  "Stonks" went on to spawn multiple similar memes in 2019 featuring Meme Man and
  focusing on other professions. Examples include Shef, Tehc and Helth. I Didn't Mean
  To Send That I Didn't Mean To Send That is a phrase featured in a series of viral
  videos depicting a string of texts sent from one person to their significant other.
  The videos, shot from a first-person POV as if the viewer is the one texting, feature
  a person sending a series of apology texts to their partner before mistakenly sending
  an unrelated image, most often a Stonks meme. On June 3rd, 2019, Redditor Renji
  posted a fake text meme on r/GoodFakeTexts, featuring the text string as described
  in the About section of this page (shown below). The "accidentally sent" image,
  in this case, is the Stonks meme. The post received over 5,000 upvotes in 15 months.
  Use In Meme Stock Communities The term "Stonks" is frequently used in Meme Stock
  communities such as /r/WallStreetBets, particularly as users invest in seemingly
  dying stocks such as Gamestop in order to turn a profit. Since the Gamestop Short
  Squeeze, similar Meme Stocks have been referred to as "Stonks." Various Examples
  Template Search Interest External References [1] Facebook – Special Meme Fresh [2]
  Reddit – /r/Ooer [3] Imgur – Dump [4] Reddit – I'll Take Your Entire Stonk [5] Reddit
  – s t o n k s [6] Reddit – me_irl [7] EbaumsWorld – 32 Weird AF Stonks Memes
aside_content: MemeStatusConfirmedType:Character,SlangYear2017OriginFacebookTagsstocks,meme
  man,surreal memes,special meme fresh,hallucinatorymenu,x37,renji,stock market,stoinks,1860000000001,ooer,r/ooerAdditional
  ReferencesDictionary.comMeme GeneratorRedditTwitterUrban Dictionary
added_at: '2019-06-05T13:33:48-04:00'
