name: Forever Alone
source: http://knowyourmeme.com/memes/forever-alone
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- forever
- alone
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Forever Alone is an exploitable rage comic character that
  is used to express loneliness and disappointment with life. The face has also been
  used as an advice animal and inspired the creation of the snowclone template "Forever
  an X." Origin Forever Alone is considered one of the first major rage comic spin-off
  characters to be creater after the original Rage Guy, which first sprang up on 4chan
  in 2009. According to various sources, the original comic was uploaded in a thread
  titled "April Fools" by FunnyJunk user Azuul on May 28th, 2010 (shown below). While
  the original artist has not been confirmed, Dictionary.com[24] cites Dominic Vanner
  as the illustrator behind the character. Spread In early June 2010, another instance
  featuring a bachelor salaryman was posted on 4chan (shown below, left). On August
  5th, 2010, Redditor L_E_G_E_N_D posted a Forever Alone rage comic titled "Prom FFFUUUU"[14]
  (shown below, right), receiving over 275 up votes and 70 comments prior to being
  archived. By September 2010, there were over 23,000 image results for "Forever Alone"
  on FunnyJunk[3] and over 50,000 on Tumblr.[4] On September 11th, single topic blog
  Forever Alone Comics[19] was launched to curate the growing collection of four-pane
  comics. On September 15th, the /r/foreveralone[23] subreddit was created, which
  received over 25,300 subscribers in the next three years. In early October, Forever
  Alone received mentions in several blogs, including Geekosystem[5], Memebase[15]
  and Uproxx.[16] Meanwhile, the meaning of term "Forever Alone" gradually expanded
  from a rage comic reference to the more general statement of being alone. On February
  13th, 2013, the International Business Times[22] published a slideshow of notable
  Valentine''s Day Forever Alone comics and image macros. As of February 2013, a Facebook[21]
  page titled "Forever Alone" has received over 7.2 million submissions. Various Examples
  In the beginning, most rage comics were illustrated with the the basic four-pane
  template, but later grew into other formats like vertical comic strips, advice animals,
  multi-pane comics with dialogues and even animated GIFs. Rage Comics Vertical Strips
  Advice Animals An Advice Animal-style image macro series dubbed "Forever Alone"
  emerged on macro generator sites Memegenerator[1] and Quickmeme[20] sometime between
  December 2010 and January 2011. As of February 2013, the "Forever Alone" Quickmeme[20]
  page has received over 62,000 submissions. Animated GIF 2011 Times Square Flash
  Mob On March 22nd, 2011, internet users on 4chan and Reddit began plotting an "involuntary"
  flash mob event by creating fake profiles on the dating site OKCupid and setting
  up a false rendezvous for single males at the Times Square, New York City at 7:30pm
  on May 13th, 2011.[6] According to Urlesque''s report[7], flyers with details of
  the action plan were posted in the forums and blogs like The Mainboard[8], NYMag[9],
  Social Spew[10], Skim Online Forums[11] and Dating Service Reporter[12]. The sudden
  influx of heavy traffic put a heavy strain on Earthcam''s servers, resulting in
  a streaming outage for viewers from 7 p.m. to 7:40 p.m. The few with access to the
  live stream took and uploaded screenshots of many men in suits loitering at meeting
  place via Tumblr and 4chan. At one point, an Anonymous guest appeared in the Earthcam
  feed with a Forever Alone poster on the side of a phone booth. 2011 Sony Ericsson
  Ad Campaign In November 2011, Sony Ericsson launched a series of video advertisements
  prominently featuring the character of Forever Alone for its Xperiathon campaign
  dubbed "The Loneliest Marathon in the World."[18] Related Memes "I Know That Feel
  Bro" “I Know That Feel Bro” is an Internet slang expression used to convey empathy
  towards or agree with someone else’s feeling or opinion. The expression, which roughly
  means “I feel you, bro,” is typically accompanied by a contour- drawing reaction
  image of two bald men embracing each other expressionlessly. The face has been used
  as an exploitable character and is often seen in “that feel when” (TFW) threads
  on image boards, which describe an emotional situation or event. The Friend Zone
  The “Friend Zone” refers to an interpersonal relationship in which one member wishes
  to become romantically involved while the other would rather remain friends only.
  Involuntary Abstinence “Involuntary Abstinence” is a dated concept in Internet humor
  typically iterated in image macros poking fun at male-oriented hobbies that may
  be deemed too nerdy, thus unattractive, by the other sex, such as LARPing, cosplaying
  and video game collecting, among others. While some instances appear to be used
  as a form of self-parody by men on the Internet, others can be seen as examples
  of virgin-shaming. Search Interest External References [1] Memegenerator – Forever
  Alone [2] FunnyJunk – Forever Alone [3] Google – forever alone search results on
  Funny Junk [4] Google – forever alone search results on Tumblr [5] Geekosystem –
  Forever Alone Meme [6] Reddit – Involuntary Flashmob [7] Urlesque – Involuntary
  Flashmob Plotted for Forever Alone Single Guys [8] The Mainboard – Forever Alone
  Involuntary Flashmob [9] NYMag – 4chan Using Fake OkCupid Profiles to Lure Pathetic
  Singles to Times Square [10] Social Spew – Forever Alone Involuntary Flashmob [11]
  Skim Online Forums – Forever Alone Flash Mob [12] Dating Service Reporter – 4chan
  Using Fake OkCupid Profiles to Lure Pathetic Singles to Times Square [13] Memebase
  – Forever Alone [14] Reddit – Prom FFFFFUUUUUUUUU [15] Memebase – Results for Forever
  Alone [16] Uproxx – Meme Watch: Forever Alone [17] Wikipedia – Involuntary celibacy
  [18] YouTube – Xperiathon''s Channel [19] ForeverAloneComics – Forever Alone Website
  [20] Quickmeme – Forever Alone [21] Facebook – Forever Alone [22] International
  Business Times – 2013 Valentine’s Day Funny [23] Reddit – /r/foreveralone [24] Dictionary.com
  – forever alone'
aside_content: MemeStatusConfirmedType:CharacterYear2010OriginFunnyJunkTagsrageguy
  spinoff,forever alone,4chan,alone,forever,involuntary,flashmob,flash mob,relationship,singledom,awkward,lonelyAdditional
  ReferencesEncyclopedia DramaticaFacebookMeme GeneratorRedditTwitterUrban Dictionary
added_at: '2010-08-25T01:23:55-04:00'
