name: Feels Bad Man
source: http://knowyourmeme.com/memes/feels-bad-man-sad-frog
keywords:
- Sad Frog
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- ''
- feels bad man
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About Sad Frog is a cartoon drawing of a depressed-looking frog,
  often accompanied by the text "Feels Bad Man" or "You Will Never X". It is used
  to denote feelings of failure or disappointment, either by posting the image or
  using the phrase "feelsbadman.jpg." Sad Frog may be seen as the antithesis of Feels
  Good Man. Origin The original Sad Frog artwork is based on Matt Furie's drawing
  of Pepe the frog. The earliest archived 4chan thread[1] was posted on January 22nd,
  2009, in which an altered version of Furie’s original image with the mouth flipped,
  saying “Feels Bad Man." On August 17th, 2009, a user on the Body Building Forums
  posted[2] the Sad Frog image with the caption "not good man." Pairing the frog with
  the phrase “You Will Never X” also began some time in 2009. Though the original
  thread was not archived, it was reuploaded to Polish image hosting service Kyon[3]
  on June 11th, 2009, noting 4chan’s anime board, /a/, as its original source. Spread
  Throughout 2010, "feelsbadman.jpg" became a popular way of conveying feelings in
  Greentext style stories throughout 4chan boards, including /mu/[5] (music), /r9k/[6]
  (Robot9000) and /sp/[7] (sports). The first Sad Frog image compilation was posted
  to FunnyJunk[8] on June 1st, 2010. The phrase "feels bad, man" was first defined
  on Urban Dictionary[4] on November 30th, 2010. A Facebook group called Feels Bad
  Man[9] was created in December 2009. As of February 2012, it has a little over 1500
  likes. In December 2010, Feelsbadman.com[10] was created, with nothing but a picture
  of the sad frog. There are also two separate Quickmeme pages[11][12] with the picture
  and an active Tumblr tag.[13] Notable Examples Search Interest Search for "feels
  bad man" began in August 2009, while search for "sad frog" did not begin to pick
  up until February 2010. Both terms have a similar pattern of spikes, but since "feels
  bad man" is a more general phrase, it is more popular. External References [1] Chanarchive
  (via Wayback Machine) – feelsbadman.jpg [2] Body Building Forums – not good man
  [3] Kyon – You will never… (page unavailable) [4] Urban Dictionary – feels bad,
  man [5] Chanarchive – Concert stories, /mu/ [6] Chanarchive – School Greentext [7]
  Chanarchive – Lions vs Bye Week [8] FunnyJunk – Sad Frog [9] Facebook – Feels Bad
  Man [10] Feelsbadman.com (via Wayback Machine) – Home [11] Quickmeme – Sad Frog
  [12] Quickmeme – FEELS BAD MAN [13] Tumblr – Posts tagged "sad frog"
aside_content: MemeStatusConfirmedYear2009Origin4chanTags4chan,image macro,matt furie,feels
  good man,sad frog,feels bad man,pepe
added_at: '2010-06-03T10:41:56-04:00'
