example:
- ''
- feels bad man
keywords:
- Sad Frog
name: Feels Bad Man
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Feels Bad Man / Sad Frog | Know Your Meme O HAI! You must login\
  \ or signup first! Already a memeber? Login Now! Don't have an account? Sign up\
  \ Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos Submit\
  \ \u2192 Images Trending Most Commented Most Favorited High Score Low Score Most\
  \ Viewed All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Feels Bad Man / Sad Frog Added 14 years ago / Updated 8 days ago Confirmed\
  \ 1,700,767 Part of a series on Pepe the Frog. [View Related Entries] View All 459\
  \ Images Navigation About \u2022 Origin \u2022 Spread \u2022 Search Interest \u2022\
  \ External References \u2022 Recent Images \u2022 Recent Videos About Sad Frog is\
  \ a cartoon drawing of a depressed-looking frog, often accompanied by the text \"\
  Feels Bad Man\" or \"You Will Never X\". It is used to denote feelings of failure\
  \ or disappointment, either by posting the image or using the phrase \"feelsbadman.jpg.\"\
  \ Sad Frog may be seen as the antithesis of Feels Good Man. Origin The original\
  \ Sad Frog artwork is based on Matt Furie's drawing of Pepe the frog. The earliest\
  \ archived 4chan thread[1] was posted on January 22nd, 2009, in which an altered\
  \ version of Furie\u2019s original image with the mouth flipped, saying \u201CFeels\
  \ Bad Man.\" On August 17th, 2009, a user on the Body Building Forums posted[2]\
  \ the Sad Frog image with the caption \"not good man.\" Pairing the frog with the\
  \ phrase \u201CYou Will Never X\u201D also began some time in 2009. Though the original\
  \ thread was not archived, it was reuploaded to Polish image hosting service Kyon[3]\
  \ on June 11th, 2009, noting 4chan\u2019s anime board, /a/, as its original source.\
  \ Spread Throughout 2010, \"feelsbadman.jpg\" became a popular way of conveying\
  \ feelings in Greentext style stories throughout 4chan boards, including /mu/[5]\
  \ (music), /r9k/[6] (Robot9000) and /sp/[7] (sports). The first Sad Frog image compilation\
  \ was posted to FunnyJunk[8] on June 1st, 2010. The phrase \"feels bad, man\" was\
  \ first defined on Urban Dictionary[4] on November 30th, 2010. A Facebook group\
  \ called Feels Bad Man[9] was created in December 2009. As of February 2012, it\
  \ has a little over 1500 likes. In December 2010, Feelsbadman.com[10] was created,\
  \ with nothing but a picture of the sad frog. There are also two separate Quickmeme\
  \ pages[11][12] with the picture and an active Tumblr tag.[13] Notable Examples\
  \ Search Interest Search for \"feels bad man\" began in August 2009, while search\
  \ for \"sad frog\" did not begin to pick up until February 2010. Both terms have\
  \ a similar pattern of spikes, but since \"feels bad man\" is a more general phrase,\
  \ it is more popular. External References [1] Chanarchive (via Wayback Machine)\
  \ \u2013 feelsbadman.jpg [2] Body Building Forums \u2013 not good man [3] Kyon \u2013\
  \ You will never\u2026 (page unavailable) [4] Urban Dictionary \u2013 feels bad,\
  \ man [5] Chanarchive \u2013 Concert stories, /mu/ [6] Chanarchive \u2013 School\
  \ Greentext [7] Chanarchive \u2013 Lions vs Bye Week [8] FunnyJunk \u2013 Sad Frog\
  \ [9] Facebook \u2013 Feels Bad Man [10] Feelsbadman.com (via Wayback Machine) \u2013\
  \ Home [11] Quickmeme \u2013 Sad Frog [12] Quickmeme \u2013 FEELS BAD MAN [13] Tumblr\
  \ \u2013 Posts tagged \"sad frog\" 4chan image macro matt furie feels good man sad\
  \ frog feels bad man pepe Share Pin Related Entries 18 total Feels Good Man Clown\
  \ Pepe / Honk Honk / Clow... Apu Apustaja Rare Pepe View All Related Entries Recent\
  \ Images 459 total View All Images Recent Videos 1 total View All Videos Sign up\
  \ for our Newsletter Load 38 Comments Comments 38 total 93 Feels Bad Man / Sad Frog\
  \ 1,700,767 1 459 38 Part of a series on Pepe the Frog. [View Related Entries] Updated\
  \ Dec 15, 2024 at 03:16PM EST by LiterallyAustin. Added Jun 03, 2010 at 10:41AM\
  \ EDT by ajosephisme. Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press\
  \ 'i' to view the image gallery, 'v' to view the video gallery, or 'r' to view a\
  \ random entry. Meme Status Confirmed Year 2009 Origin 4chan Tags 4chan, image macro,\
  \ matt furie, feels good man, sad frog, feels bad man, pepe About Sad Frog is a\
  \ cartoon drawing of a depressed-looking frog, often accompanied by the text \"\
  Feels Bad Man\" or \"You Will Never X\". It is used to denote feelings of failure\
  \ or disappointment, either by posting the image or using the phrase \"feelsbadman.jpg.\"\
  \ Sad Frog may be seen as the antithesis of Feels Good Man. Origin The original\
  \ Sad Frog artwork is based on Matt Furie's drawing of Pepe the frog. The earliest\
  \ archived 4chan thread[1] was posted on January 22nd, 2009, in which an altered\
  \ version of Furie\u2019s original image with the mouth flipped, saying \u201CFeels\
  \ Bad Man.\" On August 17th, 2009, a user on the Body Building Forums posted[2]\
  \ the Sad Frog image with the caption \"not good man.\" Pairing the frog with the\
  \ phrase \u201CYou Will Never X\u201D also began some time in 2009. Though the original\
  \ thread was not archived, it was reuploaded to Polish image hosting service Kyon[3]\
  \ on June 11th, 2009, noting 4chan\u2019s anime board, /a/, as its original source.\
  \ Spread Throughout 2010, \"feelsbadman.jpg\" became a popular way of conveying\
  \ feelings in Greentext style stories throughout 4chan boards, including /mu/[5]\
  \ (music), /r9k/[6] (Robot9000) and /sp/[7] (sports). The first Sad Frog image compilation\
  \ was posted to FunnyJunk[8] on June 1st, 2010. The phrase \"feels bad, man\" was\
  \ first defined on Urban Dictionary[4] on November 30th, 2010. A Facebook group\
  \ called Feels Bad Man[9] was created in December 2009. As of February 2012, it\
  \ has a little over 1500 likes. In December 2010, Feelsbadman.com[10] was created,\
  \ with nothing but a picture of the sad frog. There are also two separate Quickmeme\
  \ pages[11][12] with the picture and an active Tumblr tag.[13] Notable Examples\
  \ Search Interest Search for \"feels bad man\" began in August 2009, while search\
  \ for \"sad frog\" did not begin to pick up until February 2010. Both terms have\
  \ a similar pattern of spikes, but since \"feels bad man\" is a more general phrase,\
  \ it is more popular. External References [1] Chanarchive (via Wayback Machine)\
  \ \u2013 feelsbadman.jpg [2] Body Building Forums \u2013 not good man [3] Kyon \u2013\
  \ You will never\u2026 (page unavailable) [4] Urban Dictionary \u2013 feels bad,\
  \ man [5] Chanarchive \u2013 Concert stories, /mu/ [6] Chanarchive \u2013 School\
  \ Greentext [7] Chanarchive \u2013 Lions vs Bye Week [8] FunnyJunk \u2013 Sad Frog\
  \ [9] Facebook \u2013 Feels Bad Man [10] Feelsbadman.com (via Wayback Machine) \u2013\
  \ Home [11] Quickmeme \u2013 Sad Frog [12] Quickmeme \u2013 FEELS BAD MAN [13] Tumblr\
  \ \u2013 Posts tagged \"sad frog\" Related Entries 18 total Feels Good Man Clown\
  \ Pepe / Honk Honk / Clown World Apu Apustaja Rare Pepe Groyper Smug Frog Angry\
  \ Pepe Nazi Pepe Controversy Well Meme'd Fefe Pepe Punch Cheesed To Meet You View\
  \ All Related Entries Recent Videos 1 total feelsbadman.avi Feels Bad Man / Sad\
  \ Frog Uploaded by feelsman + Add a Video Recent Images 459 total Feels Bad Man\
  \ / Sad Frog Uploaded by Frank the Inventor Feels Bad Man / Sad Frog Uploaded by\
  \ TomboyLover2 Feels Bad Man / Sad Frog Uploaded by Cesar Acu\xF1a Feels Bad Man\
  \ / Sad Frog Uploaded by HoppsCarrotFarm Feels Bad Man / Sad Frog Uploaded by B.\
  \ M. S. Feels Bad Man / Sad Frog Uploaded by B. M. S. Feels Bad Man / Sad Frog Uploaded\
  \ by Square Memester Feels Bad Man / Sad Frog Uploaded by Material_Phase Feels Bad\
  \ Man / Sad Frog Uploaded by Material_Phase Feels Bad Man / Sad Frog Uploaded by\
  \ cyansmirnoff Feels Bad Man / Sad Frog Uploaded by Cesar Acu\xF1a Feels Bad Man\
  \ / Sad Frog Uploaded by Juan del Rancho + Add an Image View All Images Sign up\
  \ for our Newsletter Top Comments Delete Sensitive No Dec 16, 2014 at 04:12PM EST\
  \ wat +18 Reply Delete Sensitive Fufffusei Jun 21, 2012 at 11:55AM EDT It's okay,\
  \ man. The internet sucked in the 90's. +4 Reply + Add a Comment Comments (38) Display\
  \ Comments Add a Comment Top Entries This Month Meme Saika Kawakita Smile GIF Event\
  \ Assassination of UnitedHealthcare CEO Person Luigi Mangione UHC CEO Shooter Subculture\
  \ The Ki Sisters Culture Pornography Site Whisper View More Suggest a Change Edit\
  \ History Entry Editors (7) ajosephisme Horseeater Deactivated amanda b. Meme Librarian\
  \ Brad Digital Archaeologist & Treasurer & Pundit & Gallery Housekeeper Z. Database\
  \ Moderator & Rage Comicologist Y F Digital Archaeologist & Treasurer & Media Maid\
  \ andcallmeshirley Digital Archaeologist & Treasurer & Collection Butler \u25BC\
  \ + Request Editorship View All Editors Today's Top Image Galleries Assassination\
  \ of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing\
  \ Digital Circus About Our Story Site Rules Policies and Guidelines Credits Contact\
  \ Meme DB Memes Episodes News Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/feels-bad-man-sad-frog
template_id: sadfrog
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
