example:
- Historical Accuracy
- History Channel
- Aliens
- Historical Accuracy
keywords:
- null
name: Elmo Choosing Cocaine
overlay:
- angle: 0.0
  center_x: 0.15
  center_y: 0.34
  scale: 0.3
- angle: 0.0
  center_x: 0.73
  center_y: 0.41
  scale: 0.1
- angle: 0.0
  center_x: 0.15
  center_y: 0.8
  scale: 0.3
- angle: 0.0
  center_x: 0.73
  center_y: 0.9
  scale: 0.1
scraped_content: "Elmo Choosing Cocaine | Know Your Meme Hey! You must login or signup\
  \ first! Already a memeber? Login Now! Don't have an account? Sign up Now! Meme\
  \ Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Elmo Choosing Cocaine Added 5 years ago / Updated 4 years ago Confirmed 96,321\
  \ Part of a series on Sesame Street. [View Related Entries] View All 22 Images Navigation\
  \ About \u2022 Origin \u2022 Spread \u2022 Various Examples \u2022 Template \u2022\
  \ Search Interest \u2022 External References \u2022 Recent Images About Elmo Choosing\
  \ Cocaine is a two-panel object labeling image macro series featuring the Sesame\
  \ Street character Elmo standing between several pieces of fruit and a pile of white\
  \ powder. In the second panel, Elmo is face down in the pile of powder. The meme\
  \ typically expresses the decision to choose an unhealthy option over a healthy\
  \ one. Origin The exact origin of the photographs is currently unknown. On October\
  \ 13th, 2015, Memedroid[1] user TheDiamonx posted the two-panel image with the caption\
  \ \"Fruta o Coca.\" The post is the earliest known usage of the meme. It received\
  \ more than 1,400 points (9% upvoted) in a little over five years (shown below).\
  \ Spread On May 2nd, 2016, iFunny [2] user Cancer_me_mes posted the image with the\
  \ powder labeled \"memes.\" The post received more than 145,000 reactions and 1,200\
  \ comments in less than four years (shown below, left). Later that year, Facebook\
  \ [3] user snapwexleycore posted a variation that references the Star Wars prequel\
  \ series of films. The post received more than 115 reactions (shown below, center).\
  \ On April 21st, 2019, Redditor [4] Means-of-production posted the meme on the /r/Pikabu\
  \ subreddit. The post received more than 12,000 points (96% upvoted) and 615 comments\
  \ in less than one year (shown below, right). Various Examples Template Search Interest\
  \ Not Available. External References [1] Memedroid \u2013 Fruta o Coca [2] iFunny\
  \ \u2013 Cancer_me_mes' Post [3] Facebook \u2013 snapqexleycore's Post [4] Reddit\
  \ \u2013 /r/Pikabu elmo sesame street cocaine powder fruit children's televsion\
  \ muppet drugs columbian elmo fruits meme elmo powder meme cancer_me_mes thediamonx\
  \ memedroid snapwexleycore means-of-production Share Pin Related Entries 18 total\
  \ Elmo Rise Bert Is Evil! Jack Black's Octagon We Ride At Dawn Bitches View All\
  \ Related Entries Recent Images 22 total View All Images Recent Videos 0 total There\
  \ are no recent videos. Sign up for our Newsletter 7 Elmo Choosing Cocaine 96,321\
  \ 0 22 0 Part of a series on Sesame Street. [View Related Entries] Updated Aug 02,\
  \ 2020 at 05:52AM EDT by Y F. Added Nov 07, 2019 at 12:51PM EST by Matt. Like us\
  \ on Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the image gallery,\
  \ 'v' to view the video gallery, or 'r' to view a random entry. Meme Status Confirmed\
  \ Type: Image Macro Year 2015 Origin Memedroid Tags elmo, sesame street, cocaine,\
  \ powder, fruit, children's televsion, muppet, drugs, columbian, elmo fruits meme,\
  \ elmo powder meme, cancer_me_mes, thediamonx, memedroid, snapwexleycore, means-of-production\
  \ Additional References Meme Generator About Elmo Choosing Cocaine is a two-panel\
  \ object labeling image macro series featuring the Sesame Street character Elmo\
  \ standing between several pieces of fruit and a pile of white powder. In the second\
  \ panel, Elmo is face down in the pile of powder. The meme typically expresses the\
  \ decision to choose an unhealthy option over a healthy one. Origin The exact origin\
  \ of the photographs is currently unknown. On October 13th, 2015, Memedroid[1] user\
  \ TheDiamonx posted the two-panel image with the caption \"Fruta o Coca.\" The post\
  \ is the earliest known usage of the meme. It received more than 1,400 points (9%\
  \ upvoted) in a little over five years (shown below). Spread On May 2nd, 2016, iFunny\
  \ [2] user Cancer_me_mes posted the image with the powder labeled \"memes.\" The\
  \ post received more than 145,000 reactions and 1,200 comments in less than four\
  \ years (shown below, left). Later that year, Facebook [3] user snapwexleycore posted\
  \ a variation that references the Star Wars prequel series of films. The post received\
  \ more than 115 reactions (shown below, center). On April 21st, 2019, Redditor [4]\
  \ Means-of-production posted the meme on the /r/Pikabu subreddit. The post received\
  \ more than 12,000 points (96% upvoted) and 615 comments in less than one year (shown\
  \ below, right). Various Examples Template Search Interest Not Available. External\
  \ References [1] Memedroid \u2013 Fruta o Coca [2] iFunny \u2013 Cancer_me_mes'\
  \ Post [3] Facebook \u2013 snapqexleycore's Post [4] Reddit \u2013 /r/Pikabu Related\
  \ Entries 18 total Elmo Rise Bert Is Evil! Jack Black's Octagon We Ride At Dawn\
  \ Bitches Elmo Nuclear Bomb That's Real Fuckin' Neato Devastated Elmo Elmo vs. Rocco\
  \ Grover's F-Bomb Tickle Me Elmo Bert and Ernie Sexual Orientation Controversy Why\
  \ Is Oscar A Grouch? View All Related Entries Recent Videos There are no videos\
  \ currently available. + Add a Video Recent Images 22 total Elmo Choosing Cocaine\
  \ Uploaded by Jaimie Hamilton Elmo Choosing Cocaine Uploaded by Reddit Moments Elmo\
  \ Choosing Cocaine Uploaded by Reddit Moments Elmo Choosing Cocaine Uploaded by\
  \ Jaimie Hamilton Elmo Choosing Cocaine Uploaded by ianjuby Elmo Choosing Cocaine\
  \ Uploaded by dorukayhan Elmo Choosing Cocaine Uploaded by Quintolophon Elmo Choosing\
  \ Cocaine Uploaded by iran345 Elmo Choosing Cocaine Uploaded by FloofyZora Elmo\
  \ Choosing Cocaine Uploaded by Matt Elmo Choosing Cocaine Uploaded by Matt Elmo\
  \ Choosing Cocaine Uploaded by Matt + Add an Image View All Images Sign up for our\
  \ Newsletter + Add a Comment Comments (0) There are no comments currently available.\
  \ Display Comments Add a Comment Top Entries This Month Meme Saika Kawakita Smile\
  \ GIF Event Assassination of UnitedHealthcare CEO Person Luigi Mangione UHC CEO\
  \ Shooter Subculture The Ki Sisters Culture Pornography Site Whisper View More Suggest\
  \ a Change Edit History Entry Editors (2) Matt Secretary of Memes Y F Digital Archaeologist\
  \ & Treasurer & Media Maid + Request Editorship View All Editors Today's Top Image\
  \ Galleries Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team\
  \ Fortress 2 The Amazing Digital Circus About Our Story Site Rules Policies and\
  \ Guidelines Credits Contact Meme DB Memes Episodes News Staff Contact Extras! Style\
  \ Guide RSS Feeds"
source: https://knowyourmeme.com/memes/elmo-choosing-cocaine
template_id: elmo
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.24
  angle: 0.0
  color: white
  font: thick
  scale_x: 0.3
  scale_y: 0.25
  start: 0.0
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.35
  anchor_y: 0.21
  angle: 0.0
  color: white
  font: thick
  scale_x: 0.3
  scale_y: 0.17
  start: 0.0
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.59
  anchor_y: 0.39
  angle: 0.0
  color: white
  font: thick
  scale_x: 0.3
  scale_y: 0.1
  start: 0.0
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.0
  anchor_y: 0.69
  angle: 0.0
  color: white
  font: thick
  scale_x: 0.3
  scale_y: 0.25
  start: 0.0
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.59
  anchor_y: 0.87
  angle: 0.0
  color: white
  font: thick
  scale_x: 0.3
  scale_y: 0.1
  start: 0.0
  stop: 1.0
  style: default
text_zones: 5
