name: The Rent Is Too Damn High
source: http://knowyourmeme.com/memes/the-rent-is-too-damn-high-jimmy-mcmillan
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- the rent is
- too damn high
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About "The Rent is Too Damn High" is a political slogan adopted
  by Jimmy McMillan, a New York City resident and founder of the Rent Is Too Damn
  High Party who ran for New York’s state gubernatorial election in November 2010.
  McMillan''s catchphrase has inspired the snowclone template “The X is too damn high,”
  which is often featured in an Advice Animal image macro series featuring a photo
  of McMillan from the night of the gubernatorial debate. Origin Jimmy McMillan represented
  The Rent Is Too Damn High Party at the New York Gubernatorial debate on October
  18th, 2010. During the course of the debate, McMillan could be heard repeating his
  slogan several times. The same day, McMillan''s debate speech was uploaded to YouTube
  by news website The Daily Beast[15], which accumulated over 7.2 million views and
  21,000 comments within two years. "I represent ''The Rent Is Too Damn High Party.''
  People are working 8 hours a day and 40 hours a week and some a third job. Women
  can''t afford to take care of their children, feed their children breakfast, lunch
  and dinner. My main job is to provide a roof over your head, food on the table and
  money in your pocket. This is politics as usual, playing the silly game, and this
  is not gonna happen." As a Snowclone The slogan inspired the snowclone "The X is
  too damn high", which is used to complain about a variety of overwhelming frustrations.
  A screen capture of McMillan raising his fist was turned into an advice animal on
  the image macro generator Quickmeme,[1] many of which featured captions using the
  phrasal template. On August 6th, 2011, the first Quickmeme[13] upload was submitted
  to the /r/gaming[14] subreddit in a post titled "When other people try to use my
  computer", which included the caption "The mouse sensitivity / is too damn high!"
  Spread On October 19th, 2010, the YouTube clip was posted on several websites including
  The Huffington Post[2], BuzzFeed[4], Urlesque[5], Best Week Ever[6] and the Wall
  Street Journal.[7] On October 22nd, McMillan was featured in an episode of Ray William
  Johnson''s YouTube series Equals Three (shown left). On November 5th, the Gregory
  Brothers autotuned McMillan''s debate appearance (shown right) as part of their
  "Songify" web series. Within 18 months, the video received over 5.7 million views.
  On February 22nd, 2011, the Public Broadcasting Service[17] political blog reported
  that McMillan would be running for president in 2012 as a Republican and unveiled
  the new slogan “The deficit is too damn high.” A screen capture of McMillan raising
  his fist on the debate floor was turned into an advice animal on the image macro
  generator Quickmeme,[1] many of which featured captions using the phrasal template.
  On August 6th, 2011, the first Quickmeme[13] upload was submitted to the /r/gaming[14]
  subreddit in a post titled “When other people try to use my computer”, which included
  the caption “The mouse sensitivity / is too damn high!” Throughout 2011, the slogan
  evolved into the versatile snowclone “The X is too damn high” that can be used to
  complain about a wide range of frustrations. The Jimmy McMillan advice animal meme
  has continued to spread on Memebase[3], Tumblr[9], FunnyJunk[10] and the /r/AdviceAnimals
  subreddit.[8] As of May 23rd, 2012, the Jimmy McMillan Facebook[11] page has over
  11,000 likes, a Rent is Too Damn High Party Facebook[16] page has over 21,000 likes
  and the Quickmeme page has over 9,500 submissions. Notable Examples Image Macros
  Videos Occupy Wall Street Appearance On October 9th, 2011, the Gothamist[12] reported
  that McMillan had visited the Occupy Wall Street camp at Zuccotti Park several times
  during the first few weeks of protests, and posted a video of McMillan singing to
  the crowd. The article also linked to a video of McMillan singing to the crowd gathered
  at the site of the protest. Search Interest Search query volume for "rent is too
  damn high" peaked in October of 2010, the same month Jimmy McMillan''s appearance
  during the New York Gubernatorial debate was uploaded to YouTube. External References
  [1] Quickmeme – Jimmy McMillan [2] The Huffington Post – The Rent Is Too Damn High
  Party & Jimmy McMillan Debate In New York [3] Memebase – Jimmy McMillan [4] BuzzFeed
  – The Rent is Too Damn High Party Fliers [5] Urlesque Post: Rent is too Damn High
  Party Candidate Jimmy McMillan [6] Best Week Ever: Jimmy McMillan is Governor of
  the Internet [7] Wall Street Journal: Rent is too damn high single issue singular
  candidate [8] Reddit – r/adviceanimals too damn high [9] Tumblr – #too damn high
  [10] FunnyJunk – too damn high [11] Facebook – Jimmy McMillan [12] Gothamist – Jimmy
  McMillan Serenades Occupy Wall Street Protesters [13] Quickmeme – mouse sensitivity
  is too damn high [14] Reddit – When other people try to use my computer [15] The
  Daily Beast – The Daily Beast [16] Facebook – Rent is too Damn High Party [17] PBS
  – Rent Is Too Damn High Party founder, now a Republican, has a new slogan'
aside_content: MemeStatusConfirmedYear2010OriginNew York Gubernatorial DebateTagspolitics,debate,gubernatorial,speech,election,slogan,politician,pop
  culture,snowclone,phrasal template,kym special,occupyAdditional ReferencesWikipedia
added_at: '2010-10-19T16:07:24-04:00'
