example:
- the rent is
- too damn high
keywords:
- null
name: The Rent Is Too Damn High
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "The Rent is Too Damn High / Jimmy McMillan | Know Your Meme Namaste!\
  \ You must login or signup first! Already a memeber? Login Now! Don't have an account?\
  \ Sign up Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos\
  \ Submit \u2192 Images Trending Most Commented Most Favorited High Score Low Score\
  \ Most Viewed All Templates Upload an Image Articles News Explainers Collections\
  \ Interviews Meme Insider Magazine More Discord Newsletter Episodes Forums Meme\
  \ Store Login Abstract user icon Memes Categories Trending News Images Trending\
  \ Images Videos Trending Videos Editorials Meme Insider Magazine Newsletter Policies\
  \ and Guidelines Meme Store Old site Login Know Your Meme is the property of Literally\
  \ Media \xA92024 Literally Media. All Rights Reserved. This image Of Woman Confidently\
  \ Strolling Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years\
  \ Ago, This Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The\
  \ Anarchy Chess Memes Turns Two Years Old Today Phrase 'The Fridge Protects The\
  \ Snacks' A Growing Favorite Among Pickup Artist Influencers Jamie G, The Bosh British\
  \ Charva, Has Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also\
  \ Trending: Honey Extension Influencer Scam Renegade Raider Copypasta Assassination\
  \ of UnitedHealthcare CEO The Rent is Too Damn High / Jimmy McMillan Added 14 years\
  \ ago / Updated 8 days ago Confirmed 457,518 View All 102 Images Navigation About\
  \ \u2022 Origin \u2022 Spread \u2022 Notable Examples \u2022 Search Interest \u2022\
  \ External References \u2022 Recent Images \u2022 Recent Videos About \"The Rent\
  \ is Too Damn High\" is a political slogan adopted by Jimmy McMillan, a New York\
  \ City resident and founder of the Rent Is Too Damn High Party who ran for New York\u2019\
  s state gubernatorial election in November 2010. McMillan's catchphrase has inspired\
  \ the snowclone template \u201CThe X is too damn high,\u201D which is often featured\
  \ in an Advice Animal image macro series featuring a photo of McMillan from the\
  \ night of the gubernatorial debate. Origin Jimmy McMillan represented The Rent\
  \ Is Too Damn High Party at the New York Gubernatorial debate on October 18th, 2010.\
  \ During the course of the debate, McMillan could be heard repeating his slogan\
  \ several times. The same day, McMillan's debate speech was uploaded to YouTube\
  \ by news website The Daily Beast[15], which accumulated over 7.2 million views\
  \ and 21,000 comments within two years. \"I represent 'The Rent Is Too Damn High\
  \ Party.' People are working 8 hours a day and 40 hours a week and some a third\
  \ job. Women can't afford to take care of their children, feed their children breakfast,\
  \ lunch and dinner. My main job is to provide a roof over your head, food on the\
  \ table and money in your pocket. This is politics as usual, playing the silly game,\
  \ and this is not gonna happen.\" As a Snowclone The slogan inspired the snowclone\
  \ \"The X is too damn high\", which is used to complain about a variety of overwhelming\
  \ frustrations. A screen capture of McMillan raising his fist was turned into an\
  \ advice animal on the image macro generator Quickmeme,[1] many of which featured\
  \ captions using the phrasal template. On August 6th, 2011, the first Quickmeme[13]\
  \ upload was submitted to the /r/gaming[14] subreddit in a post titled \"When other\
  \ people try to use my computer\", which included the caption \"The mouse sensitivity\
  \ / is too damn high!\" Spread On October 19th, 2010, the YouTube clip was posted\
  \ on several websites including The Huffington Post[2], BuzzFeed[4], Urlesque[5],\
  \ Best Week Ever[6] and the Wall Street Journal.[7] On October 22nd, McMillan was\
  \ featured in an episode of Ray William Johnson's YouTube series Equals Three (shown\
  \ left). On November 5th, the Gregory Brothers autotuned McMillan's debate appearance\
  \ (shown right) as part of their \"Songify\" web series. Within 18 months, the video\
  \ received over 5.7 million views. On February 22nd, 2011, the Public Broadcasting\
  \ Service[17] political blog reported that McMillan would be running for president\
  \ in 2012 as a Republican and unveiled the new slogan \u201CThe deficit is too damn\
  \ high.\u201D A screen capture of McMillan raising his fist on the debate floor\
  \ was turned into an advice animal on the image macro generator Quickmeme,[1] many\
  \ of which featured captions using the phrasal template. On August 6th, 2011, the\
  \ first Quickmeme[13] upload was submitted to the /r/gaming[14] subreddit in a post\
  \ titled \u201CWhen other people try to use my computer\u201D, which included the\
  \ caption \u201CThe mouse sensitivity / is too damn high!\u201D Throughout 2011,\
  \ the slogan evolved into the versatile snowclone \u201CThe X is too damn high\u201D\
  \ that can be used to complain about a wide range of frustrations. The Jimmy McMillan\
  \ advice animal meme has continued to spread on Memebase[3], Tumblr[9], FunnyJunk[10]\
  \ and the /r/AdviceAnimals subreddit.[8] As of May 23rd, 2012, the Jimmy McMillan\
  \ Facebook[11] page has over 11,000 likes, a Rent is Too Damn High Party Facebook[16]\
  \ page has over 21,000 likes and the Quickmeme page has over 9,500 submissions.\
  \ Notable Examples Image Macros Videos Occupy Wall Street Appearance On October\
  \ 9th, 2011, the Gothamist[12] reported that McMillan had visited the Occupy Wall\
  \ Street camp at Zuccotti Park several times during the first few weeks of protests,\
  \ and posted a video of McMillan singing to the crowd. The article also linked to\
  \ a video of McMillan singing to the crowd gathered at the site of the protest.\
  \ Search Interest Search query volume for \"rent is too damn high\" peaked in October\
  \ of 2010, the same month Jimmy McMillan's appearance during the New York Gubernatorial\
  \ debate was uploaded to YouTube. External References [1] Quickmeme \u2013 Jimmy\
  \ McMillan [2] The Huffington Post \u2013 The Rent Is Too Damn High Party & Jimmy\
  \ McMillan Debate In New York [3] Memebase \u2013 Jimmy McMillan [4] BuzzFeed \u2013\
  \ The Rent is Too Damn High Party Fliers [5] Urlesque Post: Rent is too Damn High\
  \ Party Candidate Jimmy McMillan [6] Best Week Ever: Jimmy McMillan is Governor\
  \ of the Internet [7] Wall Street Journal: Rent is too damn high single issue singular\
  \ candidate [8] Reddit \u2013 r/adviceanimals too damn high [9] Tumblr \u2013 #too\
  \ damn high [10] FunnyJunk \u2013 too damn high [11] Facebook \u2013 Jimmy McMillan\
  \ [12] Gothamist \u2013 Jimmy McMillan Serenades Occupy Wall Street Protesters [13]\
  \ Quickmeme \u2013 mouse sensitivity is too damn high [14] Reddit \u2013 When other\
  \ people try to use my computer [15] The Daily Beast \u2013 The Daily Beast [16]\
  \ Facebook \u2013 Rent is too Damn High Party [17] PBS \u2013 Rent Is Too Damn High\
  \ Party founder, now a Republican, has a new slogan politics debate gubernatorial\
  \ speech election slogan politician pop culture snowclone phrasal template kym special\
  \ occupy Share Pin Recent Images 102 total View All Images Recent Videos 6 total\
  \ View All Videos Sign up for our Newsletter Load 92 Comments Comments 92 total\
  \ 74 The Rent is Too Damn High / Jimmy McMillan 457,518 6 102 92 Updated Dec 15,\
  \ 2024 at 06:35PM EST by LiterallyAustin. Added Oct 19, 2010 at 04:07PM EDT by Brad.\
  \ Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the\
  \ image gallery, 'v' to view the video gallery, or 'r' to view a random entry. Meme\
  \ Status Confirmed Year 2010 Origin New York Gubernatorial Debate Tags politics,\
  \ debate, gubernatorial, speech, election, slogan, politician, pop culture, snowclone,\
  \ phrasal template, kym special, occupy Additional References Wikipedia About \"\
  The Rent is Too Damn High\" is a political slogan adopted by Jimmy McMillan, a New\
  \ York City resident and founder of the Rent Is Too Damn High Party who ran for\
  \ New York\u2019s state gubernatorial election in November 2010. McMillan's catchphrase\
  \ has inspired the snowclone template \u201CThe X is too damn high,\u201D which\
  \ is often featured in an Advice Animal image macro series featuring a photo of\
  \ McMillan from the night of the gubernatorial debate. Origin Jimmy McMillan represented\
  \ The Rent Is Too Damn High Party at the New York Gubernatorial debate on October\
  \ 18th, 2010. During the course of the debate, McMillan could be heard repeating\
  \ his slogan several times. The same day, McMillan's debate speech was uploaded\
  \ to YouTube by news website The Daily Beast[15], which accumulated over 7.2 million\
  \ views and 21,000 comments within two years. \"I represent 'The Rent Is Too Damn\
  \ High Party.' People are working 8 hours a day and 40 hours a week and some a third\
  \ job. Women can't afford to take care of their children, feed their children breakfast,\
  \ lunch and dinner. My main job is to provide a roof over your head, food on the\
  \ table and money in your pocket. This is politics as usual, playing the silly game,\
  \ and this is not gonna happen.\" As a Snowclone The slogan inspired the snowclone\
  \ \"The X is too damn high\", which is used to complain about a variety of overwhelming\
  \ frustrations. A screen capture of McMillan raising his fist was turned into an\
  \ advice animal on the image macro generator Quickmeme,[1] many of which featured\
  \ captions using the phrasal template. On August 6th, 2011, the first Quickmeme[13]\
  \ upload was submitted to the /r/gaming[14] subreddit in a post titled \"When other\
  \ people try to use my computer\", which included the caption \"The mouse sensitivity\
  \ / is too damn high!\" Spread On October 19th, 2010, the YouTube clip was posted\
  \ on several websites including The Huffington Post[2], BuzzFeed[4], Urlesque[5],\
  \ Best Week Ever[6] and the Wall Street Journal.[7] On October 22nd, McMillan was\
  \ featured in an episode of Ray William Johnson's YouTube series Equals Three (shown\
  \ left). On November 5th, the Gregory Brothers autotuned McMillan's debate appearance\
  \ (shown right) as part of their \"Songify\" web series. Within 18 months, the video\
  \ received over 5.7 million views. On February 22nd, 2011, the Public Broadcasting\
  \ Service[17] political blog reported that McMillan would be running for president\
  \ in 2012 as a Republican and unveiled the new slogan \u201CThe deficit is too damn\
  \ high.\u201D A screen capture of McMillan raising his fist on the debate floor\
  \ was turned into an advice animal on the image macro generator Quickmeme,[1] many\
  \ of which featured captions using the phrasal template. On August 6th, 2011, the\
  \ first Quickmeme[13] upload was submitted to the /r/gaming[14] subreddit in a post\
  \ titled \u201CWhen other people try to use my computer\u201D, which included the\
  \ caption \u201CThe mouse sensitivity / is too damn high!\u201D Throughout 2011,\
  \ the slogan evolved into the versatile snowclone \u201CThe X is too damn high\u201D\
  \ that can be used to complain about a wide range of frustrations. The Jimmy McMillan\
  \ advice animal meme has continued to spread on Memebase[3], Tumblr[9], FunnyJunk[10]\
  \ and the /r/AdviceAnimals subreddit.[8] As of May 23rd, 2012, the Jimmy McMillan\
  \ Facebook[11] page has over 11,000 likes, a Rent is Too Damn High Party Facebook[16]\
  \ page has over 21,000 likes and the Quickmeme page has over 9,500 submissions.\
  \ Notable Examples Image Macros Videos Occupy Wall Street Appearance On October\
  \ 9th, 2011, the Gothamist[12] reported that McMillan had visited the Occupy Wall\
  \ Street camp at Zuccotti Park several times during the first few weeks of protests,\
  \ and posted a video of McMillan singing to the crowd. The article also linked to\
  \ a video of McMillan singing to the crowd gathered at the site of the protest.\
  \ Search Interest Search query volume for \"rent is too damn high\" peaked in October\
  \ of 2010, the same month Jimmy McMillan's appearance during the New York Gubernatorial\
  \ debate was uploaded to YouTube. External References [1] Quickmeme \u2013 Jimmy\
  \ McMillan [2] The Huffington Post \u2013 The Rent Is Too Damn High Party & Jimmy\
  \ McMillan Debate In New York [3] Memebase \u2013 Jimmy McMillan [4] BuzzFeed \u2013\
  \ The Rent is Too Damn High Party Fliers [5] Urlesque Post: Rent is too Damn High\
  \ Party Candidate Jimmy McMillan [6] Best Week Ever: Jimmy McMillan is Governor\
  \ of the Internet [7] Wall Street Journal: Rent is too damn high single issue singular\
  \ candidate [8] Reddit \u2013 r/adviceanimals too damn high [9] Tumblr \u2013 #too\
  \ damn high [10] FunnyJunk \u2013 too damn high [11] Facebook \u2013 Jimmy McMillan\
  \ [12] Gothamist \u2013 Jimmy McMillan Serenades Occupy Wall Street Protesters [13]\
  \ Quickmeme \u2013 mouse sensitivity is too damn high [14] Reddit \u2013 When other\
  \ people try to use my computer [15] The Daily Beast \u2013 The Daily Beast [16]\
  \ Facebook \u2013 Rent is too Damn High Party [17] PBS \u2013 Rent Is Too Damn High\
  \ Party founder, now a Republican, has a new slogan Recent Videos 6 total Jimmy\
  \ McMillan running for Ma... The Rent is Too Damn High / J... Uploaded by amanda\
  \ b. Jimmy McMillan \"Rent Is Too D... The Rent is Too Damn High / J... Uploaded\
  \ by Brad The Rent Is Too Damn High Par... The Rent is Too Damn High / J... Uploaded\
  \ by Brad Rent Is Too Damn High Party M... The Rent is Too Damn High / J... Uploaded\
  \ by Brad Auto-tune the: \"Rents Too Dam... The Rent is Too Damn High / J... Uploaded\
  \ by Darkwiz666 Rent: Too Damn High! Song The Rent is Too Damn High / J... Uploaded\
  \ by Dwight Kurt Schrute + Add a Video Recent Images 102 total The Rent is Too Damn\
  \ High / J... Uploaded by Reddit Moments The Rent is Too Damn High / J... Uploaded\
  \ by Reddit Moments The Rent is Too Damn High / J... Uploaded by Reddit Moments\
  \ The Rent is Too Damn High / J... Uploaded by Reddit Moments The Rent is Too Damn\
  \ High / J... Uploaded by Rebecca Rhodes The Rent is Too Damn High / J... Uploaded\
  \ by MasterChi The Rent is Too Damn High / J... Uploaded by Y F The Rent is Too\
  \ Damn High / J... Uploaded by erosennin789 The Rent is Too Damn High / J... Uploaded\
  \ by Mr. Skungeous The Rent is Too Damn High / J... Uploaded by Manifestopheles\
  \ The Rent is Too Damn High / J... Uploaded by Emperor Palpitoad The Rent is Too\
  \ Damn High / J... Uploaded by Andr\xE9 Niemand + Add an Image View All Images Sign\
  \ up for our Newsletter Top Comments Delete Sensitive Covetous Oct 20, 2011 at 01:49PM\
  \ EDT Fact : good facial hair makes your arguments more compelling Fact : Mr. McMillan\
  \ has excellent facial hair Fact : everything that Mr. McMillan says will be so\
  \ compelling that it will be automatically true. For example, if Mr. McMillian says\
  \ that unicorns do exist, unicorns will suddenly appear out of nowhere as if they\
  \ had been ther all that time. +16 Reply Delete Sensitive Nazi Pootawn May 23, 2012\
  \ at 08:02PM EDT Says it's confirmed on front page. Isn't on the its own page. +12\
  \ Reply + Add a Comment Comments (92) Display Comments Add a Comment Top Entries\
  \ This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (4) Brad Digital\
  \ Archaeologist & Treasurer & Pundit & Gallery Housekeeper Don Administrator & Meme\
  \ Daddy amanda b. Meme Librarian Y F Digital Archaeologist & Treasurer & Media Maid\
  \ + Request Editorship View All Editors Today's Top Image Galleries Assassination\
  \ of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing\
  \ Digital Circus About Our Story Site Rules Policies and Guidelines Credits Contact\
  \ Meme DB Memes Episodes News Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/the-rent-is-too-damn-high-jimmy-mcmillan
template_id: toohigh
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
