example:
- ''
- I have no memory of this place
keywords:
- Lord of the Rings
name: Confused Gandalf
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Confused Gandalf | Know Your Meme Sup! You must login or signup\
  \ first! Already a memeber? Login Now! Don't have an account? Sign up Now! Meme\
  \ Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Confused Gandalf Added 8 years ago / Updated 6 years ago Submission 47,204\
  \ Part of a series on Lord Of The Rings. [View Related Entries] View All 19 Images\
  \ Navigation About \u2022 Origin \u2022 Spread \u2022 Various Examples \u2022 Search\
  \ Interest \u2022 External references \u2022 Recent Images About Confused Gandalf\
  \ refers to an image macro series featuring a picture of the character Gandalf from\
  \ a scene in the 2001 film The Lord of the Rings: The Fellowship of the Ring, which\
  \ is typically used as a reaction image to convey feelings of uncertainty or unfamiliarity.\
  \ Origin In the 2001 film Lord of the Rings: The Fellowship of the Ring, Gandalf\
  \ remarks that he has \"no memory of this place\" while passing through the Mines\
  \ of Moria (shown below). On November 30th, 2011, Redditor jonatfuckdotorg posted\
  \ a 3-pane image macro of the scene with the caption \"I have no memory of this\
  \ place\" in a post titled \"Back in the office the morning after the holiday break\"\
  \ (shown below). Prior to being archived, the post gained over 1,500 votes (95%\
  \ upvoted) and 70 comments on the /r/funny[1] subreddit. Spread On Reddit, the image\
  \ macro has been often used to indicate one's confusion upon encountering a high-volume\
  \ influx of posts related to a trending topic after it has already peaked or during\
  \ its plateau. On December 8th, 2011, Redditor javabrewer posted an edited version\
  \ of the three-pane image macro with the caption \u201CI have no memory of this\
  \ codebase\u201D to /r/funny,[2] where it garnered more than 1,000 votes (90% upvoted)\
  \ and 60 comments before it was archived (shown below, left). On July 1st, 2012,\
  \ Redditor Alamlion posted the original Confused Gandalf image macro in a post titled\
  \ \u201CHow I felt as a kid when my mom cleaned my room.\u201D[4] On September 13th,\
  \ Redditor sidjun posted a mashup of Confused Gandalf with \"Am I the Only One Around\
  \ Here\" to /r/AdviceAnimals[6] (shown below, right). On March 16th, 2013, several\
  \ Redditors posted more than a dozen of Confused Gandalf image macros with the question\
  \ \"safe?\" in response to a flurry of posts and in-jokes about The Mysterious Vault\
  \ that appeared on the site's frontpage (shown below). On March 20th, Tumblr[7]\
  \ user memecenterz posted a Confused Gandalf image macro mocking the use of quiet\
  \ music in film to build tension (shown below, left). In May 2013, a page for \u201C\
  Confused Gandalf\u201D was created on Quickmeme.[5] On February 6th, 2014, Redditor\
  \ Ashwalla submitted a Confused Gandalf image macro with the caption \u201CDid I\
  \ pay my bills?\u201D to /r/AdviceAnimals[3] (shown below, right). Before the post\
  \ was archived, it received over 3,000 votes (95% upvoted) and 500 comments. Various\
  \ Examples Search Interest External references [1] Reddit \u2013 back in the office\
  \ the morning after the holiday break [2] Reddit \u2013 I was the first developer\
  \ in my company [3] Reddit \u2013 When theres actually money in my bank account\
  \ [4] Reddit \u2013 How I felt as a kid [5] Quickmeme \u2013 Confused Gandalf [6]\
  \ Reddit \u2013 Being that Im not a whiny meme connoisseur [7] Tumblr \u2013 memecenterz\
  \ gandalf lord of the rings lotr movies quotes reaction image Share Pin Related\
  \ Entries 41 total One Does Not Simply Walk Into... Pondering My Orb You Have My\
  \ Sword, and My Bow... They're Taking the Hobbits to... View All Related Entries\
  \ Recent Images 19 total View All Images Recent Videos 0 total There are no recent\
  \ videos. Sign up for our Newsletter Load 3 Comments Comments 3 total 8 Confused\
  \ Gandalf 47,204 0 19 3 Part of a series on Lord Of The Rings. [View Related Entries]\
  \ Updated Feb 14, 2018 at 05:08AM EST by Y F. Added Jan 22, 2016 at 09:36PM EST\
  \ by Mom Rivers. Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i'\
  \ to view the image gallery, 'v' to view the video gallery, or 'r' to view a random\
  \ entry. This submission is currently being researched & evaluated! You can help\
  \ confirm this entry by contributing facts, media, and other evidence of notability\
  \ and mutation. Meme Status Submission Year 2011 Origin The Fellowship of the Ring\
  \ Tags gandalf, lord of the rings, lotr, movies, quotes, reaction image About Confused\
  \ Gandalf refers to an image macro series featuring a picture of the character Gandalf\
  \ from a scene in the 2001 film The Lord of the Rings: The Fellowship of the Ring,\
  \ which is typically used as a reaction image to convey feelings of uncertainty\
  \ or unfamiliarity. Origin In the 2001 film Lord of the Rings: The Fellowship of\
  \ the Ring, Gandalf remarks that he has \"no memory of this place\" while passing\
  \ through the Mines of Moria (shown below). On November 30th, 2011, Redditor jonatfuckdotorg\
  \ posted a 3-pane image macro of the scene with the caption \"I have no memory of\
  \ this place\" in a post titled \"Back in the office the morning after the holiday\
  \ break\" (shown below). Prior to being archived, the post gained over 1,500 votes\
  \ (95% upvoted) and 70 comments on the /r/funny[1] subreddit. Spread On Reddit,\
  \ the image macro has been often used to indicate one's confusion upon encountering\
  \ a high-volume influx of posts related to a trending topic after it has already\
  \ peaked or during its plateau. On December 8th, 2011, Redditor javabrewer posted\
  \ an edited version of the three-pane image macro with the caption \u201CI have\
  \ no memory of this codebase\u201D to /r/funny,[2] where it garnered more than 1,000\
  \ votes (90% upvoted) and 60 comments before it was archived (shown below, left).\
  \ On July 1st, 2012, Redditor Alamlion posted the original Confused Gandalf image\
  \ macro in a post titled \u201CHow I felt as a kid when my mom cleaned my room.\u201D\
  [4] On September 13th, Redditor sidjun posted a mashup of Confused Gandalf with\
  \ \"Am I the Only One Around Here\" to /r/AdviceAnimals[6] (shown below, right).\
  \ On March 16th, 2013, several Redditors posted more than a dozen of Confused Gandalf\
  \ image macros with the question \"safe?\" in response to a flurry of posts and\
  \ in-jokes about The Mysterious Vault that appeared on the site's frontpage (shown\
  \ below). On March 20th, Tumblr[7] user memecenterz posted a Confused Gandalf image\
  \ macro mocking the use of quiet music in film to build tension (shown below, left).\
  \ In May 2013, a page for \u201CConfused Gandalf\u201D was created on Quickmeme.[5]\
  \ On February 6th, 2014, Redditor Ashwalla submitted a Confused Gandalf image macro\
  \ with the caption \u201CDid I pay my bills?\u201D to /r/AdviceAnimals[3] (shown\
  \ below, right). Before the post was archived, it received over 3,000 votes (95%\
  \ upvoted) and 500 comments. Various Examples Search Interest External references\
  \ [1] Reddit \u2013 back in the office the morning after the holiday break [2] Reddit\
  \ \u2013 I was the first developer in my company [3] Reddit \u2013 When theres actually\
  \ money in my bank account [4] Reddit \u2013 How I felt as a kid [5] Quickmeme \u2013\
  \ Confused Gandalf [6] Reddit \u2013 Being that Im not a whiny meme connoisseur\
  \ [7] Tumblr \u2013 memecenterz Related Entries 41 total One Does Not Simply Walk\
  \ Into Mordor Pondering My Orb You Have My Sword, and My Bow, and My Axe They're\
  \ Taking the Hobbits to Isengard You Shall Not Pass!!! All Right Then, Keep Your\
  \ Secrets Figwit You Have No Power Here! What Do Your Elf Eyes See? Gandalf's \"\
  So It Begins\" Viggo Mortensen Broke His Toe In 'The Two Towers' #Orcposting View\
  \ All Related Entries Recent Videos There are no videos currently available. + Add\
  \ a Video Recent Images 19 total Confused Gandalf Uploaded by Reddit Moments Confused\
  \ Gandalf Uploaded by Triplem Confused Gandalf Uploaded by eppursilemur Confused\
  \ Gandalf Uploaded by Don Confused Gandalf Uploaded by Don Confused Gandalf Uploaded\
  \ by Don Confused Gandalf Uploaded by Don Confused Gandalf Uploaded by Don Confused\
  \ Gandalf Uploaded by Mom Rivers Confused Gandalf Uploaded by Mom Rivers Confused\
  \ Gandalf Uploaded by Mom Rivers Confused Gandalf Uploaded by Mom Rivers + Add an\
  \ Image View All Images Sign up for our Newsletter + Add a Comment Comments (3)\
  \ Display Comments Add a Comment Top Entries This Month Meme Saika Kawakita Smile\
  \ GIF Event Assassination of UnitedHealthcare CEO Person Luigi Mangione UHC CEO\
  \ Shooter Subculture The Ki Sisters Culture Pornography Site Whisper View More Suggest\
  \ a Change Edit History Entry Editors (5) Mom Rivers Database Moderator & Political\
  \ Analyst Samekichi Kiseki Sr. Entry Moderator & Community Artist Don Administrator\
  \ & Meme Daddy Brad Digital Archaeologist & Treasurer & Pundit & Gallery Housekeeper\
  \ Y F Digital Archaeologist & Treasurer & Media Maid \u25BC + Request Editorship\
  \ View All Editors Today's Top Image Galleries Assassination of UnitedHealthcare\
  \ CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing Digital Circus About\
  \ Our Story Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes\
  \ News Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/confused-gandalf
template_id: gandalf
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
