name: Confused Gandalf
source: http://knowyourmeme.com/memes/confused-gandalf
keywords:
- Lord of the Rings
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- ''
- I have no memory of this place
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Confused Gandalf refers to an image macro series featuring
  a picture of the character Gandalf from a scene in the 2001 film The Lord of the
  Rings: The Fellowship of the Ring, which is typically used as a reaction image to
  convey feelings of uncertainty or unfamiliarity. Origin In the 2001 film Lord of
  the Rings: The Fellowship of the Ring, Gandalf remarks that he has "no memory of
  this place" while passing through the Mines of Moria (shown below). On November
  30th, 2011, Redditor jonatfuckdotorg posted a 3-pane image macro of the scene with
  the caption "I have no memory of this place" in a post titled "Back in the office
  the morning after the holiday break" (shown below). Prior to being archived, the
  post gained over 1,500 votes (95% upvoted) and 70 comments on the /r/funny[1] subreddit.
  Spread On Reddit, the image macro has been often used to indicate one''s confusion
  upon encountering a high-volume influx of posts related to a trending topic after
  it has already peaked or during its plateau. On December 8th, 2011, Redditor javabrewer
  posted an edited version of the three-pane image macro with the caption “I have
  no memory of this codebase” to /r/funny,[2] where it garnered more than 1,000 votes
  (90% upvoted) and 60 comments before it was archived (shown below, left). On July
  1st, 2012, Redditor Alamlion posted the original Confused Gandalf image macro in
  a post titled “How I felt as a kid when my mom cleaned my room.”[4] On September
  13th, Redditor sidjun posted a mashup of Confused Gandalf with "Am I the Only One
  Around Here" to /r/AdviceAnimals[6] (shown below, right). On March 16th, 2013, several
  Redditors posted more than a dozen of Confused Gandalf image macros with the question
  "safe?" in response to a flurry of posts and in-jokes about The Mysterious Vault
  that appeared on the site''s frontpage (shown below). On March 20th, Tumblr[7] user
  memecenterz posted a Confused Gandalf image macro mocking the use of quiet music
  in film to build tension (shown below, left). In May 2013, a page for “Confused
  Gandalf” was created on Quickmeme.[5] On February 6th, 2014, Redditor Ashwalla submitted
  a Confused Gandalf image macro with the caption “Did I pay my bills?” to /r/AdviceAnimals[3]
  (shown below, right). Before the post was archived, it received over 3,000 votes
  (95% upvoted) and 500 comments. Various Examples Search Interest External references
  [1] Reddit – back in the office the morning after the holiday break [2] Reddit –
  I was the first developer in my company [3] Reddit – When theres actually money
  in my bank account [4] Reddit – How I felt as a kid [5] Quickmeme – Confused Gandalf
  [6] Reddit – Being that Im not a whiny meme connoisseur [7] Tumblr – memecenterz'
aside_content: MemeStatusSubmissionYear2011OriginThe Fellowship of the RingTagsgandalf,lord
  of the rings,lotr,movies,quotes,reaction image
added_at: '2016-01-22T21:36:59-05:00'
