example:
- I supported my sister's abortion
- Still would have been cool to be a dad
keywords:
- null
name: Almost Politically Correct Redneck
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Almost Politically Correct Redneck | Know Your Meme Hauu! You must\
  \ login or signup first! Already a memeber? Login Now! Don't have an account? Sign\
  \ up Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos\
  \ Submit \u2192 Images Trending Most Commented Most Favorited High Score Low Score\
  \ Most Viewed All Templates Upload an Image Articles News Explainers Collections\
  \ Interviews Meme Insider Magazine More Discord Newsletter Episodes Forums Meme\
  \ Store Login Abstract user icon Memes Categories Trending News Images Trending\
  \ Images Videos Trending Videos Editorials Meme Insider Magazine Newsletter Policies\
  \ and Guidelines Meme Store Old site Login Know Your Meme is the property of Literally\
  \ Media \xA92024 Literally Media. All Rights Reserved. This image Of Woman Confidently\
  \ Strolling Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years\
  \ Ago, This Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The\
  \ Anarchy Chess Memes Turns Two Years Old Today Phrase 'The Fridge Protects The\
  \ Snacks' A Growing Favorite Among Pickup Artist Influencers Jamie G, The Bosh British\
  \ Charva, Has Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also\
  \ Trending: Honey Extension Influencer Scam Renegade Raider Copypasta Assassination\
  \ of UnitedHealthcare CEO Almost Politically Correct Redneck Added 12 years ago\
  \ / Updated 17 days ago Confirmed 930,838 Part of a series on Nationality Stereotypes.\
  \ [View Related Entries] View All 84 Images Featured Episode Navigation About \u2022\
  \ Origin \u2022 Spread \u2022 Search Interest \u2022 External References \u2022\
  \ Recent Images \u2022 Recent Videos About Almost Politically Correct Redneck is\
  \ an advice animal image macro series featuring a photo of a young shirtless man\
  \ with a mullet hairstyle standing next to a pickup truck. The captions typically\
  \ portray the man as earnest and well-meaning but unaware of his own stereotypical\
  \ redneck prejudice. Origin The man behind the photo is Zach Downey, a photographer\
  \ who worked at the Lilly Library at Indiana University. According to a post on\
  \ Reddit[18], Downey cut his hair into the mullet as a joke for his Halloween costume\
  \ back in 2003. At the time, his wife, Tricia, snapped a quick shot of him the morning\
  \ after Halloween and uploaded it online where it spread and became a meme. \"Two\
  \ of my friends were going out on Halloween as superheroes,\" Downey recalled. \"\
  They had special clothing, glitter on their faces, they went to a lot of trouble.\
  \ I got some clippers and cut my hair in 10 minutes and I was the hit. The mullet\
  \ is associated with rednecks or hillbillies for sure,\" he said. \"I'm not like\
  \ that, but I mean no disrespect. I have friends that I'd call and they'd call themselves\
  \ rednecks or hillbillies. That's fine. It's just not me.\" According to the post,\
  \ Downey had the haircut for just about 16 hours. His wife posed him in front of\
  \ friend Jen Owen's 1979 GMC truck and took some photos the next day. Then they\
  \ hauled out the clippers, cut the mullet into a mohawk, took more photos, shaved\
  \ his head completely and snapped a few more. \"Actually, and this was the plan\
  \ all along, I donated my hair to Locks of Love. It's kind of funny that some young\
  \ person out there actually benefited from my haircut,\" Downey said. \"Mullets\
  \ of Love?\" Originally uploaded to a mullet photo gallery website by a friend,\
  \ it was named \"Mullet of the Month\" on the site, and after that, it spread to\
  \ other places online. The photo was then used as early as July 2005 as a response\
  \ photo on the internet humor site Fark. On July 3rd, 2005, Fark user sens posted\
  \ the image[9] in response to a story claiming Toyota would be building a plant\
  \ in Canada because they did not want to train southern Americans. The photo was\
  \ used on Fark in this manner on at least 2 other occasions in 2005[10] and 2009.[2]\
  \ On May 12th, 2012, Redditor IanL27 submitted an image macro to the Advice Animals\
  \ subreddit in a post titled \"I present to you: Somewhat Politically Correct Redneck\"\
  [11], which featured the caption \"Not against gay marriage / unless the couple\
  \ is colored.\" Within three days the post received over 3,700 up votes, earning\
  \ 1124 points overall. Spread On May 13th, 2012, Redditor larkable submitted a post\
  \ titled \"A kid at my school was getting picked on for being a 'faggot', so this\
  \ guy gets up and grabs the bully by the throat and says this\"[1] to the Advice\
  \ Animals subreddit, containing an image macro with the caption \"What's wrong /\
  \ with faggots, queer?\" This post gained nearly 17,000 upvotes, 1971 points overall\
  \ and nearly 600 comments. The following day, men's humor blog Guyism[7] published\
  \ a post titled \"New Meme You Should Know: Almost Politically Correct Redneck\"\
  , which reported that the meme was born out of North Carolina's gay marriage ban\
  \ earlier that week. The same day, BodyBuilding Forums[4] member BBmisc420196 posted\
  \ a thread titled \"New meme: Almost politically correct redneck\", which included\
  \ several example image macros and received 23 responses in 24 hours. Also on May\
  \ 14th, an example with caption \"I fully support the right of my daughter to express\
  \ her love for her girlfriend in public / it's pretty hot\" was posted on the Internet\
  \ humor site FunnyJunk[5] and a Facebook[3] page for \"Almost Politically Correct\
  \ Redneck\" was created. Series of Almost Politically Correct Redneck instances\
  \ have also been shared on BroBible[16], Uproxx[6] and Slacktory.[13] In November\
  \ 2012, the image macro series came in at #17 on Buzzfeed's list of the Best New\
  \ Memes of 2012.[17] As of December, 2012, the Quickmeme[8] page has received more\
  \ than 5000 submissions and the Meme Generator[12] page hosts an additional thousand.\
  \ There have also been 760 submissions of Almost Politically Correct Redneck to\
  \ Reddit[14] and new instances continue to be posted on Tumblr.[15] Notable Examples\
  \ Search Interest External References [1] Reddit \u2013 A Kid at my school was getting\
  \ picked on [2] Fark \u2013 It's not every day you see a sheep dangling from a telephone\
  \ wire \u2013 but today happens to be that day [3] Facebook \u2013 Almost Politically\
  \ Correct Redneck [4] BodyBuilding \u2013 New meme \u2013 Almost politically correct\
  \ redneck [5] FunnyJunk \u2013 Almost Politically Correct Redneck [6] UpRoxx \u2013\
  \ Almost Politically Correct Redneck is Here To Offend Everyone [7] Guyism (now\
  \ BroBible) \u2013 ALMOST POLITICALLY CORRECT REDNECK [8] Quickmeme \u2013 Almost\
  \ politically correct redneck [9] Fark \u2013 Toyota building new plant in Canada\
  \ despite massive subsidy offers from American states. Reason: southern Americans\
  \ too dumb and illiterate to train; need directions in pictorial form [10] Fark\
  \ \u2013 Hot diggity!!! Now that thar's a dang fine mullet!! [11] Reddit \u2013\
  \ I present to you: Somewhat Politically Correct Redneck [12] Meme Generator via\
  \ WayBack Machine- Almost Politically Correct Redneck [13] Slacktory (via Wayback\
  \ Machine) \u2013 Almost Politically Correct Redneck: A New Advice Meme [14] Reddit\
  \ \u2013 Search results for \"almost politically correct redneck\" [15] Tumblr \u2013\
  \ Posts tagged \"almost politically correct redneck\" [16] BroBible \u2013 The \u2018\
  Almost Politically Correct Redneck\u2019 Meme Is a Kenny Powers Greatest Hits Album\
  \ In Meme Form [17] Buzzfeed \u2013 The 32 Best New Memes Of 2012 [18] Reddit \u2013\
  \ r/AdviceAnimals image macro redneck reddit advice animal hill billy #2 entry of\
  \ may 2012 usa sens mullet ianl27 larkable guyism bbmisc420196 brobible uproxx slacktory\
  \ zach downey locks of love political correctness Share Pin Related Entries 19 total\
  \ U WOT M8 'Murica Huahuehuahue The Main Difference Between E... View All Related\
  \ Entries Recent Images 84 total View All Images Recent Videos 3 total View All\
  \ Videos Sign up for our Newsletter Load 52 Comments Comments 52 total 63 Almost\
  \ Politically Correct Redneck 930,838 3 84 52 Part of a series on Nationality Stereotypes.\
  \ [View Related Entries] Updated Dec 06, 2024 at 03:17PM EST by LiterallyAustin.\
  \ Added May 15, 2012 at 06:18PM EDT by Don. Like us on Facebook! Like 1.8M Share\
  \ Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the video\
  \ gallery, or 'r' to view a random entry. Featured Episode Meme Status Confirmed\
  \ Type: Image Macro Year 2012 Origin Reddit Tags image macro, redneck, reddit, advice\
  \ animal, hill billy, #2 entry of may 2012, usa, sens, mullet, ianl27, larkable,\
  \ guyism, bbmisc420196, brobible, uproxx, slacktory, zach downey, locks of love,\
  \ political correctness Additional References Meme Generator About Almost Politically\
  \ Correct Redneck is an advice animal image macro series featuring a photo of a\
  \ young shirtless man with a mullet hairstyle standing next to a pickup truck. The\
  \ captions typically portray the man as earnest and well-meaning but unaware of\
  \ his own stereotypical redneck prejudice. Origin The man behind the photo is Zach\
  \ Downey, a photographer who worked at the Lilly Library at Indiana University.\
  \ According to a post on Reddit[18], Downey cut his hair into the mullet as a joke\
  \ for his Halloween costume back in 2003. At the time, his wife, Tricia, snapped\
  \ a quick shot of him the morning after Halloween and uploaded it online where it\
  \ spread and became a meme. \"Two of my friends were going out on Halloween as superheroes,\"\
  \ Downey recalled. \"They had special clothing, glitter on their faces, they went\
  \ to a lot of trouble. I got some clippers and cut my hair in 10 minutes and I was\
  \ the hit. The mullet is associated with rednecks or hillbillies for sure,\" he\
  \ said. \"I'm not like that, but I mean no disrespect. I have friends that I'd call\
  \ and they'd call themselves rednecks or hillbillies. That's fine. It's just not\
  \ me.\" According to the post, Downey had the haircut for just about 16 hours. His\
  \ wife posed him in front of friend Jen Owen's 1979 GMC truck and took some photos\
  \ the next day. Then they hauled out the clippers, cut the mullet into a mohawk,\
  \ took more photos, shaved his head completely and snapped a few more. \"Actually,\
  \ and this was the plan all along, I donated my hair to Locks of Love. It's kind\
  \ of funny that some young person out there actually benefited from my haircut,\"\
  \ Downey said. \"Mullets of Love?\" Originally uploaded to a mullet photo gallery\
  \ website by a friend, it was named \"Mullet of the Month\" on the site, and after\
  \ that, it spread to other places online. The photo was then used as early as July\
  \ 2005 as a response photo on the internet humor site Fark. On July 3rd, 2005, Fark\
  \ user sens posted the image[9] in response to a story claiming Toyota would be\
  \ building a plant in Canada because they did not want to train southern Americans.\
  \ The photo was used on Fark in this manner on at least 2 other occasions in 2005[10]\
  \ and 2009.[2] On May 12th, 2012, Redditor IanL27 submitted an image macro to the\
  \ Advice Animals subreddit in a post titled \"I present to you: Somewhat Politically\
  \ Correct Redneck\"[11], which featured the caption \"Not against gay marriage /\
  \ unless the couple is colored.\" Within three days the post received over 3,700\
  \ up votes, earning 1124 points overall. Spread On May 13th, 2012, Redditor larkable\
  \ submitted a post titled \"A kid at my school was getting picked on for being a\
  \ 'faggot', so this guy gets up and grabs the bully by the throat and says this\"\
  [1] to the Advice Animals subreddit, containing an image macro with the caption\
  \ \"What's wrong / with faggots, queer?\" This post gained nearly 17,000 upvotes,\
  \ 1971 points overall and nearly 600 comments. The following day, men's humor blog\
  \ Guyism[7] published a post titled \"New Meme You Should Know: Almost Politically\
  \ Correct Redneck\", which reported that the meme was born out of North Carolina's\
  \ gay marriage ban earlier that week. The same day, BodyBuilding Forums[4] member\
  \ BBmisc420196 posted a thread titled \"New meme: Almost politically correct redneck\"\
  , which included several example image macros and received 23 responses in 24 hours.\
  \ Also on May 14th, an example with caption \"I fully support the right of my daughter\
  \ to express her love for her girlfriend in public / it's pretty hot\" was posted\
  \ on the Internet humor site FunnyJunk[5] and a Facebook[3] page for \"Almost Politically\
  \ Correct Redneck\" was created. Series of Almost Politically Correct Redneck instances\
  \ have also been shared on BroBible[16], Uproxx[6] and Slacktory.[13] In November\
  \ 2012, the image macro series came in at #17 on Buzzfeed's list of the Best New\
  \ Memes of 2012.[17] As of December, 2012, the Quickmeme[8] page has received more\
  \ than 5000 submissions and the Meme Generator[12] page hosts an additional thousand.\
  \ There have also been 760 submissions of Almost Politically Correct Redneck to\
  \ Reddit[14] and new instances continue to be posted on Tumblr.[15] Notable Examples\
  \ Search Interest External References [1] Reddit \u2013 A Kid at my school was getting\
  \ picked on [2] Fark \u2013 It's not every day you see a sheep dangling from a telephone\
  \ wire \u2013 but today happens to be that day [3] Facebook \u2013 Almost Politically\
  \ Correct Redneck [4] BodyBuilding \u2013 New meme \u2013 Almost politically correct\
  \ redneck [5] FunnyJunk \u2013 Almost Politically Correct Redneck [6] UpRoxx \u2013\
  \ Almost Politically Correct Redneck is Here To Offend Everyone [7] Guyism (now\
  \ BroBible) \u2013 ALMOST POLITICALLY CORRECT REDNECK [8] Quickmeme \u2013 Almost\
  \ politically correct redneck [9] Fark \u2013 Toyota building new plant in Canada\
  \ despite massive subsidy offers from American states. Reason: southern Americans\
  \ too dumb and illiterate to train; need directions in pictorial form [10] Fark\
  \ \u2013 Hot diggity!!! Now that thar's a dang fine mullet!! [11] Reddit \u2013\
  \ I present to you: Somewhat Politically Correct Redneck [12] Meme Generator via\
  \ WayBack Machine- Almost Politically Correct Redneck [13] Slacktory (via Wayback\
  \ Machine) \u2013 Almost Politically Correct Redneck: A New Advice Meme [14] Reddit\
  \ \u2013 Search results for \"almost politically correct redneck\" [15] Tumblr \u2013\
  \ Posts tagged \"almost politically correct redneck\" [16] BroBible \u2013 The \u2018\
  Almost Politically Correct Redneck\u2019 Meme Is a Kenny Powers Greatest Hits Album\
  \ In Meme Form [17] Buzzfeed \u2013 The 32 Best New Memes Of 2012 [18] Reddit \u2013\
  \ r/AdviceAnimals Related Entries 19 total U WOT M8 'Murica Huahuehuahue The Main\
  \ Difference Between Europe and USA Why Do Slavs Squat? / Slav Squat The World According\
  \ To... Hon Hon Hon British People / Bri'ish Italian Military Jokes America Invading\
  \ for Oil Juan Ooga Booga / Where The White Women At View All Related Entries Recent\
  \ Videos 3 total How the 'Almost Politically C... Almost Politically Correct Re...\
  \ Uploaded by Zach ALMOST POLITICALLY CORRECT RE... Almost Politically Correct Re...\
  \ Uploaded by Trilandian Almost Politically Correct Re... Almost Politically Correct\
  \ Re... Uploaded by Abby of Many Fandoms + Add a Video Recent Images 84 total Almost\
  \ Politically Correct Re... Uploaded by Reddit Moments Almost Politically Correct\
  \ Re... Uploaded by satoshiincarbonite Almost Politically Correct Re... Uploaded\
  \ by memetimeradiohour Almost Politically Correct Re... Uploaded by Zach Almost\
  \ Politically Correct Re... Uploaded by Zach Almost Politically Correct Re... Uploaded\
  \ by Zach Almost Politically Correct Re... Uploaded by Zach Almost Politically Correct\
  \ Re... Uploaded by Zach Almost Politically Correct Re... Uploaded by Zach Almost\
  \ Politically Correct Re... Uploaded by Zach Almost Politically Correct Re... Uploaded\
  \ by Zach Almost Politically Correct Re... Uploaded by Zach + Add an Image View\
  \ All Images Sign up for our Newsletter Top Comments Delete Sensitive Voltage is\
  \ nowhere to be found May 15, 2012 at 06:50PM EDT >sees a new image macro >titled\
  \ \"almost politically correct redneck\" >comes from reddit +54 Reply Delete Sensitive\
  \ Cale May 15, 2012 at 09:20PM EDT How did you guys put my Dad on the Internet.\
  \ Also, please remember the difference between a Hillbilly and a Redneck. +28 Reply\
  \ + Add a Comment Comments (52) Display Comments Add a Comment Top Entries This\
  \ Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare CEO\
  \ Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (10) Don Administrator\
  \ & Meme Daddy Brad Digital Archaeologist & Treasurer & Pundit & Gallery Housekeeper\
  \ Alex>_> Scrapbooker & Orator amanda b. Meme Librarian \xAD\xAD\xADAlex Mercer\
  \ Entry Moderator & YouTube Scatologist SabrinaTibbetts Memepuff andcallmeshirley\
  \ Digital Archaeologist & Treasurer & Collection Butler Y F Digital Archaeologist\
  \ & Treasurer & Media Maid Zach Memenator shevyrolet Digital Archaeologist & Treasurer\
  \ & Media Bus Boy \u25BC + Request Editorship View All Editors Today's Top Image\
  \ Galleries Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team\
  \ Fortress 2 The Amazing Digital Circus About Our Story Site Rules Policies and\
  \ Guidelines Credits Contact Meme DB Memes Episodes News Staff Contact Extras! Style\
  \ Guide RSS Feeds"
source: https://knowyourmeme.com/memes/almost-politically-correct-redneck
template_id: apcr
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
