example:
- Virginity is cool, stay pure
- I am utterly incapable of getting laid
keywords:
- null
name: Peter Parker's Glasses
overlay:
- angle: 0.0
  center_x: 0.75
  center_y: 0.245
  scale: 0.49
- angle: 0.0
  center_x: 0.75
  center_y: 0.755
  scale: 0.49
scraped_content: "Peter Parker's Glasses | Know Your Meme Greetings! You must login\
  \ or signup first! Already a memeber? Login Now! Don't have an account? Sign up\
  \ Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos Submit\
  \ \u2192 Images Trending Most Commented Most Favorited High Score Low Score Most\
  \ Viewed All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Peter Parker's Glasses Added 7 years ago / Updated 12 days ago Confirmed 99,794\
  \ Part of a series on Spider-Man. [View Related Entries] View All 85 Images Navigation\
  \ About \u2022 Origin \u2022 Spread \u2022 Templates \u2022 Search Interest \u2022\
  \ External References \u2022 Recent Images About Peter Parker's Glasses is a multi-pane\
  \ exploitable series in which Spider-Man alter ego Peter Parker looks at various\
  \ images that drastically change as he puts his glasses on and off. Origin In the\
  \ 2002 film Spider-Man, the protagonist Peter Parker takes his glasses on and off\
  \ while discovering he no longer needs them after gaining super powers (shown below).\
  \ On August 29th, 2016, a four-pane image in which Hillary Clinton is transformed\
  \ into a land fill was posted on 9gag (shown below).[1] Within seven months, the\
  \ post received more than 29,200 points and 680 comments. Spread On October 14th,\
  \ Redditor TheNotoriousWeb-M-D submitted a Watch Those Wrist Rockets-themed version\
  \ of the image to /r/me_irl,[5] where it gathered upwards of 2,500 points (97% upvoted)\
  \ within five months (shown below, right). On March 12th, the official Twitter feed\
  \ for the Houston Rockets tweeted a version of the image in which a goat is transformed\
  \ into the basketball team's shooting guard James Harden (shown below).[4] Within\
  \ 10 days, the tweet received more than 5,100 likes and 4,000 retweets. On March\
  \ 19th, Redditor HellspawnedJawa submitted a photoshop of the image in which a screenshot\
  \ of a dog humping a woman becomes a poster for the 2017 film Beauty and the Beast\
  \ (shown below, left). The following day, Redditor 0v3r1de submitted a picture of\
  \ Parker looking at a cover the book The Diary of a Young Girl by Ann Frank which\
  \ transforms into the book Diary of a Wimp Kid to /r/dankmemes[2] (shown below).\
  \ Within 24 hours, the post gained over 3,000 points (95% upvoted) and was subsequently\
  \ reposted to /r/MemeEconomy.[3] Templates Video Template Search Interest Not available.\
  \ External References [1] 9gag \u2013 I can see clearly [2] Reddit \u2013 Just a\
  \ second look [3] Reddit \u2013 Peter Parker glasses memes seem to be rising [4]\
  \ Twitter \u2013 @HoustonRockets [5] Reddit \u2013 me irl peter parker spider-man\
  \ spiderman spiderman glasses glasses hellspawnedjawa Share Pin Related Entries\
  \ 50 total 60's Spider-Man Aww Yea Guy How Do I Shot Web? Dancing Spider-Man View\
  \ All Related Entries Recent Images 85 total View All Images Recent Videos 0 total\
  \ There are no recent videos. Sign up for our Newsletter Load 15 Comments Comments\
  \ 15 total 22 Peter Parker's Glasses 99,794 0 85 15 Part of a series on Spider-Man.\
  \ [View Related Entries] Updated Dec 11, 2024 at 01:14PM EST by LiterallyAustin.\
  \ Added Mar 21, 2017 at 03:54PM EDT by Don. Like us on Facebook! Like 1.8M Share\
  \ Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the video\
  \ gallery, or 'r' to view a random entry. Meme Status Confirmed Type: Exploitable\
  \ Year 2016 Origin 9gag Tags peter parker, spider-man, spiderman, spiderman glasses,\
  \ glasses, hellspawnedjawa About Peter Parker's Glasses is a multi-pane exploitable\
  \ series in which Spider-Man alter ego Peter Parker looks at various images that\
  \ drastically change as he puts his glasses on and off. Origin In the 2002 film\
  \ Spider-Man, the protagonist Peter Parker takes his glasses on and off while discovering\
  \ he no longer needs them after gaining super powers (shown below). On August 29th,\
  \ 2016, a four-pane image in which Hillary Clinton is transformed into a land fill\
  \ was posted on 9gag (shown below).[1] Within seven months, the post received more\
  \ than 29,200 points and 680 comments. Spread On October 14th, Redditor TheNotoriousWeb-M-D\
  \ submitted a Watch Those Wrist Rockets-themed version of the image to /r/me_irl,[5]\
  \ where it gathered upwards of 2,500 points (97% upvoted) within five months (shown\
  \ below, right). On March 12th, the official Twitter feed for the Houston Rockets\
  \ tweeted a version of the image in which a goat is transformed into the basketball\
  \ team's shooting guard James Harden (shown below).[4] Within 10 days, the tweet\
  \ received more than 5,100 likes and 4,000 retweets. On March 19th, Redditor HellspawnedJawa\
  \ submitted a photoshop of the image in which a screenshot of a dog humping a woman\
  \ becomes a poster for the 2017 film Beauty and the Beast (shown below, left). The\
  \ following day, Redditor 0v3r1de submitted a picture of Parker looking at a cover\
  \ the book The Diary of a Young Girl by Ann Frank which transforms into the book\
  \ Diary of a Wimp Kid to /r/dankmemes[2] (shown below). Within 24 hours, the post\
  \ gained over 3,000 points (95% upvoted) and was subsequently reposted to /r/MemeEconomy.[3]\
  \ Templates Video Template Search Interest Not available. External References [1]\
  \ 9gag \u2013 I can see clearly [2] Reddit \u2013 Just a second look [3] Reddit\
  \ \u2013 Peter Parker glasses memes seem to be rising [4] Twitter \u2013 @HoustonRockets\
  \ [5] Reddit \u2013 me irl Related Entries 50 total 60's Spider-Man Aww Yea Guy\
  \ How Do I Shot Web? Dancing Spider-Man Spider-Man Ass Slap With Great Power Comes\
  \ Great Responsibility Emo Peter Parker Italian Spiderman Raimiposting Pizza Time\
  \ Spider-Man's Presentation Toei Spider-Man / Spy Darma View All Related Entries\
  \ Recent Videos There are no videos currently available. + Add a Video Recent Images\
  \ 85 total Peter Parker's Glasses Uploaded by Jaimie Hamilton Peter Parker's Glasses\
  \ Uploaded by Edgar Weebling Peter Parker's Glasses Uploaded by Edgar Weebling Peter\
  \ Parker's Glasses Uploaded by DarthZino Peter Parker's Glasses Uploaded by Evilthing\
  \ Peter Parker's Glasses Uploaded by KXS Peter Parker's Glasses Uploaded by Liquid\
  \ Fiend Peter Parker's Glasses Uploaded by Liquid Fiend Peter Parker's Glasses Uploaded\
  \ by Liquid Fiend Peter Parker's Glasses Uploaded by Liquid Fiend Peter Parker's\
  \ Glasses Uploaded by Liquid Fiend Peter Parker's Glasses Uploaded by Liquid Fiend\
  \ + Add an Image View All Images Sign up for our Newsletter Top Comments Delete\
  \ Sensitive Pyroniusburn Mar 21, 2017 at 07:08PM EDT Is it just me or have they\
  \ got this backwards? In any other case someone putting their glasses on would help\
  \ them see better, seeing as the format is No glasses \u2013 what you see at face\
  \ value Glasses \u2013 What it \"actually\" is but in this actual context Peter\
  \ is supposed to see better without his glasses, because of his super powers I'm\
  \ just over-analysing this aren't I? +44 Reply Delete Sensitive GattsuSeijin Mar\
  \ 21, 2017 at 09:31PM EDT Nothing will be wrong if you put your glasses on! +20\
  \ Reply + Add a Comment Comments (15) Display Comments Add a Comment Top Entries\
  \ This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (3) Don Administrator\
  \ & Meme Daddy Matt Secretary of Memes Y F Digital Archaeologist & Treasurer & Media\
  \ Maid + Request Editorship View All Editors Today's Top Image Galleries Assassination\
  \ of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing\
  \ Digital Circus About Our Story Site Rules Policies and Guidelines Credits Contact\
  \ Meme DB Memes Episodes News Staff Contact Extras! Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/peter-parkers-glasses
template_id: glasses
text:
- align: center
  anchor_x: 0.5
  anchor_y: 0.0
  angle: 0.0
  color: black
  font: comic
  scale_x: 0.5
  scale_y: 0.49
  start: 0.0
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.5
  anchor_y: 0.51
  angle: 0.0
  color: black
  font: thin
  scale_x: 0.5
  scale_y: 0.49
  start: 0.0
  stop: 1.0
  style: default
text_zones: 2
