name: Peter Parker's Glasses
source: https://knowyourmeme.com/memes/peter-parkers-glasses
keywords:
- null
text:
- style: default
  color: black
  font: comic
  anchor_x: 0.5
  anchor_y: 0.0
  angle: 0.0
  scale_x: 0.5
  scale_y: 0.49
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: black
  font: thin
  anchor_x: 0.5
  anchor_y: 0.51
  angle: 0.0
  scale_x: 0.5
  scale_y: 0.49
  align: center
  start: 0.0
  stop: 1.0
example:
- Virginity is cool, stay pure
- I am utterly incapable of getting laid
overlay:
- center_x: 0.75
  center_y: 0.245
  angle: 0.0
  scale: 0.49
- center_x: 0.75
  center_y: 0.755
  angle: 0.0
  scale: 0.49
scraped_content: About Peter Parker's Glasses is a multi-pane exploitable series in
  which Spider-Man alter ego Peter Parker looks at various images that drastically
  change as he puts his glasses on and off. Origin In the 2002 film Spider-Man, the
  protagonist Peter Parker takes his glasses on and off while discovering he no longer
  needs them after gaining super powers (shown below). On August 29th, 2016, a four-pane
  image in which Hillary Clinton is transformed into a land fill was posted on 9gag
  (shown below).[1] Within seven months, the post received more than 29,200 points
  and 680 comments. Spread On October 14th, Redditor TheNotoriousWeb-M-D submitted
  a Watch Those Wrist Rockets-themed version of the image to /r/me_irl,[5] where it
  gathered upwards of 2,500 points (97% upvoted) within five months (shown below,
  right). On March 12th, the official Twitter feed for the Houston Rockets tweeted
  a version of the image in which a goat is transformed into the basketball team's
  shooting guard James Harden (shown below).[4] Within 10 days, the tweet received
  more than 5,100 likes and 4,000 retweets. On March 19th, Redditor HellspawnedJawa
  submitted a photoshop of the image in which a screenshot of a dog humping a woman
  becomes a poster for the 2017 film Beauty and the Beast (shown below, left). The
  following day, Redditor 0v3r1de submitted a picture of Parker looking at a cover
  the book The Diary of a Young Girl by Ann Frank which transforms into the book Diary
  of a Wimp Kid to /r/dankmemes[2] (shown below). Within 24 hours, the post gained
  over 3,000 points (95% upvoted) and was subsequently reposted to /r/MemeEconomy.[3]
  Templates Video Template Search Interest Not available. External References [1]
  9gag – I can see clearly [2] Reddit – Just a second look [3] Reddit – Peter Parker
  glasses memes seem to be rising [4] Twitter – @HoustonRockets [5] Reddit – me irl
aside_content: MemeStatusConfirmedType:ExploitableYear2016Origin9gagTagspeter parker,spider-man,spiderman,spiderman
  glasses,glasses,hellspawnedjawa
added_at: '2017-03-21T15:54:24-04:00'
