name: Awkward Moment Seal
source: https://knowyourmeme.com/memes/awkward-moment-seal
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- when you're watching a movie
- and your parents walk in at the sex scene
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Awkward Moment Seal is an advice animal image macro series
  featuring a seal with a wide-eyed expression and captions describing socially awkward
  or uncomfortable situations in similar vein to "That Awkward Moment…" and Socially
  Awkward Penguin.. Origin Awkward Moment Seal was originally uploaded to Nature''s
  Pics Online[13] sometime in 2010 where the photo was titled "Northern Elephant Seal
  (Weaner)" by the photographers. The picture was first submitted to Reddit April
  15th, 2014, when user Niccalv2015 submitted Nature''s Pics image to the subreddit
  /r/aww.[9] The post received over 3,000 upvotes and 373 comments and was titled
  "Hurumph." The following day, redditor Balten submitted the first captioned version
  of the seal to /r/funny titled "I always feel like the creepiest person when I do
  this…".[12] The post neared 2200 upvotes and a 89% upvote rating. On the 17th, Redditor
  walrusmeats[1] submitted another captioned version that read, "I need to shit but
  my girlfriend won''t go home," to the /r/AdviceAnimals[2] subreddit. Walrusmeats
  titled the image "Introducing squeamish seal," and gained over 400 comments and
  over 17,000 upvotes. (Below Left) The next day Redditor Honorato[7] posted an example
  of the meme to the /r/AdviceAnimals[8] subreddit titled "So are we doing a Awkward/Bad
  Moment Seal?" The submission received over 4,000 upvotes in less than a week. (Below
  Right) Spread On April 18th, the meme was covered by Mashable[4] and UpRoxx[5].
  The same day examples of the meme were also featured on the Tumblr blog TastefullyOffensive[6].
  In less than a week the post gained over 13,000 notes. An example of the image macro
  landed on Reddit''s front page on April 21st. It received more than 3,000 upvotes
  in less than 24 hours. On April 22, a Meme Generator for Awkward Moment Seal was
  published and has since received nearly 3,000 images.[10] The Facebook page "Awkward
  Moment Seal" was created May 3rd, 2014, and has since received over 3,700 likes.[11]
  Notable Examples Search Interest External References [1] Reddit – walrusmeats [2]
  Reddit – Squeamish Seal [3] Twitter – SoVeryAwkward [4] Mashable – Awkward Moment
  Seal Is the Meme for All Your Slippery Situations [5] Mashable – Meme Watch: Awkward
  Moment Seal Is Taking The Internet By Storm Because We’ve All Been There [6] Tumblr
  – tastefullyoffensive [7] Reddit – Honorato_ [8] Reddit – So are we doing a Awkward/Bad
  Moment Seal? [9] Reddit – Hurumph [10] Meme Generator – Awkward Moment Seal [11]
  Facebook – AwkMomentSeal [12] Reddit – I always feel like the creepiest person when…
  [13] Nature Pics Online – Northern Elephant Seal'
aside_content: MemeStatusConfirmedYear2014OriginRedditTagsawkward,reddit,seal,advice
  animal,socially awkwardAdditional ReferencesFacebookMeme GeneratorReddit
added_at: '2014-04-21T11:35:35-04:00'
