example:
- when you're watching a movie
- and your parents walk in at the sex scene
keywords:
- null
name: Awkward Moment Seal
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Awkward Moment Seal | Know Your Meme Yo Yo! You must login or signup\
  \ first! Already a memeber? Login Now! Don't have an account? Sign up Now! Meme\
  \ Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Awkward Moment Seal Added 10 years ago / Updated 12 days ago Confirmed 357,013\
  \ Part of a series on Socially Awkward Penguin. [View Related Entries] View All\
  \ 31 Images Navigation About \u2022 Origin \u2022 Spread \u2022 Notable Examples\
  \ \u2022 Search Interest \u2022 External References \u2022 Recent Images About Awkward\
  \ Moment Seal is an advice animal image macro series featuring a seal with a wide-eyed\
  \ expression and captions describing socially awkward or uncomfortable situations\
  \ in similar vein to \"That Awkward Moment\u2026\" and Socially Awkward Penguin..\
  \ Origin Awkward Moment Seal was originally uploaded to Nature's Pics Online[13]\
  \ sometime in 2010 where the photo was titled \"Northern Elephant Seal (Weaner)\"\
  \ by the photographers. The picture was first submitted to Reddit April 15th, 2014,\
  \ when user Niccalv2015 submitted Nature's Pics image to the subreddit /r/aww.[9]\
  \ The post received over 3,000 upvotes and 373 comments and was titled \"Hurumph.\"\
  \ The following day, redditor Balten submitted the first captioned version of the\
  \ seal to /r/funny titled \"I always feel like the creepiest person when I do this\u2026\
  \".[12] The post neared 2200 upvotes and a 89% upvote rating. On the 17th, Redditor\
  \ walrusmeats[1] submitted another captioned version that read, \"I need to shit\
  \ but my girlfriend won't go home,\" to the /r/AdviceAnimals[2] subreddit. Walrusmeats\
  \ titled the image \"Introducing squeamish seal,\" and gained over 400 comments\
  \ and over 17,000 upvotes. (Below Left) The next day Redditor Honorato[7] posted\
  \ an example of the meme to the /r/AdviceAnimals[8] subreddit titled \"So are we\
  \ doing a Awkward/Bad Moment Seal?\" The submission received over 4,000 upvotes\
  \ in less than a week. (Below Right) Spread On April 18th, the meme was covered\
  \ by Mashable[4] and UpRoxx[5]. The same day examples of the meme were also featured\
  \ on the Tumblr blog TastefullyOffensive[6]. In less than a week the post gained\
  \ over 13,000 notes. An example of the image macro landed on Reddit's front page\
  \ on April 21st. It received more than 3,000 upvotes in less than 24 hours. On April\
  \ 22, a Meme Generator for Awkward Moment Seal was published and has since received\
  \ nearly 3,000 images.[10] The Facebook page \"Awkward Moment Seal\" was created\
  \ May 3rd, 2014, and has since received over 3,700 likes.[11] Notable Examples Search\
  \ Interest External References [1] Reddit \u2013 walrusmeats [2] Reddit \u2013 Squeamish\
  \ Seal [3] Twitter \u2013 SoVeryAwkward [4] Mashable \u2013 Awkward Moment Seal\
  \ Is the Meme for All Your Slippery Situations [5] Mashable \u2013 Meme Watch: Awkward\
  \ Moment Seal Is Taking The Internet By Storm Because We\u2019ve All Been There\
  \ [6] Tumblr \u2013 tastefullyoffensive [7] Reddit \u2013 Honorato_ [8] Reddit \u2013\
  \ So are we doing a Awkward/Bad Moment Seal? [9] Reddit \u2013 Hurumph [10] Meme\
  \ Generator \u2013 Awkward Moment Seal [11] Facebook \u2013 AwkMomentSeal [12] Reddit\
  \ \u2013 I always feel like the creepiest person when\u2026 [13] Nature Pics Online\
  \ \u2013 Northern Elephant Seal awkward reddit seal advice animal socially awkward\
  \ Share Pin Recent Images 31 total View All Images Recent Videos 0 total There are\
  \ no recent videos. Sign up for our Newsletter Load 66 Comments Comments 66 total\
  \ 26 Awkward Moment Seal 357,013 0 31 66 Part of a series on Socially Awkward Penguin.\
  \ [View Related Entries] Updated Dec 11, 2024 at 04:15PM EST by LiterallyAustin.\
  \ Added Apr 21, 2014 at 11:35AM EDT by Molly Horan. Like us on Facebook! Like 1.8M\
  \ Share Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the\
  \ video gallery, or 'r' to view a random entry. Meme Status Confirmed Year 2014\
  \ Origin Reddit Tags awkward, reddit, seal, advice animal, socially awkward Additional\
  \ References Facebook Meme Generator Reddit About Awkward Moment Seal is an advice\
  \ animal image macro series featuring a seal with a wide-eyed expression and captions\
  \ describing socially awkward or uncomfortable situations in similar vein to \"\
  That Awkward Moment\u2026\" and Socially Awkward Penguin.. Origin Awkward Moment\
  \ Seal was originally uploaded to Nature's Pics Online[13] sometime in 2010 where\
  \ the photo was titled \"Northern Elephant Seal (Weaner)\" by the photographers.\
  \ The picture was first submitted to Reddit April 15th, 2014, when user Niccalv2015\
  \ submitted Nature's Pics image to the subreddit /r/aww.[9] The post received over\
  \ 3,000 upvotes and 373 comments and was titled \"Hurumph.\" The following day,\
  \ redditor Balten submitted the first captioned version of the seal to /r/funny\
  \ titled \"I always feel like the creepiest person when I do this\u2026\".[12] The\
  \ post neared 2200 upvotes and a 89% upvote rating. On the 17th, Redditor walrusmeats[1]\
  \ submitted another captioned version that read, \"I need to shit but my girlfriend\
  \ won't go home,\" to the /r/AdviceAnimals[2] subreddit. Walrusmeats titled the\
  \ image \"Introducing squeamish seal,\" and gained over 400 comments and over 17,000\
  \ upvotes. (Below Left) The next day Redditor Honorato[7] posted an example of the\
  \ meme to the /r/AdviceAnimals[8] subreddit titled \"So are we doing a Awkward/Bad\
  \ Moment Seal?\" The submission received over 4,000 upvotes in less than a week.\
  \ (Below Right) Spread On April 18th, the meme was covered by Mashable[4] and UpRoxx[5].\
  \ The same day examples of the meme were also featured on the Tumblr blog TastefullyOffensive[6].\
  \ In less than a week the post gained over 13,000 notes. An example of the image\
  \ macro landed on Reddit's front page on April 21st. It received more than 3,000\
  \ upvotes in less than 24 hours. On April 22, a Meme Generator for Awkward Moment\
  \ Seal was published and has since received nearly 3,000 images.[10] The Facebook\
  \ page \"Awkward Moment Seal\" was created May 3rd, 2014, and has since received\
  \ over 3,700 likes.[11] Notable Examples Search Interest External References [1]\
  \ Reddit \u2013 walrusmeats [2] Reddit \u2013 Squeamish Seal [3] Twitter \u2013\
  \ SoVeryAwkward [4] Mashable \u2013 Awkward Moment Seal Is the Meme for All Your\
  \ Slippery Situations [5] Mashable \u2013 Meme Watch: Awkward Moment Seal Is Taking\
  \ The Internet By Storm Because We\u2019ve All Been There [6] Tumblr \u2013 tastefullyoffensive\
  \ [7] Reddit \u2013 Honorato_ [8] Reddit \u2013 So are we doing a Awkward/Bad Moment\
  \ Seal? [9] Reddit \u2013 Hurumph [10] Meme Generator \u2013 Awkward Moment Seal\
  \ [11] Facebook \u2013 AwkMomentSeal [12] Reddit \u2013 I always feel like the creepiest\
  \ person when\u2026 [13] Nature Pics Online \u2013 Northern Elephant Seal Recent\
  \ Videos There are no videos currently available. + Add a Video Recent Images 31\
  \ total Awkward Moment Seal Uploaded by Aidan Walker Awkward Moment Seal Uploaded\
  \ by arielae Awkward Moment Seal Uploaded by Angrygeek Awkward Moment Seal Uploaded\
  \ by Particle Mare Awkward Moment Seal Uploaded by Goozer Awkward Moment Seal Uploaded\
  \ by Particle Mare Awkward Moment Seal Uploaded by Particle Mare Awkward Moment\
  \ Seal Uploaded by Jill Awkward Moment Seal Uploaded by The Cute Master :3 Awkward\
  \ Moment Seal Uploaded by Brad Awkward Moment Seal Uploaded by Brad Awkward Moment\
  \ Seal Uploaded by \xAD\xAD\xAD\xAD\xAD\xAD\xAD\xAD\xAD\xAD + Add an Image View\
  \ All Images Sign up for our Newsletter Top Comments Delete Sensitive Freakenstein\
  \ Moderator Apr 21, 2014 at 02:38PM EDT +123 Reply Delete Sensitive TheZombieFiend\
  \ Apr 21, 2014 at 02:50PM EDT > Le new Advice animal > A couple days old > Exactly\
  \ the same as socially awkward penguin > Gets an article without even spreading\
  \ outside Reddit +73 Reply + Add a Comment Comments (66) Display Comments Add a\
  \ Comment Top Entries This Month Meme Saika Kawakita Smile GIF Event Assassination\
  \ of UnitedHealthcare CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki\
  \ Sisters Culture Pornography Site Whisper View More Suggest a Change Edit History\
  \ Entry Editors (4) Molly Horan Tumblr Historian The Cute Master :3 Sr. Entry Moderator\
  \ Z. Database Moderator & Rage Comicologist shevyrolet Digital Archaeologist & Treasurer\
  \ & Media Bus Boy + Request Editorship View All Editors Today's Top Image Galleries\
  \ Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress\
  \ 2 The Amazing Digital Circus About Our Story Site Rules Policies and Guidelines\
  \ Credits Contact Meme DB Memes Episodes News Staff Contact Extras! Style Guide\
  \ RSS Feeds"
source: https://knowyourmeme.com/memes/awkward-moment-seal
template_id: ams
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
