name: We Don't Do That Here
source: https://knowyourmeme.com/memes/we-dont-do-that-here
keywords:
- Black Panther
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.15
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: khaki
  font: thin
  anchor_x: 0.1
  anchor_y: 0.85
  angle: 0.0
  scale_x: 0.8
  scale_y: 0.15
  align: center
  start: 0.0
  stop: 1.0
example:
- when someone calls your phone without warning
- We don't do that here.
overlay:
- center_x: 0.48
  center_y: 0.23
  angle: 0.0
  scale: 0.33
scraped_content: 'About We Don''t Do That Here is a memorable quote uttered by the
  character Black Panther (played by Chadwick Boseman) in the 2018 Marvel superhero
  film Avengers: Infinity War. Online, a screen-capture of the character saying the
  line has been used as the punchline to jokes about social faux pas, both real and
  absurd. Origin On April 27th, 2018, the film Avengers: Infinity War was released
  in theaters in the United States. In the film, the characters Bruce Banner and James
  Rhodes (played by Mark Ruffalo and Don Cheadle, respectively) arrive in Black Panther''s
  home in Wakanda. When Banner attempts to bow to Panther, who is the king of Wakanda,
  he responds, "We don''t do that here" (shown below). That day, Tumblr [1] user jlaws
  posted a series of gifs of the moment. The post (shown below) received more than
  4,200 notes in about six weeks. https://jlaws.tumblr.com/post/173355100923/should-we-bow-yeah-hes-a-king-avengers
  About two weeks later, Tumblr[2] user she-writes-love posted just a screen-capture
  of the line being said with the caption "When Writers™ have entire notebooks filled
  and detailed outlines and know what the fuck they’re doing. And then they ask what
  your preferred method is and you respond:" The post (shown below) received more
  than 4,100 notes. Spread The following month, Twitter [3] user @slutparadies posted
  a mock version of the reaction with the caption "When you''re from Alabama and want
  to marry outside your immediate family." The post (shown below) was shared later
  that day on the /r/dankmemes subreddit by Redditor[4] MyDixyRekt2. The post on /r/dankmemes
  received more than 5,500 points (96% upvoted) and 30 comments in 24 hours. Over
  the next 24 hours, Redditors on /r/dankmemes continued to share variations of the
  meme (examples below, center and right) Various Examples Search Interest External
  References [1] Tumblr – jlaws''s Post [2] Tumblr – she-writes-love''s Post [3] Twitter
  – @slutparadise''s Tweet [4] Reddit – Excuse me?'
aside_content: MemeStatusConfirmedType:Image Macro,ReactionYear2018OriginTumblrTagsblack
  panther,avengers,marvel,superheroes,movies,infinity war,hulk,bruce banner,chadwick
  boseman,mark ruffalo,movie quote
added_at: '2018-06-05T12:49:07-04:00'
