example:
- when someone calls your phone without warning
- We don't do that here.
keywords:
- Black Panther
name: We Don't Do That Here
overlay:
- angle: 0.0
  center_x: 0.48
  center_y: 0.23
  scale: 0.33
scraped_content: "We Don't Do That Here | Know Your Meme Hauu! You must login or signup\
  \ first! Already a memeber? Login Now! Don't have an account? Sign up Now! Meme\
  \ Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO We Don't Do That Here Added 6 years ago / Updated 10 days ago Confirmed 120,311\
  \ Part of a series on Avengers: Infinity War. [View Related Entries] View All 27\
  \ Images Navigation About \u2022 Origin \u2022 Spread \u2022 Various Examples \u2022\
  \ Search Interest \u2022 External References \u2022 Recent Images \u2022 Recent\
  \ Videos About We Don't Do That Here is a memorable quote uttered by the character\
  \ Black Panther (played by Chadwick Boseman) in the 2018 Marvel superhero film Avengers:\
  \ Infinity War. Online, a screen-capture of the character saying the line has been\
  \ used as the punchline to jokes about social faux pas, both real and absurd. Origin\
  \ On April 27th, 2018, the film Avengers: Infinity War was released in theaters\
  \ in the United States. In the film, the characters Bruce Banner and James Rhodes\
  \ (played by Mark Ruffalo and Don Cheadle, respectively) arrive in Black Panther's\
  \ home in Wakanda. When Banner attempts to bow to Panther, who is the king of Wakanda,\
  \ he responds, \"We don't do that here\" (shown below). That day, Tumblr [1] user\
  \ jlaws posted a series of gifs of the moment. The post (shown below) received more\
  \ than 4,200 notes in about six weeks. https://jlaws.tumblr.com/post/173355100923/should-we-bow-yeah-hes-a-king-avengers\
  \ About two weeks later, Tumblr[2] user she-writes-love posted just a screen-capture\
  \ of the line being said with the caption \"When Writers\u2122 have entire notebooks\
  \ filled and detailed outlines and know what the fuck they\u2019re doing. And then\
  \ they ask what your preferred method is and you respond:\" The post (shown below)\
  \ received more than 4,100 notes. Spread The following month, Twitter [3] user @slutparadies\
  \ posted a mock version of the reaction with the caption \"When you're from Alabama\
  \ and want to marry outside your immediate family.\" The post (shown below) was\
  \ shared later that day on the /r/dankmemes subreddit by Redditor[4] MyDixyRekt2.\
  \ The post on /r/dankmemes received more than 5,500 points (96% upvoted) and 30\
  \ comments in 24 hours. Over the next 24 hours, Redditors on /r/dankmemes continued\
  \ to share variations of the meme (examples below, center and right) Various Examples\
  \ Search Interest External References [1] Tumblr \u2013 jlaws's Post [2] Tumblr\
  \ \u2013 she-writes-love's Post [3] Twitter \u2013 @slutparadise's Tweet [4] Reddit\
  \ \u2013 Excuse me? black panther avengers marvel superheroes movies infinity war\
  \ hulk bruce banner chadwick boseman mark ruffalo movie quote Share Pin Related\
  \ Entries 26 total Disintegration Effect / I Don... What Did It Cost? Everything\
  \ 'Infinity War' Is The Most Am... Perfectly Balanced View All Related Entries Recent\
  \ Images 27 total View All Images Recent Videos 1 total View All Videos Sign up\
  \ for our Newsletter Load 13 Comments Comments 13 total 8 We Don't Do That Here\
  \ 120,311 1 27 13 Part of a series on Avengers: Infinity War. [View Related Entries]\
  \ Updated Dec 13, 2024 at 02:48PM EST by LiterallyAustin. Added Jun 05, 2018 at\
  \ 12:49PM EDT by Matt. Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press\
  \ 'i' to view the image gallery, 'v' to view the video gallery, or 'r' to view a\
  \ random entry. Meme Status Confirmed Type: Image Macro, Reaction Year 2018 Origin\
  \ Tumblr Tags black panther, avengers, marvel, superheroes, movies, infinity war,\
  \ hulk, bruce banner, chadwick boseman, mark ruffalo, movie quote About We Don't\
  \ Do That Here is a memorable quote uttered by the character Black Panther (played\
  \ by Chadwick Boseman) in the 2018 Marvel superhero film Avengers: Infinity War.\
  \ Online, a screen-capture of the character saying the line has been used as the\
  \ punchline to jokes about social faux pas, both real and absurd. Origin On April\
  \ 27th, 2018, the film Avengers: Infinity War was released in theaters in the United\
  \ States. In the film, the characters Bruce Banner and James Rhodes (played by Mark\
  \ Ruffalo and Don Cheadle, respectively) arrive in Black Panther's home in Wakanda.\
  \ When Banner attempts to bow to Panther, who is the king of Wakanda, he responds,\
  \ \"We don't do that here\" (shown below). That day, Tumblr [1] user jlaws posted\
  \ a series of gifs of the moment. The post (shown below) received more than 4,200\
  \ notes in about six weeks. https://jlaws.tumblr.com/post/173355100923/should-we-bow-yeah-hes-a-king-avengers\
  \ About two weeks later, Tumblr[2] user she-writes-love posted just a screen-capture\
  \ of the line being said with the caption \"When Writers\u2122 have entire notebooks\
  \ filled and detailed outlines and know what the fuck they\u2019re doing. And then\
  \ they ask what your preferred method is and you respond:\" The post (shown below)\
  \ received more than 4,100 notes. Spread The following month, Twitter [3] user @slutparadies\
  \ posted a mock version of the reaction with the caption \"When you're from Alabama\
  \ and want to marry outside your immediate family.\" The post (shown below) was\
  \ shared later that day on the /r/dankmemes subreddit by Redditor[4] MyDixyRekt2.\
  \ The post on /r/dankmemes received more than 5,500 points (96% upvoted) and 30\
  \ comments in 24 hours. Over the next 24 hours, Redditors on /r/dankmemes continued\
  \ to share variations of the meme (examples below, center and right) Various Examples\
  \ Search Interest External References [1] Tumblr \u2013 jlaws's Post [2] Tumblr\
  \ \u2013 she-writes-love's Post [3] Twitter \u2013 @slutparadise's Tweet [4] Reddit\
  \ \u2013 Excuse me? Related Entries 26 total Disintegration Effect / I Don't Feel\
  \ So Good What Did It Cost? Everything 'Infinity War' Is The Most Ambitious Crossover\
  \ Event In History Perfectly Balanced Thanos Did Nothing Wrong Thanos Edits A Small\
  \ Price to Pay for Salvation Why Is Gamora? Let Me Guess, Your Home? I Saw 14,000,605\
  \ Futures It's a Simple Spell But Quite Unbreakable Get This Man a Shield! View\
  \ All Related Entries Recent Videos 1 total Avengers Infinity War: \"we do... We\
  \ Don't Do That Here Uploaded by Matt + Add a Video Recent Images 27 total We Don't\
  \ Do That Here Uploaded by Aidan Walker We Don't Do That Here Uploaded by Rebecca\
  \ Rhodes We Don't Do That Here Uploaded by Reddit Moments We Don't Do That Here\
  \ Uploaded by nightqueen We Don't Do That Here Uploaded by JapanYoshiPlz We Don't\
  \ Do That Here Uploaded by Sachin X Deadpool We Don't Do That Here Uploaded by Philipp\
  \ We Don't Do That Here Uploaded by Political_LOL_center We Don't Do That Here Uploaded\
  \ by Amongus We Don't Do That Here Uploaded by Y F We Don't Do That Here Uploaded\
  \ by Amongus We Don't Do That Here Uploaded by Not_My_Real_Name + Add an Image View\
  \ All Images Sign up for our Newsletter Top Comments Delete Sensitive VinchVolt\
  \ Jun 06, 2018 at 09:20PM EDT Well this is one hell of a conversation. +27 Reply\
  \ Delete Sensitive The Christmas Pyro Jun 05, 2018 at 05:26PM EDT in reply to ThePunMaster\
  \ not really. prequel memes have staying power because all the scenes and quotes\
  \ are somewhat iconic. sure, infinity war memes might work right now, but it's not\
  \ clear if people will remember the movie in detail months or years from now. +18\
  \ Reply + Add a Comment Comments (13) Display Comments Add a Comment Top Entries\
  \ This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (2) Matt Secretary\
  \ of Memes Brad Digital Archaeologist & Treasurer & Pundit & Gallery Housekeeper\
  \ + Request Editorship View All Editors Today's Top Image Galleries Assassination\
  \ of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing\
  \ Digital Circus About Our Story Site Rules Policies and Guidelines Credits Contact\
  \ Meme DB Memes Episodes News Staff Contact Extras! Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/we-dont-do-that-here
template_id: wddth
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.15
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.1
  anchor_y: 0.85
  angle: 0.0
  color: khaki
  font: thin
  scale_x: 0.8
  scale_y: 0.15
  start: 0.0
  stop: 1.0
  style: default
text_zones: 2
