name: Socially Awesome Penguin
source: http://knowyourmeme.com/memes/socially-awesome-penguin
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- say a word wrong
- create hilarious inside joke
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'For more information, head to KYM Database: Socially Awkward Penguin.
  About Socially Awesome Penguin is an advice animal image macro series featuring
  a photo of a penguin with a red color wheel background. As the antithesis of Socially
  Awkward Penguin, the captions depict the character as popular, charismatic and sexually
  attractive. Origin The original photo comes from a horizontally flipped version
  of the Adélie penguin used in the Socially Awkward Penguin series (shown left),
  which first appeared on Tumblr in August of 2009. On January 13th, 2010, the "Fuck
  Yeah Socially Awesome Penguin"[6] Tumblr blog was created, with the first image
  macro featuring the caption "Say a word wrong / create hilarious inside joke"[8]
  (shown right). The first image macros were watermarked by Meme Generator[2], but
  the exact date of creation is currently unknown. On September 13th, 2012, novelist
  Andy Weir claimed responsibility for the meme in a Reddit AMA. [14] One user asked,
  "what is something secret about you that Reddit doesn''t know?" Weird responded:
  Nothing major, but some fun trivia about my life: I am a computer programmer and
  I worked for Blizzard on Warcraft II (yes I''m that old). Though I will never be
  able to prove it, I invented the "Socially Awesome Penguin" image macro meme (as
  a response to "Socially Awkward Penguin" which was popular at the time). I also
  created two webcomics, Casey and Andy and Cheshire Crossing. Not exactly a secret,
  but nobody seems to know that. Spread On April 8th, 2010, a Socially Awesome Penguin
  image macro with the caption "Crush walks up to you in hall / have a quick chat.
  You''re meeting her after school" was submitted to a Socially Awkward penguin thread
  on 4chan''s /b/ (random) board. On August 15th, a second "Socially Awesome Penguin"
  Tumblr[1] was created. On January 3rd, 2011, a post with several Socially Awesome
  Penguin derivatives was submitted to the /r/AdviceAnimals[9] subreddit by Redditor
  Mano21, receiving 1,210 up votes prior to being archived. A Socially Awesome Penguin
  Quickmeme[3] page was created the same month. On March 1st, 2012, the Internet humor
  blog Smosh[10] published a round-up of notable Socially Awesome Penguin derivatives
  from Tumblr and Reddit. On April 7th, a video featuring two young boys interacting
  with an aquarium penguin titled "Logan Meets Socially Awesome Penguin" was uploaded
  to YouTube by user TXBeer. As of April 16th, 2012, the Quickmeme page has received
  over 3,500 submissions and a Facebook[5] page for "Socially Awesome Penguin" has
  accumulated over 990 likes. Notable Examples The meme has continued to spread on
  sites like FunnyJunk[12], Tumblr[11] and /r/AdviceAnimals[13] subreddit. Reverse
  Memes Some Socially Awesome Penguin macros were created as direct reversals of Socially
  Awkward Penguin derivatives. For example, the image below shows an examples of Socially
  Awkward Penguin, a Socially Average Penguin and a Socially Awesome Penguin derivatives
  for the same social situation. Hybrid Socially Awesome Penguin often appears in
  image macros with its antithesis Socially Awkward Penguin. On May 12th, 2011, a
  "Socially Awesome Awkward Penguin" Quickmeme[14] page was created, featuring macros
  with half of the image portraying a successful social interaction and the other
  half describing a socially awkward interaction. As of April 16th, 2012, the Quickmeme
  page has received over 8,200 submissions. Template Search Interest External References
  [1] Tumblr – Socially Awesome Penguin [2] Meme Generator – Socially Awesome Penguin
  [3] Quickmeme – Socially Awesome Penguin [4] Smosh – Best of Socially Awesome Penguin!
  [5] Facebook – Socially Awesome Penguin [6] Tumblr – fuckyeahsociallyawesomepenguin
  [7] Chanarchive – Socially Awkward Penguin [8] Tumblr – say a word wrong [9] Reddit
  – socially awesome penguin [10] Smosh – Best of Socially Awesome Penguin! [11] Tumblr
  – #socially awesome penguin [12] Funny Junk – socially awesome penguin [13] Reddit
  – Socially awesome penguin [14] Quickmeme – Socially Awesome Awkward Penguin [14]
  Reddit – /r/IAmA'
aside_content: MemeStatusConfirmedYear2010OriginMeme GeneratorTagspenguin,social,awesomeAdditional
  ReferencesMeme Generator
added_at: '2011-09-25T01:07:45-04:00'
