example:
- say a word wrong
- create hilarious inside joke
keywords:
- null
name: Socially Awesome Penguin
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Socially Awesome Penguin | Know Your Meme Greetings! You must login\
  \ or signup first! Already a memeber? Login Now! Don't have an account? Sign up\
  \ Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos Submit\
  \ \u2192 Images Trending Most Commented Most Favorited High Score Low Score Most\
  \ Viewed All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Socially Awesome Penguin Added 13 years ago / Updated 10 days ago Confirmed\
  \ 141,257 View All 57 Images For more information, head to KYM Database: Socially\
  \ Awkward Penguin. Navigation About \u2022 Origin \u2022 Spread \u2022 Template\
  \ \u2022 Search Interest \u2022 External References \u2022 Recent Images \u2022\
  \ Recent Videos About Socially Awesome Penguin is an advice animal image macro series\
  \ featuring a photo of a penguin with a red color wheel background. As the antithesis\
  \ of Socially Awkward Penguin, the captions depict the character as popular, charismatic\
  \ and sexually attractive. Origin The original photo comes from a horizontally flipped\
  \ version of the Ad\xE9lie penguin used in the Socially Awkward Penguin series (shown\
  \ left), which first appeared on Tumblr in August of 2009. On January 13th, 2010,\
  \ the \"Fuck Yeah Socially Awesome Penguin\"[6] Tumblr blog was created, with the\
  \ first image macro featuring the caption \"Say a word wrong / create hilarious\
  \ inside joke\"[8] (shown right). The first image macros were watermarked by Meme\
  \ Generator[2], but the exact date of creation is currently unknown. On September\
  \ 13th, 2012, novelist Andy Weir claimed responsibility for the meme in a Reddit\
  \ AMA. [14] One user asked, \"what is something secret about you that Reddit doesn't\
  \ know?\" Weird responded: Nothing major, but some fun trivia about my life: I am\
  \ a computer programmer and I worked for Blizzard on Warcraft II (yes I'm that old).\
  \ Though I will never be able to prove it, I invented the \"Socially Awesome Penguin\"\
  \ image macro meme (as a response to \"Socially Awkward Penguin\" which was popular\
  \ at the time). I also created two webcomics, Casey and Andy and Cheshire Crossing.\
  \ Not exactly a secret, but nobody seems to know that. Spread On April 8th, 2010,\
  \ a Socially Awesome Penguin image macro with the caption \"Crush walks up to you\
  \ in hall / have a quick chat. You're meeting her after school\" was submitted to\
  \ a Socially Awkward penguin thread on 4chan's /b/ (random) board. On August 15th,\
  \ a second \"Socially Awesome Penguin\" Tumblr[1] was created. On January 3rd, 2011,\
  \ a post with several Socially Awesome Penguin derivatives was submitted to the\
  \ /r/AdviceAnimals[9] subreddit by Redditor Mano21, receiving 1,210 up votes prior\
  \ to being archived. A Socially Awesome Penguin Quickmeme[3] page was created the\
  \ same month. On March 1st, 2012, the Internet humor blog Smosh[10] published a\
  \ round-up of notable Socially Awesome Penguin derivatives from Tumblr and Reddit.\
  \ On April 7th, a video featuring two young boys interacting with an aquarium penguin\
  \ titled \"Logan Meets Socially Awesome Penguin\" was uploaded to YouTube by user\
  \ TXBeer. As of April 16th, 2012, the Quickmeme page has received over 3,500 submissions\
  \ and a Facebook[5] page for \"Socially Awesome Penguin\" has accumulated over 990\
  \ likes. Notable Examples The meme has continued to spread on sites like FunnyJunk[12],\
  \ Tumblr[11] and /r/AdviceAnimals[13] subreddit. Reverse Memes Some Socially Awesome\
  \ Penguin macros were created as direct reversals of Socially Awkward Penguin derivatives.\
  \ For example, the image below shows an examples of Socially Awkward Penguin, a\
  \ Socially Average Penguin and a Socially Awesome Penguin derivatives for the same\
  \ social situation. Hybrid Socially Awesome Penguin often appears in image macros\
  \ with its antithesis Socially Awkward Penguin. On May 12th, 2011, a \"Socially\
  \ Awesome Awkward Penguin\" Quickmeme[14] page was created, featuring macros with\
  \ half of the image portraying a successful social interaction and the other half\
  \ describing a socially awkward interaction. As of April 16th, 2012, the Quickmeme\
  \ page has received over 8,200 submissions. Template Search Interest External References\
  \ [1] Tumblr \u2013 Socially Awesome Penguin [2] Meme Generator \u2013 Socially\
  \ Awesome Penguin [3] Quickmeme \u2013 Socially Awesome Penguin [4] Smosh \u2013\
  \ Best of Socially Awesome Penguin! [5] Facebook \u2013 Socially Awesome Penguin\
  \ [6] Tumblr \u2013 fuckyeahsociallyawesomepenguin [7] Chanarchive \u2013 Socially\
  \ Awkward Penguin [8] Tumblr \u2013 say a word wrong [9] Reddit \u2013 socially\
  \ awesome penguin [10] Smosh \u2013 Best of Socially Awesome Penguin! [11] Tumblr\
  \ \u2013 #socially awesome penguin [12] Funny Junk \u2013 socially awesome penguin\
  \ [13] Reddit \u2013 Socially awesome penguin [14] Quickmeme \u2013 Socially Awesome\
  \ Awkward Penguin [14] Reddit \u2013 /r/IAmA penguin social awesome Share Pin Recent\
  \ Images 57 total View All Images Recent Videos 1 total View All Videos Sign up\
  \ for our Newsletter Load 17 Comments Comments 17 total 19 Socially Awesome Penguin\
  \ 141,257 1 57 17 Updated Dec 13, 2024 at 12:24PM EST by LiterallyAustin. Added\
  \ Sep 25, 2011 at 01:07AM EDT by xxpwnage223 _045. Like us on Facebook! Like 1.8M\
  \ Share Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the\
  \ video gallery, or 'r' to view a random entry. Meme Status Confirmed Year 2010\
  \ Origin Meme Generator Tags penguin, social, awesome Additional References Meme\
  \ Generator For more information, head to KYM Database: Socially Awkward Penguin.\
  \ About Socially Awesome Penguin is an advice animal image macro series featuring\
  \ a photo of a penguin with a red color wheel background. As the antithesis of Socially\
  \ Awkward Penguin, the captions depict the character as popular, charismatic and\
  \ sexually attractive. Origin The original photo comes from a horizontally flipped\
  \ version of the Ad\xE9lie penguin used in the Socially Awkward Penguin series (shown\
  \ left), which first appeared on Tumblr in August of 2009. On January 13th, 2010,\
  \ the \"Fuck Yeah Socially Awesome Penguin\"[6] Tumblr blog was created, with the\
  \ first image macro featuring the caption \"Say a word wrong / create hilarious\
  \ inside joke\"[8] (shown right). The first image macros were watermarked by Meme\
  \ Generator[2], but the exact date of creation is currently unknown. On September\
  \ 13th, 2012, novelist Andy Weir claimed responsibility for the meme in a Reddit\
  \ AMA. [14] One user asked, \"what is something secret about you that Reddit doesn't\
  \ know?\" Weird responded: Nothing major, but some fun trivia about my life: I am\
  \ a computer programmer and I worked for Blizzard on Warcraft II (yes I'm that old).\
  \ Though I will never be able to prove it, I invented the \"Socially Awesome Penguin\"\
  \ image macro meme (as a response to \"Socially Awkward Penguin\" which was popular\
  \ at the time). I also created two webcomics, Casey and Andy and Cheshire Crossing.\
  \ Not exactly a secret, but nobody seems to know that. Spread On April 8th, 2010,\
  \ a Socially Awesome Penguin image macro with the caption \"Crush walks up to you\
  \ in hall / have a quick chat. You're meeting her after school\" was submitted to\
  \ a Socially Awkward penguin thread on 4chan's /b/ (random) board. On August 15th,\
  \ a second \"Socially Awesome Penguin\" Tumblr[1] was created. On January 3rd, 2011,\
  \ a post with several Socially Awesome Penguin derivatives was submitted to the\
  \ /r/AdviceAnimals[9] subreddit by Redditor Mano21, receiving 1,210 up votes prior\
  \ to being archived. A Socially Awesome Penguin Quickmeme[3] page was created the\
  \ same month. On March 1st, 2012, the Internet humor blog Smosh[10] published a\
  \ round-up of notable Socially Awesome Penguin derivatives from Tumblr and Reddit.\
  \ On April 7th, a video featuring two young boys interacting with an aquarium penguin\
  \ titled \"Logan Meets Socially Awesome Penguin\" was uploaded to YouTube by user\
  \ TXBeer. As of April 16th, 2012, the Quickmeme page has received over 3,500 submissions\
  \ and a Facebook[5] page for \"Socially Awesome Penguin\" has accumulated over 990\
  \ likes. Notable Examples The meme has continued to spread on sites like FunnyJunk[12],\
  \ Tumblr[11] and /r/AdviceAnimals[13] subreddit. Reverse Memes Some Socially Awesome\
  \ Penguin macros were created as direct reversals of Socially Awkward Penguin derivatives.\
  \ For example, the image below shows an examples of Socially Awkward Penguin, a\
  \ Socially Average Penguin and a Socially Awesome Penguin derivatives for the same\
  \ social situation. Hybrid Socially Awesome Penguin often appears in image macros\
  \ with its antithesis Socially Awkward Penguin. On May 12th, 2011, a \"Socially\
  \ Awesome Awkward Penguin\" Quickmeme[14] page was created, featuring macros with\
  \ half of the image portraying a successful social interaction and the other half\
  \ describing a socially awkward interaction. As of April 16th, 2012, the Quickmeme\
  \ page has received over 8,200 submissions. Template Search Interest External References\
  \ [1] Tumblr \u2013 Socially Awesome Penguin [2] Meme Generator \u2013 Socially\
  \ Awesome Penguin [3] Quickmeme \u2013 Socially Awesome Penguin [4] Smosh \u2013\
  \ Best of Socially Awesome Penguin! [5] Facebook \u2013 Socially Awesome Penguin\
  \ [6] Tumblr \u2013 fuckyeahsociallyawesomepenguin [7] Chanarchive \u2013 Socially\
  \ Awkward Penguin [8] Tumblr \u2013 say a word wrong [9] Reddit \u2013 socially\
  \ awesome penguin [10] Smosh \u2013 Best of Socially Awesome Penguin! [11] Tumblr\
  \ \u2013 #socially awesome penguin [12] Funny Junk \u2013 socially awesome penguin\
  \ [13] Reddit \u2013 Socially awesome penguin [14] Quickmeme \u2013 Socially Awesome\
  \ Awkward Penguin [14] Reddit \u2013 /r/IAmA Recent Videos 1 total \u639B\u5DDD\u82B1\
  \u9CE5\u5712\u3000\u65B0\u805E\u3092\u6301\u3063\u3066\u304F\u308B\u30DA\u30F3\u30AE\
  \u30F3 Socially Awesome Penguin Uploaded by tokyo + Add a Video Recent Images 57\
  \ total Socially Awesome Penguin Uploaded by Reddit Moments Socially Awesome Penguin\
  \ Uploaded by Aidan Walker Socially Awesome Penguin Uploaded by Rebecca Rhodes Socially\
  \ Awesome Penguin Uploaded by Wayneee Socially Awesome Penguin Uploaded by Dr. Gregory\
  \ Horse The Pony ... Socially Awesome Penguin Uploaded by Patologi Socially Awesome\
  \ Penguin Uploaded by Brad Socially Awesome Penguin Uploaded by Brad Socially Awesome\
  \ Penguin Uploaded by Brad Socially Awesome Penguin Uploaded by Don Socially Awesome\
  \ Penguin Uploaded by Brad Socially Awesome Penguin Uploaded by Don + Add an Image\
  \ View All Images Sign up for our Newsletter Top Comment Delete Sensitive Cyber6x\
  \ Moderator Sep 25, 2011 at 02:47AM EDT Not sure if this is strong enough to deserve\
  \ its own entry. Maybe should of just been added to the socially awkward penguin\
  \ entry. +15 Reply + Add a Comment Comments (17) Display Comments Add a Comment\
  \ Top Entries This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (5) xxpwnage223\
  \ _045 Sleuth & Commentator Don Administrator & Meme Daddy Brad Digital Archaeologist\
  \ & Treasurer & Pundit & Gallery Housekeeper RandomMan Database Moderator & God\
  \ Tier Swag & Protip Advisor & Karma Tycoon & Meme Boi Matt Secretary of Memes \u25BC\
  \ + Request Editorship View All Editors Today's Top Image Galleries Assassination\
  \ of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing\
  \ Digital Circus About Our Story Site Rules Policies and Guidelines Credits Contact\
  \ Meme DB Memes Episodes News Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/socially-awesome-penguin
template_id: awesome
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
