example:
- left on unread
- left on read
keywords:
- null
name: Drakeposting
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Drakeposting | Know Your Meme 'lo! You must login or signup first!\
  \ Already a memeber? Login Now! Don't have an account? Sign up Now! Meme Encyclopedia\
  \ All Cultures Events People Sites Subcultures Videos Submit \u2192 Images Trending\
  \ Most Commented Most Favorited High Score Low Score Most Viewed All Templates Upload\
  \ an Image Articles News Explainers Collections Interviews Meme Insider Magazine\
  \ More Discord Newsletter Episodes Forums Meme Store Login Abstract user icon Memes\
  \ Categories Trending News Images Trending Images Videos Trending Videos Editorials\
  \ Meme Insider Magazine Newsletter Policies and Guidelines Meme Store Old site Login\
  \ Know Your Meme is the property of Literally Media \xA92024 Literally Media. All\
  \ Rights Reserved. This image Of Woman Confidently Strolling Through A Glass Panel\
  \ Has Been A Redraw Format Since 2021 Three Years Ago, This Boar's Head 'Exploded'\
  \ Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess Memes Turns Two Years\
  \ Old Today Phrase 'The Fridge Protects The Snacks' A Growing Favorite Among Pickup\
  \ Artist Influencers Jamie G, The Bosh British Charva, Has Taken Over TikTok With\
  \ His Signature 'Oh Cherie Amour' Sound Also Trending: Honey Extension Influencer\
  \ Scam Renegade Raider Copypasta Assassination of UnitedHealthcare CEO Drakeposting\
  \ Added 8 years ago / Updated 8 days ago Confirmed 475,817 Part of a series on Hotline\
  \ Bling. [View Related Entries] [View Related Sub-entries] View All 659 Images Navigation\
  \ About \u2022 Origin \u2022 Spread \u2022 Examples \u2022 Similar Memes \u2022\
  \ Search Interests \u2022 External References \u2022 Recent Images \u2022 Recent\
  \ Videos About Drakeposting refers to the practice of posting reaction images and\
  \ other still shots from the music video of the Canadian hip hop artist's 2015 hit\
  \ single Hotline Bling on the imageboard site 4chan, typically to express one's\
  \ disdain of the thread topic or something said by another poster in a similar vein\
  \ to the usage of Costanza.jpg. Origin The original image is taken from the music\
  \ video of Drake's 2015 hit R&B single \"Hotline Bling\", in which the hip hop artist\
  \ performs several different dance moves and gestures, including one that shows\
  \ him holding his hand up to the side of his face while looking disgusted (shown\
  \ below). The pose in question was subsequently isolated into a reaction image and\
  \ began circulating on 4chan's /v/ (video games) board as early as mid-to-late 2015\
  \ (shown below), with its earliest known usage as a reaction image found in a /v/\
  \ (video game) thread[1] about first-person shooter games posted on October 31st\
  \ earlier that year. Meanwhile, the earliest use of the term \"Drakeposting\" to\
  \ describe general discussions about the hip hop artist on 4chan dates back to a\
  \ comment posted in a /fit/ (fitness) thread[2] on May 4th, 2015. Spread In January\
  \ 2016, the usage of Drake's screenshot images from the music video \"Hotline Bling\"\
  \ quickly snowballed into a shitpostng trend across various forums on 4chan, including\
  \ /mu/[3] on January 3rd, /int/[4] (international) on January 5th, /v/[5] (video\
  \ games) on January 8th, /g/[8] (technology) on January 16th. Between January and\
  \ March in 2016, the term \"drakeposting\" was mentioned in hundreds of independently\
  \ archived discussion threads across 4chan.[9][10][11][12][13][14] As a result of\
  \ its growing presence on 4chan imageboards, the \"drakeposting\" phenomenon has\
  \ prompted a number of tangential discussion threads on Sheeky Forum, a 4chan-affiliated\
  \ community and archive site, as well as on Reddit's /r/4chan section. On January\
  \ 30th, Sheeky Forum user TechHater[15] asked about the popularity of \"drakeposting\"\
  \ on the site in a Q&A thread.[4] On February 2nd, Redditor Bobbistef[18] mentioned\
  \ \"drakeposting\" in response to an /r/4chan thread introducing the arrival of\
  \ a new exploitable meme based on the character Pacha from Disney\u2018s 2000 animated\
  \ buddy comedy film The Emperor's New Groove . On February 22nd, Sheeky Forum user\
  \ Need_TLC[17] started a survey asking other forum members' favorite Drake songs\
  \ in a thread titled \"Now that Drake is officially vidya related Sheeky Forums\
  \ culture, what is your favorite Drake song?\" Cat Drake On December 15th, 2016,\
  \ Instagram [22] user @yisucrist published a photoshopped version of the Drake \"\
  Don't Like/Like\" exploitable, featuring a black cat's head edited onto Drake's\
  \ body. Next to the cats are a cat toy and a cat box. The post (shown below) received\
  \ more than 32,000 likes in a little over one year. About 14 months later, on February\
  \ 22nd, Twitter[19] user @DustyFotter posted a version of this meme with a new cat\
  \ superimposed over Drake's face . Next to the images of the cat are a cat bed and\
  \ a cardboard box, indicating that cats prefer the box to the bed. The post (shown\
  \ below, left) received more than 12,000 retweets and 28,000 likes in four days.\
  \ Later that day, Redditor[20] JM-Rie posted a variation on the /r/memes subreddit,\
  \ featuring a keyboard instead of the cardboard box. The post (shown below, center)\
  \ received more than 27,000 points (92% upvoted) and 190 comments. Over the next\
  \ few hours, people began posting more variants of the meme based on common traits\
  \ found in cats (example below, right). The following day, The Daily Dot[21] published\
  \ an article on the emergence of the meme. Examples Similar Memes Drakeposting,\
  \ in its original form, has inspired several similar meme templates, with a person\
  \ shown disagreeing with a statement and agreeing with a counter-statement. The\
  \ most recurrent forms of such memes feature tiktoker Brittany Broski, aka Kombucha\
  \ Girl (see below on the left), and Star Trek character Geordi La Forge (see below\
  \ on the right). Search Interests External References [1] 4chan Archive \u2013 FPS\
  \ games (site down) [2] DesuArchive \u2013 Lyndsay: not a fan of Drakeposting [3]\
  \ 4chan Archive \u2013 drakeposting in 2015 [4] DesuArchive \u2013 Australians Are\
  \ Waking Up [5] 4chan Archive \u2013 ITT: Quality Memes [6] rebeccablacktech \u2013\
  \ 1366\xD7768 [7] rebeccablacktech \u2013 Java Programming [8] 4chan Archive \u2013\
  \ Touching Water Kills You [9] DesuArchive \u2013 Post Results for 'drakeposting'\
  \ [10] Fireden \u2013 Post Results for 'drakeposting' [11] Arch.b4k.co \u2013 Post\
  \ Results for 'drakeposting' [12] RebeccaBlackTech \u2013 /mu/ Post Results for\
  \ 'drakeposting' [13] RebeccaBlackTech \u2013 /g/ Post Results for 'drakeposting'\
  \ [14] DesuArchive \u2013 /int/ Post Results for 'drakeposting' [15] Sheeky Forums\
  \ \u2013 Could someone explain to me why Drakeposting is so popular on Sheeky Forums?\
  \ (site down) [16] Sheeky Forums \u2013 Give Me One Reason to Play Your Favorite\
  \ Game (site down) [17] Sheeky Forums \u2013 Now That drake Is Officially Vidya\
  \ Related and Sheeky Forum Culture, What's Your Favorite Drake Song (site down)\
  \ [18] Reddit \u2013 Spicy New Meme Pacha [19] Twitter \u2013 @DustyFotter's Tweet\
  \ [20] Reddit \u2013 Of all places to loaf around [21] The Daily Dot \u2013 \u2018\
  Cat Drake\u2019 is the feline-friendly meme you need in your life [22] Instagram\
  \ \u2013 @yisucrist's Post (login needed) drake reaction image 4chan techhater bobbistef\
  \ yisucrist dustyfotter jm-rie sheeky forum Share Pin Sub-entries 2 total Old Man\
  \ Turning Back Towards ... Coolyori / Sayori Drake Meme Recent Images 659 total\
  \ View All Images Recent Videos 4 total View All Videos Sign up for our Newsletter\
  \ Load 15 Comments Comments 15 total 76 Drakeposting 475,817 4 659 15 Part of a\
  \ series on Hotline Bling. [View Related Entries] [View Related Sub-entries] Updated\
  \ Dec 15, 2024 at 07:19PM EST by LiterallyAustin. Added Mar 31, 2016 at 03:47AM\
  \ EDT by James Blunt. Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press\
  \ 'i' to view the image gallery, 'v' to view the video gallery, or 'r' to view a\
  \ random entry. Meme Status Confirmed Type: Exploitable, Reaction Year 2015 Origin\
  \ 4chan Tags drake, reaction image, 4chan, techhater, bobbistef, yisucrist, dustyfotter,\
  \ jm-rie, sheeky forum Additional References Meme Generator About Drakeposting refers\
  \ to the practice of posting reaction images and other still shots from the music\
  \ video of the Canadian hip hop artist's 2015 hit single Hotline Bling on the imageboard\
  \ site 4chan, typically to express one's disdain of the thread topic or something\
  \ said by another poster in a similar vein to the usage of Costanza.jpg. Origin\
  \ The original image is taken from the music video of Drake's 2015 hit R&B single\
  \ \"Hotline Bling\", in which the hip hop artist performs several different dance\
  \ moves and gestures, including one that shows him holding his hand up to the side\
  \ of his face while looking disgusted (shown below). The pose in question was subsequently\
  \ isolated into a reaction image and began circulating on 4chan's /v/ (video games)\
  \ board as early as mid-to-late 2015 (shown below), with its earliest known usage\
  \ as a reaction image found in a /v/ (video game) thread[1] about first-person shooter\
  \ games posted on October 31st earlier that year. Meanwhile, the earliest use of\
  \ the term \"Drakeposting\" to describe general discussions about the hip hop artist\
  \ on 4chan dates back to a comment posted in a /fit/ (fitness) thread[2] on May\
  \ 4th, 2015. Spread In January 2016, the usage of Drake's screenshot images from\
  \ the music video \"Hotline Bling\" quickly snowballed into a shitpostng trend across\
  \ various forums on 4chan, including /mu/[3] on January 3rd, /int/[4] (international)\
  \ on January 5th, /v/[5] (video games) on January 8th, /g/[8] (technology) on January\
  \ 16th. Between January and March in 2016, the term \"drakeposting\" was mentioned\
  \ in hundreds of independently archived discussion threads across 4chan.[9][10][11][12][13][14]\
  \ As a result of its growing presence on 4chan imageboards, the \"drakeposting\"\
  \ phenomenon has prompted a number of tangential discussion threads on Sheeky Forum,\
  \ a 4chan-affiliated community and archive site, as well as on Reddit's /r/4chan\
  \ section. On January 30th, Sheeky Forum user TechHater[15] asked about the popularity\
  \ of \"drakeposting\" on the site in a Q&A thread.[4] On February 2nd, Redditor\
  \ Bobbistef[18] mentioned \"drakeposting\" in response to an /r/4chan thread introducing\
  \ the arrival of a new exploitable meme based on the character Pacha from Disney\u2018\
  s 2000 animated buddy comedy film The Emperor's New Groove . On February 22nd, Sheeky\
  \ Forum user Need_TLC[17] started a survey asking other forum members' favorite\
  \ Drake songs in a thread titled \"Now that Drake is officially vidya related Sheeky\
  \ Forums culture, what is your favorite Drake song?\" Cat Drake On December 15th,\
  \ 2016, Instagram [22] user @yisucrist published a photoshopped version of the Drake\
  \ \"Don't Like/Like\" exploitable, featuring a black cat's head edited onto Drake's\
  \ body. Next to the cats are a cat toy and a cat box. The post (shown below) received\
  \ more than 32,000 likes in a little over one year. About 14 months later, on February\
  \ 22nd, Twitter[19] user @DustyFotter posted a version of this meme with a new cat\
  \ superimposed over Drake's face . Next to the images of the cat are a cat bed and\
  \ a cardboard box, indicating that cats prefer the box to the bed. The post (shown\
  \ below, left) received more than 12,000 retweets and 28,000 likes in four days.\
  \ Later that day, Redditor[20] JM-Rie posted a variation on the /r/memes subreddit,\
  \ featuring a keyboard instead of the cardboard box. The post (shown below, center)\
  \ received more than 27,000 points (92% upvoted) and 190 comments. Over the next\
  \ few hours, people began posting more variants of the meme based on common traits\
  \ found in cats (example below, right). The following day, The Daily Dot[21] published\
  \ an article on the emergence of the meme. Examples Similar Memes Drakeposting,\
  \ in its original form, has inspired several similar meme templates, with a person\
  \ shown disagreeing with a statement and agreeing with a counter-statement. The\
  \ most recurrent forms of such memes feature tiktoker Brittany Broski, aka Kombucha\
  \ Girl (see below on the left), and Star Trek character Geordi La Forge (see below\
  \ on the right). Search Interests External References [1] 4chan Archive \u2013 FPS\
  \ games (site down) [2] DesuArchive \u2013 Lyndsay: not a fan of Drakeposting [3]\
  \ 4chan Archive \u2013 drakeposting in 2015 [4] DesuArchive \u2013 Australians Are\
  \ Waking Up [5] 4chan Archive \u2013 ITT: Quality Memes [6] rebeccablacktech \u2013\
  \ 1366\xD7768 [7] rebeccablacktech \u2013 Java Programming [8] 4chan Archive \u2013\
  \ Touching Water Kills You [9] DesuArchive \u2013 Post Results for 'drakeposting'\
  \ [10] Fireden \u2013 Post Results for 'drakeposting' [11] Arch.b4k.co \u2013 Post\
  \ Results for 'drakeposting' [12] RebeccaBlackTech \u2013 /mu/ Post Results for\
  \ 'drakeposting' [13] RebeccaBlackTech \u2013 /g/ Post Results for 'drakeposting'\
  \ [14] DesuArchive \u2013 /int/ Post Results for 'drakeposting' [15] Sheeky Forums\
  \ \u2013 Could someone explain to me why Drakeposting is so popular on Sheeky Forums?\
  \ (site down) [16] Sheeky Forums \u2013 Give Me One Reason to Play Your Favorite\
  \ Game (site down) [17] Sheeky Forums \u2013 Now That drake Is Officially Vidya\
  \ Related and Sheeky Forum Culture, What's Your Favorite Drake Song (site down)\
  \ [18] Reddit \u2013 Spicy New Meme Pacha [19] Twitter \u2013 @DustyFotter's Tweet\
  \ [20] Reddit \u2013 Of all places to loaf around [21] The Daily Dot \u2013 \u2018\
  Cat Drake\u2019 is the feline-friendly meme you need in your life [22] Instagram\
  \ \u2013 @yisucrist's Post (login needed) Sub-entries 2 total Old Man Turning Back\
  \ Towards Sex Workers Coolyori / Sayori Drake Meme Recent Videos 4 total ORIGEN\
  \ MEME- Drake-Hotline Bl... Drakeposting Uploaded by shevyrolet Drake - Hotline\
  \ Bling Drakeposting Uploaded by shevyrolet DRAKEPOSTING MEME COMPILATION Drakeposting\
  \ Uploaded by shevyrolet STL sucks ass Drakeposting Uploaded by John-XZ + Add a\
  \ Video Recent Images 659 total Drakeposting Uploaded by Jaimie Hamilton Drakeposting\
  \ Uploaded by Triplem Drakeposting Uploaded by Triplem Drakeposting Uploaded by\
  \ Jaimie Hamilton Drakeposting Uploaded by Triplem Drakeposting Uploaded by Jaimie\
  \ Hamilton Drakeposting Uploaded by Cold Hard Crash Drakeposting Uploaded by Reddit\
  \ Moments Drakeposting Uploaded by Classic Rage Meme Rook 96 Drakeposting Uploaded\
  \ by Anyone00 Drakeposting Uploaded by Triplem Drakeposting Uploaded by Triplem\
  \ + Add an Image View All Images Sign up for our Newsletter Top Comments Delete\
  \ Sensitive nickrage Apr 02, 2016 at 09:45AM EDT in reply to Jack the Dipper \"\
  The normies took our memes so we took theirs\" +48 Reply Delete Sensitive Jack the\
  \ Dipper Mar 31, 2016 at 06:26PM EDT I would have never imagined 4chan taking any\
  \ sort of liking to Drake. +42 Reply + Add a Comment Comments (15) Display Comments\
  \ Add a Comment Top Entries This Month Meme Saika Kawakita Smile GIF Event Assassination\
  \ of UnitedHealthcare CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki\
  \ Sisters Culture Pornography Site Whisper View More Suggest a Change Edit History\
  \ Entry Editors (11) James Blunt Entry Moderator & Music Maven \xAD\xAD\xADAlex\
  \ Mercer Entry Moderator & YouTube Scatologist Brad Digital Archaeologist & Treasurer\
  \ & Pundit & Gallery Housekeeper Y F Digital Archaeologist & Treasurer & Media Maid\
  \ Matt Secretary of Memes andcallmeshirley Digital Archaeologist & Treasurer & Collection\
  \ Butler Kevinvq2 Sr. Researcher & Scrapbooker & Media Chauffeur ohmyjosh Digital\
  \ Archaeologist & Cataloger shevyrolet Digital Archaeologist & Treasurer & Media\
  \ Bus Boy Triplem Entry Moderator Zach Memenator \u25BC + Request Editorship View\
  \ All Editors Today's Top Image Galleries Assassination of UnitedHealthcare CEO\
  \ Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing Digital Circus About\
  \ Our Story Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes\
  \ News Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/drakeposting
template_id: drake
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
