name: Drakeposting
source: http://knowyourmeme.com/memes/drakeposting
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- left on unread
- left on read
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Drakeposting refers to the practice of posting reaction images
  and other still shots from the music video of the Canadian hip hop artist''s 2015
  hit single Hotline Bling on the imageboard site 4chan, typically to express one''s
  disdain of the thread topic or something said by another poster in a similar vein
  to the usage of Costanza.jpg. Origin The original image is taken from the music
  video of Drake''s 2015 hit R&B single "Hotline Bling", in which the hip hop artist
  performs several different dance moves and gestures, including one that shows him
  holding his hand up to the side of his face while looking disgusted (shown below).
  The pose in question was subsequently isolated into a reaction image and began circulating
  on 4chan''s /v/ (video games) board as early as mid-to-late 2015 (shown below),
  with its earliest known usage as a reaction image found in a /v/ (video game) thread[1]
  about first-person shooter games posted on October 31st earlier that year. Meanwhile,
  the earliest use of the term "Drakeposting" to describe general discussions about
  the hip hop artist on 4chan dates back to a comment posted in a /fit/ (fitness)
  thread[2] on May 4th, 2015. Spread In January 2016, the usage of Drake''s screenshot
  images from the music video "Hotline Bling" quickly snowballed into a shitpostng
  trend across various forums on 4chan, including /mu/[3] on January 3rd, /int/[4]
  (international) on January 5th, /v/[5] (video games) on January 8th, /g/[8] (technology)
  on January 16th. Between January and March in 2016, the term "drakeposting" was
  mentioned in hundreds of independently archived discussion threads across 4chan.[9][10][11][12][13][14]
  As a result of its growing presence on 4chan imageboards, the "drakeposting" phenomenon
  has prompted a number of tangential discussion threads on Sheeky Forum, a 4chan-affiliated
  community and archive site, as well as on Reddit''s /r/4chan section. On January
  30th, Sheeky Forum user TechHater[15] asked about the popularity of "drakeposting"
  on the site in a Q&A thread.[4] On February 2nd, Redditor Bobbistef[18] mentioned
  "drakeposting" in response to an /r/4chan thread introducing the arrival of a new
  exploitable meme based on the character Pacha from Disney‘s 2000 animated buddy
  comedy film The Emperor''s New Groove . On February 22nd, Sheeky Forum user Need_TLC[17]
  started a survey asking other forum members'' favorite Drake songs in a thread titled
  "Now that Drake is officially vidya related Sheeky Forums culture, what is your
  favorite Drake song?" Cat Drake On December 15th, 2016, Instagram [22] user @yisucrist
  published a photoshopped version of the Drake "Don''t Like/Like" exploitable, featuring
  a black cat''s head edited onto Drake''s body. Next to the cats are a cat toy and
  a cat box. The post (shown below) received more than 32,000 likes in a little over
  one year. About 14 months later, on February 22nd, Twitter[19] user @DustyFotter
  posted a version of this meme with a new cat superimposed over Drake''s face . Next
  to the images of the cat are a cat bed and a cardboard box, indicating that cats
  prefer the box to the bed. The post (shown below, left) received more than 12,000
  retweets and 28,000 likes in four days. Later that day, Redditor[20] JM-Rie posted
  a variation on the /r/memes subreddit, featuring a keyboard instead of the cardboard
  box. The post (shown below, center) received more than 27,000 points (92% upvoted)
  and 190 comments. Over the next few hours, people began posting more variants of
  the meme based on common traits found in cats (example below, right). The following
  day, The Daily Dot[21] published an article on the emergence of the meme. Examples
  Similar Memes Drakeposting, in its original form, has inspired several similar meme
  templates, with a person shown disagreeing with a statement and agreeing with a
  counter-statement. The most recurrent forms of such memes feature tiktoker Brittany
  Broski, aka Kombucha Girl (see below on the left), and Star Trek character Geordi
  La Forge (see below on the right). Search Interests External References [1] 4chan
  Archive – FPS games (site down) [2] DesuArchive – Lyndsay: not a fan of Drakeposting
  [3] 4chan Archive – drakeposting in 2015 [4] DesuArchive – Australians Are Waking
  Up [5] 4chan Archive – ITT: Quality Memes [6] rebeccablacktech – 1366×768 [7] rebeccablacktech
  – Java Programming [8] 4chan Archive – Touching Water Kills You [9] DesuArchive
  – Post Results for ''drakeposting'' [10] Fireden – Post Results for ''drakeposting''
  [11] Arch.b4k.co – Post Results for ''drakeposting'' [12] RebeccaBlackTech – /mu/
  Post Results for ''drakeposting'' [13] RebeccaBlackTech – /g/ Post Results for ''drakeposting''
  [14] DesuArchive – /int/ Post Results for ''drakeposting'' [15] Sheeky Forums –
  Could someone explain to me why Drakeposting is so popular on Sheeky Forums? (site
  down) [16] Sheeky Forums – Give Me One Reason to Play Your Favorite Game (site down)
  [17] Sheeky Forums – Now That drake Is Officially Vidya Related and Sheeky Forum
  Culture, What''s Your Favorite Drake Song (site down) [18] Reddit – Spicy New Meme
  Pacha [19] Twitter – @DustyFotter''s Tweet [20] Reddit – Of all places to loaf around
  [21] The Daily Dot – ‘Cat Drake’ is the feline-friendly meme you need in your life
  [22] Instagram – @yisucrist''s Post (login needed)'
aside_content: MemeStatusConfirmedType:Exploitable,ReactionYear2015Origin4chanTagsdrake,reaction
  image,4chan,techhater,bobbistef,yisucrist,dustyfotter,jm-rie,sheeky forumAdditional
  ReferencesMeme Generator
added_at: '2016-03-31T03:47:57-04:00'
