name: Patrick Star's Wallet
source: https://knowyourmeme.com/memes/patrick-stars-wallet
keywords:
- null
text:
- style: default
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.17
  angle: 0.0
  scale_x: 0.5
  scale_y: 0.08
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: khaki
  font: thin
  anchor_x: 0.5
  anchor_y: 0.18
  angle: 0.0
  scale_x: 0.5
  scale_y: 0.07
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.4
  angle: 0.0
  scale_x: 0.5
  scale_y: 0.1
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: khaki
  font: thin
  anchor_x: 0.5
  anchor_y: 0.43
  angle: 0.0
  scale_x: 0.5
  scale_y: 0.07
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.65
  angle: 0.0
  scale_x: 0.5
  scale_y: 0.1
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: khaki
  font: thin
  anchor_x: 0.5
  anchor_y: 0.67
  angle: 0.0
  scale_x: 0.5
  scale_y: 0.08
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.92
  angle: 0.0
  scale_x: 0.5
  scale_y: 0.08
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: khaki
  font: thin
  anchor_x: 0.5
  anchor_y: 0.92
  angle: 0.0
  scale_x: 0.5
  scale_y: 0.08
  align: center
  start: 0.0
  stop: 1.0
example:
- Aren't you Patrick Star?
- Yup.
- And this is your ID?
- Yup.
- I found the ID in this wallet so it must be yours.
- That makes sense to me.
- Then take it!
- It's not my wallet.
overlay:
- center_x: 0.22
  center_y: 0.12
  angle: 0.0
  scale: 0.21
scraped_content: About Patrick Star Wallet refers to a scene from Spongebob Squarepants
  in which the villain Man Ray attempts to teach a lesson about morality to Patrick
  Star. The scene has been parodied and turned into an exploitable in which the characters
  and dialogue are altered. Origin On September 14th, 2001, the Spongebob Squarepants
  episode "Mermaid Man and Barnacle Boy III" premiered in the United States.[1] In
  the episode, Man Ray roleplays giving back Patrick's lost wallet. However, Patrick
  denies that the wallet is his despite Man Ray's logical reasoning, angering him
  (shown below). An image macro of the scene appeared online in the mid-2010s. An
  example was posted on Imgur on July 21st, 2013,[2] though the image had been circulating
  online prior. Spread The image began to grow into an exploitable in the summer of
  2016. On August 1st, one of the earliest examples was posted to Imgur, [3] in which
  Patrick is represented as an Xbox and Man Ray is represented as a gamer. The post
  has been viewed over 40,000 times (shown below). The exploitables soon adopted a
  political tone, as people satirized their frustrations with opposing viewpoints
  by representing the opposing viewpoint as Patrick. For example, a popular edit satirizing
  Not My President Democrats has Patrick agreeing to all the conditions that would
  make Donald Trump one's president, then staunchly denying that Trump is his president[4]
  (shown below, top). From the other side, a GIF of the scene in which Patrick represents
  the Alt-Right gained over 139,000 views on Imgur (shown below, bottom).[5] Political
  edits have made up the majority of the edits, though there have been examples featuring
  different topics, particularly video games. No this is Patrick Various Examples
  Search Interest External References [1] Spongebob Wikia – Mermaid Man and Barnacle
  Boy III [2] Imgur – Comic Form [3] Imgur – Xbox Post [4] Imgur – Not My President
  [5] Imgur – Alt-Right
aside_content: MemeStatusConfirmedType:ExploitableYear2016OriginSpongebob SquarepantsTagsspongbebob
  squarepants,patrick star,man-ray,exploitable
added_at: '2017-08-18T14:44:59-04:00'
