example:
- Walk in a straight line?
- Officer, I can barely stand
keywords:
- null
name: Drunk Baby
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Drunk Baby | Know Your Meme Yo Yo! You must login or signup first!\
  \ Already a memeber? Login Now! Don't have an account? Sign up Now! Meme Encyclopedia\
  \ All Cultures Events People Sites Subcultures Videos Submit \u2192 Images Trending\
  \ Most Commented Most Favorited High Score Low Score Most Viewed All Templates Upload\
  \ an Image Articles News Explainers Collections Interviews Meme Insider Magazine\
  \ More Discord Newsletter Episodes Forums Meme Store Login Abstract user icon Memes\
  \ Categories Trending News Images Trending Images Videos Trending Videos Editorials\
  \ Meme Insider Magazine Newsletter Policies and Guidelines Meme Store Old site Login\
  \ Know Your Meme is the property of Literally Media \xA92024 Literally Media. All\
  \ Rights Reserved. This image Of Woman Confidently Strolling Through A Glass Panel\
  \ Has Been A Redraw Format Since 2021 Three Years Ago, This Boar's Head 'Exploded'\
  \ Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess Memes Turns Two Years\
  \ Old Today Phrase 'The Fridge Protects The Snacks' A Growing Favorite Among Pickup\
  \ Artist Influencers Jamie G, The Bosh British Charva, Has Taken Over TikTok With\
  \ His Signature 'Oh Cherie Amour' Sound Also Trending: Honey Extension Influencer\
  \ Scam Renegade Raider Copypasta Assassination of UnitedHealthcare CEO Drunk Baby\
  \ Added 12 years ago / Updated 8 days ago Confirmed 226,186 Part of a series on\
  \ Babies. [View Related Entries] View All 67 Images Navigation About \u2022 Origin\
  \ \u2022 Spread \u2022 Notable Examples \u2022 Search Interest \u2022 External References\
  \ \u2022 Recent Images \u2022 Recent Videos About Drunk Baby is an advice animal\
  \ image macro series featuring a photograph of an infant sitting next to a pint\
  \ of beer. The captions typically portray the baby as an intoxicated storyteller\
  \ mimicking the behavior of older bar patrons. Origin The original baby photograph\
  \ (shown below, left) was submitted to the /r/funny[7] subreddit by user MaryjaneBrewington\
  \ in a post titled \"She tells the worst jokes\" on June 25th, 2012. The same day,\
  \ the first Drunk Baby image macro was submitted by Redditor snicklefritz618 to\
  \ the /r/AdviceAnimals[1] subreddit, which included the caption \"This guy\u2026\
  . / I love this guy\" (shown below, right). Within 10 days, the post received over\
  \ 6,600 up votes and 100 comments. Spread On June 26th, 2012, the Internet culture\
  \ blog Slacktory[2] published an article titled \"Drunk Baby: Another Damn Advice\
  \ Meme\", which noted the series' growing presence on Reddit despite Redditor's\
  \ tendency to get more easily jaded by child-based memes than Tumblr users. The\
  \ same day, 9gag[10] user heartstorm90 submitted an image macro with the caption\
  \ \"Hey you. Yeah, You. / I totally sucked your wife's tits\", receiving over 3,000\
  \ Facebook shares within 10 days. On June 27th, the Internet humor blog UpRoxx[4]\
  \ published a post titled \"Meme Watch: Drunk Bank Is Holding Court At The Bar\"\
  , including a slideshow of notable examples from the series. The same day, The Huffington\
  \ Post[5] published an article titled \"Drunk Baby Is Totally Going To Regret This\
  \ Tomorrow\" and the Internet humor site The FW[6] listed Drunk Baby in their \"\
  Funniest Memes of the Week\" post. On June 29th, a Facebook[9] page for \"Drunk\
  \ Baby\" was created, which received over 50 likes within one week. The meme has\
  \ continued to spread on Tumblr[8] under the tag \"#drunk baby.\" As of July 6th,\
  \ 2012, the Drunk Baby Quickmeme[3] page has accumulated over 1,550 submissions.\
  \ Notable Examples Search Interest External References [1] Reddit \u2013 Introducing\u2026\
  .Drunk Baby [2] Slacktory \u2013 Drunk Baby \u2013 Another Damn Baby Advice Meme\
  \ [3] Quickmeme \u2013 Drunk Baby [4] UpRoxx \u2013 Drunk Baby is Holding Court\
  \ At The Bar [5] The Huffington Post \u2013 Drunk Baby is Totally Going to Regret\
  \ This Tomorrow [6] The FW \u2013 Funniest Memes of the Week \u2013 Drunk Baby,\
  \ Implying Dog and more [7] Reddit \u2013 She tells the worst jokes [8] Tumblr \u2013\
  \ #drunk baby [9] Facebook \u2013 Drunk Baby [10] 9gag \u2013 Drunk Baby baby drunk\
  \ advice animal hangover maryjanebrewington snicklefritz618 slacktory heartstorm90\
  \ Share Pin Related Entries 14 total Success Kid / I Hate Sandcastles Dancing Baby\
  \ Babby Baby Godfather View All Related Entries Recent Images 67 total View All\
  \ Images Recent Videos 1 total View All Videos Sign up for our Newsletter Load 16\
  \ Comments Comments 16 total 26 Drunk Baby 226,186 1 67 16 Part of a series on Babies.\
  \ [View Related Entries] Updated Dec 15, 2024 at 03:47PM EST by LiterallyAustin.\
  \ Added Jun 27, 2012 at 11:47AM EDT by Z.. Like us on Facebook! Like 1.8M Share\
  \ Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the video\
  \ gallery, or 'r' to view a random entry. Meme Status Confirmed Type: Image Macro\
  \ Year 2012 Origin Reddit Tags baby, drunk, advice animal, hangover, maryjanebrewington,\
  \ snicklefritz618, slacktory, heartstorm90 Additional References Meme Generator\
  \ About Drunk Baby is an advice animal image macro series featuring a photograph\
  \ of an infant sitting next to a pint of beer. The captions typically portray the\
  \ baby as an intoxicated storyteller mimicking the behavior of older bar patrons.\
  \ Origin The original baby photograph (shown below, left) was submitted to the /r/funny[7]\
  \ subreddit by user MaryjaneBrewington in a post titled \"She tells the worst jokes\"\
  \ on June 25th, 2012. The same day, the first Drunk Baby image macro was submitted\
  \ by Redditor snicklefritz618 to the /r/AdviceAnimals[1] subreddit, which included\
  \ the caption \"This guy\u2026. / I love this guy\" (shown below, right). Within\
  \ 10 days, the post received over 6,600 up votes and 100 comments. Spread On June\
  \ 26th, 2012, the Internet culture blog Slacktory[2] published an article titled\
  \ \"Drunk Baby: Another Damn Advice Meme\", which noted the series' growing presence\
  \ on Reddit despite Redditor's tendency to get more easily jaded by child-based\
  \ memes than Tumblr users. The same day, 9gag[10] user heartstorm90 submitted an\
  \ image macro with the caption \"Hey you. Yeah, You. / I totally sucked your wife's\
  \ tits\", receiving over 3,000 Facebook shares within 10 days. On June 27th, the\
  \ Internet humor blog UpRoxx[4] published a post titled \"Meme Watch: Drunk Bank\
  \ Is Holding Court At The Bar\", including a slideshow of notable examples from\
  \ the series. The same day, The Huffington Post[5] published an article titled \"\
  Drunk Baby Is Totally Going To Regret This Tomorrow\" and the Internet humor site\
  \ The FW[6] listed Drunk Baby in their \"Funniest Memes of the Week\" post. On June\
  \ 29th, a Facebook[9] page for \"Drunk Baby\" was created, which received over 50\
  \ likes within one week. The meme has continued to spread on Tumblr[8] under the\
  \ tag \"#drunk baby.\" As of July 6th, 2012, the Drunk Baby Quickmeme[3] page has\
  \ accumulated over 1,550 submissions. Notable Examples Search Interest External\
  \ References [1] Reddit \u2013 Introducing\u2026.Drunk Baby [2] Slacktory \u2013\
  \ Drunk Baby \u2013 Another Damn Baby Advice Meme [3] Quickmeme \u2013 Drunk Baby\
  \ [4] UpRoxx \u2013 Drunk Baby is Holding Court At The Bar [5] The Huffington Post\
  \ \u2013 Drunk Baby is Totally Going to Regret This Tomorrow [6] The FW \u2013 Funniest\
  \ Memes of the Week \u2013 Drunk Baby, Implying Dog and more [7] Reddit \u2013 She\
  \ tells the worst jokes [8] Tumblr \u2013 #drunk baby [9] Facebook \u2013 Drunk\
  \ Baby [10] 9gag \u2013 Drunk Baby Related Entries 14 total Success Kid / I Hate\
  \ Sandcastles Dancing Baby Babby Baby Godfather Skeptical Baby Crazy Mean Baby Aka-san\
  \ / Ged\u014D Beib\u012B (\u5916\u9053\u30D9\u30A4\u30D3\u30FC) Business Baby Talking\
  \ Twin Babies The McClure Twins Giant Baby Laughing Baby View All Related Entries\
  \ Recent Videos 1 total Drunk Baby Drunk Baby Uploaded by Abby of Many Fandoms +\
  \ Add a Video Recent Images 67 total Drunk Baby Uploaded by Y F Drunk Baby Uploaded\
  \ by tiskab Drunk Baby Uploaded by Johnny Lee Drunk Baby Uploaded by Emperor Palpitoad\
  \ Drunk Baby Uploaded by Mr. Rogue Ace Drunk Baby Uploaded by Lintboy Drunk Baby\
  \ Uploaded by flaviochubes Drunk Baby Uploaded by Don Drunk Baby Uploaded by Z.\
  \ Drunk Baby Uploaded by Don Drunk Baby Uploaded by Don Drunk Baby Uploaded by Chris\
  \ Kaye + Add an Image View All Images Sign up for our Newsletter Top Comments Delete\
  \ Sensitive BlogDog123 Jun 27, 2012 at 03:02PM EDT I dunno\u2026 +0.5 Confirm +22\
  \ Reply Delete Sensitive Quantum Meme Jul 06, 2012 at 04:18PM EDT I just\u2026..advice\
  \ animals are getting boring. +7 Reply + Add a Comment Comments (16) Display Comments\
  \ Add a Comment Top Entries This Month Meme Saika Kawakita Smile GIF Event Assassination\
  \ of UnitedHealthcare CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki\
  \ Sisters Culture Pornography Site Whisper View More Suggest a Change Edit History\
  \ Entry Editors (5) Z. Database Moderator & Rage Comicologist Don Administrator\
  \ & Meme Daddy \xAD\xAD\xADAlex Mercer Entry Moderator & YouTube Scatologist LNH\
  \ Deactivated Y F Digital Archaeologist & Treasurer & Media Maid \u25BC + Request\
  \ Editorship View All Editors Today's Top Image Galleries Assassination of UnitedHealthcare\
  \ CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing Digital Circus About\
  \ Our Story Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes\
  \ News Staff Contact Extras! Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/drunk-baby--2
template_id: drunk
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
