name: Drunk Baby
source: https://knowyourmeme.com/memes/drunk-baby--2
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- Walk in a straight line?
- Officer, I can barely stand
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Drunk Baby is an advice animal image macro series featuring
  a photograph of an infant sitting next to a pint of beer. The captions typically
  portray the baby as an intoxicated storyteller mimicking the behavior of older bar
  patrons. Origin The original baby photograph (shown below, left) was submitted to
  the /r/funny[7] subreddit by user MaryjaneBrewington in a post titled "She tells
  the worst jokes" on June 25th, 2012. The same day, the first Drunk Baby image macro
  was submitted by Redditor snicklefritz618 to the /r/AdviceAnimals[1] subreddit,
  which included the caption "This guy…. / I love this guy" (shown below, right).
  Within 10 days, the post received over 6,600 up votes and 100 comments. Spread On
  June 26th, 2012, the Internet culture blog Slacktory[2] published an article titled
  "Drunk Baby: Another Damn Advice Meme", which noted the series'' growing presence
  on Reddit despite Redditor''s tendency to get more easily jaded by child-based memes
  than Tumblr users. The same day, 9gag[10] user heartstorm90 submitted an image macro
  with the caption "Hey you. Yeah, You. / I totally sucked your wife''s tits", receiving
  over 3,000 Facebook shares within 10 days. On June 27th, the Internet humor blog
  UpRoxx[4] published a post titled "Meme Watch: Drunk Bank Is Holding Court At The
  Bar", including a slideshow of notable examples from the series. The same day, The
  Huffington Post[5] published an article titled "Drunk Baby Is Totally Going To Regret
  This Tomorrow" and the Internet humor site The FW[6] listed Drunk Baby in their
  "Funniest Memes of the Week" post. On June 29th, a Facebook[9] page for "Drunk Baby"
  was created, which received over 50 likes within one week. The meme has continued
  to spread on Tumblr[8] under the tag "#drunk baby." As of July 6th, 2012, the Drunk
  Baby Quickmeme[3] page has accumulated over 1,550 submissions. Notable Examples
  Search Interest External References [1] Reddit – Introducing….Drunk Baby [2] Slacktory
  – Drunk Baby – Another Damn Baby Advice Meme [3] Quickmeme – Drunk Baby [4] UpRoxx
  – Drunk Baby is Holding Court At The Bar [5] The Huffington Post – Drunk Baby is
  Totally Going to Regret This Tomorrow [6] The FW – Funniest Memes of the Week –
  Drunk Baby, Implying Dog and more [7] Reddit – She tells the worst jokes [8] Tumblr
  – #drunk baby [9] Facebook – Drunk Baby [10] 9gag – Drunk Baby'
aside_content: MemeStatusConfirmedType:Image MacroYear2012OriginRedditTagsbaby,drunk,advice
  animal,hangover,maryjanebrewington,snicklefritz618,slacktory,heartstorm90Additional
  ReferencesMeme Generator
added_at: '2012-06-27T11:47:47-04:00'
