name: Sudden Clarity Clarence
source: http://knowyourmeme.com/memes/sudden-clarity-clarence
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- oh my god
- those weren't listerine breath strips
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About Sudden Clarity Clarence is an advice animal image macro series
  featuring a photo of a young man at a party staring into the distance as if he is
  experiencing an epiphany. The captions often contain the phrase "Oh my God" or "Holy
  Shit" followed by a sudden realization that is trivial and insignificant. The series
  has been criticized for being redudant, due to its similarities to Conspiracy Keanu
  featuring an image of a frightened-looking Keanu Reeves. Origin The original stock
  photo (shown left) was submitted to the Australia Associated Press[9] covering the
  Schoolies festival on Queensland, Australia's Gold Coast. on November 21st, 2009.
  On November 23rd, 2011, Redditor NorthernSkeptic submitted a post titled "Introducing
  Sudden Clarity Clarence"[2] that included an image macro (shown right) with the
  caption "Oh my God / dubstep sucks." The thread subsequently reached the front page
  of the /r/AdviceAnimals subreddit. Spread On February 1st, 2012, the Internet humor
  site UpRoxx[5] posted an article about the advice animal series with a slideshow
  of notable derivatives. On February 16th, Slacktory editor Nick Douglas posted an
  instance on his Tumblr[4] blog with the caption "Holy shit / I've been given a lot
  and should be more thankful" which received over 1,700 notes in two weeks. The meme
  has since spread to FunnyJunk[6] and Tumblr[7] under the tag "#sudden clarity clarence."
  The Quickmeme page has received over 3,710 submissions and a Facebook page for "Sudden
  Clarity Clarence" has 17 likes as of March 6th, 2012. Notable Examples Identity
  On March 6th, 2012, Redditor duckareokay submitted a post to the /r/AdviceAnimals[3]
  subreddit titled "A true moment of clarity" featuring a photograph (shown left)
  of a man mimicking the Suddenly Clarity Clarence with the caption "I'm a meme."
  Redditor Badk1d replied to the thread claiming his classmate Will G from southern
  California was the real Clarity Clarence and presented a photo as evidence (shown
  right). Neither of the students were from Australia where the original stock photo
  was taken. Template Search Interest Search queries for "sudden clarity clarence"
  picked up in November of 2011, the same month the first Reddit post was submitted.
  External References [1] Quickmeme – Sudden Clarity Clarence [2] Reddit – Introducing
  Sudden Clarity Clarence [3] Reddit – A true moment of clarity [4] Tumblr – Too Much
  Nick [5] UpRoxx – Sudden Clarity Clarence Finally Gets It [6] FunnyJunk – sudden
  clarity clarence [7] Tumblr – sudden clarity clarence [8] Facebook – Sudden Clarity
  Clarence [9] AAPOne – Schoolies Gold Coast
aside_content: MemeStatusConfirmedYear2011OriginRedditTagsimage macro,revelationAdditional
  ReferencesMeme Generator
added_at: '2012-03-06T12:34:22-05:00'
