name: Minor Mistake Marvin
source: http://knowyourmeme.com/memes/minor-mistake-marvin
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- Puts ice cream back
- Into the refrigerator
overlay:
- center_x: 0.56
  center_y: 0.32
  angle: 0.0
  scale: 0.175
scraped_content: 'About Minor Advice Marvin is an advice animal image macro series
  featuring a photograph of a young boy staring blankly at a distance and various
  captions detailing everyday episodes of regrettable mistakes that can unfold as
  a result of one''s own oversight. Origin On October 8th, 2014, Redditor marky_mark301
  submitted a photograph of a young boy standing in front of a partially burned ramen
  noodle container inside a microwave to the /r/pics[4] subreddit in a post titled
  “He just wanted some noodles” (shown below, left). On October 11th, Redditor onebigbagostupid
  posted an image macro using the photo with a caption about accidentally putting
  ice cream in a refrigerator titled "Introducing: Mistake Marvin" to the /r/AdviceAnimals[1]
  subreddit, where it gained over 3,000 votes (84% upvoted) in the first 48 hours
  (shown below, right). The top-voted comment was submitted by Redditor McGotham,
  who suggested that the series be called "Minor Mistake Marvin." Spread On the same
  day, Redditor BrojobBrojob submitted an image macro about forgetting to turn on
  a slow cooker before leaving for work to /r/AdviceAnimals[2] (shown below, left).
  Also on October 11th, Redditor CakeSwag submitted a Minor Mistake Marvin image macro
  joking about accidentally calling a teacher "Mom" to /r/AdviceAnimals[5] (shown
  below, right). In the following 48 hours, the posts gathered more than 3,400 votes
  (93% upvoted) and 3,000 votes (79% upvoted) respectively. On October 12th, the /r/TodayIMarvinedUp[3]
  subreddit was launched for notable Minor Mistake Marvin examples. The same day,
  Redditor BrojobBrojob''s image macro was reposted to 9gag,[6] where it accumulated
  upwards of 2,900 points and 50 comments in 24 hours. Various Examples Search Interest
  External References [1] Reddit – Introducing Mistake Marvin [2] Reddit – Minor Mistake
  Marvin [3] Reddit – /r/TodayIMarvinedUp [4] Reddit – He just wanted some noodles
  [5] Reddit – mistake marvin screw up again [6] 9gag – Minor Mistake Marvin'
aside_content: MemeStatusConfirmedYear2014OriginRedditTagsimage macro,mistake,accident,bad
  luck,stare,marky_mark301
added_at: '2014-10-13T13:38:47-04:00'
