example:
- Puts ice cream back
- Into the refrigerator
keywords:
- null
name: Minor Mistake Marvin
overlay:
- angle: 0.0
  center_x: 0.56
  center_y: 0.32
  scale: 0.175
scraped_content: "Minor Mistake Marvin | Know Your Meme Greetings! You must login\
  \ or signup first! Already a memeber? Login Now! Don't have an account? Sign up\
  \ Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos Submit\
  \ \u2192 Images Trending Most Commented Most Favorited High Score Low Score Most\
  \ Viewed All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Minor Mistake Marvin Added 10 years ago / Updated 12 days ago Confirmed 286,590\
  \ Part of a series on Advice Animals. [View Related Entries] View All 30 Images\
  \ Navigation About \u2022 Origin \u2022 Spread \u2022 Various Examples \u2022 Search\
  \ Interest \u2022 External References \u2022 Recent Images About Minor Advice Marvin\
  \ is an advice animal image macro series featuring a photograph of a young boy staring\
  \ blankly at a distance and various captions detailing everyday episodes of regrettable\
  \ mistakes that can unfold as a result of one's own oversight. Origin On October\
  \ 8th, 2014, Redditor marky_mark301 submitted a photograph of a young boy standing\
  \ in front of a partially burned ramen noodle container inside a microwave to the\
  \ /r/pics[4] subreddit in a post titled \u201CHe just wanted some noodles\u201D\
  \ (shown below, left). On October 11th, Redditor onebigbagostupid posted an image\
  \ macro using the photo with a caption about accidentally putting ice cream in a\
  \ refrigerator titled \"Introducing: Mistake Marvin\" to the /r/AdviceAnimals[1]\
  \ subreddit, where it gained over 3,000 votes (84% upvoted) in the first 48 hours\
  \ (shown below, right). The top-voted comment was submitted by Redditor McGotham,\
  \ who suggested that the series be called \"Minor Mistake Marvin.\" Spread On the\
  \ same day, Redditor BrojobBrojob submitted an image macro about forgetting to turn\
  \ on a slow cooker before leaving for work to /r/AdviceAnimals[2] (shown below,\
  \ left). Also on October 11th, Redditor CakeSwag submitted a Minor Mistake Marvin\
  \ image macro joking about accidentally calling a teacher \"Mom\" to /r/AdviceAnimals[5]\
  \ (shown below, right). In the following 48 hours, the posts gathered more than\
  \ 3,400 votes (93% upvoted) and 3,000 votes (79% upvoted) respectively. On October\
  \ 12th, the /r/TodayIMarvinedUp[3] subreddit was launched for notable Minor Mistake\
  \ Marvin examples. The same day, Redditor BrojobBrojob's image macro was reposted\
  \ to 9gag,[6] where it accumulated upwards of 2,900 points and 50 comments in 24\
  \ hours. Various Examples Search Interest External References [1] Reddit \u2013\
  \ Introducing Mistake Marvin [2] Reddit \u2013 Minor Mistake Marvin [3] Reddit \u2013\
  \ /r/TodayIMarvinedUp [4] Reddit \u2013 He just wanted some noodles [5] Reddit \u2013\
  \ mistake marvin screw up again [6] 9gag \u2013 Minor Mistake Marvin image macro\
  \ mistake accident bad luck stare marky_mark301 Share Pin Related Entries 115 total\
  \ Ermahgerd Overly Attached Girlfriend Scumbag Steve Good Guy Greg View All Related\
  \ Entries Recent Images 30 total View All Images Recent Videos 0 total There are\
  \ no recent videos. Sign up for our Newsletter Load 66 Comments Comments 66 total\
  \ 34 Minor Mistake Marvin 286,590 0 30 66 Part of a series on Advice Animals. [View\
  \ Related Entries] Updated Dec 11, 2024 at 01:02PM EST by LiterallyAustin. Added\
  \ Oct 13, 2014 at 01:38PM EDT by Don. Like us on Facebook! Like 1.8M Share Save\
  \ Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the video gallery,\
  \ or 'r' to view a random entry. Meme Status Confirmed Year 2014 Origin Reddit Tags\
  \ image macro, mistake, accident, bad luck, stare, marky_mark301 About Minor Advice\
  \ Marvin is an advice animal image macro series featuring a photograph of a young\
  \ boy staring blankly at a distance and various captions detailing everyday episodes\
  \ of regrettable mistakes that can unfold as a result of one's own oversight. Origin\
  \ On October 8th, 2014, Redditor marky_mark301 submitted a photograph of a young\
  \ boy standing in front of a partially burned ramen noodle container inside a microwave\
  \ to the /r/pics[4] subreddit in a post titled \u201CHe just wanted some noodles\u201D\
  \ (shown below, left). On October 11th, Redditor onebigbagostupid posted an image\
  \ macro using the photo with a caption about accidentally putting ice cream in a\
  \ refrigerator titled \"Introducing: Mistake Marvin\" to the /r/AdviceAnimals[1]\
  \ subreddit, where it gained over 3,000 votes (84% upvoted) in the first 48 hours\
  \ (shown below, right). The top-voted comment was submitted by Redditor McGotham,\
  \ who suggested that the series be called \"Minor Mistake Marvin.\" Spread On the\
  \ same day, Redditor BrojobBrojob submitted an image macro about forgetting to turn\
  \ on a slow cooker before leaving for work to /r/AdviceAnimals[2] (shown below,\
  \ left). Also on October 11th, Redditor CakeSwag submitted a Minor Mistake Marvin\
  \ image macro joking about accidentally calling a teacher \"Mom\" to /r/AdviceAnimals[5]\
  \ (shown below, right). In the following 48 hours, the posts gathered more than\
  \ 3,400 votes (93% upvoted) and 3,000 votes (79% upvoted) respectively. On October\
  \ 12th, the /r/TodayIMarvinedUp[3] subreddit was launched for notable Minor Mistake\
  \ Marvin examples. The same day, Redditor BrojobBrojob's image macro was reposted\
  \ to 9gag,[6] where it accumulated upwards of 2,900 points and 50 comments in 24\
  \ hours. Various Examples Search Interest External References [1] Reddit \u2013\
  \ Introducing Mistake Marvin [2] Reddit \u2013 Minor Mistake Marvin [3] Reddit \u2013\
  \ /r/TodayIMarvinedUp [4] Reddit \u2013 He just wanted some noodles [5] Reddit \u2013\
  \ mistake marvin screw up again [6] 9gag \u2013 Minor Mistake Marvin Related Entries\
  \ 115 total Ermahgerd Overly Attached Girlfriend Scumbag Steve Good Guy Greg Ridiculously\
  \ Photogenic Guy Bad Luck Brian Philosoraptor Annoying Facebook Girl The Most Interesting\
  \ Man in the World Socially Awkward Penguin Bear Grylls / Better Drink My Own Piss\
  \ Successful Black Man View All Related Entries Recent Videos There are no videos\
  \ currently available. + Add a Video Recent Images 30 total Minor Mistake Marvin\
  \ Uploaded by TheMemoryOfTrees Minor Mistake Marvin Uploaded by lolwolf Minor Mistake\
  \ Marvin Uploaded by pharmokan Minor Mistake Marvin Uploaded by Major Bummer Minor\
  \ Mistake Marvin Uploaded by Major Bummer Minor Mistake Marvin Uploaded by Major\
  \ Bummer Minor Mistake Marvin Uploaded by Sam Minor Mistake Marvin Uploaded by YouAreNotSugoi\
  \ Minor Mistake Marvin Uploaded by The Human Element Minor Mistake Marvin Uploaded\
  \ by G36K Operator-chan Minor Mistake Marvin Uploaded by The Human Element Minor\
  \ Mistake Marvin Uploaded by EpicFatGuy_0100 + Add an Image View All Images Sign\
  \ up for our Newsletter Top Comments Delete Sensitive I Need Tea Oct 14, 2014 at\
  \ 03:14AM EDT +39 Reply Delete Sensitive DanBS Oct 13, 2014 at 09:50PM EDT +34 Reply\
  \ + Add a Comment Comments (66) Display Comments Add a Comment Top Entries This\
  \ Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare CEO\
  \ Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (5) Don Administrator\
  \ & Meme Daddy Brad Digital Archaeologist & Treasurer & Pundit & Gallery Housekeeper\
  \ Dreamworks Sr. Entry Moderator & iFunnyologist & Turtle Emoji Y F Digital Archaeologist\
  \ & Treasurer & Media Maid Keira Jr. Researcher \u25BC + Request Editorship View\
  \ All Editors Today's Top Image Galleries Assassination of UnitedHealthcare CEO\
  \ Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing Digital Circus About\
  \ Our Story Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes\
  \ News Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/minor-mistake-marvin
template_id: mmm
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
