example:
- disregard females
- acquire currency
keywords:
- Archaic Rap
name: Joseph Ducreux
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Joseph Ducreux / Archaic Rap | Know Your Meme 'lo! You must login\
  \ or signup first! Already a memeber? Login Now! Don't have an account? Sign up\
  \ Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos Submit\
  \ \u2192 Images Trending Most Commented Most Favorited High Score Low Score Most\
  \ Viewed All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Joseph Ducreux / Archaic Rap Added 15 years ago / Updated 12 days ago Confirmed\
  \ 2,388,738 Part of a series on Classical Art Memes. [View Related Entries] View\
  \ All 960 Images Featured Episode Navigation About \u2022 Origin \u2022 Variations\
  \ \u2022 The Artist \u2022 Steve Buscemi Ducreux \u2022 Recent Images \u2022 Recent\
  \ Videos About Joseph Ducreux (June 26, 1735 \u2013 July 24, 1802) was an eighteenth\
  \ century French artist known for his unorthodox style of portrait paintings. On\
  \ the internet, his eccentric self-portrait has inspired a series of exploitable\
  \ macros, featuring \"archaic reinterpretation\" of popular rap lyrics superimposed\
  \ over the artwork. Reminiscent of Bayeux Tapestry image macros, this highly verbose\
  \ joke provides a satisfying challenge of \"decoding\" the corrupted lyrics back\
  \ into to the original verses. Origin Portrait de l'artiste sous les traits d'un\
  \ moqueur (English: Self-portrait of the artist in the guise of a mockingbird),\
  \ which depicts Ducreux grinning smugly while pointing his finger towards the viewer,\
  \ was completed circa 1793. Over two centuries later in 2009, Ducreux' portrait\
  \ was turned into an image macro with a caption reading \"Disregard Females, Acquire\
  \ Currency,\" an archaic reinterpretation of lyrics from Notorious B.I.G's 1995\
  \ hit single Get Money. More recently, the line \"F*ck Bitches, Get Money\" was\
  \ also featured in Lil Wayne's 2005 track Money on My Mind. Since becoming popular\
  \ on 4chan, Meme Generator and other lulz-friendly communities, the image macro\
  \ has spawned an extensive pool of variations. Variations More in the Photo Gallery.\
  \ The Artist Self-portrait, circa 1783 Joseph Ducreux was an unorthodox portrait\
  \ artist, interested less in the classical ideas of portraiture used by later French\
  \ artists like David and Ingres. Ducreux had more of what sequential art philosopher\
  \ Scott McCloud might refer to as a \u201CFormalist\u201D approach, taking the medium\
  \ to a new ground by tearing down the fourth wall between subject and audience by\
  \ depicting himself pointing out of the canvas while grinning maniacally, reflecting\
  \ his belief that facial features could be use to depict personality. Steve Buscemi\
  \ Ducreux On April 8th, 2011, a Tumblr post featured an image with Steve Buscemi's\
  \ face photoshopped over Joseph Ducreux's, and it was posted to Reddit the same\
  \ day. The following day, a Quickmeme page was created with several image macros,\
  \ often accompanied by text associated with The Big Lebowski, or other films that\
  \ Buscemi has appeared in. josheph ducreux portrait art rap lyrics image macro haiku\
  \ hip hop pimpin old french painter rephrase joseph ducreux meme Share Pin Related\
  \ Entries 13 total Monk Temptation Angry Man Pointing at Hand Truth Coming Out of\
  \ Her Well ... The Golden Ratio View All Related Entries Recent Images 960 total\
  \ View All Images Recent Videos 6 total View All Videos Sign up for our Newsletter\
  \ Load 110 Comments Comments 110 total 372 Joseph Ducreux / Archaic Rap 2,388,738\
  \ 6 960 110 Part of a series on Classical Art Memes. [View Related Entries] Updated\
  \ Dec 11, 2024 at 04:01PM EST by LiterallyAustin. Added Nov 19, 2009 at 05:36PM\
  \ EST by Caozao. Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i'\
  \ to view the image gallery, 'v' to view the video gallery, or 'r' to view a random\
  \ entry. Featured Episode Meme Status Confirmed Type: Image Macro, Pop Culture Reference\
  \ Year 2009 Origin 4chan Tags josheph, ducreux, portrait, art, rap, lyrics, image\
  \ macro, haiku, hip hop, pimpin old french painter, rephrase, joseph ducreux meme\
  \ Additional References Wikipedia About Joseph Ducreux (June 26, 1735 \u2013 July\
  \ 24, 1802) was an eighteenth century French artist known for his unorthodox style\
  \ of portrait paintings. On the internet, his eccentric self-portrait has inspired\
  \ a series of exploitable macros, featuring \"archaic reinterpretation\" of popular\
  \ rap lyrics superimposed over the artwork. Reminiscent of Bayeux Tapestry image\
  \ macros, this highly verbose joke provides a satisfying challenge of \"decoding\"\
  \ the corrupted lyrics back into to the original verses. Origin Portrait de l'artiste\
  \ sous les traits d'un moqueur (English: Self-portrait of the artist in the guise\
  \ of a mockingbird), which depicts Ducreux grinning smugly while pointing his finger\
  \ towards the viewer, was completed circa 1793. Over two centuries later in 2009,\
  \ Ducreux' portrait was turned into an image macro with a caption reading \"Disregard\
  \ Females, Acquire Currency,\" an archaic reinterpretation of lyrics from Notorious\
  \ B.I.G's 1995 hit single Get Money. More recently, the line \"F*ck Bitches, Get\
  \ Money\" was also featured in Lil Wayne's 2005 track Money on My Mind. Since becoming\
  \ popular on 4chan, Meme Generator and other lulz-friendly communities, the image\
  \ macro has spawned an extensive pool of variations. Variations More in the Photo\
  \ Gallery. The Artist Self-portrait, circa 1783 Joseph Ducreux was an unorthodox\
  \ portrait artist, interested less in the classical ideas of portraiture used by\
  \ later French artists like David and Ingres. Ducreux had more of what sequential\
  \ art philosopher Scott McCloud might refer to as a \u201CFormalist\u201D approach,\
  \ taking the medium to a new ground by tearing down the fourth wall between subject\
  \ and audience by depicting himself pointing out of the canvas while grinning maniacally,\
  \ reflecting his belief that facial features could be use to depict personality.\
  \ Steve Buscemi Ducreux On April 8th, 2011, a Tumblr post featured an image with\
  \ Steve Buscemi's face photoshopped over Joseph Ducreux's, and it was posted to\
  \ Reddit the same day. The following day, a Quickmeme page was created with several\
  \ image macros, often accompanied by text associated with The Big Lebowski, or other\
  \ films that Buscemi has appeared in. Related Entries 13 total Monk Temptation Angry\
  \ Man Pointing at Hand Truth Coming Out of Her Well to Shame Mankind The Golden\
  \ Ratio Saturn Devouring His Son The Painting Is Complete Skeleton Whispering in\
  \ Man's Ear Mozart If He Was a Good Pianist / The Beatles If They Were a Good Band\
  \ Ivan the Terrible and His Son Ivan The Reluctant Bride TikTok Trend Couple Talking\
  \ The Crucifixion Hustler View All Related Entries Recent Videos 6 total Joseph\
  \ DuCreux: Archaic Rock Joseph Ducreux / Archaic Rap Uploaded by Captain Sadness\
  \ Know Your Meme: Joseph Ducreux Joseph Ducreux / Archaic Rap Uploaded by James\
  \ PiGPEN - Ducreux Joseph Ducreux / Archaic Rap Uploaded by Viataf Joseph DuCreux:\
  \ Archaic Memes Joseph Ducreux / Archaic Rap Uploaded by Captain Sadness Extraneous\
  \ Lyrics 2011 Joseph Ducreux / Archaic Rap Uploaded by Your Local Cow Extraneous\
  \ Lyrics Joseph Ducreux / Archaic Rap Uploaded by TuxRug + Add a Video Recent Images\
  \ 960 total Joseph Ducreux / Archaic Rap Uploaded by ComradeXXL Joseph Ducreux /\
  \ Archaic Rap Uploaded by Y F Joseph Ducreux / Archaic Rap Uploaded by Dry Ice Joseph\
  \ Ducreux / Archaic Rap Uploaded by Uresmane157 Joseph Ducreux / Archaic Rap Uploaded\
  \ by Uresmane157 Joseph Ducreux / Archaic Rap Uploaded by Orgeston Joseph Ducreux\
  \ / Archaic Rap Uploaded by koalameatpie Joseph Ducreux / Archaic Rap Uploaded by\
  \ STARwithaK Joseph Ducreux / Archaic Rap Uploaded by Beat it_Beter Joseph Ducreux\
  \ / Archaic Rap Uploaded by vanimal Joseph Ducreux / Archaic Rap Uploaded by Evilthing\
  \ Joseph Ducreux / Archaic Rap Uploaded by DalekAndDirector + Add an Image View\
  \ All Images Sign up for our Newsletter Top Comments Delete Sensitive pug on toast\
  \ Jul 17, 2011 at 06:33PM EDT I find the article rather flamboyant, and despite\
  \ all those who are not yet experienced in recognizing sophisticated work, I must\
  \ say this is a piece of exquisite execution of practicing the art of documenting\
  \ a meme of the internet. Translation: a bit fancy, but even with all the noobs\
  \ I say its a good meme entry. +17 Reply Delete Sensitive SaintSentry Oct 26, 2014\
  \ at 12:00AM EDT in reply to Ricochet What do you think the point of this meme is?\
  \ +9 Reply + Add a Comment Comments (110) Display Comments Add a Comment Top Entries\
  \ This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (9) Caozao\
  \ Brad Digital Archaeologist & Treasurer & Pundit & Gallery Housekeeper Chris Menning\
  \ Digital Archaeologist & Archivist & Pundit & Early Adopter (#8) Greg Leuch Former\
  \ Sysop Don Administrator & Meme Daddy amanda b. Meme Librarian SabrinaTibbetts\
  \ Memepuff Y F Digital Archaeologist & Treasurer & Media Maid Zach Memenator \u25BC\
  \ + Request Editorship View All Editors Today's Top Image Galleries Assassination\
  \ of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing\
  \ Digital Circus About Our Story Site Rules Policies and Guidelines Credits Contact\
  \ Meme DB Memes Episodes News Staff Contact Extras! Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/joseph-ducreux-archaic-rap
template_id: jd
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
