name: What is this, a Center for Ants?!
source: http://knowyourmeme.com/memes/what-is-this-a-center-for-ants
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- what is this
- a center for ants
overlay:
- center_x: 0.325
  center_y: 0.425
  angle: 0.0
  scale: 0.5
scraped_content: 'About "What is this, a center for ants?" is a memorable quote said
  by Derek Zoolander in the 2001 comedy film Zoolander. On online forums and message
  boards, the phrase and its snowclone variants have been used to describe or criticize
  an unusually small post object or image. Origin In the 2001 comedy film Zoolander,
  the main character, Derek Zoolander (played by Ben Stiller), says the line in anger
  after confusing a scale model of his charity project Derek Zoolander Center for
  Kids Who Can''t Read Good with the actual building itself. Derek Zoolander: What
  is this? [smashes the model for the reading center] A center for ants? Mugatu: What?
  Derek Zoolander: How can we be expected to teach children to learn how to read…
  if they can''t even fit inside the building? Mugatu: Derek, this is just a small…
  Derek Zoolander: I don''t wanna hear your excuses! The building has to be at least…
  three times bigger than this! Mugatu: He''s absolutely right you know. Spread In
  the years following the release of the film, the quote became parodied in the headlines
  of several news articles, including Vulture[1], New York Magazine[2] and Apartment
  Therapy[3] among others. By 2011, snowclone variations of the original quote, most
  notably "What is this? A picture for ants?" and "What is this? A video for ants?"
  began appearing on several internet humor sites and media-sharing communities like
  Memegenerator[5], Reddit[9] and Cheezburger.[6] In August 2011, the single topic
  Tumblr blog What is This? A ______ for Ants?[7] was launched to curate a variety
  of miniature objects and tiny scale models. In February 2013, a subreddit community
  based on the same idea was launched under the name "r/thingsforants."[4] Search
  Interest External References [1] Vulture – What is This? An Art Studio for Ants?
  [2] New York Mag – Empire State Building to Look Fierce This Weekend [3] Apartment
  Therapy – NanoTV: What is This? A TV for Ants? [4] Reddit – r/thingsforants [5]
  Memegenerator – Zoolander For Ants [6] Cheezburger – What Is This, a Shower For
  Ants?? [7] Tumblr – Made for Ants [8] IMDB – Quotes from Zoolander [9] Reddit –
  Search results for ''picture for ants'' [10] Dire Critic – Roundup of Unusual Size:
  What is this, a roundup for ants?'
aside_content: MemeStatusConfirmedYear2009OriginZoolanderTagszoolander,snowclone,ants,architecture,quote,movie
  quoteAdditional ReferencesFacebookRedditTwitterUrban Dictionary
added_at: '2013-09-04T06:17:05-04:00'
