name: Types of Headaches
source: https://knowyourmeme.com/memes/types-of-headaches
keywords:
- null
text:
- style: default
  color: black
  font: thick
  anchor_x: 0.5
  anchor_y: 0.64
  angle: 0.0
  scale_x: 0.5
  scale_y: 0.08
  align: center
  start: 0.0
  stop: 1.0
example:
- Breaking Production
overlay:
- center_x: 0.74
  center_y: 0.82
  angle: 0.0
  scale: 0.15
scraped_content: 'About Types of Headaches is a series of photoshopped images, which
  add a humorous fourth type of headache to a chart of real headaches. The user-added
  condition represents something that the meme''s author dislikes or avoids. Origin
  The earliest known iteration of the chart of headaches comes from a preview image
  for the article "How to Get Rid of a headache in 5 Minutes Without Pills" on the
  website Bright Side[1] on March 24th, 2017. Spread The original image with the blue
  background was used in reposts of the blogpost on websites like anonhq.com[2] and
  Beiruiting.com.[3] Several months later, on October 30th, Instagram [4] user @memes_of_siega,
  a meme account dedicated to the video game Rainbox Six: Siege posted a reconfigured
  version of the "Types of Headaches" chart. Broken into four quadrants, the picture
  has a new, white background, and the user added a fourth headache in which the entire
  head is colored red and captioned "Seeing doc use all his stims." Later that day,
  Instagram[5] user replaced the fourth head to read "Seeing somebody reinforce kidsbedroom."
  The post (shown below, left) received more than 5,000 likes in one week. Several
  days later, Redditor [6] Asianostrich822 posted a variant in the /r/TheWaterLew
  subreddit. In this version (shown below, center), the fourth head reads "Entering
  r/dankmemes." The next day, Redditor[7] unidentified_swed photoshopped that version
  to read "Entering r/sequelmemes" in the /r/PrequelMemes subreddit. The post (shown
  below, right) received more than 1,800 points (96% upvoted) and 20 comments in five
  days. On November 3rd, Twitter [8] user @chivaskangali posted a variation in which
  the fourth head reads "Living in Turkey." The post (shown below) recieved more than
  2,500 retweets and 11,000 likes in less than a week. Various Examples Search Interest
  Not available. External References [1] Bright Side – How to Get Rid of a headache
  in 5 Minutes Without Pills [2] Anon HQ – How To Get Rid Of A Headache In 5 Minutes
  Without Pills [3] Beiruting – How To Get Rid Of A Headache In 5 Minutes Without
  Pills [4] Instagram – memes_of_siege''s Post [5] Instagram – @nerfedbeard''s Post
  [6] Reddit – It hurts my head [7] Reddit – Who dis red arm [8] Twitter – @chivaskangali''s
  Tweet'
aside_content: MemeStatusConfirmedType:Image Macro,PhotoshopYear2017OriginInstagramTagsheadaches,health,rainbow
  six,migraine,hypertension,stressAdditional ReferencesMeme Generator
added_at: '2017-11-07T12:43:24-05:00'
