example:
- Breaking Production
keywords:
- null
name: Types of Headaches
overlay:
- angle: 0.0
  center_x: 0.74
  center_y: 0.82
  scale: 0.15
scraped_content: "Types of Headaches | Know Your Meme Hello! You must login or signup\
  \ first! Already a memeber? Login Now! Don't have an account? Sign up Now! Meme\
  \ Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Types of Headaches Added 7 years ago / Updated 8 days ago Confirmed 107,641\
  \ View All 35 Images Navigation About \u2022 Origin \u2022 Spread \u2022 Various\
  \ Examples \u2022 Search Interest \u2022 External References \u2022 Recent Images\
  \ \u2022 Recent Videos About Types of Headaches is a series of photoshopped images,\
  \ which add a humorous fourth type of headache to a chart of real headaches. The\
  \ user-added condition represents something that the meme's author dislikes or avoids.\
  \ Origin The earliest known iteration of the chart of headaches comes from a preview\
  \ image for the article \"How to Get Rid of a headache in 5 Minutes Without Pills\"\
  \ on the website Bright Side[1] on March 24th, 2017. Spread The original image with\
  \ the blue background was used in reposts of the blogpost on websites like anonhq.com[2]\
  \ and Beiruiting.com.[3] Several months later, on October 30th, Instagram [4] user\
  \ @memes_of_siega, a meme account dedicated to the video game Rainbox Six: Siege\
  \ posted a reconfigured version of the \"Types of Headaches\" chart. Broken into\
  \ four quadrants, the picture has a new, white background, and the user added a\
  \ fourth headache in which the entire head is colored red and captioned \"Seeing\
  \ doc use all his stims.\" Later that day, Instagram[5] user replaced the fourth\
  \ head to read \"Seeing somebody reinforce kidsbedroom.\" The post (shown below,\
  \ left) received more than 5,000 likes in one week. Several days later, Redditor\
  \ [6] Asianostrich822 posted a variant in the /r/TheWaterLew subreddit. In this\
  \ version (shown below, center), the fourth head reads \"Entering r/dankmemes.\"\
  \ The next day, Redditor[7] unidentified_swed photoshopped that version to read\
  \ \"Entering r/sequelmemes\" in the /r/PrequelMemes subreddit. The post (shown below,\
  \ right) received more than 1,800 points (96% upvoted) and 20 comments in five days.\
  \ On November 3rd, Twitter [8] user @chivaskangali posted a variation in which the\
  \ fourth head reads \"Living in Turkey.\" The post (shown below) recieved more than\
  \ 2,500 retweets and 11,000 likes in less than a week. Various Examples Search Interest\
  \ Not available. External References [1] Bright Side \u2013 How to Get Rid of a\
  \ headache in 5 Minutes Without Pills [2] Anon HQ \u2013 How To Get Rid Of A Headache\
  \ In 5 Minutes Without Pills [3] Beiruting \u2013 How To Get Rid Of A Headache In\
  \ 5 Minutes Without Pills [4] Instagram \u2013 memes_of_siege's Post [5] Instagram\
  \ \u2013 @nerfedbeard's Post [6] Reddit \u2013 It hurts my head [7] Reddit \u2013\
  \ Who dis red arm [8] Twitter \u2013 @chivaskangali's Tweet headaches health rainbow\
  \ six migraine hypertension stress Share Pin Recent Images 35 total View All Images\
  \ Recent Videos 3 total View All Videos Sign up for our Newsletter Load 7 Comments\
  \ Comments 7 total 7 Types of Headaches 107,641 3 35 7 Updated Dec 15, 2024 at 04:35PM\
  \ EST by LiterallyAustin. Added Nov 07, 2017 at 12:43PM EST by Matt. Like us on\
  \ Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the image gallery,\
  \ 'v' to view the video gallery, or 'r' to view a random entry. Meme Status Confirmed\
  \ Type: Image Macro, Photoshop Year 2017 Origin Instagram Tags headaches, health,\
  \ rainbow six, migraine, hypertension, stress Additional References Meme Generator\
  \ About Types of Headaches is a series of photoshopped images, which add a humorous\
  \ fourth type of headache to a chart of real headaches. The user-added condition\
  \ represents something that the meme's author dislikes or avoids. Origin The earliest\
  \ known iteration of the chart of headaches comes from a preview image for the article\
  \ \"How to Get Rid of a headache in 5 Minutes Without Pills\" on the website Bright\
  \ Side[1] on March 24th, 2017. Spread The original image with the blue background\
  \ was used in reposts of the blogpost on websites like anonhq.com[2] and Beiruiting.com.[3]\
  \ Several months later, on October 30th, Instagram [4] user @memes_of_siega, a meme\
  \ account dedicated to the video game Rainbox Six: Siege posted a reconfigured version\
  \ of the \"Types of Headaches\" chart. Broken into four quadrants, the picture has\
  \ a new, white background, and the user added a fourth headache in which the entire\
  \ head is colored red and captioned \"Seeing doc use all his stims.\" Later that\
  \ day, Instagram[5] user replaced the fourth head to read \"Seeing somebody reinforce\
  \ kidsbedroom.\" The post (shown below, left) received more than 5,000 likes in\
  \ one week. Several days later, Redditor [6] Asianostrich822 posted a variant in\
  \ the /r/TheWaterLew subreddit. In this version (shown below, center), the fourth\
  \ head reads \"Entering r/dankmemes.\" The next day, Redditor[7] unidentified_swed\
  \ photoshopped that version to read \"Entering r/sequelmemes\" in the /r/PrequelMemes\
  \ subreddit. The post (shown below, right) received more than 1,800 points (96%\
  \ upvoted) and 20 comments in five days. On November 3rd, Twitter [8] user @chivaskangali\
  \ posted a variation in which the fourth head reads \"Living in Turkey.\" The post\
  \ (shown below) recieved more than 2,500 retweets and 11,000 likes in less than\
  \ a week. Various Examples Search Interest Not available. External References [1]\
  \ Bright Side \u2013 How to Get Rid of a headache in 5 Minutes Without Pills [2]\
  \ Anon HQ \u2013 How To Get Rid Of A Headache In 5 Minutes Without Pills [3] Beiruting\
  \ \u2013 How To Get Rid Of A Headache In 5 Minutes Without Pills [4] Instagram \u2013\
  \ memes_of_siege's Post [5] Instagram \u2013 @nerfedbeard's Post [6] Reddit \u2013\
  \ It hurts my head [7] Reddit \u2013 Who dis red arm [8] Twitter \u2013 @chivaskangali's\
  \ Tweet Recent Videos 3 total HOW TO GET RID OF A HEADACHE ... Types of Headaches\
  \ Uploaded by Y F Among us meme: Types of heada... Types of Headaches Uploaded by\
  \ Y F Types of headaches \U0001F92F\U0001F9E0 Types of Headaches Uploaded by Y F\
  \ + Add a Video Recent Images 35 total Types of Headaches Uploaded by Rebecca Rhodes\
  \ Types of Headaches Uploaded by Owen Types of Headaches Uploaded by Owen Types\
  \ of Headaches Uploaded by andcallmeshirley Types of Headaches Uploaded by Y F Types\
  \ of Headaches Uploaded by nightqueen Types of Headaches Uploaded by Reddit Moments\
  \ Types of Headaches Uploaded by Bridget Types of Headaches Uploaded by STRABRee\
  \ Types of Headaches Uploaded by EinFanGottes Types of Headaches Uploaded by Mangy\
  \ Black Sheep Types of Headaches Uploaded by Amongus + Add an Image View All Images\
  \ Sign up for our Newsletter Top Comment Delete Sensitive Adam DeLand Nov 07, 2017\
  \ at 01:58PM EST \"The user-added condition represents something that the meme\u2019\
  s author dislikes or avoids.\" Well, this can only go one way. +7 Reply + Add a\
  \ Comment Comments (7) Display Comments Add a Comment Top Entries This Month Meme\
  \ Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare CEO Person Luigi\
  \ Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography Site Whisper\
  \ View More Suggest a Change Edit History Entry Editors (3) Matt Secretary of Memes\
  \ Y F Digital Archaeologist & Treasurer & Media Maid Aidan Walker \"Discourse\"\
  \ Analyst + Request Editorship View All Editors Today's Top Image Galleries Assassination\
  \ of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing\
  \ Digital Circus About Our Story Site Rules Policies and Guidelines Credits Contact\
  \ Meme DB Memes Episodes News Staff Contact Extras! Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/types-of-headaches
template_id: headaches
text:
- align: center
  anchor_x: 0.5
  anchor_y: 0.64
  angle: 0.0
  color: black
  font: thick
  scale_x: 0.5
  scale_y: 0.08
  start: 0.0
  stop: 1.0
  style: default
text_zones: 1
