name: Socially Awkward Penguin
source: http://knowyourmeme.com/memes/socially-awkward-penguin
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- start telling joke
- forget punchline
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Socially Awkward Penguin is an advice animal image macro series
  featuring a penguin lacking both social skills and self esteem. The text typically
  narrates uncomfortable life situations, highlighting an exceptionally clumsy or
  inelegant response. Origin The original image was taken by nature photographer George
  F. Mobley[1] and posted to illustrate a fact sheet on Adéli penguins for National
  Geographic''s Wild Animals site.[2] The Socially Awkward Penguin image macros began
  appearing on 4chan as early as May 2009, following the explosion of either series
  like Advice Dog and Courage Wolf. In an archived thread[16] from May 31st, 2009,
  a /b/ (random) user names Socially Awkward Penguin as an explanation of the term
  "advice animal." Spread On August 30th, 2009, the single topic blog Fuck Yeah Socially
  Awkward Penguin[6] was created. That year, Socially Awkward Penguin was mentioned
  on several other 4chan boards including /co/ [17] (comics and cartoons) and /a/
  [18] (anime and manga). The first Socially Awkward Penguin mention on Reddit took
  place in a comment thread[21] on September 25th, 2009. After the original poster,
  vanhookjosh, was seeking help for his anxiety, Redditor parttimehuman used the reference
  to reassure him that everyone has moments in life where they feel uncomfortable.
  In July 2010, Buzzfeed[8] featured a series of Socially Awkward Penguin images,
  followed by Smosh[9] that November. The next month, a series of notable images was
  shared on internet culture blog Street Couch[20] and a Socially Awkward Penguin
  Android app[7] was released. The first Quickmeme[10] instance was generated in late
  December 2010.[11] The next year, the series was also featured on internet media
  blogs Topcultured[22], Runt of the Web[23], and Geekosystem.[24] As of April 2012,
  over 32,000 people have liked the Facebook page[13] associated with the macro. It
  also has evolved into a popular hashtag on Tumblr[14] and Twitter[19], to collect
  posts about awkward life situations. Notable Examples Jiffy Cabs Advertisement Redditor
  Denying_Reality[25] posted a photo of a newspaper advertisement for Canadian taxi
  company Jiffy Cabs featuring Socially Awkward Penguin on November 3rd, 2011.[15]
  Memebase[26] users confirmed that the photo came from The Muse, a student newspaper
  from the Memorial University of Newfoundland in Canada. Reverse Memes Some Socially
  Awesome Penguin macros were created as direct reversals of Socially Awkward Penguin
  derivatives. For example, the image below shows an examples of Socially Awkward
  Penguin, a Socially Average Penguin and a Socially Awesome Penguin derivatives for
  the same social situation. Socially Awesome Penguin Socially Awesome Penguin is
  the most popular derivation of Socially awkward penguin. Commonly depicted as the
  antithesis of the original character, with the captions depicting the character
  as popular, charismatic and sexually attractive. On January 13th, 2010, the "Fuck
  Yeah Socially Awesome Penguin"[27] Tumblr blog was created, with the first image
  macro featuring the caption "Say a word wrong / create hilarious inside joke".[28]
  Although the image was watermarked by Meme Generator[29], the exact date of creation
  is currently unknown. Socially Awesome Penguin follows a reverse template style
  from Socially Awkward Penguin, having the penguin face the other way and the background
  red instead of blue, matching with the characters being the complete opposite of
  each other. On April 8th, 2010, a Socially Awesome Penguin image macro with the
  caption "Crush walks up to you in hall / have a quick chat. You''re meeting her
  after school" was submitted to a Socially Awkward penguin thread on 4chan''s /b/
  (random) board. On August 15th, a second "Socially Awesome Penguin" Tumblr[30] was
  created. On January 3rd, 2011, a post with several Socially Awesome Penguin derivatives
  was submitted to the /r/AdviceAnimals[31] subreddit by Redditor Mano21, receiving
  1,210 up votes prior to being archived. A Socially Awesome Penguin Quickmeme[32]
  page was created the same month. On March 1st, 2012, the Internet humor blog Smosh[33]
  published a round-up of notable Socially Awesome Penguin derivatives from Tumblr
  and Reddit. The meme has continued to spread on sites like FunnyJunk[35], Tumblr[34]
  and /r/AdviceAnimals[36] subreddit. As of April 16th, 2012, the Quickmeme page[38]
  has received over 3,500 submissions and a Facebook[37] page for "Socially Awesome
  Penguin" has accumulated over 990 likes. Hybrid Socially Awkward Penguin often appears
  in image macros with its antithesis Socially Awesome Penguin. On May 12th, 2011,
  a "Socially Awesome Awkward Penguin" Quickmeme[14] page was created, featuring macros
  with half of the image portraying a successful social interaction and the other
  half describing a socially awkward interaction. As of April 16th, 2012, the Quickmeme
  page has received over 8,200 submissions. Getty Copyright Claim On September 2nd,
  2015, the German tech blog GetDigital[39] published a post revealing that Getty
  Images had threatened the site with a copyright lawsuit for using Socially Awkward
  Penguin without permission, requiring a payment of €785.40 in licensing fees. The
  post went on to highlight to alternative images for the image macro series, featuring
  an illustration of the penguin rather than the original Getty Images cut out (shown
  below). On September 3rd, The Daily Dot[40] published an article about the copyright
  claim, which contained a statement from Getty Images confirming that the company
  had pursued legal action to protect copyright on the penguin image. “We believe
  in protecting copyright and the livelihoods of photographers and other artists who
  rely on licensing to earn a living and fund the creation of new works. Getty Images
  has an immense responsibility to the 200,000+ artists we work with to ensure that
  their work is properly licensed when used by commercial entities. Bear in mind that
  many artists themselves are small businesses, and are entitled to be paid for their
  work.” In the coming days, other news sites published articles about Getty Images
  legal action, including BoingBoing[41] and CBC News.[42] Search Interest Search
  queries for Socially Awkward Penguin began in May 2009, the same month the earliest
  chanarchive thread took place. External References [1] National Geographic – George
  F. Mobley biography [2] National Geographic – Adelie Penguin [3] Meme Generator
  – Socially Awesome Penguin [4] Meme Generator – Socially Average Penguin [5] Meme
  Generator – Socially Terrifying Penguin [6] Tumblr – F Yeah Socially Awkward Penguin
  [7] Android Market – Socially Awkward Penguin [8] Buzzfeed – The Best Of Socially
  Awkward Penguin [9] Smosh – 25 Most Socially Awkward Penguin Moments [10] Quickmeme
  – Socially Awkward Penguin [11] Quickmeme – Looking Good / You Have No Plans Tonight
  [12] Memestache – Socially Awkward Penguins [13] Facebook – Socially Awkward Penguin
  [14] Tumblr – Posts Tagged "Socially Awkward Penguin" [15] Reddit – Socially Awkward
  Penguin On My Bus [16] chanarchive – Mention of Socially Awkward Penguin [17] chanarchive
  – Socially Awkward Penguin [18] chanarchive – Socially Awkward Penguin mention [19]
  Twitter – Search for #sociallyawkwardpenguin [20] Street Couch – The Best of Socially
  Awkward Penguin [21] Reddit – Reddit. I''m a depressed 20 year old male. I think
  about suicide. Am I abnormal? Is there hope for me? [22] Topcultured – Socially
  Awkward Penguin in Real Life [23] Runt of the Web – Something To Relate To: Socially
  Awkward Penguin [24] Geekosystem – 101 Steps Toward Becoming Socially Awkward, As
  Told By a Penguin [25] Reddit – Denying_Reality [26] Memebase – Socially Awkward
  Advertisement [27] Tumblr – fuckyeahsociallyawesomepenguin [28] Tumblr – say a word
  wrong [29] Meme Generator – Socially Awesome Penguin [30] Tumblr – Socially Awesome
  Penguin [31] Reddit – socially awesome penguin [32] Quickmeme – Socially Awesome
  Penguin [33] Smosh – Best of Socially Awesome Penguin! [34] Tumblr – #socially awesome
  penguin [35] Funny Junk – socially awesome penguin [36] Reddit – Socially awesome
  penguin [37] Facebook – Socially Awesome Penguin [38] Quickmeme – Socially Awesome
  Awkward Penguin [39] Get Digital – Getty Images demands license payment for Awkward
  Penguin! [40] The Daily Dot – Getty claims copyright on Socially Awkward Penguin
  [41] BoingBoing – Getty charges blog $868 for Socially Awkward Penguin meme images
  [42] CBC News – Getty charges blog for use of widely used internet meme'
aside_content: MemeStatusConfirmedYear2009Origin4chanTagssocially,awkward,penguin,single
  character image macro,relationship,singledom,social stereotype,socially awesomeAdditional
  ReferencesEncyclopedia DramaticaMeme GeneratorUrban Dictionary
added_at: '2009-05-28T03:58:34-04:00'
