example:
- it's okay
- lets just reschedule drinking
keywords:
- null
name: Crying on Floor
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "HOLD THE DOOR | Hold The Door | Know Your Meme Word Up! You must\
  \ login or signup first! Already a memeber? Login Now! Don't have an account? Sign\
  \ up Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos\
  \ Submit \u2192 Images Trending Most Commented Most Favorited High Score Low Score\
  \ Most Viewed All Templates Upload an Image Articles News Explainers Collections\
  \ Interviews Meme Insider Magazine More Discord Newsletter Episodes Forums Meme\
  \ Store Login Abstract user icon Memes Categories Trending News Images Trending\
  \ Images Videos Trending Videos Editorials Meme Insider Magazine Newsletter Policies\
  \ and Guidelines Meme Store Old site Login Know Your Meme is the property of Literally\
  \ Media \xA92024 Literally Media. All Rights Reserved. This image Of Woman Confidently\
  \ Strolling Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years\
  \ Ago, This Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The\
  \ Anarchy Chess Memes Turns Two Years Old Today Phrase 'The Fridge Protects The\
  \ Snacks' A Growing Favorite Among Pickup Artist Influencers Jamie G, The Bosh British\
  \ Charva, Has Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also\
  \ Trending: Honey Extension Influencer Scam Renegade Raider Copypasta Assassination\
  \ of UnitedHealthcare CEO +3 HOLD THE DOOR Uploaded by Brad May 23, 2016 at 03:10PM\
  \ EDT Share Pin Download More hold the door reaction webcomic Origin Entry: Hold\
  \ The Door Notes: source File type: jpg Resolution: (600px x 600px) File size: 52\
  \ KB View All 33 Images More: It's gonna be hard to be polite from now on... Share\
  \ Pin Hold the Door Share Pin Hodor Hodoor Share Pin Next 1 +3 Hold The Door - HOLD\
  \ THE DOOR Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press the \u2190\
  \ and \u2192 keys to navigate the gallery, 'g' to view the gallery, or 'r' to view\
  \ a random image. \u25C4 Previous View Gallery Random Image Next \u25BA More: Hold\
  \ The Door Uploaded by Brad Hold The Door Uploaded by Don Hold The Door Uploaded\
  \ by Don Hold The Door Uploaded by SteelShroom + Add a Comment Comments (0) There\
  \ are no comments currently available. Display Comments Add a Comment + Add an Image\
  \ Image Details 2,894 views (1 from today) Uploaded May 23, 2016 at 03:10PM EDT\
  \ Origin Entry Hold The Door Notes source click to expand Tags hold the door, reaction,\
  \ webcomic Claim Authorship Edit History About the Uploader Brad Digital Archaeologist\
  \ & Treasurer & Pundit & Gallery Housekeeper Textile Embed !https://i.kym-cdn.com/photos/images/newsfeed/001/125/083/b5a.jpg!\
  \ Today's Top Image Galleries Assassination of UnitedHealthcare CEO Squirrel Girl\
  \ (Doreen Green) Team Fortress 2 The Amazing Digital Circus About Our Story Site\
  \ Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes News Staff\
  \ Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/photos/1125083-hold-the-door
template_id: cryingfloor
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
