name: Futurama Fry
source: http://knowyourmeme.com/memes/futurama-fry-not-sure-if
keywords:
- Philip J. Fry
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- not sure if trolling
- or just stupid
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Futurama Fry is an image macro series that uses a still of
  Fry squinting his eyes from the TV show Futurama, and is typically paired with overlaid
  text using a phrasal template. The top line reads "Not sure if X", with "or just
  Y" as the bottom line, and is used to represent an internal monologue. Origin In
  the Season 2, Episode 6 episode of Futurama titled "The Lesser of Two Evils", Fry
  can be seen making the face shortly after being found searching Leela''s underwear
  drawer at around 15 minutes into the episode.[1] This still image was first used
  in a I See What You Did There derivative: Spread One of the earliest derivatives
  to use the phrasal template appears to be the "not sure if trolling, or just stupid"
  image macro. Derivatives can be found on Memebase[2], Quickmeme[3], FunnyJunk[4],
  Memegenerator[5], and the Advice Animals subreddit.[6] Notable Derivatives Template
  Canonical Recognition The 7th season of the show aired on June 20th, 2012.[7] In
  the weeks leading up to the start of the new season, Comedy Central aired several
  commercials featuring Fry using the style and phrasal template of "Not Sure if X".
  Amongst original ones, these also used featured various popular versions of the
  phrase found online. On June 20th, 2012, Fry appeared at the end of the opening
  sequence of the new episode in the style of the phrasal template along with the
  caption "Not sure if new episode, or just rerun of episode I watched drunk". [This
  video has been removed] [This video has been removed] Search Interest Search query
  volume for "futurama fry" is far too large to be limited to the image macro series,
  but "fry meme" and "futurama meme" may provide a more accurate look at search query
  volume specifically related to the images. Searches of the phrase commonly associated
  with the Fry meme, "Not sure if trolling, or just stupid" can also be seen as increasing
  months after the introduction of the meme. External References [1] trilulilu – Futurama
  S02E11 The Lesser Of Two Evils [dd] / 15:23 [2] Memebase – Fry [3] Quickmeme – Futurama
  Fry [4] FunnyJunk – Futurama Fry [5] Memegenerator – Futurama Fry [6] Reddit – /r/AdviceAnimals:
  Futurama Fry [7] Wikipedia – List of Futurama Episodes #Season 7'
aside_content: MemeStatusConfirmedYear2011OriginFuturamaTagsfuturama,iswydt,image
  macro,blacklist,fry,not sure if,can't tell if
added_at: '2011-06-07T11:43:52-04:00'
