name: Salt Bae
source: http://knowyourmeme.com/memes/saltbae
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- ''
- pours salt on it
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Salt Bae is a nickname given to Turkish chef Nusret Gökçe,
  who was widely discussed on social media following the circulation of a viral video
  in which he flamboyantly sprinkles salt on a carved steak. Since his online debut
  in 2017, Salt Bae has been featured in numerous memes around the internet, typically
  using his photo as an exploitable or image macro. Origin On January 7th, 2017, Gökçe
  uploaded a video of himself carving a steak and sprinkling salt over his forearm
  on to the meat (shown below). Within 48 hours, the video gained over 2.4 million
  views and 8,700 comments.[1] That day, Twitter user @lolalissaa[3] reposted the
  video along the the message "so this is #saltbae." Ottoman steak A video posted
  by nusr_et (@nusr_et) on Jan 7, 2017 at 2:44am PST Spread That evening, @lolalissaa
  reposted another video in which Gökçe hangs a cooked slab of meat over a woman''s
  mouth, garnering upwards of 3,100 likes and 2,500 retweets in two days (shown below).
  #saltbae done took it to a whole other level pic.twitter.com/bRS8K56YZL— LoLa (@lolalissaa)
  January 8, 2017 Also on January 7th, 2017, Twitter user @elBeardedBandit[1] tweeted
  a You vs. The Guy image macro featuring a screenshot of Gökçe sprinking salt (shown
  below, left). Within 48 hours, the tweet garnered more than 48,000 likes and 33,000
  retweets. The following day, Twitter user @NerdyAjet[4] posted an illustration of
  Gökçe (shown below, right). On January 8th, Twitter user @Ratchetveli tweeted a
  parody video of himself making greit with the hashtag #GritsBae (shown below). That
  evening, a Twitter moments page titled "The world is obsessed with a Turkish meat
  monger" was created, highlighting tweets about Gökçe''s video.[2] Finna make some
  breakfast. #GritsBae pic.twitter.com/LH3HpICpdT— Willie Mo'' (@Ratchetveli) January
  8, 2017 On January 9th, Twitter user @j.kube posted a parody of Gökçe''s video in
  which he cuts the crust off several slices of bread, butters them and then sprinkles
  rainbow sprinkles over his forearm (shown below). In the coming days, several news
  sites published articles about Gökçe''s online fame, including The Verge,[5] The
  Telegraph,[6] NY Mag,[7] Wall Street Journal,[9] NBC News,[10] TIME[11] and Elite
  Daily.[8] Fairy bread #saltbae #fairybae nusr_et</a></p> <p style=" color:#c9c8cd;
  font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0;
  margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis;
  white-space:nowrap;">A video posted by Alek Jakubiak (j.kube) on Jan 8, 2017 at
  9:25pm PST Marco Rubio Feud On September 17th, 2018, Nurset Gökçe served Venezuelan
  President Nicolás Maduro at his restaraunt Nusr-Et in Istanbul, Turkey. Gökçe posted
  a video of him serving Maduro, as well as presenting him with a Salt Bae t-shirt
  on his Instagram page, which has since been deleted (mirror below). [12] That day,
  Florida Senator Marco Rubio retweeted Gökçe''s post and commented,[13] "I don’t
  know who this weirdo #Saltbae is, but the guy he is so proud to host is not the
  President of #Venezuela. He is actually the overweight dictator of a nation where
  30% of the people eat only once a day & infants are suffering from malnutrition."
  The tweet (shown below, left) received more than 2,100 retweets and 3,000 likes
  in 24 hours. He continued to tweet about the subject, seemingly encouraging constituents
  to call Gökçe''s restaurant to complain. He tweeted,[14] "This guy @nusr_ett who
  admires dictator @NicolasMaduro so much actually owns a steakhouse in, of all places,
  #Miami. It’s called NUSR-ET STEAKHOUSE MIAMI located at 999 Brickell Avenue, Miami,
  FL 33131 The phone number is 1 305 415 9990 in case anyone wanted to call." Some
  online took offense to Rubio''s posting the restaurant''s address and phone number.
  Washington Post tech reporter Tony Romm tweeted,[15] "So. Sen Rubio last night tweeted
  out the name, address and phone number of a business with which he''s having a political
  disagreement, and I wonder exactly how Twitter''s going to handle that given its
  policies on real-world harm/elected officials." London Location Prices On September
  26th, 2021, Twitter user @jjamz_ tweeted a picture of a bill at Nusr-Et''s London
  location, which came out to 1,812 pounds. The picture went viral on Twitter as people
  joked about the exorbitant prices at the restaurant. 44 great british pounds for
  4 redbulls… having a laugh. pic.twitter.com/xgzs8f2cEu — Jamz  (@jjamz_) September
  26, 2021 Salt Bae Qatar FIFA World Cup Final Controversy In December 2022, Nusret
  Gökçe came under scrutiny for appearing to harrass Argentinian players during their
  World Cup Victory celebration by taking the FIFA trophy out of their hands and biting
  their medals. On December 18th, Twitter[18] user @zekedabolina posted a video of
  Lionel Messi ignoring Salt Bae as he tries to badger him and get his attention.
  The video gathered over 18.2 million views and 46,000 likes in over a month (seen
  below). Even Messi knows salt bae is a hack pic.twitter.com/c457o1GnHt — Z Bo (@zekedabolina)
  December 18, 2022 On December 19th, Twitter[17] user @JCUStreaks10 posted a video
  scrolling through a series of now-deleted videos on Salt Bae''s Instagram, where
  he can be seen trying to throw salt on the trophy and pry it from player''s hands.
  THe tweet gathered over 35,000 likes in over a month (seen below). A collection
  of Salt Bae trying for clout with these players. So painful to watch. Like forcing
  himself between 2 players and trying to take the trophy away while players try to
  maintain professionalism, but their faces can be clearly read they are annoyed pic.twitter.com/BbChdBEK3M
  — Kevin Huyghe (@JCUStreaks10) December 19, 2022 On December 20th, Twitter[16] user
  @terryflewers reposted an Instagram post by Salt Bae, saying, "This is ridiculous,
  shame on FIFA for allowing him to touch, kiss, and hold the World Cup. Salt Bae
  drops salt on meat, what is he doing there?" and gathering over 180,000 likes in
  over a month (seen below, left). Also on December 20th, the official Twitter account
  for the US Open Cup soccer tournament posted a tweet that read, "Salt Bae is hereby
  banned from the 2023 @opencup Final." The tweet gathered over 150,000 likes in nearly
  a month (seen below, right). Search Interest External References [1] Twitter – @elBeardedBandit
  [2] Twitter – world is obsessed with a Turkish meat monger [3] Twitter – @lolalissaa
  [4] Twitter – @NerdyAjet [5] The Verge – Twitters sensual butcher #SaltBae [6] The
  Telegraph – Who is Salt Bae [7] NY Mag – Everything You Need to Know About #SaltBae
  [8] Elite Daily – #SaltBae Videos Are The Mesmerizing Food Porn [9] Wall Street
  Journal – Turkish Butcher ''Salt Bae'' Has the Internet Salivating [10] NBC News
  – Meet ‘Salt Bae,’ the Turkish Chef Whose Signature Move Made Him an Internet Sensation
  [11] TIME – The ''Salt Bae'' Chef Is Opening New Restaurants to Spread His Passion
  for Meats [12] Miami Herald – First he praised Castro. Now ‘Salt Bae’ chef lavishes
  Venezuela’s Maduro with steak dinner [13] Twitter – @marcorubio''s Tweet [14] Twitter
  – @marcorubio''s Tweet [15] Twitter – @TonyRomm''s Tweet [16] Twitter – terryflewers
  [17] Twitter – JCUStreaks10 [18] Twitter – zekedabolina'
aside_content: MemeStatusConfirmedType:Character,Exploitable,Image MacroYear2017OriginTwitterRegionUnited
  StatesTagstuskish,butcher,salt,twitter,viral video,salt guy,nusret gökçe,@lolalissaa,@elbeardedbandit,@nerdyajet,@ratchetveli,salt
  bae memeAdditional ReferencesFacebookMeme GeneratorRedditTwitterUrban DictionaryWikipedia
added_at: '2017-01-09T13:54:16-05:00'
