name: Daily Struggle
source: https://knowyourmeme.com/memes/daily-struggle
keywords:
- null
text:
- style: none
  color: black
  font: thin
  anchor_x: 0.085
  anchor_y: 0.085
  angle: 12.5
  scale_x: 0.32
  scale_y: 0.095
  align: center
  start: 0.0
  stop: 0.5
- style: none
  color: black
  font: thin
  anchor_x: 0.455
  anchor_y: 0.055
  angle: 10.5
  scale_x: 0.23
  scale_y: 0.09
  align: center
  start: 0.5
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.04
  anchor_y: 0.82
  angle: 0.0
  scale_x: 0.92
  scale_y: 0.15
  align: center
  start: 0.0
  stop: 1.0
example:
- The dress is black and blue.
- The dress is gold and white.
overlay:
- center_x: 0.525
  center_y: 0.55
  angle: 0.0
  scale: 0.4
scraped_content: 'About "Daily Struggle" is an exploitable comic featuring a character
  attempting to push one of two red buttons labeled with contradicting statements.
  Origin On October 25th, 2014, animator Jake Clark posted the original comic to his
  Tumblr blog,[1] depicting a visibly shaken character wiping sweat from his brow
  while struggling to choose between two buttons labeled "BE A DICK" and "DON''T BE
  A DICK" (shown below). Clark has since noted the comic was inspired by the Sweating
  Towel Guy illustration and the character Hank Nova from Timesplitters 2 [4]. In
  the next two years, the comic gained over 9,700 notes. Spread On February 1, 2015
  the comic was submitted to Imgur by user Robban39 under the title "Daily Struggle"
  and has been viewed over 1,275,000 times [3]. In the coming hours, Redditor AcerRubrum
  posted the same Imgur submission to r/funny, where it received 3738 points (91%
  upvoted) and 117 comments prior to being archived [2]. Meanwhile, a GIF of the comic
  was submitted to Imgur, in which the "Be a Dick" button is pressed repeatedly (shown
  below). On February 20th, Redditor reposted the original comic to /r/funny,[5] where
  it gathered upwards of 2,000 votes (80% upvoted) and 40 comments prior to being
  archived. On March 29th, a variation of the comic titled "Tumblr''s dilemma" in
  which the two buttons were labeled "People can be born as the wrong gender" and
  "Gender is a social construct" was submitted to /r/funny,[7] where it garnered upwards
  of 4,400 votes (85% upvoted) and 775 comments before it was archived (shown below,
  left). On June 23rd, Redditor slapkunts posted a version of the comic representing
  the man as a "proud liberal" and editing the button labels to read "cops are evil
  and racist" and "you don''t need a gun because you have police" to /r/Libertarian[6]
  (shown below, right). Prior to being archived, the post gathered more than 3,500
  votes (80% upvoted) and 370 comments. Pushing Both Buttons On November 11th, 2020,
  visual artist Petirep posted, "I made a new iteration of the classic ''sweaty button
  pressing'' meme" to Twitter,[8] along with an original drawing of the Daily Struggle
  image where the character is pressing both buttons at once in the first panel, and
  giving a thumbs-up while smiling in the second (shown below, left). On the same
  day they posted the image to /r/MemeEconomy.[9] On the same day ShaboomBanana posted
  the first new version of the meme to Twitter[10] (shown below, right). On November
  12th, Twitter user memessss28 posted a new version of the meme to Twitter[11] garnering
  over 150 retweets and 450 likes in a month (shown below, left). By early December,
  versions of the meme began finding success on Reddit. On December 11th, Reddit user
  hardikupreti posted a version of the meme to /r/dankmemes,[12] garnering over 24,000
  upvotes and 20 Reddit awards (shown below, right). Various Examples Search Interest
  Not available. External References [1] Tumblr – The Original Comic [2] Reddit –
  Daily Struggle / Posted on 2-1-2015 [3] Imgur – Daily Struggle [4] Reddit – What
  is the Origin of the Meme of a Panicked Dude Trying to Decide Between Pressing Two
  Buttons? / Posted on 8-6-15 [5] Reddit – When I comment on something [6] Reddit
  – The Struggle [7] Reddit – Tumblrs Dilemma [8] Twitter – I made a new iteration
  of the classic ''sweaty button pressing'' meme [9] Reddit – Template: Both options
  at once [10] Twitter – shaboom_banana [11] Twitter – Me in a nutshell [12] Reddit
  – wHy dO i FiX eVeRytHinG i ToUcH'
aside_content: MemeStatusConfirmedType:ExploitableYear2014OriginTumblrTagsjake clark,exploitable,daily
  struggle,choose,button,contradicting statements,hank nova,robban39,acerrubrum,slapkunts,petirep,shaboombanana,memessss28,hardikupreti,button
  memeAdditional ReferencesMeme GeneratorRedditTumblr
added_at: '2016-01-14T06:43:17-05:00'
