example:
- The dress is black and blue.
- The dress is gold and white.
keywords:
- null
name: Daily Struggle
overlay:
- angle: 0.0
  center_x: 0.525
  center_y: 0.55
  scale: 0.4
scraped_content: "Daily Struggle / Two Buttons | Know Your Meme Word Up! You must\
  \ login or signup first! Already a memeber? Login Now! Don't have an account? Sign\
  \ up Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos\
  \ Submit \u2192 Images Trending Most Commented Most Favorited High Score Low Score\
  \ Most Viewed All Templates Upload an Image Articles News Explainers Collections\
  \ Interviews Meme Insider Magazine More Discord Newsletter Episodes Forums Meme\
  \ Store Login Abstract user icon Memes Categories Trending News Images Trending\
  \ Images Videos Trending Videos Editorials Meme Insider Magazine Newsletter Policies\
  \ and Guidelines Meme Store Old site Login Know Your Meme is the property of Literally\
  \ Media \xA92024 Literally Media. All Rights Reserved. This image Of Woman Confidently\
  \ Strolling Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years\
  \ Ago, This Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The\
  \ Anarchy Chess Memes Turns Two Years Old Today Phrase 'The Fridge Protects The\
  \ Snacks' A Growing Favorite Among Pickup Artist Influencers Jamie G, The Bosh British\
  \ Charva, Has Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also\
  \ Trending: Honey Extension Influencer Scam Renegade Raider Copypasta Assassination\
  \ of UnitedHealthcare CEO Daily Struggle / Two Buttons Added 8 years ago / Updated\
  \ about a year ago Confirmed 421,229 View All 187 Images Navigation About \u2022\
  \ Origin \u2022 Spread \u2022 Various Examples \u2022 Search Interest \u2022 External\
  \ References \u2022 Recent Images About \"Daily Struggle\" is an exploitable comic\
  \ featuring a character attempting to push one of two red buttons labeled with contradicting\
  \ statements. Origin On October 25th, 2014, animator Jake Clark posted the original\
  \ comic to his Tumblr blog,[1] depicting a visibly shaken character wiping sweat\
  \ from his brow while struggling to choose between two buttons labeled \"BE A DICK\"\
  \ and \"DON'T BE A DICK\" (shown below). Clark has since noted the comic was inspired\
  \ by the Sweating Towel Guy illustration and the character Hank Nova from Timesplitters\
  \ 2 [4]. In the next two years, the comic gained over 9,700 notes. Spread On February\
  \ 1, 2015 the comic was submitted to Imgur by user Robban39 under the title \"Daily\
  \ Struggle\" and has been viewed over 1,275,000 times [3]. In the coming hours,\
  \ Redditor AcerRubrum posted the same Imgur submission to r/funny, where it received\
  \ 3738 points (91% upvoted) and 117 comments prior to being archived [2]. Meanwhile,\
  \ a GIF of the comic was submitted to Imgur, in which the \"Be a Dick\" button is\
  \ pressed repeatedly (shown below). On February 20th, Redditor reposted the original\
  \ comic to /r/funny,[5] where it gathered upwards of 2,000 votes (80% upvoted) and\
  \ 40 comments prior to being archived. On March 29th, a variation of the comic titled\
  \ \"Tumblr's dilemma\" in which the two buttons were labeled \"People can be born\
  \ as the wrong gender\" and \"Gender is a social construct\" was submitted to /r/funny,[7]\
  \ where it garnered upwards of 4,400 votes (85% upvoted) and 775 comments before\
  \ it was archived (shown below, left). On June 23rd, Redditor slapkunts posted a\
  \ version of the comic representing the man as a \"proud liberal\" and editing the\
  \ button labels to read \"cops are evil and racist\" and \"you don't need a gun\
  \ because you have police\" to /r/Libertarian[6] (shown below, right). Prior to\
  \ being archived, the post gathered more than 3,500 votes (80% upvoted) and 370\
  \ comments. Pushing Both Buttons On November 11th, 2020, visual artist Petirep posted,\
  \ \"I made a new iteration of the classic 'sweaty button pressing' meme\" to Twitter,[8]\
  \ along with an original drawing of the Daily Struggle image where the character\
  \ is pressing both buttons at once in the first panel, and giving a thumbs-up while\
  \ smiling in the second (shown below, left). On the same day they posted the image\
  \ to /r/MemeEconomy.[9] On the same day ShaboomBanana posted the first new version\
  \ of the meme to Twitter[10] (shown below, right). On November 12th, Twitter user\
  \ memessss28 posted a new version of the meme to Twitter[11] garnering over 150\
  \ retweets and 450 likes in a month (shown below, left). By early December, versions\
  \ of the meme began finding success on Reddit. On December 11th, Reddit user hardikupreti\
  \ posted a version of the meme to /r/dankmemes,[12] garnering over 24,000 upvotes\
  \ and 20 Reddit awards (shown below, right). Various Examples Search Interest Not\
  \ available. External References [1] Tumblr \u2013 The Original Comic [2] Reddit\
  \ \u2013 Daily Struggle / Posted on 2-1-2015 [3] Imgur \u2013 Daily Struggle [4]\
  \ Reddit \u2013 What is the Origin of the Meme of a Panicked Dude Trying to Decide\
  \ Between Pressing Two Buttons? / Posted on 8-6-15 [5] Reddit \u2013 When I comment\
  \ on something [6] Reddit \u2013 The Struggle [7] Reddit \u2013 Tumblrs Dilemma\
  \ [8] Twitter \u2013 I made a new iteration of the classic 'sweaty button pressing'\
  \ meme [9] Reddit \u2013 Template: Both options at once [10] Twitter \u2013 shaboom_banana\
  \ [11] Twitter \u2013 Me in a nutshell [12] Reddit \u2013 wHy dO i FiX eVeRytHinG\
  \ i ToUcH jake clark exploitable daily struggle choose button contradicting statements\
  \ hank nova robban39 acerrubrum slapkunts petirep shaboombanana memessss28 hardikupreti\
  \ button meme Share Pin Recent Images 187 total View All Images Recent Videos 0\
  \ total There are no recent videos. Sign up for our Newsletter Load 31 Comments\
  \ Comments 31 total 69 Daily Struggle / Two Buttons 421,229 0 187 31 Updated Feb\
  \ 01, 2023 at 10:47AM EST by Zach. Added Jan 14, 2016 at 06:43AM EST by MedleyManiac.\
  \ Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the\
  \ image gallery, 'v' to view the video gallery, or 'r' to view a random entry. Meme\
  \ Status Confirmed Type: Exploitable Year 2014 Origin Tumblr Tags jake clark, exploitable,\
  \ daily struggle, choose, button, contradicting statements, hank nova, robban39,\
  \ acerrubrum, slapkunts, petirep, shaboombanana, memessss28, hardikupreti, button\
  \ meme Additional References Meme Generator Reddit Tumblr About \"Daily Struggle\"\
  \ is an exploitable comic featuring a character attempting to push one of two red\
  \ buttons labeled with contradicting statements. Origin On October 25th, 2014, animator\
  \ Jake Clark posted the original comic to his Tumblr blog,[1] depicting a visibly\
  \ shaken character wiping sweat from his brow while struggling to choose between\
  \ two buttons labeled \"BE A DICK\" and \"DON'T BE A DICK\" (shown below). Clark\
  \ has since noted the comic was inspired by the Sweating Towel Guy illustration\
  \ and the character Hank Nova from Timesplitters 2 [4]. In the next two years, the\
  \ comic gained over 9,700 notes. Spread On February 1, 2015 the comic was submitted\
  \ to Imgur by user Robban39 under the title \"Daily Struggle\" and has been viewed\
  \ over 1,275,000 times [3]. In the coming hours, Redditor AcerRubrum posted the\
  \ same Imgur submission to r/funny, where it received 3738 points (91% upvoted)\
  \ and 117 comments prior to being archived [2]. Meanwhile, a GIF of the comic was\
  \ submitted to Imgur, in which the \"Be a Dick\" button is pressed repeatedly (shown\
  \ below). On February 20th, Redditor reposted the original comic to /r/funny,[5]\
  \ where it gathered upwards of 2,000 votes (80% upvoted) and 40 comments prior to\
  \ being archived. On March 29th, a variation of the comic titled \"Tumblr's dilemma\"\
  \ in which the two buttons were labeled \"People can be born as the wrong gender\"\
  \ and \"Gender is a social construct\" was submitted to /r/funny,[7] where it garnered\
  \ upwards of 4,400 votes (85% upvoted) and 775 comments before it was archived (shown\
  \ below, left). On June 23rd, Redditor slapkunts posted a version of the comic representing\
  \ the man as a \"proud liberal\" and editing the button labels to read \"cops are\
  \ evil and racist\" and \"you don't need a gun because you have police\" to /r/Libertarian[6]\
  \ (shown below, right). Prior to being archived, the post gathered more than 3,500\
  \ votes (80% upvoted) and 370 comments. Pushing Both Buttons On November 11th, 2020,\
  \ visual artist Petirep posted, \"I made a new iteration of the classic 'sweaty\
  \ button pressing' meme\" to Twitter,[8] along with an original drawing of the Daily\
  \ Struggle image where the character is pressing both buttons at once in the first\
  \ panel, and giving a thumbs-up while smiling in the second (shown below, left).\
  \ On the same day they posted the image to /r/MemeEconomy.[9] On the same day ShaboomBanana\
  \ posted the first new version of the meme to Twitter[10] (shown below, right).\
  \ On November 12th, Twitter user memessss28 posted a new version of the meme to\
  \ Twitter[11] garnering over 150 retweets and 450 likes in a month (shown below,\
  \ left). By early December, versions of the meme began finding success on Reddit.\
  \ On December 11th, Reddit user hardikupreti posted a version of the meme to /r/dankmemes,[12]\
  \ garnering over 24,000 upvotes and 20 Reddit awards (shown below, right). Various\
  \ Examples Search Interest Not available. External References [1] Tumblr \u2013\
  \ The Original Comic [2] Reddit \u2013 Daily Struggle / Posted on 2-1-2015 [3] Imgur\
  \ \u2013 Daily Struggle [4] Reddit \u2013 What is the Origin of the Meme of a Panicked\
  \ Dude Trying to Decide Between Pressing Two Buttons? / Posted on 8-6-15 [5] Reddit\
  \ \u2013 When I comment on something [6] Reddit \u2013 The Struggle [7] Reddit \u2013\
  \ Tumblrs Dilemma [8] Twitter \u2013 I made a new iteration of the classic 'sweaty\
  \ button pressing' meme [9] Reddit \u2013 Template: Both options at once [10] Twitter\
  \ \u2013 shaboom_banana [11] Twitter \u2013 Me in a nutshell [12] Reddit \u2013\
  \ wHy dO i FiX eVeRytHinG i ToUcH Recent Videos There are no videos currently available.\
  \ + Add a Video Recent Images 187 total Daily Struggle / Two Buttons Uploaded by\
  \ Jaimie Hamilton Daily Struggle / Two Buttons Uploaded by Jaimie Hamilton Daily\
  \ Struggle / Two Buttons Uploaded by funnyfaceking Daily Struggle / Two Buttons\
  \ Uploaded by Triplem Daily Struggle / Two Buttons Uploaded by Jaimie Hamilton Daily\
  \ Struggle / Two Buttons Uploaded by Triplem Daily Struggle / Two Buttons Uploaded\
  \ by Reddit Moments Daily Struggle / Two Buttons Uploaded by Reddit Moments Daily\
  \ Struggle / Two Buttons Uploaded by Reddit Moments Daily Struggle / Two Buttons\
  \ Uploaded by False_Skeptic Daily Struggle / Two Buttons Uploaded by Reddit Moments\
  \ Daily Struggle / Two Buttons Uploaded by Reddit Moments + Add an Image View All\
  \ Images Sign up for our Newsletter Top Comments Delete Sensitive Mart\xEDn Nicol\xE1\
  s Ormaz\xE1bal Palma Jan 15, 2016 at 02:09PM EST +75 Reply Delete Sensitive CrazyCal999\
  \ Dec 11, 2020 at 01:31PM EST in reply to SotiCoto A year later, your wish is granted.\
  \ +48 Reply + Add a Comment Comments (31) Display Comments Add a Comment Top Entries\
  \ This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (9) MedleyManiac\
  \ Deactivated LNH Deactivated Jill Database Moderator & Karma Philanthropist & Meme\
  \ Taxonomist & Fleet Admiral & Amish Don Administrator & Meme Daddy Z. Database\
  \ Moderator & Rage Comicologist Y F Digital Archaeologist & Treasurer & Media Maid\
  \ andcallmeshirley Digital Archaeologist & Treasurer & Collection Butler Phillip\
  \ Hamilton Bonk Connoisseur Zach Memenator \u25BC + Request Editorship View All\
  \ Editors Today's Top Image Galleries Assassination of UnitedHealthcare CEO Squirrel\
  \ Girl (Doreen Green) Team Fortress 2 The Amazing Digital Circus About Our Story\
  \ Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes News\
  \ Staff Contact Extras! Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/daily-struggle
template_id: ds
text:
- align: center
  anchor_x: 0.085
  anchor_y: 0.085
  angle: 12.5
  color: black
  font: thin
  scale_x: 0.32
  scale_y: 0.095
  start: 0.0
  stop: 0.5
  style: none
- align: center
  anchor_x: 0.455
  anchor_y: 0.055
  angle: 10.5
  color: black
  font: thin
  scale_x: 0.23
  scale_y: 0.09
  start: 0.5
  stop: 1.0
  style: none
- align: center
  anchor_x: 0.04
  anchor_y: 0.82
  angle: 0.0
  color: white
  font: thick
  scale_x: 0.92
  scale_y: 0.15
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 3
