name: But That's None of My Business
source: http://knowyourmeme.com/memes/but-thats-none-of-my-business
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- ''
- but that's none of my business
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About "But That''s None of My Business" is a sarcastic expression
  used as a postscript to an insult or disrespectful remark said towards a specific
  individual or group. The phrase was popularized through an image macro series featuring
  Kermit the Frog from The Muppets and punchlines poking fun at a wide range of faux-pas
  and questionable behaviors in everyday social situations, with the meme format also
  becoming known simply as Kermit Drinking Tea. Origin As early as January 2014, Instagram
  users began posting captioned images of Kermit the Frog with the hashtag “#kermitmemes”
  (shown below, left).[4] On June 17th, the earliest known Kermit image macro including
  the phrase “that’s none of my business” was highlighted by the @kermitbelike[5]
  Instagram feed in a post mocking delusional women described as being "ratchet" (shown
  below, right). Spread On June 20th, the @thatsnoneofmybusinesstho Instagram[3] feed
  was created, which highlights pictures of Kermit the Frog with "none of my business"
  captions. In the first four days, the feed gained over 130,000 followers. On the
  same day, Twitter users began tweeting jokes using the hashtags #NoneOfMyBusiness
  and #Kermit, reaching over 19,000 and 11,000 mentions in the first four days respectively
  according to the Twitter analytics site Topsy.[3] On June 22nd, 2014, the single
  topic blog "Kemit the Snitch" was launched on Tumblr,[1] which highlights notable
  examples from the image macro series. The first post featured a photograph of Kermit
  the Frog drinking a glass of iced tea with a caption mocking men who wear fake Jordan
  sneakers (shown below). On the following day, YouTuber Bugatti Beez uploaded a video
  of Kermit the Frog reading notable "But Thats None Of My Business" examples (shown
  below). In the first 24 hours the video gained over 100,000 views and 480 comments.
  Various Examples As of June 2014, there are over 2,100 images uploaded under the
  tag "kermitmemes" on Instagram.[2] #TeaLizard On June 20th, 2016, the meme saw a
  resurgence when Cleveland Cavaliers'' LeBron James who led the team to earning its
  first NBA championship title in the franchise history, returned home wearing an
  “Ultimate Warrior” t-shirt and a cap embroidered with an image of Kermit the Frog
  sipping tea. That same day, James posted an Instagram of his meme-themed hat alongside
  the Larry O’Brien Trophy with the caption taunting his critics and skeptics: On
  June 21st, LeBron James'' fashion statement was picked up by several news sites
  and sports blogs, including USA Today, Washington Post, GQ, New York Daily News
  and BarStoolSports, many of which underscored the celebrity athlete''s sense of
  humor. Meanwhile, ABC''s Good Morning America (GMA) chimed in on the emerging Crying
  Lebron photoshop meme with a tweet asking the followers whether it should be counted
  among the ranks of other well-known memes in the sports world, in which Kermit the
  Frog''s tea-sipping image was mislabeled with the hashtag #tealizard. In the following
  hours, GMA''s tweet was met with a slew of snide remarks from those who noticed
  the misnomer #tealizard, as well as media coverage from The Verge, AOL, A.V. Club
  and Mashable. Search Interest External References [1] Tumblr – Kermit the Snitch
  [2] Iconosquare via Wayback Machine – kermitmemes [3] Topsy – #NoneOfMyBusiness
  #Kermit [3] Instagram – thatsnoneofmybusinesstho [4] Iconosquare via Wayback Machine
  – dat_satisfying_pancake [5] Iconosquare – @kermitbelike [6] ImgFlip – But That''s
  None of My Business [7] GIPHY – search for But That''s None of My Business [8] Tumblr
  – Tagged Results for ''But That''s None of My Business'' [9] Twitter – Search Results
  for ''But That''s None of My Business'' [10] Imgur – Search Results for ''But That''s
  None of My Business'' [11] Pinterest – Search Results for ''But That''s None of
  My Business'' [12] Uproxx (via Wayback Machine) – These Kermit The Frog “But That’s
  None Of My Business” Memes Are The New Internet Hotness [13] Instagram – @KingJames''
  Instagram [14] Bleacher Report – LeBron James Rocks Hat with ''None of My Business''
  Kermit Meme Before Game 7 [15] GQ – LeBron Hilariously Trolled the Warriors With
  His Outfit [16] USA Today – LeBron James issues a perfect post-championship response
  to his critics [17] New York Daily News – LeBron James wears Kermit sipping tea
  hat, has message for his haters [18] BarStoolSports – Whatever Stylist Put Lebron’s
  Post-Championship Outfit Together Deserves A Huge Raise [19] Washington Post – LeBron
  James and Dwyane Wade fire back at critics on Instagram [20] The Verge – 2014''s
  best meme returns, only to be brutalized by TV morning show [21] Mediaite – EXCLUSIVE:
  An ABC Insider Just Gave Us the Scoop on This Morning’s #TeaLizard Phenomenon [22]
  Mashable – Some maniac at Good Morning America called Kermit the Frog ''Tea Lizard''
  [23] BarStoolSports – Good Morning America Calls The Kermit The Frog Meme The “Tea
  Lizard” [24] AOL – #TeaLizard is now a thing -- or so says ''Good Morning America''
  [24] AV Club – With #TeaLizard, ABC subjects Kermit The Frog to greater indignity
  than cancellation'
aside_content: MemeStatusConfirmedYear2014OriginInstagramRegionUnited StatesTagsmuppets,tea,kermit
  the frog,tealizard,that's none of my business,but that's none of my business tho,#tealizard,lebron
  james,tea lizard,bugatti beez,larry o’brien,larry o’brien trophy,faux-pas,thatsnoneofmybusinesstho,topsy,fake
  jordan sneak,kermit drinking teaAdditional ReferencesMeme GeneratorPinterestTwitterUrban
  Dictionary
added_at: '2014-06-23T13:59:24-04:00'
