example:
- ''
- but that's none of my business
keywords:
- null
name: But That's None of My Business
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "But That's None of My Business | Know Your Meme Howdy! You must\
  \ login or signup first! Already a memeber? Login Now! Don't have an account? Sign\
  \ up Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos\
  \ Submit \u2192 Images Trending Most Commented Most Favorited High Score Low Score\
  \ Most Viewed All Templates Upload an Image Articles News Explainers Collections\
  \ Interviews Meme Insider Magazine More Discord Newsletter Episodes Forums Meme\
  \ Store Login Abstract user icon Memes Categories Trending News Images Trending\
  \ Images Videos Trending Videos Editorials Meme Insider Magazine Newsletter Policies\
  \ and Guidelines Meme Store Old site Login Know Your Meme is the property of Literally\
  \ Media \xA92024 Literally Media. All Rights Reserved. This image Of Woman Confidently\
  \ Strolling Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years\
  \ Ago, This Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The\
  \ Anarchy Chess Memes Turns Two Years Old Today Phrase 'The Fridge Protects The\
  \ Snacks' A Growing Favorite Among Pickup Artist Influencers Jamie G, The Bosh British\
  \ Charva, Has Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also\
  \ Trending: Honey Extension Influencer Scam Renegade Raider Copypasta Assassination\
  \ of UnitedHealthcare CEO But That's None of My Business Added 10 years ago / Updated\
  \ 8 days ago Confirmed 1,769,407 Part of a series on Kermit the Frog. [View Related\
  \ Entries] [View Related Sub-entries] View All 90 Images Navigation About \u2022\
  \ Origin \u2022 Spread \u2022 Various Examples \u2022 Search Interest \u2022 External\
  \ References \u2022 Recent Images \u2022 Recent Videos About \"But That's None of\
  \ My Business\" is a sarcastic expression used as a postscript to an insult or disrespectful\
  \ remark said towards a specific individual or group. The phrase was popularized\
  \ through an image macro series featuring Kermit the Frog from The Muppets and punchlines\
  \ poking fun at a wide range of faux-pas and questionable behaviors in everyday\
  \ social situations, with the meme format also becoming known simply as Kermit Drinking\
  \ Tea. Origin As early as January 2014, Instagram users began posting captioned\
  \ images of Kermit the Frog with the hashtag \u201C#kermitmemes\u201D (shown below,\
  \ left).[4] On June 17th, the earliest known Kermit image macro including the phrase\
  \ \u201Cthat\u2019s none of my business\u201D was highlighted by the @kermitbelike[5]\
  \ Instagram feed in a post mocking delusional women described as being \"ratchet\"\
  \ (shown below, right). Spread On June 20th, the @thatsnoneofmybusinesstho Instagram[3]\
  \ feed was created, which highlights pictures of Kermit the Frog with \"none of\
  \ my business\" captions. In the first four days, the feed gained over 130,000 followers.\
  \ On the same day, Twitter users began tweeting jokes using the hashtags #NoneOfMyBusiness\
  \ and #Kermit, reaching over 19,000 and 11,000 mentions in the first four days respectively\
  \ according to the Twitter analytics site Topsy.[3] On June 22nd, 2014, the single\
  \ topic blog \"Kemit the Snitch\" was launched on Tumblr,[1] which highlights notable\
  \ examples from the image macro series. The first post featured a photograph of\
  \ Kermit the Frog drinking a glass of iced tea with a caption mocking men who wear\
  \ fake Jordan sneakers (shown below). On the following day, YouTuber Bugatti Beez\
  \ uploaded a video of Kermit the Frog reading notable \"But Thats None Of My Business\"\
  \ examples (shown below). In the first 24 hours the video gained over 100,000 views\
  \ and 480 comments. Various Examples As of June 2014, there are over 2,100 images\
  \ uploaded under the tag \"kermitmemes\" on Instagram.[2] #TeaLizard On June 20th,\
  \ 2016, the meme saw a resurgence when Cleveland Cavaliers' LeBron James who led\
  \ the team to earning its first NBA championship title in the franchise history,\
  \ returned home wearing an \u201CUltimate Warrior\u201D t-shirt and a cap embroidered\
  \ with an image of Kermit the Frog sipping tea. That same day, James posted an Instagram\
  \ of his meme-themed hat alongside the Larry O\u2019Brien Trophy with the caption\
  \ taunting his critics and skeptics: On June 21st, LeBron James' fashion statement\
  \ was picked up by several news sites and sports blogs, including USA Today, Washington\
  \ Post, GQ, New York Daily News and BarStoolSports, many of which underscored the\
  \ celebrity athlete's sense of humor. Meanwhile, ABC's Good Morning America (GMA)\
  \ chimed in on the emerging Crying Lebron photoshop meme with a tweet asking the\
  \ followers whether it should be counted among the ranks of other well-known memes\
  \ in the sports world, in which Kermit the Frog's tea-sipping image was mislabeled\
  \ with the hashtag #tealizard. In the following hours, GMA's tweet was met with\
  \ a slew of snide remarks from those who noticed the misnomer #tealizard, as well\
  \ as media coverage from The Verge, AOL, A.V. Club and Mashable. Search Interest\
  \ External References [1] Tumblr \u2013 Kermit the Snitch [2] Iconosquare via Wayback\
  \ Machine \u2013 kermitmemes [3] Topsy \u2013 #NoneOfMyBusiness #Kermit [3] Instagram\
  \ \u2013 thatsnoneofmybusinesstho [4] Iconosquare via Wayback Machine \u2013 dat_satisfying_pancake\
  \ [5] Iconosquare \u2013 @kermitbelike [6] ImgFlip \u2013 But That's None of My\
  \ Business [7] GIPHY \u2013 search for But That's None of My Business [8] Tumblr\
  \ \u2013 Tagged Results for 'But That's None of My Business' [9] Twitter \u2013\
  \ Search Results for 'But That's None of My Business' [10] Imgur \u2013 Search Results\
  \ for 'But That's None of My Business' [11] Pinterest \u2013 Search Results for\
  \ 'But That's None of My Business' [12] Uproxx (via Wayback Machine) \u2013 These\
  \ Kermit The Frog \u201CBut That\u2019s None Of My Business\u201D Memes Are The\
  \ New Internet Hotness [13] Instagram \u2013 @KingJames' Instagram [14] Bleacher\
  \ Report \u2013 LeBron James Rocks Hat with 'None of My Business' Kermit Meme Before\
  \ Game 7 [15] GQ \u2013 LeBron Hilariously Trolled the Warriors With His Outfit\
  \ [16] USA Today \u2013 LeBron James issues a perfect post-championship response\
  \ to his critics [17] New York Daily News \u2013 LeBron James wears Kermit sipping\
  \ tea hat, has message for his haters [18] BarStoolSports \u2013 Whatever Stylist\
  \ Put Lebron\u2019s Post-Championship Outfit Together Deserves A Huge Raise [19]\
  \ Washington Post \u2013 LeBron James and Dwyane Wade fire back at critics on Instagram\
  \ [20] The Verge \u2013 2014's best meme returns, only to be brutalized by TV morning\
  \ show [21] Mediaite \u2013 EXCLUSIVE: An ABC Insider Just Gave Us the Scoop on\
  \ This Morning\u2019s #TeaLizard Phenomenon [22] Mashable \u2013 Some maniac at\
  \ Good Morning America called Kermit the Frog 'Tea Lizard' [23] BarStoolSports \u2013\
  \ Good Morning America Calls The Kermit The Frog Meme The \u201CTea Lizard\u201D\
  \ [24] AOL \u2013 #TeaLizard is now a thing -- or so says 'Good Morning America'\
  \ [24] AV Club \u2013 With #TeaLizard, ABC subjects Kermit The Frog to greater indignity\
  \ than cancellation muppets tea kermit the frog tealizard that's none of my business\
  \ but that's none of my business tho #tealizard lebron james tea lizard bugatti\
  \ beez larry o\u2019brien larry o\u2019brien trophy faux-pas thatsnoneofmybusinesstho\
  \ topsy fake jordan sneak kermit drinking tea Share Pin Related Entries 10 total\
  \ Evil Kermit Ima Keep It Real With U Chief Kermit Did 9/11 Cookie Monster Alphabet\
  \ View All Related Entries Sub-entries 2 total Take a Fucking Sip, Babes #TeaLizard\
  \ Recent Images 90 total View All Images Recent Videos 1 total View All Videos Sign\
  \ up for our Newsletter Load 76 Comments Comments 76 total 58 But That's None of\
  \ My Business 1,769,415 1 90 76 Part of a series on Kermit the Frog. [View Related\
  \ Entries] [View Related Sub-entries] Updated Dec 15, 2024 at 04:10PM EST by LiterallyAustin.\
  \ Added Jun 23, 2014 at 01:59PM EDT by QuesoFrogger. Like us on Facebook! Like 1.8M\
  \ Share Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the\
  \ video gallery, or 'r' to view a random entry. Meme Status Confirmed Year 2014\
  \ Origin Instagram Region United States Tags muppets, tea, kermit the frog, tealizard,\
  \ that's none of my business, but that's none of my business tho, #tealizard, lebron\
  \ james, tea lizard, bugatti beez, larry o\u2019brien, larry o\u2019brien trophy,\
  \ faux-pas, thatsnoneofmybusinesstho, topsy, fake jordan sneak, kermit drinking\
  \ tea Additional References Meme Generator Pinterest Twitter Urban Dictionary About\
  \ \"But That's None of My Business\" is a sarcastic expression used as a postscript\
  \ to an insult or disrespectful remark said towards a specific individual or group.\
  \ The phrase was popularized through an image macro series featuring Kermit the\
  \ Frog from The Muppets and punchlines poking fun at a wide range of faux-pas and\
  \ questionable behaviors in everyday social situations, with the meme format also\
  \ becoming known simply as Kermit Drinking Tea. Origin As early as January 2014,\
  \ Instagram users began posting captioned images of Kermit the Frog with the hashtag\
  \ \u201C#kermitmemes\u201D (shown below, left).[4] On June 17th, the earliest known\
  \ Kermit image macro including the phrase \u201Cthat\u2019s none of my business\u201D\
  \ was highlighted by the @kermitbelike[5] Instagram feed in a post mocking delusional\
  \ women described as being \"ratchet\" (shown below, right). Spread On June 20th,\
  \ the @thatsnoneofmybusinesstho Instagram[3] feed was created, which highlights\
  \ pictures of Kermit the Frog with \"none of my business\" captions. In the first\
  \ four days, the feed gained over 130,000 followers. On the same day, Twitter users\
  \ began tweeting jokes using the hashtags #NoneOfMyBusiness and #Kermit, reaching\
  \ over 19,000 and 11,000 mentions in the first four days respectively according\
  \ to the Twitter analytics site Topsy.[3] On June 22nd, 2014, the single topic blog\
  \ \"Kemit the Snitch\" was launched on Tumblr,[1] which highlights notable examples\
  \ from the image macro series. The first post featured a photograph of Kermit the\
  \ Frog drinking a glass of iced tea with a caption mocking men who wear fake Jordan\
  \ sneakers (shown below). On the following day, YouTuber Bugatti Beez uploaded a\
  \ video of Kermit the Frog reading notable \"But Thats None Of My Business\" examples\
  \ (shown below). In the first 24 hours the video gained over 100,000 views and 480\
  \ comments. Various Examples As of June 2014, there are over 2,100 images uploaded\
  \ under the tag \"kermitmemes\" on Instagram.[2] #TeaLizard On June 20th, 2016,\
  \ the meme saw a resurgence when Cleveland Cavaliers' LeBron James who led the team\
  \ to earning its first NBA championship title in the franchise history, returned\
  \ home wearing an \u201CUltimate Warrior\u201D t-shirt and a cap embroidered with\
  \ an image of Kermit the Frog sipping tea. That same day, James posted an Instagram\
  \ of his meme-themed hat alongside the Larry O\u2019Brien Trophy with the caption\
  \ taunting his critics and skeptics: On June 21st, LeBron James' fashion statement\
  \ was picked up by several news sites and sports blogs, including USA Today, Washington\
  \ Post, GQ, New York Daily News and BarStoolSports, many of which underscored the\
  \ celebrity athlete's sense of humor. Meanwhile, ABC's Good Morning America (GMA)\
  \ chimed in on the emerging Crying Lebron photoshop meme with a tweet asking the\
  \ followers whether it should be counted among the ranks of other well-known memes\
  \ in the sports world, in which Kermit the Frog's tea-sipping image was mislabeled\
  \ with the hashtag #tealizard. In the following hours, GMA's tweet was met with\
  \ a slew of snide remarks from those who noticed the misnomer #tealizard, as well\
  \ as media coverage from The Verge, AOL, A.V. Club and Mashable. Search Interest\
  \ External References [1] Tumblr \u2013 Kermit the Snitch [2] Iconosquare via Wayback\
  \ Machine \u2013 kermitmemes [3] Topsy \u2013 #NoneOfMyBusiness #Kermit [3] Instagram\
  \ \u2013 thatsnoneofmybusinesstho [4] Iconosquare via Wayback Machine \u2013 dat_satisfying_pancake\
  \ [5] Iconosquare \u2013 @kermitbelike [6] ImgFlip \u2013 But That's None of My\
  \ Business [7] GIPHY \u2013 search for But That's None of My Business [8] Tumblr\
  \ \u2013 Tagged Results for 'But That's None of My Business' [9] Twitter \u2013\
  \ Search Results for 'But That's None of My Business' [10] Imgur \u2013 Search Results\
  \ for 'But That's None of My Business' [11] Pinterest \u2013 Search Results for\
  \ 'But That's None of My Business' [12] Uproxx (via Wayback Machine) \u2013 These\
  \ Kermit The Frog \u201CBut That\u2019s None Of My Business\u201D Memes Are The\
  \ New Internet Hotness [13] Instagram \u2013 @KingJames' Instagram [14] Bleacher\
  \ Report \u2013 LeBron James Rocks Hat with 'None of My Business' Kermit Meme Before\
  \ Game 7 [15] GQ \u2013 LeBron Hilariously Trolled the Warriors With His Outfit\
  \ [16] USA Today \u2013 LeBron James issues a perfect post-championship response\
  \ to his critics [17] New York Daily News \u2013 LeBron James wears Kermit sipping\
  \ tea hat, has message for his haters [18] BarStoolSports \u2013 Whatever Stylist\
  \ Put Lebron\u2019s Post-Championship Outfit Together Deserves A Huge Raise [19]\
  \ Washington Post \u2013 LeBron James and Dwyane Wade fire back at critics on Instagram\
  \ [20] The Verge \u2013 2014's best meme returns, only to be brutalized by TV morning\
  \ show [21] Mediaite \u2013 EXCLUSIVE: An ABC Insider Just Gave Us the Scoop on\
  \ This Morning\u2019s #TeaLizard Phenomenon [22] Mashable \u2013 Some maniac at\
  \ Good Morning America called Kermit the Frog 'Tea Lizard' [23] BarStoolSports \u2013\
  \ Good Morning America Calls The Kermit The Frog Meme The \u201CTea Lizard\u201D\
  \ [24] AOL \u2013 #TeaLizard is now a thing -- or so says 'Good Morning America'\
  \ [24] AV Club \u2013 With #TeaLizard, ABC subjects Kermit The Frog to greater indignity\
  \ than cancellation Related Entries 10 total Evil Kermit Ima Keep It Real With U\
  \ Chief Kermit Did 9/11 Cookie Monster Alphabet I Am Going to Kermit Suicide Kermit\
  \ Mystery Box #ImWithKer Kermit Falling Down a Stairwell Kermit Arrives Kermit Goatse\
  \ Sub-entries 2 total Take a Fucking Sip, Babes #TeaLizard Recent Videos 1 total\
  \ Top 25 Kermit \"None Of My Bus... But That's None of My Business Uploaded by Don\
  \ + Add a Video Recent Images 90 total But That's None of My Business Uploaded by\
  \ Reddit Moments But That's None of My Business Uploaded by Reddit Moments But That's\
  \ None of My Business Uploaded by Reddit Moments But That's None of My Business\
  \ Uploaded by digby shizu But That's None of My Business Uploaded by Bridget But\
  \ That's None of My Business Uploaded by Don But That's None of My Business Uploaded\
  \ by Break But That's None of My Business Uploaded by Y F But That's None of My\
  \ Business Uploaded by Guy with Opinions But That's None of My Business Uploaded\
  \ by Immortal Scientist \u262D But That's None of My Business Uploaded by Derek\
  \ Rumpler But That's None of My Business Uploaded by Juicydeath1025 + Add an Image\
  \ View All Images Sign up for our Newsletter Top Comments Delete Sensitive Old Man\
  \ GigaChad Jun 25, 2014 at 01:40AM EDT +124 Reply Delete Sensitive Jill Moderator\
  \ Jun 24, 2014 at 08:17PM EDT Hey, not certain if it's needed in the article, but\
  \ the Muppet wiki says the scene where Kermit drinks milk is from Episode 101 of\
  \ The Muppet Show Also before you ask, yes he is actually drinking it +51 Reply\
  \ + Add a Comment Comments (76) Display Comments Add a Comment Top Entries This\
  \ Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare CEO\
  \ Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (12) QuesoFrogger\
  \ MScratch Database Moderator & Historical Meme Historian & \u300CStand User\u300D\
  \ Don Administrator & Meme Daddy Brad Digital Archaeologist & Treasurer & Pundit\
  \ & Gallery Housekeeper RandomMan Database Moderator & God Tier Swag & Protip Advisor\
  \ & Karma Tycoon & Meme Boi Jill Database Moderator & Karma Philanthropist & Meme\
  \ Taxonomist & Fleet Admiral & Amish Ari Spool The Mayor SabrinaTibbetts Memepuff\
  \ Y F Digital Archaeologist & Treasurer & Media Maid andcallmeshirley Digital Archaeologist\
  \ & Treasurer & Collection Butler shevyrolet Digital Archaeologist & Treasurer &\
  \ Media Bus Boy Zach Memenator \u25BC + Request Editorship View All Editors Today's\
  \ Top Image Galleries Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen\
  \ Green) Team Fortress 2 The Amazing Digital Circus About Our Story Site Rules Policies\
  \ and Guidelines Credits Contact Meme DB Memes Episodes News Staff Contact Extras!\
  \ Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/but-thats-none-of-my-business
template_id: kermit
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
