name: Inhaling Seagull
source: https://knowyourmeme.com/memes/inhaling-seagull
keywords:
- null
text:
- style: none
  color: white
  font: comic
  anchor_x: 0.0
  anchor_y: 0.24
  angle: 0.0
  scale_x: 0.25
  scale_y: 0.1
  align: center
  start: 0.0
  stop: 1.0
- style: none
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.75
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.25
  align: center
  start: 0.0
  stop: 1.0
example:
- some
- BODY ONCE TOLD ME THE THE WORLD WAS GONNA ROLL ME!!
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About Inhaling Seagull is an exploitable two-panel image macro series
  featuring a photograph of a seagull leaning backwards followed by a picture of the
  seagull squawking forwards. The first image is captioned with the word "inhales"
  while the second image is typically captioned with verbose copypastas and song lyrics.
  Origin On July 12th, 2012, YouTuber Dimaniztlt uploaded footage of a seagull appearing
  to throw its head backwards and laugh (shown below). Within five years, the video
  gained over 181,000 views. On September 3rd, 2017, Twitter [6] user @dioyasu tweeted
  a two-panel image of the seagull leaning back and a deep-fried image of the seagull
  with the caption "yamero." The tweet received more than 38,000 retweets and 66,000
  likes as of November 2018 (shown below, left). That day, the same user tweeted[7]
  the two-panel seagull image with the caption "inhales / BOI," referencing the *breath
  in* / Boi meme. The tweet received more than 1,000 retweets and 2,400 likes in a
  little over a year (shown below, right). Spread On September 5th, 2017, Redditor
  MasterMooper posted a vertical version of the second tweet, and within ten days,
  the post gathered upwards of 3,700 points (98% upvoted) on /r/me_irl.[1] On September
  10th, 2017, Redditor FallingTower uploaded the image captioned with a Game of Thrones
  reference to /r/freefolk[5] (shown below, left). The following day, Redditor Fedock
  submitted a variation of the image referencing the "omae ma wou shindeiru" meme
  to /r/dankmemes[4] (shown below, right). On September 13th, the Woken Memes Facebook[3]
  page posted the image captioned with lyrics from the song "Somebody Told Me" by
  The Killers (shown below, left). The same day, Imgur[2] user mentaljake uploaded
  a similar variation featuring lyrics from the song "All Star" by Smash Mouth (shown
  below, right). Related Memes Shut Seagull Shut Seagull refers to a screenshot from
  the Inhaling Seagull video where the seagull's mouth is shut and its neck is extended.
  A photoshopped-in "OK Hand Emoji" (👌) is holding the seagull's mouth shut, and the
  word "shut" is written at the bottom of the image (shown below).[8] The image slowly
  spread across Reddit as an image macro through several high-interaction posts and
  re-posts, as well as on Twitter as a reaction image (examples shown below). Various
  Examples Search Interest Not available. External References [1] Reddit – me irl
  [2] Imgur – Best use of this meme Ive seen so far [3] Facebook – Woken Memes [4]
  Reddit – Nani? [5] Reddit – /r/freefolk [6] Twitter – @dioyasu's Tweet [7] Twitter
  – @dioyasu's Tweet [8] Reddit – shut
aside_content: MemeStatusConfirmedYear2017OriginRedditTagsimage macro,seagull,bird,exploitable
added_at: '2017-09-14T11:32:44-04:00'
