example:
- some
- BODY ONCE TOLD ME THE THE WORLD WAS GONNA ROLL ME!!
keywords:
- null
name: Inhaling Seagull
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Inhaling Seagull | Know Your Meme Yo! You must login or signup first!\
  \ Already a memeber? Login Now! Don't have an account? Sign up Now! Meme Encyclopedia\
  \ All Cultures Events People Sites Subcultures Videos Submit \u2192 Images Trending\
  \ Most Commented Most Favorited High Score Low Score Most Viewed All Templates Upload\
  \ an Image Articles News Explainers Collections Interviews Meme Insider Magazine\
  \ More Discord Newsletter Episodes Forums Meme Store Login Abstract user icon Memes\
  \ Categories Trending News Images Trending Images Videos Trending Videos Editorials\
  \ Meme Insider Magazine Newsletter Policies and Guidelines Meme Store Old site Login\
  \ Know Your Meme is the property of Literally Media \xA92024 Literally Media. All\
  \ Rights Reserved. This image Of Woman Confidently Strolling Through A Glass Panel\
  \ Has Been A Redraw Format Since 2021 Three Years Ago, This Boar's Head 'Exploded'\
  \ Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess Memes Turns Two Years\
  \ Old Today Phrase 'The Fridge Protects The Snacks' A Growing Favorite Among Pickup\
  \ Artist Influencers Jamie G, The Bosh British Charva, Has Taken Over TikTok With\
  \ His Signature 'Oh Cherie Amour' Sound Also Trending: Honey Extension Influencer\
  \ Scam Renegade Raider Copypasta Assassination of UnitedHealthcare CEO Inhaling\
  \ Seagull Added 7 years ago / Updated 3 years ago Confirmed 241,978 Part of a series\
  \ on *breath in* Boi. [View Related Entries] [View Related Sub-entries] View All\
  \ 56 Images Navigation About \u2022 Origin \u2022 Spread \u2022 Related Memes \u2022\
  \ Various Examples \u2022 Search Interest \u2022 External References \u2022 Recent\
  \ Images \u2022 Recent Videos About Inhaling Seagull is an exploitable two-panel\
  \ image macro series featuring a photograph of a seagull leaning backwards followed\
  \ by a picture of the seagull squawking forwards. The first image is captioned with\
  \ the word \"inhales\" while the second image is typically captioned with verbose\
  \ copypastas and song lyrics. Origin On July 12th, 2012, YouTuber Dimaniztlt uploaded\
  \ footage of a seagull appearing to throw its head backwards and laugh (shown below).\
  \ Within five years, the video gained over 181,000 views. On September 3rd, 2017,\
  \ Twitter [6] user @dioyasu tweeted a two-panel image of the seagull leaning back\
  \ and a deep-fried image of the seagull with the caption \"yamero.\" The tweet received\
  \ more than 38,000 retweets and 66,000 likes as of November 2018 (shown below, left).\
  \ That day, the same user tweeted[7] the two-panel seagull image with the caption\
  \ \"inhales / BOI,\" referencing the *breath in* / Boi meme. The tweet received\
  \ more than 1,000 retweets and 2,400 likes in a little over a year (shown below,\
  \ right). Spread On September 5th, 2017, Redditor MasterMooper posted a vertical\
  \ version of the second tweet, and within ten days, the post gathered upwards of\
  \ 3,700 points (98% upvoted) on /r/me_irl.[1] On September 10th, 2017, Redditor\
  \ FallingTower uploaded the image captioned with a Game of Thrones reference to\
  \ /r/freefolk[5] (shown below, left). The following day, Redditor Fedock submitted\
  \ a variation of the image referencing the \"omae ma wou shindeiru\" meme to /r/dankmemes[4]\
  \ (shown below, right). On September 13th, the Woken Memes Facebook[3] page posted\
  \ the image captioned with lyrics from the song \"Somebody Told Me\" by The Killers\
  \ (shown below, left). The same day, Imgur[2] user mentaljake uploaded a similar\
  \ variation featuring lyrics from the song \"All Star\" by Smash Mouth (shown below,\
  \ right). Related Memes Shut Seagull Shut Seagull refers to a screenshot from the\
  \ Inhaling Seagull video where the seagull's mouth is shut and its neck is extended.\
  \ A photoshopped-in \"OK Hand Emoji\" (\U0001F44C) is holding the seagull's mouth\
  \ shut, and the word \"shut\" is written at the bottom of the image (shown below).[8]\
  \ The image slowly spread across Reddit as an image macro through several high-interaction\
  \ posts and re-posts, as well as on Twitter as a reaction image (examples shown\
  \ below). Various Examples Search Interest Not available. External References [1]\
  \ Reddit \u2013 me irl [2] Imgur \u2013 Best use of this meme Ive seen so far [3]\
  \ Facebook \u2013 Woken Memes [4] Reddit \u2013 Nani? [5] Reddit \u2013 /r/freefolk\
  \ [6] Twitter \u2013 @dioyasu's Tweet [7] Twitter \u2013 @dioyasu's Tweet [8] Reddit\
  \ \u2013 shut image macro seagull bird exploitable Share Pin Sub-entries 1 total\
  \ Shut Seagull Recent Images 56 total View All Images Recent Videos 2 total View\
  \ All Videos Sign up for our Newsletter Load 7 Comments Comments 7 total 31 Inhaling\
  \ Seagull 241,978 2 56 7 Part of a series on *breath in* Boi. [View Related Entries]\
  \ [View Related Sub-entries] Updated Feb 05, 2021 at 11:39AM EST by Phillip Hamilton.\
  \ Added Sep 14, 2017 at 11:32AM EDT by Don. Like us on Facebook! Like 1.8M Share\
  \ Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the video\
  \ gallery, or 'r' to view a random entry. Meme Status Confirmed Year 2017 Origin\
  \ Reddit Tags image macro, seagull, bird, exploitable About Inhaling Seagull is\
  \ an exploitable two-panel image macro series featuring a photograph of a seagull\
  \ leaning backwards followed by a picture of the seagull squawking forwards. The\
  \ first image is captioned with the word \"inhales\" while the second image is typically\
  \ captioned with verbose copypastas and song lyrics. Origin On July 12th, 2012,\
  \ YouTuber Dimaniztlt uploaded footage of a seagull appearing to throw its head\
  \ backwards and laugh (shown below). Within five years, the video gained over 181,000\
  \ views. On September 3rd, 2017, Twitter [6] user @dioyasu tweeted a two-panel image\
  \ of the seagull leaning back and a deep-fried image of the seagull with the caption\
  \ \"yamero.\" The tweet received more than 38,000 retweets and 66,000 likes as of\
  \ November 2018 (shown below, left). That day, the same user tweeted[7] the two-panel\
  \ seagull image with the caption \"inhales / BOI,\" referencing the *breath in*\
  \ / Boi meme. The tweet received more than 1,000 retweets and 2,400 likes in a little\
  \ over a year (shown below, right). Spread On September 5th, 2017, Redditor MasterMooper\
  \ posted a vertical version of the second tweet, and within ten days, the post gathered\
  \ upwards of 3,700 points (98% upvoted) on /r/me_irl.[1] On September 10th, 2017,\
  \ Redditor FallingTower uploaded the image captioned with a Game of Thrones reference\
  \ to /r/freefolk[5] (shown below, left). The following day, Redditor Fedock submitted\
  \ a variation of the image referencing the \"omae ma wou shindeiru\" meme to /r/dankmemes[4]\
  \ (shown below, right). On September 13th, the Woken Memes Facebook[3] page posted\
  \ the image captioned with lyrics from the song \"Somebody Told Me\" by The Killers\
  \ (shown below, left). The same day, Imgur[2] user mentaljake uploaded a similar\
  \ variation featuring lyrics from the song \"All Star\" by Smash Mouth (shown below,\
  \ right). Related Memes Shut Seagull Shut Seagull refers to a screenshot from the\
  \ Inhaling Seagull video where the seagull's mouth is shut and its neck is extended.\
  \ A photoshopped-in \"OK Hand Emoji\" (\U0001F44C) is holding the seagull's mouth\
  \ shut, and the word \"shut\" is written at the bottom of the image (shown below).[8]\
  \ The image slowly spread across Reddit as an image macro through several high-interaction\
  \ posts and re-posts, as well as on Twitter as a reaction image (examples shown\
  \ below). Various Examples Search Interest Not available. External References [1]\
  \ Reddit \u2013 me irl [2] Imgur \u2013 Best use of this meme Ive seen so far [3]\
  \ Facebook \u2013 Woken Memes [4] Reddit \u2013 Nani? [5] Reddit \u2013 /r/freefolk\
  \ [6] Twitter \u2013 @dioyasu's Tweet [7] Twitter \u2013 @dioyasu's Tweet [8] Reddit\
  \ \u2013 shut Sub-entries 1 total Shut Seagull Recent Videos 2 total tfw you take\
  \ your food to the... Inhaling Seagull Uploaded by A soup can Sea Gull Inc. Inhaling\
  \ Seagull Uploaded by Eris + Add a Video Recent Images 56 total Inhaling Seagull\
  \ Uploaded by Bilbo Swaggins Inhaling Seagull Uploaded by Lugamo Inhaling Seagull\
  \ Uploaded by bruhinb Inhaling Seagull Uploaded by Cold Hard Crash Inhaling Seagull\
  \ Uploaded by andcallmeshirley Inhaling Seagull Uploaded by Makena Rasmussen Inhaling\
  \ Seagull Uploaded by nightqueen Inhaling Seagull Uploaded by Adam B. Inhaling Seagull\
  \ Uploaded by Eris Inhaling Seagull Uploaded by Bridget Inhaling Seagull Uploaded\
  \ by Cheesewagon Inhaling Seagull Uploaded by AlsKaw + Add an Image View All Images\
  \ Sign up for our Newsletter Top Comments Delete Sensitive Misk Wisk Sep 14, 2017\
  \ at 02:17PM EDT in reply to Mr. Candles You've reminded me. +32 Reply Delete Sensitive\
  \ Kanade_X_Yuri Sep 14, 2017 at 03:18PM EDT in reply to Misk Wisk He's so happy\
  \ +19 Reply + Add a Comment Comments (7) Display Comments Add a Comment Top Entries\
  \ This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (5) Don Administrator\
  \ & Meme Daddy Y F Digital Archaeologist & Treasurer & Media Maid Figgy Matt Secretary\
  \ of Memes Phillip Hamilton Bonk Connoisseur \u25BC + Request Editorship View All\
  \ Editors Today's Top Image Galleries Assassination of UnitedHealthcare CEO Squirrel\
  \ Girl (Doreen Green) Team Fortress 2 The Amazing Digital Circus About Our Story\
  \ Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes News\
  \ Staff Contact Extras! Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/inhaling-seagull
template_id: seagull
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.24
  angle: 0.0
  color: white
  font: comic
  scale_x: 0.25
  scale_y: 0.1
  start: 0.0
  stop: 1.0
  style: none
- align: center
  anchor_x: 0.0
  anchor_y: 0.75
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.25
  start: 0.0
  stop: 1.0
  style: none
text_zones: 2
