name: Skeptical Third World Kid
source: http://knowyourmeme.com/memes/third-world-success
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- you finished your plate
- because i was starving?
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Third World Success is an advice animal image macro series
  featuring a photograph of a dancing tribal child with captions about overcoming
  hardships that are associated with life in underdeveloped countries. The series
  can be seen as a derivative of Success Kid and the anti-thesis of First World Problems.
  Origin Prior to the image''s association with Third World Success, the image has
  been seen on Twitter[18] as early as June 2011 and paired with the phrase "It''s
  Friday, Niggas"[16] as early as October 14th, 2011.[17] The First World Problems
  image macro series started with a BuzzFeed[13] post in March 2011 that juxtaposed
  stories from the First World Problems subreddit[14] with the items in question.
  Later that year, a Quickmeme[15] page was created featuring a stock photo of a woman
  crying. As of March 2012, the page has over 91,000 instances. Terminology The Third
  World[24] is a term coined in 1952 by French anthropologist Alfred Sauvy to define
  countries that did not take part in either capitalism (the First World) or communism
  (the Second World). Over the years, it gradually gained a negative connotation,
  being associated with poverty and a country being underdeveloped.[25] In contrast,
  the phrase First World[26] is associated with already developed countries. First
  World Problems are meant to criticize the fact that people who live in countries
  considered the First World will probably not have to encounter problems their Third
  World counterparts will: not owning a computer, starvation, and combat.[27] Spread
  On November 11th, 2011, Slacktory published a compilation of photos entitled "Third
  World Perks: A Photo Meme"[8] as a alternative to First World Problems. The images
  consisted of people living in impoverished conditions accompanied by optimistic
  captions. Approximately two and a half weeks later on November 27th, the first Third
  World Success image macro was created on Quickmeme[1], featuring a photo of a group
  of dancing children with the caption "Found water / wasn''t contaminated." It was
  subsequently posted to Reddit[12] by user somename2222 and accumulated over 12,000
  up votes within 4 days. On November 28th, the viral content site BuzzFeed[4] posted
  a round-up of instances titled "The Third World Success Kid Meme." Within 24 hours,
  there were 230 Reddit threads related to the meme and 972 Quickmeme[3] submissions.
  On November 29th, the culture blog Molempire published another compilation of derivatives.
  The meme has since spread to Tumblr[5], the Body Building forums[6] and Meme Generator.[11]
  As of March 2012, there are over 8000 instances on Quickmeme and over 630 on Reddit.[19]
  AT&T President Lawsuit On April 27th, 2015, gossip news site TMZ reported[33] that
  Aaron Slator, President of Content and Ad Sales for the American multinational telecom
  corporation AT&T (shown below, left), is facing a $100 million racial discrimination
  lawsuit filed by Knoyme King, a former employee of the company who worked under
  Slator as a content coordinator. According to the lawsuit, King claims that Slator
  had sent a text message to a friend that featured a racially insensitive instance
  of the meme (shown below, right), which also happens to be the earliest known version
  in the series, along with the note "an oldie but goodie." The message in question
  was initially discovered by one of King''s colleagues and former assistance for
  Slator while transferring his data from an old cell phone to a new one. King also
  claims that she was treated unfairly and harassed by Slator for being a close acquaintance
  of his former assistant who discovered the message and that other executives at
  AT&T were informed about the incident but took no actions to reprimand Slator. The
  suit also accuses the company of maintaining a racially prejudiced culture, as King
  alleges she was repeatedly held back for promotions in favor of less qualified non-African
  American employees. That same day, an AT&T spokesperson issued a response condemning
  the action of Slator, who has played a vital role for the company in the merging
  and acquisition of DirecTV, calling the images "offensive to everyone at AT&T" and
  assuring that "a thorough investigation" has been launched to determine the appropriate
  course of disciplinary action. On the following day, AT&T released a statement confirming
  that Slator has been fired as a result of the controversy. "Aaron Slator has been
  terminated. There is no place for demeaning behavior within AT&T and we regret the
  action was not taken earlier." Notable Examples Derivatives Second World Success
  Kid On November 30th, 2011, a spin-off image macro series known as Second World
  Success[20] emerged on Reddit, which featured a picture of a smiling child waving
  a Chinese flag and various captions criticizing the developing nation''s controversial
  issues of child labor laws and censorship of free speech. Collections of notable
  Instances were subsequently posted on Memebase[21], FunnyJunk[22], and #1 Meme Universal
  Trend.[23] Skeptical Third World Success Kid On June 22nd, 2012, Redditor anute3392
  submitted a photograph of an Ugandan child titled "Skeptical 3rd World Child"[28]
  to the /r/pics subreddit. Apparently taken by Redditor Nepalm[32] during her trip
  to Uganda as a voluntary member of the Student Global Health Alliance, the photograph
  became an instant favorite and reached the frontpage of Reddit within hours of upload.
  Though the child in the photo has not been identified, the woman has been confirmed
  to be Heena Pranav, a doctor from Chicago who was in Uganda on a charity mission
  at the time.[35] The thread[28] went onto receive more than 17,000 upvotes and 725
  comments in the first 24 hours, as well as spawning a series of image macros with
  captions alluding to the Third World Success Kid and the Skeptical Baby, an advice
  animal character based on a photo of an eyebrow-raising infant that emerged months
  earlier in January 2012. The majority of notable examples poked fun at the drastically
  different standards of living in the First World countries or the White Man''s Guilt
  mentality, some Redditors quickly rebutted with a number of instances criticizing
  the community''s inclination towards slacktivism and trivializing the grave issue
  of famine in Africa. Search Interest External References [1] Quickmeme – Found water
  [2] Reddit – Third world success [3] Quickmeme – Third World Success [4] BuzzFeed
  – The Third World Success Kid Meme [5] Tumblr – #third world success [6] Body Building
  – Third World Success [7] FunnyJunk – third world success [8] Slacktory – Third
  World Perks A Photo Meme [9] The College Town Life – All My Bitches Love Me [10]
  Harpito – Niggas that shot wyclef [11] Meme Generator – Third World Success [12]
  Quickmeme – We have first world problems, so I thought we should also have third
  world successes [13] Buzzfeed – 15 Examples Of First World Problems [14] Reddit
  – /r/firstworldproblems [15] Quickmeme – First World Problems [16] Google – Image
  search for "It''s Friday Niggas [17] Facebook – Its friday niggas Photos [18] Twitter
  – @Quamdeen [19] Reddit – Search results for "Third World Success [20] Quickmeme
  – Second World Success [21] Memebase – And It''s Mostly True! [22] FunnyJunk – Second
  World Success Comp. [23] #1 Meme Universal Trend – Second World Success meme collection
  [24] Wikipedia – Third World [25] Cuso International – What''s In a Name? [26] Wikipedia
  – First World [27] Wikipedia – First World Problem [28] Reddit – Skeptical Third
  World Child [29] Imgur – Skeptical Third World Child [30] Quickmeme – Skeptical
  3rd World Child [31] Reddit – the_sgha''s comment [32] Reddit – Nepalm''s user profile
  [33] TMZ – T&T Sued Over Racist Meme Culture of Racism [34] TMZ – "AT&T PRESIDENT
  AXED OVER RACIST MEME LAWSUIT":www.tmz.com/2015/04/28/aaron-slater-fired-att-racist-meme-lawsuit/?adid=hero7
  [35] BBC News – What a viral picture tells us about child poverty in Africa'
aside_content: MemeStatusConfirmedYear2011OriginQuickmemeTagsadvice animal,commentary,third
  world,african baby
added_at: '2011-11-29T09:24:44-05:00'
