example:
- The Internet
- Everyone
- I made this.
- You made this?
- I made this.
keywords:
- null
name: I Made This
overlay:
- angle: 0.0
  center_x: 0.485
  center_y: 0.27
  scale: 0.12
- angle: 0.0
  center_x: 0.565
  center_y: 0.57
  scale: 0.12
- angle: 0.0
  center_x: 0.59
  center_y: 0.885
  scale: 0.11
scraped_content: "I Made This | Know Your Meme Hi! You must login or signup first!\
  \ Already a memeber? Login Now! Don't have an account? Sign up Now! Meme Encyclopedia\
  \ All Cultures Events People Sites Subcultures Videos Submit \u2192 Images Trending\
  \ Most Commented Most Favorited High Score Low Score Most Viewed All Templates Upload\
  \ an Image Articles News Explainers Collections Interviews Meme Insider Magazine\
  \ More Discord Newsletter Episodes Forums Meme Store Login Abstract user icon Memes\
  \ Categories Trending News Images Trending Images Videos Trending Videos Editorials\
  \ Meme Insider Magazine Newsletter Policies and Guidelines Meme Store Old site Login\
  \ Know Your Meme is the property of Literally Media \xA92024 Literally Media. All\
  \ Rights Reserved. This image Of Woman Confidently Strolling Through A Glass Panel\
  \ Has Been A Redraw Format Since 2021 Three Years Ago, This Boar's Head 'Exploded'\
  \ Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess Memes Turns Two Years\
  \ Old Today Phrase 'The Fridge Protects The Snacks' A Growing Favorite Among Pickup\
  \ Artist Influencers Jamie G, The Bosh British Charva, Has Taken Over TikTok With\
  \ His Signature 'Oh Cherie Amour' Sound Also Trending: Honey Extension Influencer\
  \ Scam Renegade Raider Copypasta Assassination of UnitedHealthcare CEO I Made This\
  \ Added 8 years ago / Updated 8 days ago Confirmed 249,513 Part of a series on Exploitables.\
  \ [View Related Entries] View All 49 Images Navigation About \u2022 Origin \u2022\
  \ Spread \u2022 Various Examples \u2022 Search Interest \u2022 External References\
  \ \u2022 Recent Images \u2022 Recent Videos About I Made This is an exploitable\
  \ where a character claims attribution for an object that another character created.\
  \ The exploitable is used in reference to scenarios where people steal other's creations.\
  \ Origin The original comic (below) was posted by Tumblr user Nedroid (real name:\
  \ Anthony Clark)[6] on January 30th, 2013,[1] with the caption \"The Internet.\"\
  \ It gained over 65,000 notes in three years. Spread After Nedroid's initial posting,\
  \ several users on Imgur and Tumblr reposted the comic without attribution with\
  \ the title \"I Made This,\" as a pun on its content. One such post, submitted to\
  \ Imgur by user mousestar on March 9th, 2013, received more than 190 points, 270\
  \ favorites, and 2.3 million views.[5] On October 9th, 2013, Imgur user Efreeti\
  \ uploaded an edit (below, left) about inventors Nikola Tesla and Thomas Edison,\
  \ referencing their concurrent discoveries of different types of lightbulbs. The\
  \ edit garnered over 3,500 points, 900 favorites, and 200,000 views in just over\
  \ two years.[2] On November 12th, 2013, an article was created by RVA Magazine about\
  \ allegations that musician Lil' Kim used a makeup artist's work as the cover of\
  \ her album without her permission.[3] In it, the meme (below, right) is used to\
  \ explain the issue. On December 3rd, 2013, a thread asking about I Made This was\
  \ submitted to /r/outoftheloop.[4] The main post got a score of 45 (83% upvoted),\
  \ and the answer scored 48 points before it was archived. The top voted answer defined\
  \ the illustration's use as \"illustrating how quickly people try and claim someone\
  \ else's work as their own on the internet.\" Various Examples Search Interest External\
  \ References [1] Tumblr \u2013 The Internet by Nedroid / January 30th, 2013 [2]\
  \ Imgur \u2013 I made this by Efreeti / October 9th, 2013 [3] RVA Magazine \u2013\
  \ Did Lil' Kim Steal The Cover Art for 'Dead Gal Walking'? / November 12th, 2013\
  \ [4] Reddit \u2013 What is with the whole 'I made this, you made this' thing? /\
  \ December 3rd, 2013 [5] Imgur \u2013 i made this little comic, hope you like it\
  \ [6] Nedroid \u2013 Nedroid.com stealing theft plagiarism tumblr exploitable efreeti\
  \ Share Pin Related Entries 466 total It Is Wednesday My Dudes Saddam Hussein's\
  \ Hiding Place Salt Bae Esther Verkest's Help Sign View All Related Entries Recent\
  \ Images 49 total View All Images Recent Videos 1 total View All Videos Sign up\
  \ for our Newsletter Load 27 Comments Comments 27 total 32 I Made This 249,513 1\
  \ 49 27 Part of a series on Exploitables. [View Related Entries] Updated Dec 15,\
  \ 2024 at 07:19PM EST by LiterallyAustin. Added Feb 13, 2016 at 02:54AM EST by Mom\
  \ Rivers. Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i' to view\
  \ the image gallery, 'v' to view the video gallery, or 'r' to view a random entry.\
  \ Meme Status Confirmed Year 2013 Origin Tumblr Tags stealing, theft, plagiarism,\
  \ tumblr, exploitable, efreeti About I Made This is an exploitable where a character\
  \ claims attribution for an object that another character created. The exploitable\
  \ is used in reference to scenarios where people steal other's creations. Origin\
  \ The original comic (below) was posted by Tumblr user Nedroid (real name: Anthony\
  \ Clark)[6] on January 30th, 2013,[1] with the caption \"The Internet.\" It gained\
  \ over 65,000 notes in three years. Spread After Nedroid's initial posting, several\
  \ users on Imgur and Tumblr reposted the comic without attribution with the title\
  \ \"I Made This,\" as a pun on its content. One such post, submitted to Imgur by\
  \ user mousestar on March 9th, 2013, received more than 190 points, 270 favorites,\
  \ and 2.3 million views.[5] On October 9th, 2013, Imgur user Efreeti uploaded an\
  \ edit (below, left) about inventors Nikola Tesla and Thomas Edison, referencing\
  \ their concurrent discoveries of different types of lightbulbs. The edit garnered\
  \ over 3,500 points, 900 favorites, and 200,000 views in just over two years.[2]\
  \ On November 12th, 2013, an article was created by RVA Magazine about allegations\
  \ that musician Lil' Kim used a makeup artist's work as the cover of her album without\
  \ her permission.[3] In it, the meme (below, right) is used to explain the issue.\
  \ On December 3rd, 2013, a thread asking about I Made This was submitted to /r/outoftheloop.[4]\
  \ The main post got a score of 45 (83% upvoted), and the answer scored 48 points\
  \ before it was archived. The top voted answer defined the illustration's use as\
  \ \"illustrating how quickly people try and claim someone else's work as their own\
  \ on the internet.\" Various Examples Search Interest External References [1] Tumblr\
  \ \u2013 The Internet by Nedroid / January 30th, 2013 [2] Imgur \u2013 I made this\
  \ by Efreeti / October 9th, 2013 [3] RVA Magazine \u2013 Did Lil' Kim Steal The\
  \ Cover Art for 'Dead Gal Walking'? / November 12th, 2013 [4] Reddit \u2013 What\
  \ is with the whole 'I made this, you made this' thing? / December 3rd, 2013 [5]\
  \ Imgur \u2013 i made this little comic, hope you like it [6] Nedroid \u2013 Nedroid.com\
  \ Related Entries 466 total It Is Wednesday My Dudes Saddam Hussein's Hiding Place\
  \ Salt Bae Esther Verkest's Help Sign Nice Girl Bike Gee Bill! How Come Your Mom\
  \ Lets You Eat Two Wieners? Just a Chill Guy / My New Character Couple Texting in\
  \ Bed Two Guys On A Bus Middle Finger Kid Hand Pointing a Gun How To Talk To Short\
  \ People View All Related Entries Recent Videos 1 total you made this? I Made This\
  \ Uploaded by som + Add a Video Recent Images 49 total I Made This Uploaded by Oclaf\
  \ I Made This Uploaded by Triplem I Made This Uploaded by finalfrog I Made This\
  \ Uploaded by Rogger I Made This Uploaded by thatguy1 I Made This Uploaded by Evilthing\
  \ I Made This Uploaded by Novaki I Made This Uploaded by Mr. Nobody Returns I Made\
  \ This Uploaded by nicktoonhero I Made This Uploaded by Bilbo Swaggins I Made This\
  \ Uploaded by JustTheWind I Made This Uploaded by Stormwatch + Add an Image View\
  \ All Images Sign up for our Newsletter Top Comments Delete Sensitive Mr. Man Feb\
  \ 13, 2016 at 05:49AM EST +97 Reply Delete Sensitive precambrian_ARISE Feb 13, 2016\
  \ at 06:00PM EST I saw some comment (on reddit mind you) about how there's actually\
  \ two possible interpretations for the original strip ; In the first one, the first\
  \ character made the thing and the second character then declare to have made it,\
  \ stealing the credit. In the second interpretation, the first character declare\
  \ to have made the thing to the second character, who is shocked because he was\
  \ the original creator and he just realize that somebedy stole the credit for it.\
  \ Both work, both send the same message, but you can't know which one is the right\
  \ one. +37 Reply + Add a Comment Comments (27) Display Comments Add a Comment Top\
  \ Entries This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (4) Mom Rivers\
  \ Database Moderator & Political Analyst Ari Spool The Mayor Y F Digital Archaeologist\
  \ & Treasurer & Media Maid Rose Abrams Entry Moderator + Request Editorship View\
  \ All Editors Today's Top Image Galleries Assassination of UnitedHealthcare CEO\
  \ Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing Digital Circus About\
  \ Our Story Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes\
  \ News Staff Contact Extras! Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/i-made-this
template_id: made
text:
- align: center
  anchor_x: 0.01
  anchor_y: 0.28
  angle: 0.0
  color: white
  font: thick
  scale_x: 0.25
  scale_y: 0.1
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.74
  anchor_y: 0.28
  angle: 0.0
  color: white
  font: thick
  scale_x: 0.25
  scale_y: 0.1
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.27
  anchor_y: 0.04
  angle: 0.0
  color: black
  font: comic
  scale_x: 0.15
  scale_y: 0.1
  start: 0.0
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.525
  anchor_y: 0.03
  angle: 0.0
  color: black
  font: comic
  scale_x: 0.15
  scale_y: 0.1
  start: 0.0
  stop: 1.0
  style: default
- align: center
  anchor_x: 0.345
  anchor_y: 0.725
  angle: 0.0
  color: black
  font: comic
  scale_x: 0.15
  scale_y: 0.1
  start: 0.0
  stop: 1.0
  style: default
text_zones: 5
