name: I Made This
source: https://knowyourmeme.com/memes/i-made-this
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.01
  anchor_y: 0.28
  angle: 0.0
  scale_x: 0.25
  scale_y: 0.1
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.74
  anchor_y: 0.28
  angle: 0.0
  scale_x: 0.25
  scale_y: 0.1
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: black
  font: comic
  anchor_x: 0.27
  anchor_y: 0.04
  angle: 0.0
  scale_x: 0.15
  scale_y: 0.1
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: black
  font: comic
  anchor_x: 0.525
  anchor_y: 0.03
  angle: 0.0
  scale_x: 0.15
  scale_y: 0.1
  align: center
  start: 0.0
  stop: 1.0
- style: default
  color: black
  font: comic
  anchor_x: 0.345
  anchor_y: 0.725
  angle: 0.0
  scale_x: 0.15
  scale_y: 0.1
  align: center
  start: 0.0
  stop: 1.0
example:
- The Internet
- Everyone
- I made this.
- You made this?
- I made this.
overlay:
- center_x: 0.485
  center_y: 0.27
  angle: 0.0
  scale: 0.12
- center_x: 0.565
  center_y: 0.57
  angle: 0.0
  scale: 0.12
- center_x: 0.59
  center_y: 0.885
  angle: 0.0
  scale: 0.11
scraped_content: 'About I Made This is an exploitable where a character claims attribution
  for an object that another character created. The exploitable is used in reference
  to scenarios where people steal other''s creations. Origin The original comic (below)
  was posted by Tumblr user Nedroid (real name: Anthony Clark)[6] on January 30th,
  2013,[1] with the caption "The Internet." It gained over 65,000 notes in three years.
  Spread After Nedroid''s initial posting, several users on Imgur and Tumblr reposted
  the comic without attribution with the title "I Made This," as a pun on its content.
  One such post, submitted to Imgur by user mousestar on March 9th, 2013, received
  more than 190 points, 270 favorites, and 2.3 million views.[5] On October 9th, 2013,
  Imgur user Efreeti uploaded an edit (below, left) about inventors Nikola Tesla and
  Thomas Edison, referencing their concurrent discoveries of different types of lightbulbs.
  The edit garnered over 3,500 points, 900 favorites, and 200,000 views in just over
  two years.[2] On November 12th, 2013, an article was created by RVA Magazine about
  allegations that musician Lil'' Kim used a makeup artist''s work as the cover of
  her album without her permission.[3] In it, the meme (below, right) is used to explain
  the issue. On December 3rd, 2013, a thread asking about I Made This was submitted
  to /r/outoftheloop.[4] The main post got a score of 45 (83% upvoted), and the answer
  scored 48 points before it was archived. The top voted answer defined the illustration''s
  use as "illustrating how quickly people try and claim someone else''s work as their
  own on the internet." Various Examples Search Interest External References [1] Tumblr
  – The Internet by Nedroid / January 30th, 2013 [2] Imgur – I made this by Efreeti
  / October 9th, 2013 [3] RVA Magazine – Did Lil'' Kim Steal The Cover Art for ''Dead
  Gal Walking''? / November 12th, 2013 [4] Reddit – What is with the whole ''I made
  this, you made this'' thing? / December 3rd, 2013 [5] Imgur – i made this little
  comic, hope you like it [6] Nedroid – Nedroid.com'
aside_content: MemeStatusConfirmedYear2013OriginTumblrTagsstealing,theft,plagiarism,tumblr,exploitable,efreeti
added_at: '2016-02-13T02:54:24-05:00'
