example:
- they will never find your body
- as attractive as i do
keywords:
- null
name: Dating Site Murderer
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Dating Site Murderer | Know Your Meme Hello! You must login or signup\
  \ first! Already a memeber? Login Now! Don't have an account? Sign up Now! Meme\
  \ Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Dating Site Murderer Added 13 years ago / Updated 8 days ago Confirmed 563,330\
  \ Part of a series on Online Dating. [View Related Entries] View All 103 Images\
  \ Navigation About \u2022 Origin \u2022 Spread \u2022 Notable Examples \u2022 Search\
  \ Interest \u2022 External References \u2022 Recent Images About Dating Site Murderer,\
  \ sometimes known as \u201CGood Intentions Axe Murderer\u201D, is an advice animal\
  \ image macro series based on a dimly lit photograph of a bearded Redditor. The\
  \ captions typically employ the bait-and-switch scheme similar to the Successful\
  \ Black Man series: the top line implies murderous intent, while the bottom line\
  \ brings a twist of something innocuous and sweet. Origin On March 21st, 2011, Redditor\
  \ spawn02000[9] posted a picture of himself to the WTF subreddit, titled \"I uploaded\
  \ my picture to a dating site\u2026 So far no hits\u2026 :(\" [1] It received 1,965\
  \ upvotes and made the front page. On the next day, he posted a follow-up image\
  \ titled \"Ok so I changed the picture on the dating site, Still no hits\u2026 :(\"\
  [2], which accumulated 1,265 upvotes. In terms of style, the series can be likened\
  \ to Vengeance Dad and Karate Kyle which took off on 4chan only a few months prior\
  \ to the emergence of Dating Site Murderer. Spread On March 22nd, a Quickmeme[3]\
  \ page was created, kicking off the initial wave of image macros. In one of the\
  \ earliest comments[10] on spawn0200's first image, the photo was captioned with\
  \ a normal dating experience on the top line, with the bottom changing the sentence\
  \ to appear as if he was going to murder someone. After several instances of this\
  \ appeared in that comment thread, Redditor WhitakerBlackall suggested switching\
  \ the pattern of the captions[11], creating the style that took off. One of the\
  \ first internet humor outlets to post a series of Dating Site Murderer images was\
  \ men's humor site Guyism[12] on March 22nd. The next day, more instances were shared\
  \ on Urlesque[4], pop culture site Next Round[13], and humor blog Blame It On The\
  \ Voices.[14] It appeared on Memebase[5] and MSNBC[6] on March 24th before being\
  \ front-paged on BuzzFeed[7] the next day. After seeing an AMA request thread[15]\
  \ oh Reddit, spawn02000, who never revealed his real name, posted an Ask Me Anything\
  \ thread[8] on September 29th, 2011. His OkCupid profile[16] still remains active,\
  \ complete with the original photo. Notable Examples Search Interest Search for\
  \ \"Dating Site Murder\" initially peaked in April 2011, with a second peak taking\
  \ place in November. External References [1] Reddit \u2013 I uploaded my photo to\
  \ a dating site\u2026 So far no hits.. :( [2] Reddit \u2013 Ok so I changed the\
  \ picture on the dating site, Still no hits\u2026 :( [3] Quickmeme \u2013 Dating\
  \ Site Murderer [4] Urlesque \u2013 'Dating Site Murderer' Meme Attacks Internet\
  \ \u2013 You'll Die Laughing [5] Memebase \u2013 Beware the Surprisingly Well-Mannered\
  \ Dating Site Murderer! [6] MSNBC \u2013 Pre-caffeine: Creepy 'Dating Site' meme\
  \ is creepy [7] BuzzFeed \u2013 Best Of Dating Site Murderer [8] Reddit \u2013 IAmA\
  \ \u2013 So I tried this a while ago and I think I messed it up. But yes I'll do\
  \ it again. I am a meme, 'The Blind date murderer' [9] Reddit \u2013 spawn02000\
  \ [10] Reddit \u2013 Comment thread with first macro [11] Reddit \u2013 Or we could\
  \ go the reverse route [12] Guyism \u2013 New Meme You Should Know: The \u201CBlind\
  \ Date Murderer\u201D [13] Next Round \u2013 Good Intentions Axe Murderer: Best\
  \ Of The New Meme Before It Chokes\u2026On It\u2019s Own Popularity [14] Blame It\
  \ On The Voices \u2013 Meme alert: Dating Site Murderer aka Good Intentions Axe\
  \ Murderer [15] Reddit \u2013 AMA Request response [16] OkCupid \u2013 spawn02000\
  \ image macro reddit advice dog relationship singledom dating online dating profile\
  \ Share Pin Related Entries 13 total Bye Felipe OKCupid Tinder How To Start A Conversation\
  \ W... View All Related Entries Recent Images 103 total View All Images Recent Videos\
  \ 0 total There are no recent videos. Sign up for our Newsletter Load 55 Comments\
  \ Comments 55 total 105 Dating Site Murderer 563,330 0 103 55 Part of a series on\
  \ Online Dating. [View Related Entries] Updated Dec 15, 2024 at 03:25PM EST by LiterallyAustin.\
  \ Added Mar 25, 2011 at 09:53AM EDT by Trick Lobo. Like us on Facebook! Like 1.8M\
  \ Share Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the\
  \ video gallery, or 'r' to view a random entry. Meme Status Confirmed Year 2011\
  \ Origin Reddit Tags image macro, reddit, advice dog, relationship, singledom, dating,\
  \ online dating, profile About Dating Site Murderer, sometimes known as \u201CGood\
  \ Intentions Axe Murderer\u201D, is an advice animal image macro series based on\
  \ a dimly lit photograph of a bearded Redditor. The captions typically employ the\
  \ bait-and-switch scheme similar to the Successful Black Man series: the top line\
  \ implies murderous intent, while the bottom line brings a twist of something innocuous\
  \ and sweet. Origin On March 21st, 2011, Redditor spawn02000[9] posted a picture\
  \ of himself to the WTF subreddit, titled \"I uploaded my picture to a dating site\u2026\
  \ So far no hits\u2026 :(\" [1] It received 1,965 upvotes and made the front page.\
  \ On the next day, he posted a follow-up image titled \"Ok so I changed the picture\
  \ on the dating site, Still no hits\u2026 :(\"[2], which accumulated 1,265 upvotes.\
  \ In terms of style, the series can be likened to Vengeance Dad and Karate Kyle\
  \ which took off on 4chan only a few months prior to the emergence of Dating Site\
  \ Murderer. Spread On March 22nd, a Quickmeme[3] page was created, kicking off the\
  \ initial wave of image macros. In one of the earliest comments[10] on spawn0200's\
  \ first image, the photo was captioned with a normal dating experience on the top\
  \ line, with the bottom changing the sentence to appear as if he was going to murder\
  \ someone. After several instances of this appeared in that comment thread, Redditor\
  \ WhitakerBlackall suggested switching the pattern of the captions[11], creating\
  \ the style that took off. One of the first internet humor outlets to post a series\
  \ of Dating Site Murderer images was men's humor site Guyism[12] on March 22nd.\
  \ The next day, more instances were shared on Urlesque[4], pop culture site Next\
  \ Round[13], and humor blog Blame It On The Voices.[14] It appeared on Memebase[5]\
  \ and MSNBC[6] on March 24th before being front-paged on BuzzFeed[7] the next day.\
  \ After seeing an AMA request thread[15] oh Reddit, spawn02000, who never revealed\
  \ his real name, posted an Ask Me Anything thread[8] on September 29th, 2011. His\
  \ OkCupid profile[16] still remains active, complete with the original photo. Notable\
  \ Examples Search Interest Search for \"Dating Site Murder\" initially peaked in\
  \ April 2011, with a second peak taking place in November. External References [1]\
  \ Reddit \u2013 I uploaded my photo to a dating site\u2026 So far no hits.. :( [2]\
  \ Reddit \u2013 Ok so I changed the picture on the dating site, Still no hits\u2026\
  \ :( [3] Quickmeme \u2013 Dating Site Murderer [4] Urlesque \u2013 'Dating Site\
  \ Murderer' Meme Attacks Internet \u2013 You'll Die Laughing [5] Memebase \u2013\
  \ Beware the Surprisingly Well-Mannered Dating Site Murderer! [6] MSNBC \u2013 Pre-caffeine:\
  \ Creepy 'Dating Site' meme is creepy [7] BuzzFeed \u2013 Best Of Dating Site Murderer\
  \ [8] Reddit \u2013 IAmA \u2013 So I tried this a while ago and I think I messed\
  \ it up. But yes I'll do it again. I am a meme, 'The Blind date murderer' [9] Reddit\
  \ \u2013 spawn02000 [10] Reddit \u2013 Comment thread with first macro [11] Reddit\
  \ \u2013 Or we could go the reverse route [12] Guyism \u2013 New Meme You Should\
  \ Know: The \u201CBlind Date Murderer\u201D [13] Next Round \u2013 Good Intentions\
  \ Axe Murderer: Best Of The New Meme Before It Chokes\u2026On It\u2019s Own Popularity\
  \ [14] Blame It On The Voices \u2013 Meme alert: Dating Site Murderer aka Good Intentions\
  \ Axe Murderer [15] Reddit \u2013 AMA Request response [16] OkCupid \u2013 spawn02000\
  \ Related Entries 13 total Bye Felipe OKCupid Tinder How To Start A Conversation\
  \ With A Girl Ghosting Miss Travel Ashley Madison Ben Affleck's Raya Response Grindr\
  \ Tinder / Hinge \"Pay to Play\" Lawsuit Hinge Voice Prompts Schmooze View All Related\
  \ Entries Recent Videos There are no videos currently available. + Add a Video Recent\
  \ Images 103 total Dating Site Murderer Uploaded by Mislav383 Dating Site Murderer\
  \ Uploaded by \xAD\xAD\xAD\xAD\xAD\xAD\xAD\xAD\xAD\xAD Dating Site Murderer Uploaded\
  \ by McGillis \"Makshima\" Fareed Dating Site Murderer Uploaded by sodaburst Dating\
  \ Site Murderer Uploaded by sodaburst Dating Site Murderer Uploaded by sodaburst\
  \ Dating Site Murderer Uploaded by C.R. B_____ Dating Site Murderer Uploaded by\
  \ C.R. B_____ Dating Site Murderer Uploaded by stowned Dating Site Murderer Uploaded\
  \ by lowbloom Dating Site Murderer Uploaded by lowbloom Dating Site Murderer Uploaded\
  \ by Bob Holly + Add an Image View All Images Sign up for our Newsletter Top Comments\
  \ Delete Sensitive DUH_13 Nov 21, 2011 at 10:42PM EST I'M GOING TO SKIN YOU SOME\
  \ POTATOES FOR DINNER +18 Reply Delete Sensitive Trollkeeper Aug 12, 2012 at 10:29AM\
  \ EDT At last\u2026one of the few decent Advice Animals gets confirmed. +6 Reply\
  \ + Add a Comment Comments (55) Display Comments Add a Comment Top Entries This\
  \ Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare CEO\
  \ Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (6) Trick Lobo\
  \ Digital Archaeologist & Archivist & Pundit Don Administrator & Meme Daddy Olivia\
  \ Gulin Original Gangster Brad Digital Archaeologist & Treasurer & Pundit & Gallery\
  \ Housekeeper Hiroman Digital Archaeologist & Cataloger & Pundit amanda b. Meme\
  \ Librarian \u25BC + Request Editorship View All Editors Today's Top Image Galleries\
  \ Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress\
  \ 2 The Amazing Digital Circus About Our Story Site Rules Policies and Guidelines\
  \ Credits Contact Meme DB Memes Episodes News Staff Contact Extras! Style Guide\
  \ RSS Feeds"
source: http://knowyourmeme.com/memes/dating-site-murderer
template_id: dsm
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
