name: Scumbag Brain
source: http://knowyourmeme.com/memes/scumbag-brain
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- remembers the face
- but not the name
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Scumbag Brain is an advice animal image macro series featuring
  a photo of a brain that is sometimes seen wearing the Scumbag Steve hat, with captions
  that describe self-conflicting psychological experiences like sudden realizations,
  awkward dreams and persistent memories. The situations presented are similar to
  Oh God Why rage comics. Origin The earliest known Scumbag Brain image macro was
  posted to the suicide support r/suicidewatch subreddit in a thread titled "Fucking
  Scumbag Brain"[1] by Redditor Jackist on March 24th, 2011, received only 198 upvotes
  prior to being archived. Spread Compilations of the series were posted to the humor
  blog Pleated Jeans[8] on July 21st, 2011 and to the viral content site BuzzFeed[7]
  on August 9th, 2011. On October 10th, 2011, the web comic site The Oatmeal[9] published
  a comic titled "If my brain were an imaginary friend" that featured an annoying
  brain that is able to remember complex information from several years ago, but cannot
  remember where it put a set of car keys. A single-topic blog, ScumbagBrain.org[10]
  was created in March 2012. The same month a series of instances was featured on
  PopHangover.[12] Additional derivatives can be found on Memebase[5], Tumblr[4] and
  Reddit[11], where there are more than 3800 instances. A Memegenerator[3] page has
  received 280 submissions, the Quickmeme[2] page has received more than 20,000 submissions
  and a Facebook[6] fan page has accumulated 203 likes as of May 2012. Notable Examples
  Search Interest Search queries for "scumbag brain" began rising in July of 2011,
  the same month the Quickmeme page was created. External References [1] Reddit r/suicidewatch
  – F*cking Scumbag Brain [2] QuickMeme – Scumbag Brain [3] memegenerator.net – Scumbag
  Brain\ [4] Tumblr – #scumbag brain [5] Memebase – scumbag brain [6] Facebook – Scumbag
  Brain [7] BuzzFeed – The 25 Best Of The Scumbag Brain Meme [8] Pleated Jeans – The
  Best of the Scumbag Brain Meme [9] The Oatmeal – If my brain were an imaginary friend
  [10] ScumbagBrain.org – Home [11] Reddit – Scumbag Brain search results [12] Pophangover
  – Scumbag Brain Meme'
aside_content: MemeStatusConfirmedYear2011OriginRedditTagsbrain,scumbag,scumbag hat
added_at: '2011-12-01T16:34:41-05:00'
