example:
- remembers the face
- but not the name
keywords:
- null
name: Scumbag Brain
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Scumbag Brain | Know Your Meme Hi! You must login or signup first!\
  \ Already a memeber? Login Now! Don't have an account? Sign up Now! Meme Encyclopedia\
  \ All Cultures Events People Sites Subcultures Videos Submit \u2192 Images Trending\
  \ Most Commented Most Favorited High Score Low Score Most Viewed All Templates Upload\
  \ an Image Articles News Explainers Collections Interviews Meme Insider Magazine\
  \ More Discord Newsletter Episodes Forums Meme Store Login Abstract user icon Memes\
  \ Categories Trending News Images Trending Images Videos Trending Videos Editorials\
  \ Meme Insider Magazine Newsletter Policies and Guidelines Meme Store Old site Login\
  \ Know Your Meme is the property of Literally Media \xA92024 Literally Media. All\
  \ Rights Reserved. This image Of Woman Confidently Strolling Through A Glass Panel\
  \ Has Been A Redraw Format Since 2021 Three Years Ago, This Boar's Head 'Exploded'\
  \ Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess Memes Turns Two Years\
  \ Old Today Phrase 'The Fridge Protects The Snacks' A Growing Favorite Among Pickup\
  \ Artist Influencers Jamie G, The Bosh British Charva, Has Taken Over TikTok With\
  \ His Signature 'Oh Cherie Amour' Sound Also Trending: Honey Extension Influencer\
  \ Scam Renegade Raider Copypasta Scumbag Brain Added 13 years ago / Updated 12 days\
  \ ago Confirmed 196,272 Part of a series on Scumbag Hat. [View Related Entries]\
  \ View All 86 Images Navigation About \u2022 Origin \u2022 Spread \u2022 Search\
  \ Interest \u2022 External References \u2022 Recent Images About Scumbag Brain is\
  \ an advice animal image macro series featuring a photo of a brain that is sometimes\
  \ seen wearing the Scumbag Steve hat, with captions that describe self-conflicting\
  \ psychological experiences like sudden realizations, awkward dreams and persistent\
  \ memories. The situations presented are similar to Oh God Why rage comics. Origin\
  \ The earliest known Scumbag Brain image macro was posted to the suicide support\
  \ r/suicidewatch subreddit in a thread titled \"Fucking Scumbag Brain\"[1] by Redditor\
  \ Jackist on March 24th, 2011, received only 198 upvotes prior to being archived.\
  \ Spread Compilations of the series were posted to the humor blog Pleated Jeans[8]\
  \ on July 21st, 2011 and to the viral content site BuzzFeed[7] on August 9th, 2011.\
  \ On October 10th, 2011, the web comic site The Oatmeal[9] published a comic titled\
  \ \"If my brain were an imaginary friend\" that featured an annoying brain that\
  \ is able to remember complex information from several years ago, but cannot remember\
  \ where it put a set of car keys. A single-topic blog, ScumbagBrain.org[10] was\
  \ created in March 2012. The same month a series of instances was featured on PopHangover.[12]\
  \ Additional derivatives can be found on Memebase[5], Tumblr[4] and Reddit[11],\
  \ where there are more than 3800 instances. A Memegenerator[3] page has received\
  \ 280 submissions, the Quickmeme[2] page has received more than 20,000 submissions\
  \ and a Facebook[6] fan page has accumulated 203 likes as of May 2012. Notable Examples\
  \ Search Interest Search queries for \"scumbag brain\" began rising in July of 2011,\
  \ the same month the Quickmeme page was created. External References [1] Reddit\
  \ r/suicidewatch \u2013 F*cking Scumbag Brain [2] QuickMeme \u2013 Scumbag Brain\
  \ [3] memegenerator.net \u2013 Scumbag Brain\\ [4] Tumblr \u2013 #scumbag brain\
  \ [5] Memebase \u2013 scumbag brain [6] Facebook \u2013 Scumbag Brain [7] BuzzFeed\
  \ \u2013 The 25 Best Of The Scumbag Brain Meme [8] Pleated Jeans \u2013 The Best\
  \ of the Scumbag Brain Meme [9] The Oatmeal \u2013 If my brain were an imaginary\
  \ friend [10] ScumbagBrain.org \u2013 Home [11] Reddit \u2013 Scumbag Brain search\
  \ results [12] Pophangover \u2013 Scumbag Brain Meme brain scumbag scumbag hat Share\
  \ Pin Related Entries 3 total Scumbag Christian Scumbag DNA Scumbag America Recent\
  \ Images 86 total View All Images Recent Videos 0 total There are no recent videos.\
  \ Sign up for our Newsletter Load 24 Comments Comments 24 total 61 Scumbag Brain\
  \ 196,272 0 86 24 Part of a series on Scumbag Hat. [View Related Entries] Updated\
  \ Dec 11, 2024 at 12:37PM EST by LiterallyAustin. Added Dec 01, 2011 at 04:34PM\
  \ EST by Sav. Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i'\
  \ to view the image gallery, 'v' to view the video gallery, or 'r' to view a random\
  \ entry. Meme Status Confirmed Year 2011 Origin Reddit Tags brain, scumbag, scumbag\
  \ hat About Scumbag Brain is an advice animal image macro series featuring a photo\
  \ of a brain that is sometimes seen wearing the Scumbag Steve hat, with captions\
  \ that describe self-conflicting psychological experiences like sudden realizations,\
  \ awkward dreams and persistent memories. The situations presented are similar to\
  \ Oh God Why rage comics. Origin The earliest known Scumbag Brain image macro was\
  \ posted to the suicide support r/suicidewatch subreddit in a thread titled \"Fucking\
  \ Scumbag Brain\"[1] by Redditor Jackist on March 24th, 2011, received only 198\
  \ upvotes prior to being archived. Spread Compilations of the series were posted\
  \ to the humor blog Pleated Jeans[8] on July 21st, 2011 and to the viral content\
  \ site BuzzFeed[7] on August 9th, 2011. On October 10th, 2011, the web comic site\
  \ The Oatmeal[9] published a comic titled \"If my brain were an imaginary friend\"\
  \ that featured an annoying brain that is able to remember complex information from\
  \ several years ago, but cannot remember where it put a set of car keys. A single-topic\
  \ blog, ScumbagBrain.org[10] was created in March 2012. The same month a series\
  \ of instances was featured on PopHangover.[12] Additional derivatives can be found\
  \ on Memebase[5], Tumblr[4] and Reddit[11], where there are more than 3800 instances.\
  \ A Memegenerator[3] page has received 280 submissions, the Quickmeme[2] page has\
  \ received more than 20,000 submissions and a Facebook[6] fan page has accumulated\
  \ 203 likes as of May 2012. Notable Examples Search Interest Search queries for\
  \ \"scumbag brain\" began rising in July of 2011, the same month the Quickmeme page\
  \ was created. External References [1] Reddit r/suicidewatch \u2013 F*cking Scumbag\
  \ Brain [2] QuickMeme \u2013 Scumbag Brain [3] memegenerator.net \u2013 Scumbag\
  \ Brain\\ [4] Tumblr \u2013 #scumbag brain [5] Memebase \u2013 scumbag brain [6]\
  \ Facebook \u2013 Scumbag Brain [7] BuzzFeed \u2013 The 25 Best Of The Scumbag Brain\
  \ Meme [8] Pleated Jeans \u2013 The Best of the Scumbag Brain Meme [9] The Oatmeal\
  \ \u2013 If my brain were an imaginary friend [10] ScumbagBrain.org \u2013 Home\
  \ [11] Reddit \u2013 Scumbag Brain search results [12] Pophangover \u2013 Scumbag\
  \ Brain Meme Related Entries 3 total Scumbag Christian Scumbag DNA Scumbag America\
  \ Recent Videos There are no videos currently available. + Add a Video Recent Images\
  \ 86 total Scumbag Brain Uploaded by nightqueen Scumbag Brain Uploaded by Alcat\xE9\
  ia Scumbag Brain Uploaded by James Scumbag Brain Uploaded by Brad Scumbag Brain\
  \ Uploaded by naomim09 Scumbag Brain Uploaded by Unraveler Scumbag Brain Uploaded\
  \ by NecronPariah Scumbag Brain Uploaded by Kotor Scumbag Brain Uploaded by Brad\
  \ Scumbag Brain Uploaded by \xAD\xAD\xAD\xAD\xAD\xAD\xAD\xAD\xAD\xAD Scumbag Brain\
  \ Uploaded by srmojuze Scumbag Brain Uploaded by Sparkster7744 + Add an Image View\
  \ All Images Sign up for our Newsletter Top Comments Delete Sensitive Moby The Duck\
  \ Dec 01, 2011 at 10:18PM EST Someone famous dies. Thinks of a joke. +32 Reply Delete\
  \ Sensitive BalisticDerr May 12, 2012 at 04:05PM EDT +23 Reply + Add a Comment Comments\
  \ (24) Display Comments Add a Comment Top Entries This Month Meme Saika Kawakita\
  \ Smile GIF Event Assassination of UnitedHealthcare CEO Person Luigi Mangione UHC\
  \ CEO Shooter Subculture The Ki Sisters Culture Pornography Site Whisper View More\
  \ Suggest a Change Edit History Entry Editors (5) Sav Rage Comicologist Don Administrator\
  \ & Meme Daddy Cyber6x Database Moderator & Midnight Channeler amanda b. Meme Librarian\
  \ Brad Digital Archaeologist & Treasurer & Pundit & Gallery Housekeeper \u25BC +\
  \ Request Editorship View All Editors Today's Top Image Galleries Assassination\
  \ of UnitedHealthcare CEO Team Fortress 2 Squirrel Girl (Doreen Green) The Amazing\
  \ Digital Circus About Our Story Site Rules Policies and Guidelines Credits Contact\
  \ Meme DB Memes Episodes News Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/scumbag-brain
template_id: sb
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
