name: You Know What Really Grinds My Gears?
source: http://knowyourmeme.com/memes/you-know-what-really-grinds-my-gears
keywords:
- Family Guy
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- you know what really grinds my gears?
- when people post images of cogs that don't mesh
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About "You Know What Really Grinds My Gears" is a memorable quote
  from the 2005 animated comedy film Family Guy Presents: Stewie Griffin: The Untold
  Story.[1] On the web, the expression is used to preface an airing of grievances
  in an advice animal image macro series featuring Family Guy protagonist Peter Griffin.
  Origin While the phrase has been used as an English idiom to introduce one''s pet
  peeve since as early as 1987 in the comedy film Planes, Trains & Automobiles,[13]
  its online popularity can be largely attributed to a gag featured in the 2005 direct-to-DVD
  animated film Family Guy Presents Stewie Griffin: The Untold Story. In the film,
  Peter Griffin hosts a local access news program titled “You Know What Really Grinds
  My Gears,” in which he complains about things and people that irk him, including
  Lindsay Lohan, people who lived in the 19th century, and the lack of new jokes about
  priests and rabbis. The gag is a parody of the 1976 satirical film Network[2] that
  follows the story of a newscaster whose on-air rant causes ratings to skyrocket
  and ultimately save his job. Spread As early as December 16th, 2005, complaint threads
  titled "What really grinds your gears?" began appearing on message boards including
  HeroClix Realms[4] and Xbox 360 Achievements.[5] In October 2007, a blogger named
  Gracie created You Know What Really Grinds My Gears?[6] (shown below, left), a personal
  blog journaling her pet peeves and other problems. In March 2008, another blog named
  This Is What Really Grinds My Gears[7](shown below, right) was launched, showcasing
  frustrations and personal problems submitted by the readers. On June 25th, 2011,
  a Meme Generator[9] page was created for “Grinds My Gears Peter Griffin,” using
  a still image of Griffin seated at a desk from the local access show scene in the
  movie. One of the first instances to be submitted to the /r/AdviceAnimals subreddit[14]
  was posted on August 23rd, 2012, suggesting that the poster was irked that the image
  macro series was not already established (shown below, left). Although a number
  of additional instances continued to appear throughout the rest of 2012, the advice
  animal character did not make the front page until May 15th, 2013,[15] paired with
  a complaint about people using images of mechanical gears that do not fit together
  with the expression (shown above, right). Notable Examples As of June 2013, there
  are more than 3,100 submissions of Grinds My Gears Peter Griffin on Meme Generator,
  with an additional 70 instances on Quickmeme.[10] Additional instances can be found
  on Reddit[11] and Tumblr.[12] Search Interest External References [1] IMDb – Family
  Guy Presents Stewie Griffin: The Untold Story [2] Wikipedia – Network (Film) [3]
  TV Tropes – What Really Grinds My Gears [4] HeroClix Realms – What Really Grinds
  Your Gears? Thread [5] Xbox 360 Achievements – You know what really grinds my gears…
  [6] Blogspot – You Know What Really Grinds My Gears? [7] Blogspot – This Is What
  Really Grinds My Gears [8] Facebook – You Know What Really Grinds My Gears ! ! [9]
  Meme Generator – Grinds My Gears Peter Griffin\ [10] Quickmeme – You know what really
  grinds my gears [11] Reddit – Search results for "what really grinds my gears" in
  /r/AdviceAnimals [12] Tumblr – Posts tagged "you know what really grinds my gears"
  [13] IMDb – Planes, Trains & Automobiles (1987) Quotes [14] Reddit – /r/AdviceAnimals:
  What really grinds my gears… [15] Reddit – /r/AdviceAnimals: You know what really
  grinds my gears? (Engineering point of view)'
aside_content: MemeStatusConfirmedYear2005OriginFamily GuyTagsfamily guy,advice animal,pet
  peeves
added_at: '2013-06-11T15:06:28-04:00'
