name: Fuck Me, Right?
source: http://knowyourmeme.com/memes/fuck-me-right
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- ''
- fuck me, right?
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Fuck Me, Right? is an image macro series featuring a screen
  capture of Jonah Hill sarcastically laughing in the 2007 comedy film Superbad. The
  top caption usually contains a confession about an unpopular opinion or noobish
  behavior, accompanied by the bottom caption “Fuck me, right?” The expression is
  meant to convey self-pity and resignation to the way the speaker is perceived by
  the majority. Origin The sarcastic expression was popularized through a scene from
  the 2007 comedy film Superbad, in which one of the main characters Seth (played
  by Jonah Hill) attempts to find a bathroom to wash menstrual fluid from his pants,
  saying “Fuck me, right?” in response to a girl standing in line (shown below). The
  movie was released on August 17th, 2007. Seth: "I gotta wash this Merlot off, is
  this the line?" Girl in line: "What does it look like?" Seth: "Fuck me, right?"
  Spread On March 9th, 2012, Redditor dwydwyy submitted an image macro to the /r/AdviceAnimals[11]
  subreddit, featuring a screen capture of Jonah Hill in the Superbad scene accompanied
  by the caption “Tries to make frontpage without a Kony meme / Fuck me, right?” (shown
  below) in reference to conversations about the Kony 2012 video. Prior to being archived,
  the post received over 11,800 up votes and 120 comments. On August 12th, 2012, a
  Facebook[12] page for “Fuck me, right?” was created and on the following day, FunnyJunk[3]
  user lostfaux submitted an image macro with the caption “I like to watch english
  dubbed anime / Fuck me, right?” (shown below, left) in referring to the widespread
  preference of English-subtitled animes over dubbed versions. Within two months,
  the post received over 49,000 views and 460 comments. On August 29th, 9gag[4] user
  n_nobody submitted a post titled “P*rn Logic" featuring a screen capture of adult
  film star Sasha Grey with the caption “My car broke down / Fuck me, right?” (shown
  below, right), which is meant to be interpreted in a literal sense. Within one month,
  the post received over 42,000 up votes and 11,000 Facebook shares. Notable Examples
  As of October 12th, 2012, the same template is being used on several Quickmeme pages,
  including “fuck me right”[6]with over 1,400 submissions, “Fuck me right”[9] with
  over 790 submissions and “Fuck Me Right”[8] with over 490 submissions. Additional
  examples of the meme can be found on the microblogging site Tumblr[5] under the
  tag “#fuck me right.” Search Interest External References [1] Urban Dictionary –
  Fuck Me Right [2] Reddit – Your grammar sucks [3] FunnyJunk – Dubbed anime [4] 9gag
  – Porn Logic [5] Tumblr – #fuck me right [6] Quickmeme – fuck me right [7] Facebook
  – Fuck me, right? [8] Quickmeme – Fuck Me Right [9] Quickmeme – Fuck me right [10]
  Reddit – I''d like this car, Fuck me, right? [11] Reddit – How I feel posting on
  Reddit this week [12] Facebook – Fuck me, right?'
aside_content: MemeStatusConfirmedYear2012OriginRedditTagsimage macro,advice animal,superbad,movie,quoteAdditional
  ReferencesUrban Dictionary
added_at: '2012-10-12T14:22:22-04:00'
