example:
- ''
- fuck me, right?
keywords:
- null
name: Fuck Me, Right?
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Fuck Me, Right? | Know Your Meme Hello! You must login or signup\
  \ first! Already a memeber? Login Now! Don't have an account? Sign up Now! Meme\
  \ Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Fuck Me, Right? Added 12 years ago / Updated 6 years ago Confirmed 390,761\
  \ View All 43 Images Navigation About \u2022 Origin \u2022 Spread \u2022 Notable\
  \ Examples \u2022 Search Interest \u2022 External References \u2022 Recent Images\
  \ \u2022 Recent Videos About Fuck Me, Right? is an image macro series featuring\
  \ a screen capture of Jonah Hill sarcastically laughing in the 2007 comedy film\
  \ Superbad. The top caption usually contains a confession about an unpopular opinion\
  \ or noobish behavior, accompanied by the bottom caption \u201CFuck me, right?\u201D\
  \ The expression is meant to convey self-pity and resignation to the way the speaker\
  \ is perceived by the majority. Origin The sarcastic expression was popularized\
  \ through a scene from the 2007 comedy film Superbad, in which one of the main characters\
  \ Seth (played by Jonah Hill) attempts to find a bathroom to wash menstrual fluid\
  \ from his pants, saying \u201CFuck me, right?\u201D in response to a girl standing\
  \ in line (shown below). The movie was released on August 17th, 2007. Seth: \"I\
  \ gotta wash this Merlot off, is this the line?\" Girl in line: \"What does it look\
  \ like?\" Seth: \"Fuck me, right?\" Spread On March 9th, 2012, Redditor dwydwyy\
  \ submitted an image macro to the /r/AdviceAnimals[11] subreddit, featuring a screen\
  \ capture of Jonah Hill in the Superbad scene accompanied by the caption \u201C\
  Tries to make frontpage without a Kony meme / Fuck me, right?\u201D (shown below)\
  \ in reference to conversations about the Kony 2012 video. Prior to being archived,\
  \ the post received over 11,800 up votes and 120 comments. On August 12th, 2012,\
  \ a Facebook[12] page for \u201CFuck me, right?\u201D was created and on the following\
  \ day, FunnyJunk[3] user lostfaux submitted an image macro with the caption \u201C\
  I like to watch english dubbed anime / Fuck me, right?\u201D (shown below, left)\
  \ in referring to the widespread preference of English-subtitled animes over dubbed\
  \ versions. Within two months, the post received over 49,000 views and 460 comments.\
  \ On August 29th, 9gag[4] user n_nobody submitted a post titled \u201CP*rn Logic\"\
  \ featuring a screen capture of adult film star Sasha Grey with the caption \u201C\
  My car broke down / Fuck me, right?\u201D (shown below, right), which is meant to\
  \ be interpreted in a literal sense. Within one month, the post received over 42,000\
  \ up votes and 11,000 Facebook shares. Notable Examples As of October 12th, 2012,\
  \ the same template is being used on several Quickmeme pages, including \u201Cfuck\
  \ me right\u201D[6]with over 1,400 submissions, \u201CFuck me right\u201D[9] with\
  \ over 790 submissions and \u201CFuck Me Right\u201D[8] with over 490 submissions.\
  \ Additional examples of the meme can be found on the microblogging site Tumblr[5]\
  \ under the tag \u201C#fuck me right.\u201D Search Interest External References\
  \ [1] Urban Dictionary \u2013 Fuck Me Right [2] Reddit \u2013 Your grammar sucks\
  \ [3] FunnyJunk \u2013 Dubbed anime [4] 9gag \u2013 Porn Logic [5] Tumblr \u2013\
  \ #fuck me right [6] Quickmeme \u2013 fuck me right [7] Facebook \u2013 Fuck me,\
  \ right? [8] Quickmeme \u2013 Fuck Me Right [9] Quickmeme \u2013 Fuck me right [10]\
  \ Reddit \u2013 I'd like this car, Fuck me, right? [11] Reddit \u2013 How I feel\
  \ posting on Reddit this week [12] Facebook \u2013 Fuck me, right? image macro advice\
  \ animal superbad movie quote Share Pin Recent Images 43 total View All Images Recent\
  \ Videos 2 total View All Videos Sign up for our Newsletter Load 22 Comments Comments\
  \ 22 total 13 Fuck Me, Right? 390,761 2 43 22 Updated Jul 05, 2018 at 05:17AM EDT\
  \ by Y F. Added Oct 12, 2012 at 02:22PM EDT by Don. Like us on Facebook! Like 1.8M\
  \ Share Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the\
  \ video gallery, or 'r' to view a random entry. Meme Status Confirmed Year 2012\
  \ Origin Reddit Tags image macro, advice animal, superbad, movie, quote Additional\
  \ References Urban Dictionary About Fuck Me, Right? is an image macro series featuring\
  \ a screen capture of Jonah Hill sarcastically laughing in the 2007 comedy film\
  \ Superbad. The top caption usually contains a confession about an unpopular opinion\
  \ or noobish behavior, accompanied by the bottom caption \u201CFuck me, right?\u201D\
  \ The expression is meant to convey self-pity and resignation to the way the speaker\
  \ is perceived by the majority. Origin The sarcastic expression was popularized\
  \ through a scene from the 2007 comedy film Superbad, in which one of the main characters\
  \ Seth (played by Jonah Hill) attempts to find a bathroom to wash menstrual fluid\
  \ from his pants, saying \u201CFuck me, right?\u201D in response to a girl standing\
  \ in line (shown below). The movie was released on August 17th, 2007. Seth: \"I\
  \ gotta wash this Merlot off, is this the line?\" Girl in line: \"What does it look\
  \ like?\" Seth: \"Fuck me, right?\" Spread On March 9th, 2012, Redditor dwydwyy\
  \ submitted an image macro to the /r/AdviceAnimals[11] subreddit, featuring a screen\
  \ capture of Jonah Hill in the Superbad scene accompanied by the caption \u201C\
  Tries to make frontpage without a Kony meme / Fuck me, right?\u201D (shown below)\
  \ in reference to conversations about the Kony 2012 video. Prior to being archived,\
  \ the post received over 11,800 up votes and 120 comments. On August 12th, 2012,\
  \ a Facebook[12] page for \u201CFuck me, right?\u201D was created and on the following\
  \ day, FunnyJunk[3] user lostfaux submitted an image macro with the caption \u201C\
  I like to watch english dubbed anime / Fuck me, right?\u201D (shown below, left)\
  \ in referring to the widespread preference of English-subtitled animes over dubbed\
  \ versions. Within two months, the post received over 49,000 views and 460 comments.\
  \ On August 29th, 9gag[4] user n_nobody submitted a post titled \u201CP*rn Logic\"\
  \ featuring a screen capture of adult film star Sasha Grey with the caption \u201C\
  My car broke down / Fuck me, right?\u201D (shown below, right), which is meant to\
  \ be interpreted in a literal sense. Within one month, the post received over 42,000\
  \ up votes and 11,000 Facebook shares. Notable Examples As of October 12th, 2012,\
  \ the same template is being used on several Quickmeme pages, including \u201Cfuck\
  \ me right\u201D[6]with over 1,400 submissions, \u201CFuck me right\u201D[9] with\
  \ over 790 submissions and \u201CFuck Me Right\u201D[8] with over 490 submissions.\
  \ Additional examples of the meme can be found on the microblogging site Tumblr[5]\
  \ under the tag \u201C#fuck me right.\u201D Search Interest External References\
  \ [1] Urban Dictionary \u2013 Fuck Me Right [2] Reddit \u2013 Your grammar sucks\
  \ [3] FunnyJunk \u2013 Dubbed anime [4] 9gag \u2013 Porn Logic [5] Tumblr \u2013\
  \ #fuck me right [6] Quickmeme \u2013 fuck me right [7] Facebook \u2013 Fuck me,\
  \ right? [8] Quickmeme \u2013 Fuck Me Right [9] Quickmeme \u2013 Fuck me right [10]\
  \ Reddit \u2013 I'd like this car, Fuck me, right? [11] Reddit \u2013 How I feel\
  \ posting on Reddit this week [12] Facebook \u2013 Fuck me, right? Recent Videos\
  \ 2 total Fuck me, right? Fuck Me, Right? Uploaded by iddqdmode \"Fuck Me\" - Eric\
  \ Cartman \"Sou... Fuck Me, Right? Uploaded by Brad + Add a Video Recent Images\
  \ 43 total Fuck Me, Right? Uploaded by Kyle Fuck Me, Right? Uploaded by Mzuark Fuck\
  \ Me, Right? Uploaded by dturner85 Fuck Me, Right? Uploaded by CommanderTroll65\
  \ Fuck Me, Right? Uploaded by endplanets Fuck Me, Right? Uploaded by endplanets\
  \ Fuck Me, Right? Uploaded by MandarinSegments Fuck Me, Right? Uploaded by Hullabaloo\
  \ Fuck Me, Right? Uploaded by ceej215 Fuck Me, Right? Uploaded by Senza32 Fuck Me,\
  \ Right? Uploaded by BlogDog123 Fuck Me, Right? Uploaded by theproton + Add an Image\
  \ View All Images Sign up for our Newsletter Top Comments Delete Sensitive Emperor\
  \ Palpitoad Oct 12, 2012 at 04:12PM EDT A bit late on actually documenting a meme\
  \ like this KYM but it's the thought that counts. Seriously though. +18 Reply Delete\
  \ Sensitive Crimson Locks Oct 12, 2012 at 04:23PM EDT Adds an article for an advice\
  \ animal right away, commenters get pissed and say KYM is rushing. Waits to add\
  \ article on advice animal, commenters say KYM is late to the party Fuck KYM, right?\
  \ But in all seriousness, I kinda like this one (emphasis on kinda). I'm gonna need\
  \ to see some actual spread before I can confirm this. +15 Reply + Add a Comment\
  \ Comments (22) Display Comments Add a Comment Top Entries This Month Meme Saika\
  \ Kawakita Smile GIF Event Assassination of UnitedHealthcare CEO Person Luigi Mangione\
  \ UHC CEO Shooter Subculture The Ki Sisters Culture Pornography Site Whisper View\
  \ More Suggest a Change Edit History Entry Editors (4) Don Administrator & Meme\
  \ Daddy Brad Digital Archaeologist & Treasurer & Pundit & Gallery Housekeeper Molly\
  \ Horan Tumblr Historian Y F Digital Archaeologist & Treasurer & Media Maid + Request\
  \ Editorship View All Editors Today's Top Image Galleries Assassination of UnitedHealthcare\
  \ CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing Digital Circus About\
  \ Our Story Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes\
  \ News Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/fuck-me-right
template_id: fmr
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
