example:
- me waiting for mom to stop talking on the phone
- so I can tell her my Pokemon evolved
keywords:
- null
name: Mini Keanu Reeves
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Mini Keanu Reeves | Know Your Meme Yo! You must login or signup\
  \ first! Already a memeber? Login Now! Don't have an account? Sign up Now! Meme\
  \ Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Mini Keanu Reeves Added 5 years ago / Updated 5 years ago Confirmed 219,236\
  \ Part of a series on Keanu Reeves. [View Related Entries] View All 60 Images Navigation\
  \ About \u2022 Origin \u2022 Spread \u2022 Various Examples \u2022 Templates \u2022\
  \ Search Interest \u2022 External References \u2022 Recent Images About Mini Keanu\
  \ Reeves, also known as Midget Keanu Reeves and Short Keanu Reeves, refers to a\
  \ still image of Keanu Reeves from the E3 2019 Cyberpunk 2077 presentation, edited\
  \ to make the actor appear disproportionately short. Online, the image has been\
  \ circulated as a blursed image and used as an exploitable. Origin On June 9th,\
  \ 2019, actor Keanu Reeves presented the upcoming CD Projekt Red-developed video\
  \ game Cyberpunk 2077 at the Microsoft's E3 2019 Xbox press conference.[1] On the\
  \ same day, Twitter user @KojiMads tweeted a still image of Keanu Reeves standing\
  \ on the stage, writing \"he really just stood like this and everyone went nuts\"\
  \ (shown below, left).[2] Several hours later, Twitter[3] user @JT_0907 tweeted\
  \ an edited version of the photograph showing Keanu Reeves with disproportionately\
  \ short stature (shown below. right). @KojiMads reposted the image and received\
  \ over 50 retweets and 370 likes in one week.[4] Spread In the following days, multiple\
  \ reposts of the image appeared on Twitter,[5] 4chan[6] and Reddit.[7] For example,\
  \ on June 10th, 2019, an anonymous 4chan user posted the image with a caption referencing\
  \ My Turn on the Xbox meme.[6] On June 11th, 2019, Redditor illufixe posted the\
  \ image to /r/blursedimages subreddit, where it gained over 1,300 upvotes in one\
  \ week.[7] On June 10th, a version of the image captioned Breathtaking was posted\
  \ by Twitter user @Thaddeus_Hamlet (shown below, left).[8] On June 11th, Redditor\
  \ Howboutnoy posted a My Turn on the Xbox meme to /r/memes subreddit, gaining over\
  \ 6,000 upvotes in six days (shown below, center).[9] On June 12th, 2019, the image\
  \ was repost to /r/bossfight subreddit as \"Little brother Keanu\",[10] with fan\
  \ art posted by Redditor Lorpo314 on June 13th (shown below, right).[11] On June\
  \ 12th, 2019, YouTuber Pyrocynical used the image as a thumbnail for his E3 2019\
  \ review video, promoting the further spread of the meme (shown below, left).[12]\
  \ In the following days, multiple memes based on the image appeared on Reddit and\
  \ other online platforms. On June 17th, 2019, YouTuber PewDiePie used the image\
  \ as a video thumbnail (shown below, right).[13] Various Examples Templates Search\
  \ Interest External References [1] Polygon \u2013 New Cyberpunk 2077 trailer reveals\
  \ Keanu Reeves, April 2020 release date [2] Twitter \u2013 @KojiMads' Tweet [3]\
  \ Twitter \u2013 @JT_0907's Tweet [4] Twitter \u2013 @KojiMads' Tweet [5] Twitter\
  \ \u2013 @JoakkoCanonico's Tweet [6] 4chan \u2013 /v/ Post #465576137 [7] Reddit\
  \ \u2013 Blursed Keanu Reeves [8] Twitter \u2013 @Thaddeus_Hamlet's Post [9] Reddit\
  \ \u2013 Midget Keanu [10] Reddit \u2013 Little brother Keanu [11] Reddit \u2013\
  \ [OC][Art] Little brother Keanu painting i did [12] YouTube \u2013 E3 2019 [13]\
  \ YouTube \u2013 Keanu Reeves keanu reeves short shrinked mini small e3 cyberpunk\
  \ 2077 tiny pocket howboutnoy @kojimads illufixe @thaddeus_hamlet Share Pin Related\
  \ Entries 16 total Sad Keanu Conspiracy Keanu Happy Keanu You're Breathtaking View\
  \ All Related Entries Recent Images 60 total View All Images Recent Videos 0 total\
  \ There are no recent videos. Sign up for our Newsletter Load 5 Comments Comments\
  \ 5 total 22 Mini Keanu Reeves 219,236 0 60 5 Part of a series on Keanu Reeves.\
  \ [View Related Entries] Updated Dec 23, 2019 at 05:21PM EST by Matt. Added Jun\
  \ 17, 2019 at 06:13PM EDT by Philipp. Like us on Facebook! Like 1.8M Share Save\
  \ Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the video gallery,\
  \ or 'r' to view a random entry. Meme Status Confirmed Type: Exploitable Year 2019\
  \ Origin Twitter Tags keanu reeves, short, shrinked, mini, small, e3, cyberpunk\
  \ 2077, tiny, pocket, howboutnoy, @kojimads, illufixe, @thaddeus_hamlet About Mini\
  \ Keanu Reeves, also known as Midget Keanu Reeves and Short Keanu Reeves, refers\
  \ to a still image of Keanu Reeves from the E3 2019 Cyberpunk 2077 presentation,\
  \ edited to make the actor appear disproportionately short. Online, the image has\
  \ been circulated as a blursed image and used as an exploitable. Origin On June\
  \ 9th, 2019, actor Keanu Reeves presented the upcoming CD Projekt Red-developed\
  \ video game Cyberpunk 2077 at the Microsoft's E3 2019 Xbox press conference.[1]\
  \ On the same day, Twitter user @KojiMads tweeted a still image of Keanu Reeves\
  \ standing on the stage, writing \"he really just stood like this and everyone went\
  \ nuts\" (shown below, left).[2] Several hours later, Twitter[3] user @JT_0907 tweeted\
  \ an edited version of the photograph showing Keanu Reeves with disproportionately\
  \ short stature (shown below. right). @KojiMads reposted the image and received\
  \ over 50 retweets and 370 likes in one week.[4] Spread In the following days, multiple\
  \ reposts of the image appeared on Twitter,[5] 4chan[6] and Reddit.[7] For example,\
  \ on June 10th, 2019, an anonymous 4chan user posted the image with a caption referencing\
  \ My Turn on the Xbox meme.[6] On June 11th, 2019, Redditor illufixe posted the\
  \ image to /r/blursedimages subreddit, where it gained over 1,300 upvotes in one\
  \ week.[7] On June 10th, a version of the image captioned Breathtaking was posted\
  \ by Twitter user @Thaddeus_Hamlet (shown below, left).[8] On June 11th, Redditor\
  \ Howboutnoy posted a My Turn on the Xbox meme to /r/memes subreddit, gaining over\
  \ 6,000 upvotes in six days (shown below, center).[9] On June 12th, 2019, the image\
  \ was repost to /r/bossfight subreddit as \"Little brother Keanu\",[10] with fan\
  \ art posted by Redditor Lorpo314 on June 13th (shown below, right).[11] On June\
  \ 12th, 2019, YouTuber Pyrocynical used the image as a thumbnail for his E3 2019\
  \ review video, promoting the further spread of the meme (shown below, left).[12]\
  \ In the following days, multiple memes based on the image appeared on Reddit and\
  \ other online platforms. On June 17th, 2019, YouTuber PewDiePie used the image\
  \ as a video thumbnail (shown below, right).[13] Various Examples Templates Search\
  \ Interest External References [1] Polygon \u2013 New Cyberpunk 2077 trailer reveals\
  \ Keanu Reeves, April 2020 release date [2] Twitter \u2013 @KojiMads' Tweet [3]\
  \ Twitter \u2013 @JT_0907's Tweet [4] Twitter \u2013 @KojiMads' Tweet [5] Twitter\
  \ \u2013 @JoakkoCanonico's Tweet [6] 4chan \u2013 /v/ Post #465576137 [7] Reddit\
  \ \u2013 Blursed Keanu Reeves [8] Twitter \u2013 @Thaddeus_Hamlet's Post [9] Reddit\
  \ \u2013 Midget Keanu [10] Reddit \u2013 Little brother Keanu [11] Reddit \u2013\
  \ [OC][Art] Little brother Keanu painting i did [12] YouTube \u2013 E3 2019 [13]\
  \ YouTube \u2013 Keanu Reeves Related Entries 16 total Sad Keanu Conspiracy Keanu\
  \ Happy Keanu You're Breathtaking Tai Chi Keanu Sad Keanu in a Helmet Keanu Reeves\
  \ Dining in Headphones Cyberpunk 2077 Keanu Reeves / We Have a City to Burn Knock\
  \ Knock Keanu Reeves Is Such A Gentleman / Celebrity At A Barbershop Copypasta Tumbleweed\
  \ Keanu Reeves Keanu Reeves Walking in Slow Motion View All Related Entries Recent\
  \ Videos There are no videos currently available. + Add a Video Recent Images 60\
  \ total Mini Keanu Reeves Uploaded by GoingSolo44 Mini Keanu Reeves Uploaded by\
  \ Ass Railroad Mini Keanu Reeves Uploaded by Matt Mini Keanu Reeves Uploaded by\
  \ Reddit Moments Mini Keanu Reeves Uploaded by Sendy Lie Mini Keanu Reeves Uploaded\
  \ by Juicydeath1025 Mini Keanu Reeves Uploaded by Jes\xFAs martin Mini Keanu Reeves\
  \ Uploaded by Sendy Lie Mini Keanu Reeves Uploaded by Kotor Mini Keanu Reeves Uploaded\
  \ by Philipp Mini Keanu Reeves Uploaded by Philipp Mini Keanu Reeves Uploaded by\
  \ Sophie + Add an Image View All Images Sign up for our Newsletter Top Comments\
  \ Delete Sensitive Lone K. (Echoid) Jun 28, 2019 at 06:40AM EDT ok what was causing\
  \ people to search up \"mini Keanu Reaves\" between 2004-2008? +6 Reply Delete Sensitive\
  \ TOMNICE Jun 21, 2019 at 07:11PM EDT do not talk to me or my son ever again +6\
  \ Reply + Add a Comment Comments (5) Display Comments Add a Comment Top Entries\
  \ This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (4) Philipp\
  \ Memesplainer Y F Digital Archaeologist & Treasurer & Media Maid Don Administrator\
  \ & Meme Daddy Matt Secretary of Memes + Request Editorship View All Editors Today's\
  \ Top Image Galleries Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen\
  \ Green) Team Fortress 2 The Amazing Digital Circus About Our Story Site Rules Policies\
  \ and Guidelines Credits Contact Meme DB Memes Episodes News Staff Contact Extras!\
  \ Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/mini-keanu-reeves
template_id: mini-keanu
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
