name: Mini Keanu Reeves
source: https://knowyourmeme.com/memes/mini-keanu-reeves
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- me waiting for mom to stop talking on the phone
- so I can tell her my Pokemon evolved
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Mini Keanu Reeves, also known as Midget Keanu Reeves and Short
  Keanu Reeves, refers to a still image of Keanu Reeves from the E3 2019 Cyberpunk
  2077 presentation, edited to make the actor appear disproportionately short. Online,
  the image has been circulated as a blursed image and used as an exploitable. Origin
  On June 9th, 2019, actor Keanu Reeves presented the upcoming CD Projekt Red-developed
  video game Cyberpunk 2077 at the Microsoft''s E3 2019 Xbox press conference.[1]
  On the same day, Twitter user @KojiMads tweeted a still image of Keanu Reeves standing
  on the stage, writing "he really just stood like this and everyone went nuts" (shown
  below, left).[2] Several hours later, Twitter[3] user @JT_0907 tweeted an edited
  version of the photograph showing Keanu Reeves with disproportionately short stature
  (shown below. right). @KojiMads reposted the image and received over 50 retweets
  and 370 likes in one week.[4] Spread In the following days, multiple reposts of
  the image appeared on Twitter,[5] 4chan[6] and Reddit.[7] For example, on June 10th,
  2019, an anonymous 4chan user posted the image with a caption referencing My Turn
  on the Xbox meme.[6] On June 11th, 2019, Redditor illufixe posted the image to /r/blursedimages
  subreddit, where it gained over 1,300 upvotes in one week.[7] On June 10th, a version
  of the image captioned Breathtaking was posted by Twitter user @Thaddeus_Hamlet
  (shown below, left).[8] On June 11th, Redditor Howboutnoy posted a My Turn on the
  Xbox meme to /r/memes subreddit, gaining over 6,000 upvotes in six days (shown below,
  center).[9] On June 12th, 2019, the image was repost to /r/bossfight subreddit as
  "Little brother Keanu",[10] with fan art posted by Redditor Lorpo314 on June 13th
  (shown below, right).[11] On June 12th, 2019, YouTuber Pyrocynical used the image
  as a thumbnail for his E3 2019 review video, promoting the further spread of the
  meme (shown below, left).[12] In the following days, multiple memes based on the
  image appeared on Reddit and other online platforms. On June 17th, 2019, YouTuber
  PewDiePie used the image as a video thumbnail (shown below, right).[13] Various
  Examples Templates Search Interest External References [1] Polygon – New Cyberpunk
  2077 trailer reveals Keanu Reeves, April 2020 release date [2] Twitter – @KojiMads''
  Tweet [3] Twitter – @JT_0907''s Tweet [4] Twitter – @KojiMads'' Tweet [5] Twitter
  – @JoakkoCanonico''s Tweet [6] 4chan – /v/ Post #465576137 [7] Reddit – Blursed
  Keanu Reeves [8] Twitter – @Thaddeus_Hamlet''s Post [9] Reddit – Midget Keanu [10]
  Reddit – Little brother Keanu [11] Reddit – [OC][Art] Little brother Keanu painting
  i did [12] YouTube – E3 2019 [13] YouTube – Keanu Reeves'
aside_content: MemeStatusConfirmedType:ExploitableYear2019OriginTwitterTagskeanu reeves,short,shrinked,mini,small,e3,cyberpunk
  2077,tiny,pocket,howboutnoy,@kojimads,illufixe,@thaddeus_hamlet
added_at: '2019-06-17T18:13:53-04:00'
