name: No Soup for You
source: https://knowyourmeme.com/memes/no-soup-for-you-soup-nazi
keywords:
- Seinfeld
- Soup Nazi
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- no soup for you!
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About "No Soup For You" or "NO SOUP 4 U" is a catchphrase that was
  initially uttered in a 1995 episode of the American comedic sitcom Seinfeld. Online,
  the phrase is often used in the context of message boards and forums in reply to
  other users who have made requests or demands that are denied or cannot be fulfilled.
  Origin In the November 2nd, 1995 Seinfeld episode "The Soup Nazi"[1], the main characters
  check out a local soup shop with an incredibly strict chef (played by Larry Thomas[6])
  who is nicknamed "Soup Nazi" for his rules about ordering. After Elaine Benes (played
  by Julia Louis-Dreyfus) attempts to subvert his ordering procedure, the chef utters
  the statement, banning her from the shop for an entire year. Thomas'' character
  was inspired by a real-life soup vendor named Ali "Al" Yeganeh[16] whose Manhattan
  restaurant, Soup Kitchen International, had been notorious for having strict ordering
  rules[17] since 1984. Spread Throughout the 1990s, the quote and the character that
  spoke it was iconic in the Seinfeld fandom and wider pop culture, spawning specific
  merchandise[11] with the quote. One of the earliest mentions of the quote online
  appeared on August 10th, 1996, when Ted Weiman announced to alt.tv.seinfeld[18]
  that he launched a "No Soup For You" soundclip site.[19] In September 1996, the
  phrase was used on rec.sport.football.fantasy[20] in response to a question about
  whether or not a poster should veto a fantasy football trade. Between 1996 and 2003,
  the phrase was used in this declining manner on a number of newsgroups including
  alt.tv.star-trek.voyager[21], alt.music.tool[22], alt.holoworld.rpg.startrek[23]
  and alt.christnet.christianlife.[24] On April 27th, 2004, the first YTMND site[14]
  referencing the Seinfeld episode was created, gaining more than 600 views as of
  May 2013. Over the years, a handful of other sites with the title "No Soup For You"[28]
  have been created, gaining anywhere from several hundred to six thousand views.
  In 2008, the phrase was mentioned on 4chan[25] for the first time in a thread on
  /a/ (Anime and Manga) discussing Rukia Kuchiki of the series Bleach. On November
  14th, 2009, the first Facebook[15] fan page dedicated to the phrase launched, accruing
  more than 9,100 likes as of May 2013. References to the quote have appeared in image
  macros on a number of humor websites including Meme Center[7], Funnyjunk[8], Cheezburger[26]
  and Funny Pictures Blog[10], as well as in a Tumblr tag[13] and Twitter hashtag.[27]
  A Quickmeme[9] page utilizing a photo of Larry Thomas as the Soup Nazi has 26 submissions
  as of May 2013, with captions primarily relating to Reddit activities. Notable Examples
  Search Interest External References [1] Wikipedia – The Soup Nazi [2] The Guardian
  – No Catchphrase for you! [3] IMBD – The Soup Nazi [4] Soupnazi on Twitter [5] WikiSein
  – The Soup Nazi [6] RealSoupNazi.com [7] Memecenter – No Soup For You [8] Funnyjunk
  – No Soup For You [9] QuickMeme – No Soup For You [10] Funny Pictures Blog – No
  Soup For You [11] Amazon.com – No Soup For You Mens Tee [12] Rap Genius – Wale –
  The Soup [13] Tumblr – Posts tagged with ''No Soup For You'' [14] YTMND – No Soup
  For You [15] Facebook – No Soup For You [16] The Original Soup Man – Home [17] The
  Original Soup Man – Al''s Rules [18] alt.tv.seinfeld – "No Soup For You" sound clip
  site! [19] Ted''s Seinfeld Page – Seinfeld Sound Clips [20] rec.sport.football.fantasy
  – Collusion question [21] alt.tv.star-trek.voyager – Think Tank (or "NO SOUP FOR
  YOU!!!") [22] alt.music.tool – No Soup for You, Styx! [23] alt.holoworld.rpg.startrek
  – USS:Hermes No soup for you! [24] alt.christnet.christianlife – No Soup for You
  [25] Foolz Archive – NO SOUP FOR YOU! (NSFW) [26] Cheezburger – Search results for
  "no soup for you" [27] Twitter – Tweet results for #nosoupforyou [28] YTMND – Search
  results for "no soup for you"'
aside_content: MemeStatusConfirmedYear1995OriginSeinfieldTagssoup nazi,seinfield,no
  soup for youAdditional ReferencesMeme GeneratorUrban DictionaryWikipedia
added_at: '2013-05-02T00:33:20-04:00'
