example:
- no soup for you!
keywords:
- Seinfeld
- Soup Nazi
name: No Soup for You
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "No Soup for You / Soup Nazi | Know Your Meme Yo Yo! You must login\
  \ or signup first! Already a memeber? Login Now! Don't have an account? Sign up\
  \ Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos Submit\
  \ \u2192 Images Trending Most Commented Most Favorited High Score Low Score Most\
  \ Viewed All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO No Soup for You / Soup Nazi Added 11 years ago / Updated 8 days ago Confirmed\
  \ 63,415 Part of a series on Seinfeld. [View Related Entries] View All 35 Images\
  \ Navigation About \u2022 Origin \u2022 Spread \u2022 Search Interest \u2022 External\
  \ References \u2022 Recent Images \u2022 Recent Videos About \"No Soup For You\"\
  \ or \"NO SOUP 4 U\" is a catchphrase that was initially uttered in a 1995 episode\
  \ of the American comedic sitcom Seinfeld. Online, the phrase is often used in the\
  \ context of message boards and forums in reply to other users who have made requests\
  \ or demands that are denied or cannot be fulfilled. Origin In the November 2nd,\
  \ 1995 Seinfeld episode \"The Soup Nazi\"[1], the main characters check out a local\
  \ soup shop with an incredibly strict chef (played by Larry Thomas[6]) who is nicknamed\
  \ \"Soup Nazi\" for his rules about ordering. After Elaine Benes (played by Julia\
  \ Louis-Dreyfus) attempts to subvert his ordering procedure, the chef utters the\
  \ statement, banning her from the shop for an entire year. Thomas' character was\
  \ inspired by a real-life soup vendor named Ali \"Al\" Yeganeh[16] whose Manhattan\
  \ restaurant, Soup Kitchen International, had been notorious for having strict ordering\
  \ rules[17] since 1984. Spread Throughout the 1990s, the quote and the character\
  \ that spoke it was iconic in the Seinfeld fandom and wider pop culture, spawning\
  \ specific merchandise[11] with the quote. One of the earliest mentions of the quote\
  \ online appeared on August 10th, 1996, when Ted Weiman announced to alt.tv.seinfeld[18]\
  \ that he launched a \"No Soup For You\" soundclip site.[19] In September 1996,\
  \ the phrase was used on rec.sport.football.fantasy[20] in response to a question\
  \ about whether or not a poster should veto a fantasy football trade. Between 1996\
  \ and 2003, the phrase was used in this declining manner on a number of newsgroups\
  \ including alt.tv.star-trek.voyager[21], alt.music.tool[22], alt.holoworld.rpg.startrek[23]\
  \ and alt.christnet.christianlife.[24] On April 27th, 2004, the first YTMND site[14]\
  \ referencing the Seinfeld episode was created, gaining more than 600 views as of\
  \ May 2013. Over the years, a handful of other sites with the title \"No Soup For\
  \ You\"[28] have been created, gaining anywhere from several hundred to six thousand\
  \ views. In 2008, the phrase was mentioned on 4chan[25] for the first time in a\
  \ thread on /a/ (Anime and Manga) discussing Rukia Kuchiki of the series Bleach.\
  \ On November 14th, 2009, the first Facebook[15] fan page dedicated to the phrase\
  \ launched, accruing more than 9,100 likes as of May 2013. References to the quote\
  \ have appeared in image macros on a number of humor websites including Meme Center[7],\
  \ Funnyjunk[8], Cheezburger[26] and Funny Pictures Blog[10], as well as in a Tumblr\
  \ tag[13] and Twitter hashtag.[27] A Quickmeme[9] page utilizing a photo of Larry\
  \ Thomas as the Soup Nazi has 26 submissions as of May 2013, with captions primarily\
  \ relating to Reddit activities. Notable Examples Search Interest External References\
  \ [1] Wikipedia \u2013 The Soup Nazi [2] The Guardian \u2013 No Catchphrase for\
  \ you! [3] IMBD \u2013 The Soup Nazi [4] Soupnazi on Twitter [5] WikiSein \u2013\
  \ The Soup Nazi [6] RealSoupNazi.com [7] Memecenter \u2013 No Soup For You [8] Funnyjunk\
  \ \u2013 No Soup For You [9] QuickMeme \u2013 No Soup For You [10] Funny Pictures\
  \ Blog \u2013 No Soup For You [11] Amazon.com \u2013 No Soup For You Mens Tee [12]\
  \ Rap Genius \u2013 Wale \u2013 The Soup [13] Tumblr \u2013 Posts tagged with 'No\
  \ Soup For You' [14] YTMND \u2013 No Soup For You [15] Facebook \u2013 No Soup For\
  \ You [16] The Original Soup Man \u2013 Home [17] The Original Soup Man \u2013 Al's\
  \ Rules [18] alt.tv.seinfeld \u2013 \"No Soup For You\" sound clip site! [19] Ted's\
  \ Seinfeld Page \u2013 Seinfeld Sound Clips [20] rec.sport.football.fantasy \u2013\
  \ Collusion question [21] alt.tv.star-trek.voyager \u2013 Think Tank (or \"NO SOUP\
  \ FOR YOU!!!\") [22] alt.music.tool \u2013 No Soup for You, Styx! [23] alt.holoworld.rpg.startrek\
  \ \u2013 USS:Hermes No soup for you! [24] alt.christnet.christianlife \u2013 No\
  \ Soup for You [25] Foolz Archive \u2013 NO SOUP FOR YOU! (NSFW) [26] Cheezburger\
  \ \u2013 Search results for \"no soup for you\" [27] Twitter \u2013 Tweet results\
  \ for #nosoupforyou [28] YTMND \u2013 Search results for \"no soup for you\" soup\
  \ nazi seinfield no soup for you Share Pin Related Entries 7 total Costanza.jpg\
  \ / George Costanz... Kramer, What's Going On In Th... I'm Shifting Into Soup Mode\
  \ Seinfeld Theme Song Parodies View All Related Entries Recent Images 35 total View\
  \ All Images Recent Videos 4 total View All Videos Sign up for our Newsletter Load\
  \ 11 Comments Comments 11 total 4 No Soup for You / Soup Nazi 63,415 4 35 11 Part\
  \ of a series on Seinfeld. [View Related Entries] Updated Dec 15, 2024 at 07:02PM\
  \ EST by LiterallyAustin. Added May 02, 2013 at 12:33AM EDT by Blue Screen (of Death).\
  \ Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the\
  \ image gallery, 'v' to view the video gallery, or 'r' to view a random entry. Meme\
  \ Status Confirmed Year 1995 Origin Seinfield Tags soup nazi, seinfield, no soup\
  \ for you Additional References Meme Generator Urban Dictionary Wikipedia About\
  \ \"No Soup For You\" or \"NO SOUP 4 U\" is a catchphrase that was initially uttered\
  \ in a 1995 episode of the American comedic sitcom Seinfeld. Online, the phrase\
  \ is often used in the context of message boards and forums in reply to other users\
  \ who have made requests or demands that are denied or cannot be fulfilled. Origin\
  \ In the November 2nd, 1995 Seinfeld episode \"The Soup Nazi\"[1], the main characters\
  \ check out a local soup shop with an incredibly strict chef (played by Larry Thomas[6])\
  \ who is nicknamed \"Soup Nazi\" for his rules about ordering. After Elaine Benes\
  \ (played by Julia Louis-Dreyfus) attempts to subvert his ordering procedure, the\
  \ chef utters the statement, banning her from the shop for an entire year. Thomas'\
  \ character was inspired by a real-life soup vendor named Ali \"Al\" Yeganeh[16]\
  \ whose Manhattan restaurant, Soup Kitchen International, had been notorious for\
  \ having strict ordering rules[17] since 1984. Spread Throughout the 1990s, the\
  \ quote and the character that spoke it was iconic in the Seinfeld fandom and wider\
  \ pop culture, spawning specific merchandise[11] with the quote. One of the earliest\
  \ mentions of the quote online appeared on August 10th, 1996, when Ted Weiman announced\
  \ to alt.tv.seinfeld[18] that he launched a \"No Soup For You\" soundclip site.[19]\
  \ In September 1996, the phrase was used on rec.sport.football.fantasy[20] in response\
  \ to a question about whether or not a poster should veto a fantasy football trade.\
  \ Between 1996 and 2003, the phrase was used in this declining manner on a number\
  \ of newsgroups including alt.tv.star-trek.voyager[21], alt.music.tool[22], alt.holoworld.rpg.startrek[23]\
  \ and alt.christnet.christianlife.[24] On April 27th, 2004, the first YTMND site[14]\
  \ referencing the Seinfeld episode was created, gaining more than 600 views as of\
  \ May 2013. Over the years, a handful of other sites with the title \"No Soup For\
  \ You\"[28] have been created, gaining anywhere from several hundred to six thousand\
  \ views. In 2008, the phrase was mentioned on 4chan[25] for the first time in a\
  \ thread on /a/ (Anime and Manga) discussing Rukia Kuchiki of the series Bleach.\
  \ On November 14th, 2009, the first Facebook[15] fan page dedicated to the phrase\
  \ launched, accruing more than 9,100 likes as of May 2013. References to the quote\
  \ have appeared in image macros on a number of humor websites including Meme Center[7],\
  \ Funnyjunk[8], Cheezburger[26] and Funny Pictures Blog[10], as well as in a Tumblr\
  \ tag[13] and Twitter hashtag.[27] A Quickmeme[9] page utilizing a photo of Larry\
  \ Thomas as the Soup Nazi has 26 submissions as of May 2013, with captions primarily\
  \ relating to Reddit activities. Notable Examples Search Interest External References\
  \ [1] Wikipedia \u2013 The Soup Nazi [2] The Guardian \u2013 No Catchphrase for\
  \ you! [3] IMBD \u2013 The Soup Nazi [4] Soupnazi on Twitter [5] WikiSein \u2013\
  \ The Soup Nazi [6] RealSoupNazi.com [7] Memecenter \u2013 No Soup For You [8] Funnyjunk\
  \ \u2013 No Soup For You [9] QuickMeme \u2013 No Soup For You [10] Funny Pictures\
  \ Blog \u2013 No Soup For You [11] Amazon.com \u2013 No Soup For You Mens Tee [12]\
  \ Rap Genius \u2013 Wale \u2013 The Soup [13] Tumblr \u2013 Posts tagged with 'No\
  \ Soup For You' [14] YTMND \u2013 No Soup For You [15] Facebook \u2013 No Soup For\
  \ You [16] The Original Soup Man \u2013 Home [17] The Original Soup Man \u2013 Al's\
  \ Rules [18] alt.tv.seinfeld \u2013 \"No Soup For You\" sound clip site! [19] Ted's\
  \ Seinfeld Page \u2013 Seinfeld Sound Clips [20] rec.sport.football.fantasy \u2013\
  \ Collusion question [21] alt.tv.star-trek.voyager \u2013 Think Tank (or \"NO SOUP\
  \ FOR YOU!!!\") [22] alt.music.tool \u2013 No Soup for You, Styx! [23] alt.holoworld.rpg.startrek\
  \ \u2013 USS:Hermes No soup for you! [24] alt.christnet.christianlife \u2013 No\
  \ Soup for You [25] Foolz Archive \u2013 NO SOUP FOR YOU! (NSFW) [26] Cheezburger\
  \ \u2013 Search results for \"no soup for you\" [27] Twitter \u2013 Tweet results\
  \ for #nosoupforyou [28] YTMND \u2013 Search results for \"no soup for you\" Related\
  \ Entries 7 total Costanza.jpg / George Costanza Reaction Face Kramer, What's Going\
  \ On In There? I'm Shifting Into Soup Mode Seinfeld Theme Song Parodies You're Crying\
  \ From X / George Costanza Crying Jerry Seinfeld Kith Photoshoot I'm Not Ashamed\
  \ of My Body / History Recent Videos 4 total NO SOUP FOR YOU! No Soup for You /\
  \ Soup Nazi Uploaded by Blue Screen (of Death) NO SOUP FOR YOU!!!!!!! No Soup for\
  \ You / Soup Nazi Uploaded by Blue Screen (of Death) No soup for you No Soup for\
  \ You / Soup Nazi Uploaded by Blue Screen (of Death) Seinfeld - Soup Nazi - NO SOU...\
  \ No Soup for You / Soup Nazi Uploaded by Blue Screen (of Death) + Add a Video Recent\
  \ Images 35 total No Soup for You / Soup Nazi Uploaded by PMK2000 No Soup for You\
  \ / Soup Nazi Uploaded by amanda b. No Soup for You / Soup Nazi Uploaded by amanda\
  \ b. No Soup for You / Soup Nazi Uploaded by amanda b. No Soup for You / Soup Nazi\
  \ Uploaded by amanda b. No Soup for You / Soup Nazi Uploaded by amanda b. No Soup\
  \ for You / Soup Nazi Uploaded by Iran No Soup for You / Soup Nazi Uploaded by Iran\
  \ No Soup for You / Soup Nazi Uploaded by Mr. Sparkle No Soup for You / Soup Nazi\
  \ Uploaded by Mr. Sparkle No Soup for You / Soup Nazi Uploaded by Mr. Sparkle No\
  \ Soup for You / Soup Nazi Uploaded by Blue Screen (of Death) + Add an Image View\
  \ All Images Sign up for our Newsletter Top Comment Delete Sensitive Blue Screen\
  \ (of Death) May 02, 2013 at 05:14AM EDT It\u2019s never been huge. But it\u2019\
  s been around. Google image it and you will see what I mean. I remember seeing it\
  \ used on the first forums I posted on in 2002 so this is old. But it isn't dead\
  \ because the last time I saw it used was here on the KYM forums just recently (which\
  \ prompted me to start this). It has always been somewhat lingering But even if\
  \ all that is left is ancient internet fossils of a long dead meme. I still think\
  \ it should be put on record. +4 Reply + Add a Comment Comments (11) Display Comments\
  \ Add a Comment Top Entries This Month Meme Saika Kawakita Smile GIF Event Assassination\
  \ of UnitedHealthcare CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki\
  \ Sisters Culture Pornography Site Whisper View More Suggest a Change Edit History\
  \ Entry Editors (6) Blue Screen (of Death) Scrapbooker & Elocutionist & Media Bus\
  \ Boy opspe Historical Meme Historian Brad Digital Archaeologist & Treasurer & Pundit\
  \ & Gallery Housekeeper amanda b. Meme Librarian VanManner Sr. Entry Moderator Y\
  \ F Digital Archaeologist & Treasurer & Media Maid \u25BC + Request Editorship View\
  \ All Editors Today's Top Image Galleries Assassination of UnitedHealthcare CEO\
  \ Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing Digital Circus About\
  \ Our Story Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes\
  \ News Staff Contact Extras! Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/no-soup-for-you-soup-nazi
template_id: soup-nazi
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
