example:
- at least
- you tried
keywords:
- null
name: At Least You Tried
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "You Tried | Know Your Meme Hey! You must login or signup first!\
  \ Already a memeber? Login Now! Don't have an account? Sign up Now! Meme Encyclopedia\
  \ All Cultures Events People Sites Subcultures Videos Submit \u2192 Images Trending\
  \ Most Commented Most Favorited High Score Low Score Most Viewed All Templates Upload\
  \ an Image Articles News Explainers Collections Interviews Meme Insider Magazine\
  \ More Discord Newsletter Episodes Forums Meme Store Login Abstract user icon Memes\
  \ Categories Trending News Images Trending Images Videos Trending Videos Editorials\
  \ Meme Insider Magazine Newsletter Policies and Guidelines Meme Store Old site Login\
  \ Know Your Meme is the property of Literally Media \xA92024 Literally Media. All\
  \ Rights Reserved. This image Of Woman Confidently Strolling Through A Glass Panel\
  \ Has Been A Redraw Format Since 2021 Three Years Ago, This Boar's Head 'Exploded'\
  \ Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess Memes Turns Two Years\
  \ Old Today Phrase 'The Fridge Protects The Snacks' A Growing Favorite Among Pickup\
  \ Artist Influencers Jamie G, The Bosh British Charva, Has Taken Over TikTok With\
  \ His Signature 'Oh Cherie Amour' Sound Also Trending: Honey Extension Influencer\
  \ Scam Renegade Raider Copypasta Assassination of UnitedHealthcare CEO You Tried\
  \ Added 12 years ago / Updated 12 days ago Confirmed 431,383 View All 244 Images\
  \ Navigation About \u2022 Origin \u2022 Spread \u2022 Notable Examples \u2022 Search\
  \ Interest \u2022 External References \u2022 Recent Images \u2022 Recent Videos\
  \ About \"You Tried\" is a reaction image used to pity someone else's failed attempt\
  \ at humor or insult, oftentimes sarcastically in similar vein to usage of \"Seems\
  \ Legit\". On Tumblr, this is typically presented as a clip art of a golden star\
  \ captioned with the phrase. Origin The practice of rewarding a job well done with\
  \ motivational stickers or stamps can be traced back to its usage in elementary\
  \ schools to award students for completing an assignment or good behaviors. On the\
  \ web, clip art images of gold star have been used as genuine complements towards\
  \ quality user submissions as early as in January 2011 and its sarcastic usage on\
  \ Tumblr reportedly began sometime in May 2012.[citation needed] Precursor: At Least\
  \ You Tried While it is difficult to pinpoint the origin of its online usage, the\
  \ phrase \"at least you tried\" has been paired with FAIL image macros and cute\
  \ animal photos on various humor communities like eBaumsworld[3], Threadbombing[4]\
  \ and Reddit[1] as early as July 2008, including one of a capsized military tank\
  \ and a photo of two wolf pups. Spread On Tumblr[6], the Gold Star reaction image\
  \ is typically added at the end of a reblogged post to point out its inadequacy\
  \ or shortcoming. Since gaining prominence through its usage on the site[6][7][8],\
  \ the Gold Star has spawned numerous variations of the phrase \"You Tried\" as well\
  \ as negative responses from other Tumblr users regarding its allegedly excessive\
  \ usage. The Gold Star reaction image also became associated with Tumblr's Homestuck\
  \ webcomic fandom after it was paired with a poorly drawn image[9] of Homestuck\
  \ characters published on June 12th, 2012. Notable Examples There are numerous derivatives\
  \ of the Gold Star reaction image circulating on Tumblr, many of them bearing other\
  \ messages like \"You Didn't Try\" or \"You Died.\" Participation Award In November\
  \ 2015, a website called Awards Against Humanity[11] began selling \"Participation\
  \ Award\" trophies with the phrase \"You Tried\" engraved on the brass plate. The\
  \ product, which can be purchased for $14.95 (USD) comes with a \"Certificate of\
  \ Participation\" document, is described as a practical joke one can play on friends\
  \ in a similar vein to the Ship Your Enemies Glitter project. Search Interest External\
  \ References [1] Reddit \u2013 At least you tried [2] Reddit \u2013 Rooney Consoling\
  \ Chicharito [3] eBaumsworld \u2013 At Least You Tried [4] Threadbombing \u2013\
  \ At Least You Tried [5] Tumblr \u2013 Search Results for You Tried [6] Tumblr \u2013\
  \ Untitled [7] Tumblr \u2013 Untitled [8] Tumblr \u2013 Untitled [9] MS Paint Adventures\
  \ \u2013 Dirk, This is Us [10] Tumblr \u2013 Oops I Did a Thing I Have No Shame\
  \ [11] Awards Against Humanity \u2013 Participation Award catchphrase tumblr reaction\
  \ slangs of 2012 Share Pin Recent Images 244 total View All Images Recent Videos\
  \ 3 total View All Videos Sign up for our Newsletter Load 30 Comments Comments 30\
  \ total 105 You Tried 431,383 3 244 30 Updated Dec 11, 2024 at 12:43PM EST by LiterallyAustin.\
  \ Added Jun 12, 2012 at 08:24PM EDT by Surprise Bit. Like us on Facebook! Like 1.8M\
  \ Share Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the\
  \ video gallery, or 'r' to view a random entry. Meme Status Confirmed Year 2012\
  \ Origin Tumblr Tags catchphrase, tumblr, reaction, slangs of 2012 About \"You Tried\"\
  \ is a reaction image used to pity someone else's failed attempt at humor or insult,\
  \ oftentimes sarcastically in similar vein to usage of \"Seems Legit\". On Tumblr,\
  \ this is typically presented as a clip art of a golden star captioned with the\
  \ phrase. Origin The practice of rewarding a job well done with motivational stickers\
  \ or stamps can be traced back to its usage in elementary schools to award students\
  \ for completing an assignment or good behaviors. On the web, clip art images of\
  \ gold star have been used as genuine complements towards quality user submissions\
  \ as early as in January 2011 and its sarcastic usage on Tumblr reportedly began\
  \ sometime in May 2012.[citation needed] Precursor: At Least You Tried While it\
  \ is difficult to pinpoint the origin of its online usage, the phrase \"at least\
  \ you tried\" has been paired with FAIL image macros and cute animal photos on various\
  \ humor communities like eBaumsworld[3], Threadbombing[4] and Reddit[1] as early\
  \ as July 2008, including one of a capsized military tank and a photo of two wolf\
  \ pups. Spread On Tumblr[6], the Gold Star reaction image is typically added at\
  \ the end of a reblogged post to point out its inadequacy or shortcoming. Since\
  \ gaining prominence through its usage on the site[6][7][8], the Gold Star has spawned\
  \ numerous variations of the phrase \"You Tried\" as well as negative responses\
  \ from other Tumblr users regarding its allegedly excessive usage. The Gold Star\
  \ reaction image also became associated with Tumblr's Homestuck webcomic fandom\
  \ after it was paired with a poorly drawn image[9] of Homestuck characters published\
  \ on June 12th, 2012. Notable Examples There are numerous derivatives of the Gold\
  \ Star reaction image circulating on Tumblr, many of them bearing other messages\
  \ like \"You Didn't Try\" or \"You Died.\" Participation Award In November 2015,\
  \ a website called Awards Against Humanity[11] began selling \"Participation Award\"\
  \ trophies with the phrase \"You Tried\" engraved on the brass plate. The product,\
  \ which can be purchased for $14.95 (USD) comes with a \"Certificate of Participation\"\
  \ document, is described as a practical joke one can play on friends in a similar\
  \ vein to the Ship Your Enemies Glitter project. Search Interest External References\
  \ [1] Reddit \u2013 At least you tried [2] Reddit \u2013 Rooney Consoling Chicharito\
  \ [3] eBaumsworld \u2013 At Least You Tried [4] Threadbombing \u2013 At Least You\
  \ Tried [5] Tumblr \u2013 Search Results for You Tried [6] Tumblr \u2013 Untitled\
  \ [7] Tumblr \u2013 Untitled [8] Tumblr \u2013 Untitled [9] MS Paint Adventures\
  \ \u2013 Dirk, This is Us [10] Tumblr \u2013 Oops I Did a Thing I Have No Shame\
  \ [11] Awards Against Humanity \u2013 Participation Award Recent Videos 3 total\
  \ you tried You Tried Uploaded by Nkil Incendio Portezuelo You Tried Uploaded by\
  \ Brad In the Hall of You Tried You Tried Uploaded by Turd le + Add a Video Recent\
  \ Images 244 total You Tried Uploaded by omeremin You Tried Uploaded by andcallmeshirley\
  \ You Tried Uploaded by andcallmeshirley You Tried Uploaded by Owen You Tried Uploaded\
  \ by Owen You Tried Uploaded by Triplem You Tried Uploaded by leetyeet You Tried\
  \ Uploaded by ooftown You Tried Uploaded by dacinch8 You Tried Uploaded by kiddodangeroustheemo\
  \ You Tried Uploaded by Canadiancookie You Tried Uploaded by stickteam + Add an\
  \ Image View All Images Sign up for our Newsletter Top Comments Delete Sensitive\
  \ Surprise Bit Jun 12, 2012 at 08:24PM EDT inb4: +38 Reply Delete Sensitive Necro910:\
  \ That Krieger Dude Jun 18, 2012 at 10:16PM EDT I signed up to Tumblr to follow\
  \ various ask-blogs just in time to see this meme be born +27 Reply + Add a Comment\
  \ Comments (30) Display Comments Add a Comment Top Entries This Month Meme Saika\
  \ Kawakita Smile GIF Event Assassination of UnitedHealthcare CEO Person Luigi Mangione\
  \ UHC CEO Shooter Subculture The Ki Sisters Culture Pornography Site Whisper View\
  \ More Suggest a Change Edit History Entry Editors (4) Surprise Bit Tumblrologist\
  \ MDFification ??? opspe Historical Meme Historian Brad Digital Archaeologist &\
  \ Treasurer & Pundit & Gallery Housekeeper + Request Editorship View All Editors\
  \ Today's Top Image Galleries Assassination of UnitedHealthcare CEO Squirrel Girl\
  \ (Doreen Green) Team Fortress 2 The Amazing Digital Circus About Our Story Site\
  \ Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes News Staff\
  \ Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/you-tried
template_id: tried
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
