name: At Least You Tried
source: http://knowyourmeme.com/memes/you-tried
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- at least
- you tried
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About "You Tried" is a reaction image used to pity someone else''s
  failed attempt at humor or insult, oftentimes sarcastically in similar vein to usage
  of "Seems Legit". On Tumblr, this is typically presented as a clip art of a golden
  star captioned with the phrase. Origin The practice of rewarding a job well done
  with motivational stickers or stamps can be traced back to its usage in elementary
  schools to award students for completing an assignment or good behaviors. On the
  web, clip art images of gold star have been used as genuine complements towards
  quality user submissions as early as in January 2011 and its sarcastic usage on
  Tumblr reportedly began sometime in May 2012.[citation needed] Precursor: At Least
  You Tried While it is difficult to pinpoint the origin of its online usage, the
  phrase "at least you tried" has been paired with FAIL image macros and cute animal
  photos on various humor communities like eBaumsworld[3], Threadbombing[4] and Reddit[1]
  as early as July 2008, including one of a capsized military tank and a photo of
  two wolf pups. Spread On Tumblr[6], the Gold Star reaction image is typically added
  at the end of a reblogged post to point out its inadequacy or shortcoming. Since
  gaining prominence through its usage on the site[6][7][8], the Gold Star has spawned
  numerous variations of the phrase "You Tried" as well as negative responses from
  other Tumblr users regarding its allegedly excessive usage. The Gold Star reaction
  image also became associated with Tumblr''s Homestuck webcomic fandom after it was
  paired with a poorly drawn image[9] of Homestuck characters published on June 12th,
  2012. Notable Examples There are numerous derivatives of the Gold Star reaction
  image circulating on Tumblr, many of them bearing other messages like "You Didn''t
  Try" or "You Died." Participation Award In November 2015, a website called Awards
  Against Humanity[11] began selling "Participation Award" trophies with the phrase
  "You Tried" engraved on the brass plate. The product, which can be purchased for
  $14.95 (USD) comes with a "Certificate of Participation" document, is described
  as a practical joke one can play on friends in a similar vein to the Ship Your Enemies
  Glitter project. Search Interest External References [1] Reddit – At least you tried
  [2] Reddit – Rooney Consoling Chicharito [3] eBaumsworld – At Least You Tried [4]
  Threadbombing – At Least You Tried [5] Tumblr – Search Results for You Tried [6]
  Tumblr – Untitled [7] Tumblr – Untitled [8] Tumblr – Untitled [9] MS Paint Adventures
  – Dirk, This is Us [10] Tumblr – Oops I Did a Thing I Have No Shame [11] Awards
  Against Humanity – Participation Award'
aside_content: MemeStatusConfirmedYear2012OriginTumblrTagscatchphrase,tumblr,reaction,slangs
  of 2012
added_at: '2012-06-12T20:24:22-04:00'
