name: Good Guy Greg
source: http://knowyourmeme.com/memes/good-guy-greg
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- sleeps on your couch
- makes breakfast
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Good Guy Greg (GGG) is an advice animal image macro series
  featuring a photo of a square-jawed man smiling at the camera with a marijuana cigarette
  in his mouth. As the antithesis of Scumbag Steve, the captions generally depict
  the character as kind, generous or empathetic to other people. Origin Good Guy Greg
  is rumored to have started on 4chan''s /b/ (random) board but an archived thread
  has yet to be found. On April 26th, 2011, the template photo was uploaded to the
  image remixing site Canvas[1] with the description "This is Good Guy Greg." The
  Canvas thread received over 570 remix replies within 11 months. Precursors On February
  3rd, 2011, an image macro called "Generous Jeff" was posted to the marijuana enthusiast
  subreddit /r/trees[8], which depicted the character as a lovable stoner (shown left).
  On February 9th, a Scumbag Steve spin-off called "Cool Guy Steve" (shown right)
  appeared on Reddit[7], shortly after he was interviewed by Know Your Meme. Spread
  On May 19th, 2011, the first Good Guy Greg Quickmeme[2] image macro was uploaded
  with the caption "Sleeps on your couch / makes breakfast." The same day, the macro
  was posted to the /r/AdviceAnimals[3] subreddit by user RsonW, which reached the
  front page receiving 1,717 up votes prior to being archived. On June 12th, a compilation
  of GGG examples were posted to the list-making website Ranker.[16] On June 14th,
  the first Urban Dictionary[15] definition for "Good Guy Greg" was submitted by user
  DrDragun, identifying the character as an Internet meme on 4chan and Reddit. The
  advice animal template eventually reached 4chan[23] with the earliest known archived
  thread dating to October 6th. On October 14th, the “F--k Yeah Good Guy Greg”[17]
  Tumblr blog was created, curating 63 image macros in six months. On October 30th,
  the Internet humor site BuzzFeed[18] published a compilation of notable GGG examples.
  The meme has continued to spread on sites like FunnyJunk[4], Tumblr[5] and Memebase.[14]
  As of April 19th, 2011, a Facebook page for "Good Guy Greg" has over 28,500 likes,
  a Quickmeme[12] page has received over 52,500 submissions and a Meme Generator[6]
  page has over 89,000 items. Notable Derivatives Derivative: Good Guy Grog On March
  26th, 2012, Redditor partyfunk8 posted an image macro to the /r/AdviceAnimals subreddit
  featuring GGG''s face edited on to a photo of a caveman with the caption "Takes
  girl back to his cave / doesn''t club her" (shown left). The post reached the front
  page and received over 4,800 up votes in 23 days. On April 4th, BuzzFeed published
  a compilation of notable Good Guy Grog examples. Identity On August 10th, 2011,
  Redditor fishieman posted an AMA thread titled "Reddit, I passed the 6 week challenge
  and crewed along side GGG. Iama a commercial fisherman, ama."[9] He included several
  pictures of the man he claims is the real GGG. Several users have disputed that
  this is actually the real GGG, cited several physical differences between the men
  in the photos. On January 11th, 2012, a man posted to 4chan''s[22] /b/ board claiming
  to be the real Good Guy Greg. Many users were skeptical, noting several facial characteristics
  that did not match the original GGG photo. Template Search Interest External References
  [1] Canvas (via Wayback Machine) – #4chan [2] Quickmeme – Good Guy Greg [3] Reddit
  – Good Guy Greg stays the night [4] FunnyJunk – Good Guy Greg (must be logged in)
  [5] Tumblr – #good guy greg [6] Memegenerator – Good Guy Greg [7] Reddit – Steve''s
  Last Act of Scumbaggery [8] Reddit – Generous Jeff [9] Reddit – Reddit, I passed
  the 6 week challenge and crewed along side Good Guy Greg. Iama a commercial fisherman,
  ama [10] Reddit – The original Good Guy Greg [11] Wikipedia – Jonas Salk [12] Quickmeme
  – Good Guy Greg [13] Facebook – Good Guy Greg [14] Memebase – Good Guy Greg [15]
  Urban Dictionary – Good Guy Greg [16] Ranker – The Very Best of Good Guy Greg [17]
  Tumblr – F--k Yeah Good Guy Greg [18] BuzzFeed – The Best of Good Guy Greg [19]
  Reddit – Good Guy Grog [20] Quickmeme – Good Guy Grog [21] BuzzFeed – The Best of
  the Good Guy Grog Meme [22] Chanarchive – irl good guy greg [23] Chanarchive – if
  I were steve jobs'
aside_content: MemeStatusConfirmedYear2011Origin4chanTagsnotables of 2011,ggg,stoner
  humor,social stereotype,rsonw,drdragun,partyfunk8,fishiemanAdditional ReferencesMeme
  Generator
added_at: '2011-04-26T11:18:03-04:00'
