example:
- does testing
- in production
keywords:
- null
name: Insanity Wolf
overlay:
- angle: 0.0
  center_x: 0.505
  center_y: 0.515
  scale: 0.525
scraped_content: "Insanity Wolf | Know Your Meme Hauu! You must login or signup first!\
  \ Already a memeber? Login Now! Don't have an account? Sign up Now! Meme Encyclopedia\
  \ All Cultures Events People Sites Subcultures Videos Submit \u2192 Images Trending\
  \ Most Commented Most Favorited High Score Low Score Most Viewed All Templates Upload\
  \ an Image Articles News Explainers Collections Interviews Meme Insider Magazine\
  \ More Discord Newsletter Episodes Forums Meme Store Login Abstract user icon Memes\
  \ Categories Trending News Images Trending Images Videos Trending Videos Editorials\
  \ Meme Insider Magazine Newsletter Policies and Guidelines Meme Store Old site Login\
  \ Know Your Meme is the property of Literally Media \xA92024 Literally Media. All\
  \ Rights Reserved. This image Of Woman Confidently Strolling Through A Glass Panel\
  \ Has Been A Redraw Format Since 2021 Three Years Ago, This Boar's Head 'Exploded'\
  \ Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess Memes Turns Two Years\
  \ Old Today Phrase 'The Fridge Protects The Snacks' A Growing Favorite Among Pickup\
  \ Artist Influencers Jamie G, The Bosh British Charva, Has Taken Over TikTok With\
  \ His Signature 'Oh Cherie Amour' Sound Also Trending: Honey Extension Influencer\
  \ Scam Renegade Raider Copypasta Assassination of UnitedHealthcare CEO Insanity\
  \ Wolf Added 15 years ago / Updated 8 days ago This entry contains content that\
  \ may be considered sensitive to some viewers. Confirmed 1,712,547 Part of a series\
  \ on Advice Animals. [View Related Entries] [View Related Sub-entries] WARNING:\
  \ The text in the following image macros contain extreme profanity. Navigation About\
  \ \u2022 Before Memegenerator \u2022 Derivatives within Memegenerator \u2022 External\
  \ References \u2022 Recent Images \u2022 Recent Videos About Insanity Wolf is like\
  \ the mentally disturbed cousin of Courage Wolf and is placed in theGod Tier category\
  \ on Memegenerator.net. While Courage Wolf often encourages people to overcome life's\
  \ obstacles, Insanity wolf tells his viewers to rape, kill, and commit other acts\
  \ of insanity. There is even a Facebook app for Insanity Wolf. Before Memegenerator\
  \ Although the Insanity Wolf meme began in 2009, the wolf image from which this\
  \ meme is derived has been appearing online since at least 2006. On October 21st,\
  \ 2006, YTMND user deathtoll5000x created OMGWTFHOLYSHI-! (WARNING: loud volume).\
  \ This YTMND has under 800 views and is not responsible for popularizing the image.\
  \ The image also appears on vivcam6300's Flickr image stream, posted October 21st,\
  \ 2007 and labeled \"inter net pic\" The image has also been used in a 1999 printing\
  \ of Sir Arthur Conan Doyle's The Hound of the Baskervilles. A TinEye Image Search\
  \ shows that this fierce wolf has been used as a popular forum avatar for a number\
  \ of years. Given the immense presence of this photo and the different ways it has\
  \ been used, it is likely that it is a commonly available piece of stock photography.\
  \ Derivatives within Memegenerator Insanity Scene Wolf, currently in the Proper\
  \ Tier. SCENE WOLF, currently in the Meh Tier. External References Memebase single\
  \ character image macro advice dog Share Pin Related Entries 115 total Ermahgerd\
  \ Overly Attached Girlfriend Scumbag Steve Good Guy Greg View All Related Entries\
  \ Sub-entries 2 total Scene Wolf Baby Insanity Wolf Recent Images 443 total View\
  \ All Images Recent Videos 3 total View All Videos Sign up for our Newsletter Load\
  \ 72 Comments Comments 72 total 171 Insanity Wolf 1,712,547 3 443 72 Part of a series\
  \ on Advice Animals. [View Related Entries] [View Related Sub-entries] Updated Dec\
  \ 15, 2024 at 03:10PM EST by LiterallyAustin. Added Nov 23, 2009 at 05:53AM EST\
  \ by Vorpalsword. Like us on Facebook! Like 1.8M Share Save Tweet PROTIP: Press\
  \ 'i' to view the image gallery, 'v' to view the video gallery, or 'r' to view a\
  \ random entry. This entry contains content that may be considered sensitive to\
  \ some viewers. Meme Status Confirmed Badges: Sensitive Year 2009 Origin 4chan Tags\
  \ single character image macro, advice dog Additional References Encyclopedia Dramatica\
  \ Meme Generator Urban Dictionary WARNING: The text in the following image macros\
  \ contain extreme profanity. About Insanity Wolf is like the mentally disturbed\
  \ cousin of Courage Wolf and is placed in theGod Tier category on Memegenerator.net.\
  \ While Courage Wolf often encourages people to overcome life's obstacles, Insanity\
  \ wolf tells his viewers to rape, kill, and commit other acts of insanity. There\
  \ is even a Facebook app for Insanity Wolf. Before Memegenerator Although the Insanity\
  \ Wolf meme began in 2009, the wolf image from which this meme is derived has been\
  \ appearing online since at least 2006. On October 21st, 2006, YTMND user deathtoll5000x\
  \ created OMGWTFHOLYSHI-! (WARNING: loud volume). This YTMND has under 800 views\
  \ and is not responsible for popularizing the image. The image also appears on vivcam6300's\
  \ Flickr image stream, posted October 21st, 2007 and labeled \"inter net pic\" The\
  \ image has also been used in a 1999 printing of Sir Arthur Conan Doyle's The Hound\
  \ of the Baskervilles. A TinEye Image Search shows that this fierce wolf has been\
  \ used as a popular forum avatar for a number of years. Given the immense presence\
  \ of this photo and the different ways it has been used, it is likely that it is\
  \ a commonly available piece of stock photography. Derivatives within Memegenerator\
  \ Insanity Scene Wolf, currently in the Proper Tier. SCENE WOLF, currently in the\
  \ Meh Tier. External References Memebase Related Entries 115 total Ermahgerd Overly\
  \ Attached Girlfriend Scumbag Steve Good Guy Greg Ridiculously Photogenic Guy Bad\
  \ Luck Brian Philosoraptor Annoying Facebook Girl The Most Interesting Man in the\
  \ World Socially Awkward Penguin Bear Grylls / Better Drink My Own Piss Successful\
  \ Black Man View All Related Entries Sub-entries 2 total Scene Wolf Baby Insanity\
  \ Wolf Recent Videos 3 total INSANITY WOLF 2 Insanity Wolf Uploaded by Trilandian\
  \ How Insanity Wolf Killed Chri... Insanity Wolf Uploaded by High Five Ghost ANIMEME\
  \ - Insanity Wolf Insanity Wolf Uploaded by Whales Are cool + Add a Video Recent\
  \ Images 443 total Insanity Wolf Uploaded by Reddit Moments Insanity Wolf Uploaded\
  \ by PrinnyFreak Insanity Wolf Uploaded by Y F Insanity Wolf Uploaded by Wambamsamman\
  \ Insanity Wolf Uploaded by Eodraconis Rexus Insanity Wolf Uploaded by Luigifan\
  \ Insanity Wolf Uploaded by Wambamsamman Insanity Wolf Uploaded by Wambamsamman\
  \ Insanity Wolf Uploaded by Wambamsamman Insanity Wolf Uploaded by Wambamsamman\
  \ Insanity Wolf Uploaded by Wambamsamman Insanity Wolf Uploaded by Hypercat-Z +\
  \ Add an Image View All Images Sign up for our Newsletter Top Comments Delete Sensitive\
  \ Fenris Jul 09, 2011 at 02:29AM EDT Read courage wolf to be inspired Read insanity\
  \ wolf to plan your day +19 Reply Delete Sensitive cuthulhu4president Jan 29, 2012\
  \ at 11:35PM EST someone tries to deadpool this meme? THROW THEIR BODY IN THE DEADPOOL!!!!\
  \ +8 Reply + Add a Comment Comments (72) Display Comments Add a Comment Top Entries\
  \ This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (9) Vorpalsword\
  \ Sleuth Captain Blubber Database Moderator & Tikibar Management Chris Menning Digital\
  \ Archaeologist & Archivist & Pundit & Early Adopter (#8) Brad Digital Archaeologist\
  \ & Treasurer & Pundit & Gallery Housekeeper Tomberry Database Moderator & French\
  \ Specialist & Pony Hater Don Administrator & Meme Daddy Hiroman Digital Archaeologist\
  \ & Cataloger & Pundit SabrinaTibbetts Memepuff shevyrolet Digital Archaeologist\
  \ & Treasurer & Media Bus Boy \u25BC + Request Editorship View All Editors Today's\
  \ Top Image Galleries Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen\
  \ Green) Team Fortress 2 The Amazing Digital Circus About Our Story Site Rules Policies\
  \ and Guidelines Credits Contact Meme DB Memes Episodes News Staff Contact Extras!\
  \ Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/insanity-wolf
template_id: iw
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
