name: Insanity Wolf
source: http://knowyourmeme.com/memes/insanity-wolf
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- does testing
- in production
overlay:
- center_x: 0.505
  center_y: 0.515
  angle: 0.0
  scale: 0.525
scraped_content: 'WARNING: The text in the following image macros contain extreme
  profanity. About Insanity Wolf is like the mentally disturbed cousin of Courage
  Wolf and is placed in theGod Tier category on Memegenerator.net. While Courage Wolf
  often encourages people to overcome life''s obstacles, Insanity wolf tells his viewers
  to rape, kill, and commit other acts of insanity. There is even a Facebook app for
  Insanity Wolf. Before Memegenerator Although the Insanity Wolf meme began in 2009,
  the wolf image from which this meme is derived has been appearing online since at
  least 2006. On October 21st, 2006, YTMND user deathtoll5000x created OMGWTFHOLYSHI-!
  (WARNING: loud volume). This YTMND has under 800 views and is not responsible for
  popularizing the image. The image also appears on vivcam6300''s Flickr image stream,
  posted October 21st, 2007 and labeled "inter net pic" The image has also been used
  in a 1999 printing of Sir Arthur Conan Doyle''s The Hound of the Baskervilles. A
  TinEye Image Search shows that this fierce wolf has been used as a popular forum
  avatar for a number of years. Given the immense presence of this photo and the different
  ways it has been used, it is likely that it is a commonly available piece of stock
  photography. Derivatives within Memegenerator Insanity Scene Wolf, currently in
  the Proper Tier. SCENE WOLF, currently in the Meh Tier. External References Memebase'
aside_content: MemeStatusConfirmedBadges:SensitiveYear2009Origin4chanTagssingle character
  image macro,advice dogAdditional ReferencesEncyclopedia DramaticaMeme GeneratorUrban
  Dictionary
added_at: '2009-11-23T05:53:55-05:00'
