example:
- what if the CIA invented dinosaurs
- to discourage time travel?
keywords:
- null
name: Conspiracy Keanu
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Conspiracy Keanu | Know Your Meme Hauu! You must login or signup\
  \ first! Already a memeber? Login Now! Don't have an account? Sign up Now! Meme\
  \ Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Conspiracy Keanu Added 13 years ago / Updated 17 days ago Confirmed 1,328,121\
  \ Part of a series on Keanu Reeves. [View Related Entries] View All 279 Images Navigation\
  \ About \u2022 Origin \u2022 Spread \u2022 Notable Examples \u2022 Derivatives \u2022\
  \ Template \u2022 Search Interest \u2022 External References \u2022 Recent Images\
  \ \u2022 Recent Videos About Conspiracy Keanu is an advice animal image macro series\
  \ featuring a still photo of the Hollywood actor Keanu Reeves wearing a frightened\
  \ expression from the 1989 comedy film Bill and Ted\u2019s Excellent Adventure.\
  \ The images are typically captioned with paranoid conjectures and absurdly philosophical\
  \ questions that bear similarities to the Paranoid Parrot, Philosoraptor and Stoner\
  \ Dog advice animal series. Origin On December 11th, 2008, New York Magazine's Vulture\
  \ Blog[3] published a slideshow titled \u201CVulture\u2019s Complete Field Guide\
  \ to the Facial Expressions of Keanu Reeves\u201D that consisted of screen captures\
  \ of Reeves from various films. The 22nd slide featured an image of Ted (played\
  \ by Keanu Reeves) taken from the 1989 comedy film Bill & Ted\u2019s Excellent Adventure\
  \ in a scene where Ted is being chased by medieval knights. The image was subsequently\
  \ used as a reaction face with the earliest known instance occurring on the Fark[1]\
  \ forums (shown left) on September 17th, 2010. The first image macro (shown right)\
  \ was posted to the r/funny subreddit[2] with the caption \u201CWhat if we CAN breathe\
  \ in space / and they just don\u2019t want us to escape\u201D on June 2nd, 2011,\
  \ which accumulated 6,847 up votes prior to being archived. Spread An instance with\
  \ the caption \"What if all the specs we see in the light / are all miniature universes?\"\
  \ was submitted to the humor site FunnyJunk[11] on September 24th, 2011. Beginning\
  \ in November 2011, Conspiracy Keanu image macros spread on a larger scale with\
  \ the launch of a Facebook fan page[10] on November 19th and compilations were posted\
  \ to various sites including BuzzFeed[13], Pleated Jeans[14] and the web culture\
  \ blog UpRoxx[5] within the next few days. On December 15th, the web culture blog\
  \ Smosh[16] published a \"Best of Conspiracy Keanu\" post. The domain for the single\
  \ topic blog ConspiracyKeanu.com[12] was registered on December 18th. Additionally,\
  \ derivatives have been posted to FunnyJunk[6], Tumblr[7], Troll.me[9] and Reddit.[8]\
  \ As of April 2012, the Quickmeme[4] page has 37,458 submissions and the Facebook[15]\
  \ page has 1,421 likes. Notable Examples Derivatives On Quickmeme, searching for\
  \ 'conspiracy' results in numerous spin-offs.[17] These vary between humans and\
  \ animals, to fictional characters, with the text on the image macro matching to\
  \ the image. Even though most of these only generated a few images and didn't gain\
  \ much popularity, more successful versions are Conspiracy Cat[18] and various instances\
  \ of Conspiracry Lyra[19] [20]. Template Search Interest External References [1]\
  \ Fark \u2013 China plans to lead world in eco-friendly cars. Haven't they lead\
  \ enough? [2] Reddit \u2013 Conspiracy Keanu [3] NYMag \u2013 Vulture\u2019s Complete\
  \ Field Guide to the Facial Expressions of Keanu Reeves [4] Quickmeme \u2013 Conspiracy\
  \ Keanu [5] UpRoxx \u2013 Conspiracy Keanu Puts A Meme To What Keanu Reeves Is Thinking\
  \ [6] FunnyJunk (must login to run the search) \u2013 conspiracy keanu [7] Tumblr\
  \ \u2013 #conspiracy keanu [8] Reddit \u2013 conspiracy keanu [9] Troll.me via Way\
  \ Back Machine \u2013 conspiracy keanu [10] Facebook \u2013 Conspiracy Keanu [11]\
  \ Funny Junk \u2013 What If [12] ConspiracyKeanu.com \u2013 Conspiracy Keanu [13]\
  \ BuzzFeed \u2013 The 21 Best Conspiracy Keanu Meme Images [14] Pleated Jeans \u2013\
  \ Best of the Conspiracy Keanu Meme [15] Facebook \u2013 Conspiracy Keanu [16] Smosh\
  \ \u2013 Best of Conspiracy Keanu! [17] Quickmeme \u2013 Search Results 'Conspiracy'\
  \ [18] Quickmeme \u2013 Conspiracy Cat [19] Quickmeme \u2013 Conspiracy Lyra 1 [20]\
  \ Quickmeme \u2013 Conspiracy Lyra 2 conspiracy 420 keanu reeves stoner humor Share\
  \ Pin Related Entries 16 total Sad Keanu Happy Keanu Mini Keanu Reeves You're Breathtaking\
  \ View All Related Entries Recent Images 279 total View All Images Recent Videos\
  \ 1 total View All Videos Sign up for our Newsletter Load 45 Comments Comments 45\
  \ total 134 Conspiracy Keanu 1,328,121 1 279 45 Part of a series on Keanu Reeves.\
  \ [View Related Entries] Updated Dec 06, 2024 at 04:44PM EST by LiterallyAustin.\
  \ Added Nov 19, 2011 at 07:08AM EST by Heather. Like us on Facebook! Like 1.8M Share\
  \ Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the video\
  \ gallery, or 'r' to view a random entry. Meme Status Confirmed Type: Image Macro\
  \ Year 2011 Origin Reddit Tags conspiracy, 420, keanu reeves, stoner humor Additional\
  \ References Meme Generator About Conspiracy Keanu is an advice animal image macro\
  \ series featuring a still photo of the Hollywood actor Keanu Reeves wearing a frightened\
  \ expression from the 1989 comedy film Bill and Ted\u2019s Excellent Adventure.\
  \ The images are typically captioned with paranoid conjectures and absurdly philosophical\
  \ questions that bear similarities to the Paranoid Parrot, Philosoraptor and Stoner\
  \ Dog advice animal series. Origin On December 11th, 2008, New York Magazine's Vulture\
  \ Blog[3] published a slideshow titled \u201CVulture\u2019s Complete Field Guide\
  \ to the Facial Expressions of Keanu Reeves\u201D that consisted of screen captures\
  \ of Reeves from various films. The 22nd slide featured an image of Ted (played\
  \ by Keanu Reeves) taken from the 1989 comedy film Bill & Ted\u2019s Excellent Adventure\
  \ in a scene where Ted is being chased by medieval knights. The image was subsequently\
  \ used as a reaction face with the earliest known instance occurring on the Fark[1]\
  \ forums (shown left) on September 17th, 2010. The first image macro (shown right)\
  \ was posted to the r/funny subreddit[2] with the caption \u201CWhat if we CAN breathe\
  \ in space / and they just don\u2019t want us to escape\u201D on June 2nd, 2011,\
  \ which accumulated 6,847 up votes prior to being archived. Spread An instance with\
  \ the caption \"What if all the specs we see in the light / are all miniature universes?\"\
  \ was submitted to the humor site FunnyJunk[11] on September 24th, 2011. Beginning\
  \ in November 2011, Conspiracy Keanu image macros spread on a larger scale with\
  \ the launch of a Facebook fan page[10] on November 19th and compilations were posted\
  \ to various sites including BuzzFeed[13], Pleated Jeans[14] and the web culture\
  \ blog UpRoxx[5] within the next few days. On December 15th, the web culture blog\
  \ Smosh[16] published a \"Best of Conspiracy Keanu\" post. The domain for the single\
  \ topic blog ConspiracyKeanu.com[12] was registered on December 18th. Additionally,\
  \ derivatives have been posted to FunnyJunk[6], Tumblr[7], Troll.me[9] and Reddit.[8]\
  \ As of April 2012, the Quickmeme[4] page has 37,458 submissions and the Facebook[15]\
  \ page has 1,421 likes. Notable Examples Derivatives On Quickmeme, searching for\
  \ 'conspiracy' results in numerous spin-offs.[17] These vary between humans and\
  \ animals, to fictional characters, with the text on the image macro matching to\
  \ the image. Even though most of these only generated a few images and didn't gain\
  \ much popularity, more successful versions are Conspiracy Cat[18] and various instances\
  \ of Conspiracry Lyra[19] [20]. Template Search Interest External References [1]\
  \ Fark \u2013 China plans to lead world in eco-friendly cars. Haven't they lead\
  \ enough? [2] Reddit \u2013 Conspiracy Keanu [3] NYMag \u2013 Vulture\u2019s Complete\
  \ Field Guide to the Facial Expressions of Keanu Reeves [4] Quickmeme \u2013 Conspiracy\
  \ Keanu [5] UpRoxx \u2013 Conspiracy Keanu Puts A Meme To What Keanu Reeves Is Thinking\
  \ [6] FunnyJunk (must login to run the search) \u2013 conspiracy keanu [7] Tumblr\
  \ \u2013 #conspiracy keanu [8] Reddit \u2013 conspiracy keanu [9] Troll.me via Way\
  \ Back Machine \u2013 conspiracy keanu [10] Facebook \u2013 Conspiracy Keanu [11]\
  \ Funny Junk \u2013 What If [12] ConspiracyKeanu.com \u2013 Conspiracy Keanu [13]\
  \ BuzzFeed \u2013 The 21 Best Conspiracy Keanu Meme Images [14] Pleated Jeans \u2013\
  \ Best of the Conspiracy Keanu Meme [15] Facebook \u2013 Conspiracy Keanu [16] Smosh\
  \ \u2013 Best of Conspiracy Keanu! [17] Quickmeme \u2013 Search Results 'Conspiracy'\
  \ [18] Quickmeme \u2013 Conspiracy Cat [19] Quickmeme \u2013 Conspiracy Lyra 1 [20]\
  \ Quickmeme \u2013 Conspiracy Lyra 2 Related Entries 16 total Sad Keanu Happy Keanu\
  \ Mini Keanu Reeves You're Breathtaking Tai Chi Keanu Sad Keanu in a Helmet Keanu\
  \ Reeves Dining in Headphones Cyberpunk 2077 Keanu Reeves / We Have a City to Burn\
  \ Knock Knock Keanu Reeves Is Such A Gentleman / Celebrity At A Barbershop Copypasta\
  \ Tumbleweed Keanu Reeves Keanu Reeves Walking in Slow Motion View All Related Entries\
  \ Recent Videos 1 total Conspiracy Keanu scene from B... Conspiracy Keanu Uploaded\
  \ by JB1995 + Add a Video Recent Images 279 total Conspiracy Keanu Uploaded by FatmanAss\
  \ Conspiracy Keanu Uploaded by Evilthing Conspiracy Keanu Uploaded by Evilthing\
  \ Conspiracy Keanu Uploaded by KYM Grand Elder Conspiracy Keanu Uploaded by Ozzy\
  \ Mandias Conspiracy Keanu Uploaded by Rebecca Rhodes Conspiracy Keanu Uploaded\
  \ by Dry Ice Conspiracy Keanu Uploaded by oudaveguy98 Conspiracy Keanu Uploaded\
  \ by Talonvaki Conspiracy Keanu Uploaded by OurDeerLeader Conspiracy Keanu Uploaded\
  \ by Philipp Conspiracy Keanu Uploaded by Usereus + Add an Image View All Images\
  \ Sign up for our Newsletter Top Comments Delete Sensitive SixthHokage Nov 19, 2011\
  \ at 03:39PM EST +71 Reply Delete Sensitive Victor142 Dec 04, 2011 at 10:56PM EST\
  \ +28 Reply + Add a Comment Comments (45) Display Comments Add a Comment Top Entries\
  \ This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (8) Heather\
  \ Don Administrator & Meme Daddy Brad Digital Archaeologist & Treasurer & Pundit\
  \ & Gallery Housekeeper RandomMan Database Moderator & God Tier Swag & Protip Advisor\
  \ & Karma Tycoon & Meme Boi \xAD\xAD\xADAlex Mercer Entry Moderator & YouTube Scatologist\
  \ The Cute Master :3 Sr. Entry Moderator SabrinaTibbetts Memepuff Y F Digital Archaeologist\
  \ & Treasurer & Media Maid \u25BC + Request Editorship View All Editors Today's\
  \ Top Image Galleries Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen\
  \ Green) Team Fortress 2 The Amazing Digital Circus About Our Story Site Rules Policies\
  \ and Guidelines Credits Contact Meme DB Memes Episodes News Staff Contact Extras!\
  \ Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/conspiracy-keanu
template_id: keanu
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
