name: Conspiracy Keanu
source: http://knowyourmeme.com/memes/conspiracy-keanu
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- what if the CIA invented dinosaurs
- to discourage time travel?
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Conspiracy Keanu is an advice animal image macro series featuring
  a still photo of the Hollywood actor Keanu Reeves wearing a frightened expression
  from the 1989 comedy film Bill and Ted’s Excellent Adventure. The images are typically
  captioned with paranoid conjectures and absurdly philosophical questions that bear
  similarities to the Paranoid Parrot, Philosoraptor and Stoner Dog advice animal
  series. Origin On December 11th, 2008, New York Magazine''s Vulture Blog[3] published
  a slideshow titled “Vulture’s Complete Field Guide to the Facial Expressions of
  Keanu Reeves” that consisted of screen captures of Reeves from various films. The
  22nd slide featured an image of Ted (played by Keanu Reeves) taken from the 1989
  comedy film Bill & Ted’s Excellent Adventure in a scene where Ted is being chased
  by medieval knights. The image was subsequently used as a reaction face with the
  earliest known instance occurring on the Fark[1] forums (shown left) on September
  17th, 2010. The first image macro (shown right) was posted to the r/funny subreddit[2]
  with the caption “What if we CAN breathe in space / and they just don’t want us
  to escape” on June 2nd, 2011, which accumulated 6,847 up votes prior to being archived.
  Spread An instance with the caption "What if all the specs we see in the light /
  are all miniature universes?" was submitted to the humor site FunnyJunk[11] on September
  24th, 2011. Beginning in November 2011, Conspiracy Keanu image macros spread on
  a larger scale with the launch of a Facebook fan page[10] on November 19th and compilations
  were posted to various sites including BuzzFeed[13], Pleated Jeans[14] and the web
  culture blog UpRoxx[5] within the next few days. On December 15th, the web culture
  blog Smosh[16] published a "Best of Conspiracy Keanu" post. The domain for the single
  topic blog ConspiracyKeanu.com[12] was registered on December 18th. Additionally,
  derivatives have been posted to FunnyJunk[6], Tumblr[7], Troll.me[9] and Reddit.[8]
  As of April 2012, the Quickmeme[4] page has 37,458 submissions and the Facebook[15]
  page has 1,421 likes. Notable Examples Derivatives On Quickmeme, searching for ''conspiracy''
  results in numerous spin-offs.[17] These vary between humans and animals, to fictional
  characters, with the text on the image macro matching to the image. Even though
  most of these only generated a few images and didn''t gain much popularity, more
  successful versions are Conspiracy Cat[18] and various instances of Conspiracry
  Lyra[19] [20]. Template Search Interest External References [1] Fark – China plans
  to lead world in eco-friendly cars. Haven''t they lead enough? [2] Reddit – Conspiracy
  Keanu [3] NYMag – Vulture’s Complete Field Guide to the Facial Expressions of Keanu
  Reeves [4] Quickmeme – Conspiracy Keanu [5] UpRoxx – Conspiracy Keanu Puts A Meme
  To What Keanu Reeves Is Thinking [6] FunnyJunk (must login to run the search) –
  conspiracy keanu [7] Tumblr – #conspiracy keanu [8] Reddit – conspiracy keanu [9]
  Troll.me via Way Back Machine – conspiracy keanu [10] Facebook – Conspiracy Keanu
  [11] Funny Junk – What If [12] ConspiracyKeanu.com – Conspiracy Keanu [13] BuzzFeed
  – The 21 Best Conspiracy Keanu Meme Images [14] Pleated Jeans – Best of the Conspiracy
  Keanu Meme [15] Facebook – Conspiracy Keanu [16] Smosh – Best of Conspiracy Keanu!
  [17] Quickmeme – Search Results ''Conspiracy'' [18] Quickmeme – Conspiracy Cat [19]
  Quickmeme – Conspiracy Lyra 1 [20] Quickmeme – Conspiracy Lyra 2'
aside_content: MemeStatusConfirmedType:Image MacroYear2011OriginRedditTagsconspiracy,420,keanu
  reeves,stoner humorAdditional ReferencesMeme Generator
added_at: '2011-11-19T07:08:24-05:00'
