name: Persian Cat Room Guardian
source: https://knowyourmeme.com/memes/persian-cat-room-guardian
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- when you wake up from a nap
- and your mom starts yelling at you
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: About Persian Room Cat Guardian, also known as Cat-Monkey or Monkey-Cat,
  is a reaction and image macro series and photoshop meme featuring photographs of
  a stuffed toy cat seated on top of a box with arms outstretched. Image macros of
  the photos are typically captioned with frustrating or annoying situations, using
  the stuffed toy's pose to convey an incredulous reaction. Origin On August 5th,
  2013, DeviantArtist[1] AnyaBoz posted a photograph of a stuffed cat toy titled "Persian
  Cat Room Guardian," describing room guardians as "small creatures that protect one's
  home from negative spirits and energies" (shown below). Spread The images remained
  undiscovered until early 2016 when they began appearing on Instagram in the form
  of reaction image macros. On February 5th, 2016, the @ratchetpeoplemeet Instagram[5]
  page posted an image macro featuring two photos of the stuffed toy with the caption
  "When you ask your girl what's wrong and she gets mad even more and says 'you're
  supposed to know'" (shown below, left). Within four days, the image gained over
  8,500 likes. The following day, Anyaboz posted several photos Tumblr[3] blog, including
  another image macro with the caption "When you wake up from a nap and your mom starts
  yelling at you" (shown below, right). That day, Anyaboz updated the DeviantArt page
  noting that the picture had "become somewhat of a meme" and encouraged others to
  credit her when using the photo. On February 7th, Reddit captainchase submitted
  the photograph to the /r/photoshopbattles[2] subreddit, describing it as a "monkey
  looking thing." Within 24 hours, the post gathered upwards of 2,100 votes (91% upvoted)
  and 100 comments, many of which contained edited versions of the image (shown below).
  The same day, Redditor majkadajk submitted a post titled "What is the origin of
  the stuffed white monkey looking thing?" to /r/OutOfTheLoop,[4] to which Redditor
  Beast_Mode_Alfy cited Anyaboz DeviantArt page. Also on February 7th, the @gymmemesofficial[6]
  Instagram page posted an image macro of the stuffed toy with the caption "When you
  get done with the dumbbells and see someone else racked theirs in place of yours"
  (shown below). Template Search Interest External References [1] DeviantArt – Persian
  Cat Room Guardian [2] Reddit – Psbattle – whatever this monkey looking this is [3]
  Tumblr – Anyaboz [4] Reddit – What is the origin of this monkey cat looking thing
  [5] Instagram – @ratchetpeoplemeet [6] Instagram – @gymemesofficial
aside_content: MemeStatusConfirmedType:Animal,Exploitable,ReactionYear2013OriginDeviantArtRegionUnited
  StatesTagsreaction image,photoshop,deviantart,deviantartist,stuffed toy,stuffed
  animal,cat,persian cat room guardian meme,taxidermy,white cat,hands up,confused,monkey
  cat memeAdditional ReferencesMeme Generator
added_at: '2016-02-08T18:10:57-05:00'
