example:
- when you wake up from a nap
- and your mom starts yelling at you
keywords:
- null
name: Persian Cat Room Guardian
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Persian Cat Room Guardian | Know Your Meme Word Up! You must login\
  \ or signup first! Already a memeber? Login Now! Don't have an account? Sign up\
  \ Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos Submit\
  \ \u2192 Images Trending Most Commented Most Favorited High Score Low Score Most\
  \ Viewed All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Persian Cat Room Guardian Added 8 years ago / Updated about a year ago Confirmed\
  \ 691,514 Part of a series on Cats. [View Related Entries] View All 26 Images Navigation\
  \ About \u2022 Origin \u2022 Spread \u2022 Template \u2022 Search Interest \u2022\
  \ External References \u2022 Recent Images About Persian Room Cat Guardian, also\
  \ known as Cat-Monkey or Monkey-Cat, is a reaction and image macro series and photoshop\
  \ meme featuring photographs of a stuffed toy cat seated on top of a box with arms\
  \ outstretched. Image macros of the photos are typically captioned with frustrating\
  \ or annoying situations, using the stuffed toy's pose to convey an incredulous\
  \ reaction. Origin On August 5th, 2013, DeviantArtist[1] AnyaBoz posted a photograph\
  \ of a stuffed cat toy titled \"Persian Cat Room Guardian,\" describing room guardians\
  \ as \"small creatures that protect one's home from negative spirits and energies\"\
  \ (shown below). Spread The images remained undiscovered until early 2016 when they\
  \ began appearing on Instagram in the form of reaction image macros. On February\
  \ 5th, 2016, the @ratchetpeoplemeet Instagram[5] page posted an image macro featuring\
  \ two photos of the stuffed toy with the caption \"When you ask your girl what's\
  \ wrong and she gets mad even more and says 'you're supposed to know'\" (shown below,\
  \ left). Within four days, the image gained over 8,500 likes. The following day,\
  \ Anyaboz posted several photos Tumblr[3] blog, including another image macro with\
  \ the caption \"When you wake up from a nap and your mom starts yelling at you\"\
  \ (shown below, right). That day, Anyaboz updated the DeviantArt page noting that\
  \ the picture had \"become somewhat of a meme\" and encouraged others to credit\
  \ her when using the photo. On February 7th, Reddit captainchase submitted the photograph\
  \ to the /r/photoshopbattles[2] subreddit, describing it as a \"monkey looking thing.\"\
  \ Within 24 hours, the post gathered upwards of 2,100 votes (91% upvoted) and 100\
  \ comments, many of which contained edited versions of the image (shown below).\
  \ The same day, Redditor majkadajk submitted a post titled \"What is the origin\
  \ of the stuffed white monkey looking thing?\" to /r/OutOfTheLoop,[4] to which Redditor\
  \ Beast_Mode_Alfy cited Anyaboz DeviantArt page. Also on February 7th, the @gymmemesofficial[6]\
  \ Instagram page posted an image macro of the stuffed toy with the caption \"When\
  \ you get done with the dumbbells and see someone else racked theirs in place of\
  \ yours\" (shown below). Template Search Interest External References [1] DeviantArt\
  \ \u2013 Persian Cat Room Guardian [2] Reddit \u2013 Psbattle \u2013 whatever this\
  \ monkey looking this is [3] Tumblr \u2013 Anyaboz [4] Reddit \u2013 What is the\
  \ origin of this monkey cat looking thing [5] Instagram \u2013 @ratchetpeoplemeet\
  \ [6] Instagram \u2013 @gymemesofficial reaction image photoshop deviantart deviantartist\
  \ stuffed toy stuffed animal cat persian cat room guardian meme taxidermy white\
  \ cat hands up confused monkey cat meme Share Pin Related Entries 211 total Grumpy\
  \ Cat Nyan Cat Business Cat Smudge the Cat View All Related Entries Recent Images\
  \ 26 total View All Images Recent Videos 0 total There are no recent videos. Sign\
  \ up for our Newsletter Load 23 Comments Comments 23 total 51 Persian Cat Room Guardian\
  \ 691,514 0 26 23 Part of a series on Cats. [View Related Entries] Updated Aug 04,\
  \ 2023 at 06:07PM EDT by Zach. Added Feb 08, 2016 at 06:10PM EST by Don. Like us\
  \ on Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the image gallery,\
  \ 'v' to view the video gallery, or 'r' to view a random entry. Meme Status Confirmed\
  \ Type: Animal, Exploitable, Reaction Year 2013 Origin DeviantArt Region United\
  \ States Tags reaction image, photoshop, deviantart, deviantartist, stuffed toy,\
  \ stuffed animal, cat, persian cat room guardian meme, taxidermy, white cat, hands\
  \ up, confused, monkey cat meme Additional References Meme Generator About Persian\
  \ Room Cat Guardian, also known as Cat-Monkey or Monkey-Cat, is a reaction and image\
  \ macro series and photoshop meme featuring photographs of a stuffed toy cat seated\
  \ on top of a box with arms outstretched. Image macros of the photos are typically\
  \ captioned with frustrating or annoying situations, using the stuffed toy's pose\
  \ to convey an incredulous reaction. Origin On August 5th, 2013, DeviantArtist[1]\
  \ AnyaBoz posted a photograph of a stuffed cat toy titled \"Persian Cat Room Guardian,\"\
  \ describing room guardians as \"small creatures that protect one's home from negative\
  \ spirits and energies\" (shown below). Spread The images remained undiscovered\
  \ until early 2016 when they began appearing on Instagram in the form of reaction\
  \ image macros. On February 5th, 2016, the @ratchetpeoplemeet Instagram[5] page\
  \ posted an image macro featuring two photos of the stuffed toy with the caption\
  \ \"When you ask your girl what's wrong and she gets mad even more and says 'you're\
  \ supposed to know'\" (shown below, left). Within four days, the image gained over\
  \ 8,500 likes. The following day, Anyaboz posted several photos Tumblr[3] blog,\
  \ including another image macro with the caption \"When you wake up from a nap and\
  \ your mom starts yelling at you\" (shown below, right). That day, Anyaboz updated\
  \ the DeviantArt page noting that the picture had \"become somewhat of a meme\"\
  \ and encouraged others to credit her when using the photo. On February 7th, Reddit\
  \ captainchase submitted the photograph to the /r/photoshopbattles[2] subreddit,\
  \ describing it as a \"monkey looking thing.\" Within 24 hours, the post gathered\
  \ upwards of 2,100 votes (91% upvoted) and 100 comments, many of which contained\
  \ edited versions of the image (shown below). The same day, Redditor majkadajk submitted\
  \ a post titled \"What is the origin of the stuffed white monkey looking thing?\"\
  \ to /r/OutOfTheLoop,[4] to which Redditor Beast_Mode_Alfy cited Anyaboz DeviantArt\
  \ page. Also on February 7th, the @gymmemesofficial[6] Instagram page posted an\
  \ image macro of the stuffed toy with the caption \"When you get done with the dumbbells\
  \ and see someone else racked theirs in place of yours\" (shown below). Template\
  \ Search Interest External References [1] DeviantArt \u2013 Persian Cat Room Guardian\
  \ [2] Reddit \u2013 Psbattle \u2013 whatever this monkey looking this is [3] Tumblr\
  \ \u2013 Anyaboz [4] Reddit \u2013 What is the origin of this monkey cat looking\
  \ thing [5] Instagram \u2013 @ratchetpeoplemeet [6] Instagram \u2013 @gymemesofficial\
  \ Related Entries 211 total Grumpy Cat Nyan Cat Business Cat Smudge the Cat Longcat\
  \ Chonk / Oh Lawd He Comin' Big Floppa Ceiling Cat I Should Buy a Boat Cat Chemistry\
  \ Cat Polite Cat Cats Can Have a Little Salami View All Related Entries Recent Videos\
  \ There are no videos currently available. + Add a Video Recent Images 26 total\
  \ Persian Cat Room Guardian Uploaded by Fiftytwo144 Persian Cat Room Guardian Uploaded\
  \ by shevyrolet Persian Cat Room Guardian Uploaded by Makena Rasmussen Persian Cat\
  \ Room Guardian Uploaded by Reddit Moments Persian Cat Room Guardian Uploaded by\
  \ shevyrolet Persian Cat Room Guardian Uploaded by Immortal Scientist \u262D Persian\
  \ Cat Room Guardian Uploaded by Jill Persian Cat Room Guardian Uploaded by Dank\
  \ Pepedorf, First Earl o... Persian Cat Room Guardian Uploaded by GhettoRobin Persian\
  \ Cat Room Guardian Uploaded by Frozen99 Persian Cat Room Guardian Uploaded by memesnake2000\
  \ Persian Cat Room Guardian Uploaded by MrGermanblood + Add an Image View All Images\
  \ Sign up for our Newsletter Top Comments Delete Sensitive Paulie DeMafia Mk2 Feb\
  \ 08, 2016 at 08:04PM EST American Room Guardian +37 Reply Delete Sensitive Real\
  \ Waluigi Feb 09, 2016 at 04:39PM EST When your parents ask where your meme went\
  \ +28 Reply + Add a Comment Comments (23) Display Comments Add a Comment Top Entries\
  \ This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (6) Don Administrator\
  \ & Meme Daddy Brad Digital Archaeologist & Treasurer & Pundit & Gallery Housekeeper\
  \ LNH Deactivated Sophie Digital Archaeologist & Treasurer & Media Bus Boy shevyrolet\
  \ Digital Archaeologist & Treasurer & Media Bus Boy Zach Memenator \u25BC + Request\
  \ Editorship View All Editors Today's Top Image Galleries Assassination of UnitedHealthcare\
  \ CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing Digital Circus About\
  \ Our Story Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes\
  \ News Staff Contact Extras! Style Guide RSS Feeds"
source: https://knowyourmeme.com/memes/persian-cat-room-guardian
template_id: persian
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
