example:
- ''
- hhhehehe
keywords:
- null
name: Laughing Lizard
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Laughing Lizard / hhhehehe | Know Your Meme Word Up! You must login\
  \ or signup first! Already a memeber? Login Now! Don't have an account? Sign up\
  \ Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos Submit\
  \ \u2192 Images Trending Most Commented Most Favorited High Score Low Score Most\
  \ Viewed All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Laughing Lizard / hhhehehe Added 10 years ago / Updated 8 days ago Confirmed\
  \ 147,231 Part of a series on Interior Monologue Captioning. [View Related Entries]\
  \ View All 75 Images Navigation About \u2022 Origin \u2022 Spread \u2022 Notable\
  \ Examples \u2022 Search Interest \u2022 External References \u2022 Recent Images\
  \ About Laughing Lizard is an image macro featuring a photograph of a horned lizard\
  \ and an interior monologue caption that reads \"hhhehehe.\" Due to the lizard's\
  \ facial expression resembling the laughter of a human, the captioned photograph\
  \ is also used as a reaction image to indicate a sense of amusement, especially\
  \ when triggered by something that is deemed silly or lowbrow. Origin On April 24th,\
  \ 2009, nature photographer Casey Myers uploaded a photograph to the image-sharing\
  \ site Flickriver[1] of a horned lizard spotted in the Tonto National Forest Campgrounds\
  \ at Lake Roosevelt in Arizona. In the photograph, the lizard appears to be chuckling\
  \ or smiling, as suggested by its slightly agape mouth. On August 17th, 2011, Tumblr\
  \ user effington[2] posted the same image, but this time, with the caption \"hhhehehe\"\
  \ overlaid by the lizard's mouth in the style of interior monologue captioning.\
  \ As of July 2014, the post has gained over 14,000 notes. Spread On September 12th,\
  \ 2011, Redditor discovergeneralmills created the subreddit /r/laughinglizards/.[3]\
  \ In 2012, at least three Tumblr posts filed under the tag #laughing lizard gained\
  \ some traction with hundreds of notes, including sweetneverafter's post[5] on June\
  \ 16th and vaalon's[6] post on November 18th, both of which have gained more than\
  \ 600 notes, and dandy-pants'[7] post on November 28th, which has accumulated over\
  \ 92,000 notes. In 2013, the trend continued with at least two Tumblr posts garnering\
  \ more than 5,000 notes, including memelibrarian's[8] post on January 17th and voldyrule's[9]\
  \ post on January 18th. By 2014, the popularity of the laughing lizard had waned\
  \ significantly, though the image continued to spread in the form of an animated\
  \ GIF published via MemeCollection[4] on July 15th, 2014. Notable Examples Search\
  \ Interest External References [1] Flickriver \u2013 Casey Myers Photography [2]\
  \ Tumblr \u2013 hhhehehe [3] Reddit \u2013 laughinglizards [4] MemeCollection- Laughing\
  \ Hue Lizard GIF [5] Tumblr- sweetneverafter [6] Tumblr- vaalon [7] Tumblr- dandy-pants\
  \ [8] Tumblr- memelibrarian [9] Tumblr- voldyrule image macro lizard laughing horned\
  \ lizard hhhehehe animal interior monologue Share Pin Related Entries 8 total Doge\
  \ Snek Stop It Son, You Are Doing Me... Captioned Stock Photos View All Related\
  \ Entries Recent Images 75 total View All Images Recent Videos 0 total There are\
  \ no recent videos. Sign up for our Newsletter Load 18 Comments Comments 18 total\
  \ 30 Laughing Lizard / hhhehehe 147,231 0 75 18 Part of a series on Interior Monologue\
  \ Captioning. [View Related Entries] Updated Dec 15, 2024 at 04:11PM EST by LiterallyAustin.\
  \ Added Aug 03, 2014 at 11:44AM EDT by MScratch. Like us on Facebook! Like 1.8M\
  \ Share Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view the\
  \ video gallery, or 'r' to view a random entry. Meme Status Confirmed Year 2011\
  \ Origin Tumblr Tags image macro, lizard, laughing, horned lizard, hhhehehe, animal,\
  \ interior monologue About Laughing Lizard is an image macro featuring a photograph\
  \ of a horned lizard and an interior monologue caption that reads \"hhhehehe.\"\
  \ Due to the lizard's facial expression resembling the laughter of a human, the\
  \ captioned photograph is also used as a reaction image to indicate a sense of amusement,\
  \ especially when triggered by something that is deemed silly or lowbrow. Origin\
  \ On April 24th, 2009, nature photographer Casey Myers uploaded a photograph to\
  \ the image-sharing site Flickriver[1] of a horned lizard spotted in the Tonto National\
  \ Forest Campgrounds at Lake Roosevelt in Arizona. In the photograph, the lizard\
  \ appears to be chuckling or smiling, as suggested by its slightly agape mouth.\
  \ On August 17th, 2011, Tumblr user effington[2] posted the same image, but this\
  \ time, with the caption \"hhhehehe\" overlaid by the lizard's mouth in the style\
  \ of interior monologue captioning. As of July 2014, the post has gained over 14,000\
  \ notes. Spread On September 12th, 2011, Redditor discovergeneralmills created the\
  \ subreddit /r/laughinglizards/.[3] In 2012, at least three Tumblr posts filed under\
  \ the tag #laughing lizard gained some traction with hundreds of notes, including\
  \ sweetneverafter's post[5] on June 16th and vaalon's[6] post on November 18th,\
  \ both of which have gained more than 600 notes, and dandy-pants'[7] post on November\
  \ 28th, which has accumulated over 92,000 notes. In 2013, the trend continued with\
  \ at least two Tumblr posts garnering more than 5,000 notes, including memelibrarian's[8]\
  \ post on January 17th and voldyrule's[9] post on January 18th. By 2014, the popularity\
  \ of the laughing lizard had waned significantly, though the image continued to\
  \ spread in the form of an animated GIF published via MemeCollection[4] on July\
  \ 15th, 2014. Notable Examples Search Interest External References [1] Flickriver\
  \ \u2013 Casey Myers Photography [2] Tumblr \u2013 hhhehehe [3] Reddit \u2013 laughinglizards\
  \ [4] MemeCollection- Laughing Hue Lizard GIF [5] Tumblr- sweetneverafter [6] Tumblr-\
  \ vaalon [7] Tumblr- dandy-pants [8] Tumblr- memelibrarian [9] Tumblr- voldyrule\
  \ Related Entries 8 total Doge Snek Stop It Son, You Are Doing Me A Frighten Captioned\
  \ Stock Photos Stop Das Gay Master Trole Kid Oh You So Crazy Animals Talking In\
  \ All Caps Recent Videos There are no videos currently available. + Add a Video\
  \ Recent Images 75 total Laughing Lizard / hhhehehe Uploaded by Grommet the Swood\
  \ Laughing Lizard / hhhehehe Uploaded by Blu Spy Laughing Lizard / hhhehehe Uploaded\
  \ by Lycanroc Laughing Lizard / hhhehehe Uploaded by stalfos420 Laughing Lizard\
  \ / hhhehehe Uploaded by AndyHarp94 Laughing Lizard / hhhehehe Uploaded by Yours\
  \ Truly Laughing Lizard / hhhehehe Uploaded by MScratch Laughing Lizard / hhhehehe\
  \ Uploaded by Jill Laughing Lizard / hhhehehe Uploaded by Jill Laughing Lizard /\
  \ hhhehehe Uploaded by Don Laughing Lizard / hhhehehe Uploaded by Don Laughing Lizard\
  \ / hhhehehe Uploaded by Don + Add an Image View All Images Sign up for our Newsletter\
  \ Top Comments Delete Sensitive Archmage Aug 05, 2014 at 06:02AM EDT On one hand,\
  \ it's yet another image macro meme. On the other hand, it's not from Reddit. +28\
  \ Reply Delete Sensitive HorribleGhost Aug 06, 2014 at 01:44AM EDT +17 Reply + Add\
  \ a Comment Comments (18) Display Comments Add a Comment Top Entries This Month\
  \ Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare CEO Person\
  \ Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography Site\
  \ Whisper View More Suggest a Change Edit History Entry Editors (3) MScratch Database\
  \ Moderator & Historical Meme Historian & \u300CStand User\u300D Molly Horan Tumblr\
  \ Historian Brad Digital Archaeologist & Treasurer & Pundit & Gallery Housekeeper\
  \ + Request Editorship View All Editors Today's Top Image Galleries Assassination\
  \ of UnitedHealthcare CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing\
  \ Digital Circus About Our Story Site Rules Policies and Guidelines Credits Contact\
  \ Meme DB Memes Episodes News Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/laughing-lizard-hhhehehe
template_id: ll
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
