name: Laughing Lizard
source: http://knowyourmeme.com/memes/laughing-lizard-hhhehehe
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- ''
- hhhehehe
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Laughing Lizard is an image macro featuring a photograph of
  a horned lizard and an interior monologue caption that reads "hhhehehe." Due to
  the lizard''s facial expression resembling the laughter of a human, the captioned
  photograph is also used as a reaction image to indicate a sense of amusement, especially
  when triggered by something that is deemed silly or lowbrow. Origin On April 24th,
  2009, nature photographer Casey Myers uploaded a photograph to the image-sharing
  site Flickriver[1] of a horned lizard spotted in the Tonto National Forest Campgrounds
  at Lake Roosevelt in Arizona. In the photograph, the lizard appears to be chuckling
  or smiling, as suggested by its slightly agape mouth. On August 17th, 2011, Tumblr
  user effington[2] posted the same image, but this time, with the caption "hhhehehe"
  overlaid by the lizard''s mouth in the style of interior monologue captioning. As
  of July 2014, the post has gained over 14,000 notes. Spread On September 12th, 2011,
  Redditor discovergeneralmills created the subreddit /r/laughinglizards/.[3] In 2012,
  at least three Tumblr posts filed under the tag #laughing lizard gained some traction
  with hundreds of notes, including sweetneverafter''s post[5] on June 16th and vaalon''s[6]
  post on November 18th, both of which have gained more than 600 notes, and dandy-pants''[7]
  post on November 28th, which has accumulated over 92,000 notes. In 2013, the trend
  continued with at least two Tumblr posts garnering more than 5,000 notes, including
  memelibrarian''s[8] post on January 17th and voldyrule''s[9] post on January 18th.
  By 2014, the popularity of the laughing lizard had waned significantly, though the
  image continued to spread in the form of an animated GIF published via MemeCollection[4]
  on July 15th, 2014. Notable Examples Search Interest External References [1] Flickriver
  – Casey Myers Photography [2] Tumblr – hhhehehe [3] Reddit – laughinglizards [4]
  MemeCollection- Laughing Hue Lizard GIF [5] Tumblr- sweetneverafter [6] Tumblr-
  vaalon [7] Tumblr- dandy-pants [8] Tumblr- memelibrarian [9] Tumblr- voldyrule'
aside_content: MemeStatusConfirmedYear2011OriginTumblrTagsimage macro,lizard,laughing,horned
  lizard,hhhehehe,animal,interior monologue
added_at: '2014-08-03T11:44:46-04:00'
