example:
- can't workout
- don't want to get too buff
keywords:
- null
name: Butthurt Dweller
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Butthurt Dweller / Gordo Granudo | Know Your Meme Hello! You must\
  \ login or signup first! Already a memeber? Login Now! Don't have an account? Sign\
  \ up Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos\
  \ Submit \u2192 Images Trending Most Commented Most Favorited High Score Low Score\
  \ Most Viewed All Templates Upload an Image Articles News Explainers Collections\
  \ Interviews Meme Insider Magazine More Discord Newsletter Episodes Forums Meme\
  \ Store Login Abstract user icon Memes Categories Trending News Images Trending\
  \ Images Videos Trending Videos Editorials Meme Insider Magazine Newsletter Policies\
  \ and Guidelines Meme Store Old site Login Know Your Meme is the property of Literally\
  \ Media \xA92024 Literally Media. All Rights Reserved. This image Of Woman Confidently\
  \ Strolling Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years\
  \ Ago, This Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The\
  \ Anarchy Chess Memes Turns Two Years Old Today Phrase 'The Fridge Protects The\
  \ Snacks' A Growing Favorite Among Pickup Artist Influencers Jamie G, The Bosh British\
  \ Charva, Has Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also\
  \ Trending: Honey Extension Influencer Scam Renegade Raider Copypasta Assassination\
  \ of UnitedHealthcare CEO Butthurt Dweller / Gordo Granudo Added 14 years ago /\
  \ Updated 17 days ago Confirmed 871,381 Part of a series on Advice Animals. [View\
  \ Related Entries] View All 66 Images Navigation About \u2022 Origin \u2022 Spread\
  \ \u2022 Examples \u2022 Search Interest \u2022 External References \u2022 Recent\
  \ Images \u2022 Recent Videos About Butthurt Dweller, also known as \"Gordo Granudo\"\
  , is an image macro series that features a photo of a young adult male with a ponytail\
  \ and glasses accompanied by overlaid text that involves a smug or judgmental statement.\
  \ Origin The man depicted in the image is Finnish resident KimmoKM, who discussed\
  \ the origin of the meme in an IRC interview[1]: The meme started in a Finnish imageboard\
  \ as \"Ruma huora, en panisi\" (ugly whore, I wouldn't fuck her) and then later\
  \ I've occasionally seen it flying around 4chan and other sites There are now plenty\
  \ of English variations that use the same smug approach, usually judging how sexually\
  \ attractive he finds a member of the opposite sex. Spread \"Basement Dweller\"\
  \ entry was first registed on Urban Dictionary[2] on October 16, 2003: A male over\
  \ the age of eightteen, usually with no formal education, who continues to live\
  \ at home with his parent(s) and has no ambition to move out or contribute to society.\
  \ His will to live is sucked by his daily marijuana regiment. He can be found working\
  \ second shift at your local gas station. Lives in a perpetual state of \"Getting\
  \ his shit together.\" The meme became quite popular through web application sites\
  \ like MemeGenerator[3] and Quickmeme[4]. Examples Template Rage Face In 2011, a\
  \ vectoritzed version of the Butthurt Dweller's face began to be used in rage comics,\
  \ representing the topics of the geeks. Search Interest Search queries for \"butthurt\
  \ dweller\" saw a huge spike in February of 2011, and the search traffic is shown\
  \ to be almost exclusively from Spain. External References [1] Pastebin \u2013 IRC\
  \ interview [2] Urban Dictionary \u2013 Basement Dweller [3] MemeGenerator \u2013\
  \ Basement Dweller [4] Quickmeme \u2013 Butthurt Dweller image macro spanish finnish\
  \ basement social stereotype Share Pin Related Entries 115 total Ermahgerd Overly\
  \ Attached Girlfriend Scumbag Steve Good Guy Greg View All Related Entries Recent\
  \ Images 66 total View All Images Recent Videos 17 total View All Videos Sign up\
  \ for our Newsletter Load 73 Comments Comments 73 total 39 Butthurt Dweller / Gordo\
  \ Granudo 871,381 17 66 73 Part of a series on Advice Animals. [View Related Entries]\
  \ Updated Dec 06, 2024 at 02:54PM EST by LiterallyAustin. Added Aug 06, 2010 at\
  \ 04:01PM EDT by Adam DeLand. Like us on Facebook! Like 1.8M Share Save Tweet PROTIP:\
  \ Press 'i' to view the image gallery, 'v' to view the video gallery, or 'r' to\
  \ view a random entry. Meme Status Confirmed Year 2010 Origin Meme Generator Tags\
  \ image macro, spanish, finnish, basement, social stereotype Additional References\
  \ Meme Generator About Butthurt Dweller, also known as \"Gordo Granudo\", is an\
  \ image macro series that features a photo of a young adult male with a ponytail\
  \ and glasses accompanied by overlaid text that involves a smug or judgmental statement.\
  \ Origin The man depicted in the image is Finnish resident KimmoKM, who discussed\
  \ the origin of the meme in an IRC interview[1]: The meme started in a Finnish imageboard\
  \ as \"Ruma huora, en panisi\" (ugly whore, I wouldn't fuck her) and then later\
  \ I've occasionally seen it flying around 4chan and other sites There are now plenty\
  \ of English variations that use the same smug approach, usually judging how sexually\
  \ attractive he finds a member of the opposite sex. Spread \"Basement Dweller\"\
  \ entry was first registed on Urban Dictionary[2] on October 16, 2003: A male over\
  \ the age of eightteen, usually with no formal education, who continues to live\
  \ at home with his parent(s) and has no ambition to move out or contribute to society.\
  \ His will to live is sucked by his daily marijuana regiment. He can be found working\
  \ second shift at your local gas station. Lives in a perpetual state of \"Getting\
  \ his shit together.\" The meme became quite popular through web application sites\
  \ like MemeGenerator[3] and Quickmeme[4]. Examples Template Rage Face In 2011, a\
  \ vectoritzed version of the Butthurt Dweller's face began to be used in rage comics,\
  \ representing the topics of the geeks. Search Interest Search queries for \"butthurt\
  \ dweller\" saw a huge spike in February of 2011, and the search traffic is shown\
  \ to be almost exclusively from Spain. External References [1] Pastebin \u2013 IRC\
  \ interview [2] Urban Dictionary \u2013 Basement Dweller [3] MemeGenerator \u2013\
  \ Basement Dweller [4] Quickmeme \u2013 Butthurt Dweller Related Entries 115 total\
  \ Ermahgerd Overly Attached Girlfriend Scumbag Steve Good Guy Greg Ridiculously\
  \ Photogenic Guy Bad Luck Brian Philosoraptor Annoying Facebook Girl The Most Interesting\
  \ Man in the World Socially Awkward Penguin Bear Grylls / Better Drink My Own Piss\
  \ Successful Black Man View All Related Entries Recent Videos 17 total Jaidefinichon\
  \ Photoshop Gordo... Butthurt Dweller / Gordo Granudo Uploaded by shevyrolet el\
  \ gordo granudo chateando Butthurt Dweller / Gordo Granudo Uploaded by shevyrolet\
  \ tributo al gordo granudo Butthurt Dweller / Gordo Granudo Uploaded by shevyrolet\
  \ Official Reddit Butthurt Video Butthurt Dweller / Gordo Granudo Uploaded by shevyrolet\
  \ Best Butthurt Dweller Memes -... Butthurt Dweller / Gordo Granudo Uploaded by\
  \ shevyrolet el gordo granudo y la marihua... Butthurt Dweller / Gordo Granudo Uploaded\
  \ by shevyrolet Gordo Granudo da realidade Butthurt Dweller / Gordo Granudo Uploaded\
  \ by shevyrolet gordo granudo 2 Butthurt Dweller / Gordo Granudo Uploaded by shevyrolet\
  \ + Add a Video View All Videos Recent Images 66 total Butthurt Dweller / Gordo\
  \ Granudo Uploaded by Fight Milk22 Butthurt Dweller / Gordo Granudo Uploaded by\
  \ Brad Butthurt Dweller / Gordo Granudo Uploaded by MScratch Butthurt Dweller /\
  \ Gordo Granudo Uploaded by Genry Butthurt Dweller / Gordo Granudo Uploaded by effaroo\
  \ Butthurt Dweller / Gordo Granudo Uploaded by Adam DeLand Butthurt Dweller / Gordo\
  \ Granudo Uploaded by ri Butthurt Dweller / Gordo Granudo Uploaded by Dead Account\
  \ Butthurt Dweller / Gordo Granudo Uploaded by RandomMan Butthurt Dweller / Gordo\
  \ Granudo Uploaded by Binbin Butthurt Dweller / Gordo Granudo Uploaded by StreetGuy\
  \ Butthurt Dweller / Gordo Granudo Uploaded by InglipEfuner + Add an Image View\
  \ All Images Sign up for our Newsletter Top Comments Delete Sensitive Ma3ta Jan\
  \ 27, 2012 at 02:01AM EST I knew he looked familiar +33 Reply Delete Sensitive mentalwriter\
  \ Oct 25, 2011 at 06:12PM EDT @TenToes Says the one on the internet. +7 Reply +\
  \ Add a Comment Comments (73) Display Comments Add a Comment Top Entries This Month\
  \ Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare CEO Person\
  \ Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography Site\
  \ Whisper View More Suggest a Change Edit History Entry Editors (6) Adam DeLand\
  \ Sr. Researcher & Archivist & Orator & Media Chauffeur Don Administrator & Meme\
  \ Daddy Brad Digital Archaeologist & Treasurer & Pundit & Gallery Housekeeper Z.\
  \ Database Moderator & Rage Comicologist SabrinaTibbetts Memepuff shevyrolet Digital\
  \ Archaeologist & Treasurer & Media Bus Boy \u25BC + Request Editorship View All\
  \ Editors Today's Top Image Galleries Assassination of UnitedHealthcare CEO Squirrel\
  \ Girl (Doreen Green) Team Fortress 2 The Amazing Digital Circus About Our Story\
  \ Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes News\
  \ Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/butthurt-dweller-gordo-granudo
template_id: bd
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
