example:
- you were the chosen one!
keywords:
- null
name: You Were the Chosen One!
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "You Were The Chosen One! | Know Your Meme Hello! You must login\
  \ or signup first! Already a memeber? Login Now! Don't have an account? Sign up\
  \ Now! Meme Encyclopedia All Cultures Events People Sites Subcultures Videos Submit\
  \ \u2192 Images Trending Most Commented Most Favorited High Score Low Score Most\
  \ Viewed All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO You Were The Chosen One! Added 10 years ago / Updated 17 days ago Confirmed\
  \ 235,347 Part of a series on Obi-Wan Kenobi. [View Related Entries] View All 105\
  \ Images Navigation About \u2022 Origin \u2022 Spread \u2022 Notable Examples \u2022\
  \ Search Interest \u2022 External References \u2022 Recent Images About \u201CYou\
  \ were the chosen one!\u201D is a quote from the 2005 science fiction film Star\
  \ Wars: Episode III \u2013 Revenge of the Sith that is used to express disappointment\
  \ in someone or something that was once previously seen as promising. On the web,\
  \ the quote is often referenced in the form of an image macro based on a still shot\
  \ of Obi-Wan Kenobi from the corresponding scene in the film. Origin In Star Wars\
  \ Episode III: Revenge Of The Sith (2005), Jedi Master Obi-Wan Kenobi (Ewan McGregor)\
  \ is tasked with defeating his former apprentice Anakin Skywalker (Hayden Christensen),\
  \ who has led a genocide against the Jedi in spite of the fact he was suppose to\
  \ be the one to bring an end to the Sith. When Obi-Wan defeats Anakin, he cries\
  \ out: \"You were the chosen one! It was said that you would destroy the Sith, not\
  \ join them. You were to bring balance to the Force, not leave it in darkness!\"\
  [1] The scene was first uploaded to YouTube by reconelement[3] on January 22nd,\
  \ 2007. As of March 2014, the video has gained over 10.2 million views. [This video\
  \ has been removed] Spread On June 29, 2007, YouTuber Starr Hoffman[4] uploaded\
  \ a video featuring a man dressed as a jedi chasing a man holding an ice cream machine\
  \ while yelling \"You were the frozen one.\" On December 8th, 2007, Frasier Online[5]\
  \ fan forum user Texaveryfan wrote a short piece of fan fiction which featured Frasier\
  \ turning to the \"dark side of pretension.\" His friend shouts at him, \"You were\
  \ the Chosen One! It was said that you would destroy the higher classes, not join\
  \ them!\" On February 13th, 2011, a Facebook Page[7] for \"You Were the Chosen One\"\
  \ was created. The image macro first appeared on Tumblr on December 16th, 2011,\
  \ when Tumblr user wefuckingkepttrack[6] posted it as a way to express his disappointment\
  \ in President Obama. The image macro quickly became popular on Tumblr with over\
  \ 13 posts tagged #youwerethechosen one in 2012, including those-who-matter-dont-mind's[8]\
  \ post on Twilight, shylockbones's[9] post on soccer, and unheardastronaut's[11]\
  \ post on The Big Bang Theory. The quote's page on Meme Generator [3] has over 3,500\
  \ entries as of March 2014. Notable Examples Search Interest External References\
  \ [1] IMDB \u2013 Star Wars Episode III: Revenge Of The Sith [2] Meme Generator\
  \ \u2013 You Were The Chosen One\u201D Puts A Character In Yellowface [3] YouTube\
  \ \u2013 reconelement [4] YouTube \u2013 Starr Hoffman [5] Frasier Online \u2013\
  \ Frasier Winslow Crane Case File [6] Tumblr \u2013 wefuckingkepttrack (page deleted)\
  \ [7] Facebook \u2013 you were the chosen one [8] Facebook \u2013 those-who-matter-dont-mind\
  \ [9] Tumblr \u2013 shylockbones (page deleted) [10] Tumblr \u2013 #youwerethechosenone\
  \ [11] Tumblr \u2013 unheardastronaut star wars dark side anakin skywalker obi wan\
  \ kenobi you were the chosen one disappointment movie quote reconelement wefuckingkepttrack\
  \ texaveryfan starr hoffman Share Pin Related Entries 7 total Hello There I Have\
  \ The High Ground Well, Of Course I Know Him. H... [Visible Confusion] View All\
  \ Related Entries Recent Images 105 total View All Images Recent Videos 0 total\
  \ There are no recent videos. Sign up for our Newsletter Load 34 Comments Comments\
  \ 34 total 32 You Were The Chosen One! 235,347 0 105 34 Part of a series on Obi-Wan\
  \ Kenobi. [View Related Entries] Updated Dec 06, 2024 at 03:36PM EST by LiterallyAustin.\
  \ Added Mar 31, 2014 at 02:51PM EDT by Kung Fu Cthulhu. Like us on Facebook! Like\
  \ 1.8M Share Save Tweet PROTIP: Press 'i' to view the image gallery, 'v' to view\
  \ the video gallery, or 'r' to view a random entry. Meme Status Confirmed Year 2007\
  \ Origin YouTube Tags star wars, dark side, anakin skywalker, obi wan kenobi, you\
  \ were the chosen one, disappointment, movie quote, reconelement, wefuckingkepttrack,\
  \ texaveryfan, starr hoffman Additional References Meme Generator About \u201CYou\
  \ were the chosen one!\u201D is a quote from the 2005 science fiction film Star\
  \ Wars: Episode III \u2013 Revenge of the Sith that is used to express disappointment\
  \ in someone or something that was once previously seen as promising. On the web,\
  \ the quote is often referenced in the form of an image macro based on a still shot\
  \ of Obi-Wan Kenobi from the corresponding scene in the film. Origin In Star Wars\
  \ Episode III: Revenge Of The Sith (2005), Jedi Master Obi-Wan Kenobi (Ewan McGregor)\
  \ is tasked with defeating his former apprentice Anakin Skywalker (Hayden Christensen),\
  \ who has led a genocide against the Jedi in spite of the fact he was suppose to\
  \ be the one to bring an end to the Sith. When Obi-Wan defeats Anakin, he cries\
  \ out: \"You were the chosen one! It was said that you would destroy the Sith, not\
  \ join them. You were to bring balance to the Force, not leave it in darkness!\"\
  [1] The scene was first uploaded to YouTube by reconelement[3] on January 22nd,\
  \ 2007. As of March 2014, the video has gained over 10.2 million views. [This video\
  \ has been removed] Spread On June 29, 2007, YouTuber Starr Hoffman[4] uploaded\
  \ a video featuring a man dressed as a jedi chasing a man holding an ice cream machine\
  \ while yelling \"You were the frozen one.\" On December 8th, 2007, Frasier Online[5]\
  \ fan forum user Texaveryfan wrote a short piece of fan fiction which featured Frasier\
  \ turning to the \"dark side of pretension.\" His friend shouts at him, \"You were\
  \ the Chosen One! It was said that you would destroy the higher classes, not join\
  \ them!\" On February 13th, 2011, a Facebook Page[7] for \"You Were the Chosen One\"\
  \ was created. The image macro first appeared on Tumblr on December 16th, 2011,\
  \ when Tumblr user wefuckingkepttrack[6] posted it as a way to express his disappointment\
  \ in President Obama. The image macro quickly became popular on Tumblr with over\
  \ 13 posts tagged #youwerethechosen one in 2012, including those-who-matter-dont-mind's[8]\
  \ post on Twilight, shylockbones's[9] post on soccer, and unheardastronaut's[11]\
  \ post on The Big Bang Theory. The quote's page on Meme Generator [3] has over 3,500\
  \ entries as of March 2014. Notable Examples Search Interest External References\
  \ [1] IMDB \u2013 Star Wars Episode III: Revenge Of The Sith [2] Meme Generator\
  \ \u2013 You Were The Chosen One\u201D Puts A Character In Yellowface [3] YouTube\
  \ \u2013 reconelement [4] YouTube \u2013 Starr Hoffman [5] Frasier Online \u2013\
  \ Frasier Winslow Crane Case File [6] Tumblr \u2013 wefuckingkepttrack (page deleted)\
  \ [7] Facebook \u2013 you were the chosen one [8] Facebook \u2013 those-who-matter-dont-mind\
  \ [9] Tumblr \u2013 shylockbones (page deleted) [10] Tumblr \u2013 #youwerethechosenone\
  \ [11] Tumblr \u2013 unheardastronaut Related Entries 7 total Hello There I Have\
  \ The High Ground Well, Of Course I Know Him. He's Me. [Visible Confusion] Impossible.\
  \ Perhaps the Archives Are Incomplete. Another Happy Landing Always on the Move\
  \ Recent Videos There are no videos currently available. + Add a Video Recent Images\
  \ 105 total You Were The Chosen One! Uploaded by Reddit Moments You Were The Chosen\
  \ One! Uploaded by Reddit Moments You Were The Chosen One! Uploaded by Matt You\
  \ Were The Chosen One! Uploaded by Jazz Wizard You Were The Chosen One! Uploaded\
  \ by Reddit Moments You Were The Chosen One! Uploaded by Mike You Were The Chosen\
  \ One! Uploaded by MidnaGamer You Were The Chosen One! Uploaded by Unraveler You\
  \ Were The Chosen One! Uploaded by The Triggermiser You Were The Chosen One! Uploaded\
  \ by Cold Hard Crash You Were The Chosen One! Uploaded by GameAndWatcher You Were\
  \ The Chosen One! Uploaded by Nobody115 + Add an Image View All Images Sign up for\
  \ our Newsletter Top Comments Delete Sensitive Sir Soundwave Moderator Mar 31, 2014\
  \ at 04:44PM EDT +47 Reply Delete Sensitive Outta here Mar 31, 2014 at 04:17PM EDT\
  \ YOU WERE THE CHOSEN ONE! YOU WERE SUPPOSED TO +1 CONFIRM, NOT +1 DEADPOOL! +31\
  \ Reply + Add a Comment Comments (34) Display Comments Add a Comment Top Entries\
  \ This Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare\
  \ CEO Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (8) Kung Fu\
  \ Cthulhu Researcher & Treasurer & Elocutionist & Media Bus Boy Slutty Sam Karma\
  \ Philanthropist Molly Horan Tumblr Historian VanManner Sr. Entry Moderator The\
  \ Cute Master :3 Sr. Entry Moderator Matt Secretary of Memes Y F Digital Archaeologist\
  \ & Treasurer & Media Maid ohmyjosh Digital Archaeologist & Cataloger \u25BC + Request\
  \ Editorship View All Editors Today's Top Image Galleries Assassination of UnitedHealthcare\
  \ CEO Squirrel Girl (Doreen Green) Team Fortress 2 The Amazing Digital Circus About\
  \ Our Story Site Rules Policies and Guidelines Credits Contact Meme DB Memes Episodes\
  \ News Staff Contact Extras! Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/you-were-the-chosen-one
template_id: chosen
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
