name: You Were the Chosen One!
source: http://knowyourmeme.com/memes/you-were-the-chosen-one
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- you were the chosen one!
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About “You were the chosen one!” is a quote from the 2005 science
  fiction film Star Wars: Episode III – Revenge of the Sith that is used to express
  disappointment in someone or something that was once previously seen as promising.
  On the web, the quote is often referenced in the form of an image macro based on
  a still shot of Obi-Wan Kenobi from the corresponding scene in the film. Origin
  In Star Wars Episode III: Revenge Of The Sith (2005), Jedi Master Obi-Wan Kenobi
  (Ewan McGregor) is tasked with defeating his former apprentice Anakin Skywalker
  (Hayden Christensen), who has led a genocide against the Jedi in spite of the fact
  he was suppose to be the one to bring an end to the Sith. When Obi-Wan defeats Anakin,
  he cries out: "You were the chosen one! It was said that you would destroy the Sith,
  not join them. You were to bring balance to the Force, not leave it in darkness!"[1]
  The scene was first uploaded to YouTube by reconelement[3] on January 22nd, 2007.
  As of March 2014, the video has gained over 10.2 million views. [This video has
  been removed] Spread On June 29, 2007, YouTuber Starr Hoffman[4] uploaded a video
  featuring a man dressed as a jedi chasing a man holding an ice cream machine while
  yelling "You were the frozen one." On December 8th, 2007, Frasier Online[5] fan
  forum user Texaveryfan wrote a short piece of fan fiction which featured Frasier
  turning to the "dark side of pretension." His friend shouts at him, "You were the
  Chosen One! It was said that you would destroy the higher classes, not join them!"
  On February 13th, 2011, a Facebook Page[7] for "You Were the Chosen One" was created.
  The image macro first appeared on Tumblr on December 16th, 2011, when Tumblr user
  wefuckingkepttrack[6] posted it as a way to express his disappointment in President
  Obama. The image macro quickly became popular on Tumblr with over 13 posts tagged
  #youwerethechosen one in 2012, including those-who-matter-dont-mind''s[8] post on
  Twilight, shylockbones''s[9] post on soccer, and unheardastronaut''s[11] post on
  The Big Bang Theory. The quote''s page on Meme Generator [3] has over 3,500 entries
  as of March 2014. Notable Examples Search Interest External References [1] IMDB
  – Star Wars Episode III: Revenge Of The Sith [2] Meme Generator – You Were The Chosen
  One” Puts A Character In Yellowface [3] YouTube – reconelement [4] YouTube – Starr
  Hoffman [5] Frasier Online – Frasier Winslow Crane Case File [6] Tumblr – wefuckingkepttrack
  (page deleted) [7] Facebook – you were the chosen one [8] Facebook – those-who-matter-dont-mind
  [9] Tumblr – shylockbones (page deleted) [10] Tumblr – #youwerethechosenone [11]
  Tumblr – unheardastronaut'
aside_content: MemeStatusConfirmedYear2007OriginYouTubeTagsstar wars,dark side,anakin
  skywalker,obi wan kenobi,you were the chosen one,disappointment,movie quote,reconelement,wefuckingkepttrack,texaveryfan,starr
  hoffmanAdditional ReferencesMeme Generator
added_at: '2014-03-31T14:51:04-04:00'
