example:
- ''
- do it live!
keywords:
- null
name: Do It Live!
overlay:
- angle: 0.0
  center_x: 0.5
  center_y: 0.5
  scale: 0.25
scraped_content: "Bill O'Reilly Rant | Know Your Meme Hauu! You must login or signup\
  \ first! Already a memeber? Login Now! Don't have an account? Sign up Now! Meme\
  \ Encyclopedia All Cultures Events People Sites Subcultures Videos Submit \u2192\
  \ Images Trending Most Commented Most Favorited High Score Low Score Most Viewed\
  \ All Templates Upload an Image Articles News Explainers Collections Interviews\
  \ Meme Insider Magazine More Discord Newsletter Episodes Forums Meme Store Login\
  \ Abstract user icon Memes Categories Trending News Images Trending Images Videos\
  \ Trending Videos Editorials Meme Insider Magazine Newsletter Policies and Guidelines\
  \ Meme Store Old site Login Know Your Meme is the property of Literally Media \xA9\
  2024 Literally Media. All Rights Reserved. This image Of Woman Confidently Strolling\
  \ Through A Glass Panel Has Been A Redraw Format Since 2021 Three Years Ago, This\
  \ Boar's Head 'Exploded' Onto The Meme Scene Remember Il Vaticano? The Anarchy Chess\
  \ Memes Turns Two Years Old Today Phrase 'The Fridge Protects The Snacks' A Growing\
  \ Favorite Among Pickup Artist Influencers Jamie G, The Bosh British Charva, Has\
  \ Taken Over TikTok With His Signature 'Oh Cherie Amour' Sound Also Trending: Honey\
  \ Extension Influencer Scam Renegade Raider Copypasta Assassination of UnitedHealthcare\
  \ CEO Bill O'Reilly Rant Added 15 years ago / Updated 8 days ago Confirmed 336,993\
  \ Part of a series on Bill O'Reilly. [View Related Entries] View All 21 Images Navigation\
  \ About \u2022 Origin \u2022 Spread \u2022 Various Examples \u2022 Search Interest\
  \ \u2022 External References \u2022 Recent Images \u2022 Recent Videos About Bill\
  \ O'Reilly Rant refers to a viral video featuring television host Bill O'Reilly\
  \ yelling and cursing at his coworkers during a taping of the show Inside Edition.\
  \ Origin On May 12th, 2008, YouTuber OffbeatEarth posted a video to YouTube titled\
  \ \"Bill O'Reilly Flips Out,\" featuring leaked footage of O'Reilly yelling profanities\
  \ at his co-workers while experiencing technical difficulties with his teleprompter.\
  \ While the original video was removed, YouTuber CrownVictoriaCop reuploaded it\
  \ the following day, gathering more than 2.6 million views and 3,400 comments over\
  \ the next nine years (shown below). \"We'll do it live!\" Fuck it! Do it live!\
  \ I'll write it and we'll do it live!\" Spread On April 13th, 2009, YouTuber saintnickXIII\
  \ uploaded a remix of the video dubbed with audio from the \"Stop Calling Me a Homo\"\
  \ video (shown below). Within eight years, the video received upwards of 779,000\
  \ views and 970 comments. On May 24th, 2011, Stephen Colbert parodied the rant in\
  \ an episode of the Colbert Report (shown below, left). On June 20th, 2012, YouTuber\
  \ Sully Omar uploaded a dubstep remix of the video, garnering more than 299,000\
  \ views and 460 comments within five years (shown below, right). On April 7th, 2015,\
  \ YouTuber Tobii UK uploaded a Family Guy parody of the video, which received upwards\
  \ of 1.15 million views and 360 comments over the next three years (shown below).\
  \ Various Examples YTMND Pages Bill O'Reilly is asked read to Brallie A Typical\
  \ Day At Fox News What Does O'Reilly's Mouth Do? Bill O'Reilly's afraid of Keith\
  \ Olbermann O REILLY? Geraldo vs. Oreilly Lawrence O'Donnell's Rant On September\
  \ 20th, 2017, Mediaite posted leaked outtakes of MSNBC host Lawrence O'Donnell cursing\
  \ at coworkers for eight minutes during a recording of his show conducted on August\
  \ 29th the previous month. That evening, the RealStoryNews YouTube channel reuploaded\
  \ the footage (shown below). [This video has been removed] Search Interest According\
  \ to Google insights, the video shot up to viral status in early 2008: External\
  \ References [1] Internet Archive \u2013 Bill O'Reilly Flips Out [2] Mediaite \u2013\
  \ Watch MSNBCs Lawrence O\u2019Donnells Unhinged Outtakes freakout outtake celebrity\
  \ rant raging viral video remix newscast bill o'reilley tv fox news Share Pin Related\
  \ Entries 1 total Bill O'Reilly You Can't Expla... Recent Images 21 total View All\
  \ Images Recent Videos 7 total View All Videos Sign up for our Newsletter Load 37\
  \ Comments Comments 37 total 29 Bill O'Reilly Rant 336,993 7 21 37 Part of a series\
  \ on Bill O'Reilly. [View Related Entries] Updated Dec 15, 2024 at 06:24PM EST by\
  \ LiterallyAustin. Added Aug 29, 2009 at 09:25PM EDT by Greg McCoral. Like us on\
  \ Facebook! Like 1.8M Share Save Tweet PROTIP: Press 'i' to view the image gallery,\
  \ 'v' to view the video gallery, or 'r' to view a random entry. Meme Status Confirmed\
  \ Year 2008 Origin YouTube Tags freakout, outtake, celebrity, rant, raging, viral\
  \ video, remix, newscast, bill o'reilley, tv, fox news Additional References Wikipedia\
  \ About Bill O'Reilly Rant refers to a viral video featuring television host Bill\
  \ O'Reilly yelling and cursing at his coworkers during a taping of the show Inside\
  \ Edition. Origin On May 12th, 2008, YouTuber OffbeatEarth posted a video to YouTube\
  \ titled \"Bill O'Reilly Flips Out,\" featuring leaked footage of O'Reilly yelling\
  \ profanities at his co-workers while experiencing technical difficulties with his\
  \ teleprompter. While the original video was removed, YouTuber CrownVictoriaCop\
  \ reuploaded it the following day, gathering more than 2.6 million views and 3,400\
  \ comments over the next nine years (shown below). \"We'll do it live!\" Fuck it!\
  \ Do it live! I'll write it and we'll do it live!\" Spread On April 13th, 2009,\
  \ YouTuber saintnickXIII uploaded a remix of the video dubbed with audio from the\
  \ \"Stop Calling Me a Homo\" video (shown below). Within eight years, the video\
  \ received upwards of 779,000 views and 970 comments. On May 24th, 2011, Stephen\
  \ Colbert parodied the rant in an episode of the Colbert Report (shown below, left).\
  \ On June 20th, 2012, YouTuber Sully Omar uploaded a dubstep remix of the video,\
  \ garnering more than 299,000 views and 460 comments within five years (shown below,\
  \ right). On April 7th, 2015, YouTuber Tobii UK uploaded a Family Guy parody of\
  \ the video, which received upwards of 1.15 million views and 360 comments over\
  \ the next three years (shown below). Various Examples YTMND Pages Bill O'Reilly\
  \ is asked read to Brallie A Typical Day At Fox News What Does O'Reilly's Mouth\
  \ Do? Bill O'Reilly's afraid of Keith Olbermann O REILLY? Geraldo vs. Oreilly Lawrence\
  \ O'Donnell's Rant On September 20th, 2017, Mediaite posted leaked outtakes of MSNBC\
  \ host Lawrence O'Donnell cursing at coworkers for eight minutes during a recording\
  \ of his show conducted on August 29th the previous month. That evening, the RealStoryNews\
  \ YouTube channel reuploaded the footage (shown below). [This video has been removed]\
  \ Search Interest According to Google insights, the video shot up to viral status\
  \ in early 2008: External References [1] Internet Archive \u2013 Bill O'Reilly Flips\
  \ Out [2] Mediaite \u2013 Watch MSNBCs Lawrence O\u2019Donnells Unhinged Outtakes\
  \ Related Entries 1 total Bill O'Reilly You Can't Explain That Recent Videos 7 total\
  \ Inside MSNBC's Lawrence O'Don... Bill O'Reilly Rant Uploaded by Don Bill O\u2019\
  Reilly and Lawrence O\u2019... Bill O'Reilly Rant Uploaded by Hootanic Bill Is Doing\
  \ an Anger Bill O'Reilly Rant Uploaded by Adam Stop Calling Bill O Reilly A ...\
  \ Bill O'Reilly Rant Uploaded by Ari Spool fuckin thing sucks Bill O'Reilly Rant\
  \ Uploaded by James Ventertainment - Bill O'Reilly Bill O'Reilly Rant Uploaded by\
  \ Overdream + Add a Video Recent Images 21 total Bill O'Reilly Rant Uploaded by\
  \ Nukem4D Bill O'Reilly Rant Uploaded by SonofX51 Bill O'Reilly Rant Uploaded by\
  \ Vlad Bill O'Reilly Rant Uploaded by boxxyismymom Bill O'Reilly Rant Uploaded by\
  \ topple Bill O'Reilly Rant Uploaded by Caozao Bill O'Reilly Rant Uploaded by SnatchPlay\
  \ Bill O'Reilly Rant Uploaded by Katie C. Bill O'Reilly Rant Uploaded by Katie C.\
  \ Bill O'Reilly Rant Uploaded by Katie C. Bill O'Reilly Rant Uploaded by Katie C.\
  \ Bill O'Reilly Rant Uploaded by Katie C. + Add an Image View All Images Sign up\
  \ for our Newsletter Top Comment Delete Sensitive oudaveguy98 Sep 21, 2017 at 07:56PM\
  \ EDT Gotta love it when the default personalities of these elitist shills gets\
  \ exposed. O'Donnell beats O'Reilly on this one for sustained tantrum duration and\
  \ in the f-bomb count; plus his staff looks like they are working for Kim Jong Un\
  \ and fear for their lives. I'm guessing this wasn't a one off rant for this prima\
  \ donna propagandist. What's your definition of a toxic work environment? +6 Reply\
  \ + Add a Comment Comments (37) Display Comments Add a Comment Top Entries This\
  \ Month Meme Saika Kawakita Smile GIF Event Assassination of UnitedHealthcare CEO\
  \ Person Luigi Mangione UHC CEO Shooter Subculture The Ki Sisters Culture Pornography\
  \ Site Whisper View More Suggest a Change Edit History Entry Editors (13) Greg McCoral\
  \ Deactivated redspear75 Deactivated Brad Digital Archaeologist & Treasurer & Pundit\
  \ & Gallery Housekeeper Jamie Dubs Scientist Emeritus AJ Mazur Digital Archaeologist\
  \ Don Administrator & Meme Daddy amanda b. Meme Librarian Ari Spool The Mayor Adam\
  \ Know Your Meme Universal Champion Jill Database Moderator & Karma Philanthropist\
  \ & Meme Taxonomist & Fleet Admiral & Amish James Nic Cage Fan andcallmeshirley\
  \ Digital Archaeologist & Treasurer & Collection Butler Kevinvq2 Sr. Researcher\
  \ & Scrapbooker & Media Chauffeur \u25BC + Request Editorship View All Editors Today's\
  \ Top Image Galleries Assassination of UnitedHealthcare CEO Squirrel Girl (Doreen\
  \ Green) Team Fortress 2 The Amazing Digital Circus About Our Story Site Rules Policies\
  \ and Guidelines Credits Contact Meme DB Memes Episodes News Staff Contact Extras!\
  \ Style Guide RSS Feeds"
source: http://knowyourmeme.com/memes/bill-oreilly-rant
template_id: live
text:
- align: center
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
- align: center
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  color: white
  font: thick
  scale_x: 1.0
  scale_y: 0.2
  start: 0.0
  stop: 1.0
  style: upper
text_zones: 2
