name: Do It Live!
source: http://knowyourmeme.com/memes/bill-oreilly-rant
keywords:
- null
text:
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.0
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
- style: upper
  color: white
  font: thick
  anchor_x: 0.0
  anchor_y: 0.8
  angle: 0.0
  scale_x: 1.0
  scale_y: 0.2
  align: center
  start: 0.0
  stop: 1.0
example:
- ''
- do it live!
overlay:
- center_x: 0.5
  center_y: 0.5
  angle: 0.0
  scale: 0.25
scraped_content: 'About Bill O''Reilly Rant refers to a viral video featuring television
  host Bill O''Reilly yelling and cursing at his coworkers during a taping of the
  show Inside Edition. Origin On May 12th, 2008, YouTuber OffbeatEarth posted a video
  to YouTube titled "Bill O''Reilly Flips Out," featuring leaked footage of O''Reilly
  yelling profanities at his co-workers while experiencing technical difficulties
  with his teleprompter. While the original video was removed, YouTuber CrownVictoriaCop
  reuploaded it the following day, gathering more than 2.6 million views and 3,400
  comments over the next nine years (shown below). "We''ll do it live!" Fuck it! Do
  it live! I''ll write it and we''ll do it live!" Spread On April 13th, 2009, YouTuber
  saintnickXIII uploaded a remix of the video dubbed with audio from the "Stop Calling
  Me a Homo" video (shown below). Within eight years, the video received upwards of
  779,000 views and 970 comments. On May 24th, 2011, Stephen Colbert parodied the
  rant in an episode of the Colbert Report (shown below, left). On June 20th, 2012,
  YouTuber Sully Omar uploaded a dubstep remix of the video, garnering more than 299,000
  views and 460 comments within five years (shown below, right). On April 7th, 2015,
  YouTuber Tobii UK uploaded a Family Guy parody of the video, which received upwards
  of 1.15 million views and 360 comments over the next three years (shown below).
  Various Examples YTMND Pages Bill O''Reilly is asked read to Brallie A Typical Day
  At Fox News What Does O''Reilly''s Mouth Do? Bill O''Reilly''s afraid of Keith Olbermann
  O REILLY? Geraldo vs. Oreilly Lawrence O''Donnell''s Rant On September 20th, 2017,
  Mediaite posted leaked outtakes of MSNBC host Lawrence O''Donnell cursing at coworkers
  for eight minutes during a recording of his show conducted on August 29th the previous
  month. That evening, the RealStoryNews YouTube channel reuploaded the footage (shown
  below). [This video has been removed] Search Interest According to Google insights,
  the video shot up to viral status in early 2008: External References [1] Internet
  Archive – Bill O''Reilly Flips Out [2] Mediaite – Watch MSNBCs Lawrence O’Donnells
  Unhinged Outtakes'
aside_content: MemeStatusConfirmedYear2008OriginYouTubeTagsfreakout,outtake,celebrity,rant,raging,viral
  video,remix,newscast,bill o'reilley,tv,fox newsAdditional ReferencesWikipedia
added_at: '2009-08-29T21:25:41-04:00'
